# The 🤗 datasets library
## [Introduction](https://huggingface.co/course/chapter5/1?fw=pt)

In [Chapter 3](https://huggingface.co/course/chapter3) you got your first taste of the 🤗 Datasets library and saw that there were three main steps when it came to fine-tuning a model:
- Load a dataset from the Hugging Face Hub.
- Preprocess the data with `Dataset.map()`.
- Load and compute metrics.

But this is just scratching the surface of what 🤗 Datasets can do! In this chapter, we will take a deep dive into the library. Along the way, we'll find answers to the following questions:
- What do you do when your dataset is not on the Hub?
- How can you slice and dice a dataset? (And what if you *really* need to use Pandas?)
- What do you do when your dataset is huge and will melt your laptop's RAM?
- What the heck are "memory mapping" and Apache Arrow?
- How can you create your own dataset and push it to the Hub?

The techniques you learn here will prepare you for the advanced tokenization and fine-tuning tasks in [Chapter 6](https://huggingface.co/course/chapter6) and [Chapter 7](https://huggingface.co/course/chapter7) — so grab a coffee and let's get started!

## [What if my dataset isn't on the Hub?](https://huggingface.co/course/chapter5/2?fw=pt)

You know how to use the Hugging Face Hub to download datasets, but you'll often find yourself working with data that is stored either on your laptop or on a remote server. In this section we'll show you how 🤗 Datasets can be used to load datasets that aren't available on the Hugging Face Hub.

In [1]:
from IPython.display import HTML
HTML('<iframe width="640" height="360" src="https://www.youtube.com/embed/HyQgpJTkRdE" allowfullscreen></iframe>')

/home/matthias/Desktop/MachineLearning/Huggingface-course/env/lib/python3.12/site-packages/IPython/core/display.py:475: UserWarning: Consider using IPython.display.IFrame instead
  warnings.warn("Consider using IPython.display.IFrame instead")

### Working with local and remote datasets
🤗 Datasets provides loading scripts to handle the loading of local and remote datasets. It supports several common data formats, such as:

| Data format | Loading script | Example
| :---- | :------- | :---- |
| CSV & TSV | `csv` | `load_dataset("csv", data_files="my_file.csv")` |
| Text files | `text` | `load_dataset("text", data_files="my_file.txt")` |
| JSON & JSON Lines | `json` | `load_dataset("json", data_files="my_file.jsonl")` |
| Pickled DataFrames | `pandas` | `load_dataset("pandas", data_files="my_dataframe.pkl")` |

As shown in the table, for each data format we just need to specify the type of loading script in the `load_dataset()` function, along with a `data_files` argument that specifies the path to one or more files. Let's start by loading a dataset from local files; later we'll see how to do the same with remote files.

### Loading a local dataset

For this example we'll use the [SQuAD-it](https://github.com/crux82/squad-it/) dataset, which is a large-scale dataset for question answering in Italian.

The training and test splits are hosted on GitHub, so we can download them with a simple `wget` command:

In [2]:
# the following commands to download the data files and move them to the "data" folder need to run only once
#!wget "https://github.com/crux82/squad-it/raw/master/SQuAD_it-train.json.gz"
#!wget "https://github.com/crux82/squad-it/raw/master/SQuAD_it-test.json.gz"
#!mv "SQuAD_it-train.json.gz" "sections/section_5/data"
#!mv "SQuAD_it-test.json.gz" "sections/section_5/data"

This will download two compressed files called *SQuAD_it-train.json.gz* and *SQuAD_it-test.json.gz*, which we can decompress with the Linux `gzip` command:

In [3]:
# the following command needs to run only once
#!gzip -dkv sections/section_5/data/SQuAD_it-*.json.gz

We can see that the compressed files have been replaced with *SQuAD_it-train.json* and *SQuAD_it-test.json*, and that the data is stored in the JSON format.
> <font color="darkgreen">✎ If you're wondering why there's a `!` character in the above shell commands, that's because we're running them within a Jupyter notebook. Simply remove the prefix if you want to download and unzip the dataset within a terminal.</font>

To load a JSON file with the `load_dataset()` function, we just need to know if we're dealing with ordinary JSON (similar to a nested dictionary) or JSON Lines (line-separated JSON). Like many question answering datasets, SQuAD-it uses the nested format, with all the text stored in a `data` field. This means we can load the dataset by specifying the `field` argument as follows:

In [4]:
from datasets import load_dataset
squad_it_dataset = load_dataset("json", data_files="sections/section_5/data/SQuAD_it-train.json", field="data")

By default, loading local files creates a `DatasetDict` object with a `train` split. We can see this by inspecting the `squad_it_dataset` object:

In [5]:
squad_it_dataset

DatasetDict({
    train: Dataset({
        features: ['title', 'paragraphs'],
        num_rows: 442
    })
})

This shows us the number of rows and the column names associated with the training set. We can view one of the examples by indexing into the `train` split as follows:

In [6]:
print(squad_it_dataset["train"][0]["title"])
for paragraph in squad_it_dataset["train"][0]["paragraphs"][:2]:
    print(f"\n{paragraph}")

Terremoto del Sichuan del 2008

{'context': "Il terremoto del Sichuan del 2008 o il terremoto del Gran Sichuan, misurato a 8.0 Ms e 7.9 Mw, e si è verificato alle 02:28:01 PM China Standard Time all' epicentro (06:28:01 UTC) il 12 maggio nella provincia del Sichuan, ha ucciso 69.197 persone e lasciato 18.222 dispersi.", 'qas': [{'answers': [{'answer_start': 29, 'text': '2008'}], 'id': '56cdca7862d2951400fa6826', 'question': 'In quale anno si è verificato il terremoto nel Sichuan?'}, {'answers': [{'answer_start': 232, 'text': '69.197'}], 'id': '56cdca7862d2951400fa6828', 'question': 'Quante persone sono state uccise come risultato?'}, {'answers': [{'answer_start': 29, 'text': '2008'}], 'id': '56d4f9902ccc5a1400d833c0', 'question': 'Quale anno ha avuto luogo il terremoto del Sichuan?'}, {'answers': [{'answer_start': 78, 'text': '8.0 Ms e 7.9 Mw'}], 'id': '56d4f9902ccc5a1400d833c1', 'question': 'Che cosa ha fatto la misura di sisma?'}, {'answers': [{'answer_start': 183, 'text': '12 maggio'}], 'id': '56d4f9902ccc5a1400d833c2', 'question': 'Che giorno si è verificato il terremoto?'}, {'answers': [{'answer_start': 118, 'text': '02:28:01 PM China Standard Time'}], 'id': '56d4f9902ccc5a1400d833c3', 'question': 'Che ora del giorno è accaduto il terremoto?'}, {'answers': [{'answer_start': 232, 'text': '69.197'}], 'id': '56d4f9902ccc5a1400d833c4', 'question': 'Quante persone sono morte?'}]}

{'context': 'E\' noto anche come terremoto di Wenchuan (Cinese:????; pinyin: Wènchu? n dà dìzhèn; letteralmente:"Grande terremoto di Wenchuan"), dopo l\' ubicazione dell\' epicentro del terremoto, Wenchuan County, Sichuan. L\' epicentro era di 80 chilometri (50 miglia) ad ovest nord-ovest di Chengdu, capoluogo di provincia, con una profondità focale di 19 km (12 miglia). Il terremoto ha colpito anche i paesi vicini e lontani da Pechino e Shanghai-1.500 km (930 mi) e 1.700 km (1.060 mi) di distanza, dove gli edifici adibiti a uffici hanno oscillato con il tremore. Forti scosse di assestamento, un po\' superiori alla magnitudo 6, hanno continuato a colpire l\' area anche mesi dopo il sisma principale, causando nuove vittime e danni.', 'qas': [{'answers': [{'answer_start': 415, 'text': 'Pechino e Shanghai'}], 'id': '56cdcb2c62d2951400fa6830', 'question': 'Quali città lontane in altri paesi potrebbero sentire il terremoto?'}, {'answers': [{'answer_start': 338, 'text': '19 km'}], 'id': '56cdcb2c62d2951400fa6833', 'question': 'Qual è stata la profondità focale del terremoto?'}, {'answers': [{'answer_start': 659, 'text': 'mesi dopo'}], 'id': '56cdcb2c62d2951400fa6834', 'question': 'Quanto tempo dopo il terremoto si sono sentite le scosse di assestamento?'}, {'answers': [{'answer_start': 181, 'text': 'Wenchuan County, Sichuan'}], 'id': '56d4fb6f2ccc5a1400d833d5', 'question': "Dov' era l' epicentro del terremoto?"}, {'answers': [{'answer_start': 227, 'text': '80 chilometri'}], 'id': '56d4fb6f2ccc5a1400d833d6', 'question': 'Quanto lontano era da Chengdu?'}, {'answers': [{'answer_start': 338, 'text': '19 km'}], 'id': '56d4fb6f2ccc5a1400d833d7', 'question': 'Qual era la profondità focale del sisma?'}]}

Great, we've loaded our first local dataset! But while this worked for the training set, what we really want is to include both the `train` and `test` splits in a single `DatasetDict` object so we can apply `Dataset.map()` functions across both splits at once. To do this, we can provide a dictionary to the `data_files` argument that maps each split name to a file associated with that split:

In [7]:
data_files = {"train": "sections/section_5/data/SQuAD_it-train.json", "test": "sections/section_5/data/SQuAD_it-test.json"}
squad_it_dataset = load_dataset("json", data_files=data_files, field="data")
squad_it_dataset

DatasetDict({
    train: Dataset({
        features: ['title', 'paragraphs'],
        num_rows: 442
    })
    test: Dataset({
        features: ['title', 'paragraphs'],
        num_rows: 48
    })
})

This is exactly what we wanted. Now, we can apply various preprocessing techniques to clean up the data, tokenize the reviews, and so on.

> The `data_files` argument of the `load_dataset()` function is quite flexible and can be either a single file path, a list of file paths, or a dictionary that maps split names to file paths. You can also glob files that match a specified pattern according to the rules used by the Unix shell (e.g., you can glob all the JSON files in a directory as a single split by setting `data_files="*.json"`). See the 🤗 Datasets [documentation](https://huggingface.co/docs/datasets/loading.html#local-and-remote-files) for more details.

The loading scripts in 🤗 Datasets actually support automatic decompression of the input files, so we could have skipped the use of `gzip` by pointing the `data_files` argument directly to the compressed files:

In [8]:
data_files = {"train": "sections/section_5/data/SQuAD_it-train.json.gz", "test": "sections/section_5/data/SQuAD_it-test.json.gz"}
squad_it_dataset = load_dataset("json", data_files=data_files, field="data")
squad_it_dataset

DatasetDict({
    train: Dataset({
        features: ['title', 'paragraphs'],
        num_rows: 442
    })
    test: Dataset({
        features: ['title', 'paragraphs'],
        num_rows: 48
    })
})

This can be useful if you don't want to manually decompress many GZIP files. The automatic decompression also applies to other common formats like ZIP and TAR, so you just need to point `data_files` to the compressed files and you're good to go!

Now that you know how to load local files on your laptop or desktop, let's take a look at loading remote files.
### Loading a remote dataset

If you're working as a data scientist or coder in a company, there's a good chance the datasets you want to analyze are stored on some remote server. Fortunately, loading remote files is just as simple as loading local ones! Instead of providing a path to local files, we point the `data_files` argument of `load_dataset()` to one or more URLs where the remote files are stored. For example, for the SQuAD-it dataset hosted on GitHub, we can just point `data_files` to the <i>SQuAD_it-\*.json.gz</i> URLs as follows:

In [9]:
url = "https://github.com/crux82/squad-it/raw/master/"
data_files = {
    "train": url + "SQuAD_it-train.json.gz",
    "test": url + "SQuAD_it-test.json.gz",
}
squad_it_dataset = load_dataset("json", data_files=data_files, field="data")
squad_it_dataset

DatasetDict({
    train: Dataset({
        features: ['title', 'paragraphs'],
        num_rows: 442
    })
    test: Dataset({
        features: ['title', 'paragraphs'],
        num_rows: 48
    })
})

This returns the same `DatasetDict` object obtained above, but saves us the step of manually downloading and decompressing the <i>SQuAD_it-\*.json.gz</i> files. This wraps up our foray into the various ways to load datasets that aren't hosted on the Hugging Face Hub. Now that we've got a dataset to play with, let's get our hands dirty with various data-wrangling techniques!

> ✏️ Try it out! <font color="darkgreen">Pick another dataset hosted on GitHub or the [UCI Machine Learning Repository](https://archive.ics.uci.edu/ml/index.php) and try loading it both locally and remotely using the techniques introduced above. For bonus points, try loading a dataset that's stored in a CSV or text format (see the [documentation](https://huggingface.co/docs/datasets/loading.html#local-and-remote-files) for more information on these formats).</font>

In [10]:
# Trying it out
## load dataset locally, from csv
!wget "https://archive.ics.uci.edu/ml/machine-learning-databases/00611/accelerometer.csv"
!mv "accelerometer.csv" "sections/section_5/data"
accelerometer_dataset = load_dataset("csv", data_files="sections/section_5/data/accelerometer.csv")
print(f"Accelerometer dataset:\n{accelerometer_dataset}")
## load dataset remotely
data_files = {"train": "https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"}
iris_dataset = load_dataset("csv", data_files=data_files)
text = "Add some preprocessing to correct the `features` and to add the first instance (=current `features`)!"
print(f"Iris dataset:\n{iris_dataset}\n{text}")

--2025-03-24 15:01:30--  https://archive.ics.uci.edu/ml/machine-learning-databases/00611/accelerometer.csv
Resolving archive.ics.uci.edu (archive.ics.uci.edu)... 128.195.10.252
connected. to archive.ics.uci.edu (archive.ics.uci.edu)|128.195.10.252|:443...
HTTP request sent, awaiting response... 200 OK
Length: unspecified
Saving to: ‘accelerometer.csv’

accelerometer.csv       [      <=>           ]   3.56M  2.54MB/s    in 1.4s

2025-03-24 15:01:32 (2.54 MB/s) - ‘accelerometer.csv’ saved [3731094]

Generating train split: 0 examples [00:00, ? examples/s]

Accelerometer dataset:
DatasetDict({
    train: Dataset({
        features: ['wconfid', 'pctid', 'x', 'y', 'z'],
        num_rows: 153000
    })
})
Iris dataset:
DatasetDict({
    train: Dataset({
        features: ['5.1', '3.5', '1.4', '0.2', 'Iris-setosa'],
        num_rows: 149
    })
})
Add some preprocessing to correct the `features` and to add the first instance (=current `features`)!

## [Time to slice and dice](https://huggingface.co/course/chapter5/3?fw=pt)

Most of the time, the data you work with won't be perfectly prepared for training models. In this section we'll explore the various features that 🤗 Datasets provides to clean up your datasets.

In [11]:
HTML('<iframe width="640" height="360" src="https://www.youtube.com/embed/tqfSFcPMgOI" allowfullscreen></iframe>')

/home/matthias/Desktop/MachineLearning/Huggingface-course/env/lib/python3.12/site-packages/IPython/core/display.py:475: UserWarning: Consider using IPython.display.IFrame instead
  warnings.warn("Consider using IPython.display.IFrame instead")

### Slicing and dicing our data

Similar to Pandas, 🤗 Datasets provides several functions to manipulate the contents of `Dataset` and `DatasetDict` objects. We already encountered the `Dataset.map()` method in Chapter 3, and in this section we'll explore some of the other functions at our disposal.

For this example we'll use the [Drug Review Dataset](https://archive.ics.uci.edu/ml/datasets/Drug+Review+Dataset+%28Drugs.com%29) that's hosted on the [UC Irvine Machine Learning Repository}(https://archive.ics.uci.edu/ml/index.php), which contains patient reviews on various drugs, along with the condition being treated and a 10-star rating of the patient's satisfaction.

First we need to download and extract the data, which can be done with the `wget` and `unzip` commands:

In [12]:
# the following commands need to run only once
!wget "https://archive.ics.uci.edu/ml/machine-learning-databases/00462/drugsCom_raw.zip"
!mv "drugsCom_raw.zip" "sections/section_5/data"
!unzip -o "sections/section_5/data/drugsCom_raw.zip" -d "sections/section_5/data"

--2025-03-24 15:01:40--  https://archive.ics.uci.edu/ml/machine-learning-databases/00462/drugsCom_raw.zip
Resolving archive.ics.uci.edu (archive.ics.uci.edu)... 128.195.10.252
connected. to archive.ics.uci.edu (archive.ics.uci.edu)|128.195.10.252|:443...
HTTP request sent, awaiting response... 200 OK
Length: unspecified
Saving to: ‘drugsCom_raw.zip’

drugsCom_raw.zip        [             <=>    ]  41.00M  12.0MB/s    in 4.5s

2025-03-24 15:01:45 (9.12 MB/s) - ‘drugsCom_raw.zip’ saved [42989872]

Archive:  sections/section_5/data/drugsCom_raw.zip
  inflating: sections/section_5/data/drugsComTest_raw.tsv
  inflating: sections/section_5/data/drugsComTrain_raw.tsv

Since TSV is just a variant of CSV that uses tabs instead of commas as the separator, we can load these files by using the csv loading script and specifying the `delimiter` argument in the `load_dataset()` function as follows:

In [13]:
data_files = {"train": "sections/section_5/data/drugsComTrain_raw.tsv", "test": "sections/section_5/data/drugsComTest_raw.tsv"}
# \t is the tab character in Python
drug_dataset = load_dataset("csv", data_files=data_files, delimiter="\t")
drug_dataset

DatasetDict({
    train: Dataset({
        features: ['Unnamed: 0', 'drugName', 'condition', 'review', 'rating', 'date', 'usefulCount'],
        num_rows: 161297
    })
    test: Dataset({
        features: ['Unnamed: 0', 'drugName', 'condition', 'review', 'rating', 'date', 'usefulCount'],
        num_rows: 53766
    })
})

A good practice when doing any sort of data analysis is to grab a small random sample to get a quick feel for the type of data you're working with. In 🤗 Datasets, we can create a random sample by chaining the `Dataset.shuffle()` and `Dataset.select()` functions together:

In [14]:
drug_sample = drug_dataset["train"].shuffle(seed=42).select(range(1000))
# Peek at the first few examples
drug_sample[:3]

{'Unnamed: 0': [87571, 178045, 80482],
 'drugName': ['Naproxen', 'Duloxetine', 'Mobic'],
 'condition': ['Gout, Acute', 'ibromyalgia', 'Inflammatory Conditions'],
 'review': ['"like the previous person mention, I&#039;m a strong believer of aleve, it works faster for my gout than the prescription meds I take. No more going to the doctor for refills.....Aleve works!"',
  '"I have taken Cymbalta for about a year and a half for fibromyalgia pain. It is great\r\nas a pain reducer and an anti-depressant, however, the side effects outweighed \r\nany benefit I got from it. I had trouble with restlessness, being tired constantly,\r\ndizziness, dry mouth, numbness and tingling in my feet, and horrible sweating. I am\r\nbeing weaned off of it now. Went from 60 mg to 30mg and now to 15 mg. I will be\r\noff completely in about a week. The fibro pain is coming back, but I would rather deal with it than the side effects."',
  '"I have been taking Mobic for over a year with no side effects other than an elevated blood pressure.  I had severe knee and ankle pain which completely went away after taking Mobic.  I attempted to stop the medication however pain returned after a few days."'],
 'rating': [9.0, 3.0, 10.0],
 'date': ['September 2, 2015', 'November 7, 2011', 'June 5, 2013'],
 'usefulCount': [36, 13, 128]}

Note that we've fixed the seed in `Dataset.shuffle()` for reproducibility purposes. `Dataset.select()` expects an iterable of indices, so we've passed `range(1000)` to grab the first 1,000 examples from the shuffled dataset. From this sample we can already see a few quirks in our dataset:
- The `Unnamed: 0` column looks suspiciously like an anonymized ID for each patient.
- The `condition` column includes a mix of uppercase and lowercase labels.
- The `reviews` are of varying length and contain a mix of Python line separators (`\r\n`) as well as HTML character codes like `&\#039;`.

Let's see how we can use 🤗 Datasets to deal with each of these issues. To test the patient ID hypothesis for the `Unnamed: 0` column, we can use the `Dataset.unique()` function to verify that the number of IDs matches the number of rows in each split:

In [15]:
for split in drug_dataset.keys():
    assert len(drug_dataset[split]) == len(drug_dataset[split].unique("Unnamed: 0"))

This seems to confirm our hypothesis, so let's clean up the dataset a bit by renaming the `Unnamed: 0` column to something a bit more interpretable. We can use the `DatasetDict.rename_column()` function to rename the column across both splits in one go:

In [16]:
drug_dataset = drug_dataset.rename_column(
    original_column_name="Unnamed: 0", new_column_name="patient_id"
)
drug_dataset

DatasetDict({
    train: Dataset({
        features: ['patient_id', 'drugName', 'condition', 'review', 'rating', 'date', 'usefulCount'],
        num_rows: 161297
    })
    test: Dataset({
        features: ['patient_id', 'drugName', 'condition', 'review', 'rating', 'date', 'usefulCount'],
        num_rows: 53766
    })
})

> ✏️ Try it out! <font color="darkgreen">Use the `Dataset.unique()` function to find the number of unique drugs and conditions in the training and test sets.</font>

In [17]:
# Trying it out
print(f'unique drugs in the "train" set:\t{len(drug_dataset["train"].unique("drugName"))}')
print(f'unique drugs in the "test" set: \t{len(drug_dataset["test"].unique("drugName"))}')
print(f'unique conditions in the "train" set:\t{len(drug_dataset["train"].unique("condition"))}')
print(f'unique conditions in the "test" set:\t{len(drug_dataset["test"].unique("condition"))}')

unique drugs in the "train" set:	3436
unique drugs in the "test" set: 	2637
unique conditions in the "train" set:	885
unique conditions in the "test" set:	709

Next, let's normalize all the `condition` labels using `Dataset.map()`. As we did with tokenization in [Chapter 3](https://huggingface.co/course/chapter3), we can define a simple function that can be applied across all the rows of each split in `drug_dataset`:

```python
def lowercase_condition(example):
    return {"condition": example["condition"].lower()}
drug_dataset.map(lowercase_condition)

AttributeError: 'NoneType' object has no attribute 'lower'
```

Oh no, we've run into a problem with our map function! From the error we can infer that some of the entries in the `condition` column are `None`, which cannot be lowercased as they're not strings. Let's drop these rows using `Dataset.filter()`, which works in a similar way to `Dataset.map()` and expects a function that receives a single example of the dataset. Instead of writing an explicit function like:
```python
def filter_nones(x):
    return x["condition"] is not None
```
and then running `drug_dataset.filter(filter_nones)`, we can do this in one line using a *lambda function*. In Python, lambda functions are small functions that you can define without explicitly naming them. They take the general form:
```python
lambda <arguments> : <expression>
```
where `lambda` is one of Python's special [keywords](https://docs.python.org/3/reference/lexical_analysis.html#keywords), `<arguments>` is a list/set of comma-separated values that define the inputs to the function, and `<expression>` represents the operations you wish to execute. For example, we can define a simple lambda function that squares a number as follows:

In [18]:
lambda x : x * x

To apply this function to an input, we need to wrap it and the input in parentheses:

In [19]:
(lambda x: x * x)(3)

9

Similarly, we can define lambda functions with multiple arguments by separating them with commas. For example, we can compute the area of a triangle as follows:

In [20]:
(lambda base, height: 0.5 * base * height)(4, 8)

16.0

Lambda functions are handy when you want to define small, single-use functions (for more information about them, we recommend reading the excellent [Real Python tutorial](https://realpython.com/python-lambda/) by Andre Burgaud). In the 🤗 Datasets context, we can use lambda functions to define simple map and filter operations, so let's use this trick to eliminate the `None` entries in our dataset:

In [21]:
drug_dataset = drug_dataset.filter(lambda x: x["condition"] is not None)

With the `None` entries removed, we can normalize our `condition` column:

In [22]:
def lowercase_condition(example):
    return {"condition": example["condition"].lower()}

drug_dataset = drug_dataset.map(lowercase_condition)
# Check that lowercasing worked
drug_dataset["train"]["condition"][:3]

['left ventricular dysfunction', 'adhd', 'birth control']

It works! Now that we've cleaned up the labels, let's take a look at cleaning up the reviews themselves.

### Creating new columns
Whenever you're dealing with customer reviews, a good practice is to check the number of words in each review. A review might be just a single word like "Great!" or a full-blown essay with thousands of words, and depending on the use case you'll need to handle these extremes differently. To compute the number of words in each review, we'll use a rough heuristic based on splitting each text by whitespace.

Let's define a simple function that counts the number of words in each review:

In [23]:
def compute_review_length(example):
    return {"review_length": len(example["review"].split())}

Unlike our `lowercase_condition()` function, `compute_review_length()` returns a dictionary whose key does not correspond to one of the column names in the dataset. In this case, when `compute_review_length()` is passed to `Dataset.map()`, it will be applied to all the rows in the dataset to create a new `review_length` column:

In [24]:
drug_dataset = drug_dataset.map(compute_review_length)
# Inspect the first training example
drug_dataset["train"][0]

{'patient_id': 206461,
 'drugName': 'Valsartan',
 'condition': 'left ventricular dysfunction',
 'review': '"It has no side effect, I take it in combination of Bystolic 5 Mg and Fish Oil"',
 'rating': 9.0,
 'date': 'May 20, 2012',
 'usefulCount': 27,
 'review_length': 17}

As expected, we can see a `review_length` column has been added to our training set. We can sort this new column with `Dataset.sort()` to see what the extreme values look like:

In [25]:
drug_dataset["train"].sort("review_length")[:3]

{'patient_id': [111469, 13653, 53602],
 'drugName': ['Ledipasvir / sofosbuvir',
  'Amphetamine / dextroamphetamine',
  'Alesse'],
 'condition': ['hepatitis c', 'adhd', 'birth control'],
 'review': ['"Headache"', '"Great"', '"Awesome"'],
 'rating': [10.0, 10.0, 10.0],
 'date': ['February 3, 2015', 'October 20, 2009', 'November 23, 2015'],
 'usefulCount': [41, 3, 0],
 'review_length': [1, 1, 1]}

As we suspected, some reviews contain just a single word, which, although it may be okay for sentiment analysis, would not be informative if we want to predict the condition.

> <font color="darkgreen">🙋 An alternative way to add new columns to a dataset is with the `Dataset.add_column()` function. This allows you to provide the column as a Python list or NumPy array and can be handy in situations where `Dataset.map()` is not well suited for your analysis.</font>

Let's use the `Dataset.filter()` function to remove reviews that contain fewer than 30 words. Similarly to what we did with the condition column, we can filter out the very short reviews by requiring that the reviews have a length above this threshold:

In [26]:
drug_dataset = drug_dataset.filter(lambda x: x["review_length"] > 30)
print(drug_dataset.num_rows)

{'train': 138514, 'test': 46108}

As you can see, this has removed around 15% of the reviews from our original training and test sets.

> ✏️ Try it out! <font color="darkgreen">Use the `Dataset.sort()` function to inspect the reviews with the largest numbers of words. See the documentation to see which argument you need to use to sort the reviews by length in descending order.</font>

In [27]:
# Trying it out
drug_dataset_sorted_by_review_length = drug_dataset["train"].sort("review_length", reverse=True)
print(drug_dataset_sorted_by_review_length)
for i in range(3):
    review = drug_dataset_sorted_by_review_length["review"][i]
    review_length = drug_dataset_sorted_by_review_length["review_length"][i]
    print(f"\nreview {i}\nlength {review_length}\n{review[:500]}...")
# documentation: https://huggingface.co/docs/datasets/package_reference/main_classes#datasets.Dataset.sort

Dataset({
    features: ['patient_id', 'drugName', 'condition', 'review', 'rating', 'date', 'usefulCount', 'review_length'],
    num_rows: 138514
})

review 0
length 1894
"Two and a half months ago I was prescribed Venlafaxine to help prevent chronic migraines.
It did help the migraines (reduced them by almost half), but with it came a host of side effects that were far worse than the problem I was trying to get rid of.
Having now come off of the stuff, I would not recommend anyone ever use Venlafaxine unless they suffer from extreme / suicidal depression. I mean extreme in the most emphatic sense of the word.
Before trying Venlafaxine, I was a writer. While ...

review 1
length 1162
"I don&rsquo;t find a lot of positive stories about antidepressants, or I find stories where people are taking the antidepressant the wrong way.

I wanted to share my experience.  A positive one.

I&rsquo;ve had generalized anxiety disorder, SEVERE OCD, and panic disorder for as long as I can remember.  My first memory of having an episode was when I was 4 years old at my kindergarten interview.  I feel as though I was born with the illnesses mentioned above, right from the womb.  When I was...

review 2
length 1107
"My Complicated experience with the insertion of the copper IUD. It was &quot;one of the most difficult &amp; Complicated IUD insertions I&#039;ve had in a very long time&quot; quoting the words of my Gynecologist MD. Now I have not been sexually active for over a year and a half (by choice) &amp; I&#039;ve never had kids so that for one was a concern for my doctor since she said i might be very tight &amp; feel pain. Anywhom I am 23 and recently decided to date again &amp; wanted to have a conv...

The last thing we need to deal with is the presence of HTML character codes in our reviews. We can use Python's `html`
 module to unescape these characters, like so:

In [28]:
import html
text = "I&#039;m a transformer called BERT"
html.unescape(text)

"I'm a transformer called BERT"

We'll use `Dataset.map()` to unescape all the HTML characters in our corpus:

In [29]:
drug_dataset = drug_dataset.map(lambda x: {"review": html.unescape(x["review"])})

As you can see, the `Dataset.map()` method is quite useful for processing data — and we haven't even scratched the surface of everything it can do!

### The `map()` method's superpowers

The `Dataset.map()` method takes a batched argument that, if set to `True`, causes it to send a batch of examples to the map function at once (the batch size is configurable but defaults to 1,000). For instance, the previous map function that unescaped all the HTML took a bit of time to run (you can read the time taken from the progress bars). We can speed this up by processing several elements at the same time using a list comprehension.

When you specify `batched=True` the function receives a dictionary with the fields of the dataset, but each value is now a *list of values*, and not just a single value. The return value of `Dataset.map()` should be the same: a dictionary with the fields we want to update or add to our dataset, and a list of values. For example, here is another way to unescape all HTML characters, but using `batched=True`:

In [30]:
new_drug_dataset = drug_dataset.map(
    lambda x: {"review": [html.unescape(o) for o in x["review"]]},
    batched=True
)
new_drug_dataset

DatasetDict({
    train: Dataset({
        features: ['patient_id', 'drugName', 'condition', 'review', 'rating', 'date', 'usefulCount', 'review_length'],
        num_rows: 138514
    })
    test: Dataset({
        features: ['patient_id', 'drugName', 'condition', 'review', 'rating', 'date', 'usefulCount', 'review_length'],
        num_rows: 46108
    })
})

If you're running this code in a notebook, you'll see that this command executes way faster than the previous one. And it's not because our reviews have already been HTML-unescaped — if you re-execute the instruction from the previous section (without `batched=True`), it will take the same amount of time as before. This is because list comprehensions are usually faster than executing the same code in a `for` loop, and we also gain some performance by accessing lots of elements at the same time instead of one by one.

Using `Dataset.map()` with `batched=True` will be essential to unlock the speed of the "fast" tokenizers that we'll encounter in [Chapter 6](https://huggingface.co/course/chapter6), which can quickly tokenize big lists of texts. For instance, to tokenize all the drug reviews with a fast tokenizer, we could use a function like this:

In [31]:
from transformers import AutoTokenizer
tokenizer = AutoTokenizer.from_pretrained("bert-base-cased")
def tokenize_function(examples):
    return tokenizer(examples["review"], truncation=True)

As you saw in [Chapter 3](https://huggingface.co/course/chapter3), we can pass one or several examples to the tokenizer, so we can use this function with or without `batched=True`. Let's take this opportunity to compare the performance of the different options. In a notebook, you can time a one-line instruction by adding `%time` before the line of code you wish to measure:

In [32]:
%time tokenized_dataset = drug_dataset.map(tokenize_function, batched=True)

CPU times: user 12.5 ms, sys: 7.96 ms, total: 20.5 ms
Wall time: 19.5 ms

You can also time a whole cell by putting `%%time` at the beginning of the cell. On the hardware we executed this on, it showed 10.8s for this instruction (it's the number written after "Wall time").
> ✏️ Try it out! <font color="darkgreen">Execute the same instruction with and without `batched=True`, then try it with a slow tokenizer (add `use_fast=False` in the `AutoTokenizer.from_pretrained()` method) so you can see what numbers you get on your hardware.</font>

In [33]:
# Trying it out
## a fast tokenizer
%time tokenized_dataset = drug_dataset.map(tokenize_function, batched=True)
%time tokenized_dataset = drug_dataset.map(tokenize_function, batched=False)
## not a fast tokenizer
not_a_fast_tokenizer = AutoTokenizer.from_pretrained("bert-base-cased", use_fast=False)
def not_a_fast_tokenize_function(examples):
    return not_a_fast_tokenizer(examples["review"], truncation=True)
%time tokenized_dataset = drug_dataset.map(not_a_fast_tokenize_function, batched=True)
%time tokenized_dataset = drug_dataset.map(not_a_fast_tokenize_function, batched=False)

CPU times: user 27.1 ms, sys: 1.91 ms, total: 29 ms
Wall time: 28.6 ms
CPU times: user 14.2 ms, sys: 6.02 ms, total: 20.2 ms
Wall time: 20.2 ms
CPU times: user 313 ms, sys: 7.82 ms, total: 321 ms
Wall time: 324 ms
CPU times: user 305 ms, sys: 8.83 ms, total: 314 ms
Wall time: 314 ms

Here are the results we obtained with and without batching, with a fast and a slow tokenizer:

|Options|Fast tokenizer|Slow tokenizer|
|-------|--------------|--------------|
|`batched=True`|18.3ms|325s|
|`batched=False`|15.5ms|353ms|

This means that using a fast tokenizer with the `batched=True` option is (not) 30 times faster than its slow counterpart with no batching — this is truly amazing! That's the main reason why fast tokenizers are the default when using `AutoTokenizer` (and why they are called "fast"). They're able to achieve such a speedup because behind the scenes the tokenization code is executed in Rust, which is a language that makes it easy to parallelize code execution.

Parallelization is also the reason for the nearly 6x speedup the fast tokenizer achieves with batching: you can't parallelize a single tokenization operation, but when you want to tokenize lots of texts at the same time you can just split the execution across several processes, each responsible for its own texts.

`Dataset.map()` also has some parallelization capabilities of its own. Since they are not backed by Rust, they won't let a slow tokenizer catch up with a fast one, but they can still be helpful (especially if you're using a tokenizer that doesn't have a fast version). To enable multiprocessing, use the `num_proc` argument and specify the number of processes to use in your call to `Dataset.map()`:

In [34]:
slow_tokenizer = AutoTokenizer.from_pretrained("bert-base-cased", use_fast=False)
def slow_tokenize_function(examples):
    return slow_tokenizer(examples["review"], truncation=True)
tokenized_dataset = drug_dataset.map(slow_tokenize_function, batched=True, num_proc=8)
tokenized_dataset

DatasetDict({
    train: Dataset({
        features: ['patient_id', 'drugName', 'condition', 'review', 'rating', 'date', 'usefulCount', 'review_length', 'input_ids', 'token_type_ids', 'attention_mask'],
        num_rows: 138514
    })
    test: Dataset({
        features: ['patient_id', 'drugName', 'condition', 'review', 'rating', 'date', 'usefulCount', 'review_length', 'input_ids', 'token_type_ids', 'attention_mask'],
        num_rows: 46108
    })
})

You can experiment a little with timing to determine the optimal number of processes to use; in our case 8 seemed to produce the best speed gain. Here are the numbers we got with and without multiprocessing:

|Options|Fast tokenizer|Slow tokenizer|
|-------|--------------|--------------|
|`batched=True`|13.6s|2min5s|
|`batched=False`|1min6s|2min34s|
|`batched=True`, `num_proc=8`|6.52s|41.3s|
|`batched=False`, `num_proc=8`|9.49s|45.2s|

Those are much more reasonable results for the slow tokenizer, but the performance of the fast tokenizer was also substantially improved. Note, however, that won't always be the case — for values of `num_proc` other than 8, our tests showed that it was faster to use `batched=True` without that option. In general, we don't recommend using Python multiprocessing for fast tokenizers with `batched=True`.
> <font color="darkgreen">Using `num_proc` to speed up your processing is usually a great idea, as long as the function you are using is not already doing some kind of multiprocessing of its own.</font>

All of this functionality condensed into a single method is already pretty amazing, but there's more! With `Dataset.map()` and `batched=True` you can change the number of elements in your dataset. This is super useful in many situations where you want to create several training features from one example, and we will need to do this as part of the preprocessing for several of the NLP tasks we'll undertake in [Chapter 7](https://huggingface.co/course/chapter7).
> <font color="darkgreen">💡 In machine learning, an *example* is usually defined as the set of *features* that we feed to the model. In some contexts, these features will be the set of columns in a `Dataset`, but in others (like here and for question answering), multiple features can be extracted from a single example and belong to a single column.</font>

Let's have a look at how it works! Here we will tokenize our examples and truncate them to a maximum length of 128, but we will ask the tokenizer to return *all* the chunks of the texts instead of just the first one. This can be done with `return_overflowing_tokens=True`:

In [35]:
def tokenize_and_split(examples):
    return tokenizer(
        examples["review"],
        truncation=True,
        max_length=128,
        return_overflowing_tokens=True,
    )
#
tokenize_and_split

Let's test this on one example before using `Dataset.map()` on the whole dataset:

In [36]:
result = tokenize_and_split(drug_dataset["train"][0])
[len(inp) for inp in result["input_ids"]]

[128, 49]

So, our first example in the training set became two features because it was tokenized to more than the maximum number of tokens we specified: the first one of length 128 and the second one of length 49. Now let's do this for all elements of the dataset!
```python
tokenized_dataset = drug_dataset.map(tokenize_and_split, batched=True)

ArrowInvalid: Column 1 named condition expected length 1463 but got length 1000
```

Oh no! That didn't work! Why not? Looking at the error message will give us a clue: there is a mismatch in the lengths of one of the columns, one being of length 1,463 and the other of length 1,000. If you've looked at the `Dataset.map()` documentation, you may recall that it's the number of samples passed to the function that we are mapping; here those 1,000 examples gave 1,463 new features, resulting in a shape error.

The problem is that we're trying to mix two different datasets of different sizes: the `drug_dataset` columns will have a certain number of examples (the 1,000 in our error), but the `tokenized_dataset` we are building will have more (the 1,463 in the error message). That doesn't work for a `Dataset`, so we need to either remove the columns from the old dataset or make them the same size as they are in the new dataset. We can do the former with the `remove_columns` argument:

In [37]:
tokenized_dataset = drug_dataset.map(
    tokenize_and_split, batched=True, remove_columns=drug_dataset["train"].column_names
)
tokenized_dataset

DatasetDict({
    train: Dataset({
        features: ['input_ids', 'token_type_ids', 'attention_mask', 'overflow_to_sample_mapping'],
        num_rows: 206772
    })
    test: Dataset({
        features: ['input_ids', 'token_type_ids', 'attention_mask', 'overflow_to_sample_mapping'],
        num_rows: 68876
    })
})

Now this works without error. We can check that our new dataset has many more elements than the original dataset by comparing the lengths:

In [38]:
len(tokenized_dataset["train"]), len(drug_dataset["train"])

(206772, 138514)

We mentioned that we can also deal with the mismatched length problem by making the old columns the same size as the new ones. To do this, we will need the `overflow_to_sample_mapping` field the tokenizer returns when we set `return_overflowing_tokens=True`. It gives us a mapping from a new feature index to the index of the sample it originated from. Using this, we can associate each key present in our original dataset with a list of values of the right size by repeating the values of each example as many times as it generates new features:

In [39]:
def tokenize_and_split(examples):
    result = tokenizer(
        examples["review"],
        truncation=True,
        max_length=128,
        return_overflowing_tokens=True,
    )
    # Extract mapping between new and old indices
    sample_map = result.pop("overflow_to_sample_mapping")
    for key, values in examples.items():
        result[key] = [values[i] for i in sample_map]
    return result

We can see it works with `Dataset.map()` without us needing to remove the old columns:

In [40]:
tokenized_dataset = drug_dataset.map(tokenize_and_split, batched=True)
tokenized_dataset

DatasetDict({
    train: Dataset({
        features: ['patient_id', 'drugName', 'condition', 'review', 'rating', 'date', 'usefulCount', 'review_length', 'input_ids', 'token_type_ids', 'attention_mask'],
        num_rows: 206772
    })
    test: Dataset({
        features: ['patient_id', 'drugName', 'condition', 'review', 'rating', 'date', 'usefulCount', 'review_length', 'input_ids', 'token_type_ids', 'attention_mask'],
        num_rows: 68876
    })
})

We get the same number of training features as before, but here we've kept all the old fields. If you need them for some post-processing after applying your model, you might want to use this approach.

You've now seen how 🤗 Datasets can be used to preprocess a dataset in various ways. Although the processing functions of 🤗 Datasets will cover most of your model training needs, there may be times when you'll need to switch to Pandas to access more powerful features, like `DataFrame.groupby()` or high-level APIs for visualization. Fortunately, 🤗 Datasets is designed to be interoperable with libraries such as Pandas, NumPy, PyTorch, TensorFlow, and JAX. Let's take a look at how this works.

### From `Datasets` to `DataFrames` and back

In [41]:
HTML('<iframe width="640" height="360" src="https://www.youtube.com/embed/tfcY1067A5Q" allowfullscreen></iframe>')

/home/matthias/Desktop/MachineLearning/Huggingface-course/env/lib/python3.12/site-packages/IPython/core/display.py:475: UserWarning: Consider using IPython.display.IFrame instead
  warnings.warn("Consider using IPython.display.IFrame instead")

To enable the conversion between various third-party libraries, 🤗 Datasets provides a `Dataset.set_format()` function. This function only changes the *output format* of the dataset, so you can easily switch to another format without affecting the underlying *data format*, which is Apache Arrow. The formatting is done in place. To demonstrate, let's convert our dataset to Pandas:

In [42]:
drug_dataset.set_format("pandas")
drug_dataset

DatasetDict({
    train: Dataset({
        features: ['patient_id', 'drugName', 'condition', 'review', 'rating', 'date', 'usefulCount', 'review_length'],
        num_rows: 138514
    })
    test: Dataset({
        features: ['patient_id', 'drugName', 'condition', 'review', 'rating', 'date', 'usefulCount', 'review_length'],
        num_rows: 46108
    })
})

Now when we access elements of the dataset we get a `pandas.DataFrame` instead of a dictionary:

In [43]:
drug_dataset["train"][:3]

,patient_id,drugName,condition,review,rating,date,usefulCount,review_length
0,95260,Guanfacine,adhd,"""My son is halfway through his fourth week of ...",8.0,"April 27, 2010",192,141
1,92703,Lybrel,birth control,"""I used to take another oral contraceptive, wh...",5.0,"December 14, 2009",17,134
2,138000,Ortho Evra,birth control,"""This is my first time using any form of birth...",8.0,"November 3, 2015",10,89

Let's create a `pandas.DataFrame` for the whole training set by selecting all the elements of `drug_dataset["train"]`:

In [44]:
train_df = drug_dataset["train"][:]
train_df

,patient_id,drugName,condition,review,rating,date,usefulCount,review_length
0,95260,Guanfacine,adhd,"""My son is halfway through his fourth week of ...",8.0,"April 27, 2010",192,141
1,92703,Lybrel,birth control,"""I used to take another oral contraceptive, wh...",5.0,"December 14, 2009",17,134
2,138000,Ortho Evra,birth control,"""This is my first time using any form of birth...",8.0,"November 3, 2015",10,89
3,35696,Buprenorphine / naloxone,opiate dependence,"""Suboxone has completely turned my life around...",9.0,"November 27, 2016",37,124
4,155963,Cialis,benign prostatic hyperplasia,"""2nd day on 5mg started to work with rock hard...",2.0,"November 28, 2015",43,68
...,...,...,...,...,...,...,...,...
138509,164345,Junel 1.5 / 30,birth control,"""This would be my second month on Junel. I've ...",6.0,"May 27, 2015",0,71
138510,191035,Campral,alcohol dependence,"""I wrote my first report in Mid-October of 201...",10.0,"May 31, 2015",125,127
138511,127085,Metoclopramide,nausea/vomiting,"""I was given this in IV before surgey. I immed...",1.0,"November 1, 2011",34,50
138512,47128,Thyroid desiccated,underactive thyroid,"""I've been on thyroid medication 49 years, I s...",10.0,"September 19, 2015",79,136
138513,215220,Lubiprostone,"constipation, chronic","""I've had chronic constipation all my adult li...",9.0,"December 13, 2014",116,63

> <font color="darkgreen">🚨 Under the hood, `Dataset.set_format()` changes the return format for the dataset's `__getitem__()` dunder method. This means that when we want to create a new object like `train_df` from a `Dataset` in the `"pandas"` format, we need to slice the whole dataset to obtain a `pandas.DataFrame`. You can verify for yourself that the type of `drug_dataset["train"]` is `Dataset`, irrespective of the output format.</font>

From here we can use all the Pandas functionality that we want. For example, we can do fancy chaining to compute the class distribution among the `condition` entries:

In [45]:
frequencies = (
    train_df["condition"]
    .value_counts()
    .to_frame()
    .reset_index()
    .rename(columns={"index": "condition", "condition": "frequency"})
)
frequencies.head()

       frequency  count
0  birth control  27655
1     depression   8023
2           acne   5209
3        anxiety   4991
4           pain   4744

And once we're done with our Pandas analysis, we can always create a new `Dataset` object by using the `Dataset.from_pandas()` function as follows:

In [46]:
from datasets import Dataset
freq_dataset = Dataset.from_pandas(frequencies)
freq_dataset

Dataset({
    features: ['frequency', 'count'],
    num_rows: 819
})

> ✏️ Try it out! <font color="darkgreen">Compute the average rating per drug and store the result in a new `Dataset`.</font>

In [47]:
# Trying it out
## https://stackoverflow.com/questions/30482071/how-to-calculate-mean-values-grouped-on-another-column-in-pandas
## https://stackoverflow.com/questions/17141558/how-to-sort-a-dataframe-in-python-pandas-by-two-or-more-columns
ratings = (
    train_df
    .groupby("drugName", as_index=False)["rating"]
    .mean()
    .sort_values(["rating", "drugName"], ascending=[False, True])
)
ratings

                        drugName  rating
0      A + D Cracked Skin Relief    10.0
1                     A / B Otic    10.0
8                    Abiraterone    10.0
12                 Absorbine Jr.    10.0
17                      Accolate    10.0
...                          ...     ...
2999                    Zileuton     1.0
3024                    Zostavax     1.0
3025         Zoster vaccine live     1.0
3027  Zostrix Diabetic Foot Pain     1.0
3049       depo-subQ provera 104     1.0

[3052 rows x 2 columns]

This wraps up our tour of the various preprocessing techniques available in 🤗 Datasets. To round out the section, let's create a validation set to prepare the dataset for training a classifier on. Before doing so, we'll reset the output format of `drug_dataset` from `"pandas"` to `"arrow"`:

In [48]:
drug_dataset.reset_format()
drug_dataset

DatasetDict({
    train: Dataset({
        features: ['patient_id', 'drugName', 'condition', 'review', 'rating', 'date', 'usefulCount', 'review_length'],
        num_rows: 138514
    })
    test: Dataset({
        features: ['patient_id', 'drugName', 'condition', 'review', 'rating', 'date', 'usefulCount', 'review_length'],
        num_rows: 46108
    })
})

### Creating a validation set

Although we have a test set we could use for evaluation, it's a good practice to leave the test set untouched and create a separate validation set during development. Once you are happy with the performance of your models on the validation set, you can do a final sanity check on the test set. This process helps mitigate the risk that you'll overfit to the test set and deploy a model that fails on real-world data.

🤗 Datasets provides a `Dataset.train_test_split()` function that is based on the famous functionality from `scikit-learn`. Let's use it to split our training set into `train` and `validation` splits (we set the seed argument for reproducibility):

In [49]:
drug_dataset_clean = drug_dataset["train"].train_test_split(train_size=0.8, seed=42)
# Rename the default "test" split to "validation"
drug_dataset_clean["validation"] = drug_dataset_clean.pop("test")
# Add the "test" set to our `DatasetDict`
drug_dataset_clean["test"] = drug_dataset["test"]
drug_dataset_clean

DatasetDict({
    train: Dataset({
        features: ['patient_id', 'drugName', 'condition', 'review', 'rating', 'date', 'usefulCount', 'review_length'],
        num_rows: 110811
    })
    validation: Dataset({
        features: ['patient_id', 'drugName', 'condition', 'review', 'rating', 'date', 'usefulCount', 'review_length'],
        num_rows: 27703
    })
    test: Dataset({
        features: ['patient_id', 'drugName', 'condition', 'review', 'rating', 'date', 'usefulCount', 'review_length'],
        num_rows: 46108
    })
})

Great, we've now prepared a dataset that's ready for training some models on! In section 5 we'll show you how to upload datasets to the Hugging Face Hub, but for now let's cap off our analysis by looking at a few ways you can save datasets on your local machine.

### Saving a dataset

In [50]:
HTML('<iframe width="640" height="360" src="https://www.youtube.com/embed/blF9uxYcKHo" allowfullscreen></iframe>')

/home/matthias/Desktop/MachineLearning/Huggingface-course/env/lib/python3.12/site-packages/IPython/core/display.py:475: UserWarning: Consider using IPython.display.IFrame instead
  warnings.warn("Consider using IPython.display.IFrame instead")

Although 🤗 Datasets will cache every downloaded dataset and the operations performed on it, there are times when you'll want to save a dataset to disk (e.g., in case the cache gets deleted). As shown in the table below, 🤗 Datasets provides three main functions to save your dataset in different formats:

|Data format|Function|
|-----------|--------|
|Arrow|`Dataset.save_to_disk()`|
|CSV|`Dataset.to_csv()`|
|JSON|`Dataset.to_json()`|

For example, let's save our cleaned dataset in the Arrow format:

In [51]:
drug_dataset_clean.save_to_disk("sections/section_5/data/drug-reviews")

Saving the dataset (0/1 shards):   0%|          | 0/110811 [00:00<?, ? examples/s]

Saving the dataset (0/1 shards):   0%|          | 0/27703 [00:00<?, ? examples/s]

Saving the dataset (0/1 shards):   0%|          | 0/46108 [00:00<?, ? examples/s]

This will create a directory with the following structure:
```
drug-reviews/
├── dataset_dict.json
├── test
│   ├── dataset.arrow
│   ├── dataset_info.json
│   └── state.json
├── train
│   ├── dataset.arrow
│   ├── dataset_info.json
│   ├── indices.arrow
│   └── state.json
└── validation
    ├── dataset.arrow
    ├── dataset_info.json
    ├── indices.arrow
    └── state.json
```
where we can see that each split is associated with its own *dataset.arrow* table, and some metadata in *dataset_info.json* and *state.json*. You can think of the Arrow format as a fancy table of columns and rows that is optimized for building high-performance applications that process and transport large datasets.

Once the dataset is saved, we can load it by using the `load_from_disk()` function as follows:

In [52]:
from datasets import load_from_disk
drug_dataset_reloaded = load_from_disk("sections/section_5/data/drug-reviews")
drug_dataset_reloaded

DatasetDict({
    train: Dataset({
        features: ['patient_id', 'drugName', 'condition', 'review', 'rating', 'date', 'usefulCount', 'review_length'],
        num_rows: 110811
    })
    validation: Dataset({
        features: ['patient_id', 'drugName', 'condition', 'review', 'rating', 'date', 'usefulCount', 'review_length'],
        num_rows: 27703
    })
    test: Dataset({
        features: ['patient_id', 'drugName', 'condition', 'review', 'rating', 'date', 'usefulCount', 'review_length'],
        num_rows: 46108
    })
})

For the CSV and JSON formats, we have to store each split as a separate file. One way to do this is by iterating over the keys and values in the `DatasetDict` object:

In [53]:
for split, dataset in drug_dataset_clean.items():
    dataset.to_json(f"drug-reviews-{split}.jsonl")

Creating json from Arrow format:   0%|          | 0/111 [00:00<?, ?ba/s]

Creating json from Arrow format:   0%|          | 0/28 [00:00<?, ?ba/s]

Creating json from Arrow format:   0%|          | 0/47 [00:00<?, ?ba/s]

This saves each split in [JSON Lines format](https://jsonlines.org/), where each row in the dataset is stored as a single line of JSON. Here's what the first example looks like:

In [54]:
!mv "drug-reviews-test.jsonl" "sections/section_5/data"
!mv "drug-reviews-train.jsonl" "sections/section_5/data"
!mv "drug-reviews-validation.jsonl" "sections/section_5/data"
!head -n 1 "sections/section_5/data/drug-reviews-train.jsonl"

{"patient_id":89879,"drugName":"Cyclosporine","condition":"keratoconjunctivitis sicca","review":"\"I have used Restasis for about a year now and have seen almost no progress.  For most of my life I've had red and bothersome eyes. After trying various eye drops, my doctor recommended Restasis.  He said it typically takes 3 to 6 months for it to really kick in but it never did kick in.  When I put the drops in it burns my eyes for the first 30 - 40 minutes.  I've talked with my doctor about this and he said it is normal but should go away after some time, but it hasn't. Every year around spring time my eyes get terrible irritated  and this year has been the same (maybe even worse than other years) even though I've been using Restasis for a year now. The only difference I notice was for the first couple weeks, but now I'm ready to move on.\"","rating":2.0,"date":"April 20, 2013","usefulCount":69,"review_length":147}

We can then use the techniques from [section 2](https://huggingface.co/course/chapter5/2) to load the JSON files as follows:

In [55]:
data_files = {
    "train": "sections/section_5/data/drug-reviews-train.jsonl",
    "validation": "sections/section_5/data/drug-reviews-validation.jsonl",
    "test": "sections/section_5/data/drug-reviews-test.jsonl",
}
drug_dataset_reloaded = load_dataset("json", data_files=data_files)
drug_dataset_reloaded

Generating train split: 0 examples [00:00, ? examples/s]

Generating validation split: 0 examples [00:00, ? examples/s]

Generating test split: 0 examples [00:00, ? examples/s]

DatasetDict({
    train: Dataset({
        features: ['patient_id', 'drugName', 'condition', 'review', 'rating', 'date', 'usefulCount', 'review_length'],
        num_rows: 110811
    })
    validation: Dataset({
        features: ['patient_id', 'drugName', 'condition', 'review', 'rating', 'date', 'usefulCount', 'review_length'],
        num_rows: 27703
    })
    test: Dataset({
        features: ['patient_id', 'drugName', 'condition', 'review', 'rating', 'date', 'usefulCount', 'review_length'],
        num_rows: 46108
    })
})

And that's it for our excursion into data wrangling with 🤗 Datasets! Now that we have a cleaned dataset for training a model on, here are a few ideas that you could try out:
1. Use the techniques from [Chapter 3](https://huggingface.co/course/chapter3) to train a classifier that can predict the patient condition based on the drug review.
1. Use the `summarization` pipeline from [Chapter 1](https://huggingface.co/course/chapter1) to generate summaries of the reviews.

Next, we'll take a look at how 🤗 Datasets can enable you to work with huge datasets without blowing up your laptop!

## [Big data? 🤗 Datasets to the rescue!](https://huggingface.co/course/chapter5/4?fw=pt)

Nowadays it is not uncommon to find yourself working with multi-gigabyte datasets, especially if you're planning to pretrain a transformer like BERT or GPT-2 from scratch. In these cases, even *loading* the data can be a challenge. For example, the WebText corpus used to pretrain GPT-2 consists of over 8 million documents and 40 GB of text — loading this into your laptop's RAM is likely to give it a heart attack!

Fortunately, 🤗 Datasets has been designed to overcome these limitations. It frees you from memory management problems by treating datasets as *memory-mapped* files, and from hard drive limits by *streaming* the entries in a corpus.

In [56]:
HTML('<iframe width="640" height="360" src="https://www.youtube.com/embed/JwISwTCPPWo" allowfullscreen></iframe>')

In this section we'll explore these features of 🤗 Datasets with a huge 825 GB corpus known as [the Pile](https://pile.eleuther.ai/). Let's get started!

### What is the Pile?

The Pile is an English text corpus that was created by [EleutherAI](https://www.eleuther.ai/) for training large-scale language models. It includes a diverse range of datasets, spanning scientific articles, GitHub code repositories, and filtered web text. The training corpus is available in [14 GB chunks](https://mystic.the-eye.eu/public/AI/pile/), and you can also download several of the [individual components](https://mystic.the-eye.eu/public/AI/pile_preliminary_components/). Let's start by taking a look at the PubMed Abstracts dataset, which is a corpus of abstracts from 15 million biomedical publications on [PubMed](https://pubmed.ncbi.nlm.nih.gov/). The dataset is in [JSON Lines format](https://jsonlines.org/) and is compressed using the `zstandard` library, so first we need to install that:

In [57]:
# the following command needs to run only once
#!pip install zstandard

Next, we can load the dataset using the method for remote files that we learned in [section 2](https://huggingface.co/course/chapter5/2):

In [58]:
import os
from dotenv import load_dotenv
load_dotenv()
HUGGINGFACE_TOKEN = os.getenv("HUGGINGFACE_TOKEN")
from huggingface_hub import login
login(token=HUGGINGFACE_TOKEN)
import zstandard
from datasets import load_dataset
data_files = "https://huggingface.co/datasets/mdroth/huggingface-course_section-5_zst/resolve/main/data/PubMed-200k-RTC_train.jsonl.zst"
print(data_files)
pubmed_dataset = load_dataset("json", data_files=data_files, split="train")
pubmed_dataset

https://huggingface.co/datasets/mdroth/huggingface-course_section-5_zst/resolve/main/data/PubMed-200k-RTC_train.jsonl.zst

Dataset({
    features: ['abstract_text', 'target'],
    num_rows: 2211861
})

We can see that there are 2,211,861 rows and 2 columns in our dataset — that's a lot!
> <font color="darkgreen">✎ By default, 🤗 Datasets will decompress the files needed to load a dataset. If you want to preserve hard drive space, you can pass `DownloadConfig(delete_extracted=True)` to the `download_config` argument of `load_dataset()`. See the [documentation](https://huggingface.co/docs/datasets/package_reference/builder_classes.html?#datasets.utils.DownloadConfig) for more details.</font>

Let's inspect the contents of the first example:

In [59]:
pubmed_dataset[0]

{'abstract_text': 'The emergence of HIV as a chronic condition means that people living with HIV are required to take more responsibility for the self-management of their condition , including making physical , emotional and social adjustments .',
 'target': 'BACKGROUND'}

Okay, this looks like the abstract from a medical article. Now let's see how much RAM we've used to load the dataset!

### The magic of memory mapping
A simple way to measure memory usage in Python is with the [`psutil`](https://psutil.readthedocs.io/en/latest/) library, which can be installed with `pip` as follows:

In [60]:
# the following command needs to run only once
#!pip install psutil

It provides a `Process` class that allows us to check the memory usage of the current process as follows:

In [61]:
import psutil
# Process.memory_info is expressed in bytes, so convert to megabytes
print(f"RAM used: {psutil.Process().memory_info().rss / (1024**2):.2f} MB")

RAM used: 1203.63 MB

Here, the `rss` attribute refers to the *resident set size*, which is the fraction of memory that a process occupies in RAM. This measurement also includes the memory used by the Python interpreter and the libraries we've loaded, so the actual amount of memory used to load the dataset is a bit smaller. For comparison, let's see how large the dataset is on disk, using the `dataset_size` attribute. Since the result is expressed in bytes like before, we need to manually convert it to mega- or gigabytes:

In [62]:
print(f"Number of files in dataset : {pubmed_dataset.dataset_size}")
size_mb = pubmed_dataset.dataset_size / (1024**3)
print(f"Dataset size (cache file) : {size_mb:.2f} GB")

Number of files in dataset : 368440643
Dataset size (cache file) : 0.34 GB

Nice — despite it being almost 0.34 GB large, we're able to load and access the dataset with much less RAM!
> ✏️ Try it out! <font color="darkgreen">Pick one of the subsets from the Pile that is larger than your laptop or desktop's RAM, load it with 🤗 Datasets, and measure the amount of RAM used. Note that to get an accurate measurement, you'll want to do this in a new process. You can find the decompressed sizes of each subset in Table 1 of the Pile paper.</font>

In [63]:
# Trying it out
data_files = "https://huggingface.co/datasets/mdroth/huggingface-course_section-5_zst/resolve/main/data/LegalText-classification_train.jsonl.zst"
FreeLaw_dataset = load_dataset("json", data_files=data_files, split="train")
print(f"Number of files in dataset : {FreeLaw_dataset.dataset_size}")
size_gb = FreeLaw_dataset.dataset_size / (1024**3)
print(f"Dataset size (cache file) : {size_gb:.2f} GB")

Number of files in dataset : 68062254
Dataset size (cache file) : 0.06 GB

If you're familiar with Pandas, this result might come as a surprise because of Wes Kinney's famous [rule of thumb](https://wesmckinney.com/blog/apache-arrow-pandas-internals/) that you typically need 5 to 10 times as much RAM as the size of your dataset. So how does 🤗 Datasets solve this memory management problem? 🤗 Datasets treats each dataset as a [memory-mapped file](https://en.wikipedia.org/wiki/Memory-mapped_file), which provides a mapping between RAM and filesystem storage that allows the library to access and operate on elements of the dataset without needing to fully load it into memory.

Memory-mapped files can also be shared across multiple processes, which enables methods like `Dataset.map()` to be parallelized without needing to move or copy the dataset. Under the hood, these capabilities are all realized by the [Apache Arrow](https://arrow.apache.org/) memory format and [`pyarrow`](https://arrow.apache.org/docs/python/index.html) library, which make the data loading and processing lightning fast. (For more details about Apache Arrow and comparisons to Pandas, check out [Dejan Simic's blog post](https://towardsdatascience.com/apache-arrow-read-dataframe-with-zero-memory-69634092b1a).) To see this in action, let's run a little speed test by iterating over all the elements in the PubMed Abstracts dataset:

In [64]:
import timeit
code_snippet = """
batch_size = 1000
for idx in range(0, len(pubmed_dataset), batch_size):
    _ = pubmed_dataset[idx:idx + batch_size]
"""
time = timeit.timeit(stmt=code_snippet, number=1, globals=globals())
size_gb = round(size_gb, 2)
time = round(time, 2)
size_gb_per_s = round(size_gb/time, 4)
print(f"Iterated over {len(pubmed_dataset)} examples (about {size_gb} GB) in {time}s, i.e., {size_gb_per_s} GB/s")

Iterated over 2211861 examples (about 0.06 GB) in 3.5s, i.e., 0.0171 GB/s

Here we've used Python's `timeit` module to measure the execution time taken by `code_snippet`. You'll typically be able to iterate over a dataset at speeds of a few tenths of a GB/s to several GB/s. This works great for the vast majority of applications, but sometimes you'll have to work with a dataset that is too large to even store on your laptop's hard drive. For example, if we tried to download the Pile in its entirety, we'd need 825 GB of free disk space! To handle these cases, 🤗 Datasets provides a streaming feature that allows us to download and access elements on the fly, without needing to download the whole dataset. Let's take a look at how this works.
> <font color="darkgreen">💡 In Jupyter notebooks, you can also time cells using the [`%%timeit` magic function](https://ipython.readthedocs.io/en/stable/interactive/magics.html#magic-timeit).</font>

### Streaming datasets
To enable dataset streaming you just need to pass the `streaming=True` argument to the `load_dataset()` function. For example, let's load the PubMed Abstracts dataset again, but in streaming mode:

In [65]:
data_files = "https://huggingface.co/datasets/mdroth/huggingface-course_section-5_zst/resolve/main/data/PubMed-200k-RTC_train.jsonl.zst"
pubmed_dataset_streamed = load_dataset("json", data_files=data_files, split="train", streaming=True)
pubmed_dataset_streamed

IterableDataset({
    features: ['abstract_text', 'target'],
    num_shards: 1
})

Instead of the familiar `Dataset` that we've encountered elsewhere in this chapter, the object returned with `streaming=True` is an `IterableDataset`. As the name suggests, to access the elements of an `IterableDataset` we need to iterate over it. We can access the first element of our streamed dataset as follows:

In [66]:
next(iter(pubmed_dataset_streamed))

{'abstract_text': 'The emergence of HIV as a chronic condition means that people living with HIV are required to take more responsibility for the self-management of their condition , including making physical , emotional and social adjustments .',
 'target': 'BACKGROUND'}

The elements from a streamed dataset can be processed on the fly using `IterableDataset.map()`, which is useful during training if you need to tokenize the inputs. The process is exactly the same as the one we used to tokenize our dataset in [Chapter 3](https://huggingface.co/course/chapter3), with the only difference being that outputs are returned one by one:

In [67]:
tokenizer = AutoTokenizer.from_pretrained("distilbert-base-uncased")
tokenized_dataset = pubmed_dataset_streamed.map(lambda x: tokenizer(x["abstract_text"]))
next(iter(tokenized_dataset))

{'abstract_text': 'The emergence of HIV as a chronic condition means that people living with HIV are required to take more responsibility for the self-management of their condition , including making physical , emotional and social adjustments .',
 'target': 'BACKGROUND',
 'input_ids': [101,
  1996,
  14053,
  1997,
  9820,
  2004,
  1037,
  11888,
  4650,
  2965,
  2008,
  2111,
  2542,
  2007,
  9820,
  2024,
  3223,
  2000,
  2202,
  2062,
  5368,
  2005,
  1996,
  2969,
  1011,
  2968,
  1997,
  2037,
  4650,
  1010,
  2164,
  2437,
  3558,
  1010,
  6832,
  1998,
  2591,
  24081,
  1012,
  102],
 'attention_mask': [1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1]}

> <font color="darkgreen">💡 To speed up tokenization with streaming you can pass `batched=True`, as we saw in the last section. It will process the examples batch by batch; the default batch size is 1,000 and can be specified with the `batch_size` argument.</font>

You can also shuffle a streamed dataset using `IterableDataset.shuffle()`, but unlike `Dataset.shuffle()` this only shuffles the elements in a predefined `buffer_size`:

In [68]:
shuffled_dataset = pubmed_dataset_streamed.shuffle(buffer_size=10_000, seed=42)
next(iter(shuffled_dataset))

{'abstract_text': 'Safety and reactogenicity of a new heptavalent DTPw-HBV/Hib-MenAC ( diphtheria , tetanus , whole cell pertussis-hepatitis B virus/Haemophilus influenzae type b-Neisseria meningitidis serogroups A and C ) vaccine was compared with a widely used pentavalent DTPw-HBV/Hib vaccine .',
 'target': 'OBJECTIVE'}

In this example, we selected a random example from the first 10,000 examples in the buffer. Once an example is accessed, its spot in the buffer is filled with the next example in the corpus (i.e., the 10,001st example in the case above). You can also select elements from a streamed dataset using the `IterableDataset.take()` and `IterableDataset.skip()` functions, which act in a similar way to `Dataset.select()`. For example, to select the first 5 examples in the PubMed Abstracts dataset we can do the following:

In [69]:
dataset_head = pubmed_dataset_streamed.take(5)
list(dataset_head)

[{'abstract_text': 'The emergence of HIV as a chronic condition means that people living with HIV are required to take more responsibility for the self-management of their condition , including making physical , emotional and social adjustments .',
  'target': 'BACKGROUND'},
 {'abstract_text': 'This paper describes the design and evaluation of Positive Outlook , an online program aiming to enhance the self-management skills of gay men living with HIV .',
  'target': 'BACKGROUND'},
 {'abstract_text': 'This study is designed as a randomised controlled trial in which men living with HIV in Australia will be assigned to either an intervention group or usual care control group .',
  'target': 'METHODS'},
 {'abstract_text': "The intervention group will participate in the online group program ` Positive Outlook ' .",
  'target': 'METHODS'},
 {'abstract_text': 'The program is based on self-efficacy theory and uses a self-management approach to enhance skills , confidence and abilities to manage the psychosocial issues associated with HIV in daily life .',
  'target': 'METHODS'}]

Similarly, you can use the `IterableDataset.skip()` function to create training and validation splits from a shuffled dataset as follows:

In [70]:
# Skip the first 1,000 examples and include the rest in the training set
train_dataset = shuffled_dataset.skip(1000)
# Take the first 1,000 examples for the validation set
validation_dataset = shuffled_dataset.take(1000)
validation_dataset

IterableDataset({
    features: ['abstract_text', 'target'],
    num_shards: 1
})

Let's round out our exploration of dataset streaming with a common application: combining multiple datasets together to create a single corpus. 🤗 Datasets provides an `interleave_datasets()` function that converts a list of `IterableDataset` objects into a single `IterableDataset`, where the elements of the new dataset are obtained by alternating among the source examples. This function is especially useful when you're trying to combine large datasets, so as an example let's stream the FreeLaw subset of the Pile, which is a 51 GB dataset of legal opinions from US courts:

In [71]:
law_dataset_streamed = load_dataset(
    "json",
    data_files="https://huggingface.co/datasets/mdroth/huggingface-course_section-5_zst/resolve/main/data/LegalText-classification_train.jsonl.zst",
    split="train",
    streaming=True,
)
next(iter(law_dataset_streamed))

{'case_outcome': 'cited',
 'case_title': 'Alpine Hardwood (Aust) Pty Ltd v Hardys Pty Ltd (No 2) [2002] FCA 224 ; (2002) 190 ALR 121',
 'case_text': 'Ordinarily that discretion will be exercised so that costs follow the event and are awarded on a party and party basis. A departure from normal practice to award indemnity costs requires some special or unusual feature in the case: Alpine Hardwood (Aust) Pty Ltd v Hardys Pty Ltd (No 2) [2002] FCA 224 ; (2002) 190 ALR 121 at [11] (Weinberg J) citing Colgate Palmolive Co v Cussons Pty Ltd (1993) 46 FCR 225 at 233 (Sheppard J).'}

This dataset is large enough to stress the RAM of most laptops, yet we've been able to load and access it without breaking a sweat! Let's now combine the examples from the FreeLaw and PubMed Abstracts datasets with the `interleave_datasets()` function:

In [72]:
from itertools import islice
from datasets import interleave_datasets
combined_dataset = interleave_datasets([pubmed_dataset_streamed, law_dataset_streamed])
list(islice(combined_dataset, 2))

[{'abstract_text': 'The emergence of HIV as a chronic condition means that people living with HIV are required to take more responsibility for the self-management of their condition , including making physical , emotional and social adjustments .',
  'target': 'BACKGROUND',
  'case_outcome': None,
  'case_title': None,
  'case_text': None},
 {'abstract_text': None,
  'target': None,
  'case_outcome': 'cited',
  'case_title': 'Alpine Hardwood (Aust) Pty Ltd v Hardys Pty Ltd (No 2) [2002] FCA 224 ; (2002) 190 ALR 121',
  'case_text': 'Ordinarily that discretion will be exercised so that costs follow the event and are awarded on a party and party basis. A departure from normal practice to award indemnity costs requires some special or unusual feature in the case: Alpine Hardwood (Aust) Pty Ltd v Hardys Pty Ltd (No 2) [2002] FCA 224 ; (2002) 190 ALR 121 at [11] (Weinberg J) citing Colgate Palmolive Co v Cussons Pty Ltd (1993) 46 FCR 225 at 233 (Sheppard J).'}]

Here we've used the `islice()` function from Python's `itertools` module to select the first two examples from the combined dataset, and we can see that they match the first examples from each of the two source datasets.

Finally, if you want to stream the [Pile (deduplicated)](https://huggingface.co/datasets/gmongaras/EleutherAI_the_pile_deduplicated)  in its 825 GB entirety, you can grab all the prepared files as follows:

In [73]:
from datasets import load_dataset
# note the "train-*-of00083.parquet" in the next line
data_files = "https://huggingface.co/datasets/gmongaras/EleutherAI_the_pile_deduplicated/resolve/main/data/train-*-of-00083.parquet"
# load the dataset in streaming mode using the built-in parquet reader
streaming_dataset = load_dataset("parquet", data_files=data_files, streaming=True)
print(streaming_dataset["train"])
# custom addition for iterating over the streaming dataset and printing the first 4 examples
for i, instance in enumerate(streaming_dataset["train"]):
    print("#"*14)
    print(f"# instance {i} #")
    print("#"*14)
    print(f"\n{instance["text"][:1000]} ...\n")
    if i == 3: # stop after printing 4 examples
        break

Resolving data files:   0%|          | 0/83 [00:00<?, ?it/s]

IterableDataset({
    features: ['text'],
    num_shards: 83
})
##############
# instance 0 #
##############

It is done, and submitted. You can play “Survival of the Tastiest” on Android, and on the web. Playing on the web works, but you have to simulate multi-touch for table moving and that can be a bit confusing.

There’s a lot I’d like to talk about. I’ll go through every topic, insted of making the typical what went right/wrong list.

Concept

Working over the theme was probably one of the hardest tasks I had to face.

Originally, I had an idea of what kind of game I wanted to develop, gameplay wise – something with lots of enemies/actors, simple graphics, maybe set in space, controlled from a top-down view. I was confident I could fit any theme around it.

In the end, the problem with a theme like “Evolution” in a game is that evolution is unassisted. It happens through several seemingly random mutations over time, with the most apt permutation surviving. This genetic car simulator is, in my opinion, a great example of actual evolution of a species facing a challenge. But is it a game?

 ...

##############
# instance 1 #
##############

Topic: reinvent midnight madness

Amazon announced a new service at the AWS re:Invent Midnight Madness event. Amazon Sumerian is a solution that aims to make it easier for developers to build virtual reality, augmented reality, and 3D applications. It features a user friendly editor, which can be used to drag and drop 3D objects and characters into scenes. Amazon … continue reading ...

##############
# instance 2 #
##############

About Grand Slam Fishing Charters

As a family owned business we know how important it is that your trip becomes the best memory of your vacation, we are proud of our islands, our waters and our crew and we are desperate show you the best possible time during your stay. We can not guarantee fish every time but we can guarantee you a great time! The biggest perk of our job is seeing so many of our customers become close friends”

A Great Way To Make New Friends!

Our dockside parties are a great way to make new friends! Everyone is welcome!

Andrea runs the whole operation, from discussing your initial needs by phone or email through to ensuring you have sufficient potato chips. Andrea has worked as concierge for many International resorts and fully understands the high expectations of international visitors.

“Life’s A Game But Fishing Is Serious!”

Unlike many tour operators, our crew are highly valued and have been with us since day 1. Each have their own personalities and sense of h ...

##############
# instance 3 #
##############

Working Women, Special Provision and the Debate on Equality

There has been considerable coverage in the media recently about the possibility of offering women in employment paid leave from work during their menstrual period. This has generated a broad range of responses relating to long-standing discussions about ‘equality’ and ‘difference’: is women’s equality best achieved by treating them the same as men or by making provisions that recognise their differences in terms of physiological constitution and biological functions?

If the UK introduces such an initiative, it would not be the first country in the contemporary world to do so. Many countries in Asia already make the provision and Russia debated introducing a law in 2013. The policy also has a significant historical precedent. A whole chapter of my book Women Workers in the Soviet Interwar Economy: From ‘Protection’ to ‘Equality’ (Macmillan, 1999), based on extensive research conducted for my PhD, is devoted to ‘Provision for ...

> ✏️ Try it out! <font color="darkgreen">Use one of the large Common Crawl corpora like [`mc4`](https://huggingface.co/datasets/mc4) or [`oscar`](https://huggingface.co/datasets/oscar) to create a streaming multilingual dataset that represents the spoken proportions of languages in a country of your choice. For example, the four national languages in Switzerland are German, French, Italian, and Romansh, so you could try creating a Swiss corpus by sampling the Oscar subsets according to their spoken proportion.</font>

In [74]:
# Trying it out
# The following languages are supported: bg, cs, da, de, el, en, es, et, fi, fr, ga, hu, it, lt, lv, mt, nl, pl, pt, ro, sk, sl, sv
# According to ChatGPT, 96.5% of people in Germany speak German and 60.5% speak English
# 96.5 / 60.5 = 1.5950 = 15950 / 10000
mc4_legal_dataset_de = load_dataset("joelito/mc4_legal", "de", split="train", streaming=True).remove_columns(["url", "timestamp", "matches"])
mc4_legal_dataset_en = load_dataset("joelito/mc4_legal", "en", split="train", streaming=True).remove_columns(["url", "timestamp", "matches"])
mc4_legal_dataset_de, mc4_legal_dataset_en

Loading Dataset Infos from /home/matthias/.cache/huggingface/modules/datasets_modules/datasets/joelito--mc4_legal/455b0c3963b4c25452e226c39b79bcbb7f8c2fc30ca86b7a930b157a0618814b
Loading Dataset Infos from /home/matthias/.cache/huggingface/modules/datasets_modules/datasets/joelito--mc4_legal/455b0c3963b4c25452e226c39b79bcbb7f8c2fc30ca86b7a930b157a0618814b

(IterableDataset({
     features: ['index', 'text'],
     num_shards: 2
 }),
 IterableDataset({
     features: ['index', 'text'],
     num_shards: 2
 }))

These are the chosen datasets. The following function takes two lists as arguments: The first list is a list of iterable datasets and the second is an equally long list of instances. The latter list shall be used to control the number of instances stemming from the passed datasets.

In [75]:
# Still trying it out
import random
from itertools import islice
def interleaved_shuffle(datasets, samples_per_dataset, buffer_size=1000):
    """
    Streams from multiple datasets and interleaves their samples with partial shuffling.
    Arguments:
    - datasets: list of streaming datasets (or iterators)
    - samples_per_dataset: list of integers (how many items to take from each)
    - buffer_size: number of items to buffer before shuffling
    Returns:
    - a generator that yields interleaved and partially shuffled examples
    """
    # Make sure we're getting actual samples from each dataset, not the iterators themselves!
    iterators = [islice(ds, n) for ds, n in zip(datasets, samples_per_dataset)]
    # This will store our current buffer of samples
    buffer = []
    # We'll loop until all iterators are exhausted
    # Instead of zip(), loop over each iterator independently in round-robin style
    while iterators:
        for i, it in enumerate(iterators[:]):  # iterate over a *copy* of the list
            try:
                item = next(it)  # try to get next item
                buffer.append(item)
            except StopIteration:
                # Remove exhausted iterator
                iterators.remove(it)
            # If buffer is full, shuffle and yield
            if len(buffer) >= buffer_size:
                random.shuffle(buffer)
                for sample in buffer:
                    yield sample
                buffer.clear()
    # Final flush of any remaining items
    if buffer:
        random.shuffle(buffer)
        for sample in buffer:
            yield sample
from itertools import islice

# Create the interleaved and shuffled streaming dataset
mc4_legal_de_en_interleaved_shuffled_streaming_dataset = interleaved_shuffle(
    [mc4_legal_dataset_de, mc4_legal_dataset_en],
    [15950, 10000]
)
# Now print the actual first m examples and each text only until the n-th character
m = 3
n = 1000
for i, example in enumerate(islice(mc4_legal_de_en_interleaved_shuffled_streaming_dataset, m), 1):
    print(f"\n{i}.\n{example['text'][:n]} ...")

1.
Europäischer Gerichtshof, Urteil vom 08.05.2003 mit dem Az.: C-14/02	/* Banner Ads */
Aktenzeichen: C-14/02
Rechtsgebiete: EGV, Richtlinie 73/23/EWG, Richtlinie 89/336/EWG, Richtlinie 1999/5/EWG
Richtlinie 1999/5/EWG
1. Aus dem Wortlaut und der Zielsetzung der Richtlinie 73/23 zur Angleichung der Rechtsvorschriften der Mitgliedstaaten betreffend elektrische Betriebsmittel zur Verwendung innerhalb bestimmter Spannungsgrenzen, der Richtlinie 89/336 zur Angleichung der Rechtsvorschriften der Mitgliedstaaten über die elektromagnetische Verträglichkeit sowie der Richtlinie 1999/5 über Funkanlagen und Telekommunikationseinrichtungen und die gegenseitige Anerkennung ihrer Konformität ergibt sich, dass sie in ihrem jeweiligen Anwendungsbereich eine vollständige Harmonisierung bezwecken. Folglich müssen die Mitgliedstaaten diesen Richtlinien in den diesen unterliegenden Bereichen voll nachkommen und dürfen zuwiderlaufende nationale Bestimmungen nicht beibehalten.
Artikel 3 der Richtlinie 73/23, ...

2.
Die Erkenntnis, dass der Handel mit Episode 1 16 terakhir buku sinopsis drama korea terbaru,baca sinopsis sinopsis drama korea terbaru Sinopsis Marriage Not Dating Episode 1 Terakhir.20 Jul 2014 Keterangan K-Drama. Judul drama Korea: Marriage Not Dating (literal title) Revised romanization: Yeonae Malgo Gyeolhon Hangul: 연애 말고 dating uk no registration heb20 Jul 2014 Episode 6: I Who Seem Alone but Is Not Alone But Looks Alone aka Am Marriage, Not Dating Episode 6 Recap July 24, 2014 at 1:16 PM. match dating new zealand nu30 Des 2014 Sinopsis Drama Korea Terbaru Marriage Not Dating ini akan membahas Marriage Not Dating Episode 1 hingga terakhir serta menyajikan
Sinopsis Drama Korea: Sinopsis Marriage Not Dating Episode 2-1
Sinopsis Drama Korea Terbaru Marriage Not Dating Episode 1- Terakhir, Sinopsis Lengkap Marriage Not Dating Episode 1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16 p diddy dating 2014 Instagram foto vanonlyhdkorean - MARRIAGE NOT DATING ❀ Episode 9 r dating tips newsletter 22 A ...

3.
Keine Finanzamtszuständigkeit bei ausländischem Zulassungsbesitzer bei fiktiver Erstzulassung - Findok Internet
Berufungsentscheidung - Steuer (Referent) des UFSL vom 17.01.2005, RV/0189-L/03
Keine Finanzamtszuständigkeit bei ausländischem Zulassungsbesitzer bei fiktiver Erstzulassung
RV/0189-L/03-RS1 Permalink
Die Erhebung der NoVA bei erstmaliger (fiktiver) Zulassung nach § 1 Zi 3 NoVAG setzt einen Besitzer der ausländischen Zulassung mit inländischem (Wohn)Sitz voraus, da andernfalls nach § 11 Abs 2 NoVAG iVm § 4 Zi 2 NoVAG keine inländische Finanzamtszuständigkeit besteht.
Verwendung im Inland, Kraftfahrgesetz, Zulassung, Abgabenschuldner, Zuständigkeit, Zulassungsbesitzer, rechtmäßiger Besitzer
Der unabhängige Finanzsenat hat über die Berufung des Bw, Adresse, vertreten durch Wölflingseder & Partner, Steuerberatungskanzlei, 4040 Linz, J.W. Kleinstrasse 18,vom 4. Oktober 2002 gegen den Bescheid des Finanzamtes Kirchdorf an der Krems, vertreten durch HR Dr. Josef Reiter,vom 21. Juni ...

You now have all the tools you need to load and process datasets of all shapes and sizes — but unless you're exceptionally lucky, there will come a point in your NLP journey where you'll have to actually create a dataset to solve the problem at hand. That's the topic of the next section!

## [Creating your own dataset](https://huggingface.co/course/chapter5/5?fw=pt)

Sometimes the dataset that you need to build an NLP application doesn't exist, so you'll need to create it yourself. In this section we'll show you how to create a corpus of [GitHub issues](https://github.com/features/issues/), which are commonly used to track bugs or features in GitHub repositories. This corpus could be used for various purposes, including:
- Exploring how long it takes to close open issues or pull requests
- Training a *multilabel classifier* that can tag issues with metadata based on the issue's description (e.g., "bug", "enhancement", or "question")
- Creating a semantic search engine to find which issues match a user's query

Here we'll focus on creating the corpus, and in the next section we'll tackle the semantic search application. To keep things meta, we'll use the GitHub issues associated with a popular open source project: 🤗 Datasets! Let's take a look at how to get the data and explore the information contained in these issues.

### Getting the data

You can find all the issues in 🤗 Datasets by navigating to the repository's [Issues tab](https://github.com/huggingface/datasets/issues). As shown in the following screenshot, at the time of writing there were 331 open issues and 668 closed ones.

<img style="float=center;" src="sections/section_5/images/huggingfaceDatasets.png" width="80%">

If you click on one of these issues you'll find it contains a title, a description, and a set of labels that characterize the issue. An example is shown in the screenshot below.

<img style="float=center;" src="sections/section_5/images/enableStreaming.png" width="90%">

To download all the repository's issues, we'll use the [GitHub REST API](https://docs.github.com/en/rest) to poll the [`Issues` endpoint](https://docs.github.com/en/rest/reference/issues#list-repository-issues). This endpoint returns a list of JSON objects, with each object containing a large number of fields that include the title and description as well as metadata about the status of the issue and so on.

A convenient way to download the issues is via the `requests` library, which is the standard way for making HTTP requests in Python. You can install the library by running:

In [76]:
# the following command needs to run only once 
#!pip install requests

Once the library is installed, you can make GET requests to the `Issues` endpoint by invoking the `requests.get()` function. For example, you can run the following command to retrieve the first issue on the first page:

In [77]:
import requests
url = "https://api.github.com/repos/huggingface/datasets/issues?page=1&per_page=1"
response = requests.get(url)

The `response` object contains a lot of useful information about the request, including the HTTP status code:

In [78]:
response.status_code

200

where a `200` status means the request was successful (you can find a list of possible HTTP status codes [here](https://en.wikipedia.org/wiki/List_of_HTTP_status_codes)). What we are really interested in, though, is the *payload*, which can be accessed in various formats like bytes, strings, or JSON. Since we know our issues are in JSON format, let's inspect the payload as follows:

In [79]:
response.json()

[{'url': 'https://api.github.com/repos/huggingface/datasets/issues/7472',
  'repository_url': 'https://api.github.com/repos/huggingface/datasets',
  'labels_url': 'https://api.github.com/repos/huggingface/datasets/issues/7472/labels{/name}',
  'comments_url': 'https://api.github.com/repos/huggingface/datasets/issues/7472/comments',
  'events_url': 'https://api.github.com/repos/huggingface/datasets/issues/7472/events',
  'html_url': 'https://github.com/huggingface/datasets/issues/7472',
  'id': 2937607272,
  'node_id': 'I_kwDODunzps6vGFRo',
  'number': 7472,
  'title': 'Label casting during `map` process is canceled after the `map` process',
  'user': {'login': 'yoshitomo-matsubara',
   'id': 11156001,
   'node_id': 'MDQ6VXNlcjExMTU2MDAx',
   'avatar_url': 'https://avatars.githubusercontent.com/u/11156001?v=4',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/yoshitomo-matsubara',
   'html_url': 'https://github.com/yoshitomo-matsubara',
   'followers_url': 'https://api.github.com/users/yoshitomo-matsubara/followers',
   'following_url': 'https://api.github.com/users/yoshitomo-matsubara/following{/other_user}',
   'gists_url': 'https://api.github.com/users/yoshitomo-matsubara/gists{/gist_id}',
   'starred_url': 'https://api.github.com/users/yoshitomo-matsubara/starred{/owner}{/repo}',
   'subscriptions_url': 'https://api.github.com/users/yoshitomo-matsubara/subscriptions',
   'organizations_url': 'https://api.github.com/users/yoshitomo-matsubara/orgs',
   'repos_url': 'https://api.github.com/users/yoshitomo-matsubara/repos',
   'events_url': 'https://api.github.com/users/yoshitomo-matsubara/events{/privacy}',
   'received_events_url': 'https://api.github.com/users/yoshitomo-matsubara/received_events',
   'type': 'User',
   'user_view_type': 'public',
   'site_admin': False},
  'labels': [],
  'state': 'open',
  'locked': False,
  'assignee': None,
  'assignees': [],
  'milestone': None,
  'comments': 0,
  'created_at': '2025-03-21T07:56:22Z',
  'updated_at': '2025-03-21T07:58:14Z',
  'closed_at': None,
  'author_association': 'NONE',
  'type': None,
  'sub_issues_summary': {'total': 0, 'completed': 0, 'percent_completed': 0},
  'active_lock_reason': None,
  'body': '### Describe the bug\n\nWhen preprocessing a multi-label dataset, I introduced a step to convert int labels to float labels as [BCEWithLogitsLoss](https://pytorch.org/docs/stable/generated/torch.nn.BCEWithLogitsLoss.html) expects float labels and forward function of models in transformers package internally use `BCEWithLogitsLoss`\n\nHowever, the casting was canceled after `.map` process and the label values still use int values, which leads to an error\n```\n  File "/home/yoshitomo/anaconda3/envs/torchdistill/lib/python3.10/site-packages/transformers/models/bert/modeling_bert.py", line 1711, in forward\n    loss = loss_fct(logits, labels)\n  File "/home/yoshitomo/anaconda3/envs/torchdistill/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl\n    return self._call_impl(*args, **kwargs)\n  File "/home/yoshitomo/anaconda3/envs/torchdistill/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl\n    return forward_call(*args, **kwargs)\n  File "/home/yoshitomo/anaconda3/envs/torchdistill/lib/python3.10/site-packages/torch/nn/modules/loss.py", line 819, in forward\n    return F.binary_cross_entropy_with_logits(\n  File "/home/yoshitomo/anaconda3/envs/torchdistill/lib/python3.10/site-packages/torch/nn/functional.py", line 3628, in binary_cross_entropy_with_logits\n    return torch.binary_cross_entropy_with_logits(\nRuntimeError: result type Float can\'t be cast to the desired output type Long\n```\n\nThis seems like happening only when the original labels are int values (see examples below)\n\n### Steps to reproduce the bug\n\nIf the original dataset uses a list of int labels, it will cancel the int->float casting\n\n```python\nfrom datasets import Dataset\n\ndata = {\n    \'text\': [\'text1\', \'text2\', \'text3\', \'text4\'],\n    \'labels\': [[0, 1, 2], [3], [3, 4], [3]]\n}\n\ndataset = Dataset.from_dict(data)\n\nlabel_set = set([label for labels in data[\'labels\'] for label in labels])\nlabel2idx = {label: idx for idx, label in enumerate(sorted(label_set))}\n\n\ndef multi_labels_to_ids(labels):\n    ids = [0.0] * len(label2idx)\n    for label in labels:\n        ids[label2idx[label]] = 1.0\n    return ids\n\ndef preprocess(examples):\n    result = {\'sentence\': [[0, 3, 4] for _ in range(len(examples[\'labels\']))]}\n    print(\'"labels" are int\', examples[\'labels\'])\n    result[\'labels\'] = [multi_labels_to_ids(l) for l in examples[\'labels\']]\n    print(\'"labels" were converted to multi-label format with float values\', result[\'labels\'])\n    return result\n\n\npreprocessed_dataset = dataset.map(preprocess, batched=True, remove_columns=[\'labels\', \'text\'])\nprint(preprocessed_dataset[0][\'labels\'])\n# Output: "[1, 1, 1, 0, 0]"\n# Expected: "[1.0, 1.0, 1.0, 0.0, 0.0]"\n```\n\nIf the original dataset uses non-int labels, it works as expected.\n\n```python\nfrom datasets import Dataset\n\ndata = {\n    \'text\': [\'text1\', \'text2\', \'text3\', \'text4\'],\n    \'labels\': [[\'label1\', \'label2\', \'label3\'], [\'label4\'], [\'label4\', \'label5\'], [\'label4\']]\n}\n\ndataset = Dataset.from_dict(data)\n\nlabel_set = set([label for labels in data[\'labels\'] for label in labels])\nlabel2idx = {label: idx for idx, label in enumerate(sorted(label_set))}\n\n\ndef multi_labels_to_ids(labels):\n    ids = [0.0] * len(label2idx)\n    for label in labels:\n        ids[label2idx[label]] = 1.0\n    return ids\n\ndef preprocess(examples):\n    result = {\'sentence\': [[0, 3, 4] for _ in range(len(examples[\'labels\']))]}\n    print(\'"labels" are int\', examples[\'labels\'])\n    result[\'labels\'] = [multi_labels_to_ids(l) for l in examples[\'labels\']]\n    print(\'"labels" were converted to multi-label format with float values\', result[\'labels\'])\n    return result\n\n\npreprocessed_dataset = dataset.map(preprocess, batched=True, remove_columns=[\'labels\', \'text\'])\nprint(preprocessed_dataset[0][\'labels\'])\n# Output: "[1.0, 1.0, 1.0, 0.0, 0.0]"\n# Expected: "[1.0, 1.0, 1.0, 0.0, 0.0]"\n```\n\nNote that the only difference between these two examples is\n>    \'labels\': [[0, 1, 2], [3], [3, 4], [3]]\n\nv.s\n\n>    \'labels\': [[\'label1\', \'label2\', \'label3\'], [\'label4\'], [\'label4\', \'label5\'], [\'label4\']]\n\n\n\n### Expected behavior\n\nEven if the original dataset uses a list of int labels, the int->float casting during `.map` process should not be canceled as shown in the above example\n\n### Environment info\n\nOS Ubuntu 22.04 LTS\nPython 3.10.11\ndatasets v3.4.1',
  'closed_by': None,
  'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/7472/reactions',
   'total_count': 0,
   '+1': 0,
   '-1': 0,
   'laugh': 0,
   'hooray': 0,
   'confused': 0,
   'heart': 0,
   'rocket': 0,
   'eyes': 0},
  'timeline_url': 'https://api.github.com/repos/huggingface/datasets/issues/7472/timeline',
  'performed_via_github_app': None,
  'state_reason': None}]

Whoa, that's a lot of information! We can see useful fields like `title`, `body`, and `number` that describe the issue, as well as information about the GitHub user who opened the issue.
> ✏️ Try it out! <font color="darkgreen">Click on a few of the URLs in the JSON payload above to get a feel for what type of information each GitHub issue is linked to.</font>

In [80]:
# Trying it out
try_str = """
The url https://github.com/huggingface/datasets/issues/7399 is about a potential bug in the IterableDatasetDict map function:
It might be missing the desc parameter.
Under `user` > `avatar_url`, the url https://avatars.githubusercontent.com/u/7976840?v=4 leads to a cute avatar image.
"""
print(try_str)

The url https://github.com/huggingface/datasets/issues/7399 is about a potential bug in the IterableDatasetDict map function:
It might be missing the desc parameter.
Under `user` > `avatar_url`, the url https://avatars.githubusercontent.com/u/7976840?v=4 leads to a cute avatar image.

As described in the GitHub [documentation](https://docs.github.com/en/rest/overview/resources-in-the-rest-api#rate-limiting), unauthenticated requests are limited to 60 requests per hour. Although you can increase the `per_page` query parameter to reduce the number of requests you make, you will still hit the rate limit on any repository that has more than a few thousand issues. So instead, you should follow GitHub's [instructions](https://docs.github.com/en/github/authenticating-to-github/creating-a-personal-access-token) on creating a *personal access token* so that you can boost the rate limit to 5,000 requests per hour. Once you have your token, you can include it as part of the request header:

In [81]:
GITHUB_TOKEN = os.getenv("GITHUB_TOKEN")
headers = {"Authorization": f"token {GITHUB_TOKEN}"}

> <font color="darkred">⚠️ Do not share a notebook with your `GITHUB_TOKEN` pasted in it. We recommend you delete the last cell once you have executed it to avoid leaking this information accidentally. Even better, store the token in an *.env* file and use the [`python-dotenv` library](https://github.com/theskumar/python-dotenv) to load it automatically for you as an environment variable</font>.

Now that we have our access token, let's create a function that can download all the issues from a GitHub repository:

In [113]:
import time
import math
from pathlib import Path
import pandas as pd
from tqdm.notebook import tqdm

def fetch_issues(
    owner="huggingface",
    repo="datasets",
    num_issues=1_000,
    rate_limit=100,
    issues_path=Path("."),
):
    if not issues_path.is_dir():
        issues_path.mkdir(exist_ok=True)

    batch = []
    all_issues = []
    per_page = 100  # Number of issues to return per page
    num_pages = math.ceil(num_issues / per_page)
    base_url = "https://api.github.com/repos"

    for page in tqdm(range(num_pages)):
        # Query with state=all to get both open and closed issues
        query = f"issues?page={page}&per_page={per_page}&state=all"
        issues = requests.get(f"{base_url}/{owner}/{repo}/{query}", headers=headers)
        batch.extend(issues.json())

        if len(batch) > rate_limit and len(all_issues) < num_issues:
            all_issues.extend(batch)
            batch = []  # Flush batch for next time period
            print(f"Reached GitHub rate limit. Sleeping for one hour ...")
            time.sleep(60 * 60 + 1)

    all_issues.extend(batch)
    df = pd.DataFrame.from_records(all_issues)
    df.to_json(f"{issues_path}/{repo}-issues.jsonl", orient="records", lines=True)
    print(f"Downloaded all the issues for {repo}! Dataset stored at {issues_path}/{repo}-issues.jsonl")

Now when we call `fetch_issues()` it will download all the issues in batches to avoid exceeding GitHub's limit on the number of requests per hour; the result will be stored locally in a *repository_name-issues.jsonl* file, where each line is a JSON object that represents an issue. Let's use this function to grab all the issues from 🤗 Datasets:

In [ ]:
# Depending on your internet connection, this can take several minutes to run...
# The following line needs to run only once (run 'fetch_issues(repo="transformers")' for "Try it out" further below)
fetch_issues()                      # for the default datasets repo

  0%|          | 0/10 [00:00<?, ?it/s]

Reached GitHub rate limit. Sleeping for one hour ...

Once the issues are downloaded we can load them locally using our newfound skills from [section 2](https://huggingface.co/course/chaper5/2):

In [115]:
issues_dataset = load_dataset("json", data_files="sections/section_5/data/datasets-issues.jsonl", split="train")
issues_dataset

Using custom data configuration default-ad8f542b20e92ae9
Loading Dataset Infos from /home/matthias/Desktop/MachineLearning/Huggingface-course/env/lib/python3.12/site-packages/datasets/packaged_modules/json
Overwrite dataset info from restored data version if exists.
Loading Dataset info from /home/matthias/.cache/huggingface/datasets/json/default-ad8f542b20e92ae9/0.0.0/f4e89e8750d5d5ffbef2c078bf0ddfedef29dc2faff52a6255cf513c05eb1092
Found cached dataset json (/home/matthias/.cache/huggingface/datasets/json/default-ad8f542b20e92ae9/0.0.0/f4e89e8750d5d5ffbef2c078bf0ddfedef29dc2faff52a6255cf513c05eb1092)
Loading Dataset info from /home/matthias/.cache/huggingface/datasets/json/default-ad8f542b20e92ae9/0.0.0/f4e89e8750d5d5ffbef2c078bf0ddfedef29dc2faff52a6255cf513c05eb1092

Dataset({
    features: ['url', 'repository_url', 'labels_url', 'comments_url', 'events_url', 'html_url', 'id', 'node_id', 'number', 'title', 'user', 'labels', 'state', 'locked', 'assignee', 'assignees', 'milestone', 'comments', 'created_at', 'updated_at', 'closed_at', 'author_association', 'type', 'sub_issues_summary', 'active_lock_reason', 'body', 'closed_by', 'reactions', 'timeline_url', 'performed_via_github_app', 'state_reason', 'draft', 'pull_request'],
    num_rows: 3000
})

Great, we've created our first dataset from scratch! But why are there several thousand issues when the [Issues tab](https://github.com/huggingface/datasets/issues) of the 🤗 Datasets repository only shows around 1,000 issues in total 🤔? As described in the GitHub [documentation](https://docs.github.com/en/rest/reference/issues#list-issues-assigned-to-the-authenticated-user), that's because we've downloaded all the pull requests as well:

> <i>"GitHub's REST API v3 considers every pull request an issue, but not every *issue* is a pull request. For this reason, "*Issues*" endpoints may return both issues and pull requests in the response. You can identify pull requests by the `pull_request` key. Be aware that the `id` of a pull request returned from "*Issues*" endpoints will be an issue id."</i>

Since the contents of issues and pull requests are quite different, let's do some minor preprocessing to enable us to distinguish between them.

### Cleaning up the data

The above snippet from GitHub's documentation tells us that the `pull_request` column can be used to differentiate between issues and pull requests. Let's look at a random sample to see what the difference is. As we did in [section 3](https://huggingface.co/course/chapter5/3), we'll chain `Dataset.shuffle()` and `Dataset.select()` to create a random sample and then zip the `html_url` and `pull_request` columns so we can compare the various URLs:

In [116]:
sample = issues_dataset.shuffle(seed=666).select(range(3))
# print out the URL and pull request entries
for url, pr in zip(sample["html_url"], sample["pull_request"]):
    print(f">> URL: {url}")
    print(f">> Pull request: {pr}\n")

Loading cached shuffled indices for dataset at /home/matthias/.cache/huggingface/datasets/json/default-ad8f542b20e92ae9/0.0.0/f4e89e8750d5d5ffbef2c078bf0ddfedef29dc2faff52a6255cf513c05eb1092/cache-1246b532aba00c4b.arrow

>> URL: https://github.com/huggingface/datasets/issues/7323
>> Pull request: None

>> URL: https://github.com/huggingface/datasets/pull/4630
>> Pull request: {'url': 'https://api.github.com/repos/huggingface/datasets/pulls/4630', 'html_url': 'https://github.com/huggingface/datasets/pull/4630', 'diff_url': 'https://github.com/huggingface/datasets/pull/4630.diff', 'patch_url': 'https://github.com/huggingface/datasets/pull/4630.patch', 'merged_at': datetime.datetime(2022, 7, 5, 15, 8, 21)}

>> URL: https://github.com/huggingface/datasets/pull/4645
>> Pull request: {'url': 'https://api.github.com/repos/huggingface/datasets/pulls/4645', 'html_url': 'https://github.com/huggingface/datasets/pull/4645', 'diff_url': 'https://github.com/huggingface/datasets/pull/4645.diff', 'patch_url': 'https://github.com/huggingface/datasets/pull/4645.patch', 'merged_at': datetime.datetime(2022, 7, 6, 15, 45, 5)}

Here we can see that each pull request is associated with various URLs, while ordinary issues have a `None` entry. We can use this distinction to create a new `is_pull_request` column that checks whether the `pull_request` field is `None` or not:

In [117]:
issues_dataset = issues_dataset.map(lambda x: {"is_pull_request": False if x["pull_request"] is None else True})
issues_dataset

Loading cached processed dataset at /home/matthias/.cache/huggingface/datasets/json/default-ad8f542b20e92ae9/0.0.0/f4e89e8750d5d5ffbef2c078bf0ddfedef29dc2faff52a6255cf513c05eb1092/cache-329a0347ca0f3357.arrow

Dataset({
    features: ['url', 'repository_url', 'labels_url', 'comments_url', 'events_url', 'html_url', 'id', 'node_id', 'number', 'title', 'user', 'labels', 'state', 'locked', 'assignee', 'assignees', 'milestone', 'comments', 'created_at', 'updated_at', 'closed_at', 'author_association', 'type', 'sub_issues_summary', 'active_lock_reason', 'body', 'closed_by', 'reactions', 'timeline_url', 'performed_via_github_app', 'state_reason', 'draft', 'pull_request', 'is_pull_request'],
    num_rows: 3000
})

> ✏️ Try it out! <font color="darkgreen">Calculate the average time it takes to close issues in 🤗 Datasets. You may find the `Dataset.filter()` function useful to filter out the pull requests and open issues, and you can use the `Dataset.set_format()` function to convert the dataset to a `DataFrame` so you can easily manipulate the `created_at` and `closed_at` timestamps. For bonus points, calculate the average time it takes to close pull requests.</font>

In [118]:
# Trying it out
import datetime
## get closed issues and pull requests
print(f"total items:\t\t{issues_dataset.num_rows}")
closed_dataset = issues_dataset.filter(lambda x: x["closed_at"] is not None)
print(f"closed items:\t\t{closed_dataset.num_rows}")
closed_issues_dataset = closed_dataset.filter(lambda x: x["pull_request"] is None)
print(f"closed issues:\t\t{closed_issues_dataset.num_rows}")
closed_pullRequests_dataset = closed_dataset.filter(lambda x: x["pull_request"] is not None)
print(f"closed pull requests:\t{closed_pullRequests_dataset.num_rows}")
## define helper functions
### format time
def formatTime(tstr, value, unit, trail):
    if tstr!="" or value!=0:
        tstr += f"{int(value)}{unit}{trail}"
    return tstr
### turn seconds into time string
def secs2DHMS(secs):
    tstr=""
    days = secs // (24 * 3600)
    secs %= 24 * 3600
    tstr = formatTime(tstr, days, "d", " ")
    hours = secs // 3600
    secs %= 3600
    tstr = formatTime(tstr, hours, "h", ":")
    mins = secs // 60
    secs %= 60
    tstr = formatTime(tstr, mins, "m", ":")
    tstr = formatTime(tstr, secs, "s", "")
    return tstr
### get mean closing time (in seconds) of github issues or pull requests
def get_mean_closing_time(github_dataset):
    durations = []
    for item in github_dataset:
        start = str(item["created_at"])
        end = str(item["closed_at"])
        # https://docs.python.org/3/library/datetime.html#strftime-and-strptime-format-codes
        start_seconds = time.mktime(datetime.datetime.strptime(start, "%Y-%m-%d %H:%M:%S").timetuple())
        end_seconds = time.mktime(datetime.datetime.strptime(end, "%Y-%m-%d %H:%M:%S").timetuple())
        durations.append(end_seconds - start_seconds)
    mean = sum(durations) / len(durations)
    return secs2DHMS(mean)
## produce output
print(f"average duration until closing for GitHub issues:\t\t{get_mean_closing_time(closed_issues_dataset)}")
print(f"average duration until closing for GitHub pull requests:\t{get_mean_closing_time(closed_pullRequests_dataset)}")

Loading cached processed dataset at /home/matthias/.cache/huggingface/datasets/json/default-ad8f542b20e92ae9/0.0.0/f4e89e8750d5d5ffbef2c078bf0ddfedef29dc2faff52a6255cf513c05eb1092/cache-be874956fbd0d54a.arrow
Loading cached processed dataset at /home/matthias/.cache/huggingface/datasets/json/default-ad8f542b20e92ae9/0.0.0/f4e89e8750d5d5ffbef2c078bf0ddfedef29dc2faff52a6255cf513c05eb1092/cache-f043ed385cafdf91.arrow
Loading cached processed dataset at /home/matthias/.cache/huggingface/datasets/json/default-ad8f542b20e92ae9/0.0.0/f4e89e8750d5d5ffbef2c078bf0ddfedef29dc2faff52a6255cf513c05eb1092/cache-3f61622913b6fa1b.arrow

total items:		3000
closed items:		2335
closed issues:		984
closed pull requests:	1351
average duration until closing for GitHub issues:		33d 4h:21m:24s
average duration until closing for GitHub pull requests:	12d 1h:53m:39s

Although we could proceed to further clean up the dataset by dropping or renaming some columns, it is generally a good practice to keep the dataset as "raw" as possible at this stage so that it can be easily used in multiple applications.

Before we push our dataset to the Hugging Face Hub, let's deal with one thing that's missing from it: the comments associated with each issue and pull request. We'll add them next with — you guessed it — the GitHub REST API!

### Augmenting the dataset

As shown in the following screenshot, the comments associated with an issue or pull request provide a rich source of information, especially if we're interested in building a search engine to answer user queries about the library.

<img style="float=center;" width="85%" src="sections/section_5/images/adding_a_dataset.png">

The GitHub REST API provides a [`Comments` endpoint](https://docs.github.com/en/rest/reference/issues#list-issue-comments) that returns all the comments associated with an issue number. Let's test the endpoint to see what it returns:

In [119]:
issue_number = 2792
url = f"https://api.github.com/repos/huggingface/datasets/issues/{issue_number}/comments"
response = requests.get(url, headers=headers)
response.json()

[{'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/897594128',
  'html_url': 'https://github.com/huggingface/datasets/pull/2792#issuecomment-897594128',
  'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/2792',
  'id': 897594128,
  'node_id': 'IC_kwDODunzps41gDMQ',
  'user': {'login': 'bhavitvyamalik',
   'id': 19718818,
   'node_id': 'MDQ6VXNlcjE5NzE4ODE4',
   'avatar_url': 'https://avatars.githubusercontent.com/u/19718818?v=4',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/bhavitvyamalik',
   'html_url': 'https://github.com/bhavitvyamalik',
   'followers_url': 'https://api.github.com/users/bhavitvyamalik/followers',
   'following_url': 'https://api.github.com/users/bhavitvyamalik/following{/other_user}',
   'gists_url': 'https://api.github.com/users/bhavitvyamalik/gists{/gist_id}',
   'starred_url': 'https://api.github.com/users/bhavitvyamalik/starred{/owner}{/repo}',
   'subscriptions_url': 'https://api.github.com/users/bhavitvyamalik/subscriptions',
   'organizations_url': 'https://api.github.com/users/bhavitvyamalik/orgs',
   'repos_url': 'https://api.github.com/users/bhavitvyamalik/repos',
   'events_url': 'https://api.github.com/users/bhavitvyamalik/events{/privacy}',
   'received_events_url': 'https://api.github.com/users/bhavitvyamalik/received_events',
   'type': 'User',
   'user_view_type': 'public',
   'site_admin': False},
  'created_at': '2021-08-12T12:21:52Z',
  'updated_at': '2021-08-12T12:31:17Z',
  'author_association': 'CONTRIBUTOR',
  'body': "@albertvillanova my tests are failing here:\r\n```\r\ndataset_name = 'gooaq'\r\n\r\n    def test_load_dataset(self, dataset_name):\r\n        configs = self.dataset_tester.load_all_configs(dataset_name, is_local=True)[:1]\r\n>       self.dataset_tester.check_load_dataset(dataset_name, configs, is_local=True, use_local_dummy_data=True)\r\n\r\ntests/test_dataset_common.py:234: \r\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \r\ntests/test_dataset_common.py:187: in check_load_dataset\r\n    self.parent.assertTrue(len(dataset[split]) > 0)\r\nE   AssertionError: False is not true\r\n```\r\nWhen I try loading dataset on local machine it works fine. Any suggestions on how can I avoid this error?",
  'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/897594128/reactions',
   'total_count': 0,
   '+1': 0,
   '-1': 0,
   'laugh': 0,
   'hooray': 0,
   'confused': 0,
   'heart': 0,
   'rocket': 0,
   'eyes': 0},
  'performed_via_github_app': None},
 {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/898644889',
  'html_url': 'https://github.com/huggingface/datasets/pull/2792#issuecomment-898644889',
  'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/2792',
  'id': 898644889,
  'node_id': 'IC_kwDODunzps41kDuZ',
  'user': {'login': 'bhavitvyamalik',
   'id': 19718818,
   'node_id': 'MDQ6VXNlcjE5NzE4ODE4',
   'avatar_url': 'https://avatars.githubusercontent.com/u/19718818?v=4',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/bhavitvyamalik',
   'html_url': 'https://github.com/bhavitvyamalik',
   'followers_url': 'https://api.github.com/users/bhavitvyamalik/followers',
   'following_url': 'https://api.github.com/users/bhavitvyamalik/following{/other_user}',
   'gists_url': 'https://api.github.com/users/bhavitvyamalik/gists{/gist_id}',
   'starred_url': 'https://api.github.com/users/bhavitvyamalik/starred{/owner}{/repo}',
   'subscriptions_url': 'https://api.github.com/users/bhavitvyamalik/subscriptions',
   'organizations_url': 'https://api.github.com/users/bhavitvyamalik/orgs',
   'repos_url': 'https://api.github.com/users/bhavitvyamalik/repos',
   'events_url': 'https://api.github.com/users/bhavitvyamalik/events{/privacy}',
   'received_events_url': 'https://api.github.com/users/bhavitvyamalik/received_events',
   'type': 'User',
   'user_view_type': 'public',
   'site_admin': False},
  'created_at': '2021-08-13T18:28:27Z',
  'updated_at': '2021-08-13T18:28:27Z',
  'author_association': 'CONTRIBUTOR',
  'body': 'Thanks for the help, @albertvillanova! All tests are passing now.',
  'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/898644889/reactions',
   'total_count': 0,
   '+1': 0,
   '-1': 0,
   'laugh': 0,
   'hooray': 0,
   'confused': 0,
   'heart': 0,
   'rocket': 0,
   'eyes': 0},
  'performed_via_github_app': None}]

We can see that the comment is stored in the `body` field, so let's write a simple function that returns all the comments associated with an issue by picking out the `body` contents for each element in `response.json()`:

In [120]:
def get_comments(issue_number):
    url = f"https://api.github.com/repos/huggingface/datasets/issues/{issue_number}/comments"
    response = requests.get(url, headers=headers)
    return [r["body"] for r in response.json()]

# Test our function works as expected
get_comments(2792)

["@albertvillanova my tests are failing here:\r\n```\r\ndataset_name = 'gooaq'\r\n\r\n    def test_load_dataset(self, dataset_name):\r\n        configs = self.dataset_tester.load_all_configs(dataset_name, is_local=True)[:1]\r\n>       self.dataset_tester.check_load_dataset(dataset_name, configs, is_local=True, use_local_dummy_data=True)\r\n\r\ntests/test_dataset_common.py:234: \r\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \r\ntests/test_dataset_common.py:187: in check_load_dataset\r\n    self.parent.assertTrue(len(dataset[split]) > 0)\r\nE   AssertionError: False is not true\r\n```\r\nWhen I try loading dataset on local machine it works fine. Any suggestions on how can I avoid this error?",
 'Thanks for the help, @albertvillanova! All tests are passing now.']

This looks good, so let's use `Dataset.map()` to add a new `comments` column to each issue in our dataset:

In [121]:
%%time
# Depending on your internet connection, this can take quite some time.
# And due to the GitHub API's rate limit, it might take several minutes to just see any progress, at all!
issues_with_comments_dataset = issues_dataset.map(lambda x: {"comments": get_comments(x["number"])})
issues_with_comments_dataset

Map:   0%|          | 0/3000 [00:00<?, ? examples/s]

Caching processed dataset at /home/matthias/.cache/huggingface/datasets/json/default-ad8f542b20e92ae9/0.0.0/f4e89e8750d5d5ffbef2c078bf0ddfedef29dc2faff52a6255cf513c05eb1092/cache-8159dbb3d5aba2e0.arrow

ConnectTimeout: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/huggingface/datasets/issues/7461/comments (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7a264144f590>, 'Connection to api.github.com timed out. (connect timeout=None)'))

[{'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1622320308', 'html_url': 'https://github.com/huggingface/datasets/issues/6008#issuecomment-1622320308', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/6008', 'id': 1622320308, 'node_id': 'IC_kwDODunzps5gsqS0', 'user': {'login': 'mariosasko', 'id': 47462742, 'node_id': 'MDQ6VXNlcjQ3NDYyNzQy', 'avatar_url': 'https://avatars.githubusercontent.com/u/47462742?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/mariosasko', 'html_url': 'https://github.com/mariosasko', 'followers_url': 'https://api.github.com/users/mariosasko/followers', 'following_url': 'https://api.github.com/users/mariosasko/following{/other_user}', 'gists_url': 'https://api.github.com/users/mariosasko/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/mariosasko/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/mariosasko/subscriptions', 'organizations_url': 'https://api.github.com/users/mariosasko/orgs', 'repos_url': 'https://api.github.com/users/mariosasko/repos', 'events_url': 'https://api.github.com/users/mariosasko/events{/privacy}', 'received_events_url': 'https://api.github.com/users/mariosasko/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-07-05T19:09:38Z', 'updated_at': '2023-07-05T19:09:38Z', 'author_association': 'CONTRIBUTOR', 'body': 'By default, we write data to disk (so it can be memory-mapped) every 1000 rows/samples. You can control this with the `writer_batch_size` parameter. Also, when working with fixed-size arrays, the `ArrayXD` feature types yield better performance (e.g., in your case, `features=datasets.Features({"i": datasets.Array3D(shape=(512,512,3), dtype="float32")})` should be faster).\r\n\r\nOur support for multi-dim arrays could be better, and we plan to improve it as part of https://github.com/huggingface/datasets/issues/5272.', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1622320308/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1622567452', 'html_url': 'https://github.com/huggingface/datasets/issues/6008#issuecomment-1622567452', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/6008', 'id': 1622567452, 'node_id': 'IC_kwDODunzps5gtmoc', 'user': {'login': 'andreemic', 'id': 27695722, 'node_id': 'MDQ6VXNlcjI3Njk1NzIy', 'avatar_url': 'https://avatars.githubusercontent.com/u/27695722?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/andreemic', 'html_url': 'https://github.com/andreemic', 'followers_url': 'https://api.github.com/users/andreemic/followers', 'following_url': 'https://api.github.com/users/andreemic/following{/other_user}', 'gists_url': 'https://api.github.com/users/andreemic/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/andreemic/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/andreemic/subscriptions', 'organizations_url': 'https://api.github.com/users/andreemic/orgs', 'repos_url': 'https://api.github.com/users/andreemic/repos', 'events_url': 'https://api.github.com/users/andreemic/events{/privacy}', 'received_events_url': 'https://api.github.com/users/andreemic/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-07-05T21:44:33Z', 'updated_at': '2023-07-05T21:44:33Z', 'author_association': 'NONE', 'body': '> By default, we write data to disk (so it can be memory-mapped) every 1000 rows/samples. You can control this with the `writer_batch_size` parameter. Also, when working with fixed-size arrays, the `ArrayXD` feature types yield better performance (e.g., in your case, `features=datasets.Features({"i": datasets.Array3D(shape=(512,512,3), dtype="float32")})` should be faster).\r\n> \r\n> Our support for multi-dim arrays could be better, and we plan to improve it as part of #5272.\r\n\r\nThanks for the explanation! The Image array was just for demonstration, I use PIL Images in practice. Does that make a difference? What\'s the best approach for a dataset with PIL Images as rows?', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1622567452/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1623972849', 'html_url': 'https://github.com/huggingface/datasets/issues/6008#issuecomment-1623972849', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/6008', 'id': 1623972849, 'node_id': 'IC_kwDODunzps5gy9vx', 'user': {'login': 'mariosasko', 'id': 47462742, 'node_id': 'MDQ6VXNlcjQ3NDYyNzQy', 'avatar_url': 'https://avatars.githubusercontent.com/u/47462742?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/mariosasko', 'html_url': 'https://github.com/mariosasko', 'followers_url': 'https://api.github.com/users/mariosasko/followers', 'following_url': 'https://api.github.com/users/mariosasko/following{/other_user}', 'gists_url': 'https://api.github.com/users/mariosasko/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/mariosasko/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/mariosasko/subscriptions', 'organizations_url': 'https://api.github.com/users/mariosasko/orgs', 'repos_url': 'https://api.github.com/users/mariosasko/repos', 'events_url': 'https://api.github.com/users/mariosasko/events{/privacy}', 'received_events_url': 'https://api.github.com/users/mariosasko/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-07-06T16:29:25Z', 'updated_at': '2023-07-06T16:32:02Z', 'author_association': 'CONTRIBUTOR', 'body': "It's best to use the `datasets.Image()` feature type for PIL images (to save space) :)", 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1623972849/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}]

[{'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1621109784', 'html_url': 'https://github.com/huggingface/datasets/issues/6006#issuecomment-1621109784', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/6006', 'id': 1621109784, 'node_id': 'IC_kwDODunzps5goCwY', 'user': {'login': 'xipq', 'id': 115634163, 'node_id': 'U_kgDOBuRv8w', 'avatar_url': 'https://avatars.githubusercontent.com/u/115634163?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/xipq', 'html_url': 'https://github.com/xipq', 'followers_url': 'https://api.github.com/users/xipq/followers', 'following_url': 'https://api.github.com/users/xipq/following{/other_user}', 'gists_url': 'https://api.github.com/users/xipq/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/xipq/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/xipq/subscriptions', 'organizations_url': 'https://api.github.com/users/xipq/orgs', 'repos_url': 'https://api.github.com/users/xipq/repos', 'events_url': 'https://api.github.com/users/xipq/events{/privacy}', 'received_events_url': 'https://api.github.com/users/xipq/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-07-05T06:31:01Z', 'updated_at': '2023-07-05T06:31:01Z', 'author_association': 'NONE', 'body': 'issue due to corrupted download files. resolved after cleaning download cache. sorry for any inconvinence.', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1621109784/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}]

[{'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1618983451', 'html_url': 'https://github.com/huggingface/datasets/pull/6004#issuecomment-1618983451', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/6004', 'id': 1618983451, 'node_id': 'IC_kwDODunzps5gf7ob', 'user': {'login': 'github-actions[bot]', 'id': 41898282, 'node_id': 'MDM6Qm90NDE4OTgyODI=', 'avatar_url': 'https://avatars.githubusercontent.com/in/15368?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/github-actions%5Bbot%5D', 'html_url': 'https://github.com/apps/github-actions', 'followers_url': 'https://api.github.com/users/github-actions%5Bbot%5D/followers', 'following_url': 'https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}', 'gists_url': 'https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/github-actions%5Bbot%5D/subscriptions', 'organizations_url': 'https://api.github.com/users/github-actions%5Bbot%5D/orgs', 'repos_url': 'https://api.github.com/users/github-actions%5Bbot%5D/repos', 'events_url': 'https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}', 'received_events_url': 'https://api.github.com/users/github-actions%5Bbot%5D/received_events', 'type': 'Bot', 'site_admin': False}, 'created_at': '2023-07-03T18:29:33Z', 'updated_at': '2023-07-03T18:29:33Z', 'author_association': 'NONE', 'body': '<details>\n<summary>Show benchmarks</summary>\n\nPyArrow==8.0.0\n\n<details>\n<summary>Show updated benchmarks!</summary>\n\n### Benchmark: benchmark_array_xd.json\n\n| metric | read_batch_formatted_as_numpy after write_array2d | read_batch_formatted_as_numpy after write_flattened_sequence | read_batch_formatted_as_numpy after write_nested_sequence | read_batch_unformated after write_array2d | read_batch_unformated after write_flattened_sequence | read_batch_unformated after write_nested_sequence | read_col_formatted_as_numpy after write_array2d | read_col_formatted_as_numpy after write_flattened_sequence | read_col_formatted_as_numpy after write_nested_sequence | read_col_unformated after write_array2d | read_col_unformated after write_flattened_sequence | read_col_unformated after write_nested_sequence | read_formatted_as_numpy after write_array2d | read_formatted_as_numpy after write_flattened_sequence | read_formatted_as_numpy after write_nested_sequence | read_unformated after write_array2d | read_unformated after write_flattened_sequence | read_unformated after write_nested_sequence | write_array2d | write_flattened_sequence | write_nested_sequence |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.006897 / 0.011353 (-0.004456) | 0.004207 / 0.011008 (-0.006802) | 0.104828 / 0.038508 (0.066320) | 0.048054 / 0.023109 (0.024945) | 0.373991 / 0.275898 (0.098093) | 0.426740 / 0.323480 (0.103260) | 0.005540 / 0.007986 (-0.002446) | 0.003531 / 0.004328 (-0.000797) | 0.079304 / 0.004250 (0.075053) | 0.066996 / 0.037052 (0.029944) | 0.370675 / 0.258489 (0.112186) | 0.414154 / 0.293841 (0.120313) | 0.031567 / 0.128546 (-0.096979) | 0.008843 / 0.075646 (-0.066803) | 0.357426 / 0.419271 (-0.061845) | 0.067040 / 0.043533 (0.023508) | 0.362384 / 0.255139 (0.107245) | 0.376056 / 0.283200 (0.092856) | 0.032985 / 0.141683 (-0.108697) | 1.560603 / 1.452155 (0.108448) | 1.619024 / 1.492716 (0.126308) |\n\n### Benchmark: benchmark_getitem\\_100B.json\n\n| metric | get_batch_of\\_1024\\_random_rows | get_batch_of\\_1024\\_rows | get_first_row | get_last_row |\n|--------|---|---|---|---|\n| new / old (diff) | 0.229059 / 0.018006 (0.211053) | 0.440513 / 0.000490 (0.440023) | 0.004647 / 0.000200 (0.004447) | 0.000085 / 0.000054 (0.000030) |\n\n### Benchmark: benchmark_indices_mapping.json\n\n| metric | select | shard | shuffle | sort | train_test_split |\n|--------|---|---|---|---|---|\n| new / old (diff) | 0.029517 / 0.037411 (-0.007894) | 0.120974 / 0.014526 (0.106448) | 0.125070 / 0.176557 (-0.051486) | 0.184695 / 0.737135 (-0.552441) | 0.130244 / 0.296338 (-0.166095) |\n\n### Benchmark: benchmark_iterating.json\n\n| metric | read 5000 | read 50000 | read_batch 50000 10 | read_batch 50000 100 | read_batch 50000 1000 | read_formatted numpy 5000 | read_formatted pandas 5000 | read_formatted tensorflow 5000 | read_formatted torch 5000 | read_formatted_batch numpy 5000 10 | read_formatted_batch numpy 5000 1000 | shuffled read 5000 | shuffled read 50000 | shuffled read_batch 50000 10 | shuffled read_batch 50000 100 | shuffled read_batch 50000 1000 | shuffled read_formatted numpy 5000 | shuffled read_formatted_batch numpy 5000 10 | shuffled read_formatted_batch numpy 5000 1000 |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.436930 / 0.215209 (0.221721) | 4.356118 / 2.077655 (2.278463) | 2.049169 / 1.504120 (0.545049) | 1.842898 / 1.541195 (0.301703) | 1.918948 / 1.468490 (0.450458) | 0.553573 / 4.584777 (-4.031204) | 3.883195 / 3.745712 (0.137483) | 3.209780 / 5.269862 (-2.060081) | 1.551707 / 4.565676 (-3.013970) | 0.068181 / 0.424275 (-0.356094) | 0.012370 / 0.007607 (0.004762) | 0.539899 / 0.226044 (0.313854) | 5.380008 / 2.268929 (3.111079) | 2.518178 / 55.444624 (-52.926446) | 2.174190 / 6.876477 (-4.702286) | 2.317812 / 2.142072 (0.175740) | 0.674154 / 4.805227 (-4.131073) | 0.149313 / 6.500664 (-6.351351) | 0.068297 / 0.075469 (-0.007172) |\n\n### Benchmark: benchmark_map_filter.json\n\n| metric | filter | map fast-tokenizer batched | map identity | map identity batched | map no-op batched | map no-op batched numpy | map no-op batched pandas | map no-op batched pytorch | map no-op batched tensorflow |\n|--------|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 1.261426 / 1.841788 (-0.580362) | 15.316378 / 8.074308 (7.242070) | 13.573512 / 10.191392 (3.382120) | 0.190022 / 0.680424 (-0.490401) | 0.018697 / 0.534201 (-0.515504) | 0.448122 / 0.579283 (-0.131161) | 0.435044 / 0.434364 (0.000681) | 0.550065 / 0.540337 (0.009728) | 0.653547 / 1.386936 (-0.733389) |\n\n</details>\nPyArrow==latest\n\n<details>\n<summary>Show updated benchmarks!</summary>\n\n### Benchmark: benchmark_array_xd.json\n\n| metric | read_batch_formatted_as_numpy after write_array2d | read_batch_formatted_as_numpy after write_flattened_sequence | read_batch_formatted_as_numpy after write_nested_sequence | read_batch_unformated after write_array2d | read_batch_unformated after write_flattened_sequence | read_batch_unformated after write_nested_sequence | read_col_formatted_as_numpy after write_array2d | read_col_formatted_as_numpy after write_flattened_sequence | read_col_formatted_as_numpy after write_nested_sequence | read_col_unformated after write_array2d | read_col_unformated after write_flattened_sequence | read_col_unformated after write_nested_sequence | read_formatted_as_numpy after write_array2d | read_formatted_as_numpy after write_flattened_sequence | read_formatted_as_numpy after write_nested_sequence | read_unformated after write_array2d | read_unformated after write_flattened_sequence | read_unformated after write_nested_sequence | write_array2d | write_flattened_sequence | write_nested_sequence |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.007116 / 0.011353 (-0.004237) | 0.004375 / 0.011008 (-0.006633) | 0.081793 / 0.038508 (0.043285) | 0.047980 / 0.023109 (0.024871) | 0.392185 / 0.275898 (0.116287) | 0.462263 / 0.323480 (0.138783) | 0.005574 / 0.007986 (-0.002412) | 0.003552 / 0.004328 (-0.000776) | 0.080413 / 0.004250 (0.076162) | 0.065539 / 0.037052 (0.028487) | 0.413137 / 0.258489 (0.154648) | 0.467377 / 0.293841 (0.173536) | 0.034386 / 0.128546 (-0.094160) | 0.009183 / 0.075646 (-0.066464) | 0.087542 / 0.419271 (-0.331730) | 0.053954 / 0.043533 (0.010421) | 0.385096 / 0.255139 (0.129957) | 0.404900 / 0.283200 (0.121701) | 0.025908 / 0.141683 (-0.115775) | 1.550159 / 1.452155 (0.098005) | 1.598794 / 1.492716 (0.106078) |\n\n### Benchmark: benchmark_getitem\\_100B.json\n\n| metric | get_batch_of\\_1024\\_random_rows | get_batch_of\\_1024\\_rows | get_first_row | get_last_row |\n|--------|---|---|---|---|\n| new / old (diff) | 0.246222 / 0.018006 (0.228216) | 0.441095 / 0.000490 (0.440605) | 0.006863 / 0.000200 (0.006663) | 0.000109 / 0.000054 (0.000055) |\n\n### Benchmark: benchmark_indices_mapping.json\n\n| metric | select | shard | shuffle | sort | train_test_split |\n|--------|---|---|---|---|---|\n| new / old (diff) | 0.032179 / 0.037411 (-0.005233) | 0.120112 / 0.014526 (0.105586) | 0.129326 / 0.176557 (-0.047230) | 0.184542 / 0.737135 (-0.552593) | 0.135038 / 0.296338 (-0.161300) |\n\n### Benchmark: benchmark_iterating.json\n\n| metric | read 5000 | read 50000 | read_batch 50000 10 | read_batch 50000 100 | read_batch 50000 1000 | read_formatted numpy 5000 | read_formatted pandas 5000 | read_formatted tensorflow 5000 | read_formatted torch 5000 | read_formatted_batch numpy 5000 10 | read_formatted_batch numpy 5000 1000 | shuffled read 5000 | shuffled read 50000 | shuffled read_batch 50000 10 | shuffled read_batch 50000 100 | shuffled read_batch 50000 1000 | shuffled read_formatted numpy 5000 | shuffled read_formatted_batch numpy 5000 10 | shuffled read_formatted_batch numpy 5000 1000 |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.459002 / 0.215209 (0.243793) | 4.580258 / 2.077655 (2.502604) | 2.296689 / 1.504120 (0.792569) | 2.104338 / 1.541195 (0.563143) | 2.182896 / 1.468490 (0.714406) | 0.546447 / 4.584777 (-4.038330) | 3.854047 / 3.745712 (0.108335) | 1.873829 / 5.269862 (-3.396032) | 1.116484 / 4.565676 (-3.449193) | 0.067158 / 0.424275 (-0.357117) | 0.012035 / 0.007607 (0.004428) | 0.556642 / 0.226044 (0.330597) | 5.574436 / 2.268929 (3.305508) | 2.828223 / 55.444624 (-52.616402) | 2.519851 / 6.876477 (-4.356626) | 2.668594 / 2.142072 (0.526521) | 0.675989 / 4.805227 (-4.129238) | 0.146075 / 6.500664 (-6.354589) | 0.067788 / 0.075469 (-0.007681) |\n\n### Benchmark: benchmark_map_filter.json\n\n| metric | filter | map fast-tokenizer batched | map identity | map identity batched | map no-op batched | map no-op batched numpy | map no-op batched pandas | map no-op batched pytorch | map no-op batched tensorflow |\n|--------|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 1.345958 / 1.841788 (-0.495830) | 15.672748 / 8.074308 (7.598440) | 14.937583 / 10.191392 (4.746191) | 0.163479 / 0.680424 (-0.516945) | 0.018364 / 0.534201 (-0.515837) | 0.433296 / 0.579283 (-0.145987) | 0.432463 / 0.434364 (-0.001901) | 0.512000 / 0.540337 (-0.028338) | 0.619397 / 1.386936 (-0.767539) |\n\n</details>\n</details>\n\n![](https://cml.dev/watermark.png#0832d48a07ed00b406271f4b4439e6d54ae38ebf "CML watermark")\n', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1618983451/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1618987509', 'html_url': 'https://github.com/huggingface/datasets/pull/6004#issuecomment-1618987509', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/6004', 'id': 1618987509, 'node_id': 'IC_kwDODunzps5gf8n1', 'user': {'login': 'HuggingFaceDocBuilderDev', 'id': 99929124, 'node_id': 'U_kgDOBfTMJA', 'avatar_url': 'https://avatars.githubusercontent.com/u/99929124?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/HuggingFaceDocBuilderDev', 'html_url': 'https://github.com/HuggingFaceDocBuilderDev', 'followers_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/followers', 'following_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/following{/other_user}', 'gists_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/subscriptions', 'organizations_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/orgs', 'repos_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/repos', 'events_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/events{/privacy}', 'received_events_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-07-03T18:34:20Z', 'updated_at': '2023-07-06T16:55:54Z', 'author_association': 'NONE', 'body': '_The documentation is not available anymore as the PR was closed or merged._', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1618987509/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1623981849', 'html_url': 'https://github.com/huggingface/datasets/pull/6004#issuecomment-1623981849', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/6004', 'id': 1623981849, 'node_id': 'IC_kwDODunzps5gy_8Z', 'user': {'login': 'github-actions[bot]', 'id': 41898282, 'node_id': 'MDM6Qm90NDE4OTgyODI=', 'avatar_url': 'https://avatars.githubusercontent.com/in/15368?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/github-actions%5Bbot%5D', 'html_url': 'https://github.com/apps/github-actions', 'followers_url': 'https://api.github.com/users/github-actions%5Bbot%5D/followers', 'following_url': 'https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}', 'gists_url': 'https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/github-actions%5Bbot%5D/subscriptions', 'organizations_url': 'https://api.github.com/users/github-actions%5Bbot%5D/orgs', 'repos_url': 'https://api.github.com/users/github-actions%5Bbot%5D/repos', 'events_url': 'https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}', 'received_events_url': 'https://api.github.com/users/github-actions%5Bbot%5D/received_events', 'type': 'Bot', 'site_admin': False}, 'created_at': '2023-07-06T16:36:53Z', 'updated_at': '2023-07-06T16:36:53Z', 'author_association': 'NONE', 'body': '<details>\n<summary>Show benchmarks</summary>\n\nPyArrow==8.0.0\n\n<details>\n<summary>Show updated benchmarks!</summary>\n\n### Benchmark: benchmark_array_xd.json\n\n| metric | read_batch_formatted_as_numpy after write_array2d | read_batch_formatted_as_numpy after write_flattened_sequence | read_batch_formatted_as_numpy after write_nested_sequence | read_batch_unformated after write_array2d | read_batch_unformated after write_flattened_sequence | read_batch_unformated after write_nested_sequence | read_col_formatted_as_numpy after write_array2d | read_col_formatted_as_numpy after write_flattened_sequence | read_col_formatted_as_numpy after write_nested_sequence | read_col_unformated after write_array2d | read_col_unformated after write_flattened_sequence | read_col_unformated after write_nested_sequence | read_formatted_as_numpy after write_array2d | read_formatted_as_numpy after write_flattened_sequence | read_formatted_as_numpy after write_nested_sequence | read_unformated after write_array2d | read_unformated after write_flattened_sequence | read_unformated after write_nested_sequence | write_array2d | write_flattened_sequence | write_nested_sequence |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.010097 / 0.011353 (-0.001256) | 0.005070 / 0.011008 (-0.005939) | 0.118638 / 0.038508 (0.080130) | 0.043651 / 0.023109 (0.020542) | 0.356074 / 0.275898 (0.080176) | 0.414578 / 0.323480 (0.091098) | 0.005939 / 0.007986 (-0.002046) | 0.004927 / 0.004328 (0.000598) | 0.089545 / 0.004250 (0.085294) | 0.067533 / 0.037052 (0.030481) | 0.371550 / 0.258489 (0.113061) | 0.417808 / 0.293841 (0.123967) | 0.045186 / 0.128546 (-0.083361) | 0.015763 / 0.075646 (-0.059883) | 0.393304 / 0.419271 (-0.025967) | 0.065123 / 0.043533 (0.021591) | 0.345057 / 0.255139 (0.089918) | 0.378809 / 0.283200 (0.095610) | 0.033243 / 0.141683 (-0.108440) | 1.679956 / 1.452155 (0.227802) | 1.775456 / 1.492716 (0.282739) |\n\n### Benchmark: benchmark_getitem\\_100B.json\n\n| metric | get_batch_of\\_1024\\_random_rows | get_batch_of\\_1024\\_rows | get_first_row | get_last_row |\n|--------|---|---|---|---|\n| new / old (diff) | 0.229723 / 0.018006 (0.211717) | 0.554630 / 0.000490 (0.554140) | 0.008729 / 0.000200 (0.008529) | 0.000183 / 0.000054 (0.000129) |\n\n### Benchmark: benchmark_indices_mapping.json\n\n| metric | select | shard | shuffle | sort | train_test_split |\n|--------|---|---|---|---|---|\n| new / old (diff) | 0.027284 / 0.037411 (-0.010128) | 0.114741 / 0.014526 (0.100215) | 0.129188 / 0.176557 (-0.047369) | 0.189270 / 0.737135 (-0.547866) | 0.126000 / 0.296338 (-0.170339) |\n\n### Benchmark: benchmark_iterating.json\n\n| metric | read 5000 | read 50000 | read_batch 50000 10 | read_batch 50000 100 | read_batch 50000 1000 | read_formatted numpy 5000 | read_formatted pandas 5000 | read_formatted tensorflow 5000 | read_formatted torch 5000 | read_formatted_batch numpy 5000 10 | read_formatted_batch numpy 5000 1000 | shuffled read 5000 | shuffled read 50000 | shuffled read_batch 50000 10 | shuffled read_batch 50000 100 | shuffled read_batch 50000 1000 | shuffled read_formatted numpy 5000 | shuffled read_formatted_batch numpy 5000 10 | shuffled read_formatted_batch numpy 5000 1000 |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.580417 / 0.215209 (0.365208) | 5.829337 / 2.077655 (3.751683) | 2.421191 / 1.504120 (0.917071) | 2.063673 / 1.541195 (0.522479) | 2.133427 / 1.468490 (0.664937) | 0.830964 / 4.584777 (-3.753813) | 5.107139 / 3.745712 (1.361427) | 4.599451 / 5.269862 (-0.670410) | 2.406502 / 4.565676 (-2.159175) | 0.100422 / 0.424275 (-0.323853) | 0.011850 / 0.007607 (0.004243) | 0.741881 / 0.226044 (0.515836) | 7.425689 / 2.268929 (5.156760) | 3.068948 / 55.444624 (-52.375676) | 2.496292 / 6.876477 (-4.380184) | 2.566420 / 2.142072 (0.424348) | 1.093084 / 4.805227 (-3.712144) | 0.224106 / 6.500664 (-6.276558) | 0.084549 / 0.075469 (0.009080) |\n\n### Benchmark: benchmark_map_filter.json\n\n| metric | filter | map fast-tokenizer batched | map identity | map identity batched | map no-op batched | map no-op batched numpy | map no-op batched pandas | map no-op batched pytorch | map no-op batched tensorflow |\n|--------|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 1.416315 / 1.841788 (-0.425473) | 16.306901 / 8.074308 (8.232593) | 19.792419 / 10.191392 (9.601027) | 0.224223 / 0.680424 (-0.456201) | 0.026385 / 0.534201 (-0.507816) | 0.463460 / 0.579283 (-0.115823) | 0.598385 / 0.434364 (0.164021) | 0.543981 / 0.540337 (0.003644) | 0.647454 / 1.386936 (-0.739482) |\n\n</details>\nPyArrow==latest\n\n<details>\n<summary>Show updated benchmarks!</summary>\n\n### Benchmark: benchmark_array_xd.json\n\n| metric | read_batch_formatted_as_numpy after write_array2d | read_batch_formatted_as_numpy after write_flattened_sequence | read_batch_formatted_as_numpy after write_nested_sequence | read_batch_unformated after write_array2d | read_batch_unformated after write_flattened_sequence | read_batch_unformated after write_nested_sequence | read_col_formatted_as_numpy after write_array2d | read_col_formatted_as_numpy after write_flattened_sequence | read_col_formatted_as_numpy after write_nested_sequen

[]
[{'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1618685937', 'html_url': 'https://github.com/huggingface/datasets/pull/6002#issuecomment-1618685937', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/6002', 'id': 1618685937, 'node_id': 'IC_kwDODunzps5gey_x', 'user': {'login': 'mariosasko', 'id': 47462742, 'node_id': 'MDQ6VXNlcjQ3NDYyNzQy', 'avatar_url': 'https://avatars.githubusercontent.com/u/47462742?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/mariosasko', 'html_url': 'https://github.com/mariosasko', 'followers_url': 'https://api.github.com/users/mariosasko/followers', 'following_url': 'https://api.github.com/users/mariosasko/following{/other_user}', 'gists_url': 'https://api.github.com/users/mariosasko/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/mariosasko/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/mariosasko/subscriptions', 'organizations_url': 'https://api.github.com/users/mariosasko/orgs', 'repos_url': 'https://api.github.com/users/mariosasko/repos', 'events_url': 'https://api.github.com/users/mariosasko/events{/privacy}', 'received_events_url': 'https://api.github.com/users/mariosasko/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-07-03T15:34:17Z', 'updated_at': '2023-07-03T15:34:17Z', 'author_association': 'CONTRIBUTOR', 'body': 'The metrics API in `datasets` is deprecated as of version 2.0, and `evaulate` is our new library for metrics. You can add a new metric to it by following [these steps](https://huggingface.co/docs/evaluate/creating_and_sharing).', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1618685937/reactions', 'total_count': 1, '+1': 1, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}]

[{'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1614599163', 'html_url': 'https://github.com/huggingface/datasets/pull/6000#issuecomment-1614599163', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/6000', 'id': 1614599163, 'node_id': 'IC_kwDODunzps5gPNP7', 'user': {'login': 'github-actions[bot]', 'id': 41898282, 'node_id': 'MDM6Qm90NDE4OTgyODI=', 'avatar_url': 'https://avatars.githubusercontent.com/in/15368?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/github-actions%5Bbot%5D', 'html_url': 'https://github.com/apps/github-actions', 'followers_url': 'https://api.github.com/users/github-actions%5Bbot%5D/followers', 'following_url': 'https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}', 'gists_url': 'https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/github-actions%5Bbot%5D/subscriptions', 'organizations_url': 'https://api.github.com/users/github-actions%5Bbot%5D/orgs', 'repos_url': 'https://api.github.com/users/github-actions%5Bbot%5D/repos', 'events_url': 'https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}', 'received_events_url': 'https://api.github.com/users/github-actions%5Bbot%5D/received_events', 'type': 'Bot', 'site_admin': False}, 'created_at': '2023-06-30T12:43:32Z', 'updated_at': '2023-06-30T12:43:32Z', 'author_association': 'NONE', 'body': '<details>\n<summary>Show benchmarks</summary>\n\nPyArrow==8.0.0\n\n<details>\n<summary>Show updated benchmarks!</summary>\n\n### Benchmark: benchmark_array_xd.json\n\n| metric | read_batch_formatted_as_numpy after write_array2d | read_batch_formatted_as_numpy after write_flattened_sequence | read_batch_formatted_as_numpy after write_nested_sequence | read_batch_unformated after write_array2d | read_batch_unformated after write_flattened_sequence | read_batch_unformated after write_nested_sequence | read_col_formatted_as_numpy after write_array2d | read_col_formatted_as_numpy after write_flattened_sequence | read_col_formatted_as_numpy after write_nested_sequence | read_col_unformated after write_array2d | read_col_unformated after write_flattened_sequence | read_col_unformated after write_nested_sequence | read_formatted_as_numpy after write_array2d | read_formatted_as_numpy after write_flattened_sequence | read_formatted_as_numpy after write_nested_sequence | read_unformated after write_array2d | read_unformated after write_flattened_sequence | read_unformated after write_nested_sequence | write_array2d | write_flattened_sequence | write_nested_sequence |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.006722 / 0.011353 (-0.004631) | 0.004425 / 0.011008 (-0.006583) | 0.100850 / 0.038508 (0.062341) | 0.040816 / 0.023109 (0.017707) | 0.348823 / 0.275898 (0.072925) | 0.446285 / 0.323480 (0.122805) | 0.005738 / 0.007986 (-0.002247) | 0.003517 / 0.004328 (-0.000811) | 0.078824 / 0.004250 (0.074574) | 0.064695 / 0.037052 (0.027643) | 0.389894 / 0.258489 (0.131405) | 0.416107 / 0.293841 (0.122266) | 0.028850 / 0.128546 (-0.099696) | 0.009011 / 0.075646 (-0.066635) | 0.323117 / 0.419271 (-0.096154) | 0.049162 / 0.043533 (0.005629) | 0.340144 / 0.255139 (0.085005) | 0.382072 / 0.283200 (0.098872) | 0.023160 / 0.141683 (-0.118523) | 1.549218 / 1.452155 (0.097063) | 1.581266 / 1.492716 (0.088550) |\n\n### Benchmark: benchmark_getitem\\_100B.json\n\n| metric | get_batch_of\\_1024\\_random_rows | get_batch_of\\_1024\\_rows | get_first_row | get_last_row |\n|--------|---|---|---|---|\n| new / old (diff) | 0.293360 / 0.018006 (0.275353) | 0.602189 / 0.000490 (0.601700) | 0.004608 / 0.000200 (0.004408) | 0.000082 / 0.000054 (0.000028) |\n\n### Benchmark: benchmark_indices_mapping.json\n\n| metric | select | shard | shuffle | sort | train_test_split |\n|--------|---|---|---|---|---|\n| new / old (diff) | 0.028144 / 0.037411 (-0.009267) | 0.107088 / 0.014526 (0.092562) | 0.112188 / 0.176557 (-0.064369) | 0.174669 / 0.737135 (-0.562466) | 0.116359 / 0.296338 (-0.179980) |\n\n### Benchmark: benchmark_iterating.json\n\n| metric | read 5000 | read 50000 | read_batch 50000 10 | read_batch 50000 100 | read_batch 50000 1000 | read_formatted numpy 5000 | read_formatted pandas 5000 | read_formatted tensorflow 5000 | read_formatted torch 5000 | read_formatted_batch numpy 5000 10 | read_formatted_batch numpy 5000 1000 | shuffled read 5000 | shuffled read 50000 | shuffled read_batch 50000 10 | shuffled read_batch 50000 100 | shuffled read_batch 50000 1000 | shuffled read_formatted numpy 5000 | shuffled read_formatted_batch numpy 5000 10 | shuffled read_formatted_batch numpy 5000 1000 |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.422911 / 0.215209 (0.207702) | 4.231524 / 2.077655 (2.153869) | 1.906711 / 1.504120 (0.402591) | 1.706841 / 1.541195 (0.165646) | 1.792066 / 1.468490 (0.323576) | 0.559221 / 4.584777 (-4.025556) | 3.434280 / 3.745712 (-0.311433) | 1.918714 / 5.269862 (-3.351148) | 1.073070 / 4.565676 (-3.492606) | 0.067891 / 0.424275 (-0.356384) | 0.011927 / 0.007607 (0.004320) | 0.530843 / 0.226044 (0.304799) | 5.309213 / 2.268929 (3.040285) | 2.439246 / 55.444624 (-53.005378) | 2.101245 / 6.876477 (-4.775231) | 2.177436 / 2.142072 (0.035363) | 0.672150 / 4.805227 (-4.133077) | 0.137571 / 6.500664 (-6.363093) | 0.068343 / 0.075469 (-0.007126) |\n\n### Benchmark: benchmark_map_filter.json\n\n| metric | filter | map fast-tokenizer batched | map identity | map identity batched | map no-op batched | map no-op batched numpy | map no-op batched pandas | map no-op batched pytorch | map no-op batched tensorflow |\n|--------|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 1.265262 / 1.841788 (-0.576525) | 14.988021 / 8.074308 (6.913713) | 13.611677 / 10.191392 (3.420285) | 0.171389 / 0.680424 (-0.509035) | 0.017681 / 0.534201 (-0.516520) | 0.377542 / 0.579283 (-0.201741) | 0.399475 / 0.434364 (-0.034889) | 0.469553 / 0.540337 (-0.070785) | 0.561888 / 1.386936 (-0.825048) |\n\n</details>\nPyArrow==latest\n\n<details>\n<summary>Show updated benchmarks!</summary>\n\n### Benchmark: benchmark_array_xd.json\n\n| metric | read_batch_formatted_as_numpy after write_array2d | read_batch_formatted_as_numpy after write_flattened_sequence | read_batch_formatted_as_numpy after write_nested_sequence | read_batch_unformated after write_array2d | read_batch_unformated after write_flattened_sequence | read_batch_unformated after write_nested_sequence | read_col_formatted_as_numpy after write_array2d | read_col_formatted_as_numpy after write_flattened_sequence | read_col_formatted_as_numpy after write_nested_sequence | read_col_unformated after write_array2d | read_col_unformated after write_flattened_sequence | read_col_unformated after write_nested_sequence | read_formatted_as_numpy after write_array2d | read_formatted_as_numpy after write_flattened_sequence | read_formatted_as_numpy after write_nested_sequence | read_unformated after write_array2d | read_unformated after write_flattened_sequence | read_unformated after write_nested_sequence | write_array2d | write_flattened_sequence | write_nested_sequence |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.006782 / 0.011353 (-0.004571) | 0.004412 / 0.011008 (-0.006597) | 0.078594 / 0.038508 (0.040086) | 0.039930 / 0.023109 (0.016820) | 0.371879 / 0.275898 (0.095981) | 0.444910 / 0.323480 (0.121430) | 0.005707 / 0.007986 (-0.002279) | 0.003901 / 0.004328 (-0.000427) | 0.080125 / 0.004250 (0.075875) | 0.063977 / 0.037052 (0.026925) | 0.382781 / 0.258489 (0.124292) | 0.441791 / 0.293841 (0.147950) | 0.030428 / 0.128546 (-0.098118) | 0.009008 / 0.075646 (-0.066638) | 0.084447 / 0.419271 (-0.334824) | 0.044432 / 0.043533 (0.000899) | 0.365686 / 0.255139 (0.110547) | 0.394312 / 0.283200 (0.111113) | 0.024508 / 0.141683 (-0.117175) | 1.577020 / 1.452155 (0.124865) | 1.630259 / 1.492716 (0.137543) |\n\n### Benchmark: benchmark_getitem\\_100B.json\n\n| metric | get_batch_of\\_1024\\_random_rows | get_batch_of\\_1024\\_rows | get_first_row | get_last_row |\n|--------|---|---|---|---|\n| new / old (diff) | 0.307960 / 0.018006 (0.289953) | 0.591473 / 0.000490 (0.590983) | 0.008098 / 0.000200 (0.007898) | 0.000110 / 0.000054 (0.000056) |\n\n### Benchmark: benchmark_indices_mapping.json\n\n| metric | select | shard | shuffle | sort | train_test_split |\n|--------|---|---|---|---|---|\n| new / old (diff) | 0.029567 / 0.037411 (-0.007845) | 0.112773 / 0.014526 (0.098247) | 0.117362 / 0.176557 (-0.059194) | 0.174293 / 0.737135 (-0.562843) | 0.123156 / 0.296338 (-0.173182) |\n\n### Benchmark: benchmark_iterating.json\n\n| metric | read 5000 | read 50000 | read_batch 50000 10 | read_batch 50000 100 | read_batch 50000 1000 | read_formatted numpy 5000 | read_formatted pandas 5000 | read_formatted tensorflow 5000 | read_formatted torch 5000 | read_formatted_batch numpy 5000 10 | read_formatted_batch numpy 5000 1000 | shuffled read 5000 | shuffled read 50000 | shuffled read_batch 50000 10 | shuffled read_batch 50000 100 | shuffled read_batch 50000 1000 | shuffled read_formatted numpy 5000 | shuffled read_formatted_batch numpy 5000 10 | shuffled read_formatted_batch numpy 5000 1000 |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.457475 / 0.215209 (0.242266) | 4.599067 / 2.077655 (2.521412) | 2.262638 / 1.504120 (0.758518) | 2.124943 / 1.541195 (0.583748) | 2.339912 / 1.468490 (0.871422) | 0.566264 / 4.584777 (-4.018513) | 3.489261 / 3.745712 (-0.256451) | 1.925151 / 5.269862 (-3.344711) | 1.099389 / 4.565676 (-3.466287) | 0.068232 / 0.424275 (-0.356043) | 0.011660 / 0.007607 (0.004052) | 0.571227 / 0.226044 (0.345183) | 5.702059 / 2.268929 (3.433130) | 2.837701 / 55.444624 (-52.606924) | 2.605468 / 6.876477 (-4.271008) | 2.818396 / 2.142072 (0.676323) | 0.681856 / 4.805227 (-4.123371) | 0.141401 / 6.500664 (-6.359263) | 0.069728 / 0.075469 (-0.005741) |\n\n### Benchmark: benchmark_map_filter.json\n\n| metric | filter | map fast-tokenizer batched | map identity | map identity batched | map no-op batched | map no-op batched numpy | map no-op batched pandas | map no-op batched pytorch | map no-op batched tensorflow |\n|--------|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 1.354935 / 1.841788 (-0.486853) | 15.437404 / 8.074308 (7.363095) | 15.415193 / 10.191392 (5.223801) | 0.153459 / 0.680424 (-0.526964) | 0.017190 / 0.534201 (-0.517011) | 0.367256 / 0.579283 (-0.212027) | 0.392709 / 0.434364 (-0.041655) | 0.426125 / 0.540337 (-0.114213) | 0.522612 / 1.386936 (-0.864324) |\n\n</details>\n</details>\n\n![](https://cml.dev/watermark.png#25ac13d8ab23e7d99252ce083a45e8333b6bbcdc "CML watermark")\n', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1614599163/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1614609480', 'html_url': 'https://github.com/huggingface/datasets/pull/6000#issuecomment-1614609480', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/6000', 'id': 1614609480, 'node_id': 'IC_kwDODunzps5gPPxI', 'user': {'login': 'HuggingFaceDocBuilderDev', 'id': 99929124, 'node_id': 'U_kgDOBfTMJA', 'avatar_url': 'https://avatars.githubusercontent.com/u/99929124?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/HuggingFaceDocBuilderDev', 'html_url': 'https://github.com/HuggingFaceDocBuilderDev', 'followers_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/followers', 'following_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/following{/other_user}', 'gists_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/subscriptions', 'organizations_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/orgs', 'repos_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/repos', 'events_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/events{/privacy}', 'received_events_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-30T12:52:56Z', 'updated_at': '2023-06-30T13:08:54Z', 'author_association': 'NONE', 'body': '_The documentation is not available anymore as the PR was closed or merged._', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1614609480/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1614614182', 'html_url': 'https://github.com/huggingface/datasets/pull/6000#issuecomment-1614614182', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/6000', 'id': 1614614182, 'node_id': 'IC_kwDODunzps5gPQ6m', 'user': {'login': 'github-actions[bot]', 'id': 41898282, 'node_id': 'MDM6Qm90NDE4OTgyODI=', 'avatar_url': 'https://avatars.githubusercontent.com/in/15368?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/github-actions%5Bbot%5D', 'html_url': 'https://github.com/apps/github-actions', 'followers_url': 'https://api.github.com/users/github-actions%5Bbot%5D/followers', 'following_url': 'https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}', 'gists_url': 'https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/github-actions%5Bbot%5D/subscriptions', 'organizations_url': 'https://api.github.com/users/github-actions%5Bbot%5D/orgs', 'repos_url': 'https://api.github.com/users/github-actions%5Bbot%5D/repos', 'events_url': 'https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}', 'received_events_url': 'https://api.github.com/users/github-actions%5Bbot%5D/received_events', 'type': 'Bot', 'site_admin': False}, 'created_at': '2023-06-30T12:57:00Z', 'updated_at': '2023-06-30T12:57:00Z', 'author_association': 'NONE', 'body': '<details>\n<summary>Show benchmarks</summary>\n\nPyArrow==8.0.0\n\n<details>\n<summary>Show updated benchmarks!</summary>\n\n### Benchmark: benchmark_array_xd.json\n\n| metric | read_batch_formatted_as_numpy after write_array2d | read_batch_formatted_as_numpy after write_flattened_sequence | read_batch_formatted_as_numpy after write_nested_sequence | read_batch_unformated after write_array2d | read_batch_unformated after write_flattened_sequence | read_batch_unformated after write_nested_sequence | read_col_formatted_as_numpy after write_array2d | read_col_formatted_as_numpy after write_flattened_sequence | read_col_formatted_as_numpy after write_nested_sequence | read_col_unformated after write_array2d | read_col_unformated after write_flattened_sequence | read_col_unformated after write_nested_sequence | read_formatted_as_numpy after write_array2d | read_formatted_as_numpy after write_flattened_sequence | read_formatted_as_numpy after write_nested_sequence | read_unformated after write_array2d | read_unformated after write_flattened_sequence | read_unformated after write_nested_sequence | write_array2d | write_flattened_sequence | write_nested_sequence |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.009183 / 0.011353 (-0.002170) | 0.005232 / 0.011008 (-0.005776) | 0.120349 / 0.038508 (0.081841) | 0.044715 / 0.023109 (0.021606) | 0.361519 / 0.275898 (0.085621) | 0.463702 / 0.323480 (0.140223) | 0.005842 / 0.007986 (-0.002144) | 0.004041 / 0.004328 (-0.000288) | 0.096953 / 0.004250 (0.092703) | 0.070593 / 0.037052 (0.033540) | 0.409790 / 0.258489 (0.151301) | 0.477452 / 0.293841 (0.183611) | 0.045827 / 0.128546 (-0.082719) | 0.014038 / 0.075646 (-0.061608) | 0.421317 / 0.419271 (0.002045) | 0.065276 / 0.043533 (0.021743) | 0.360074 / 0.255139 (0.104935) | 0.409147 / 0.283200 (0.125947) | 0.032444 / 0.141683 (-0.109238) | 1.739257 / 1.452155 (0.287102) | 1.831408 / 1.492716 (0.338692) |\n\n### Benchmark: benchmark_getitem\\_100B.json\n\n| metric | get_batch_of\\_1024\\_random_rows | get_batch_of\\_1024\\_rows | get_first_row | get_last_row |\n|--------|---|---|---|---|\n| new / old (diff) | 0.274852 / 0.018006 (0.256846) | 0.596320 / 0.000490 (0.595830) | 0.006399 / 0.000200 (0.006199) | 0.000133 / 0.000054 (0.000079) |\n\n### Benchmark: benchmark_indices_mapping.json\n\n| metric | select | shard | shuffle | sort | train_test_split |\n|--------|---|---|---|---|---|\n| new / old (diff) | 0.031400 / 0.037411 (-0.006012) | 0.127052 / 0.014526 (0.112526) | 0.134269 / 0.176557 (-0.042288) | 0.225998 / 0.737135 (-0.511137) | 0.150019 / 0.296338 (-0.146319) |\n\n### Benchmark: benchmark_iterating.json\n\n| metric | read 5000 | read 50000 | read_batch 50000 10 | read_batch 50000 100 | read_batch 50000 1000 | read_formatted numpy 5000 | read_formatted pandas 5000 | read_formatted tensorflow 5000 | read_formatted torch 5000 | read_formatted_batch numpy 5000 10 | read_formatted_batch numpy 5000 1000 | shuffled read 5000 | shuffled read 50000 | shuffled read_batch 50000 10 | shuffled read_batch 50000 100 | shuffled read_batch 50000 1000 | shuffled read_formatted numpy 5000 | shuffled read_formatted_batch numpy 5000 10 | shuffled read_formatted_batch numpy 5000 1000 |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.654202 / 0.215209 (0.438993) | 6.216735 / 2.077655 (4.139081) | 2.440214 / 1.504120 (0.936094) | 2.150575 / 1.541195 (0.609380) | 2.124790 / 1.468490 (0.656300) | 0.923514 / 4.584777 (-3.661263) | 5.556924 / 3.745712 (1.811212) | 2.843886 / 5.269862 (-2.425975) | 1.834232 / 4.565676 (-2.731444) | 0.111735 / 0.424275 (-0.312540) | 0.014823 / 0.007607 (0.007216) | 0.820503 / 0.226044 (0.594459) | 7.887737 / 2.268929 (5.618809) | 3.120307 / 55.444624 (-52.324317) | 2.405856 / 6.876477 (-4.470621) | 2.411239 / 2.142072 (0.269167) | 1.071283 / 4.805227 (-3.733944) | 0.227738 / 6.500664 (-6.272926) | 0.073516 / 0.075469 (-0.001953) |\n\n### Benchmark: benchmark_map_filter.json\n\n| metric | filter | map fast-tokenizer batched | map identity | map identity batched | map no-op batched | map no-op batched numpy | map no-op batched pandas | map no-op batched pytorch | map no-op batched tensorflow |\n|--------|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 1.531806 / 1.841788 (-0.309982) | 18.547661 / 8.074308 (10.473353) | 21.083922 / 10.191392 (10.892530) | 0.241706 / 0.680424 (-0.438718) | 0.034169 / 0.534201 (-0.500032) | 0.497514 / 0.579283 (-0.081769) | 0.599801 / 0.434364 (0.165437) | 0.576465 / 0.540337 (0.036127) | 0.673509 / 1.386936 (-0.713427) |\n\n</details>\nPyArrow==latest\n\n<details>\n<summary>Show updated benchmarks!</summary>\n\n### Benchmark: benchmark_array_xd.json\n\n| metric | read_batch_formatted_as_numpy after write_array2d | read_batch_formatted_as_numpy after write_flattened_sequence | read_batch_formatted_as_numpy after write_nested_sequence | read_batch_unformated after write_array2d | read_batch_unformated after write_flattened_sequence | read_batch_unformated after write_nested_sequence | read_col_formatted_as_numpy after write_array2d | read_col_formatted_as_numpy after write_flattened_sequence | read_col_formatted_as_numpy after write_nested

[{'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1614166461', 'html_url': 'https://github.com/huggingface/datasets/issues/5999#issuecomment-1614166461', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5999', 'id': 1614166461, 'node_id': 'IC_kwDODunzps5gNjm9', 'user': {'login': 'albertvillanova', 'id': 8515462, 'node_id': 'MDQ6VXNlcjg1MTU0NjI=', 'avatar_url': 'https://avatars.githubusercontent.com/u/8515462?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/albertvillanova', 'html_url': 'https://github.com/albertvillanova', 'followers_url': 'https://api.github.com/users/albertvillanova/followers', 'following_url': 'https://api.github.com/users/albertvillanova/following{/other_user}', 'gists_url': 'https://api.github.com/users/albertvillanova/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/albertvillanova/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/albertvillanova/subscriptions', 'organizations_url': 'https://api.github.com/users/albertvillanova/orgs', 'repos_url': 'https://api.github.com/users/albertvillanova/repos', 'events_url': 'https://api.github.com/users/albertvillanova/events{/privacy}', 'received_events_url': 'https://api.github.com/users/albertvillanova/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-30T05:57:22Z', 'updated_at': '2023-06-30T05:57:22Z', 'author_association': 'MEMBER', 'body': "Thanks for reporting, @Praful932.\r\n\r\nLet's continue the conversation on the Hub: https://huggingface.co/datasets/xglue/discussions/5", 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1614166461/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}]
[{'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1614725726', 'html_url': 'https://github.com/huggingface/datasets/issues/5998#issuecomment-1614725726', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5998', 'id': 1614725726, 'node_id': 'IC_kwDODunzps5gPsJe', 'user': {'login': 'albertvillanova', 'id': 8515462, 'node_id': 'MDQ6VXNlcjg1MTU0NjI=', 'avatar_url': 'https://avatars.githubusercontent.com/u/8515462?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/albertvillanova', 'html_url': 'https://github.com/albertvillanova', 'followers_url': 'https://api.github.com/users/albertvillanova/followers', 'following_url': 'https://api.github.com/users/albertvillanova/following{/other_user}', 'gists_url': 'https://api.github.com/users/albertvillanova/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/albertvillanova/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/albertvillanova/subscriptions', 'organizations_url': 'https://api.github.com/users/albertvillanova/orgs', 'repos_url': 'https://api.github.com/users/albertvillanova/repos', 'events_url': 'https://api.github.com/users/albertvillanova/events{/privacy}', 'received_events_url': 'https://api.github.com/users/albertvillanova/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-30T14:21:03Z', 'updated_at': '2023-06-30T14:21:03Z', 'author_association': 'MEMBER', 'body': 'Thanks for reporting, @wangyuxinwhy. ', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1614725726/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}]
[{'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1613875170', 'html_url': 'https://github.com/huggingface/datasets/issues/5997#issuecomment-1613875170', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5997', 'id': 1613875170, 'node_id': 'IC_kwDODunzps5gMcfi', 'user': {'login': 'siddhsql', 'id': 127623723, 'node_id': 'U_kgDOB5tiKw', 'avatar_url': 'https://avatars.githubusercontent.com/u/127623723?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/siddhsql', 'html_url': 'https://github.com/siddhsql', 'followers_url': 'https://api.github.com/users/siddhsql/followers', 'following_url': 'https://api.github.com/users/siddhsql/following{/other_user}', 'gists_url': 'https://api.github.com/users/siddhsql/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/siddhsql/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/siddhsql/subscriptions', 'organizations_url': 'https://api.github.com/users/siddhsql/orgs', 'repos_url': 'https://api.github.com/users/siddhsql/repos', 'events_url': 'https://api.github.com/users/siddhsql/events{/privacy}', 'received_events_url': 'https://api.github.com/users/siddhsql/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-29T22:22:19Z', 'updated_at': '2023-06-29T22:22:19Z', 'author_association': 'NONE', 'body': 'I just noticed the [docs](https://github.com/huggingface/datasets/blob/main/src/datasets/arrow_dataset.py#L2881C11-L2881C200) say:\r\n\r\n>If batched is `True` and `batch_size` is `n > 1`, then the function takes a batch of `n` examples as input and can return a batch with `n` examples, or with an arbitrary number of examples.\r\n\r\nso maybe this is a bug then.', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1613875170/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1618952519', 'html_url': 'https://github.com/huggingface/datasets/issues/5997#issuecomment-1618952519', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5997', 'id': 1618952519, 'node_id': 'IC_kwDODunzps5gf0FH', 'user': {'login': 'mariosasko', 'id': 47462742, 'node_id': 'MDQ6VXNlcjQ3NDYyNzQy', 'avatar_url': 'https://avatars.githubusercontent.com/u/47462742?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/mariosasko', 'html_url': 'https://github.com/mariosasko', 'followers_url': 'https://api.github.com/users/mariosasko/followers', 'following_url': 'https://api.github.com/users/mariosasko/following{/other_user}', 'gists_url': 'https://api.github.com/users/mariosasko/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/mariosasko/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/mariosasko/subscriptions', 'organizations_url': 'https://api.github.com/users/mariosasko/orgs', 'repos_url': 'https://api.github.com/users/mariosasko/repos', 'events_url': 'https://api.github.com/users/mariosasko/events{/privacy}', 'received_events_url': 'https://api.github.com/users/mariosasko/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-07-03T17:58:51Z', 'updated_at': '2023-07-03T17:58:51Z', 'author_association': 'CONTRIBUTOR', 'body': 'All the values in a batch must be of the same length. So one solution is dropping all the input columns:\r\n```python\r\ndata = data.map(lambda samples: tokenizer(samples["text"], max_length=tokenizer.model_max_length, truncation=True, stride=4, return_overflowing_tokens=True), batched=True, remove_columns=data.column_names)\r\n```\r\n\r\nAnother is padding/transforming the input columns to the tokenizer output\'s length (447). ', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1618952519/reactions', 'total_count': 1, '+1': 1, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}]

[{'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1609607635', 'html_url': 'https://github.com/huggingface/datasets/pull/5995#issuecomment-1609607635', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5995', 'id': 1609607635, 'node_id': 'IC_kwDODunzps5f8KnT', 'user': {'login': 'HuggingFaceDocBuilderDev', 'id': 99929124, 'node_id': 'U_kgDOBfTMJA', 'avatar_url': 'https://avatars.githubusercontent.com/u/99929124?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/HuggingFaceDocBuilderDev', 'html_url': 'https://github.com/HuggingFaceDocBuilderDev', 'followers_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/followers', 'following_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/following{/other_user}', 'gists_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/subscriptions', 'organizations_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/orgs', 'repos_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/repos', 'events_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/events{/privacy}', 'received_events_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-27T14:20:24Z', 'updated_at': '2023-06-28T13:47:08Z', 'author_association': 'NONE', 'body': '_The documentation is not available anymore as the PR was closed or merged._', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1609607635/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1609610766', 'html_url': 'https://github.com/huggingface/datasets/pull/5995#issuecomment-1609610766', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5995', 'id': 1609610766, 'node_id': 'IC_kwDODunzps5f8LYO', 'user': {'login': 'github-actions[bot]', 'id': 41898282, 'node_id': 'MDM6Qm90NDE4OTgyODI=', 'avatar_url': 'https://avatars.githubusercontent.com/in/15368?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/github-actions%5Bbot%5D', 'html_url': 'https://github.com/apps/github-actions', 'followers_url': 'https://api.github.com/users/github-actions%5Bbot%5D/followers', 'following_url': 'https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}', 'gists_url': 'https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/github-actions%5Bbot%5D/subscriptions', 'organizations_url': 'https://api.github.com/users/github-actions%5Bbot%5D/orgs', 'repos_url': 'https://api.github.com/users/github-actions%5Bbot%5D/repos', 'events_url': 'https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}', 'received_events_url': 'https://api.github.com/users/github-actions%5Bbot%5D/received_events', 'type': 'Bot', 'site_admin': False}, 'created_at': '2023-06-27T14:21:48Z', 'updated_at': '2023-06-27T14:21:48Z', 'author_association': 'NONE', 'body': '<details>\n<summary>Show benchmarks</summary>\n\nPyArrow==8.0.0\n\n<details>\n<summary>Show updated benchmarks!</summary>\n\n### Benchmark: benchmark_array_xd.json\n\n| metric | read_batch_formatted_as_numpy after write_array2d | read_batch_formatted_as_numpy after write_flattened_sequence | read_batch_formatted_as_numpy after write_nested_sequence | read_batch_unformated after write_array2d | read_batch_unformated after write_flattened_sequence | read_batch_unformated after write_nested_sequence | read_col_formatted_as_numpy after write_array2d | read_col_formatted_as_numpy after write_flattened_sequence | read_col_formatted_as_numpy after write_nested_sequence | read_col_unformated after write_array2d | read_col_unformated after write_flattened_sequence | read_col_unformated after write_nested_sequence | read_formatted_as_numpy after write_array2d | read_formatted_as_numpy after write_flattened_sequence | read_formatted_as_numpy after write_nested_sequence | read_unformated after write_array2d | read_unformated after write_flattened_sequence | read_unformated after write_nested_sequence | write_array2d | write_flattened_sequence | write_nested_sequence |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.009725 / 0.011353 (-0.001628) | 0.006014 / 0.011008 (-0.004994) | 0.136039 / 0.038508 (0.097531) | 0.049685 / 0.023109 (0.026576) | 0.492967 / 0.275898 (0.217068) | 0.553775 / 0.323480 (0.230295) | 0.007421 / 0.007986 (-0.000564) | 0.004686 / 0.004328 (0.000357) | 0.106639 / 0.004250 (0.102389) | 0.073483 / 0.037052 (0.036431) | 0.507194 / 0.258489 (0.248705) | 0.535760 / 0.293841 (0.241919) | 0.049666 / 0.128546 (-0.078880) | 0.014139 / 0.075646 (-0.061507) | 0.435459 / 0.419271 (0.016188) | 0.076026 / 0.043533 (0.032493) | 0.454542 / 0.255139 (0.199403) | 0.512724 / 0.283200 (0.229524) | 0.034969 / 0.141683 (-0.106713) | 1.881048 / 1.452155 (0.428893) | 1.959915 / 1.492716 (0.467199) |\n\n### Benchmark: benchmark_getitem\\_100B.json\n\n| metric | get_batch_of\\_1024\\_random_rows | get_batch_of\\_1024\\_rows | get_first_row | get_last_row |\n|--------|---|---|---|---|\n| new / old (diff) | 0.265322 / 0.018006 (0.247316) | 0.573963 / 0.000490 (0.573474) | 0.017493 / 0.000200 (0.017293) | 0.000637 / 0.000054 (0.000582) |\n\n### Benchmark: benchmark_indices_mapping.json\n\n| metric | select | shard | shuffle | sort | train_test_split |\n|--------|---|---|---|---|---|\n| new / old (diff) | 0.028712 / 0.037411 (-0.008699) | 0.149554 / 0.014526 (0.135029) | 0.130013 / 0.176557 (-0.046544) | 0.203408 / 0.737135 (-0.533727) | 0.144778 / 0.296338 (-0.151561) |\n\n### Benchmark: benchmark_iterating.json\n\n| metric | read 5000 | read 50000 | read_batch 50000 10 | read_batch 50000 100 | read_batch 50000 1000 | read_formatted numpy 5000 | read_formatted pandas 5000 | read_formatted tensorflow 5000 | read_formatted torch 5000 | read_formatted_batch numpy 5000 10 | read_formatted_batch numpy 5000 1000 | shuffled read 5000 | shuffled read 50000 | shuffled read_batch 50000 10 | shuffled read_batch 50000 100 | shuffled read_batch 50000 1000 | shuffled read_formatted numpy 5000 | shuffled read_formatted_batch numpy 5000 10 | shuffled read_formatted_batch numpy 5000 1000 |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.664198 / 0.215209 (0.448989) | 6.418054 / 2.077655 (4.340399) | 2.602338 / 1.504120 (1.098219) | 2.212992 / 1.541195 (0.671797) | 2.214309 / 1.468490 (0.745819) | 0.914772 / 4.584777 (-3.670005) | 5.824831 / 3.745712 (2.079119) | 2.865381 / 5.269862 (-2.404481) | 1.906020 / 4.565676 (-2.659657) | 0.106947 / 0.424275 (-0.317328) | 0.013467 / 0.007607 (0.005860) | 0.834556 / 0.226044 (0.608512) | 8.237078 / 2.268929 (5.968150) | 3.380919 / 55.444624 (-52.063705) | 2.656713 / 6.876477 (-4.219764) | 2.834941 / 2.142072 (0.692869) | 1.151241 / 4.805227 (-3.653986) | 0.220860 / 6.500664 (-6.279804) | 0.080781 / 0.075469 (0.005312) |\n\n### Benchmark: benchmark_map_filter.json\n\n| metric | filter | map fast-tokenizer batched | map identity | map identity batched | map no-op batched | map no-op batched numpy | map no-op batched pandas | map no-op batched pytorch | map no-op batched tensorflow |\n|--------|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 1.655128 / 1.841788 (-0.186660) | 18.696108 / 8.074308 (10.621800) | 22.882108 / 10.191392 (12.690716) | 0.236041 / 0.680424 (-0.444383) | 0.031073 / 0.534201 (-0.503128) | 0.525263 / 0.579283 (-0.054021) | 0.632933 / 0.434364 (0.198569) | 0.707228 / 0.540337 (0.166890) | 0.753508 / 1.386936 (-0.633428) |\n\n</details>\nPyArrow==latest\n\n<details>\n<summary>Show updated benchmarks!</summary>\n\n### Benchmark: benchmark_array_xd.json\n\n| metric | read_batch_formatted_as_numpy after write_array2d | read_batch_formatted_as_numpy after write_flattened_sequence | read_batch_formatted_as_numpy after write_nested_sequence | read_batch_unformated after write_array2d | read_batch_unformated after write_flattened_sequence | read_batch_unformated after write_nested_sequence | read_col_formatted_as_numpy after write_array2d | read_col_formatted_as_numpy after write_flattened_sequence | read_col_formatted_as_numpy after write_nested_sequence | read_col_unformated after write_array2d | read_col_unformated after write_flattened_sequence | read_col_unformated after write_nested_sequence | read_formatted_as_numpy after write_array2d | read_formatted_as_numpy after write_flattened_sequence | read_formatted_as_numpy after write_nested_sequence | read_unformated after write_array2d | read_unformated after write_flattened_sequence | read_unformated after write_nested_sequence | write_array2d | write_flattened_sequence | write_nested_sequence |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.009875 / 0.011353 (-0.001478) | 0.005135 / 0.011008 (-0.005873) | 0.101307 / 0.038508 (0.062799) | 0.044895 / 0.023109 (0.021786) | 0.497824 / 0.275898 (0.221926) | 0.573098 / 0.323480 (0.249618) | 0.006669 / 0.007986 (-0.001317) | 0.004289 / 0.004328 (-0.000039) | 0.105824 / 0.004250 (0.101573) | 0.061002 / 0.037052 (0.023950) | 0.510127 / 0.258489 (0.251638) | 0.581387 / 0.293841 (0.287546) | 0.052843 / 0.128546 (-0.075703) | 0.015506 / 0.075646 (-0.060140) | 0.116057 / 0.419271 (-0.303215) | 0.063444 / 0.043533 (0.019912) | 0.479366 / 0.255139 (0.224227) | 0.518419 / 0.283200 (0.235220) | 0.034876 / 0.141683 (-0.106806) | 2.018446 / 1.452155 (0.566292) | 1.960755 / 1.492716 (0.468039) |\n\n### Benchmark: benchmark_getitem\\_100B.json\n\n| metric | get_batch_of\\_1024\\_random_rows | get_batch_of\\_1024\\_rows | get_first_row | get_last_row |\n|--------|---|---|---|---|\n| new / old (diff) | 0.269077 / 0.018006 (0.251070) | 0.606059 / 0.000490 (0.605569) | 0.000488 / 0.000200 (0.000288) | 0.000093 / 0.000054 (0.000038) |\n\n### Benchmark: benchmark_indices_mapping.json\n\n| metric | select | shard | shuffle | sort | train_test_split |\n|--------|---|---|---|---|---|\n| new / old (diff) | 0.032465 / 0.037411 (-0.004946) | 0.136517 / 0.014526 (0.121991) | 0.147740 / 0.176557 (-0.028816) | 0.193802 / 0.737135 (-0.543334) | 0.151876 / 0.296338 (-0.144462) |\n\n### Benchmark: benchmark_iterating.json\n\n| metric | read 5000 | read 50000 | read_batch 50000 10 | read_batch 50000 100 | read_batch 50000 1000 | read_formatted numpy 5000 | read_formatted pandas 5000 | read_formatted tensorflow 5000 | read_formatted torch 5000 | read_formatted_batch numpy 5000 10 | read_formatted_batch numpy 5000 1000 | shuffled read 5000 | shuffled read 50000 | shuffled read_batch 50000 10 | shuffled read_batch 50000 100 | shuffled read_batch 50000 1000 | shuffled read_formatted numpy 5000 | shuffled read_formatted_batch numpy 5000 10 | shuffled read_formatted_batch numpy 5000 1000 |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.709866 / 0.215209 (0.494657) | 6.848193 / 2.077655 (4.770538) | 3.310853 / 1.504120 (1.806733) | 2.940813 / 1.541195 (1.399619) | 2.934934 / 1.468490 (1.466444) | 0.927104 / 4.584777 (-3.657673) | 5.921607 / 3.745712 (2.175895) | 4.926558 / 5.269862 (-0.343303) | 2.853269 / 4.565676 (-1.712407) | 0.120278 / 0.424275 (-0.303998) | 0.015468 / 0.007607 (0.007861) | 0.820509 / 0.226044 (0.594464) | 8.263136 / 2.268929 (5.994208) | 3.780214 / 55.444624 (-51.664410) | 3.108482 / 6.876477 (-3.767995) | 3.101544 / 2.142072 (0.959471) | 1.165539 / 4.805227 (-3.639688) | 0.229215 / 6.500664 (-6.271449) | 0.079862 / 0.075469 (0.004393) |\n\n### Benchmark: benchmark_map_filter.json\n\n| metric | filter | map fast-tokenizer batched | map identity | map identity batched | map no-op batched | map no-op batched numpy | map no-op batched pandas | map no-op batched pytorch | map no-op batched tensorflow |\n|--------|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 1.775071 / 1.841788 (-0.066717) | 19.327621 / 8.074308 (11.253313) | 23.057537 / 10.191392 (12.866145) | 0.250649 / 0.680424 (-0.429775) | 0.029767 / 0.534201 (-0.504434) | 0.554774 / 0.579283 (-0.024509) | 0.651919 / 0.434364 (0.217555) | 0.651641 / 0.540337 (0.111304) | 0.762386 / 1.386936 (-0.624550) |\n\n</details>\n</details>\n\n![](https://cml.dev/watermark.png#fdc3ce7060366f480621e8640903c9ab476164e7 "CML watermark")\n', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1609610766/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1609689479', 'html_url': 'https://github.com/huggingface/datasets/pull/5995#issuecomment-1609689479', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5995', 'id': 1609689479, 'node_id': 'IC_kwDODunzps5f8emH', 'user': {'login': 'github-actions[bot]', 'id': 41898282, 'node_id': 'MDM6Qm90NDE4OTgyODI=', 'avatar_url': 'https://avatars.githubusercontent.com/in/15368?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/github-actions%5Bbot%5D', 'html_url': 'https://github.com/apps/github-actions', 'followers_url': 'https://api.github.com/users/github-actions%5Bbot%5D/followers', 'following_url': 'https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}', 'gists_url': 'https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/github-actions%5Bbot%5D/subscriptions', 'organizations_url': 'https://api.github.com/users/github-actions%5Bbot%5D/orgs', 'repos_url': 'https://api.github.com/users/github-actions%5Bbot%5D/repos', 'events_url': 'https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}', 'received_events_url': 'https://api.github.com/users/github-actions%5Bbot%5D/received_events', 'type': 'Bot', 'site_admin': False}, 'created_at': '2023-06-27T15:02:38Z', 'updated_at': '2023-06-27T15:02:38Z', 'author_association': 'NONE', 'body': '<details>\n<summary>Show benchmarks</summary>\n\nPyArrow==8.0.0\n\n<details>\n<summary>Show updated benchmarks!</summary>\n\n### Benchmark: benchmark_array_xd.json\n\n| metric | read_batch_formatted_as_numpy after write_array2d | read_batch_formatted_as_numpy after write_flattened_sequence | read_batch_formatted_as_numpy after write_nested_sequence | read_batch_unformated after write_array2d | read_batch_unformated after write_flattened_sequence | read_batch_unformated after write_nested_sequence | read_col_formatted_as_numpy after write_array2d | read_col_formatted_as_numpy after write_flattened_sequence | read_col_formatted_as_numpy after write_nested_sequence | read_col_unformated after write_array2d | read_col_unformated after write_flattened_sequence | read_col_unformated after write_nested_sequence | read_formatted_as_numpy after write_array2d | read_formatted_as_numpy after write_flattened_sequence | read_formatted_as_numpy after write_nested_sequence | read_unformated after write_array2d | read_unformated after write_flattened_sequence | read_unformated after write_nested_sequence | write_array2d | write_flattened_sequence | write_nested_sequence |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.005997 / 0.011353 (-0.005356) | 0.003892 / 0.011008 (-0.007116) | 0.098020 / 0.038508 (0.059512) | 0.042584 / 0.023109 (0.019475) | 0.317909 / 0.275898 (0.042011) | 0.395042 / 0.323480 (0.071563) | 0.005358 / 0.007986 (-0.002628) | 0.003266 / 0.004328 (-0.001062) | 0.076698 / 0.004250 (0.072447) | 0.062331 / 0.037052 (0.025279) | 0.334900 / 0.258489 (0.076411) | 0.379355 / 0.293841 (0.085514) | 0.030815 / 0.128546 (-0.097731) | 0.008596 / 0.075646 (-0.067050) | 0.327739 / 0.419271 (-0.091533) | 0.054061 / 0.043533 (0.010528) | 0.311044 / 0.255139 (0.055905) | 0.336705 / 0.283200 (0.053506) | 0.022785 / 0.141683 (-0.118898) | 1.516793 / 1.452155 (0.064639) | 1.590435 / 1.492716 (0.097719) |\n\n### Benchmark: benchmark_getitem\\_100B.json\n\n| metric | get_batch_of\\_1024\\_random_rows | get_batch_of\\_1024\\_rows | get_first_row | get_last_row |\n|--------|---|---|---|---|\n| new / old (diff) | 0.289157 / 0.018006 (0.271151) | 0.531074 / 0.000490 (0.530585) | 0.004672 / 0.000200 (0.004472) | 0.000095 / 0.000054 (0.000040) |\n\n### Benchmark: benchmark_indices_mapping.json\n\n| metric | select | shard | shuffle | sort | train_test_split |\n|--------|---|---|---|---|---|\n| new / old (diff) | 0.026173 / 0.037411 (-0.011238) | 0.105723 / 0.014526 (0.091197) | 0.118010 / 0.176557 (-0.058547) | 0.178062 / 0.737135 (-0.559073) | 0.120059 / 0.296338 (-0.176279) |\n\n### Benchmark: benchmark_iterating.json\n\n| metric | read 5000 | read 50000 | read_batch 50000 10 | read_batch 50000 100 | read_batch 50000 1000 | read_formatted numpy 5000 | read_formatted pandas 5000 | read_formatted tensorflow 5000 | read_formatted torch 5000 | read_formatted_batch numpy 5000 10 | read_formatted_batch numpy 5000 1000 | shuffled read 5000 | shuffled read 50000 | shuffled read_batch 50000 10 | shuffled read_batch 50000 100 | shuffled read_batch 50000 1000 | shuffled read_formatted numpy 5000 | shuffled read_formatted_batch numpy 5000 10 | shuffled read_formatted_batch numpy 5000 1000 |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.410870 / 0.215209 (0.195661) | 4.042183 / 2.077655 (1.964528) | 1.830059 / 1.504120 (0.325939) | 1.638996 / 1.541195 (0.097802) | 1.701368 / 1.468490 (0.232878) | 0.529915 / 4.584777 (-4.054861) | 3.693308 / 3.745712 (-0.052404) | 1.827875 / 5.269862 (-3.441986) | 1.063237 / 4.565676 (-3.502440) | 0.065368 / 0.424275 (-0.358907) | 0.010986 / 0.007607 (0.003379) | 0.509399 / 0.226044 (0.283354) | 5.092739 / 2.268929 (2.823810) | 2.293490 / 55.444624 (-53.151135) | 1.958742 / 6.876477 (-4.917735) | 2.024985 / 2.142072 (-0.117088) | 0.646978 / 4.805227 (-4.158249) | 0.138616 / 6.500664 (-6.362048) | 0.062101 / 0.075469 (-0.013368) |\n\n### Benchmark: benchmark_map_filter.json\n\n| metric | filter | map fast-tokenizer batched | map identity | map identity batched | map no-op batched | map no-op batched numpy | map no-op batched pandas | map no-op batched pytorch | map no-op batched tensorflow |\n|--------|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 1.202016 / 1.841788 (-0.639772) | 14.493204 / 8.074308 (6.418896) | 12.992160 / 10.191392 (2.800768) | 0.188922 / 0.680424 (-0.491502) | 0.017594 / 0.534201 (-0.516606) | 0.399917 / 0.579283 (-0.179367) | 0.429760 / 0.434364 (-0.004604) | 0.497906 / 0.540337 (-0.042431) | 0.608745 / 1.386936 (-0.778191) |\n\n</details>\nPyArrow==latest\n\n<details>\n<summary>Show updated benchmarks!</summary>\n\n### Benchmark: benchmark_array_xd.json\n\n| metric | read_batch_formatted_as_numpy after write_array2d | read_batch_formatted_as_numpy after write_flattened_sequence | read_batch_formatted_as_numpy after write_nested_sequence | read_batch_unformated after write_array2d | read_batch_unformated after write_flattened_sequence | read_batch_unformated after write_nested_sequence | read_col_formatted_as_numpy after write_array2d | read_col_formatted_as_numpy after write_flattened_sequence | read_col_formatted_as_numpy after write_nested_se

[{'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1609421011', 'html_url': 'https://github.com/huggingface/datasets/pull/5994#issuecomment-1609421011', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5994', 'id': 1609421011, 'node_id': 'IC_kwDODunzps5f7dDT', 'user': {'login': 'github-actions[bot]', 'id': 41898282, 'node_id': 'MDM6Qm90NDE4OTgyODI=', 'avatar_url': 'https://avatars.githubusercontent.com/in/15368?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/github-actions%5Bbot%5D', 'html_url': 'https://github.com/apps/github-actions', 'followers_url': 'https://api.github.com/users/github-actions%5Bbot%5D/followers', 'following_url': 'https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}', 'gists_url': 'https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/github-actions%5Bbot%5D/subscriptions', 'organizations_url': 'https://api.github.com/users/github-actions%5Bbot%5D/orgs', 'repos_url': 'https://api.github.com/users/github-actions%5Bbot%5D/repos', 'events_url': 'https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}', 'received_events_url': 'https://api.github.com/users/github-actions%5Bbot%5D/received_events', 'type': 'Bot', 'site_admin': False}, 'created_at': '2023-06-27T12:38:27Z', 'updated_at': '2023-06-27T12:38:27Z', 'author_association': 'NONE', 'body': '<details>\n<summary>Show benchmarks</summary>\n\nPyArrow==8.0.0\n\n<details>\n<summary>Show updated benchmarks!</summary>\n\n### Benchmark: benchmark_array_xd.json\n\n| metric | read_batch_formatted_as_numpy after write_array2d | read_batch_formatted_as_numpy after write_flattened_sequence | read_batch_formatted_as_numpy after write_nested_sequence | read_batch_unformated after write_array2d | read_batch_unformated after write_flattened_sequence | read_batch_unformated after write_nested_sequence | read_col_formatted_as_numpy after write_array2d | read_col_formatted_as_numpy after write_flattened_sequence | read_col_formatted_as_numpy after write_nested_sequence | read_col_unformated after write_array2d | read_col_unformated after write_flattened_sequence | read_col_unformated after write_nested_sequence | read_formatted_as_numpy after write_array2d | read_formatted_as_numpy after write_flattened_sequence | read_formatted_as_numpy after write_nested_sequence | read_unformated after write_array2d | read_unformated after write_flattened_sequence | read_unformated after write_nested_sequence | write_array2d | write_flattened_sequence | write_nested_sequence |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.005969 / 0.011353 (-0.005384) | 0.003687 / 0.011008 (-0.007321) | 0.100843 / 0.038508 (0.062335) | 0.036912 / 0.023109 (0.013803) | 0.312389 / 0.275898 (0.036491) | 0.370335 / 0.323480 (0.046855) | 0.003434 / 0.007986 (-0.004552) | 0.003710 / 0.004328 (-0.000619) | 0.076899 / 0.004250 (0.072648) | 0.053647 / 0.037052 (0.016594) | 0.324825 / 0.258489 (0.066336) | 0.367711 / 0.293841 (0.073870) | 0.028079 / 0.128546 (-0.100467) | 0.008326 / 0.075646 (-0.067320) | 0.312342 / 0.419271 (-0.106930) | 0.047423 / 0.043533 (0.003890) | 0.321063 / 0.255139 (0.065924) | 0.336508 / 0.283200 (0.053308) | 0.019973 / 0.141683 (-0.121710) | 1.529334 / 1.452155 (0.077179) | 1.573746 / 1.492716 (0.081030) |\n\n### Benchmark: benchmark_getitem\\_100B.json\n\n| metric | get_batch_of\\_1024\\_random_rows | get_batch_of\\_1024\\_rows | get_first_row | get_last_row |\n|--------|---|---|---|---|\n| new / old (diff) | 0.210849 / 0.018006 (0.192843) | 0.418798 / 0.000490 (0.418309) | 0.007347 / 0.000200 (0.007147) | 0.000070 / 0.000054 (0.000016) |\n\n### Benchmark: benchmark_indices_mapping.json\n\n| metric | select | shard | shuffle | sort | train_test_split |\n|--------|---|---|---|---|---|\n| new / old (diff) | 0.022718 / 0.037411 (-0.014694) | 0.098400 / 0.014526 (0.083874) | 0.106590 / 0.176557 (-0.069967) | 0.168460 / 0.737135 (-0.568675) | 0.108401 / 0.296338 (-0.187938) |\n\n### Benchmark: benchmark_iterating.json\n\n| metric | read 5000 | read 50000 | read_batch 50000 10 | read_batch 50000 100 | read_batch 50000 1000 | read_formatted numpy 5000 | read_formatted pandas 5000 | read_formatted tensorflow 5000 | read_formatted torch 5000 | read_formatted_batch numpy 5000 10 | read_formatted_batch numpy 5000 1000 | shuffled read 5000 | shuffled read 50000 | shuffled read_batch 50000 10 | shuffled read_batch 50000 100 | shuffled read_batch 50000 1000 | shuffled read_formatted numpy 5000 | shuffled read_formatted_batch numpy 5000 10 | shuffled read_formatted_batch numpy 5000 1000 |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.443066 / 0.215209 (0.227857) | 4.416658 / 2.077655 (2.339003) | 2.088844 / 1.504120 (0.584724) | 1.879564 / 1.541195 (0.338369) | 1.933815 / 1.468490 (0.465325) | 0.565085 / 4.584777 (-4.019692) | 3.412440 / 3.745712 (-0.333273) | 1.754686 / 5.269862 (-3.515175) | 1.024576 / 4.565676 (-3.541100) | 0.067909 / 0.424275 (-0.356366) | 0.011054 / 0.007607 (0.003447) | 0.534748 / 0.226044 (0.308703) | 5.351457 / 2.268929 (3.082529) | 2.517368 / 55.444624 (-52.927256) | 2.182762 / 6.876477 (-4.693715) | 2.238205 / 2.142072 (0.096133) | 0.672962 / 4.805227 (-4.132265) | 0.136098 / 6.500664 (-6.364566) | 0.066534 / 0.075469 (-0.008935) |\n\n### Benchmark: benchmark_map_filter.json\n\n| metric | filter | map fast-tokenizer batched | map identity | map identity batched | map no-op batched | map no-op batched numpy | map no-op batched pandas | map no-op batched pytorch | map no-op batched tensorflow |\n|--------|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 1.281241 / 1.841788 (-0.560547) | 13.872881 / 8.074308 (5.798573) | 13.161023 / 10.191392 (2.969631) | 0.130011 / 0.680424 (-0.550412) | 0.016759 / 0.534201 (-0.517442) | 0.359802 / 0.579283 (-0.219481) | 0.392577 / 0.434364 (-0.041787) | 0.427742 / 0.540337 (-0.112595) | 0.522241 / 1.386936 (-0.864695) |\n\n</details>\nPyArrow==latest\n\n<details>\n<summary>Show updated benchmarks!</summary>\n\n### Benchmark: benchmark_array_xd.json\n\n| metric | read_batch_formatted_as_numpy after write_array2d | read_batch_formatted_as_numpy after write_flattened_sequence | read_batch_formatted_as_numpy after write_nested_sequence | read_batch_unformated after write_array2d | read_batch_unformated after write_flattened_sequence | read_batch_unformated after write_nested_sequence | read_col_formatted_as_numpy after write_array2d | read_col_formatted_as_numpy after write_flattened_sequence | read_col_formatted_as_numpy after write_nested_sequence | read_col_unformated after write_array2d | read_col_unformated after write_flattened_sequence | read_col_unformated after write_nested_sequence | read_formatted_as_numpy after write_array2d | read_formatted_as_numpy after write_flattened_sequence | read_formatted_as_numpy after write_nested_sequence | read_unformated after write_array2d | read_unformated after write_flattened_sequence | read_unformated after write_nested_sequence | write_array2d | write_flattened_sequence | write_nested_sequence |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.005985 / 0.011353 (-0.005368) | 0.003705 / 0.011008 (-0.007304) | 0.077699 / 0.038508 (0.039191) | 0.035686 / 0.023109 (0.012577) | 0.420356 / 0.275898 (0.144458) | 0.476753 / 0.323480 (0.153273) | 0.003510 / 0.007986 (-0.004475) | 0.002807 / 0.004328 (-0.001521) | 0.077151 / 0.004250 (0.072901) | 0.046420 / 0.037052 (0.009368) | 0.391781 / 0.258489 (0.133292) | 0.461128 / 0.293841 (0.167287) | 0.027847 / 0.128546 (-0.100699) | 0.008322 / 0.075646 (-0.067324) | 0.082768 / 0.419271 (-0.336503) | 0.042629 / 0.043533 (-0.000904) | 0.405745 / 0.255139 (0.150606) | 0.430797 / 0.283200 (0.147598) | 0.019832 / 0.141683 (-0.121851) | 1.556208 / 1.452155 (0.104054) | 1.612166 / 1.492716 (0.119450) |\n\n### Benchmark: benchmark_getitem\\_100B.json\n\n| metric | get_batch_of\\_1024\\_random_rows | get_batch_of\\_1024\\_rows | get_first_row | get_last_row |\n|--------|---|---|---|---|\n| new / old (diff) | 0.230633 / 0.018006 (0.212626) | 0.401667 / 0.000490 (0.401178) | 0.000776 / 0.000200 (0.000576) | 0.000069 / 0.000054 (0.000014) |\n\n### Benchmark: benchmark_indices_mapping.json\n\n| metric | select | shard | shuffle | sort | train_test_split |\n|--------|---|---|---|---|---|\n| new / old (diff) | 0.024959 / 0.037411 (-0.012452) | 0.100560 / 0.014526 (0.086034) | 0.109175 / 0.176557 (-0.067382) | 0.159919 / 0.737135 (-0.577217) | 0.112810 / 0.296338 (-0.183528) |\n\n### Benchmark: benchmark_iterating.json\n\n| metric | read 5000 | read 50000 | read_batch 50000 10 | read_batch 50000 100 | read_batch 50000 1000 | read_formatted numpy 5000 | read_formatted pandas 5000 | read_formatted tensorflow 5000 | read_formatted torch 5000 | read_formatted_batch numpy 5000 10 | read_formatted_batch numpy 5000 1000 | shuffled read 5000 | shuffled read 50000 | shuffled read_batch 50000 10 | shuffled read_batch 50000 100 | shuffled read_batch 50000 1000 | shuffled read_formatted numpy 5000 | shuffled read_formatted_batch numpy 5000 10 | shuffled read_formatted_batch numpy 5000 1000 |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.460601 / 0.215209 (0.245392) | 4.620039 / 2.077655 (2.542385) | 2.257900 / 1.504120 (0.753780) | 2.039192 / 1.541195 (0.497997) | 2.064451 / 1.468490 (0.595961) | 0.557887 / 4.584777 (-4.026890) | 3.356100 / 3.745712 (-0.389612) | 1.703578 / 5.269862 (-3.566284) | 1.024984 / 4.565676 (-3.540693) | 0.067602 / 0.424275 (-0.356673) | 0.011450 / 0.007607 (0.003842) | 0.563230 / 0.226044 (0.337186) | 5.632150 / 2.268929 (3.363221) | 2.698701 / 55.444624 (-52.745924) | 2.363218 / 6.876477 (-4.513259) | 2.363997 / 2.142072 (0.221925) | 0.671260 / 4.805227 (-4.133967) | 0.136166 / 6.500664 (-6.364499) | 0.067094 / 0.075469 (-0.008375) |\n\n### Benchmark: benchmark_map_filter.json\n\n| metric | filter | map fast-tokenizer batched | map identity | map identity batched | map no-op batched | map no-op batched numpy | map no-op batched pandas | map no-op batched pytorch | map no-op batched tensorflow |\n|--------|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 1.303030 / 1.841788 (-0.538757) | 14.137277 / 8.074308 (6.062969) | 13.937631 / 10.191392 (3.746239) | 0.162626 / 0.680424 (-0.517798) | 0.016687 / 0.534201 (-0.517514) | 0.363657 / 0.579283 (-0.215626) | 0.392021 / 0.434364 (-0.042343) | 0.427275 / 0.540337 (-0.113062) | 0.512192 / 1.386936 (-0.874744) |\n\n</details>\n</details>\n\n![](https://cml.dev/watermark.png#42603528d9bd8c3ab287ed0eadc7fa3d1ef4cfd8 "CML watermark")\n', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1609421011/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1609426080', 'html_url': 'https://github.com/huggingface/datasets/pull/5994#issuecomment-1609426080', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5994', 'id': 1609426080, 'node_id': 'IC_kwDODunzps5f7eSg', 'user': {'login': 'HuggingFaceDocBuilderDev', 'id': 99929124, 'node_id': 'U_kgDOBfTMJA', 'avatar_url': 'https://avatars.githubusercontent.com/u/99929124?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/HuggingFaceDocBuilderDev', 'html_url': 'https://github.com/HuggingFaceDocBuilderDev', 'followers_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/followers', 'following_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/following{/other_user}', 'gists_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/subscriptions', 'organizations_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/orgs', 'repos_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/repos', 'events_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/events{/privacy}', 'received_events_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-27T12:41:50Z', 'updated_at': '2023-06-27T15:33:13Z', 'author_association': 'NONE', 'body': '_The documentation is not available anymore as the PR was closed or merged._', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1609426080/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1609427850', 'html_url': 'https://github.com/huggingface/datasets/pull/5994#issuecomment-1609427850', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5994', 'id': 1609427850, 'node_id': 'IC_kwDODunzps5f7euK', 'user': {'login': 'github-actions[bot]', 'id': 41898282, 'node_id': 'MDM6Qm90NDE4OTgyODI=', 'avatar_url': 'https://avatars.githubusercontent.com/in/15368?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/github-actions%5Bbot%5D', 'html_url': 'https://github.com/apps/github-actions', 'followers_url': 'https://api.github.com/users/github-actions%5Bbot%5D/followers', 'following_url': 'https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}', 'gists_url': 'https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/github-actions%5Bbot%5D/subscriptions', 'organizations_url': 'https://api.github.com/users/github-actions%5Bbot%5D/orgs', 'repos_url': 'https://api.github.com/users/github-actions%5Bbot%5D/repos', 'events_url': 'https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}', 'received_events_url': 'https://api.github.com/users/github-actions%5Bbot%5D/received_events', 'type': 'Bot', 'site_admin': False}, 'created_at': '2023-06-27T12:42:58Z', 'updated_at': '2023-06-27T12:42:58Z', 'author_association': 'NONE', 'body': '<details>\n<summary>Show benchmarks</summary>\n\nPyArrow==8.0.0\n\n<details>\n<summary>Show updated benchmarks!</summary>\n\n### Benchmark: benchmark_array_xd.json\n\n| metric | read_batch_formatted_as_numpy after write_array2d | read_batch_formatted_as_numpy after write_flattened_sequence | read_batch_formatted_as_numpy after write_nested_sequence | read_batch_unformated after write_array2d | read_batch_unformated after write_flattened_sequence | read_batch_unformated after write_nested_sequence | read_col_formatted_as_numpy after write_array2d | read_col_formatted_as_numpy after write_flattened_sequence | read_col_formatted_as_numpy after write_nested_sequence | read_col_unformated after write_array2d | read_col_unformated after write_flattened_sequence | read_col_unformated after write_nested_sequence | read_formatted_as_numpy after write_array2d | read_formatted_as_numpy after write_flattened_sequence | read_formatted_as_numpy after write_nested_sequence | read_unformated after write_array2d | read_unformated after write_flattened_sequence | read_unformated after write_nested_sequence | write_array2d | write_flattened_sequence | write_nested_sequence |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.005974 / 0.011353 (-0.005378) | 0.003947 / 0.011008 (-0.007061) | 0.098604 / 0.038508 (0.060096) | 0.036947 / 0.023109 (0.013838) | 0.311844 / 0.275898 (0.035946) | 0.375243 / 0.323480 (0.051763) | 0.003453 / 0.007986 (-0.004533) | 0.003834 / 0.004328 (-0.000495) | 0.077943 / 0.004250 (0.073692) | 0.052956 / 0.037052 (0.015904) | 0.320812 / 0.258489 (0.062323) | 0.373963 / 0.293841 (0.080122) | 0.028382 / 0.128546 (-0.100164) | 0.008525 / 0.075646 (-0.067121) | 0.311306 / 0.419271 (-0.107965) | 0.047029 / 0.043533 (0.003496) | 0.309933 / 0.255139 (0.054794) | 0.335114 / 0.283200 (0.051915) | 0.019629 / 0.141683 (-0.122054) | 1.569771 / 1.452155 (0.117617) | 1.585899 / 1.492716 (0.093182) |\n\n### Benchmark: benchmark_getitem\\_100B.json\n\n| metric | get_batch_of\\_1024\\_random_rows | get_batch_of\\_1024\\_rows | get_first_row | get_last_row |\n|--------|---|---|---|---|\n| new / old (diff) | 0.216565 / 0.018006 (0.198559) | 0.426717 / 0.000490 (0.426228) | 0.003609 / 0.000200 (0.003409) | 0.000077 / 0.000054 (0.000023) |\n\n### Benchmark: benchmark_indices_mapping.json\n\n| metric | select | shard | shuffle | sort | train_test_split |\n|--------|---|---|---|---|---|\n| new / old (diff) | 0.023079 / 0.037411 (-0.014332) | 0.096954 / 0.014526 (0.082428) | 0.105398 / 0.176557 (-0.071158) | 0.165433 / 0.737135 (-0.571703) | 0.109703 / 0.296338 (-0.186636) |\n\n### Benchmark: benchmark_iterating.json\n\n| metric | read 5000 | read 50000 | read_batch 50000 10 | read_batch 50000 100 | read_batch 50000 1000 | read_formatted numpy 5000 | read_formatted pandas 5000 | read_formatted tensorflow 5000 | read_formatted torch 5000 | read_formatted_batch numpy 5000 10 | read_formatted_batch numpy 5000 1000 | shuffled read 5000 | shuffled read 50000 | shuffled read_batch 50000 10 | shuffled read_batch 50000 100 | shuffled read_batch 50000 1000 | shuffled read_formatted numpy 5000 | shuffled read_formatted_batch numpy 5000 10 | shuffled read_formatted_batch numpy 5000 1000 |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.456227 / 0.215209 (0.241018) | 4.529857 / 2.077655 (2.452202) | 2.214054 / 1.504120 (0.709934) | 2.029716 / 1.541195 (0.488521) | 2.081175 / 1.468490 (0.612685) | 0.563642 / 4.584777 (-4.021135) | 3.355393 / 3.745712 (-0.390320) | 1.765938 / 5.269862 (-3.503924) | 1.039062 / 4.565676 (-3.526615) | 0.067952 / 0.424275 (-0.356323) | 0.011044 / 0.007607 (0.003437) | 0.556935 / 0.226044 (0.330890) | 5.588167 / 2.268929 (3.319239) | 2.667217 / 55.444624 (-52.777407) | 2.337383 / 6.876477 (-4.539094) | 2.429590 / 2.142072 (0.287517) | 0.676972 / 4.805227 (-4.128256) | 0.135782 / 6.500664 (-6.364882) | 0.066323 / 0.075469 (-0.009146) |\n\n### Benchmark: benchmark_map_filter.json\n\n| metric | filter | map fast-tokenizer batched | map identity | map identity batched | map no-op batched | map no-op batched numpy | map no-op batched pandas | map no-op batched pytorch | map no-op batched tensorflow |\n|--------|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 1.237358 / 1.841788 (-0.604429) | 13.910492 / 8.074308 (5.836184) | 13.227275 / 10.191392 (3.035883) | 0.146857 / 0.680424 (-0.533567) | 0.016991 / 0.534201 (-0.517210) | 0.363637 / 0.579283 (-0.215646) | 0.392462 / 0.434364 (-0.041902) | 0.450009 / 0.540337 (-0.090329) | 0.536077 / 1.386936 (-0.850859) |\n\n</details>\nPyArrow==latest\n\n<details>\n<summary>Show updated benchmarks!</summary>\n\n### Benchmark: benchmark_array_xd.json\n\n| metric | read_batch_formatted_as_numpy after write_array2d | read_batch_formatted_as_numpy after write_flattened_sequence | read_batch_formatted_as_numpy after write_nested_sequence | read_batch_unformated after write_array2d | read_batch_unformated after write_flattened_sequence | read_batch_unformated after write_nested_sequence | read_col_formatted_as_numpy after write_array2d | read_col_formatted_as_numpy after write_flattened_sequence | read_col_formatted_as_numpy after write_nes

[{'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1609761600', 'html_url': 'https://github.com/huggingface/datasets/issues/5993#issuecomment-1609761600', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5993', 'id': 1609761600, 'node_id': 'IC_kwDODunzps5f8wNA', 'user': {'login': 'lhoestq', 'id': 42851186, 'node_id': 'MDQ6VXNlcjQyODUxMTg2', 'avatar_url': 'https://avatars.githubusercontent.com/u/42851186?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/lhoestq', 'html_url': 'https://github.com/lhoestq', 'followers_url': 'https://api.github.com/users/lhoestq/followers', 'following_url': 'https://api.github.com/users/lhoestq/following{/other_user}', 'gists_url': 'https://api.github.com/users/lhoestq/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/lhoestq/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/lhoestq/subscriptions', 'organizations_url': 'https://api.github.com/users/lhoestq/orgs', 'repos_url': 'https://api.github.com/users/lhoestq/repos', 'events_url': 'https://api.github.com/users/lhoestq/events{/privacy}', 'received_events_url': 'https://api.github.com/users/lhoestq/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-27T15:33:25Z', 'updated_at': '2023-06-27T15:33:25Z', 'author_association': 'MEMBER', 'body': "We'll do a new release of `datasets` soon to make the fix available :)\r\n\r\nIn the meantime you can use `datasets` from source (main)", 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1609761600/reactions', 'total_count': 1, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 1, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1609766729', 'html_url': 'https://github.com/huggingface/datasets/issues/5993#issuecomment-1609766729', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5993', 'id': 1609766729, 'node_id': 'IC_kwDODunzps5f8xdJ', 'user': {'login': 'exs-avianello', 'id': 128361578, 'node_id': 'U_kgDOB6akag', 'avatar_url': 'https://avatars.githubusercontent.com/u/128361578?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/exs-avianello', 'html_url': 'https://github.com/exs-avianello', 'followers_url': 'https://api.github.com/users/exs-avianello/followers', 'following_url': 'https://api.github.com/users/exs-avianello/following{/other_user}', 'gists_url': 'https://api.github.com/users/exs-avianello/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/exs-avianello/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/exs-avianello/subscriptions', 'organizations_url': 'https://api.github.com/users/exs-avianello/orgs', 'repos_url': 'https://api.github.com/users/exs-avianello/repos', 'events_url': 'https://api.github.com/users/exs-avianello/events{/privacy}', 'received_events_url': 'https://api.github.com/users/exs-avianello/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-27T15:36:41Z', 'updated_at': '2023-06-27T15:36:41Z', 'author_association': 'NONE', 'body': 'Thank you very much @lhoestq ! 🚀 ', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1609766729/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}]
[{'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1609120912', 'html_url': 'https://github.com/huggingface/datasets/pull/5992#issuecomment-1609120912', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5992', 'id': 1609120912, 'node_id': 'IC_kwDODunzps5f6TyQ', 'user': {'login': 'HuggingFaceDocBuilderDev', 'id': 99929124, 'node_id': 'U_kgDOBfTMJA', 'avatar_url': 'https://avatars.githubusercontent.com/u/99929124?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/HuggingFaceDocBuilderDev', 'html_url': 'https://github.com/HuggingFaceDocBuilderDev', 'followers_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/followers', 'following_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/following{/other_user}', 'gists_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/subscriptions', 'organizations_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/orgs', 'repos_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/repos', 'events_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/events{/privacy}', 'received_events_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-27T09:23:07Z', 'updated_at': '2023-06-27T09:23:07Z', 'author_association': 'NONE', 'body': 'The docs for this PR live [here](https://moon-ci-docs.huggingface.co/docs/datasets/pr_5992). All of your documentation changes will be reflected on that endpoint.', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1609120912/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}]
[]
[{'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1607443382', 'html_url': 'https://github.com/huggingface/datasets/issues/5989#issuecomment-1607443382', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5989', 'id': 1607443382, 'node_id': 'IC_kwDODunzps5fz6O2', 'user': {'login': 'polinaeterna', 'id': 16348744, 'node_id': 'MDQ6VXNlcjE2MzQ4NzQ0', 'avatar_url': 'https://avatars.githubusercontent.com/u/16348744?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/polinaeterna', 'html_url': 'https://github.com/polinaeterna', 'followers_url': 'https://api.github.com/users/polinaeterna/followers', 'following_url': 'https://api.github.com/users/polinaeterna/following{/other_user}', 'gists_url': 'https://api.github.com/users/polinaeterna/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/polinaeterna/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/polinaeterna/subscriptions', 'organizations_url': 'https://api.github.com/users/polinaeterna/orgs', 'repos_url': 'https://api.github.com/users/polinaeterna/repos', 'events_url': 'https://api.github.com/users/polinaeterna/events{/privacy}', 'received_events_url': 'https://api.github.com/users/polinaeterna/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-26T13:11:20Z', 'updated_at': '2023-06-26T13:11:20Z', 'author_association': 'CONTRIBUTOR', 'body': "in this case we need to decide what to do with the existing datasets with white space characters (there shouldn't be a lot of them I think)", 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1607443382/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1607446604', 'html_url': 'https://github.com/huggingface/datasets/issues/5989#issuecomment-1607446604', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5989', 'id': 1607446604, 'node_id': 'IC_kwDODunzps5fz7BM', 'user': {'login': 'severo', 'id': 1676121, 'node_id': 'MDQ6VXNlcjE2NzYxMjE=', 'avatar_url': 'https://avatars.githubusercontent.com/u/1676121?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/severo', 'html_url': 'https://github.com/severo', 'followers_url': 'https://api.github.com/users/severo/followers', 'following_url': 'https://api.github.com/users/severo/following{/other_user}', 'gists_url': 'https://api.github.com/users/severo/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/severo/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/severo/subscriptions', 'organizations_url': 'https://api.github.com/users/severo/orgs', 'repos_url': 'https://api.github.com/users/severo/repos', 'events_url': 'https://api.github.com/users/severo/events{/privacy}', 'received_events_url': 'https://api.github.com/users/severo/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-26T13:12:58Z', 'updated_at': '2023-06-26T13:12:58Z', 'author_association': 'CONTRIBUTOR', 'body': 'I imagine that we should stop supporting them, and help the user fix them?', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1607446604/reactions', 'total_count': 1, '+1': 1, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}]

[{'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1607870533', 'html_url': 'https://github.com/huggingface/datasets/issues/5988#issuecomment-1607870533', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5988', 'id': 1607870533, 'node_id': 'IC_kwDODunzps5f1ihF', 'user': {'login': 'mariosasko', 'id': 47462742, 'node_id': 'MDQ6VXNlcjQ3NDYyNzQy', 'avatar_url': 'https://avatars.githubusercontent.com/u/47462742?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/mariosasko', 'html_url': 'https://github.com/mariosasko', 'followers_url': 'https://api.github.com/users/mariosasko/followers', 'following_url': 'https://api.github.com/users/mariosasko/following{/other_user}', 'gists_url': 'https://api.github.com/users/mariosasko/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/mariosasko/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/mariosasko/subscriptions', 'organizations_url': 'https://api.github.com/users/mariosasko/orgs', 'repos_url': 'https://api.github.com/users/mariosasko/repos', 'events_url': 'https://api.github.com/users/mariosasko/events{/privacy}', 'received_events_url': 'https://api.github.com/users/mariosasko/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-26T16:59:59Z', 'updated_at': '2023-06-27T12:38:34Z', 'author_association': 'CONTRIBUTOR', 'body': 'Unfortunately, I can\'t reproduce the error. What does the following code return for you?\r\n```python\r\nimport requests\r\nfrom huggingface_hub import hf_hub_url\r\nr = requests.get(hf_hub_url("codeparrot/codeparrot-clean-train", "dataset_infos.json", repo_type="dataset"))\r\n```\r\n\r\nAlso, can you provide more info about your network (region, proxies, etc.)?', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1607870533/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}]
[{'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1608055333', 'html_url': 'https://github.com/huggingface/datasets/issues/5987#issuecomment-1608055333', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5987', 'id': 1608055333, 'node_id': 'IC_kwDODunzps5f2Pol', 'user': {'login': 'mariosasko', 'id': 47462742, 'node_id': 'MDQ6VXNlcjQ3NDYyNzQy', 'avatar_url': 'https://avatars.githubusercontent.com/u/47462742?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/mariosasko', 'html_url': 'https://github.com/mariosasko', 'followers_url': 'https://api.github.com/users/mariosasko/followers', 'following_url': 'https://api.github.com/users/mariosasko/following{/other_user}', 'gists_url': 'https://api.github.com/users/mariosasko/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/mariosasko/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/mariosasko/subscriptions', 'organizations_url': 'https://api.github.com/users/mariosasko/orgs', 'repos_url': 'https://api.github.com/users/mariosasko/repos', 'events_url': 'https://api.github.com/users/mariosasko/events{/privacy}', 'received_events_url': 'https://api.github.com/users/mariosasko/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-26T18:52:36Z', 'updated_at': '2023-06-26T18:52:36Z', 'author_association': 'CONTRIBUTOR', 'body': 'Can you explain your use case for `max_shard_size`? \r\n\r\nOn some systems, there is a limit to the size of a memory-mapped file, so we could consider exposing this parameter in `load_dataset`.', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1608055333/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1608590487', 'html_url': 'https://github.com/huggingface/datasets/issues/5987#issuecomment-1608590487', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5987', 'id': 1608590487, 'node_id': 'IC_kwDODunzps5f4SSX', 'user': {'login': 'npuichigo', 'id': 11533479, 'node_id': 'MDQ6VXNlcjExNTMzNDc5', 'avatar_url': 'https://avatars.githubusercontent.com/u/11533479?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/npuichigo', 'html_url': 'https://github.com/npuichigo', 'followers_url': 'https://api.github.com/users/npuichigo/followers', 'following_url': 'https://api.github.com/users/npuichigo/following{/other_user}', 'gists_url': 'https://api.github.com/users/npuichigo/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/npuichigo/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/npuichigo/subscriptions', 'organizations_url': 'https://api.github.com/users/npuichigo/orgs', 'repos_url': 'https://api.github.com/users/npuichigo/repos', 'events_url': 'https://api.github.com/users/npuichigo/events{/privacy}', 'received_events_url': 'https://api.github.com/users/npuichigo/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-27T01:59:37Z', 'updated_at': '2023-06-27T01:59:37Z', 'author_association': 'NONE', 'body': 'In my use case, users may choose a proper size to balance the cost and benefit of using large shard size. (On azure blob or hdfs which may automatically download the shard from background)', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1608590487/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1611836049', 'html_url': 'https://github.com/huggingface/datasets/issues/5987#issuecomment-1611836049', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5987', 'id': 1611836049, 'node_id': 'IC_kwDODunzps5gEqqR', 'user': {'login': 'mariosasko', 'id': 47462742, 'node_id': 'MDQ6VXNlcjQ3NDYyNzQy', 'avatar_url': 'https://avatars.githubusercontent.com/u/47462742?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/mariosasko', 'html_url': 'https://github.com/mariosasko', 'followers_url': 'https://api.github.com/users/mariosasko/followers', 'following_url': 'https://api.github.com/users/mariosasko/following{/other_user}', 'gists_url': 'https://api.github.com/users/mariosasko/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/mariosasko/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/mariosasko/subscriptions', 'organizations_url': 'https://api.github.com/users/mariosasko/orgs', 'repos_url': 'https://api.github.com/users/mariosasko/repos', 'events_url': 'https://api.github.com/users/mariosasko/events{/privacy}', 'received_events_url': 'https://api.github.com/users/mariosasko/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-28T17:44:40Z', 'updated_at': '2023-06-28T17:44:40Z', 'author_association': 'CONTRIBUTOR', 'body': "But `load_dataset` doesn't support caching (and reading) Arrow datasets from remote storage. \r\n\r\n`load_datset_builder` + `download_and_prepare` is not equal to `load_dataset`. The latter has one more step, `builder.as_dataset`, that memory-maps Arrow files, which only works for local files.", 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1611836049/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1612388769', 'html_url': 'https://github.com/huggingface/datasets/issues/5987#issuecomment-1612388769', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5987', 'id': 1612388769, 'node_id': 'IC_kwDODunzps5gGxmh', 'user': {'login': 'npuichigo', 'id': 11533479, 'node_id': 'MDQ6VXNlcjExNTMzNDc5', 'avatar_url': 'https://avatars.githubusercontent.com/u/11533479?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/npuichigo', 'html_url': 'https://github.com/npuichigo', 'followers_url': 'https://api.github.com/users/npuichigo/followers', 'following_url': 'https://api.github.com/users/npuichigo/following{/other_user}', 'gists_url': 'https://api.github.com/users/npuichigo/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/npuichigo/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/npuichigo/subscriptions', 'organizations_url': 'https://api.github.com/users/npuichigo/orgs', 'repos_url': 'https://api.github.com/users/npuichigo/repos', 'events_url': 'https://api.github.com/users/npuichigo/events{/privacy}', 'received_events_url': 'https://api.github.com/users/npuichigo/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-29T03:42:09Z', 'updated_at': '2023-06-29T03:42:09Z', 'author_association': 'NONE', 'body': 'Thanks. So if I want to use `IterableDataset` and control the size of single arrow file, how should I organize the data loader? Maybe `load_dataset_build` + `download_and_prepare` + `builder.as_dataset` + `dataset.to_iterable_dataset`?', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1612388769/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1613387103', 'html_url': 'https://github.com/huggingface/datasets/issues/5987#issuecomment-1613387103', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5987', 'id': 1613387103, 'node_id': 'IC_kwDODunzps5gKlVf', 'user': {'login': 'mariosasko', 'id': 47462742, 'node_id': 'MDQ6VXNlcjQ3NDYyNzQy', 'avatar_url': 'https://avatars.githubusercontent.com/u/47462742?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/mariosasko', 'html_url': 'https://github.com/mariosasko', 'followers_url': 'https://api.github.com/users/mariosasko/followers', 'following_url': 'https://api.github.com/users/mariosasko/following{/other_user}', 'gists_url': 'https://api.github.com/users/mariosasko/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/mariosasko/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/mariosasko/subscriptions', 'organizations_url': 'https://api.github.com/users/mariosasko/orgs', 'repos_url': 'https://api.github.com/users/mariosasko/repos', 'events_url': 'https://api.github.com/users/mariosasko/events{/privacy}', 'received_events_url': 'https://api.github.com/users/mariosasko/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-29T15:24:38Z', 'updated_at': '2023-06-29T15:24:38Z', 'author_association': 'CONTRIBUTOR', 'body': 'Yes, this should work.\r\n\r\nI think we can expose `max_shard_size` in `load_dataset`, so feel free to open a PR.', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1613387103/reactions', 'total_count': 1, '+1': 1, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}]

[{'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1622177194', 'html_url': 'https://github.com/huggingface/datasets/pull/5986#issuecomment-1622177194', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5986', 'id': 1622177194, 'node_id': 'IC_kwDODunzps5gsHWq', 'user': {'login': 'maddiedawson', 'id': 106995444, 'node_id': 'U_kgDOBmCe9A', 'avatar_url': 'https://avatars.githubusercontent.com/u/106995444?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/maddiedawson', 'html_url': 'https://github.com/maddiedawson', 'followers_url': 'https://api.github.com/users/maddiedawson/followers', 'following_url': 'https://api.github.com/users/maddiedawson/following{/other_user}', 'gists_url': 'https://api.github.com/users/maddiedawson/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/maddiedawson/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/maddiedawson/subscriptions', 'organizations_url': 'https://api.github.com/users/maddiedawson/orgs', 'repos_url': 'https://api.github.com/users/maddiedawson/repos', 'events_url': 'https://api.github.com/users/maddiedawson/events{/privacy}', 'received_events_url': 'https://api.github.com/users/maddiedawson/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-07-05T17:21:03Z', 'updated_at': '2023-07-05T17:21:03Z', 'author_association': 'CONTRIBUTOR', 'body': '@lhoestq would you be able to review this please and also approve the workflow?', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1622177194/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1623359134', 'html_url': 'https://github.com/huggingface/datasets/pull/5986#issuecomment-1623359134', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5986', 'id': 1623359134, 'node_id': 'IC_kwDODunzps5gwn6e', 'user': {'login': 'lhoestq', 'id': 42851186, 'node_id': 'MDQ6VXNlcjQyODUxMTg2', 'avatar_url': 'https://avatars.githubusercontent.com/u/42851186?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/lhoestq', 'html_url': 'https://github.com/lhoestq', 'followers_url': 'https://api.github.com/users/lhoestq/followers', 'following_url': 'https://api.github.com/users/lhoestq/following{/other_user}', 'gists_url': 'https://api.github.com/users/lhoestq/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/lhoestq/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/lhoestq/subscriptions', 'organizations_url': 'https://api.github.com/users/lhoestq/orgs', 'repos_url': 'https://api.github.com/users/lhoestq/repos', 'events_url': 'https://api.github.com/users/lhoestq/events{/privacy}', 'received_events_url': 'https://api.github.com/users/lhoestq/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-07-06T09:40:43Z', 'updated_at': '2023-07-06T09:40:43Z', 'author_association': 'MEMBER', 'body': 'Sounds good to me :) feel free to run `make style` to apply code formatting', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1623359134/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1623366517', 'html_url': 'https://github.com/huggingface/datasets/pull/5986#issuecomment-1623366517', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5986', 'id': 1623366517, 'node_id': 'IC_kwDODunzps5gwpt1', 'user': {'login': 'HuggingFaceDocBuilderDev', 'id': 99929124, 'node_id': 'U_kgDOBfTMJA', 'avatar_url': 'https://avatars.githubusercontent.com/u/99929124?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/HuggingFaceDocBuilderDev', 'html_url': 'https://github.com/HuggingFaceDocBuilderDev', 'followers_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/followers', 'following_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/following{/other_user}', 'gists_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/subscriptions', 'organizations_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/orgs', 'repos_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/repos', 'events_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/events{/privacy}', 'received_events_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-07-06T09:44:55Z', 'updated_at': '2023-07-07T09:56:36Z', 'author_association': 'NONE', 'body': '_The documentation is not available anymore as the PR was closed or merged._', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1623366517/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1623976935', 'html_url': 'https://github.com/huggingface/datasets/pull/5986#issuecomment-1623976935', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5986', 'id': 1623976935, 'node_id': 'IC_kwDODunzps5gy-vn', 'user': {'login': 'lhoestq', 'id': 42851186, 'node_id': 'MDQ6VXNlcjQyODUxMTg2', 'avatar_url': 'https://avatars.githubusercontent.com/u/42851186?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/lhoestq', 'html_url': 'https://github.com/lhoestq', 'followers_url': 'https://api.github.com/users/lhoestq/followers', 'following_url': 'https://api.github.com/users/lhoestq/following{/other_user}', 'gists_url': 'https://api.github.com/users/lhoestq/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/lhoestq/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/lhoestq/subscriptions', 'organizations_url': 'https://api.github.com/users/lhoestq/orgs', 'repos_url': 'https://api.github.com/users/lhoestq/repos', 'events_url': 'https://api.github.com/users/lhoestq/events{/privacy}', 'received_events_url': 'https://api.github.com/users/lhoestq/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-07-06T16:32:53Z', 'updated_at': '2023-07-06T16:32:53Z', 'author_association': 'MEMBER', 'body': 'cool ! I think we can merge once all comments have been addressed', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1623976935/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1624079323', 'html_url': 'https://github.com/huggingface/datasets/pull/5986#issuecomment-1624079323', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5986', 'id': 1624079323, 'node_id': 'IC_kwDODunzps5gzXvb', 'user': {'login': 'mathewjacob1002', 'id': 134338709, 'node_id': 'U_kgDOCAHYlQ', 'avatar_url': 'https://avatars.githubusercontent.com/u/134338709?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/mathewjacob1002', 'html_url': 'https://github.com/mathewjacob1002', 'followers_url': 'https://api.github.com/users/mathewjacob1002/followers', 'following_url': 'https://api.github.com/users/mathewjacob1002/following{/other_user}', 'gists_url': 'https://api.github.com/users/mathewjacob1002/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/mathewjacob1002/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/mathewjacob1002/subscriptions', 'organizations_url': 'https://api.github.com/users/mathewjacob1002/orgs', 'repos_url': 'https://api.github.com/users/mathewjacob1002/repos', 'events_url': 'https://api.github.com/users/mathewjacob1002/events{/privacy}', 'received_events_url': 'https://api.github.com/users/mathewjacob1002/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-07-06T17:41:13Z', 'updated_at': '2023-07-06T17:41:13Z', 'author_association': 'CONTRIBUTOR', 'body': '@lhoestq I just addressed the comments and I think we can move ahead with this! \r\n', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1624079323/reactions', 'total_count': 1, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 1, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1625176426', 'html_url': 'https://github.com/huggingface/datasets/pull/5986#issuecomment-1625176426', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5986', 'id': 1625176426, 'node_id': 'IC_kwDODunzps5g3jlq', 'user': {'login': 'github-actions[bot]', 'id': 41898282, 'node_id': 'MDM6Qm90NDE4OTgyODI=', 'avatar_url': 'https://avatars.githubusercontent.com/in/15368?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/github-actions%5Bbot%5D', 'html_url': 'https://github.com/apps/github-actions', 'followers_url': 'https://api.github.com/users/github-actions%5Bbot%5D/followers', 'following_url': 'https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}', 'gists_url': 'https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/github-actions%5Bbot%5D/subscriptions', 'organizations_url': 'https://api.github.com/users/github-actions%5Bbot%5D/orgs', 'repos_url': 'https://api.github.com/users/github-actions%5Bbot%5D/repos', 'events_url': 'https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}', 'received_events_url': 'https://api.github.com/users/github-actions%5Bbot%5D/received_events', 'type': 'Bot', 'site_admin': False}, 'created_at': '2023-07-07T10:05:58Z', 'updated_at': '2023-07-07T10:05:58Z', 'author_association': 'NONE', 'body': '<details>\n<summary>Show benchmarks</summary>\n\nPyArrow==8.0.0\n\n<details>\n<summary>Show updated benchmarks!</summary>\n\n### Benchmark: benchmark_array_xd.json\n\n| metric | read_batch_formatted_as_numpy after write_array2d | read_batch_formatted_as_numpy after write_flattened_sequence | read_batch_formatted_as_numpy after write_nested_sequence | read_batch_unformated after write_array2d | read_batch_unformated after write_flattened_sequence | read_batch_unformated after write_nested_sequence | read_col_formatted_as_numpy after write_array2d | read_col_formatted_as_numpy after write_flattened_sequence | read_col_formatted_as_numpy after write_nested_sequence | read_col_unformated after write_array2d | read_col_unformated after write_flattened_sequence | read_col_unformated after write_nested_sequence | read_formatted_as_numpy after write_array2d | read_formatted_as_numpy after write_flattened_sequence | read_formatted_as_numpy after write_nested_sequence | read_unformated after write_array2d | read_unformated after write_flattened_sequence | read_unformated after write_nested_sequence | write_array2d | write_flattened_sequence | write_nested_sequence |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.007734 / 0.011353 (-0.003619) | 0.004608 / 0.011008 (-0.006400) | 0.094466 / 0.038508 (0.055958) | 0.086477 / 0.023109 (0.063368) | 0.410311 / 0.275898 (0.134413) | 0.455560 / 0.323480 (0.132080) | 0.006112 / 0.007986 (-0.001874) | 0.003845 / 0.004328 (-0.000483) | 0.072506 / 0.004250 (0.068256) | 0.066721 / 0.037052 (0.029669) | 0.409967 / 0.258489 (0.151478) | 0.460480 / 0.293841 (0.166639) | 0.036700 / 0.128546 (-0.091847) | 0.009854 / 0.075646 (-0.065792) | 0.320936 / 0.419271 (-0.098335) | 0.061002 / 0.043533 (0.017469) | 0.413963 / 0.255139 (0.158824) | 0.426787 / 0.283200 (0.143588) | 0.029182 / 0.141683 (-0.112501) | 1.685136 / 1.452155 (0.232981) | 1.754590 / 1.492716 (0.261873) |\n\n### Benchmark: benchmark_getitem\\_100B.json\n\n| metric | get_batch_of\\_1024\\_random_rows | get_batch_of\\_1024\\_rows | get_first_row | get_last_row |\n|--------|---|---|---|---|\n| new / old (diff) | 0.222698 / 0.018006 (0.204692) | 0.505929 / 0.000490 (0.505440) | 0.005291 / 0.000200 (0.005091) | 0.000097 / 0.000054 (0.000042) |\n\n### Benchmark: benchmark_indices_mapping.json\n\n| metric | select | shard | shuffle | sort | train_test_split |\n|--------|---|---|---|---|---|\n| new / old (diff) | 0.032527 / 0.037411 (-0.004884) | 0.094842 / 0.014526 (0.080317) | 0.110138 / 0.176557 (-0.066418) | 0.193786 / 0.737135 (-0.543349) | 0.112593 / 0.296338 (-0.183745) |\n\n### Benchmark: benchmark_iterating.json\n\n| metric | read 5000 | read 50000 | read_batch 50000 10 | read_batch 50000 100 | read_batch 50000 1000 | read_formatted numpy 5000 | read_formatted pandas 5000 | read_formatted tensorflow 5000 | read_formatted torch 5000 | read_formatted_batch numpy 5000 10 | read_formatted_batch numpy 5000 1000 | shuffled read 5000 | shuffled read 50000 | shuffled read_batch 50000 10 | shuffled read_batch 50000 100 | shuffled read_batch 50000 1000 | shuffled read_formatted numpy 5000 | shuffled read_formatted_batch numpy 5000 10 | shuffled read_formatted_batch numpy 5000 1000 |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.441671 / 0.215209 (0.226461) | 4.392961 / 2.077655 (2.315306) | 2.161111 / 1.504120 (0.656991) | 1.967080 / 1.541195 (0.425885) | 2.065411 / 1.468490 (0.596920) | 0.561080 / 4.584777 (-4.023697) | 4.159612 / 3.745712 (0.413900) | 6.435248 / 5.269862 (1.165386) | 3.732338 / 4.565676 (-0.833339) | 0.066156 / 0.424275 (-0.358119) | 0.008030 / 0.007607 (0.000423) | 0.532182 / 0.226044 (0.306137) | 5.315142 / 2.268929 (3.046213) | 2.680157 / 55.444624 (-52.764467) | 2.303799 / 6.876477 (-4.572677) | 2.530911 / 2.142072 (0.388838) | 0.669504 / 4.805227 (-4.135723) | 0.151940 / 6.500664 (-6.348724) | 0.066999 / 0.075469 (-0.008470) |\n\n### Benchmark: benchmark_map_filter.json\n\n| metric | filter | map fast-tokenizer batched | map identity | map identity batched | map no-op batched | map no-op batched numpy | map no-op batched pandas | map no-op batched pytorch | map no-op batched tensorflow |\n|--------|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 1.424275 / 1.841788 (-0.417513) | 21.550742 / 8.074308 (13.476434) | 16.031414 / 10.191392 (5.840022) | 0.194681 / 0.680424 (-0.485743) | 0.020389 / 0.534201 (-0.513812) | 0.429808 / 0.579283 (-0.149475) | 0.457503 / 0.434364 (0.023139) | 0.511522 / 0.540337 (-0.028816) | 0.682621 / 1.386936 (-0.704315) |\n\n</details>\nPyArrow==latest\n\n<details>\n<summary>Show updated benchmarks!</summary>\n\n### Benchmark: benchmark_array_xd.json\n\n| metric | read_batch_formatted_as_numpy after write_array2d | read_batch_formatted_as_numpy after write_flattened_sequence | read_batch_formatted_as_numpy after write_nested_sequence | read_batch_unformated after write_array2d | read_batch_unformated after write_flattened_sequence | read_batch_unformated after write_nested_sequence | read_col_formatted_as_numpy after write_array2d | read_col_formatted_as_numpy after write_flattened_sequence | read_col_formatted_as_numpy after write_nested_sequence | read_col_unformated after write_array2d | read_col_unformated after write_flattened_sequence | read_col_unformated after write_nested_sequence | read_formatted_as_numpy after write_array2d | read_formatted_as_numpy after write_flattened_sequence | read_formatted_as_numpy after write_nested_sequence | read_unformated after write_array2d | read_unformated after write_flattened_sequence | read_unformated after write_nested_sequence | write_array2d | write_flattened_sequence | write_nested_sequence |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.007519 / 0.011353 (-0.003834) | 0.004445 / 0.011008 (-0.006563) | 0.071946 / 0.038508 (0.033438) | 0.082982 / 0.023109 (0.059873) | 0.459938 / 0.275898 (0.184040) | 0.504875 / 0.323480 (0.181395) | 0.005805 / 0.007986 (-0.002181) | 0.003740 / 0.004328 (-0.000589) | 0.071998 / 0.004250 (0.067747) | 0.062580 / 0.037052 (0.025527) | 0.462263 / 0.258489 (0.203774) | 0.506355 / 0.293841 (0.212514) | 0.036321 / 0.128546 (-0.092225) | 0.009830 / 0.075646 (-0.065816) | 0.079810 / 0.419271 (-0.339461) | 0.055291 / 0.043533 (0.011758) | 0.464093 / 0.255139 (0.208954) | 0.481109 / 0.283200 (0.197910) | 0.026909 / 0.141683 (-0.114774) | 1.652538 / 1.452155 (0.200383) | 1.750713 / 1.492716 (0.257997) |\n\n### Benchmark: benchmark_getitem\\_100B.json\n\n| metric | get_batch_of\\_1024\\_random_rows | get_batch_of\\_1024\\_rows | get_first_row | get_last_row |\n|--------|---|---|---|---|\n| new / old (diff) | 0.267552 / 0.018006 (0.249546) | 0.502021 / 0.000490 (0.501531) | 0.001635 / 0.000200 (0.001435) | 0.000099 / 0.000054 (0.000044) |\n\n### Benchmark: benchmark_indices_mapping.json\n\n| metric | select | shard | shuffle | sort | train_test_split |\n|--------|---|---|---|---|---|\n| new / old (diff) | 0.033747 / 0.037411 (-0.003665) | 0.104242 / 0.014526 (0.089716) | 0.113829 / 0.176557 (-0.062728) | 0.176242 / 0.737135 (-0.560893) | 0.117002 / 0.296338 (-0.179336) |\n\n### Benchmark: benchmark_iterating.json\n\n| metric | read 5000 | read 50000 | read_batch 50000 10 | read_batch 50000 100 | read_batch 50000 1000 | read_formatted numpy 5000 | read_formatted pandas 5000 | read_formatted tensorflow 5000 | read_formatted torch 5000 | read_formatted_batch numpy 5000 10 | read_formatted_batch numpy 5000 1000 | shuffled read 5000 | shuffled read 50000 | shuffled read_batch 50000 10 | shuffled read_batch 50000 100 | shuffled read_batch 50000 1000 | shuffled read_formatted numpy 5000 | shuffled read_formatted_batch numpy 5000 10 | shuffled read_formatted_batch numpy 5000 1000 |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.476731 / 0.215209 (0.261522) | 4.727054 / 2.077655 (2.649399) | 2.589396 / 1.504120 (1.085276) | 2.511180 / 1.541195 (0.969985) | 2.634122 / 1.468490 (1.165632) | 0.563840 / 4.584777 (-4.020937) | 4.140212 / 3.745712 (0.394500) | 6.188789 / 5.269862 (0.918928) | 3.716897 / 4.565676 (-0.848780) | 0.065823 / 0.424275 (-0.358452) | 0.007705 / 0.007607 (0.000098) | 0.566580 / 0.226044 (0.340535) | 5.653306 / 2.268929 (3.384377) | 3.028756 / 55.444624 (-52.415868) | 2.592319 / 6.876477 (-4.284158) | 2.614250 / 2.142072 (0.472178) | 0.667135 / 4.805227 (-4.138093) | 0.153455 / 6.500664 (-6.347209) | 0.069321 / 0.075469 (-0.006148) |\n\n### Benchmark: benchmark_map_filter.json\n\n| metric | filter | map fast-tokenizer batched | map identity | map identity batched | map no-op batched | map no-op batched numpy | map no-op batched pandas | map no-op batched pytorch | map no-op batched tensorflow |\n|--------|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 1.541978 / 1.841788 (-0.299810) | 21.747360 / 8.074308 (13.673052) | 15.963657 / 10.191392 (5.772265) | 0.192843 / 0.680424 (-0.487581) | 0.020702 / 0.534201 (-0.513499) | 0.433620 / 0.579283 (-0.145663) | 0.467327 / 0.434364 (0.032963) | 0.507398 / 0.540337 (-0.032940) | 0.692797 / 1.386936 (-0.694140) |\n\n</details>\n</details>\n\n![](https://cml.dev/watermark.png#396cf9419d12e3150e2051793b10f2c813780a90 "CML watermark")\n', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1625176426/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'lau

[{'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1607379408', 'html_url': 'https://github.com/huggingface/datasets/issues/5985#issuecomment-1607379408', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5985', 'id': 1607379408, 'node_id': 'IC_kwDODunzps5fzqnQ', 'user': {'login': 'mariosasko', 'id': 47462742, 'node_id': 'MDQ6VXNlcjQ3NDYyNzQy', 'avatar_url': 'https://avatars.githubusercontent.com/u/47462742?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/mariosasko', 'html_url': 'https://github.com/mariosasko', 'followers_url': 'https://api.github.com/users/mariosasko/followers', 'following_url': 'https://api.github.com/users/mariosasko/following{/other_user}', 'gists_url': 'https://api.github.com/users/mariosasko/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/mariosasko/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/mariosasko/subscriptions', 'organizations_url': 'https://api.github.com/users/mariosasko/orgs', 'repos_url': 'https://api.github.com/users/mariosasko/repos', 'events_url': 'https://api.github.com/users/mariosasko/events{/privacy}', 'received_events_url': 'https://api.github.com/users/mariosasko/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-26T12:34:44Z', 'updated_at': '2023-06-26T12:34:44Z', 'author_association': 'CONTRIBUTOR', 'body': 'This is a known issue: https://github.com/huggingface/datasets/issues/3847.\r\n\r\nFixing this requires significant work - rewriting the `tokenizers` lib to make them immutable.\r\n\r\nThe current solution is to pass `cache_file_name` to `map` to use that file for caching or calling a tokenizer before `map` (with the same set of parameters as the ones in the map transform)', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1607379408/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}]
[{'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1607962103', 'html_url': 'https://github.com/huggingface/datasets/issues/5984#issuecomment-1607962103', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5984', 'id': 1607962103, 'node_id': 'IC_kwDODunzps5f1433', 'user': {'login': 'mariosasko', 'id': 47462742, 'node_id': 'MDQ6VXNlcjQ3NDYyNzQy', 'avatar_url': 'https://avatars.githubusercontent.com/u/47462742?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/mariosasko', 'html_url': 'https://github.com/mariosasko', 'followers_url': 'https://api.github.com/users/mariosasko/followers', 'following_url': 'https://api.github.com/users/mariosasko/following{/other_user}', 'gists_url': 'https://api.github.com/users/mariosasko/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/mariosasko/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/mariosasko/subscriptions', 'organizations_url': 'https://api.github.com/users/mariosasko/orgs', 'repos_url': 'https://api.github.com/users/mariosasko/repos', 'events_url': 'https://api.github.com/users/mariosasko/events{/privacy}', 'received_events_url': 'https://api.github.com/users/mariosasko/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-26T17:59:25Z', 'updated_at': '2023-06-26T17:59:25Z', 'author_association': 'CONTRIBUTOR', 'body': 'For this to be possible, we would have to switch from the "Streaming" Arrow format to the "Random Access" (IPC/Feather) format, which allows reading arbitrary record batches (explained [here](https://arrow.apache.org/docs/python/ipc.html)). We could then use these batches to construct shards.\r\n\r\n@lhoestq @albertvillanova Do you think this use case is worth the switch? Also, we currently shard files, not inner row groups/chunks. Should we also support sharding row groups (e.g. if the number of input files is 1)?\r\n\r\nPS: I don\'t expect significant speed-up for local, uncompressed Arrow files.', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1607962103/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1609426767', 'html_url': 'https://github.com/huggingface/datasets/issues/5984#issuecomment-1609426767', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5984', 'id': 1609426767, 'node_id': 'IC_kwDODunzps5f7edP', 'user': {'login': 'lhoestq', 'id': 42851186, 'node_id': 'MDQ6VXNlcjQyODUxMTg2', 'avatar_url': 'https://avatars.githubusercontent.com/u/42851186?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/lhoestq', 'html_url': 'https://github.com/lhoestq', 'followers_url': 'https://api.github.com/users/lhoestq/followers', 'following_url': 'https://api.github.com/users/lhoestq/following{/other_user}', 'gists_url': 'https://api.github.com/users/lhoestq/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/lhoestq/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/lhoestq/subscriptions', 'organizations_url': 'https://api.github.com/users/lhoestq/orgs', 'repos_url': 'https://api.github.com/users/lhoestq/repos', 'events_url': 'https://api.github.com/users/lhoestq/events{/privacy}', 'received_events_url': 'https://api.github.com/users/lhoestq/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-27T12:42:17Z', 'updated_at': '2023-06-27T12:42:17Z', 'author_association': 'MEMBER', 'body': 'Alternatively we could support multiprocessing map for iterable datasets and let the user do the CPU intensive task there ?\r\n\r\nThis way it would work on arrow data but also on any iterable dataset', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1609426767/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1620234926', 'html_url': 'https://github.com/huggingface/datasets/issues/5984#issuecomment-1620234926', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5984', 'id': 1620234926, 'node_id': 'IC_kwDODunzps5gktKu', 'user': {'login': 'imarquart', 'id': 102803372, 'node_id': 'U_kgDOBiCnrA', 'avatar_url': 'https://avatars.githubusercontent.com/u/102803372?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/imarquart', 'html_url': 'https://github.com/imarquart', 'followers_url': 'https://api.github.com/users/imarquart/followers', 'following_url': 'https://api.github.com/users/imarquart/following{/other_user}', 'gists_url': 'https://api.github.com/users/imarquart/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/imarquart/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/imarquart/subscriptions', 'organizations_url': 'https://api.github.com/users/imarquart/orgs', 'repos_url': 'https://api.github.com/users/imarquart/repos', 'events_url': 'https://api.github.com/users/imarquart/events{/privacy}', 'received_events_url': 'https://api.github.com/users/imarquart/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-07-04T13:16:11Z', 'updated_at': '2023-07-04T13:16:11Z', 'author_association': 'NONE', 'body': '> For this to be possible, we would have to switch from the "Streaming" Arrow format to the "Random Access" (IPC/Feather) format, which allows reading arbitrary record batches (explained [here](https://arrow.apache.org/docs/python/ipc.html)). We could then use these batches to construct shards.\r\n> \r\n> @lhoestq @albertvillanova Do you think this use case is worth the switch? Also, we currently shard files, not inner row groups/chunks. Should we also support sharding row groups (e.g. if the number of input files is 1)?\r\n> \r\n> PS: I don\'t expect significant speed-up for local, uncompressed Arrow files.\r\n\r\nCould you explain why you\'d need to change the arrow format?\r\n\r\nWhen we use streaming datasets we simply determine the number of worker shards and then add some modulo logic at the appropriate place. Worst case scenario, you\'d skip streaming entries according to the number of shards.\r\n\r\nFor PyTorch, I\'d be happy to provide an implementation or a sketch thereof, if you point me toward what the testing requirements would be for such a PR.', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1620234926/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1620457064', 'html_url': 'https://github.com/huggingface/datasets/issues/5984#issuecomment-1620457064', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5984', 'id': 1620457064, 'node_id': 'IC_kwDODunzps5gljZo', 'user': {'login': 'lhoestq', 'id': 42851186, 'node_id': 'MDQ6VXNlcjQyODUxMTg2', 'avatar_url': 'https://avatars.githubusercontent.com/u/42851186?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/lhoestq', 'html_url': 'https://github.com/lhoestq', 'followers_url': 'https://api.github.com/users/lhoestq/followers', 'following_url': 'https://api.github.com/users/lhoestq/following{/other_user}', 'gists_url': 'https://api.github.com/users/lhoestq/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/lhoestq/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/lhoestq/subscriptions', 'organizations_url': 'https://api.github.com/users/lhoestq/orgs', 'repos_url': 'https://api.github.com/users/lhoestq/repos', 'events_url': 'https://api.github.com/users/lhoestq/events{/privacy}', 'received_events_url': 'https://api.github.com/users/lhoestq/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-07-04T15:35:17Z', 'updated_at': '2023-07-04T15:35:17Z', 'author_association': 'MEMBER', 'body': "> Could you explain why you'd need to change the arrow format?\r\n\r\nThis way workers have random access to the location of the file where its dataset subset starts. Currently we're using the Arrow streaming format which doesn't include the metadata of the record batches offsets. This is needed here to efficiently split a dataset made of one single file.", 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1620457064/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1620513876', 'html_url': 'https://github.com/huggingface/datasets/issues/5984#issuecomment-1620513876', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5984', 'id': 1620513876, 'node_id': 'IC_kwDODunzps5glxRU', 'user': {'login': 'imarquart', 'id': 102803372, 'node_id': 'U_kgDOBiCnrA', 'avatar_url': 'https://avatars.githubusercontent.com/u/102803372?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/imarquart', 'html_url': 'https://github.com/imarquart', 'followers_url': 'https://api.github.com/users/imarquart/followers', 'following_url': 'https://api.github.com/users/imarquart/following{/other_user}', 'gists_url': 'https://api.github.com/users/imarquart/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/imarquart/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/imarquart/subscriptions', 'organizations_url': 'https://api.github.com/users/imarquart/orgs', 'repos_url': 'https://api.github.com/users/imarquart/repos', 'events_url': 'https://api.github.com/users/imarquart/events{/privacy}', 'received_events_url': 'https://api.github.com/users/imarquart/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-07-04T16:28:12Z', 'updated_at': '2023-07-04T16:29:48Z', 'author_association': 'NONE', 'body': "> > Could you explain why you'd need to change the arrow format?\r\n> \r\n> This way workers have random access to the location of the file where its dataset subset starts. Currently we're using the Arrow streaming format which doesn't include the metadata of the record batches offsets. This is needed here to efficiently split a dataset made of one single file.\r\n\r\nI guess I don't understand why you'd need to subset the dataset in the first place. \r\nIt seems sufficient to figure out how to offset or skip rows.\r\n\r\nFor instance, using pyArrow, you could use RecordBatchStreamReader to zero-copy iterate over records with read_next_batch and then only initiate the next step for records modulo worker shard.\r\nThat's one way to do it, where of course you'd need to account for gpu sharding as well.\r\n\r\n\r\nOtherwise, how did you implement worker/node/GPU sharding for iterable/streaming data where you do not have index information or prior splits (e.g. files)?", 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1620513876/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1620544051', 'html_url': 'https://github.com/huggingface/datasets/issues/5984#issuecomment-1620544051', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5984', 'id': 1620544051, 'node_id': 'IC_kwDODunzps5gl4oz', 'user': {'login': 'lhoestq', 'id': 42851186, 'node_id': 'MDQ6VXNlcjQyODUxMTg2', 'avatar_url': 'https://avatars.githubusercontent.com/u/42851186?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/lhoestq', 'html_url': 'https://github.com/lhoestq', 'followers_url': 'https://api.github.com/users/lhoestq/followers', 'following_url': 'https://api.github.com/users/lhoestq/following{/other_user}', 'gists_url': 'https://api.github.com/users/lhoestq/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/lhoestq/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/lhoestq/subscriptions', 'organizations_url': 'https://api.github.com/users/lhoestq/orgs', 'repos_url': 'https://api.github.com/users/lhoestq/repos', 'events_url': 'https://api.github.com/users/lhoestq/events{/privacy}', 'received_events_url': 'https://api.github.com/users/lhoestq/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-07-04T17:03:55Z', 'updated_at': '2023-07-04T17:03:55Z', 'author_association': 'MEMBER', 'body': '> For instance, using pyArrow, you could use RecordBatchStreamReader to zero-copy iterate over records with read_next_batch and then only initiate the next step for records modulo worker shard.\r\n\r\nThat works indeed ! And what we meant is that you can make it even faster to instantiate. Indeed using RecordBatchStreamReader you need to get the list of all the record batches in each worker, whereas you could just get the list of record batches per worker if you use the record batches locations in the Arrow IPC file footer. This would be especially appreciated to have a fast instantiation in case you have tens of thousands of Arrow files for example.', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1620544051/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}]

[]
[{'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1603492683', 'html_url': 'https://github.com/huggingface/datasets/issues/5982#issuecomment-1603492683', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5982', 'id': 1603492683, 'node_id': 'IC_kwDODunzps5fk1tL', 'user': {'login': 'abzdel', 'id': 55398496, 'node_id': 'MDQ6VXNlcjU1Mzk4NDk2', 'avatar_url': 'https://avatars.githubusercontent.com/u/55398496?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/abzdel', 'html_url': 'https://github.com/abzdel', 'followers_url': 'https://api.github.com/users/abzdel/followers', 'following_url': 'https://api.github.com/users/abzdel/following{/other_user}', 'gists_url': 'https://api.github.com/users/abzdel/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/abzdel/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/abzdel/subscriptions', 'organizations_url': 'https://api.github.com/users/abzdel/orgs', 'repos_url': 'https://api.github.com/users/abzdel/repos', 'events_url': 'https://api.github.com/users/abzdel/events{/privacy}', 'received_events_url': 'https://api.github.com/users/abzdel/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-23T01:01:39Z', 'updated_at': '2023-06-23T01:01:39Z', 'author_association': 'NONE', 'body': 'This wasn’t working for me a bit earlier, but it looks to be back up now', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1603492683/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1607748879', 'html_url': 'https://github.com/huggingface/datasets/issues/5982#issuecomment-1607748879', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5982', 'id': 1607748879, 'node_id': 'IC_kwDODunzps5f1E0P', 'user': {'login': 'mariosasko', 'id': 47462742, 'node_id': 'MDQ6VXNlcjQ3NDYyNzQy', 'avatar_url': 'https://avatars.githubusercontent.com/u/47462742?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/mariosasko', 'html_url': 'https://github.com/mariosasko', 'followers_url': 'https://api.github.com/users/mariosasko/followers', 'following_url': 'https://api.github.com/users/mariosasko/following{/other_user}', 'gists_url': 'https://api.github.com/users/mariosasko/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/mariosasko/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/mariosasko/subscriptions', 'organizations_url': 'https://api.github.com/users/mariosasko/orgs', 'repos_url': 'https://api.github.com/users/mariosasko/repos', 'events_url': 'https://api.github.com/users/mariosasko/events{/privacy}', 'received_events_url': 'https://api.github.com/users/mariosasko/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-26T15:44:55Z', 'updated_at': '2023-06-26T15:44:55Z', 'author_association': 'CONTRIBUTOR', 'body': 'We had a minor issue updating the docs after the latest release. It should work now :).', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1607748879/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}]
[{'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1607811182', 'html_url': 'https://github.com/huggingface/datasets/issues/5981#issuecomment-1607811182', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5981', 'id': 1607811182, 'node_id': 'IC_kwDODunzps5f1UBu', 'user': {'login': 'mariosasko', 'id': 47462742, 'node_id': 'MDQ6VXNlcjQ3NDYyNzQy', 'avatar_url': 'https://avatars.githubusercontent.com/u/47462742?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/mariosasko', 'html_url': 'https://github.com/mariosasko', 'followers_url': 'https://api.github.com/users/mariosasko/followers', 'following_url': 'https://api.github.com/users/mariosasko/following{/other_user}', 'gists_url': 'https://api.github.com/users/mariosasko/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/mariosasko/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/mariosasko/subscriptions', 'organizations_url': 'https://api.github.com/users/mariosasko/orgs', 'repos_url': 'https://api.github.com/users/mariosasko/repos', 'events_url': 'https://api.github.com/users/mariosasko/events{/privacy}', 'received_events_url': 'https://api.github.com/users/mariosasko/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-26T16:17:43Z', 'updated_at': '2023-06-26T16:19:40Z', 'author_association': 'CONTRIBUTOR', 'body': "I think it's more likely that this issue is related to PyTorch than Datasets, as PyTorch (on import) registers functions to execute when forking a process. Maybe this is the culprit: https://github.com/pytorch/pytorch/issues/99625", 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1607811182/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1608140952', 'html_url': 'https://github.com/huggingface/datasets/issues/5981#issuecomment-1608140952', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5981', 'id': 1608140952, 'node_id': 'IC_kwDODunzps5f2kiY', 'user': {'login': 'mmr-crexi', 'id': 107141022, 'node_id': 'U_kgDOBmLXng', 'avatar_url': 'https://avatars.githubusercontent.com/u/107141022?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/mmr-crexi', 'html_url': 'https://github.com/mmr-crexi', 'followers_url': 'https://api.github.com/users/mmr-crexi/followers', 'following_url': 'https://api.github.com/users/mmr-crexi/following{/other_user}', 'gists_url': 'https://api.github.com/users/mmr-crexi/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/mmr-crexi/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/mmr-crexi/subscriptions', 'organizations_url': 'https://api.github.com/users/mmr-crexi/orgs', 'repos_url': 'https://api.github.com/users/mmr-crexi/repos', 'events_url': 'https://api.github.com/users/mmr-crexi/events{/privacy}', 'received_events_url': 'https://api.github.com/users/mmr-crexi/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-26T19:53:47Z', 'updated_at': '2023-06-26T19:53:47Z', 'author_association': 'NONE', 'body': "From reading that ticket, it may be down in mkl?  Is it worth hotfixing in the meantime, with the express intention of turning it off?  I know that's a horribly crufty solution, but it's also deeply frustrating to be limited to 2 cores for operations as simple as filtration.", 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1608140952/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1624002338', 'html_url': 'https://github.com/huggingface/datasets/issues/5981#issuecomment-1624002338', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5981', 'id': 1624002338, 'node_id': 'IC_kwDODunzps5gzE8i', 'user': {'login': 'mariosasko', 'id': 47462742, 'node_id': 'MDQ6VXNlcjQ3NDYyNzQy', 'avatar_url': 'https://avatars.githubusercontent.com/u/47462742?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/mariosasko', 'html_url': 'https://github.com/mariosasko', 'followers_url': 'https://api.github.com/users/mariosasko/followers', 'following_url': 'https://api.github.com/users/mariosasko/following{/other_user}', 'gists_url': 'https://api.github.com/users/mariosasko/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/mariosasko/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/mariosasko/subscriptions', 'organizations_url': 'https://api.github.com/users/mariosasko/orgs', 'repos_url': 'https://api.github.com/users/mariosasko/repos', 'events_url': 'https://api.github.com/users/mariosasko/events{/privacy}', 'received_events_url': 'https://api.github.com/users/mariosasko/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-07-06T16:53:33Z', 'updated_at': '2023-07-06T16:53:33Z', 'author_association': 'CONTRIBUTOR', 'body': "This is too specific and unrelated to `datasets`, so this shouldn't be fixed here.", 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1624002338/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}]

[{'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1607442854', 'html_url': 'https://github.com/huggingface/datasets/issues/5980#issuecomment-1607442854', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5980', 'id': 1607442854, 'node_id': 'IC_kwDODunzps5fz6Gm', 'user': {'login': 'mariosasko', 'id': 47462742, 'node_id': 'MDQ6VXNlcjQ3NDYyNzQy', 'avatar_url': 'https://avatars.githubusercontent.com/u/47462742?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/mariosasko', 'html_url': 'https://github.com/mariosasko', 'followers_url': 'https://api.github.com/users/mariosasko/followers', 'following_url': 'https://api.github.com/users/mariosasko/following{/other_user}', 'gists_url': 'https://api.github.com/users/mariosasko/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/mariosasko/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/mariosasko/subscriptions', 'organizations_url': 'https://api.github.com/users/mariosasko/orgs', 'repos_url': 'https://api.github.com/users/mariosasko/repos', 'events_url': 'https://api.github.com/users/mariosasko/events{/privacy}', 'received_events_url': 'https://api.github.com/users/mariosasko/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-26T13:11:05Z', 'updated_at': '2023-06-26T13:11:05Z', 'author_association': 'CONTRIBUTOR', 'body': 'Can you try again? Maybe there was a minor outage.', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1607442854/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1607636780', 'html_url': 'https://github.com/huggingface/datasets/issues/5980#issuecomment-1607636780', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5980', 'id': 1607636780, 'node_id': 'IC_kwDODunzps5f0pcs', 'user': {'login': 'tbenthompson', 'id': 4241811, 'node_id': 'MDQ6VXNlcjQyNDE4MTE=', 'avatar_url': 'https://avatars.githubusercontent.com/u/4241811?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/tbenthompson', 'html_url': 'https://github.com/tbenthompson', 'followers_url': 'https://api.github.com/users/tbenthompson/followers', 'following_url': 'https://api.github.com/users/tbenthompson/following{/other_user}', 'gists_url': 'https://api.github.com/users/tbenthompson/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/tbenthompson/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/tbenthompson/subscriptions', 'organizations_url': 'https://api.github.com/users/tbenthompson/orgs', 'repos_url': 'https://api.github.com/users/tbenthompson/repos', 'events_url': 'https://api.github.com/users/tbenthompson/events{/privacy}', 'received_events_url': 'https://api.github.com/users/tbenthompson/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-26T14:42:45Z', 'updated_at': '2023-06-26T14:42:45Z', 'author_association': 'NONE', 'body': "Yes, it seems to be working now. In case it's helpful, the outage lasted several days. It was failing as late as yesterday morning. ", 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1607636780/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1609049454', 'html_url': 'https://github.com/huggingface/datasets/issues/5980#issuecomment-1609049454', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5980', 'id': 1609049454, 'node_id': 'IC_kwDODunzps5f6CVu', 'user': {'login': 'julien-c', 'id': 326577, 'node_id': 'MDQ6VXNlcjMyNjU3Nw==', 'avatar_url': 'https://avatars.githubusercontent.com/u/326577?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/julien-c', 'html_url': 'https://github.com/julien-c', 'followers_url': 'https://api.github.com/users/julien-c/followers', 'following_url': 'https://api.github.com/users/julien-c/following{/other_user}', 'gists_url': 'https://api.github.com/users/julien-c/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/julien-c/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/julien-c/subscriptions', 'organizations_url': 'https://api.github.com/users/julien-c/orgs', 'repos_url': 'https://api.github.com/users/julien-c/repos', 'events_url': 'https://api.github.com/users/julien-c/events{/privacy}', 'received_events_url': 'https://api.github.com/users/julien-c/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-27T08:38:19Z', 'updated_at': '2023-06-27T08:38:19Z', 'author_association': 'MEMBER', 'body': "we fixed something on the server side, glad it's fixed now", 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1609049454/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}]

[{'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1603128738', 'html_url': 'https://github.com/huggingface/datasets/pull/5978#issuecomment-1603128738', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5978', 'id': 1603128738, 'node_id': 'IC_kwDODunzps5fjc2i', 'user': {'login': 'HuggingFaceDocBuilderDev', 'id': 99929124, 'node_id': 'U_kgDOBfTMJA', 'avatar_url': 'https://avatars.githubusercontent.com/u/99929124?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/HuggingFaceDocBuilderDev', 'html_url': 'https://github.com/HuggingFaceDocBuilderDev', 'followers_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/followers', 'following_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/following{/other_user}', 'gists_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/subscriptions', 'organizations_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/orgs', 'repos_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/repos', 'events_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/events{/privacy}', 'received_events_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-22T18:28:14Z', 'updated_at': '2023-06-22T18:30:44Z', 'author_association': 'NONE', 'body': '_The documentation is not available anymore as the PR was closed or merged._', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1603128738/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1603130676', 'html_url': 'https://github.com/huggingface/datasets/pull/5978#issuecomment-1603130676', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5978', 'id': 1603130676, 'node_id': 'IC_kwDODunzps5fjdU0', 'user': {'login': 'github-actions[bot]', 'id': 41898282, 'node_id': 'MDM6Qm90NDE4OTgyODI=', 'avatar_url': 'https://avatars.githubusercontent.com/in/15368?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/github-actions%5Bbot%5D', 'html_url': 'https://github.com/apps/github-actions', 'followers_url': 'https://api.github.com/users/github-actions%5Bbot%5D/followers', 'following_url': 'https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}', 'gists_url': 'https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/github-actions%5Bbot%5D/subscriptions', 'organizations_url': 'https://api.github.com/users/github-actions%5Bbot%5D/orgs', 'repos_url': 'https://api.github.com/users/github-actions%5Bbot%5D/repos', 'events_url': 'https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}', 'received_events_url': 'https://api.github.com/users/github-actions%5Bbot%5D/received_events', 'type': 'Bot', 'site_admin': False}, 'created_at': '2023-06-22T18:29:56Z', 'updated_at': '2023-06-22T18:29:56Z', 'author_association': 'NONE', 'body': '<details>\n<summary>Show benchmarks</summary>\n\nPyArrow==8.0.0\n\n<details>\n<summary>Show updated benchmarks!</summary>\n\n### Benchmark: benchmark_array_xd.json\n\n| metric | read_batch_formatted_as_numpy after write_array2d | read_batch_formatted_as_numpy after write_flattened_sequence | read_batch_formatted_as_numpy after write_nested_sequence | read_batch_unformated after write_array2d | read_batch_unformated after write_flattened_sequence | read_batch_unformated after write_nested_sequence | read_col_formatted_as_numpy after write_array2d | read_col_formatted_as_numpy after write_flattened_sequence | read_col_formatted_as_numpy after write_nested_sequence | read_col_unformated after write_array2d | read_col_unformated after write_flattened_sequence | read_col_unformated after write_nested_sequence | read_formatted_as_numpy after write_array2d | read_formatted_as_numpy after write_flattened_sequence | read_formatted_as_numpy after write_nested_sequence | read_unformated after write_array2d | read_unformated after write_flattened_sequence | read_unformated after write_nested_sequence | write_array2d | write_flattened_sequence | write_nested_sequence |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.006173 / 0.011353 (-0.005180) | 0.003773 / 0.011008 (-0.007235) | 0.099499 / 0.038508 (0.060991) | 0.037918 / 0.023109 (0.014809) | 0.321329 / 0.275898 (0.045431) | 0.379739 / 0.323480 (0.056259) | 0.004664 / 0.007986 (-0.003322) | 0.002943 / 0.004328 (-0.001385) | 0.077759 / 0.004250 (0.073509) | 0.055271 / 0.037052 (0.018219) | 0.329428 / 0.258489 (0.070939) | 0.378731 / 0.293841 (0.084890) | 0.027737 / 0.128546 (-0.100810) | 0.008566 / 0.075646 (-0.067081) | 0.313220 / 0.419271 (-0.106052) | 0.047101 / 0.043533 (0.003568) | 0.316211 / 0.255139 (0.061072) | 0.341826 / 0.283200 (0.058626) | 0.020838 / 0.141683 (-0.120845) | 1.550064 / 1.452155 (0.097909) | 1.706518 / 1.492716 (0.213801) |\n\n### Benchmark: benchmark_getitem\\_100B.json\n\n| metric | get_batch_of\\_1024\\_random_rows | get_batch_of\\_1024\\_rows | get_first_row | get_last_row |\n|--------|---|---|---|---|\n| new / old (diff) | 0.203093 / 0.018006 (0.185087) | 0.425345 / 0.000490 (0.424856) | 0.004800 / 0.000200 (0.004600) | 0.000077 / 0.000054 (0.000022) |\n\n### Benchmark: benchmark_indices_mapping.json\n\n| metric | select | shard | shuffle | sort | train_test_split |\n|--------|---|---|---|---|---|\n| new / old (diff) | 0.024590 / 0.037411 (-0.012821) | 0.098115 / 0.014526 (0.083589) | 0.108274 / 0.176557 (-0.068282) | 0.170804 / 0.737135 (-0.566332) | 0.110560 / 0.296338 (-0.185778) |\n\n### Benchmark: benchmark_iterating.json\n\n| metric | read 5000 | read 50000 | read_batch 50000 10 | read_batch 50000 100 | read_batch 50000 1000 | read_formatted numpy 5000 | read_formatted pandas 5000 | read_formatted tensorflow 5000 | read_formatted torch 5000 | read_formatted_batch numpy 5000 10 | read_formatted_batch numpy 5000 1000 | shuffled read 5000 | shuffled read 50000 | shuffled read_batch 50000 10 | shuffled read_batch 50000 100 | shuffled read_batch 50000 1000 | shuffled read_formatted numpy 5000 | shuffled read_formatted_batch numpy 5000 10 | shuffled read_formatted_batch numpy 5000 1000 |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.425251 / 0.215209 (0.210042) | 4.239075 / 2.077655 (2.161421) | 1.955601 / 1.504120 (0.451481) | 1.774796 / 1.541195 (0.233602) | 1.826641 / 1.468490 (0.358150) | 0.558777 / 4.584777 (-4.026000) | 3.361697 / 3.745712 (-0.384015) | 1.764468 / 5.269862 (-3.505394) | 1.032280 / 4.565676 (-3.533396) | 0.067872 / 0.424275 (-0.356403) | 0.010998 / 0.007607 (0.003391) | 0.525682 / 0.226044 (0.299637) | 5.254356 / 2.268929 (2.985427) | 2.384332 / 55.444624 (-53.060292) | 2.045578 / 6.876477 (-4.830898) | 2.170914 / 2.142072 (0.028841) | 0.674782 / 4.805227 (-4.130445) | 0.135351 / 6.500664 (-6.365314) | 0.066591 / 0.075469 (-0.008878) |\n\n### Benchmark: benchmark_map_filter.json\n\n| metric | filter | map fast-tokenizer batched | map identity | map identity batched | map no-op batched | map no-op batched numpy | map no-op batched pandas | map no-op batched pytorch | map no-op batched tensorflow |\n|--------|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 1.209181 / 1.841788 (-0.632606) | 14.044518 / 8.074308 (5.970210) | 13.184705 / 10.191392 (2.993313) | 0.130836 / 0.680424 (-0.549588) | 0.016582 / 0.534201 (-0.517619) | 0.360005 / 0.579283 (-0.219279) | 0.379519 / 0.434364 (-0.054845) | 0.422174 / 0.540337 (-0.118164) | 0.515546 / 1.386936 (-0.871390) |\n\n</details>\nPyArrow==latest\n\n<details>\n<summary>Show updated benchmarks!</summary>\n\n### Benchmark: benchmark_array_xd.json\n\n| metric | read_batch_formatted_as_numpy after write_array2d | read_batch_formatted_as_numpy after write_flattened_sequence | read_batch_formatted_as_numpy after write_nested_sequence | read_batch_unformated after write_array2d | read_batch_unformated after write_flattened_sequence | read_batch_unformated after write_nested_sequence | read_col_formatted_as_numpy after write_array2d | read_col_formatted_as_numpy after write_flattened_sequence | read_col_formatted_as_numpy after write_nested_sequence | read_col_unformated after write_array2d | read_col_unformated after write_flattened_sequence | read_col_unformated after write_nested_sequence | read_formatted_as_numpy after write_array2d | read_formatted_as_numpy after write_flattened_sequence | read_formatted_as_numpy after write_nested_sequence | read_unformated after write_array2d | read_unformated after write_flattened_sequence | read_unformated after write_nested_sequence | write_array2d | write_flattened_sequence | write_nested_sequence |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.006293 / 0.011353 (-0.005060) | 0.003784 / 0.011008 (-0.007224) | 0.079248 / 0.038508 (0.040739) | 0.038452 / 0.023109 (0.015343) | 0.444727 / 0.275898 (0.168829) | 0.500535 / 0.323480 (0.177055) | 0.003455 / 0.007986 (-0.004531) | 0.002873 / 0.004328 (-0.001455) | 0.077439 / 0.004250 (0.073189) | 0.047855 / 0.037052 (0.010803) | 0.448049 / 0.258489 (0.189560) | 0.509517 / 0.293841 (0.215676) | 0.028359 / 0.128546 (-0.100188) | 0.008503 / 0.075646 (-0.067143) | 0.084961 / 0.419271 (-0.334310) | 0.042880 / 0.043533 (-0.000653) | 0.436628 / 0.255139 (0.181489) | 0.456574 / 0.283200 (0.173375) | 0.019539 / 0.141683 (-0.122144) | 1.561273 / 1.452155 (0.109118) | 1.572018 / 1.492716 (0.079301) |\n\n### Benchmark: benchmark_getitem\\_100B.json\n\n| metric | get_batch_of\\_1024\\_random_rows | get_batch_of\\_1024\\_rows | get_first_row | get_last_row |\n|--------|---|---|---|---|\n| new / old (diff) | 0.230250 / 0.018006 (0.212244) | 0.415189 / 0.000490 (0.414700) | 0.003213 / 0.000200 (0.003013) | 0.000080 / 0.000054 (0.000026) |\n\n### Benchmark: benchmark_indices_mapping.json\n\n| metric | select | shard | shuffle | sort | train_test_split |\n|--------|---|---|---|---|---|\n| new / old (diff) | 0.025541 / 0.037411 (-0.011871) | 0.102326 / 0.014526 (0.087800) | 0.110258 / 0.176557 (-0.066298) | 0.162488 / 0.737135 (-0.574647) | 0.112782 / 0.296338 (-0.183556) |\n\n### Benchmark: benchmark_iterating.json\n\n| metric | read 5000 | read 50000 | read_batch 50000 10 | read_batch 50000 100 | read_batch 50000 1000 | read_formatted numpy 5000 | read_formatted pandas 5000 | read_formatted tensorflow 5000 | read_formatted torch 5000 | read_formatted_batch numpy 5000 10 | read_formatted_batch numpy 5000 1000 | shuffled read 5000 | shuffled read 50000 | shuffled read_batch 50000 10 | shuffled read_batch 50000 100 | shuffled read_batch 50000 1000 | shuffled read_formatted numpy 5000 | shuffled read_formatted_batch numpy 5000 10 | shuffled read_formatted_batch numpy 5000 1000 |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.457936 / 0.215209 (0.242727) | 4.581503 / 2.077655 (2.503848) | 2.237659 / 1.504120 (0.733540) | 2.029960 / 1.541195 (0.488765) | 2.082911 / 1.468490 (0.614421) | 0.556485 / 4.584777 (-4.028292) | 3.384418 / 3.745712 (-0.361295) | 1.748809 / 5.269862 (-3.521053) | 1.034759 / 4.565676 (-3.530917) | 0.067500 / 0.424275 (-0.356776) | 0.011425 / 0.007607 (0.003818) | 0.561340 / 0.226044 (0.335295) | 5.623629 / 2.268929 (3.354701) | 2.733587 / 55.444624 (-52.711038) | 2.401578 / 6.876477 (-4.474899) | 2.524569 / 2.142072 (0.382496) | 0.673170 / 4.805227 (-4.132057) | 0.136681 / 6.500664 (-6.363983) | 0.068060 / 0.075469 (-0.007409) |\n\n### Benchmark: benchmark_map_filter.json\n\n| metric | filter | map fast-tokenizer batched | map identity | map identity batched | map no-op batched | map no-op batched numpy | map no-op batched pandas | map no-op batched pytorch | map no-op batched tensorflow |\n|--------|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 1.318651 / 1.841788 (-0.523137) | 14.362123 / 8.074308 (6.287815) | 14.385964 / 10.191392 (4.194572) | 0.149914 / 0.680424 (-0.530510) | 0.016877 / 0.534201 (-0.517324) | 0.358406 / 0.579283 (-0.220877) | 0.394349 / 0.434364 (-0.040015) | 0.422471 / 0.540337 (-0.117866) | 0.513807 / 1.386936 (-0.873129) |\n\n</details>\n</details>\n\n![](https://cml.dev/watermark.png#1b9ce11d1b94e6178df663ff5fcad029849d10fb "CML watermark")\n', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1603130676/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1603138535', 'html_url': 'https://github.com/huggingface/datasets/pull/5978#issuecomment-1603138535', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5978', 'id': 1603138535, 'node_id': 'IC_kwDODunzps5fjfPn', 'user': {'login': 'github-actions[bot]', 'id': 41898282, 'node_id': 'MDM6Qm90NDE4OTgyODI=', 'avatar_url': 'https://avatars.githubusercontent.com/in/15368?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/github-actions%5Bbot%5D', 'html_url': 'https://github.com/apps/github-actions', 'followers_url': 'https://api.github.com/users/github-actions%5Bbot%5D/followers', 'following_url': 'https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}', 'gists_url': 'https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/github-actions%5Bbot%5D/subscriptions', 'organizations_url': 'https://api.github.com/users/github-actions%5Bbot%5D/orgs', 'repos_url': 'https://api.github.com/users/github-actions%5Bbot%5D/repos', 'events_url': 'https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}', 'received_events_url': 'https://api.github.com/users/github-actions%5Bbot%5D/received_events', 'type': 'Bot', 'site_admin': False}, 'created_at': '2023-06-22T18:37:13Z', 'updated_at': '2023-06-22T18:37:13Z', 'author_association': 'NONE', 'body': '<details>\n<summary>Show benchmarks</summary>\n\nPyArrow==8.0.0\n\n<details>\n<summary>Show updated benchmarks!</summary>\n\n### Benchmark: benchmark_array_xd.json\n\n| metric | read_batch_formatted_as_numpy after write_array2d | read_batch_formatted_as_numpy after write_flattened_sequence | read_batch_formatted_as_numpy after write_nested_sequence | read_batch_unformated after write_array2d | read_batch_unformated after write_flattened_sequence | read_batch_unformated after write_nested_sequence | read_col_formatted_as_numpy after write_array2d | read_col_formatted_as_numpy after write_flattened_sequence | read_col_formatted_as_numpy after write_nested_sequence | read_col_unformated after write_array2d | read_col_unformated after write_flattened_sequence | read_col_unformated after write_nested_sequence | read_formatted_as_numpy after write_array2d | read_formatted_as_numpy after write_flattened_sequence | read_formatted_as_numpy after write_nested_sequence | read_unformated after write_array2d | read_unformated after write_flattened_sequence | read_unformated after write_nested_sequence | write_array2d | write_flattened_sequence | write_nested_sequence |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.006272 / 0.011353 (-0.005080) | 0.003903 / 0.011008 (-0.007105) | 0.100180 / 0.038508 (0.061672) | 0.037799 / 0.023109 (0.014690) | 0.385627 / 0.275898 (0.109729) | 0.446518 / 0.323480 (0.123038) | 0.004811 / 0.007986 (-0.003175) | 0.003032 / 0.004328 (-0.001296) | 0.077063 / 0.004250 (0.072812) | 0.055564 / 0.037052 (0.018512) | 0.397346 / 0.258489 (0.138857) | 0.443242 / 0.293841 (0.149401) | 0.027904 / 0.128546 (-0.100642) | 0.008386 / 0.075646 (-0.067260) | 0.315013 / 0.419271 (-0.104259) | 0.047943 / 0.043533 (0.004410) | 0.378443 / 0.255139 (0.123304) | 0.411472 / 0.283200 (0.128272) | 0.020465 / 0.141683 (-0.121218) | 1.526594 / 1.452155 (0.074439) | 1.547018 / 1.492716 (0.054301) |\n\n### Benchmark: benchmark_getitem\\_100B.json\n\n| metric | get_batch_of\\_1024\\_random_rows | get_batch_of\\_1024\\_rows | get_first_row | get_last_row |\n|--------|---|---|---|---|\n| new / old (diff) | 0.219377 / 0.018006 (0.201370) | 0.430254 / 0.000490 (0.429764) | 0.003218 / 0.000200 (0.003018) | 0.000072 / 0.000054 (0.000017) |\n\n### Benchmark: benchmark_indices_mapping.json\n\n| metric | select | shard | shuffle | sort | train_test_split |\n|--------|---|---|---|---|---|\n| new / old (diff) | 0.023667 / 0.037411 (-0.013744) | 0.099143 / 0.014526 (0.084617) | 0.106044 / 0.176557 (-0.070513) | 0.166186 / 0.737135 (-0.570949) | 0.108736 / 0.296338 (-0.187603) |\n\n### Benchmark: benchmark_iterating.json\n\n| metric | read 5000 | read 50000 | read_batch 50000 10 | read_batch 50000 100 | read_batch 50000 1000 | read_formatted numpy 5000 | read_formatted pandas 5000 | read_formatted tensorflow 5000 | read_formatted torch 5000 | read_formatted_batch numpy 5000 10 | read_formatted_batch numpy 5000 1000 | shuffled read 5000 | shuffled read 50000 | shuffled read_batch 50000 10 | shuffled read_batch 50000 100 | shuffled read_batch 50000 1000 | shuffled read_formatted numpy 5000 | shuffled read_formatted_batch numpy 5000 10 | shuffled read_formatted_batch numpy 5000 1000 |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.437971 / 0.215209 (0.222762) | 4.363675 / 2.077655 (2.286021) | 2.011993 / 1.504120 (0.507873) | 1.845189 / 1.541195 (0.303994) | 1.831848 / 1.468490 (0.363358) | 0.562402 / 4.584777 (-4.022375) | 3.365259 / 3.745712 (-0.380453) | 1.781491 / 5.269862 (-3.488371) | 1.023454 / 4.565676 (-3.542223) | 0.067857 / 0.424275 (-0.356418) | 0.011076 / 0.007607 (0.003469) | 0.532267 / 0.226044 (0.306223) | 5.340344 / 2.268929 (3.071415) | 2.388649 / 55.444624 (-53.055976) | 2.055373 / 6.876477 (-4.821104) | 2.205047 / 2.142072 (0.062975) | 0.672909 / 4.805227 (-4.132318) | 0.135244 / 6.500664 (-6.365420) | 0.066184 / 0.075469 (-0.009285) |\n\n### Benchmark: benchmark_map_filter.json\n\n| metric | filter | map fast-tokenizer batched | map identity | map identity batched | map no-op batched | map no-op batched numpy | map no-op batched pandas | map no-op batched pytorch | map no-op batched tensorflow |\n|--------|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 1.206838 / 1.841788 (-0.634950) | 13.967075 / 8.074308 (5.892767) | 13.143971 / 10.191392 (2.952579) | 0.143991 / 0.680424 (-0.536433) | 0.016673 / 0.534201 (-0.517527) | 0.376180 / 0.579283 (-0.203103) | 0.386550 / 0.434364 (-0.047814) | 0.440590 / 0.540337 (-0.099747) | 0.529974 / 1.386936 (-0.856962) |\n\n</details>\nPyArrow==latest\n\n<details>\n<summary>Show updated benchmarks!</summary>\n\n### Benchmark: benchmark_array_xd.json\n\n| metric | read_batch_formatted_as_numpy after write_array2d | read_batch_formatted_as_numpy after write_flattened_sequence | read_batch_formatted_as_numpy after write_nested_sequence | read_batch_unformated after write_array2d | read_batch_unformated after write_flattened_sequence | read_batch_unformated after write_nested_sequence | read_col_formatted_as_numpy after write_array2d | read_col_formatted_as_numpy after write_flattened_sequence | read_col_formatted_as_numpy after write_nes

[{'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1602969800', 'html_url': 'https://github.com/huggingface/datasets/pull/5976#issuecomment-1602969800', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5976', 'id': 1602969800, 'node_id': 'IC_kwDODunzps5fi2DI', 'user': {'login': 'lhoestq', 'id': 42851186, 'node_id': 'MDQ6VXNlcjQyODUxMTg2', 'avatar_url': 'https://avatars.githubusercontent.com/u/42851186?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/lhoestq', 'html_url': 'https://github.com/lhoestq', 'followers_url': 'https://api.github.com/users/lhoestq/followers', 'following_url': 'https://api.github.com/users/lhoestq/following{/other_user}', 'gists_url': 'https://api.github.com/users/lhoestq/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/lhoestq/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/lhoestq/subscriptions', 'organizations_url': 'https://api.github.com/users/lhoestq/orgs', 'repos_url': 'https://api.github.com/users/lhoestq/repos', 'events_url': 'https://api.github.com/users/lhoestq/events{/privacy}', 'received_events_url': 'https://api.github.com/users/lhoestq/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-22T16:24:35Z', 'updated_at': '2023-06-22T16:24:35Z', 'author_association': 'MEMBER', 'body': 'Hi ! Do you think this can be fixed at the Pool level ? Ideally it should be the Pool responsibility to handle this, not the `map` code. We could even subclass Pool if needed (at least the one from `multiprocess`)', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1602969800/reactions', 'total_count': 1, '+1': 1, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1606119332', 'html_url': 'https://github.com/huggingface/datasets/pull/5976#issuecomment-1606119332', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5976', 'id': 1606119332, 'node_id': 'IC_kwDODunzps5fu2-k', 'user': {'login': 'pappacena', 'id': 1213561, 'node_id': 'MDQ6VXNlcjEyMTM1NjE=', 'avatar_url': 'https://avatars.githubusercontent.com/u/1213561?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/pappacena', 'html_url': 'https://github.com/pappacena', 'followers_url': 'https://api.github.com/users/pappacena/followers', 'following_url': 'https://api.github.com/users/pappacena/following{/other_user}', 'gists_url': 'https://api.github.com/users/pappacena/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/pappacena/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/pappacena/subscriptions', 'organizations_url': 'https://api.github.com/users/pappacena/orgs', 'repos_url': 'https://api.github.com/users/pappacena/repos', 'events_url': 'https://api.github.com/users/pappacena/events{/privacy}', 'received_events_url': 'https://api.github.com/users/pappacena/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-25T14:48:23Z', 'updated_at': '2023-06-25T14:48:23Z', 'author_association': 'CONTRIBUTOR', 'body': '@lhoestq it makes sense to me. Just pushed a refactoring creating a `class ProcessPool(multiprocess.pool.Pool)` to keep track of the PID changes.', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1606119332/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1607198049', 'html_url': 'https://github.com/huggingface/datasets/pull/5976#issuecomment-1607198049', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5976', 'id': 1607198049, 'node_id': 'IC_kwDODunzps5fy-Vh', 'user': {'login': 'HuggingFaceDocBuilderDev', 'id': 99929124, 'node_id': 'U_kgDOBfTMJA', 'avatar_url': 'https://avatars.githubusercontent.com/u/99929124?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/HuggingFaceDocBuilderDev', 'html_url': 'https://github.com/HuggingFaceDocBuilderDev', 'followers_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/followers', 'following_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/following{/other_user}', 'gists_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/subscriptions', 'organizations_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/orgs', 'repos_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/repos', 'events_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/events{/privacy}', 'received_events_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-26T10:46:58Z', 'updated_at': '2023-07-10T09:50:40Z', 'author_association': 'NONE', 'body': '_The documentation is not available anymore as the PR was closed or merged._', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1607198049/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1607366435', 'html_url': 'https://github.com/huggingface/datasets/pull/5976#issuecomment-1607366435', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5976', 'id': 1607366435, 'node_id': 'IC_kwDODunzps5fzncj', 'user': {'login': 'lhoestq', 'id': 42851186, 'node_id': 'MDQ6VXNlcjQyODUxMTg2', 'avatar_url': 'https://avatars.githubusercontent.com/u/42851186?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/lhoestq', 'html_url': 'https://github.com/lhoestq', 'followers_url': 'https://api.github.com/users/lhoestq/followers', 'following_url': 'https://api.github.com/users/lhoestq/following{/other_user}', 'gists_url': 'https://api.github.com/users/lhoestq/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/lhoestq/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/lhoestq/subscriptions', 'organizations_url': 'https://api.github.com/users/lhoestq/orgs', 'repos_url': 'https://api.github.com/users/lhoestq/repos', 'events_url': 'https://api.github.com/users/lhoestq/events{/privacy}', 'received_events_url': 'https://api.github.com/users/lhoestq/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-26T12:25:28Z', 'updated_at': '2023-06-26T12:27:27Z', 'author_association': 'MEMBER', 'body': 'I managed to raise an error without subclassing Pool with two additions to `iflatmap_unordered`:\r\n\r\n1. at the beggining\r\n```python\r\noriginal_pool = list(pool._pool)\r\n```\r\n\r\n2. in the loop\r\n```python\r\nif any(async_result._pool != original_pool for async_result in async_results) and queue.empty():\r\n    raise RuntimeError(\r\n        "One of the subprocesses has abruptly died during map operation."\r\n        "To debug the error, disable multiprocessing."\r\n    )\r\n```\r\n\r\nIt\'s still a fix that only works for `iflatmap_unordered` (so not for map, imap etc) but is maybe simpler that subclassing. It also works for both multiprocessing.Pool and multiprocess.Pool', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1607366435/reactions', 'total_count': 1, '+1': 1, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1622608115', 'html_url': 'https://github.com/huggingface/datasets/pull/5976#issuecomment-1622608115', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5976', 'id': 1622608115, 'node_id': 'IC_kwDODunzps5gtwjz', 'user': {'login': 'pappacena', 'id': 1213561, 'node_id': 'MDQ6VXNlcjEyMTM1NjE=', 'avatar_url': 'https://avatars.githubusercontent.com/u/1213561?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/pappacena', 'html_url': 'https://github.com/pappacena', 'followers_url': 'https://api.github.com/users/pappacena/followers', 'following_url': 'https://api.github.com/users/pappacena/following{/other_user}', 'gists_url': 'https://api.github.com/users/pappacena/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/pappacena/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/pappacena/subscriptions', 'organizations_url': 'https://api.github.com/users/pappacena/orgs', 'repos_url': 'https://api.github.com/users/pappacena/repos', 'events_url': 'https://api.github.com/users/pappacena/events{/privacy}', 'received_events_url': 'https://api.github.com/users/pappacena/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-07-05T22:21:37Z', 'updated_at': '2023-07-05T22:21:37Z', 'author_association': 'CONTRIBUTOR', 'body': '@lhoestq sorry for the delay. Busy weeks here. \r\n\r\nI just pushed the change you requested. It looks closer to the original proposal, actually.\r\n\r\nIt seems that `map` actually uses `iflatmap_unordered` ([here](https://github.com/huggingface/datasets/blob/819bb4346434912eb405ce3f3e9f21dc25a2fe85/src/datasets/arrow_dataset.py#L1509)). I think this solution works fine for the `map` method (which is the one being tested by the new `tests/test_arrow_dataset.py::BaseDatasetTest::test_map_crash_subprocess`, right?).', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1622608115/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1623363297', 'html_url': 'https://github.com/huggingface/datasets/pull/5976#issuecomment-1623363297', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5976', 'id': 1623363297, 'node_id': 'IC_kwDODunzps5gwo7h', 'user': {'login': 'lhoestq', 'id': 42851186, 'node_id': 'MDQ6VXNlcjQyODUxMTg2', 'avatar_url': 'https://avatars.githubusercontent.com/u/42851186?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/lhoestq', 'html_url': 'https://github.com/lhoestq', 'followers_url': 'https://api.github.com/users/lhoestq/followers', 'following_url': 'https://api.github.com/users/lhoestq/following{/other_user}', 'gists_url': 'https://api.github.com/users/lhoestq/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/lhoestq/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/lhoestq/subscriptions', 'organizations_url': 'https://api.github.com/users/lhoestq/orgs', 'repos_url': 'https://api.github.com/users/lhoestq/repos', 'events_url': 'https://api.github.com/users/lhoestq/events{/privacy}', 'received_events_url': 'https://api.github.com/users/lhoestq/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-07-06T09:42:44Z', 'updated_at': '2023-07-06T09:42:44Z', 'author_association': 'MEMBER', 'body': "Yes fixing iflatmap_unordered does fix Dataset.map, but it won't fix any Pool.map that we may use elsewhere so we'll have to keep this in mind.", 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1623363297/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1623417396', 'html_url': 'https://github.com/huggingface/datasets/pull/5976#issuecomment-1623417396', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5976', 'id': 1623417396, 'node_id': 'IC_kwDODunzps5gw2I0', 'user': {'login': 'lhoestq', 'id': 42851186, 'node_id': 'MDQ6VXNlcjQyODUxMTg2', 'avatar_url': 'https://avatars.githubusercontent.com/u/42851186?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/lhoestq', 'html_url': 'https://github.com/lhoestq', 'followers_url': 'https://api.github.com/users/lhoestq/followers', 'following_url': 'https://api.github.com/users/lhoestq/following{/other_user}', 'gists_url': 'https://api.github.com/users/lhoestq/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/lhoestq/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/lhoestq/subscriptions', 'organizations_url': 'https://api.github.com/users/lhoestq/orgs', 'repos_url': 'https://api.github.com/users/lhoestq/repos', 'events_url': 'https://api.github.com/users/lhoestq/events{/privacy}', 'received_events_url': 'https://api.github.com/users/lhoestq/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-07-06T10:20:47Z', 'updated_at': '2023-07-06T10:20:47Z', 'author_association': 'MEMBER', 'body': 'It looks all good to me, feel free to fix code formatting by running `make style` and we can merge :)', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1623417396/reactions', 'total_count': 1, '+1': 1, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1623652642', 'html_url': 'https://github.com/huggingface/datasets/pull/5976#issuecomment-1623652642', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5976', 'id': 1623652642, 'node_id': 'IC_kwDODunzps5gxvki', 'user': {'login': 'pappacena', 'id': 1213561, 'node_id': 'MDQ6VXNlcjEyMTM1NjE=', 'avatar_url': 'https://avatars.githubusercontent.com/u/1213561?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/pappacena', 'html_url': 'https://github.com/pappacena', 'followers_url': 'https://api.github.com/users/pappacena/followers', 'following_url': 'https://api.github.com/users/pappacena/following{/other_user}', 'gists_url': 'https://api.github.com/users/pappacena/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/pappacena/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/pappacena/subscriptions', 'organizations_url': 'https://api.github.com/users/pappacena/orgs', 'repos_url': 'https://api.github.com/users/pappacena/repos', 'events_url': 'https://api.github.com/users/pappacena/events{/privacy}', 'received_events_url': 'https://api.github.com/users/pappacena/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-07-06T13:09:11Z', 'updated_at': '2023-07-06T13:09:11Z', 'author_association': 'CONTRIBUTOR', 'body': "> Yes fixing iflatmap_unordered does fix Dataset.map, but it won't fix any Pool.map that we may use elsewhere so we'll have to keep this in mind.\r\n\r\nRight, I agree. The best way moving forward is probably not using the buggy `multiprocess.Pool` anymore, and replace it with `concurrent.futures.ProcessPoolExecutor` as much as possible.\r\n\r\nAnyway, I've run `make style` now. Thanks for the support!", 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1623652642/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1623863963', 'html_url': 'https://github.com/huggingface/datasets/pull/5976#issuecomment-1623863963', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5976', 'id': 1623863963, 'node_id': 'IC_kwDODunzps5gyjKb', 'user': {'login': 'lhoestq', 'id': 42851186, 'node_id': 'MDQ6VXNlcjQyODUxMTg2', 'avatar_url': 'https://avatars.githubusercontent.com/u/42851186?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/lhoestq', 'html_url': 'https://github.com/lhoestq', 'followers_url': 'https://api.github.com/users/lhoestq/followers', 'following_url': 'https://api.github.com/users/lhoestq/following{/other_user}', 'gists_url': 'https://api.github.com/users/lhoestq/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/lhoestq/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/lhoestq/subscriptions', 'organizations_url': 'https://api.github.com/users/lhoestq/orgs', 'repos_url': 'https://api.github.com/users/lhoestq/repos', 'events_url': 'https://api.github.com/users/lhoestq/events{/privacy}', 'received_events_url': 'https://api.github.com/users/lhoestq/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-07-06T15:17:14Z', 'updated_at': '2023-07-06T15:17:14Z', 'author_association': 'MEMBER', 'body': "It looks like checking the async_result._pool doesn't always work - sorry about that. We might just go back to your original solution then. Would also be cool to open an issue in `multiprocess` to ask if they have a solution or if they plan to fix this.", 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1623863963/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1624454056', 'html_url': 'https://github.com/huggingface/datasets/pull/5976#issuecomment-1624454056', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5976', 'id': 1624454056, 'node_id': 'IC_kwDODunzps5g0zOo', 'user': {'login': 'pappacena', 'id': 1213561, 'node_id': 'MDQ6VXNlcjEyMTM1NjE=', 'avatar_url': 'https://avatars.githubusercontent.com/u/1213561?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/pappacena', 'html_url': 'https://github.com/pappacena', 'followers_url': 'https://api.github.com/users/pappacena/followers', 'following_url': 'https://api.github.com/users/pappacena/following{/other_user}', 'gists_url': 'https://api.github.com/users/pappacena/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/pappacena/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/pappacena/subscriptions', 'organizations_url': 'https://api.github.com/users/pappacena/orgs', 'repos_url': 'https://api.github.com/users/pappacena/repos', 'events_url': 'https://api.github.com/users/pappacena/events{/privacy}', 'received_events_url': 'https://api.github.com/users/pappacena/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-07-07T00:03:47Z', 'updated_at': '2023-07-07T00:03:47Z', 'author_association': 'CONTRIBUTOR', 'body': "@lhoestq no problem! Reverted to the previous version.\r\n\r\nTBH, given the discussions [in this python issue](https://github.com/python/cpython/issues/66587), I don't think the error in `multiprocess` will be merged upstream any time soon...", 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1624454056/reactions', 'total_count': 1, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 1, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1628626592', 'html_url': 'https://github.com/huggingface/datasets/pull/5976#issuecomment-1628626592', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5976', 'id': 1628626592, 'node_id': 'IC_kwDODunzps5hEt6g', 'user': {'login': 'github-actions[bot]', 'id': 41898282, 'node_id': 'MDM6Qm90NDE4OTgyODI=', 'avatar_url': 'https://avatars.githubusercontent.com/in/15368?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/github-actions%5Bbot%5D', 'html_url': 'https://github.com/apps/github-actions', 'followers_url': 'https://api.github.com/use

[{'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1601738997', 'html_url': 'https://github.com/huggingface/datasets/issues/5975#issuecomment-1601738997', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5975', 'id': 1601738997, 'node_id': 'IC_kwDODunzps5feJj1', 'user': {'login': 'Krystianp00000', 'id': 88916743, 'node_id': 'MDQ6VXNlcjg4OTE2NzQz', 'avatar_url': 'https://avatars.githubusercontent.com/u/88916743?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/Krystianp00000', 'html_url': 'https://github.com/Krystianp00000', 'followers_url': 'https://api.github.com/users/Krystianp00000/followers', 'following_url': 'https://api.github.com/users/Krystianp00000/following{/other_user}', 'gists_url': 'https://api.github.com/users/Krystianp00000/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/Krystianp00000/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/Krystianp00000/subscriptions', 'organizations_url': 'https://api.github.com/users/Krystianp00000/orgs', 'repos_url': 'https://api.github.com/users/Krystianp00000/repos', 'events_url': 'https://api.github.com/users/Krystianp00000/events{/privacy}', 'received_events_url': 'https://api.github.com/users/Krystianp00000/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-21T22:02:05Z', 'updated_at': '2023-06-21T22:02:05Z', 'author_association': 'NONE', 'body': 'Duplicate of #', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1601738997/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1602739485', 'html_url': 'https://github.com/huggingface/datasets/issues/5975#issuecomment-1602739485', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5975', 'id': 1602739485, 'node_id': 'IC_kwDODunzps5fh90d', 'user': {'login': 'lhoestq', 'id': 42851186, 'node_id': 'MDQ6VXNlcjQyODUxMTg2', 'avatar_url': 'https://avatars.githubusercontent.com/u/42851186?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/lhoestq', 'html_url': 'https://github.com/lhoestq', 'followers_url': 'https://api.github.com/users/lhoestq/followers', 'following_url': 'https://api.github.com/users/lhoestq/following{/other_user}', 'gists_url': 'https://api.github.com/users/lhoestq/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/lhoestq/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/lhoestq/subscriptions', 'organizations_url': 'https://api.github.com/users/lhoestq/orgs', 'repos_url': 'https://api.github.com/users/lhoestq/repos', 'events_url': 'https://api.github.com/users/lhoestq/events{/privacy}', 'received_events_url': 'https://api.github.com/users/lhoestq/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-22T14:27:08Z', 'updated_at': '2023-06-22T14:27:08Z', 'author_association': 'MEMBER', 'body': 'Hi ! can you try to set the upper case environment variables `HTTP_PROXY` and `HTTPS_PROXY` ?\r\n\r\nWe use `aiohttp` for streaming and it uses case sensitive environment variables', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1602739485/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1607244302', 'html_url': 'https://github.com/huggingface/datasets/issues/5975#issuecomment-1607244302', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5975', 'id': 1607244302, 'node_id': 'IC_kwDODunzps5fzJoO', 'user': {'login': 'Veluchs', 'id': 135350576, 'node_id': 'U_kgDOCBFJMA', 'avatar_url': 'https://avatars.githubusercontent.com/u/135350576?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/Veluchs', 'html_url': 'https://github.com/Veluchs', 'followers_url': 'https://api.github.com/users/Veluchs/followers', 'following_url': 'https://api.github.com/users/Veluchs/following{/other_user}', 'gists_url': 'https://api.github.com/users/Veluchs/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/Veluchs/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/Veluchs/subscriptions', 'organizations_url': 'https://api.github.com/users/Veluchs/orgs', 'repos_url': 'https://api.github.com/users/Veluchs/repos', 'events_url': 'https://api.github.com/users/Veluchs/events{/privacy}', 'received_events_url': 'https://api.github.com/users/Veluchs/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-26T11:12:30Z', 'updated_at': '2023-06-26T11:12:30Z', 'author_association': 'NONE', 'body': 'Hi, thanks for the quick reply.\r\n\r\nI set the uppercase env variables with\r\n\r\n`\r\nos.environ[\'HTTP_PROXY\'] = "http://example.com:xxxx" \r\nos.environ[\'HTTPS_PROXY\'] = "http://example.com:xxxx" \r\n`\r\n\r\nHowever, I still get the same error.\r\n\r\nOne thing that could be helpfull: When downloading a dataset without streaming i get the following message:\r\n_HF google storage unreachable. Downloading and preparing it from source_.\r\nThe download does however work as expected.\r\n', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1607244302/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1607279202', 'html_url': 'https://github.com/huggingface/datasets/issues/5975#issuecomment-1607279202', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5975', 'id': 1607279202, 'node_id': 'IC_kwDODunzps5fzSJi', 'user': {'login': 'lhoestq', 'id': 42851186, 'node_id': 'MDQ6VXNlcjQyODUxMTg2', 'avatar_url': 'https://avatars.githubusercontent.com/u/42851186?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/lhoestq', 'html_url': 'https://github.com/lhoestq', 'followers_url': 'https://api.github.com/users/lhoestq/followers', 'following_url': 'https://api.github.com/users/lhoestq/following{/other_user}', 'gists_url': 'https://api.github.com/users/lhoestq/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/lhoestq/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/lhoestq/subscriptions', 'organizations_url': 'https://api.github.com/users/lhoestq/orgs', 'repos_url': 'https://api.github.com/users/lhoestq/repos', 'events_url': 'https://api.github.com/users/lhoestq/events{/privacy}', 'received_events_url': 'https://api.github.com/users/lhoestq/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-26T11:33:04Z', 'updated_at': '2023-06-26T11:33:04Z', 'author_association': 'MEMBER', 'body': 'Are you able to use `aiohttp` to get the file at `https://huggingface.co/datasets/facebook/voxpopuli/resolve/main/data/n_files.json` using your proxy ?', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1607279202/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1607369766', 'html_url': 'https://github.com/huggingface/datasets/issues/5975#issuecomment-1607369766', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5975', 'id': 1607369766, 'node_id': 'IC_kwDODunzps5fzoQm', 'user': {'login': 'Veluchs', 'id': 135350576, 'node_id': 'U_kgDOCBFJMA', 'avatar_url': 'https://avatars.githubusercontent.com/u/135350576?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/Veluchs', 'html_url': 'https://github.com/Veluchs', 'followers_url': 'https://api.github.com/users/Veluchs/followers', 'following_url': 'https://api.github.com/users/Veluchs/following{/other_user}', 'gists_url': 'https://api.github.com/users/Veluchs/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/Veluchs/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/Veluchs/subscriptions', 'organizations_url': 'https://api.github.com/users/Veluchs/orgs', 'repos_url': 'https://api.github.com/users/Veluchs/repos', 'events_url': 'https://api.github.com/users/Veluchs/events{/privacy}', 'received_events_url': 'https://api.github.com/users/Veluchs/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-26T12:27:59Z', 'updated_at': '2023-06-26T12:29:01Z', 'author_association': 'NONE', 'body': 'It only works when passing trust_env=True when creating the ClientSession, as well as setting ssl=False.\r\n\r\nWorking Example:\r\n\r\n```\r\nimport os\r\n\r\nos.environ[\'HTTP_PROXY\'] = "xyz"\r\nos.environ[\'HTTPS_PROXY\'] = "xyz"\r\n\r\nimport asyncio\r\nimport aiohttp\r\n\r\nasync def download_pep(url):\r\n    async with aiohttp.ClientSession(trust_env=True) as session:\r\n        print("1")\r\n        async with session.get(url, ssl=False) as resp:\r\n            print("2")\r\n            content = await resp.text()\r\n            print(content)\r\n            return content\r\n\r\nasyncio.run(download_pep("https://huggingface.co/datasets/facebook/voxpopuli/resolve/main/data/n_files.json"))\r\n```\r\n\r\n\r\n\r\nSSL Verification has been a problem with other packages as well. Usually I circumvent the problem by setting\r\n```\r\nimport ssl\r\nssl._create_default_https_context = ssl._create_unverified_context\r\n```\r\n(probably not the best idea for security), although here aiohttp does not seem to use this default context.', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1607369766/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1607391399', 'html_url': 'https://github.com/huggingface/datasets/issues/5975#issuecomment-1607391399', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5975', 'id': 1607391399, 'node_id': 'IC_kwDODunzps5fztin', 'user': {'login': 'lhoestq', 'id': 42851186, 'node_id': 'MDQ6VXNlcjQyODUxMTg2', 'avatar_url': 'https://avatars.githubusercontent.com/u/42851186?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/lhoestq', 'html_url': 'https://github.com/lhoestq', 'followers_url': 'https://api.github.com/users/lhoestq/followers', 'following_url': 'https://api.github.com/users/lhoestq/following{/other_user}', 'gists_url': 'https://api.github.com/users/lhoestq/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/lhoestq/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/lhoestq/subscriptions', 'organizations_url': 'https://api.github.com/users/lhoestq/orgs', 'repos_url': 'https://api.github.com/users/lhoestq/repos', 'events_url': 'https://api.github.com/users/lhoestq/events{/privacy}', 'received_events_url': 'https://api.github.com/users/lhoestq/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-26T12:43:33Z', 'updated_at': '2023-06-26T12:43:33Z', 'author_association': 'MEMBER', 'body': 'We do pass `trust_env` as well. Could you share the full stack trace you get when streaming using `datasets` ? That could help locate where we might have forgotten to pass `trust_env`', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1607391399/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1607403769', 'html_url': 'https://github.com/huggingface/datasets/issues/5975#issuecomment-1607403769', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5975', 'id': 1607403769, 'node_id': 'IC_kwDODunzps5fzwj5', 'user': {'login': 'Veluchs', 'id': 135350576, 'node_id': 'U_kgDOCBFJMA', 'avatar_url': 'https://avatars.githubusercontent.com/u/135350576?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/Veluchs', 'html_url': 'https://github.com/Veluchs', 'followers_url': 'https://api.github.com/users/Veluchs/followers', 'following_url': 'https://api.github.com/users/Veluchs/following{/other_user}', 'gists_url': 'https://api.github.com/users/Veluchs/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/Veluchs/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/Veluchs/subscriptions', 'organizations_url': 'https://api.github.com/users/Veluchs/orgs', 'repos_url': 'https://api.github.com/users/Veluchs/repos', 'events_url': 'https://api.github.com/users/Veluchs/events{/privacy}', 'received_events_url': 'https://api.github.com/users/Veluchs/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-26T12:52:08Z', 'updated_at': '2023-06-26T12:52:08Z', 'author_association': 'NONE', 'body': 'Is there a way to disable ssl verification when streaming a dataset. I suspect this might be the isssue with my proxy.\r\n\r\n\r\nHere you go:\r\n\r\n```\r\nFileNotFoundError                         Traceback (most recent call last)\r\nCell In[8], line 3\r\n      1 from datasets import load_dataset\r\n----> 3 ds = load_dataset("facebook/voxpopuli", name="de", streaming=True)\r\n      5 sample = next(iter(ds))\r\n\r\nFile [~/.conda/envs/audio_hf/lib/python3.10/site-packages/datasets/load.py:1790](https://vscode-remote+ssh-002dremote-002bml-002er-002dsoftware-002eat.vscode-resource.vscode-cdn.net/home/wrsbri/projects/audio_course/~/.conda/envs/audio_hf/lib/python3.10/site-packages/datasets/load.py:1790), in load_dataset(path, name, data_dir, data_files, split, cache_dir, features, download_config, download_mode, verification_mode, ignore_verifications, keep_in_memory, save_infos, revision, use_auth_token, task, streaming, num_proc, storage_options, **config_kwargs)\r\n   1788 # Return iterable dataset in case of streaming\r\n   1789 if streaming:\r\n-> 1790     return builder_instance.as_streaming_dataset(split=split)\r\n   1792 # Some datasets are already processed on the HF google storage\r\n   1793 # Don\'t try downloading from Google storage for the packaged datasets as text, json, csv or pandas\r\n   1794 try_from_hf_gcs = path not in _PACKAGED_DATASETS_MODULES\r\n\r\nFile [~/.conda/envs/audio_hf/lib/python3.10/site-packages/datasets/builder.py:1281](https://vscode-remote+ssh-002dremote-002bml-002er-002dsoftware-002eat.vscode-resource.vscode-cdn.net/home/wrsbri/projects/audio_course/~/.conda/envs/audio_hf/lib/python3.10/site-packages/datasets/builder.py:1281), in DatasetBuilder.as_streaming_dataset(self, split, base_path)\r\n   1274 dl_manager = StreamingDownloadManager(\r\n   1275     base_path=base_path or self.base_path,\r\n   1276     download_config=DownloadConfig(use_auth_token=self.use_auth_token, storage_options=self.storage_options),\r\n   1277     dataset_name=self.name,\r\n   1278     data_dir=self.config.data_dir,\r\n   1279 )\r\n   1280 self._check_manual_download(dl_manager)\r\n-> 1281 splits_generators = {sg.name: sg for sg in self._split_generators(dl_manager)}\r\n   1282 # By default, return all splits\r\n   1283 if split is None:\r\n\r\nFile [~/.cache/huggingface/modules/datasets_modules/datasets/facebook--voxpopuli/b5ff837284f0778eefe0f642734e142d8c3f574eba8c9c8a4b13602297f73604/voxpopuli.py:120](https://vscode-remote+ssh-002dremote-002bml-002er-002dsoftware-002eat.vscode-resource.vscode-cdn.net/home/wrsbri/projects/audio_course/~/.cache/huggingface/modules/datasets_modules/datasets/facebook--voxpopuli/b5ff837284f0778eefe0f642734e142d8c3f574eba8c9c8a4b13602297f73604/voxpopuli.py:120), in Voxpopuli._split_generators(self, dl_manager)\r\n    118 def _split_generators(self, dl_manager):\r\n    119     n_shards_path = dl_manager.download_and_extract(_N_SHARDS_FILE)\r\n--> 120     with open(n_shards_path) as f:\r\n    121         n_shards = json.load(f)\r\n    123     if self.config.name == "en_accented":\r\n\r\nFile [~/.conda/envs/audio_hf/lib/python3.10/site-packages/datasets/streaming.py:71](https://vscode-remote+ssh-002dremote-002bml-002er-002dsoftware-002eat.vscode-resource.vscode-cdn.net/home/wrsbri/projects/audio_course/~/.conda/envs/audio_hf/lib/python3.10/site-packages/datasets/streaming.py:71), in extend_module_for_streaming..wrap_auth..wrapper(*args, **kwargs)\r\n     69 @wraps(function)\r\n     70 def wrapper(*args, **kwargs):\r\n---> 71     return function(*args, use_auth_token=use_auth_token, **kwargs)\r\n\r\nFile [~/.conda/envs/audio_hf/lib/python3.10/site-packages/datasets/download/streaming_download_manager.py:517](https://vscode-remote+ssh-002dremote-002bml-002er-002dsoftware-002eat.vscode-resource.vscode-cdn.net/home/wrsbri/projects/audio_course/~/.conda/envs/audio_hf/lib/python3.10/site-packages/datasets/download/streaming_download_manager.py:517), in xopen(file, mode, use_auth_token, *args, **kwargs)\r\n    515 except FileNotFoundError:\r\n    516     if file.startswith(config.HF_ENDPOINT):\r\n--> 517         raise FileNotFoundError(\r\n    518             file + "\\nIf the repo is private or gated, make sure to log in with `huggingface-cli login`."\r\n    519         ) from None\r\n    520     else:\r\n    521         raise\r\n\r\nFileNotFoundError: https://huggingface.co/datasets/facebook/voxpopuli/resolve/main/data/n_files.json\r\nIf the repo is private or gated, make sure to log in with `huggingface-cli login`.\r\n```', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1607403769/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1607598308', 'html_url': 'https://github.com/huggingface/datasets/issues/5975#issuecomment-1607598308', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5975', 'id': 1607598308, 'node_id': 'IC_kwDODunzps5f0gDk', 'user': {'login': 'lhoestq', 'id': 42851186, 'node_id': 'MDQ6VXNlcjQyODUxMTg2', 'avatar_url': 'https://avatars.githubusercontent.com/u/42851186?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/lhoestq', 'html_url': 'https://github.com/lhoestq', 'followers_url': 'https://api.github.com/users/lhoestq/followers', 'following_url': 'https://api.github.com/users/lhoestq/following{/other_user}', 'gists_url': 'https://api.github.com/users/lhoestq/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/lhoestq/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/lhoestq/subscriptions', 'organizations_url': 'https://api.github.com/users/lhoestq/orgs', 'repos_url': 'https://api.github.com/users/lhoestq/repos', 'events_url': 'https://api.github.com/users/lhoestq/events{/privacy}', 'received_events_url': 'https://api.github.com/users/lhoestq/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-26T14:21:32Z', 'updated_at': '2023-06-26T14:21:32Z', 'author_association': 'MEMBER', 'body': "> Is there a way to disable ssl verification when streaming a dataset.\r\n\r\nI don't think so.\r\n\r\nWe use `fsspec` HTTPFileSystem implementation that is based on `aiohttp`. If you register a subclass of HTTPFileSystem that has SSL disabled by default it could work, but I wouldn't recommended it because it can raise security issues.", 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1607598308/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, '

[{'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1601171167', 'html_url': 'https://github.com/huggingface/datasets/pull/5974#issuecomment-1601171167', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5974', 'id': 1601171167, 'node_id': 'IC_kwDODunzps5fb-7f', 'user': {'login': 'HuggingFaceDocBuilderDev', 'id': 99929124, 'node_id': 'U_kgDOBfTMJA', 'avatar_url': 'https://avatars.githubusercontent.com/u/99929124?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/HuggingFaceDocBuilderDev', 'html_url': 'https://github.com/HuggingFaceDocBuilderDev', 'followers_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/followers', 'following_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/following{/other_user}', 'gists_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/subscriptions', 'organizations_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/orgs', 'repos_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/repos', 'events_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/events{/privacy}', 'received_events_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-21T16:37:53Z', 'updated_at': '2023-06-26T10:28:09Z', 'author_association': 'NONE', 'body': '_The documentation is not available anymore as the PR was closed or merged._', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1601171167/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1601171513', 'html_url': 'https://github.com/huggingface/datasets/pull/5974#issuecomment-1601171513', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5974', 'id': 1601171513, 'node_id': 'IC_kwDODunzps5fb_A5', 'user': {'login': 'github-actions[bot]', 'id': 41898282, 'node_id': 'MDM6Qm90NDE4OTgyODI=', 'avatar_url': 'https://avatars.githubusercontent.com/in/15368?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/github-actions%5Bbot%5D', 'html_url': 'https://github.com/apps/github-actions', 'followers_url': 'https://api.github.com/users/github-actions%5Bbot%5D/followers', 'following_url': 'https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}', 'gists_url': 'https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/github-actions%5Bbot%5D/subscriptions', 'organizations_url': 'https://api.github.com/users/github-actions%5Bbot%5D/orgs', 'repos_url': 'https://api.github.com/users/github-actions%5Bbot%5D/repos', 'events_url': 'https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}', 'received_events_url': 'https://api.github.com/users/github-actions%5Bbot%5D/received_events', 'type': 'Bot', 'site_admin': False}, 'created_at': '2023-06-21T16:38:10Z', 'updated_at': '2023-06-21T16:38:10Z', 'author_association': 'NONE', 'body': '<details>\n<summary>Show benchmarks</summary>\n\nPyArrow==8.0.0\n\n<details>\n<summary>Show updated benchmarks!</summary>\n\n### Benchmark: benchmark_array_xd.json\n\n| metric | read_batch_formatted_as_numpy after write_array2d | read_batch_formatted_as_numpy after write_flattened_sequence | read_batch_formatted_as_numpy after write_nested_sequence | read_batch_unformated after write_array2d | read_batch_unformated after write_flattened_sequence | read_batch_unformated after write_nested_sequence | read_col_formatted_as_numpy after write_array2d | read_col_formatted_as_numpy after write_flattened_sequence | read_col_formatted_as_numpy after write_nested_sequence | read_col_unformated after write_array2d | read_col_unformated after write_flattened_sequence | read_col_unformated after write_nested_sequence | read_formatted_as_numpy after write_array2d | read_formatted_as_numpy after write_flattened_sequence | read_formatted_as_numpy after write_nested_sequence | read_unformated after write_array2d | read_unformated after write_flattened_sequence | read_unformated after write_nested_sequence | write_array2d | write_flattened_sequence | write_nested_sequence |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.006518 / 0.011353 (-0.004835) | 0.004121 / 0.011008 (-0.006887) | 0.103350 / 0.038508 (0.064842) | 0.045030 / 0.023109 (0.021920) | 0.351670 / 0.275898 (0.075772) | 0.408110 / 0.323480 (0.084630) | 0.003883 / 0.007986 (-0.004102) | 0.003352 / 0.004328 (-0.000977) | 0.078786 / 0.004250 (0.074535) | 0.063977 / 0.037052 (0.026925) | 0.369759 / 0.258489 (0.111270) | 0.415103 / 0.293841 (0.121262) | 0.033069 / 0.128546 (-0.095477) | 0.008863 / 0.075646 (-0.066783) | 0.353660 / 0.419271 (-0.065611) | 0.055714 / 0.043533 (0.012181) | 0.350458 / 0.255139 (0.095319) | 0.369505 / 0.283200 (0.086305) | 0.022822 / 0.141683 (-0.118861) | 1.537588 / 1.452155 (0.085433) | 1.590569 / 1.492716 (0.097853) |\n\n### Benchmark: benchmark_getitem\\_100B.json\n\n| metric | get_batch_of\\_1024\\_random_rows | get_batch_of\\_1024\\_rows | get_first_row | get_last_row |\n|--------|---|---|---|---|\n| new / old (diff) | 0.206826 / 0.018006 (0.188819) | 0.471625 / 0.000490 (0.471135) | 0.005188 / 0.000200 (0.004988) | 0.000316 / 0.000054 (0.000261) |\n\n### Benchmark: benchmark_indices_mapping.json\n\n| metric | select | shard | shuffle | sort | train_test_split |\n|--------|---|---|---|---|---|\n| new / old (diff) | 0.028148 / 0.037411 (-0.009263) | 0.111941 / 0.014526 (0.097415) | 0.122106 / 0.176557 (-0.054451) | 0.181127 / 0.737135 (-0.556009) | 0.127534 / 0.296338 (-0.168805) |\n\n### Benchmark: benchmark_iterating.json\n\n| metric | read 5000 | read 50000 | read_batch 50000 10 | read_batch 50000 100 | read_batch 50000 1000 | read_formatted numpy 5000 | read_formatted pandas 5000 | read_formatted tensorflow 5000 | read_formatted torch 5000 | read_formatted_batch numpy 5000 10 | read_formatted_batch numpy 5000 1000 | shuffled read 5000 | shuffled read 50000 | shuffled read_batch 50000 10 | shuffled read_batch 50000 100 | shuffled read_batch 50000 1000 | shuffled read_formatted numpy 5000 | shuffled read_formatted_batch numpy 5000 10 | shuffled read_formatted_batch numpy 5000 1000 |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.409520 / 0.215209 (0.194311) | 4.098455 / 2.077655 (2.020800) | 1.852447 / 1.504120 (0.348327) | 1.657036 / 1.541195 (0.115842) | 1.709624 / 1.468490 (0.241134) | 0.542806 / 4.584777 (-4.041970) | 3.809352 / 3.745712 (0.063640) | 1.855412 / 5.269862 (-3.414449) | 1.109180 / 4.565676 (-3.456497) | 0.066801 / 0.424275 (-0.357474) | 0.011832 / 0.007607 (0.004225) | 0.518338 / 0.226044 (0.292293) | 5.190108 / 2.268929 (2.921179) | 2.320602 / 55.444624 (-53.124023) | 1.991416 / 6.876477 (-4.885060) | 2.106989 / 2.142072 (-0.035084) | 0.668914 / 4.805227 (-4.136313) | 0.145325 / 6.500664 (-6.355340) | 0.065145 / 0.075469 (-0.010324) |\n\n### Benchmark: benchmark_map_filter.json\n\n| metric | filter | map fast-tokenizer batched | map identity | map identity batched | map no-op batched | map no-op batched numpy | map no-op batched pandas | map no-op batched pytorch | map no-op batched tensorflow |\n|--------|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 1.254706 / 1.841788 (-0.587082) | 14.707264 / 8.074308 (6.632956) | 14.615423 / 10.191392 (4.424031) | 0.170764 / 0.680424 (-0.509659) | 0.017905 / 0.534201 (-0.516296) | 0.435606 / 0.579283 (-0.143677) | 0.434648 / 0.434364 (0.000284) | 0.520813 / 0.540337 (-0.019524) | 0.633902 / 1.386936 (-0.753034) |\n\n</details>\nPyArrow==latest\n\n<details>\n<summary>Show updated benchmarks!</summary>\n\n### Benchmark: benchmark_array_xd.json\n\n| metric | read_batch_formatted_as_numpy after write_array2d | read_batch_formatted_as_numpy after write_flattened_sequence | read_batch_formatted_as_numpy after write_nested_sequence | read_batch_unformated after write_array2d | read_batch_unformated after write_flattened_sequence | read_batch_unformated after write_nested_sequence | read_col_formatted_as_numpy after write_array2d | read_col_formatted_as_numpy after write_flattened_sequence | read_col_formatted_as_numpy after write_nested_sequence | read_col_unformated after write_array2d | read_col_unformated after write_flattened_sequence | read_col_unformated after write_nested_sequence | read_formatted_as_numpy after write_array2d | read_formatted_as_numpy after write_flattened_sequence | read_formatted_as_numpy after write_nested_sequence | read_unformated after write_array2d | read_unformated after write_flattened_sequence | read_unformated after write_nested_sequence | write_array2d | write_flattened_sequence | write_nested_sequence |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.007212 / 0.011353 (-0.004141) | 0.004301 / 0.011008 (-0.006707) | 0.080767 / 0.038508 (0.042258) | 0.051949 / 0.023109 (0.028840) | 0.398473 / 0.275898 (0.122575) | 0.465038 / 0.323480 (0.141558) | 0.005580 / 0.007986 (-0.002406) | 0.003556 / 0.004328 (-0.000773) | 0.080682 / 0.004250 (0.076431) | 0.059517 / 0.037052 (0.022464) | 0.421171 / 0.258489 (0.162682) | 0.459752 / 0.293841 (0.165911) | 0.032960 / 0.128546 (-0.095586) | 0.009107 / 0.075646 (-0.066539) | 0.086382 / 0.419271 (-0.332889) | 0.056053 / 0.043533 (0.012520) | 0.393357 / 0.255139 (0.138218) | 0.412972 / 0.283200 (0.129772) | 0.031115 / 0.141683 (-0.110568) | 1.576961 / 1.452155 (0.124806) | 1.627249 / 1.492716 (0.134533) |\n\n### Benchmark: benchmark_getitem\\_100B.json\n\n| metric | get_batch_of\\_1024\\_random_rows | get_batch_of\\_1024\\_rows | get_first_row | get_last_row |\n|--------|---|---|---|---|\n| new / old (diff) | 0.227618 / 0.018006 (0.209612) | 0.444640 / 0.000490 (0.444150) | 0.004376 / 0.000200 (0.004176) | 0.000092 / 0.000054 (0.000038) |\n\n### Benchmark: benchmark_indices_mapping.json\n\n| metric | select | shard | shuffle | sort | train_test_split |\n|--------|---|---|---|---|---|\n| new / old (diff) | 0.030826 / 0.037411 (-0.006586) | 0.117587 / 0.014526 (0.103062) | 0.127467 / 0.176557 (-0.049089) | 0.184440 / 0.737135 (-0.552695) | 0.133664 / 0.296338 (-0.162675) |\n\n### Benchmark: benchmark_iterating.json\n\n| metric | read 5000 | read 50000 | read_batch 50000 10 | read_batch 50000 100 | read_batch 50000 1000 | read_formatted numpy 5000 | read_formatted pandas 5000 | read_formatted tensorflow 5000 | read_formatted torch 5000 | read_formatted_batch numpy 5000 10 | read_formatted_batch numpy 5000 1000 | shuffled read 5000 | shuffled read 50000 | shuffled read_batch 50000 10 | shuffled read_batch 50000 100 | shuffled read_batch 50000 1000 | shuffled read_formatted numpy 5000 | shuffled read_formatted_batch numpy 5000 10 | shuffled read_formatted_batch numpy 5000 1000 |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.443183 / 0.215209 (0.227974) | 4.408312 / 2.077655 (2.330658) | 2.132487 / 1.504120 (0.628367) | 1.923632 / 1.541195 (0.382438) | 1.967882 / 1.468490 (0.499392) | 0.552954 / 4.584777 (-4.031823) | 3.777701 / 3.745712 (0.031989) | 1.857686 / 5.269862 (-3.412176) | 1.104847 / 4.565676 (-3.460829) | 0.068350 / 0.424275 (-0.355925) | 0.012437 / 0.007607 (0.004830) | 0.559258 / 0.226044 (0.333214) | 5.593258 / 2.268929 (3.324330) | 2.648059 / 55.444624 (-52.796565) | 2.277428 / 6.876477 (-4.599049) | 2.351685 / 2.142072 (0.209612) | 0.678750 / 4.805227 (-4.126477) | 0.145550 / 6.500664 (-6.355114) | 0.066556 / 0.075469 (-0.008913) |\n\n### Benchmark: benchmark_map_filter.json\n\n| metric | filter | map fast-tokenizer batched | map identity | map identity batched | map no-op batched | map no-op batched numpy | map no-op batched pandas | map no-op batched pytorch | map no-op batched tensorflow |\n|--------|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 1.327128 / 1.841788 (-0.514659) | 15.649079 / 8.074308 (7.574771) | 14.478659 / 10.191392 (4.287267) | 0.147633 / 0.680424 (-0.532791) | 0.018502 / 0.534201 (-0.515699) | 0.438556 / 0.579283 (-0.140727) | 0.433381 / 0.434364 (-0.000983) | 0.514367 / 0.540337 (-0.025970) | 0.618347 / 1.386936 (-0.768589) |\n\n</details>\n</details>\n\n![](https://cml.dev/watermark.png#16aa1c886c5b499641a4bb3d8ce4a4f7de8244b7 "CML watermark")\n', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1601171513/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1607181987', 'html_url': 'https://github.com/huggingface/datasets/pull/5974#issuecomment-1607181987', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5974', 'id': 1607181987, 'node_id': 'IC_kwDODunzps5fy6aj', 'user': {'login': 'github-actions[bot]', 'id': 41898282, 'node_id': 'MDM6Qm90NDE4OTgyODI=', 'avatar_url': 'https://avatars.githubusercontent.com/in/15368?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/github-actions%5Bbot%5D', 'html_url': 'https://github.com/apps/github-actions', 'followers_url': 'https://api.github.com/users/github-actions%5Bbot%5D/followers', 'following_url': 'https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}', 'gists_url': 'https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/github-actions%5Bbot%5D/subscriptions', 'organizations_url': 'https://api.github.com/users/github-actions%5Bbot%5D/orgs', 'repos_url': 'https://api.github.com/users/github-actions%5Bbot%5D/repos', 'events_url': 'https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}', 'received_events_url': 'https://api.github.com/users/github-actions%5Bbot%5D/received_events', 'type': 'Bot', 'site_admin': False}, 'created_at': '2023-06-26T10:34:42Z', 'updated_at': '2023-06-26T10:34:42Z', 'author_association': 'NONE', 'body': '<details>\n<summary>Show benchmarks</summary>\n\nPyArrow==8.0.0\n\n<details>\n<summary>Show updated benchmarks!</summary>\n\n### Benchmark: benchmark_array_xd.json\n\n| metric | read_batch_formatted_as_numpy after write_array2d | read_batch_formatted_as_numpy after write_flattened_sequence | read_batch_formatted_as_numpy after write_nested_sequence | read_batch_unformated after write_array2d | read_batch_unformated after write_flattened_sequence | read_batch_unformated after write_nested_sequence | read_col_formatted_as_numpy after write_array2d | read_col_formatted_as_numpy after write_flattened_sequence | read_col_formatted_as_numpy after write_nested_sequence | read_col_unformated after write_array2d | read_col_unformated after write_flattened_sequence | read_col_unformated after write_nested_sequence | read_formatted_as_numpy after write_array2d | read_formatted_as_numpy after write_flattened_sequence | read_formatted_as_numpy after write_nested_sequence | read_unformated after write_array2d | read_unformated after write_flattened_sequence | read_unformated after write_nested_sequence | write_array2d | write_flattened_sequence | write_nested_sequence |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.006078 / 0.011353 (-0.005275) | 0.003914 / 0.011008 (-0.007095) | 0.102039 / 0.038508 (0.063531) | 0.037660 / 0.023109 (0.014551) | 0.348963 / 0.275898 (0.073065) | 0.407284 / 0.323480 (0.083804) | 0.004661 / 0.007986 (-0.003324) | 0.003253 / 0.004328 (-0.001076) | 0.078276 / 0.004250 (0.074025) | 0.054144 / 0.037052 (0.017091) | 0.376715 / 0.258489 (0.118225) | 0.418499 / 0.293841 (0.124658) | 0.027627 / 0.128546 (-0.100919) | 0.008494 / 0.075646 (-0.067152) | 0.316894 / 0.419271 (-0.102377) | 0.046560 / 0.043533 (0.003027) | 0.339835 / 0.255139 (0.084696) | 0.374628 / 0.283200 (0.091428) | 0.020729 / 0.141683 (-0.120954) | 1.502769 / 1.452155 (0.050615) | 1.548756 / 1.492716 (0.056040) |\n\n### Benchmark: benchmark_getitem\\_100B.json\n\n| metric | get_batch_of\\_1024\\_random_rows | get_batch_of\\_1024\\_rows | get_first_row | get_last_row |\n|--------|---|---|---|---|\n| new / old (diff) | 0.229192 / 0.018006 (0.211186) | 0.426245 / 0.000490 (0.425756) | 0.005190 / 0.000200 (0.004990) | 0.000081 / 0.000054 (0.000026) |\n\n### Benchmark: benchmark_indices_mapping.json\n\n| metric | select | shard | shuffle | sort | train_test_split |\n|--------|---|---|---|---|---|\n| new / old (diff) | 0.024271 / 0.037411 (-0.013140) | 0.098869 / 0.014526 (0.084343) | 0.105079 / 0.176557 (-0.071477) | 0.164707 / 0.737135 (-0.572428) | 0.110337 / 0.296338 (-0.186002) |\n\n### Benchmark: benchmark_iterating.json\n\n| metric | read 5000 | read 50000 | read_batch 50000 10 | read_batch 50000 100 | read_batch 50000 1000 | read_formatted numpy 5000 | read_formatted pandas 5000 | read_formatted tensorflow 5000 | read_formatted torch 5000 | read_formatted_batch numpy 5000 10 | read_formatted_batch numpy 5000 1000 | shuffled read 5000 | shuffled read 50000 | shuffled read_batch 50000 10 | shuffled read_batch 50000 100 | shuffled read_batch 50000 1000 | shuffled read_formatted numpy 5000 | shuffled read_formatted_batch numpy 5000 10 | shuffled read_formatted_batch numpy 5000 1000 |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.426593 / 0.215209 (0.211383) | 4.293977 / 2.077655 (2.216323) | 1.928502 / 1.504120 (0.424382) | 1.728623 / 1.541195 (0.187428) | 1.792084 / 1.468490 (0.323594) | 0.568737 / 4.584777 (-4.016040) | 3.438534 / 3.745712 (-0.307178) | 1.797798 / 5.269862 (-3.472063) | 1.054078 / 4.565676 (-3.511598) | 0.068711 / 0.424275 (-0.355564) | 0.011250 / 0.007607 (0.003643) | 0.529299 / 0.226044 (0.303255) | 5.283965 / 2.268929 (3.015037) | 2.358274 / 55.444624 (-53.086350) | 2.012818 / 6.876477 (-4.863659) | 2.109923 / 2.142072 (-0.032149) | 0.679556 / 4.805227 (-4.125671) | 0.138346 / 6.500664 (-6.362318) | 0.066349 / 0.075469 (-0.009120) |\n\n### Benchmark: benchmark_map_filter.json\n\n| metric | filter | map fast-tokenizer batched | map identity | map identity batched | map no-op batched | map no-op batched numpy | map no-op batched pandas | map no-op batched pytorch | map no-op batched tensorflow |\n|--------|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 1.193994 / 1.841788 (-0.647794) | 14.073158 / 8.074308 (5.998850) | 13.488525 / 10.191392 (3.297133) | 0.144536 / 0.680424 (-0.535888) | 0.016748 / 0.534201 (-0.517453) | 0.362703 / 0.579283 (-0.216580) | 0.389511 / 0.434364 (-0.044853) | 0.427296 / 0.540337 (-0.113041) | 0.513227 / 1.386936 (-0.873709) |\n\n</details>\nPyArrow==latest\n\n<details>\n<summary>Show updated benchmarks!</summary>\n\n### Benchmark: benchmark_array_xd.json\n\n| metric | read_batch_formatted_as_numpy after write_array2d | read_batch_formatted_as_numpy after write_flattened_sequence | read_batch_formatted_as_numpy after write_nested_sequence | read_batch_unformated after write_array2d | read_batch_unformated after write_flattened_sequence | read_batch_unformated after write_nested_sequence | read_col_formatted_as_numpy after write_array2d | read_col_formatted_as_numpy after write_flattened_sequence | read_col_formatted_as_numpy after write_neste

[{'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1601092005', 'html_url': 'https://github.com/huggingface/datasets/pull/5972#issuecomment-1601092005', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5972', 'id': 1601092005, 'node_id': 'IC_kwDODunzps5fbrml', 'user': {'login': 'github-actions[bot]', 'id': 41898282, 'node_id': 'MDM6Qm90NDE4OTgyODI=', 'avatar_url': 'https://avatars.githubusercontent.com/in/15368?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/github-actions%5Bbot%5D', 'html_url': 'https://github.com/apps/github-actions', 'followers_url': 'https://api.github.com/users/github-actions%5Bbot%5D/followers', 'following_url': 'https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}', 'gists_url': 'https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/github-actions%5Bbot%5D/subscriptions', 'organizations_url': 'https://api.github.com/users/github-actions%5Bbot%5D/orgs', 'repos_url': 'https://api.github.com/users/github-actions%5Bbot%5D/repos', 'events_url': 'https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}', 'received_events_url': 'https://api.github.com/users/github-actions%5Bbot%5D/received_events', 'type': 'Bot', 'site_admin': False}, 'created_at': '2023-06-21T15:49:49Z', 'updated_at': '2023-06-21T15:49:49Z', 'author_association': 'NONE', 'body': '<details>\n<summary>Show benchmarks</summary>\n\nPyArrow==8.0.0\n\n<details>\n<summary>Show updated benchmarks!</summary>\n\n### Benchmark: benchmark_array_xd.json\n\n| metric | read_batch_formatted_as_numpy after write_array2d | read_batch_formatted_as_numpy after write_flattened_sequence | read_batch_formatted_as_numpy after write_nested_sequence | read_batch_unformated after write_array2d | read_batch_unformated after write_flattened_sequence | read_batch_unformated after write_nested_sequence | read_col_formatted_as_numpy after write_array2d | read_col_formatted_as_numpy after write_flattened_sequence | read_col_formatted_as_numpy after write_nested_sequence | read_col_unformated after write_array2d | read_col_unformated after write_flattened_sequence | read_col_unformated after write_nested_sequence | read_formatted_as_numpy after write_array2d | read_formatted_as_numpy after write_flattened_sequence | read_formatted_as_numpy after write_nested_sequence | read_unformated after write_array2d | read_unformated after write_flattened_sequence | read_unformated after write_nested_sequence | write_array2d | write_flattened_sequence | write_nested_sequence |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.006983 / 0.011353 (-0.004369) | 0.004473 / 0.011008 (-0.006535) | 0.105158 / 0.038508 (0.066650) | 0.048973 / 0.023109 (0.025864) | 0.358771 / 0.275898 (0.082873) | 0.432389 / 0.323480 (0.108909) | 0.005689 / 0.007986 (-0.002297) | 0.003584 / 0.004328 (-0.000744) | 0.080852 / 0.004250 (0.076601) | 0.066133 / 0.037052 (0.029081) | 0.370981 / 0.258489 (0.112492) | 0.406942 / 0.293841 (0.113101) | 0.032123 / 0.128546 (-0.096424) | 0.009313 / 0.075646 (-0.066333) | 0.355220 / 0.419271 (-0.064051) | 0.055768 / 0.043533 (0.012235) | 0.370545 / 0.255139 (0.115406) | 0.375619 / 0.283200 (0.092419) | 0.024258 / 0.141683 (-0.117425) | 1.559073 / 1.452155 (0.106918) | 1.616520 / 1.492716 (0.123804) |\n\n### Benchmark: benchmark_getitem\\_100B.json\n\n| metric | get_batch_of\\_1024\\_random_rows | get_batch_of\\_1024\\_rows | get_first_row | get_last_row |\n|--------|---|---|---|---|\n| new / old (diff) | 0.277893 / 0.018006 (0.259887) | 0.535447 / 0.000490 (0.534957) | 0.004877 / 0.000200 (0.004677) | 0.000092 / 0.000054 (0.000037) |\n\n### Benchmark: benchmark_indices_mapping.json\n\n| metric | select | shard | shuffle | sort | train_test_split |\n|--------|---|---|---|---|---|\n| new / old (diff) | 0.029444 / 0.037411 (-0.007968) | 0.114366 / 0.014526 (0.099841) | 0.130957 / 0.176557 (-0.045599) | 0.189604 / 0.737135 (-0.547531) | 0.131682 / 0.296338 (-0.164656) |\n\n### Benchmark: benchmark_iterating.json\n\n| metric | read 5000 | read 50000 | read_batch 50000 10 | read_batch 50000 100 | read_batch 50000 1000 | read_formatted numpy 5000 | read_formatted pandas 5000 | read_formatted tensorflow 5000 | read_formatted torch 5000 | read_formatted_batch numpy 5000 10 | read_formatted_batch numpy 5000 1000 | shuffled read 5000 | shuffled read 50000 | shuffled read_batch 50000 10 | shuffled read_batch 50000 100 | shuffled read_batch 50000 1000 | shuffled read_formatted numpy 5000 | shuffled read_formatted_batch numpy 5000 10 | shuffled read_formatted_batch numpy 5000 1000 |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.412315 / 0.215209 (0.197106) | 4.093879 / 2.077655 (2.016225) | 1.856169 / 1.504120 (0.352050) | 1.655358 / 1.541195 (0.114164) | 1.758190 / 1.468490 (0.289699) | 0.545829 / 4.584777 (-4.038948) | 3.871436 / 3.745712 (0.125724) | 1.938244 / 5.269862 (-3.331618) | 1.122727 / 4.565676 (-3.442950) | 0.067107 / 0.424275 (-0.357168) | 0.012012 / 0.007607 (0.004405) | 0.518868 / 0.226044 (0.292824) | 5.235081 / 2.268929 (2.966153) | 2.335115 / 55.444624 (-53.109509) | 2.013074 / 6.876477 (-4.863402) | 2.219808 / 2.142072 (0.077735) | 0.674602 / 4.805227 (-4.130626) | 0.147051 / 6.500664 (-6.353613) | 0.068444 / 0.075469 (-0.007025) |\n\n### Benchmark: benchmark_map_filter.json\n\n| metric | filter | map fast-tokenizer batched | map identity | map identity batched | map no-op batched | map no-op batched numpy | map no-op batched pandas | map no-op batched pytorch | map no-op batched tensorflow |\n|--------|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 1.245600 / 1.841788 (-0.596188) | 15.537727 / 8.074308 (7.463419) | 15.074300 / 10.191392 (4.882908) | 0.194217 / 0.680424 (-0.486207) | 0.018536 / 0.534201 (-0.515665) | 0.437085 / 0.579283 (-0.142198) | 0.441123 / 0.434364 (0.006759) | 0.530681 / 0.540337 (-0.009657) | 0.649154 / 1.386936 (-0.737782) |\n\n</details>\nPyArrow==latest\n\n<details>\n<summary>Show updated benchmarks!</summary>\n\n### Benchmark: benchmark_array_xd.json\n\n| metric | read_batch_formatted_as_numpy after write_array2d | read_batch_formatted_as_numpy after write_flattened_sequence | read_batch_formatted_as_numpy after write_nested_sequence | read_batch_unformated after write_array2d | read_batch_unformated after write_flattened_sequence | read_batch_unformated after write_nested_sequence | read_col_formatted_as_numpy after write_array2d | read_col_formatted_as_numpy after write_flattened_sequence | read_col_formatted_as_numpy after write_nested_sequence | read_col_unformated after write_array2d | read_col_unformated after write_flattened_sequence | read_col_unformated after write_nested_sequence | read_formatted_as_numpy after write_array2d | read_formatted_as_numpy after write_flattened_sequence | read_formatted_as_numpy after write_nested_sequence | read_unformated after write_array2d | read_unformated after write_flattened_sequence | read_unformated after write_nested_sequence | write_array2d | write_flattened_sequence | write_nested_sequence |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.007243 / 0.011353 (-0.004110) | 0.004688 / 0.011008 (-0.006320) | 0.079809 / 0.038508 (0.041301) | 0.046915 / 0.023109 (0.023805) | 0.415144 / 0.275898 (0.139246) | 0.474867 / 0.323480 (0.151388) | 0.004550 / 0.007986 (-0.003435) | 0.004585 / 0.004328 (0.000257) | 0.080837 / 0.004250 (0.076587) | 0.061667 / 0.037052 (0.024614) | 0.411321 / 0.258489 (0.152832) | 0.464195 / 0.293841 (0.170354) | 0.032510 / 0.128546 (-0.096037) | 0.009306 / 0.075646 (-0.066340) | 0.086637 / 0.419271 (-0.332635) | 0.053335 / 0.043533 (0.009802) | 0.402302 / 0.255139 (0.147163) | 0.424864 / 0.283200 (0.141664) | 0.026573 / 0.141683 (-0.115110) | 1.566793 / 1.452155 (0.114639) | 1.628118 / 1.492716 (0.135401) |\n\n### Benchmark: benchmark_getitem\\_100B.json\n\n| metric | get_batch_of\\_1024\\_random_rows | get_batch_of\\_1024\\_rows | get_first_row | get_last_row |\n|--------|---|---|---|---|\n| new / old (diff) | 0.317802 / 0.018006 (0.299796) | 0.544593 / 0.000490 (0.544103) | 0.005690 / 0.000200 (0.005490) | 0.000107 / 0.000054 (0.000053) |\n\n### Benchmark: benchmark_indices_mapping.json\n\n| metric | select | shard | shuffle | sort | train_test_split |\n|--------|---|---|---|---|---|\n| new / old (diff) | 0.033015 / 0.037411 (-0.004397) | 0.121940 / 0.014526 (0.107414) | 0.132920 / 0.176557 (-0.043637) | 0.191481 / 0.737135 (-0.545655) | 0.139139 / 0.296338 (-0.157199) |\n\n### Benchmark: benchmark_iterating.json\n\n| metric | read 5000 | read 50000 | read_batch 50000 10 | read_batch 50000 100 | read_batch 50000 1000 | read_formatted numpy 5000 | read_formatted pandas 5000 | read_formatted tensorflow 5000 | read_formatted torch 5000 | read_formatted_batch numpy 5000 10 | read_formatted_batch numpy 5000 1000 | shuffled read 5000 | shuffled read 50000 | shuffled read_batch 50000 10 | shuffled read_batch 50000 100 | shuffled read_batch 50000 1000 | shuffled read_formatted numpy 5000 | shuffled read_formatted_batch numpy 5000 10 | shuffled read_formatted_batch numpy 5000 1000 |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.460382 / 0.215209 (0.245173) | 4.610046 / 2.077655 (2.532392) | 2.296573 / 1.504120 (0.792453) | 2.099735 / 1.541195 (0.558540) | 2.213913 / 1.468490 (0.745423) | 0.544871 / 4.584777 (-4.039906) | 3.814174 / 3.745712 (0.068462) | 3.246397 / 5.269862 (-2.023464) | 1.480236 / 4.565676 (-3.085440) | 0.068464 / 0.424275 (-0.355811) | 0.012651 / 0.007607 (0.005043) | 0.564989 / 0.226044 (0.338944) | 5.639188 / 2.268929 (3.370259) | 2.827601 / 55.444624 (-52.617023) | 2.473743 / 6.876477 (-4.402734) | 2.567413 / 2.142072 (0.425340) | 0.674351 / 4.805227 (-4.130876) | 0.146248 / 6.500664 (-6.354416) | 0.067553 / 0.075469 (-0.007916) |\n\n### Benchmark: benchmark_map_filter.json\n\n| metric | filter | map fast-tokenizer batched | map identity | map identity batched | map no-op batched | map no-op batched numpy | map no-op batched pandas | map no-op batched pytorch | map no-op batched tensorflow |\n|--------|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 1.346703 / 1.841788 (-0.495085) | 16.494787 / 8.074308 (8.420479) | 15.179487 / 10.191392 (4.988095) | 0.181864 / 0.680424 (-0.498560) | 0.018857 / 0.534201 (-0.515344) | 0.437787 / 0.579283 (-0.141496) | 0.431770 / 0.434364 (-0.002594) | 0.507116 / 0.540337 (-0.033221) | 0.608899 / 1.386936 (-0.778037) |\n\n</details>\n</details>\n\n![](https://cml.dev/watermark.png#0fd5b7412f907675e76b183a6e39ef6d176fdcc0 "CML watermark")\n', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1601092005/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1601224017', 'html_url': 'https://github.com/huggingface/datasets/pull/5972#issuecomment-1601224017', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5972', 'id': 1601224017, 'node_id': 'IC_kwDODunzps5fcL1R', 'user': {'login': 'HuggingFaceDocBuilderDev', 'id': 99929124, 'node_id': 'U_kgDOBfTMJA', 'avatar_url': 'https://avatars.githubusercontent.com/u/99929124?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/HuggingFaceDocBuilderDev', 'html_url': 'https://github.com/HuggingFaceDocBuilderDev', 'followers_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/followers', 'following_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/following{/other_user}', 'gists_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/subscriptions', 'organizations_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/orgs', 'repos_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/repos', 'events_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/events{/privacy}', 'received_events_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-21T16:55:44Z', 'updated_at': '2023-06-22T14:17:28Z', 'author_association': 'NONE', 'body': '_The documentation is not available anymore as the PR was closed or merged._', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1601224017/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1601227503', 'html_url': 'https://github.com/huggingface/datasets/pull/5972#issuecomment-1601227503', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5972', 'id': 1601227503, 'node_id': 'IC_kwDODunzps5fcMrv', 'user': {'login': 'github-actions[bot]', 'id': 41898282, 'node_id': 'MDM6Qm90NDE4OTgyODI=', 'avatar_url': 'https://avatars.githubusercontent.com/in/15368?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/github-actions%5Bbot%5D', 'html_url': 'https://github.com/apps/github-actions', 'followers_url': 'https://api.github.com/users/github-actions%5Bbot%5D/followers', 'following_url': 'https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}', 'gists_url': 'https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/github-actions%5Bbot%5D/subscriptions', 'organizations_url': 'https://api.github.com/users/github-actions%5Bbot%5D/orgs', 'repos_url': 'https://api.github.com/users/github-actions%5Bbot%5D/repos', 'events_url': 'https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}', 'received_events_url': 'https://api.github.com/users/github-actions%5Bbot%5D/received_events', 'type': 'Bot', 'site_admin': False}, 'created_at': '2023-06-21T16:57:13Z', 'updated_at': '2023-06-21T16:57:13Z', 'author_association': 'NONE', 'body': '<details>\n<summary>Show benchmarks</summary>\n\nPyArrow==8.0.0\n\n<details>\n<summary>Show updated benchmarks!</summary>\n\n### Benchmark: benchmark_array_xd.json\n\n| metric | read_batch_formatted_as_numpy after write_array2d | read_batch_formatted_as_numpy after write_flattened_sequence | read_batch_formatted_as_numpy after write_nested_sequence | read_batch_unformated after write_array2d | read_batch_unformated after write_flattened_sequence | read_batch_unformated after write_nested_sequence | read_col_formatted_as_numpy after write_array2d | read_col_formatted_as_numpy after write_flattened_sequence | read_col_formatted_as_numpy after write_nested_sequence | read_col_unformated after write_array2d | read_col_unformated after write_flattened_sequence | read_col_unformated after write_nested_sequence | read_formatted_as_numpy after write_array2d | read_formatted_as_numpy after write_flattened_sequence | read_formatted_as_numpy after write_nested_sequence | read_unformated after write_array2d | read_unformated after write_flattened_sequence | read_unformated after write_nested_sequence | write_array2d | write_flattened_sequence | write_nested_sequence |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.005963 / 0.011353 (-0.005390) | 0.003743 / 0.011008 (-0.007265) | 0.098519 / 0.038508 (0.060011) | 0.037392 / 0.023109 (0.014283) | 0.322706 / 0.275898 (0.046808) | 0.380032 / 0.323480 (0.056552) | 0.004694 / 0.007986 (-0.003292) | 0.002897 / 0.004328 (-0.001432) | 0.078664 / 0.004250 (0.074414) | 0.052646 / 0.037052 (0.015594) | 0.335523 / 0.258489 (0.077034) | 0.375464 / 0.293841 (0.081623) | 0.027537 / 0.128546 (-0.101010) | 0.008452 / 0.075646 (-0.067194) | 0.313844 / 0.419271 (-0.105427) | 0.047368 / 0.043533 (0.003835) | 0.313833 / 0.255139 (0.058694) | 0.342284 / 0.283200 (0.059085) | 0.021136 / 0.141683 (-0.120547) | 1.544764 / 1.452155 (0.092610) | 1.563850 / 1.492716 (0.071134) |\n\n### Benchmark: benchmark_getitem\\_100B.json\n\n| metric | get_batch_of\\_1024\\_random_rows | get_batch_of\\_1024\\_rows | get_first_row | get_last_row |\n|--------|---|---|---|---|\n| new / old (diff) | 0.188609 / 0.018006 (0.170603) | 0.421686 / 0.000490 (0.421196) | 0.003336 / 0.000200 (0.003136) | 0.000077 / 0.000054 (0.000023) |\n\n### Benchmark: benchmark_indices_mapping.json\n\n| metric | select | shard | shuffle | sort | train_test_split |\n|--------|---|---|---|---|---|\n| new / old (diff) | 0.023678 / 0.037411 (-0.013733) | 0.099191 / 0.014526 (0.084665) | 0.105819 / 0.176557 (-0.070738) | 0.169654 / 0.737135 (-0.567481) | 0.110240 / 0.296338 (-0.186099) |\n\n### Benchmark: benchmark_iterating.json\n\n| metric | read 5000 | read 50000 | read_batch 50000 10 | read_batch 50000 100 | read_batch 50000 1000 | read_formatted numpy 5000 | read_formatted pandas 5000 | read_formatted tensorflow 5000 | read_formatted torch 5000 | read_formatted_batch numpy 5000 10 | read_formatted_batch numpy 5000 1000 | shuffled read 5000 | shuffled read 50000 | shuffled read_batch 50000 10 | shuffled read_batch 50000 100 | shuffled read_batch 50000 1000 | shuffled read_formatted numpy 5000 | shuffled read_formatted_batch numpy 5000 10 | shuffled read_formatted_batch numpy 5000 1000 |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.425497 / 0.215209 (0.210288) | 4.237165 / 2.077655 (2.159510) | 1.902953 / 1.504120 (0.398833) | 1.699012 / 1.541195 (0.157818) | 1.751107 / 1.468490 (0.282617) | 0.563326 / 4.584777 (-4.021451) | 3.394189 / 3.745712 (-0.351523) | 2.706129 / 5.269862 (-2.563732) | 1.361522 / 4.565676 (-3.204155) | 0.067776 / 0.424275 (-0.356499) | 0.010959 / 0.007607 (0.003352) | 0.530905 / 0.226044 (0.304860) | 5.322467 / 2.268929 (3.053538) | 2.384356 / 55.444624 (-53.060269) | 2.044196 / 6.876477 (-4.832281) | 2.119837 / 2.142072 (-0.022235) | 0.682236 / 4.805227 (-4.122991) | 0.136921 / 6.500664 (-6.363743) | 0.066784 / 0.075469 (-0.008685) |\n\n### Benchmark: benchmark_map_filter.json\n\n| metric | filter | map fast-tokenizer batched | map identity | map identity batched | map no-op batched | map no-op batched numpy | map no-op batched pandas | map no-op batched pytorch | map no-op batched tensorflow |\n|--------|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 1.210642 / 1.841788 (-0.631146) | 13.804572 / 8.074308 (5.730264) | 13.309229 / 10.191392 (3.117837) | 0.154356 / 0.680424 (-0.526068) | 0.016833 / 0.534201 (-0.517368) | 0.366503 / 0.579283 (-0.212780) | 0.385201 / 0.434364 (-0.049163) | 0.426713 / 0.540337 (-0.113624) | 0.516795 / 1.386936 (-0.870141) |\n\n</details>\nPyArrow==latest\n\n<details>\n<summary>Show updated benchmarks!</summary>\n\n### Benchmark: benchmark_array_xd.json\n\n| metric | read_batch_formatted_as_numpy after write_array2d | read_batch_formatted_as_numpy after write_flattened_sequence | read_batch_formatted_as_numpy after write_nested_sequence | read_batch_unformated after write_array2d | read_batch_unformated after write_flattened_sequence | read_batch_unformated after write_nested_sequence | read_col_formatted_as_numpy after write_array2d | read_col_formatted_as_numpy after write_flattened_sequence | read_col_formatted_as_numpy after write_nested_

[{'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1601139555', 'html_url': 'https://github.com/huggingface/datasets/issues/5971#issuecomment-1601139555', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5971', 'id': 1601139555, 'node_id': 'IC_kwDODunzps5fb3Nj', 'user': {'login': 'mariosasko', 'id': 47462742, 'node_id': 'MDQ6VXNlcjQ3NDYyNzQy', 'avatar_url': 'https://avatars.githubusercontent.com/u/47462742?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/mariosasko', 'html_url': 'https://github.com/mariosasko', 'followers_url': 'https://api.github.com/users/mariosasko/followers', 'following_url': 'https://api.github.com/users/mariosasko/following{/other_user}', 'gists_url': 'https://api.github.com/users/mariosasko/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/mariosasko/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/mariosasko/subscriptions', 'organizations_url': 'https://api.github.com/users/mariosasko/orgs', 'repos_url': 'https://api.github.com/users/mariosasko/repos', 'events_url': 'https://api.github.com/users/mariosasko/events{/privacy}', 'received_events_url': 'https://api.github.com/users/mariosasko/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-21T16:15:11Z', 'updated_at': '2023-06-21T16:15:11Z', 'author_association': 'CONTRIBUTOR', 'body': 'Loading a local dataset also works the same way when `data_files` are not specified, so I agree we should make this info  easier to discover \r\n\r\ncc @stevhliu ', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1601139555/reactions', 'total_count': 2, '+1': 2, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1603591751', 'html_url': 'https://github.com/huggingface/datasets/issues/5971#issuecomment-1603591751', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5971', 'id': 1603591751, 'node_id': 'IC_kwDODunzps5flN5H', 'user': {'login': 'benjaminbrown038', 'id': 35114142, 'node_id': 'MDQ6VXNlcjM1MTE0MTQy', 'avatar_url': 'https://avatars.githubusercontent.com/u/35114142?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/benjaminbrown038', 'html_url': 'https://github.com/benjaminbrown038', 'followers_url': 'https://api.github.com/users/benjaminbrown038/followers', 'following_url': 'https://api.github.com/users/benjaminbrown038/following{/other_user}', 'gists_url': 'https://api.github.com/users/benjaminbrown038/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/benjaminbrown038/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/benjaminbrown038/subscriptions', 'organizations_url': 'https://api.github.com/users/benjaminbrown038/orgs', 'repos_url': 'https://api.github.com/users/benjaminbrown038/repos', 'events_url': 'https://api.github.com/users/benjaminbrown038/events{/privacy}', 'received_events_url': 'https://api.github.com/users/benjaminbrown038/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-23T02:06:27Z', 'updated_at': '2023-06-23T02:08:40Z', 'author_association': 'NONE', 'body': 'Is this issue open? If so, I will self assign. ', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1603591751/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1611839643', 'html_url': 'https://github.com/huggingface/datasets/issues/5971#issuecomment-1611839643', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5971', 'id': 1611839643, 'node_id': 'IC_kwDODunzps5gErib', 'user': {'login': 'mariosasko', 'id': 47462742, 'node_id': 'MDQ6VXNlcjQ3NDYyNzQy', 'avatar_url': 'https://avatars.githubusercontent.com/u/47462742?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/mariosasko', 'html_url': 'https://github.com/mariosasko', 'followers_url': 'https://api.github.com/users/mariosasko/followers', 'following_url': 'https://api.github.com/users/mariosasko/following{/other_user}', 'gists_url': 'https://api.github.com/users/mariosasko/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/mariosasko/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/mariosasko/subscriptions', 'organizations_url': 'https://api.github.com/users/mariosasko/orgs', 'repos_url': 'https://api.github.com/users/mariosasko/repos', 'events_url': 'https://api.github.com/users/mariosasko/events{/privacy}', 'received_events_url': 'https://api.github.com/users/mariosasko/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-28T17:47:47Z', 'updated_at': '2023-06-28T17:47:47Z', 'author_association': 'CONTRIBUTOR', 'body': "@benjaminbrown038 Yes, it is. Maybe @stevhliu can give some pointers on improving this doc page's discoverability.", 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1611839643/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1612143151', 'html_url': 'https://github.com/huggingface/datasets/issues/5971#issuecomment-1612143151', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5971', 'id': 1612143151, 'node_id': 'IC_kwDODunzps5gF1ov', 'user': {'login': 'stevhliu', 'id': 59462357, 'node_id': 'MDQ6VXNlcjU5NDYyMzU3', 'avatar_url': 'https://avatars.githubusercontent.com/u/59462357?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/stevhliu', 'html_url': 'https://github.com/stevhliu', 'followers_url': 'https://api.github.com/users/stevhliu/followers', 'following_url': 'https://api.github.com/users/stevhliu/following{/other_user}', 'gists_url': 'https://api.github.com/users/stevhliu/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/stevhliu/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/stevhliu/subscriptions', 'organizations_url': 'https://api.github.com/users/stevhliu/orgs', 'repos_url': 'https://api.github.com/users/stevhliu/repos', 'events_url': 'https://api.github.com/users/stevhliu/events{/privacy}', 'received_events_url': 'https://api.github.com/users/stevhliu/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-28T21:39:56Z', 'updated_at': '2023-06-28T21:39:56Z', 'author_association': 'MEMBER', 'body': 'I think we can add a version of the [Main use-case](https://huggingface.co/docs/datasets/repository_structure#main-usecase) section to the [Share a dataset to the Hub](https://huggingface.co/docs/datasets/upload_dataset) tutorial. \r\n\r\nCurrently, it doesn\'t tell you *how* to structure the repository; it only tells you how to create it. So adding the "main use-case" will help bridge the gap and make it easier to find. We should also add a link to the [Structure your repository](https://huggingface.co/docs/datasets/repository_structure) guide for users who want to learn about the other options.', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1612143151/reactions', 'total_count': 1, '+1': 1, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1621133279', 'html_url': 'https://github.com/huggingface/datasets/issues/5971#issuecomment-1621133279', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5971', 'id': 1621133279, 'node_id': 'IC_kwDODunzps5goIff', 'user': {'login': 'benjaminbrown038', 'id': 35114142, 'node_id': 'MDQ6VXNlcjM1MTE0MTQy', 'avatar_url': 'https://avatars.githubusercontent.com/u/35114142?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/benjaminbrown038', 'html_url': 'https://github.com/benjaminbrown038', 'followers_url': 'https://api.github.com/users/benjaminbrown038/followers', 'following_url': 'https://api.github.com/users/benjaminbrown038/following{/other_user}', 'gists_url': 'https://api.github.com/users/benjaminbrown038/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/benjaminbrown038/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/benjaminbrown038/subscriptions', 'organizations_url': 'https://api.github.com/users/benjaminbrown038/orgs', 'repos_url': 'https://api.github.com/users/benjaminbrown038/repos', 'events_url': 'https://api.github.com/users/benjaminbrown038/events{/privacy}', 'received_events_url': 'https://api.github.com/users/benjaminbrown038/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-07-05T06:51:27Z', 'updated_at': '2023-07-05T06:51:27Z', 'author_association': 'NONE', 'body': '#self-assign', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1621133279/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}]

[{'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1601819907', 'html_url': 'https://github.com/huggingface/datasets/issues/5970#issuecomment-1601819907', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5970', 'id': 1601819907, 'node_id': 'IC_kwDODunzps5fedUD', 'user': {'login': 'balisujohn', 'id': 20377292, 'node_id': 'MDQ6VXNlcjIwMzc3Mjky', 'avatar_url': 'https://avatars.githubusercontent.com/u/20377292?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/balisujohn', 'html_url': 'https://github.com/balisujohn', 'followers_url': 'https://api.github.com/users/balisujohn/followers', 'following_url': 'https://api.github.com/users/balisujohn/following{/other_user}', 'gists_url': 'https://api.github.com/users/balisujohn/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/balisujohn/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/balisujohn/subscriptions', 'organizations_url': 'https://api.github.com/users/balisujohn/orgs', 'repos_url': 'https://api.github.com/users/balisujohn/repos', 'events_url': 'https://api.github.com/users/balisujohn/events{/privacy}', 'received_events_url': 'https://api.github.com/users/balisujohn/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-21T23:30:52Z', 'updated_at': '2023-06-21T23:30:52Z', 'author_association': 'NONE', 'body': 'Here\'s a minimal way to reproduce the bug, for the sake of convenience.\r\n````\r\nfrom datasets import Dataset, DatasetInfo, load_dataset\r\n\r\n\r\nepisodes_dict = {"test":[1,2,3],"test2": [1,2,4]}\r\n\r\nhugging_face_dataset = Dataset.from_dict(\r\n    episodes_dict, info=DatasetInfo(description="test_str")\r\n)\r\nprint(hugging_face_dataset.info)\r\n\r\nhugging_face_dataset.push_to_hub("balisujohn/minari_test", private=True)\r\n\r\nredownloaded_dataset= load_dataset("balisujohn/minari_test")["train"]\r\n\r\n\r\nprint(redownloaded_dataset.info)\r\n````\r\n', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1601819907/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1602734419', 'html_url': 'https://github.com/huggingface/datasets/issues/5970#issuecomment-1602734419', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5970', 'id': 1602734419, 'node_id': 'IC_kwDODunzps5fh8lT', 'user': {'login': 'lhoestq', 'id': 42851186, 'node_id': 'MDQ6VXNlcjQyODUxMTg2', 'avatar_url': 'https://avatars.githubusercontent.com/u/42851186?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/lhoestq', 'html_url': 'https://github.com/lhoestq', 'followers_url': 'https://api.github.com/users/lhoestq/followers', 'following_url': 'https://api.github.com/users/lhoestq/following{/other_user}', 'gists_url': 'https://api.github.com/users/lhoestq/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/lhoestq/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/lhoestq/subscriptions', 'organizations_url': 'https://api.github.com/users/lhoestq/orgs', 'repos_url': 'https://api.github.com/users/lhoestq/repos', 'events_url': 'https://api.github.com/users/lhoestq/events{/privacy}', 'received_events_url': 'https://api.github.com/users/lhoestq/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-22T14:23:56Z', 'updated_at': '2023-06-22T14:23:56Z', 'author_association': 'MEMBER', 'body': 'Thanks for reporting !\r\n\r\nFor now I would recommend uploading a separate JSON file for your metadata.\r\n\r\nAlternatively you can upload a second configuration of the dataset containing your metadata but this feature is not released yet (though you can already use it from [here](https://github.com/huggingface/datasets/pull/5331), it will be released soon)', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1602734419/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}]

[{'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1598638610', 'html_url': 'https://github.com/huggingface/datasets/issues/5968#issuecomment-1598638610', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5968', 'id': 1598638610, 'node_id': 'IC_kwDODunzps5fSUoS', 'user': {'login': 'patrickvonplaten', 'id': 23423619, 'node_id': 'MDQ6VXNlcjIzNDIzNjE5', 'avatar_url': 'https://avatars.githubusercontent.com/u/23423619?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/patrickvonplaten', 'html_url': 'https://github.com/patrickvonplaten', 'followers_url': 'https://api.github.com/users/patrickvonplaten/followers', 'following_url': 'https://api.github.com/users/patrickvonplaten/following{/other_user}', 'gists_url': 'https://api.github.com/users/patrickvonplaten/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/patrickvonplaten/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/patrickvonplaten/subscriptions', 'organizations_url': 'https://api.github.com/users/patrickvonplaten/orgs', 'repos_url': 'https://api.github.com/users/patrickvonplaten/repos', 'events_url': 'https://api.github.com/users/patrickvonplaten/events{/privacy}', 'received_events_url': 'https://api.github.com/users/patrickvonplaten/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-20T11:58:49Z', 'updated_at': '2023-06-20T11:58:49Z', 'author_association': 'MEMBER', 'body': 'cc @pcuenca as well. \r\n\r\nNot super urgent btw', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1598638610/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1598720494', 'html_url': 'https://github.com/huggingface/datasets/issues/5968#issuecomment-1598720494', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5968', 'id': 1598720494, 'node_id': 'IC_kwDODunzps5fSonu', 'user': {'login': 'lhoestq', 'id': 42851186, 'node_id': 'MDQ6VXNlcjQyODUxMTg2', 'avatar_url': 'https://avatars.githubusercontent.com/u/42851186?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/lhoestq', 'html_url': 'https://github.com/lhoestq', 'followers_url': 'https://api.github.com/users/lhoestq/followers', 'following_url': 'https://api.github.com/users/lhoestq/following{/other_user}', 'gists_url': 'https://api.github.com/users/lhoestq/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/lhoestq/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/lhoestq/subscriptions', 'organizations_url': 'https://api.github.com/users/lhoestq/orgs', 'repos_url': 'https://api.github.com/users/lhoestq/repos', 'events_url': 'https://api.github.com/users/lhoestq/events{/privacy}', 'received_events_url': 'https://api.github.com/users/lhoestq/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-20T12:57:05Z', 'updated_at': '2023-06-20T12:57:05Z', 'author_association': 'MEMBER', 'body': 'The issue commes from the dataset itself and is not related to the `datasets` lib\r\n\r\nsee https://huggingface.co/datasets/mozilla-foundation/common_voice_6_1/blob/2c475b3b88e0f2e5828f830a4b91618a25ff20b7/common_voice_6_1.py#L148-L152', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1598720494/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1600562035', 'html_url': 'https://github.com/huggingface/datasets/issues/5968#issuecomment-1600562035', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5968', 'id': 1600562035, 'node_id': 'IC_kwDODunzps5fZqNz', 'user': {'login': 'patrickvonplaten', 'id': 23423619, 'node_id': 'MDQ6VXNlcjIzNDIzNjE5', 'avatar_url': 'https://avatars.githubusercontent.com/u/23423619?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/patrickvonplaten', 'html_url': 'https://github.com/patrickvonplaten', 'followers_url': 'https://api.github.com/users/patrickvonplaten/followers', 'following_url': 'https://api.github.com/users/patrickvonplaten/following{/other_user}', 'gists_url': 'https://api.github.com/users/patrickvonplaten/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/patrickvonplaten/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/patrickvonplaten/subscriptions', 'organizations_url': 'https://api.github.com/users/patrickvonplaten/orgs', 'repos_url': 'https://api.github.com/users/patrickvonplaten/repos', 'events_url': 'https://api.github.com/users/patrickvonplaten/events{/privacy}', 'received_events_url': 'https://api.github.com/users/patrickvonplaten/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-21T10:08:37Z', 'updated_at': '2023-06-21T10:08:37Z', 'author_association': 'MEMBER', 'body': "Let's remove these lines in the dataset no? cc @anton-l @Vaibhavs10 ", 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1600562035/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}]
[{'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1602744263', 'html_url': 'https://github.com/huggingface/datasets/issues/5967#issuecomment-1602744263', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5967', 'id': 1602744263, 'node_id': 'IC_kwDODunzps5fh-_H', 'user': {'login': 'lhoestq', 'id': 42851186, 'node_id': 'MDQ6VXNlcjQyODUxMTg2', 'avatar_url': 'https://avatars.githubusercontent.com/u/42851186?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/lhoestq', 'html_url': 'https://github.com/lhoestq', 'followers_url': 'https://api.github.com/users/lhoestq/followers', 'following_url': 'https://api.github.com/users/lhoestq/following{/other_user}', 'gists_url': 'https://api.github.com/users/lhoestq/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/lhoestq/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/lhoestq/subscriptions', 'organizations_url': 'https://api.github.com/users/lhoestq/orgs', 'repos_url': 'https://api.github.com/users/lhoestq/repos', 'events_url': 'https://api.github.com/users/lhoestq/events{/privacy}', 'received_events_url': 'https://api.github.com/users/lhoestq/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-22T14:30:02Z', 'updated_at': '2023-06-22T14:30:02Z', 'author_association': 'MEMBER', 'body': "This must be due to DatasetInfo.from_merge which drops them and is used in `concatenate_datasets`.\r\n\r\nAnd you're experiencing this issue because multiprocessing does concatenate the resulting datasets from each process.\r\n\r\nMaybe they should be kept if all the subdatasets share the same values for config_name and split", 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1602744263/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1611026405', 'html_url': 'https://github.com/huggingface/datasets/issues/5967#issuecomment-1611026405', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5967', 'id': 1611026405, 'node_id': 'IC_kwDODunzps5gBk_l', 'user': {'login': 'sanchit-gandhi', 'id': 93869735, 'node_id': 'U_kgDOBZhWpw', 'avatar_url': 'https://avatars.githubusercontent.com/u/93869735?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/sanchit-gandhi', 'html_url': 'https://github.com/sanchit-gandhi', 'followers_url': 'https://api.github.com/users/sanchit-gandhi/followers', 'following_url': 'https://api.github.com/users/sanchit-gandhi/following{/other_user}', 'gists_url': 'https://api.github.com/users/sanchit-gandhi/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/sanchit-gandhi/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/sanchit-gandhi/subscriptions', 'organizations_url': 'https://api.github.com/users/sanchit-gandhi/orgs', 'repos_url': 'https://api.github.com/users/sanchit-gandhi/repos', 'events_url': 'https://api.github.com/users/sanchit-gandhi/events{/privacy}', 'received_events_url': 'https://api.github.com/users/sanchit-gandhi/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-28T08:55:25Z', 'updated_at': '2023-06-28T08:55:25Z', 'author_association': 'CONTRIBUTOR', 'body': 'That sounds like a clean workaround!', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1611026405/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}]

[{'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1597497151', 'html_url': 'https://github.com/huggingface/datasets/pull/5966#issuecomment-1597497151', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5966', 'id': 1597497151, 'node_id': 'IC_kwDODunzps5fN98_', 'user': {'login': 'github-actions[bot]', 'id': 41898282, 'node_id': 'MDM6Qm90NDE4OTgyODI=', 'avatar_url': 'https://avatars.githubusercontent.com/in/15368?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/github-actions%5Bbot%5D', 'html_url': 'https://github.com/apps/github-actions', 'followers_url': 'https://api.github.com/users/github-actions%5Bbot%5D/followers', 'following_url': 'https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}', 'gists_url': 'https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/github-actions%5Bbot%5D/subscriptions', 'organizations_url': 'https://api.github.com/users/github-actions%5Bbot%5D/orgs', 'repos_url': 'https://api.github.com/users/github-actions%5Bbot%5D/repos', 'events_url': 'https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}', 'received_events_url': 'https://api.github.com/users/github-actions%5Bbot%5D/received_events', 'type': 'Bot', 'site_admin': False}, 'created_at': '2023-06-19T17:02:23Z', 'updated_at': '2023-06-19T17:02:23Z', 'author_association': 'NONE', 'body': '<details>\n<summary>Show benchmarks</summary>\n\nPyArrow==8.0.0\n\n<details>\n<summary>Show updated benchmarks!</summary>\n\n### Benchmark: benchmark_array_xd.json\n\n| metric | read_batch_formatted_as_numpy after write_array2d | read_batch_formatted_as_numpy after write_flattened_sequence | read_batch_formatted_as_numpy after write_nested_sequence | read_batch_unformated after write_array2d | read_batch_unformated after write_flattened_sequence | read_batch_unformated after write_nested_sequence | read_col_formatted_as_numpy after write_array2d | read_col_formatted_as_numpy after write_flattened_sequence | read_col_formatted_as_numpy after write_nested_sequence | read_col_unformated after write_array2d | read_col_unformated after write_flattened_sequence | read_col_unformated after write_nested_sequence | read_formatted_as_numpy after write_array2d | read_formatted_as_numpy after write_flattened_sequence | read_formatted_as_numpy after write_nested_sequence | read_unformated after write_array2d | read_unformated after write_flattened_sequence | read_unformated after write_nested_sequence | write_array2d | write_flattened_sequence | write_nested_sequence |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.006186 / 0.011353 (-0.005167) | 0.003744 / 0.011008 (-0.007264) | 0.097295 / 0.038508 (0.058787) | 0.037106 / 0.023109 (0.013997) | 0.424154 / 0.275898 (0.148256) | 0.474536 / 0.323480 (0.151057) | 0.003454 / 0.007986 (-0.004532) | 0.003865 / 0.004328 (-0.000463) | 0.077348 / 0.004250 (0.073097) | 0.051728 / 0.037052 (0.014675) | 0.437120 / 0.258489 (0.178631) | 0.478379 / 0.293841 (0.184538) | 0.028939 / 0.128546 (-0.099608) | 0.008376 / 0.075646 (-0.067270) | 0.312002 / 0.419271 (-0.107270) | 0.053723 / 0.043533 (0.010190) | 0.424815 / 0.255139 (0.169676) | 0.446203 / 0.283200 (0.163004) | 0.026553 / 0.141683 (-0.115130) | 1.479983 / 1.452155 (0.027828) | 1.530613 / 1.492716 (0.037896) |\n\n### Benchmark: benchmark_getitem\\_100B.json\n\n| metric | get_batch_of\\_1024\\_random_rows | get_batch_of\\_1024\\_rows | get_first_row | get_last_row |\n|--------|---|---|---|---|\n| new / old (diff) | 0.196627 / 0.018006 (0.178620) | 0.422361 / 0.000490 (0.421871) | 0.003442 / 0.000200 (0.003242) | 0.000077 / 0.000054 (0.000023) |\n\n### Benchmark: benchmark_indices_mapping.json\n\n| metric | select | shard | shuffle | sort | train_test_split |\n|--------|---|---|---|---|---|\n| new / old (diff) | 0.022913 / 0.037411 (-0.014499) | 0.096011 / 0.014526 (0.081485) | 0.104091 / 0.176557 (-0.072466) | 0.163273 / 0.737135 (-0.573862) | 0.109142 / 0.296338 (-0.187197) |\n\n### Benchmark: benchmark_iterating.json\n\n| metric | read 5000 | read 50000 | read_batch 50000 10 | read_batch 50000 100 | read_batch 50000 1000 | read_formatted numpy 5000 | read_formatted pandas 5000 | read_formatted tensorflow 5000 | read_formatted torch 5000 | read_formatted_batch numpy 5000 10 | read_formatted_batch numpy 5000 1000 | shuffled read 5000 | shuffled read 50000 | shuffled read_batch 50000 10 | shuffled read_batch 50000 100 | shuffled read_batch 50000 1000 | shuffled read_formatted numpy 5000 | shuffled read_formatted_batch numpy 5000 10 | shuffled read_formatted_batch numpy 5000 1000 |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.431032 / 0.215209 (0.215823) | 4.314391 / 2.077655 (2.236737) | 2.003812 / 1.504120 (0.499692) | 1.799538 / 1.541195 (0.258344) | 1.830026 / 1.468490 (0.361536) | 0.560131 / 4.584777 (-4.024646) | 3.368997 / 3.745712 (-0.376715) | 1.703032 / 5.269862 (-3.566830) | 1.026949 / 4.565676 (-3.538727) | 0.067507 / 0.424275 (-0.356768) | 0.010910 / 0.007607 (0.003303) | 0.532606 / 0.226044 (0.306562) | 5.345179 / 2.268929 (3.076250) | 2.368077 / 55.444624 (-53.076548) | 2.028913 / 6.876477 (-4.847564) | 2.147621 / 2.142072 (0.005549) | 0.675696 / 4.805227 (-4.129531) | 0.134902 / 6.500664 (-6.365762) | 0.065004 / 0.075469 (-0.010465) |\n\n### Benchmark: benchmark_map_filter.json\n\n| metric | filter | map fast-tokenizer batched | map identity | map identity batched | map no-op batched | map no-op batched numpy | map no-op batched pandas | map no-op batched pytorch | map no-op batched tensorflow |\n|--------|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 1.233412 / 1.841788 (-0.608376) | 13.767465 / 8.074308 (5.693157) | 13.933653 / 10.191392 (3.742261) | 0.129010 / 0.680424 (-0.551414) | 0.016708 / 0.534201 (-0.517493) | 0.362341 / 0.579283 (-0.216942) | 0.390902 / 0.434364 (-0.043462) | 0.429156 / 0.540337 (-0.111182) | 0.521166 / 1.386936 (-0.865770) |\n\n</details>\nPyArrow==latest\n\n<details>\n<summary>Show updated benchmarks!</summary>\n\n### Benchmark: benchmark_array_xd.json\n\n| metric | read_batch_formatted_as_numpy after write_array2d | read_batch_formatted_as_numpy after write_flattened_sequence | read_batch_formatted_as_numpy after write_nested_sequence | read_batch_unformated after write_array2d | read_batch_unformated after write_flattened_sequence | read_batch_unformated after write_nested_sequence | read_col_formatted_as_numpy after write_array2d | read_col_formatted_as_numpy after write_flattened_sequence | read_col_formatted_as_numpy after write_nested_sequence | read_col_unformated after write_array2d | read_col_unformated after write_flattened_sequence | read_col_unformated after write_nested_sequence | read_formatted_as_numpy after write_array2d | read_formatted_as_numpy after write_flattened_sequence | read_formatted_as_numpy after write_nested_sequence | read_unformated after write_array2d | read_unformated after write_flattened_sequence | read_unformated after write_nested_sequence | write_array2d | write_flattened_sequence | write_nested_sequence |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.006169 / 0.011353 (-0.005184) | 0.003839 / 0.011008 (-0.007169) | 0.078784 / 0.038508 (0.040276) | 0.040218 / 0.023109 (0.017109) | 0.360439 / 0.275898 (0.084541) | 0.423957 / 0.323480 (0.100477) | 0.003456 / 0.007986 (-0.004529) | 0.002900 / 0.004328 (-0.001428) | 0.078820 / 0.004250 (0.074569) | 0.047240 / 0.037052 (0.010187) | 0.372081 / 0.258489 (0.113592) | 0.424263 / 0.293841 (0.130422) | 0.027977 / 0.128546 (-0.100569) | 0.008400 / 0.075646 (-0.067246) | 0.084399 / 0.419271 (-0.334872) | 0.043303 / 0.043533 (-0.000230) | 0.361583 / 0.255139 (0.106444) | 0.394987 / 0.283200 (0.111787) | 0.020006 / 0.141683 (-0.121677) | 1.520208 / 1.452155 (0.068053) | 1.587335 / 1.492716 (0.094619) |\n\n### Benchmark: benchmark_getitem\\_100B.json\n\n| metric | get_batch_of\\_1024\\_random_rows | get_batch_of\\_1024\\_rows | get_first_row | get_last_row |\n|--------|---|---|---|---|\n| new / old (diff) | 0.223847 / 0.018006 (0.205840) | 0.402194 / 0.000490 (0.401704) | 0.000384 / 0.000200 (0.000184) | 0.000057 / 0.000054 (0.000003) |\n\n### Benchmark: benchmark_indices_mapping.json\n\n| metric | select | shard | shuffle | sort | train_test_split |\n|--------|---|---|---|---|---|\n| new / old (diff) | 0.024902 / 0.037411 (-0.012509) | 0.099076 / 0.014526 (0.084550) | 0.108041 / 0.176557 (-0.068516) | 0.159385 / 0.737135 (-0.577750) | 0.111442 / 0.296338 (-0.184896) |\n\n### Benchmark: benchmark_iterating.json\n\n| metric | read 5000 | read 50000 | read_batch 50000 10 | read_batch 50000 100 | read_batch 50000 1000 | read_formatted numpy 5000 | read_formatted pandas 5000 | read_formatted tensorflow 5000 | read_formatted torch 5000 | read_formatted_batch numpy 5000 10 | read_formatted_batch numpy 5000 1000 | shuffled read 5000 | shuffled read 50000 | shuffled read_batch 50000 10 | shuffled read_batch 50000 100 | shuffled read_batch 50000 1000 | shuffled read_formatted numpy 5000 | shuffled read_formatted_batch numpy 5000 10 | shuffled read_formatted_batch numpy 5000 1000 |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.446232 / 0.215209 (0.231023) | 4.464927 / 2.077655 (2.387272) | 2.155234 / 1.504120 (0.651114) | 1.953645 / 1.541195 (0.412450) | 1.965991 / 1.468490 (0.497501) | 0.553473 / 4.584777 (-4.031304) | 3.321397 / 3.745712 (-0.424315) | 1.693761 / 5.269862 (-3.576101) | 1.006299 / 4.565676 (-3.559378) | 0.067013 / 0.424275 (-0.357262) | 0.011116 / 0.007607 (0.003509) | 0.555014 / 0.226044 (0.328970) | 5.535694 / 2.268929 (3.266765) | 2.598339 / 55.444624 (-52.846285) | 2.249298 / 6.876477 (-4.627179) | 2.243419 / 2.142072 (0.101347) | 0.667603 / 4.805227 (-4.137624) | 0.133322 / 6.500664 (-6.367343) | 0.065473 / 0.075469 (-0.009996) |\n\n### Benchmark: benchmark_map_filter.json\n\n| metric | filter | map fast-tokenizer batched | map identity | map identity batched | map no-op batched | map no-op batched numpy | map no-op batched pandas | map no-op batched pytorch | map no-op batched tensorflow |\n|--------|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 1.293051 / 1.841788 (-0.548737) | 14.103731 / 8.074308 (6.029423) | 14.215204 / 10.191392 (4.023812) | 0.143990 / 0.680424 (-0.536434) | 0.016805 / 0.534201 (-0.517396) | 0.363264 / 0.579283 (-0.216019) | 0.392769 / 0.434364 (-0.041594) | 0.425291 / 0.540337 (-0.115046) | 0.515479 / 1.386936 (-0.871457) |\n\n</details>\n</details>\n\n![](https://cml.dev/watermark.png#e03a58f3f5d7e6f07279fb833e62d859a0babaad "CML watermark")\n', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1597497151/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1597497412', 'html_url': 'https://github.com/huggingface/datasets/pull/5966#issuecomment-1597497412', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5966', 'id': 1597497412, 'node_id': 'IC_kwDODunzps5fN-BE', 'user': {'login': 'HuggingFaceDocBuilderDev', 'id': 99929124, 'node_id': 'U_kgDOBfTMJA', 'avatar_url': 'https://avatars.githubusercontent.com/u/99929124?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/HuggingFaceDocBuilderDev', 'html_url': 'https://github.com/HuggingFaceDocBuilderDev', 'followers_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/followers', 'following_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/following{/other_user}', 'gists_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/subscriptions', 'organizations_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/orgs', 'repos_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/repos', 'events_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/events{/privacy}', 'received_events_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-19T17:02:34Z', 'updated_at': '2023-06-19T17:22:36Z', 'author_association': 'NONE', 'body': '_The documentation is not available anymore as the PR was closed or merged._', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1597497412/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1597524920', 'html_url': 'https://github.com/huggingface/datasets/pull/5966#issuecomment-1597524920', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5966', 'id': 1597524920, 'node_id': 'IC_kwDODunzps5fOEu4', 'user': {'login': 'github-actions[bot]', 'id': 41898282, 'node_id': 'MDM6Qm90NDE4OTgyODI=', 'avatar_url': 'https://avatars.githubusercontent.com/in/15368?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/github-actions%5Bbot%5D', 'html_url': 'https://github.com/apps/github-actions', 'followers_url': 'https://api.github.com/users/github-actions%5Bbot%5D/followers', 'following_url': 'https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}', 'gists_url': 'https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/github-actions%5Bbot%5D/subscriptions', 'organizations_url': 'https://api.github.com/users/github-actions%5Bbot%5D/orgs', 'repos_url': 'https://api.github.com/users/github-actions%5Bbot%5D/repos', 'events_url': 'https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}', 'received_events_url': 'https://api.github.com/users/github-actions%5Bbot%5D/received_events', 'type': 'Bot', 'site_admin': False}, 'created_at': '2023-06-19T17:29:11Z', 'updated_at': '2023-06-19T17:29:11Z', 'author_association': 'NONE', 'body': '<details>\n<summary>Show benchmarks</summary>\n\nPyArrow==8.0.0\n\n<details>\n<summary>Show updated benchmarks!</summary>\n\n### Benchmark: benchmark_array_xd.json\n\n| metric | read_batch_formatted_as_numpy after write_array2d | read_batch_formatted_as_numpy after write_flattened_sequence | read_batch_formatted_as_numpy after write_nested_sequence | read_batch_unformated after write_array2d | read_batch_unformated after write_flattened_sequence | read_batch_unformated after write_nested_sequence | read_col_formatted_as_numpy after write_array2d | read_col_formatted_as_numpy after write_flattened_sequence | read_col_formatted_as_numpy after write_nested_sequence | read_col_unformated after write_array2d | read_col_unformated after write_flattened_sequence | read_col_unformated after write_nested_sequence | read_formatted_as_numpy after write_array2d | read_formatted_as_numpy after write_flattened_sequence | read_formatted_as_numpy after write_nested_sequence | read_unformated after write_array2d | read_unformated after write_flattened_sequence | read_unformated after write_nested_sequence | write_array2d | write_flattened_sequence | write_nested_sequence |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.006346 / 0.011353 (-0.005006) | 0.004130 / 0.011008 (-0.006878) | 0.096898 / 0.038508 (0.058390) | 0.042564 / 0.023109 (0.019455) | 0.343748 / 0.275898 (0.067850) | 0.412515 / 0.323480 (0.089035) | 0.006153 / 0.007986 (-0.001833) | 0.003345 / 0.004328 (-0.000984) | 0.075314 / 0.004250 (0.071064) | 0.061478 / 0.037052 (0.024426) | 0.362948 / 0.258489 (0.104459) | 0.401533 / 0.293841 (0.107692) | 0.032363 / 0.128546 (-0.096184) | 0.008780 / 0.075646 (-0.066867) | 0.328691 / 0.419271 (-0.090580) | 0.054253 / 0.043533 (0.010721) | 0.340783 / 0.255139 (0.085644) | 0.360705 / 0.283200 (0.077505) | 0.023183 / 0.141683 (-0.118500) | 1.484078 / 1.452155 (0.031924) | 1.528581 / 1.492716 (0.035865) |\n\n### Benchmark: benchmark_getitem\\_100B.json\n\n| metric | get_batch_of\\_1024\\_random_rows | get_batch_of\\_1024\\_rows | get_first_row | get_last_row |\n|--------|---|---|---|---|\n| new / old (diff) | 0.208732 / 0.018006 (0.190726) | 0.452572 / 0.000490 (0.452082) | 0.002936 / 0.000200 (0.002737) | 0.000082 / 0.000054 (0.000028) |\n\n### Benchmark: benchmark_indices_mapping.json\n\n| metric | select | shard | shuffle | sort | train_test_split |\n|--------|---|---|---|---|---|\n| new / old (diff) | 0.024616 / 0.037411 (-0.012795) | 0.107547 / 0.014526 (0.093021) | 0.114492 / 0.176557 (-0.062065) | 0.171770 / 0.737135 (-0.565365) | 0.122538 / 0.296338 (-0.173800) |\n\n### Benchmark: benchmark_iterating.json\n\n| metric | read 5000 | read 50000 | read_batch 50000 10 | read_batch 50000 100 | read_batch 50000 1000 | read_formatted numpy 5000 | read_formatted pandas 5000 | read_formatted tensorflow 5000 | read_formatted torch 5000 | read_formatted_batch numpy 5000 10 | read_formatted_batch numpy 5000 1000 | shuffled read 5000 | shuffled read 50000 | shuffled read_batch 50000 10 | shuffled read_batch 50000 100 | shuffled read_batch 50000 1000 | shuffled read_formatted numpy 5000 | shuffled read_formatted_batch numpy 5000 10 | shuffled read_formatted_batch numpy 5000 1000 |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.406140 / 0.215209 (0.190930) | 4.062391 / 2.077655 (1.984736) | 1.865962 / 1.504120 (0.361842) | 1.682236 / 1.541195 (0.141041) | 1.738119 / 1.468490 (0.269629) | 0.532244 / 4.584777 (-4.052533) | 3.816421 / 3.745712 (0.070709) | 2.981205 / 5.269862 (-2.288656) | 1.519497 / 4.565676 (-3.046179) | 0.065904 / 0.424275 (-0.358371) | 0.011277 / 0.007607 (0.003670) | 0.512789 / 0.226044 (0.286745) | 5.107618 / 2.268929 (2.838690) | 2.419399 / 55.444624 (-53.025226) | 2.079262 / 6.876477 (-4.797214) | 2.150447 / 2.142072 (0.008375) | 0.696737 / 4.805227 (-4.108490) | 0.142497 / 6.500664 (-6.358167) | 0.063521 / 0.075469 (-0.011949) |\n\n### Benchmark: benchmark_map_filter.json\n\n| metric | filter | map fast-tokenizer batched | map identity | map identity batched | map no-op batched | map no-op batched numpy | map no-op batched pandas | map no-op batched pytorch | map no-op batched tensorflow |\n|--------|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 1.180692 / 1.841788 (-0.661095) | 14.343084 / 8.074308 (6.268776) | 13.303719 / 10.191392 (3.112327) | 0.164234 / 0.680424 (-0.516190) | 0.017439 / 0.534201 (-0.516762) | 0.399712 / 0.579283 (-0.179571) | 0.428248 / 0.434364 (-0.006115) | 0.471909 / 0.540337 (-0.068428) | 0.573853 / 1.386936 (-0.813083) |\n\n</details>\nPyArrow==latest\n\n<details>\n<summary>Show updated benchmarks!</summary>\n\n### Benchmark: benchmark_array_xd.json\n\n| metric | read_batch_formatted_as_numpy after write_array2d | read_batch_formatted_as_numpy after write_flattened_sequence | read_batch_formatted_as_numpy after write_nested_sequence | read_batch_unformated after write_array2d | read_batch_unformated after write_flattened_sequence | read_batch_unformated after write_nested_sequence | read_col_formatted_as_numpy after write_array2d | read_col_formatted_as_numpy after write_flattened_sequence | read_col_formatted_as_numpy after write_nest

[{'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1601542007', 'html_url': 'https://github.com/huggingface/datasets/issues/5965#issuecomment-1601542007', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5965', 'id': 1601542007, 'node_id': 'IC_kwDODunzps5fdZd3', 'user': {'login': 'mariosasko', 'id': 47462742, 'node_id': 'MDQ6VXNlcjQ3NDYyNzQy', 'avatar_url': 'https://avatars.githubusercontent.com/u/47462742?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/mariosasko', 'html_url': 'https://github.com/mariosasko', 'followers_url': 'https://api.github.com/users/mariosasko/followers', 'following_url': 'https://api.github.com/users/mariosasko/following{/other_user}', 'gists_url': 'https://api.github.com/users/mariosasko/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/mariosasko/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/mariosasko/subscriptions', 'organizations_url': 'https://api.github.com/users/mariosasko/orgs', 'repos_url': 'https://api.github.com/users/mariosasko/repos', 'events_url': 'https://api.github.com/users/mariosasko/events{/privacy}', 'received_events_url': 'https://api.github.com/users/mariosasko/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-21T19:21:09Z', 'updated_at': '2023-06-21T19:21:09Z', 'author_association': 'CONTRIBUTOR', 'body': 'Thanks for reporting! \r\n\r\nSpecifying the target features explicitly should avoid this error:\r\n```python\r\ndataset = dataset.map(\r\n    batch_process,\r\n    batched=True,\r\n    batch_size=1,\r\n    num_proc=1,\r\n    remove_columns=dataset.column_names,\r\n    features=datasets.Features({"texts": datasets.Sequence(datasets.Value("string"))})\r\n)\r\n```\r\n\r\nThis error stems from our type promotion not handling the nested case. But this promotion/casting allocates memory in most scenarios, which can be problematic for large datasets, so explicitly passing the features is the optimal solution.', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1601542007/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1601563320', 'html_url': 'https://github.com/huggingface/datasets/issues/5965#issuecomment-1601563320', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5965', 'id': 1601563320, 'node_id': 'IC_kwDODunzps5fdeq4', 'user': {'login': 'piercefreeman', 'id': 1712066, 'node_id': 'MDQ6VXNlcjE3MTIwNjY=', 'avatar_url': 'https://avatars.githubusercontent.com/u/1712066?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/piercefreeman', 'html_url': 'https://github.com/piercefreeman', 'followers_url': 'https://api.github.com/users/piercefreeman/followers', 'following_url': 'https://api.github.com/users/piercefreeman/following{/other_user}', 'gists_url': 'https://api.github.com/users/piercefreeman/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/piercefreeman/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/piercefreeman/subscriptions', 'organizations_url': 'https://api.github.com/users/piercefreeman/orgs', 'repos_url': 'https://api.github.com/users/piercefreeman/repos', 'events_url': 'https://api.github.com/users/piercefreeman/events{/privacy}', 'received_events_url': 'https://api.github.com/users/piercefreeman/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-21T19:35:37Z', 'updated_at': '2023-06-21T19:35:37Z', 'author_association': 'NONE', 'body': 'Hi @mariosasko thanks for the context, this is helpful to know. Would it be worth having some logic to generate this explicit feature specification automatically if a type annotation for a .map returns a dataclass that can be inferred?\r\n\r\nFeels like something that would be easy to implement and could save memory / deal with this case in a standardized way.', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1601563320/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1601590228', 'html_url': 'https://github.com/huggingface/datasets/issues/5965#issuecomment-1601590228', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5965', 'id': 1601590228, 'node_id': 'IC_kwDODunzps5fdlPU', 'user': {'login': 'mariosasko', 'id': 47462742, 'node_id': 'MDQ6VXNlcjQ3NDYyNzQy', 'avatar_url': 'https://avatars.githubusercontent.com/u/47462742?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/mariosasko', 'html_url': 'https://github.com/mariosasko', 'followers_url': 'https://api.github.com/users/mariosasko/followers', 'following_url': 'https://api.github.com/users/mariosasko/following{/other_user}', 'gists_url': 'https://api.github.com/users/mariosasko/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/mariosasko/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/mariosasko/subscriptions', 'organizations_url': 'https://api.github.com/users/mariosasko/orgs', 'repos_url': 'https://api.github.com/users/mariosasko/repos', 'events_url': 'https://api.github.com/users/mariosasko/events{/privacy}', 'received_events_url': 'https://api.github.com/users/mariosasko/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-21T19:59:53Z', 'updated_at': '2023-06-21T20:00:03Z', 'author_association': 'CONTRIBUTOR', 'body': '> . Would it be worth having some logic to generate this explicit feature specification automatically if a type annotation for a .map returns a dataclass that can be inferred?\r\n\r\nInteresting proposal! Yes, we could consider doing this if the (return) type hint is `TypedDict`, and raise an error that type hints are incorrect if the cast using the inferred types fails.', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1601590228/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}]
[{'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1597170512', 'html_url': 'https://github.com/huggingface/datasets/pull/5964#issuecomment-1597170512', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5964', 'id': 1597170512, 'node_id': 'IC_kwDODunzps5fMuNQ', 'user': {'login': 'HuggingFaceDocBuilderDev', 'id': 99929124, 'node_id': 'U_kgDOBfTMJA', 'avatar_url': 'https://avatars.githubusercontent.com/u/99929124?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/HuggingFaceDocBuilderDev', 'html_url': 'https://github.com/HuggingFaceDocBuilderDev', 'followers_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/followers', 'following_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/following{/other_user}', 'gists_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/subscriptions', 'organizations_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/orgs', 'repos_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/repos', 'events_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/events{/privacy}', 'received_events_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-19T13:12:33Z', 'updated_at': '2023-06-19T17:23:12Z', 'author_association': 'NONE', 'body': '_The documentation is not available anymore as the PR was closed or merged._', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1597170512/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1597525248', 'html_url': 'https://github.com/huggingface/datasets/pull/5964#issuecomment-1597525248', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5964', 'id': 1597525248, 'node_id': 'IC_kwDODunzps5fOE0A', 'user': {'login': 'github-actions[bot]', 'id': 41898282, 'node_id': 'MDM6Qm90NDE4OTgyODI=', 'avatar_url': 'https://avatars.githubusercontent.com/in/15368?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/github-actions%5Bbot%5D', 'html_url': 'https://github.com/apps/github-actions', 'followers_url': 'https://api.github.com/users/github-actions%5Bbot%5D/followers', 'following_url': 'https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}', 'gists_url': 'https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/github-actions%5Bbot%5D/subscriptions', 'organizations_url': 'https://api.github.com/users/github-actions%5Bbot%5D/orgs', 'repos_url': 'https://api.github.com/users/github-actions%5Bbot%5D/repos', 'events_url': 'https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}', 'received_events_url': 'https://api.github.com/users/github-actions%5Bbot%5D/received_events', 'type': 'Bot', 'site_admin': False}, 'created_at': '2023-06-19T17:29:36Z', 'updated_at': '2023-06-19T17:29:36Z', 'author_association': 'NONE', 'body': '<details>\n<summary>Show benchmarks</summary>\n\nPyArrow==8.0.0\n\n<details>\n<summary>Show updated benchmarks!</summary>\n\n### Benchmark: benchmark_array_xd.json\n\n| metric | read_batch_formatted_as_numpy after write_array2d | read_batch_formatted_as_numpy after write_flattened_sequence | read_batch_formatted_as_numpy after write_nested_sequence | read_batch_unformated after write_array2d | read_batch_unformated after write_flattened_sequence | read_batch_unformated after write_nested_sequence | read_col_formatted_as_numpy after write_array2d | read_col_formatted_as_numpy after write_flattened_sequence | read_col_formatted_as_numpy after write_nested_sequence | read_col_unformated after write_array2d | read_col_unformated after write_flattened_sequence | read_col_unformated after write_nested_sequence | read_formatted_as_numpy after write_array2d | read_formatted_as_numpy after write_flattened_sequence | read_formatted_as_numpy after write_nested_sequence | read_unformated after write_array2d | read_unformated after write_flattened_sequence | read_unformated after write_nested_sequence | write_array2d | write_flattened_sequence | write_nested_sequence |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.006795 / 0.011353 (-0.004558) | 0.004170 / 0.011008 (-0.006838) | 0.098698 / 0.038508 (0.060190) | 0.045393 / 0.023109 (0.022284) | 0.309205 / 0.275898 (0.033307) | 0.361333 / 0.323480 (0.037853) | 0.006009 / 0.007986 (-0.001977) | 0.003334 / 0.004328 (-0.000995) | 0.075071 / 0.004250 (0.070821) | 0.062587 / 0.037052 (0.025535) | 0.322395 / 0.258489 (0.063906) | 0.360499 / 0.293841 (0.066659) | 0.032243 / 0.128546 (-0.096303) | 0.008768 / 0.075646 (-0.066878) | 0.329799 / 0.419271 (-0.089472) | 0.062261 / 0.043533 (0.018728) | 0.298112 / 0.255139 (0.042973) | 0.322815 / 0.283200 (0.039615) | 0.032348 / 0.141683 (-0.109335) | 1.445807 / 1.452155 (-0.006347) | 1.528768 / 1.492716 (0.036051) |\n\n### Benchmark: benchmark_getitem\\_100B.json\n\n| metric | get_batch_of\\_1024\\_random_rows | get_batch_of\\_1024\\_rows | get_first_row | get_last_row |\n|--------|---|---|---|---|\n| new / old (diff) | 0.195701 / 0.018006 (0.177695) | 0.437042 / 0.000490 (0.436552) | 0.003867 / 0.000200 (0.003667) | 0.000080 / 0.000054 (0.000026) |\n\n### Benchmark: benchmark_indices_mapping.json\n\n| metric | select | shard | shuffle | sort | train_test_split |\n|--------|---|---|---|---|---|\n| new / old (diff) | 0.026713 / 0.037411 (-0.010698) | 0.109548 / 0.014526 (0.095022) | 0.119216 / 0.176557 (-0.057341) | 0.178947 / 0.737135 (-0.558188) | 0.125224 / 0.296338 (-0.171114) |\n\n### Benchmark: benchmark_iterating.json\n\n| metric | read 5000 | read 50000 | read_batch 50000 10 | read_batch 50000 100 | read_batch 50000 1000 | read_formatted numpy 5000 | read_formatted pandas 5000 | read_formatted tensorflow 5000 | read_formatted torch 5000 | read_formatted_batch numpy 5000 10 | read_formatted_batch numpy 5000 1000 | shuffled read 5000 | shuffled read 50000 | shuffled read_batch 50000 10 | shuffled read_batch 50000 100 | shuffled read_batch 50000 1000 | shuffled read_formatted numpy 5000 | shuffled read_formatted_batch numpy 5000 10 | shuffled read_formatted_batch numpy 5000 1000 |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.400885 / 0.215209 (0.185676) | 3.991223 / 2.077655 (1.913568) | 1.818449 / 1.504120 (0.314329) | 1.609285 / 1.541195 (0.068090) | 1.666675 / 1.468490 (0.198184) | 0.531486 / 4.584777 (-4.053291) | 3.770142 / 3.745712 (0.024430) | 3.057189 / 5.269862 (-2.212673) | 1.517491 / 4.565676 (-3.048186) | 0.065782 / 0.424275 (-0.358493) | 0.011251 / 0.007607 (0.003644) | 0.504277 / 0.226044 (0.278233) | 5.038979 / 2.268929 (2.770050) | 2.254717 / 55.444624 (-53.189908) | 1.929743 / 6.876477 (-4.946734) | 2.080051 / 2.142072 (-0.062022) | 0.656831 / 4.805227 (-4.148396) | 0.142860 / 6.500664 (-6.357804) | 0.063057 / 0.075469 (-0.012412) |\n\n### Benchmark: benchmark_map_filter.json\n\n| metric | filter | map fast-tokenizer batched | map identity | map identity batched | map no-op batched | map no-op batched numpy | map no-op batched pandas | map no-op batched pytorch | map no-op batched tensorflow |\n|--------|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 1.208819 / 1.841788 (-0.632969) | 14.456966 / 8.074308 (6.382658) | 12.839799 / 10.191392 (2.648407) | 0.164361 / 0.680424 (-0.516063) | 0.017330 / 0.534201 (-0.516871) | 0.397384 / 0.579283 (-0.181899) | 0.422704 / 0.434364 (-0.011660) | 0.472065 / 0.540337 (-0.068273) | 0.576960 / 1.386936 (-0.809976) |\n\n</details>\nPyArrow==latest\n\n<details>\n<summary>Show updated benchmarks!</summary>\n\n### Benchmark: benchmark_array_xd.json\n\n| metric | read_batch_formatted_as_numpy after write_array2d | read_batch_formatted_as_numpy after write_flattened_sequence | read_batch_formatted_as_numpy after write_nested_sequence | read_batch_unformated after write_array2d | read_batch_unformated after write_flattened_sequence | read_batch_unformated after write_nested_sequence | read_col_formatted_as_numpy after write_array2d | read_col_formatted_as_numpy after write_flattened_sequence | read_col_formatted_as_numpy after write_nested_sequence | read_col_unformated after write_array2d | read_col_unformated after write_flattened_sequence | read_col_unformated after write_nested_sequence | read_formatted_as_numpy after write_array2d | read_formatted_as_numpy after write_flattened_sequence | read_formatted_as_numpy after write_nested_sequence | read_unformated after write_array2d | read_unformated after write_flattened_sequence | read_unformated after write_nested_sequence | write_array2d | write_flattened_sequence | write_nested_sequence |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.006950 / 0.011353 (-0.004403) | 0.004012 / 0.011008 (-0.006997) | 0.076050 / 0.038508 (0.037542) | 0.046646 / 0.023109 (0.023537) | 0.353813 / 0.275898 (0.077915) | 0.417111 / 0.323480 (0.093631) | 0.005422 / 0.007986 (-0.002564) | 0.003356 / 0.004328 (-0.000972) | 0.076662 / 0.004250 (0.072411) | 0.055018 / 0.037052 (0.017966) | 0.371561 / 0.258489 (0.113072) | 0.410471 / 0.293841 (0.116630) | 0.031860 / 0.128546 (-0.096686) | 0.008754 / 0.075646 (-0.066893) | 0.083192 / 0.419271 (-0.336079) | 0.050479 / 0.043533 (0.006946) | 0.351725 / 0.255139 (0.096586) | 0.371596 / 0.283200 (0.088396) | 0.023042 / 0.141683 (-0.118641) | 1.480533 / 1.452155 (0.028379) | 1.545970 / 1.492716 (0.053254) |\n\n### Benchmark: benchmark_getitem\\_100B.json\n\n| metric | get_batch_of\\_1024\\_random_rows | get_batch_of\\_1024\\_rows | get_first_row | get_last_row |\n|--------|---|---|---|---|\n| new / old (diff) | 0.220095 / 0.018006 (0.202089) | 0.441550 / 0.000490 (0.441061) | 0.000375 / 0.000200 (0.000175) | 0.000056 / 0.000054 (0.000002) |\n\n### Benchmark: benchmark_indices_mapping.json\n\n| metric | select | shard | shuffle | sort | train_test_split |\n|--------|---|---|---|---|---|\n| new / old (diff) | 0.029527 / 0.037411 (-0.007884) | 0.111645 / 0.014526 (0.097119) | 0.125732 / 0.176557 (-0.050825) | 0.177322 / 0.737135 (-0.559813) | 0.128620 / 0.296338 (-0.167718) |\n\n### Benchmark: benchmark_iterating.json\n\n| metric | read 5000 | read 50000 | read_batch 50000 10 | read_batch 50000 100 | read_batch 50000 1000 | read_formatted numpy 5000 | read_formatted pandas 5000 | read_formatted tensorflow 5000 | read_formatted torch 5000 | read_formatted_batch numpy 5000 10 | read_formatted_batch numpy 5000 1000 | shuffled read 5000 | shuffled read 50000 | shuffled read_batch 50000 10 | shuffled read_batch 50000 100 | shuffled read_batch 50000 1000 | shuffled read_formatted numpy 5000 | shuffled read_formatted_batch numpy 5000 10 | shuffled read_formatted_batch numpy 5000 1000 |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.432415 / 0.215209 (0.217206) | 4.314381 / 2.077655 (2.236726) | 2.079450 / 1.504120 (0.575331) | 1.893139 / 1.541195 (0.351944) | 1.951363 / 1.468490 (0.482873) | 0.531466 / 4.584777 (-4.053311) | 3.716860 / 3.745712 (-0.028852) | 1.850111 / 5.269862 (-3.419750) | 1.100676 / 4.565676 (-3.465000) | 0.066247 / 0.424275 (-0.358028) | 0.011503 / 0.007607 (0.003896) | 0.537208 / 0.226044 (0.311164) | 5.367560 / 2.268929 (3.098631) | 2.543697 / 55.444624 (-52.900927) | 2.221670 / 6.876477 (-4.654806) | 2.252009 / 2.142072 (0.109937) | 0.658509 / 4.805227 (-4.146718) | 0.142345 / 6.500664 (-6.358319) | 0.064701 / 0.075469 (-0.010768) |\n\n### Benchmark: benchmark_map_filter.json\n\n| metric | filter | map fast-tokenizer batched | map identity | map identity batched | map no-op batched | map no-op batched numpy | map no-op batched pandas | map no-op batched pytorch | map no-op batched tensorflow |\n|--------|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 1.266442 / 1.841788 (-0.575346) | 15.105953 / 8.074308 (7.031645) | 14.288229 / 10.191392 (4.096837) | 0.161182 / 0.680424 (-0.519242) | 0.017074 / 0.534201 (-0.517127) | 0.399464 / 0.579283 (-0.179819) | 0.419459 / 0.434364 (-0.014905) | 0.467553 / 0.540337 (-0.072784) | 0.566337 / 1.386936 (-0.820599) |\n\n</details>\n</details>\n\n![](https://cml.dev/watermark.png#53ac2d9662f9e5923ae7c52199eaa620d82f0043 "CML watermark")\n', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1597525248/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}]

[{'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1596531677', 'html_url': 'https://github.com/huggingface/datasets/issues/5963#issuecomment-1596531677', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5963', 'id': 1596531677, 'node_id': 'IC_kwDODunzps5fKSPd', 'user': {'login': 'yanzia12138', 'id': 112800614, 'node_id': 'U_kgDOBrkzZg', 'avatar_url': 'https://avatars.githubusercontent.com/u/112800614?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/yanzia12138', 'html_url': 'https://github.com/yanzia12138', 'followers_url': 'https://api.github.com/users/yanzia12138/followers', 'following_url': 'https://api.github.com/users/yanzia12138/following{/other_user}', 'gists_url': 'https://api.github.com/users/yanzia12138/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/yanzia12138/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/yanzia12138/subscriptions', 'organizations_url': 'https://api.github.com/users/yanzia12138/orgs', 'repos_url': 'https://api.github.com/users/yanzia12138/repos', 'events_url': 'https://api.github.com/users/yanzia12138/events{/privacy}', 'received_events_url': 'https://api.github.com/users/yanzia12138/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-19T05:31:46Z', 'updated_at': '2023-06-19T05:33:39Z', 'author_association': 'NONE', 'body': 'i got error using method from_spark  when using multi-node Spark cluster. seems could only use "from_spark" in local?', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1596531677/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1596700502', 'html_url': 'https://github.com/huggingface/datasets/issues/5963#issuecomment-1596700502', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5963', 'id': 1596700502, 'node_id': 'IC_kwDODunzps5fK7dW', 'user': {'login': 'yanzia12138', 'id': 112800614, 'node_id': 'U_kgDOBrkzZg', 'avatar_url': 'https://avatars.githubusercontent.com/u/112800614?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/yanzia12138', 'html_url': 'https://github.com/yanzia12138', 'followers_url': 'https://api.github.com/users/yanzia12138/followers', 'following_url': 'https://api.github.com/users/yanzia12138/following{/other_user}', 'gists_url': 'https://api.github.com/users/yanzia12138/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/yanzia12138/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/yanzia12138/subscriptions', 'organizations_url': 'https://api.github.com/users/yanzia12138/orgs', 'repos_url': 'https://api.github.com/users/yanzia12138/repos', 'events_url': 'https://api.github.com/users/yanzia12138/events{/privacy}', 'received_events_url': 'https://api.github.com/users/yanzia12138/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-19T08:01:40Z', 'updated_at': '2023-06-19T08:01:40Z', 'author_association': 'NONE', 'body': '@lhoestq ', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1596700502/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1596951620', 'html_url': 'https://github.com/huggingface/datasets/issues/5963#issuecomment-1596951620', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5963', 'id': 1596951620, 'node_id': 'IC_kwDODunzps5fL4xE', 'user': {'login': 'lhoestq', 'id': 42851186, 'node_id': 'MDQ6VXNlcjQyODUxMTg2', 'avatar_url': 'https://avatars.githubusercontent.com/u/42851186?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/lhoestq', 'html_url': 'https://github.com/lhoestq', 'followers_url': 'https://api.github.com/users/lhoestq/followers', 'following_url': 'https://api.github.com/users/lhoestq/following{/other_user}', 'gists_url': 'https://api.github.com/users/lhoestq/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/lhoestq/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/lhoestq/subscriptions', 'organizations_url': 'https://api.github.com/users/lhoestq/orgs', 'repos_url': 'https://api.github.com/users/lhoestq/repos', 'events_url': 'https://api.github.com/users/lhoestq/events{/privacy}', 'received_events_url': 'https://api.github.com/users/lhoestq/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-19T10:44:30Z', 'updated_at': '2023-06-19T10:44:30Z', 'author_association': 'MEMBER', 'body': 'cc @maddiedawson it looks like there an issue with `_validate_cache_dir` ?\r\n\r\nIt looks like the function passed to mapPartitions has a reference to the Spark dataset builder, and therefore contains the SparkContext itself.\r\n\r\nI think it can be fixed by defining `create_cache_and_write_probe` outside the Spark dataset builder, and pass a `partial(create_cache_and_write_probe, cache_dir=self._cache_dir)` to `mapPartitions`', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1596951620/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1608421944', 'html_url': 'https://github.com/huggingface/datasets/issues/5963#issuecomment-1608421944', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5963', 'id': 1608421944, 'node_id': 'IC_kwDODunzps5f3pI4', 'user': {'login': 'maddiedawson', 'id': 106995444, 'node_id': 'U_kgDOBmCe9A', 'avatar_url': 'https://avatars.githubusercontent.com/u/106995444?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/maddiedawson', 'html_url': 'https://github.com/maddiedawson', 'followers_url': 'https://api.github.com/users/maddiedawson/followers', 'following_url': 'https://api.github.com/users/maddiedawson/following{/other_user}', 'gists_url': 'https://api.github.com/users/maddiedawson/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/maddiedawson/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/maddiedawson/subscriptions', 'organizations_url': 'https://api.github.com/users/maddiedawson/orgs', 'repos_url': 'https://api.github.com/users/maddiedawson/repos', 'events_url': 'https://api.github.com/users/maddiedawson/events{/privacy}', 'received_events_url': 'https://api.github.com/users/maddiedawson/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-26T22:48:38Z', 'updated_at': '2023-06-26T22:48:38Z', 'author_association': 'CONTRIBUTOR', 'body': 'Just saw this; thanks for flagging! Your proposed solution sounds good. I can prepare a PR', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1608421944/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1612321233', 'html_url': 'https://github.com/huggingface/datasets/issues/5963#issuecomment-1612321233', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5963', 'id': 1612321233, 'node_id': 'IC_kwDODunzps5gGhHR', 'user': {'login': 'yanzia12138', 'id': 112800614, 'node_id': 'U_kgDOBrkzZg', 'avatar_url': 'https://avatars.githubusercontent.com/u/112800614?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/yanzia12138', 'html_url': 'https://github.com/yanzia12138', 'followers_url': 'https://api.github.com/users/yanzia12138/followers', 'following_url': 'https://api.github.com/users/yanzia12138/following{/other_user}', 'gists_url': 'https://api.github.com/users/yanzia12138/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/yanzia12138/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/yanzia12138/subscriptions', 'organizations_url': 'https://api.github.com/users/yanzia12138/orgs', 'repos_url': 'https://api.github.com/users/yanzia12138/repos', 'events_url': 'https://api.github.com/users/yanzia12138/events{/privacy}', 'received_events_url': 'https://api.github.com/users/yanzia12138/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-29T01:58:26Z', 'updated_at': '2023-06-29T01:58:26Z', 'author_association': 'NONE', 'body': '@maddiedawson  can you show me the demo ,so i can test in local .before your PR', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1612321233/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}]

[]
[{'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1592811547', 'html_url': 'https://github.com/huggingface/datasets/issues/5961#issuecomment-1592811547', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5961', 'id': 1592811547, 'node_id': 'IC_kwDODunzps5e8GAb', 'user': {'login': 'johnchienbronci', 'id': 27708347, 'node_id': 'MDQ6VXNlcjI3NzA4MzQ3', 'avatar_url': 'https://avatars.githubusercontent.com/u/27708347?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/johnchienbronci', 'html_url': 'https://github.com/johnchienbronci', 'followers_url': 'https://api.github.com/users/johnchienbronci/followers', 'following_url': 'https://api.github.com/users/johnchienbronci/following{/other_user}', 'gists_url': 'https://api.github.com/users/johnchienbronci/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/johnchienbronci/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/johnchienbronci/subscriptions', 'organizations_url': 'https://api.github.com/users/johnchienbronci/orgs', 'repos_url': 'https://api.github.com/users/johnchienbronci/repos', 'events_url': 'https://api.github.com/users/johnchienbronci/events{/privacy}', 'received_events_url': 'https://api.github.com/users/johnchienbronci/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-15T10:50:41Z', 'updated_at': '2023-06-15T10:50:41Z', 'author_association': 'NONE', 'body': 'Does "number of shards" refer to the total number of data?\r\n\r\nmy config:\r\nnproc_per_node=2\r\nds=ds[\'train\'] = load_dataset(streaming=True).take(50000)\r\n\r\nI\'m test again: in prepare_data(),  data have the same for each GPU\r\n', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1592811547/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1592831128', 'html_url': 'https://github.com/huggingface/datasets/issues/5961#issuecomment-1592831128', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5961', 'id': 1592831128, 'node_id': 'IC_kwDODunzps5e8KyY', 'user': {'login': 'lhoestq', 'id': 42851186, 'node_id': 'MDQ6VXNlcjQyODUxMTg2', 'avatar_url': 'https://avatars.githubusercontent.com/u/42851186?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/lhoestq', 'html_url': 'https://github.com/lhoestq', 'followers_url': 'https://api.github.com/users/lhoestq/followers', 'following_url': 'https://api.github.com/users/lhoestq/following{/other_user}', 'gists_url': 'https://api.github.com/users/lhoestq/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/lhoestq/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/lhoestq/subscriptions', 'organizations_url': 'https://api.github.com/users/lhoestq/orgs', 'repos_url': 'https://api.github.com/users/lhoestq/repos', 'events_url': 'https://api.github.com/users/lhoestq/events{/privacy}', 'received_events_url': 'https://api.github.com/users/lhoestq/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-15T11:00:31Z', 'updated_at': '2023-06-15T11:00:31Z', 'author_association': 'MEMBER', 'body': "The number of shards is `ds.n_shards`. It corresponds generally to the number of files the dataset is made of, to be able to distribute to several nodes.\r\n\r\n**You don't end up with the same data per GPU**. But all the samples are going through your preprocessing function you pass to map. They are just skipped afterwards to only keep 1 sample out of n(GPUs)", 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1592831128/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1592854470', 'html_url': 'https://github.com/huggingface/datasets/issues/5961#issuecomment-1592854470', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5961', 'id': 1592854470, 'node_id': 'IC_kwDODunzps5e8QfG', 'user': {'login': 'johnchienbronci', 'id': 27708347, 'node_id': 'MDQ6VXNlcjI3NzA4MzQ3', 'avatar_url': 'https://avatars.githubusercontent.com/u/27708347?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/johnchienbronci', 'html_url': 'https://github.com/johnchienbronci', 'followers_url': 'https://api.github.com/users/johnchienbronci/followers', 'following_url': 'https://api.github.com/users/johnchienbronci/following{/other_user}', 'gists_url': 'https://api.github.com/users/johnchienbronci/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/johnchienbronci/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/johnchienbronci/subscriptions', 'organizations_url': 'https://api.github.com/users/johnchienbronci/orgs', 'repos_url': 'https://api.github.com/users/johnchienbronci/repos', 'events_url': 'https://api.github.com/users/johnchienbronci/events{/privacy}', 'received_events_url': 'https://api.github.com/users/johnchienbronci/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-15T11:17:36Z', 'updated_at': '2023-06-15T11:17:36Z', 'author_association': 'NONE', 'body': 'For each GPU, although see the same data in prepare_data(), the actual training data will not be the same in the end. \r\nIs my understanding correct?\r\n\r\nWhere can I print the actual training data for each GPU?', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1592854470/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1592880136', 'html_url': 'https://github.com/huggingface/datasets/issues/5961#issuecomment-1592880136', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5961', 'id': 1592880136, 'node_id': 'IC_kwDODunzps5e8WwI', 'user': {'login': 'lhoestq', 'id': 42851186, 'node_id': 'MDQ6VXNlcjQyODUxMTg2', 'avatar_url': 'https://avatars.githubusercontent.com/u/42851186?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/lhoestq', 'html_url': 'https://github.com/lhoestq', 'followers_url': 'https://api.github.com/users/lhoestq/followers', 'following_url': 'https://api.github.com/users/lhoestq/following{/other_user}', 'gists_url': 'https://api.github.com/users/lhoestq/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/lhoestq/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/lhoestq/subscriptions', 'organizations_url': 'https://api.github.com/users/lhoestq/orgs', 'repos_url': 'https://api.github.com/users/lhoestq/repos', 'events_url': 'https://api.github.com/users/lhoestq/events{/privacy}', 'received_events_url': 'https://api.github.com/users/lhoestq/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-15T11:39:25Z', 'updated_at': '2023-06-15T11:39:25Z', 'author_association': 'MEMBER', 'body': '> For each GPU, although see the same data in prepare_data(), the actual training data will not be the same in the end.\r\nIs my understanding correct?\r\n\r\nYes exactly :)\r\n\r\n> Where can I print the actual training data for each GPU?\r\n\r\nYou should call print in the data_collator', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1592880136/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1595674774', 'html_url': 'https://github.com/huggingface/datasets/issues/5961#issuecomment-1595674774', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5961', 'id': 1595674774, 'node_id': 'IC_kwDODunzps5fHBCW', 'user': {'login': 'johnchienbronci', 'id': 27708347, 'node_id': 'MDQ6VXNlcjI3NzA4MzQ3', 'avatar_url': 'https://avatars.githubusercontent.com/u/27708347?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/johnchienbronci', 'html_url': 'https://github.com/johnchienbronci', 'followers_url': 'https://api.github.com/users/johnchienbronci/followers', 'following_url': 'https://api.github.com/users/johnchienbronci/following{/other_user}', 'gists_url': 'https://api.github.com/users/johnchienbronci/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/johnchienbronci/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/johnchienbronci/subscriptions', 'organizations_url': 'https://api.github.com/users/johnchienbronci/orgs', 'repos_url': 'https://api.github.com/users/johnchienbronci/repos', 'events_url': 'https://api.github.com/users/johnchienbronci/events{/privacy}', 'received_events_url': 'https://api.github.com/users/johnchienbronci/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-17T08:45:06Z', 'updated_at': '2023-06-17T08:45:06Z', 'author_association': 'NONE', 'body': 'I print out n_shards, and under multiple GPUs, this value is always 1.\r\nIs this value correct?', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1595674774/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1596987676', 'html_url': 'https://github.com/huggingface/datasets/issues/5961#issuecomment-1596987676', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5961', 'id': 1596987676, 'node_id': 'IC_kwDODunzps5fMBkc', 'user': {'login': 'lhoestq', 'id': 42851186, 'node_id': 'MDQ6VXNlcjQyODUxMTg2', 'avatar_url': 'https://avatars.githubusercontent.com/u/42851186?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/lhoestq', 'html_url': 'https://github.com/lhoestq', 'followers_url': 'https://api.github.com/users/lhoestq/followers', 'following_url': 'https://api.github.com/users/lhoestq/following{/other_user}', 'gists_url': 'https://api.github.com/users/lhoestq/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/lhoestq/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/lhoestq/subscriptions', 'organizations_url': 'https://api.github.com/users/lhoestq/orgs', 'repos_url': 'https://api.github.com/users/lhoestq/repos', 'events_url': 'https://api.github.com/users/lhoestq/events{/privacy}', 'received_events_url': 'https://api.github.com/users/lhoestq/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-19T11:08:52Z', 'updated_at': '2023-06-19T11:08:52Z', 'author_association': 'MEMBER', 'body': "Yes it's correct, and it explains why you always have the same data passed to your map function (the data can't be split).\r\n\r\nBut after being passed to `map`, each GPU keeps one example out of n(GPUs) so that you don't end up with duplicate data across GPUs", 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1596987676/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1597994829', 'html_url': 'https://github.com/huggingface/datasets/issues/5961#issuecomment-1597994829', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5961', 'id': 1597994829, 'node_id': 'IC_kwDODunzps5fP3dN', 'user': {'login': 'johnchienbronci', 'id': 27708347, 'node_id': 'MDQ6VXNlcjI3NzA4MzQ3', 'avatar_url': 'https://avatars.githubusercontent.com/u/27708347?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/johnchienbronci', 'html_url': 'https://github.com/johnchienbronci', 'followers_url': 'https://api.github.com/users/johnchienbronci/followers', 'following_url': 'https://api.github.com/users/johnchienbronci/following{/other_user}', 'gists_url': 'https://api.github.com/users/johnchienbronci/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/johnchienbronci/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/johnchienbronci/subscriptions', 'organizations_url': 'https://api.github.com/users/johnchienbronci/orgs', 'repos_url': 'https://api.github.com/users/johnchienbronci/repos', 'events_url': 'https://api.github.com/users/johnchienbronci/events{/privacy}', 'received_events_url': 'https://api.github.com/users/johnchienbronci/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-20T01:30:40Z', 'updated_at': '2023-06-20T01:30:40Z', 'author_association': 'NONE', 'body': '> > For each GPU, although see the same data in prepare_data(), the actual training data will not be the same in the end.\r\n> > Is my understanding correct?\r\n> \r\n> Yes exactly :)\r\n> \r\n> > Where can I print the actual training data for each GPU?\r\n> \r\n> You should call print in the data_collator\r\n\r\nOK, when printing the train data in the data collator, each GPU sees different data.\r\n\r\nThanks for your reply', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1597994829/reactions', 'total_count': 1, '+1': 1, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}]

[{'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1591751779', 'html_url': 'https://github.com/huggingface/datasets/issues/5959#issuecomment-1591751779', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5959', 'id': 1591751779, 'node_id': 'IC_kwDODunzps5e4DRj', 'user': {'login': 'JiazhaoLi', 'id': 31148397, 'node_id': 'MDQ6VXNlcjMxMTQ4Mzk3', 'avatar_url': 'https://avatars.githubusercontent.com/u/31148397?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/JiazhaoLi', 'html_url': 'https://github.com/JiazhaoLi', 'followers_url': 'https://api.github.com/users/JiazhaoLi/followers', 'following_url': 'https://api.github.com/users/JiazhaoLi/following{/other_user}', 'gists_url': 'https://api.github.com/users/JiazhaoLi/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/JiazhaoLi/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/JiazhaoLi/subscriptions', 'organizations_url': 'https://api.github.com/users/JiazhaoLi/orgs', 'repos_url': 'https://api.github.com/users/JiazhaoLi/repos', 'events_url': 'https://api.github.com/users/JiazhaoLi/events{/privacy}', 'received_events_url': 'https://api.github.com/users/JiazhaoLi/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-14T18:04:01Z', 'updated_at': '2023-06-14T18:04:01Z', 'author_association': 'NONE', 'body': "Sorry, I solve this by call `evaluate.load('glue_metric.py','sst-2')`\r\n", 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1591751779/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}]

[{'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1591599974', 'html_url': 'https://github.com/huggingface/datasets/pull/5957#issuecomment-1591599974', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5957', 'id': 1591599974, 'node_id': 'IC_kwDODunzps5e3eNm', 'user': {'login': 'github-actions[bot]', 'id': 41898282, 'node_id': 'MDM6Qm90NDE4OTgyODI=', 'avatar_url': 'https://avatars.githubusercontent.com/in/15368?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/github-actions%5Bbot%5D', 'html_url': 'https://github.com/apps/github-actions', 'followers_url': 'https://api.github.com/users/github-actions%5Bbot%5D/followers', 'following_url': 'https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}', 'gists_url': 'https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/github-actions%5Bbot%5D/subscriptions', 'organizations_url': 'https://api.github.com/users/github-actions%5Bbot%5D/orgs', 'repos_url': 'https://api.github.com/users/github-actions%5Bbot%5D/repos', 'events_url': 'https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}', 'received_events_url': 'https://api.github.com/users/github-actions%5Bbot%5D/received_events', 'type': 'Bot', 'site_admin': False}, 'created_at': '2023-06-14T16:24:30Z', 'updated_at': '2023-06-14T16:24:30Z', 'author_association': 'NONE', 'body': '<details>\n<summary>Show benchmarks</summary>\n\nPyArrow==8.0.0\n\n<details>\n<summary>Show updated benchmarks!</summary>\n\n### Benchmark: benchmark_array_xd.json\n\n| metric | read_batch_formatted_as_numpy after write_array2d | read_batch_formatted_as_numpy after write_flattened_sequence | read_batch_formatted_as_numpy after write_nested_sequence | read_batch_unformated after write_array2d | read_batch_unformated after write_flattened_sequence | read_batch_unformated after write_nested_sequence | read_col_formatted_as_numpy after write_array2d | read_col_formatted_as_numpy after write_flattened_sequence | read_col_formatted_as_numpy after write_nested_sequence | read_col_unformated after write_array2d | read_col_unformated after write_flattened_sequence | read_col_unformated after write_nested_sequence | read_formatted_as_numpy after write_array2d | read_formatted_as_numpy after write_flattened_sequence | read_formatted_as_numpy after write_nested_sequence | read_unformated after write_array2d | read_unformated after write_flattened_sequence | read_unformated after write_nested_sequence | write_array2d | write_flattened_sequence | write_nested_sequence |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.006498 / 0.011353 (-0.004855) | 0.003970 / 0.011008 (-0.007038) | 0.099242 / 0.038508 (0.060734) | 0.044363 / 0.023109 (0.021254) | 0.313900 / 0.275898 (0.038002) | 0.386562 / 0.323480 (0.063082) | 0.003837 / 0.007986 (-0.004149) | 0.004203 / 0.004328 (-0.000125) | 0.076191 / 0.004250 (0.071940) | 0.058823 / 0.037052 (0.021771) | 0.333838 / 0.258489 (0.075349) | 0.368235 / 0.293841 (0.074394) | 0.030774 / 0.128546 (-0.097772) | 0.008787 / 0.075646 (-0.066860) | 0.326474 / 0.419271 (-0.092798) | 0.050903 / 0.043533 (0.007370) | 0.303928 / 0.255139 (0.048789) | 0.321532 / 0.283200 (0.038333) | 0.024162 / 0.141683 (-0.117520) | 1.479662 / 1.452155 (0.027507) | 1.520300 / 1.492716 (0.027584) |\n\n### Benchmark: benchmark_getitem\\_100B.json\n\n| metric | get_batch_of\\_1024\\_random_rows | get_batch_of\\_1024\\_rows | get_first_row | get_last_row |\n|--------|---|---|---|---|\n| new / old (diff) | 0.212403 / 0.018006 (0.194397) | 0.448019 / 0.000490 (0.447529) | 0.005465 / 0.000200 (0.005265) | 0.000388 / 0.000054 (0.000334) |\n\n### Benchmark: benchmark_indices_mapping.json\n\n| metric | select | shard | shuffle | sort | train_test_split |\n|--------|---|---|---|---|---|\n| new / old (diff) | 0.027533 / 0.037411 (-0.009878) | 0.117477 / 0.014526 (0.102952) | 0.121182 / 0.176557 (-0.055374) | 0.181150 / 0.737135 (-0.555985) | 0.128557 / 0.296338 (-0.167782) |\n\n### Benchmark: benchmark_iterating.json\n\n| metric | read 5000 | read 50000 | read_batch 50000 10 | read_batch 50000 100 | read_batch 50000 1000 | read_formatted numpy 5000 | read_formatted pandas 5000 | read_formatted tensorflow 5000 | read_formatted torch 5000 | read_formatted_batch numpy 5000 10 | read_formatted_batch numpy 5000 1000 | shuffled read 5000 | shuffled read 50000 | shuffled read_batch 50000 10 | shuffled read_batch 50000 100 | shuffled read_batch 50000 1000 | shuffled read_formatted numpy 5000 | shuffled read_formatted_batch numpy 5000 10 | shuffled read_formatted_batch numpy 5000 1000 |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.397763 / 0.215209 (0.182554) | 3.959460 / 2.077655 (1.881805) | 1.822057 / 1.504120 (0.317937) | 1.627020 / 1.541195 (0.085826) | 1.695394 / 1.468490 (0.226904) | 0.536848 / 4.584777 (-4.047929) | 3.765205 / 3.745712 (0.019493) | 3.196300 / 5.269862 (-2.073561) | 1.623583 / 4.565676 (-2.942094) | 0.065823 / 0.424275 (-0.358452) | 0.011062 / 0.007607 (0.003455) | 0.500428 / 0.226044 (0.274384) | 5.008816 / 2.268929 (2.739888) | 2.314660 / 55.444624 (-53.129965) | 2.007429 / 6.876477 (-4.869047) | 2.141438 / 2.142072 (-0.000635) | 0.656697 / 4.805227 (-4.148530) | 0.143555 / 6.500664 (-6.357109) | 0.063928 / 0.075469 (-0.011541) |\n\n### Benchmark: benchmark_map_filter.json\n\n| metric | filter | map fast-tokenizer batched | map identity | map identity batched | map no-op batched | map no-op batched numpy | map no-op batched pandas | map no-op batched pytorch | map no-op batched tensorflow |\n|--------|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 1.169038 / 1.841788 (-0.672750) | 15.027186 / 8.074308 (6.952878) | 13.571484 / 10.191392 (3.380092) | 0.166437 / 0.680424 (-0.513986) | 0.017656 / 0.534201 (-0.516545) | 0.397725 / 0.579283 (-0.181558) | 0.451019 / 0.434364 (0.016655) | 0.469134 / 0.540337 (-0.071203) | 0.575885 / 1.386936 (-0.811051) |\n\n</details>\nPyArrow==latest\n\n<details>\n<summary>Show updated benchmarks!</summary>\n\n### Benchmark: benchmark_array_xd.json\n\n| metric | read_batch_formatted_as_numpy after write_array2d | read_batch_formatted_as_numpy after write_flattened_sequence | read_batch_formatted_as_numpy after write_nested_sequence | read_batch_unformated after write_array2d | read_batch_unformated after write_flattened_sequence | read_batch_unformated after write_nested_sequence | read_col_formatted_as_numpy after write_array2d | read_col_formatted_as_numpy after write_flattened_sequence | read_col_formatted_as_numpy after write_nested_sequence | read_col_unformated after write_array2d | read_col_unformated after write_flattened_sequence | read_col_unformated after write_nested_sequence | read_formatted_as_numpy after write_array2d | read_formatted_as_numpy after write_flattened_sequence | read_formatted_as_numpy after write_nested_sequence | read_unformated after write_array2d | read_unformated after write_flattened_sequence | read_unformated after write_nested_sequence | write_array2d | write_flattened_sequence | write_nested_sequence |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.006887 / 0.011353 (-0.004465) | 0.004166 / 0.011008 (-0.006842) | 0.077137 / 0.038508 (0.038629) | 0.055631 / 0.023109 (0.032522) | 0.397658 / 0.275898 (0.121760) | 0.473981 / 0.323480 (0.150502) | 0.005365 / 0.007986 (-0.002621) | 0.003401 / 0.004328 (-0.000928) | 0.076481 / 0.004250 (0.072231) | 0.056014 / 0.037052 (0.018961) | 0.415253 / 0.258489 (0.156764) | 0.457620 / 0.293841 (0.163779) | 0.031850 / 0.128546 (-0.096696) | 0.008869 / 0.075646 (-0.066777) | 0.083475 / 0.419271 (-0.335796) | 0.049232 / 0.043533 (0.005699) | 0.392947 / 0.255139 (0.137808) | 0.417243 / 0.283200 (0.134043) | 0.024554 / 0.141683 (-0.117129) | 1.508081 / 1.452155 (0.055926) | 1.541845 / 1.492716 (0.049129) |\n\n### Benchmark: benchmark_getitem\\_100B.json\n\n| metric | get_batch_of\\_1024\\_random_rows | get_batch_of\\_1024\\_rows | get_first_row | get_last_row |\n|--------|---|---|---|---|\n| new / old (diff) | 0.228470 / 0.018006 (0.210464) | 0.450933 / 0.000490 (0.450443) | 0.001508 / 0.000200 (0.001308) | 0.000083 / 0.000054 (0.000029) |\n\n### Benchmark: benchmark_indices_mapping.json\n\n| metric | select | shard | shuffle | sort | train_test_split |\n|--------|---|---|---|---|---|\n| new / old (diff) | 0.030189 / 0.037411 (-0.007222) | 0.118853 / 0.014526 (0.104327) | 0.124809 / 0.176557 (-0.051747) | 0.175066 / 0.737135 (-0.562069) | 0.129819 / 0.296338 (-0.166519) |\n\n### Benchmark: benchmark_iterating.json\n\n| metric | read 5000 | read 50000 | read_batch 50000 10 | read_batch 50000 100 | read_batch 50000 1000 | read_formatted numpy 5000 | read_formatted pandas 5000 | read_formatted tensorflow 5000 | read_formatted torch 5000 | read_formatted_batch numpy 5000 10 | read_formatted_batch numpy 5000 1000 | shuffled read 5000 | shuffled read 50000 | shuffled read_batch 50000 10 | shuffled read_batch 50000 100 | shuffled read_batch 50000 1000 | shuffled read_formatted numpy 5000 | shuffled read_formatted_batch numpy 5000 10 | shuffled read_formatted_batch numpy 5000 1000 |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.451830 / 0.215209 (0.236621) | 4.505352 / 2.077655 (2.427698) | 2.309303 / 1.504120 (0.805183) | 2.120983 / 1.541195 (0.579789) | 2.198808 / 1.468490 (0.730317) | 0.543836 / 4.584777 (-4.040940) | 3.836650 / 3.745712 (0.090938) | 1.872293 / 5.269862 (-3.397568) | 1.122335 / 4.565676 (-3.443342) | 0.067463 / 0.424275 (-0.356812) | 0.012143 / 0.007607 (0.004536) | 0.553674 / 0.226044 (0.327630) | 5.572101 / 2.268929 (3.303173) | 2.772151 / 55.444624 (-52.672473) | 2.451557 / 6.876477 (-4.424920) | 2.521241 / 2.142072 (0.379169) | 0.665799 / 4.805227 (-4.139428) | 0.143842 / 6.500664 (-6.356822) | 0.065373 / 0.075469 (-0.010096) |\n\n### Benchmark: benchmark_map_filter.json\n\n| metric | filter | map fast-tokenizer batched | map identity | map identity batched | map no-op batched | map no-op batched numpy | map no-op batched pandas | map no-op batched pytorch | map no-op batched tensorflow |\n|--------|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 1.271013 / 1.841788 (-0.570775) | 15.290054 / 8.074308 (7.215746) | 14.807044 / 10.191392 (4.615652) | 0.163767 / 0.680424 (-0.516657) | 0.017383 / 0.534201 (-0.516818) | 0.393046 / 0.579283 (-0.186237) | 0.423056 / 0.434364 (-0.011308) | 0.459193 / 0.540337 (-0.081145) | 0.559964 / 1.386936 (-0.826972) |\n\n</details>\n</details>\n\n![](https://cml.dev/watermark.png#011b75f044ef7fa6b8981ef3496615296aeb315b "CML watermark")\n', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1591599974/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1591600364', 'html_url': 'https://github.com/huggingface/datasets/pull/5957#issuecomment-1591600364', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5957', 'id': 1591600364, 'node_id': 'IC_kwDODunzps5e3eTs', 'user': {'login': 'HuggingFaceDocBuilderDev', 'id': 99929124, 'node_id': 'U_kgDOBfTMJA', 'avatar_url': 'https://avatars.githubusercontent.com/u/99929124?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/HuggingFaceDocBuilderDev', 'html_url': 'https://github.com/HuggingFaceDocBuilderDev', 'followers_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/followers', 'following_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/following{/other_user}', 'gists_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/subscriptions', 'organizations_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/orgs', 'repos_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/repos', 'events_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/events{/privacy}', 'received_events_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-14T16:24:46Z', 'updated_at': '2023-06-14T16:25:05Z', 'author_association': 'NONE', 'body': '_The documentation is not available anymore as the PR was closed or merged._', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1591600364/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1591613383', 'html_url': 'https://github.com/huggingface/datasets/pull/5957#issuecomment-1591613383', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5957', 'id': 1591613383, 'node_id': 'IC_kwDODunzps5e3hfH', 'user': {'login': 'github-actions[bot]', 'id': 41898282, 'node_id': 'MDM6Qm90NDE4OTgyODI=', 'avatar_url': 'https://avatars.githubusercontent.com/in/15368?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/github-actions%5Bbot%5D', 'html_url': 'https://github.com/apps/github-actions', 'followers_url': 'https://api.github.com/users/github-actions%5Bbot%5D/followers', 'following_url': 'https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}', 'gists_url': 'https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/github-actions%5Bbot%5D/subscriptions', 'organizations_url': 'https://api.github.com/users/github-actions%5Bbot%5D/orgs', 'repos_url': 'https://api.github.com/users/github-actions%5Bbot%5D/repos', 'events_url': 'https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}', 'received_events_url': 'https://api.github.com/users/github-actions%5Bbot%5D/received_events', 'type': 'Bot', 'site_admin': False}, 'created_at': '2023-06-14T16:32:18Z', 'updated_at': '2023-06-14T16:32:18Z', 'author_association': 'NONE', 'body': '<details>\n<summary>Show benchmarks</summary>\n\nPyArrow==8.0.0\n\n<details>\n<summary>Show updated benchmarks!</summary>\n\n### Benchmark: benchmark_array_xd.json\n\n| metric | read_batch_formatted_as_numpy after write_array2d | read_batch_formatted_as_numpy after write_flattened_sequence | read_batch_formatted_as_numpy after write_nested_sequence | read_batch_unformated after write_array2d | read_batch_unformated after write_flattened_sequence | read_batch_unformated after write_nested_sequence | read_col_formatted_as_numpy after write_array2d | read_col_formatted_as_numpy after write_flattened_sequence | read_col_formatted_as_numpy after write_nested_sequence | read_col_unformated after write_array2d | read_col_unformated after write_flattened_sequence | read_col_unformated after write_nested_sequence | read_formatted_as_numpy after write_array2d | read_formatted_as_numpy after write_flattened_sequence | read_formatted_as_numpy after write_nested_sequence | read_unformated after write_array2d | read_unformated after write_flattened_sequence | read_unformated after write_nested_sequence | write_array2d | write_flattened_sequence | write_nested_sequence |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.006112 / 0.011353 (-0.005241) | 0.003712 / 0.011008 (-0.007297) | 0.099996 / 0.038508 (0.061488) | 0.037526 / 0.023109 (0.014417) | 0.305834 / 0.275898 (0.029936) | 0.361368 / 0.323480 (0.037888) | 0.004849 / 0.007986 (-0.003136) | 0.002912 / 0.004328 (-0.001417) | 0.077729 / 0.004250 (0.073479) | 0.053203 / 0.037052 (0.016151) | 0.318088 / 0.258489 (0.059599) | 0.371745 / 0.293841 (0.077904) | 0.029384 / 0.128546 (-0.099162) | 0.008504 / 0.075646 (-0.067142) | 0.318472 / 0.419271 (-0.100799) | 0.046043 / 0.043533 (0.002510) | 0.310418 / 0.255139 (0.055279) | 0.335044 / 0.283200 (0.051844) | 0.020364 / 0.141683 (-0.121319) | 1.503201 / 1.452155 (0.051047) | 1.556408 / 1.492716 (0.063692) |\n\n### Benchmark: benchmark_getitem\\_100B.json\n\n| metric | get_batch_of\\_1024\\_random_rows | get_batch_of\\_1024\\_rows | get_first_row | get_last_row |\n|--------|---|---|---|---|\n| new / old (diff) | 0.210245 / 0.018006 (0.192239) | 0.418918 / 0.000490 (0.418428) | 0.002552 / 0.000200 (0.002352) | 0.000084 / 0.000054 (0.000030) |\n\n### Benchmark: benchmark_indices_mapping.json\n\n| metric | select | shard | shuffle | sort | train_test_split |\n|--------|---|---|---|---|---|\n| new / old (diff) | 0.022295 / 0.037411 (-0.015116) | 0.099534 / 0.014526 (0.085008) | 0.106432 / 0.176557 (-0.070124) | 0.165110 / 0.737135 (-0.572026) | 0.109851 / 0.296338 (-0.186488) |\n\n### Benchmark: benchmark_iterating.json\n\n| metric | read 5000 | read 50000 | read_batch 50000 10 | read_batch 50000 100 | read_batch 50000 1000 | read_formatted numpy 5000 | read_formatted pandas 5000 | read_formatted tensorflow 5000 | read_formatted torch 5000 | read_formatted_batch numpy 5000 10 | read_formatted_batch numpy 5000 1000 | shuffled read 5000 | shuffled read 50000 | shuffled read_batch 50000 10 | shuffled read_batch 50000 100 | shuffled read_batch 50000 1000 | shuffled read_formatted numpy 5000 | shuffled read_formatted_batch numpy 5000 10 | shuffled read_formatted_batch numpy 5000 1000 |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.423947 / 0.215209 (0.208738) | 4.232978 / 2.077655 (2.155323) | 2.004849 / 1.504120 (0.500729) | 1.814345 / 1.541195 (0.273151) | 1.809192 / 1.468490 (0.340702) | 0.561146 / 4.584777 (-4.023631) | 3.385043 / 3.745712 (-0.360669) | 1.708265 / 5.269862 (-3.561597) | 1.030290 / 4.565676 (-3.535387) | 0.067095 / 0.424275 (-0.357180) | 0.011052 / 0.007607 (0.003445) | 0.522416 / 0.226044 (0.296371) | 5.207003 / 2.268929 (2.938075) | 2.367067 / 55.444624 (-53.077558) | 1.998705 / 6.876477 (-4.877772) | 2.068633 / 2.142072 (-0.073439) | 0.672396 / 4.805227 (-4.132831) | 0.135818 / 6.500664 (-6.364846) | 0.065229 / 0.075469 (-0.010240) |\n\n### Benchmark: benchmark_map_filter.json\n\n| metric | filter | map fast-tokenizer batched | map identity | map identity batched | map no-op batched | map no-op batched numpy | map no-op batched pandas | map no-op batched pytorch | map no-op batched tensorflow |\n|--------|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 1.187079 / 1.841788 (-0.654709) | 13.893153 / 8.074308 (5.818845) | 13.951328 / 10.191392 (3.759936) | 0.142519 / 0.680424 (-0.537905) | 0.016546 / 0.534201 (-0.517655) | 0.364008 / 0.579283 (-0.215275) | 0.385957 / 0.434364 (-0.048407) | 0.425218 / 0.540337 (-0.115120) | 0.519586 / 1.386936 (-0.867350) |\n\n</details>\nPyArrow==latest\n\n<details>\n<summary>Show updated benchmarks!</summary>\n\n### Benchmark: benchmark_array_xd.json\n\n| metric | read_batch_formatted_as_numpy after write_array2d | read_batch_formatted_as_numpy after write_flattened_sequence | read_batch_formatted_as_numpy after write_nested_sequence | read_batch_unformated after write_array2d | read_batch_unformated after write_flattened_sequence | read_batch_unformated after write_nested_sequence | read_col_formatted_as_numpy after write_array2d | read_col_formatted_as_numpy after write_flattened_sequence | read_col_formatted_as_numpy after write_neste

[{'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1591262393', 'html_url': 'https://github.com/huggingface/datasets/pull/5956#issuecomment-1591262393', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5956', 'id': 1591262393, 'node_id': 'IC_kwDODunzps5e2Ly5', 'user': {'login': 'HuggingFaceDocBuilderDev', 'id': 99929124, 'node_id': 'U_kgDOBfTMJA', 'avatar_url': 'https://avatars.githubusercontent.com/u/99929124?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/HuggingFaceDocBuilderDev', 'html_url': 'https://github.com/HuggingFaceDocBuilderDev', 'followers_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/followers', 'following_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/following{/other_user}', 'gists_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/subscriptions', 'organizations_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/orgs', 'repos_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/repos', 'events_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/events{/privacy}', 'received_events_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-14T13:56:16Z', 'updated_at': '2023-06-14T14:34:12Z', 'author_association': 'NONE', 'body': '_The documentation is not available anymore as the PR was closed or merged._', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1591262393/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1591263440', 'html_url': 'https://github.com/huggingface/datasets/pull/5956#issuecomment-1591263440', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5956', 'id': 1591263440, 'node_id': 'IC_kwDODunzps5e2MDQ', 'user': {'login': 'github-actions[bot]', 'id': 41898282, 'node_id': 'MDM6Qm90NDE4OTgyODI=', 'avatar_url': 'https://avatars.githubusercontent.com/in/15368?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/github-actions%5Bbot%5D', 'html_url': 'https://github.com/apps/github-actions', 'followers_url': 'https://api.github.com/users/github-actions%5Bbot%5D/followers', 'following_url': 'https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}', 'gists_url': 'https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/github-actions%5Bbot%5D/subscriptions', 'organizations_url': 'https://api.github.com/users/github-actions%5Bbot%5D/orgs', 'repos_url': 'https://api.github.com/users/github-actions%5Bbot%5D/repos', 'events_url': 'https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}', 'received_events_url': 'https://api.github.com/users/github-actions%5Bbot%5D/received_events', 'type': 'Bot', 'site_admin': False}, 'created_at': '2023-06-14T13:56:53Z', 'updated_at': '2023-06-14T13:56:53Z', 'author_association': 'NONE', 'body': '<details>\n<summary>Show benchmarks</summary>\n\nPyArrow==8.0.0\n\n<details>\n<summary>Show updated benchmarks!</summary>\n\n### Benchmark: benchmark_array_xd.json\n\n| metric | read_batch_formatted_as_numpy after write_array2d | read_batch_formatted_as_numpy after write_flattened_sequence | read_batch_formatted_as_numpy after write_nested_sequence | read_batch_unformated after write_array2d | read_batch_unformated after write_flattened_sequence | read_batch_unformated after write_nested_sequence | read_col_formatted_as_numpy after write_array2d | read_col_formatted_as_numpy after write_flattened_sequence | read_col_formatted_as_numpy after write_nested_sequence | read_col_unformated after write_array2d | read_col_unformated after write_flattened_sequence | read_col_unformated after write_nested_sequence | read_formatted_as_numpy after write_array2d | read_formatted_as_numpy after write_flattened_sequence | read_formatted_as_numpy after write_nested_sequence | read_unformated after write_array2d | read_unformated after write_flattened_sequence | read_unformated after write_nested_sequence | write_array2d | write_flattened_sequence | write_nested_sequence |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.005893 / 0.011353 (-0.005460) | 0.003682 / 0.011008 (-0.007327) | 0.098358 / 0.038508 (0.059850) | 0.028130 / 0.023109 (0.005020) | 0.305960 / 0.275898 (0.030062) | 0.334869 / 0.323480 (0.011390) | 0.003522 / 0.007986 (-0.004463) | 0.003683 / 0.004328 (-0.000645) | 0.079418 / 0.004250 (0.075168) | 0.037662 / 0.037052 (0.000609) | 0.310893 / 0.258489 (0.052404) | 0.341347 / 0.293841 (0.047506) | 0.027450 / 0.128546 (-0.101096) | 0.008381 / 0.075646 (-0.067265) | 0.316020 / 0.419271 (-0.103252) | 0.045079 / 0.043533 (0.001546) | 0.307806 / 0.255139 (0.052667) | 0.331804 / 0.283200 (0.048604) | 0.091806 / 0.141683 (-0.049877) | 1.492611 / 1.452155 (0.040457) | 1.551762 / 1.492716 (0.059046) |\n\n### Benchmark: benchmark_getitem\\_100B.json\n\n| metric | get_batch_of\\_1024\\_random_rows | get_batch_of\\_1024\\_rows | get_first_row | get_last_row |\n|--------|---|---|---|---|\n| new / old (diff) | 0.201640 / 0.018006 (0.183634) | 0.422776 / 0.000490 (0.422286) | 0.003734 / 0.000200 (0.003535) | 0.000080 / 0.000054 (0.000026) |\n\n### Benchmark: benchmark_indices_mapping.json\n\n| metric | select | shard | shuffle | sort | train_test_split |\n|--------|---|---|---|---|---|\n| new / old (diff) | 0.025429 / 0.037411 (-0.011982) | 0.104699 / 0.014526 (0.090173) | 0.110505 / 0.176557 (-0.066051) | 0.171252 / 0.737135 (-0.565883) | 0.113131 / 0.296338 (-0.183208) |\n\n### Benchmark: benchmark_iterating.json\n\n| metric | read 5000 | read 50000 | read_batch 50000 10 | read_batch 50000 100 | read_batch 50000 1000 | read_formatted numpy 5000 | read_formatted pandas 5000 | read_formatted tensorflow 5000 | read_formatted torch 5000 | read_formatted_batch numpy 5000 10 | read_formatted_batch numpy 5000 1000 | shuffled read 5000 | shuffled read 50000 | shuffled read_batch 50000 10 | shuffled read_batch 50000 100 | shuffled read_batch 50000 1000 | shuffled read_formatted numpy 5000 | shuffled read_formatted_batch numpy 5000 10 | shuffled read_formatted_batch numpy 5000 1000 |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.419914 / 0.215209 (0.204705) | 4.184414 / 2.077655 (2.106760) | 1.999263 / 1.504120 (0.495143) | 1.828669 / 1.541195 (0.287474) | 1.940366 / 1.468490 (0.471876) | 0.556939 / 4.584777 (-4.027838) | 3.389164 / 3.745712 (-0.356548) | 1.796323 / 5.269862 (-3.473538) | 1.048843 / 4.565676 (-3.516833) | 0.067315 / 0.424275 (-0.356960) | 0.011531 / 0.007607 (0.003923) | 0.517226 / 0.226044 (0.291182) | 5.167255 / 2.268929 (2.898326) | 2.431129 / 55.444624 (-53.013495) | 2.133913 / 6.876477 (-4.742564) | 2.359021 / 2.142072 (0.216948) | 0.666390 / 4.805227 (-4.138838) | 0.135147 / 6.500664 (-6.365517) | 0.064855 / 0.075469 (-0.010614) |\n\n### Benchmark: benchmark_map_filter.json\n\n| metric | filter | map fast-tokenizer batched | map identity | map identity batched | map no-op batched | map no-op batched numpy | map no-op batched pandas | map no-op batched pytorch | map no-op batched tensorflow |\n|--------|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 1.166530 / 1.841788 (-0.675258) | 14.060551 / 8.074308 (5.986242) | 14.171663 / 10.191392 (3.980271) | 0.285821 / 0.680424 (-0.394603) | 0.016867 / 0.534201 (-0.517334) | 0.369102 / 0.579283 (-0.210181) | 0.393580 / 0.434364 (-0.040784) | 0.423721 / 0.540337 (-0.116616) | 0.512559 / 1.386936 (-0.874377) |\n\n</details>\nPyArrow==latest\n\n<details>\n<summary>Show updated benchmarks!</summary>\n\n### Benchmark: benchmark_array_xd.json\n\n| metric | read_batch_formatted_as_numpy after write_array2d | read_batch_formatted_as_numpy after write_flattened_sequence | read_batch_formatted_as_numpy after write_nested_sequence | read_batch_unformated after write_array2d | read_batch_unformated after write_flattened_sequence | read_batch_unformated after write_nested_sequence | read_col_formatted_as_numpy after write_array2d | read_col_formatted_as_numpy after write_flattened_sequence | read_col_formatted_as_numpy after write_nested_sequence | read_col_unformated after write_array2d | read_col_unformated after write_flattened_sequence | read_col_unformated after write_nested_sequence | read_formatted_as_numpy after write_array2d | read_formatted_as_numpy after write_flattened_sequence | read_formatted_as_numpy after write_nested_sequence | read_unformated after write_array2d | read_unformated after write_flattened_sequence | read_unformated after write_nested_sequence | write_array2d | write_flattened_sequence | write_nested_sequence |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.006674 / 0.011353 (-0.004679) | 0.004006 / 0.011008 (-0.007002) | 0.080160 / 0.038508 (0.041652) | 0.032508 / 0.023109 (0.009399) | 0.378168 / 0.275898 (0.102270) | 0.417796 / 0.323480 (0.094316) | 0.003706 / 0.007986 (-0.004280) | 0.002995 / 0.004328 (-0.001333) | 0.079275 / 0.004250 (0.075025) | 0.043690 / 0.037052 (0.006638) | 0.377717 / 0.258489 (0.119228) | 0.439801 / 0.293841 (0.145961) | 0.028438 / 0.128546 (-0.100108) | 0.008661 / 0.075646 (-0.066985) | 0.085280 / 0.419271 (-0.333991) | 0.043716 / 0.043533 (0.000183) | 0.370086 / 0.255139 (0.114947) | 0.403763 / 0.283200 (0.120563) | 0.095022 / 0.141683 (-0.046661) | 1.534376 / 1.452155 (0.082221) | 1.597658 / 1.492716 (0.104942) |\n\n### Benchmark: benchmark_getitem\\_100B.json\n\n| metric | get_batch_of\\_1024\\_random_rows | get_batch_of\\_1024\\_rows | get_first_row | get_last_row |\n|--------|---|---|---|---|\n| new / old (diff) | 0.240229 / 0.018006 (0.222223) | 0.496281 / 0.000490 (0.495792) | 0.002165 / 0.000200 (0.001965) | 0.000075 / 0.000054 (0.000020) |\n\n### Benchmark: benchmark_indices_mapping.json\n\n| metric | select | shard | shuffle | sort | train_test_split |\n|--------|---|---|---|---|---|\n| new / old (diff) | 0.025330 / 0.037411 (-0.012081) | 0.102414 / 0.014526 (0.087888) | 0.112733 / 0.176557 (-0.063824) | 0.161181 / 0.737135 (-0.575955) | 0.114196 / 0.296338 (-0.182143) |\n\n### Benchmark: benchmark_iterating.json\n\n| metric | read 5000 | read 50000 | read_batch 50000 10 | read_batch 50000 100 | read_batch 50000 1000 | read_formatted numpy 5000 | read_formatted pandas 5000 | read_formatted tensorflow 5000 | read_formatted torch 5000 | read_formatted_batch numpy 5000 10 | read_formatted_batch numpy 5000 1000 | shuffled read 5000 | shuffled read 50000 | shuffled read_batch 50000 10 | shuffled read_batch 50000 100 | shuffled read_batch 50000 1000 | shuffled read_formatted numpy 5000 | shuffled read_formatted_batch numpy 5000 10 | shuffled read_formatted_batch numpy 5000 1000 |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.456808 / 0.215209 (0.241599) | 4.534937 / 2.077655 (2.457283) | 2.318834 / 1.504120 (0.814714) | 2.074085 / 1.541195 (0.532890) | 2.117409 / 1.468490 (0.648919) | 0.559110 / 4.584777 (-4.025667) | 3.371695 / 3.745712 (-0.374017) | 2.543154 / 5.269862 (-2.726708) | 1.360552 / 4.565676 (-3.205125) | 0.067602 / 0.424275 (-0.356674) | 0.011396 / 0.007607 (0.003789) | 0.561666 / 0.226044 (0.335622) | 5.607666 / 2.268929 (3.338737) | 2.802775 / 55.444624 (-52.641849) | 2.486162 / 6.876477 (-4.390315) | 2.390885 / 2.142072 (0.248813) | 0.667407 / 4.805227 (-4.137820) | 0.135948 / 6.500664 (-6.364717) | 0.067272 / 0.075469 (-0.008197) |\n\n### Benchmark: benchmark_map_filter.json\n\n| metric | filter | map fast-tokenizer batched | map identity | map identity batched | map no-op batched | map no-op batched numpy | map no-op batched pandas | map no-op batched pytorch | map no-op batched tensorflow |\n|--------|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 1.279664 / 1.841788 (-0.562124) | 15.188099 / 8.074308 (7.113791) | 14.380355 / 10.191392 (4.188963) | 0.140344 / 0.680424 (-0.540080) | 0.016832 / 0.534201 (-0.517369) | 0.364631 / 0.579283 (-0.214652) | 0.400306 / 0.434364 (-0.034058) | 0.430793 / 0.540337 (-0.109545) | 0.525923 / 1.386936 (-0.861013) |\n\n</details>\n</details>\n\n![](https://cml.dev/watermark.png#48ca19cf1f4d1c99765a1f847c1f6b849496d99d "CML watermark")\n', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1591263440/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1591321614', 'html_url': 'https://github.com/huggingface/datasets/pull/5956#issuecomment-1591321614', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5956', 'id': 1591321614, 'node_id': 'IC_kwDODunzps5e2aQO', 'user': {'login': 'github-actions[bot]', 'id': 41898282, 'node_id': 'MDM6Qm90NDE4OTgyODI=', 'avatar_url': 'https://avatars.githubusercontent.com/in/15368?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/github-actions%5Bbot%5D', 'html_url': 'https://github.com/apps/github-actions', 'followers_url': 'https://api.github.com/users/github-actions%5Bbot%5D/followers', 'following_url': 'https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}', 'gists_url': 'https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/github-actions%5Bbot%5D/subscriptions', 'organizations_url': 'https://api.github.com/users/github-actions%5Bbot%5D/orgs', 'repos_url': 'https://api.github.com/users/github-actions%5Bbot%5D/repos', 'events_url': 'https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}', 'received_events_url': 'https://api.github.com/users/github-actions%5Bbot%5D/received_events', 'type': 'Bot', 'site_admin': False}, 'created_at': '2023-06-14T14:22:58Z', 'updated_at': '2023-06-14T14:22:58Z', 'author_association': 'NONE', 'body': '<details>\n<summary>Show benchmarks</summary>\n\nPyArrow==8.0.0\n\n<details>\n<summary>Show updated benchmarks!</summary>\n\n### Benchmark: benchmark_array_xd.json\n\n| metric | read_batch_formatted_as_numpy after write_array2d | read_batch_formatted_as_numpy after write_flattened_sequence | read_batch_formatted_as_numpy after write_nested_sequence | read_batch_unformated after write_array2d | read_batch_unformated after write_flattened_sequence | read_batch_unformated after write_nested_sequence | read_col_formatted_as_numpy after write_array2d | read_col_formatted_as_numpy after write_flattened_sequence | read_col_formatted_as_numpy after write_nested_sequence | read_col_unformated after write_array2d | read_col_unformated after write_flattened_sequence | read_col_unformated after write_nested_sequence | read_formatted_as_numpy after write_array2d | read_formatted_as_numpy after write_flattened_sequence | read_formatted_as_numpy after write_nested_sequence | read_unformated after write_array2d | read_unformated after write_flattened_sequence | read_unformated after write_nested_sequence | write_array2d | write_flattened_sequence | write_nested_sequence |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.008502 / 0.011353 (-0.002851) | 0.005946 / 0.011008 (-0.005062) | 0.131279 / 0.038508 (0.092771) | 0.035400 / 0.023109 (0.012291) | 0.423240 / 0.275898 (0.147342) | 0.470248 / 0.323480 (0.146768) | 0.004949 / 0.007986 (-0.003037) | 0.004544 / 0.004328 (0.000215) | 0.106856 / 0.004250 (0.102605) | 0.046579 / 0.037052 (0.009527) | 0.441135 / 0.258489 (0.182646) | 0.470401 / 0.293841 (0.176561) | 0.047231 / 0.128546 (-0.081315) | 0.017278 / 0.075646 (-0.058368) | 0.401937 / 0.419271 (-0.017335) | 0.067151 / 0.043533 (0.023619) | 0.453908 / 0.255139 (0.198769) | 0.422171 / 0.283200 (0.138971) | 0.123583 / 0.141683 (-0.018100) | 1.852895 / 1.452155 (0.400740) | 1.827282 / 1.492716 (0.334566) |\n\n### Benchmark: benchmark_getitem\\_100B.json\n\n| metric | get_batch_of\\_1024\\_random_rows | get_batch_of\\_1024\\_rows | get_first_row | get_last_row |\n|--------|---|---|---|---|\n| new / old (diff) | 0.246419 / 0.018006 (0.228413) | 0.576930 / 0.000490 (0.576440) | 0.007511 / 0.000200 (0.007312) | 0.000165 / 0.000054 (0.000111) |\n\n### Benchmark: benchmark_indices_mapping.json\n\n| metric | select | shard | shuffle | sort | train_test_split |\n|--------|---|---|---|---|---|\n| new / old (diff) | 0.032732 / 0.037411 (-0.004680) | 0.130266 / 0.014526 (0.115740) | 0.150537 / 0.176557 (-0.026019) | 0.218554 / 0.737135 (-0.518582) | 0.148572 / 0.296338 (-0.147766) |\n\n### Benchmark: benchmark_iterating.json\n\n| metric | read 5000 | read 50000 | read_batch 50000 10 | read_batch 50000 100 | read_batch 50000 1000 | read_formatted numpy 5000 | read_formatted pandas 5000 | read_formatted tensorflow 5000 | read_formatted torch 5000 | read_formatted_batch numpy 5000 10 | read_formatted_batch numpy 5000 1000 | shuffled read 5000 | shuffled read 50000 | shuffled read_batch 50000 10 | shuffled read_batch 50000 100 | shuffled read_batch 50000 1000 | shuffled read_formatted numpy 5000 | shuffled read_formatted_batch numpy 5000 10 | shuffled read_formatted_batch numpy 5000 1000 |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.598611 / 0.215209 (0.383402) | 6.181219 / 2.077655 (4.103564) | 2.473468 / 1.504120 (0.969348) | 2.206374 / 1.541195 (0.665179) | 2.216707 / 1.468490 (0.748217) | 0.981295 / 4.584777 (-3.603482) | 5.716384 / 3.745712 (1.970672) | 5.882327 / 5.269862 (0.612466) | 2.761081 / 4.565676 (-1.804595) | 0.113544 / 0.424275 (-0.310731) | 0.015131 / 0.007607 (0.007524) | 0.850939 / 0.226044 (0.624894) | 8.046611 / 2.268929 (5.777682) | 3.340542 / 55.444624 (-52.104083) | 2.673692 / 6.876477 (-4.202785) | 2.926330 / 2.142072 (0.784257) | 1.176164 / 4.805227 (-3.629064) | 0.226745 / 6.500664 (-6.273919) | 0.085910 / 0.075469 (0.010441) |\n\n### Benchmark: benchmark_map_filter.json\n\n| metric | filter | map fast-tokenizer batched | map identity | map identity batched | map no-op batched | map no-op batched numpy | map no-op batched pandas | map no-op batched pytorch | map no-op batched tensorflow |\n|--------|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 1.483792 / 1.841788 (-0.357995) | 18.895009 / 8.074308 (10.820701) | 20.982461 / 10.191392 (10.791069) | 0.253085 / 0.680424 (-0.427339) | 0.031284 / 0.534201 (-0.502917) | 0.516569 / 0.579283 (-0.062714) | 0.635781 / 0.434364 (0.201417) | 0.604359 / 0.540337 (0.064022) | 0.725278 / 1.386936 (-0.661658) |\n\n</details>\nPyArrow==latest\n\n<details>\n<summary>Show updated benchmarks!</summary>\n\n### Benchmark: benchmark_array_xd.json\n\n| metric | read_batch_formatted_as_numpy after write_array2d | read_batch_formatted_as_numpy after write_flattened_sequence | read_batch_formatted_as_numpy after write_nested_sequence | read_batch_unformated after write_array2d | read_batch_unformated after write_flattened_sequence | read_batch_unformated after write_nested_sequence | read_col_formatted_as_numpy after write_array2d | read_col_formatted_as_numpy after write_flattened_sequence | read_col_formatted_as_numpy after write_nested_s

[{'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1591627100', 'html_url': 'https://github.com/huggingface/datasets/issues/5955#issuecomment-1591627100', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5955', 'id': 1591627100, 'node_id': 'IC_kwDODunzps5e3k1c', 'user': {'login': 'mariosasko', 'id': 47462742, 'node_id': 'MDQ6VXNlcjQ3NDYyNzQy', 'avatar_url': 'https://avatars.githubusercontent.com/u/47462742?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/mariosasko', 'html_url': 'https://github.com/mariosasko', 'followers_url': 'https://api.github.com/users/mariosasko/followers', 'following_url': 'https://api.github.com/users/mariosasko/following{/other_user}', 'gists_url': 'https://api.github.com/users/mariosasko/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/mariosasko/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/mariosasko/subscriptions', 'organizations_url': 'https://api.github.com/users/mariosasko/orgs', 'repos_url': 'https://api.github.com/users/mariosasko/repos', 'events_url': 'https://api.github.com/users/mariosasko/events{/privacy}', 'received_events_url': 'https://api.github.com/users/mariosasko/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-14T16:39:55Z', 'updated_at': '2023-06-14T16:39:55Z', 'author_association': 'CONTRIBUTOR', 'body': "This is the actual error:\r\n```\r\nFailed to read file '/home/lakala/hjc/code/pycode/glm/temp.json' with error <class 'pyarrow.lib.ArrowInvalid'>: cannot mix list and non-list, non-null values\r\n```\r\nWhich means some samples are incorrectly formatted.\r\n\r\nPyArrow, a storage backend that we use under the hood, requires that all the list elements have the same level of nesting (same number of dimensions) or are `None`.\r\n```python\r\nimport pyarrow as pa\r\npa.array([[1, 2, 3], 2]) # ArrowInvalid: cannot mix list and non-list, non-null values\r\npa.array([[1, 2, 3], [2]]) # works\r\n``` ", 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1591627100/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1592175484', 'html_url': 'https://github.com/huggingface/datasets/issues/5955#issuecomment-1592175484', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5955', 'id': 1592175484, 'node_id': 'IC_kwDODunzps5e5qt8', 'user': {'login': 'Night-Quiet', 'id': 73934131, 'node_id': 'MDQ6VXNlcjczOTM0MTMx', 'avatar_url': 'https://avatars.githubusercontent.com/u/73934131?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/Night-Quiet', 'html_url': 'https://github.com/Night-Quiet', 'followers_url': 'https://api.github.com/users/Night-Quiet/followers', 'following_url': 'https://api.github.com/users/Night-Quiet/following{/other_user}', 'gists_url': 'https://api.github.com/users/Night-Quiet/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/Night-Quiet/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/Night-Quiet/subscriptions', 'organizations_url': 'https://api.github.com/users/Night-Quiet/orgs', 'repos_url': 'https://api.github.com/users/Night-Quiet/repos', 'events_url': 'https://api.github.com/users/Night-Quiet/events{/privacy}', 'received_events_url': 'https://api.github.com/users/Night-Quiet/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-15T00:57:11Z', 'updated_at': '2023-06-15T00:57:11Z', 'author_association': 'NONE', 'body': "@mariosasko \r\nI used the same operation to check the original data before and after slicing.\r\nThis is reflected in my code.\r\n160000 is not a specific number.\r\nI can also get output using 150000.\r\nThis doesn't seem to align very well with what you said.\r\nBecause if only some sample formats are incorrect.\r\nSo there should be an error in one of the front and back slices.\r\nthank you for your reply.", 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1592175484/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1593095764', 'html_url': 'https://github.com/huggingface/datasets/issues/5955#issuecomment-1593095764', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5955', 'id': 1593095764, 'node_id': 'IC_kwDODunzps5e9LZU', 'user': {'login': 'mariosasko', 'id': 47462742, 'node_id': 'MDQ6VXNlcjQ3NDYyNzQy', 'avatar_url': 'https://avatars.githubusercontent.com/u/47462742?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/mariosasko', 'html_url': 'https://github.com/mariosasko', 'followers_url': 'https://api.github.com/users/mariosasko/followers', 'following_url': 'https://api.github.com/users/mariosasko/following{/other_user}', 'gists_url': 'https://api.github.com/users/mariosasko/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/mariosasko/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/mariosasko/subscriptions', 'organizations_url': 'https://api.github.com/users/mariosasko/orgs', 'repos_url': 'https://api.github.com/users/mariosasko/repos', 'events_url': 'https://api.github.com/users/mariosasko/events{/privacy}', 'received_events_url': 'https://api.github.com/users/mariosasko/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-15T13:44:29Z', 'updated_at': '2023-06-15T13:44:29Z', 'author_association': 'CONTRIBUTOR', 'body': 'Our JSON loader does the following in your case:\r\n\r\n```python\r\nimport json\r\nimport pyarrow as pa\r\n\r\nwith open(file, encoding="utf-8") as f:\r\n    dataset = json.load(f)\r\nkeys = set().union(*[row.keys() for row in dataset])\r\nmapping = {col: [row.get(col) for row in dataset] for col in keys}\r\npa_table = pa.Table.from_pydict(mapping) # the ArrowInvalid error comes from here\r\n```\r\n\r\nSo if this code throws an error with correctly-formatted JSON, then this is an Arrow bug and should be reported in their repo.\r\n\r\n> I used the same operation to check the original data before and after slicing.\r\nThis is reflected in my code.\r\n160000 is not a specific number.\r\nI can also get output using 150000.\r\nThis doesn\'t seem to align very well with what you said.\r\nBecause if only some sample formats are incorrect.\r\nSo there should be an error in one of the front and back slices.\r\n\r\nYou should shuffle the data to make sure that\'s not the case', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1593095764/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1594377464', 'html_url': 'https://github.com/huggingface/datasets/issues/5955#issuecomment-1594377464', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5955', 'id': 1594377464, 'node_id': 'IC_kwDODunzps5fCET4', 'user': {'login': 'Night-Quiet', 'id': 73934131, 'node_id': 'MDQ6VXNlcjczOTM0MTMx', 'avatar_url': 'https://avatars.githubusercontent.com/u/73934131?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/Night-Quiet', 'html_url': 'https://github.com/Night-Quiet', 'followers_url': 'https://api.github.com/users/Night-Quiet/followers', 'following_url': 'https://api.github.com/users/Night-Quiet/following{/other_user}', 'gists_url': 'https://api.github.com/users/Night-Quiet/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/Night-Quiet/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/Night-Quiet/subscriptions', 'organizations_url': 'https://api.github.com/users/Night-Quiet/orgs', 'repos_url': 'https://api.github.com/users/Night-Quiet/repos', 'events_url': 'https://api.github.com/users/Night-Quiet/events{/privacy}', 'received_events_url': 'https://api.github.com/users/Night-Quiet/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-16T09:15:16Z', 'updated_at': '2023-06-16T09:15:16Z', 'author_association': 'NONE', 'body': '@mariosasko \r\nThank you.\r\nI will try again.', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1594377464/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}]

[{'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1590943012', 'html_url': 'https://github.com/huggingface/datasets/pull/5954#issuecomment-1590943012', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5954', 'id': 1590943012, 'node_id': 'IC_kwDODunzps5e090k', 'user': {'login': 'HuggingFaceDocBuilderDev', 'id': 99929124, 'node_id': 'U_kgDOBfTMJA', 'avatar_url': 'https://avatars.githubusercontent.com/u/99929124?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/HuggingFaceDocBuilderDev', 'html_url': 'https://github.com/HuggingFaceDocBuilderDev', 'followers_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/followers', 'following_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/following{/other_user}', 'gists_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/subscriptions', 'organizations_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/orgs', 'repos_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/repos', 'events_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/events{/privacy}', 'received_events_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-14T10:38:33Z', 'updated_at': '2023-06-14T12:27:01Z', 'author_association': 'NONE', 'body': '_The documentation is not available anymore as the PR was closed or merged._', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1590943012/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1590944890', 'html_url': 'https://github.com/huggingface/datasets/pull/5954#issuecomment-1590944890', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5954', 'id': 1590944890, 'node_id': 'IC_kwDODunzps5e0-R6', 'user': {'login': 'github-actions[bot]', 'id': 41898282, 'node_id': 'MDM6Qm90NDE4OTgyODI=', 'avatar_url': 'https://avatars.githubusercontent.com/in/15368?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/github-actions%5Bbot%5D', 'html_url': 'https://github.com/apps/github-actions', 'followers_url': 'https://api.github.com/users/github-actions%5Bbot%5D/followers', 'following_url': 'https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}', 'gists_url': 'https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/github-actions%5Bbot%5D/subscriptions', 'organizations_url': 'https://api.github.com/users/github-actions%5Bbot%5D/orgs', 'repos_url': 'https://api.github.com/users/github-actions%5Bbot%5D/repos', 'events_url': 'https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}', 'received_events_url': 'https://api.github.com/users/github-actions%5Bbot%5D/received_events', 'type': 'Bot', 'site_admin': False}, 'created_at': '2023-06-14T10:40:05Z', 'updated_at': '2023-06-14T10:40:05Z', 'author_association': 'NONE', 'body': '<details>\n<summary>Show benchmarks</summary>\n\nPyArrow==8.0.0\n\n<details>\n<summary>Show updated benchmarks!</summary>\n\n### Benchmark: benchmark_array_xd.json\n\n| metric | read_batch_formatted_as_numpy after write_array2d | read_batch_formatted_as_numpy after write_flattened_sequence | read_batch_formatted_as_numpy after write_nested_sequence | read_batch_unformated after write_array2d | read_batch_unformated after write_flattened_sequence | read_batch_unformated after write_nested_sequence | read_col_formatted_as_numpy after write_array2d | read_col_formatted_as_numpy after write_flattened_sequence | read_col_formatted_as_numpy after write_nested_sequence | read_col_unformated after write_array2d | read_col_unformated after write_flattened_sequence | read_col_unformated after write_nested_sequence | read_formatted_as_numpy after write_array2d | read_formatted_as_numpy after write_flattened_sequence | read_formatted_as_numpy after write_nested_sequence | read_unformated after write_array2d | read_unformated after write_flattened_sequence | read_unformated after write_nested_sequence | write_array2d | write_flattened_sequence | write_nested_sequence |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.006374 / 0.011353 (-0.004979) | 0.004100 / 0.011008 (-0.006909) | 0.104031 / 0.038508 (0.065523) | 0.035186 / 0.023109 (0.012076) | 0.328904 / 0.275898 (0.053006) | 0.361409 / 0.323480 (0.037929) | 0.003855 / 0.007986 (-0.004130) | 0.004140 / 0.004328 (-0.000189) | 0.080406 / 0.004250 (0.076156) | 0.045658 / 0.037052 (0.008606) | 0.341133 / 0.258489 (0.082644) | 0.372688 / 0.293841 (0.078847) | 0.032025 / 0.128546 (-0.096521) | 0.008877 / 0.075646 (-0.066769) | 0.354784 / 0.419271 (-0.064488) | 0.068874 / 0.043533 (0.025341) | 0.335441 / 0.255139 (0.080302) | 0.356498 / 0.283200 (0.073298) | 0.113367 / 0.141683 (-0.028316) | 1.522458 / 1.452155 (0.070304) | 1.608046 / 1.492716 (0.115329) |\n\n### Benchmark: benchmark_getitem\\_100B.json\n\n| metric | get_batch_of\\_1024\\_random_rows | get_batch_of\\_1024\\_rows | get_first_row | get_last_row |\n|--------|---|---|---|---|\n| new / old (diff) | 0.231653 / 0.018006 (0.213647) | 0.446678 / 0.000490 (0.446188) | 0.003246 / 0.000200 (0.003046) | 0.000085 / 0.000054 (0.000030) |\n\n### Benchmark: benchmark_indices_mapping.json\n\n| metric | select | shard | shuffle | sort | train_test_split |\n|--------|---|---|---|---|---|\n| new / old (diff) | 0.025299 / 0.037411 (-0.012112) | 0.111440 / 0.014526 (0.096914) | 0.118758 / 0.176557 (-0.057799) | 0.175037 / 0.737135 (-0.562098) | 0.124583 / 0.296338 (-0.171755) |\n\n### Benchmark: benchmark_iterating.json\n\n| metric | read 5000 | read 50000 | read_batch 50000 10 | read_batch 50000 100 | read_batch 50000 1000 | read_formatted numpy 5000 | read_formatted pandas 5000 | read_formatted tensorflow 5000 | read_formatted torch 5000 | read_formatted_batch numpy 5000 10 | read_formatted_batch numpy 5000 1000 | shuffled read 5000 | shuffled read 50000 | shuffled read_batch 50000 10 | shuffled read_batch 50000 100 | shuffled read_batch 50000 1000 | shuffled read_formatted numpy 5000 | shuffled read_formatted_batch numpy 5000 10 | shuffled read_formatted_batch numpy 5000 1000 |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.418694 / 0.215209 (0.203484) | 4.174695 / 2.077655 (2.097041) | 1.890323 / 1.504120 (0.386203) | 1.683300 / 1.541195 (0.142106) | 1.781954 / 1.468490 (0.313464) | 0.546131 / 4.584777 (-4.038645) | 3.768055 / 3.745712 (0.022343) | 1.839878 / 5.269862 (-3.429983) | 1.111877 / 4.565676 (-3.453800) | 0.068568 / 0.424275 (-0.355707) | 0.011950 / 0.007607 (0.004343) | 0.527469 / 0.226044 (0.301425) | 5.274887 / 2.268929 (3.005958) | 2.391274 / 55.444624 (-53.053351) | 2.063837 / 6.876477 (-4.812640) | 2.140627 / 2.142072 (-0.001445) | 0.681508 / 4.805227 (-4.123719) | 0.148203 / 6.500664 (-6.352461) | 0.064456 / 0.075469 (-0.011013) |\n\n### Benchmark: benchmark_map_filter.json\n\n| metric | filter | map fast-tokenizer batched | map identity | map identity batched | map no-op batched | map no-op batched numpy | map no-op batched pandas | map no-op batched pytorch | map no-op batched tensorflow |\n|--------|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 1.221478 / 1.841788 (-0.620310) | 14.713705 / 8.074308 (6.639397) | 14.674184 / 10.191392 (4.482792) | 0.148411 / 0.680424 (-0.532012) | 0.017858 / 0.534201 (-0.516343) | 0.436166 / 0.579283 (-0.143117) | 0.437290 / 0.434364 (0.002926) | 0.521994 / 0.540337 (-0.018343) | 0.635488 / 1.386936 (-0.751448) |\n\n</details>\nPyArrow==latest\n\n<details>\n<summary>Show updated benchmarks!</summary>\n\n### Benchmark: benchmark_array_xd.json\n\n| metric | read_batch_formatted_as_numpy after write_array2d | read_batch_formatted_as_numpy after write_flattened_sequence | read_batch_formatted_as_numpy after write_nested_sequence | read_batch_unformated after write_array2d | read_batch_unformated after write_flattened_sequence | read_batch_unformated after write_nested_sequence | read_col_formatted_as_numpy after write_array2d | read_col_formatted_as_numpy after write_flattened_sequence | read_col_formatted_as_numpy after write_nested_sequence | read_col_unformated after write_array2d | read_col_unformated after write_flattened_sequence | read_col_unformated after write_nested_sequence | read_formatted_as_numpy after write_array2d | read_formatted_as_numpy after write_flattened_sequence | read_formatted_as_numpy after write_nested_sequence | read_unformated after write_array2d | read_unformated after write_flattened_sequence | read_unformated after write_nested_sequence | write_array2d | write_flattened_sequence | write_nested_sequence |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.006108 / 0.011353 (-0.005245) | 0.003888 / 0.011008 (-0.007120) | 0.078424 / 0.038508 (0.039916) | 0.033618 / 0.023109 (0.010509) | 0.376284 / 0.275898 (0.100386) | 0.396957 / 0.323480 (0.073477) | 0.003799 / 0.007986 (-0.004187) | 0.003160 / 0.004328 (-0.001168) | 0.078358 / 0.004250 (0.074107) | 0.045597 / 0.037052 (0.008545) | 0.386396 / 0.258489 (0.127907) | 0.412985 / 0.293841 (0.119144) | 0.031610 / 0.128546 (-0.096936) | 0.008720 / 0.075646 (-0.066926) | 0.085944 / 0.419271 (-0.333328) | 0.050780 / 0.043533 (0.007247) | 0.378099 / 0.255139 (0.122960) | 0.381894 / 0.283200 (0.098694) | 0.098926 / 0.141683 (-0.042756) | 1.513842 / 1.452155 (0.061688) | 1.595040 / 1.492716 (0.102323) |\n\n### Benchmark: benchmark_getitem\\_100B.json\n\n| metric | get_batch_of\\_1024\\_random_rows | get_batch_of\\_1024\\_rows | get_first_row | get_last_row |\n|--------|---|---|---|---|\n| new / old (diff) | 0.208169 / 0.018006 (0.190163) | 0.431653 / 0.000490 (0.431163) | 0.000935 / 0.000200 (0.000735) | 0.000088 / 0.000054 (0.000034) |\n\n### Benchmark: benchmark_indices_mapping.json\n\n| metric | select | shard | shuffle | sort | train_test_split |\n|--------|---|---|---|---|---|\n| new / old (diff) | 0.029600 / 0.037411 (-0.007812) | 0.116936 / 0.014526 (0.102410) | 0.125603 / 0.176557 (-0.050953) | 0.177007 / 0.737135 (-0.560129) | 0.130602 / 0.296338 (-0.165736) |\n\n### Benchmark: benchmark_iterating.json\n\n| metric | read 5000 | read 50000 | read_batch 50000 10 | read_batch 50000 100 | read_batch 50000 1000 | read_formatted numpy 5000 | read_formatted pandas 5000 | read_formatted tensorflow 5000 | read_formatted torch 5000 | read_formatted_batch numpy 5000 10 | read_formatted_batch numpy 5000 1000 | shuffled read 5000 | shuffled read 50000 | shuffled read_batch 50000 10 | shuffled read_batch 50000 100 | shuffled read_batch 50000 1000 | shuffled read_formatted numpy 5000 | shuffled read_formatted_batch numpy 5000 10 | shuffled read_formatted_batch numpy 5000 1000 |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.457158 / 0.215209 (0.241949) | 4.563254 / 2.077655 (2.485599) | 2.303549 / 1.504120 (0.799429) | 2.107269 / 1.541195 (0.566074) | 2.130861 / 1.468490 (0.662371) | 0.548931 / 4.584777 (-4.035846) | 3.745578 / 3.745712 (-0.000134) | 1.820372 / 5.269862 (-3.449490) | 1.099316 / 4.565676 (-3.466361) | 0.068218 / 0.424275 (-0.356057) | 0.012336 / 0.007607 (0.004728) | 0.569721 / 0.226044 (0.343676) | 5.691312 / 2.268929 (3.422384) | 2.797483 / 55.444624 (-52.647141) | 2.422621 / 6.876477 (-4.453855) | 2.426187 / 2.142072 (0.284115) | 0.674777 / 4.805227 (-4.130451) | 0.144855 / 6.500664 (-6.355809) | 0.065805 / 0.075469 (-0.009664) |\n\n### Benchmark: benchmark_map_filter.json\n\n| metric | filter | map fast-tokenizer batched | map identity | map identity batched | map no-op batched | map no-op batched numpy | map no-op batched pandas | map no-op batched pytorch | map no-op batched tensorflow |\n|--------|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 1.305078 / 1.841788 (-0.536709) | 14.874315 / 8.074308 (6.800007) | 14.541301 / 10.191392 (4.349909) | 0.175818 / 0.680424 (-0.504606) | 0.018169 / 0.534201 (-0.516032) | 0.435836 / 0.579283 (-0.143447) | 0.458397 / 0.434364 (0.024033) | 0.506232 / 0.540337 (-0.034106) | 0.605306 / 1.386936 (-0.781630) |\n\n</details>\n</details>\n\n![](https://cml.dev/watermark.png#7e0c1ceab96821c7c6557482d25a9bd2078d716a "CML watermark")\n', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1590944890/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1591106129', 'html_url': 'https://github.com/huggingface/datasets/pull/5954#issuecomment-1591106129', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5954', 'id': 1591106129, 'node_id': 'IC_kwDODunzps5e1lpR', 'user': {'login': 'github-actions[bot]', 'id': 41898282, 'node_id': 'MDM6Qm90NDE4OTgyODI=', 'avatar_url': 'https://avatars.githubusercontent.com/in/15368?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/github-actions%5Bbot%5D', 'html_url': 'https://github.com/apps/github-actions', 'followers_url': 'https://api.github.com/users/github-actions%5Bbot%5D/followers', 'following_url': 'https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}', 'gists_url': 'https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/github-actions%5Bbot%5D/subscriptions', 'organizations_url': 'https://api.github.com/users/github-actions%5Bbot%5D/orgs', 'repos_url': 'https://api.github.com/users/github-actions%5Bbot%5D/repos', 'events_url': 'https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}', 'received_events_url': 'https://api.github.com/users/github-actions%5Bbot%5D/received_events', 'type': 'Bot', 'site_admin': False}, 'created_at': '2023-06-14T12:33:26Z', 'updated_at': '2023-06-14T12:33:26Z', 'author_association': 'NONE', 'body': '<details>\n<summary>Show benchmarks</summary>\n\nPyArrow==8.0.0\n\n<details>\n<summary>Show updated benchmarks!</summary>\n\n### Benchmark: benchmark_array_xd.json\n\n| metric | read_batch_formatted_as_numpy after write_array2d | read_batch_formatted_as_numpy after write_flattened_sequence | read_batch_formatted_as_numpy after write_nested_sequence | read_batch_unformated after write_array2d | read_batch_unformated after write_flattened_sequence | read_batch_unformated after write_nested_sequence | read_col_formatted_as_numpy after write_array2d | read_col_formatted_as_numpy after write_flattened_sequence | read_col_formatted_as_numpy after write_nested_sequence | read_col_unformated after write_array2d | read_col_unformated after write_flattened_sequence | read_col_unformated after write_nested_sequence | read_formatted_as_numpy after write_array2d | read_formatted_as_numpy after write_flattened_sequence | read_formatted_as_numpy after write_nested_sequence | read_unformated after write_array2d | read_unformated after write_flattened_sequence | read_unformated after write_nested_sequence | write_array2d | write_flattened_sequence | write_nested_sequence |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.006138 / 0.011353 (-0.005215) | 0.003792 / 0.011008 (-0.007216) | 0.099417 / 0.038508 (0.060908) | 0.028739 / 0.023109 (0.005630) | 0.302835 / 0.275898 (0.026937) | 0.336397 / 0.323480 (0.012918) | 0.003537 / 0.007986 (-0.004449) | 0.002973 / 0.004328 (-0.001355) | 0.077461 / 0.004250 (0.073211) | 0.039493 / 0.037052 (0.002440) | 0.302367 / 0.258489 (0.043878) | 0.344936 / 0.293841 (0.051095) | 0.027813 / 0.128546 (-0.100733) | 0.008591 / 0.075646 (-0.067055) | 0.318975 / 0.419271 (-0.100297) | 0.045971 / 0.043533 (0.002438) | 0.301672 / 0.255139 (0.046533) | 0.328202 / 0.283200 (0.045003) | 0.091400 / 0.141683 (-0.050282) | 1.487215 / 1.452155 (0.035060) | 1.557730 / 1.492716 (0.065014) |\n\n### Benchmark: benchmark_getitem\\_100B.json\n\n| metric | get_batch_of\\_1024\\_random_rows | get_batch_of\\_1024\\_rows | get_first_row | get_last_row |\n|--------|---|---|---|---|\n| new / old (diff) | 0.208343 / 0.018006 (0.190336) | 0.426764 / 0.000490 (0.426275) | 0.001196 / 0.000200 (0.000996) | 0.000069 / 0.000054 (0.000015) |\n\n### Benchmark: benchmark_indices_mapping.json\n\n| metric | select | shard | shuffle | sort | train_test_split |\n|--------|---|---|---|---|---|\n| new / old (diff) | 0.024332 / 0.037411 (-0.013079) | 0.101861 / 0.014526 (0.087335) | 0.108669 / 0.176557 (-0.067888) | 0.172042 / 0.737135 (-0.565093) | 0.113048 / 0.296338 (-0.183290) |\n\n### Benchmark: benchmark_iterating.json\n\n| metric | read 5000 | read 50000 | read_batch 50000 10 | read_batch 50000 100 | read_batch 50000 1000 | read_formatted numpy 5000 | read_formatted pandas 5000 | read_formatted tensorflow 5000 | read_formatted torch 5000 | read_formatted_batch numpy 5000 10 | read_formatted_batch numpy 5000 1000 | shuffled read 5000 | shuffled read 50000 | shuffled read_batch 50000 10 | shuffled read_batch 50000 100 | shuffled read_batch 50000 1000 | shuffled read_formatted numpy 5000 | shuffled read_formatted_batch numpy 5000 10 | shuffled read_formatted_batch numpy 5000 1000 |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.421419 / 0.215209 (0.206210) | 4.200816 / 2.077655 (2.123162) | 1.913516 / 1.504120 (0.409396) | 1.712167 / 1.541195 (0.170972) | 1.762129 / 1.468490 (0.293639) | 0.561616 / 4.584777 (-4.023161) | 3.398122 / 3.745712 (-0.347590) | 1.744323 / 5.269862 (-3.525538) | 1.036023 / 4.565676 (-3.529653) | 0.067658 / 0.424275 (-0.356617) | 0.011145 / 0.007607 (0.003538) | 0.522803 / 0.226044 (0.296759) | 5.226245 / 2.268929 (2.957317) | 2.355148 / 55.444624 (-53.089476) | 2.014939 / 6.876477 (-4.861538) | 2.140028 / 2.142072 (-0.002044) | 0.695049 / 4.805227 (-4.110178) | 0.138428 / 6.500664 (-6.362236) | 0.066721 / 0.075469 (-0.008748) |\n\n### Benchmark: benchmark_map_filter.json\n\n| metric | filter | map fast-tokenizer batched | map identity | map identity batched | map no-op batched | map no-op batched numpy | map no-op batched pandas | map no-op batched pytorch | map no-op batched tensorflow |\n|--------|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 1.219610 / 1.841788 (-0.622177) | 14.239576 / 8.074308 (6.165268) | 14.381955 / 10.191392 (4.190563) | 0.131208 / 0.680424 (-0.549216) | 0.016698 / 0.534201 (-0.517503) | 0.361373 / 0.579283 (-0.217910) | 0.382560 / 0.434364 (-0.051804) | 0.419427 / 0.540337 (-0.120911) | 0.508314 / 1.386936 (-0.878622) |\n\n</details>\nPyArrow==latest\n\n<details>\n<summary>Show updated benchmarks!</summary>\n\n### Benchmark: benchmark_array_xd.json\n\n| metric | read_batch_formatted_as_numpy after write_array2d | read_batch_formatted_as_numpy after write_flattened_sequence | read_batch_formatted_as_numpy after write_nested_sequence | read_batch_unformated after write_array2d | read_batch_unformated after write_flattened_sequence | read_batch_unformated after write_nested_sequence | read_col_formatted_as_numpy after write_array2d | read_col_formatted_as_numpy after write_flattened_sequence | read_col_formatted_as_numpy after write_neste

[{'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1590891684', 'html_url': 'https://github.com/huggingface/datasets/issues/5953#issuecomment-1590891684', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5953', 'id': 1590891684, 'node_id': 'IC_kwDODunzps5e0xSk', 'user': {'login': 'patrickvonplaten', 'id': 23423619, 'node_id': 'MDQ6VXNlcjIzNDIzNjE5', 'avatar_url': 'https://avatars.githubusercontent.com/u/23423619?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/patrickvonplaten', 'html_url': 'https://github.com/patrickvonplaten', 'followers_url': 'https://api.github.com/users/patrickvonplaten/followers', 'following_url': 'https://api.github.com/users/patrickvonplaten/following{/other_user}', 'gists_url': 'https://api.github.com/users/patrickvonplaten/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/patrickvonplaten/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/patrickvonplaten/subscriptions', 'organizations_url': 'https://api.github.com/users/patrickvonplaten/orgs', 'repos_url': 'https://api.github.com/users/patrickvonplaten/repos', 'events_url': 'https://api.github.com/users/patrickvonplaten/events{/privacy}', 'received_events_url': 'https://api.github.com/users/patrickvonplaten/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-14T10:04:36Z', 'updated_at': '2023-06-14T10:04:36Z', 'author_association': 'MEMBER', 'body': 'cc @sanchit-gandhi @Vaibhavs10 @lhoestq - this is mainly for demos that use Common Voice datasets as done here: https://github.com/facebookresearch/fairseq/tree/main/examples/mms#-transformers\r\n', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1590891684/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1590900665', 'html_url': 'https://github.com/huggingface/datasets/issues/5953#issuecomment-1590900665', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5953', 'id': 1590900665, 'node_id': 'IC_kwDODunzps5e0ze5', 'user': {'login': 'lhoestq', 'id': 42851186, 'node_id': 'MDQ6VXNlcjQyODUxMTg2', 'avatar_url': 'https://avatars.githubusercontent.com/u/42851186?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/lhoestq', 'html_url': 'https://github.com/lhoestq', 'followers_url': 'https://api.github.com/users/lhoestq/followers', 'following_url': 'https://api.github.com/users/lhoestq/following{/other_user}', 'gists_url': 'https://api.github.com/users/lhoestq/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/lhoestq/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/lhoestq/subscriptions', 'organizations_url': 'https://api.github.com/users/lhoestq/orgs', 'repos_url': 'https://api.github.com/users/lhoestq/repos', 'events_url': 'https://api.github.com/users/lhoestq/events{/privacy}', 'received_events_url': 'https://api.github.com/users/lhoestq/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-14T10:10:06Z', 'updated_at': '2023-06-14T10:10:06Z', 'author_association': 'MEMBER', 'body': 'Hi ! the error for me is\r\n\r\n```\r\nFileNotFoundError: Couldn\'t find a dataset script at /content/mozilla-foundation/common_voice_13_0/common_voice_13_0.py or any data file in the same directory. Couldn\'t find \'mozilla-foundation/common_voice_13_0\' on the Hugging Face Hub either: FileNotFoundError: Dataset \'mozilla-foundation/common_voice_13_0\' doesn\'t exist on the Hub. If the repo is private or gated, make sure to log in with `huggingface-cli login`.\r\n```\r\n\r\nAnd tbh idk how you managed to get your error. "n_shards.json" is not even a thing in `datasets`', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1590900665/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1590912854', 'html_url': 'https://github.com/huggingface/datasets/issues/5953#issuecomment-1590912854', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5953', 'id': 1590912854, 'node_id': 'IC_kwDODunzps5e02dW', 'user': {'login': 'Vaibhavs10', 'id': 18682411, 'node_id': 'MDQ6VXNlcjE4NjgyNDEx', 'avatar_url': 'https://avatars.githubusercontent.com/u/18682411?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/Vaibhavs10', 'html_url': 'https://github.com/Vaibhavs10', 'followers_url': 'https://api.github.com/users/Vaibhavs10/followers', 'following_url': 'https://api.github.com/users/Vaibhavs10/following{/other_user}', 'gists_url': 'https://api.github.com/users/Vaibhavs10/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/Vaibhavs10/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/Vaibhavs10/subscriptions', 'organizations_url': 'https://api.github.com/users/Vaibhavs10/orgs', 'repos_url': 'https://api.github.com/users/Vaibhavs10/repos', 'events_url': 'https://api.github.com/users/Vaibhavs10/events{/privacy}', 'received_events_url': 'https://api.github.com/users/Vaibhavs10/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-14T10:17:06Z', 'updated_at': '2023-06-14T10:17:06Z', 'author_association': 'MEMBER', 'body': "Okay, I am able to reproduce @patrickvonplaten's original error: https://github.com/Vaibhavs10/scratchpad/blob/main/cv13_datasets_test.ipynb\r\n\r\nAlso not sure why it looks for `n_shards.json`", 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1590912854/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1590917492', 'html_url': 'https://github.com/huggingface/datasets/issues/5953#issuecomment-1590917492', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5953', 'id': 1590917492, 'node_id': 'IC_kwDODunzps5e03l0', 'user': {'login': 'lhoestq', 'id': 42851186, 'node_id': 'MDQ6VXNlcjQyODUxMTg2', 'avatar_url': 'https://avatars.githubusercontent.com/u/42851186?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/lhoestq', 'html_url': 'https://github.com/lhoestq', 'followers_url': 'https://api.github.com/users/lhoestq/followers', 'following_url': 'https://api.github.com/users/lhoestq/following{/other_user}', 'gists_url': 'https://api.github.com/users/lhoestq/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/lhoestq/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/lhoestq/subscriptions', 'organizations_url': 'https://api.github.com/users/lhoestq/orgs', 'repos_url': 'https://api.github.com/users/lhoestq/repos', 'events_url': 'https://api.github.com/users/lhoestq/events{/privacy}', 'received_events_url': 'https://api.github.com/users/lhoestq/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-14T10:19:12Z', 'updated_at': '2023-06-14T10:19:12Z', 'author_association': 'MEMBER', 'body': 'Ok I see, this file is downloaded from the CV dataset script - let me investigate', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1590917492/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1590919623', 'html_url': 'https://github.com/huggingface/datasets/issues/5953#issuecomment-1590919623', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5953', 'id': 1590919623, 'node_id': 'IC_kwDODunzps5e04HH', 'user': {'login': 'lhoestq', 'id': 42851186, 'node_id': 'MDQ6VXNlcjQyODUxMTg2', 'avatar_url': 'https://avatars.githubusercontent.com/u/42851186?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/lhoestq', 'html_url': 'https://github.com/lhoestq', 'followers_url': 'https://api.github.com/users/lhoestq/followers', 'following_url': 'https://api.github.com/users/lhoestq/following{/other_user}', 'gists_url': 'https://api.github.com/users/lhoestq/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/lhoestq/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/lhoestq/subscriptions', 'organizations_url': 'https://api.github.com/users/lhoestq/orgs', 'repos_url': 'https://api.github.com/users/lhoestq/repos', 'events_url': 'https://api.github.com/users/lhoestq/events{/privacy}', 'received_events_url': 'https://api.github.com/users/lhoestq/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-14T10:20:44Z', 'updated_at': '2023-06-14T10:20:44Z', 'author_association': 'MEMBER', 'body': "Ok I see: when you log out you no longer have access to the repository.\r\n\r\nTherefore the dataset script is loaded from cache:\r\n```\r\nWARNING:datasets.load:Using the latest cached version of the module from /root/.cache/huggingface/modules/datasets_modules/datasets/mozilla-foundation--common_voice_13_0/22809012aac1fc9803eaffc44122e4149043748e93933935d5ea19898587e4d7 (last modified on Wed Jun 14 10:13:17 2023) since it couldn't be found locally at mozilla-foundation/common_voice_13_0., or remotely on the Hugging Face Hub.\r\n```\r\n\r\nand the script tries to download the n_shards.json but fails", 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1590919623/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1591069057', 'html_url': 'https://github.com/huggingface/datasets/issues/5953#issuecomment-1591069057', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5953', 'id': 1591069057, 'node_id': 'IC_kwDODunzps5e1cmB', 'user': {'login': 'lhoestq', 'id': 42851186, 'node_id': 'MDQ6VXNlcjQyODUxMTg2', 'avatar_url': 'https://avatars.githubusercontent.com/u/42851186?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/lhoestq', 'html_url': 'https://github.com/lhoestq', 'followers_url': 'https://api.github.com/users/lhoestq/followers', 'following_url': 'https://api.github.com/users/lhoestq/following{/other_user}', 'gists_url': 'https://api.github.com/users/lhoestq/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/lhoestq/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/lhoestq/subscriptions', 'organizations_url': 'https://api.github.com/users/lhoestq/orgs', 'repos_url': 'https://api.github.com/users/lhoestq/repos', 'events_url': 'https://api.github.com/users/lhoestq/events{/privacy}', 'received_events_url': 'https://api.github.com/users/lhoestq/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-14T12:08:52Z', 'updated_at': '2023-06-14T12:08:52Z', 'author_association': 'MEMBER', 'body': "Is this ok for you https://github.com/huggingface/datasets/pull/5954 ?\r\n\r\nI'll do a release this afternoon", 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1591069057/reactions', 'total_count': 1, '+1': 1, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1591597719', 'html_url': 'https://github.com/huggingface/datasets/issues/5953#issuecomment-1591597719', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5953', 'id': 1591597719, 'node_id': 'IC_kwDODunzps5e3dqX', 'user': {'login': 'patrickvonplaten', 'id': 23423619, 'node_id': 'MDQ6VXNlcjIzNDIzNjE5', 'avatar_url': 'https://avatars.githubusercontent.com/u/23423619?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/patrickvonplaten', 'html_url': 'https://github.com/patrickvonplaten', 'followers_url': 'https://api.github.com/users/patrickvonplaten/followers', 'following_url': 'https://api.github.com/users/patrickvonplaten/following{/other_user}', 'gists_url': 'https://api.github.com/users/patrickvonplaten/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/patrickvonplaten/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/patrickvonplaten/subscriptions', 'organizations_url': 'https://api.github.com/users/patrickvonplaten/orgs', 'repos_url': 'https://api.github.com/users/patrickvonplaten/repos', 'events_url': 'https://api.github.com/users/patrickvonplaten/events{/privacy}', 'received_events_url': 'https://api.github.com/users/patrickvonplaten/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-14T16:22:55Z', 'updated_at': '2023-06-14T16:22:55Z', 'author_association': 'MEMBER', 'body': 'Cool! ', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1591597719/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1591621991', 'html_url': 'https://github.com/huggingface/datasets/issues/5953#issuecomment-1591621991', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5953', 'id': 1591621991, 'node_id': 'IC_kwDODunzps5e3jln', 'user': {'login': 'lhoestq', 'id': 42851186, 'node_id': 'MDQ6VXNlcjQyODUxMTg2', 'avatar_url': 'https://avatars.githubusercontent.com/u/42851186?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/lhoestq', 'html_url': 'https://github.com/lhoestq', 'followers_url': 'https://api.github.com/users/lhoestq/followers', 'following_url': 'https://api.github.com/users/lhoestq/following{/other_user}', 'gists_url': 'https://api.github.com/users/lhoestq/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/lhoestq/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/lhoestq/subscriptions', 'organizations_url': 'https://api.github.com/users/lhoestq/orgs', 'repos_url': 'https://api.github.com/users/lhoestq/repos', 'events_url': 'https://api.github.com/users/lhoestq/events{/privacy}', 'received_events_url': 'https://api.github.com/users/lhoestq/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-14T16:36:51Z', 'updated_at': '2023-06-14T16:36:51Z', 'author_association': 'MEMBER', 'body': 'this is included in the new release 2.13.0', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1591621991/reactions', 'total_count': 1, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 1, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}]

[{'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1590863966', 'html_url': 'https://github.com/huggingface/datasets/pull/5952#issuecomment-1590863966', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5952', 'id': 1590863966, 'node_id': 'IC_kwDODunzps5e0qhe', 'user': {'login': 'HuggingFaceDocBuilderDev', 'id': 99929124, 'node_id': 'U_kgDOBfTMJA', 'avatar_url': 'https://avatars.githubusercontent.com/u/99929124?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/HuggingFaceDocBuilderDev', 'html_url': 'https://github.com/HuggingFaceDocBuilderDev', 'followers_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/followers', 'following_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/following{/other_user}', 'gists_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/subscriptions', 'organizations_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/orgs', 'repos_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/repos', 'events_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/events{/privacy}', 'received_events_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-14T09:47:57Z', 'updated_at': '2023-06-14T14:35:09Z', 'author_association': 'NONE', 'body': '_The documentation is not available anymore as the PR was closed or merged._', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1590863966/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1590866332', 'html_url': 'https://github.com/huggingface/datasets/pull/5952#issuecomment-1590866332', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5952', 'id': 1590866332, 'node_id': 'IC_kwDODunzps5e0rGc', 'user': {'login': 'github-actions[bot]', 'id': 41898282, 'node_id': 'MDM6Qm90NDE4OTgyODI=', 'avatar_url': 'https://avatars.githubusercontent.com/in/15368?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/github-actions%5Bbot%5D', 'html_url': 'https://github.com/apps/github-actions', 'followers_url': 'https://api.github.com/users/github-actions%5Bbot%5D/followers', 'following_url': 'https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}', 'gists_url': 'https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/github-actions%5Bbot%5D/subscriptions', 'organizations_url': 'https://api.github.com/users/github-actions%5Bbot%5D/orgs', 'repos_url': 'https://api.github.com/users/github-actions%5Bbot%5D/repos', 'events_url': 'https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}', 'received_events_url': 'https://api.github.com/users/github-actions%5Bbot%5D/received_events', 'type': 'Bot', 'site_admin': False}, 'created_at': '2023-06-14T09:49:35Z', 'updated_at': '2023-06-14T09:49:35Z', 'author_association': 'NONE', 'body': '<details>\n<summary>Show benchmarks</summary>\n\nPyArrow==8.0.0\n\n<details>\n<summary>Show updated benchmarks!</summary>\n\n### Benchmark: benchmark_array_xd.json\n\n| metric | read_batch_formatted_as_numpy after write_array2d | read_batch_formatted_as_numpy after write_flattened_sequence | read_batch_formatted_as_numpy after write_nested_sequence | read_batch_unformated after write_array2d | read_batch_unformated after write_flattened_sequence | read_batch_unformated after write_nested_sequence | read_col_formatted_as_numpy after write_array2d | read_col_formatted_as_numpy after write_flattened_sequence | read_col_formatted_as_numpy after write_nested_sequence | read_col_unformated after write_array2d | read_col_unformated after write_flattened_sequence | read_col_unformated after write_nested_sequence | read_formatted_as_numpy after write_array2d | read_formatted_as_numpy after write_flattened_sequence | read_formatted_as_numpy after write_nested_sequence | read_unformated after write_array2d | read_unformated after write_flattened_sequence | read_unformated after write_nested_sequence | write_array2d | write_flattened_sequence | write_nested_sequence |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.006522 / 0.011353 (-0.004831) | 0.004319 / 0.011008 (-0.006690) | 0.099280 / 0.038508 (0.060772) | 0.033117 / 0.023109 (0.010007) | 0.339392 / 0.275898 (0.063494) | 0.366219 / 0.323480 (0.042739) | 0.003896 / 0.007986 (-0.004090) | 0.003412 / 0.004328 (-0.000916) | 0.076655 / 0.004250 (0.072404) | 0.045203 / 0.037052 (0.008150) | 0.355800 / 0.258489 (0.097311) | 0.372533 / 0.293841 (0.078692) | 0.032318 / 0.128546 (-0.096229) | 0.009030 / 0.075646 (-0.066616) | 0.328701 / 0.419271 (-0.090571) | 0.052891 / 0.043533 (0.009358) | 0.341131 / 0.255139 (0.085992) | 0.351593 / 0.283200 (0.068393) | 0.105136 / 0.141683 (-0.036546) | 1.475953 / 1.452155 (0.023798) | 1.566074 / 1.492716 (0.073357) |\n\n### Benchmark: benchmark_getitem\\_100B.json\n\n| metric | get_batch_of\\_1024\\_random_rows | get_batch_of\\_1024\\_rows | get_first_row | get_last_row |\n|--------|---|---|---|---|\n| new / old (diff) | 0.216671 / 0.018006 (0.198664) | 0.446952 / 0.000490 (0.446462) | 0.006340 / 0.000200 (0.006140) | 0.000096 / 0.000054 (0.000042) |\n\n### Benchmark: benchmark_indices_mapping.json\n\n| metric | select | shard | shuffle | sort | train_test_split |\n|--------|---|---|---|---|---|\n| new / old (diff) | 0.028293 / 0.037411 (-0.009118) | 0.112298 / 0.014526 (0.097773) | 0.118634 / 0.176557 (-0.057923) | 0.175542 / 0.737135 (-0.561593) | 0.124773 / 0.296338 (-0.171565) |\n\n### Benchmark: benchmark_iterating.json\n\n| metric | read 5000 | read 50000 | read_batch 50000 10 | read_batch 50000 100 | read_batch 50000 1000 | read_formatted numpy 5000 | read_formatted pandas 5000 | read_formatted tensorflow 5000 | read_formatted torch 5000 | read_formatted_batch numpy 5000 10 | read_formatted_batch numpy 5000 1000 | shuffled read 5000 | shuffled read 50000 | shuffled read_batch 50000 10 | shuffled read_batch 50000 100 | shuffled read_batch 50000 1000 | shuffled read_formatted numpy 5000 | shuffled read_formatted_batch numpy 5000 10 | shuffled read_formatted_batch numpy 5000 1000 |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.435209 / 0.215209 (0.220000) | 4.344361 / 2.077655 (2.266706) | 2.128943 / 1.504120 (0.624823) | 1.945465 / 1.541195 (0.404271) | 2.049932 / 1.468490 (0.581442) | 0.547126 / 4.584777 (-4.037651) | 3.768698 / 3.745712 (0.022986) | 1.924441 / 5.269862 (-3.345420) | 1.146364 / 4.565676 (-3.419312) | 0.067466 / 0.424275 (-0.356809) | 0.011175 / 0.007607 (0.003568) | 0.540978 / 0.226044 (0.314933) | 5.393120 / 2.268929 (3.124191) | 2.639027 / 55.444624 (-52.805597) | 2.327216 / 6.876477 (-4.549261) | 2.500532 / 2.142072 (0.358460) | 0.679120 / 4.805227 (-4.126107) | 0.148824 / 6.500664 (-6.351840) | 0.064195 / 0.075469 (-0.011274) |\n\n### Benchmark: benchmark_map_filter.json\n\n| metric | filter | map fast-tokenizer batched | map identity | map identity batched | map no-op batched | map no-op batched numpy | map no-op batched pandas | map no-op batched pytorch | map no-op batched tensorflow |\n|--------|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 1.158387 / 1.841788 (-0.683401) | 14.880751 / 8.074308 (6.806443) | 14.725249 / 10.191392 (4.533857) | 0.149785 / 0.680424 (-0.530639) | 0.017338 / 0.534201 (-0.516863) | 0.390980 / 0.579283 (-0.188303) | 0.425611 / 0.434364 (-0.008753) | 0.458851 / 0.540337 (-0.081487) | 0.559209 / 1.386936 (-0.827727) |\n\n</details>\nPyArrow==latest\n\n<details>\n<summary>Show updated benchmarks!</summary>\n\n### Benchmark: benchmark_array_xd.json\n\n| metric | read_batch_formatted_as_numpy after write_array2d | read_batch_formatted_as_numpy after write_flattened_sequence | read_batch_formatted_as_numpy after write_nested_sequence | read_batch_unformated after write_array2d | read_batch_unformated after write_flattened_sequence | read_batch_unformated after write_nested_sequence | read_col_formatted_as_numpy after write_array2d | read_col_formatted_as_numpy after write_flattened_sequence | read_col_formatted_as_numpy after write_nested_sequence | read_col_unformated after write_array2d | read_col_unformated after write_flattened_sequence | read_col_unformated after write_nested_sequence | read_formatted_as_numpy after write_array2d | read_formatted_as_numpy after write_flattened_sequence | read_formatted_as_numpy after write_nested_sequence | read_unformated after write_array2d | read_unformated after write_flattened_sequence | read_unformated after write_nested_sequence | write_array2d | write_flattened_sequence | write_nested_sequence |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.006835 / 0.011353 (-0.004518) | 0.004318 / 0.011008 (-0.006690) | 0.076715 / 0.038508 (0.038207) | 0.033528 / 0.023109 (0.010419) | 0.411986 / 0.275898 (0.136087) | 0.438752 / 0.323480 (0.115272) | 0.004039 / 0.007986 (-0.003947) | 0.003509 / 0.004328 (-0.000819) | 0.077924 / 0.004250 (0.073673) | 0.049519 / 0.037052 (0.012467) | 0.420595 / 0.258489 (0.162106) | 0.450536 / 0.293841 (0.156695) | 0.032817 / 0.128546 (-0.095729) | 0.008963 / 0.075646 (-0.066684) | 0.083818 / 0.419271 (-0.335454) | 0.057591 / 0.043533 (0.014058) | 0.404605 / 0.255139 (0.149466) | 0.423661 / 0.283200 (0.140462) | 0.110698 / 0.141683 (-0.030984) | 1.512515 / 1.452155 (0.060361) | 1.569207 / 1.492716 (0.076490) |\n\n### Benchmark: benchmark_getitem\\_100B.json\n\n| metric | get_batch_of\\_1024\\_random_rows | get_batch_of\\_1024\\_rows | get_first_row | get_last_row |\n|--------|---|---|---|---|\n| new / old (diff) | 0.200795 / 0.018006 (0.182789) | 0.448853 / 0.000490 (0.448363) | 0.003657 / 0.000200 (0.003457) | 0.000102 / 0.000054 (0.000048) |\n\n### Benchmark: benchmark_indices_mapping.json\n\n| metric | select | shard | shuffle | sort | train_test_split |\n|--------|---|---|---|---|---|\n| new / old (diff) | 0.031612 / 0.037411 (-0.005799) | 0.116712 / 0.014526 (0.102186) | 0.126162 / 0.176557 (-0.050395) | 0.180522 / 0.737135 (-0.556614) | 0.129768 / 0.296338 (-0.166570) |\n\n### Benchmark: benchmark_iterating.json\n\n| metric | read 5000 | read 50000 | read_batch 50000 10 | read_batch 50000 100 | read_batch 50000 1000 | read_formatted numpy 5000 | read_formatted pandas 5000 | read_formatted tensorflow 5000 | read_formatted torch 5000 | read_formatted_batch numpy 5000 10 | read_formatted_batch numpy 5000 1000 | shuffled read 5000 | shuffled read 50000 | shuffled read_batch 50000 10 | shuffled read_batch 50000 100 | shuffled read_batch 50000 1000 | shuffled read_formatted numpy 5000 | shuffled read_formatted_batch numpy 5000 10 | shuffled read_formatted_batch numpy 5000 1000 |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.433797 / 0.215209 (0.218588) | 4.353099 / 2.077655 (2.275444) | 2.117582 / 1.504120 (0.613462) | 1.934487 / 1.541195 (0.393292) | 2.016988 / 1.468490 (0.548498) | 0.531387 / 4.584777 (-4.053390) | 3.843520 / 3.745712 (0.097807) | 1.879560 / 5.269862 (-3.390301) | 1.129445 / 4.565676 (-3.436231) | 0.065952 / 0.424275 (-0.358323) | 0.011566 / 0.007607 (0.003959) | 0.533949 / 0.226044 (0.307904) | 5.327447 / 2.268929 (3.058518) | 2.572202 / 55.444624 (-52.872422) | 2.240723 / 6.876477 (-4.635753) | 2.329290 / 2.142072 (0.187217) | 0.662162 / 4.805227 (-4.143066) | 0.143191 / 6.500664 (-6.357473) | 0.065273 / 0.075469 (-0.010196) |\n\n### Benchmark: benchmark_map_filter.json\n\n| metric | filter | map fast-tokenizer batched | map identity | map identity batched | map no-op batched | map no-op batched numpy | map no-op batched pandas | map no-op batched pytorch | map no-op batched tensorflow |\n|--------|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 1.274945 / 1.841788 (-0.566843) | 15.444511 / 8.074308 (7.370203) | 14.793524 / 10.191392 (4.602132) | 0.175607 / 0.680424 (-0.504817) | 0.017324 / 0.534201 (-0.516877) | 0.396172 / 0.579283 (-0.183111) | 0.437334 / 0.434364 (0.002970) | 0.472621 / 0.540337 (-0.067716) | 0.574888 / 1.386936 (-0.812048) |\n\n</details>\n</details>\n\n![](https://cml.dev/watermark.png#b4ab1b3ed7257b0e0ad075d7271a51835f320a5e "CML watermark")\n', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1590866332/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1591366071', 'html_url': 'https://github.com/huggingface/datasets/pull/5952#issuecomment-1591366071', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5952', 'id': 1591366071, 'node_id': 'IC_kwDODunzps5e2lG3', 'user': {'login': 'github-actions[bot]', 'id': 41898282, 'node_id': 'MDM6Qm90NDE4OTgyODI=', 'avatar_url': 'https://avatars.githubusercontent.com/in/15368?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/github-actions%5Bbot%5D', 'html_url': 'https://github.com/apps/github-actions', 'followers_url': 'https://api.github.com/users/github-actions%5Bbot%5D/followers', 'following_url': 'https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}', 'gists_url': 'https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/github-actions%5Bbot%5D/subscriptions', 'organizations_url': 'https://api.github.com/users/github-actions%5Bbot%5D/orgs', 'repos_url': 'https://api.github.com/users/github-actions%5Bbot%5D/repos', 'events_url': 'https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}', 'received_events_url': 'https://api.github.com/users/github-actions%5Bbot%5D/received_events', 'type': 'Bot', 'site_admin': False}, 'created_at': '2023-06-14T14:42:30Z', 'updated_at': '2023-06-14T14:42:30Z', 'author_association': 'NONE', 'body': '<details>\n<summary>Show benchmarks</summary>\n\nPyArrow==8.0.0\n\n<details>\n<summary>Show updated benchmarks!</summary>\n\n### Benchmark: benchmark_array_xd.json\n\n| metric | read_batch_formatted_as_numpy after write_array2d | read_batch_formatted_as_numpy after write_flattened_sequence | read_batch_formatted_as_numpy after write_nested_sequence | read_batch_unformated after write_array2d | read_batch_unformated after write_flattened_sequence | read_batch_unformated after write_nested_sequence | read_col_formatted_as_numpy after write_array2d | read_col_formatted_as_numpy after write_flattened_sequence | read_col_formatted_as_numpy after write_nested_sequence | read_col_unformated after write_array2d | read_col_unformated after write_flattened_sequence | read_col_unformated after write_nested_sequence | read_formatted_as_numpy after write_array2d | read_formatted_as_numpy after write_flattened_sequence | read_formatted_as_numpy after write_nested_sequence | read_unformated after write_array2d | read_unformated after write_flattened_sequence | read_unformated after write_nested_sequence | write_array2d | write_flattened_sequence | write_nested_sequence |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.006976 / 0.011353 (-0.004377) | 0.004541 / 0.011008 (-0.006467) | 0.106085 / 0.038508 (0.067577) | 0.029148 / 0.023109 (0.006039) | 0.306386 / 0.275898 (0.030488) | 0.351474 / 0.323480 (0.027994) | 0.003924 / 0.007986 (-0.004062) | 0.004588 / 0.004328 (0.000260) | 0.090479 / 0.004250 (0.086229) | 0.041195 / 0.037052 (0.004142) | 0.346020 / 0.258489 (0.087531) | 0.362526 / 0.293841 (0.068685) | 0.041020 / 0.128546 (-0.087526) | 0.012536 / 0.075646 (-0.063110) | 0.333247 / 0.419271 (-0.086024) | 0.059786 / 0.043533 (0.016253) | 0.318094 / 0.255139 (0.062955) | 0.343879 / 0.283200 (0.060679) | 0.110083 / 0.141683 (-0.031600) | 1.514027 / 1.452155 (0.061872) | 1.551435 / 1.492716 (0.058719) |\n\n### Benchmark: benchmark_getitem\\_100B.json\n\n| metric | get_batch_of\\_1024\\_random_rows | get_batch_of\\_1024\\_rows | get_first_row | get_last_row |\n|--------|---|---|---|---|\n| new / old (diff) | 0.235401 / 0.018006 (0.217395) | 0.544292 / 0.000490 (0.543803) | 0.005284 / 0.000200 (0.005084) | 0.000112 / 0.000054 (0.000057) |\n\n### Benchmark: benchmark_indices_mapping.json\n\n| metric | select | shard | shuffle | sort | train_test_split |\n|--------|---|---|---|---|---|\n| new / old (diff) | 0.025008 / 0.037411 (-0.012403) | 0.102235 / 0.014526 (0.087709) | 0.105523 / 0.176557 (-0.071034) | 0.180846 / 0.737135 (-0.556289) | 0.107078 / 0.296338 (-0.189261) |\n\n### Benchmark: benchmark_iterating.json\n\n| metric | read 5000 | read 50000 | read_batch 50000 10 | read_batch 50000 100 | read_batch 50000 1000 | read_formatted numpy 5000 | read_formatted pandas 5000 | read_formatted tensorflow 5000 | read_formatted torch 5000 | read_formatted_batch numpy 5000 10 | read_formatted_batch numpy 5000 1000 | shuffled read 5000 | shuffled read 50000 | shuffled read_batch 50000 10 | shuffled read_batch 50000 100 | shuffled read_batch 50000 1000 | shuffled read_formatted numpy 5000 | shuffled read_formatted_batch numpy 5000 10 | shuffled read_formatted_batch numpy 5000 1000 |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.502374 / 0.215209 (0.287165) | 5.224254 / 2.077655 (3.146600) | 1.987193 / 1.504120 (0.483073) | 1.694680 / 1.541195 (0.153485) | 1.663907 / 1.468490 (0.195417) | 0.786470 / 4.584777 (-3.798307) | 4.977895 / 3.745712 (1.232183) | 4.713451 / 5.269862 (-0.556410) | 2.298763 / 4.565676 (-2.266913) | 0.090225 / 0.424275 (-0.334051) | 0.011427 / 0.007607 (0.003820) | 0.640686 / 0.226044 (0.414641) | 6.351727 / 2.268929 (4.082798) | 2.636912 / 55.444624 (-52.807712) | 2.075566 / 6.876477 (-4.800911) | 2.080260 / 2.142072 (-0.061812) | 0.952727 / 4.805227 (-3.852500) | 0.188651 / 6.500664 (-6.312013) | 0.068997 / 0.075469 (-0.006472) |\n\n### Benchmark: benchmark_map_filter.json\n\n| metric | filter | map fast-tokenizer batched | map identity | map identity batched | map no-op batched | map no-op batched numpy | map no-op batched pandas | map no-op batched pytorch | map no-op batched tensorflow |\n|--------|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 1.258878 / 1.841788 (-0.582910) | 15.444724 / 8.074308 (7.370416) | 17.521918 / 10.191392 (7.330526) | 0.189732 / 0.680424 (-0.490692) | 0.031084 / 0.534201 (-0.503117) | 0.445150 / 0.579283 (-0.134133) | 0.575844 / 0.434364 (0.141480) | 0.498162 / 0.540337 (-0.042176) | 0.635885 / 1.386936 (-0.751051) |\n\n</details>\nPyArrow==latest\n\n<details>\n<summary>Show updated benchmarks!</summary>\n\n### Benchmark: benchmark_array_xd.json\n\n| metric | read_batch_formatted_as_numpy after write_array2d | read_batch_formatted_as_numpy after write_flattened_sequence | read_batch_formatted_as_numpy after write_nested_sequence | read_batch_unformated after write_array2d | read_batch_unformated after write_flattened_sequence | read_batch_unformated after write_nested_sequence | read_col_formatted_as_numpy after write_array2d | read_col_formatted_as_numpy after write_flattened_sequence | read_col_formatted_as_numpy after write_nested_se

[{'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1591070908', 'html_url': 'https://github.com/huggingface/datasets/issues/5951#issuecomment-1591070908', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5951', 'id': 1591070908, 'node_id': 'IC_kwDODunzps5e1dC8', 'user': {'login': 'lhoestq', 'id': 42851186, 'node_id': 'MDQ6VXNlcjQyODUxMTg2', 'avatar_url': 'https://avatars.githubusercontent.com/u/42851186?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/lhoestq', 'html_url': 'https://github.com/lhoestq', 'followers_url': 'https://api.github.com/users/lhoestq/followers', 'following_url': 'https://api.github.com/users/lhoestq/following{/other_user}', 'gists_url': 'https://api.github.com/users/lhoestq/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/lhoestq/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/lhoestq/subscriptions', 'organizations_url': 'https://api.github.com/users/lhoestq/orgs', 'repos_url': 'https://api.github.com/users/lhoestq/repos', 'events_url': 'https://api.github.com/users/lhoestq/events{/privacy}', 'received_events_url': 'https://api.github.com/users/lhoestq/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-14T12:10:16Z', 'updated_at': '2023-06-14T12:10:16Z', 'author_association': 'MEMBER', 'body': "Thanks for opening https://huggingface.co/datasets/discofuse/discussions/3, let's continue the discussion over there if you don't mind", 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1591070908/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1591205426', 'html_url': 'https://github.com/huggingface/datasets/issues/5951#issuecomment-1591205426', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5951', 'id': 1591205426, 'node_id': 'IC_kwDODunzps5e194y', 'user': {'login': 'akesh1235', 'id': 125154243, 'node_id': 'U_kgDOB3Wzww', 'avatar_url': 'https://avatars.githubusercontent.com/u/125154243?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/akesh1235', 'html_url': 'https://github.com/akesh1235', 'followers_url': 'https://api.github.com/users/akesh1235/followers', 'following_url': 'https://api.github.com/users/akesh1235/following{/other_user}', 'gists_url': 'https://api.github.com/users/akesh1235/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/akesh1235/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/akesh1235/subscriptions', 'organizations_url': 'https://api.github.com/users/akesh1235/orgs', 'repos_url': 'https://api.github.com/users/akesh1235/repos', 'events_url': 'https://api.github.com/users/akesh1235/events{/privacy}', 'received_events_url': 'https://api.github.com/users/akesh1235/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-14T13:24:33Z', 'updated_at': '2023-06-14T13:25:06Z', 'author_association': 'NONE', 'body': 'I have posted there also sir, please check\r\n@lhoestq', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1591205426/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}]
[{'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1591075911', 'html_url': 'https://github.com/huggingface/datasets/issues/5950#issuecomment-1591075911', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5950', 'id': 1591075911, 'node_id': 'IC_kwDODunzps5e1eRH', 'user': {'login': 'lhoestq', 'id': 42851186, 'node_id': 'MDQ6VXNlcjQyODUxMTg2', 'avatar_url': 'https://avatars.githubusercontent.com/u/42851186?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/lhoestq', 'html_url': 'https://github.com/lhoestq', 'followers_url': 'https://api.github.com/users/lhoestq/followers', 'following_url': 'https://api.github.com/users/lhoestq/following{/other_user}', 'gists_url': 'https://api.github.com/users/lhoestq/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/lhoestq/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/lhoestq/subscriptions', 'organizations_url': 'https://api.github.com/users/lhoestq/orgs', 'repos_url': 'https://api.github.com/users/lhoestq/repos', 'events_url': 'https://api.github.com/users/lhoestq/events{/privacy}', 'received_events_url': 'https://api.github.com/users/lhoestq/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-14T12:13:38Z', 'updated_at': '2023-06-14T12:13:38Z', 'author_association': 'MEMBER', 'body': 'Hi ! We use the Arrow columnar format under the hood, which doesn\'t support such dictionaries: each field must have a fixed type and exist in each sample.\r\n\r\nInstead you can restructure your data like\r\n```\r\n{\r\n    "index": 0,\r\n    "keys": ["2 * x + y >= 3"],\r\n    "values": [["2 * x + y >= 3", "4 * x + 2 * y >= 6"]],\r\n    }\r\n},\r\n...\r\n{\r\n    "index": 9999,\r\n    "keys": ["x >= 6"],\r\n    "values": [["x >= 6", "x >= 0", "x >= -1"]],\r\n},\r\n...\r\n```', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1591075911/reactions', 'total_count': 1, '+1': 1, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}]

[{'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1589241316', 'html_url': 'https://github.com/huggingface/datasets/pull/5948#issuecomment-1589241316', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5948', 'id': 1589241316, 'node_id': 'IC_kwDODunzps5eueXk', 'user': {'login': 'HuggingFaceDocBuilderDev', 'id': 99929124, 'node_id': 'U_kgDOBfTMJA', 'avatar_url': 'https://avatars.githubusercontent.com/u/99929124?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/HuggingFaceDocBuilderDev', 'html_url': 'https://github.com/HuggingFaceDocBuilderDev', 'followers_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/followers', 'following_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/following{/other_user}', 'gists_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/subscriptions', 'organizations_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/orgs', 'repos_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/repos', 'events_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/events{/privacy}', 'received_events_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-13T12:44:25Z', 'updated_at': '2023-06-14T15:04:22Z', 'author_association': 'NONE', 'body': '_The documentation is not available anymore as the PR was closed or merged._', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1589241316/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1591437857', 'html_url': 'https://github.com/huggingface/datasets/pull/5948#issuecomment-1591437857', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5948', 'id': 1591437857, 'node_id': 'IC_kwDODunzps5e22oh', 'user': {'login': 'github-actions[bot]', 'id': 41898282, 'node_id': 'MDM6Qm90NDE4OTgyODI=', 'avatar_url': 'https://avatars.githubusercontent.com/in/15368?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/github-actions%5Bbot%5D', 'html_url': 'https://github.com/apps/github-actions', 'followers_url': 'https://api.github.com/users/github-actions%5Bbot%5D/followers', 'following_url': 'https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}', 'gists_url': 'https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/github-actions%5Bbot%5D/subscriptions', 'organizations_url': 'https://api.github.com/users/github-actions%5Bbot%5D/orgs', 'repos_url': 'https://api.github.com/users/github-actions%5Bbot%5D/repos', 'events_url': 'https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}', 'received_events_url': 'https://api.github.com/users/github-actions%5Bbot%5D/received_events', 'type': 'Bot', 'site_admin': False}, 'created_at': '2023-06-14T15:11:54Z', 'updated_at': '2023-06-14T15:11:54Z', 'author_association': 'NONE', 'body': '<details>\n<summary>Show benchmarks</summary>\n\nPyArrow==8.0.0\n\n<details>\n<summary>Show updated benchmarks!</summary>\n\n### Benchmark: benchmark_array_xd.json\n\n| metric | read_batch_formatted_as_numpy after write_array2d | read_batch_formatted_as_numpy after write_flattened_sequence | read_batch_formatted_as_numpy after write_nested_sequence | read_batch_unformated after write_array2d | read_batch_unformated after write_flattened_sequence | read_batch_unformated after write_nested_sequence | read_col_formatted_as_numpy after write_array2d | read_col_formatted_as_numpy after write_flattened_sequence | read_col_formatted_as_numpy after write_nested_sequence | read_col_unformated after write_array2d | read_col_unformated after write_flattened_sequence | read_col_unformated after write_nested_sequence | read_formatted_as_numpy after write_array2d | read_formatted_as_numpy after write_flattened_sequence | read_formatted_as_numpy after write_nested_sequence | read_unformated after write_array2d | read_unformated after write_flattened_sequence | read_unformated after write_nested_sequence | write_array2d | write_flattened_sequence | write_nested_sequence |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.007220 / 0.011353 (-0.004133) | 0.004558 / 0.011008 (-0.006451) | 0.116647 / 0.038508 (0.078139) | 0.046845 / 0.023109 (0.023736) | 0.352429 / 0.275898 (0.076531) | 0.429739 / 0.323480 (0.106259) | 0.006620 / 0.007986 (-0.001366) | 0.003731 / 0.004328 (-0.000597) | 0.088683 / 0.004250 (0.084433) | 0.070583 / 0.037052 (0.033530) | 0.366699 / 0.258489 (0.108210) | 0.420730 / 0.293841 (0.126889) | 0.037342 / 0.128546 (-0.091204) | 0.010041 / 0.075646 (-0.065605) | 0.383477 / 0.419271 (-0.035795) | 0.060279 / 0.043533 (0.016746) | 0.349988 / 0.255139 (0.094849) | 0.371423 / 0.283200 (0.088224) | 0.026725 / 0.141683 (-0.114958) | 1.736886 / 1.452155 (0.284731) | 1.812874 / 1.492716 (0.320157) |\n\n### Benchmark: benchmark_getitem\\_100B.json\n\n| metric | get_batch_of\\_1024\\_random_rows | get_batch_of\\_1024\\_rows | get_first_row | get_last_row |\n|--------|---|---|---|---|\n| new / old (diff) | 0.253256 / 0.018006 (0.235250) | 0.563470 / 0.000490 (0.562980) | 0.010475 / 0.000200 (0.010275) | 0.000164 / 0.000054 (0.000110) |\n\n### Benchmark: benchmark_indices_mapping.json\n\n| metric | select | shard | shuffle | sort | train_test_split |\n|--------|---|---|---|---|---|\n| new / old (diff) | 0.030518 / 0.037411 (-0.006893) | 0.133324 / 0.014526 (0.118798) | 0.137095 / 0.176557 (-0.039461) | 0.202227 / 0.737135 (-0.534909) | 0.144195 / 0.296338 (-0.152143) |\n\n### Benchmark: benchmark_iterating.json\n\n| metric | read 5000 | read 50000 | read_batch 50000 10 | read_batch 50000 100 | read_batch 50000 1000 | read_formatted numpy 5000 | read_formatted pandas 5000 | read_formatted tensorflow 5000 | read_formatted torch 5000 | read_formatted_batch numpy 5000 10 | read_formatted_batch numpy 5000 1000 | shuffled read 5000 | shuffled read 50000 | shuffled read_batch 50000 10 | shuffled read_batch 50000 100 | shuffled read_batch 50000 1000 | shuffled read_formatted numpy 5000 | shuffled read_formatted_batch numpy 5000 10 | shuffled read_formatted_batch numpy 5000 1000 |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.480870 / 0.215209 (0.265661) | 4.822713 / 2.077655 (2.745058) | 2.124183 / 1.504120 (0.620064) | 1.910733 / 1.541195 (0.369538) | 1.970266 / 1.468490 (0.501776) | 0.624695 / 4.584777 (-3.960082) | 4.459659 / 3.745712 (0.713947) | 2.210123 / 5.269862 (-3.059739) | 1.300520 / 4.565676 (-3.265157) | 0.077096 / 0.424275 (-0.347180) | 0.013333 / 0.007607 (0.005726) | 0.596841 / 0.226044 (0.370797) | 5.917397 / 2.268929 (3.648469) | 2.699397 / 55.444624 (-52.745228) | 2.274833 / 6.876477 (-4.601644) | 2.525376 / 2.142072 (0.383304) | 0.755718 / 4.805227 (-4.049510) | 0.163587 / 6.500664 (-6.337077) | 0.072817 / 0.075469 (-0.002653) |\n\n### Benchmark: benchmark_map_filter.json\n\n| metric | filter | map fast-tokenizer batched | map identity | map identity batched | map no-op batched | map no-op batched numpy | map no-op batched pandas | map no-op batched pytorch | map no-op batched tensorflow |\n|--------|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 1.524306 / 1.841788 (-0.317481) | 18.843312 / 8.074308 (10.769004) | 15.694644 / 10.191392 (5.503252) | 0.177400 / 0.680424 (-0.503024) | 0.020104 / 0.534201 (-0.514097) | 0.466421 / 0.579283 (-0.112862) | 0.537274 / 0.434364 (0.102910) | 0.576920 / 0.540337 (0.036583) | 0.718889 / 1.386936 (-0.668047) |\n\n</details>\nPyArrow==latest\n\n<details>\n<summary>Show updated benchmarks!</summary>\n\n### Benchmark: benchmark_array_xd.json\n\n| metric | read_batch_formatted_as_numpy after write_array2d | read_batch_formatted_as_numpy after write_flattened_sequence | read_batch_formatted_as_numpy after write_nested_sequence | read_batch_unformated after write_array2d | read_batch_unformated after write_flattened_sequence | read_batch_unformated after write_nested_sequence | read_col_formatted_as_numpy after write_array2d | read_col_formatted_as_numpy after write_flattened_sequence | read_col_formatted_as_numpy after write_nested_sequence | read_col_unformated after write_array2d | read_col_unformated after write_flattened_sequence | read_col_unformated after write_nested_sequence | read_formatted_as_numpy after write_array2d | read_formatted_as_numpy after write_flattened_sequence | read_formatted_as_numpy after write_nested_sequence | read_unformated after write_array2d | read_unformated after write_flattened_sequence | read_unformated after write_nested_sequence | write_array2d | write_flattened_sequence | write_nested_sequence |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.007671 / 0.011353 (-0.003682) | 0.004850 / 0.011008 (-0.006158) | 0.090085 / 0.038508 (0.051576) | 0.052023 / 0.023109 (0.028914) | 0.508575 / 0.275898 (0.232677) | 0.590024 / 0.323480 (0.266544) | 0.004564 / 0.007986 (-0.003422) | 0.005345 / 0.004328 (0.001017) | 0.087904 / 0.004250 (0.083653) | 0.064446 / 0.037052 (0.027394) | 0.525625 / 0.258489 (0.267136) | 0.584307 / 0.293841 (0.290466) | 0.037221 / 0.128546 (-0.091325) | 0.010588 / 0.075646 (-0.065059) | 0.098612 / 0.419271 (-0.320659) | 0.059597 / 0.043533 (0.016064) | 0.488064 / 0.255139 (0.232925) | 0.522330 / 0.283200 (0.239131) | 0.030004 / 0.141683 (-0.111679) | 1.732512 / 1.452155 (0.280357) | 1.809027 / 1.492716 (0.316310) |\n\n### Benchmark: benchmark_getitem\\_100B.json\n\n| metric | get_batch_of\\_1024\\_random_rows | get_batch_of\\_1024\\_rows | get_first_row | get_last_row |\n|--------|---|---|---|---|\n| new / old (diff) | 0.218741 / 0.018006 (0.200735) | 0.494946 / 0.000490 (0.494456) | 0.004580 / 0.000200 (0.004380) | 0.000104 / 0.000054 (0.000049) |\n\n### Benchmark: benchmark_indices_mapping.json\n\n| metric | select | shard | shuffle | sort | train_test_split |\n|--------|---|---|---|---|---|\n| new / old (diff) | 0.034916 / 0.037411 (-0.002495) | 0.133695 / 0.014526 (0.119169) | 0.147964 / 0.176557 (-0.028592) | 0.213210 / 0.737135 (-0.523926) | 0.148850 / 0.296338 (-0.147488) |\n\n### Benchmark: benchmark_iterating.json\n\n| metric | read 5000 | read 50000 | read_batch 50000 10 | read_batch 50000 100 | read_batch 50000 1000 | read_formatted numpy 5000 | read_formatted pandas 5000 | read_formatted tensorflow 5000 | read_formatted torch 5000 | read_formatted_batch numpy 5000 10 | read_formatted_batch numpy 5000 1000 | shuffled read 5000 | shuffled read 50000 | shuffled read_batch 50000 10 | shuffled read_batch 50000 100 | shuffled read_batch 50000 1000 | shuffled read_formatted numpy 5000 | shuffled read_formatted_batch numpy 5000 10 | shuffled read_formatted_batch numpy 5000 1000 |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.508855 / 0.215209 (0.293646) | 5.065088 / 2.077655 (2.987433) | 2.473110 / 1.504120 (0.968990) | 2.259765 / 1.541195 (0.718570) | 2.359189 / 1.468490 (0.890699) | 0.639082 / 4.584777 (-3.945695) | 4.768195 / 3.745712 (1.022482) | 2.253803 / 5.269862 (-3.016059) | 1.442996 / 4.565676 (-3.122680) | 0.078761 / 0.424275 (-0.345514) | 0.013936 / 0.007607 (0.006329) | 0.625977 / 0.226044 (0.399933) | 6.260817 / 2.268929 (3.991888) | 3.149640 / 55.444624 (-52.294985) | 2.753555 / 6.876477 (-4.122921) | 2.831872 / 2.142072 (0.689799) | 0.781294 / 4.805227 (-4.023933) | 0.169109 / 6.500664 (-6.331555) | 0.075810 / 0.075469 (0.000341) |\n\n### Benchmark: benchmark_map_filter.json\n\n| metric | filter | map fast-tokenizer batched | map identity | map identity batched | map no-op batched | map no-op batched numpy | map no-op batched pandas | map no-op batched pytorch | map no-op batched tensorflow |\n|--------|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 1.533282 / 1.841788 (-0.308506) | 19.460579 / 8.074308 (11.386271) | 17.250424 / 10.191392 (7.059032) | 0.193485 / 0.680424 (-0.486939) | 0.020650 / 0.534201 (-0.513551) | 0.472110 / 0.579283 (-0.107173) | 0.532276 / 0.434364 (0.097912) | 0.613152 / 0.540337 (0.072814) | 0.684684 / 1.386936 (-0.702252) |\n\n</details>\n</details>\n\n![](https://cml.dev/watermark.png#650a86ee122209d4a8c8e8068c01ebfd3ba553f5 "CML watermark")\n', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1591437857/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}]

[{'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1591081260', 'html_url': 'https://github.com/huggingface/datasets/issues/5947#issuecomment-1591081260', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5947', 'id': 1591081260, 'node_id': 'IC_kwDODunzps5e1fks', 'user': {'login': 'lhoestq', 'id': 42851186, 'node_id': 'MDQ6VXNlcjQyODUxMTg2', 'avatar_url': 'https://avatars.githubusercontent.com/u/42851186?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/lhoestq', 'html_url': 'https://github.com/lhoestq', 'followers_url': 'https://api.github.com/users/lhoestq/followers', 'following_url': 'https://api.github.com/users/lhoestq/following{/other_user}', 'gists_url': 'https://api.github.com/users/lhoestq/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/lhoestq/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/lhoestq/subscriptions', 'organizations_url': 'https://api.github.com/users/lhoestq/orgs', 'repos_url': 'https://api.github.com/users/lhoestq/repos', 'events_url': 'https://api.github.com/users/lhoestq/events{/privacy}', 'received_events_url': 'https://api.github.com/users/lhoestq/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-14T12:17:36Z', 'updated_at': '2023-06-14T12:17:36Z', 'author_association': 'MEMBER', 'body': 'Hi ! The audio data don\'t always exist as files on disk - the blobs are often stored in the Arrow files. For now I\'d suggest disabling decoding with `.cast_column("audio", Audio(decode=False))` and apply your own decoding that handles corrupted files (maybe to filter them out ?)\r\n\r\ncc @sanchit-gandhi since it\'s related to our discussion about allowing users to make decoding return `None` and show a warning when there are corrupted files', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1591081260/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1591121455', 'html_url': 'https://github.com/huggingface/datasets/issues/5947#issuecomment-1591121455', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5947', 'id': 1591121455, 'node_id': 'IC_kwDODunzps5e1pYv', 'user': {'login': 'wetdog', 'id': 8949105, 'node_id': 'MDQ6VXNlcjg5NDkxMDU=', 'avatar_url': 'https://avatars.githubusercontent.com/u/8949105?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/wetdog', 'html_url': 'https://github.com/wetdog', 'followers_url': 'https://api.github.com/users/wetdog/followers', 'following_url': 'https://api.github.com/users/wetdog/following{/other_user}', 'gists_url': 'https://api.github.com/users/wetdog/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/wetdog/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/wetdog/subscriptions', 'organizations_url': 'https://api.github.com/users/wetdog/orgs', 'repos_url': 'https://api.github.com/users/wetdog/repos', 'events_url': 'https://api.github.com/users/wetdog/events{/privacy}', 'received_events_url': 'https://api.github.com/users/wetdog/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-14T12:44:02Z', 'updated_at': '2023-06-14T12:45:01Z', 'author_association': 'NONE', 'body': 'Thanks @lhoestq, I wasn\'t aware of the decode flag. It makes more sense as you say to show a warning when there are corrupted files together with some metadata of the file that allows to filter them from the dataset.\r\n\r\nMy workaround was to catch the LibsndfileError and generate a dummy audio with an unsual sample rate to filter it later. However returning `None` seems better. \r\n\r\n`try:\r\n    array, sampling_rate = sf.read(file)\r\nexcept sf.LibsndfileError:\r\n    print("bad file")\r\n    array = np.array([0.0])\r\n    sampling_rate = 99.000` \r\n\r\n', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1591121455/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}]
[{'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1589080032', 'html_url': 'https://github.com/huggingface/datasets/issues/5946#issuecomment-1589080032', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5946', 'id': 1589080032, 'node_id': 'IC_kwDODunzps5et2_g', 'user': {'login': 'syngokhan', 'id': 70565543, 'node_id': 'MDQ6VXNlcjcwNTY1NTQz', 'avatar_url': 'https://avatars.githubusercontent.com/u/70565543?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/syngokhan', 'html_url': 'https://github.com/syngokhan', 'followers_url': 'https://api.github.com/users/syngokhan/followers', 'following_url': 'https://api.github.com/users/syngokhan/following{/other_user}', 'gists_url': 'https://api.github.com/users/syngokhan/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/syngokhan/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/syngokhan/subscriptions', 'organizations_url': 'https://api.github.com/users/syngokhan/orgs', 'repos_url': 'https://api.github.com/users/syngokhan/repos', 'events_url': 'https://api.github.com/users/syngokhan/events{/privacy}', 'received_events_url': 'https://api.github.com/users/syngokhan/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-13T11:06:43Z', 'updated_at': '2023-06-13T11:06:43Z', 'author_association': 'NONE', 'body': 'https://colab.research.google.com/#scrollTo=AQ_HCYruWIHU&fileId=https%3A//huggingface.co/dfurman/falcon-40b-chat-oasst1/blob/main/finetune_falcon40b_oasst1_with_bnb_peft.ipynb\r\n\r\nI ran the same administration exactly the same but got the same error', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1589080032/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1591085621', 'html_url': 'https://github.com/huggingface/datasets/issues/5946#issuecomment-1591085621', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5946', 'id': 1591085621, 'node_id': 'IC_kwDODunzps5e1go1', 'user': {'login': 'lhoestq', 'id': 42851186, 'node_id': 'MDQ6VXNlcjQyODUxMTg2', 'avatar_url': 'https://avatars.githubusercontent.com/u/42851186?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/lhoestq', 'html_url': 'https://github.com/lhoestq', 'followers_url': 'https://api.github.com/users/lhoestq/followers', 'following_url': 'https://api.github.com/users/lhoestq/following{/other_user}', 'gists_url': 'https://api.github.com/users/lhoestq/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/lhoestq/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/lhoestq/subscriptions', 'organizations_url': 'https://api.github.com/users/lhoestq/orgs', 'repos_url': 'https://api.github.com/users/lhoestq/repos', 'events_url': 'https://api.github.com/users/lhoestq/events{/privacy}', 'received_events_url': 'https://api.github.com/users/lhoestq/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-14T12:20:12Z', 'updated_at': '2023-06-14T12:20:12Z', 'author_association': 'MEMBER', 'body': 'Looks related to https://discuss.huggingface.co/t/indexerror-invalid-key-16-is-out-of-bounds-for-size-0/14298/4?u=lhoestq', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1591085621/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1595661238', 'html_url': 'https://github.com/huggingface/datasets/issues/5946#issuecomment-1595661238', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5946', 'id': 1595661238, 'node_id': 'IC_kwDODunzps5fG9u2', 'user': {'login': 'syngokhan', 'id': 70565543, 'node_id': 'MDQ6VXNlcjcwNTY1NTQz', 'avatar_url': 'https://avatars.githubusercontent.com/u/70565543?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/syngokhan', 'html_url': 'https://github.com/syngokhan', 'followers_url': 'https://api.github.com/users/syngokhan/followers', 'following_url': 'https://api.github.com/users/syngokhan/following{/other_user}', 'gists_url': 'https://api.github.com/users/syngokhan/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/syngokhan/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/syngokhan/subscriptions', 'organizations_url': 'https://api.github.com/users/syngokhan/orgs', 'repos_url': 'https://api.github.com/users/syngokhan/repos', 'events_url': 'https://api.github.com/users/syngokhan/events{/privacy}', 'received_events_url': 'https://api.github.com/users/syngokhan/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-17T07:51:58Z', 'updated_at': '2023-06-17T07:52:31Z', 'author_association': 'NONE', 'body': '> Looks related to https://discuss.huggingface.co/t/indexerror-invalid-key-16-is-out-of-bounds-for-size-0/14298/4?u=lhoestq\n\nThe problem has not been solved, I have tried this before, but the problem is the same', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1595661238/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1634503846', 'html_url': 'https://github.com/huggingface/datasets/issues/5946#issuecomment-1634503846', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5946', 'id': 1634503846, 'node_id': 'IC_kwDODunzps5hbIym', 'user': {'login': 'serino28', 'id': 61455975, 'node_id': 'MDQ6VXNlcjYxNDU1OTc1', 'avatar_url': 'https://avatars.githubusercontent.com/u/61455975?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/serino28', 'html_url': 'https://github.com/serino28', 'followers_url': 'https://api.github.com/users/serino28/followers', 'following_url': 'https://api.github.com/users/serino28/following{/other_user}', 'gists_url': 'https://api.github.com/users/serino28/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/serino28/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/serino28/subscriptions', 'organizations_url': 'https://api.github.com/users/serino28/orgs', 'repos_url': 'https://api.github.com/users/serino28/repos', 'events_url': 'https://api.github.com/users/serino28/events{/privacy}', 'received_events_url': 'https://api.github.com/users/serino28/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-07-13T15:59:42Z', 'updated_at': '2023-07-13T15:59:42Z', 'author_association': 'NONE', 'body': '> \r\n\r\n@syngokhan did u solve it? \r\nI am desperate ', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1634503846/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}]

[{'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1591082689', 'html_url': 'https://github.com/huggingface/datasets/issues/5945#issuecomment-1591082689', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5945', 'id': 1591082689, 'node_id': 'IC_kwDODunzps5e1f7B', 'user': {'login': 'lhoestq', 'id': 42851186, 'node_id': 'MDQ6VXNlcjQyODUxMTg2', 'avatar_url': 'https://avatars.githubusercontent.com/u/42851186?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/lhoestq', 'html_url': 'https://github.com/lhoestq', 'followers_url': 'https://api.github.com/users/lhoestq/followers', 'following_url': 'https://api.github.com/users/lhoestq/following{/other_user}', 'gists_url': 'https://api.github.com/users/lhoestq/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/lhoestq/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/lhoestq/subscriptions', 'organizations_url': 'https://api.github.com/users/lhoestq/orgs', 'repos_url': 'https://api.github.com/users/lhoestq/repos', 'events_url': 'https://api.github.com/users/lhoestq/events{/privacy}', 'received_events_url': 'https://api.github.com/users/lhoestq/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-14T12:18:30Z', 'updated_at': '2023-06-14T12:18:30Z', 'author_association': 'MEMBER', 'body': 'Hi ! Feel free to re-run your code later, it will resume automatically where you left', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1591082689/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1596191510', 'html_url': 'https://github.com/huggingface/datasets/issues/5945#issuecomment-1596191510', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5945', 'id': 1596191510, 'node_id': 'IC_kwDODunzps5fI_MW', 'user': {'login': 'Ar770', 'id': 77382661, 'node_id': 'MDQ6VXNlcjc3MzgyNjYx', 'avatar_url': 'https://avatars.githubusercontent.com/u/77382661?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/Ar770', 'html_url': 'https://github.com/Ar770', 'followers_url': 'https://api.github.com/users/Ar770/followers', 'following_url': 'https://api.github.com/users/Ar770/following{/other_user}', 'gists_url': 'https://api.github.com/users/Ar770/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/Ar770/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/Ar770/subscriptions', 'organizations_url': 'https://api.github.com/users/Ar770/orgs', 'repos_url': 'https://api.github.com/users/Ar770/repos', 'events_url': 'https://api.github.com/users/Ar770/events{/privacy}', 'received_events_url': 'https://api.github.com/users/Ar770/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-18T16:00:13Z', 'updated_at': '2023-06-18T16:00:13Z', 'author_association': 'NONE', 'body': 'Tried many times in the last 2 weeks, problem remains.', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1596191510/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1596964827', 'html_url': 'https://github.com/huggingface/datasets/issues/5945#issuecomment-1596964827', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5945', 'id': 1596964827, 'node_id': 'IC_kwDODunzps5fL7_b', 'user': {'login': 'lhoestq', 'id': 42851186, 'node_id': 'MDQ6VXNlcjQyODUxMTg2', 'avatar_url': 'https://avatars.githubusercontent.com/u/42851186?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/lhoestq', 'html_url': 'https://github.com/lhoestq', 'followers_url': 'https://api.github.com/users/lhoestq/followers', 'following_url': 'https://api.github.com/users/lhoestq/following{/other_user}', 'gists_url': 'https://api.github.com/users/lhoestq/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/lhoestq/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/lhoestq/subscriptions', 'organizations_url': 'https://api.github.com/users/lhoestq/orgs', 'repos_url': 'https://api.github.com/users/lhoestq/repos', 'events_url': 'https://api.github.com/users/lhoestq/events{/privacy}', 'received_events_url': 'https://api.github.com/users/lhoestq/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-19T10:54:54Z', 'updated_at': '2023-06-19T10:54:54Z', 'author_association': 'MEMBER', 'body': 'Alternatively you can save your dataset in parquet files locally and upload them to the hub manually\r\n\r\n```python\r\nfrom tqdm import tqdm\r\nnum_shards = 60\r\nfor index in tqdm(range(num_shards)):\r\n    ds.shard(num_shards=num_shards, index=index, contiguous=True).to_parquet(f"{index:05d}.parquet")\r\n````', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1596964827/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}]

[]
[{'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1591088082', 'html_url': 'https://github.com/huggingface/datasets/issues/5941#issuecomment-1591088082', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5941', 'id': 1591088082, 'node_id': 'IC_kwDODunzps5e1hPS', 'user': {'login': 'lhoestq', 'id': 42851186, 'node_id': 'MDQ6VXNlcjQyODUxMTg2', 'avatar_url': 'https://avatars.githubusercontent.com/u/42851186?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/lhoestq', 'html_url': 'https://github.com/lhoestq', 'followers_url': 'https://api.github.com/users/lhoestq/followers', 'following_url': 'https://api.github.com/users/lhoestq/following{/other_user}', 'gists_url': 'https://api.github.com/users/lhoestq/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/lhoestq/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/lhoestq/subscriptions', 'organizations_url': 'https://api.github.com/users/lhoestq/orgs', 'repos_url': 'https://api.github.com/users/lhoestq/repos', 'events_url': 'https://api.github.com/users/lhoestq/events{/privacy}', 'received_events_url': 'https://api.github.com/users/lhoestq/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-14T12:22:00Z', 'updated_at': '2023-06-14T12:22:00Z', 'author_association': 'MEMBER', 'body': 'Hi ! you can speed it up using multiprocessing by passing `num_proc=` to `load_dataset()`', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1591088082/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1592173628', 'html_url': 'https://github.com/huggingface/datasets/issues/5941#issuecomment-1592173628', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5941', 'id': 1592173628, 'node_id': 'IC_kwDODunzps5e5qQ8', 'user': {'login': 'xyx361100238', 'id': 19569322, 'node_id': 'MDQ6VXNlcjE5NTY5MzIy', 'avatar_url': 'https://avatars.githubusercontent.com/u/19569322?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/xyx361100238', 'html_url': 'https://github.com/xyx361100238', 'followers_url': 'https://api.github.com/users/xyx361100238/followers', 'following_url': 'https://api.github.com/users/xyx361100238/following{/other_user}', 'gists_url': 'https://api.github.com/users/xyx361100238/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/xyx361100238/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/xyx361100238/subscriptions', 'organizations_url': 'https://api.github.com/users/xyx361100238/orgs', 'repos_url': 'https://api.github.com/users/xyx361100238/repos', 'events_url': 'https://api.github.com/users/xyx361100238/events{/privacy}', 'received_events_url': 'https://api.github.com/users/xyx361100238/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-15T00:53:46Z', 'updated_at': '2023-06-15T00:53:46Z', 'author_association': 'NONE', 'body': 'already did，but not useful for step Generating train split，it works in step "Resolving data files" & "Downloading data files" ', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1592173628/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1592174718', 'html_url': 'https://github.com/huggingface/datasets/issues/5941#issuecomment-1592174718', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5941', 'id': 1592174718, 'node_id': 'IC_kwDODunzps5e5qh-', 'user': {'login': 'xyx361100238', 'id': 19569322, 'node_id': 'MDQ6VXNlcjE5NTY5MzIy', 'avatar_url': 'https://avatars.githubusercontent.com/u/19569322?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/xyx361100238', 'html_url': 'https://github.com/xyx361100238', 'followers_url': 'https://api.github.com/users/xyx361100238/followers', 'following_url': 'https://api.github.com/users/xyx361100238/following{/other_user}', 'gists_url': 'https://api.github.com/users/xyx361100238/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/xyx361100238/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/xyx361100238/subscriptions', 'organizations_url': 'https://api.github.com/users/xyx361100238/orgs', 'repos_url': 'https://api.github.com/users/xyx361100238/repos', 'events_url': 'https://api.github.com/users/xyx361100238/events{/privacy}', 'received_events_url': 'https://api.github.com/users/xyx361100238/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-15T00:55:58Z', 'updated_at': '2023-06-15T00:55:58Z', 'author_association': 'NONE', 'body': '@mariosasko some advice ， thanks！', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1592174718/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1595807119', 'html_url': 'https://github.com/huggingface/datasets/issues/5941#issuecomment-1595807119', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5941', 'id': 1595807119, 'node_id': 'IC_kwDODunzps5fHhWP', 'user': {'login': 'mengban', 'id': 14243491, 'node_id': 'MDQ6VXNlcjE0MjQzNDkx', 'avatar_url': 'https://avatars.githubusercontent.com/u/14243491?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/mengban', 'html_url': 'https://github.com/mengban', 'followers_url': 'https://api.github.com/users/mengban/followers', 'following_url': 'https://api.github.com/users/mengban/following{/other_user}', 'gists_url': 'https://api.github.com/users/mengban/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/mengban/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/mengban/subscriptions', 'organizations_url': 'https://api.github.com/users/mengban/orgs', 'repos_url': 'https://api.github.com/users/mengban/repos', 'events_url': 'https://api.github.com/users/mengban/events{/privacy}', 'received_events_url': 'https://api.github.com/users/mengban/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-17T17:00:58Z', 'updated_at': '2023-06-17T17:00:58Z', 'author_association': 'NONE', 'body': 'I met the same problem,  terrible  experience', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1595807119/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1633407402', 'html_url': 'https://github.com/huggingface/datasets/issues/5941#issuecomment-1633407402', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5941', 'id': 1633407402, 'node_id': 'IC_kwDODunzps5hW9Gq', 'user': {'login': 'xyx361100238', 'id': 19569322, 'node_id': 'MDQ6VXNlcjE5NTY5MzIy', 'avatar_url': 'https://avatars.githubusercontent.com/u/19569322?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/xyx361100238', 'html_url': 'https://github.com/xyx361100238', 'followers_url': 'https://api.github.com/users/xyx361100238/followers', 'following_url': 'https://api.github.com/users/xyx361100238/following{/other_user}', 'gists_url': 'https://api.github.com/users/xyx361100238/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/xyx361100238/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/xyx361100238/subscriptions', 'organizations_url': 'https://api.github.com/users/xyx361100238/orgs', 'repos_url': 'https://api.github.com/users/xyx361100238/repos', 'events_url': 'https://api.github.com/users/xyx361100238/events{/privacy}', 'received_events_url': 'https://api.github.com/users/xyx361100238/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-07-13T01:32:53Z', 'updated_at': '2023-07-13T01:32:53Z', 'author_association': 'NONE', 'body': '@mariosasko ', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1633407402/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1634763738', 'html_url': 'https://github.com/huggingface/datasets/issues/5941#issuecomment-1634763738', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5941', 'id': 1634763738, 'node_id': 'IC_kwDODunzps5hcIPa', 'user': {'login': 'mariosasko', 'id': 47462742, 'node_id': 'MDQ6VXNlcjQ3NDYyNzQy', 'avatar_url': 'https://avatars.githubusercontent.com/u/47462742?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/mariosasko', 'html_url': 'https://github.com/mariosasko', 'followers_url': 'https://api.github.com/users/mariosasko/followers', 'following_url': 'https://api.github.com/users/mariosasko/following{/other_user}', 'gists_url': 'https://api.github.com/users/mariosasko/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/mariosasko/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/mariosasko/subscriptions', 'organizations_url': 'https://api.github.com/users/mariosasko/orgs', 'repos_url': 'https://api.github.com/users/mariosasko/repos', 'events_url': 'https://api.github.com/users/mariosasko/events{/privacy}', 'received_events_url': 'https://api.github.com/users/mariosasko/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-07-13T19:15:10Z', 'updated_at': '2023-07-13T19:15:41Z', 'author_association': 'CONTRIBUTOR', 'body': "We need more info about the issue to provide help. \r\n\r\nCan you interrupt the process (with `num_proc=None`) after the `load_dataset` call when the slowdown occurs? So we can know what part of the code is causing it.\r\n\r\nThe `audiofolder` \\ `imagefolder` with metadata is not performant for large datasets. Luckily, we can make them much faster if drop the nested metadata files feature (not that useful). I plan to work on this soon.\r\n\r\nIn the meantime, it's better to use `Dataset.from_generator` (requires replacing the `load_dataset` calls in the transformers script with `Dataset.from_generator`) or write a dataset loading script for large datasets.", 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1634763738/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}]

[{'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1607120155', 'html_url': 'https://github.com/huggingface/datasets/issues/5990#issuecomment-1607120155', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5990', 'id': 1607120155, 'node_id': 'IC_kwDODunzps5fyrUb', 'user': {'login': 'Wauplin', 'id': 11801849, 'node_id': 'MDQ6VXNlcjExODAxODQ5', 'avatar_url': 'https://avatars.githubusercontent.com/u/11801849?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/Wauplin', 'html_url': 'https://github.com/Wauplin', 'followers_url': 'https://api.github.com/users/Wauplin/followers', 'following_url': 'https://api.github.com/users/Wauplin/following{/other_user}', 'gists_url': 'https://api.github.com/users/Wauplin/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/Wauplin/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/Wauplin/subscriptions', 'organizations_url': 'https://api.github.com/users/Wauplin/orgs', 'repos_url': 'https://api.github.com/users/Wauplin/repos', 'events_url': 'https://api.github.com/users/Wauplin/events{/privacy}', 'received_events_url': 'https://api.github.com/users/Wauplin/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-13T09:50:49Z', 'updated_at': '2023-06-13T09:51:03Z', 'author_association': 'CONTRIBUTOR', 'body': "Hi @AntreasAntoniou , sorry to know you are facing this issue. To help debugging it, could you tell me:\r\n- What is the total dataset size?\r\n- Is it always failing on the same shard or is the hanging problem happening randomly?\r\n- Were you able to save the dataset as parquet locally? This would help us determine if the problem comes from the upload or the file generation.\r\n\r\nI'm cc-ing @lhoestq who might have some insights from a `datasets` perspective.", 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1607120155/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1607120168', 'html_url': 'https://github.com/huggingface/datasets/issues/5990#issuecomment-1607120168', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5990', 'id': 1607120168, 'node_id': 'IC_kwDODunzps5fyrUo', 'user': {'login': 'lhoestq', 'id': 42851186, 'node_id': 'MDQ6VXNlcjQyODUxMTg2', 'avatar_url': 'https://avatars.githubusercontent.com/u/42851186?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/lhoestq', 'html_url': 'https://github.com/lhoestq', 'followers_url': 'https://api.github.com/users/lhoestq/followers', 'following_url': 'https://api.github.com/users/lhoestq/following{/other_user}', 'gists_url': 'https://api.github.com/users/lhoestq/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/lhoestq/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/lhoestq/subscriptions', 'organizations_url': 'https://api.github.com/users/lhoestq/orgs', 'repos_url': 'https://api.github.com/users/lhoestq/repos', 'events_url': 'https://api.github.com/users/lhoestq/events{/privacy}', 'received_events_url': 'https://api.github.com/users/lhoestq/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-13T16:18:12Z', 'updated_at': '2023-06-13T16:18:12Z', 'author_association': 'MEMBER', 'body': 'One trick that can also help is to check the traceback when you kill your python process: it will show where in the code it was hanging', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1607120168/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1607120179', 'html_url': 'https://github.com/huggingface/datasets/issues/5990#issuecomment-1607120179', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5990', 'id': 1607120179, 'node_id': 'IC_kwDODunzps5fyrUz', 'user': {'login': 'AntreasAntoniou', 'id': 10792502, 'node_id': 'MDQ6VXNlcjEwNzkyNTAy', 'avatar_url': 'https://avatars.githubusercontent.com/u/10792502?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/AntreasAntoniou', 'html_url': 'https://github.com/AntreasAntoniou', 'followers_url': 'https://api.github.com/users/AntreasAntoniou/followers', 'following_url': 'https://api.github.com/users/AntreasAntoniou/following{/other_user}', 'gists_url': 'https://api.github.com/users/AntreasAntoniou/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/AntreasAntoniou/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/AntreasAntoniou/subscriptions', 'organizations_url': 'https://api.github.com/users/AntreasAntoniou/orgs', 'repos_url': 'https://api.github.com/users/AntreasAntoniou/repos', 'events_url': 'https://api.github.com/users/AntreasAntoniou/events{/privacy}', 'received_events_url': 'https://api.github.com/users/AntreasAntoniou/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-16T17:10:16Z', 'updated_at': '2023-06-16T17:10:16Z', 'author_association': 'NONE', 'body': 'Right. So I did the trick @lhoestq suggested. Here is where things seem to hang\r\n\r\n```\r\nError while uploading \'data/train-00120-of-00195-466c2dbab2eb9989.parquet\' to the Hub.                                                                                                     \r\nPushing split train to the Hub.                                                                                                                                                            \r\nCreating parquet from Arrow format: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:03<00:00,  1.15s/ba]\r\nUpload 1 LFS files: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:52<00:00, 52.12s/it]\r\nCreating parquet from Arrow format: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:03<00:00,  1.08s/ba]\r\nUpload 1 LFS files: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:45<00:00, 45.54s/it]\r\nCreating parquet from Arrow format: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:03<00:00,  1.08s/ba]\r\nCreating parquet from Arrow format: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:03<00:00,  1.03s/ba^Upload 1 LFS files:   0%|                                                                                                                                         | 0/1 [\r\n21:27:35<?, ?it/s]                                                                                                                                                                         \r\nPushing dataset shards to the dataset hub:  63%|█████████████████████████████████████████████████████████████▎                                    | 122/195 [23:37:11<14:07:59, 696.98s/it]\r\n^CError in sys.excepthook:                                                                                                                                                                 \r\nTraceback (most recent call last):                                                                                                                                                         \r\n  File "/opt/conda/envs/main/lib/python3.10/site-packages/rich/console.py", line 1699, in print                                                                                            \r\n    extend(render(renderable, render_options))                                                                                                                                             \r\n  File "/opt/conda/envs/main/lib/python3.10/site-packages/rich/console.py", line 1335, in render                                                                                           \r\n    yield from self.render(render_output, _options)                                                                                                                                        \r\n  File "/opt/conda/envs/main/lib/python3.10/site-packages/rich/console.py", line 1331, in render                                                                                           \r\n    for render_output in iter_render:                                                                                                                                                      \r\n  File "/opt/conda/envs/main/lib/python3.10/site-packages/rich/constrain.py", line 29, in __rich_console__                                                                                 \r\n    yield from console.render(self.renderable, child_options)                                                                                                                              \r\n  File "/opt/conda/envs/main/lib/python3.10/site-packages/rich/console.py", line 1331, in render                                                                                           \r\n    for render_output in iter_render:                                                                                                                                                      \r\n  File "/opt/conda/envs/main/lib/python3.10/site-packages/rich/panel.py", line 220, in __rich_console__                                                                                    \r\n    lines = console.render_lines(renderable, child_options, style=style)                                                                                                                   \r\n  File "/opt/conda/envs/main/lib/python3.10/site-packages/rich/console.py", line 1371, in render_lines                                                                                     \r\n    lines = list(                                                                                                                                                                          \r\n  File "/opt/conda/envs/main/lib/python3.10/site-packages/rich/segment.py", line 292, in split_and_crop_lines                                                                              \r\n    for segment in segments:                                                                                                                                                               \r\n  File "/opt/conda/envs/main/lib/python3.10/site-packages/rich/console.py", line 1331, in render                                                                                           \r\n    for render_output in iter_render:                                                                                                                                                      \r\n  File "/opt/conda/envs/main/lib/python3.10/site-packages/rich/padding.py", line 97, in __rich_console__                                                                                   \r\n    lines = console.render_lines(                                                                                                                                                          \r\n  File "/opt/conda/envs/main/lib/python3.10/site-packages/rich/console.py", line 1371, in render_lines                                                                                     \r\n    lines = list(                                                                                                                                                                          \r\n  File "/opt/conda/envs/main/lib/python3.10/site-packages/rich/segment.py", line 292, in split_and_crop_lines                                                                              \r\n    for segment in segments:                                                                                                                                                               \r\n  File "/opt/conda/envs/main/lib/python3.10/site-packages/rich/console.py", line 1335, in render                                                                                           \r\n    yield from self.render(render_output, _options)                                                                                                                                        \r\n  File "/opt/conda/envs/main/lib/python3.10/site-packages/rich/console.py", line 1331, in render                                                                                           \r\n    for render_output in iter_render:                                                                                                                                                      \r\n  File "/opt/conda/envs/main/lib/python3.10/site-packages/rich/syntax.py", line 611, in __rich_console__                                                                                   \r\n    segments = Segments(self._get_syntax(console, options))                                                                                                                                \r\n  File "/opt/conda/envs/main/lib/python3.10/site-packages/rich/segment.py", line 668, in __init__                                                                                          \r\n    self.segments = list(segments)                                                                                                                                                         \r\n  File "/opt/conda/envs/main/lib/python3.10/site-packages/rich/syntax.py", line 674, in _get_syntax                                                                                        \r\n    lines: Union[List[Text], Lines] = text.split("\\n", allow_blank=ends_on_nl)                                                                                                             \r\n  File "/opt/conda/envs/main/lib/python3.10/site-packages/rich/text.py", line 1042, in split                                                                                               \r\n    lines = Lines(                                                                                                                                                                         \r\n  File "/opt/conda/envs/main/lib/python3.10/site-packages/rich/containers.py", line 70, in __init__                                                                                        \r\n    self._lines: List["Text"] = list(lines)                                                                                                                                                \r\n  File "/opt/conda/envs/main/lib/python3.10/site-packages/rich/text.py", line 1043, in <genexpr>                                                                                           \r\n    line for line in self.divide(flatten_spans()) if line.plain != separator                                                                                                               \r\n  File "/opt/conda/envs/main/lib/python3.10/site-packages/rich/text.py", line 385, in plain                                                    \r\n    if len(self._text) != 1:                                                                                                                                                               \r\nKeyboardInterrupt                                                                                                                                                                                                                                                                              \r\n                                                                                                                                                                                                                                            \r\nOriginal exception was:                                                                                                                                                                                                                                                                        \r\nTraceback (most recent call last):                                                                                                                                                                                                          \r\n  File "/opt/conda/envs/main/lib/python3.10/site-packages/tqdm/contrib/concurrent.py", line 51, in _executor_map                                                                                                                                                                               \r\n    return list(tqdm_class(ex.map(fn, *iterables, chunksize=chunksize), **kwargs))                                                                                                                                                          \r\n  File "/opt/conda/envs/main/lib/python3.10/site-packages/tqdm/std.py", line 1178, in __iter__                                                                                                                                                                                                 \r\n    for obj in iterable:                                                                                                                                                                   \r\n  File "/opt/conda/envs/main/lib/python3.10/concurrent/futures/_base.py", line 621, in result_iterator                                                                                                                                                                                         \r\n    yield _result_or_cancel(fs.pop())                                                                                                                                                      \r\n  File "/opt/conda/envs/main/lib/python3.10/concurrent/futures/_base.py", line 319, in _result_or_cancel                                                                                                                                                                                       \r\n    return fut.result(timeout)                                                                                                                                                             \r\n  File "/opt/conda/envs/main/lib/python3.10/concurrent/futures/_base.py", line 453, in result                                                                                                                                                                                                  \r\n    self._condition.wait(timeout)                                                                                                                                                                                                           \r\n  File "/opt/conda/envs/main/lib/python3.10/threading.py", line 320, in wait                                                                                                                                                                                                                   \r\n    waiter.acquire()                                                                                                                                                                                                                        \r\nKeyboardInterrupt                       

[]
[{'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1591183246', 'html_url': 'https://github.com/huggingface/datasets/pull/5938#issuecomment-1591183246', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5938', 'id': 1591183246, 'node_id': 'IC_kwDODunzps5e14eO', 'user': {'login': 'HuggingFaceDocBuilderDev', 'id': 99929124, 'node_id': 'U_kgDOBfTMJA', 'avatar_url': 'https://avatars.githubusercontent.com/u/99929124?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/HuggingFaceDocBuilderDev', 'html_url': 'https://github.com/HuggingFaceDocBuilderDev', 'followers_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/followers', 'following_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/following{/other_user}', 'gists_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/subscriptions', 'organizations_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/orgs', 'repos_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/repos', 'events_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/events{/privacy}', 'received_events_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-14T13:11:48Z', 'updated_at': '2023-06-14T13:27:51Z', 'author_association': 'NONE', 'body': '_The documentation is not available anymore as the PR was closed or merged._', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1591183246/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1591224238', 'html_url': 'https://github.com/huggingface/datasets/pull/5938#issuecomment-1591224238', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5938', 'id': 1591224238, 'node_id': 'IC_kwDODunzps5e2Ceu', 'user': {'login': 'github-actions[bot]', 'id': 41898282, 'node_id': 'MDM6Qm90NDE4OTgyODI=', 'avatar_url': 'https://avatars.githubusercontent.com/in/15368?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/github-actions%5Bbot%5D', 'html_url': 'https://github.com/apps/github-actions', 'followers_url': 'https://api.github.com/users/github-actions%5Bbot%5D/followers', 'following_url': 'https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}', 'gists_url': 'https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/github-actions%5Bbot%5D/subscriptions', 'organizations_url': 'https://api.github.com/users/github-actions%5Bbot%5D/orgs', 'repos_url': 'https://api.github.com/users/github-actions%5Bbot%5D/repos', 'events_url': 'https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}', 'received_events_url': 'https://api.github.com/users/github-actions%5Bbot%5D/received_events', 'type': 'Bot', 'site_admin': False}, 'created_at': '2023-06-14T13:35:37Z', 'updated_at': '2023-06-14T13:35:37Z', 'author_association': 'NONE', 'body': '<details>\n<summary>Show benchmarks</summary>\n\nPyArrow==8.0.0\n\n<details>\n<summary>Show updated benchmarks!</summary>\n\n### Benchmark: benchmark_array_xd.json\n\n| metric | read_batch_formatted_as_numpy after write_array2d | read_batch_formatted_as_numpy after write_flattened_sequence | read_batch_formatted_as_numpy after write_nested_sequence | read_batch_unformated after write_array2d | read_batch_unformated after write_flattened_sequence | read_batch_unformated after write_nested_sequence | read_col_formatted_as_numpy after write_array2d | read_col_formatted_as_numpy after write_flattened_sequence | read_col_formatted_as_numpy after write_nested_sequence | read_col_unformated after write_array2d | read_col_unformated after write_flattened_sequence | read_col_unformated after write_nested_sequence | read_formatted_as_numpy after write_array2d | read_formatted_as_numpy after write_flattened_sequence | read_formatted_as_numpy after write_nested_sequence | read_unformated after write_array2d | read_unformated after write_flattened_sequence | read_unformated after write_nested_sequence | write_array2d | write_flattened_sequence | write_nested_sequence |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.007241 / 0.011353 (-0.004112) | 0.004574 / 0.011008 (-0.006434) | 0.120481 / 0.038508 (0.081973) | 0.040492 / 0.023109 (0.017383) | 0.391399 / 0.275898 (0.115501) | 0.422844 / 0.323480 (0.099365) | 0.004441 / 0.007986 (-0.003545) | 0.004544 / 0.004328 (0.000216) | 0.089482 / 0.004250 (0.085231) | 0.052939 / 0.037052 (0.015887) | 0.393649 / 0.258489 (0.135160) | 0.433852 / 0.293841 (0.140011) | 0.035882 / 0.128546 (-0.092664) | 0.010172 / 0.075646 (-0.065474) | 0.410331 / 0.419271 (-0.008940) | 0.061481 / 0.043533 (0.017948) | 0.405066 / 0.255139 (0.149927) | 0.417732 / 0.283200 (0.134532) | 0.121647 / 0.141683 (-0.020035) | 1.790624 / 1.452155 (0.338469) | 1.863398 / 1.492716 (0.370681) |\n\n### Benchmark: benchmark_getitem\\_100B.json\n\n| metric | get_batch_of\\_1024\\_random_rows | get_batch_of\\_1024\\_rows | get_first_row | get_last_row |\n|--------|---|---|---|---|\n| new / old (diff) | 0.250650 / 0.018006 (0.232644) | 0.489044 / 0.000490 (0.488554) | 0.010421 / 0.000200 (0.010222) | 0.000106 / 0.000054 (0.000051) |\n\n### Benchmark: benchmark_indices_mapping.json\n\n| metric | select | shard | shuffle | sort | train_test_split |\n|--------|---|---|---|---|---|\n| new / old (diff) | 0.030340 / 0.037411 (-0.007071) | 0.128318 / 0.014526 (0.113792) | 0.140463 / 0.176557 (-0.036093) | 0.205762 / 0.737135 (-0.531373) | 0.147996 / 0.296338 (-0.148342) |\n\n### Benchmark: benchmark_iterating.json\n\n| metric | read 5000 | read 50000 | read_batch 50000 10 | read_batch 50000 100 | read_batch 50000 1000 | read_formatted numpy 5000 | read_formatted pandas 5000 | read_formatted tensorflow 5000 | read_formatted torch 5000 | read_formatted_batch numpy 5000 10 | read_formatted_batch numpy 5000 1000 | shuffled read 5000 | shuffled read 50000 | shuffled read_batch 50000 10 | shuffled read_batch 50000 100 | shuffled read_batch 50000 1000 | shuffled read_formatted numpy 5000 | shuffled read_formatted_batch numpy 5000 10 | shuffled read_formatted_batch numpy 5000 1000 |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.493158 / 0.215209 (0.277949) | 4.858346 / 2.077655 (2.780691) | 2.242942 / 1.504120 (0.738822) | 2.010092 / 1.541195 (0.468897) | 2.076765 / 1.468490 (0.608275) | 0.636669 / 4.584777 (-3.948108) | 4.478027 / 3.745712 (0.732314) | 2.157843 / 5.269862 (-3.112019) | 1.305133 / 4.565676 (-3.260543) | 0.079220 / 0.424275 (-0.345055) | 0.013858 / 0.007607 (0.006251) | 0.604501 / 0.226044 (0.378457) | 5.950071 / 2.268929 (3.681143) | 2.738373 / 55.444624 (-52.706251) | 2.380275 / 6.876477 (-4.496201) | 2.517108 / 2.142072 (0.375035) | 0.772249 / 4.805227 (-4.032979) | 0.169874 / 6.500664 (-6.330790) | 0.078026 / 0.075469 (0.002557) |\n\n### Benchmark: benchmark_map_filter.json\n\n| metric | filter | map fast-tokenizer batched | map identity | map identity batched | map no-op batched | map no-op batched numpy | map no-op batched pandas | map no-op batched pytorch | map no-op batched tensorflow |\n|--------|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 1.450200 / 1.841788 (-0.391588) | 17.810965 / 8.074308 (9.736657) | 15.518998 / 10.191392 (5.327606) | 0.200469 / 0.680424 (-0.479954) | 0.020777 / 0.534201 (-0.513424) | 0.504556 / 0.579283 (-0.074727) | 0.518493 / 0.434364 (0.084129) | 0.615335 / 0.540337 (0.074998) | 0.754065 / 1.386936 (-0.632871) |\n\n</details>\nPyArrow==latest\n\n<details>\n<summary>Show updated benchmarks!</summary>\n\n### Benchmark: benchmark_array_xd.json\n\n| metric | read_batch_formatted_as_numpy after write_array2d | read_batch_formatted_as_numpy after write_flattened_sequence | read_batch_formatted_as_numpy after write_nested_sequence | read_batch_unformated after write_array2d | read_batch_unformated after write_flattened_sequence | read_batch_unformated after write_nested_sequence | read_col_formatted_as_numpy after write_array2d | read_col_formatted_as_numpy after write_flattened_sequence | read_col_formatted_as_numpy after write_nested_sequence | read_col_unformated after write_array2d | read_col_unformated after write_flattened_sequence | read_col_unformated after write_nested_sequence | read_formatted_as_numpy after write_array2d | read_formatted_as_numpy after write_flattened_sequence | read_formatted_as_numpy after write_nested_sequence | read_unformated after write_array2d | read_unformated after write_flattened_sequence | read_unformated after write_nested_sequence | write_array2d | write_flattened_sequence | write_nested_sequence |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.007224 / 0.011353 (-0.004129) | 0.004663 / 0.011008 (-0.006345) | 0.092151 / 0.038508 (0.053643) | 0.038359 / 0.023109 (0.015250) | 0.486413 / 0.275898 (0.210515) | 0.521596 / 0.323480 (0.198116) | 0.004207 / 0.007986 (-0.003778) | 0.003745 / 0.004328 (-0.000583) | 0.089840 / 0.004250 (0.085589) | 0.050996 / 0.037052 (0.013943) | 0.498090 / 0.258489 (0.239601) | 0.533647 / 0.293841 (0.239806) | 0.035151 / 0.128546 (-0.093395) | 0.010293 / 0.075646 (-0.065354) | 0.099056 / 0.419271 (-0.320215) | 0.057365 / 0.043533 (0.013833) | 0.470652 / 0.255139 (0.215513) | 0.509801 / 0.283200 (0.226602) | 0.115650 / 0.141683 (-0.026033) | 1.810860 / 1.452155 (0.358705) | 1.896775 / 1.492716 (0.404059) |\n\n### Benchmark: benchmark_getitem\\_100B.json\n\n| metric | get_batch_of\\_1024\\_random_rows | get_batch_of\\_1024\\_rows | get_first_row | get_last_row |\n|--------|---|---|---|---|\n| new / old (diff) | 0.261887 / 0.018006 (0.243880) | 0.489919 / 0.000490 (0.489430) | 0.006117 / 0.000200 (0.005917) | 0.000134 / 0.000054 (0.000079) |\n\n### Benchmark: benchmark_indices_mapping.json\n\n| metric | select | shard | shuffle | sort | train_test_split |\n|--------|---|---|---|---|---|\n| new / old (diff) | 0.035033 / 0.037411 (-0.002378) | 0.141093 / 0.014526 (0.126567) | 0.152613 / 0.176557 (-0.023943) | 0.218351 / 0.737135 (-0.518785) | 0.158366 / 0.296338 (-0.137972) |\n\n### Benchmark: benchmark_iterating.json\n\n| metric | read 5000 | read 50000 | read_batch 50000 10 | read_batch 50000 100 | read_batch 50000 1000 | read_formatted numpy 5000 | read_formatted pandas 5000 | read_formatted tensorflow 5000 | read_formatted torch 5000 | read_formatted_batch numpy 5000 10 | read_formatted_batch numpy 5000 1000 | shuffled read 5000 | shuffled read 50000 | shuffled read_batch 50000 10 | shuffled read_batch 50000 100 | shuffled read_batch 50000 1000 | shuffled read_formatted numpy 5000 | shuffled read_formatted_batch numpy 5000 10 | shuffled read_formatted_batch numpy 5000 1000 |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.542219 / 0.215209 (0.327010) | 5.479358 / 2.077655 (3.401703) | 2.749586 / 1.504120 (1.245466) | 2.537686 / 1.541195 (0.996491) | 2.582351 / 1.468490 (1.113861) | 0.636750 / 4.584777 (-3.948027) | 4.537501 / 3.745712 (0.791789) | 2.141392 / 5.269862 (-3.128469) | 1.279711 / 4.565676 (-3.285965) | 0.079227 / 0.424275 (-0.345048) | 0.014141 / 0.007607 (0.006534) | 0.662070 / 0.226044 (0.436025) | 6.572144 / 2.268929 (4.303215) | 3.321349 / 55.444624 (-52.123275) | 2.928219 / 6.876477 (-3.948258) | 3.002732 / 2.142072 (0.860659) | 0.773808 / 4.805227 (-4.031419) | 0.166017 / 6.500664 (-6.334647) | 0.076424 / 0.075469 (0.000955) |\n\n### Benchmark: benchmark_map_filter.json\n\n| metric | filter | map fast-tokenizer batched | map identity | map identity batched | map no-op batched | map no-op batched numpy | map no-op batched pandas | map no-op batched pytorch | map no-op batched tensorflow |\n|--------|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 1.584325 / 1.841788 (-0.257463) | 18.359247 / 8.074308 (10.284938) | 16.977875 / 10.191392 (6.786483) | 0.195381 / 0.680424 (-0.485043) | 0.021048 / 0.534201 (-0.513153) | 0.512237 / 0.579283 (-0.067047) | 0.511435 / 0.434364 (0.077071) | 0.592856 / 0.540337 (0.052518) | 0.711905 / 1.386936 (-0.675031) |\n\n</details>\n</details>\n\n![](https://cml.dev/watermark.png#d536e37b21a6dd5c122b6d8113994ec50846c5b5 "CML watermark")\n', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1591224238/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}]

[{'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1584311735', 'html_url': 'https://github.com/huggingface/datasets/pull/5937#issuecomment-1584311735', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5937', 'id': 1584311735, 'node_id': 'IC_kwDODunzps5ebq23', 'user': {'login': 'HuggingFaceDocBuilderDev', 'id': 99929124, 'node_id': 'U_kgDOBfTMJA', 'avatar_url': 'https://avatars.githubusercontent.com/u/99929124?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/HuggingFaceDocBuilderDev', 'html_url': 'https://github.com/HuggingFaceDocBuilderDev', 'followers_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/followers', 'following_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/following{/other_user}', 'gists_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/subscriptions', 'organizations_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/orgs', 'repos_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/repos', 'events_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/events{/privacy}', 'received_events_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-09T10:02:26Z', 'updated_at': '2023-06-14T12:24:26Z', 'author_association': 'NONE', 'body': '_The documentation is not available anymore as the PR was closed or merged._', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1584311735/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1591101762', 'html_url': 'https://github.com/huggingface/datasets/pull/5937#issuecomment-1591101762', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5937', 'id': 1591101762, 'node_id': 'IC_kwDODunzps5e1klC', 'user': {'login': 'github-actions[bot]', 'id': 41898282, 'node_id': 'MDM6Qm90NDE4OTgyODI=', 'avatar_url': 'https://avatars.githubusercontent.com/in/15368?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/github-actions%5Bbot%5D', 'html_url': 'https://github.com/apps/github-actions', 'followers_url': 'https://api.github.com/users/github-actions%5Bbot%5D/followers', 'following_url': 'https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}', 'gists_url': 'https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/github-actions%5Bbot%5D/subscriptions', 'organizations_url': 'https://api.github.com/users/github-actions%5Bbot%5D/orgs', 'repos_url': 'https://api.github.com/users/github-actions%5Bbot%5D/repos', 'events_url': 'https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}', 'received_events_url': 'https://api.github.com/users/github-actions%5Bbot%5D/received_events', 'type': 'Bot', 'site_admin': False}, 'created_at': '2023-06-14T12:30:58Z', 'updated_at': '2023-06-14T12:30:58Z', 'author_association': 'NONE', 'body': '<details>\n<summary>Show benchmarks</summary>\n\nPyArrow==8.0.0\n\n<details>\n<summary>Show updated benchmarks!</summary>\n\n### Benchmark: benchmark_array_xd.json\n\n| metric | read_batch_formatted_as_numpy after write_array2d | read_batch_formatted_as_numpy after write_flattened_sequence | read_batch_formatted_as_numpy after write_nested_sequence | read_batch_unformated after write_array2d | read_batch_unformated after write_flattened_sequence | read_batch_unformated after write_nested_sequence | read_col_formatted_as_numpy after write_array2d | read_col_formatted_as_numpy after write_flattened_sequence | read_col_formatted_as_numpy after write_nested_sequence | read_col_unformated after write_array2d | read_col_unformated after write_flattened_sequence | read_col_unformated after write_nested_sequence | read_formatted_as_numpy after write_array2d | read_formatted_as_numpy after write_flattened_sequence | read_formatted_as_numpy after write_nested_sequence | read_unformated after write_array2d | read_unformated after write_flattened_sequence | read_unformated after write_nested_sequence | write_array2d | write_flattened_sequence | write_nested_sequence |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.006157 / 0.011353 (-0.005196) | 0.003790 / 0.011008 (-0.007219) | 0.097889 / 0.038508 (0.059381) | 0.029038 / 0.023109 (0.005929) | 0.306918 / 0.275898 (0.031020) | 0.339637 / 0.323480 (0.016157) | 0.003526 / 0.007986 (-0.004460) | 0.003102 / 0.004328 (-0.001227) | 0.076908 / 0.004250 (0.072658) | 0.039254 / 0.037052 (0.002201) | 0.309197 / 0.258489 (0.050708) | 0.345635 / 0.293841 (0.051794) | 0.027954 / 0.128546 (-0.100593) | 0.008510 / 0.075646 (-0.067136) | 0.314674 / 0.419271 (-0.104598) | 0.057102 / 0.043533 (0.013569) | 0.307495 / 0.255139 (0.052356) | 0.329501 / 0.283200 (0.046302) | 0.098450 / 0.141683 (-0.043233) | 1.480102 / 1.452155 (0.027948) | 1.550554 / 1.492716 (0.057838) |\n\n### Benchmark: benchmark_getitem\\_100B.json\n\n| metric | get_batch_of\\_1024\\_random_rows | get_batch_of\\_1024\\_rows | get_first_row | get_last_row |\n|--------|---|---|---|---|\n| new / old (diff) | 0.207440 / 0.018006 (0.189434) | 0.426560 / 0.000490 (0.426071) | 0.003250 / 0.000200 (0.003050) | 0.000074 / 0.000054 (0.000019) |\n\n### Benchmark: benchmark_indices_mapping.json\n\n| metric | select | shard | shuffle | sort | train_test_split |\n|--------|---|---|---|---|---|\n| new / old (diff) | 0.023777 / 0.037411 (-0.013634) | 0.103905 / 0.014526 (0.089379) | 0.108324 / 0.176557 (-0.068233) | 0.167223 / 0.737135 (-0.569913) | 0.113529 / 0.296338 (-0.182810) |\n\n### Benchmark: benchmark_iterating.json\n\n| metric | read 5000 | read 50000 | read_batch 50000 10 | read_batch 50000 100 | read_batch 50000 1000 | read_formatted numpy 5000 | read_formatted pandas 5000 | read_formatted tensorflow 5000 | read_formatted torch 5000 | read_formatted_batch numpy 5000 10 | read_formatted_batch numpy 5000 1000 | shuffled read 5000 | shuffled read 50000 | shuffled read_batch 50000 10 | shuffled read_batch 50000 100 | shuffled read_batch 50000 1000 | shuffled read_formatted numpy 5000 | shuffled read_formatted_batch numpy 5000 10 | shuffled read_formatted_batch numpy 5000 1000 |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.426770 / 0.215209 (0.211561) | 4.251806 / 2.077655 (2.174151) | 2.010426 / 1.504120 (0.506306) | 1.858630 / 1.541195 (0.317435) | 1.941318 / 1.468490 (0.472828) | 0.558056 / 4.584777 (-4.026721) | 3.399107 / 3.745712 (-0.346606) | 1.758386 / 5.269862 (-3.511476) | 1.036305 / 4.565676 (-3.529372) | 0.067094 / 0.424275 (-0.357182) | 0.011167 / 0.007607 (0.003560) | 0.526705 / 0.226044 (0.300661) | 5.250319 / 2.268929 (2.981390) | 2.496723 / 55.444624 (-52.947902) | 2.154013 / 6.876477 (-4.722464) | 2.394724 / 2.142072 (0.252652) | 0.669723 / 4.805227 (-4.135504) | 0.136367 / 6.500664 (-6.364297) | 0.067080 / 0.075469 (-0.008389) |\n\n### Benchmark: benchmark_map_filter.json\n\n| metric | filter | map fast-tokenizer batched | map identity | map identity batched | map no-op batched | map no-op batched numpy | map no-op batched pandas | map no-op batched pytorch | map no-op batched tensorflow |\n|--------|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 1.269700 / 1.841788 (-0.572088) | 14.099775 / 8.074308 (6.025467) | 14.422936 / 10.191392 (4.231544) | 0.132344 / 0.680424 (-0.548080) | 0.016744 / 0.534201 (-0.517457) | 0.378286 / 0.579283 (-0.200997) | 0.392282 / 0.434364 (-0.042082) | 0.437648 / 0.540337 (-0.102689) | 0.528554 / 1.386936 (-0.858382) |\n\n</details>\nPyArrow==latest\n\n<details>\n<summary>Show updated benchmarks!</summary>\n\n### Benchmark: benchmark_array_xd.json\n\n| metric | read_batch_formatted_as_numpy after write_array2d | read_batch_formatted_as_numpy after write_flattened_sequence | read_batch_formatted_as_numpy after write_nested_sequence | read_batch_unformated after write_array2d | read_batch_unformated after write_flattened_sequence | read_batch_unformated after write_nested_sequence | read_col_formatted_as_numpy after write_array2d | read_col_formatted_as_numpy after write_flattened_sequence | read_col_formatted_as_numpy after write_nested_sequence | read_col_unformated after write_array2d | read_col_unformated after write_flattened_sequence | read_col_unformated after write_nested_sequence | read_formatted_as_numpy after write_array2d | read_formatted_as_numpy after write_flattened_sequence | read_formatted_as_numpy after write_nested_sequence | read_unformated after write_array2d | read_unformated after write_flattened_sequence | read_unformated after write_nested_sequence | write_array2d | write_flattened_sequence | write_nested_sequence |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.006086 / 0.011353 (-0.005267) | 0.003769 / 0.011008 (-0.007239) | 0.077414 / 0.038508 (0.038906) | 0.027806 / 0.023109 (0.004697) | 0.360333 / 0.275898 (0.084434) | 0.404725 / 0.323480 (0.081245) | 0.003443 / 0.007986 (-0.004543) | 0.004434 / 0.004328 (0.000106) | 0.077309 / 0.004250 (0.073059) | 0.040441 / 0.037052 (0.003388) | 0.358627 / 0.258489 (0.100138) | 0.415246 / 0.293841 (0.121405) | 0.027718 / 0.128546 (-0.100829) | 0.008495 / 0.075646 (-0.067151) | 0.082874 / 0.419271 (-0.336397) | 0.042323 / 0.043533 (-0.001210) | 0.354895 / 0.255139 (0.099756) | 0.390032 / 0.283200 (0.106832) | 0.092377 / 0.141683 (-0.049306) | 1.492817 / 1.452155 (0.040662) | 1.551859 / 1.492716 (0.059143) |\n\n### Benchmark: benchmark_getitem\\_100B.json\n\n| metric | get_batch_of\\_1024\\_random_rows | get_batch_of\\_1024\\_rows | get_first_row | get_last_row |\n|--------|---|---|---|---|\n| new / old (diff) | 0.198921 / 0.018006 (0.180915) | 0.417699 / 0.000490 (0.417209) | 0.001349 / 0.000200 (0.001149) | 0.000071 / 0.000054 (0.000016) |\n\n### Benchmark: benchmark_indices_mapping.json\n\n| metric | select | shard | shuffle | sort | train_test_split |\n|--------|---|---|---|---|---|\n| new / old (diff) | 0.026349 / 0.037411 (-0.011062) | 0.105712 / 0.014526 (0.091186) | 0.111792 / 0.176557 (-0.064765) | 0.163677 / 0.737135 (-0.573459) | 0.116864 / 0.296338 (-0.179474) |\n\n### Benchmark: benchmark_iterating.json\n\n| metric | read 5000 | read 50000 | read_batch 50000 10 | read_batch 50000 100 | read_batch 50000 1000 | read_formatted numpy 5000 | read_formatted pandas 5000 | read_formatted tensorflow 5000 | read_formatted torch 5000 | read_formatted_batch numpy 5000 10 | read_formatted_batch numpy 5000 1000 | shuffled read 5000 | shuffled read 50000 | shuffled read_batch 50000 10 | shuffled read_batch 50000 100 | shuffled read_batch 50000 1000 | shuffled read_formatted numpy 5000 | shuffled read_formatted_batch numpy 5000 10 | shuffled read_formatted_batch numpy 5000 1000 |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.447532 / 0.215209 (0.232323) | 4.468770 / 2.077655 (2.391116) | 2.403820 / 1.504120 (0.899700) | 2.273640 / 1.541195 (0.732445) | 2.337505 / 1.468490 (0.869015) | 0.560729 / 4.584777 (-4.024048) | 3.389165 / 3.745712 (-0.356547) | 2.697614 / 5.269862 (-2.572247) | 1.351909 / 4.565676 (-3.213768) | 0.068089 / 0.424275 (-0.356186) | 0.011639 / 0.007607 (0.004032) | 0.555277 / 0.226044 (0.329233) | 5.559291 / 2.268929 (3.290363) | 2.657609 / 55.444624 (-52.787015) | 2.346667 / 6.876477 (-4.529809) | 2.615823 / 2.142072 (0.473751) | 0.668662 / 4.805227 (-4.136566) | 0.136593 / 6.500664 (-6.364071) | 0.068384 / 0.075469 (-0.007085) |\n\n### Benchmark: benchmark_map_filter.json\n\n| metric | filter | map fast-tokenizer batched | map identity | map identity batched | map no-op batched | map no-op batched numpy | map no-op batched pandas | map no-op batched pytorch | map no-op batched tensorflow |\n|--------|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 1.312089 / 1.841788 (-0.529699) | 14.477510 / 8.074308 (6.403202) | 14.231432 / 10.191392 (4.040040) | 0.132015 / 0.680424 (-0.548409) | 0.016908 / 0.534201 (-0.517293) | 0.368315 / 0.579283 (-0.210968) | 0.397964 / 0.434364 (-0.036400) | 0.432446 / 0.540337 (-0.107891) | 0.526349 / 1.386936 (-0.860587) |\n\n</details>\n</details>\n\n![](https://cml.dev/watermark.png#78b4d55c3cfc60e309eb033d3ed0aba5e796b6ce "CML watermark")\n', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1591101762/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}]

[{'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1584156198', 'html_url': 'https://github.com/huggingface/datasets/issues/5936#issuecomment-1584156198', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5936', 'id': 1584156198, 'node_id': 'IC_kwDODunzps5ebE4m', 'user': {'login': 'qgallouedec', 'id': 45557362, 'node_id': 'MDQ6VXNlcjQ1NTU3MzYy', 'avatar_url': 'https://avatars.githubusercontent.com/u/45557362?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/qgallouedec', 'html_url': 'https://github.com/qgallouedec', 'followers_url': 'https://api.github.com/users/qgallouedec/followers', 'following_url': 'https://api.github.com/users/qgallouedec/following{/other_user}', 'gists_url': 'https://api.github.com/users/qgallouedec/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/qgallouedec/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/qgallouedec/subscriptions', 'organizations_url': 'https://api.github.com/users/qgallouedec/orgs', 'repos_url': 'https://api.github.com/users/qgallouedec/repos', 'events_url': 'https://api.github.com/users/qgallouedec/events{/privacy}', 'received_events_url': 'https://api.github.com/users/qgallouedec/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-09T08:09:50Z', 'updated_at': '2023-06-09T08:10:03Z', 'author_association': 'CONTRIBUTOR', 'body': 'Related, `float16` is the only dtype not supported by `Array2D` (probably by every `ArrayND`):\r\n\r\n```python\r\nfrom datasets import Array2D, Features, Dataset\r\n\r\nimport numpy as np\r\n\r\nfor dtype in [\r\n    "bool",  # ok\r\n    "int8",  # ok\r\n    "int16",  # ok\r\n    "int32",  # ok\r\n    "int64",  # ok\r\n    "uint8",  # ok\r\n    "uint16",  # ok\r\n    "uint32",  # ok\r\n    "uint64",  # ok\r\n    "float16",  # failed\r\n    "float32",  # ok\r\n    "float64",  # ok\r\n]:\r\n    features = Features({"foo": Array2D(dtype=dtype, shape=(3, 4))})\r\n    array = np.zeros((3, 4), dtype=dtype)\r\n    try:\r\n        dataset = Dataset.from_dict({"foo": [array]}, features=features)\r\n    except Exception as e:\r\n        print(f"Failed for dtype={dtype}")\r\n```', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1584156198/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1584301900', 'html_url': 'https://github.com/huggingface/datasets/issues/5936#issuecomment-1584301900', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5936', 'id': 1584301900, 'node_id': 'IC_kwDODunzps5ebodM', 'user': {'login': 'qgallouedec', 'id': 45557362, 'node_id': 'MDQ6VXNlcjQ1NTU3MzYy', 'avatar_url': 'https://avatars.githubusercontent.com/u/45557362?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/qgallouedec', 'html_url': 'https://github.com/qgallouedec', 'followers_url': 'https://api.github.com/users/qgallouedec/followers', 'following_url': 'https://api.github.com/users/qgallouedec/following{/other_user}', 'gists_url': 'https://api.github.com/users/qgallouedec/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/qgallouedec/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/qgallouedec/subscriptions', 'organizations_url': 'https://api.github.com/users/qgallouedec/orgs', 'repos_url': 'https://api.github.com/users/qgallouedec/repos', 'events_url': 'https://api.github.com/users/qgallouedec/events{/privacy}', 'received_events_url': 'https://api.github.com/users/qgallouedec/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-09T09:55:41Z', 'updated_at': '2023-06-09T11:05:02Z', 'author_association': 'CONTRIBUTOR', 'body': "Here's something I can't explain:\r\n\r\nWhen an array is encoded in the `from_dict` method, the numpy array is converted to a list (thus losing the original dtype, which is transfromed to the nearest builtin Python type)\r\n\r\nhttps://github.com/huggingface/datasets/blob/6ee61e6e695b1df9f232d47faf3a5e2b30b33737/src/datasets/features/features.py#L524-L525\r\n\r\nHowever, later on, this same data is written to memory, and it seems authorized that the data is an array (or in this case, a list of arrays). \r\n\r\nhttps://github.com/huggingface/datasets/blob/6ee61e6e695b1df9f232d47faf3a5e2b30b33737/src/datasets/arrow_writer.py#L185-L186\r\n\r\nSo the question is: why convert it to a Python list? This seems to be quite expensive both in terms of write time (all data is copied) and memory (e.g., an int8 is converted to an int64).\r\n\r\nFinally, if I try to remove this step, it solves all the previous problems, and it seems to me that it doesn't break anything (the CI passes without problem).", 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1584301900/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1588898420', 'html_url': 'https://github.com/huggingface/datasets/issues/5936#issuecomment-1588898420', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5936', 'id': 1588898420, 'node_id': 'IC_kwDODunzps5etKp0', 'user': {'login': 'lhoestq', 'id': 42851186, 'node_id': 'MDQ6VXNlcjQyODUxMTg2', 'avatar_url': 'https://avatars.githubusercontent.com/u/42851186?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/lhoestq', 'html_url': 'https://github.com/lhoestq', 'followers_url': 'https://api.github.com/users/lhoestq/followers', 'following_url': 'https://api.github.com/users/lhoestq/following{/other_user}', 'gists_url': 'https://api.github.com/users/lhoestq/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/lhoestq/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/lhoestq/subscriptions', 'organizations_url': 'https://api.github.com/users/lhoestq/orgs', 'repos_url': 'https://api.github.com/users/lhoestq/repos', 'events_url': 'https://api.github.com/users/lhoestq/events{/privacy}', 'received_events_url': 'https://api.github.com/users/lhoestq/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-13T09:23:38Z', 'updated_at': '2023-06-13T09:23:38Z', 'author_association': 'MEMBER', 'body': "Arrow only support 1d numpy arrays, so we convert multidim arrays to lists of 1s arrays (and keep the dtype).\r\n\r\nThough you noticed that it's concerting to lists and lose the dtype. If it's the case then it's a bug.", 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1588898420/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1588901420', 'html_url': 'https://github.com/huggingface/datasets/issues/5936#issuecomment-1588901420', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5936', 'id': 1588901420, 'node_id': 'IC_kwDODunzps5etLYs', 'user': {'login': 'lhoestq', 'id': 42851186, 'node_id': 'MDQ6VXNlcjQyODUxMTg2', 'avatar_url': 'https://avatars.githubusercontent.com/u/42851186?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/lhoestq', 'html_url': 'https://github.com/lhoestq', 'followers_url': 'https://api.github.com/users/lhoestq/followers', 'following_url': 'https://api.github.com/users/lhoestq/following{/other_user}', 'gists_url': 'https://api.github.com/users/lhoestq/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/lhoestq/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/lhoestq/subscriptions', 'organizations_url': 'https://api.github.com/users/lhoestq/orgs', 'repos_url': 'https://api.github.com/users/lhoestq/repos', 'events_url': 'https://api.github.com/users/lhoestq/events{/privacy}', 'received_events_url': 'https://api.github.com/users/lhoestq/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-13T09:25:34Z', 'updated_at': '2023-06-13T09:25:34Z', 'author_association': 'MEMBER', 'body': "Ok the conversion to list shouldn't be there indeed ! Could you open a PR to remove it ?", 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1588901420/reactions', 'total_count': 1, '+1': 1, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}]

[{'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1582771831', 'html_url': 'https://github.com/huggingface/datasets/pull/5935#issuecomment-1582771831', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5935', 'id': 1582771831, 'node_id': 'IC_kwDODunzps5eVy53', 'user': {'login': 'github-actions[bot]', 'id': 41898282, 'node_id': 'MDM6Qm90NDE4OTgyODI=', 'avatar_url': 'https://avatars.githubusercontent.com/in/15368?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/github-actions%5Bbot%5D', 'html_url': 'https://github.com/apps/github-actions', 'followers_url': 'https://api.github.com/users/github-actions%5Bbot%5D/followers', 'following_url': 'https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}', 'gists_url': 'https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/github-actions%5Bbot%5D/subscriptions', 'organizations_url': 'https://api.github.com/users/github-actions%5Bbot%5D/orgs', 'repos_url': 'https://api.github.com/users/github-actions%5Bbot%5D/repos', 'events_url': 'https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}', 'received_events_url': 'https://api.github.com/users/github-actions%5Bbot%5D/received_events', 'type': 'Bot', 'site_admin': False}, 'created_at': '2023-06-08T15:08:20Z', 'updated_at': '2023-06-08T15:08:20Z', 'author_association': 'NONE', 'body': '<details>\n<summary>Show benchmarks</summary>\n\nPyArrow==8.0.0\n\n<details>\n<summary>Show updated benchmarks!</summary>\n\n### Benchmark: benchmark_array_xd.json\n\n| metric | read_batch_formatted_as_numpy after write_array2d | read_batch_formatted_as_numpy after write_flattened_sequence | read_batch_formatted_as_numpy after write_nested_sequence | read_batch_unformated after write_array2d | read_batch_unformated after write_flattened_sequence | read_batch_unformated after write_nested_sequence | read_col_formatted_as_numpy after write_array2d | read_col_formatted_as_numpy after write_flattened_sequence | read_col_formatted_as_numpy after write_nested_sequence | read_col_unformated after write_array2d | read_col_unformated after write_flattened_sequence | read_col_unformated after write_nested_sequence | read_formatted_as_numpy after write_array2d | read_formatted_as_numpy after write_flattened_sequence | read_formatted_as_numpy after write_nested_sequence | read_unformated after write_array2d | read_unformated after write_flattened_sequence | read_unformated after write_nested_sequence | write_array2d | write_flattened_sequence | write_nested_sequence |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.007489 / 0.011353 (-0.003864) | 0.004914 / 0.011008 (-0.006095) | 0.111626 / 0.038508 (0.073117) | 0.037920 / 0.023109 (0.014811) | 0.350571 / 0.275898 (0.074673) | 0.389667 / 0.323480 (0.066187) | 0.006309 / 0.007986 (-0.001676) | 0.005488 / 0.004328 (0.001160) | 0.083962 / 0.004250 (0.079712) | 0.050728 / 0.037052 (0.013675) | 0.360997 / 0.258489 (0.102508) | 0.392736 / 0.293841 (0.098895) | 0.031975 / 0.128546 (-0.096571) | 0.009941 / 0.075646 (-0.065705) | 0.379840 / 0.419271 (-0.039432) | 0.056522 / 0.043533 (0.012989) | 0.359379 / 0.255139 (0.104240) | 0.384487 / 0.283200 (0.101287) | 0.117523 / 0.141683 (-0.024160) | 1.683639 / 1.452155 (0.231485) | 1.791645 / 1.492716 (0.298929) |\n\n### Benchmark: benchmark_getitem\\_100B.json\n\n| metric | get_batch_of\\_1024\\_random_rows | get_batch_of\\_1024\\_rows | get_first_row | get_last_row |\n|--------|---|---|---|---|\n| new / old (diff) | 0.236862 / 0.018006 (0.218856) | 0.481208 / 0.000490 (0.480719) | 0.007455 / 0.000200 (0.007255) | 0.000111 / 0.000054 (0.000057) |\n\n### Benchmark: benchmark_indices_mapping.json\n\n| metric | select | shard | shuffle | sort | train_test_split |\n|--------|---|---|---|---|---|\n| new / old (diff) | 0.030854 / 0.037411 (-0.006557) | 0.126892 / 0.014526 (0.112367) | 0.139207 / 0.176557 (-0.037350) | 0.206447 / 0.737135 (-0.530689) | 0.143095 / 0.296338 (-0.153244) |\n\n### Benchmark: benchmark_iterating.json\n\n| metric | read 5000 | read 50000 | read_batch 50000 10 | read_batch 50000 100 | read_batch 50000 1000 | read_formatted numpy 5000 | read_formatted pandas 5000 | read_formatted tensorflow 5000 | read_formatted torch 5000 | read_formatted_batch numpy 5000 10 | read_formatted_batch numpy 5000 1000 | shuffled read 5000 | shuffled read 50000 | shuffled read_batch 50000 10 | shuffled read_batch 50000 100 | shuffled read_batch 50000 1000 | shuffled read_formatted numpy 5000 | shuffled read_formatted_batch numpy 5000 10 | shuffled read_formatted_batch numpy 5000 1000 |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.474677 / 0.215209 (0.259468) | 4.699534 / 2.077655 (2.621879) | 2.152102 / 1.504120 (0.647983) | 1.934815 / 1.541195 (0.393620) | 1.986448 / 1.468490 (0.517958) | 0.607184 / 4.584777 (-3.977593) | 4.480385 / 3.745712 (0.734673) | 2.074729 / 5.269862 (-3.195132) | 1.182383 / 4.565676 (-3.383294) | 0.075624 / 0.424275 (-0.348651) | 0.014046 / 0.007607 (0.006439) | 0.598859 / 0.226044 (0.372814) | 5.959551 / 2.268929 (3.690622) | 2.700851 / 55.444624 (-52.743773) | 2.303775 / 6.876477 (-4.572702) | 2.456441 / 2.142072 (0.314369) | 0.747185 / 4.805227 (-4.058042) | 0.165787 / 6.500664 (-6.334878) | 0.075817 / 0.075469 (0.000348) |\n\n### Benchmark: benchmark_map_filter.json\n\n| metric | filter | map fast-tokenizer batched | map identity | map identity batched | map no-op batched | map no-op batched numpy | map no-op batched pandas | map no-op batched pytorch | map no-op batched tensorflow |\n|--------|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 1.411859 / 1.841788 (-0.429928) | 17.375495 / 8.074308 (9.301187) | 15.187098 / 10.191392 (4.995706) | 0.169953 / 0.680424 (-0.510471) | 0.020204 / 0.534201 (-0.513997) | 0.461424 / 0.579283 (-0.117859) | 0.494443 / 0.434364 (0.060080) | 0.544583 / 0.540337 (0.004246) | 0.648231 / 1.386936 (-0.738705) |\n\n</details>\nPyArrow==latest\n\n<details>\n<summary>Show updated benchmarks!</summary>\n\n### Benchmark: benchmark_array_xd.json\n\n| metric | read_batch_formatted_as_numpy after write_array2d | read_batch_formatted_as_numpy after write_flattened_sequence | read_batch_formatted_as_numpy after write_nested_sequence | read_batch_unformated after write_array2d | read_batch_unformated after write_flattened_sequence | read_batch_unformated after write_nested_sequence | read_col_formatted_as_numpy after write_array2d | read_col_formatted_as_numpy after write_flattened_sequence | read_col_formatted_as_numpy after write_nested_sequence | read_col_unformated after write_array2d | read_col_unformated after write_flattened_sequence | read_col_unformated after write_nested_sequence | read_formatted_as_numpy after write_array2d | read_formatted_as_numpy after write_flattened_sequence | read_formatted_as_numpy after write_nested_sequence | read_unformated after write_array2d | read_unformated after write_flattened_sequence | read_unformated after write_nested_sequence | write_array2d | write_flattened_sequence | write_nested_sequence |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.007785 / 0.011353 (-0.003568) | 0.005314 / 0.011008 (-0.005694) | 0.087273 / 0.038508 (0.048765) | 0.037810 / 0.023109 (0.014701) | 0.425473 / 0.275898 (0.149575) | 0.459976 / 0.323480 (0.136497) | 0.007270 / 0.007986 (-0.000716) | 0.004631 / 0.004328 (0.000303) | 0.087063 / 0.004250 (0.082812) | 0.052630 / 0.037052 (0.015578) | 0.432384 / 0.258489 (0.173895) | 0.500291 / 0.293841 (0.206450) | 0.033144 / 0.128546 (-0.095402) | 0.010101 / 0.075646 (-0.065545) | 0.096068 / 0.419271 (-0.323204) | 0.062750 / 0.043533 (0.019217) | 0.419308 / 0.255139 (0.164169) | 0.437099 / 0.283200 (0.153900) | 0.122289 / 0.141683 (-0.019394) | 1.737829 / 1.452155 (0.285674) | 1.851481 / 1.492716 (0.358765) |\n\n### Benchmark: benchmark_getitem\\_100B.json\n\n| metric | get_batch_of\\_1024\\_random_rows | get_batch_of\\_1024\\_rows | get_first_row | get_last_row |\n|--------|---|---|---|---|\n| new / old (diff) | 0.014277 / 0.018006 (-0.003729) | 0.489835 / 0.000490 (0.489345) | 0.008423 / 0.000200 (0.008223) | 0.000188 / 0.000054 (0.000134) |\n\n### Benchmark: benchmark_indices_mapping.json\n\n| metric | select | shard | shuffle | sort | train_test_split |\n|--------|---|---|---|---|---|\n| new / old (diff) | 0.032966 / 0.037411 (-0.004445) | 0.130069 / 0.014526 (0.115544) | 0.144372 / 0.176557 (-0.032185) | 0.200400 / 0.737135 (-0.536735) | 0.149384 / 0.296338 (-0.146954) |\n\n### Benchmark: benchmark_iterating.json\n\n| metric | read 5000 | read 50000 | read_batch 50000 10 | read_batch 50000 100 | read_batch 50000 1000 | read_formatted numpy 5000 | read_formatted pandas 5000 | read_formatted tensorflow 5000 | read_formatted torch 5000 | read_formatted_batch numpy 5000 10 | read_formatted_batch numpy 5000 1000 | shuffled read 5000 | shuffled read 50000 | shuffled read_batch 50000 10 | shuffled read_batch 50000 100 | shuffled read_batch 50000 1000 | shuffled read_formatted numpy 5000 | shuffled read_formatted_batch numpy 5000 10 | shuffled read_formatted_batch numpy 5000 1000 |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.511542 / 0.215209 (0.296333) | 5.093879 / 2.077655 (3.016225) | 2.572088 / 1.504120 (1.067968) | 2.339118 / 1.541195 (0.797923) | 2.441637 / 1.468490 (0.973147) | 0.614818 / 4.584777 (-3.969959) | 4.724441 / 3.745712 (0.978729) | 5.431978 / 5.269862 (0.162116) | 2.257794 / 4.565676 (-2.307883) | 0.078109 / 0.424275 (-0.346166) | 0.013821 / 0.007607 (0.006214) | 0.639232 / 0.226044 (0.413188) | 6.424623 / 2.268929 (4.155694) | 3.163018 / 55.444624 (-52.281606) | 2.756786 / 6.876477 (-4.119690) | 2.808655 / 2.142072 (0.666583) | 0.745843 / 4.805227 (-4.059385) | 0.165562 / 6.500664 (-6.335102) | 0.076610 / 0.075469 (0.001141) |\n\n### Benchmark: benchmark_map_filter.json\n\n| metric | filter | map fast-tokenizer batched | map identity | map identity batched | map no-op batched | map no-op batched numpy | map no-op batched pandas | map no-op batched pytorch | map no-op batched tensorflow |\n|--------|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 1.738630 / 1.841788 (-0.103158) | 18.073573 / 8.074308 (9.999265) | 16.482820 / 10.191392 (6.291428) | 0.213233 / 0.680424 (-0.467191) | 0.022839 / 0.534201 (-0.511362) | 0.487043 / 0.579283 (-0.092240) | 0.512518 / 0.434364 (0.078154) | 0.549365 / 0.540337 (0.009028) | 0.656612 / 1.386936 (-0.730324) |\n\n</details>\n</details>\n\n![](https://cml.dev/watermark.png#288e92b03bd4ec91c10c8a529b32631cfaba9fb7 "CML watermark")\n', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1582771831/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1582772683', 'html_url': 'https://github.com/huggingface/datasets/pull/5935#issuecomment-1582772683', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5935', 'id': 1582772683, 'node_id': 'IC_kwDODunzps5eVzHL', 'user': {'login': 'severo', 'id': 1676121, 'node_id': 'MDQ6VXNlcjE2NzYxMjE=', 'avatar_url': 'https://avatars.githubusercontent.com/u/1676121?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/severo', 'html_url': 'https://github.com/severo', 'followers_url': 'https://api.github.com/users/severo/followers', 'following_url': 'https://api.github.com/users/severo/following{/other_user}', 'gists_url': 'https://api.github.com/users/severo/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/severo/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/severo/subscriptions', 'organizations_url': 'https://api.github.com/users/severo/orgs', 'repos_url': 'https://api.github.com/users/severo/repos', 'events_url': 'https://api.github.com/users/severo/events{/privacy}', 'received_events_url': 'https://api.github.com/users/severo/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-08T15:08:44Z', 'updated_at': '2023-06-08T15:08:44Z', 'author_association': 'CONTRIBUTOR', 'body': 'Good idea!\r\n\r\nI was wondering: if we want to optimize the balance between the size of downloading a row group, and the number of rows in the group, would it make sense to compute the row group size by checking the average size of the rows?\r\n\r\neg. 32x32 images could have a larger row group size than full HD images, no? Relying on the size would even remove the need to check the column types.\r\n\r\n(in this proposal, we could use the computed row group size, eg 837, or use the nearest row group size in a list of values: 10, 100, 1000, 10000)', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1582772683/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1582796509', 'html_url': 'https://github.com/huggingface/datasets/pull/5935#issuecomment-1582796509', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5935', 'id': 1582796509, 'node_id': 'IC_kwDODunzps5eV47d', 'user': {'login': 'lhoestq', 'id': 42851186, 'node_id': 'MDQ6VXNlcjQyODUxMTg2', 'avatar_url': 'https://avatars.githubusercontent.com/u/42851186?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/lhoestq', 'html_url': 'https://github.com/lhoestq', 'followers_url': 'https://api.github.com/users/lhoestq/followers', 'following_url': 'https://api.github.com/users/lhoestq/following{/other_user}', 'gists_url': 'https://api.github.com/users/lhoestq/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/lhoestq/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/lhoestq/subscriptions', 'organizations_url': 'https://api.github.com/users/lhoestq/orgs', 'repos_url': 'https://api.github.com/users/lhoestq/repos', 'events_url': 'https://api.github.com/users/lhoestq/events{/privacy}', 'received_events_url': 'https://api.github.com/users/lhoestq/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-08T15:18:00Z', 'updated_at': '2023-06-08T15:18:00Z', 'author_association': 'MEMBER', 'body': 'Probably, but I would go for a simpler solution first :p', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1582796509/reactions', 'total_count': 1, '+1': 1, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1582820421', 'html_url': 'https://github.com/huggingface/datasets/pull/5935#issuecomment-1582820421', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5935', 'id': 1582820421, 'node_id': 'IC_kwDODunzps5eV-xF', 'user': {'login': 'severo', 'id': 1676121, 'node_id': 'MDQ6VXNlcjE2NzYxMjE=', 'avatar_url': 'https://avatars.githubusercontent.com/u/1676121?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/severo', 'html_url': 'https://github.com/severo', 'followers_url': 'https://api.github.com/users/severo/followers', 'following_url': 'https://api.github.com/users/severo/following{/other_user}', 'gists_url': 'https://api.github.com/users/severo/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/severo/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/severo/subscriptions', 'organizations_url': 'https://api.github.com/users/severo/orgs', 'repos_url': 'https://api.github.com/users/severo/repos', 'events_url': 'https://api.github.com/users/severo/events{/privacy}', 'received_events_url': 'https://api.github.com/users/severo/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-08T15:26:54Z', 'updated_at': '2023-06-08T15:27:05Z', 'author_association': 'CONTRIBUTOR', 'body': "Sure! I wanted to understand if the idea made sense or not, but it's not for this PR.", 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1582820421/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1584647951', 'html_url': 'https://github.com/huggingface/datasets/pull/5935#issuecomment-1584647951', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5935', 'id': 1584647951, 'node_id': 'IC_kwDODunzps5ec88P', 'user': {'login': 'lhoestq', 'id': 42851186, 'node_id': 'MDQ6VXNlcjQyODUxMTg2', 'avatar_url': 'https://avatars.githubusercontent.com/u/42851186?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/lhoestq', 'html_url': 'https://github.com/lhoestq', 'followers_url': 'https://api.github.com/users/lhoestq/followers', 'following_url': 'https://api.github.com/users/lhoestq/following{/other_user}', 'gists_url': 'https://api.github.com/users/lhoestq/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/lhoestq/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/lhoestq/subscriptions', 'organizations_url': 'https://api.github.com/users/lhoestq/orgs', 'repos_url': 'https://api.github.com/users/lhoestq/repos', 'events_url': 'https://api.github.com/users/lhoestq/events{/privacy}', 'received_events_url': 'https://api.github.com/users/lhoestq/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-09T14:13:34Z', 'updated_at': '2023-06-09T14:13:34Z', 'author_association': 'MEMBER', 'body': "I think it will be more useful for people who use the viewer and won't impact sequential io that much.", 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1584647951/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1584827426', 'html_url': 'https://github.com/huggingface/datasets/pull/5935#issuecomment-1584827426', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5935', 'id': 1584827426, 'node_id': 'IC_kwDODunzps5edowi', 'user': {'login': 'mariosasko', 'id': 47462742, 'node_id': 'MDQ6VXNlcjQ3NDYyNzQy', 'avatar_url': 'https://avatars.githubusercontent.com/u/47462742?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/mariosasko', 'html_url': 'https://github.com/mariosasko', 'followers_url': 'https://api.github.com/users/mariosasko/followers', 'following_url': 'https://api.github.com/users/mariosasko/following{/other_user}', 'gists_url': 'https://api.github.com/users/mariosasko/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/mariosasko/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/mariosasko/subscriptions', 'organizations_url': 'https://api.github.com/users/mariosasko/orgs', 'repos_url': 'https://api.github.com/users/mariosasko/repos', 'events_url': 'https://api.github.com/users/mariosasko/events{/privacy}', 'received_events_url': 'https://api.github.com/users/mariosasko/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-09T16:10:49Z', 'updated_at': '2023-06-09T16:10:49Z', 'author_association': 'CONTRIBUTOR', 'body': "DuckDB [paragraph](https://duckdb.org/docs/data/parquet/tips.html#s

[{'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1633001666', 'html_url': 'https://github.com/huggingface/datasets/pull/5934#issuecomment-1633001666', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5934', 'id': 1633001666, 'node_id': 'IC_kwDODunzps5hVaDC', 'user': {'login': 'mariosasko', 'id': 47462742, 'node_id': 'MDQ6VXNlcjQ3NDYyNzQy', 'avatar_url': 'https://avatars.githubusercontent.com/u/47462742?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/mariosasko', 'html_url': 'https://github.com/mariosasko', 'followers_url': 'https://api.github.com/users/mariosasko/followers', 'following_url': 'https://api.github.com/users/mariosasko/following{/other_user}', 'gists_url': 'https://api.github.com/users/mariosasko/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/mariosasko/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/mariosasko/subscriptions', 'organizations_url': 'https://api.github.com/users/mariosasko/orgs', 'repos_url': 'https://api.github.com/users/mariosasko/repos', 'events_url': 'https://api.github.com/users/mariosasko/events{/privacy}', 'received_events_url': 'https://api.github.com/users/mariosasko/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-07-12T18:17:39Z', 'updated_at': '2023-07-12T18:17:39Z', 'author_association': 'CONTRIBUTOR', 'body': "I've addressed this as part of #6019, so feel free to close this PR. ", 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1633001666/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1633005976', 'html_url': 'https://github.com/huggingface/datasets/pull/5934#issuecomment-1633005976', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5934', 'id': 1633005976, 'node_id': 'IC_kwDODunzps5hVbGY', 'user': {'login': 'Laurent2916', 'id': 21087104, 'node_id': 'MDQ6VXNlcjIxMDg3MTA0', 'avatar_url': 'https://avatars.githubusercontent.com/u/21087104?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/Laurent2916', 'html_url': 'https://github.com/Laurent2916', 'followers_url': 'https://api.github.com/users/Laurent2916/followers', 'following_url': 'https://api.github.com/users/Laurent2916/following{/other_user}', 'gists_url': 'https://api.github.com/users/Laurent2916/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/Laurent2916/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/Laurent2916/subscriptions', 'organizations_url': 'https://api.github.com/users/Laurent2916/orgs', 'repos_url': 'https://api.github.com/users/Laurent2916/repos', 'events_url': 'https://api.github.com/users/Laurent2916/events{/privacy}', 'received_events_url': 'https://api.github.com/users/Laurent2916/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-07-12T18:21:02Z', 'updated_at': '2023-07-12T18:21:02Z', 'author_association': 'CONTRIBUTOR', 'body': 'Thanks !', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1633005976/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}]

[{'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1581148696', 'html_url': 'https://github.com/huggingface/datasets/pull/5932#issuecomment-1581148696', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5932', 'id': 1581148696, 'node_id': 'IC_kwDODunzps5ePmoY', 'user': {'login': 'github-actions[bot]', 'id': 41898282, 'node_id': 'MDM6Qm90NDE4OTgyODI=', 'avatar_url': 'https://avatars.githubusercontent.com/in/15368?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/github-actions%5Bbot%5D', 'html_url': 'https://github.com/apps/github-actions', 'followers_url': 'https://api.github.com/users/github-actions%5Bbot%5D/followers', 'following_url': 'https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}', 'gists_url': 'https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/github-actions%5Bbot%5D/subscriptions', 'organizations_url': 'https://api.github.com/users/github-actions%5Bbot%5D/orgs', 'repos_url': 'https://api.github.com/users/github-actions%5Bbot%5D/repos', 'events_url': 'https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}', 'received_events_url': 'https://api.github.com/users/github-actions%5Bbot%5D/received_events', 'type': 'Bot', 'site_admin': False}, 'created_at': '2023-06-07T16:18:59Z', 'updated_at': '2023-06-07T16:18:59Z', 'author_association': 'NONE', 'body': '<details>\n<summary>Show benchmarks</summary>\n\nPyArrow==8.0.0\n\n<details>\n<summary>Show updated benchmarks!</summary>\n\n### Benchmark: benchmark_array_xd.json\n\n| metric | read_batch_formatted_as_numpy after write_array2d | read_batch_formatted_as_numpy after write_flattened_sequence | read_batch_formatted_as_numpy after write_nested_sequence | read_batch_unformated after write_array2d | read_batch_unformated after write_flattened_sequence | read_batch_unformated after write_nested_sequence | read_col_formatted_as_numpy after write_array2d | read_col_formatted_as_numpy after write_flattened_sequence | read_col_formatted_as_numpy after write_nested_sequence | read_col_unformated after write_array2d | read_col_unformated after write_flattened_sequence | read_col_unformated after write_nested_sequence | read_formatted_as_numpy after write_array2d | read_formatted_as_numpy after write_flattened_sequence | read_formatted_as_numpy after write_nested_sequence | read_unformated after write_array2d | read_unformated after write_flattened_sequence | read_unformated after write_nested_sequence | write_array2d | write_flattened_sequence | write_nested_sequence |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.008499 / 0.011353 (-0.002854) | 0.006155 / 0.011008 (-0.004853) | 0.124032 / 0.038508 (0.085524) | 0.037337 / 0.023109 (0.014228) | 0.389274 / 0.275898 (0.113376) | 0.427736 / 0.323480 (0.104257) | 0.006929 / 0.007986 (-0.001057) | 0.005017 / 0.004328 (0.000689) | 0.096356 / 0.004250 (0.092105) | 0.055694 / 0.037052 (0.018642) | 0.391417 / 0.258489 (0.132928) | 0.448098 / 0.293841 (0.154257) | 0.042442 / 0.128546 (-0.086105) | 0.013456 / 0.075646 (-0.062190) | 0.423502 / 0.419271 (0.004230) | 0.062919 / 0.043533 (0.019386) | 0.384317 / 0.255139 (0.129178) | 0.410851 / 0.283200 (0.127652) | 0.112807 / 0.141683 (-0.028875) | 1.746050 / 1.452155 (0.293895) | 1.977974 / 1.492716 (0.485257) |\n\n### Benchmark: benchmark_getitem\\_100B.json\n\n| metric | get_batch_of\\_1024\\_random_rows | get_batch_of\\_1024\\_rows | get_first_row | get_last_row |\n|--------|---|---|---|---|\n| new / old (diff) | 0.306382 / 0.018006 (0.288375) | 0.620310 / 0.000490 (0.619820) | 0.009309 / 0.000200 (0.009109) | 0.000106 / 0.000054 (0.000052) |\n\n### Benchmark: benchmark_indices_mapping.json\n\n| metric | select | shard | shuffle | sort | train_test_split |\n|--------|---|---|---|---|---|\n| new / old (diff) | 0.026900 / 0.037411 (-0.010511) | 0.140125 / 0.014526 (0.125599) | 0.136295 / 0.176557 (-0.040261) | 0.207721 / 0.737135 (-0.529414) | 0.146328 / 0.296338 (-0.150011) |\n\n### Benchmark: benchmark_iterating.json\n\n| metric | read 5000 | read 50000 | read_batch 50000 10 | read_batch 50000 100 | read_batch 50000 1000 | read_formatted numpy 5000 | read_formatted pandas 5000 | read_formatted tensorflow 5000 | read_formatted torch 5000 | read_formatted_batch numpy 5000 10 | read_formatted_batch numpy 5000 1000 | shuffled read 5000 | shuffled read 50000 | shuffled read_batch 50000 10 | shuffled read_batch 50000 100 | shuffled read_batch 50000 1000 | shuffled read_formatted numpy 5000 | shuffled read_formatted_batch numpy 5000 10 | shuffled read_formatted_batch numpy 5000 1000 |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.616712 / 0.215209 (0.401503) | 6.237820 / 2.077655 (4.160166) | 2.503809 / 1.504120 (0.999689) | 2.129739 / 1.541195 (0.588544) | 2.160768 / 1.468490 (0.692277) | 0.971273 / 4.584777 (-3.613504) | 5.687161 / 3.745712 (1.941449) | 2.738148 / 5.269862 (-2.531713) | 1.692695 / 4.565676 (-2.872981) | 0.113701 / 0.424275 (-0.310574) | 0.014809 / 0.007607 (0.007202) | 0.774795 / 0.226044 (0.548750) | 7.660012 / 2.268929 (5.391083) | 3.253036 / 55.444624 (-52.191588) | 2.607498 / 6.876477 (-4.268979) | 2.681678 / 2.142072 (0.539606) | 1.095275 / 4.805227 (-3.709952) | 0.239078 / 6.500664 (-6.261586) | 0.081034 / 0.075469 (0.005565) |\n\n### Benchmark: benchmark_map_filter.json\n\n| metric | filter | map fast-tokenizer batched | map identity | map identity batched | map no-op batched | map no-op batched numpy | map no-op batched pandas | map no-op batched pytorch | map no-op batched tensorflow |\n|--------|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 1.574547 / 1.841788 (-0.267240) | 18.323566 / 8.074308 (10.249258) | 19.274482 / 10.191392 (9.083090) | 0.210275 / 0.680424 (-0.470149) | 0.031843 / 0.534201 (-0.502358) | 0.514843 / 0.579283 (-0.064440) | 0.633782 / 0.434364 (0.199418) | 0.588569 / 0.540337 (0.048232) | 0.721401 / 1.386936 (-0.665535) |\n\n</details>\nPyArrow==latest\n\n<details>\n<summary>Show updated benchmarks!</summary>\n\n### Benchmark: benchmark_array_xd.json\n\n| metric | read_batch_formatted_as_numpy after write_array2d | read_batch_formatted_as_numpy after write_flattened_sequence | read_batch_formatted_as_numpy after write_nested_sequence | read_batch_unformated after write_array2d | read_batch_unformated after write_flattened_sequence | read_batch_unformated after write_nested_sequence | read_col_formatted_as_numpy after write_array2d | read_col_formatted_as_numpy after write_flattened_sequence | read_col_formatted_as_numpy after write_nested_sequence | read_col_unformated after write_array2d | read_col_unformated after write_flattened_sequence | read_col_unformated after write_nested_sequence | read_formatted_as_numpy after write_array2d | read_formatted_as_numpy after write_flattened_sequence | read_formatted_as_numpy after write_nested_sequence | read_unformated after write_array2d | read_unformated after write_flattened_sequence | read_unformated after write_nested_sequence | write_array2d | write_flattened_sequence | write_nested_sequence |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.008866 / 0.011353 (-0.002487) | 0.006460 / 0.011008 (-0.004548) | 0.121337 / 0.038508 (0.082829) | 0.033896 / 0.023109 (0.010786) | 0.455702 / 0.275898 (0.179804) | 0.509685 / 0.323480 (0.186205) | 0.007650 / 0.007986 (-0.000336) | 0.005578 / 0.004328 (0.001250) | 0.098505 / 0.004250 (0.094255) | 0.056122 / 0.037052 (0.019069) | 0.478483 / 0.258489 (0.219994) | 0.560008 / 0.293841 (0.266167) | 0.044926 / 0.128546 (-0.083620) | 0.014562 / 0.075646 (-0.061085) | 0.115027 / 0.419271 (-0.304244) | 0.066494 / 0.043533 (0.022961) | 0.463434 / 0.255139 (0.208296) | 0.513856 / 0.283200 (0.230656) | 0.126436 / 0.141683 (-0.015247) | 1.874729 / 1.452155 (0.422575) | 1.925080 / 1.492716 (0.432364) |\n\n### Benchmark: benchmark_getitem\\_100B.json\n\n| metric | get_batch_of\\_1024\\_random_rows | get_batch_of\\_1024\\_rows | get_first_row | get_last_row |\n|--------|---|---|---|---|\n| new / old (diff) | 0.012672 / 0.018006 (-0.005334) | 0.615797 / 0.000490 (0.615307) | 0.001606 / 0.000200 (0.001406) | 0.000118 / 0.000054 (0.000064) |\n\n### Benchmark: benchmark_indices_mapping.json\n\n| metric | select | shard | shuffle | sort | train_test_split |\n|--------|---|---|---|---|---|\n| new / old (diff) | 0.031104 / 0.037411 (-0.006307) | 0.130107 / 0.014526 (0.115581) | 0.140587 / 0.176557 (-0.035970) | 0.205081 / 0.737135 (-0.532054) | 0.144068 / 0.296338 (-0.152270) |\n\n### Benchmark: benchmark_iterating.json\n\n| metric | read 5000 | read 50000 | read_batch 50000 10 | read_batch 50000 100 | read_batch 50000 1000 | read_formatted numpy 5000 | read_formatted pandas 5000 | read_formatted tensorflow 5000 | read_formatted torch 5000 | read_formatted_batch numpy 5000 10 | read_formatted_batch numpy 5000 1000 | shuffled read 5000 | shuffled read 50000 | shuffled read_batch 50000 10 | shuffled read_batch 50000 100 | shuffled read_batch 50000 1000 | shuffled read_formatted numpy 5000 | shuffled read_formatted_batch numpy 5000 10 | shuffled read_formatted_batch numpy 5000 1000 |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.646549 / 0.215209 (0.431340) | 6.403962 / 2.077655 (4.326307) | 2.812594 / 1.504120 (1.308474) | 2.478480 / 1.541195 (0.937285) | 2.552385 / 1.468490 (1.083895) | 0.991987 / 4.584777 (-3.592790) | 5.777917 / 3.745712 (2.032205) | 5.697830 / 5.269862 (0.427969) | 2.370583 / 4.565676 (-2.195094) | 0.109905 / 0.424275 (-0.314370) | 0.013801 / 0.007607 (0.006193) | 0.799932 / 0.226044 (0.573888) | 8.155672 / 2.268929 (5.886743) | 3.711662 / 55.444624 (-51.732963) | 3.042164 / 6.876477 (-3.834312) | 3.073549 / 2.142072 (0.931477) | 1.137515 / 4.805227 (-3.667712) | 0.231266 / 6.500664 (-6.269398) | 0.080893 / 0.075469 (0.005424) |\n\n### Benchmark: benchmark_map_filter.json\n\n| metric | filter | map fast-tokenizer batched | map identity | map identity batched | map no-op batched | map no-op batched numpy | map no-op batched pandas | map no-op batched pytorch | map no-op batched tensorflow |\n|--------|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 1.669210 / 1.841788 (-0.172577) | 18.747144 / 8.074308 (10.672836) | 21.084589 / 10.191392 (10.893197) | 0.241379 / 0.680424 (-0.439045) | 0.029473 / 0.534201 (-0.504728) | 0.524605 / 0.579283 (-0.054678) | 0.622852 / 0.434364 (0.188488) | 0.604941 / 0.540337 (0.064604) | 0.715978 / 1.386936 (-0.670958) |\n\n</details>\n</details>\n\n![](https://cml.dev/watermark.png#142484a60b1330359d7713e906fc9e5e30aa9f64 "CML watermark")\n', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1581148696/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1582302609', 'html_url': 'https://github.com/huggingface/datasets/pull/5932#issuecomment-1582302609', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5932', 'id': 1582302609, 'node_id': 'IC_kwDODunzps5eUAWR', 'user': {'login': 'lhoestq', 'id': 42851186, 'node_id': 'MDQ6VXNlcjQyODUxMTg2', 'avatar_url': 'https://avatars.githubusercontent.com/u/42851186?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/lhoestq', 'html_url': 'https://github.com/lhoestq', 'followers_url': 'https://api.github.com/users/lhoestq/followers', 'following_url': 'https://api.github.com/users/lhoestq/following{/other_user}', 'gists_url': 'https://api.github.com/users/lhoestq/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/lhoestq/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/lhoestq/subscriptions', 'organizations_url': 'https://api.github.com/users/lhoestq/orgs', 'repos_url': 'https://api.github.com/users/lhoestq/repos', 'events_url': 'https://api.github.com/users/lhoestq/events{/privacy}', 'received_events_url': 'https://api.github.com/users/lhoestq/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-08T10:14:19Z', 'updated_at': '2023-06-08T10:14:19Z', 'author_association': 'MEMBER', 'body': 'Cool ! what about `.github/workflows/build_pr_documentation.yml` and `.github/workflows/delete_doc_comment.yml` ?', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1582302609/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1584308014', 'html_url': 'https://github.com/huggingface/datasets/pull/5932#issuecomment-1584308014', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5932', 'id': 1584308014, 'node_id': 'IC_kwDODunzps5ebp8u', 'user': {'login': 'github-actions[bot]', 'id': 41898282, 'node_id': 'MDM6Qm90NDE4OTgyODI=', 'avatar_url': 'https://avatars.githubusercontent.com/in/15368?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/github-actions%5Bbot%5D', 'html_url': 'https://github.com/apps/github-actions', 'followers_url': 'https://api.github.com/users/github-actions%5Bbot%5D/followers', 'following_url': 'https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}', 'gists_url': 'https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/github-actions%5Bbot%5D/subscriptions', 'organizations_url': 'https://api.github.com/users/github-actions%5Bbot%5D/orgs', 'repos_url': 'https://api.github.com/users/github-actions%5Bbot%5D/repos', 'events_url': 'https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}', 'received_events_url': 'https://api.github.com/users/github-actions%5Bbot%5D/received_events', 'type': 'Bot', 'site_admin': False}, 'created_at': '2023-06-09T10:00:14Z', 'updated_at': '2023-06-09T10:00:14Z', 'author_association': 'NONE', 'body': '<details>\n<summary>Show benchmarks</summary>\n\nPyArrow==8.0.0\n\n<details>\n<summary>Show updated benchmarks!</summary>\n\n### Benchmark: benchmark_array_xd.json\n\n| metric | read_batch_formatted_as_numpy after write_array2d | read_batch_formatted_as_numpy after write_flattened_sequence | read_batch_formatted_as_numpy after write_nested_sequence | read_batch_unformated after write_array2d | read_batch_unformated after write_flattened_sequence | read_batch_unformated after write_nested_sequence | read_col_formatted_as_numpy after write_array2d | read_col_formatted_as_numpy after write_flattened_sequence | read_col_formatted_as_numpy after write_nested_sequence | read_col_unformated after write_array2d | read_col_unformated after write_flattened_sequence | read_col_unformated after write_nested_sequence | read_formatted_as_numpy after write_array2d | read_formatted_as_numpy after write_flattened_sequence | read_formatted_as_numpy after write_nested_sequence | read_unformated after write_array2d | read_unformated after write_flattened_sequence | read_unformated after write_nested_sequence | write_array2d | write_flattened_sequence | write_nested_sequence |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.005973 / 0.011353 (-0.005380) | 0.004389 / 0.011008 (-0.006620) | 0.096076 / 0.038508 (0.057568) | 0.031569 / 0.023109 (0.008460) | 0.328300 / 0.275898 (0.052402) | 0.359356 / 0.323480 (0.035876) | 0.005378 / 0.007986 (-0.002607) | 0.003703 / 0.004328 (-0.000625) | 0.075251 / 0.004250 (0.071000) | 0.042340 / 0.037052 (0.005287) | 0.346103 / 0.258489 (0.087614) | 0.379896 / 0.293841 (0.086055) | 0.027493 / 0.128546 (-0.101053) | 0.009033 / 0.075646 (-0.066613) | 0.327829 / 0.419271 (-0.091442) | 0.064074 / 0.043533 (0.020541) | 0.337703 / 0.255139 (0.082564) | 0.355335 / 0.283200 (0.072136) | 0.101179 / 0.141683 (-0.040504) | 1.471738 / 1.452155 (0.019584) | 1.539031 / 1.492716 (0.046315) |\n\n### Benchmark: benchmark_getitem\\_100B.json\n\n| metric | get_batch_of\\_1024\\_random_rows | get_batch_of\\_1024\\_rows | get_first_row | get_last_row |\n|--------|---|---|---|---|\n| new / old (diff) | 0.194097 / 0.018006 (0.176091) | 0.434190 / 0.000490 (0.433701) | 0.005730 / 0.000200 (0.005530) | 0.000088 / 0.000054 (0.000033) |\n\n### Benchmark: benchmark_indices_mapping.json\n\n| metric | select | shard | shuffle | sort | train_test_split |\n|--------|---|---|---|---|---|\n| new / old (diff) | 0.025634 / 0.037411 (-0.011778) | 0.105080 / 0.014526 (0.090555) | 0.116508 / 0.176557 (-0.060049) | 0.173867 / 0.737135 (-0.563269) | 0.117749 / 0.296338 (-0.178590) |\n\n### Benchmark: benchmark_iterating.json\n\n| metric | read 5000 | read 50000 | read_batch 50000 10 | read_batch 50000 100 | read_batch 50000 1000 | read_formatted numpy 5000 | read_formatted pandas 5000 | read_formatted tensorflow 5000 | read_formatted torch 5000 | read_formatted_batch numpy 5000 10 | read_formatted_batch numpy 5000 1000 | shuffled read 5000 | shuffled read 50000 | shuffled read_batch 50000 10 | shuffled read_batch 50000 100 | shuffled read_batch 50000 1000 | shuffled read_formatted numpy 5000 | shuffled read_formatted_batch numpy 5000 10 | shuffled read_formatted_batch numpy 5000 1000 |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.401566 / 0.215209 (0.186357) | 4.003558 / 2.077655 (1.925903) | 1.802756 / 1.504120 (0.298636) | 1.604222 / 1.541195 (0.063027) | 1.656617 / 1.468490 (0.188127) | 0.523385 / 4.584777 (-4.061392) | 3.744292 / 3.745712 (-0.001420) | 1.794295 / 5.269862 (-3.475567) | 1.044690 / 4.565676 (-3.520987) | 0.064992 / 0.424275 (-0.359284) | 0.011542 / 0.007607 (0.003935) | 0.507830 / 0.226044 (0.281785) | 5.061574 / 2.268929 (2.792645) | 2.252896 / 55.444624 (-53.191729) | 1.912551 / 6.876477 (-4.963926) | 2.073510 / 2.142072 (-0.068562) | 0.642148 / 4.805227 (-4.163079) | 0.140151 / 6.500664 (-6.360513) | 0.062623 / 0.075469 (-0.012846) |\n\n### Benchmark: benchmark_map_filter.json\n\n| metric | filter | map fast-tokenizer batched | map identity | map identity batched | map no-op batched | map no-op batched numpy | map no-op batched pandas | map no-op batched pytorch | map no-op batched tensorflow |\n|--------|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 1.180367 / 1.841788 (-0.661421) | 14.263475 / 8.074308 (6.189167) | 12.917251 / 10.191392 (2.725859) | 0.143815 / 0.680424 (-0.536608) | 0.017286 / 0.534201 (-0.516915) | 0.388411 / 0.579283 (-0.190872) | 0.430512 / 0.434364 (-0.003851) | 0.466595 / 0.540337 (-0.073742) | 0.564545 / 1.386936 (-0.822391) |\n\n</details>\nPyArrow==latest\n\n<details>\n<summary>Show updated benchmarks!</summary>\n\n### Benchmark: benchmark_array_xd.json\n\n| metric | read_batch_formatted_as_numpy after write_array2d | read_batch_formatted_as_numpy after write_flattened_sequence | read_batch_formatted_as_numpy after write_nested_sequence | read_batch_unformated after write_array2d | read_batch_unformated after write_flattened_sequence | read_batch_unformated after write_nested_sequence | read_col_formatted_as_numpy after write_array2d | read_col_formatted_as_numpy after write_flattened_sequence | read_col_formatted_as_numpy after write_nested_sequence | read_col_unformated after write_array2d | read_col_unformated after write_flattened_sequence | read_col_unformated after write_nested_sequence | read_

[{'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1591892826', 'html_url': 'https://github.com/huggingface/datasets/issues/5931#issuecomment-1591892826', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5931', 'id': 1591892826, 'node_id': 'IC_kwDODunzps5e4lta', 'user': {'login': 'mariosasko', 'id': 47462742, 'node_id': 'MDQ6VXNlcjQ3NDYyNzQy', 'avatar_url': 'https://avatars.githubusercontent.com/u/47462742?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/mariosasko', 'html_url': 'https://github.com/mariosasko', 'followers_url': 'https://api.github.com/users/mariosasko/followers', 'following_url': 'https://api.github.com/users/mariosasko/following{/other_user}', 'gists_url': 'https://api.github.com/users/mariosasko/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/mariosasko/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/mariosasko/subscriptions', 'organizations_url': 'https://api.github.com/users/mariosasko/orgs', 'repos_url': 'https://api.github.com/users/mariosasko/repos', 'events_url': 'https://api.github.com/users/mariosasko/events{/privacy}', 'received_events_url': 'https://api.github.com/users/mariosasko/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-14T20:00:37Z', 'updated_at': '2023-06-14T20:01:55Z', 'author_association': 'CONTRIBUTOR', 'body': 'This can happen when a map transform cannot be hashed deterministically (e.g., an object referenced by the transform changes its state after the first call - an issue with fast tokenizers). The solution is to provide `cache_file_name` in the `map` call to check this file for the cached result instead of relying on the default caching mechanism.', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1591892826/reactions', 'total_count': 1, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 1, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}]
[{'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1593215945', 'html_url': 'https://github.com/huggingface/datasets/issues/5930#issuecomment-1593215945', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5930', 'id': 1593215945, 'node_id': 'IC_kwDODunzps5e9ovJ', 'user': {'login': 'mariosasko', 'id': 47462742, 'node_id': 'MDQ6VXNlcjQ3NDYyNzQy', 'avatar_url': 'https://avatars.githubusercontent.com/u/47462742?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/mariosasko', 'html_url': 'https://github.com/mariosasko', 'followers_url': 'https://api.github.com/users/mariosasko/followers', 'following_url': 'https://api.github.com/users/mariosasko/following{/other_user}', 'gists_url': 'https://api.github.com/users/mariosasko/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/mariosasko/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/mariosasko/subscriptions', 'organizations_url': 'https://api.github.com/users/mariosasko/orgs', 'repos_url': 'https://api.github.com/users/mariosasko/repos', 'events_url': 'https://api.github.com/users/mariosasko/events{/privacy}', 'received_events_url': 'https://api.github.com/users/mariosasko/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-15T14:49:20Z', 'updated_at': '2023-06-15T14:49:20Z', 'author_association': 'CONTRIBUTOR', 'body': "This issue seems to have been resolved, so I'm closing it.", 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1593215945/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}]
[{'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1593173095', 'html_url': 'https://github.com/huggingface/datasets/issues/5929#issuecomment-1593173095', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5929', 'id': 1593173095, 'node_id': 'IC_kwDODunzps5e9eRn', 'user': {'login': 'mariosasko', 'id': 47462742, 'node_id': 'MDQ6VXNlcjQ3NDYyNzQy', 'avatar_url': 'https://avatars.githubusercontent.com/u/47462742?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/mariosasko', 'html_url': 'https://github.com/mariosasko', 'followers_url': 'https://api.github.com/users/mariosasko/followers', 'following_url': 'https://api.github.com/users/mariosasko/following{/other_user}', 'gists_url': 'https://api.github.com/users/mariosasko/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/mariosasko/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/mariosasko/subscriptions', 'organizations_url': 'https://api.github.com/users/mariosasko/orgs', 'repos_url': 'https://api.github.com/users/mariosasko/repos', 'events_url': 'https://api.github.com/users/mariosasko/events{/privacy}', 'received_events_url': 'https://api.github.com/users/mariosasko/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-15T14:25:59Z', 'updated_at': '2023-06-15T14:25:59Z', 'author_association': 'CONTRIBUTOR', 'body': "Hi! The times match when I run this code locally or on Colab.\r\n\r\nAlso, we use `multiprocess`, not `multiprocessing`, for parallelization, and torch's `__init__.py` (executed on `import torch` ) slightly modifies the latter.", 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1593173095/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1594652793', 'html_url': 'https://github.com/huggingface/datasets/issues/5929#issuecomment-1594652793', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5929', 'id': 1594652793, 'node_id': 'IC_kwDODunzps5fDHh5', 'user': {'login': 'Maxscha', 'id': 12814709, 'node_id': 'MDQ6VXNlcjEyODE0NzA5', 'avatar_url': 'https://avatars.githubusercontent.com/u/12814709?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/Maxscha', 'html_url': 'https://github.com/Maxscha', 'followers_url': 'https://api.github.com/users/Maxscha/followers', 'following_url': 'https://api.github.com/users/Maxscha/following{/other_user}', 'gists_url': 'https://api.github.com/users/Maxscha/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/Maxscha/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/Maxscha/subscriptions', 'organizations_url': 'https://api.github.com/users/Maxscha/orgs', 'repos_url': 'https://api.github.com/users/Maxscha/repos', 'events_url': 'https://api.github.com/users/Maxscha/events{/privacy}', 'received_events_url': 'https://api.github.com/users/Maxscha/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-16T13:09:12Z', 'updated_at': '2023-06-16T13:09:12Z', 'author_association': 'NONE', 'body': "Hey Mariosasko,\r\n\r\nThanks for looking into it. We further did some investigations after your comment and figured out it's only affecting some hardware/software configurations with the `pytorch` installation of `conda-forge`. Based on this we found the following issue in PyTorch: https://github.com/pytorch/pytorch/issues/102269 with a quick fix for now.\r\n\r\nSince it seems to be a deeper issue with forking processes, the difference between`multiprocess` and `multiprocessing` didn't make a difference.\r\n\r\nClosing this, since the issue comes from `pytorch` not `dataset`. \r\n", 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1594652793/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}]

[{'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1578952220', 'html_url': 'https://github.com/huggingface/datasets/issues/5927#issuecomment-1578952220', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5927', 'id': 1578952220, 'node_id': 'IC_kwDODunzps5eHOYc', 'user': {'login': 'qgallouedec', 'id': 45557362, 'node_id': 'MDQ6VXNlcjQ1NTU3MzYy', 'avatar_url': 'https://avatars.githubusercontent.com/u/45557362?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/qgallouedec', 'html_url': 'https://github.com/qgallouedec', 'followers_url': 'https://api.github.com/users/qgallouedec/followers', 'following_url': 'https://api.github.com/users/qgallouedec/following{/other_user}', 'gists_url': 'https://api.github.com/users/qgallouedec/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/qgallouedec/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/qgallouedec/subscriptions', 'organizations_url': 'https://api.github.com/users/qgallouedec/orgs', 'repos_url': 'https://api.github.com/users/qgallouedec/repos', 'events_url': 'https://api.github.com/users/qgallouedec/events{/privacy}', 'received_events_url': 'https://api.github.com/users/qgallouedec/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-06T15:11:39Z', 'updated_at': '2023-06-06T15:11:39Z', 'author_association': 'CONTRIBUTOR', 'body': "Easy fix would be to add:\r\n\r\n```python\r\nnull_indices -= np.arange(len(null_indices))\r\n```\r\n\r\nbefore L279, but I'm not sure it's the most intuitive way to fix it.", 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1578952220/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1589229304', 'html_url': 'https://github.com/huggingface/datasets/issues/5927#issuecomment-1589229304', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5927', 'id': 1589229304, 'node_id': 'IC_kwDODunzps5eubb4', 'user': {'login': 'qgallouedec', 'id': 45557362, 'node_id': 'MDQ6VXNlcjQ1NTU3MzYy', 'avatar_url': 'https://avatars.githubusercontent.com/u/45557362?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/qgallouedec', 'html_url': 'https://github.com/qgallouedec', 'followers_url': 'https://api.github.com/users/qgallouedec/followers', 'following_url': 'https://api.github.com/users/qgallouedec/following{/other_user}', 'gists_url': 'https://api.github.com/users/qgallouedec/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/qgallouedec/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/qgallouedec/subscriptions', 'organizations_url': 'https://api.github.com/users/qgallouedec/orgs', 'repos_url': 'https://api.github.com/users/qgallouedec/repos', 'events_url': 'https://api.github.com/users/qgallouedec/events{/privacy}', 'received_events_url': 'https://api.github.com/users/qgallouedec/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-13T12:39:17Z', 'updated_at': '2023-06-13T12:39:39Z', 'author_association': 'CONTRIBUTOR', 'body': 'Same issue here:\r\n\r\nhttps://github.com/huggingface/datasets/blob/7fcbe5b1575c8d162b65b9397b3dfda995a4e048/src/datasets/features/features.py#L1398\r\n\r\nFixed in #5948 ', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1589229304/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}]
[{'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1578898800', 'html_url': 'https://github.com/huggingface/datasets/issues/5926#issuecomment-1578898800', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5926', 'id': 1578898800, 'node_id': 'IC_kwDODunzps5eHBVw', 'user': {'login': 'albertvillanova', 'id': 8515462, 'node_id': 'MDQ6VXNlcjg1MTU0NjI=', 'avatar_url': 'https://avatars.githubusercontent.com/u/8515462?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/albertvillanova', 'html_url': 'https://github.com/albertvillanova', 'followers_url': 'https://api.github.com/users/albertvillanova/followers', 'following_url': 'https://api.github.com/users/albertvillanova/following{/other_user}', 'gists_url': 'https://api.github.com/users/albertvillanova/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/albertvillanova/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/albertvillanova/subscriptions', 'organizations_url': 'https://api.github.com/users/albertvillanova/orgs', 'repos_url': 'https://api.github.com/users/albertvillanova/repos', 'events_url': 'https://api.github.com/users/albertvillanova/events{/privacy}', 'received_events_url': 'https://api.github.com/users/albertvillanova/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-06T14:41:50Z', 'updated_at': '2023-06-06T14:41:50Z', 'author_association': 'MEMBER', 'body': 'Thanks for reporting, @severo.\r\n\r\nThis is a known issue with `fsspec`:\r\n- #5862\r\n- https://github.com/fsspec/filesystem_spec/issues/1265', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1578898800/reactions', 'total_count': 1, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 1, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}]
[{'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1635029964', 'html_url': 'https://github.com/huggingface/datasets/pull/6030#issuecomment-1635029964', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/6030', 'id': 1635029964, 'node_id': 'IC_kwDODunzps5hdJPM', 'user': {'login': 'HuggingFaceDocBuilderDev', 'id': 99929124, 'node_id': 'U_kgDOBfTMJA', 'avatar_url': 'https://avatars.githubusercontent.com/u/99929124?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/HuggingFaceDocBuilderDev', 'html_url': 'https://github.com/HuggingFaceDocBuilderDev', 'followers_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/followers', 'following_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/following{/other_user}', 'gists_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/subscriptions', 'organizations_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/orgs', 'repos_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/repos', 'events_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/events{/privacy}', 'received_events_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-07-13T22:55:25Z', 'updated_at': '2023-07-13T22:55:25Z', 'author_association': 'NONE', 'body': 'The docs for this PR live [here](https://moon-ci-docs.huggingface.co/docs/datasets/pr_6030). All of your documentation changes will be reflected on that endpoint.', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1635029964/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}]

[{'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1634486519', 'html_url': 'https://github.com/huggingface/datasets/pull/6028#issuecomment-1634486519', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/6028', 'id': 1634486519, 'node_id': 'IC_kwDODunzps5hbEj3', 'user': {'login': 'HuggingFaceDocBuilderDev', 'id': 99929124, 'node_id': 'U_kgDOBfTMJA', 'avatar_url': 'https://avatars.githubusercontent.com/u/99929124?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/HuggingFaceDocBuilderDev', 'html_url': 'https://github.com/HuggingFaceDocBuilderDev', 'followers_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/followers', 'following_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/following{/other_user}', 'gists_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/subscriptions', 'organizations_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/orgs', 'repos_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/repos', 'events_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/events{/privacy}', 'received_events_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-07-13T15:48:11Z', 'updated_at': '2023-07-13T15:48:11Z', 'author_association': 'NONE', 'body': 'The docs for this PR live [here](https://moon-ci-docs.huggingface.co/docs/datasets/pr_6028). All of your documentation changes will be reflected on that endpoint.', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1634486519/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1634489939', 'html_url': 'https://github.com/huggingface/datasets/pull/6028#issuecomment-1634489939', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/6028', 'id': 1634489939, 'node_id': 'IC_kwDODunzps5hbFZT', 'user': {'login': 'github-actions[bot]', 'id': 41898282, 'node_id': 'MDM6Qm90NDE4OTgyODI=', 'avatar_url': 'https://avatars.githubusercontent.com/in/15368?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/github-actions%5Bbot%5D', 'html_url': 'https://github.com/apps/github-actions', 'followers_url': 'https://api.github.com/users/github-actions%5Bbot%5D/followers', 'following_url': 'https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}', 'gists_url': 'https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/github-actions%5Bbot%5D/subscriptions', 'organizations_url': 'https://api.github.com/users/github-actions%5Bbot%5D/orgs', 'repos_url': 'https://api.github.com/users/github-actions%5Bbot%5D/repos', 'events_url': 'https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}', 'received_events_url': 'https://api.github.com/users/github-actions%5Bbot%5D/received_events', 'type': 'Bot', 'site_admin': False}, 'created_at': '2023-07-13T15:50:24Z', 'updated_at': '2023-07-13T15:50:24Z', 'author_association': 'NONE', 'body': '<details>\n<summary>Show benchmarks</summary>\n\nPyArrow==8.0.0\n\n<details>\n<summary>Show updated benchmarks!</summary>\n\n### Benchmark: benchmark_array_xd.json\n\n| metric | read_batch_formatted_as_numpy after write_array2d | read_batch_formatted_as_numpy after write_flattened_sequence | read_batch_formatted_as_numpy after write_nested_sequence | read_batch_unformated after write_array2d | read_batch_unformated after write_flattened_sequence | read_batch_unformated after write_nested_sequence | read_col_formatted_as_numpy after write_array2d | read_col_formatted_as_numpy after write_flattened_sequence | read_col_formatted_as_numpy after write_nested_sequence | read_col_unformated after write_array2d | read_col_unformated after write_flattened_sequence | read_col_unformated after write_nested_sequence | read_formatted_as_numpy after write_array2d | read_formatted_as_numpy after write_flattened_sequence | read_formatted_as_numpy after write_nested_sequence | read_unformated after write_array2d | read_unformated after write_flattened_sequence | read_unformated after write_nested_sequence | write_array2d | write_flattened_sequence | write_nested_sequence |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.006665 / 0.011353 (-0.004688) | 0.004376 / 0.011008 (-0.006633) | 0.085529 / 0.038508 (0.047021) | 0.076372 / 0.023109 (0.053263) | 0.310019 / 0.275898 (0.034121) | 0.341404 / 0.323480 (0.017924) | 0.005666 / 0.007986 (-0.002320) | 0.003763 / 0.004328 (-0.000566) | 0.064678 / 0.004250 (0.060427) | 0.059283 / 0.037052 (0.022231) | 0.316194 / 0.258489 (0.057704) | 0.349397 / 0.293841 (0.055557) | 0.031199 / 0.128546 (-0.097347) | 0.008724 / 0.075646 (-0.066923) | 0.300236 / 0.419271 (-0.119035) | 0.068872 / 0.043533 (0.025339) | 0.308521 / 0.255139 (0.053382) | 0.331292 / 0.283200 (0.048092) | 0.028236 / 0.141683 (-0.113447) | 1.501365 / 1.452155 (0.049211) | 1.554334 / 1.492716 (0.061618) |\n\n### Benchmark: benchmark_getitem\\_100B.json\n\n| metric | get_batch_of\\_1024\\_random_rows | get_batch_of\\_1024\\_rows | get_first_row | get_last_row |\n|--------|---|---|---|---|\n| new / old (diff) | 0.238291 / 0.018006 (0.220285) | 0.565069 / 0.000490 (0.564580) | 0.001626 / 0.000200 (0.001426) | 0.000070 / 0.000054 (0.000015) |\n\n### Benchmark: benchmark_indices_mapping.json\n\n| metric | select | shard | shuffle | sort | train_test_split |\n|--------|---|---|---|---|---|\n| new / old (diff) | 0.029777 / 0.037411 (-0.007634) | 0.082873 / 0.014526 (0.068347) | 0.099619 / 0.176557 (-0.076937) | 0.156572 / 0.737135 (-0.580563) | 0.099887 / 0.296338 (-0.196452) |\n\n### Benchmark: benchmark_iterating.json\n\n| metric | read 5000 | read 50000 | read_batch 50000 10 | read_batch 50000 100 | read_batch 50000 1000 | read_formatted numpy 5000 | read_formatted pandas 5000 | read_formatted tensorflow 5000 | read_formatted torch 5000 | read_formatted_batch numpy 5000 10 | read_formatted_batch numpy 5000 1000 | shuffled read 5000 | shuffled read 50000 | shuffled read_batch 50000 10 | shuffled read_batch 50000 100 | shuffled read_batch 50000 1000 | shuffled read_formatted numpy 5000 | shuffled read_formatted_batch numpy 5000 10 | shuffled read_formatted_batch numpy 5000 1000 |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.401017 / 0.215209 (0.185808) | 3.827192 / 2.077655 (1.749537) | 1.861554 / 1.504120 (0.357434) | 1.699869 / 1.541195 (0.158674) | 1.720043 / 1.468490 (0.251553) | 0.486757 / 4.584777 (-4.098020) | 3.638125 / 3.745712 (-0.107587) | 5.844959 / 5.269862 (0.575097) | 3.454901 / 4.565676 (-1.110775) | 0.057650 / 0.424275 (-0.366625) | 0.007341 / 0.007607 (-0.000266) | 0.462698 / 0.226044 (0.236654) | 4.633472 / 2.268929 (2.364544) | 2.287607 / 55.444624 (-53.157017) | 2.057318 / 6.876477 (-4.819159) | 2.203657 / 2.142072 (0.061584) | 0.598136 / 4.805227 (-4.207091) | 0.134012 / 6.500664 (-6.366653) | 0.060824 / 0.075469 (-0.014645) |\n\n### Benchmark: benchmark_map_filter.json\n\n| metric | filter | map fast-tokenizer batched | map identity | map identity batched | map no-op batched | map no-op batched numpy | map no-op batched pandas | map no-op batched pytorch | map no-op batched tensorflow |\n|--------|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 1.277752 / 1.841788 (-0.564036) | 20.013398 / 8.074308 (11.939089) | 14.372993 / 10.191392 (4.181601) | 0.169991 / 0.680424 (-0.510433) | 0.018344 / 0.534201 (-0.515857) | 0.396985 / 0.579283 (-0.182299) | 0.416289 / 0.434364 (-0.018075) | 0.458658 / 0.540337 (-0.081680) | 0.692980 / 1.386936 (-0.693956) |\n\n</details>\nPyArrow==latest\n\n<details>\n<summary>Show updated benchmarks!</summary>\n\n### Benchmark: benchmark_array_xd.json\n\n| metric | read_batch_formatted_as_numpy after write_array2d | read_batch_formatted_as_numpy after write_flattened_sequence | read_batch_formatted_as_numpy after write_nested_sequence | read_batch_unformated after write_array2d | read_batch_unformated after write_flattened_sequence | read_batch_unformated after write_nested_sequence | read_col_formatted_as_numpy after write_array2d | read_col_formatted_as_numpy after write_flattened_sequence | read_col_formatted_as_numpy after write_nested_sequence | read_col_unformated after write_array2d | read_col_unformated after write_flattened_sequence | read_col_unformated after write_nested_sequence | read_formatted_as_numpy after write_array2d | read_formatted_as_numpy after write_flattened_sequence | read_formatted_as_numpy after write_nested_sequence | read_unformated after write_array2d | read_unformated after write_flattened_sequence | read_unformated after write_nested_sequence | write_array2d | write_flattened_sequence | write_nested_sequence |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.006689 / 0.011353 (-0.004664) | 0.004393 / 0.011008 (-0.006615) | 0.064069 / 0.038508 (0.025561) | 0.080717 / 0.023109 (0.057607) | 0.370090 / 0.275898 (0.094191) | 0.400432 / 0.323480 (0.076952) | 0.005613 / 0.007986 (-0.002372) | 0.003641 / 0.004328 (-0.000687) | 0.064771 / 0.004250 (0.060520) | 0.057555 / 0.037052 (0.020502) | 0.392156 / 0.258489 (0.133667) | 0.409842 / 0.293841 (0.116001) | 0.031500 / 0.128546 (-0.097047) | 0.008786 / 0.075646 (-0.066860) | 0.070342 / 0.419271 (-0.348929) | 0.048646 / 0.043533 (0.005113) | 0.360914 / 0.255139 (0.105775) | 0.387626 / 0.283200 (0.104426) | 0.022787 / 0.141683 (-0.118896) | 1.508915 / 1.452155 (0.056761) | 1.539719 / 1.492716 (0.047002) |\n\n### Benchmark: benchmark_getitem\\_100B.json\n\n| metric | get_batch_of\\_1024\\_random_rows | get_batch_of\\_1024\\_rows | get_first_row | get_last_row |\n|--------|---|---|---|---|\n| new / old (diff) | 0.257985 / 0.018006 (0.239979) | 0.550990 / 0.000490 (0.550501) | 0.000407 / 0.000200 (0.000207) | 0.000057 / 0.000054 (0.000003) |\n\n### Benchmark: benchmark_indices_mapping.json\n\n| metric | select | shard | shuffle | sort | train_test_split |\n|--------|---|---|---|---|---|\n| new / old (diff) | 0.030183 / 0.037411 (-0.007228) | 0.086882 / 0.014526 (0.072356) | 0.102382 / 0.176557 (-0.074175) | 0.154745 / 0.737135 (-0.582390) | 0.104008 / 0.296338 (-0.192331) |\n\n### Benchmark: benchmark_iterating.json\n\n| metric | read 5000 | read 50000 | read_batch 50000 10 | read_batch 50000 100 | read_batch 50000 1000 | read_formatted numpy 5000 | read_formatted pandas 5000 | read_formatted tensorflow 5000 | read_formatted torch 5000 | read_formatted_batch numpy 5000 10 | read_formatted_batch numpy 5000 1000 | shuffled read 5000 | shuffled read 50000 | shuffled read_batch 50000 10 | shuffled read_batch 50000 100 | shuffled read_batch 50000 1000 | shuffled read_formatted numpy 5000 | shuffled read_formatted_batch numpy 5000 10 | shuffled read_formatted_batch numpy 5000 1000 |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.426284 / 0.215209 (0.211075) | 4.240812 / 2.077655 (2.163158) | 2.261240 / 1.504120 (0.757120) | 2.085905 / 1.541195 (0.544710) | 2.160374 / 1.468490 (0.691883) | 0.481126 / 4.584777 (-4.103651) | 3.516234 / 3.745712 (-0.229478) | 3.325322 / 5.269862 (-1.944539) | 2.043307 / 4.565676 (-2.522369) | 0.056663 / 0.424275 (-0.367612) | 0.007786 / 0.007607 (0.000179) | 0.497614 / 0.226044 (0.271570) | 4.974529 / 2.268929 (2.705600) | 2.700018 / 55.444624 (-52.744606) | 2.393778 / 6.876477 (-4.482699) | 2.628202 / 2.142072 (0.486130) | 0.594316 / 4.805227 (-4.210911) | 0.147092 / 6.500664 (-6.353572) | 0.062207 / 0.075469 (-0.013262) |\n\n### Benchmark: benchmark_map_filter.json\n\n| metric | filter | map fast-tokenizer batched | map identity | map identity batched | map no-op batched | map no-op batched numpy | map no-op batched pandas | map no-op batched pytorch | map no-op batched tensorflow |\n|--------|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 1.315676 / 1.841788 (-0.526112) | 20.749251 / 8.074308 (12.674943) | 14.371553 / 10.191392 (4.180160) | 0.170249 / 0.680424 (-0.510175) | 0.018478 / 0.534201 (-0.515722) | 0.395710 / 0.579283 (-0.183573) | 0.409706 / 0.434364 (-0.024658) | 0.463454 / 0.540337 (-0.076884) | 0.615657 / 1.386936 (-0.771279) |\n\n</details>\n</details>\n\n![](https://cml.dev/watermark.png#c5a752d8e8ca0a6ed118b024ba03c1b4a2881177 "CML watermark")\n', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1634489939/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1634602776', 'html_url': 'https://github.com/huggingface/datasets/pull/6028#issuecomment-1634602776', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/6028', 'id': 1634602776, 'node_id': 'IC_kwDODunzps5hbg8Y', 'user': {'login': 'github-actions[bot]', 'id': 41898282, 'node_id': 'MDM6Qm90NDE4OTgyODI=', 'avatar_url': 'https://avatars.githubusercontent.com/in/15368?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/github-actions%5Bbot%5D', 'html_url': 'https://github.com/apps/github-actions', 'followers_url': 'https://api.github.com/users/github-actions%5Bbot%5D/followers', 'following_url': 'https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}', 'gists_url': 'https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/github-actions%5Bbot%5D/subscriptions', 'organizations_url': 'https://api.github.com/users/github-actions%5Bbot%5D/orgs', 'repos_url': 'https://api.github.com/users/github-actions%5Bbot%5D/repos', 'events_url': 'https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}', 'received_events_url': 'https://api.github.com/users/github-actions%5Bbot%5D/received_events', 'type': 'Bot', 'site_admin': False}, 'created_at': '2023-07-13T17:06:23Z', 'updated_at': '2023-07-13T17:06:23Z', 'author_association': 'NONE', 'body': '<details>\n<summary>Show benchmarks</summary>\n\nPyArrow==8.0.0\n\n<details>\n<summary>Show updated benchmarks!</summary>\n\n### Benchmark: benchmark_array_xd.json\n\n| metric | read_batch_formatted_as_numpy after write_array2d | read_batch_formatted_as_numpy after write_flattened_sequence | read_batch_formatted_as_numpy after write_nested_sequence | read_batch_unformated after write_array2d | read_batch_unformated after write_flattened_sequence | read_batch_unformated after write_nested_sequence | read_col_formatted_as_numpy after write_array2d | read_col_formatted_as_numpy after write_flattened_sequence | read_col_formatted_as_numpy after write_nested_sequence | read_col_unformated after write_array2d | read_col_unformated after write_flattened_sequence | read_col_unformated after write_nested_sequence | read_formatted_as_numpy after write_array2d | read_formatted_as_numpy after write_flattened_sequence | read_formatted_as_numpy after write_nested_sequence | read_unformated after write_array2d | read_unformated after write_flattened_sequence | read_unformated after write_nested_sequence | write_array2d | write_flattened_sequence | write_nested_sequence |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.007224 / 0.011353 (-0.004129) | 0.004506 / 0.011008 (-0.006503) | 0.096729 / 0.038508 (0.058221) | 0.082394 / 0.023109 (0.059284) | 0.390954 / 0.275898 (0.115056) | 0.416647 / 0.323480 (0.093167) | 0.005894 / 0.007986 (-0.002092) | 0.003756 / 0.004328 (-0.000572) | 0.075800 / 0.004250 (0.071549) | 0.062683 / 0.037052 (0.025631) | 0.398959 / 0.258489 (0.140470) | 0.436624 / 0.293841 (0.142783) | 0.034650 / 0.128546 (-0.093896) | 0.009655 / 0.075646 (-0.065991) | 0.315761 / 0.419271 (-0.103511) | 0.060957 / 0.043533 (0.017424) | 0.385649 / 0.255139 (0.130510) | 0.394022 / 0.283200 (0.110822) | 0.024601 / 0.141683 (-0.117082) | 1.729586 / 1.452155 (0.277431) | 1.724153 / 1.492716 (0.231437) |\n\n### Benchmark: benchmark_getitem\\_100B.json\n\n| metric | get_batch_of\\_1024\\_random_rows | get_batch_of\\_1024\\_rows | get_first_row | get_last_row |\n|--------|---|---|---|---|\n| new / old (diff) | 0.207070 / 0.018006 (0.189063) | 0.466502 / 0.000490 (0.466012) | 0.010739 / 0.000200 (0.010540) | 0.000214 / 0.000054 (0.000160) |\n\n### Benchmark: benchmark_indices_mapping.json\n\n| metric | select | shard | shuffle | sort | train_test_split |\n|--------|---|---|---|---|---|\n| new / old (diff) | 0.031633 / 0.037411 (-0.005779) | 0.095345 / 0.014526 (0.080819) | 0.105399 / 0.176557 (-0.071157) | 0.174173 / 0.737135 (-0.562962) | 0.104207 / 0.296338 (-0.192132) |\n\n### Benchmark: benchmark_iterating.json\n\n| metric | read 5000 | read 50000 | read_batch 50000 10 | read_batch 50000 100 | read_batch 50000 1000 | read_formatted numpy 5000 | read_formatted pandas 5000 | read_formatted tensorflow 5000 | read_formatted torch 5000 | read_formatted_batch numpy 5000 10 | read_formatted_batch numpy 5000 1000 | shuffled read 5000 | shuffled read 50000 | shuffled read_batch 50000 10 | shuffled read_batch 50000 100 | shuffled read_batch 50000 1000 | shuffled read_formatted numpy 5000 | shuffled read_formatted_batch numpy 5000 10 | shuffled read_formatted_batch numpy 5000 1000 |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.435312 / 0.215209 (0.220103) | 4.265600 / 2.077655 (2.187946) | 2.056500 / 1.504120 (0.552380) | 1.848023 / 1.541195 (0.306828) | 1.946156 / 1.468490 (0.477666) | 0.557788 / 4.584777 (-4.026989) | 4.070289 / 3.745712 (0.324577) | 3.608027 / 5.269862 (-1.661835) | 2.214556 / 4.565676 (-2.351121) | 0.062623 / 0.424275 (-0.361652) | 0.008083 / 0.007607 (0.000476) | 0.491782 / 0.226044 (0.265738) | 4.989963 / 2.268929 (2.721035) | 2.575867 / 55.444624 (-52.868757) | 2.208045 / 6.876477 (-4.668431) | 2.364184 / 2.142072 (0.222112) | 0.633925 / 4.805227 (-4.171302) | 0.144323 / 6.500664 (-6.356341) | 0.067505 / 0.075469 (-0.007965) |\n\n### Benchmark: benchmark_map_filter.json\n\n| metric | filter | map fast-tokenizer batched | map identity | map identity batched | map no-op batched | map no-op batched numpy | map no-op batched pandas | map no-op batched pytorch | map no-op batched tensorflow |\n|--------|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 1.467219 / 1.841788 (-0.374569) | 22.334967 / 8.074308 (14.260659) | 15.715747 / 10.191392 (5.524355) | 0.175443 / 0.680424 (-0.504980) | 0.026165 / 0.534201 (-0.508036) | 0.490675 / 0.579283 (-0.088608) | 0.509211 / 0.434364 (0.074847) | 0.586303 / 0.540337 (0.045965) | 0.785052 / 1.386936 (-0.601884) |\n\n</details>\nPyArrow==latest\n\n<details>\n<summary>Show updated benchmarks!</summary>\n\n### Benchmark: benchmark_array_xd.json\n\n| metric | read_batch_formatted_as_numpy after write_array2d | read_batch_formatted_as_numpy after write_flattened_sequence | read_batch_formatted_as_numpy after write_nested_sequence | read_batch_unformated after write_array2d | read_batch_unformated after write_flattened_sequence | read_batch_unformated after write_nested_sequence | read_col_formatted_as_numpy after write_array2d | read_col_formatted_

[{'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1634236583', 'html_url': 'https://github.com/huggingface/datasets/pull/6027#issuecomment-1634236583', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/6027', 'id': 1634236583, 'node_id': 'IC_kwDODunzps5haHin', 'user': {'login': 'HuggingFaceDocBuilderDev', 'id': 99929124, 'node_id': 'U_kgDOBfTMJA', 'avatar_url': 'https://avatars.githubusercontent.com/u/99929124?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/HuggingFaceDocBuilderDev', 'html_url': 'https://github.com/HuggingFaceDocBuilderDev', 'followers_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/followers', 'following_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/following{/other_user}', 'gists_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/subscriptions', 'organizations_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/orgs', 'repos_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/repos', 'events_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/events{/privacy}', 'received_events_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-07-13T13:21:56Z', 'updated_at': '2023-07-13T13:58:02Z', 'author_association': 'NONE', 'body': '_The documentation is not available anymore as the PR was closed or merged._', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1634236583/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1634245327', 'html_url': 'https://github.com/huggingface/datasets/pull/6027#issuecomment-1634245327', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/6027', 'id': 1634245327, 'node_id': 'IC_kwDODunzps5haJrP', 'user': {'login': 'github-actions[bot]', 'id': 41898282, 'node_id': 'MDM6Qm90NDE4OTgyODI=', 'avatar_url': 'https://avatars.githubusercontent.com/in/15368?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/github-actions%5Bbot%5D', 'html_url': 'https://github.com/apps/github-actions', 'followers_url': 'https://api.github.com/users/github-actions%5Bbot%5D/followers', 'following_url': 'https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}', 'gists_url': 'https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/github-actions%5Bbot%5D/subscriptions', 'organizations_url': 'https://api.github.com/users/github-actions%5Bbot%5D/orgs', 'repos_url': 'https://api.github.com/users/github-actions%5Bbot%5D/repos', 'events_url': 'https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}', 'received_events_url': 'https://api.github.com/users/github-actions%5Bbot%5D/received_events', 'type': 'Bot', 'site_admin': False}, 'created_at': '2023-07-13T13:27:23Z', 'updated_at': '2023-07-13T13:27:23Z', 'author_association': 'NONE', 'body': '<details>\n<summary>Show benchmarks</summary>\n\nPyArrow==8.0.0\n\n<details>\n<summary>Show updated benchmarks!</summary>\n\n### Benchmark: benchmark_array_xd.json\n\n| metric | read_batch_formatted_as_numpy after write_array2d | read_batch_formatted_as_numpy after write_flattened_sequence | read_batch_formatted_as_numpy after write_nested_sequence | read_batch_unformated after write_array2d | read_batch_unformated after write_flattened_sequence | read_batch_unformated after write_nested_sequence | read_col_formatted_as_numpy after write_array2d | read_col_formatted_as_numpy after write_flattened_sequence | read_col_formatted_as_numpy after write_nested_sequence | read_col_unformated after write_array2d | read_col_unformated after write_flattened_sequence | read_col_unformated after write_nested_sequence | read_formatted_as_numpy after write_array2d | read_formatted_as_numpy after write_flattened_sequence | read_formatted_as_numpy after write_nested_sequence | read_unformated after write_array2d | read_unformated after write_flattened_sequence | read_unformated after write_nested_sequence | write_array2d | write_flattened_sequence | write_nested_sequence |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.008698 / 0.011353 (-0.002655) | 0.005250 / 0.011008 (-0.005758) | 0.104101 / 0.038508 (0.065593) | 0.085021 / 0.023109 (0.061912) | 0.426653 / 0.275898 (0.150755) | 0.460449 / 0.323480 (0.136969) | 0.005222 / 0.007986 (-0.002763) | 0.006280 / 0.004328 (0.001951) | 0.083458 / 0.004250 (0.079207) | 0.066132 / 0.037052 (0.029079) | 0.433416 / 0.258489 (0.174927) | 0.482718 / 0.293841 (0.188877) | 0.048872 / 0.128546 (-0.079675) | 0.013699 / 0.075646 (-0.061948) | 0.365660 / 0.419271 (-0.053611) | 0.071008 / 0.043533 (0.027475) | 0.428688 / 0.255139 (0.173549) | 0.443554 / 0.283200 (0.160354) | 0.035901 / 0.141683 (-0.105782) | 1.829296 / 1.452155 (0.377141) | 1.862351 / 1.492716 (0.369635) |\n\n### Benchmark: benchmark_getitem\\_100B.json\n\n| metric | get_batch_of\\_1024\\_random_rows | get_batch_of\\_1024\\_rows | get_first_row | get_last_row |\n|--------|---|---|---|---|\n| new / old (diff) | 0.236284 / 0.018006 (0.218278) | 0.584075 / 0.000490 (0.583585) | 0.004634 / 0.000200 (0.004434) | 0.000125 / 0.000054 (0.000070) |\n\n### Benchmark: benchmark_indices_mapping.json\n\n| metric | select | shard | shuffle | sort | train_test_split |\n|--------|---|---|---|---|---|\n| new / old (diff) | 0.034723 / 0.037411 (-0.002688) | 0.100989 / 0.014526 (0.086464) | 0.113722 / 0.176557 (-0.062834) | 0.187659 / 0.737135 (-0.549477) | 0.113937 / 0.296338 (-0.182401) |\n\n### Benchmark: benchmark_iterating.json\n\n| metric | read 5000 | read 50000 | read_batch 50000 10 | read_batch 50000 100 | read_batch 50000 1000 | read_formatted numpy 5000 | read_formatted pandas 5000 | read_formatted tensorflow 5000 | read_formatted torch 5000 | read_formatted_batch numpy 5000 10 | read_formatted_batch numpy 5000 1000 | shuffled read 5000 | shuffled read 50000 | shuffled read_batch 50000 10 | shuffled read_batch 50000 100 | shuffled read_batch 50000 1000 | shuffled read_formatted numpy 5000 | shuffled read_formatted_batch numpy 5000 10 | shuffled read_formatted_batch numpy 5000 1000 |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.587500 / 0.215209 (0.372291) | 5.847371 / 2.077655 (3.769716) | 2.599691 / 1.504120 (1.095571) | 2.246187 / 1.541195 (0.704992) | 2.419126 / 1.468490 (0.950636) | 0.847327 / 4.584777 (-3.737450) | 5.230438 / 3.745712 (1.484726) | 7.539021 / 5.269862 (2.269160) | 4.617473 / 4.565676 (0.051797) | 0.103620 / 0.424275 (-0.320655) | 0.009195 / 0.007607 (0.001588) | 0.714247 / 0.226044 (0.488203) | 7.331621 / 2.268929 (5.062693) | 3.416575 / 55.444624 (-52.028049) | 2.649467 / 6.876477 (-4.227009) | 2.928091 / 2.142072 (0.786018) | 1.002155 / 4.805227 (-3.803072) | 0.210790 / 6.500664 (-6.289874) | 0.081303 / 0.075469 (0.005834) |\n\n### Benchmark: benchmark_map_filter.json\n\n| metric | filter | map fast-tokenizer batched | map identity | map identity batched | map no-op batched | map no-op batched numpy | map no-op batched pandas | map no-op batched pytorch | map no-op batched tensorflow |\n|--------|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 1.655431 / 1.841788 (-0.186357) | 24.069595 / 8.074308 (15.995287) | 20.923766 / 10.191392 (10.732374) | 0.232021 / 0.680424 (-0.448403) | 0.026355 / 0.534201 (-0.507846) | 0.496830 / 0.579283 (-0.082453) | 0.582620 / 0.434364 (0.148257) | 0.551227 / 0.540337 (0.010890) | 0.756389 / 1.386936 (-0.630547) |\n\n</details>\nPyArrow==latest\n\n<details>\n<summary>Show updated benchmarks!</summary>\n\n### Benchmark: benchmark_array_xd.json\n\n| metric | read_batch_formatted_as_numpy after write_array2d | read_batch_formatted_as_numpy after write_flattened_sequence | read_batch_formatted_as_numpy after write_nested_sequence | read_batch_unformated after write_array2d | read_batch_unformated after write_flattened_sequence | read_batch_unformated after write_nested_sequence | read_col_formatted_as_numpy after write_array2d | read_col_formatted_as_numpy after write_flattened_sequence | read_col_formatted_as_numpy after write_nested_sequence | read_col_unformated after write_array2d | read_col_unformated after write_flattened_sequence | read_col_unformated after write_nested_sequence | read_formatted_as_numpy after write_array2d | read_formatted_as_numpy after write_flattened_sequence | read_formatted_as_numpy after write_nested_sequence | read_unformated after write_array2d | read_unformated after write_flattened_sequence | read_unformated after write_nested_sequence | write_array2d | write_flattened_sequence | write_nested_sequence |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.009329 / 0.011353 (-0.002024) | 0.005045 / 0.011008 (-0.005964) | 0.082116 / 0.038508 (0.043608) | 0.082420 / 0.023109 (0.059311) | 0.502513 / 0.275898 (0.226615) | 0.526098 / 0.323480 (0.202618) | 0.007468 / 0.007986 (-0.000517) | 0.005477 / 0.004328 (0.001148) | 0.082617 / 0.004250 (0.078367) | 0.070292 / 0.037052 (0.033239) | 0.503290 / 0.258489 (0.244801) | 0.541631 / 0.293841 (0.247790) | 0.050826 / 0.128546 (-0.077721) | 0.014699 / 0.075646 (-0.060948) | 0.094441 / 0.419271 (-0.324830) | 0.065034 / 0.043533 (0.021501) | 0.486778 / 0.255139 (0.231639) | 0.516907 / 0.283200 (0.233707) | 0.045140 / 0.141683 (-0.096543) | 1.831676 / 1.452155 (0.379521) | 1.910865 / 1.492716 (0.418149) |\n\n### Benchmark: benchmark_getitem\\_100B.json\n\n| metric | get_batch_of\\_1024\\_random_rows | get_batch_of\\_1024\\_rows | get_first_row | get_last_row |\n|--------|---|---|---|---|\n| new / old (diff) | 0.286818 / 0.018006 (0.268812) | 0.558621 / 0.000490 (0.558131) | 0.002830 / 0.000200 (0.002630) | 0.000148 / 0.000054 (0.000094) |\n\n### Benchmark: benchmark_indices_mapping.json\n\n| metric | select | shard | shuffle | sort | train_test_split |\n|--------|---|---|---|---|---|\n| new / old (diff) | 0.036716 / 0.037411 (-0.000696) | 0.107830 / 0.014526 (0.093305) | 0.116368 / 0.176557 (-0.060188) | 0.178401 / 0.737135 (-0.558734) | 0.124729 / 0.296338 (-0.171609) |\n\n### Benchmark: benchmark_iterating.json\n\n| metric | read 5000 | read 50000 | read_batch 50000 10 | read_batch 50000 100 | read_batch 50000 1000 | read_formatted numpy 5000 | read_formatted pandas 5000 | read_formatted tensorflow 5000 | read_formatted torch 5000 | read_formatted_batch numpy 5000 10 | read_formatted_batch numpy 5000 1000 | shuffled read 5000 | shuffled read 50000 | shuffled read_batch 50000 10 | shuffled read_batch 50000 100 | shuffled read_batch 50000 1000 | shuffled read_formatted numpy 5000 | shuffled read_formatted_batch numpy 5000 10 | shuffled read_formatted_batch numpy 5000 1000 |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.633557 / 0.215209 (0.418348) | 6.423135 / 2.077655 (4.345480) | 2.981883 / 1.504120 (1.477763) | 2.755592 / 1.541195 (1.214398) | 2.769337 / 1.468490 (1.300847) | 0.836219 / 4.584777 (-3.748558) | 5.302030 / 3.745712 (1.556318) | 7.463960 / 5.269862 (2.194098) | 4.427254 / 4.565676 (-0.138422) | 0.095990 / 0.424275 (-0.328285) | 0.009264 / 0.007607 (0.001657) | 0.770642 / 0.226044 (0.544597) | 7.779667 / 2.268929 (5.510739) | 3.799115 / 55.444624 (-51.645509) | 3.212560 / 6.876477 (-3.663917) | 3.281657 / 2.142072 (1.139584) | 1.044981 / 4.805227 (-3.760246) | 0.210693 / 6.500664 (-6.289971) | 0.079466 / 0.075469 (0.003997) |\n\n### Benchmark: benchmark_map_filter.json\n\n| metric | filter | map fast-tokenizer batched | map identity | map identity batched | map no-op batched | map no-op batched numpy | map no-op batched pandas | map no-op batched pytorch | map no-op batched tensorflow |\n|--------|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 1.793155 / 1.841788 (-0.048632) | 24.691127 / 8.074308 (16.616819) | 22.083150 / 10.191392 (11.891758) | 0.242246 / 0.680424 (-0.438178) | 0.028001 / 0.534201 (-0.506200) | 0.494061 / 0.579283 (-0.085222) | 0.599288 / 0.434364 (0.164924) | 0.552101 / 0.540337 (0.011764) | 0.784093 / 1.386936 (-0.602843) |\n\n</details>\n</details>\n\n![](https://cml.dev/watermark.png#cd429c39604af34bc3a3ba1f463329b23fcbc1e3 "CML watermark")\n', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1634245327/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1634310188', 'html_url': 'https://github.com/huggingface/datasets/pull/6027#issuecomment-1634310188', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/6027', 'id': 1634310188, 'node_id': 'IC_kwDODunzps5haZgs', 'user': {'login': 'github-actions[bot]', 'id': 41898282, 'node_id': 'MDM6Qm90NDE4OTgyODI=', 'avatar_url': 'https://avatars.githubusercontent.com/in/15368?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/github-actions%5Bbot%5D', 'html_url': 'https://github.com/apps/github-actions', 'followers_url': 'https://api.github.com/users/github-actions%5Bbot%5D/followers', 'following_url': 'https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}', 'gists_url': 'https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/github-actions%5Bbot%5D/subscriptions', 'organizations_url': 'https://api.github.com/users/github-actions%5Bbot%5D/orgs', 'repos_url': 'https://api.github.com/users/github-actions%5Bbot%5D/repos', 'events_url': 'https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}', 'received_events_url': 'https://api.github.com/users/github-actions%5Bbot%5D/received_events', 'type': 'Bot', 'site_admin': False}, 'created_at': '2023-07-13T14:06:20Z', 'updated_at': '2023-07-13T14:06:20Z', 'author_association': 'NONE', 'body': '<details>\n<summary>Show benchmarks</summary>\n\nPyArrow==8.0.0\n\n<details>\n<summary>Show updated benchmarks!</summary>\n\n### Benchmark: benchmark_array_xd.json\n\n| metric | read_batch_formatted_as_numpy after write_array2d | read_batch_formatted_as_numpy after write_flattened_sequence | read_batch_formatted_as_numpy after write_nested_sequence | read_batch_unformated after write_array2d | read_batch_unformated after write_flattened_sequence | read_batch_unformated after write_nested_sequence | read_col_formatted_as_numpy after write_array2d | read_col_formatted_as_numpy after write_flattened_sequence | read_col_formatted_as_numpy after write_nested_sequence | read_col_unformated after write_array2d | read_col_unformated after write_flattened_sequence | read_col_unformated after write_nested_sequence | read_formatted_as_numpy after write_array2d | read_formatted_as_numpy after write_flattened_sequence | read_formatted_as_numpy after write_nested_sequence | read_unformated after write_array2d | read_unformated after write_flattened_sequence | read_unformated after write_nested_sequence | write_array2d | write_flattened_sequence | write_nested_sequence |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.006658 / 0.011353 (-0.004695) | 0.004044 / 0.011008 (-0.006965) | 0.085844 / 0.038508 (0.047336) | 0.077147 / 0.023109 (0.054038) | 0.344387 / 0.275898 (0.068489) | 0.376718 / 0.323480 (0.053238) | 0.005537 / 0.007986 (-0.002448) | 0.003452 / 0.004328 (-0.000876) | 0.065326 / 0.004250 (0.061076) | 0.057639 / 0.037052 (0.020587) | 0.352363 / 0.258489 (0.093873) | 0.378939 / 0.293841 (0.085098) | 0.031259 / 0.128546 (-0.097287) | 0.008464 / 0.075646 (-0.067183) | 0.289076 / 0.419271 (-0.130195) | 0.052991 / 0.043533 (0.009459) | 0.346053 / 0.255139 (0.090914) | 0.362761 / 0.283200 (0.079561) | 0.023501 / 0.141683 (-0.118182) | 1.478312 / 1.452155 (0.026157) | 1.545437 / 1.492716 (0.052721) |\n\n### Benchmark: benchmark_getitem\\_100B.json\n\n| metric | get_batch_of\\_1024\\_random_rows | get_batch_of\\_1024\\_rows | get_first_row | get_last_row |\n|--------|---|---|---|---|\n| new / old (diff) | 0.202964 / 0.018006 (0.184957) | 0.534793 / 0.000490 (0.534303) | 0.006025 / 0.000200 (0.005825) | 0.000225 / 0.000054 (0.000171) |\n\n### Benchmark: benchmark_indices_mapping.json\n\n| metric | select | shard | shuffle | sort | train_test_split |\n|--------|---|---|---|---|---|\n| new / old (diff) | 0.029418 / 0.037411 (-0.007993) | 0.084297 / 0.014526 (0.069771) | 0.096702 / 0.176557 (-0.079855) | 0.157355 / 0.737135 (-0.579781) | 0.097858 / 0.296338 (-0.198480) |\n\n### Benchmark: benchmark_iterating.json\n\n| metric | read 5000 | read 50000 | read_batch 50000 10 | read_batch 50000 100 | read_batch 50000 1000 | read_formatted numpy 5000 | read_formatted pandas 5000 | read_formatted tensorflow 5000 | read_formatted torch 5000 | read_formatted_batch numpy 5000 10 | read_formatted_batch numpy 5000 1000 | shuffled read 5000 | shuffled read 50000 | shuffled read_batch 50000 10 | shuffled read_batch 50000 100 | shuffled read_batch 50000 1000 | shuffled read_formatted numpy 5000 | shuffled read_formatted_batch numpy 5000 10 | shuffled read_formatted_batch numpy 5000 1000 |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.380728 / 0.215209 (0.165519) | 3.787712 / 2.077655 (1.710057) | 1.836393 / 1.504120 (0.332273) | 1.678415 / 1.541195 (0.137220) | 1.781800 / 1.468490 (0.313310) | 0.478677 / 4.584777 (-4.106100) | 3.614080 / 3.745712 (-0.131632) | 3.255637 / 5.269862 (-2.014225) | 2.063642 / 4.565676 (-2.502035) | 0.056470 / 0.424275 (-0.367805) | 0.007408 / 0.007607 (-0.000199) | 0.459155 / 0.226044 (0.233111) | 4.586679 / 2.268929 (2.317750) | 2.305737 / 55.444624 (-53.138888) | 1.954755 / 6.876477 (-4.921721) | 2.190809 / 2.142072 (0.048737) | 0.572426 / 4.805227 (-4.232802) | 0.130349 / 6.500664 (-6.370315) | 0.059346 / 0.075469 (-0.016124) |\n\n### Benchmark: benchmark_map_filter.json\n\n| metric | filter | map fast-tokenizer batched | map identity | map identity batched | map no-op batched | map no-op batched numpy | map no-op batched pandas | map no-op batched pytorch | map no-op batched tensorflow |\n|--------|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 1.253671 / 1.841788 (-0.588117) | 19.509015 / 8.074308 (11.434706) | 13.951349 / 10.191392 (3.759957) | 0.171038 / 0.680424 (-0.509386) | 0.018826 / 0.534201 (-0.515375) | 0.394642 / 0.579283 (-0.184642) | 0.419614 / 0.434364 (-0.014750) | 0.470931 / 0.540337 (-0.069406) | 0.643858 / 1.386936 (-0.743078) |\n\n</details>\nPyArrow==latest\n\n<details>\n<summary>Show updated benchmarks!</summary>\n\n### Benchmark: benchmark_array_xd.json\n\n| metric | read_batch_formatted_as_numpy after write_array2d | read_batch_formatted_as_numpy after write_flattened_sequence | read_batch_formatted_as_numpy after write_nested_sequence | read_batch_unformated after write_array2d | read_batch_unformated after write_flattened_sequence | read_batch_unformated after write_nested_sequence | read_col_formatted_as_numpy after write_array2d | read_col_formatted_as_numpy after write_flattened_sequence | read_col_formatted_as_numpy after write_nested_sequ

[{'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1634173316', 'html_url': 'https://github.com/huggingface/datasets/pull/6026#issuecomment-1634173316', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/6026', 'id': 1634173316, 'node_id': 'IC_kwDODunzps5hZ4GE', 'user': {'login': 'HuggingFaceDocBuilderDev', 'id': 99929124, 'node_id': 'U_kgDOBfTMJA', 'avatar_url': 'https://avatars.githubusercontent.com/u/99929124?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/HuggingFaceDocBuilderDev', 'html_url': 'https://github.com/HuggingFaceDocBuilderDev', 'followers_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/followers', 'following_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/following{/other_user}', 'gists_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/subscriptions', 'organizations_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/orgs', 'repos_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/repos', 'events_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/events{/privacy}', 'received_events_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-07-13T12:40:01Z', 'updated_at': '2023-07-13T12:40:01Z', 'author_association': 'NONE', 'body': 'The docs for this PR live [here](https://moon-ci-docs.huggingface.co/docs/datasets/pr_6026). All of your documentation changes will be reflected on that endpoint.', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1634173316/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1634177672', 'html_url': 'https://github.com/huggingface/datasets/pull/6026#issuecomment-1634177672', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/6026', 'id': 1634177672, 'node_id': 'IC_kwDODunzps5hZ5KI', 'user': {'login': 'github-actions[bot]', 'id': 41898282, 'node_id': 'MDM6Qm90NDE4OTgyODI=', 'avatar_url': 'https://avatars.githubusercontent.com/in/15368?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/github-actions%5Bbot%5D', 'html_url': 'https://github.com/apps/github-actions', 'followers_url': 'https://api.github.com/users/github-actions%5Bbot%5D/followers', 'following_url': 'https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}', 'gists_url': 'https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/github-actions%5Bbot%5D/subscriptions', 'organizations_url': 'https://api.github.com/users/github-actions%5Bbot%5D/orgs', 'repos_url': 'https://api.github.com/users/github-actions%5Bbot%5D/repos', 'events_url': 'https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}', 'received_events_url': 'https://api.github.com/users/github-actions%5Bbot%5D/received_events', 'type': 'Bot', 'site_admin': False}, 'created_at': '2023-07-13T12:42:56Z', 'updated_at': '2023-07-13T12:42:56Z', 'author_association': 'NONE', 'body': '<details>\n<summary>Show benchmarks</summary>\n\nPyArrow==8.0.0\n\n<details>\n<summary>Show updated benchmarks!</summary>\n\n### Benchmark: benchmark_array_xd.json\n\n| metric | read_batch_formatted_as_numpy after write_array2d | read_batch_formatted_as_numpy after write_flattened_sequence | read_batch_formatted_as_numpy after write_nested_sequence | read_batch_unformated after write_array2d | read_batch_unformated after write_flattened_sequence | read_batch_unformated after write_nested_sequence | read_col_formatted_as_numpy after write_array2d | read_col_formatted_as_numpy after write_flattened_sequence | read_col_formatted_as_numpy after write_nested_sequence | read_col_unformated after write_array2d | read_col_unformated after write_flattened_sequence | read_col_unformated after write_nested_sequence | read_formatted_as_numpy after write_array2d | read_formatted_as_numpy after write_flattened_sequence | read_formatted_as_numpy after write_nested_sequence | read_unformated after write_array2d | read_unformated after write_flattened_sequence | read_unformated after write_nested_sequence | write_array2d | write_flattened_sequence | write_nested_sequence |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.006444 / 0.011353 (-0.004909) | 0.003768 / 0.011008 (-0.007240) | 0.079625 / 0.038508 (0.041117) | 0.064490 / 0.023109 (0.041381) | 0.313858 / 0.275898 (0.037960) | 0.350810 / 0.323480 (0.027330) | 0.004804 / 0.007986 (-0.003182) | 0.002904 / 0.004328 (-0.001425) | 0.061728 / 0.004250 (0.057477) | 0.052265 / 0.037052 (0.015213) | 0.321246 / 0.258489 (0.062757) | 0.353873 / 0.293841 (0.060032) | 0.027510 / 0.128546 (-0.101036) | 0.007942 / 0.075646 (-0.067704) | 0.260518 / 0.419271 (-0.158754) | 0.045686 / 0.043533 (0.002153) | 0.316821 / 0.255139 (0.061682) | 0.337086 / 0.283200 (0.053886) | 0.022188 / 0.141683 (-0.119495) | 1.427345 / 1.452155 (-0.024810) | 1.476059 / 1.492716 (-0.016657) |\n\n### Benchmark: benchmark_getitem\\_100B.json\n\n| metric | get_batch_of\\_1024\\_random_rows | get_batch_of\\_1024\\_rows | get_first_row | get_last_row |\n|--------|---|---|---|---|\n| new / old (diff) | 0.189640 / 0.018006 (0.171634) | 0.429724 / 0.000490 (0.429235) | 0.005314 / 0.000200 (0.005114) | 0.000076 / 0.000054 (0.000021) |\n\n### Benchmark: benchmark_indices_mapping.json\n\n| metric | select | shard | shuffle | sort | train_test_split |\n|--------|---|---|---|---|---|\n| new / old (diff) | 0.024412 / 0.037411 (-0.013000) | 0.073488 / 0.014526 (0.058962) | 0.083843 / 0.176557 (-0.092714) | 0.147849 / 0.737135 (-0.589286) | 0.085465 / 0.296338 (-0.210873) |\n\n### Benchmark: benchmark_iterating.json\n\n| metric | read 5000 | read 50000 | read_batch 50000 10 | read_batch 50000 100 | read_batch 50000 1000 | read_formatted numpy 5000 | read_formatted pandas 5000 | read_formatted tensorflow 5000 | read_formatted torch 5000 | read_formatted_batch numpy 5000 10 | read_formatted_batch numpy 5000 1000 | shuffled read 5000 | shuffled read 50000 | shuffled read_batch 50000 10 | shuffled read_batch 50000 100 | shuffled read_batch 50000 1000 | shuffled read_formatted numpy 5000 | shuffled read_formatted_batch numpy 5000 10 | shuffled read_formatted_batch numpy 5000 1000 |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.405314 / 0.215209 (0.190105) | 4.071471 / 2.077655 (1.993816) | 1.916252 / 1.504120 (0.412132) | 1.721616 / 1.541195 (0.180422) | 1.807187 / 1.468490 (0.338697) | 0.498045 / 4.584777 (-4.086732) | 3.057526 / 3.745712 (-0.688187) | 4.451424 / 5.269862 (-0.818437) | 2.764020 / 4.565676 (-1.801656) | 0.057665 / 0.424275 (-0.366610) | 0.006679 / 0.007607 (-0.000928) | 0.485733 / 0.226044 (0.259688) | 4.844367 / 2.268929 (2.575438) | 2.435359 / 55.444624 (-53.009265) | 2.111478 / 6.876477 (-4.764999) | 2.377448 / 2.142072 (0.235375) | 0.587997 / 4.805227 (-4.217230) | 0.125545 / 6.500664 (-6.375120) | 0.061509 / 0.075469 (-0.013960) |\n\n### Benchmark: benchmark_map_filter.json\n\n| metric | filter | map fast-tokenizer batched | map identity | map identity batched | map no-op batched | map no-op batched numpy | map no-op batched pandas | map no-op batched pytorch | map no-op batched tensorflow |\n|--------|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 1.229210 / 1.841788 (-0.612577) | 18.553994 / 8.074308 (10.479686) | 14.037877 / 10.191392 (3.846485) | 0.144230 / 0.680424 (-0.536194) | 0.016891 / 0.534201 (-0.517310) | 0.329039 / 0.579283 (-0.250244) | 0.357269 / 0.434364 (-0.077095) | 0.384222 / 0.540337 (-0.156115) | 0.521292 / 1.386936 (-0.865644) |\n\n</details>\nPyArrow==latest\n\n<details>\n<summary>Show updated benchmarks!</summary>\n\n### Benchmark: benchmark_array_xd.json\n\n| metric | read_batch_formatted_as_numpy after write_array2d | read_batch_formatted_as_numpy after write_flattened_sequence | read_batch_formatted_as_numpy after write_nested_sequence | read_batch_unformated after write_array2d | read_batch_unformated after write_flattened_sequence | read_batch_unformated after write_nested_sequence | read_col_formatted_as_numpy after write_array2d | read_col_formatted_as_numpy after write_flattened_sequence | read_col_formatted_as_numpy after write_nested_sequence | read_col_unformated after write_array2d | read_col_unformated after write_flattened_sequence | read_col_unformated after write_nested_sequence | read_formatted_as_numpy after write_array2d | read_formatted_as_numpy after write_flattened_sequence | read_formatted_as_numpy after write_nested_sequence | read_unformated after write_array2d | read_unformated after write_flattened_sequence | read_unformated after write_nested_sequence | write_array2d | write_flattened_sequence | write_nested_sequence |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.006359 / 0.011353 (-0.004994) | 0.003721 / 0.011008 (-0.007287) | 0.062047 / 0.038508 (0.023539) | 0.065267 / 0.023109 (0.042158) | 0.360164 / 0.275898 (0.084266) | 0.402292 / 0.323480 (0.078812) | 0.005603 / 0.007986 (-0.002382) | 0.002966 / 0.004328 (-0.001363) | 0.062580 / 0.004250 (0.058330) | 0.053634 / 0.037052 (0.016582) | 0.362210 / 0.258489 (0.103721) | 0.404285 / 0.293841 (0.110444) | 0.027567 / 0.128546 (-0.100979) | 0.008119 / 0.075646 (-0.067528) | 0.067577 / 0.419271 (-0.351694) | 0.042867 / 0.043533 (-0.000666) | 0.361576 / 0.255139 (0.106437) | 0.389061 / 0.283200 (0.105862) | 0.021923 / 0.141683 (-0.119760) | 1.446259 / 1.452155 (-0.005895) | 1.490724 / 1.492716 (-0.001992) |\n\n### Benchmark: benchmark_getitem\\_100B.json\n\n| metric | get_batch_of\\_1024\\_random_rows | get_batch_of\\_1024\\_rows | get_first_row | get_last_row |\n|--------|---|---|---|---|\n| new / old (diff) | 0.206433 / 0.018006 (0.188427) | 0.424178 / 0.000490 (0.423688) | 0.002340 / 0.000200 (0.002140) | 0.000069 / 0.000054 (0.000015) |\n\n### Benchmark: benchmark_indices_mapping.json\n\n| metric | select | shard | shuffle | sort | train_test_split |\n|--------|---|---|---|---|---|\n| new / old (diff) | 0.024955 / 0.037411 (-0.012456) | 0.077446 / 0.014526 (0.062920) | 0.088540 / 0.176557 (-0.088017) | 0.141225 / 0.737135 (-0.595910) | 0.089747 / 0.296338 (-0.206592) |\n\n### Benchmark: benchmark_iterating.json\n\n| metric | read 5000 | read 50000 | read_batch 50000 10 | read_batch 50000 100 | read_batch 50000 1000 | read_formatted numpy 5000 | read_formatted pandas 5000 | read_formatted tensorflow 5000 | read_formatted torch 5000 | read_formatted_batch numpy 5000 10 | read_formatted_batch numpy 5000 1000 | shuffled read 5000 | shuffled read 50000 | shuffled read_batch 50000 10 | shuffled read_batch 50000 100 | shuffled read_batch 50000 1000 | shuffled read_formatted numpy 5000 | shuffled read_formatted_batch numpy 5000 10 | shuffled read_formatted_batch numpy 5000 1000 |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.443738 / 0.215209 (0.228529) | 4.208887 / 2.077655 (2.131233) | 2.155127 / 1.504120 (0.651007) | 2.028178 / 1.541195 (0.486983) | 2.084903 / 1.468490 (0.616413) | 0.497530 / 4.584777 (-4.087247) | 3.069012 / 3.745712 (-0.676700) | 3.025184 / 5.269862 (-2.244678) | 1.904687 / 4.565676 (-2.660990) | 0.057526 / 0.424275 (-0.366749) | 0.006482 / 0.007607 (-0.001125) | 0.494692 / 0.226044 (0.268647) | 4.944437 / 2.268929 (2.675508) | 2.655989 / 55.444624 (-52.788635) | 2.331677 / 6.876477 (-4.544800) | 2.382396 / 2.142072 (0.240324) | 0.582019 / 4.805227 (-4.223209) | 0.125866 / 6.500664 (-6.374799) | 0.062908 / 0.075469 (-0.012561) |\n\n### Benchmark: benchmark_map_filter.json\n\n| metric | filter | map fast-tokenizer batched | map identity | map identity batched | map no-op batched | map no-op batched numpy | map no-op batched pandas | map no-op batched pytorch | map no-op batched tensorflow |\n|--------|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 1.294612 / 1.841788 (-0.547176) | 19.016152 / 8.074308 (10.941844) | 14.088828 / 10.191392 (3.897436) | 0.160842 / 0.680424 (-0.519582) | 0.017054 / 0.534201 (-0.517146) | 0.333647 / 0.579283 (-0.245636) | 0.348094 / 0.434364 (-0.086270) | 0.394970 / 0.540337 (-0.145367) | 0.551141 / 1.386936 (-0.835795) |\n\n</details>\n</details>\n\n![](https://cml.dev/watermark.png#9e9cfe886792b30b5000808072a0f91ec8536749 "CML watermark")\n', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1634177672/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1634182632', 'html_url': 'https://github.com/huggingface/datasets/pull/6026#issuecomment-1634182632', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/6026', 'id': 1634182632, 'node_id': 'IC_kwDODunzps5hZ6Xo', 'user': {'login': 'github-actions[bot]', 'id': 41898282, 'node_id': 'MDM6Qm90NDE4OTgyODI=', 'avatar_url': 'https://avatars.githubusercontent.com/in/15368?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/github-actions%5Bbot%5D', 'html_url': 'https://github.com/apps/github-actions', 'followers_url': 'https://api.github.com/users/github-actions%5Bbot%5D/followers', 'following_url': 'https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}', 'gists_url': 'https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/github-actions%5Bbot%5D/subscriptions', 'organizations_url': 'https://api.github.com/users/github-actions%5Bbot%5D/orgs', 'repos_url': 'https://api.github.com/users/github-actions%5Bbot%5D/repos', 'events_url': 'https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}', 'received_events_url': 'https://api.github.com/users/github-actions%5Bbot%5D/received_events', 'type': 'Bot', 'site_admin': False}, 'created_at': '2023-07-13T12:46:25Z', 'updated_at': '2023-07-13T12:46:25Z', 'author_association': 'NONE', 'body': '<details>\n<summary>Show benchmarks</summary>\n\nPyArrow==8.0.0\n\n<details>\n<summary>Show updated benchmarks!</summary>\n\n### Benchmark: benchmark_array_xd.json\n\n| metric | read_batch_formatted_as_numpy after write_array2d | read_batch_formatted_as_numpy after write_flattened_sequence | read_batch_formatted_as_numpy after write_nested_sequence | read_batch_unformated after write_array2d | read_batch_unformated after write_flattened_sequence | read_batch_unformated after write_nested_sequence | read_col_formatted_as_numpy after write_array2d | read_col_formatted_as_numpy after write_flattened_sequence | read_col_formatted_as_numpy after write_nested_sequence | read_col_unformated after write_array2d | read_col_unformated after write_flattened_sequence | read_col_unformated after write_nested_sequence | read_formatted_as_numpy after write_array2d | read_formatted_as_numpy after write_flattened_sequence | read_formatted_as_numpy after write_nested_sequence | read_unformated after write_array2d | read_unformated after write_flattened_sequence | read_unformated after write_nested_sequence | write_array2d | write_flattened_sequence | write_nested_sequence |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.007442 / 0.011353 (-0.003911) | 0.004302 / 0.011008 (-0.006707) | 0.087159 / 0.038508 (0.048651) | 0.095094 / 0.023109 (0.071985) | 0.315422 / 0.275898 (0.039524) | 0.346672 / 0.323480 (0.023192) | 0.005811 / 0.007986 (-0.002174) | 0.003597 / 0.004328 (-0.000731) | 0.066400 / 0.004250 (0.062150) | 0.065947 / 0.037052 (0.028894) | 0.323269 / 0.258489 (0.064780) | 0.353309 / 0.293841 (0.059468) | 0.032268 / 0.128546 (-0.096278) | 0.008696 / 0.075646 (-0.066950) | 0.291486 / 0.419271 (-0.127786) | 0.054609 / 0.043533 (0.011076) | 0.321061 / 0.255139 (0.065922) | 0.336907 / 0.283200 (0.053707) | 0.027338 / 0.141683 (-0.114345) | 1.496442 / 1.452155 (0.044287) | 1.576946 / 1.492716 (0.084229) |\n\n### Benchmark: benchmark_getitem\\_100B.json\n\n| metric | get_batch_of\\_1024\\_random_rows | get_batch_of\\_1024\\_rows | get_first_row | get_last_row |\n|--------|---|---|---|---|\n| new / old (diff) | 0.229140 / 0.018006 (0.211134) | 0.487500 / 0.000490 (0.487010) | 0.002425 / 0.000200 (0.002225) | 0.000089 / 0.000054 (0.000034) |\n\n### Benchmark: benchmark_indices_mapping.json\n\n| metric | select | shard | shuffle | sort | train_test_split |\n|--------|---|---|---|---|---|\n| new / old (diff) | 0.029351 / 0.037411 (-0.008060) | 0.089610 / 0.014526 (0.075084) | 0.097880 / 0.176557 (-0.078676) | 0.155947 / 0.737135 (-0.581189) | 0.098593 / 0.296338 (-0.197745) |\n\n### Benchmark: benchmark_iterating.json\n\n| metric | read 5000 | read 50000 | read_batch 50000 10 | read_batch 50000 100 | read_batch 50000 1000 | read_formatted numpy 5000 | read_formatted pandas 5000 | read_formatted tensorflow 5000 | read_formatted torch 5000 | read_formatted_batch numpy 5000 10 | read_formatted_batch numpy 5000 1000 | shuffled read 5000 | shuffled read 50000 | shuffled read_batch 50000 10 | shuffled read_batch 50000 100 | shuffled read_batch 50000 1000 | shuffled read_formatted numpy 5000 | shuffled read_formatted_batch numpy 5000 10 | shuffled read_formatted_batch numpy 5000 1000 |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.382911 / 0.215209 (0.167702) | 3.820363 / 2.077655 (1.742708) | 1.866385 / 1.504120 (0.362265) | 1.712910 / 1.541195 (0.171716) | 1.813863 / 1.468490 (0.345373) | 0.484884 / 4.584777 (-4.099893) | 3.678911 / 3.745712 (-0.066801) | 5.249908 / 5.269862 (-0.019953) | 3.099614 / 4.565676 (-1.466063) | 0.057449 / 0.424275 (-0.366826) | 0.007728 / 0.007607 (0.000120) | 0.462123 / 0.226044 (0.236078) | 4.603942 / 2.268929 (2.335014) | 2.380957 / 55.444624 (-53.063668) | 2.059621 / 6.876477 (-4.816856) | 2.293764 / 2.142072 (0.151691) | 0.636471 / 4.805227 (-4.168756) | 0.150112 / 6.500664 (-6.350552) | 0.063705 / 0.075469 (-0.011764) |\n\n### Benchmark: benchmark_map_filter.json\n\n| metric | filter | map fast-tokenizer batched | map identity | map identity batched | map no-op batched | map no-op batched numpy | map no-op batched pandas | map no-op batched pytorch | map no-op batched tensorflow |\n|--------|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 1.358099 / 1.841788 (-0.483689) | 20.193750 / 8.074308 (12.119442) | 14.297350 / 10.191392 (4.105958) | 0.164477 / 0.680424 (-0.515947) | 0.018259 / 0.534201 (-0.515942) | 0.399010 / 0.579283 (-0.180273) | 0.417306 / 0.434364 (-0.017058) | 0.456961 / 0.540337 (-0.083377) | 0.631068 / 1.386936 (-0.755868) |\n\n</details>\nPyArrow==latest\n\n<details>\n<summary>Show updated benchmarks!</summary>\n\n### Benchmark: benchmark_array_xd.json\n\n| metric | read_batch_formatted_as_numpy after write_array2d | read_batch_formatted_as_numpy after write_flattened_sequence | read_batch_formatted_as_numpy after write_nested_sequence | read_batch_unformated after write_array2d | read_batch_unformated after write_flattened_sequence | read_batch_unformated after write_nested_sequence | read_col_formatted_as_numpy after write_array2d | read_col_

[{'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1634232942', 'html_url': 'https://github.com/huggingface/datasets/issues/6025#issuecomment-1634232942', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/6025', 'id': 1634232942, 'node_id': 'IC_kwDODunzps5haGpu', 'user': {'login': 'mariosasko', 'id': 47462742, 'node_id': 'MDQ6VXNlcjQ3NDYyNzQy', 'avatar_url': 'https://avatars.githubusercontent.com/u/47462742?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/mariosasko', 'html_url': 'https://github.com/mariosasko', 'followers_url': 'https://api.github.com/users/mariosasko/followers', 'following_url': 'https://api.github.com/users/mariosasko/following{/other_user}', 'gists_url': 'https://api.github.com/users/mariosasko/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/mariosasko/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/mariosasko/subscriptions', 'organizations_url': 'https://api.github.com/users/mariosasko/orgs', 'repos_url': 'https://api.github.com/users/mariosasko/repos', 'events_url': 'https://api.github.com/users/mariosasko/events{/privacy}', 'received_events_url': 'https://api.github.com/users/mariosasko/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-07-13T13:19:44Z', 'updated_at': '2023-07-13T13:19:44Z', 'author_association': 'CONTRIBUTOR', 'body': "I've opened a PR with a fix. In the meantime, you can avoid the error by deleting `task_templates` with `dataset.info.task_templates = None` before the `interleave_datasets` call.\r\n` ", 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1634232942/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}]
[{'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1633176251', 'html_url': 'https://github.com/huggingface/datasets/pull/6024#issuecomment-1633176251', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/6024', 'id': 1633176251, 'node_id': 'IC_kwDODunzps5hWEq7', 'user': {'login': 'maddiedawson', 'id': 106995444, 'node_id': 'U_kgDOBmCe9A', 'avatar_url': 'https://avatars.githubusercontent.com/u/106995444?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/maddiedawson', 'html_url': 'https://github.com/maddiedawson', 'followers_url': 'https://api.github.com/users/maddiedawson/followers', 'following_url': 'https://api.github.com/users/maddiedawson/following{/other_user}', 'gists_url': 'https://api.github.com/users/maddiedawson/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/maddiedawson/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/maddiedawson/subscriptions', 'organizations_url': 'https://api.github.com/users/maddiedawson/orgs', 'repos_url': 'https://api.github.com/users/maddiedawson/repos', 'events_url': 'https://api.github.com/users/maddiedawson/events{/privacy}', 'received_events_url': 'https://api.github.com/users/maddiedawson/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-07-12T20:31:39Z', 'updated_at': '2023-07-12T20:31:39Z', 'author_association': 'CONTRIBUTOR', 'body': 'Ptal @lhoestq :) I tested this manually on a multi-node Databricks cluster', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1633176251/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1633182421', 'html_url': 'https://github.com/huggingface/datasets/pull/6024#issuecomment-1633182421', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/6024', 'id': 1633182421, 'node_id': 'IC_kwDODunzps5hWGLV', 'user': {'login': 'maddiedawson', 'id': 106995444, 'node_id': 'U_kgDOBmCe9A', 'avatar_url': 'https://avatars.githubusercontent.com/u/106995444?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/maddiedawson', 'html_url': 'https://github.com/maddiedawson', 'followers_url': 'https://api.github.com/users/maddiedawson/followers', 'following_url': 'https://api.github.com/users/maddiedawson/following{/other_user}', 'gists_url': 'https://api.github.com/users/maddiedawson/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/maddiedawson/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/maddiedawson/subscriptions', 'organizations_url': 'https://api.github.com/users/maddiedawson/orgs', 'repos_url': 'https://api.github.com/users/maddiedawson/repos', 'events_url': 'https://api.github.com/users/maddiedawson/events{/privacy}', 'received_events_url': 'https://api.github.com/users/maddiedawson/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-07-12T20:36:43Z', 'updated_at': '2023-07-12T20:36:43Z', 'author_association': 'CONTRIBUTOR', 'body': 'Hm looks like the check_code_quality failures are unrelated to me change... https://github.com/huggingface/datasets/actions/runs/5536162850/jobs/10103451883?pr=6024', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1633182421/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1633183972', 'html_url': 'https://github.com/huggingface/datasets/pull/6024#issuecomment-1633183972', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/6024', 'id': 1633183972, 'node_id': 'IC_kwDODunzps5hWGjk', 'user': {'login': 'HuggingFaceDocBuilderDev', 'id': 99929124, 'node_id': 'U_kgDOBfTMJA', 'avatar_url': 'https://avatars.githubusercontent.com/u/99929124?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/HuggingFaceDocBuilderDev', 'html_url': 'https://github.com/HuggingFaceDocBuilderDev', 'followers_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/followers', 'following_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/following{/other_user}', 'gists_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/subscriptions', 'organizations_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/orgs', 'repos_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/repos', 'events_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/events{/privacy}', 'received_events_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-07-12T20:37:58Z', 'updated_at': '2023-07-13T12:37:39Z', 'author_association': 'NONE', 'body': '_The documentation is not available anymore as the PR was closed or merged._', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1633183972/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1634182012', 'html_url': 'https://github.com/huggingface/datasets/pull/6024#issuecomment-1634182012', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/6024', 'id': 1634182012, 'node_id': 'IC_kwDODunzps5hZ6N8', 'user': {'login': 'github-actions[bot]', 'id': 41898282, 'node_id': 'MDM6Qm90NDE4OTgyODI=', 'avatar_url': 'https://avatars.githubusercontent.com/in/15368?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/github-actions%5Bbot%5D', 'html_url': 'https://github.com/apps/github-actions', 'followers_url': 'https://api.github.com/users/github-actions%5Bbot%5D/followers', 'following_url': 'https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}', 'gists_url': 'https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/github-actions%5Bbot%5D/subscriptions', 'organizations_url': 'https://api.github.com/users/github-actions%5Bbot%5D/orgs', 'repos_url': 'https://api.github.com/users/github-actions%5Bbot%5D/repos', 'events_url': 'https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}', 'received_events_url': 'https://api.github.com/users/github-actions%5Bbot%5D/received_events', 'type': 'Bot', 'site_admin': False}, 'created_at': '2023-07-13T12:46:01Z', 'updated_at': '2023-07-13T12:46:01Z', 'author_association': 'NONE', 'body': '<details>\n<summary>Show benchmarks</summary>\n\nPyArrow==8.0.0\n\n<details>\n<summary>Show updated benchmarks!</summary>\n\n### Benchmark: benchmark_array_xd.json\n\n| metric | read_batch_formatted_as_numpy after write_array2d | read_batch_formatted_as_numpy after write_flattened_sequence | read_batch_formatted_as_numpy after write_nested_sequence | read_batch_unformated after write_array2d | read_batch_unformated after write_flattened_sequence | read_batch_unformated after write_nested_sequence | read_col_formatted_as_numpy after write_array2d | read_col_formatted_as_numpy after write_flattened_sequence | read_col_formatted_as_numpy after write_nested_sequence | read_col_unformated after write_array2d | read_col_unformated after write_flattened_sequence | read_col_unformated after write_nested_sequence | read_formatted_as_numpy after write_array2d | read_formatted_as_numpy after write_flattened_sequence | read_formatted_as_numpy after write_nested_sequence | read_unformated after write_array2d | read_unformated after write_flattened_sequence | read_unformated after write_nested_sequence | write_array2d | write_flattened_sequence | write_nested_sequence |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.005952 / 0.011353 (-0.005400) | 0.003585 / 0.011008 (-0.007424) | 0.079163 / 0.038508 (0.040655) | 0.057926 / 0.023109 (0.034817) | 0.326647 / 0.275898 (0.050749) | 0.383485 / 0.323480 (0.060005) | 0.004530 / 0.007986 (-0.003456) | 0.002821 / 0.004328 (-0.001508) | 0.062071 / 0.004250 (0.057820) | 0.048023 / 0.037052 (0.010971) | 0.329368 / 0.258489 (0.070879) | 0.390877 / 0.293841 (0.097036) | 0.026959 / 0.128546 (-0.101588) | 0.007911 / 0.075646 (-0.067735) | 0.259956 / 0.419271 (-0.159315) | 0.044582 / 0.043533 (0.001049) | 0.320537 / 0.255139 (0.065398) | 0.373814 / 0.283200 (0.090614) | 0.020275 / 0.141683 (-0.121408) | 1.532128 / 1.452155 (0.079973) | 1.595031 / 1.492716 (0.102315) |\n\n### Benchmark: benchmark_getitem\\_100B.json\n\n| metric | get_batch_of\\_1024\\_random_rows | get_batch_of\\_1024\\_rows | get_first_row | get_last_row |\n|--------|---|---|---|---|\n| new / old (diff) | 0.186127 / 0.018006 (0.168120) | 0.428586 / 0.000490 (0.428097) | 0.005180 / 0.000200 (0.004980) | 0.000069 / 0.000054 (0.000015) |\n\n### Benchmark: benchmark_indices_mapping.json\n\n| metric | select | shard | shuffle | sort | train_test_split |\n|--------|---|---|---|---|---|\n| new / old (diff) | 0.024876 / 0.037411 (-0.012536) | 0.072169 / 0.014526 (0.057643) | 0.082015 / 0.176557 (-0.094542) | 0.147467 / 0.737135 (-0.589668) | 0.082769 / 0.296338 (-0.213570) |\n\n### Benchmark: benchmark_iterating.json\n\n| metric | read 5000 | read 50000 | read_batch 50000 10 | read_batch 50000 100 | read_batch 50000 1000 | read_formatted numpy 5000 | read_formatted pandas 5000 | read_formatted tensorflow 5000 | read_formatted torch 5000 | read_formatted_batch numpy 5000 10 | read_formatted_batch numpy 5000 1000 | shuffled read 5000 | shuffled read 50000 | shuffled read_batch 50000 10 | shuffled read_batch 50000 100 | shuffled read_batch 50000 1000 | shuffled read_formatted numpy 5000 | shuffled read_formatted_batch numpy 5000 10 | shuffled read_formatted_batch numpy 5000 1000 |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.410625 / 0.215209 (0.195416) | 4.116742 / 2.077655 (2.039088) | 2.172291 / 1.504120 (0.668171) | 2.022462 / 1.541195 (0.481268) | 2.048142 / 1.468490 (0.579651) | 0.503152 / 4.584777 (-4.081625) | 3.019135 / 3.745712 (-0.726577) | 3.589451 / 5.269862 (-1.680410) | 2.206876 / 4.565676 (-2.358801) | 0.057687 / 0.424275 (-0.366588) | 0.006560 / 0.007607 (-0.001047) | 0.475585 / 0.226044 (0.249541) | 4.784344 / 2.268929 (2.515416) | 2.506322 / 55.444624 (-52.938302) | 2.168251 / 6.876477 (-4.708225) | 2.324453 / 2.142072 (0.182381) | 0.590609 / 4.805227 (-4.214618) | 0.124178 / 6.500664 (-6.376486) | 0.059197 / 0.075469 (-0.016272) |\n\n### Benchmark: benchmark_map_filter.json\n\n| metric | filter | map fast-tokenizer batched | map identity | map identity batched | map no-op batched | map no-op batched numpy | map no-op batched pandas | map no-op batched pytorch | map no-op batched tensorflow |\n|--------|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 1.212359 / 1.841788 (-0.629429) | 17.915843 / 8.074308 (9.841535) | 13.128330 / 10.191392 (2.936938) | 0.144805 / 0.680424 (-0.535618) | 0.016889 / 0.534201 (-0.517312) | 0.344056 / 0.579283 (-0.235227) | 0.359370 / 0.434364 (-0.074994) | 0.404199 / 0.540337 (-0.136138) | 0.549117 / 1.386936 (-0.837819) |\n\n</details>\nPyArrow==latest\n\n<details>\n<summary>Show updated benchmarks!</summary>\n\n### Benchmark: benchmark_array_xd.json\n\n| metric | read_batch_formatted_as_numpy after write_array2d | read_batch_formatted_as_numpy after write_flattened_sequence | read_batch_formatted_as_numpy after write_nested_sequence | read_batch_unformated after write_array2d | read_batch_unformated after write_flattened_sequence | read_batch_unformated after write_nested_sequence | read_col_formatted_as_numpy after write_array2d | read_col_formatted_as_numpy after write_flattened_sequence | read_col_formatted_as_numpy after write_nested_sequence | read_col_unformated after write_array2d | read_col_unformated after write_flattened_sequence | read_col_unformated after write_nested_sequence | read_formatted_as_numpy after write_array2d | read_formatted_as_numpy after write_flattened_sequence | read_formatted_as_numpy after write_nested_sequence | read_unformated after write_array2d | read_unformated after write_flattened_sequence | read_unformated after write_nested_sequence | write_array2d | write_flattened_sequence | write_nested_sequence |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.005914 / 0.011353 (-0.005439) | 0.003565 / 0.011008 (-0.007443) | 0.061575 / 0.038508 (0.023067) | 0.057677 / 0.023109 (0.034568) | 0.359753 / 0.275898 (0.083855) | 0.394135 / 0.323480 (0.070655) | 0.004648 / 0.007986 (-0.003338) | 0.002795 / 0.004328 (-0.001534) | 0.061877 / 0.004250 (0.057626) | 0.049673 / 0.037052 (0.012621) | 0.363120 / 0.258489 (0.104631) | 0.402685 / 0.293841 (0.108844) | 0.027021 / 0.128546 (-0.101525) | 0.008006 / 0.075646 (-0.067641) | 0.067398 / 0.419271 (-0.351874) | 0.044442 / 0.043533 (0.000909) | 0.364851 / 0.255139 (0.109712) | 0.387219 / 0.283200 (0.104019) | 0.027267 / 0.141683 (-0.114416) | 1.466675 / 1.452155 (0.014520) | 1.512607 / 1.492716 (0.019891) |\n\n### Benchmark: benchmark_getitem\\_100B.json\n\n| metric | get_batch_of\\_1024\\_random_rows | get_batch_of\\_1024\\_rows | get_first_row | get_last_row |\n|--------|---|---|---|---|\n| new / old (diff) | 0.206156 / 0.018006 (0.188150) | 0.410877 / 0.000490 (0.410387) | 0.003061 / 0.000200 (0.002861) | 0.000068 / 0.000054 (0.000013) |\n\n### Benchmark: benchmark_indices_mapping.json\n\n| metric | select | shard | shuffle | sort | train_test_split |\n|--------|---|---|---|---|---|\n| new / old (diff) | 0.024869 / 0.037411 (-0.012542) | 0.075736 / 0.014526 (0.061210) | 0.083922 / 0.176557 (-0.092634) | 0.139510 / 0.737135 (-0.597626) | 0.087685 / 0.296338 (-0.208654) |\n\n### Benchmark: benchmark_iterating.json\n\n| metric | read 5000 | read 50000 | read_batch 50000 10 | read_batch 50000 100 | read_batch 50000 1000 | read_formatted numpy 5000 | read_formatted pandas 5000 | read_formatted tensorflow 5000 | read_formatted torch 5000 | read_formatted_batch numpy 5000 10 | read_formatted_batch numpy 5000 1000 | shuffled read 5000 | shuffled read 50000 | shuffled read_batch 50000 10 | shuffled read_batch 50000 100 | shuffled read_batch 50000 1000 | shuffled read_formatted numpy 5000 | shuffled read_formatted_batch numpy 5000 10 | shuffled read_formatted_batch numpy 5000 1000 |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.414473 / 0.215209 (0.199264) | 4.150633 / 2.077655 (2.072979) | 2.132892 / 1.504120 (0.628773) | 1.964072 / 1.541195 (0.422878) | 2.003353 / 1.468490 (0.534863) | 0.498012 / 4.584777 (-4.086765) | 3.010135 / 3.745712 (-0.735577) | 2.841130 / 5.269862 (-2.428732) | 1.826013 / 4.565676 (-2.739664) | 0.057443 / 0.424275 (-0.366832) | 0.006374 / 0.007607 (-0.001234) | 0.490337 / 0.226044 (0.264292) | 4.889628 / 2.268929 (2.620700) | 2.575626 / 55.444624 (-52.868998) | 2.246522 / 6.876477 (-4.629955) | 2.276183 / 2.142072 (0.134110) | 0.581465 / 4.805227 (-4.223763) | 0.123877 / 6.500664 (-6.376787) | 0.060339 / 0.075469 (-0.015130) |\n\n### Benchmark: benchmark_map_filter.json\n\n| metric | filter | map fast-tokenizer batched | map identity | map identity batched | map no-op batched | map no-op batched numpy | map no-op batched pandas | map no-op batched pytorch | map no-op batched tensorflow |\n|--------|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 1.333202 / 1.841788 (-0.508585) | 18.363558 / 8.074308 (10.289250) | 14.109356 / 10.191392 (3.917964) | 0.147358 / 0.680424 (-0.533066) | 0.016813 / 0.534201 (-0.517388) | 0.334815 / 0.579283 (-0.244468) | 0.366576 / 0.434364 (-0.067788) | 0.397223 / 0.540337 (-0.143115) | 0.547893 / 1.386936 (-0.839043) |\n\n</details>\n</details>\n\n![](https://cml.dev/watermark.png#67ac60bcbebe9ddac70264951b1d584c93003cdf "CML watermark")\n', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1634182012/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}]

[{'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1632793828', 'html_url': 'https://github.com/huggingface/datasets/pull/6023#issuecomment-1632793828', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/6023', 'id': 1632793828, 'node_id': 'IC_kwDODunzps5hUnTk', 'user': {'login': 'HuggingFaceDocBuilderDev', 'id': 99929124, 'node_id': 'U_kgDOBfTMJA', 'avatar_url': 'https://avatars.githubusercontent.com/u/99929124?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/HuggingFaceDocBuilderDev', 'html_url': 'https://github.com/HuggingFaceDocBuilderDev', 'followers_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/followers', 'following_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/following{/other_user}', 'gists_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/subscriptions', 'organizations_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/orgs', 'repos_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/repos', 'events_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/events{/privacy}', 'received_events_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-07-12T15:52:00Z', 'updated_at': '2023-07-12T16:18:37Z', 'author_association': 'NONE', 'body': '_The documentation is not available anymore as the PR was closed or merged._', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1632793828/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1632799524', 'html_url': 'https://github.com/huggingface/datasets/pull/6023#issuecomment-1632799524', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/6023', 'id': 1632799524, 'node_id': 'IC_kwDODunzps5hUosk', 'user': {'login': 'github-actions[bot]', 'id': 41898282, 'node_id': 'MDM6Qm90NDE4OTgyODI=', 'avatar_url': 'https://avatars.githubusercontent.com/in/15368?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/github-actions%5Bbot%5D', 'html_url': 'https://github.com/apps/github-actions', 'followers_url': 'https://api.github.com/users/github-actions%5Bbot%5D/followers', 'following_url': 'https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}', 'gists_url': 'https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/github-actions%5Bbot%5D/subscriptions', 'organizations_url': 'https://api.github.com/users/github-actions%5Bbot%5D/orgs', 'repos_url': 'https://api.github.com/users/github-actions%5Bbot%5D/repos', 'events_url': 'https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}', 'received_events_url': 'https://api.github.com/users/github-actions%5Bbot%5D/received_events', 'type': 'Bot', 'site_admin': False}, 'created_at': '2023-07-12T15:55:47Z', 'updated_at': '2023-07-12T15:55:47Z', 'author_association': 'NONE', 'body': '<details>\n<summary>Show benchmarks</summary>\n\nPyArrow==8.0.0\n\n<details>\n<summary>Show updated benchmarks!</summary>\n\n### Benchmark: benchmark_array_xd.json\n\n| metric | read_batch_formatted_as_numpy after write_array2d | read_batch_formatted_as_numpy after write_flattened_sequence | read_batch_formatted_as_numpy after write_nested_sequence | read_batch_unformated after write_array2d | read_batch_unformated after write_flattened_sequence | read_batch_unformated after write_nested_sequence | read_col_formatted_as_numpy after write_array2d | read_col_formatted_as_numpy after write_flattened_sequence | read_col_formatted_as_numpy after write_nested_sequence | read_col_unformated after write_array2d | read_col_unformated after write_flattened_sequence | read_col_unformated after write_nested_sequence | read_formatted_as_numpy after write_array2d | read_formatted_as_numpy after write_flattened_sequence | read_formatted_as_numpy after write_nested_sequence | read_unformated after write_array2d | read_unformated after write_flattened_sequence | read_unformated after write_nested_sequence | write_array2d | write_flattened_sequence | write_nested_sequence |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.007108 / 0.011353 (-0.004245) | 0.004446 / 0.011008 (-0.006562) | 0.084013 / 0.038508 (0.045505) | 0.084271 / 0.023109 (0.061162) | 0.324496 / 0.275898 (0.048598) | 0.347783 / 0.323480 (0.024303) | 0.004382 / 0.007986 (-0.003604) | 0.005200 / 0.004328 (0.000872) | 0.065117 / 0.004250 (0.060866) | 0.063368 / 0.037052 (0.026316) | 0.328731 / 0.258489 (0.070242) | 0.356676 / 0.293841 (0.062835) | 0.031155 / 0.128546 (-0.097392) | 0.008672 / 0.075646 (-0.066975) | 0.287573 / 0.419271 (-0.131698) | 0.053692 / 0.043533 (0.010160) | 0.308796 / 0.255139 (0.053657) | 0.330521 / 0.283200 (0.047321) | 0.025010 / 0.141683 (-0.116672) | 1.498968 / 1.452155 (0.046813) | 1.552096 / 1.492716 (0.059380) |\n\n### Benchmark: benchmark_getitem\\_100B.json\n\n| metric | get_batch_of\\_1024\\_random_rows | get_batch_of\\_1024\\_rows | get_first_row | get_last_row |\n|--------|---|---|---|---|\n| new / old (diff) | 0.263580 / 0.018006 (0.245574) | 0.559765 / 0.000490 (0.559275) | 0.003450 / 0.000200 (0.003250) | 0.000079 / 0.000054 (0.000024) |\n\n### Benchmark: benchmark_indices_mapping.json\n\n| metric | select | shard | shuffle | sort | train_test_split |\n|--------|---|---|---|---|---|\n| new / old (diff) | 0.029403 / 0.037411 (-0.008008) | 0.088154 / 0.014526 (0.073628) | 0.100372 / 0.176557 (-0.076185) | 0.157777 / 0.737135 (-0.579359) | 0.102273 / 0.296338 (-0.194066) |\n\n### Benchmark: benchmark_iterating.json\n\n| metric | read 5000 | read 50000 | read_batch 50000 10 | read_batch 50000 100 | read_batch 50000 1000 | read_formatted numpy 5000 | read_formatted pandas 5000 | read_formatted tensorflow 5000 | read_formatted torch 5000 | read_formatted_batch numpy 5000 10 | read_formatted_batch numpy 5000 1000 | shuffled read 5000 | shuffled read 50000 | shuffled read_batch 50000 10 | shuffled read_batch 50000 100 | shuffled read_batch 50000 1000 | shuffled read_formatted numpy 5000 | shuffled read_formatted_batch numpy 5000 10 | shuffled read_formatted_batch numpy 5000 1000 |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.387027 / 0.215209 (0.171818) | 3.854260 / 2.077655 (1.776605) | 1.875159 / 1.504120 (0.371039) | 1.703734 / 1.541195 (0.162539) | 1.814305 / 1.468490 (0.345815) | 0.482524 / 4.584777 (-4.102253) | 3.463602 / 3.745712 (-0.282110) | 4.004766 / 5.269862 (-1.265095) | 2.406751 / 4.565676 (-2.158925) | 0.057069 / 0.424275 (-0.367206) | 0.007448 / 0.007607 (-0.000159) | 0.465801 / 0.226044 (0.239757) | 4.636700 / 2.268929 (2.367771) | 2.329475 / 55.444624 (-53.115150) | 1.998330 / 6.876477 (-4.878146) | 2.264617 / 2.142072 (0.122544) | 0.577998 / 4.805227 (-4.227230) | 0.130846 / 6.500664 (-6.369818) | 0.059713 / 0.075469 (-0.015756) |\n\n### Benchmark: benchmark_map_filter.json\n\n| metric | filter | map fast-tokenizer batched | map identity | map identity batched | map no-op batched | map no-op batched numpy | map no-op batched pandas | map no-op batched pytorch | map no-op batched tensorflow |\n|--------|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 1.275931 / 1.841788 (-0.565857) | 20.396288 / 8.074308 (12.321980) | 13.875242 / 10.191392 (3.683850) | 0.164367 / 0.680424 (-0.516057) | 0.018573 / 0.534201 (-0.515628) | 0.397516 / 0.579283 (-0.181767) | 0.398977 / 0.434364 (-0.035387) | 0.462386 / 0.540337 (-0.077951) | 0.610129 / 1.386936 (-0.776807) |\n\n</details>\nPyArrow==latest\n\n<details>\n<summary>Show updated benchmarks!</summary>\n\n### Benchmark: benchmark_array_xd.json\n\n| metric | read_batch_formatted_as_numpy after write_array2d | read_batch_formatted_as_numpy after write_flattened_sequence | read_batch_formatted_as_numpy after write_nested_sequence | read_batch_unformated after write_array2d | read_batch_unformated after write_flattened_sequence | read_batch_unformated after write_nested_sequence | read_col_formatted_as_numpy after write_array2d | read_col_formatted_as_numpy after write_flattened_sequence | read_col_formatted_as_numpy after write_nested_sequence | read_col_unformated after write_array2d | read_col_unformated after write_flattened_sequence | read_col_unformated after write_nested_sequence | read_formatted_as_numpy after write_array2d | read_formatted_as_numpy after write_flattened_sequence | read_formatted_as_numpy after write_nested_sequence | read_unformated after write_array2d | read_unformated after write_flattened_sequence | read_unformated after write_nested_sequence | write_array2d | write_flattened_sequence | write_nested_sequence |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.006912 / 0.011353 (-0.004441) | 0.004212 / 0.011008 (-0.006797) | 0.065707 / 0.038508 (0.027199) | 0.090435 / 0.023109 (0.067325) | 0.380539 / 0.275898 (0.104641) | 0.412692 / 0.323480 (0.089212) | 0.005545 / 0.007986 (-0.002441) | 0.003657 / 0.004328 (-0.000672) | 0.065380 / 0.004250 (0.061130) | 0.062901 / 0.037052 (0.025848) | 0.385931 / 0.258489 (0.127442) | 0.416272 / 0.293841 (0.122431) | 0.031974 / 0.128546 (-0.096572) | 0.008783 / 0.075646 (-0.066863) | 0.071424 / 0.419271 (-0.347847) | 0.049454 / 0.043533 (0.005921) | 0.374231 / 0.255139 (0.119092) | 0.386530 / 0.283200 (0.103331) | 0.025404 / 0.141683 (-0.116279) | 1.469869 / 1.452155 (0.017715) | 1.548629 / 1.492716 (0.055913) |\n\n### Benchmark: benchmark_getitem\\_100B.json\n\n| metric | get_batch_of\\_1024\\_random_rows | get_batch_of\\_1024\\_rows | get_first_row | get_last_row |\n|--------|---|---|---|---|\n| new / old (diff) | 0.218413 / 0.018006 (0.200406) | 0.573863 / 0.000490 (0.573373) | 0.004156 / 0.000200 (0.003956) | 0.000097 / 0.000054 (0.000043) |\n\n### Benchmark: benchmark_indices_mapping.json\n\n| metric | select | shard | shuffle | sort | train_test_split |\n|--------|---|---|---|---|---|\n| new / old (diff) | 0.032610 / 0.037411 (-0.004801) | 0.088270 / 0.014526 (0.073744) | 0.106821 / 0.176557 (-0.069735) | 0.164498 / 0.737135 (-0.572638) | 0.106881 / 0.296338 (-0.189457) |\n\n### Benchmark: benchmark_iterating.json\n\n| metric | read 5000 | read 50000 | read_batch 50000 10 | read_batch 50000 100 | read_batch 50000 1000 | read_formatted numpy 5000 | read_formatted pandas 5000 | read_formatted tensorflow 5000 | read_formatted torch 5000 | read_formatted_batch numpy 5000 10 | read_formatted_batch numpy 5000 1000 | shuffled read 5000 | shuffled read 50000 | shuffled read_batch 50000 10 | shuffled read_batch 50000 100 | shuffled read_batch 50000 1000 | shuffled read_formatted numpy 5000 | shuffled read_formatted_batch numpy 5000 10 | shuffled read_formatted_batch numpy 5000 1000 |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.433730 / 0.215209 (0.218520) | 4.323902 / 2.077655 (2.246247) | 2.308607 / 1.504120 (0.804487) | 2.138888 / 1.541195 (0.597693) | 2.246760 / 1.468490 (0.778269) | 0.486863 / 4.584777 (-4.097914) | 3.561826 / 3.745712 (-0.183886) | 5.592685 / 5.269862 (0.322824) | 3.318560 / 4.565676 (-1.247116) | 0.057348 / 0.424275 (-0.366927) | 0.007434 / 0.007607 (-0.000174) | 0.506767 / 0.226044 (0.280723) | 5.083097 / 2.268929 (2.814168) | 2.780618 / 55.444624 (-52.664006) | 2.456924 / 6.876477 (-4.419553) | 2.564184 / 2.142072 (0.422112) | 0.580693 / 4.805227 (-4.224534) | 0.134471 / 6.500664 (-6.366194) | 0.062883 / 0.075469 (-0.012586) |\n\n### Benchmark: benchmark_map_filter.json\n\n| metric | filter | map fast-tokenizer batched | map identity | map identity batched | map no-op batched | map no-op batched numpy | map no-op batched pandas | map no-op batched pytorch | map no-op batched tensorflow |\n|--------|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 1.346618 / 1.841788 (-0.495169) | 20.547998 / 8.074308 (12.473690) | 14.404159 / 10.191392 (4.212767) | 0.176612 / 0.680424 (-0.503812) | 0.018372 / 0.534201 (-0.515829) | 0.395636 / 0.579283 (-0.183647) | 0.410661 / 0.434364 (-0.023703) | 0.468782 / 0.540337 (-0.071555) | 0.637476 / 1.386936 (-0.749460) |\n\n</details>\n</details>\n\n![](https://cml.dev/watermark.png#0172d4dac0ca823e8bd293cfd4d28e78d92efe42 "CML watermark")\n', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1632799524/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1632855436', 'html_url': 'https://github.com/huggingface/datasets/pull/6023#issuecomment-1632855436', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/6023', 'id': 1632855436, 'node_id': 'IC_kwDODunzps5hU2WM', 'user': {'login': 'github-actions[bot]', 'id': 41898282, 'node_id': 'MDM6Qm90NDE4OTgyODI=', 'avatar_url': 'https://avatars.githubusercontent.com/in/15368?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/github-actions%5Bbot%5D', 'html_url': 'https://github.com/apps/github-actions', 'followers_url': 'https://api.github.com/users/github-actions%5Bbot%5D/followers', 'following_url': 'https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}', 'gists_url': 'https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/github-actions%5Bbot%5D/subscriptions', 'organizations_url': 'https://api.github.com/users/github-actions%5Bbot%5D/orgs', 'repos_url': 'https://api.github.com/users/github-actions%5Bbot%5D/repos', 'events_url': 'https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}', 'received_events_url': 'https://api.github.com/users/github-actions%5Bbot%5D/received_events', 'type': 'Bot', 'site_admin': False}, 'created_at': '2023-07-12T16:29:26Z', 'updated_at': '2023-07-12T16:29:26Z', 'author_association': 'NONE', 'body': '<details>\n<summary>Show benchmarks</summary>\n\nPyArrow==8.0.0\n\n<details>\n<summary>Show updated benchmarks!</summary>\n\n### Benchmark: benchmark_array_xd.json\n\n| metric | read_batch_formatted_as_numpy after write_array2d | read_batch_formatted_as_numpy after write_flattened_sequence | read_batch_formatted_as_numpy after write_nested_sequence | read_batch_unformated after write_array2d | read_batch_unformated after write_flattened_sequence | read_batch_unformated after write_nested_sequence | read_col_formatted_as_numpy after write_array2d | read_col_formatted_as_numpy after write_flattened_sequence | read_col_formatted_as_numpy after write_nested_sequence | read_col_unformated after write_array2d | read_col_unformated after write_flattened_sequence | read_col_unformated after write_nested_sequence | read_formatted_as_numpy after write_array2d | read_formatted_as_numpy after write_flattened_sequence | read_formatted_as_numpy after write_nested_sequence | read_unformated after write_array2d | read_unformated after write_flattened_sequence | read_unformated after write_nested_sequence | write_array2d | write_flattened_sequence | write_nested_sequence |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.009896 / 0.011353 (-0.001457) | 0.004658 / 0.011008 (-0.006351) | 0.101185 / 0.038508 (0.062677) | 0.075480 / 0.023109 (0.052371) | 0.410620 / 0.275898 (0.134722) | 0.470639 / 0.323480 (0.147159) | 0.007042 / 0.007986 (-0.000943) | 0.003909 / 0.004328 (-0.000419) | 0.079676 / 0.004250 (0.075425) | 0.066921 / 0.037052 (0.029869) | 0.423624 / 0.258489 (0.165135) | 0.473008 / 0.293841 (0.179167) | 0.048492 / 0.128546 (-0.080054) | 0.012833 / 0.075646 (-0.062813) | 0.335286 / 0.419271 (-0.083985) | 0.083506 / 0.043533 (0.039973) | 0.401918 / 0.255139 (0.146779) | 0.467975 / 0.283200 (0.184775) | 0.050025 / 0.141683 (-0.091658) | 1.679392 / 1.452155 (0.227237) | 1.852812 / 1.492716 (0.360095) |\n\n### Benchmark: benchmark_getitem\\_100B.json\n\n| metric | get_batch_of\\_1024\\_random_rows | get_batch_of\\_1024\\_rows | get_first_row | get_last_row |\n|--------|---|---|---|---|\n| new / old (diff) | 0.248067 / 0.018006 (0.230061) | 0.584818 / 0.000490 (0.584328) | 0.021558 / 0.000200 (0.021358) | 0.000104 / 0.000054 (0.000050) |\n\n### Benchmark: benchmark_indices_mapping.json\n\n| metric | select | shard | shuffle | sort | train_test_split |\n|--------|---|---|---|---|---|\n| new / old (diff) | 0.028572 / 0.037411 (-0.008839) | 0.097212 / 0.014526 (0.082686) | 0.121675 / 0.176557 (-0.054881) | 0.186597 / 0.737135 (-0.550538) | 0.122285 / 0.296338 (-0.174053) |\n\n### Benchmark: benchmark_iterating.json\n\n| metric | read 5000 | read 50000 | read_batch 50000 10 | read_batch 50000 100 | read_batch 50000 1000 | read_formatted numpy 5000 | read_formatted pandas 5000 | read_formatted tensorflow 5000 | read_formatted torch 5000 | read_formatted_batch numpy 5000 10 | read_formatted_batch numpy 5000 1000 | shuffled read 5000 | shuffled read 50000 | shuffled read_batch 50000 10 | shuffled read_batch 50000 100 | shuffled read_batch 50000 1000 | shuffled read_formatted numpy 5000 | shuffled read_formatted_batch numpy 5000 10 | shuffled read_formatted_batch numpy 5000 1000 |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.586279 / 0.215209 (0.371070) | 5.634402 / 2.077655 (3.556747) | 2.560648 / 1.504120 (1.056528) | 2.288796 / 1.541195 (0.747601) | 2.402580 / 1.468490 (0.934090) | 0.801453 / 4.584777 (-3.783324) | 5.036654 / 3.745712 (1.290942) | 8.319972 / 5.269862 (3.050110) | 4.665620 / 4.565676 (0.099944) | 0.107292 / 0.424275 (-0.316983) | 0.009206 / 0.007607 (0.001599) | 0.766505 / 0.226044 (0.540461) | 7.333784 / 2.268929 (5.064856) | 3.601875 / 55.444624 (-51.842749) | 2.886388 / 6.876477 (-3.990089) | 3.231797 / 2.142072 (1.089725) | 1.179509 / 4.805227 (-3.625718) | 0.224656 / 6.500664 (-6.276008) | 0.084749 / 0.075469 (0.009280) |\n\n### Benchmark: benchmark_map_filter.json\n\n| metric | filter | map fast-tokenizer batched | map identity | map identity batched | map no-op batched | map no-op batched numpy | map no-op batched pandas | map no-op batched pytorch | map no-op batched tensorflow |\n|--------|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 1.772345 / 1.841788 (-0.069443) | 24.138788 / 8.074308 (16.064480) | 20.712416 / 10.191392 (10.521024) | 0.254655 / 0.680424 (-0.425769) | 0.028858 / 0.534201 (-0.505343) | 0.499314 / 0.579283 (-0.079969) | 0.605797 / 0.434364 (0.171433) | 0.567628 / 0.540337 (0.027290) | 0.752288 / 1.386936 (-0.634648) |\n\n</details>\nPyArrow==latest\n\n<details>\n<summary>Show updated benchmarks!</summary>\n\n### Benchmark: benchmark_array_xd.json\n\n| metric | read_batch_formatted_as_numpy after write_array2d | read_batch_formatted_as_numpy after write_flattened_sequence | read_batch_formatted_as_numpy after write_nested_sequence | read_batch_unformated after write_array2d | read_batch_unformated after write_flattened_sequence | read_batch_unformated after write_nested_sequence | read_col_formatted_as_numpy after write_array2d | read_col_formatted_as_numpy after write_flattened_sequence | read_col_formatted_as_numpy after write_nested

[{'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1632785935', 'html_url': 'https://github.com/huggingface/datasets/issues/6022#issuecomment-1632785935', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/6022', 'id': 1632785935, 'node_id': 'IC_kwDODunzps5hUlYP', 'user': {'login': 'mariosasko', 'id': 47462742, 'node_id': 'MDQ6VXNlcjQ3NDYyNzQy', 'avatar_url': 'https://avatars.githubusercontent.com/u/47462742?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/mariosasko', 'html_url': 'https://github.com/mariosasko', 'followers_url': 'https://api.github.com/users/mariosasko/followers', 'following_url': 'https://api.github.com/users/mariosasko/following{/other_user}', 'gists_url': 'https://api.github.com/users/mariosasko/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/mariosasko/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/mariosasko/subscriptions', 'organizations_url': 'https://api.github.com/users/mariosasko/orgs', 'repos_url': 'https://api.github.com/users/mariosasko/repos', 'events_url': 'https://api.github.com/users/mariosasko/events{/privacy}', 'received_events_url': 'https://api.github.com/users/mariosasko/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-07-12T15:47:02Z', 'updated_at': '2023-07-12T15:47:02Z', 'author_association': 'CONTRIBUTOR', 'body': "Thanks for reporting! I've opened a PR with a fix.", 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1632785935/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}]
[{'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1631547366', 'html_url': 'https://github.com/huggingface/datasets/pull/6021#issuecomment-1631547366', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/6021', 'id': 1631547366, 'node_id': 'IC_kwDODunzps5hP2_m', 'user': {'login': 'HuggingFaceDocBuilderDev', 'id': 99929124, 'node_id': 'U_kgDOBfTMJA', 'avatar_url': 'https://avatars.githubusercontent.com/u/99929124?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/HuggingFaceDocBuilderDev', 'html_url': 'https://github.com/HuggingFaceDocBuilderDev', 'followers_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/followers', 'following_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/following{/other_user}', 'gists_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/subscriptions', 'organizations_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/orgs', 'repos_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/repos', 'events_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/events{/privacy}', 'received_events_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-07-11T21:40:29Z', 'updated_at': '2023-07-12T17:03:31Z', 'author_association': 'NONE', 'body': '_The documentation is not available anymore as the PR was closed or merged._', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1631547366/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1632911416', 'html_url': 'https://github.com/huggingface/datasets/pull/6021#issuecomment-1632911416', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/6021', 'id': 1632911416, 'node_id': 'IC_kwDODunzps5hVEA4', 'user': {'login': 'github-actions[bot]', 'id': 41898282, 'node_id': 'MDM6Qm90NDE4OTgyODI=', 'avatar_url': 'https://avatars.githubusercontent.com/in/15368?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/github-actions%5Bbot%5D', 'html_url': 'https://github.com/apps/github-actions', 'followers_url': 'https://api.github.com/users/github-actions%5Bbot%5D/followers', 'following_url': 'https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}', 'gists_url': 'https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/github-actions%5Bbot%5D/subscriptions', 'organizations_url': 'https://api.github.com/users/github-actions%5Bbot%5D/orgs', 'repos_url': 'https://api.github.com/users/github-actions%5Bbot%5D/repos', 'events_url': 'https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}', 'received_events_url': 'https://api.github.com/users/github-actions%5Bbot%5D/received_events', 'type': 'Bot', 'site_admin': False}, 'created_at': '2023-07-12T17:13:01Z', 'updated_at': '2023-07-12T17:13:01Z', 'author_association': 'NONE', 'body': '<details>\n<summary>Show benchmarks</summary>\n\nPyArrow==8.0.0\n\n<details>\n<summary>Show updated benchmarks!</summary>\n\n### Benchmark: benchmark_array_xd.json\n\n| metric | read_batch_formatted_as_numpy after write_array2d | read_batch_formatted_as_numpy after write_flattened_sequence | read_batch_formatted_as_numpy after write_nested_sequence | read_batch_unformated after write_array2d | read_batch_unformated after write_flattened_sequence | read_batch_unformated after write_nested_sequence | read_col_formatted_as_numpy after write_array2d | read_col_formatted_as_numpy after write_flattened_sequence | read_col_formatted_as_numpy after write_nested_sequence | read_col_unformated after write_array2d | read_col_unformated after write_flattened_sequence | read_col_unformated after write_nested_sequence | read_formatted_as_numpy after write_array2d | read_formatted_as_numpy after write_flattened_sequence | read_formatted_as_numpy after write_nested_sequence | read_unformated after write_array2d | read_unformated after write_flattened_sequence | read_unformated after write_nested_sequence | write_array2d | write_flattened_sequence | write_nested_sequence |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.007697 / 0.011353 (-0.003656) | 0.004233 / 0.011008 (-0.006776) | 0.087890 / 0.038508 (0.049382) | 0.065305 / 0.023109 (0.042196) | 0.366919 / 0.275898 (0.091020) | 0.399656 / 0.323480 (0.076176) | 0.006753 / 0.007986 (-0.001232) | 0.003428 / 0.004328 (-0.000900) | 0.070180 / 0.004250 (0.065930) | 0.054164 / 0.037052 (0.017112) | 0.377130 / 0.258489 (0.118641) | 0.403456 / 0.293841 (0.109615) | 0.042639 / 0.128546 (-0.085907) | 0.012396 / 0.075646 (-0.063250) | 0.314235 / 0.419271 (-0.105036) | 0.061976 / 0.043533 (0.018443) | 0.376959 / 0.255139 (0.121820) | 0.433313 / 0.283200 (0.150113) | 0.031253 / 0.141683 (-0.110430) | 1.555749 / 1.452155 (0.103594) | 1.643905 / 1.492716 (0.151189) |\n\n### Benchmark: benchmark_getitem\\_100B.json\n\n| metric | get_batch_of\\_1024\\_random_rows | get_batch_of\\_1024\\_rows | get_first_row | get_last_row |\n|--------|---|---|---|---|\n| new / old (diff) | 0.208630 / 0.018006 (0.190624) | 0.519532 / 0.000490 (0.519042) | 0.003719 / 0.000200 (0.003519) | 0.000099 / 0.000054 (0.000045) |\n\n### Benchmark: benchmark_indices_mapping.json\n\n| metric | select | shard | shuffle | sort | train_test_split |\n|--------|---|---|---|---|---|\n| new / old (diff) | 0.027403 / 0.037411 (-0.010008) | 0.080990 / 0.014526 (0.066464) | 0.090424 / 0.176557 (-0.086133) | 0.153922 / 0.737135 (-0.583213) | 0.098156 / 0.296338 (-0.198183) |\n\n### Benchmark: benchmark_iterating.json\n\n| metric | read 5000 | read 50000 | read_batch 50000 10 | read_batch 50000 100 | read_batch 50000 1000 | read_formatted numpy 5000 | read_formatted pandas 5000 | read_formatted tensorflow 5000 | read_formatted torch 5000 | read_formatted_batch numpy 5000 10 | read_formatted_batch numpy 5000 1000 | shuffled read 5000 | shuffled read 50000 | shuffled read_batch 50000 10 | shuffled read_batch 50000 100 | shuffled read_batch 50000 1000 | shuffled read_formatted numpy 5000 | shuffled read_formatted_batch numpy 5000 10 | shuffled read_formatted_batch numpy 5000 1000 |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.519453 / 0.215209 (0.304244) | 5.100089 / 2.077655 (3.022434) | 2.212165 / 1.504120 (0.708045) | 1.894405 / 1.541195 (0.353210) | 1.922914 / 1.468490 (0.454424) | 0.762443 / 4.584777 (-3.822334) | 4.669214 / 3.745712 (0.923502) | 5.016066 / 5.269862 (-0.253796) | 3.128821 / 4.565676 (-1.436856) | 0.091541 / 0.424275 (-0.332734) | 0.007582 / 0.007607 (-0.000026) | 0.652753 / 0.226044 (0.426709) | 6.601375 / 2.268929 (4.332446) | 3.076948 / 55.444624 (-52.367677) | 2.250544 / 6.876477 (-4.625933) | 2.404059 / 2.142072 (0.261987) | 0.994917 / 4.805227 (-3.810311) | 0.200318 / 6.500664 (-6.300346) | 0.069354 / 0.075469 (-0.006115) |\n\n### Benchmark: benchmark_map_filter.json\n\n| metric | filter | map fast-tokenizer batched | map identity | map identity batched | map no-op batched | map no-op batched numpy | map no-op batched pandas | map no-op batched pytorch | map no-op batched tensorflow |\n|--------|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 1.482559 / 1.841788 (-0.359229) | 20.722092 / 8.074308 (12.647784) | 17.703217 / 10.191392 (7.511825) | 0.215370 / 0.680424 (-0.465053) | 0.028208 / 0.534201 (-0.505993) | 0.425992 / 0.579283 (-0.153291) | 0.492785 / 0.434364 (0.058421) | 0.474154 / 0.540337 (-0.066183) | 0.644599 / 1.386936 (-0.742337) |\n\n</details>\nPyArrow==latest\n\n<details>\n<summary>Show updated benchmarks!</summary>\n\n### Benchmark: benchmark_array_xd.json\n\n| metric | read_batch_formatted_as_numpy after write_array2d | read_batch_formatted_as_numpy after write_flattened_sequence | read_batch_formatted_as_numpy after write_nested_sequence | read_batch_unformated after write_array2d | read_batch_unformated after write_flattened_sequence | read_batch_unformated after write_nested_sequence | read_col_formatted_as_numpy after write_array2d | read_col_formatted_as_numpy after write_flattened_sequence | read_col_formatted_as_numpy after write_nested_sequence | read_col_unformated after write_array2d | read_col_unformated after write_flattened_sequence | read_col_unformated after write_nested_sequence | read_formatted_as_numpy after write_array2d | read_formatted_as_numpy after write_flattened_sequence | read_formatted_as_numpy after write_nested_sequence | read_unformated after write_array2d | read_unformated after write_flattened_sequence | read_unformated after write_nested_sequence | write_array2d | write_flattened_sequence | write_nested_sequence |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.008372 / 0.011353 (-0.002981) | 0.004543 / 0.011008 (-0.006465) | 0.070564 / 0.038508 (0.032056) | 0.066855 / 0.023109 (0.043746) | 0.386724 / 0.275898 (0.110826) | 0.432184 / 0.323480 (0.108704) | 0.005250 / 0.007986 (-0.002736) | 0.003630 / 0.004328 (-0.000698) | 0.069310 / 0.004250 (0.065060) | 0.055759 / 0.037052 (0.018707) | 0.375789 / 0.258489 (0.117299) | 0.417335 / 0.293841 (0.123494) | 0.043424 / 0.128546 (-0.085122) | 0.013106 / 0.075646 (-0.062541) | 0.087836 / 0.419271 (-0.331436) | 0.057770 / 0.043533 (0.014237) | 0.396694 / 0.255139 (0.141555) | 0.439350 / 0.283200 (0.156150) | 0.031660 / 0.141683 (-0.110023) | 1.571339 / 1.452155 (0.119185) | 1.667169 / 1.492716 (0.174452) |\n\n### Benchmark: benchmark_getitem\\_100B.json\n\n| metric | get_batch_of\\_1024\\_random_rows | get_batch_of\\_1024\\_rows | get_first_row | get_last_row |\n|--------|---|---|---|---|\n| new / old (diff) | 0.180534 / 0.018006 (0.162528) | 0.540027 / 0.000490 (0.539537) | 0.003573 / 0.000200 (0.003373) | 0.000141 / 0.000054 (0.000086) |\n\n### Benchmark: benchmark_indices_mapping.json\n\n| metric | select | shard | shuffle | sort | train_test_split |\n|--------|---|---|---|---|---|\n| new / old (diff) | 0.031380 / 0.037411 (-0.006032) | 0.083762 / 0.014526 (0.069236) | 0.098166 / 0.176557 (-0.078390) | 0.160761 / 0.737135 (-0.576374) | 0.097683 / 0.296338 (-0.198656) |\n\n### Benchmark: benchmark_iterating.json\n\n| metric | read 5000 | read 50000 | read_batch 50000 10 | read_batch 50000 100 | read_batch 50000 1000 | read_formatted numpy 5000 | read_formatted pandas 5000 | read_formatted tensorflow 5000 | read_formatted torch 5000 | read_formatted_batch numpy 5000 10 | read_formatted_batch numpy 5000 1000 | shuffled read 5000 | shuffled read 50000 | shuffled read_batch 50000 10 | shuffled read_batch 50000 100 | shuffled read_batch 50000 1000 | shuffled read_formatted numpy 5000 | shuffled read_formatted_batch numpy 5000 10 | shuffled read_formatted_batch numpy 5000 1000 |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.568074 / 0.215209 (0.352865) | 5.660544 / 2.077655 (3.582889) | 2.416698 / 1.504120 (0.912578) | 2.177096 / 1.541195 (0.635901) | 2.206178 / 1.468490 (0.737688) | 0.844864 / 4.584777 (-3.739912) | 4.793636 / 3.745712 (1.047923) | 7.062387 / 5.269862 (1.792525) | 4.201228 / 4.565676 (-0.364449) | 0.091997 / 0.424275 (-0.332279) | 0.007881 / 0.007607 (0.000274) | 0.679466 / 0.226044 (0.453422) | 6.580268 / 2.268929 (4.311340) | 3.229907 / 55.444624 (-52.214717) | 2.524877 / 6.876477 (-4.351600) | 2.463796 / 2.142072 (0.321723) | 0.975627 / 4.805227 (-3.829600) | 0.186670 / 6.500664 (-6.313994) | 0.065307 / 0.075469 (-0.010163) |\n\n### Benchmark: benchmark_map_filter.json\n\n| metric | filter | map fast-tokenizer batched | map identity | map identity batched | map no-op batched | map no-op batched numpy | map no-op batched pandas | map no-op batched pytorch | map no-op batched tensorflow |\n|--------|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 1.501447 / 1.841788 (-0.340340) | 21.231037 / 8.074308 (13.156729) | 17.591671 / 10.191392 (7.400279) | 0.212745 / 0.680424 (-0.467679) | 0.026100 / 0.534201 (-0.508101) | 0.428391 / 0.579283 (-0.150892) | 0.535268 / 0.434364 (0.100904) | 0.506733 / 0.540337 (-0.033604) | 0.660832 / 1.386936 (-0.726104) |\n\n</details>\n</details>\n\n![](https://cml.dev/watermark.png#962537d7ee9191438ef47a4185d0ba626b2ee949 "CML watermark")\n', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1632911416/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}]

[{'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1632803184', 'html_url': 'https://github.com/huggingface/datasets/issues/6020#issuecomment-1632803184', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/6020', 'id': 1632803184, 'node_id': 'IC_kwDODunzps5hUplw', 'user': {'login': 'mariosasko', 'id': 47462742, 'node_id': 'MDQ6VXNlcjQ3NDYyNzQy', 'avatar_url': 'https://avatars.githubusercontent.com/u/47462742?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/mariosasko', 'html_url': 'https://github.com/mariosasko', 'followers_url': 'https://api.github.com/users/mariosasko/followers', 'following_url': 'https://api.github.com/users/mariosasko/following{/other_user}', 'gists_url': 'https://api.github.com/users/mariosasko/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/mariosasko/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/mariosasko/subscriptions', 'organizations_url': 'https://api.github.com/users/mariosasko/orgs', 'repos_url': 'https://api.github.com/users/mariosasko/repos', 'events_url': 'https://api.github.com/users/mariosasko/events{/privacy}', 'received_events_url': 'https://api.github.com/users/mariosasko/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-07-12T15:58:05Z', 'updated_at': '2023-07-12T15:58:24Z', 'author_association': 'CONTRIBUTOR', 'body': 'This scenario currently requires explicitly passing the target features (to avoid the error): \r\n```python\r\nimport datasets\r\n\r\n...\r\n\r\nfeatures = dataset.features\r\nfeatures["output"] = = [{"test": datasets.Value("int64")}]\r\ntest2 = dataset.map(lambda row, idx: test_func(row, idx), with_indices=True, num_proc=32, features=features)\r\n```', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1632803184/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}]

[{'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1633000304', 'html_url': 'https://github.com/huggingface/datasets/pull/6018#issuecomment-1633000304', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/6018', 'id': 1633000304, 'node_id': 'IC_kwDODunzps5hVZtw', 'user': {'login': 'mariosasko', 'id': 47462742, 'node_id': 'MDQ6VXNlcjQ3NDYyNzQy', 'avatar_url': 'https://avatars.githubusercontent.com/u/47462742?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/mariosasko', 'html_url': 'https://github.com/mariosasko', 'followers_url': 'https://api.github.com/users/mariosasko/followers', 'following_url': 'https://api.github.com/users/mariosasko/following{/other_user}', 'gists_url': 'https://api.github.com/users/mariosasko/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/mariosasko/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/mariosasko/subscriptions', 'organizations_url': 'https://api.github.com/users/mariosasko/orgs', 'repos_url': 'https://api.github.com/users/mariosasko/repos', 'events_url': 'https://api.github.com/users/mariosasko/events{/privacy}', 'received_events_url': 'https://api.github.com/users/mariosasko/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-07-12T18:16:55Z', 'updated_at': '2023-07-12T18:16:55Z', 'author_association': 'CONTRIBUTOR', 'body': 'We no longer host datasets in this repo. You should use the HF Hub instead.', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1633000304/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}]
[]
[{'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1632847921', 'html_url': 'https://github.com/huggingface/datasets/pull/6016#issuecomment-1632847921', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/6016', 'id': 1632847921, 'node_id': 'IC_kwDODunzps5hU0gx', 'user': {'login': 'HuggingFaceDocBuilderDev', 'id': 99929124, 'node_id': 'U_kgDOBfTMJA', 'avatar_url': 'https://avatars.githubusercontent.com/u/99929124?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/HuggingFaceDocBuilderDev', 'html_url': 'https://github.com/HuggingFaceDocBuilderDev', 'followers_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/followers', 'following_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/following{/other_user}', 'gists_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/subscriptions', 'organizations_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/orgs', 'repos_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/repos', 'events_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/events{/privacy}', 'received_events_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-07-12T16:23:53Z', 'updated_at': '2023-07-12T16:23:53Z', 'author_association': 'NONE', 'body': 'The docs for this PR live [here](https://moon-ci-docs.huggingface.co/docs/datasets/pr_6016). All of your documentation changes will be reflected on that endpoint.', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1632847921/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1632995990', 'html_url': 'https://github.com/huggingface/datasets/pull/6016#issuecomment-1632995990', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/6016', 'id': 1632995990, 'node_id': 'IC_kwDODunzps5hVYqW', 'user': {'login': 'mariosasko', 'id': 47462742, 'node_id': 'MDQ6VXNlcjQ3NDYyNzQy', 'avatar_url': 'https://avatars.githubusercontent.com/u/47462742?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/mariosasko', 'html_url': 'https://github.com/mariosasko', 'followers_url': 'https://api.github.com/users/mariosasko/followers', 'following_url': 'https://api.github.com/users/mariosasko/following{/other_user}', 'gists_url': 'https://api.github.com/users/mariosasko/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/mariosasko/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/mariosasko/subscriptions', 'organizations_url': 'https://api.github.com/users/mariosasko/orgs', 'repos_url': 'https://api.github.com/users/mariosasko/repos', 'events_url': 'https://api.github.com/users/mariosasko/events{/privacy}', 'received_events_url': 'https://api.github.com/users/mariosasko/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-07-12T18:13:28Z', 'updated_at': '2023-07-12T23:16:01Z', 'author_association': 'CONTRIBUTOR', 'body': 'It we could have something similar to Polars, that would be great.\r\n\r\nThis is what Polars outputs: \r\n* `__repr__`/`__str__` :\r\n```\r\nshape: (67_349, 3)\r\n┌───────┬───────────────────────────────────┬───────┐\r\n│ idx   ┆ sentence                          ┆ label │\r\n│ ---   ┆ ---                               ┆ ---   │\r\n│ i32   ┆ str                               ┆ i64   │\r\n╞═══════╪═══════════════════════════════════╪═══════╡\r\n│ 0     ┆ hide new secretions from the par… ┆ 0     │\r\n│ 1     ┆ contains no wit , only labored g… ┆ 0     │\r\n│ 2     ┆ that loves its characters and co… ┆ 1     │\r\n│ 3     ┆ remains utterly satisfied to rem… ┆ 0     │\r\n│ …     ┆ …                                 ┆ …     │\r\n│ 67345 ┆ anguish , anger and frustration   ┆ 0     │\r\n│ 67346 ┆ at achieving the modest , crowd-… ┆ 1     │\r\n│ 67347 ┆ a patient viewer                  ┆ 1     │\r\n│ 67348 ┆ this new jangle of noise , mayhe… ┆ 0     │\r\n└───────┴───────────────────────────────────┴───────┘\r\n```\r\n\r\n* `_repr_html_`:\r\n<img width="251" alt="Screenshot 2023-07-12 at 18 25 58" src="https://github.com/huggingface/datasets/assets/47462742/5d04519d-f302-4411-9fbc-7445bdf53b23">\r\n\r\n', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1632995990/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}]

[{'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1631101792', 'html_url': 'https://github.com/huggingface/datasets/issues/6014#issuecomment-1631101792', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/6014', 'id': 1631101792, 'node_id': 'IC_kwDODunzps5hOKNg', 'user': {'login': 'lhoestq', 'id': 42851186, 'node_id': 'MDQ6VXNlcjQyODUxMTg2', 'avatar_url': 'https://avatars.githubusercontent.com/u/42851186?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/lhoestq', 'html_url': 'https://github.com/lhoestq', 'followers_url': 'https://api.github.com/users/lhoestq/followers', 'following_url': 'https://api.github.com/users/lhoestq/following{/other_user}', 'gists_url': 'https://api.github.com/users/lhoestq/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/lhoestq/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/lhoestq/subscriptions', 'organizations_url': 'https://api.github.com/users/lhoestq/orgs', 'repos_url': 'https://api.github.com/users/lhoestq/repos', 'events_url': 'https://api.github.com/users/lhoestq/events{/privacy}', 'received_events_url': 'https://api.github.com/users/lhoestq/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-07-11T16:07:41Z', 'updated_at': '2023-07-11T16:07:41Z', 'author_association': 'MEMBER', 'body': 'Hi ! The huggingface/dataset-viewer code was not maintained anymore because we switched to a new dataset viewer that is deployed available for each dataset the Hugging Face website.\r\n\r\nWhat are you using this old repository for ?', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1631101792/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1631178439', 'html_url': 'https://github.com/huggingface/datasets/issues/6014#issuecomment-1631178439', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/6014', 'id': 1631178439, 'node_id': 'IC_kwDODunzps5hOc7H', 'user': {'login': 'mariosasko', 'id': 47462742, 'node_id': 'MDQ6VXNlcjQ3NDYyNzQy', 'avatar_url': 'https://avatars.githubusercontent.com/u/47462742?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/mariosasko', 'html_url': 'https://github.com/mariosasko', 'followers_url': 'https://api.github.com/users/mariosasko/followers', 'following_url': 'https://api.github.com/users/mariosasko/following{/other_user}', 'gists_url': 'https://api.github.com/users/mariosasko/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/mariosasko/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/mariosasko/subscriptions', 'organizations_url': 'https://api.github.com/users/mariosasko/orgs', 'repos_url': 'https://api.github.com/users/mariosasko/repos', 'events_url': 'https://api.github.com/users/mariosasko/events{/privacy}', 'received_events_url': 'https://api.github.com/users/mariosasko/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-07-11T17:03:06Z', 'updated_at': '2023-07-11T17:03:39Z', 'author_association': 'CONTRIBUTOR', 'body': "I think these parts are outdated:\r\n\r\n* https://github.com/huggingface/datasets-viewer/blob/8efad8eae313a891f713469983bf4c744786f26e/run.py#L126-L131\r\n* https://github.com/huggingface/datasets-viewer/blob/8efad8eae313a891f713469983bf4c744786f26e/run.py#L145-L150\r\n\r\nTo make the viewer work, the first one should be replaced with the following:\r\n```python\r\ndataset_module = datasets.load.dataset_module_factory(path)\r\nbuilder_cls = datasets.load.import_main_class(dataset_module.module_path)\r\nconfs = builder_cls.BUILDER_CONFIGS\r\n```\r\nAnd the second one:\r\n```python\r\ndataset_module = datasets.load.dataset_module_factory(path)\r\nbuilder_cls = datasets.load.import_main_class(dataset_module.module_path)\r\nif conf:\r\n    builder_instance = builder_cls(name=conf, cache_dir=path if path_to_datasets is not None else None)\r\nelse:\r\n    builder_instance = builder_cls(cache_dir=path if path_to_datasets is not None else None)\r\n```\r\n\r\nBut as @lhoestq suggested, it's better to use the `datasets-server` API nowadays to [fetch the rows](https://huggingface.co/docs/datasets-server/rows).", 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1631178439/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1631185809', 'html_url': 'https://github.com/huggingface/datasets/issues/6014#issuecomment-1631185809', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/6014', 'id': 1631185809, 'node_id': 'IC_kwDODunzps5hOeuR', 'user': {'login': 'julien-c', 'id': 326577, 'node_id': 'MDQ6VXNlcjMyNjU3Nw==', 'avatar_url': 'https://avatars.githubusercontent.com/u/326577?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/julien-c', 'html_url': 'https://github.com/julien-c', 'followers_url': 'https://api.github.com/users/julien-c/followers', 'following_url': 'https://api.github.com/users/julien-c/following{/other_user}', 'gists_url': 'https://api.github.com/users/julien-c/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/julien-c/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/julien-c/subscriptions', 'organizations_url': 'https://api.github.com/users/julien-c/orgs', 'repos_url': 'https://api.github.com/users/julien-c/repos', 'events_url': 'https://api.github.com/users/julien-c/events{/privacy}', 'received_events_url': 'https://api.github.com/users/julien-c/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-07-11T17:08:33Z', 'updated_at': '2023-07-11T17:08:33Z', 'author_association': 'MEMBER', 'body': '> The dataset viewer on the Hugging Face website is incredibly useful\r\n\r\n@mariosasko i think @lilyorlilypad wants to run the new dataset-viewer, not the old one', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1631185809/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1631751283', 'html_url': 'https://github.com/huggingface/datasets/issues/6014#issuecomment-1631751283', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/6014', 'id': 1631751283, 'node_id': 'IC_kwDODunzps5hQoxz', 'user': {'login': 'lilyorlilypad', 'id': 105081034, 'node_id': 'U_kgDOBkNoyg', 'avatar_url': 'https://avatars.githubusercontent.com/u/105081034?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/lilyorlilypad', 'html_url': 'https://github.com/lilyorlilypad', 'followers_url': 'https://api.github.com/users/lilyorlilypad/followers', 'following_url': 'https://api.github.com/users/lilyorlilypad/following{/other_user}', 'gists_url': 'https://api.github.com/users/lilyorlilypad/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/lilyorlilypad/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/lilyorlilypad/subscriptions', 'organizations_url': 'https://api.github.com/users/lilyorlilypad/orgs', 'repos_url': 'https://api.github.com/users/lilyorlilypad/repos', 'events_url': 'https://api.github.com/users/lilyorlilypad/events{/privacy}', 'received_events_url': 'https://api.github.com/users/lilyorlilypad/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-07-12T02:21:38Z', 'updated_at': '2023-07-12T02:21:38Z', 'author_association': 'NONE', 'body': '> wants to run the new dataset-viewer, not the old one\r\n\r\nThanks for the clarification for me. I do want to run the new dataset-viewer. ', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1631751283/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1632216581', 'html_url': 'https://github.com/huggingface/datasets/issues/6014#issuecomment-1632216581', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/6014', 'id': 1632216581, 'node_id': 'IC_kwDODunzps5hSaYF', 'user': {'login': 'lhoestq', 'id': 42851186, 'node_id': 'MDQ6VXNlcjQyODUxMTg2', 'avatar_url': 'https://avatars.githubusercontent.com/u/42851186?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/lhoestq', 'html_url': 'https://github.com/lhoestq', 'followers_url': 'https://api.github.com/users/lhoestq/followers', 'following_url': 'https://api.github.com/users/lhoestq/following{/other_user}', 'gists_url': 'https://api.github.com/users/lhoestq/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/lhoestq/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/lhoestq/subscriptions', 'organizations_url': 'https://api.github.com/users/lhoestq/orgs', 'repos_url': 'https://api.github.com/users/lhoestq/repos', 'events_url': 'https://api.github.com/users/lhoestq/events{/privacy}', 'received_events_url': 'https://api.github.com/users/lhoestq/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-07-12T10:02:46Z', 'updated_at': '2023-07-12T10:02:46Z', 'author_association': 'MEMBER', 'body': "It should be possible to run it locally using the HF datasets-server API (docs [here](https://huggingface.co/docs/datasets-server)) but the front end part is not open source (yet ?)\r\n\r\nThe back-end is open source though if you're interested: https://github.com/huggingface/datasets-server\r\nIt automatically converts datasets on HF to Parquet, which is the format we use to power the viewer.", 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1632216581/reactions', 'total_count': 2, '+1': 2, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1632617270', 'html_url': 'https://github.com/huggingface/datasets/issues/6014#issuecomment-1632617270', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/6014', 'id': 1632617270, 'node_id': 'IC_kwDODunzps5hT8M2', 'user': {'login': 'julien-c', 'id': 326577, 'node_id': 'MDQ6VXNlcjMyNjU3Nw==', 'avatar_url': 'https://avatars.githubusercontent.com/u/326577?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/julien-c', 'html_url': 'https://github.com/julien-c', 'followers_url': 'https://api.github.com/users/julien-c/followers', 'following_url': 'https://api.github.com/users/julien-c/following{/other_user}', 'gists_url': 'https://api.github.com/users/julien-c/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/julien-c/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/julien-c/subscriptions', 'organizations_url': 'https://api.github.com/users/julien-c/orgs', 'repos_url': 'https://api.github.com/users/julien-c/repos', 'events_url': 'https://api.github.com/users/julien-c/events{/privacy}', 'received_events_url': 'https://api.github.com/users/julien-c/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-07-12T14:18:49Z', 'updated_at': '2023-07-12T14:18:49Z', 'author_association': 'MEMBER', 'body': "the new frontend would probably be hard to open source, as is, as it's quite intertwined with the Hub's code.\r\n\r\nHowever, at some point it would be amazing to have a community-driven open source implementation of a frontend to datasets-server! ", 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1632617270/reactions', 'total_count': 1, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 1, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}]

[{'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1629183653', 'html_url': 'https://github.com/huggingface/datasets/issues/6013#issuecomment-1629183653', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/6013', 'id': 1629183653, 'node_id': 'IC_kwDODunzps5hG16l', 'user': {'login': 'mariosasko', 'id': 47462742, 'node_id': 'MDQ6VXNlcjQ3NDYyNzQy', 'avatar_url': 'https://avatars.githubusercontent.com/u/47462742?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/mariosasko', 'html_url': 'https://github.com/mariosasko', 'followers_url': 'https://api.github.com/users/mariosasko/followers', 'following_url': 'https://api.github.com/users/mariosasko/following{/other_user}', 'gists_url': 'https://api.github.com/users/mariosasko/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/mariosasko/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/mariosasko/subscriptions', 'organizations_url': 'https://api.github.com/users/mariosasko/orgs', 'repos_url': 'https://api.github.com/users/mariosasko/repos', 'events_url': 'https://api.github.com/users/mariosasko/events{/privacy}', 'received_events_url': 'https://api.github.com/users/mariosasko/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-07-10T15:21:56Z', 'updated_at': '2023-07-10T15:37:52Z', 'author_association': 'CONTRIBUTOR', 'body': 'You can use the `remove_columns` parameter in `map` to avoid duplicating the columns (and save disk space) and then concatenate the original dataset with the map result:\r\n```python\r\nfrom datasets import concatenate_datasets\r\n# dummy example\r\nds_new = ds.map(lambda x: {"new_col": x["col"] + 2}, remove_columns=ds.column_names)\r\nds_combined = concatenate_datasets([ds, ds_new], axis=1)\r\n```\r\n\r\nDoing this automatically is hard to implement efficiently unless we know ahead of time which existing columns will be modified by a `map` transform. We have this info when `input_columns` are specified, so I think this is the only case we can optimize.', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1629183653/reactions', 'total_count': 1, '+1': 1, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}]
[{'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1629137653', 'html_url': 'https://github.com/huggingface/datasets/issues/6012#issuecomment-1629137653', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/6012', 'id': 1629137653, 'node_id': 'IC_kwDODunzps5hGqr1', 'user': {'login': 'mariosasko', 'id': 47462742, 'node_id': 'MDQ6VXNlcjQ3NDYyNzQy', 'avatar_url': 'https://avatars.githubusercontent.com/u/47462742?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/mariosasko', 'html_url': 'https://github.com/mariosasko', 'followers_url': 'https://api.github.com/users/mariosasko/followers', 'following_url': 'https://api.github.com/users/mariosasko/following{/other_user}', 'gists_url': 'https://api.github.com/users/mariosasko/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/mariosasko/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/mariosasko/subscriptions', 'organizations_url': 'https://api.github.com/users/mariosasko/orgs', 'repos_url': 'https://api.github.com/users/mariosasko/repos', 'events_url': 'https://api.github.com/users/mariosasko/events{/privacy}', 'received_events_url': 'https://api.github.com/users/mariosasko/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-07-10T14:54:57Z', 'updated_at': '2023-07-10T14:54:57Z', 'author_association': 'CONTRIBUTOR', 'body': "You can use `with_transform` to get a new dataset object.\r\n\r\nSupport for lazy `map` has already been discussed [here](https://github.com/huggingface/datasets/issues/3385) a little bit. Personally, I'm not a fan, as this would make `map` even more complex. ", 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1629137653/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1629143476', 'html_url': 'https://github.com/huggingface/datasets/issues/6012#issuecomment-1629143476', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/6012', 'id': 1629143476, 'node_id': 'IC_kwDODunzps5hGsG0', 'user': {'login': 'NightMachinery', 'id': 36224762, 'node_id': 'MDQ6VXNlcjM2MjI0NzYy', 'avatar_url': 'https://avatars.githubusercontent.com/u/36224762?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/NightMachinery', 'html_url': 'https://github.com/NightMachinery', 'followers_url': 'https://api.github.com/users/NightMachinery/followers', 'following_url': 'https://api.github.com/users/NightMachinery/following{/other_user}', 'gists_url': 'https://api.github.com/users/NightMachinery/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/NightMachinery/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/NightMachinery/subscriptions', 'organizations_url': 'https://api.github.com/users/NightMachinery/orgs', 'repos_url': 'https://api.github.com/users/NightMachinery/repos', 'events_url': 'https://api.github.com/users/NightMachinery/events{/privacy}', 'received_events_url': 'https://api.github.com/users/NightMachinery/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-07-10T14:58:24Z', 'updated_at': '2023-07-10T14:58:24Z', 'author_association': 'CONTRIBUTOR', 'body': "> You can use `with_transform` to get a new dataset object.\r\n> \r\n> Support for lazy `map` has already been discussed [here](https://github.com/huggingface/datasets/issues/3385) a little bit. Personally, I'm not a fan, as this would make `map` even more complex.\r\n\r\nI read about IterableDataset, and it seems to have lazy mapping. But I can't figure out how to convert an IterableDataset into a normal one when needed.\r\n\r\n`with_transform` still does not chain AFAIU.", 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1629143476/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1629212065', 'html_url': 'https://github.com/huggingface/datasets/issues/6012#issuecomment-1629212065', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/6012', 'id': 1629212065, 'node_id': 'IC_kwDODunzps5hG82h', 'user': {'login': 'mariosasko', 'id': 47462742, 'node_id': 'MDQ6VXNlcjQ3NDYyNzQy', 'avatar_url': 'https://avatars.githubusercontent.com/u/47462742?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/mariosasko', 'html_url': 'https://github.com/mariosasko', 'followers_url': 'https://api.github.com/users/mariosasko/followers', 'following_url': 'https://api.github.com/users/mariosasko/following{/other_user}', 'gists_url': 'https://api.github.com/users/mariosasko/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/mariosasko/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/mariosasko/subscriptions', 'organizations_url': 'https://api.github.com/users/mariosasko/orgs', 'repos_url': 'https://api.github.com/users/mariosasko/repos', 'events_url': 'https://api.github.com/users/mariosasko/events{/privacy}', 'received_events_url': 'https://api.github.com/users/mariosasko/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-07-10T15:37:25Z', 'updated_at': '2023-07-10T15:37:25Z', 'author_association': 'CONTRIBUTOR', 'body': "> I read about IterableDataset, and it seems to have lazy mapping. But I can't figure out how to convert an IterableDataset into a normal one when needed.\r\n\r\nYou must cache an `IterableDataset` to disk to load it as a `Dataset`. One way to do this is with `Dataset.from_generator`:\r\n```python\r\nfrom functools import partial\r\nfrom datasets import Dataset\r\n\r\ndef gen_from_iterable_dataset(iterable_ds)\r\n    yield from iterable_ds\r\n\r\nds = Dataset.from_generator(partial(gen_from_iterable_dataset, iterable_ds), features=iterable_ds.features})\r\n```\r\n\r\n> with_transform still does not chain AFAIU.\r\n\r\nYes, not supported yet - the solution is to combine the transforms into a single one.", 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1629212065/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1631120611', 'html_url': 'https://github.com/huggingface/datasets/issues/6012#issuecomment-1631120611', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/6012', 'id': 1631120611, 'node_id': 'IC_kwDODunzps5hOOzj', 'user': {'login': 'lhoestq', 'id': 42851186, 'node_id': 'MDQ6VXNlcjQyODUxMTg2', 'avatar_url': 'https://avatars.githubusercontent.com/u/42851186?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/lhoestq', 'html_url': 'https://github.com/lhoestq', 'followers_url': 'https://api.github.com/users/lhoestq/followers', 'following_url': 'https://api.github.com/users/lhoestq/following{/other_user}', 'gists_url': 'https://api.github.com/users/lhoestq/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/lhoestq/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/lhoestq/subscriptions', 'organizations_url': 'https://api.github.com/users/lhoestq/orgs', 'repos_url': 'https://api.github.com/users/lhoestq/repos', 'events_url': 'https://api.github.com/users/lhoestq/events{/privacy}', 'received_events_url': 'https://api.github.com/users/lhoestq/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-07-11T16:19:57Z', 'updated_at': '2023-07-11T16:19:57Z', 'author_association': 'MEMBER', 'body': 'I wonder if it would be beneficial to have a dedicated method to do that ? Maybe a `.save_to_disk()` so that the user can reload the resulting dataset later ?', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1631120611/reactions', 'total_count': 1, '+1': 1, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1634820043', 'html_url': 'https://github.com/huggingface/datasets/issues/6012#issuecomment-1634820043', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/6012', 'id': 1634820043, 'node_id': 'IC_kwDODunzps5hcV_L', 'user': {'login': 'NightMachinery', 'id': 36224762, 'node_id': 'MDQ6VXNlcjM2MjI0NzYy', 'avatar_url': 'https://avatars.githubusercontent.com/u/36224762?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/NightMachinery', 'html_url': 'https://github.com/NightMachinery', 'followers_url': 'https://api.github.com/users/NightMachinery/followers', 'following_url': 'https://api.github.com/users/NightMachinery/following{/other_user}', 'gists_url': 'https://api.github.com/users/NightMachinery/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/NightMachinery/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/NightMachinery/subscriptions', 'organizations_url': 'https://api.github.com/users/NightMachinery/orgs', 'repos_url': 'https://api.github.com/users/NightMachinery/repos', 'events_url': 'https://api.github.com/users/NightMachinery/events{/privacy}', 'received_events_url': 'https://api.github.com/users/NightMachinery/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-07-13T19:52:20Z', 'updated_at': '2023-07-13T19:52:20Z', 'author_association': 'CONTRIBUTOR', 'body': '> ```python\r\n> from functools import partial\r\n> from datasets import Dataset\r\n> \r\n> def gen_from_iterable_dataset(iterable_ds)\r\n>     yield from iterable_ds\r\n> \r\n> ds = Dataset.from_generator(partial(gen_from_iterable_dataset, iterable_ds), features=iterable_ds.features})\r\n> ```\r\n\r\n@mariosasko With these complex mapping functions, what hash will be used to cache this dataset?\r\n', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1634820043/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}]

[{'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1628999441', 'html_url': 'https://github.com/huggingface/datasets/issues/6011#issuecomment-1628999441', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/6011', 'id': 1628999441, 'node_id': 'IC_kwDODunzps5hGI8R', 'user': {'login': 'mariosasko', 'id': 47462742, 'node_id': 'MDQ6VXNlcjQ3NDYyNzQy', 'avatar_url': 'https://avatars.githubusercontent.com/u/47462742?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/mariosasko', 'html_url': 'https://github.com/mariosasko', 'followers_url': 'https://api.github.com/users/mariosasko/followers', 'following_url': 'https://api.github.com/users/mariosasko/following{/other_user}', 'gists_url': 'https://api.github.com/users/mariosasko/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/mariosasko/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/mariosasko/subscriptions', 'organizations_url': 'https://api.github.com/users/mariosasko/orgs', 'repos_url': 'https://api.github.com/users/mariosasko/repos', 'events_url': 'https://api.github.com/users/mariosasko/events{/privacy}', 'received_events_url': 'https://api.github.com/users/mariosasko/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-07-10T13:43:41Z', 'updated_at': '2023-07-10T13:43:41Z', 'author_association': 'CONTRIBUTOR', 'body': 'Hi! You can do `ds.get_index("embeddings").faiss_index.metric_type` to get the metric type and then match the result with the FAISS metric [enum](https://github.com/facebookresearch/faiss/blob/43d86e30736ede853c384b24667fc3ab897d6ba9/faiss/MetricType.h#L22-L36) (should be L2).', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1628999441/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1630032356', 'html_url': 'https://github.com/huggingface/datasets/issues/6011#issuecomment-1630032356', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/6011', 'id': 1630032356, 'node_id': 'IC_kwDODunzps5hKFHk', 'user': {'login': 'YichiRockyZhang', 'id': 29335344, 'node_id': 'MDQ6VXNlcjI5MzM1MzQ0', 'avatar_url': 'https://avatars.githubusercontent.com/u/29335344?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/YichiRockyZhang', 'html_url': 'https://github.com/YichiRockyZhang', 'followers_url': 'https://api.github.com/users/YichiRockyZhang/followers', 'following_url': 'https://api.github.com/users/YichiRockyZhang/following{/other_user}', 'gists_url': 'https://api.github.com/users/YichiRockyZhang/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/YichiRockyZhang/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/YichiRockyZhang/subscriptions', 'organizations_url': 'https://api.github.com/users/YichiRockyZhang/orgs', 'repos_url': 'https://api.github.com/users/YichiRockyZhang/repos', 'events_url': 'https://api.github.com/users/YichiRockyZhang/events{/privacy}', 'received_events_url': 'https://api.github.com/users/YichiRockyZhang/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-07-11T03:02:35Z', 'updated_at': '2023-07-11T03:02:35Z', 'author_association': 'NONE', 'body': "Ah! Thank you for pointing this out. FYI: the enum indicates it's using the inner product. Using `torch.inner` or `torch.dot` still produces a discrepancy compared to the built-in score. I think this is because of the compression/quantization that occurs with the FAISS index.", 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1630032356/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}]
[{'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1627738973', 'html_url': 'https://github.com/huggingface/datasets/issues/6010#issuecomment-1627738973', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/6010', 'id': 1627738973, 'node_id': 'IC_kwDODunzps5hBVNd', 'user': {'login': 'Ganryuu', 'id': 63643948, 'node_id': 'MDQ6VXNlcjYzNjQzOTQ4', 'avatar_url': 'https://avatars.githubusercontent.com/u/63643948?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/Ganryuu', 'html_url': 'https://github.com/Ganryuu', 'followers_url': 'https://api.github.com/users/Ganryuu/followers', 'following_url': 'https://api.github.com/users/Ganryuu/following{/other_user}', 'gists_url': 'https://api.github.com/users/Ganryuu/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/Ganryuu/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/Ganryuu/subscriptions', 'organizations_url': 'https://api.github.com/users/Ganryuu/orgs', 'repos_url': 'https://api.github.com/users/Ganryuu/repos', 'events_url': 'https://api.github.com/users/Ganryuu/events{/privacy}', 'received_events_url': 'https://api.github.com/users/Ganryuu/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-07-09T14:58:53Z', 'updated_at': '2023-07-09T14:58:53Z', 'author_association': 'NONE', 'body': 'I want to take a shot at this if possible ', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1627738973/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1629099479', 'html_url': 'https://github.com/huggingface/datasets/issues/6010#issuecomment-1629099479', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/6010', 'id': 1629099479, 'node_id': 'IC_kwDODunzps5hGhXX', 'user': {'login': 'mariosasko', 'id': 47462742, 'node_id': 'MDQ6VXNlcjQ3NDYyNzQy', 'avatar_url': 'https://avatars.githubusercontent.com/u/47462742?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/mariosasko', 'html_url': 'https://github.com/mariosasko', 'followers_url': 'https://api.github.com/users/mariosasko/followers', 'following_url': 'https://api.github.com/users/mariosasko/following{/other_user}', 'gists_url': 'https://api.github.com/users/mariosasko/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/mariosasko/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/mariosasko/subscriptions', 'organizations_url': 'https://api.github.com/users/mariosasko/orgs', 'repos_url': 'https://api.github.com/users/mariosasko/repos', 'events_url': 'https://api.github.com/users/mariosasko/events{/privacy}', 'received_events_url': 'https://api.github.com/users/mariosasko/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-07-10T14:32:54Z', 'updated_at': '2023-07-10T14:32:54Z', 'author_association': 'CONTRIBUTOR', 'body': 'Yes, feel free to work on this.\r\n\r\nYou can check the PyArrow Table `__repr__`  and Polars DataFrame `__repr__`/`_repr_html_` implementations for some pointers/ideas.', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1629099479/reactions', 'total_count': 1, '+1': 1, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}]

[{'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1622320308', 'html_url': 'https://github.com/huggingface/datasets/issues/6008#issuecomment-1622320308', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/6008', 'id': 1622320308, 'node_id': 'IC_kwDODunzps5gsqS0', 'user': {'login': 'mariosasko', 'id': 47462742, 'node_id': 'MDQ6VXNlcjQ3NDYyNzQy', 'avatar_url': 'https://avatars.githubusercontent.com/u/47462742?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/mariosasko', 'html_url': 'https://github.com/mariosasko', 'followers_url': 'https://api.github.com/users/mariosasko/followers', 'following_url': 'https://api.github.com/users/mariosasko/following{/other_user}', 'gists_url': 'https://api.github.com/users/mariosasko/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/mariosasko/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/mariosasko/subscriptions', 'organizations_url': 'https://api.github.com/users/mariosasko/orgs', 'repos_url': 'https://api.github.com/users/mariosasko/repos', 'events_url': 'https://api.github.com/users/mariosasko/events{/privacy}', 'received_events_url': 'https://api.github.com/users/mariosasko/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-07-05T19:09:38Z', 'updated_at': '2023-07-05T19:09:38Z', 'author_association': 'CONTRIBUTOR', 'body': 'By default, we write data to disk (so it can be memory-mapped) every 1000 rows/samples. You can control this with the `writer_batch_size` parameter. Also, when working with fixed-size arrays, the `ArrayXD` feature types yield better performance (e.g., in your case, `features=datasets.Features({"i": datasets.Array3D(shape=(512,512,3), dtype="float32")})` should be faster).\r\n\r\nOur support for multi-dim arrays could be better, and we plan to improve it as part of https://github.com/huggingface/datasets/issues/5272.', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1622320308/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1622567452', 'html_url': 'https://github.com/huggingface/datasets/issues/6008#issuecomment-1622567452', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/6008', 'id': 1622567452, 'node_id': 'IC_kwDODunzps5gtmoc', 'user': {'login': 'andreemic', 'id': 27695722, 'node_id': 'MDQ6VXNlcjI3Njk1NzIy', 'avatar_url': 'https://avatars.githubusercontent.com/u/27695722?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/andreemic', 'html_url': 'https://github.com/andreemic', 'followers_url': 'https://api.github.com/users/andreemic/followers', 'following_url': 'https://api.github.com/users/andreemic/following{/other_user}', 'gists_url': 'https://api.github.com/users/andreemic/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/andreemic/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/andreemic/subscriptions', 'organizations_url': 'https://api.github.com/users/andreemic/orgs', 'repos_url': 'https://api.github.com/users/andreemic/repos', 'events_url': 'https://api.github.com/users/andreemic/events{/privacy}', 'received_events_url': 'https://api.github.com/users/andreemic/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-07-05T21:44:33Z', 'updated_at': '2023-07-05T21:44:33Z', 'author_association': 'NONE', 'body': '> By default, we write data to disk (so it can be memory-mapped) every 1000 rows/samples. You can control this with the `writer_batch_size` parameter. Also, when working with fixed-size arrays, the `ArrayXD` feature types yield better performance (e.g., in your case, `features=datasets.Features({"i": datasets.Array3D(shape=(512,512,3), dtype="float32")})` should be faster).\r\n> \r\n> Our support for multi-dim arrays could be better, and we plan to improve it as part of #5272.\r\n\r\nThanks for the explanation! The Image array was just for demonstration, I use PIL Images in practice. Does that make a difference? What\'s the best approach for a dataset with PIL Images as rows?', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1622567452/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1623972849', 'html_url': 'https://github.com/huggingface/datasets/issues/6008#issuecomment-1623972849', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/6008', 'id': 1623972849, 'node_id': 'IC_kwDODunzps5gy9vx', 'user': {'login': 'mariosasko', 'id': 47462742, 'node_id': 'MDQ6VXNlcjQ3NDYyNzQy', 'avatar_url': 'https://avatars.githubusercontent.com/u/47462742?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/mariosasko', 'html_url': 'https://github.com/mariosasko', 'followers_url': 'https://api.github.com/users/mariosasko/followers', 'following_url': 'https://api.github.com/users/mariosasko/following{/other_user}', 'gists_url': 'https://api.github.com/users/mariosasko/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/mariosasko/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/mariosasko/subscriptions', 'organizations_url': 'https://api.github.com/users/mariosasko/orgs', 'repos_url': 'https://api.github.com/users/mariosasko/repos', 'events_url': 'https://api.github.com/users/mariosasko/events{/privacy}', 'received_events_url': 'https://api.github.com/users/mariosasko/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-07-06T16:29:25Z', 'updated_at': '2023-07-06T16:32:02Z', 'author_association': 'CONTRIBUTOR', 'body': "It's best to use the `datasets.Image()` feature type for PIL images (to save space) :)", 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1623972849/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}]

[{'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1621109784', 'html_url': 'https://github.com/huggingface/datasets/issues/6006#issuecomment-1621109784', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/6006', 'id': 1621109784, 'node_id': 'IC_kwDODunzps5goCwY', 'user': {'login': 'xipq', 'id': 115634163, 'node_id': 'U_kgDOBuRv8w', 'avatar_url': 'https://avatars.githubusercontent.com/u/115634163?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/xipq', 'html_url': 'https://github.com/xipq', 'followers_url': 'https://api.github.com/users/xipq/followers', 'following_url': 'https://api.github.com/users/xipq/following{/other_user}', 'gists_url': 'https://api.github.com/users/xipq/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/xipq/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/xipq/subscriptions', 'organizations_url': 'https://api.github.com/users/xipq/orgs', 'repos_url': 'https://api.github.com/users/xipq/repos', 'events_url': 'https://api.github.com/users/xipq/events{/privacy}', 'received_events_url': 'https://api.github.com/users/xipq/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-07-05T06:31:01Z', 'updated_at': '2023-07-05T06:31:01Z', 'author_association': 'NONE', 'body': 'issue due to corrupted download files. resolved after cleaning download cache. sorry for any inconvinence.', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1621109784/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}]

[{'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1618983451', 'html_url': 'https://github.com/huggingface/datasets/pull/6004#issuecomment-1618983451', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/6004', 'id': 1618983451, 'node_id': 'IC_kwDODunzps5gf7ob', 'user': {'login': 'github-actions[bot]', 'id': 41898282, 'node_id': 'MDM6Qm90NDE4OTgyODI=', 'avatar_url': 'https://avatars.githubusercontent.com/in/15368?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/github-actions%5Bbot%5D', 'html_url': 'https://github.com/apps/github-actions', 'followers_url': 'https://api.github.com/users/github-actions%5Bbot%5D/followers', 'following_url': 'https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}', 'gists_url': 'https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/github-actions%5Bbot%5D/subscriptions', 'organizations_url': 'https://api.github.com/users/github-actions%5Bbot%5D/orgs', 'repos_url': 'https://api.github.com/users/github-actions%5Bbot%5D/repos', 'events_url': 'https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}', 'received_events_url': 'https://api.github.com/users/github-actions%5Bbot%5D/received_events', 'type': 'Bot', 'site_admin': False}, 'created_at': '2023-07-03T18:29:33Z', 'updated_at': '2023-07-03T18:29:33Z', 'author_association': 'NONE', 'body': '<details>\n<summary>Show benchmarks</summary>\n\nPyArrow==8.0.0\n\n<details>\n<summary>Show updated benchmarks!</summary>\n\n### Benchmark: benchmark_array_xd.json\n\n| metric | read_batch_formatted_as_numpy after write_array2d | read_batch_formatted_as_numpy after write_flattened_sequence | read_batch_formatted_as_numpy after write_nested_sequence | read_batch_unformated after write_array2d | read_batch_unformated after write_flattened_sequence | read_batch_unformated after write_nested_sequence | read_col_formatted_as_numpy after write_array2d | read_col_formatted_as_numpy after write_flattened_sequence | read_col_formatted_as_numpy after write_nested_sequence | read_col_unformated after write_array2d | read_col_unformated after write_flattened_sequence | read_col_unformated after write_nested_sequence | read_formatted_as_numpy after write_array2d | read_formatted_as_numpy after write_flattened_sequence | read_formatted_as_numpy after write_nested_sequence | read_unformated after write_array2d | read_unformated after write_flattened_sequence | read_unformated after write_nested_sequence | write_array2d | write_flattened_sequence | write_nested_sequence |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.006897 / 0.011353 (-0.004456) | 0.004207 / 0.011008 (-0.006802) | 0.104828 / 0.038508 (0.066320) | 0.048054 / 0.023109 (0.024945) | 0.373991 / 0.275898 (0.098093) | 0.426740 / 0.323480 (0.103260) | 0.005540 / 0.007986 (-0.002446) | 0.003531 / 0.004328 (-0.000797) | 0.079304 / 0.004250 (0.075053) | 0.066996 / 0.037052 (0.029944) | 0.370675 / 0.258489 (0.112186) | 0.414154 / 0.293841 (0.120313) | 0.031567 / 0.128546 (-0.096979) | 0.008843 / 0.075646 (-0.066803) | 0.357426 / 0.419271 (-0.061845) | 0.067040 / 0.043533 (0.023508) | 0.362384 / 0.255139 (0.107245) | 0.376056 / 0.283200 (0.092856) | 0.032985 / 0.141683 (-0.108697) | 1.560603 / 1.452155 (0.108448) | 1.619024 / 1.492716 (0.126308) |\n\n### Benchmark: benchmark_getitem\\_100B.json\n\n| metric | get_batch_of\\_1024\\_random_rows | get_batch_of\\_1024\\_rows | get_first_row | get_last_row |\n|--------|---|---|---|---|\n| new / old (diff) | 0.229059 / 0.018006 (0.211053) | 0.440513 / 0.000490 (0.440023) | 0.004647 / 0.000200 (0.004447) | 0.000085 / 0.000054 (0.000030) |\n\n### Benchmark: benchmark_indices_mapping.json\n\n| metric | select | shard | shuffle | sort | train_test_split |\n|--------|---|---|---|---|---|\n| new / old (diff) | 0.029517 / 0.037411 (-0.007894) | 0.120974 / 0.014526 (0.106448) | 0.125070 / 0.176557 (-0.051486) | 0.184695 / 0.737135 (-0.552441) | 0.130244 / 0.296338 (-0.166095) |\n\n### Benchmark: benchmark_iterating.json\n\n| metric | read 5000 | read 50000 | read_batch 50000 10 | read_batch 50000 100 | read_batch 50000 1000 | read_formatted numpy 5000 | read_formatted pandas 5000 | read_formatted tensorflow 5000 | read_formatted torch 5000 | read_formatted_batch numpy 5000 10 | read_formatted_batch numpy 5000 1000 | shuffled read 5000 | shuffled read 50000 | shuffled read_batch 50000 10 | shuffled read_batch 50000 100 | shuffled read_batch 50000 1000 | shuffled read_formatted numpy 5000 | shuffled read_formatted_batch numpy 5000 10 | shuffled read_formatted_batch numpy 5000 1000 |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.436930 / 0.215209 (0.221721) | 4.356118 / 2.077655 (2.278463) | 2.049169 / 1.504120 (0.545049) | 1.842898 / 1.541195 (0.301703) | 1.918948 / 1.468490 (0.450458) | 0.553573 / 4.584777 (-4.031204) | 3.883195 / 3.745712 (0.137483) | 3.209780 / 5.269862 (-2.060081) | 1.551707 / 4.565676 (-3.013970) | 0.068181 / 0.424275 (-0.356094) | 0.012370 / 0.007607 (0.004762) | 0.539899 / 0.226044 (0.313854) | 5.380008 / 2.268929 (3.111079) | 2.518178 / 55.444624 (-52.926446) | 2.174190 / 6.876477 (-4.702286) | 2.317812 / 2.142072 (0.175740) | 0.674154 / 4.805227 (-4.131073) | 0.149313 / 6.500664 (-6.351351) | 0.068297 / 0.075469 (-0.007172) |\n\n### Benchmark: benchmark_map_filter.json\n\n| metric | filter | map fast-tokenizer batched | map identity | map identity batched | map no-op batched | map no-op batched numpy | map no-op batched pandas | map no-op batched pytorch | map no-op batched tensorflow |\n|--------|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 1.261426 / 1.841788 (-0.580362) | 15.316378 / 8.074308 (7.242070) | 13.573512 / 10.191392 (3.382120) | 0.190022 / 0.680424 (-0.490401) | 0.018697 / 0.534201 (-0.515504) | 0.448122 / 0.579283 (-0.131161) | 0.435044 / 0.434364 (0.000681) | 0.550065 / 0.540337 (0.009728) | 0.653547 / 1.386936 (-0.733389) |\n\n</details>\nPyArrow==latest\n\n<details>\n<summary>Show updated benchmarks!</summary>\n\n### Benchmark: benchmark_array_xd.json\n\n| metric | read_batch_formatted_as_numpy after write_array2d | read_batch_formatted_as_numpy after write_flattened_sequence | read_batch_formatted_as_numpy after write_nested_sequence | read_batch_unformated after write_array2d | read_batch_unformated after write_flattened_sequence | read_batch_unformated after write_nested_sequence | read_col_formatted_as_numpy after write_array2d | read_col_formatted_as_numpy after write_flattened_sequence | read_col_formatted_as_numpy after write_nested_sequence | read_col_unformated after write_array2d | read_col_unformated after write_flattened_sequence | read_col_unformated after write_nested_sequence | read_formatted_as_numpy after write_array2d | read_formatted_as_numpy after write_flattened_sequence | read_formatted_as_numpy after write_nested_sequence | read_unformated after write_array2d | read_unformated after write_flattened_sequence | read_unformated after write_nested_sequence | write_array2d | write_flattened_sequence | write_nested_sequence |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.007116 / 0.011353 (-0.004237) | 0.004375 / 0.011008 (-0.006633) | 0.081793 / 0.038508 (0.043285) | 0.047980 / 0.023109 (0.024871) | 0.392185 / 0.275898 (0.116287) | 0.462263 / 0.323480 (0.138783) | 0.005574 / 0.007986 (-0.002412) | 0.003552 / 0.004328 (-0.000776) | 0.080413 / 0.004250 (0.076162) | 0.065539 / 0.037052 (0.028487) | 0.413137 / 0.258489 (0.154648) | 0.467377 / 0.293841 (0.173536) | 0.034386 / 0.128546 (-0.094160) | 0.009183 / 0.075646 (-0.066464) | 0.087542 / 0.419271 (-0.331730) | 0.053954 / 0.043533 (0.010421) | 0.385096 / 0.255139 (0.129957) | 0.404900 / 0.283200 (0.121701) | 0.025908 / 0.141683 (-0.115775) | 1.550159 / 1.452155 (0.098005) | 1.598794 / 1.492716 (0.106078) |\n\n### Benchmark: benchmark_getitem\\_100B.json\n\n| metric | get_batch_of\\_1024\\_random_rows | get_batch_of\\_1024\\_rows | get_first_row | get_last_row |\n|--------|---|---|---|---|\n| new / old (diff) | 0.246222 / 0.018006 (0.228216) | 0.441095 / 0.000490 (0.440605) | 0.006863 / 0.000200 (0.006663) | 0.000109 / 0.000054 (0.000055) |\n\n### Benchmark: benchmark_indices_mapping.json\n\n| metric | select | shard | shuffle | sort | train_test_split |\n|--------|---|---|---|---|---|\n| new / old (diff) | 0.032179 / 0.037411 (-0.005233) | 0.120112 / 0.014526 (0.105586) | 0.129326 / 0.176557 (-0.047230) | 0.184542 / 0.737135 (-0.552593) | 0.135038 / 0.296338 (-0.161300) |\n\n### Benchmark: benchmark_iterating.json\n\n| metric | read 5000 | read 50000 | read_batch 50000 10 | read_batch 50000 100 | read_batch 50000 1000 | read_formatted numpy 5000 | read_formatted pandas 5000 | read_formatted tensorflow 5000 | read_formatted torch 5000 | read_formatted_batch numpy 5000 10 | read_formatted_batch numpy 5000 1000 | shuffled read 5000 | shuffled read 50000 | shuffled read_batch 50000 10 | shuffled read_batch 50000 100 | shuffled read_batch 50000 1000 | shuffled read_formatted numpy 5000 | shuffled read_formatted_batch numpy 5000 10 | shuffled read_formatted_batch numpy 5000 1000 |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.459002 / 0.215209 (0.243793) | 4.580258 / 2.077655 (2.502604) | 2.296689 / 1.504120 (0.792569) | 2.104338 / 1.541195 (0.563143) | 2.182896 / 1.468490 (0.714406) | 0.546447 / 4.584777 (-4.038330) | 3.854047 / 3.745712 (0.108335) | 1.873829 / 5.269862 (-3.396032) | 1.116484 / 4.565676 (-3.449193) | 0.067158 / 0.424275 (-0.357117) | 0.012035 / 0.007607 (0.004428) | 0.556642 / 0.226044 (0.330597) | 5.574436 / 2.268929 (3.305508) | 2.828223 / 55.444624 (-52.616402) | 2.519851 / 6.876477 (-4.356626) | 2.668594 / 2.142072 (0.526521) | 0.675989 / 4.805227 (-4.129238) | 0.146075 / 6.500664 (-6.354589) | 0.067788 / 0.075469 (-0.007681) |\n\n### Benchmark: benchmark_map_filter.json\n\n| metric | filter | map fast-tokenizer batched | map identity | map identity batched | map no-op batched | map no-op batched numpy | map no-op batched pandas | map no-op batched pytorch | map no-op batched tensorflow |\n|--------|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 1.345958 / 1.841788 (-0.495830) | 15.672748 / 8.074308 (7.598440) | 14.937583 / 10.191392 (4.746191) | 0.163479 / 0.680424 (-0.516945) | 0.018364 / 0.534201 (-0.515837) | 0.433296 / 0.579283 (-0.145987) | 0.432463 / 0.434364 (-0.001901) | 0.512000 / 0.540337 (-0.028338) | 0.619397 / 1.386936 (-0.767539) |\n\n</details>\n</details>\n\n![](https://cml.dev/watermark.png#0832d48a07ed00b406271f4b4439e6d54ae38ebf "CML watermark")\n', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1618983451/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1618987509', 'html_url': 'https://github.com/huggingface/datasets/pull/6004#issuecomment-1618987509', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/6004', 'id': 1618987509, 'node_id': 'IC_kwDODunzps5gf8n1', 'user': {'login': 'HuggingFaceDocBuilderDev', 'id': 99929124, 'node_id': 'U_kgDOBfTMJA', 'avatar_url': 'https://avatars.githubusercontent.com/u/99929124?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/HuggingFaceDocBuilderDev', 'html_url': 'https://github.com/HuggingFaceDocBuilderDev', 'followers_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/followers', 'following_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/following{/other_user}', 'gists_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/subscriptions', 'organizations_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/orgs', 'repos_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/repos', 'events_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/events{/privacy}', 'received_events_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-07-03T18:34:20Z', 'updated_at': '2023-07-06T16:55:54Z', 'author_association': 'NONE', 'body': '_The documentation is not available anymore as the PR was closed or merged._', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1618987509/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1623981849', 'html_url': 'https://github.com/huggingface/datasets/pull/6004#issuecomment-1623981849', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/6004', 'id': 1623981849, 'node_id': 'IC_kwDODunzps5gy_8Z', 'user': {'login': 'github-actions[bot]', 'id': 41898282, 'node_id': 'MDM6Qm90NDE4OTgyODI=', 'avatar_url': 'https://avatars.githubusercontent.com/in/15368?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/github-actions%5Bbot%5D', 'html_url': 'https://github.com/apps/github-actions', 'followers_url': 'https://api.github.com/users/github-actions%5Bbot%5D/followers', 'following_url': 'https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}', 'gists_url': 'https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/github-actions%5Bbot%5D/subscriptions', 'organizations_url': 'https://api.github.com/users/github-actions%5Bbot%5D/orgs', 'repos_url': 'https://api.github.com/users/github-actions%5Bbot%5D/repos', 'events_url': 'https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}', 'received_events_url': 'https://api.github.com/users/github-actions%5Bbot%5D/received_events', 'type': 'Bot', 'site_admin': False}, 'created_at': '2023-07-06T16:36:53Z', 'updated_at': '2023-07-06T16:36:53Z', 'author_association': 'NONE', 'body': '<details>\n<summary>Show benchmarks</summary>\n\nPyArrow==8.0.0\n\n<details>\n<summary>Show updated benchmarks!</summary>\n\n### Benchmark: benchmark_array_xd.json\n\n| metric | read_batch_formatted_as_numpy after write_array2d | read_batch_formatted_as_numpy after write_flattened_sequence | read_batch_formatted_as_numpy after write_nested_sequence | read_batch_unformated after write_array2d | read_batch_unformated after write_flattened_sequence | read_batch_unformated after write_nested_sequence | read_col_formatted_as_numpy after write_array2d | read_col_formatted_as_numpy after write_flattened_sequence | read_col_formatted_as_numpy after write_nested_sequence | read_col_unformated after write_array2d | read_col_unformated after write_flattened_sequence | read_col_unformated after write_nested_sequence | read_formatted_as_numpy after write_array2d | read_formatted_as_numpy after write_flattened_sequence | read_formatted_as_numpy after write_nested_sequence | read_unformated after write_array2d | read_unformated after write_flattened_sequence | read_unformated after write_nested_sequence | write_array2d | write_flattened_sequence | write_nested_sequence |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.010097 / 0.011353 (-0.001256) | 0.005070 / 0.011008 (-0.005939) | 0.118638 / 0.038508 (0.080130) | 0.043651 / 0.023109 (0.020542) | 0.356074 / 0.275898 (0.080176) | 0.414578 / 0.323480 (0.091098) | 0.005939 / 0.007986 (-0.002046) | 0.004927 / 0.004328 (0.000598) | 0.089545 / 0.004250 (0.085294) | 0.067533 / 0.037052 (0.030481) | 0.371550 / 0.258489 (0.113061) | 0.417808 / 0.293841 (0.123967) | 0.045186 / 0.128546 (-0.083361) | 0.015763 / 0.075646 (-0.059883) | 0.393304 / 0.419271 (-0.025967) | 0.065123 / 0.043533 (0.021591) | 0.345057 / 0.255139 (0.089918) | 0.378809 / 0.283200 (0.095610) | 0.033243 / 0.141683 (-0.108440) | 1.679956 / 1.452155 (0.227802) | 1.775456 / 1.492716 (0.282739) |\n\n### Benchmark: benchmark_getitem\\_100B.json\n\n| metric | get_batch_of\\_1024\\_random_rows | get_batch_of\\_1024\\_rows | get_first_row | get_last_row |\n|--------|---|---|---|---|\n| new / old (diff) | 0.229723 / 0.018006 (0.211717) | 0.554630 / 0.000490 (0.554140) | 0.008729 / 0.000200 (0.008529) | 0.000183 / 0.000054 (0.000129) |\n\n### Benchmark: benchmark_indices_mapping.json\n\n| metric | select | shard | shuffle | sort | train_test_split |\n|--------|---|---|---|---|---|\n| new / old (diff) | 0.027284 / 0.037411 (-0.010128) | 0.114741 / 0.014526 (0.100215) | 0.129188 / 0.176557 (-0.047369) | 0.189270 / 0.737135 (-0.547866) | 0.126000 / 0.296338 (-0.170339) |\n\n### Benchmark: benchmark_iterating.json\n\n| metric | read 5000 | read 50000 | read_batch 50000 10 | read_batch 50000 100 | read_batch 50000 1000 | read_formatted numpy 5000 | read_formatted pandas 5000 | read_formatted tensorflow 5000 | read_formatted torch 5000 | read_formatted_batch numpy 5000 10 | read_formatted_batch numpy 5000 1000 | shuffled read 5000 | shuffled read 50000 | shuffled read_batch 50000 10 | shuffled read_batch 50000 100 | shuffled read_batch 50000 1000 | shuffled read_formatted numpy 5000 | shuffled read_formatted_batch numpy 5000 10 | shuffled read_formatted_batch numpy 5000 1000 |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.580417 / 0.215209 (0.365208) | 5.829337 / 2.077655 (3.751683) | 2.421191 / 1.504120 (0.917071) | 2.063673 / 1.541195 (0.522479) | 2.133427 / 1.468490 (0.664937) | 0.830964 / 4.584777 (-3.753813) | 5.107139 / 3.745712 (1.361427) | 4.599451 / 5.269862 (-0.670410) | 2.406502 / 4.565676 (-2.159175) | 0.100422 / 0.424275 (-0.323853) | 0.011850 / 0.007607 (0.004243) | 0.741881 / 0.226044 (0.515836) | 7.425689 / 2.268929 (5.156760) | 3.068948 / 55.444624 (-52.375676) | 2.496292 / 6.876477 (-4.380184) | 2.566420 / 2.142072 (0.424348) | 1.093084 / 4.805227 (-3.712144) | 0.224106 / 6.500664 (-6.276558) | 0.084549 / 0.075469 (0.009080) |\n\n### Benchmark: benchmark_map_filter.json\n\n| metric | filter | map fast-tokenizer batched | map identity | map identity batched | map no-op batched | map no-op batched numpy | map no-op batched pandas | map no-op batched pytorch | map no-op batched tensorflow |\n|--------|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 1.416315 / 1.841788 (-0.425473) | 16.306901 / 8.074308 (8.232593) | 19.792419 / 10.191392 (9.601027) | 0.224223 / 0.680424 (-0.456201) | 0.026385 / 0.534201 (-0.507816) | 0.463460 / 0.579283 (-0.115823) | 0.598385 / 0.434364 (0.164021) | 0.543981 / 0.540337 (0.003644) | 0.647454 / 1.386936 (-0.739482) |\n\n</details>\nPyArrow==latest\n\n<details>\n<summary>Show updated benchmarks!</summary>\n\n### Benchmark: benchmark_array_xd.json\n\n| metric | read_batch_formatted_as_numpy after write_array2d | read_batch_formatted_as_numpy after write_flattened_sequence | read_batch_formatted_as_numpy after write_nested_sequence | read_batch_unformated after write_array2d | read_batch_unformated after write_flattened_sequence | read_batch_unformated after write_nested_sequence | read_col_formatted_as_numpy after write_array2d | read_col_formatted_as_numpy after write_flattened_sequence | read_col_formatted_as_numpy after write_nested_sequen

[]
[{'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1618685937', 'html_url': 'https://github.com/huggingface/datasets/pull/6002#issuecomment-1618685937', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/6002', 'id': 1618685937, 'node_id': 'IC_kwDODunzps5gey_x', 'user': {'login': 'mariosasko', 'id': 47462742, 'node_id': 'MDQ6VXNlcjQ3NDYyNzQy', 'avatar_url': 'https://avatars.githubusercontent.com/u/47462742?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/mariosasko', 'html_url': 'https://github.com/mariosasko', 'followers_url': 'https://api.github.com/users/mariosasko/followers', 'following_url': 'https://api.github.com/users/mariosasko/following{/other_user}', 'gists_url': 'https://api.github.com/users/mariosasko/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/mariosasko/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/mariosasko/subscriptions', 'organizations_url': 'https://api.github.com/users/mariosasko/orgs', 'repos_url': 'https://api.github.com/users/mariosasko/repos', 'events_url': 'https://api.github.com/users/mariosasko/events{/privacy}', 'received_events_url': 'https://api.github.com/users/mariosasko/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-07-03T15:34:17Z', 'updated_at': '2023-07-03T15:34:17Z', 'author_association': 'CONTRIBUTOR', 'body': 'The metrics API in `datasets` is deprecated as of version 2.0, and `evaulate` is our new library for metrics. You can add a new metric to it by following [these steps](https://huggingface.co/docs/evaluate/creating_and_sharing).', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1618685937/reactions', 'total_count': 1, '+1': 1, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}]

[{'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1614599163', 'html_url': 'https://github.com/huggingface/datasets/pull/6000#issuecomment-1614599163', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/6000', 'id': 1614599163, 'node_id': 'IC_kwDODunzps5gPNP7', 'user': {'login': 'github-actions[bot]', 'id': 41898282, 'node_id': 'MDM6Qm90NDE4OTgyODI=', 'avatar_url': 'https://avatars.githubusercontent.com/in/15368?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/github-actions%5Bbot%5D', 'html_url': 'https://github.com/apps/github-actions', 'followers_url': 'https://api.github.com/users/github-actions%5Bbot%5D/followers', 'following_url': 'https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}', 'gists_url': 'https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/github-actions%5Bbot%5D/subscriptions', 'organizations_url': 'https://api.github.com/users/github-actions%5Bbot%5D/orgs', 'repos_url': 'https://api.github.com/users/github-actions%5Bbot%5D/repos', 'events_url': 'https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}', 'received_events_url': 'https://api.github.com/users/github-actions%5Bbot%5D/received_events', 'type': 'Bot', 'site_admin': False}, 'created_at': '2023-06-30T12:43:32Z', 'updated_at': '2023-06-30T12:43:32Z', 'author_association': 'NONE', 'body': '<details>\n<summary>Show benchmarks</summary>\n\nPyArrow==8.0.0\n\n<details>\n<summary>Show updated benchmarks!</summary>\n\n### Benchmark: benchmark_array_xd.json\n\n| metric | read_batch_formatted_as_numpy after write_array2d | read_batch_formatted_as_numpy after write_flattened_sequence | read_batch_formatted_as_numpy after write_nested_sequence | read_batch_unformated after write_array2d | read_batch_unformated after write_flattened_sequence | read_batch_unformated after write_nested_sequence | read_col_formatted_as_numpy after write_array2d | read_col_formatted_as_numpy after write_flattened_sequence | read_col_formatted_as_numpy after write_nested_sequence | read_col_unformated after write_array2d | read_col_unformated after write_flattened_sequence | read_col_unformated after write_nested_sequence | read_formatted_as_numpy after write_array2d | read_formatted_as_numpy after write_flattened_sequence | read_formatted_as_numpy after write_nested_sequence | read_unformated after write_array2d | read_unformated after write_flattened_sequence | read_unformated after write_nested_sequence | write_array2d | write_flattened_sequence | write_nested_sequence |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.006722 / 0.011353 (-0.004631) | 0.004425 / 0.011008 (-0.006583) | 0.100850 / 0.038508 (0.062341) | 0.040816 / 0.023109 (0.017707) | 0.348823 / 0.275898 (0.072925) | 0.446285 / 0.323480 (0.122805) | 0.005738 / 0.007986 (-0.002247) | 0.003517 / 0.004328 (-0.000811) | 0.078824 / 0.004250 (0.074574) | 0.064695 / 0.037052 (0.027643) | 0.389894 / 0.258489 (0.131405) | 0.416107 / 0.293841 (0.122266) | 0.028850 / 0.128546 (-0.099696) | 0.009011 / 0.075646 (-0.066635) | 0.323117 / 0.419271 (-0.096154) | 0.049162 / 0.043533 (0.005629) | 0.340144 / 0.255139 (0.085005) | 0.382072 / 0.283200 (0.098872) | 0.023160 / 0.141683 (-0.118523) | 1.549218 / 1.452155 (0.097063) | 1.581266 / 1.492716 (0.088550) |\n\n### Benchmark: benchmark_getitem\\_100B.json\n\n| metric | get_batch_of\\_1024\\_random_rows | get_batch_of\\_1024\\_rows | get_first_row | get_last_row |\n|--------|---|---|---|---|\n| new / old (diff) | 0.293360 / 0.018006 (0.275353) | 0.602189 / 0.000490 (0.601700) | 0.004608 / 0.000200 (0.004408) | 0.000082 / 0.000054 (0.000028) |\n\n### Benchmark: benchmark_indices_mapping.json\n\n| metric | select | shard | shuffle | sort | train_test_split |\n|--------|---|---|---|---|---|\n| new / old (diff) | 0.028144 / 0.037411 (-0.009267) | 0.107088 / 0.014526 (0.092562) | 0.112188 / 0.176557 (-0.064369) | 0.174669 / 0.737135 (-0.562466) | 0.116359 / 0.296338 (-0.179980) |\n\n### Benchmark: benchmark_iterating.json\n\n| metric | read 5000 | read 50000 | read_batch 50000 10 | read_batch 50000 100 | read_batch 50000 1000 | read_formatted numpy 5000 | read_formatted pandas 5000 | read_formatted tensorflow 5000 | read_formatted torch 5000 | read_formatted_batch numpy 5000 10 | read_formatted_batch numpy 5000 1000 | shuffled read 5000 | shuffled read 50000 | shuffled read_batch 50000 10 | shuffled read_batch 50000 100 | shuffled read_batch 50000 1000 | shuffled read_formatted numpy 5000 | shuffled read_formatted_batch numpy 5000 10 | shuffled read_formatted_batch numpy 5000 1000 |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.422911 / 0.215209 (0.207702) | 4.231524 / 2.077655 (2.153869) | 1.906711 / 1.504120 (0.402591) | 1.706841 / 1.541195 (0.165646) | 1.792066 / 1.468490 (0.323576) | 0.559221 / 4.584777 (-4.025556) | 3.434280 / 3.745712 (-0.311433) | 1.918714 / 5.269862 (-3.351148) | 1.073070 / 4.565676 (-3.492606) | 0.067891 / 0.424275 (-0.356384) | 0.011927 / 0.007607 (0.004320) | 0.530843 / 0.226044 (0.304799) | 5.309213 / 2.268929 (3.040285) | 2.439246 / 55.444624 (-53.005378) | 2.101245 / 6.876477 (-4.775231) | 2.177436 / 2.142072 (0.035363) | 0.672150 / 4.805227 (-4.133077) | 0.137571 / 6.500664 (-6.363093) | 0.068343 / 0.075469 (-0.007126) |\n\n### Benchmark: benchmark_map_filter.json\n\n| metric | filter | map fast-tokenizer batched | map identity | map identity batched | map no-op batched | map no-op batched numpy | map no-op batched pandas | map no-op batched pytorch | map no-op batched tensorflow |\n|--------|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 1.265262 / 1.841788 (-0.576525) | 14.988021 / 8.074308 (6.913713) | 13.611677 / 10.191392 (3.420285) | 0.171389 / 0.680424 (-0.509035) | 0.017681 / 0.534201 (-0.516520) | 0.377542 / 0.579283 (-0.201741) | 0.399475 / 0.434364 (-0.034889) | 0.469553 / 0.540337 (-0.070785) | 0.561888 / 1.386936 (-0.825048) |\n\n</details>\nPyArrow==latest\n\n<details>\n<summary>Show updated benchmarks!</summary>\n\n### Benchmark: benchmark_array_xd.json\n\n| metric | read_batch_formatted_as_numpy after write_array2d | read_batch_formatted_as_numpy after write_flattened_sequence | read_batch_formatted_as_numpy after write_nested_sequence | read_batch_unformated after write_array2d | read_batch_unformated after write_flattened_sequence | read_batch_unformated after write_nested_sequence | read_col_formatted_as_numpy after write_array2d | read_col_formatted_as_numpy after write_flattened_sequence | read_col_formatted_as_numpy after write_nested_sequence | read_col_unformated after write_array2d | read_col_unformated after write_flattened_sequence | read_col_unformated after write_nested_sequence | read_formatted_as_numpy after write_array2d | read_formatted_as_numpy after write_flattened_sequence | read_formatted_as_numpy after write_nested_sequence | read_unformated after write_array2d | read_unformated after write_flattened_sequence | read_unformated after write_nested_sequence | write_array2d | write_flattened_sequence | write_nested_sequence |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.006782 / 0.011353 (-0.004571) | 0.004412 / 0.011008 (-0.006597) | 0.078594 / 0.038508 (0.040086) | 0.039930 / 0.023109 (0.016820) | 0.371879 / 0.275898 (0.095981) | 0.444910 / 0.323480 (0.121430) | 0.005707 / 0.007986 (-0.002279) | 0.003901 / 0.004328 (-0.000427) | 0.080125 / 0.004250 (0.075875) | 0.063977 / 0.037052 (0.026925) | 0.382781 / 0.258489 (0.124292) | 0.441791 / 0.293841 (0.147950) | 0.030428 / 0.128546 (-0.098118) | 0.009008 / 0.075646 (-0.066638) | 0.084447 / 0.419271 (-0.334824) | 0.044432 / 0.043533 (0.000899) | 0.365686 / 0.255139 (0.110547) | 0.394312 / 0.283200 (0.111113) | 0.024508 / 0.141683 (-0.117175) | 1.577020 / 1.452155 (0.124865) | 1.630259 / 1.492716 (0.137543) |\n\n### Benchmark: benchmark_getitem\\_100B.json\n\n| metric | get_batch_of\\_1024\\_random_rows | get_batch_of\\_1024\\_rows | get_first_row | get_last_row |\n|--------|---|---|---|---|\n| new / old (diff) | 0.307960 / 0.018006 (0.289953) | 0.591473 / 0.000490 (0.590983) | 0.008098 / 0.000200 (0.007898) | 0.000110 / 0.000054 (0.000056) |\n\n### Benchmark: benchmark_indices_mapping.json\n\n| metric | select | shard | shuffle | sort | train_test_split |\n|--------|---|---|---|---|---|\n| new / old (diff) | 0.029567 / 0.037411 (-0.007845) | 0.112773 / 0.014526 (0.098247) | 0.117362 / 0.176557 (-0.059194) | 0.174293 / 0.737135 (-0.562843) | 0.123156 / 0.296338 (-0.173182) |\n\n### Benchmark: benchmark_iterating.json\n\n| metric | read 5000 | read 50000 | read_batch 50000 10 | read_batch 50000 100 | read_batch 50000 1000 | read_formatted numpy 5000 | read_formatted pandas 5000 | read_formatted tensorflow 5000 | read_formatted torch 5000 | read_formatted_batch numpy 5000 10 | read_formatted_batch numpy 5000 1000 | shuffled read 5000 | shuffled read 50000 | shuffled read_batch 50000 10 | shuffled read_batch 50000 100 | shuffled read_batch 50000 1000 | shuffled read_formatted numpy 5000 | shuffled read_formatted_batch numpy 5000 10 | shuffled read_formatted_batch numpy 5000 1000 |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.457475 / 0.215209 (0.242266) | 4.599067 / 2.077655 (2.521412) | 2.262638 / 1.504120 (0.758518) | 2.124943 / 1.541195 (0.583748) | 2.339912 / 1.468490 (0.871422) | 0.566264 / 4.584777 (-4.018513) | 3.489261 / 3.745712 (-0.256451) | 1.925151 / 5.269862 (-3.344711) | 1.099389 / 4.565676 (-3.466287) | 0.068232 / 0.424275 (-0.356043) | 0.011660 / 0.007607 (0.004052) | 0.571227 / 0.226044 (0.345183) | 5.702059 / 2.268929 (3.433130) | 2.837701 / 55.444624 (-52.606924) | 2.605468 / 6.876477 (-4.271008) | 2.818396 / 2.142072 (0.676323) | 0.681856 / 4.805227 (-4.123371) | 0.141401 / 6.500664 (-6.359263) | 0.069728 / 0.075469 (-0.005741) |\n\n### Benchmark: benchmark_map_filter.json\n\n| metric | filter | map fast-tokenizer batched | map identity | map identity batched | map no-op batched | map no-op batched numpy | map no-op batched pandas | map no-op batched pytorch | map no-op batched tensorflow |\n|--------|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 1.354935 / 1.841788 (-0.486853) | 15.437404 / 8.074308 (7.363095) | 15.415193 / 10.191392 (5.223801) | 0.153459 / 0.680424 (-0.526964) | 0.017190 / 0.534201 (-0.517011) | 0.367256 / 0.579283 (-0.212027) | 0.392709 / 0.434364 (-0.041655) | 0.426125 / 0.540337 (-0.114213) | 0.522612 / 1.386936 (-0.864324) |\n\n</details>\n</details>\n\n![](https://cml.dev/watermark.png#25ac13d8ab23e7d99252ce083a45e8333b6bbcdc "CML watermark")\n', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1614599163/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1614609480', 'html_url': 'https://github.com/huggingface/datasets/pull/6000#issuecomment-1614609480', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/6000', 'id': 1614609480, 'node_id': 'IC_kwDODunzps5gPPxI', 'user': {'login': 'HuggingFaceDocBuilderDev', 'id': 99929124, 'node_id': 'U_kgDOBfTMJA', 'avatar_url': 'https://avatars.githubusercontent.com/u/99929124?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/HuggingFaceDocBuilderDev', 'html_url': 'https://github.com/HuggingFaceDocBuilderDev', 'followers_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/followers', 'following_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/following{/other_user}', 'gists_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/subscriptions', 'organizations_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/orgs', 'repos_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/repos', 'events_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/events{/privacy}', 'received_events_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-30T12:52:56Z', 'updated_at': '2023-06-30T13:08:54Z', 'author_association': 'NONE', 'body': '_The documentation is not available anymore as the PR was closed or merged._', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1614609480/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1614614182', 'html_url': 'https://github.com/huggingface/datasets/pull/6000#issuecomment-1614614182', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/6000', 'id': 1614614182, 'node_id': 'IC_kwDODunzps5gPQ6m', 'user': {'login': 'github-actions[bot]', 'id': 41898282, 'node_id': 'MDM6Qm90NDE4OTgyODI=', 'avatar_url': 'https://avatars.githubusercontent.com/in/15368?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/github-actions%5Bbot%5D', 'html_url': 'https://github.com/apps/github-actions', 'followers_url': 'https://api.github.com/users/github-actions%5Bbot%5D/followers', 'following_url': 'https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}', 'gists_url': 'https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/github-actions%5Bbot%5D/subscriptions', 'organizations_url': 'https://api.github.com/users/github-actions%5Bbot%5D/orgs', 'repos_url': 'https://api.github.com/users/github-actions%5Bbot%5D/repos', 'events_url': 'https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}', 'received_events_url': 'https://api.github.com/users/github-actions%5Bbot%5D/received_events', 'type': 'Bot', 'site_admin': False}, 'created_at': '2023-06-30T12:57:00Z', 'updated_at': '2023-06-30T12:57:00Z', 'author_association': 'NONE', 'body': '<details>\n<summary>Show benchmarks</summary>\n\nPyArrow==8.0.0\n\n<details>\n<summary>Show updated benchmarks!</summary>\n\n### Benchmark: benchmark_array_xd.json\n\n| metric | read_batch_formatted_as_numpy after write_array2d | read_batch_formatted_as_numpy after write_flattened_sequence | read_batch_formatted_as_numpy after write_nested_sequence | read_batch_unformated after write_array2d | read_batch_unformated after write_flattened_sequence | read_batch_unformated after write_nested_sequence | read_col_formatted_as_numpy after write_array2d | read_col_formatted_as_numpy after write_flattened_sequence | read_col_formatted_as_numpy after write_nested_sequence | read_col_unformated after write_array2d | read_col_unformated after write_flattened_sequence | read_col_unformated after write_nested_sequence | read_formatted_as_numpy after write_array2d | read_formatted_as_numpy after write_flattened_sequence | read_formatted_as_numpy after write_nested_sequence | read_unformated after write_array2d | read_unformated after write_flattened_sequence | read_unformated after write_nested_sequence | write_array2d | write_flattened_sequence | write_nested_sequence |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.009183 / 0.011353 (-0.002170) | 0.005232 / 0.011008 (-0.005776) | 0.120349 / 0.038508 (0.081841) | 0.044715 / 0.023109 (0.021606) | 0.361519 / 0.275898 (0.085621) | 0.463702 / 0.323480 (0.140223) | 0.005842 / 0.007986 (-0.002144) | 0.004041 / 0.004328 (-0.000288) | 0.096953 / 0.004250 (0.092703) | 0.070593 / 0.037052 (0.033540) | 0.409790 / 0.258489 (0.151301) | 0.477452 / 0.293841 (0.183611) | 0.045827 / 0.128546 (-0.082719) | 0.014038 / 0.075646 (-0.061608) | 0.421317 / 0.419271 (0.002045) | 0.065276 / 0.043533 (0.021743) | 0.360074 / 0.255139 (0.104935) | 0.409147 / 0.283200 (0.125947) | 0.032444 / 0.141683 (-0.109238) | 1.739257 / 1.452155 (0.287102) | 1.831408 / 1.492716 (0.338692) |\n\n### Benchmark: benchmark_getitem\\_100B.json\n\n| metric | get_batch_of\\_1024\\_random_rows | get_batch_of\\_1024\\_rows | get_first_row | get_last_row |\n|--------|---|---|---|---|\n| new / old (diff) | 0.274852 / 0.018006 (0.256846) | 0.596320 / 0.000490 (0.595830) | 0.006399 / 0.000200 (0.006199) | 0.000133 / 0.000054 (0.000079) |\n\n### Benchmark: benchmark_indices_mapping.json\n\n| metric | select | shard | shuffle | sort | train_test_split |\n|--------|---|---|---|---|---|\n| new / old (diff) | 0.031400 / 0.037411 (-0.006012) | 0.127052 / 0.014526 (0.112526) | 0.134269 / 0.176557 (-0.042288) | 0.225998 / 0.737135 (-0.511137) | 0.150019 / 0.296338 (-0.146319) |\n\n### Benchmark: benchmark_iterating.json\n\n| metric | read 5000 | read 50000 | read_batch 50000 10 | read_batch 50000 100 | read_batch 50000 1000 | read_formatted numpy 5000 | read_formatted pandas 5000 | read_formatted tensorflow 5000 | read_formatted torch 5000 | read_formatted_batch numpy 5000 10 | read_formatted_batch numpy 5000 1000 | shuffled read 5000 | shuffled read 50000 | shuffled read_batch 50000 10 | shuffled read_batch 50000 100 | shuffled read_batch 50000 1000 | shuffled read_formatted numpy 5000 | shuffled read_formatted_batch numpy 5000 10 | shuffled read_formatted_batch numpy 5000 1000 |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.654202 / 0.215209 (0.438993) | 6.216735 / 2.077655 (4.139081) | 2.440214 / 1.504120 (0.936094) | 2.150575 / 1.541195 (0.609380) | 2.124790 / 1.468490 (0.656300) | 0.923514 / 4.584777 (-3.661263) | 5.556924 / 3.745712 (1.811212) | 2.843886 / 5.269862 (-2.425975) | 1.834232 / 4.565676 (-2.731444) | 0.111735 / 0.424275 (-0.312540) | 0.014823 / 0.007607 (0.007216) | 0.820503 / 0.226044 (0.594459) | 7.887737 / 2.268929 (5.618809) | 3.120307 / 55.444624 (-52.324317) | 2.405856 / 6.876477 (-4.470621) | 2.411239 / 2.142072 (0.269167) | 1.071283 / 4.805227 (-3.733944) | 0.227738 / 6.500664 (-6.272926) | 0.073516 / 0.075469 (-0.001953) |\n\n### Benchmark: benchmark_map_filter.json\n\n| metric | filter | map fast-tokenizer batched | map identity | map identity batched | map no-op batched | map no-op batched numpy | map no-op batched pandas | map no-op batched pytorch | map no-op batched tensorflow |\n|--------|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 1.531806 / 1.841788 (-0.309982) | 18.547661 / 8.074308 (10.473353) | 21.083922 / 10.191392 (10.892530) | 0.241706 / 0.680424 (-0.438718) | 0.034169 / 0.534201 (-0.500032) | 0.497514 / 0.579283 (-0.081769) | 0.599801 / 0.434364 (0.165437) | 0.576465 / 0.540337 (0.036127) | 0.673509 / 1.386936 (-0.713427) |\n\n</details>\nPyArrow==latest\n\n<details>\n<summary>Show updated benchmarks!</summary>\n\n### Benchmark: benchmark_array_xd.json\n\n| metric | read_batch_formatted_as_numpy after write_array2d | read_batch_formatted_as_numpy after write_flattened_sequence | read_batch_formatted_as_numpy after write_nested_sequence | read_batch_unformated after write_array2d | read_batch_unformated after write_flattened_sequence | read_batch_unformated after write_nested_sequence | read_col_formatted_as_numpy after write_array2d | read_col_formatted_as_numpy after write_flattened_sequence | read_col_formatted_as_numpy after write_nested

[{'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1614166461', 'html_url': 'https://github.com/huggingface/datasets/issues/5999#issuecomment-1614166461', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5999', 'id': 1614166461, 'node_id': 'IC_kwDODunzps5gNjm9', 'user': {'login': 'albertvillanova', 'id': 8515462, 'node_id': 'MDQ6VXNlcjg1MTU0NjI=', 'avatar_url': 'https://avatars.githubusercontent.com/u/8515462?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/albertvillanova', 'html_url': 'https://github.com/albertvillanova', 'followers_url': 'https://api.github.com/users/albertvillanova/followers', 'following_url': 'https://api.github.com/users/albertvillanova/following{/other_user}', 'gists_url': 'https://api.github.com/users/albertvillanova/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/albertvillanova/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/albertvillanova/subscriptions', 'organizations_url': 'https://api.github.com/users/albertvillanova/orgs', 'repos_url': 'https://api.github.com/users/albertvillanova/repos', 'events_url': 'https://api.github.com/users/albertvillanova/events{/privacy}', 'received_events_url': 'https://api.github.com/users/albertvillanova/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-30T05:57:22Z', 'updated_at': '2023-06-30T05:57:22Z', 'author_association': 'MEMBER', 'body': "Thanks for reporting, @Praful932.\r\n\r\nLet's continue the conversation on the Hub: https://huggingface.co/datasets/xglue/discussions/5", 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1614166461/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}]
[{'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1614725726', 'html_url': 'https://github.com/huggingface/datasets/issues/5998#issuecomment-1614725726', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5998', 'id': 1614725726, 'node_id': 'IC_kwDODunzps5gPsJe', 'user': {'login': 'albertvillanova', 'id': 8515462, 'node_id': 'MDQ6VXNlcjg1MTU0NjI=', 'avatar_url': 'https://avatars.githubusercontent.com/u/8515462?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/albertvillanova', 'html_url': 'https://github.com/albertvillanova', 'followers_url': 'https://api.github.com/users/albertvillanova/followers', 'following_url': 'https://api.github.com/users/albertvillanova/following{/other_user}', 'gists_url': 'https://api.github.com/users/albertvillanova/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/albertvillanova/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/albertvillanova/subscriptions', 'organizations_url': 'https://api.github.com/users/albertvillanova/orgs', 'repos_url': 'https://api.github.com/users/albertvillanova/repos', 'events_url': 'https://api.github.com/users/albertvillanova/events{/privacy}', 'received_events_url': 'https://api.github.com/users/albertvillanova/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-30T14:21:03Z', 'updated_at': '2023-06-30T14:21:03Z', 'author_association': 'MEMBER', 'body': 'Thanks for reporting, @wangyuxinwhy. ', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1614725726/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}]
[{'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1613875170', 'html_url': 'https://github.com/huggingface/datasets/issues/5997#issuecomment-1613875170', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5997', 'id': 1613875170, 'node_id': 'IC_kwDODunzps5gMcfi', 'user': {'login': 'siddhsql', 'id': 127623723, 'node_id': 'U_kgDOB5tiKw', 'avatar_url': 'https://avatars.githubusercontent.com/u/127623723?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/siddhsql', 'html_url': 'https://github.com/siddhsql', 'followers_url': 'https://api.github.com/users/siddhsql/followers', 'following_url': 'https://api.github.com/users/siddhsql/following{/other_user}', 'gists_url': 'https://api.github.com/users/siddhsql/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/siddhsql/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/siddhsql/subscriptions', 'organizations_url': 'https://api.github.com/users/siddhsql/orgs', 'repos_url': 'https://api.github.com/users/siddhsql/repos', 'events_url': 'https://api.github.com/users/siddhsql/events{/privacy}', 'received_events_url': 'https://api.github.com/users/siddhsql/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-29T22:22:19Z', 'updated_at': '2023-06-29T22:22:19Z', 'author_association': 'NONE', 'body': 'I just noticed the [docs](https://github.com/huggingface/datasets/blob/main/src/datasets/arrow_dataset.py#L2881C11-L2881C200) say:\r\n\r\n>If batched is `True` and `batch_size` is `n > 1`, then the function takes a batch of `n` examples as input and can return a batch with `n` examples, or with an arbitrary number of examples.\r\n\r\nso maybe this is a bug then.', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1613875170/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1618952519', 'html_url': 'https://github.com/huggingface/datasets/issues/5997#issuecomment-1618952519', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5997', 'id': 1618952519, 'node_id': 'IC_kwDODunzps5gf0FH', 'user': {'login': 'mariosasko', 'id': 47462742, 'node_id': 'MDQ6VXNlcjQ3NDYyNzQy', 'avatar_url': 'https://avatars.githubusercontent.com/u/47462742?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/mariosasko', 'html_url': 'https://github.com/mariosasko', 'followers_url': 'https://api.github.com/users/mariosasko/followers', 'following_url': 'https://api.github.com/users/mariosasko/following{/other_user}', 'gists_url': 'https://api.github.com/users/mariosasko/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/mariosasko/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/mariosasko/subscriptions', 'organizations_url': 'https://api.github.com/users/mariosasko/orgs', 'repos_url': 'https://api.github.com/users/mariosasko/repos', 'events_url': 'https://api.github.com/users/mariosasko/events{/privacy}', 'received_events_url': 'https://api.github.com/users/mariosasko/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-07-03T17:58:51Z', 'updated_at': '2023-07-03T17:58:51Z', 'author_association': 'CONTRIBUTOR', 'body': 'All the values in a batch must be of the same length. So one solution is dropping all the input columns:\r\n```python\r\ndata = data.map(lambda samples: tokenizer(samples["text"], max_length=tokenizer.model_max_length, truncation=True, stride=4, return_overflowing_tokens=True), batched=True, remove_columns=data.column_names)\r\n```\r\n\r\nAnother is padding/transforming the input columns to the tokenizer output\'s length (447). ', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1618952519/reactions', 'total_count': 1, '+1': 1, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}]

[{'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1609607635', 'html_url': 'https://github.com/huggingface/datasets/pull/5995#issuecomment-1609607635', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5995', 'id': 1609607635, 'node_id': 'IC_kwDODunzps5f8KnT', 'user': {'login': 'HuggingFaceDocBuilderDev', 'id': 99929124, 'node_id': 'U_kgDOBfTMJA', 'avatar_url': 'https://avatars.githubusercontent.com/u/99929124?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/HuggingFaceDocBuilderDev', 'html_url': 'https://github.com/HuggingFaceDocBuilderDev', 'followers_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/followers', 'following_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/following{/other_user}', 'gists_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/subscriptions', 'organizations_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/orgs', 'repos_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/repos', 'events_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/events{/privacy}', 'received_events_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-27T14:20:24Z', 'updated_at': '2023-06-28T13:47:08Z', 'author_association': 'NONE', 'body': '_The documentation is not available anymore as the PR was closed or merged._', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1609607635/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1609610766', 'html_url': 'https://github.com/huggingface/datasets/pull/5995#issuecomment-1609610766', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5995', 'id': 1609610766, 'node_id': 'IC_kwDODunzps5f8LYO', 'user': {'login': 'github-actions[bot]', 'id': 41898282, 'node_id': 'MDM6Qm90NDE4OTgyODI=', 'avatar_url': 'https://avatars.githubusercontent.com/in/15368?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/github-actions%5Bbot%5D', 'html_url': 'https://github.com/apps/github-actions', 'followers_url': 'https://api.github.com/users/github-actions%5Bbot%5D/followers', 'following_url': 'https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}', 'gists_url': 'https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/github-actions%5Bbot%5D/subscriptions', 'organizations_url': 'https://api.github.com/users/github-actions%5Bbot%5D/orgs', 'repos_url': 'https://api.github.com/users/github-actions%5Bbot%5D/repos', 'events_url': 'https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}', 'received_events_url': 'https://api.github.com/users/github-actions%5Bbot%5D/received_events', 'type': 'Bot', 'site_admin': False}, 'created_at': '2023-06-27T14:21:48Z', 'updated_at': '2023-06-27T14:21:48Z', 'author_association': 'NONE', 'body': '<details>\n<summary>Show benchmarks</summary>\n\nPyArrow==8.0.0\n\n<details>\n<summary>Show updated benchmarks!</summary>\n\n### Benchmark: benchmark_array_xd.json\n\n| metric | read_batch_formatted_as_numpy after write_array2d | read_batch_formatted_as_numpy after write_flattened_sequence | read_batch_formatted_as_numpy after write_nested_sequence | read_batch_unformated after write_array2d | read_batch_unformated after write_flattened_sequence | read_batch_unformated after write_nested_sequence | read_col_formatted_as_numpy after write_array2d | read_col_formatted_as_numpy after write_flattened_sequence | read_col_formatted_as_numpy after write_nested_sequence | read_col_unformated after write_array2d | read_col_unformated after write_flattened_sequence | read_col_unformated after write_nested_sequence | read_formatted_as_numpy after write_array2d | read_formatted_as_numpy after write_flattened_sequence | read_formatted_as_numpy after write_nested_sequence | read_unformated after write_array2d | read_unformated after write_flattened_sequence | read_unformated after write_nested_sequence | write_array2d | write_flattened_sequence | write_nested_sequence |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.009725 / 0.011353 (-0.001628) | 0.006014 / 0.011008 (-0.004994) | 0.136039 / 0.038508 (0.097531) | 0.049685 / 0.023109 (0.026576) | 0.492967 / 0.275898 (0.217068) | 0.553775 / 0.323480 (0.230295) | 0.007421 / 0.007986 (-0.000564) | 0.004686 / 0.004328 (0.000357) | 0.106639 / 0.004250 (0.102389) | 0.073483 / 0.037052 (0.036431) | 0.507194 / 0.258489 (0.248705) | 0.535760 / 0.293841 (0.241919) | 0.049666 / 0.128546 (-0.078880) | 0.014139 / 0.075646 (-0.061507) | 0.435459 / 0.419271 (0.016188) | 0.076026 / 0.043533 (0.032493) | 0.454542 / 0.255139 (0.199403) | 0.512724 / 0.283200 (0.229524) | 0.034969 / 0.141683 (-0.106713) | 1.881048 / 1.452155 (0.428893) | 1.959915 / 1.492716 (0.467199) |\n\n### Benchmark: benchmark_getitem\\_100B.json\n\n| metric | get_batch_of\\_1024\\_random_rows | get_batch_of\\_1024\\_rows | get_first_row | get_last_row |\n|--------|---|---|---|---|\n| new / old (diff) | 0.265322 / 0.018006 (0.247316) | 0.573963 / 0.000490 (0.573474) | 0.017493 / 0.000200 (0.017293) | 0.000637 / 0.000054 (0.000582) |\n\n### Benchmark: benchmark_indices_mapping.json\n\n| metric | select | shard | shuffle | sort | train_test_split |\n|--------|---|---|---|---|---|\n| new / old (diff) | 0.028712 / 0.037411 (-0.008699) | 0.149554 / 0.014526 (0.135029) | 0.130013 / 0.176557 (-0.046544) | 0.203408 / 0.737135 (-0.533727) | 0.144778 / 0.296338 (-0.151561) |\n\n### Benchmark: benchmark_iterating.json\n\n| metric | read 5000 | read 50000 | read_batch 50000 10 | read_batch 50000 100 | read_batch 50000 1000 | read_formatted numpy 5000 | read_formatted pandas 5000 | read_formatted tensorflow 5000 | read_formatted torch 5000 | read_formatted_batch numpy 5000 10 | read_formatted_batch numpy 5000 1000 | shuffled read 5000 | shuffled read 50000 | shuffled read_batch 50000 10 | shuffled read_batch 50000 100 | shuffled read_batch 50000 1000 | shuffled read_formatted numpy 5000 | shuffled read_formatted_batch numpy 5000 10 | shuffled read_formatted_batch numpy 5000 1000 |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.664198 / 0.215209 (0.448989) | 6.418054 / 2.077655 (4.340399) | 2.602338 / 1.504120 (1.098219) | 2.212992 / 1.541195 (0.671797) | 2.214309 / 1.468490 (0.745819) | 0.914772 / 4.584777 (-3.670005) | 5.824831 / 3.745712 (2.079119) | 2.865381 / 5.269862 (-2.404481) | 1.906020 / 4.565676 (-2.659657) | 0.106947 / 0.424275 (-0.317328) | 0.013467 / 0.007607 (0.005860) | 0.834556 / 0.226044 (0.608512) | 8.237078 / 2.268929 (5.968150) | 3.380919 / 55.444624 (-52.063705) | 2.656713 / 6.876477 (-4.219764) | 2.834941 / 2.142072 (0.692869) | 1.151241 / 4.805227 (-3.653986) | 0.220860 / 6.500664 (-6.279804) | 0.080781 / 0.075469 (0.005312) |\n\n### Benchmark: benchmark_map_filter.json\n\n| metric | filter | map fast-tokenizer batched | map identity | map identity batched | map no-op batched | map no-op batched numpy | map no-op batched pandas | map no-op batched pytorch | map no-op batched tensorflow |\n|--------|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 1.655128 / 1.841788 (-0.186660) | 18.696108 / 8.074308 (10.621800) | 22.882108 / 10.191392 (12.690716) | 0.236041 / 0.680424 (-0.444383) | 0.031073 / 0.534201 (-0.503128) | 0.525263 / 0.579283 (-0.054021) | 0.632933 / 0.434364 (0.198569) | 0.707228 / 0.540337 (0.166890) | 0.753508 / 1.386936 (-0.633428) |\n\n</details>\nPyArrow==latest\n\n<details>\n<summary>Show updated benchmarks!</summary>\n\n### Benchmark: benchmark_array_xd.json\n\n| metric | read_batch_formatted_as_numpy after write_array2d | read_batch_formatted_as_numpy after write_flattened_sequence | read_batch_formatted_as_numpy after write_nested_sequence | read_batch_unformated after write_array2d | read_batch_unformated after write_flattened_sequence | read_batch_unformated after write_nested_sequence | read_col_formatted_as_numpy after write_array2d | read_col_formatted_as_numpy after write_flattened_sequence | read_col_formatted_as_numpy after write_nested_sequence | read_col_unformated after write_array2d | read_col_unformated after write_flattened_sequence | read_col_unformated after write_nested_sequence | read_formatted_as_numpy after write_array2d | read_formatted_as_numpy after write_flattened_sequence | read_formatted_as_numpy after write_nested_sequence | read_unformated after write_array2d | read_unformated after write_flattened_sequence | read_unformated after write_nested_sequence | write_array2d | write_flattened_sequence | write_nested_sequence |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.009875 / 0.011353 (-0.001478) | 0.005135 / 0.011008 (-0.005873) | 0.101307 / 0.038508 (0.062799) | 0.044895 / 0.023109 (0.021786) | 0.497824 / 0.275898 (0.221926) | 0.573098 / 0.323480 (0.249618) | 0.006669 / 0.007986 (-0.001317) | 0.004289 / 0.004328 (-0.000039) | 0.105824 / 0.004250 (0.101573) | 0.061002 / 0.037052 (0.023950) | 0.510127 / 0.258489 (0.251638) | 0.581387 / 0.293841 (0.287546) | 0.052843 / 0.128546 (-0.075703) | 0.015506 / 0.075646 (-0.060140) | 0.116057 / 0.419271 (-0.303215) | 0.063444 / 0.043533 (0.019912) | 0.479366 / 0.255139 (0.224227) | 0.518419 / 0.283200 (0.235220) | 0.034876 / 0.141683 (-0.106806) | 2.018446 / 1.452155 (0.566292) | 1.960755 / 1.492716 (0.468039) |\n\n### Benchmark: benchmark_getitem\\_100B.json\n\n| metric | get_batch_of\\_1024\\_random_rows | get_batch_of\\_1024\\_rows | get_first_row | get_last_row |\n|--------|---|---|---|---|\n| new / old (diff) | 0.269077 / 0.018006 (0.251070) | 0.606059 / 0.000490 (0.605569) | 0.000488 / 0.000200 (0.000288) | 0.000093 / 0.000054 (0.000038) |\n\n### Benchmark: benchmark_indices_mapping.json\n\n| metric | select | shard | shuffle | sort | train_test_split |\n|--------|---|---|---|---|---|\n| new / old (diff) | 0.032465 / 0.037411 (-0.004946) | 0.136517 / 0.014526 (0.121991) | 0.147740 / 0.176557 (-0.028816) | 0.193802 / 0.737135 (-0.543334) | 0.151876 / 0.296338 (-0.144462) |\n\n### Benchmark: benchmark_iterating.json\n\n| metric | read 5000 | read 50000 | read_batch 50000 10 | read_batch 50000 100 | read_batch 50000 1000 | read_formatted numpy 5000 | read_formatted pandas 5000 | read_formatted tensorflow 5000 | read_formatted torch 5000 | read_formatted_batch numpy 5000 10 | read_formatted_batch numpy 5000 1000 | shuffled read 5000 | shuffled read 50000 | shuffled read_batch 50000 10 | shuffled read_batch 50000 100 | shuffled read_batch 50000 1000 | shuffled read_formatted numpy 5000 | shuffled read_formatted_batch numpy 5000 10 | shuffled read_formatted_batch numpy 5000 1000 |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.709866 / 0.215209 (0.494657) | 6.848193 / 2.077655 (4.770538) | 3.310853 / 1.504120 (1.806733) | 2.940813 / 1.541195 (1.399619) | 2.934934 / 1.468490 (1.466444) | 0.927104 / 4.584777 (-3.657673) | 5.921607 / 3.745712 (2.175895) | 4.926558 / 5.269862 (-0.343303) | 2.853269 / 4.565676 (-1.712407) | 0.120278 / 0.424275 (-0.303998) | 0.015468 / 0.007607 (0.007861) | 0.820509 / 0.226044 (0.594464) | 8.263136 / 2.268929 (5.994208) | 3.780214 / 55.444624 (-51.664410) | 3.108482 / 6.876477 (-3.767995) | 3.101544 / 2.142072 (0.959471) | 1.165539 / 4.805227 (-3.639688) | 0.229215 / 6.500664 (-6.271449) | 0.079862 / 0.075469 (0.004393) |\n\n### Benchmark: benchmark_map_filter.json\n\n| metric | filter | map fast-tokenizer batched | map identity | map identity batched | map no-op batched | map no-op batched numpy | map no-op batched pandas | map no-op batched pytorch | map no-op batched tensorflow |\n|--------|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 1.775071 / 1.841788 (-0.066717) | 19.327621 / 8.074308 (11.253313) | 23.057537 / 10.191392 (12.866145) | 0.250649 / 0.680424 (-0.429775) | 0.029767 / 0.534201 (-0.504434) | 0.554774 / 0.579283 (-0.024509) | 0.651919 / 0.434364 (0.217555) | 0.651641 / 0.540337 (0.111304) | 0.762386 / 1.386936 (-0.624550) |\n\n</details>\n</details>\n\n![](https://cml.dev/watermark.png#fdc3ce7060366f480621e8640903c9ab476164e7 "CML watermark")\n', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1609610766/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1609689479', 'html_url': 'https://github.com/huggingface/datasets/pull/5995#issuecomment-1609689479', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5995', 'id': 1609689479, 'node_id': 'IC_kwDODunzps5f8emH', 'user': {'login': 'github-actions[bot]', 'id': 41898282, 'node_id': 'MDM6Qm90NDE4OTgyODI=', 'avatar_url': 'https://avatars.githubusercontent.com/in/15368?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/github-actions%5Bbot%5D', 'html_url': 'https://github.com/apps/github-actions', 'followers_url': 'https://api.github.com/users/github-actions%5Bbot%5D/followers', 'following_url': 'https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}', 'gists_url': 'https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/github-actions%5Bbot%5D/subscriptions', 'organizations_url': 'https://api.github.com/users/github-actions%5Bbot%5D/orgs', 'repos_url': 'https://api.github.com/users/github-actions%5Bbot%5D/repos', 'events_url': 'https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}', 'received_events_url': 'https://api.github.com/users/github-actions%5Bbot%5D/received_events', 'type': 'Bot', 'site_admin': False}, 'created_at': '2023-06-27T15:02:38Z', 'updated_at': '2023-06-27T15:02:38Z', 'author_association': 'NONE', 'body': '<details>\n<summary>Show benchmarks</summary>\n\nPyArrow==8.0.0\n\n<details>\n<summary>Show updated benchmarks!</summary>\n\n### Benchmark: benchmark_array_xd.json\n\n| metric | read_batch_formatted_as_numpy after write_array2d | read_batch_formatted_as_numpy after write_flattened_sequence | read_batch_formatted_as_numpy after write_nested_sequence | read_batch_unformated after write_array2d | read_batch_unformated after write_flattened_sequence | read_batch_unformated after write_nested_sequence | read_col_formatted_as_numpy after write_array2d | read_col_formatted_as_numpy after write_flattened_sequence | read_col_formatted_as_numpy after write_nested_sequence | read_col_unformated after write_array2d | read_col_unformated after write_flattened_sequence | read_col_unformated after write_nested_sequence | read_formatted_as_numpy after write_array2d | read_formatted_as_numpy after write_flattened_sequence | read_formatted_as_numpy after write_nested_sequence | read_unformated after write_array2d | read_unformated after write_flattened_sequence | read_unformated after write_nested_sequence | write_array2d | write_flattened_sequence | write_nested_sequence |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.005997 / 0.011353 (-0.005356) | 0.003892 / 0.011008 (-0.007116) | 0.098020 / 0.038508 (0.059512) | 0.042584 / 0.023109 (0.019475) | 0.317909 / 0.275898 (0.042011) | 0.395042 / 0.323480 (0.071563) | 0.005358 / 0.007986 (-0.002628) | 0.003266 / 0.004328 (-0.001062) | 0.076698 / 0.004250 (0.072447) | 0.062331 / 0.037052 (0.025279) | 0.334900 / 0.258489 (0.076411) | 0.379355 / 0.293841 (0.085514) | 0.030815 / 0.128546 (-0.097731) | 0.008596 / 0.075646 (-0.067050) | 0.327739 / 0.419271 (-0.091533) | 0.054061 / 0.043533 (0.010528) | 0.311044 / 0.255139 (0.055905) | 0.336705 / 0.283200 (0.053506) | 0.022785 / 0.141683 (-0.118898) | 1.516793 / 1.452155 (0.064639) | 1.590435 / 1.492716 (0.097719) |\n\n### Benchmark: benchmark_getitem\\_100B.json\n\n| metric | get_batch_of\\_1024\\_random_rows | get_batch_of\\_1024\\_rows | get_first_row | get_last_row |\n|--------|---|---|---|---|\n| new / old (diff) | 0.289157 / 0.018006 (0.271151) | 0.531074 / 0.000490 (0.530585) | 0.004672 / 0.000200 (0.004472) | 0.000095 / 0.000054 (0.000040) |\n\n### Benchmark: benchmark_indices_mapping.json\n\n| metric | select | shard | shuffle | sort | train_test_split |\n|--------|---|---|---|---|---|\n| new / old (diff) | 0.026173 / 0.037411 (-0.011238) | 0.105723 / 0.014526 (0.091197) | 0.118010 / 0.176557 (-0.058547) | 0.178062 / 0.737135 (-0.559073) | 0.120059 / 0.296338 (-0.176279) |\n\n### Benchmark: benchmark_iterating.json\n\n| metric | read 5000 | read 50000 | read_batch 50000 10 | read_batch 50000 100 | read_batch 50000 1000 | read_formatted numpy 5000 | read_formatted pandas 5000 | read_formatted tensorflow 5000 | read_formatted torch 5000 | read_formatted_batch numpy 5000 10 | read_formatted_batch numpy 5000 1000 | shuffled read 5000 | shuffled read 50000 | shuffled read_batch 50000 10 | shuffled read_batch 50000 100 | shuffled read_batch 50000 1000 | shuffled read_formatted numpy 5000 | shuffled read_formatted_batch numpy 5000 10 | shuffled read_formatted_batch numpy 5000 1000 |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.410870 / 0.215209 (0.195661) | 4.042183 / 2.077655 (1.964528) | 1.830059 / 1.504120 (0.325939) | 1.638996 / 1.541195 (0.097802) | 1.701368 / 1.468490 (0.232878) | 0.529915 / 4.584777 (-4.054861) | 3.693308 / 3.745712 (-0.052404) | 1.827875 / 5.269862 (-3.441986) | 1.063237 / 4.565676 (-3.502440) | 0.065368 / 0.424275 (-0.358907) | 0.010986 / 0.007607 (0.003379) | 0.509399 / 0.226044 (0.283354) | 5.092739 / 2.268929 (2.823810) | 2.293490 / 55.444624 (-53.151135) | 1.958742 / 6.876477 (-4.917735) | 2.024985 / 2.142072 (-0.117088) | 0.646978 / 4.805227 (-4.158249) | 0.138616 / 6.500664 (-6.362048) | 0.062101 / 0.075469 (-0.013368) |\n\n### Benchmark: benchmark_map_filter.json\n\n| metric | filter | map fast-tokenizer batched | map identity | map identity batched | map no-op batched | map no-op batched numpy | map no-op batched pandas | map no-op batched pytorch | map no-op batched tensorflow |\n|--------|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 1.202016 / 1.841788 (-0.639772) | 14.493204 / 8.074308 (6.418896) | 12.992160 / 10.191392 (2.800768) | 0.188922 / 0.680424 (-0.491502) | 0.017594 / 0.534201 (-0.516606) | 0.399917 / 0.579283 (-0.179367) | 0.429760 / 0.434364 (-0.004604) | 0.497906 / 0.540337 (-0.042431) | 0.608745 / 1.386936 (-0.778191) |\n\n</details>\nPyArrow==latest\n\n<details>\n<summary>Show updated benchmarks!</summary>\n\n### Benchmark: benchmark_array_xd.json\n\n| metric | read_batch_formatted_as_numpy after write_array2d | read_batch_formatted_as_numpy after write_flattened_sequence | read_batch_formatted_as_numpy after write_nested_sequence | read_batch_unformated after write_array2d | read_batch_unformated after write_flattened_sequence | read_batch_unformated after write_nested_sequence | read_col_formatted_as_numpy after write_array2d | read_col_formatted_as_numpy after write_flattened_sequence | read_col_formatted_as_numpy after write_nested_se

[{'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1609421011', 'html_url': 'https://github.com/huggingface/datasets/pull/5994#issuecomment-1609421011', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5994', 'id': 1609421011, 'node_id': 'IC_kwDODunzps5f7dDT', 'user': {'login': 'github-actions[bot]', 'id': 41898282, 'node_id': 'MDM6Qm90NDE4OTgyODI=', 'avatar_url': 'https://avatars.githubusercontent.com/in/15368?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/github-actions%5Bbot%5D', 'html_url': 'https://github.com/apps/github-actions', 'followers_url': 'https://api.github.com/users/github-actions%5Bbot%5D/followers', 'following_url': 'https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}', 'gists_url': 'https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/github-actions%5Bbot%5D/subscriptions', 'organizations_url': 'https://api.github.com/users/github-actions%5Bbot%5D/orgs', 'repos_url': 'https://api.github.com/users/github-actions%5Bbot%5D/repos', 'events_url': 'https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}', 'received_events_url': 'https://api.github.com/users/github-actions%5Bbot%5D/received_events', 'type': 'Bot', 'site_admin': False}, 'created_at': '2023-06-27T12:38:27Z', 'updated_at': '2023-06-27T12:38:27Z', 'author_association': 'NONE', 'body': '<details>\n<summary>Show benchmarks</summary>\n\nPyArrow==8.0.0\n\n<details>\n<summary>Show updated benchmarks!</summary>\n\n### Benchmark: benchmark_array_xd.json\n\n| metric | read_batch_formatted_as_numpy after write_array2d | read_batch_formatted_as_numpy after write_flattened_sequence | read_batch_formatted_as_numpy after write_nested_sequence | read_batch_unformated after write_array2d | read_batch_unformated after write_flattened_sequence | read_batch_unformated after write_nested_sequence | read_col_formatted_as_numpy after write_array2d | read_col_formatted_as_numpy after write_flattened_sequence | read_col_formatted_as_numpy after write_nested_sequence | read_col_unformated after write_array2d | read_col_unformated after write_flattened_sequence | read_col_unformated after write_nested_sequence | read_formatted_as_numpy after write_array2d | read_formatted_as_numpy after write_flattened_sequence | read_formatted_as_numpy after write_nested_sequence | read_unformated after write_array2d | read_unformated after write_flattened_sequence | read_unformated after write_nested_sequence | write_array2d | write_flattened_sequence | write_nested_sequence |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.005969 / 0.011353 (-0.005384) | 0.003687 / 0.011008 (-0.007321) | 0.100843 / 0.038508 (0.062335) | 0.036912 / 0.023109 (0.013803) | 0.312389 / 0.275898 (0.036491) | 0.370335 / 0.323480 (0.046855) | 0.003434 / 0.007986 (-0.004552) | 0.003710 / 0.004328 (-0.000619) | 0.076899 / 0.004250 (0.072648) | 0.053647 / 0.037052 (0.016594) | 0.324825 / 0.258489 (0.066336) | 0.367711 / 0.293841 (0.073870) | 0.028079 / 0.128546 (-0.100467) | 0.008326 / 0.075646 (-0.067320) | 0.312342 / 0.419271 (-0.106930) | 0.047423 / 0.043533 (0.003890) | 0.321063 / 0.255139 (0.065924) | 0.336508 / 0.283200 (0.053308) | 0.019973 / 0.141683 (-0.121710) | 1.529334 / 1.452155 (0.077179) | 1.573746 / 1.492716 (0.081030) |\n\n### Benchmark: benchmark_getitem\\_100B.json\n\n| metric | get_batch_of\\_1024\\_random_rows | get_batch_of\\_1024\\_rows | get_first_row | get_last_row |\n|--------|---|---|---|---|\n| new / old (diff) | 0.210849 / 0.018006 (0.192843) | 0.418798 / 0.000490 (0.418309) | 0.007347 / 0.000200 (0.007147) | 0.000070 / 0.000054 (0.000016) |\n\n### Benchmark: benchmark_indices_mapping.json\n\n| metric | select | shard | shuffle | sort | train_test_split |\n|--------|---|---|---|---|---|\n| new / old (diff) | 0.022718 / 0.037411 (-0.014694) | 0.098400 / 0.014526 (0.083874) | 0.106590 / 0.176557 (-0.069967) | 0.168460 / 0.737135 (-0.568675) | 0.108401 / 0.296338 (-0.187938) |\n\n### Benchmark: benchmark_iterating.json\n\n| metric | read 5000 | read 50000 | read_batch 50000 10 | read_batch 50000 100 | read_batch 50000 1000 | read_formatted numpy 5000 | read_formatted pandas 5000 | read_formatted tensorflow 5000 | read_formatted torch 5000 | read_formatted_batch numpy 5000 10 | read_formatted_batch numpy 5000 1000 | shuffled read 5000 | shuffled read 50000 | shuffled read_batch 50000 10 | shuffled read_batch 50000 100 | shuffled read_batch 50000 1000 | shuffled read_formatted numpy 5000 | shuffled read_formatted_batch numpy 5000 10 | shuffled read_formatted_batch numpy 5000 1000 |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.443066 / 0.215209 (0.227857) | 4.416658 / 2.077655 (2.339003) | 2.088844 / 1.504120 (0.584724) | 1.879564 / 1.541195 (0.338369) | 1.933815 / 1.468490 (0.465325) | 0.565085 / 4.584777 (-4.019692) | 3.412440 / 3.745712 (-0.333273) | 1.754686 / 5.269862 (-3.515175) | 1.024576 / 4.565676 (-3.541100) | 0.067909 / 0.424275 (-0.356366) | 0.011054 / 0.007607 (0.003447) | 0.534748 / 0.226044 (0.308703) | 5.351457 / 2.268929 (3.082529) | 2.517368 / 55.444624 (-52.927256) | 2.182762 / 6.876477 (-4.693715) | 2.238205 / 2.142072 (0.096133) | 0.672962 / 4.805227 (-4.132265) | 0.136098 / 6.500664 (-6.364566) | 0.066534 / 0.075469 (-0.008935) |\n\n### Benchmark: benchmark_map_filter.json\n\n| metric | filter | map fast-tokenizer batched | map identity | map identity batched | map no-op batched | map no-op batched numpy | map no-op batched pandas | map no-op batched pytorch | map no-op batched tensorflow |\n|--------|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 1.281241 / 1.841788 (-0.560547) | 13.872881 / 8.074308 (5.798573) | 13.161023 / 10.191392 (2.969631) | 0.130011 / 0.680424 (-0.550412) | 0.016759 / 0.534201 (-0.517442) | 0.359802 / 0.579283 (-0.219481) | 0.392577 / 0.434364 (-0.041787) | 0.427742 / 0.540337 (-0.112595) | 0.522241 / 1.386936 (-0.864695) |\n\n</details>\nPyArrow==latest\n\n<details>\n<summary>Show updated benchmarks!</summary>\n\n### Benchmark: benchmark_array_xd.json\n\n| metric | read_batch_formatted_as_numpy after write_array2d | read_batch_formatted_as_numpy after write_flattened_sequence | read_batch_formatted_as_numpy after write_nested_sequence | read_batch_unformated after write_array2d | read_batch_unformated after write_flattened_sequence | read_batch_unformated after write_nested_sequence | read_col_formatted_as_numpy after write_array2d | read_col_formatted_as_numpy after write_flattened_sequence | read_col_formatted_as_numpy after write_nested_sequence | read_col_unformated after write_array2d | read_col_unformated after write_flattened_sequence | read_col_unformated after write_nested_sequence | read_formatted_as_numpy after write_array2d | read_formatted_as_numpy after write_flattened_sequence | read_formatted_as_numpy after write_nested_sequence | read_unformated after write_array2d | read_unformated after write_flattened_sequence | read_unformated after write_nested_sequence | write_array2d | write_flattened_sequence | write_nested_sequence |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.005985 / 0.011353 (-0.005368) | 0.003705 / 0.011008 (-0.007304) | 0.077699 / 0.038508 (0.039191) | 0.035686 / 0.023109 (0.012577) | 0.420356 / 0.275898 (0.144458) | 0.476753 / 0.323480 (0.153273) | 0.003510 / 0.007986 (-0.004475) | 0.002807 / 0.004328 (-0.001521) | 0.077151 / 0.004250 (0.072901) | 0.046420 / 0.037052 (0.009368) | 0.391781 / 0.258489 (0.133292) | 0.461128 / 0.293841 (0.167287) | 0.027847 / 0.128546 (-0.100699) | 0.008322 / 0.075646 (-0.067324) | 0.082768 / 0.419271 (-0.336503) | 0.042629 / 0.043533 (-0.000904) | 0.405745 / 0.255139 (0.150606) | 0.430797 / 0.283200 (0.147598) | 0.019832 / 0.141683 (-0.121851) | 1.556208 / 1.452155 (0.104054) | 1.612166 / 1.492716 (0.119450) |\n\n### Benchmark: benchmark_getitem\\_100B.json\n\n| metric | get_batch_of\\_1024\\_random_rows | get_batch_of\\_1024\\_rows | get_first_row | get_last_row |\n|--------|---|---|---|---|\n| new / old (diff) | 0.230633 / 0.018006 (0.212626) | 0.401667 / 0.000490 (0.401178) | 0.000776 / 0.000200 (0.000576) | 0.000069 / 0.000054 (0.000014) |\n\n### Benchmark: benchmark_indices_mapping.json\n\n| metric | select | shard | shuffle | sort | train_test_split |\n|--------|---|---|---|---|---|\n| new / old (diff) | 0.024959 / 0.037411 (-0.012452) | 0.100560 / 0.014526 (0.086034) | 0.109175 / 0.176557 (-0.067382) | 0.159919 / 0.737135 (-0.577217) | 0.112810 / 0.296338 (-0.183528) |\n\n### Benchmark: benchmark_iterating.json\n\n| metric | read 5000 | read 50000 | read_batch 50000 10 | read_batch 50000 100 | read_batch 50000 1000 | read_formatted numpy 5000 | read_formatted pandas 5000 | read_formatted tensorflow 5000 | read_formatted torch 5000 | read_formatted_batch numpy 5000 10 | read_formatted_batch numpy 5000 1000 | shuffled read 5000 | shuffled read 50000 | shuffled read_batch 50000 10 | shuffled read_batch 50000 100 | shuffled read_batch 50000 1000 | shuffled read_formatted numpy 5000 | shuffled read_formatted_batch numpy 5000 10 | shuffled read_formatted_batch numpy 5000 1000 |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.460601 / 0.215209 (0.245392) | 4.620039 / 2.077655 (2.542385) | 2.257900 / 1.504120 (0.753780) | 2.039192 / 1.541195 (0.497997) | 2.064451 / 1.468490 (0.595961) | 0.557887 / 4.584777 (-4.026890) | 3.356100 / 3.745712 (-0.389612) | 1.703578 / 5.269862 (-3.566284) | 1.024984 / 4.565676 (-3.540693) | 0.067602 / 0.424275 (-0.356673) | 0.011450 / 0.007607 (0.003842) | 0.563230 / 0.226044 (0.337186) | 5.632150 / 2.268929 (3.363221) | 2.698701 / 55.444624 (-52.745924) | 2.363218 / 6.876477 (-4.513259) | 2.363997 / 2.142072 (0.221925) | 0.671260 / 4.805227 (-4.133967) | 0.136166 / 6.500664 (-6.364499) | 0.067094 / 0.075469 (-0.008375) |\n\n### Benchmark: benchmark_map_filter.json\n\n| metric | filter | map fast-tokenizer batched | map identity | map identity batched | map no-op batched | map no-op batched numpy | map no-op batched pandas | map no-op batched pytorch | map no-op batched tensorflow |\n|--------|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 1.303030 / 1.841788 (-0.538757) | 14.137277 / 8.074308 (6.062969) | 13.937631 / 10.191392 (3.746239) | 0.162626 / 0.680424 (-0.517798) | 0.016687 / 0.534201 (-0.517514) | 0.363657 / 0.579283 (-0.215626) | 0.392021 / 0.434364 (-0.042343) | 0.427275 / 0.540337 (-0.113062) | 0.512192 / 1.386936 (-0.874744) |\n\n</details>\n</details>\n\n![](https://cml.dev/watermark.png#42603528d9bd8c3ab287ed0eadc7fa3d1ef4cfd8 "CML watermark")\n', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1609421011/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1609426080', 'html_url': 'https://github.com/huggingface/datasets/pull/5994#issuecomment-1609426080', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5994', 'id': 1609426080, 'node_id': 'IC_kwDODunzps5f7eSg', 'user': {'login': 'HuggingFaceDocBuilderDev', 'id': 99929124, 'node_id': 'U_kgDOBfTMJA', 'avatar_url': 'https://avatars.githubusercontent.com/u/99929124?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/HuggingFaceDocBuilderDev', 'html_url': 'https://github.com/HuggingFaceDocBuilderDev', 'followers_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/followers', 'following_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/following{/other_user}', 'gists_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/subscriptions', 'organizations_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/orgs', 'repos_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/repos', 'events_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/events{/privacy}', 'received_events_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-27T12:41:50Z', 'updated_at': '2023-06-27T15:33:13Z', 'author_association': 'NONE', 'body': '_The documentation is not available anymore as the PR was closed or merged._', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1609426080/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1609427850', 'html_url': 'https://github.com/huggingface/datasets/pull/5994#issuecomment-1609427850', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5994', 'id': 1609427850, 'node_id': 'IC_kwDODunzps5f7euK', 'user': {'login': 'github-actions[bot]', 'id': 41898282, 'node_id': 'MDM6Qm90NDE4OTgyODI=', 'avatar_url': 'https://avatars.githubusercontent.com/in/15368?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/github-actions%5Bbot%5D', 'html_url': 'https://github.com/apps/github-actions', 'followers_url': 'https://api.github.com/users/github-actions%5Bbot%5D/followers', 'following_url': 'https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}', 'gists_url': 'https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/github-actions%5Bbot%5D/subscriptions', 'organizations_url': 'https://api.github.com/users/github-actions%5Bbot%5D/orgs', 'repos_url': 'https://api.github.com/users/github-actions%5Bbot%5D/repos', 'events_url': 'https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}', 'received_events_url': 'https://api.github.com/users/github-actions%5Bbot%5D/received_events', 'type': 'Bot', 'site_admin': False}, 'created_at': '2023-06-27T12:42:58Z', 'updated_at': '2023-06-27T12:42:58Z', 'author_association': 'NONE', 'body': '<details>\n<summary>Show benchmarks</summary>\n\nPyArrow==8.0.0\n\n<details>\n<summary>Show updated benchmarks!</summary>\n\n### Benchmark: benchmark_array_xd.json\n\n| metric | read_batch_formatted_as_numpy after write_array2d | read_batch_formatted_as_numpy after write_flattened_sequence | read_batch_formatted_as_numpy after write_nested_sequence | read_batch_unformated after write_array2d | read_batch_unformated after write_flattened_sequence | read_batch_unformated after write_nested_sequence | read_col_formatted_as_numpy after write_array2d | read_col_formatted_as_numpy after write_flattened_sequence | read_col_formatted_as_numpy after write_nested_sequence | read_col_unformated after write_array2d | read_col_unformated after write_flattened_sequence | read_col_unformated after write_nested_sequence | read_formatted_as_numpy after write_array2d | read_formatted_as_numpy after write_flattened_sequence | read_formatted_as_numpy after write_nested_sequence | read_unformated after write_array2d | read_unformated after write_flattened_sequence | read_unformated after write_nested_sequence | write_array2d | write_flattened_sequence | write_nested_sequence |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.005974 / 0.011353 (-0.005378) | 0.003947 / 0.011008 (-0.007061) | 0.098604 / 0.038508 (0.060096) | 0.036947 / 0.023109 (0.013838) | 0.311844 / 0.275898 (0.035946) | 0.375243 / 0.323480 (0.051763) | 0.003453 / 0.007986 (-0.004533) | 0.003834 / 0.004328 (-0.000495) | 0.077943 / 0.004250 (0.073692) | 0.052956 / 0.037052 (0.015904) | 0.320812 / 0.258489 (0.062323) | 0.373963 / 0.293841 (0.080122) | 0.028382 / 0.128546 (-0.100164) | 0.008525 / 0.075646 (-0.067121) | 0.311306 / 0.419271 (-0.107965) | 0.047029 / 0.043533 (0.003496) | 0.309933 / 0.255139 (0.054794) | 0.335114 / 0.283200 (0.051915) | 0.019629 / 0.141683 (-0.122054) | 1.569771 / 1.452155 (0.117617) | 1.585899 / 1.492716 (0.093182) |\n\n### Benchmark: benchmark_getitem\\_100B.json\n\n| metric | get_batch_of\\_1024\\_random_rows | get_batch_of\\_1024\\_rows | get_first_row | get_last_row |\n|--------|---|---|---|---|\n| new / old (diff) | 0.216565 / 0.018006 (0.198559) | 0.426717 / 0.000490 (0.426228) | 0.003609 / 0.000200 (0.003409) | 0.000077 / 0.000054 (0.000023) |\n\n### Benchmark: benchmark_indices_mapping.json\n\n| metric | select | shard | shuffle | sort | train_test_split |\n|--------|---|---|---|---|---|\n| new / old (diff) | 0.023079 / 0.037411 (-0.014332) | 0.096954 / 0.014526 (0.082428) | 0.105398 / 0.176557 (-0.071158) | 0.165433 / 0.737135 (-0.571703) | 0.109703 / 0.296338 (-0.186636) |\n\n### Benchmark: benchmark_iterating.json\n\n| metric | read 5000 | read 50000 | read_batch 50000 10 | read_batch 50000 100 | read_batch 50000 1000 | read_formatted numpy 5000 | read_formatted pandas 5000 | read_formatted tensorflow 5000 | read_formatted torch 5000 | read_formatted_batch numpy 5000 10 | read_formatted_batch numpy 5000 1000 | shuffled read 5000 | shuffled read 50000 | shuffled read_batch 50000 10 | shuffled read_batch 50000 100 | shuffled read_batch 50000 1000 | shuffled read_formatted numpy 5000 | shuffled read_formatted_batch numpy 5000 10 | shuffled read_formatted_batch numpy 5000 1000 |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.456227 / 0.215209 (0.241018) | 4.529857 / 2.077655 (2.452202) | 2.214054 / 1.504120 (0.709934) | 2.029716 / 1.541195 (0.488521) | 2.081175 / 1.468490 (0.612685) | 0.563642 / 4.584777 (-4.021135) | 3.355393 / 3.745712 (-0.390320) | 1.765938 / 5.269862 (-3.503924) | 1.039062 / 4.565676 (-3.526615) | 0.067952 / 0.424275 (-0.356323) | 0.011044 / 0.007607 (0.003437) | 0.556935 / 0.226044 (0.330890) | 5.588167 / 2.268929 (3.319239) | 2.667217 / 55.444624 (-52.777407) | 2.337383 / 6.876477 (-4.539094) | 2.429590 / 2.142072 (0.287517) | 0.676972 / 4.805227 (-4.128256) | 0.135782 / 6.500664 (-6.364882) | 0.066323 / 0.075469 (-0.009146) |\n\n### Benchmark: benchmark_map_filter.json\n\n| metric | filter | map fast-tokenizer batched | map identity | map identity batched | map no-op batched | map no-op batched numpy | map no-op batched pandas | map no-op batched pytorch | map no-op batched tensorflow |\n|--------|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 1.237358 / 1.841788 (-0.604429) | 13.910492 / 8.074308 (5.836184) | 13.227275 / 10.191392 (3.035883) | 0.146857 / 0.680424 (-0.533567) | 0.016991 / 0.534201 (-0.517210) | 0.363637 / 0.579283 (-0.215646) | 0.392462 / 0.434364 (-0.041902) | 0.450009 / 0.540337 (-0.090329) | 0.536077 / 1.386936 (-0.850859) |\n\n</details>\nPyArrow==latest\n\n<details>\n<summary>Show updated benchmarks!</summary>\n\n### Benchmark: benchmark_array_xd.json\n\n| metric | read_batch_formatted_as_numpy after write_array2d | read_batch_formatted_as_numpy after write_flattened_sequence | read_batch_formatted_as_numpy after write_nested_sequence | read_batch_unformated after write_array2d | read_batch_unformated after write_flattened_sequence | read_batch_unformated after write_nested_sequence | read_col_formatted_as_numpy after write_array2d | read_col_formatted_as_numpy after write_flattened_sequence | read_col_formatted_as_numpy after write_nes

[{'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1609761600', 'html_url': 'https://github.com/huggingface/datasets/issues/5993#issuecomment-1609761600', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5993', 'id': 1609761600, 'node_id': 'IC_kwDODunzps5f8wNA', 'user': {'login': 'lhoestq', 'id': 42851186, 'node_id': 'MDQ6VXNlcjQyODUxMTg2', 'avatar_url': 'https://avatars.githubusercontent.com/u/42851186?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/lhoestq', 'html_url': 'https://github.com/lhoestq', 'followers_url': 'https://api.github.com/users/lhoestq/followers', 'following_url': 'https://api.github.com/users/lhoestq/following{/other_user}', 'gists_url': 'https://api.github.com/users/lhoestq/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/lhoestq/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/lhoestq/subscriptions', 'organizations_url': 'https://api.github.com/users/lhoestq/orgs', 'repos_url': 'https://api.github.com/users/lhoestq/repos', 'events_url': 'https://api.github.com/users/lhoestq/events{/privacy}', 'received_events_url': 'https://api.github.com/users/lhoestq/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-27T15:33:25Z', 'updated_at': '2023-06-27T15:33:25Z', 'author_association': 'MEMBER', 'body': "We'll do a new release of `datasets` soon to make the fix available :)\r\n\r\nIn the meantime you can use `datasets` from source (main)", 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1609761600/reactions', 'total_count': 1, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 1, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1609766729', 'html_url': 'https://github.com/huggingface/datasets/issues/5993#issuecomment-1609766729', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5993', 'id': 1609766729, 'node_id': 'IC_kwDODunzps5f8xdJ', 'user': {'login': 'exs-avianello', 'id': 128361578, 'node_id': 'U_kgDOB6akag', 'avatar_url': 'https://avatars.githubusercontent.com/u/128361578?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/exs-avianello', 'html_url': 'https://github.com/exs-avianello', 'followers_url': 'https://api.github.com/users/exs-avianello/followers', 'following_url': 'https://api.github.com/users/exs-avianello/following{/other_user}', 'gists_url': 'https://api.github.com/users/exs-avianello/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/exs-avianello/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/exs-avianello/subscriptions', 'organizations_url': 'https://api.github.com/users/exs-avianello/orgs', 'repos_url': 'https://api.github.com/users/exs-avianello/repos', 'events_url': 'https://api.github.com/users/exs-avianello/events{/privacy}', 'received_events_url': 'https://api.github.com/users/exs-avianello/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-27T15:36:41Z', 'updated_at': '2023-06-27T15:36:41Z', 'author_association': 'NONE', 'body': 'Thank you very much @lhoestq ! 🚀 ', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1609766729/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}]
[{'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1609120912', 'html_url': 'https://github.com/huggingface/datasets/pull/5992#issuecomment-1609120912', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5992', 'id': 1609120912, 'node_id': 'IC_kwDODunzps5f6TyQ', 'user': {'login': 'HuggingFaceDocBuilderDev', 'id': 99929124, 'node_id': 'U_kgDOBfTMJA', 'avatar_url': 'https://avatars.githubusercontent.com/u/99929124?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/HuggingFaceDocBuilderDev', 'html_url': 'https://github.com/HuggingFaceDocBuilderDev', 'followers_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/followers', 'following_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/following{/other_user}', 'gists_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/subscriptions', 'organizations_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/orgs', 'repos_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/repos', 'events_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/events{/privacy}', 'received_events_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-27T09:23:07Z', 'updated_at': '2023-06-27T09:23:07Z', 'author_association': 'NONE', 'body': 'The docs for this PR live [here](https://moon-ci-docs.huggingface.co/docs/datasets/pr_5992). All of your documentation changes will be reflected on that endpoint.', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1609120912/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}]
[]
[{'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1607443382', 'html_url': 'https://github.com/huggingface/datasets/issues/5989#issuecomment-1607443382', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5989', 'id': 1607443382, 'node_id': 'IC_kwDODunzps5fz6O2', 'user': {'login': 'polinaeterna', 'id': 16348744, 'node_id': 'MDQ6VXNlcjE2MzQ4NzQ0', 'avatar_url': 'https://avatars.githubusercontent.com/u/16348744?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/polinaeterna', 'html_url': 'https://github.com/polinaeterna', 'followers_url': 'https://api.github.com/users/polinaeterna/followers', 'following_url': 'https://api.github.com/users/polinaeterna/following{/other_user}', 'gists_url': 'https://api.github.com/users/polinaeterna/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/polinaeterna/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/polinaeterna/subscriptions', 'organizations_url': 'https://api.github.com/users/polinaeterna/orgs', 'repos_url': 'https://api.github.com/users/polinaeterna/repos', 'events_url': 'https://api.github.com/users/polinaeterna/events{/privacy}', 'received_events_url': 'https://api.github.com/users/polinaeterna/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-26T13:11:20Z', 'updated_at': '2023-06-26T13:11:20Z', 'author_association': 'CONTRIBUTOR', 'body': "in this case we need to decide what to do with the existing datasets with white space characters (there shouldn't be a lot of them I think)", 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1607443382/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1607446604', 'html_url': 'https://github.com/huggingface/datasets/issues/5989#issuecomment-1607446604', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5989', 'id': 1607446604, 'node_id': 'IC_kwDODunzps5fz7BM', 'user': {'login': 'severo', 'id': 1676121, 'node_id': 'MDQ6VXNlcjE2NzYxMjE=', 'avatar_url': 'https://avatars.githubusercontent.com/u/1676121?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/severo', 'html_url': 'https://github.com/severo', 'followers_url': 'https://api.github.com/users/severo/followers', 'following_url': 'https://api.github.com/users/severo/following{/other_user}', 'gists_url': 'https://api.github.com/users/severo/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/severo/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/severo/subscriptions', 'organizations_url': 'https://api.github.com/users/severo/orgs', 'repos_url': 'https://api.github.com/users/severo/repos', 'events_url': 'https://api.github.com/users/severo/events{/privacy}', 'received_events_url': 'https://api.github.com/users/severo/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-26T13:12:58Z', 'updated_at': '2023-06-26T13:12:58Z', 'author_association': 'CONTRIBUTOR', 'body': 'I imagine that we should stop supporting them, and help the user fix them?', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1607446604/reactions', 'total_count': 1, '+1': 1, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}]

[{'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1607870533', 'html_url': 'https://github.com/huggingface/datasets/issues/5988#issuecomment-1607870533', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5988', 'id': 1607870533, 'node_id': 'IC_kwDODunzps5f1ihF', 'user': {'login': 'mariosasko', 'id': 47462742, 'node_id': 'MDQ6VXNlcjQ3NDYyNzQy', 'avatar_url': 'https://avatars.githubusercontent.com/u/47462742?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/mariosasko', 'html_url': 'https://github.com/mariosasko', 'followers_url': 'https://api.github.com/users/mariosasko/followers', 'following_url': 'https://api.github.com/users/mariosasko/following{/other_user}', 'gists_url': 'https://api.github.com/users/mariosasko/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/mariosasko/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/mariosasko/subscriptions', 'organizations_url': 'https://api.github.com/users/mariosasko/orgs', 'repos_url': 'https://api.github.com/users/mariosasko/repos', 'events_url': 'https://api.github.com/users/mariosasko/events{/privacy}', 'received_events_url': 'https://api.github.com/users/mariosasko/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-26T16:59:59Z', 'updated_at': '2023-06-27T12:38:34Z', 'author_association': 'CONTRIBUTOR', 'body': 'Unfortunately, I can\'t reproduce the error. What does the following code return for you?\r\n```python\r\nimport requests\r\nfrom huggingface_hub import hf_hub_url\r\nr = requests.get(hf_hub_url("codeparrot/codeparrot-clean-train", "dataset_infos.json", repo_type="dataset"))\r\n```\r\n\r\nAlso, can you provide more info about your network (region, proxies, etc.)?', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1607870533/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}]
[{'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1608055333', 'html_url': 'https://github.com/huggingface/datasets/issues/5987#issuecomment-1608055333', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5987', 'id': 1608055333, 'node_id': 'IC_kwDODunzps5f2Pol', 'user': {'login': 'mariosasko', 'id': 47462742, 'node_id': 'MDQ6VXNlcjQ3NDYyNzQy', 'avatar_url': 'https://avatars.githubusercontent.com/u/47462742?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/mariosasko', 'html_url': 'https://github.com/mariosasko', 'followers_url': 'https://api.github.com/users/mariosasko/followers', 'following_url': 'https://api.github.com/users/mariosasko/following{/other_user}', 'gists_url': 'https://api.github.com/users/mariosasko/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/mariosasko/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/mariosasko/subscriptions', 'organizations_url': 'https://api.github.com/users/mariosasko/orgs', 'repos_url': 'https://api.github.com/users/mariosasko/repos', 'events_url': 'https://api.github.com/users/mariosasko/events{/privacy}', 'received_events_url': 'https://api.github.com/users/mariosasko/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-26T18:52:36Z', 'updated_at': '2023-06-26T18:52:36Z', 'author_association': 'CONTRIBUTOR', 'body': 'Can you explain your use case for `max_shard_size`? \r\n\r\nOn some systems, there is a limit to the size of a memory-mapped file, so we could consider exposing this parameter in `load_dataset`.', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1608055333/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1608590487', 'html_url': 'https://github.com/huggingface/datasets/issues/5987#issuecomment-1608590487', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5987', 'id': 1608590487, 'node_id': 'IC_kwDODunzps5f4SSX', 'user': {'login': 'npuichigo', 'id': 11533479, 'node_id': 'MDQ6VXNlcjExNTMzNDc5', 'avatar_url': 'https://avatars.githubusercontent.com/u/11533479?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/npuichigo', 'html_url': 'https://github.com/npuichigo', 'followers_url': 'https://api.github.com/users/npuichigo/followers', 'following_url': 'https://api.github.com/users/npuichigo/following{/other_user}', 'gists_url': 'https://api.github.com/users/npuichigo/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/npuichigo/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/npuichigo/subscriptions', 'organizations_url': 'https://api.github.com/users/npuichigo/orgs', 'repos_url': 'https://api.github.com/users/npuichigo/repos', 'events_url': 'https://api.github.com/users/npuichigo/events{/privacy}', 'received_events_url': 'https://api.github.com/users/npuichigo/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-27T01:59:37Z', 'updated_at': '2023-06-27T01:59:37Z', 'author_association': 'NONE', 'body': 'In my use case, users may choose a proper size to balance the cost and benefit of using large shard size. (On azure blob or hdfs which may automatically download the shard from background)', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1608590487/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1611836049', 'html_url': 'https://github.com/huggingface/datasets/issues/5987#issuecomment-1611836049', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5987', 'id': 1611836049, 'node_id': 'IC_kwDODunzps5gEqqR', 'user': {'login': 'mariosasko', 'id': 47462742, 'node_id': 'MDQ6VXNlcjQ3NDYyNzQy', 'avatar_url': 'https://avatars.githubusercontent.com/u/47462742?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/mariosasko', 'html_url': 'https://github.com/mariosasko', 'followers_url': 'https://api.github.com/users/mariosasko/followers', 'following_url': 'https://api.github.com/users/mariosasko/following{/other_user}', 'gists_url': 'https://api.github.com/users/mariosasko/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/mariosasko/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/mariosasko/subscriptions', 'organizations_url': 'https://api.github.com/users/mariosasko/orgs', 'repos_url': 'https://api.github.com/users/mariosasko/repos', 'events_url': 'https://api.github.com/users/mariosasko/events{/privacy}', 'received_events_url': 'https://api.github.com/users/mariosasko/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-28T17:44:40Z', 'updated_at': '2023-06-28T17:44:40Z', 'author_association': 'CONTRIBUTOR', 'body': "But `load_dataset` doesn't support caching (and reading) Arrow datasets from remote storage. \r\n\r\n`load_datset_builder` + `download_and_prepare` is not equal to `load_dataset`. The latter has one more step, `builder.as_dataset`, that memory-maps Arrow files, which only works for local files.", 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1611836049/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1612388769', 'html_url': 'https://github.com/huggingface/datasets/issues/5987#issuecomment-1612388769', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5987', 'id': 1612388769, 'node_id': 'IC_kwDODunzps5gGxmh', 'user': {'login': 'npuichigo', 'id': 11533479, 'node_id': 'MDQ6VXNlcjExNTMzNDc5', 'avatar_url': 'https://avatars.githubusercontent.com/u/11533479?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/npuichigo', 'html_url': 'https://github.com/npuichigo', 'followers_url': 'https://api.github.com/users/npuichigo/followers', 'following_url': 'https://api.github.com/users/npuichigo/following{/other_user}', 'gists_url': 'https://api.github.com/users/npuichigo/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/npuichigo/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/npuichigo/subscriptions', 'organizations_url': 'https://api.github.com/users/npuichigo/orgs', 'repos_url': 'https://api.github.com/users/npuichigo/repos', 'events_url': 'https://api.github.com/users/npuichigo/events{/privacy}', 'received_events_url': 'https://api.github.com/users/npuichigo/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-29T03:42:09Z', 'updated_at': '2023-06-29T03:42:09Z', 'author_association': 'NONE', 'body': 'Thanks. So if I want to use `IterableDataset` and control the size of single arrow file, how should I organize the data loader? Maybe `load_dataset_build` + `download_and_prepare` + `builder.as_dataset` + `dataset.to_iterable_dataset`?', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1612388769/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1613387103', 'html_url': 'https://github.com/huggingface/datasets/issues/5987#issuecomment-1613387103', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5987', 'id': 1613387103, 'node_id': 'IC_kwDODunzps5gKlVf', 'user': {'login': 'mariosasko', 'id': 47462742, 'node_id': 'MDQ6VXNlcjQ3NDYyNzQy', 'avatar_url': 'https://avatars.githubusercontent.com/u/47462742?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/mariosasko', 'html_url': 'https://github.com/mariosasko', 'followers_url': 'https://api.github.com/users/mariosasko/followers', 'following_url': 'https://api.github.com/users/mariosasko/following{/other_user}', 'gists_url': 'https://api.github.com/users/mariosasko/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/mariosasko/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/mariosasko/subscriptions', 'organizations_url': 'https://api.github.com/users/mariosasko/orgs', 'repos_url': 'https://api.github.com/users/mariosasko/repos', 'events_url': 'https://api.github.com/users/mariosasko/events{/privacy}', 'received_events_url': 'https://api.github.com/users/mariosasko/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-29T15:24:38Z', 'updated_at': '2023-06-29T15:24:38Z', 'author_association': 'CONTRIBUTOR', 'body': 'Yes, this should work.\r\n\r\nI think we can expose `max_shard_size` in `load_dataset`, so feel free to open a PR.', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1613387103/reactions', 'total_count': 1, '+1': 1, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}]

[{'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1622177194', 'html_url': 'https://github.com/huggingface/datasets/pull/5986#issuecomment-1622177194', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5986', 'id': 1622177194, 'node_id': 'IC_kwDODunzps5gsHWq', 'user': {'login': 'maddiedawson', 'id': 106995444, 'node_id': 'U_kgDOBmCe9A', 'avatar_url': 'https://avatars.githubusercontent.com/u/106995444?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/maddiedawson', 'html_url': 'https://github.com/maddiedawson', 'followers_url': 'https://api.github.com/users/maddiedawson/followers', 'following_url': 'https://api.github.com/users/maddiedawson/following{/other_user}', 'gists_url': 'https://api.github.com/users/maddiedawson/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/maddiedawson/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/maddiedawson/subscriptions', 'organizations_url': 'https://api.github.com/users/maddiedawson/orgs', 'repos_url': 'https://api.github.com/users/maddiedawson/repos', 'events_url': 'https://api.github.com/users/maddiedawson/events{/privacy}', 'received_events_url': 'https://api.github.com/users/maddiedawson/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-07-05T17:21:03Z', 'updated_at': '2023-07-05T17:21:03Z', 'author_association': 'CONTRIBUTOR', 'body': '@lhoestq would you be able to review this please and also approve the workflow?', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1622177194/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1623359134', 'html_url': 'https://github.com/huggingface/datasets/pull/5986#issuecomment-1623359134', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5986', 'id': 1623359134, 'node_id': 'IC_kwDODunzps5gwn6e', 'user': {'login': 'lhoestq', 'id': 42851186, 'node_id': 'MDQ6VXNlcjQyODUxMTg2', 'avatar_url': 'https://avatars.githubusercontent.com/u/42851186?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/lhoestq', 'html_url': 'https://github.com/lhoestq', 'followers_url': 'https://api.github.com/users/lhoestq/followers', 'following_url': 'https://api.github.com/users/lhoestq/following{/other_user}', 'gists_url': 'https://api.github.com/users/lhoestq/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/lhoestq/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/lhoestq/subscriptions', 'organizations_url': 'https://api.github.com/users/lhoestq/orgs', 'repos_url': 'https://api.github.com/users/lhoestq/repos', 'events_url': 'https://api.github.com/users/lhoestq/events{/privacy}', 'received_events_url': 'https://api.github.com/users/lhoestq/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-07-06T09:40:43Z', 'updated_at': '2023-07-06T09:40:43Z', 'author_association': 'MEMBER', 'body': 'Sounds good to me :) feel free to run `make style` to apply code formatting', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1623359134/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1623366517', 'html_url': 'https://github.com/huggingface/datasets/pull/5986#issuecomment-1623366517', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5986', 'id': 1623366517, 'node_id': 'IC_kwDODunzps5gwpt1', 'user': {'login': 'HuggingFaceDocBuilderDev', 'id': 99929124, 'node_id': 'U_kgDOBfTMJA', 'avatar_url': 'https://avatars.githubusercontent.com/u/99929124?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/HuggingFaceDocBuilderDev', 'html_url': 'https://github.com/HuggingFaceDocBuilderDev', 'followers_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/followers', 'following_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/following{/other_user}', 'gists_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/subscriptions', 'organizations_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/orgs', 'repos_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/repos', 'events_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/events{/privacy}', 'received_events_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-07-06T09:44:55Z', 'updated_at': '2023-07-07T09:56:36Z', 'author_association': 'NONE', 'body': '_The documentation is not available anymore as the PR was closed or merged._', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1623366517/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1623976935', 'html_url': 'https://github.com/huggingface/datasets/pull/5986#issuecomment-1623976935', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5986', 'id': 1623976935, 'node_id': 'IC_kwDODunzps5gy-vn', 'user': {'login': 'lhoestq', 'id': 42851186, 'node_id': 'MDQ6VXNlcjQyODUxMTg2', 'avatar_url': 'https://avatars.githubusercontent.com/u/42851186?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/lhoestq', 'html_url': 'https://github.com/lhoestq', 'followers_url': 'https://api.github.com/users/lhoestq/followers', 'following_url': 'https://api.github.com/users/lhoestq/following{/other_user}', 'gists_url': 'https://api.github.com/users/lhoestq/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/lhoestq/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/lhoestq/subscriptions', 'organizations_url': 'https://api.github.com/users/lhoestq/orgs', 'repos_url': 'https://api.github.com/users/lhoestq/repos', 'events_url': 'https://api.github.com/users/lhoestq/events{/privacy}', 'received_events_url': 'https://api.github.com/users/lhoestq/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-07-06T16:32:53Z', 'updated_at': '2023-07-06T16:32:53Z', 'author_association': 'MEMBER', 'body': 'cool ! I think we can merge once all comments have been addressed', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1623976935/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1624079323', 'html_url': 'https://github.com/huggingface/datasets/pull/5986#issuecomment-1624079323', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5986', 'id': 1624079323, 'node_id': 'IC_kwDODunzps5gzXvb', 'user': {'login': 'mathewjacob1002', 'id': 134338709, 'node_id': 'U_kgDOCAHYlQ', 'avatar_url': 'https://avatars.githubusercontent.com/u/134338709?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/mathewjacob1002', 'html_url': 'https://github.com/mathewjacob1002', 'followers_url': 'https://api.github.com/users/mathewjacob1002/followers', 'following_url': 'https://api.github.com/users/mathewjacob1002/following{/other_user}', 'gists_url': 'https://api.github.com/users/mathewjacob1002/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/mathewjacob1002/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/mathewjacob1002/subscriptions', 'organizations_url': 'https://api.github.com/users/mathewjacob1002/orgs', 'repos_url': 'https://api.github.com/users/mathewjacob1002/repos', 'events_url': 'https://api.github.com/users/mathewjacob1002/events{/privacy}', 'received_events_url': 'https://api.github.com/users/mathewjacob1002/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-07-06T17:41:13Z', 'updated_at': '2023-07-06T17:41:13Z', 'author_association': 'CONTRIBUTOR', 'body': '@lhoestq I just addressed the comments and I think we can move ahead with this! \r\n', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1624079323/reactions', 'total_count': 1, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 1, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1625176426', 'html_url': 'https://github.com/huggingface/datasets/pull/5986#issuecomment-1625176426', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5986', 'id': 1625176426, 'node_id': 'IC_kwDODunzps5g3jlq', 'user': {'login': 'github-actions[bot]', 'id': 41898282, 'node_id': 'MDM6Qm90NDE4OTgyODI=', 'avatar_url': 'https://avatars.githubusercontent.com/in/15368?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/github-actions%5Bbot%5D', 'html_url': 'https://github.com/apps/github-actions', 'followers_url': 'https://api.github.com/users/github-actions%5Bbot%5D/followers', 'following_url': 'https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}', 'gists_url': 'https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/github-actions%5Bbot%5D/subscriptions', 'organizations_url': 'https://api.github.com/users/github-actions%5Bbot%5D/orgs', 'repos_url': 'https://api.github.com/users/github-actions%5Bbot%5D/repos', 'events_url': 'https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}', 'received_events_url': 'https://api.github.com/users/github-actions%5Bbot%5D/received_events', 'type': 'Bot', 'site_admin': False}, 'created_at': '2023-07-07T10:05:58Z', 'updated_at': '2023-07-07T10:05:58Z', 'author_association': 'NONE', 'body': '<details>\n<summary>Show benchmarks</summary>\n\nPyArrow==8.0.0\n\n<details>\n<summary>Show updated benchmarks!</summary>\n\n### Benchmark: benchmark_array_xd.json\n\n| metric | read_batch_formatted_as_numpy after write_array2d | read_batch_formatted_as_numpy after write_flattened_sequence | read_batch_formatted_as_numpy after write_nested_sequence | read_batch_unformated after write_array2d | read_batch_unformated after write_flattened_sequence | read_batch_unformated after write_nested_sequence | read_col_formatted_as_numpy after write_array2d | read_col_formatted_as_numpy after write_flattened_sequence | read_col_formatted_as_numpy after write_nested_sequence | read_col_unformated after write_array2d | read_col_unformated after write_flattened_sequence | read_col_unformated after write_nested_sequence | read_formatted_as_numpy after write_array2d | read_formatted_as_numpy after write_flattened_sequence | read_formatted_as_numpy after write_nested_sequence | read_unformated after write_array2d | read_unformated after write_flattened_sequence | read_unformated after write_nested_sequence | write_array2d | write_flattened_sequence | write_nested_sequence |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.007734 / 0.011353 (-0.003619) | 0.004608 / 0.011008 (-0.006400) | 0.094466 / 0.038508 (0.055958) | 0.086477 / 0.023109 (0.063368) | 0.410311 / 0.275898 (0.134413) | 0.455560 / 0.323480 (0.132080) | 0.006112 / 0.007986 (-0.001874) | 0.003845 / 0.004328 (-0.000483) | 0.072506 / 0.004250 (0.068256) | 0.066721 / 0.037052 (0.029669) | 0.409967 / 0.258489 (0.151478) | 0.460480 / 0.293841 (0.166639) | 0.036700 / 0.128546 (-0.091847) | 0.009854 / 0.075646 (-0.065792) | 0.320936 / 0.419271 (-0.098335) | 0.061002 / 0.043533 (0.017469) | 0.413963 / 0.255139 (0.158824) | 0.426787 / 0.283200 (0.143588) | 0.029182 / 0.141683 (-0.112501) | 1.685136 / 1.452155 (0.232981) | 1.754590 / 1.492716 (0.261873) |\n\n### Benchmark: benchmark_getitem\\_100B.json\n\n| metric | get_batch_of\\_1024\\_random_rows | get_batch_of\\_1024\\_rows | get_first_row | get_last_row |\n|--------|---|---|---|---|\n| new / old (diff) | 0.222698 / 0.018006 (0.204692) | 0.505929 / 0.000490 (0.505440) | 0.005291 / 0.000200 (0.005091) | 0.000097 / 0.000054 (0.000042) |\n\n### Benchmark: benchmark_indices_mapping.json\n\n| metric | select | shard | shuffle | sort | train_test_split |\n|--------|---|---|---|---|---|\n| new / old (diff) | 0.032527 / 0.037411 (-0.004884) | 0.094842 / 0.014526 (0.080317) | 0.110138 / 0.176557 (-0.066418) | 0.193786 / 0.737135 (-0.543349) | 0.112593 / 0.296338 (-0.183745) |\n\n### Benchmark: benchmark_iterating.json\n\n| metric | read 5000 | read 50000 | read_batch 50000 10 | read_batch 50000 100 | read_batch 50000 1000 | read_formatted numpy 5000 | read_formatted pandas 5000 | read_formatted tensorflow 5000 | read_formatted torch 5000 | read_formatted_batch numpy 5000 10 | read_formatted_batch numpy 5000 1000 | shuffled read 5000 | shuffled read 50000 | shuffled read_batch 50000 10 | shuffled read_batch 50000 100 | shuffled read_batch 50000 1000 | shuffled read_formatted numpy 5000 | shuffled read_formatted_batch numpy 5000 10 | shuffled read_formatted_batch numpy 5000 1000 |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.441671 / 0.215209 (0.226461) | 4.392961 / 2.077655 (2.315306) | 2.161111 / 1.504120 (0.656991) | 1.967080 / 1.541195 (0.425885) | 2.065411 / 1.468490 (0.596920) | 0.561080 / 4.584777 (-4.023697) | 4.159612 / 3.745712 (0.413900) | 6.435248 / 5.269862 (1.165386) | 3.732338 / 4.565676 (-0.833339) | 0.066156 / 0.424275 (-0.358119) | 0.008030 / 0.007607 (0.000423) | 0.532182 / 0.226044 (0.306137) | 5.315142 / 2.268929 (3.046213) | 2.680157 / 55.444624 (-52.764467) | 2.303799 / 6.876477 (-4.572677) | 2.530911 / 2.142072 (0.388838) | 0.669504 / 4.805227 (-4.135723) | 0.151940 / 6.500664 (-6.348724) | 0.066999 / 0.075469 (-0.008470) |\n\n### Benchmark: benchmark_map_filter.json\n\n| metric | filter | map fast-tokenizer batched | map identity | map identity batched | map no-op batched | map no-op batched numpy | map no-op batched pandas | map no-op batched pytorch | map no-op batched tensorflow |\n|--------|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 1.424275 / 1.841788 (-0.417513) | 21.550742 / 8.074308 (13.476434) | 16.031414 / 10.191392 (5.840022) | 0.194681 / 0.680424 (-0.485743) | 0.020389 / 0.534201 (-0.513812) | 0.429808 / 0.579283 (-0.149475) | 0.457503 / 0.434364 (0.023139) | 0.511522 / 0.540337 (-0.028816) | 0.682621 / 1.386936 (-0.704315) |\n\n</details>\nPyArrow==latest\n\n<details>\n<summary>Show updated benchmarks!</summary>\n\n### Benchmark: benchmark_array_xd.json\n\n| metric | read_batch_formatted_as_numpy after write_array2d | read_batch_formatted_as_numpy after write_flattened_sequence | read_batch_formatted_as_numpy after write_nested_sequence | read_batch_unformated after write_array2d | read_batch_unformated after write_flattened_sequence | read_batch_unformated after write_nested_sequence | read_col_formatted_as_numpy after write_array2d | read_col_formatted_as_numpy after write_flattened_sequence | read_col_formatted_as_numpy after write_nested_sequence | read_col_unformated after write_array2d | read_col_unformated after write_flattened_sequence | read_col_unformated after write_nested_sequence | read_formatted_as_numpy after write_array2d | read_formatted_as_numpy after write_flattened_sequence | read_formatted_as_numpy after write_nested_sequence | read_unformated after write_array2d | read_unformated after write_flattened_sequence | read_unformated after write_nested_sequence | write_array2d | write_flattened_sequence | write_nested_sequence |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.007519 / 0.011353 (-0.003834) | 0.004445 / 0.011008 (-0.006563) | 0.071946 / 0.038508 (0.033438) | 0.082982 / 0.023109 (0.059873) | 0.459938 / 0.275898 (0.184040) | 0.504875 / 0.323480 (0.181395) | 0.005805 / 0.007986 (-0.002181) | 0.003740 / 0.004328 (-0.000589) | 0.071998 / 0.004250 (0.067747) | 0.062580 / 0.037052 (0.025527) | 0.462263 / 0.258489 (0.203774) | 0.506355 / 0.293841 (0.212514) | 0.036321 / 0.128546 (-0.092225) | 0.009830 / 0.075646 (-0.065816) | 0.079810 / 0.419271 (-0.339461) | 0.055291 / 0.043533 (0.011758) | 0.464093 / 0.255139 (0.208954) | 0.481109 / 0.283200 (0.197910) | 0.026909 / 0.141683 (-0.114774) | 1.652538 / 1.452155 (0.200383) | 1.750713 / 1.492716 (0.257997) |\n\n### Benchmark: benchmark_getitem\\_100B.json\n\n| metric | get_batch_of\\_1024\\_random_rows | get_batch_of\\_1024\\_rows | get_first_row | get_last_row |\n|--------|---|---|---|---|\n| new / old (diff) | 0.267552 / 0.018006 (0.249546) | 0.502021 / 0.000490 (0.501531) | 0.001635 / 0.000200 (0.001435) | 0.000099 / 0.000054 (0.000044) |\n\n### Benchmark: benchmark_indices_mapping.json\n\n| metric | select | shard | shuffle | sort | train_test_split |\n|--------|---|---|---|---|---|\n| new / old (diff) | 0.033747 / 0.037411 (-0.003665) | 0.104242 / 0.014526 (0.089716) | 0.113829 / 0.176557 (-0.062728) | 0.176242 / 0.737135 (-0.560893) | 0.117002 / 0.296338 (-0.179336) |\n\n### Benchmark: benchmark_iterating.json\n\n| metric | read 5000 | read 50000 | read_batch 50000 10 | read_batch 50000 100 | read_batch 50000 1000 | read_formatted numpy 5000 | read_formatted pandas 5000 | read_formatted tensorflow 5000 | read_formatted torch 5000 | read_formatted_batch numpy 5000 10 | read_formatted_batch numpy 5000 1000 | shuffled read 5000 | shuffled read 50000 | shuffled read_batch 50000 10 | shuffled read_batch 50000 100 | shuffled read_batch 50000 1000 | shuffled read_formatted numpy 5000 | shuffled read_formatted_batch numpy 5000 10 | shuffled read_formatted_batch numpy 5000 1000 |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.476731 / 0.215209 (0.261522) | 4.727054 / 2.077655 (2.649399) | 2.589396 / 1.504120 (1.085276) | 2.511180 / 1.541195 (0.969985) | 2.634122 / 1.468490 (1.165632) | 0.563840 / 4.584777 (-4.020937) | 4.140212 / 3.745712 (0.394500) | 6.188789 / 5.269862 (0.918928) | 3.716897 / 4.565676 (-0.848780) | 0.065823 / 0.424275 (-0.358452) | 0.007705 / 0.007607 (0.000098) | 0.566580 / 0.226044 (0.340535) | 5.653306 / 2.268929 (3.384377) | 3.028756 / 55.444624 (-52.415868) | 2.592319 / 6.876477 (-4.284158) | 2.614250 / 2.142072 (0.472178) | 0.667135 / 4.805227 (-4.138093) | 0.153455 / 6.500664 (-6.347209) | 0.069321 / 0.075469 (-0.006148) |\n\n### Benchmark: benchmark_map_filter.json\n\n| metric | filter | map fast-tokenizer batched | map identity | map identity batched | map no-op batched | map no-op batched numpy | map no-op batched pandas | map no-op batched pytorch | map no-op batched tensorflow |\n|--------|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 1.541978 / 1.841788 (-0.299810) | 21.747360 / 8.074308 (13.673052) | 15.963657 / 10.191392 (5.772265) | 0.192843 / 0.680424 (-0.487581) | 0.020702 / 0.534201 (-0.513499) | 0.433620 / 0.579283 (-0.145663) | 0.467327 / 0.434364 (0.032963) | 0.507398 / 0.540337 (-0.032940) | 0.692797 / 1.386936 (-0.694140) |\n\n</details>\n</details>\n\n![](https://cml.dev/watermark.png#396cf9419d12e3150e2051793b10f2c813780a90 "CML watermark")\n', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1625176426/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'lau

[{'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1607379408', 'html_url': 'https://github.com/huggingface/datasets/issues/5985#issuecomment-1607379408', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5985', 'id': 1607379408, 'node_id': 'IC_kwDODunzps5fzqnQ', 'user': {'login': 'mariosasko', 'id': 47462742, 'node_id': 'MDQ6VXNlcjQ3NDYyNzQy', 'avatar_url': 'https://avatars.githubusercontent.com/u/47462742?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/mariosasko', 'html_url': 'https://github.com/mariosasko', 'followers_url': 'https://api.github.com/users/mariosasko/followers', 'following_url': 'https://api.github.com/users/mariosasko/following{/other_user}', 'gists_url': 'https://api.github.com/users/mariosasko/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/mariosasko/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/mariosasko/subscriptions', 'organizations_url': 'https://api.github.com/users/mariosasko/orgs', 'repos_url': 'https://api.github.com/users/mariosasko/repos', 'events_url': 'https://api.github.com/users/mariosasko/events{/privacy}', 'received_events_url': 'https://api.github.com/users/mariosasko/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-26T12:34:44Z', 'updated_at': '2023-06-26T12:34:44Z', 'author_association': 'CONTRIBUTOR', 'body': 'This is a known issue: https://github.com/huggingface/datasets/issues/3847.\r\n\r\nFixing this requires significant work - rewriting the `tokenizers` lib to make them immutable.\r\n\r\nThe current solution is to pass `cache_file_name` to `map` to use that file for caching or calling a tokenizer before `map` (with the same set of parameters as the ones in the map transform)', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1607379408/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}]
[{'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1607962103', 'html_url': 'https://github.com/huggingface/datasets/issues/5984#issuecomment-1607962103', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5984', 'id': 1607962103, 'node_id': 'IC_kwDODunzps5f1433', 'user': {'login': 'mariosasko', 'id': 47462742, 'node_id': 'MDQ6VXNlcjQ3NDYyNzQy', 'avatar_url': 'https://avatars.githubusercontent.com/u/47462742?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/mariosasko', 'html_url': 'https://github.com/mariosasko', 'followers_url': 'https://api.github.com/users/mariosasko/followers', 'following_url': 'https://api.github.com/users/mariosasko/following{/other_user}', 'gists_url': 'https://api.github.com/users/mariosasko/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/mariosasko/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/mariosasko/subscriptions', 'organizations_url': 'https://api.github.com/users/mariosasko/orgs', 'repos_url': 'https://api.github.com/users/mariosasko/repos', 'events_url': 'https://api.github.com/users/mariosasko/events{/privacy}', 'received_events_url': 'https://api.github.com/users/mariosasko/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-26T17:59:25Z', 'updated_at': '2023-06-26T17:59:25Z', 'author_association': 'CONTRIBUTOR', 'body': 'For this to be possible, we would have to switch from the "Streaming" Arrow format to the "Random Access" (IPC/Feather) format, which allows reading arbitrary record batches (explained [here](https://arrow.apache.org/docs/python/ipc.html)). We could then use these batches to construct shards.\r\n\r\n@lhoestq @albertvillanova Do you think this use case is worth the switch? Also, we currently shard files, not inner row groups/chunks. Should we also support sharding row groups (e.g. if the number of input files is 1)?\r\n\r\nPS: I don\'t expect significant speed-up for local, uncompressed Arrow files.', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1607962103/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1609426767', 'html_url': 'https://github.com/huggingface/datasets/issues/5984#issuecomment-1609426767', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5984', 'id': 1609426767, 'node_id': 'IC_kwDODunzps5f7edP', 'user': {'login': 'lhoestq', 'id': 42851186, 'node_id': 'MDQ6VXNlcjQyODUxMTg2', 'avatar_url': 'https://avatars.githubusercontent.com/u/42851186?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/lhoestq', 'html_url': 'https://github.com/lhoestq', 'followers_url': 'https://api.github.com/users/lhoestq/followers', 'following_url': 'https://api.github.com/users/lhoestq/following{/other_user}', 'gists_url': 'https://api.github.com/users/lhoestq/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/lhoestq/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/lhoestq/subscriptions', 'organizations_url': 'https://api.github.com/users/lhoestq/orgs', 'repos_url': 'https://api.github.com/users/lhoestq/repos', 'events_url': 'https://api.github.com/users/lhoestq/events{/privacy}', 'received_events_url': 'https://api.github.com/users/lhoestq/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-27T12:42:17Z', 'updated_at': '2023-06-27T12:42:17Z', 'author_association': 'MEMBER', 'body': 'Alternatively we could support multiprocessing map for iterable datasets and let the user do the CPU intensive task there ?\r\n\r\nThis way it would work on arrow data but also on any iterable dataset', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1609426767/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1620234926', 'html_url': 'https://github.com/huggingface/datasets/issues/5984#issuecomment-1620234926', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5984', 'id': 1620234926, 'node_id': 'IC_kwDODunzps5gktKu', 'user': {'login': 'imarquart', 'id': 102803372, 'node_id': 'U_kgDOBiCnrA', 'avatar_url': 'https://avatars.githubusercontent.com/u/102803372?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/imarquart', 'html_url': 'https://github.com/imarquart', 'followers_url': 'https://api.github.com/users/imarquart/followers', 'following_url': 'https://api.github.com/users/imarquart/following{/other_user}', 'gists_url': 'https://api.github.com/users/imarquart/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/imarquart/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/imarquart/subscriptions', 'organizations_url': 'https://api.github.com/users/imarquart/orgs', 'repos_url': 'https://api.github.com/users/imarquart/repos', 'events_url': 'https://api.github.com/users/imarquart/events{/privacy}', 'received_events_url': 'https://api.github.com/users/imarquart/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-07-04T13:16:11Z', 'updated_at': '2023-07-04T13:16:11Z', 'author_association': 'NONE', 'body': '> For this to be possible, we would have to switch from the "Streaming" Arrow format to the "Random Access" (IPC/Feather) format, which allows reading arbitrary record batches (explained [here](https://arrow.apache.org/docs/python/ipc.html)). We could then use these batches to construct shards.\r\n> \r\n> @lhoestq @albertvillanova Do you think this use case is worth the switch? Also, we currently shard files, not inner row groups/chunks. Should we also support sharding row groups (e.g. if the number of input files is 1)?\r\n> \r\n> PS: I don\'t expect significant speed-up for local, uncompressed Arrow files.\r\n\r\nCould you explain why you\'d need to change the arrow format?\r\n\r\nWhen we use streaming datasets we simply determine the number of worker shards and then add some modulo logic at the appropriate place. Worst case scenario, you\'d skip streaming entries according to the number of shards.\r\n\r\nFor PyTorch, I\'d be happy to provide an implementation or a sketch thereof, if you point me toward what the testing requirements would be for such a PR.', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1620234926/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1620457064', 'html_url': 'https://github.com/huggingface/datasets/issues/5984#issuecomment-1620457064', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5984', 'id': 1620457064, 'node_id': 'IC_kwDODunzps5gljZo', 'user': {'login': 'lhoestq', 'id': 42851186, 'node_id': 'MDQ6VXNlcjQyODUxMTg2', 'avatar_url': 'https://avatars.githubusercontent.com/u/42851186?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/lhoestq', 'html_url': 'https://github.com/lhoestq', 'followers_url': 'https://api.github.com/users/lhoestq/followers', 'following_url': 'https://api.github.com/users/lhoestq/following{/other_user}', 'gists_url': 'https://api.github.com/users/lhoestq/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/lhoestq/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/lhoestq/subscriptions', 'organizations_url': 'https://api.github.com/users/lhoestq/orgs', 'repos_url': 'https://api.github.com/users/lhoestq/repos', 'events_url': 'https://api.github.com/users/lhoestq/events{/privacy}', 'received_events_url': 'https://api.github.com/users/lhoestq/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-07-04T15:35:17Z', 'updated_at': '2023-07-04T15:35:17Z', 'author_association': 'MEMBER', 'body': "> Could you explain why you'd need to change the arrow format?\r\n\r\nThis way workers have random access to the location of the file where its dataset subset starts. Currently we're using the Arrow streaming format which doesn't include the metadata of the record batches offsets. This is needed here to efficiently split a dataset made of one single file.", 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1620457064/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1620513876', 'html_url': 'https://github.com/huggingface/datasets/issues/5984#issuecomment-1620513876', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5984', 'id': 1620513876, 'node_id': 'IC_kwDODunzps5glxRU', 'user': {'login': 'imarquart', 'id': 102803372, 'node_id': 'U_kgDOBiCnrA', 'avatar_url': 'https://avatars.githubusercontent.com/u/102803372?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/imarquart', 'html_url': 'https://github.com/imarquart', 'followers_url': 'https://api.github.com/users/imarquart/followers', 'following_url': 'https://api.github.com/users/imarquart/following{/other_user}', 'gists_url': 'https://api.github.com/users/imarquart/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/imarquart/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/imarquart/subscriptions', 'organizations_url': 'https://api.github.com/users/imarquart/orgs', 'repos_url': 'https://api.github.com/users/imarquart/repos', 'events_url': 'https://api.github.com/users/imarquart/events{/privacy}', 'received_events_url': 'https://api.github.com/users/imarquart/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-07-04T16:28:12Z', 'updated_at': '2023-07-04T16:29:48Z', 'author_association': 'NONE', 'body': "> > Could you explain why you'd need to change the arrow format?\r\n> \r\n> This way workers have random access to the location of the file where its dataset subset starts. Currently we're using the Arrow streaming format which doesn't include the metadata of the record batches offsets. This is needed here to efficiently split a dataset made of one single file.\r\n\r\nI guess I don't understand why you'd need to subset the dataset in the first place. \r\nIt seems sufficient to figure out how to offset or skip rows.\r\n\r\nFor instance, using pyArrow, you could use RecordBatchStreamReader to zero-copy iterate over records with read_next_batch and then only initiate the next step for records modulo worker shard.\r\nThat's one way to do it, where of course you'd need to account for gpu sharding as well.\r\n\r\n\r\nOtherwise, how did you implement worker/node/GPU sharding for iterable/streaming data where you do not have index information or prior splits (e.g. files)?", 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1620513876/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1620544051', 'html_url': 'https://github.com/huggingface/datasets/issues/5984#issuecomment-1620544051', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5984', 'id': 1620544051, 'node_id': 'IC_kwDODunzps5gl4oz', 'user': {'login': 'lhoestq', 'id': 42851186, 'node_id': 'MDQ6VXNlcjQyODUxMTg2', 'avatar_url': 'https://avatars.githubusercontent.com/u/42851186?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/lhoestq', 'html_url': 'https://github.com/lhoestq', 'followers_url': 'https://api.github.com/users/lhoestq/followers', 'following_url': 'https://api.github.com/users/lhoestq/following{/other_user}', 'gists_url': 'https://api.github.com/users/lhoestq/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/lhoestq/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/lhoestq/subscriptions', 'organizations_url': 'https://api.github.com/users/lhoestq/orgs', 'repos_url': 'https://api.github.com/users/lhoestq/repos', 'events_url': 'https://api.github.com/users/lhoestq/events{/privacy}', 'received_events_url': 'https://api.github.com/users/lhoestq/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-07-04T17:03:55Z', 'updated_at': '2023-07-04T17:03:55Z', 'author_association': 'MEMBER', 'body': '> For instance, using pyArrow, you could use RecordBatchStreamReader to zero-copy iterate over records with read_next_batch and then only initiate the next step for records modulo worker shard.\r\n\r\nThat works indeed ! And what we meant is that you can make it even faster to instantiate. Indeed using RecordBatchStreamReader you need to get the list of all the record batches in each worker, whereas you could just get the list of record batches per worker if you use the record batches locations in the Arrow IPC file footer. This would be especially appreciated to have a fast instantiation in case you have tens of thousands of Arrow files for example.', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1620544051/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}]

[]
[{'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1603492683', 'html_url': 'https://github.com/huggingface/datasets/issues/5982#issuecomment-1603492683', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5982', 'id': 1603492683, 'node_id': 'IC_kwDODunzps5fk1tL', 'user': {'login': 'abzdel', 'id': 55398496, 'node_id': 'MDQ6VXNlcjU1Mzk4NDk2', 'avatar_url': 'https://avatars.githubusercontent.com/u/55398496?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/abzdel', 'html_url': 'https://github.com/abzdel', 'followers_url': 'https://api.github.com/users/abzdel/followers', 'following_url': 'https://api.github.com/users/abzdel/following{/other_user}', 'gists_url': 'https://api.github.com/users/abzdel/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/abzdel/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/abzdel/subscriptions', 'organizations_url': 'https://api.github.com/users/abzdel/orgs', 'repos_url': 'https://api.github.com/users/abzdel/repos', 'events_url': 'https://api.github.com/users/abzdel/events{/privacy}', 'received_events_url': 'https://api.github.com/users/abzdel/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-23T01:01:39Z', 'updated_at': '2023-06-23T01:01:39Z', 'author_association': 'NONE', 'body': 'This wasn’t working for me a bit earlier, but it looks to be back up now', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1603492683/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1607748879', 'html_url': 'https://github.com/huggingface/datasets/issues/5982#issuecomment-1607748879', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5982', 'id': 1607748879, 'node_id': 'IC_kwDODunzps5f1E0P', 'user': {'login': 'mariosasko', 'id': 47462742, 'node_id': 'MDQ6VXNlcjQ3NDYyNzQy', 'avatar_url': 'https://avatars.githubusercontent.com/u/47462742?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/mariosasko', 'html_url': 'https://github.com/mariosasko', 'followers_url': 'https://api.github.com/users/mariosasko/followers', 'following_url': 'https://api.github.com/users/mariosasko/following{/other_user}', 'gists_url': 'https://api.github.com/users/mariosasko/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/mariosasko/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/mariosasko/subscriptions', 'organizations_url': 'https://api.github.com/users/mariosasko/orgs', 'repos_url': 'https://api.github.com/users/mariosasko/repos', 'events_url': 'https://api.github.com/users/mariosasko/events{/privacy}', 'received_events_url': 'https://api.github.com/users/mariosasko/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-26T15:44:55Z', 'updated_at': '2023-06-26T15:44:55Z', 'author_association': 'CONTRIBUTOR', 'body': 'We had a minor issue updating the docs after the latest release. It should work now :).', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1607748879/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}]
[{'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1607811182', 'html_url': 'https://github.com/huggingface/datasets/issues/5981#issuecomment-1607811182', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5981', 'id': 1607811182, 'node_id': 'IC_kwDODunzps5f1UBu', 'user': {'login': 'mariosasko', 'id': 47462742, 'node_id': 'MDQ6VXNlcjQ3NDYyNzQy', 'avatar_url': 'https://avatars.githubusercontent.com/u/47462742?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/mariosasko', 'html_url': 'https://github.com/mariosasko', 'followers_url': 'https://api.github.com/users/mariosasko/followers', 'following_url': 'https://api.github.com/users/mariosasko/following{/other_user}', 'gists_url': 'https://api.github.com/users/mariosasko/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/mariosasko/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/mariosasko/subscriptions', 'organizations_url': 'https://api.github.com/users/mariosasko/orgs', 'repos_url': 'https://api.github.com/users/mariosasko/repos', 'events_url': 'https://api.github.com/users/mariosasko/events{/privacy}', 'received_events_url': 'https://api.github.com/users/mariosasko/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-26T16:17:43Z', 'updated_at': '2023-06-26T16:19:40Z', 'author_association': 'CONTRIBUTOR', 'body': "I think it's more likely that this issue is related to PyTorch than Datasets, as PyTorch (on import) registers functions to execute when forking a process. Maybe this is the culprit: https://github.com/pytorch/pytorch/issues/99625", 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1607811182/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1608140952', 'html_url': 'https://github.com/huggingface/datasets/issues/5981#issuecomment-1608140952', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5981', 'id': 1608140952, 'node_id': 'IC_kwDODunzps5f2kiY', 'user': {'login': 'mmr-crexi', 'id': 107141022, 'node_id': 'U_kgDOBmLXng', 'avatar_url': 'https://avatars.githubusercontent.com/u/107141022?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/mmr-crexi', 'html_url': 'https://github.com/mmr-crexi', 'followers_url': 'https://api.github.com/users/mmr-crexi/followers', 'following_url': 'https://api.github.com/users/mmr-crexi/following{/other_user}', 'gists_url': 'https://api.github.com/users/mmr-crexi/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/mmr-crexi/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/mmr-crexi/subscriptions', 'organizations_url': 'https://api.github.com/users/mmr-crexi/orgs', 'repos_url': 'https://api.github.com/users/mmr-crexi/repos', 'events_url': 'https://api.github.com/users/mmr-crexi/events{/privacy}', 'received_events_url': 'https://api.github.com/users/mmr-crexi/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-26T19:53:47Z', 'updated_at': '2023-06-26T19:53:47Z', 'author_association': 'NONE', 'body': "From reading that ticket, it may be down in mkl?  Is it worth hotfixing in the meantime, with the express intention of turning it off?  I know that's a horribly crufty solution, but it's also deeply frustrating to be limited to 2 cores for operations as simple as filtration.", 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1608140952/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1624002338', 'html_url': 'https://github.com/huggingface/datasets/issues/5981#issuecomment-1624002338', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5981', 'id': 1624002338, 'node_id': 'IC_kwDODunzps5gzE8i', 'user': {'login': 'mariosasko', 'id': 47462742, 'node_id': 'MDQ6VXNlcjQ3NDYyNzQy', 'avatar_url': 'https://avatars.githubusercontent.com/u/47462742?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/mariosasko', 'html_url': 'https://github.com/mariosasko', 'followers_url': 'https://api.github.com/users/mariosasko/followers', 'following_url': 'https://api.github.com/users/mariosasko/following{/other_user}', 'gists_url': 'https://api.github.com/users/mariosasko/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/mariosasko/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/mariosasko/subscriptions', 'organizations_url': 'https://api.github.com/users/mariosasko/orgs', 'repos_url': 'https://api.github.com/users/mariosasko/repos', 'events_url': 'https://api.github.com/users/mariosasko/events{/privacy}', 'received_events_url': 'https://api.github.com/users/mariosasko/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-07-06T16:53:33Z', 'updated_at': '2023-07-06T16:53:33Z', 'author_association': 'CONTRIBUTOR', 'body': "This is too specific and unrelated to `datasets`, so this shouldn't be fixed here.", 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1624002338/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}]

[{'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1607442854', 'html_url': 'https://github.com/huggingface/datasets/issues/5980#issuecomment-1607442854', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5980', 'id': 1607442854, 'node_id': 'IC_kwDODunzps5fz6Gm', 'user': {'login': 'mariosasko', 'id': 47462742, 'node_id': 'MDQ6VXNlcjQ3NDYyNzQy', 'avatar_url': 'https://avatars.githubusercontent.com/u/47462742?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/mariosasko', 'html_url': 'https://github.com/mariosasko', 'followers_url': 'https://api.github.com/users/mariosasko/followers', 'following_url': 'https://api.github.com/users/mariosasko/following{/other_user}', 'gists_url': 'https://api.github.com/users/mariosasko/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/mariosasko/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/mariosasko/subscriptions', 'organizations_url': 'https://api.github.com/users/mariosasko/orgs', 'repos_url': 'https://api.github.com/users/mariosasko/repos', 'events_url': 'https://api.github.com/users/mariosasko/events{/privacy}', 'received_events_url': 'https://api.github.com/users/mariosasko/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-26T13:11:05Z', 'updated_at': '2023-06-26T13:11:05Z', 'author_association': 'CONTRIBUTOR', 'body': 'Can you try again? Maybe there was a minor outage.', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1607442854/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1607636780', 'html_url': 'https://github.com/huggingface/datasets/issues/5980#issuecomment-1607636780', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5980', 'id': 1607636780, 'node_id': 'IC_kwDODunzps5f0pcs', 'user': {'login': 'tbenthompson', 'id': 4241811, 'node_id': 'MDQ6VXNlcjQyNDE4MTE=', 'avatar_url': 'https://avatars.githubusercontent.com/u/4241811?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/tbenthompson', 'html_url': 'https://github.com/tbenthompson', 'followers_url': 'https://api.github.com/users/tbenthompson/followers', 'following_url': 'https://api.github.com/users/tbenthompson/following{/other_user}', 'gists_url': 'https://api.github.com/users/tbenthompson/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/tbenthompson/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/tbenthompson/subscriptions', 'organizations_url': 'https://api.github.com/users/tbenthompson/orgs', 'repos_url': 'https://api.github.com/users/tbenthompson/repos', 'events_url': 'https://api.github.com/users/tbenthompson/events{/privacy}', 'received_events_url': 'https://api.github.com/users/tbenthompson/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-26T14:42:45Z', 'updated_at': '2023-06-26T14:42:45Z', 'author_association': 'NONE', 'body': "Yes, it seems to be working now. In case it's helpful, the outage lasted several days. It was failing as late as yesterday morning. ", 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1607636780/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1609049454', 'html_url': 'https://github.com/huggingface/datasets/issues/5980#issuecomment-1609049454', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5980', 'id': 1609049454, 'node_id': 'IC_kwDODunzps5f6CVu', 'user': {'login': 'julien-c', 'id': 326577, 'node_id': 'MDQ6VXNlcjMyNjU3Nw==', 'avatar_url': 'https://avatars.githubusercontent.com/u/326577?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/julien-c', 'html_url': 'https://github.com/julien-c', 'followers_url': 'https://api.github.com/users/julien-c/followers', 'following_url': 'https://api.github.com/users/julien-c/following{/other_user}', 'gists_url': 'https://api.github.com/users/julien-c/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/julien-c/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/julien-c/subscriptions', 'organizations_url': 'https://api.github.com/users/julien-c/orgs', 'repos_url': 'https://api.github.com/users/julien-c/repos', 'events_url': 'https://api.github.com/users/julien-c/events{/privacy}', 'received_events_url': 'https://api.github.com/users/julien-c/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-27T08:38:19Z', 'updated_at': '2023-06-27T08:38:19Z', 'author_association': 'MEMBER', 'body': "we fixed something on the server side, glad it's fixed now", 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1609049454/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}]

[{'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1603128738', 'html_url': 'https://github.com/huggingface/datasets/pull/5978#issuecomment-1603128738', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5978', 'id': 1603128738, 'node_id': 'IC_kwDODunzps5fjc2i', 'user': {'login': 'HuggingFaceDocBuilderDev', 'id': 99929124, 'node_id': 'U_kgDOBfTMJA', 'avatar_url': 'https://avatars.githubusercontent.com/u/99929124?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/HuggingFaceDocBuilderDev', 'html_url': 'https://github.com/HuggingFaceDocBuilderDev', 'followers_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/followers', 'following_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/following{/other_user}', 'gists_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/subscriptions', 'organizations_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/orgs', 'repos_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/repos', 'events_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/events{/privacy}', 'received_events_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-22T18:28:14Z', 'updated_at': '2023-06-22T18:30:44Z', 'author_association': 'NONE', 'body': '_The documentation is not available anymore as the PR was closed or merged._', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1603128738/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1603130676', 'html_url': 'https://github.com/huggingface/datasets/pull/5978#issuecomment-1603130676', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5978', 'id': 1603130676, 'node_id': 'IC_kwDODunzps5fjdU0', 'user': {'login': 'github-actions[bot]', 'id': 41898282, 'node_id': 'MDM6Qm90NDE4OTgyODI=', 'avatar_url': 'https://avatars.githubusercontent.com/in/15368?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/github-actions%5Bbot%5D', 'html_url': 'https://github.com/apps/github-actions', 'followers_url': 'https://api.github.com/users/github-actions%5Bbot%5D/followers', 'following_url': 'https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}', 'gists_url': 'https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/github-actions%5Bbot%5D/subscriptions', 'organizations_url': 'https://api.github.com/users/github-actions%5Bbot%5D/orgs', 'repos_url': 'https://api.github.com/users/github-actions%5Bbot%5D/repos', 'events_url': 'https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}', 'received_events_url': 'https://api.github.com/users/github-actions%5Bbot%5D/received_events', 'type': 'Bot', 'site_admin': False}, 'created_at': '2023-06-22T18:29:56Z', 'updated_at': '2023-06-22T18:29:56Z', 'author_association': 'NONE', 'body': '<details>\n<summary>Show benchmarks</summary>\n\nPyArrow==8.0.0\n\n<details>\n<summary>Show updated benchmarks!</summary>\n\n### Benchmark: benchmark_array_xd.json\n\n| metric | read_batch_formatted_as_numpy after write_array2d | read_batch_formatted_as_numpy after write_flattened_sequence | read_batch_formatted_as_numpy after write_nested_sequence | read_batch_unformated after write_array2d | read_batch_unformated after write_flattened_sequence | read_batch_unformated after write_nested_sequence | read_col_formatted_as_numpy after write_array2d | read_col_formatted_as_numpy after write_flattened_sequence | read_col_formatted_as_numpy after write_nested_sequence | read_col_unformated after write_array2d | read_col_unformated after write_flattened_sequence | read_col_unformated after write_nested_sequence | read_formatted_as_numpy after write_array2d | read_formatted_as_numpy after write_flattened_sequence | read_formatted_as_numpy after write_nested_sequence | read_unformated after write_array2d | read_unformated after write_flattened_sequence | read_unformated after write_nested_sequence | write_array2d | write_flattened_sequence | write_nested_sequence |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.006173 / 0.011353 (-0.005180) | 0.003773 / 0.011008 (-0.007235) | 0.099499 / 0.038508 (0.060991) | 0.037918 / 0.023109 (0.014809) | 0.321329 / 0.275898 (0.045431) | 0.379739 / 0.323480 (0.056259) | 0.004664 / 0.007986 (-0.003322) | 0.002943 / 0.004328 (-0.001385) | 0.077759 / 0.004250 (0.073509) | 0.055271 / 0.037052 (0.018219) | 0.329428 / 0.258489 (0.070939) | 0.378731 / 0.293841 (0.084890) | 0.027737 / 0.128546 (-0.100810) | 0.008566 / 0.075646 (-0.067081) | 0.313220 / 0.419271 (-0.106052) | 0.047101 / 0.043533 (0.003568) | 0.316211 / 0.255139 (0.061072) | 0.341826 / 0.283200 (0.058626) | 0.020838 / 0.141683 (-0.120845) | 1.550064 / 1.452155 (0.097909) | 1.706518 / 1.492716 (0.213801) |\n\n### Benchmark: benchmark_getitem\\_100B.json\n\n| metric | get_batch_of\\_1024\\_random_rows | get_batch_of\\_1024\\_rows | get_first_row | get_last_row |\n|--------|---|---|---|---|\n| new / old (diff) | 0.203093 / 0.018006 (0.185087) | 0.425345 / 0.000490 (0.424856) | 0.004800 / 0.000200 (0.004600) | 0.000077 / 0.000054 (0.000022) |\n\n### Benchmark: benchmark_indices_mapping.json\n\n| metric | select | shard | shuffle | sort | train_test_split |\n|--------|---|---|---|---|---|\n| new / old (diff) | 0.024590 / 0.037411 (-0.012821) | 0.098115 / 0.014526 (0.083589) | 0.108274 / 0.176557 (-0.068282) | 0.170804 / 0.737135 (-0.566332) | 0.110560 / 0.296338 (-0.185778) |\n\n### Benchmark: benchmark_iterating.json\n\n| metric | read 5000 | read 50000 | read_batch 50000 10 | read_batch 50000 100 | read_batch 50000 1000 | read_formatted numpy 5000 | read_formatted pandas 5000 | read_formatted tensorflow 5000 | read_formatted torch 5000 | read_formatted_batch numpy 5000 10 | read_formatted_batch numpy 5000 1000 | shuffled read 5000 | shuffled read 50000 | shuffled read_batch 50000 10 | shuffled read_batch 50000 100 | shuffled read_batch 50000 1000 | shuffled read_formatted numpy 5000 | shuffled read_formatted_batch numpy 5000 10 | shuffled read_formatted_batch numpy 5000 1000 |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.425251 / 0.215209 (0.210042) | 4.239075 / 2.077655 (2.161421) | 1.955601 / 1.504120 (0.451481) | 1.774796 / 1.541195 (0.233602) | 1.826641 / 1.468490 (0.358150) | 0.558777 / 4.584777 (-4.026000) | 3.361697 / 3.745712 (-0.384015) | 1.764468 / 5.269862 (-3.505394) | 1.032280 / 4.565676 (-3.533396) | 0.067872 / 0.424275 (-0.356403) | 0.010998 / 0.007607 (0.003391) | 0.525682 / 0.226044 (0.299637) | 5.254356 / 2.268929 (2.985427) | 2.384332 / 55.444624 (-53.060292) | 2.045578 / 6.876477 (-4.830898) | 2.170914 / 2.142072 (0.028841) | 0.674782 / 4.805227 (-4.130445) | 0.135351 / 6.500664 (-6.365314) | 0.066591 / 0.075469 (-0.008878) |\n\n### Benchmark: benchmark_map_filter.json\n\n| metric | filter | map fast-tokenizer batched | map identity | map identity batched | map no-op batched | map no-op batched numpy | map no-op batched pandas | map no-op batched pytorch | map no-op batched tensorflow |\n|--------|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 1.209181 / 1.841788 (-0.632606) | 14.044518 / 8.074308 (5.970210) | 13.184705 / 10.191392 (2.993313) | 0.130836 / 0.680424 (-0.549588) | 0.016582 / 0.534201 (-0.517619) | 0.360005 / 0.579283 (-0.219279) | 0.379519 / 0.434364 (-0.054845) | 0.422174 / 0.540337 (-0.118164) | 0.515546 / 1.386936 (-0.871390) |\n\n</details>\nPyArrow==latest\n\n<details>\n<summary>Show updated benchmarks!</summary>\n\n### Benchmark: benchmark_array_xd.json\n\n| metric | read_batch_formatted_as_numpy after write_array2d | read_batch_formatted_as_numpy after write_flattened_sequence | read_batch_formatted_as_numpy after write_nested_sequence | read_batch_unformated after write_array2d | read_batch_unformated after write_flattened_sequence | read_batch_unformated after write_nested_sequence | read_col_formatted_as_numpy after write_array2d | read_col_formatted_as_numpy after write_flattened_sequence | read_col_formatted_as_numpy after write_nested_sequence | read_col_unformated after write_array2d | read_col_unformated after write_flattened_sequence | read_col_unformated after write_nested_sequence | read_formatted_as_numpy after write_array2d | read_formatted_as_numpy after write_flattened_sequence | read_formatted_as_numpy after write_nested_sequence | read_unformated after write_array2d | read_unformated after write_flattened_sequence | read_unformated after write_nested_sequence | write_array2d | write_flattened_sequence | write_nested_sequence |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.006293 / 0.011353 (-0.005060) | 0.003784 / 0.011008 (-0.007224) | 0.079248 / 0.038508 (0.040739) | 0.038452 / 0.023109 (0.015343) | 0.444727 / 0.275898 (0.168829) | 0.500535 / 0.323480 (0.177055) | 0.003455 / 0.007986 (-0.004531) | 0.002873 / 0.004328 (-0.001455) | 0.077439 / 0.004250 (0.073189) | 0.047855 / 0.037052 (0.010803) | 0.448049 / 0.258489 (0.189560) | 0.509517 / 0.293841 (0.215676) | 0.028359 / 0.128546 (-0.100188) | 0.008503 / 0.075646 (-0.067143) | 0.084961 / 0.419271 (-0.334310) | 0.042880 / 0.043533 (-0.000653) | 0.436628 / 0.255139 (0.181489) | 0.456574 / 0.283200 (0.173375) | 0.019539 / 0.141683 (-0.122144) | 1.561273 / 1.452155 (0.109118) | 1.572018 / 1.492716 (0.079301) |\n\n### Benchmark: benchmark_getitem\\_100B.json\n\n| metric | get_batch_of\\_1024\\_random_rows | get_batch_of\\_1024\\_rows | get_first_row | get_last_row |\n|--------|---|---|---|---|\n| new / old (diff) | 0.230250 / 0.018006 (0.212244) | 0.415189 / 0.000490 (0.414700) | 0.003213 / 0.000200 (0.003013) | 0.000080 / 0.000054 (0.000026) |\n\n### Benchmark: benchmark_indices_mapping.json\n\n| metric | select | shard | shuffle | sort | train_test_split |\n|--------|---|---|---|---|---|\n| new / old (diff) | 0.025541 / 0.037411 (-0.011871) | 0.102326 / 0.014526 (0.087800) | 0.110258 / 0.176557 (-0.066298) | 0.162488 / 0.737135 (-0.574647) | 0.112782 / 0.296338 (-0.183556) |\n\n### Benchmark: benchmark_iterating.json\n\n| metric | read 5000 | read 50000 | read_batch 50000 10 | read_batch 50000 100 | read_batch 50000 1000 | read_formatted numpy 5000 | read_formatted pandas 5000 | read_formatted tensorflow 5000 | read_formatted torch 5000 | read_formatted_batch numpy 5000 10 | read_formatted_batch numpy 5000 1000 | shuffled read 5000 | shuffled read 50000 | shuffled read_batch 50000 10 | shuffled read_batch 50000 100 | shuffled read_batch 50000 1000 | shuffled read_formatted numpy 5000 | shuffled read_formatted_batch numpy 5000 10 | shuffled read_formatted_batch numpy 5000 1000 |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.457936 / 0.215209 (0.242727) | 4.581503 / 2.077655 (2.503848) | 2.237659 / 1.504120 (0.733540) | 2.029960 / 1.541195 (0.488765) | 2.082911 / 1.468490 (0.614421) | 0.556485 / 4.584777 (-4.028292) | 3.384418 / 3.745712 (-0.361295) | 1.748809 / 5.269862 (-3.521053) | 1.034759 / 4.565676 (-3.530917) | 0.067500 / 0.424275 (-0.356776) | 0.011425 / 0.007607 (0.003818) | 0.561340 / 0.226044 (0.335295) | 5.623629 / 2.268929 (3.354701) | 2.733587 / 55.444624 (-52.711038) | 2.401578 / 6.876477 (-4.474899) | 2.524569 / 2.142072 (0.382496) | 0.673170 / 4.805227 (-4.132057) | 0.136681 / 6.500664 (-6.363983) | 0.068060 / 0.075469 (-0.007409) |\n\n### Benchmark: benchmark_map_filter.json\n\n| metric | filter | map fast-tokenizer batched | map identity | map identity batched | map no-op batched | map no-op batched numpy | map no-op batched pandas | map no-op batched pytorch | map no-op batched tensorflow |\n|--------|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 1.318651 / 1.841788 (-0.523137) | 14.362123 / 8.074308 (6.287815) | 14.385964 / 10.191392 (4.194572) | 0.149914 / 0.680424 (-0.530510) | 0.016877 / 0.534201 (-0.517324) | 0.358406 / 0.579283 (-0.220877) | 0.394349 / 0.434364 (-0.040015) | 0.422471 / 0.540337 (-0.117866) | 0.513807 / 1.386936 (-0.873129) |\n\n</details>\n</details>\n\n![](https://cml.dev/watermark.png#1b9ce11d1b94e6178df663ff5fcad029849d10fb "CML watermark")\n', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1603130676/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1603138535', 'html_url': 'https://github.com/huggingface/datasets/pull/5978#issuecomment-1603138535', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5978', 'id': 1603138535, 'node_id': 'IC_kwDODunzps5fjfPn', 'user': {'login': 'github-actions[bot]', 'id': 41898282, 'node_id': 'MDM6Qm90NDE4OTgyODI=', 'avatar_url': 'https://avatars.githubusercontent.com/in/15368?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/github-actions%5Bbot%5D', 'html_url': 'https://github.com/apps/github-actions', 'followers_url': 'https://api.github.com/users/github-actions%5Bbot%5D/followers', 'following_url': 'https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}', 'gists_url': 'https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/github-actions%5Bbot%5D/subscriptions', 'organizations_url': 'https://api.github.com/users/github-actions%5Bbot%5D/orgs', 'repos_url': 'https://api.github.com/users/github-actions%5Bbot%5D/repos', 'events_url': 'https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}', 'received_events_url': 'https://api.github.com/users/github-actions%5Bbot%5D/received_events', 'type': 'Bot', 'site_admin': False}, 'created_at': '2023-06-22T18:37:13Z', 'updated_at': '2023-06-22T18:37:13Z', 'author_association': 'NONE', 'body': '<details>\n<summary>Show benchmarks</summary>\n\nPyArrow==8.0.0\n\n<details>\n<summary>Show updated benchmarks!</summary>\n\n### Benchmark: benchmark_array_xd.json\n\n| metric | read_batch_formatted_as_numpy after write_array2d | read_batch_formatted_as_numpy after write_flattened_sequence | read_batch_formatted_as_numpy after write_nested_sequence | read_batch_unformated after write_array2d | read_batch_unformated after write_flattened_sequence | read_batch_unformated after write_nested_sequence | read_col_formatted_as_numpy after write_array2d | read_col_formatted_as_numpy after write_flattened_sequence | read_col_formatted_as_numpy after write_nested_sequence | read_col_unformated after write_array2d | read_col_unformated after write_flattened_sequence | read_col_unformated after write_nested_sequence | read_formatted_as_numpy after write_array2d | read_formatted_as_numpy after write_flattened_sequence | read_formatted_as_numpy after write_nested_sequence | read_unformated after write_array2d | read_unformated after write_flattened_sequence | read_unformated after write_nested_sequence | write_array2d | write_flattened_sequence | write_nested_sequence |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.006272 / 0.011353 (-0.005080) | 0.003903 / 0.011008 (-0.007105) | 0.100180 / 0.038508 (0.061672) | 0.037799 / 0.023109 (0.014690) | 0.385627 / 0.275898 (0.109729) | 0.446518 / 0.323480 (0.123038) | 0.004811 / 0.007986 (-0.003175) | 0.003032 / 0.004328 (-0.001296) | 0.077063 / 0.004250 (0.072812) | 0.055564 / 0.037052 (0.018512) | 0.397346 / 0.258489 (0.138857) | 0.443242 / 0.293841 (0.149401) | 0.027904 / 0.128546 (-0.100642) | 0.008386 / 0.075646 (-0.067260) | 0.315013 / 0.419271 (-0.104259) | 0.047943 / 0.043533 (0.004410) | 0.378443 / 0.255139 (0.123304) | 0.411472 / 0.283200 (0.128272) | 0.020465 / 0.141683 (-0.121218) | 1.526594 / 1.452155 (0.074439) | 1.547018 / 1.492716 (0.054301) |\n\n### Benchmark: benchmark_getitem\\_100B.json\n\n| metric | get_batch_of\\_1024\\_random_rows | get_batch_of\\_1024\\_rows | get_first_row | get_last_row |\n|--------|---|---|---|---|\n| new / old (diff) | 0.219377 / 0.018006 (0.201370) | 0.430254 / 0.000490 (0.429764) | 0.003218 / 0.000200 (0.003018) | 0.000072 / 0.000054 (0.000017) |\n\n### Benchmark: benchmark_indices_mapping.json\n\n| metric | select | shard | shuffle | sort | train_test_split |\n|--------|---|---|---|---|---|\n| new / old (diff) | 0.023667 / 0.037411 (-0.013744) | 0.099143 / 0.014526 (0.084617) | 0.106044 / 0.176557 (-0.070513) | 0.166186 / 0.737135 (-0.570949) | 0.108736 / 0.296338 (-0.187603) |\n\n### Benchmark: benchmark_iterating.json\n\n| metric | read 5000 | read 50000 | read_batch 50000 10 | read_batch 50000 100 | read_batch 50000 1000 | read_formatted numpy 5000 | read_formatted pandas 5000 | read_formatted tensorflow 5000 | read_formatted torch 5000 | read_formatted_batch numpy 5000 10 | read_formatted_batch numpy 5000 1000 | shuffled read 5000 | shuffled read 50000 | shuffled read_batch 50000 10 | shuffled read_batch 50000 100 | shuffled read_batch 50000 1000 | shuffled read_formatted numpy 5000 | shuffled read_formatted_batch numpy 5000 10 | shuffled read_formatted_batch numpy 5000 1000 |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.437971 / 0.215209 (0.222762) | 4.363675 / 2.077655 (2.286021) | 2.011993 / 1.504120 (0.507873) | 1.845189 / 1.541195 (0.303994) | 1.831848 / 1.468490 (0.363358) | 0.562402 / 4.584777 (-4.022375) | 3.365259 / 3.745712 (-0.380453) | 1.781491 / 5.269862 (-3.488371) | 1.023454 / 4.565676 (-3.542223) | 0.067857 / 0.424275 (-0.356418) | 0.011076 / 0.007607 (0.003469) | 0.532267 / 0.226044 (0.306223) | 5.340344 / 2.268929 (3.071415) | 2.388649 / 55.444624 (-53.055976) | 2.055373 / 6.876477 (-4.821104) | 2.205047 / 2.142072 (0.062975) | 0.672909 / 4.805227 (-4.132318) | 0.135244 / 6.500664 (-6.365420) | 0.066184 / 0.075469 (-0.009285) |\n\n### Benchmark: benchmark_map_filter.json\n\n| metric | filter | map fast-tokenizer batched | map identity | map identity batched | map no-op batched | map no-op batched numpy | map no-op batched pandas | map no-op batched pytorch | map no-op batched tensorflow |\n|--------|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 1.206838 / 1.841788 (-0.634950) | 13.967075 / 8.074308 (5.892767) | 13.143971 / 10.191392 (2.952579) | 0.143991 / 0.680424 (-0.536433) | 0.016673 / 0.534201 (-0.517527) | 0.376180 / 0.579283 (-0.203103) | 0.386550 / 0.434364 (-0.047814) | 0.440590 / 0.540337 (-0.099747) | 0.529974 / 1.386936 (-0.856962) |\n\n</details>\nPyArrow==latest\n\n<details>\n<summary>Show updated benchmarks!</summary>\n\n### Benchmark: benchmark_array_xd.json\n\n| metric | read_batch_formatted_as_numpy after write_array2d | read_batch_formatted_as_numpy after write_flattened_sequence | read_batch_formatted_as_numpy after write_nested_sequence | read_batch_unformated after write_array2d | read_batch_unformated after write_flattened_sequence | read_batch_unformated after write_nested_sequence | read_col_formatted_as_numpy after write_array2d | read_col_formatted_as_numpy after write_flattened_sequence | read_col_formatted_as_numpy after write_nes

[{'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1602969800', 'html_url': 'https://github.com/huggingface/datasets/pull/5976#issuecomment-1602969800', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5976', 'id': 1602969800, 'node_id': 'IC_kwDODunzps5fi2DI', 'user': {'login': 'lhoestq', 'id': 42851186, 'node_id': 'MDQ6VXNlcjQyODUxMTg2', 'avatar_url': 'https://avatars.githubusercontent.com/u/42851186?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/lhoestq', 'html_url': 'https://github.com/lhoestq', 'followers_url': 'https://api.github.com/users/lhoestq/followers', 'following_url': 'https://api.github.com/users/lhoestq/following{/other_user}', 'gists_url': 'https://api.github.com/users/lhoestq/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/lhoestq/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/lhoestq/subscriptions', 'organizations_url': 'https://api.github.com/users/lhoestq/orgs', 'repos_url': 'https://api.github.com/users/lhoestq/repos', 'events_url': 'https://api.github.com/users/lhoestq/events{/privacy}', 'received_events_url': 'https://api.github.com/users/lhoestq/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-22T16:24:35Z', 'updated_at': '2023-06-22T16:24:35Z', 'author_association': 'MEMBER', 'body': 'Hi ! Do you think this can be fixed at the Pool level ? Ideally it should be the Pool responsibility to handle this, not the `map` code. We could even subclass Pool if needed (at least the one from `multiprocess`)', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1602969800/reactions', 'total_count': 1, '+1': 1, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1606119332', 'html_url': 'https://github.com/huggingface/datasets/pull/5976#issuecomment-1606119332', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5976', 'id': 1606119332, 'node_id': 'IC_kwDODunzps5fu2-k', 'user': {'login': 'pappacena', 'id': 1213561, 'node_id': 'MDQ6VXNlcjEyMTM1NjE=', 'avatar_url': 'https://avatars.githubusercontent.com/u/1213561?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/pappacena', 'html_url': 'https://github.com/pappacena', 'followers_url': 'https://api.github.com/users/pappacena/followers', 'following_url': 'https://api.github.com/users/pappacena/following{/other_user}', 'gists_url': 'https://api.github.com/users/pappacena/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/pappacena/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/pappacena/subscriptions', 'organizations_url': 'https://api.github.com/users/pappacena/orgs', 'repos_url': 'https://api.github.com/users/pappacena/repos', 'events_url': 'https://api.github.com/users/pappacena/events{/privacy}', 'received_events_url': 'https://api.github.com/users/pappacena/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-25T14:48:23Z', 'updated_at': '2023-06-25T14:48:23Z', 'author_association': 'CONTRIBUTOR', 'body': '@lhoestq it makes sense to me. Just pushed a refactoring creating a `class ProcessPool(multiprocess.pool.Pool)` to keep track of the PID changes.', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1606119332/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1607198049', 'html_url': 'https://github.com/huggingface/datasets/pull/5976#issuecomment-1607198049', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5976', 'id': 1607198049, 'node_id': 'IC_kwDODunzps5fy-Vh', 'user': {'login': 'HuggingFaceDocBuilderDev', 'id': 99929124, 'node_id': 'U_kgDOBfTMJA', 'avatar_url': 'https://avatars.githubusercontent.com/u/99929124?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/HuggingFaceDocBuilderDev', 'html_url': 'https://github.com/HuggingFaceDocBuilderDev', 'followers_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/followers', 'following_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/following{/other_user}', 'gists_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/subscriptions', 'organizations_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/orgs', 'repos_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/repos', 'events_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/events{/privacy}', 'received_events_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-26T10:46:58Z', 'updated_at': '2023-07-10T09:50:40Z', 'author_association': 'NONE', 'body': '_The documentation is not available anymore as the PR was closed or merged._', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1607198049/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1607366435', 'html_url': 'https://github.com/huggingface/datasets/pull/5976#issuecomment-1607366435', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5976', 'id': 1607366435, 'node_id': 'IC_kwDODunzps5fzncj', 'user': {'login': 'lhoestq', 'id': 42851186, 'node_id': 'MDQ6VXNlcjQyODUxMTg2', 'avatar_url': 'https://avatars.githubusercontent.com/u/42851186?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/lhoestq', 'html_url': 'https://github.com/lhoestq', 'followers_url': 'https://api.github.com/users/lhoestq/followers', 'following_url': 'https://api.github.com/users/lhoestq/following{/other_user}', 'gists_url': 'https://api.github.com/users/lhoestq/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/lhoestq/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/lhoestq/subscriptions', 'organizations_url': 'https://api.github.com/users/lhoestq/orgs', 'repos_url': 'https://api.github.com/users/lhoestq/repos', 'events_url': 'https://api.github.com/users/lhoestq/events{/privacy}', 'received_events_url': 'https://api.github.com/users/lhoestq/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-26T12:25:28Z', 'updated_at': '2023-06-26T12:27:27Z', 'author_association': 'MEMBER', 'body': 'I managed to raise an error without subclassing Pool with two additions to `iflatmap_unordered`:\r\n\r\n1. at the beggining\r\n```python\r\noriginal_pool = list(pool._pool)\r\n```\r\n\r\n2. in the loop\r\n```python\r\nif any(async_result._pool != original_pool for async_result in async_results) and queue.empty():\r\n    raise RuntimeError(\r\n        "One of the subprocesses has abruptly died during map operation."\r\n        "To debug the error, disable multiprocessing."\r\n    )\r\n```\r\n\r\nIt\'s still a fix that only works for `iflatmap_unordered` (so not for map, imap etc) but is maybe simpler that subclassing. It also works for both multiprocessing.Pool and multiprocess.Pool', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1607366435/reactions', 'total_count': 1, '+1': 1, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1622608115', 'html_url': 'https://github.com/huggingface/datasets/pull/5976#issuecomment-1622608115', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5976', 'id': 1622608115, 'node_id': 'IC_kwDODunzps5gtwjz', 'user': {'login': 'pappacena', 'id': 1213561, 'node_id': 'MDQ6VXNlcjEyMTM1NjE=', 'avatar_url': 'https://avatars.githubusercontent.com/u/1213561?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/pappacena', 'html_url': 'https://github.com/pappacena', 'followers_url': 'https://api.github.com/users/pappacena/followers', 'following_url': 'https://api.github.com/users/pappacena/following{/other_user}', 'gists_url': 'https://api.github.com/users/pappacena/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/pappacena/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/pappacena/subscriptions', 'organizations_url': 'https://api.github.com/users/pappacena/orgs', 'repos_url': 'https://api.github.com/users/pappacena/repos', 'events_url': 'https://api.github.com/users/pappacena/events{/privacy}', 'received_events_url': 'https://api.github.com/users/pappacena/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-07-05T22:21:37Z', 'updated_at': '2023-07-05T22:21:37Z', 'author_association': 'CONTRIBUTOR', 'body': '@lhoestq sorry for the delay. Busy weeks here. \r\n\r\nI just pushed the change you requested. It looks closer to the original proposal, actually.\r\n\r\nIt seems that `map` actually uses `iflatmap_unordered` ([here](https://github.com/huggingface/datasets/blob/819bb4346434912eb405ce3f3e9f21dc25a2fe85/src/datasets/arrow_dataset.py#L1509)). I think this solution works fine for the `map` method (which is the one being tested by the new `tests/test_arrow_dataset.py::BaseDatasetTest::test_map_crash_subprocess`, right?).', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1622608115/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1623363297', 'html_url': 'https://github.com/huggingface/datasets/pull/5976#issuecomment-1623363297', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5976', 'id': 1623363297, 'node_id': 'IC_kwDODunzps5gwo7h', 'user': {'login': 'lhoestq', 'id': 42851186, 'node_id': 'MDQ6VXNlcjQyODUxMTg2', 'avatar_url': 'https://avatars.githubusercontent.com/u/42851186?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/lhoestq', 'html_url': 'https://github.com/lhoestq', 'followers_url': 'https://api.github.com/users/lhoestq/followers', 'following_url': 'https://api.github.com/users/lhoestq/following{/other_user}', 'gists_url': 'https://api.github.com/users/lhoestq/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/lhoestq/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/lhoestq/subscriptions', 'organizations_url': 'https://api.github.com/users/lhoestq/orgs', 'repos_url': 'https://api.github.com/users/lhoestq/repos', 'events_url': 'https://api.github.com/users/lhoestq/events{/privacy}', 'received_events_url': 'https://api.github.com/users/lhoestq/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-07-06T09:42:44Z', 'updated_at': '2023-07-06T09:42:44Z', 'author_association': 'MEMBER', 'body': "Yes fixing iflatmap_unordered does fix Dataset.map, but it won't fix any Pool.map that we may use elsewhere so we'll have to keep this in mind.", 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1623363297/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1623417396', 'html_url': 'https://github.com/huggingface/datasets/pull/5976#issuecomment-1623417396', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5976', 'id': 1623417396, 'node_id': 'IC_kwDODunzps5gw2I0', 'user': {'login': 'lhoestq', 'id': 42851186, 'node_id': 'MDQ6VXNlcjQyODUxMTg2', 'avatar_url': 'https://avatars.githubusercontent.com/u/42851186?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/lhoestq', 'html_url': 'https://github.com/lhoestq', 'followers_url': 'https://api.github.com/users/lhoestq/followers', 'following_url': 'https://api.github.com/users/lhoestq/following{/other_user}', 'gists_url': 'https://api.github.com/users/lhoestq/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/lhoestq/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/lhoestq/subscriptions', 'organizations_url': 'https://api.github.com/users/lhoestq/orgs', 'repos_url': 'https://api.github.com/users/lhoestq/repos', 'events_url': 'https://api.github.com/users/lhoestq/events{/privacy}', 'received_events_url': 'https://api.github.com/users/lhoestq/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-07-06T10:20:47Z', 'updated_at': '2023-07-06T10:20:47Z', 'author_association': 'MEMBER', 'body': 'It looks all good to me, feel free to fix code formatting by running `make style` and we can merge :)', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1623417396/reactions', 'total_count': 1, '+1': 1, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1623652642', 'html_url': 'https://github.com/huggingface/datasets/pull/5976#issuecomment-1623652642', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5976', 'id': 1623652642, 'node_id': 'IC_kwDODunzps5gxvki', 'user': {'login': 'pappacena', 'id': 1213561, 'node_id': 'MDQ6VXNlcjEyMTM1NjE=', 'avatar_url': 'https://avatars.githubusercontent.com/u/1213561?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/pappacena', 'html_url': 'https://github.com/pappacena', 'followers_url': 'https://api.github.com/users/pappacena/followers', 'following_url': 'https://api.github.com/users/pappacena/following{/other_user}', 'gists_url': 'https://api.github.com/users/pappacena/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/pappacena/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/pappacena/subscriptions', 'organizations_url': 'https://api.github.com/users/pappacena/orgs', 'repos_url': 'https://api.github.com/users/pappacena/repos', 'events_url': 'https://api.github.com/users/pappacena/events{/privacy}', 'received_events_url': 'https://api.github.com/users/pappacena/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-07-06T13:09:11Z', 'updated_at': '2023-07-06T13:09:11Z', 'author_association': 'CONTRIBUTOR', 'body': "> Yes fixing iflatmap_unordered does fix Dataset.map, but it won't fix any Pool.map that we may use elsewhere so we'll have to keep this in mind.\r\n\r\nRight, I agree. The best way moving forward is probably not using the buggy `multiprocess.Pool` anymore, and replace it with `concurrent.futures.ProcessPoolExecutor` as much as possible.\r\n\r\nAnyway, I've run `make style` now. Thanks for the support!", 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1623652642/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1623863963', 'html_url': 'https://github.com/huggingface/datasets/pull/5976#issuecomment-1623863963', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5976', 'id': 1623863963, 'node_id': 'IC_kwDODunzps5gyjKb', 'user': {'login': 'lhoestq', 'id': 42851186, 'node_id': 'MDQ6VXNlcjQyODUxMTg2', 'avatar_url': 'https://avatars.githubusercontent.com/u/42851186?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/lhoestq', 'html_url': 'https://github.com/lhoestq', 'followers_url': 'https://api.github.com/users/lhoestq/followers', 'following_url': 'https://api.github.com/users/lhoestq/following{/other_user}', 'gists_url': 'https://api.github.com/users/lhoestq/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/lhoestq/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/lhoestq/subscriptions', 'organizations_url': 'https://api.github.com/users/lhoestq/orgs', 'repos_url': 'https://api.github.com/users/lhoestq/repos', 'events_url': 'https://api.github.com/users/lhoestq/events{/privacy}', 'received_events_url': 'https://api.github.com/users/lhoestq/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-07-06T15:17:14Z', 'updated_at': '2023-07-06T15:17:14Z', 'author_association': 'MEMBER', 'body': "It looks like checking the async_result._pool doesn't always work - sorry about that. We might just go back to your original solution then. Would also be cool to open an issue in `multiprocess` to ask if they have a solution or if they plan to fix this.", 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1623863963/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1624454056', 'html_url': 'https://github.com/huggingface/datasets/pull/5976#issuecomment-1624454056', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5976', 'id': 1624454056, 'node_id': 'IC_kwDODunzps5g0zOo', 'user': {'login': 'pappacena', 'id': 1213561, 'node_id': 'MDQ6VXNlcjEyMTM1NjE=', 'avatar_url': 'https://avatars.githubusercontent.com/u/1213561?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/pappacena', 'html_url': 'https://github.com/pappacena', 'followers_url': 'https://api.github.com/users/pappacena/followers', 'following_url': 'https://api.github.com/users/pappacena/following{/other_user}', 'gists_url': 'https://api.github.com/users/pappacena/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/pappacena/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/pappacena/subscriptions', 'organizations_url': 'https://api.github.com/users/pappacena/orgs', 'repos_url': 'https://api.github.com/users/pappacena/repos', 'events_url': 'https://api.github.com/users/pappacena/events{/privacy}', 'received_events_url': 'https://api.github.com/users/pappacena/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-07-07T00:03:47Z', 'updated_at': '2023-07-07T00:03:47Z', 'author_association': 'CONTRIBUTOR', 'body': "@lhoestq no problem! Reverted to the previous version.\r\n\r\nTBH, given the discussions [in this python issue](https://github.com/python/cpython/issues/66587), I don't think the error in `multiprocess` will be merged upstream any time soon...", 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1624454056/reactions', 'total_count': 1, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 1, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1628626592', 'html_url': 'https://github.com/huggingface/datasets/pull/5976#issuecomment-1628626592', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5976', 'id': 1628626592, 'node_id': 'IC_kwDODunzps5hEt6g', 'user': {'login': 'github-actions[bot]', 'id': 41898282, 'node_id': 'MDM6Qm90NDE4OTgyODI=', 'avatar_url': 'https://avatars.githubusercontent.com/in/15368?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/github-actions%5Bbot%5D', 'html_url': 'https://github.com/apps/github-actions', 'followers_url': 'https://api.github.com/use

[{'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1601738997', 'html_url': 'https://github.com/huggingface/datasets/issues/5975#issuecomment-1601738997', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5975', 'id': 1601738997, 'node_id': 'IC_kwDODunzps5feJj1', 'user': {'login': 'Krystianp00000', 'id': 88916743, 'node_id': 'MDQ6VXNlcjg4OTE2NzQz', 'avatar_url': 'https://avatars.githubusercontent.com/u/88916743?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/Krystianp00000', 'html_url': 'https://github.com/Krystianp00000', 'followers_url': 'https://api.github.com/users/Krystianp00000/followers', 'following_url': 'https://api.github.com/users/Krystianp00000/following{/other_user}', 'gists_url': 'https://api.github.com/users/Krystianp00000/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/Krystianp00000/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/Krystianp00000/subscriptions', 'organizations_url': 'https://api.github.com/users/Krystianp00000/orgs', 'repos_url': 'https://api.github.com/users/Krystianp00000/repos', 'events_url': 'https://api.github.com/users/Krystianp00000/events{/privacy}', 'received_events_url': 'https://api.github.com/users/Krystianp00000/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-21T22:02:05Z', 'updated_at': '2023-06-21T22:02:05Z', 'author_association': 'NONE', 'body': 'Duplicate of #', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1601738997/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1602739485', 'html_url': 'https://github.com/huggingface/datasets/issues/5975#issuecomment-1602739485', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5975', 'id': 1602739485, 'node_id': 'IC_kwDODunzps5fh90d', 'user': {'login': 'lhoestq', 'id': 42851186, 'node_id': 'MDQ6VXNlcjQyODUxMTg2', 'avatar_url': 'https://avatars.githubusercontent.com/u/42851186?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/lhoestq', 'html_url': 'https://github.com/lhoestq', 'followers_url': 'https://api.github.com/users/lhoestq/followers', 'following_url': 'https://api.github.com/users/lhoestq/following{/other_user}', 'gists_url': 'https://api.github.com/users/lhoestq/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/lhoestq/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/lhoestq/subscriptions', 'organizations_url': 'https://api.github.com/users/lhoestq/orgs', 'repos_url': 'https://api.github.com/users/lhoestq/repos', 'events_url': 'https://api.github.com/users/lhoestq/events{/privacy}', 'received_events_url': 'https://api.github.com/users/lhoestq/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-22T14:27:08Z', 'updated_at': '2023-06-22T14:27:08Z', 'author_association': 'MEMBER', 'body': 'Hi ! can you try to set the upper case environment variables `HTTP_PROXY` and `HTTPS_PROXY` ?\r\n\r\nWe use `aiohttp` for streaming and it uses case sensitive environment variables', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1602739485/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1607244302', 'html_url': 'https://github.com/huggingface/datasets/issues/5975#issuecomment-1607244302', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5975', 'id': 1607244302, 'node_id': 'IC_kwDODunzps5fzJoO', 'user': {'login': 'Veluchs', 'id': 135350576, 'node_id': 'U_kgDOCBFJMA', 'avatar_url': 'https://avatars.githubusercontent.com/u/135350576?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/Veluchs', 'html_url': 'https://github.com/Veluchs', 'followers_url': 'https://api.github.com/users/Veluchs/followers', 'following_url': 'https://api.github.com/users/Veluchs/following{/other_user}', 'gists_url': 'https://api.github.com/users/Veluchs/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/Veluchs/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/Veluchs/subscriptions', 'organizations_url': 'https://api.github.com/users/Veluchs/orgs', 'repos_url': 'https://api.github.com/users/Veluchs/repos', 'events_url': 'https://api.github.com/users/Veluchs/events{/privacy}', 'received_events_url': 'https://api.github.com/users/Veluchs/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-26T11:12:30Z', 'updated_at': '2023-06-26T11:12:30Z', 'author_association': 'NONE', 'body': 'Hi, thanks for the quick reply.\r\n\r\nI set the uppercase env variables with\r\n\r\n`\r\nos.environ[\'HTTP_PROXY\'] = "http://example.com:xxxx" \r\nos.environ[\'HTTPS_PROXY\'] = "http://example.com:xxxx" \r\n`\r\n\r\nHowever, I still get the same error.\r\n\r\nOne thing that could be helpfull: When downloading a dataset without streaming i get the following message:\r\n_HF google storage unreachable. Downloading and preparing it from source_.\r\nThe download does however work as expected.\r\n', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1607244302/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1607279202', 'html_url': 'https://github.com/huggingface/datasets/issues/5975#issuecomment-1607279202', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5975', 'id': 1607279202, 'node_id': 'IC_kwDODunzps5fzSJi', 'user': {'login': 'lhoestq', 'id': 42851186, 'node_id': 'MDQ6VXNlcjQyODUxMTg2', 'avatar_url': 'https://avatars.githubusercontent.com/u/42851186?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/lhoestq', 'html_url': 'https://github.com/lhoestq', 'followers_url': 'https://api.github.com/users/lhoestq/followers', 'following_url': 'https://api.github.com/users/lhoestq/following{/other_user}', 'gists_url': 'https://api.github.com/users/lhoestq/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/lhoestq/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/lhoestq/subscriptions', 'organizations_url': 'https://api.github.com/users/lhoestq/orgs', 'repos_url': 'https://api.github.com/users/lhoestq/repos', 'events_url': 'https://api.github.com/users/lhoestq/events{/privacy}', 'received_events_url': 'https://api.github.com/users/lhoestq/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-26T11:33:04Z', 'updated_at': '2023-06-26T11:33:04Z', 'author_association': 'MEMBER', 'body': 'Are you able to use `aiohttp` to get the file at `https://huggingface.co/datasets/facebook/voxpopuli/resolve/main/data/n_files.json` using your proxy ?', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1607279202/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1607369766', 'html_url': 'https://github.com/huggingface/datasets/issues/5975#issuecomment-1607369766', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5975', 'id': 1607369766, 'node_id': 'IC_kwDODunzps5fzoQm', 'user': {'login': 'Veluchs', 'id': 135350576, 'node_id': 'U_kgDOCBFJMA', 'avatar_url': 'https://avatars.githubusercontent.com/u/135350576?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/Veluchs', 'html_url': 'https://github.com/Veluchs', 'followers_url': 'https://api.github.com/users/Veluchs/followers', 'following_url': 'https://api.github.com/users/Veluchs/following{/other_user}', 'gists_url': 'https://api.github.com/users/Veluchs/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/Veluchs/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/Veluchs/subscriptions', 'organizations_url': 'https://api.github.com/users/Veluchs/orgs', 'repos_url': 'https://api.github.com/users/Veluchs/repos', 'events_url': 'https://api.github.com/users/Veluchs/events{/privacy}', 'received_events_url': 'https://api.github.com/users/Veluchs/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-26T12:27:59Z', 'updated_at': '2023-06-26T12:29:01Z', 'author_association': 'NONE', 'body': 'It only works when passing trust_env=True when creating the ClientSession, as well as setting ssl=False.\r\n\r\nWorking Example:\r\n\r\n```\r\nimport os\r\n\r\nos.environ[\'HTTP_PROXY\'] = "xyz"\r\nos.environ[\'HTTPS_PROXY\'] = "xyz"\r\n\r\nimport asyncio\r\nimport aiohttp\r\n\r\nasync def download_pep(url):\r\n    async with aiohttp.ClientSession(trust_env=True) as session:\r\n        print("1")\r\n        async with session.get(url, ssl=False) as resp:\r\n            print("2")\r\n            content = await resp.text()\r\n            print(content)\r\n            return content\r\n\r\nasyncio.run(download_pep("https://huggingface.co/datasets/facebook/voxpopuli/resolve/main/data/n_files.json"))\r\n```\r\n\r\n\r\n\r\nSSL Verification has been a problem with other packages as well. Usually I circumvent the problem by setting\r\n```\r\nimport ssl\r\nssl._create_default_https_context = ssl._create_unverified_context\r\n```\r\n(probably not the best idea for security), although here aiohttp does not seem to use this default context.', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1607369766/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1607391399', 'html_url': 'https://github.com/huggingface/datasets/issues/5975#issuecomment-1607391399', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5975', 'id': 1607391399, 'node_id': 'IC_kwDODunzps5fztin', 'user': {'login': 'lhoestq', 'id': 42851186, 'node_id': 'MDQ6VXNlcjQyODUxMTg2', 'avatar_url': 'https://avatars.githubusercontent.com/u/42851186?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/lhoestq', 'html_url': 'https://github.com/lhoestq', 'followers_url': 'https://api.github.com/users/lhoestq/followers', 'following_url': 'https://api.github.com/users/lhoestq/following{/other_user}', 'gists_url': 'https://api.github.com/users/lhoestq/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/lhoestq/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/lhoestq/subscriptions', 'organizations_url': 'https://api.github.com/users/lhoestq/orgs', 'repos_url': 'https://api.github.com/users/lhoestq/repos', 'events_url': 'https://api.github.com/users/lhoestq/events{/privacy}', 'received_events_url': 'https://api.github.com/users/lhoestq/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-26T12:43:33Z', 'updated_at': '2023-06-26T12:43:33Z', 'author_association': 'MEMBER', 'body': 'We do pass `trust_env` as well. Could you share the full stack trace you get when streaming using `datasets` ? That could help locate where we might have forgotten to pass `trust_env`', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1607391399/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1607403769', 'html_url': 'https://github.com/huggingface/datasets/issues/5975#issuecomment-1607403769', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5975', 'id': 1607403769, 'node_id': 'IC_kwDODunzps5fzwj5', 'user': {'login': 'Veluchs', 'id': 135350576, 'node_id': 'U_kgDOCBFJMA', 'avatar_url': 'https://avatars.githubusercontent.com/u/135350576?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/Veluchs', 'html_url': 'https://github.com/Veluchs', 'followers_url': 'https://api.github.com/users/Veluchs/followers', 'following_url': 'https://api.github.com/users/Veluchs/following{/other_user}', 'gists_url': 'https://api.github.com/users/Veluchs/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/Veluchs/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/Veluchs/subscriptions', 'organizations_url': 'https://api.github.com/users/Veluchs/orgs', 'repos_url': 'https://api.github.com/users/Veluchs/repos', 'events_url': 'https://api.github.com/users/Veluchs/events{/privacy}', 'received_events_url': 'https://api.github.com/users/Veluchs/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-26T12:52:08Z', 'updated_at': '2023-06-26T12:52:08Z', 'author_association': 'NONE', 'body': 'Is there a way to disable ssl verification when streaming a dataset. I suspect this might be the isssue with my proxy.\r\n\r\n\r\nHere you go:\r\n\r\n```\r\nFileNotFoundError                         Traceback (most recent call last)\r\nCell In[8], line 3\r\n      1 from datasets import load_dataset\r\n----> 3 ds = load_dataset("facebook/voxpopuli", name="de", streaming=True)\r\n      5 sample = next(iter(ds))\r\n\r\nFile [~/.conda/envs/audio_hf/lib/python3.10/site-packages/datasets/load.py:1790](https://vscode-remote+ssh-002dremote-002bml-002er-002dsoftware-002eat.vscode-resource.vscode-cdn.net/home/wrsbri/projects/audio_course/~/.conda/envs/audio_hf/lib/python3.10/site-packages/datasets/load.py:1790), in load_dataset(path, name, data_dir, data_files, split, cache_dir, features, download_config, download_mode, verification_mode, ignore_verifications, keep_in_memory, save_infos, revision, use_auth_token, task, streaming, num_proc, storage_options, **config_kwargs)\r\n   1788 # Return iterable dataset in case of streaming\r\n   1789 if streaming:\r\n-> 1790     return builder_instance.as_streaming_dataset(split=split)\r\n   1792 # Some datasets are already processed on the HF google storage\r\n   1793 # Don\'t try downloading from Google storage for the packaged datasets as text, json, csv or pandas\r\n   1794 try_from_hf_gcs = path not in _PACKAGED_DATASETS_MODULES\r\n\r\nFile [~/.conda/envs/audio_hf/lib/python3.10/site-packages/datasets/builder.py:1281](https://vscode-remote+ssh-002dremote-002bml-002er-002dsoftware-002eat.vscode-resource.vscode-cdn.net/home/wrsbri/projects/audio_course/~/.conda/envs/audio_hf/lib/python3.10/site-packages/datasets/builder.py:1281), in DatasetBuilder.as_streaming_dataset(self, split, base_path)\r\n   1274 dl_manager = StreamingDownloadManager(\r\n   1275     base_path=base_path or self.base_path,\r\n   1276     download_config=DownloadConfig(use_auth_token=self.use_auth_token, storage_options=self.storage_options),\r\n   1277     dataset_name=self.name,\r\n   1278     data_dir=self.config.data_dir,\r\n   1279 )\r\n   1280 self._check_manual_download(dl_manager)\r\n-> 1281 splits_generators = {sg.name: sg for sg in self._split_generators(dl_manager)}\r\n   1282 # By default, return all splits\r\n   1283 if split is None:\r\n\r\nFile [~/.cache/huggingface/modules/datasets_modules/datasets/facebook--voxpopuli/b5ff837284f0778eefe0f642734e142d8c3f574eba8c9c8a4b13602297f73604/voxpopuli.py:120](https://vscode-remote+ssh-002dremote-002bml-002er-002dsoftware-002eat.vscode-resource.vscode-cdn.net/home/wrsbri/projects/audio_course/~/.cache/huggingface/modules/datasets_modules/datasets/facebook--voxpopuli/b5ff837284f0778eefe0f642734e142d8c3f574eba8c9c8a4b13602297f73604/voxpopuli.py:120), in Voxpopuli._split_generators(self, dl_manager)\r\n    118 def _split_generators(self, dl_manager):\r\n    119     n_shards_path = dl_manager.download_and_extract(_N_SHARDS_FILE)\r\n--> 120     with open(n_shards_path) as f:\r\n    121         n_shards = json.load(f)\r\n    123     if self.config.name == "en_accented":\r\n\r\nFile [~/.conda/envs/audio_hf/lib/python3.10/site-packages/datasets/streaming.py:71](https://vscode-remote+ssh-002dremote-002bml-002er-002dsoftware-002eat.vscode-resource.vscode-cdn.net/home/wrsbri/projects/audio_course/~/.conda/envs/audio_hf/lib/python3.10/site-packages/datasets/streaming.py:71), in extend_module_for_streaming..wrap_auth..wrapper(*args, **kwargs)\r\n     69 @wraps(function)\r\n     70 def wrapper(*args, **kwargs):\r\n---> 71     return function(*args, use_auth_token=use_auth_token, **kwargs)\r\n\r\nFile [~/.conda/envs/audio_hf/lib/python3.10/site-packages/datasets/download/streaming_download_manager.py:517](https://vscode-remote+ssh-002dremote-002bml-002er-002dsoftware-002eat.vscode-resource.vscode-cdn.net/home/wrsbri/projects/audio_course/~/.conda/envs/audio_hf/lib/python3.10/site-packages/datasets/download/streaming_download_manager.py:517), in xopen(file, mode, use_auth_token, *args, **kwargs)\r\n    515 except FileNotFoundError:\r\n    516     if file.startswith(config.HF_ENDPOINT):\r\n--> 517         raise FileNotFoundError(\r\n    518             file + "\\nIf the repo is private or gated, make sure to log in with `huggingface-cli login`."\r\n    519         ) from None\r\n    520     else:\r\n    521         raise\r\n\r\nFileNotFoundError: https://huggingface.co/datasets/facebook/voxpopuli/resolve/main/data/n_files.json\r\nIf the repo is private or gated, make sure to log in with `huggingface-cli login`.\r\n```', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1607403769/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1607598308', 'html_url': 'https://github.com/huggingface/datasets/issues/5975#issuecomment-1607598308', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5975', 'id': 1607598308, 'node_id': 'IC_kwDODunzps5f0gDk', 'user': {'login': 'lhoestq', 'id': 42851186, 'node_id': 'MDQ6VXNlcjQyODUxMTg2', 'avatar_url': 'https://avatars.githubusercontent.com/u/42851186?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/lhoestq', 'html_url': 'https://github.com/lhoestq', 'followers_url': 'https://api.github.com/users/lhoestq/followers', 'following_url': 'https://api.github.com/users/lhoestq/following{/other_user}', 'gists_url': 'https://api.github.com/users/lhoestq/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/lhoestq/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/lhoestq/subscriptions', 'organizations_url': 'https://api.github.com/users/lhoestq/orgs', 'repos_url': 'https://api.github.com/users/lhoestq/repos', 'events_url': 'https://api.github.com/users/lhoestq/events{/privacy}', 'received_events_url': 'https://api.github.com/users/lhoestq/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-26T14:21:32Z', 'updated_at': '2023-06-26T14:21:32Z', 'author_association': 'MEMBER', 'body': "> Is there a way to disable ssl verification when streaming a dataset.\r\n\r\nI don't think so.\r\n\r\nWe use `fsspec` HTTPFileSystem implementation that is based on `aiohttp`. If you register a subclass of HTTPFileSystem that has SSL disabled by default it could work, but I wouldn't recommended it because it can raise security issues.", 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1607598308/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, '

[{'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1601171167', 'html_url': 'https://github.com/huggingface/datasets/pull/5974#issuecomment-1601171167', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5974', 'id': 1601171167, 'node_id': 'IC_kwDODunzps5fb-7f', 'user': {'login': 'HuggingFaceDocBuilderDev', 'id': 99929124, 'node_id': 'U_kgDOBfTMJA', 'avatar_url': 'https://avatars.githubusercontent.com/u/99929124?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/HuggingFaceDocBuilderDev', 'html_url': 'https://github.com/HuggingFaceDocBuilderDev', 'followers_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/followers', 'following_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/following{/other_user}', 'gists_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/subscriptions', 'organizations_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/orgs', 'repos_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/repos', 'events_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/events{/privacy}', 'received_events_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-21T16:37:53Z', 'updated_at': '2023-06-26T10:28:09Z', 'author_association': 'NONE', 'body': '_The documentation is not available anymore as the PR was closed or merged._', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1601171167/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1601171513', 'html_url': 'https://github.com/huggingface/datasets/pull/5974#issuecomment-1601171513', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5974', 'id': 1601171513, 'node_id': 'IC_kwDODunzps5fb_A5', 'user': {'login': 'github-actions[bot]', 'id': 41898282, 'node_id': 'MDM6Qm90NDE4OTgyODI=', 'avatar_url': 'https://avatars.githubusercontent.com/in/15368?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/github-actions%5Bbot%5D', 'html_url': 'https://github.com/apps/github-actions', 'followers_url': 'https://api.github.com/users/github-actions%5Bbot%5D/followers', 'following_url': 'https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}', 'gists_url': 'https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/github-actions%5Bbot%5D/subscriptions', 'organizations_url': 'https://api.github.com/users/github-actions%5Bbot%5D/orgs', 'repos_url': 'https://api.github.com/users/github-actions%5Bbot%5D/repos', 'events_url': 'https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}', 'received_events_url': 'https://api.github.com/users/github-actions%5Bbot%5D/received_events', 'type': 'Bot', 'site_admin': False}, 'created_at': '2023-06-21T16:38:10Z', 'updated_at': '2023-06-21T16:38:10Z', 'author_association': 'NONE', 'body': '<details>\n<summary>Show benchmarks</summary>\n\nPyArrow==8.0.0\n\n<details>\n<summary>Show updated benchmarks!</summary>\n\n### Benchmark: benchmark_array_xd.json\n\n| metric | read_batch_formatted_as_numpy after write_array2d | read_batch_formatted_as_numpy after write_flattened_sequence | read_batch_formatted_as_numpy after write_nested_sequence | read_batch_unformated after write_array2d | read_batch_unformated after write_flattened_sequence | read_batch_unformated after write_nested_sequence | read_col_formatted_as_numpy after write_array2d | read_col_formatted_as_numpy after write_flattened_sequence | read_col_formatted_as_numpy after write_nested_sequence | read_col_unformated after write_array2d | read_col_unformated after write_flattened_sequence | read_col_unformated after write_nested_sequence | read_formatted_as_numpy after write_array2d | read_formatted_as_numpy after write_flattened_sequence | read_formatted_as_numpy after write_nested_sequence | read_unformated after write_array2d | read_unformated after write_flattened_sequence | read_unformated after write_nested_sequence | write_array2d | write_flattened_sequence | write_nested_sequence |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.006518 / 0.011353 (-0.004835) | 0.004121 / 0.011008 (-0.006887) | 0.103350 / 0.038508 (0.064842) | 0.045030 / 0.023109 (0.021920) | 0.351670 / 0.275898 (0.075772) | 0.408110 / 0.323480 (0.084630) | 0.003883 / 0.007986 (-0.004102) | 0.003352 / 0.004328 (-0.000977) | 0.078786 / 0.004250 (0.074535) | 0.063977 / 0.037052 (0.026925) | 0.369759 / 0.258489 (0.111270) | 0.415103 / 0.293841 (0.121262) | 0.033069 / 0.128546 (-0.095477) | 0.008863 / 0.075646 (-0.066783) | 0.353660 / 0.419271 (-0.065611) | 0.055714 / 0.043533 (0.012181) | 0.350458 / 0.255139 (0.095319) | 0.369505 / 0.283200 (0.086305) | 0.022822 / 0.141683 (-0.118861) | 1.537588 / 1.452155 (0.085433) | 1.590569 / 1.492716 (0.097853) |\n\n### Benchmark: benchmark_getitem\\_100B.json\n\n| metric | get_batch_of\\_1024\\_random_rows | get_batch_of\\_1024\\_rows | get_first_row | get_last_row |\n|--------|---|---|---|---|\n| new / old (diff) | 0.206826 / 0.018006 (0.188819) | 0.471625 / 0.000490 (0.471135) | 0.005188 / 0.000200 (0.004988) | 0.000316 / 0.000054 (0.000261) |\n\n### Benchmark: benchmark_indices_mapping.json\n\n| metric | select | shard | shuffle | sort | train_test_split |\n|--------|---|---|---|---|---|\n| new / old (diff) | 0.028148 / 0.037411 (-0.009263) | 0.111941 / 0.014526 (0.097415) | 0.122106 / 0.176557 (-0.054451) | 0.181127 / 0.737135 (-0.556009) | 0.127534 / 0.296338 (-0.168805) |\n\n### Benchmark: benchmark_iterating.json\n\n| metric | read 5000 | read 50000 | read_batch 50000 10 | read_batch 50000 100 | read_batch 50000 1000 | read_formatted numpy 5000 | read_formatted pandas 5000 | read_formatted tensorflow 5000 | read_formatted torch 5000 | read_formatted_batch numpy 5000 10 | read_formatted_batch numpy 5000 1000 | shuffled read 5000 | shuffled read 50000 | shuffled read_batch 50000 10 | shuffled read_batch 50000 100 | shuffled read_batch 50000 1000 | shuffled read_formatted numpy 5000 | shuffled read_formatted_batch numpy 5000 10 | shuffled read_formatted_batch numpy 5000 1000 |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.409520 / 0.215209 (0.194311) | 4.098455 / 2.077655 (2.020800) | 1.852447 / 1.504120 (0.348327) | 1.657036 / 1.541195 (0.115842) | 1.709624 / 1.468490 (0.241134) | 0.542806 / 4.584777 (-4.041970) | 3.809352 / 3.745712 (0.063640) | 1.855412 / 5.269862 (-3.414449) | 1.109180 / 4.565676 (-3.456497) | 0.066801 / 0.424275 (-0.357474) | 0.011832 / 0.007607 (0.004225) | 0.518338 / 0.226044 (0.292293) | 5.190108 / 2.268929 (2.921179) | 2.320602 / 55.444624 (-53.124023) | 1.991416 / 6.876477 (-4.885060) | 2.106989 / 2.142072 (-0.035084) | 0.668914 / 4.805227 (-4.136313) | 0.145325 / 6.500664 (-6.355340) | 0.065145 / 0.075469 (-0.010324) |\n\n### Benchmark: benchmark_map_filter.json\n\n| metric | filter | map fast-tokenizer batched | map identity | map identity batched | map no-op batched | map no-op batched numpy | map no-op batched pandas | map no-op batched pytorch | map no-op batched tensorflow |\n|--------|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 1.254706 / 1.841788 (-0.587082) | 14.707264 / 8.074308 (6.632956) | 14.615423 / 10.191392 (4.424031) | 0.170764 / 0.680424 (-0.509659) | 0.017905 / 0.534201 (-0.516296) | 0.435606 / 0.579283 (-0.143677) | 0.434648 / 0.434364 (0.000284) | 0.520813 / 0.540337 (-0.019524) | 0.633902 / 1.386936 (-0.753034) |\n\n</details>\nPyArrow==latest\n\n<details>\n<summary>Show updated benchmarks!</summary>\n\n### Benchmark: benchmark_array_xd.json\n\n| metric | read_batch_formatted_as_numpy after write_array2d | read_batch_formatted_as_numpy after write_flattened_sequence | read_batch_formatted_as_numpy after write_nested_sequence | read_batch_unformated after write_array2d | read_batch_unformated after write_flattened_sequence | read_batch_unformated after write_nested_sequence | read_col_formatted_as_numpy after write_array2d | read_col_formatted_as_numpy after write_flattened_sequence | read_col_formatted_as_numpy after write_nested_sequence | read_col_unformated after write_array2d | read_col_unformated after write_flattened_sequence | read_col_unformated after write_nested_sequence | read_formatted_as_numpy after write_array2d | read_formatted_as_numpy after write_flattened_sequence | read_formatted_as_numpy after write_nested_sequence | read_unformated after write_array2d | read_unformated after write_flattened_sequence | read_unformated after write_nested_sequence | write_array2d | write_flattened_sequence | write_nested_sequence |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.007212 / 0.011353 (-0.004141) | 0.004301 / 0.011008 (-0.006707) | 0.080767 / 0.038508 (0.042258) | 0.051949 / 0.023109 (0.028840) | 0.398473 / 0.275898 (0.122575) | 0.465038 / 0.323480 (0.141558) | 0.005580 / 0.007986 (-0.002406) | 0.003556 / 0.004328 (-0.000773) | 0.080682 / 0.004250 (0.076431) | 0.059517 / 0.037052 (0.022464) | 0.421171 / 0.258489 (0.162682) | 0.459752 / 0.293841 (0.165911) | 0.032960 / 0.128546 (-0.095586) | 0.009107 / 0.075646 (-0.066539) | 0.086382 / 0.419271 (-0.332889) | 0.056053 / 0.043533 (0.012520) | 0.393357 / 0.255139 (0.138218) | 0.412972 / 0.283200 (0.129772) | 0.031115 / 0.141683 (-0.110568) | 1.576961 / 1.452155 (0.124806) | 1.627249 / 1.492716 (0.134533) |\n\n### Benchmark: benchmark_getitem\\_100B.json\n\n| metric | get_batch_of\\_1024\\_random_rows | get_batch_of\\_1024\\_rows | get_first_row | get_last_row |\n|--------|---|---|---|---|\n| new / old (diff) | 0.227618 / 0.018006 (0.209612) | 0.444640 / 0.000490 (0.444150) | 0.004376 / 0.000200 (0.004176) | 0.000092 / 0.000054 (0.000038) |\n\n### Benchmark: benchmark_indices_mapping.json\n\n| metric | select | shard | shuffle | sort | train_test_split |\n|--------|---|---|---|---|---|\n| new / old (diff) | 0.030826 / 0.037411 (-0.006586) | 0.117587 / 0.014526 (0.103062) | 0.127467 / 0.176557 (-0.049089) | 0.184440 / 0.737135 (-0.552695) | 0.133664 / 0.296338 (-0.162675) |\n\n### Benchmark: benchmark_iterating.json\n\n| metric | read 5000 | read 50000 | read_batch 50000 10 | read_batch 50000 100 | read_batch 50000 1000 | read_formatted numpy 5000 | read_formatted pandas 5000 | read_formatted tensorflow 5000 | read_formatted torch 5000 | read_formatted_batch numpy 5000 10 | read_formatted_batch numpy 5000 1000 | shuffled read 5000 | shuffled read 50000 | shuffled read_batch 50000 10 | shuffled read_batch 50000 100 | shuffled read_batch 50000 1000 | shuffled read_formatted numpy 5000 | shuffled read_formatted_batch numpy 5000 10 | shuffled read_formatted_batch numpy 5000 1000 |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.443183 / 0.215209 (0.227974) | 4.408312 / 2.077655 (2.330658) | 2.132487 / 1.504120 (0.628367) | 1.923632 / 1.541195 (0.382438) | 1.967882 / 1.468490 (0.499392) | 0.552954 / 4.584777 (-4.031823) | 3.777701 / 3.745712 (0.031989) | 1.857686 / 5.269862 (-3.412176) | 1.104847 / 4.565676 (-3.460829) | 0.068350 / 0.424275 (-0.355925) | 0.012437 / 0.007607 (0.004830) | 0.559258 / 0.226044 (0.333214) | 5.593258 / 2.268929 (3.324330) | 2.648059 / 55.444624 (-52.796565) | 2.277428 / 6.876477 (-4.599049) | 2.351685 / 2.142072 (0.209612) | 0.678750 / 4.805227 (-4.126477) | 0.145550 / 6.500664 (-6.355114) | 0.066556 / 0.075469 (-0.008913) |\n\n### Benchmark: benchmark_map_filter.json\n\n| metric | filter | map fast-tokenizer batched | map identity | map identity batched | map no-op batched | map no-op batched numpy | map no-op batched pandas | map no-op batched pytorch | map no-op batched tensorflow |\n|--------|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 1.327128 / 1.841788 (-0.514659) | 15.649079 / 8.074308 (7.574771) | 14.478659 / 10.191392 (4.287267) | 0.147633 / 0.680424 (-0.532791) | 0.018502 / 0.534201 (-0.515699) | 0.438556 / 0.579283 (-0.140727) | 0.433381 / 0.434364 (-0.000983) | 0.514367 / 0.540337 (-0.025970) | 0.618347 / 1.386936 (-0.768589) |\n\n</details>\n</details>\n\n![](https://cml.dev/watermark.png#16aa1c886c5b499641a4bb3d8ce4a4f7de8244b7 "CML watermark")\n', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1601171513/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1607181987', 'html_url': 'https://github.com/huggingface/datasets/pull/5974#issuecomment-1607181987', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5974', 'id': 1607181987, 'node_id': 'IC_kwDODunzps5fy6aj', 'user': {'login': 'github-actions[bot]', 'id': 41898282, 'node_id': 'MDM6Qm90NDE4OTgyODI=', 'avatar_url': 'https://avatars.githubusercontent.com/in/15368?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/github-actions%5Bbot%5D', 'html_url': 'https://github.com/apps/github-actions', 'followers_url': 'https://api.github.com/users/github-actions%5Bbot%5D/followers', 'following_url': 'https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}', 'gists_url': 'https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/github-actions%5Bbot%5D/subscriptions', 'organizations_url': 'https://api.github.com/users/github-actions%5Bbot%5D/orgs', 'repos_url': 'https://api.github.com/users/github-actions%5Bbot%5D/repos', 'events_url': 'https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}', 'received_events_url': 'https://api.github.com/users/github-actions%5Bbot%5D/received_events', 'type': 'Bot', 'site_admin': False}, 'created_at': '2023-06-26T10:34:42Z', 'updated_at': '2023-06-26T10:34:42Z', 'author_association': 'NONE', 'body': '<details>\n<summary>Show benchmarks</summary>\n\nPyArrow==8.0.0\n\n<details>\n<summary>Show updated benchmarks!</summary>\n\n### Benchmark: benchmark_array_xd.json\n\n| metric | read_batch_formatted_as_numpy after write_array2d | read_batch_formatted_as_numpy after write_flattened_sequence | read_batch_formatted_as_numpy after write_nested_sequence | read_batch_unformated after write_array2d | read_batch_unformated after write_flattened_sequence | read_batch_unformated after write_nested_sequence | read_col_formatted_as_numpy after write_array2d | read_col_formatted_as_numpy after write_flattened_sequence | read_col_formatted_as_numpy after write_nested_sequence | read_col_unformated after write_array2d | read_col_unformated after write_flattened_sequence | read_col_unformated after write_nested_sequence | read_formatted_as_numpy after write_array2d | read_formatted_as_numpy after write_flattened_sequence | read_formatted_as_numpy after write_nested_sequence | read_unformated after write_array2d | read_unformated after write_flattened_sequence | read_unformated after write_nested_sequence | write_array2d | write_flattened_sequence | write_nested_sequence |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.006078 / 0.011353 (-0.005275) | 0.003914 / 0.011008 (-0.007095) | 0.102039 / 0.038508 (0.063531) | 0.037660 / 0.023109 (0.014551) | 0.348963 / 0.275898 (0.073065) | 0.407284 / 0.323480 (0.083804) | 0.004661 / 0.007986 (-0.003324) | 0.003253 / 0.004328 (-0.001076) | 0.078276 / 0.004250 (0.074025) | 0.054144 / 0.037052 (0.017091) | 0.376715 / 0.258489 (0.118225) | 0.418499 / 0.293841 (0.124658) | 0.027627 / 0.128546 (-0.100919) | 0.008494 / 0.075646 (-0.067152) | 0.316894 / 0.419271 (-0.102377) | 0.046560 / 0.043533 (0.003027) | 0.339835 / 0.255139 (0.084696) | 0.374628 / 0.283200 (0.091428) | 0.020729 / 0.141683 (-0.120954) | 1.502769 / 1.452155 (0.050615) | 1.548756 / 1.492716 (0.056040) |\n\n### Benchmark: benchmark_getitem\\_100B.json\n\n| metric | get_batch_of\\_1024\\_random_rows | get_batch_of\\_1024\\_rows | get_first_row | get_last_row |\n|--------|---|---|---|---|\n| new / old (diff) | 0.229192 / 0.018006 (0.211186) | 0.426245 / 0.000490 (0.425756) | 0.005190 / 0.000200 (0.004990) | 0.000081 / 0.000054 (0.000026) |\n\n### Benchmark: benchmark_indices_mapping.json\n\n| metric | select | shard | shuffle | sort | train_test_split |\n|--------|---|---|---|---|---|\n| new / old (diff) | 0.024271 / 0.037411 (-0.013140) | 0.098869 / 0.014526 (0.084343) | 0.105079 / 0.176557 (-0.071477) | 0.164707 / 0.737135 (-0.572428) | 0.110337 / 0.296338 (-0.186002) |\n\n### Benchmark: benchmark_iterating.json\n\n| metric | read 5000 | read 50000 | read_batch 50000 10 | read_batch 50000 100 | read_batch 50000 1000 | read_formatted numpy 5000 | read_formatted pandas 5000 | read_formatted tensorflow 5000 | read_formatted torch 5000 | read_formatted_batch numpy 5000 10 | read_formatted_batch numpy 5000 1000 | shuffled read 5000 | shuffled read 50000 | shuffled read_batch 50000 10 | shuffled read_batch 50000 100 | shuffled read_batch 50000 1000 | shuffled read_formatted numpy 5000 | shuffled read_formatted_batch numpy 5000 10 | shuffled read_formatted_batch numpy 5000 1000 |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.426593 / 0.215209 (0.211383) | 4.293977 / 2.077655 (2.216323) | 1.928502 / 1.504120 (0.424382) | 1.728623 / 1.541195 (0.187428) | 1.792084 / 1.468490 (0.323594) | 0.568737 / 4.584777 (-4.016040) | 3.438534 / 3.745712 (-0.307178) | 1.797798 / 5.269862 (-3.472063) | 1.054078 / 4.565676 (-3.511598) | 0.068711 / 0.424275 (-0.355564) | 0.011250 / 0.007607 (0.003643) | 0.529299 / 0.226044 (0.303255) | 5.283965 / 2.268929 (3.015037) | 2.358274 / 55.444624 (-53.086350) | 2.012818 / 6.876477 (-4.863659) | 2.109923 / 2.142072 (-0.032149) | 0.679556 / 4.805227 (-4.125671) | 0.138346 / 6.500664 (-6.362318) | 0.066349 / 0.075469 (-0.009120) |\n\n### Benchmark: benchmark_map_filter.json\n\n| metric | filter | map fast-tokenizer batched | map identity | map identity batched | map no-op batched | map no-op batched numpy | map no-op batched pandas | map no-op batched pytorch | map no-op batched tensorflow |\n|--------|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 1.193994 / 1.841788 (-0.647794) | 14.073158 / 8.074308 (5.998850) | 13.488525 / 10.191392 (3.297133) | 0.144536 / 0.680424 (-0.535888) | 0.016748 / 0.534201 (-0.517453) | 0.362703 / 0.579283 (-0.216580) | 0.389511 / 0.434364 (-0.044853) | 0.427296 / 0.540337 (-0.113041) | 0.513227 / 1.386936 (-0.873709) |\n\n</details>\nPyArrow==latest\n\n<details>\n<summary>Show updated benchmarks!</summary>\n\n### Benchmark: benchmark_array_xd.json\n\n| metric | read_batch_formatted_as_numpy after write_array2d | read_batch_formatted_as_numpy after write_flattened_sequence | read_batch_formatted_as_numpy after write_nested_sequence | read_batch_unformated after write_array2d | read_batch_unformated after write_flattened_sequence | read_batch_unformated after write_nested_sequence | read_col_formatted_as_numpy after write_array2d | read_col_formatted_as_numpy after write_flattened_sequence | read_col_formatted_as_numpy after write_neste

[{'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1601092005', 'html_url': 'https://github.com/huggingface/datasets/pull/5972#issuecomment-1601092005', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5972', 'id': 1601092005, 'node_id': 'IC_kwDODunzps5fbrml', 'user': {'login': 'github-actions[bot]', 'id': 41898282, 'node_id': 'MDM6Qm90NDE4OTgyODI=', 'avatar_url': 'https://avatars.githubusercontent.com/in/15368?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/github-actions%5Bbot%5D', 'html_url': 'https://github.com/apps/github-actions', 'followers_url': 'https://api.github.com/users/github-actions%5Bbot%5D/followers', 'following_url': 'https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}', 'gists_url': 'https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/github-actions%5Bbot%5D/subscriptions', 'organizations_url': 'https://api.github.com/users/github-actions%5Bbot%5D/orgs', 'repos_url': 'https://api.github.com/users/github-actions%5Bbot%5D/repos', 'events_url': 'https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}', 'received_events_url': 'https://api.github.com/users/github-actions%5Bbot%5D/received_events', 'type': 'Bot', 'site_admin': False}, 'created_at': '2023-06-21T15:49:49Z', 'updated_at': '2023-06-21T15:49:49Z', 'author_association': 'NONE', 'body': '<details>\n<summary>Show benchmarks</summary>\n\nPyArrow==8.0.0\n\n<details>\n<summary>Show updated benchmarks!</summary>\n\n### Benchmark: benchmark_array_xd.json\n\n| metric | read_batch_formatted_as_numpy after write_array2d | read_batch_formatted_as_numpy after write_flattened_sequence | read_batch_formatted_as_numpy after write_nested_sequence | read_batch_unformated after write_array2d | read_batch_unformated after write_flattened_sequence | read_batch_unformated after write_nested_sequence | read_col_formatted_as_numpy after write_array2d | read_col_formatted_as_numpy after write_flattened_sequence | read_col_formatted_as_numpy after write_nested_sequence | read_col_unformated after write_array2d | read_col_unformated after write_flattened_sequence | read_col_unformated after write_nested_sequence | read_formatted_as_numpy after write_array2d | read_formatted_as_numpy after write_flattened_sequence | read_formatted_as_numpy after write_nested_sequence | read_unformated after write_array2d | read_unformated after write_flattened_sequence | read_unformated after write_nested_sequence | write_array2d | write_flattened_sequence | write_nested_sequence |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.006983 / 0.011353 (-0.004369) | 0.004473 / 0.011008 (-0.006535) | 0.105158 / 0.038508 (0.066650) | 0.048973 / 0.023109 (0.025864) | 0.358771 / 0.275898 (0.082873) | 0.432389 / 0.323480 (0.108909) | 0.005689 / 0.007986 (-0.002297) | 0.003584 / 0.004328 (-0.000744) | 0.080852 / 0.004250 (0.076601) | 0.066133 / 0.037052 (0.029081) | 0.370981 / 0.258489 (0.112492) | 0.406942 / 0.293841 (0.113101) | 0.032123 / 0.128546 (-0.096424) | 0.009313 / 0.075646 (-0.066333) | 0.355220 / 0.419271 (-0.064051) | 0.055768 / 0.043533 (0.012235) | 0.370545 / 0.255139 (0.115406) | 0.375619 / 0.283200 (0.092419) | 0.024258 / 0.141683 (-0.117425) | 1.559073 / 1.452155 (0.106918) | 1.616520 / 1.492716 (0.123804) |\n\n### Benchmark: benchmark_getitem\\_100B.json\n\n| metric | get_batch_of\\_1024\\_random_rows | get_batch_of\\_1024\\_rows | get_first_row | get_last_row |\n|--------|---|---|---|---|\n| new / old (diff) | 0.277893 / 0.018006 (0.259887) | 0.535447 / 0.000490 (0.534957) | 0.004877 / 0.000200 (0.004677) | 0.000092 / 0.000054 (0.000037) |\n\n### Benchmark: benchmark_indices_mapping.json\n\n| metric | select | shard | shuffle | sort | train_test_split |\n|--------|---|---|---|---|---|\n| new / old (diff) | 0.029444 / 0.037411 (-0.007968) | 0.114366 / 0.014526 (0.099841) | 0.130957 / 0.176557 (-0.045599) | 0.189604 / 0.737135 (-0.547531) | 0.131682 / 0.296338 (-0.164656) |\n\n### Benchmark: benchmark_iterating.json\n\n| metric | read 5000 | read 50000 | read_batch 50000 10 | read_batch 50000 100 | read_batch 50000 1000 | read_formatted numpy 5000 | read_formatted pandas 5000 | read_formatted tensorflow 5000 | read_formatted torch 5000 | read_formatted_batch numpy 5000 10 | read_formatted_batch numpy 5000 1000 | shuffled read 5000 | shuffled read 50000 | shuffled read_batch 50000 10 | shuffled read_batch 50000 100 | shuffled read_batch 50000 1000 | shuffled read_formatted numpy 5000 | shuffled read_formatted_batch numpy 5000 10 | shuffled read_formatted_batch numpy 5000 1000 |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.412315 / 0.215209 (0.197106) | 4.093879 / 2.077655 (2.016225) | 1.856169 / 1.504120 (0.352050) | 1.655358 / 1.541195 (0.114164) | 1.758190 / 1.468490 (0.289699) | 0.545829 / 4.584777 (-4.038948) | 3.871436 / 3.745712 (0.125724) | 1.938244 / 5.269862 (-3.331618) | 1.122727 / 4.565676 (-3.442950) | 0.067107 / 0.424275 (-0.357168) | 0.012012 / 0.007607 (0.004405) | 0.518868 / 0.226044 (0.292824) | 5.235081 / 2.268929 (2.966153) | 2.335115 / 55.444624 (-53.109509) | 2.013074 / 6.876477 (-4.863402) | 2.219808 / 2.142072 (0.077735) | 0.674602 / 4.805227 (-4.130626) | 0.147051 / 6.500664 (-6.353613) | 0.068444 / 0.075469 (-0.007025) |\n\n### Benchmark: benchmark_map_filter.json\n\n| metric | filter | map fast-tokenizer batched | map identity | map identity batched | map no-op batched | map no-op batched numpy | map no-op batched pandas | map no-op batched pytorch | map no-op batched tensorflow |\n|--------|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 1.245600 / 1.841788 (-0.596188) | 15.537727 / 8.074308 (7.463419) | 15.074300 / 10.191392 (4.882908) | 0.194217 / 0.680424 (-0.486207) | 0.018536 / 0.534201 (-0.515665) | 0.437085 / 0.579283 (-0.142198) | 0.441123 / 0.434364 (0.006759) | 0.530681 / 0.540337 (-0.009657) | 0.649154 / 1.386936 (-0.737782) |\n\n</details>\nPyArrow==latest\n\n<details>\n<summary>Show updated benchmarks!</summary>\n\n### Benchmark: benchmark_array_xd.json\n\n| metric | read_batch_formatted_as_numpy after write_array2d | read_batch_formatted_as_numpy after write_flattened_sequence | read_batch_formatted_as_numpy after write_nested_sequence | read_batch_unformated after write_array2d | read_batch_unformated after write_flattened_sequence | read_batch_unformated after write_nested_sequence | read_col_formatted_as_numpy after write_array2d | read_col_formatted_as_numpy after write_flattened_sequence | read_col_formatted_as_numpy after write_nested_sequence | read_col_unformated after write_array2d | read_col_unformated after write_flattened_sequence | read_col_unformated after write_nested_sequence | read_formatted_as_numpy after write_array2d | read_formatted_as_numpy after write_flattened_sequence | read_formatted_as_numpy after write_nested_sequence | read_unformated after write_array2d | read_unformated after write_flattened_sequence | read_unformated after write_nested_sequence | write_array2d | write_flattened_sequence | write_nested_sequence |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.007243 / 0.011353 (-0.004110) | 0.004688 / 0.011008 (-0.006320) | 0.079809 / 0.038508 (0.041301) | 0.046915 / 0.023109 (0.023805) | 0.415144 / 0.275898 (0.139246) | 0.474867 / 0.323480 (0.151388) | 0.004550 / 0.007986 (-0.003435) | 0.004585 / 0.004328 (0.000257) | 0.080837 / 0.004250 (0.076587) | 0.061667 / 0.037052 (0.024614) | 0.411321 / 0.258489 (0.152832) | 0.464195 / 0.293841 (0.170354) | 0.032510 / 0.128546 (-0.096037) | 0.009306 / 0.075646 (-0.066340) | 0.086637 / 0.419271 (-0.332635) | 0.053335 / 0.043533 (0.009802) | 0.402302 / 0.255139 (0.147163) | 0.424864 / 0.283200 (0.141664) | 0.026573 / 0.141683 (-0.115110) | 1.566793 / 1.452155 (0.114639) | 1.628118 / 1.492716 (0.135401) |\n\n### Benchmark: benchmark_getitem\\_100B.json\n\n| metric | get_batch_of\\_1024\\_random_rows | get_batch_of\\_1024\\_rows | get_first_row | get_last_row |\n|--------|---|---|---|---|\n| new / old (diff) | 0.317802 / 0.018006 (0.299796) | 0.544593 / 0.000490 (0.544103) | 0.005690 / 0.000200 (0.005490) | 0.000107 / 0.000054 (0.000053) |\n\n### Benchmark: benchmark_indices_mapping.json\n\n| metric | select | shard | shuffle | sort | train_test_split |\n|--------|---|---|---|---|---|\n| new / old (diff) | 0.033015 / 0.037411 (-0.004397) | 0.121940 / 0.014526 (0.107414) | 0.132920 / 0.176557 (-0.043637) | 0.191481 / 0.737135 (-0.545655) | 0.139139 / 0.296338 (-0.157199) |\n\n### Benchmark: benchmark_iterating.json\n\n| metric | read 5000 | read 50000 | read_batch 50000 10 | read_batch 50000 100 | read_batch 50000 1000 | read_formatted numpy 5000 | read_formatted pandas 5000 | read_formatted tensorflow 5000 | read_formatted torch 5000 | read_formatted_batch numpy 5000 10 | read_formatted_batch numpy 5000 1000 | shuffled read 5000 | shuffled read 50000 | shuffled read_batch 50000 10 | shuffled read_batch 50000 100 | shuffled read_batch 50000 1000 | shuffled read_formatted numpy 5000 | shuffled read_formatted_batch numpy 5000 10 | shuffled read_formatted_batch numpy 5000 1000 |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.460382 / 0.215209 (0.245173) | 4.610046 / 2.077655 (2.532392) | 2.296573 / 1.504120 (0.792453) | 2.099735 / 1.541195 (0.558540) | 2.213913 / 1.468490 (0.745423) | 0.544871 / 4.584777 (-4.039906) | 3.814174 / 3.745712 (0.068462) | 3.246397 / 5.269862 (-2.023464) | 1.480236 / 4.565676 (-3.085440) | 0.068464 / 0.424275 (-0.355811) | 0.012651 / 0.007607 (0.005043) | 0.564989 / 0.226044 (0.338944) | 5.639188 / 2.268929 (3.370259) | 2.827601 / 55.444624 (-52.617023) | 2.473743 / 6.876477 (-4.402734) | 2.567413 / 2.142072 (0.425340) | 0.674351 / 4.805227 (-4.130876) | 0.146248 / 6.500664 (-6.354416) | 0.067553 / 0.075469 (-0.007916) |\n\n### Benchmark: benchmark_map_filter.json\n\n| metric | filter | map fast-tokenizer batched | map identity | map identity batched | map no-op batched | map no-op batched numpy | map no-op batched pandas | map no-op batched pytorch | map no-op batched tensorflow |\n|--------|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 1.346703 / 1.841788 (-0.495085) | 16.494787 / 8.074308 (8.420479) | 15.179487 / 10.191392 (4.988095) | 0.181864 / 0.680424 (-0.498560) | 0.018857 / 0.534201 (-0.515344) | 0.437787 / 0.579283 (-0.141496) | 0.431770 / 0.434364 (-0.002594) | 0.507116 / 0.540337 (-0.033221) | 0.608899 / 1.386936 (-0.778037) |\n\n</details>\n</details>\n\n![](https://cml.dev/watermark.png#0fd5b7412f907675e76b183a6e39ef6d176fdcc0 "CML watermark")\n', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1601092005/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1601224017', 'html_url': 'https://github.com/huggingface/datasets/pull/5972#issuecomment-1601224017', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5972', 'id': 1601224017, 'node_id': 'IC_kwDODunzps5fcL1R', 'user': {'login': 'HuggingFaceDocBuilderDev', 'id': 99929124, 'node_id': 'U_kgDOBfTMJA', 'avatar_url': 'https://avatars.githubusercontent.com/u/99929124?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/HuggingFaceDocBuilderDev', 'html_url': 'https://github.com/HuggingFaceDocBuilderDev', 'followers_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/followers', 'following_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/following{/other_user}', 'gists_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/subscriptions', 'organizations_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/orgs', 'repos_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/repos', 'events_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/events{/privacy}', 'received_events_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-21T16:55:44Z', 'updated_at': '2023-06-22T14:17:28Z', 'author_association': 'NONE', 'body': '_The documentation is not available anymore as the PR was closed or merged._', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1601224017/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1601227503', 'html_url': 'https://github.com/huggingface/datasets/pull/5972#issuecomment-1601227503', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5972', 'id': 1601227503, 'node_id': 'IC_kwDODunzps5fcMrv', 'user': {'login': 'github-actions[bot]', 'id': 41898282, 'node_id': 'MDM6Qm90NDE4OTgyODI=', 'avatar_url': 'https://avatars.githubusercontent.com/in/15368?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/github-actions%5Bbot%5D', 'html_url': 'https://github.com/apps/github-actions', 'followers_url': 'https://api.github.com/users/github-actions%5Bbot%5D/followers', 'following_url': 'https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}', 'gists_url': 'https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/github-actions%5Bbot%5D/subscriptions', 'organizations_url': 'https://api.github.com/users/github-actions%5Bbot%5D/orgs', 'repos_url': 'https://api.github.com/users/github-actions%5Bbot%5D/repos', 'events_url': 'https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}', 'received_events_url': 'https://api.github.com/users/github-actions%5Bbot%5D/received_events', 'type': 'Bot', 'site_admin': False}, 'created_at': '2023-06-21T16:57:13Z', 'updated_at': '2023-06-21T16:57:13Z', 'author_association': 'NONE', 'body': '<details>\n<summary>Show benchmarks</summary>\n\nPyArrow==8.0.0\n\n<details>\n<summary>Show updated benchmarks!</summary>\n\n### Benchmark: benchmark_array_xd.json\n\n| metric | read_batch_formatted_as_numpy after write_array2d | read_batch_formatted_as_numpy after write_flattened_sequence | read_batch_formatted_as_numpy after write_nested_sequence | read_batch_unformated after write_array2d | read_batch_unformated after write_flattened_sequence | read_batch_unformated after write_nested_sequence | read_col_formatted_as_numpy after write_array2d | read_col_formatted_as_numpy after write_flattened_sequence | read_col_formatted_as_numpy after write_nested_sequence | read_col_unformated after write_array2d | read_col_unformated after write_flattened_sequence | read_col_unformated after write_nested_sequence | read_formatted_as_numpy after write_array2d | read_formatted_as_numpy after write_flattened_sequence | read_formatted_as_numpy after write_nested_sequence | read_unformated after write_array2d | read_unformated after write_flattened_sequence | read_unformated after write_nested_sequence | write_array2d | write_flattened_sequence | write_nested_sequence |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.005963 / 0.011353 (-0.005390) | 0.003743 / 0.011008 (-0.007265) | 0.098519 / 0.038508 (0.060011) | 0.037392 / 0.023109 (0.014283) | 0.322706 / 0.275898 (0.046808) | 0.380032 / 0.323480 (0.056552) | 0.004694 / 0.007986 (-0.003292) | 0.002897 / 0.004328 (-0.001432) | 0.078664 / 0.004250 (0.074414) | 0.052646 / 0.037052 (0.015594) | 0.335523 / 0.258489 (0.077034) | 0.375464 / 0.293841 (0.081623) | 0.027537 / 0.128546 (-0.101010) | 0.008452 / 0.075646 (-0.067194) | 0.313844 / 0.419271 (-0.105427) | 0.047368 / 0.043533 (0.003835) | 0.313833 / 0.255139 (0.058694) | 0.342284 / 0.283200 (0.059085) | 0.021136 / 0.141683 (-0.120547) | 1.544764 / 1.452155 (0.092610) | 1.563850 / 1.492716 (0.071134) |\n\n### Benchmark: benchmark_getitem\\_100B.json\n\n| metric | get_batch_of\\_1024\\_random_rows | get_batch_of\\_1024\\_rows | get_first_row | get_last_row |\n|--------|---|---|---|---|\n| new / old (diff) | 0.188609 / 0.018006 (0.170603) | 0.421686 / 0.000490 (0.421196) | 0.003336 / 0.000200 (0.003136) | 0.000077 / 0.000054 (0.000023) |\n\n### Benchmark: benchmark_indices_mapping.json\n\n| metric | select | shard | shuffle | sort | train_test_split |\n|--------|---|---|---|---|---|\n| new / old (diff) | 0.023678 / 0.037411 (-0.013733) | 0.099191 / 0.014526 (0.084665) | 0.105819 / 0.176557 (-0.070738) | 0.169654 / 0.737135 (-0.567481) | 0.110240 / 0.296338 (-0.186099) |\n\n### Benchmark: benchmark_iterating.json\n\n| metric | read 5000 | read 50000 | read_batch 50000 10 | read_batch 50000 100 | read_batch 50000 1000 | read_formatted numpy 5000 | read_formatted pandas 5000 | read_formatted tensorflow 5000 | read_formatted torch 5000 | read_formatted_batch numpy 5000 10 | read_formatted_batch numpy 5000 1000 | shuffled read 5000 | shuffled read 50000 | shuffled read_batch 50000 10 | shuffled read_batch 50000 100 | shuffled read_batch 50000 1000 | shuffled read_formatted numpy 5000 | shuffled read_formatted_batch numpy 5000 10 | shuffled read_formatted_batch numpy 5000 1000 |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.425497 / 0.215209 (0.210288) | 4.237165 / 2.077655 (2.159510) | 1.902953 / 1.504120 (0.398833) | 1.699012 / 1.541195 (0.157818) | 1.751107 / 1.468490 (0.282617) | 0.563326 / 4.584777 (-4.021451) | 3.394189 / 3.745712 (-0.351523) | 2.706129 / 5.269862 (-2.563732) | 1.361522 / 4.565676 (-3.204155) | 0.067776 / 0.424275 (-0.356499) | 0.010959 / 0.007607 (0.003352) | 0.530905 / 0.226044 (0.304860) | 5.322467 / 2.268929 (3.053538) | 2.384356 / 55.444624 (-53.060269) | 2.044196 / 6.876477 (-4.832281) | 2.119837 / 2.142072 (-0.022235) | 0.682236 / 4.805227 (-4.122991) | 0.136921 / 6.500664 (-6.363743) | 0.066784 / 0.075469 (-0.008685) |\n\n### Benchmark: benchmark_map_filter.json\n\n| metric | filter | map fast-tokenizer batched | map identity | map identity batched | map no-op batched | map no-op batched numpy | map no-op batched pandas | map no-op batched pytorch | map no-op batched tensorflow |\n|--------|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 1.210642 / 1.841788 (-0.631146) | 13.804572 / 8.074308 (5.730264) | 13.309229 / 10.191392 (3.117837) | 0.154356 / 0.680424 (-0.526068) | 0.016833 / 0.534201 (-0.517368) | 0.366503 / 0.579283 (-0.212780) | 0.385201 / 0.434364 (-0.049163) | 0.426713 / 0.540337 (-0.113624) | 0.516795 / 1.386936 (-0.870141) |\n\n</details>\nPyArrow==latest\n\n<details>\n<summary>Show updated benchmarks!</summary>\n\n### Benchmark: benchmark_array_xd.json\n\n| metric | read_batch_formatted_as_numpy after write_array2d | read_batch_formatted_as_numpy after write_flattened_sequence | read_batch_formatted_as_numpy after write_nested_sequence | read_batch_unformated after write_array2d | read_batch_unformated after write_flattened_sequence | read_batch_unformated after write_nested_sequence | read_col_formatted_as_numpy after write_array2d | read_col_formatted_as_numpy after write_flattened_sequence | read_col_formatted_as_numpy after write_nested_

[{'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1601139555', 'html_url': 'https://github.com/huggingface/datasets/issues/5971#issuecomment-1601139555', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5971', 'id': 1601139555, 'node_id': 'IC_kwDODunzps5fb3Nj', 'user': {'login': 'mariosasko', 'id': 47462742, 'node_id': 'MDQ6VXNlcjQ3NDYyNzQy', 'avatar_url': 'https://avatars.githubusercontent.com/u/47462742?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/mariosasko', 'html_url': 'https://github.com/mariosasko', 'followers_url': 'https://api.github.com/users/mariosasko/followers', 'following_url': 'https://api.github.com/users/mariosasko/following{/other_user}', 'gists_url': 'https://api.github.com/users/mariosasko/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/mariosasko/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/mariosasko/subscriptions', 'organizations_url': 'https://api.github.com/users/mariosasko/orgs', 'repos_url': 'https://api.github.com/users/mariosasko/repos', 'events_url': 'https://api.github.com/users/mariosasko/events{/privacy}', 'received_events_url': 'https://api.github.com/users/mariosasko/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-21T16:15:11Z', 'updated_at': '2023-06-21T16:15:11Z', 'author_association': 'CONTRIBUTOR', 'body': 'Loading a local dataset also works the same way when `data_files` are not specified, so I agree we should make this info  easier to discover \r\n\r\ncc @stevhliu ', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1601139555/reactions', 'total_count': 2, '+1': 2, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1603591751', 'html_url': 'https://github.com/huggingface/datasets/issues/5971#issuecomment-1603591751', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5971', 'id': 1603591751, 'node_id': 'IC_kwDODunzps5flN5H', 'user': {'login': 'benjaminbrown038', 'id': 35114142, 'node_id': 'MDQ6VXNlcjM1MTE0MTQy', 'avatar_url': 'https://avatars.githubusercontent.com/u/35114142?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/benjaminbrown038', 'html_url': 'https://github.com/benjaminbrown038', 'followers_url': 'https://api.github.com/users/benjaminbrown038/followers', 'following_url': 'https://api.github.com/users/benjaminbrown038/following{/other_user}', 'gists_url': 'https://api.github.com/users/benjaminbrown038/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/benjaminbrown038/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/benjaminbrown038/subscriptions', 'organizations_url': 'https://api.github.com/users/benjaminbrown038/orgs', 'repos_url': 'https://api.github.com/users/benjaminbrown038/repos', 'events_url': 'https://api.github.com/users/benjaminbrown038/events{/privacy}', 'received_events_url': 'https://api.github.com/users/benjaminbrown038/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-23T02:06:27Z', 'updated_at': '2023-06-23T02:08:40Z', 'author_association': 'NONE', 'body': 'Is this issue open? If so, I will self assign. ', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1603591751/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1611839643', 'html_url': 'https://github.com/huggingface/datasets/issues/5971#issuecomment-1611839643', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5971', 'id': 1611839643, 'node_id': 'IC_kwDODunzps5gErib', 'user': {'login': 'mariosasko', 'id': 47462742, 'node_id': 'MDQ6VXNlcjQ3NDYyNzQy', 'avatar_url': 'https://avatars.githubusercontent.com/u/47462742?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/mariosasko', 'html_url': 'https://github.com/mariosasko', 'followers_url': 'https://api.github.com/users/mariosasko/followers', 'following_url': 'https://api.github.com/users/mariosasko/following{/other_user}', 'gists_url': 'https://api.github.com/users/mariosasko/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/mariosasko/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/mariosasko/subscriptions', 'organizations_url': 'https://api.github.com/users/mariosasko/orgs', 'repos_url': 'https://api.github.com/users/mariosasko/repos', 'events_url': 'https://api.github.com/users/mariosasko/events{/privacy}', 'received_events_url': 'https://api.github.com/users/mariosasko/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-28T17:47:47Z', 'updated_at': '2023-06-28T17:47:47Z', 'author_association': 'CONTRIBUTOR', 'body': "@benjaminbrown038 Yes, it is. Maybe @stevhliu can give some pointers on improving this doc page's discoverability.", 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1611839643/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1612143151', 'html_url': 'https://github.com/huggingface/datasets/issues/5971#issuecomment-1612143151', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5971', 'id': 1612143151, 'node_id': 'IC_kwDODunzps5gF1ov', 'user': {'login': 'stevhliu', 'id': 59462357, 'node_id': 'MDQ6VXNlcjU5NDYyMzU3', 'avatar_url': 'https://avatars.githubusercontent.com/u/59462357?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/stevhliu', 'html_url': 'https://github.com/stevhliu', 'followers_url': 'https://api.github.com/users/stevhliu/followers', 'following_url': 'https://api.github.com/users/stevhliu/following{/other_user}', 'gists_url': 'https://api.github.com/users/stevhliu/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/stevhliu/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/stevhliu/subscriptions', 'organizations_url': 'https://api.github.com/users/stevhliu/orgs', 'repos_url': 'https://api.github.com/users/stevhliu/repos', 'events_url': 'https://api.github.com/users/stevhliu/events{/privacy}', 'received_events_url': 'https://api.github.com/users/stevhliu/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-28T21:39:56Z', 'updated_at': '2023-06-28T21:39:56Z', 'author_association': 'MEMBER', 'body': 'I think we can add a version of the [Main use-case](https://huggingface.co/docs/datasets/repository_structure#main-usecase) section to the [Share a dataset to the Hub](https://huggingface.co/docs/datasets/upload_dataset) tutorial. \r\n\r\nCurrently, it doesn\'t tell you *how* to structure the repository; it only tells you how to create it. So adding the "main use-case" will help bridge the gap and make it easier to find. We should also add a link to the [Structure your repository](https://huggingface.co/docs/datasets/repository_structure) guide for users who want to learn about the other options.', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1612143151/reactions', 'total_count': 1, '+1': 1, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1621133279', 'html_url': 'https://github.com/huggingface/datasets/issues/5971#issuecomment-1621133279', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5971', 'id': 1621133279, 'node_id': 'IC_kwDODunzps5goIff', 'user': {'login': 'benjaminbrown038', 'id': 35114142, 'node_id': 'MDQ6VXNlcjM1MTE0MTQy', 'avatar_url': 'https://avatars.githubusercontent.com/u/35114142?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/benjaminbrown038', 'html_url': 'https://github.com/benjaminbrown038', 'followers_url': 'https://api.github.com/users/benjaminbrown038/followers', 'following_url': 'https://api.github.com/users/benjaminbrown038/following{/other_user}', 'gists_url': 'https://api.github.com/users/benjaminbrown038/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/benjaminbrown038/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/benjaminbrown038/subscriptions', 'organizations_url': 'https://api.github.com/users/benjaminbrown038/orgs', 'repos_url': 'https://api.github.com/users/benjaminbrown038/repos', 'events_url': 'https://api.github.com/users/benjaminbrown038/events{/privacy}', 'received_events_url': 'https://api.github.com/users/benjaminbrown038/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-07-05T06:51:27Z', 'updated_at': '2023-07-05T06:51:27Z', 'author_association': 'NONE', 'body': '#self-assign', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1621133279/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}]

[{'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1601819907', 'html_url': 'https://github.com/huggingface/datasets/issues/5970#issuecomment-1601819907', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5970', 'id': 1601819907, 'node_id': 'IC_kwDODunzps5fedUD', 'user': {'login': 'balisujohn', 'id': 20377292, 'node_id': 'MDQ6VXNlcjIwMzc3Mjky', 'avatar_url': 'https://avatars.githubusercontent.com/u/20377292?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/balisujohn', 'html_url': 'https://github.com/balisujohn', 'followers_url': 'https://api.github.com/users/balisujohn/followers', 'following_url': 'https://api.github.com/users/balisujohn/following{/other_user}', 'gists_url': 'https://api.github.com/users/balisujohn/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/balisujohn/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/balisujohn/subscriptions', 'organizations_url': 'https://api.github.com/users/balisujohn/orgs', 'repos_url': 'https://api.github.com/users/balisujohn/repos', 'events_url': 'https://api.github.com/users/balisujohn/events{/privacy}', 'received_events_url': 'https://api.github.com/users/balisujohn/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-21T23:30:52Z', 'updated_at': '2023-06-21T23:30:52Z', 'author_association': 'NONE', 'body': 'Here\'s a minimal way to reproduce the bug, for the sake of convenience.\r\n````\r\nfrom datasets import Dataset, DatasetInfo, load_dataset\r\n\r\n\r\nepisodes_dict = {"test":[1,2,3],"test2": [1,2,4]}\r\n\r\nhugging_face_dataset = Dataset.from_dict(\r\n    episodes_dict, info=DatasetInfo(description="test_str")\r\n)\r\nprint(hugging_face_dataset.info)\r\n\r\nhugging_face_dataset.push_to_hub("balisujohn/minari_test", private=True)\r\n\r\nredownloaded_dataset= load_dataset("balisujohn/minari_test")["train"]\r\n\r\n\r\nprint(redownloaded_dataset.info)\r\n````\r\n', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1601819907/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1602734419', 'html_url': 'https://github.com/huggingface/datasets/issues/5970#issuecomment-1602734419', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5970', 'id': 1602734419, 'node_id': 'IC_kwDODunzps5fh8lT', 'user': {'login': 'lhoestq', 'id': 42851186, 'node_id': 'MDQ6VXNlcjQyODUxMTg2', 'avatar_url': 'https://avatars.githubusercontent.com/u/42851186?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/lhoestq', 'html_url': 'https://github.com/lhoestq', 'followers_url': 'https://api.github.com/users/lhoestq/followers', 'following_url': 'https://api.github.com/users/lhoestq/following{/other_user}', 'gists_url': 'https://api.github.com/users/lhoestq/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/lhoestq/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/lhoestq/subscriptions', 'organizations_url': 'https://api.github.com/users/lhoestq/orgs', 'repos_url': 'https://api.github.com/users/lhoestq/repos', 'events_url': 'https://api.github.com/users/lhoestq/events{/privacy}', 'received_events_url': 'https://api.github.com/users/lhoestq/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-22T14:23:56Z', 'updated_at': '2023-06-22T14:23:56Z', 'author_association': 'MEMBER', 'body': 'Thanks for reporting !\r\n\r\nFor now I would recommend uploading a separate JSON file for your metadata.\r\n\r\nAlternatively you can upload a second configuration of the dataset containing your metadata but this feature is not released yet (though you can already use it from [here](https://github.com/huggingface/datasets/pull/5331), it will be released soon)', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1602734419/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}]

[{'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1598638610', 'html_url': 'https://github.com/huggingface/datasets/issues/5968#issuecomment-1598638610', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5968', 'id': 1598638610, 'node_id': 'IC_kwDODunzps5fSUoS', 'user': {'login': 'patrickvonplaten', 'id': 23423619, 'node_id': 'MDQ6VXNlcjIzNDIzNjE5', 'avatar_url': 'https://avatars.githubusercontent.com/u/23423619?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/patrickvonplaten', 'html_url': 'https://github.com/patrickvonplaten', 'followers_url': 'https://api.github.com/users/patrickvonplaten/followers', 'following_url': 'https://api.github.com/users/patrickvonplaten/following{/other_user}', 'gists_url': 'https://api.github.com/users/patrickvonplaten/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/patrickvonplaten/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/patrickvonplaten/subscriptions', 'organizations_url': 'https://api.github.com/users/patrickvonplaten/orgs', 'repos_url': 'https://api.github.com/users/patrickvonplaten/repos', 'events_url': 'https://api.github.com/users/patrickvonplaten/events{/privacy}', 'received_events_url': 'https://api.github.com/users/patrickvonplaten/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-20T11:58:49Z', 'updated_at': '2023-06-20T11:58:49Z', 'author_association': 'MEMBER', 'body': 'cc @pcuenca as well. \r\n\r\nNot super urgent btw', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1598638610/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1598720494', 'html_url': 'https://github.com/huggingface/datasets/issues/5968#issuecomment-1598720494', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5968', 'id': 1598720494, 'node_id': 'IC_kwDODunzps5fSonu', 'user': {'login': 'lhoestq', 'id': 42851186, 'node_id': 'MDQ6VXNlcjQyODUxMTg2', 'avatar_url': 'https://avatars.githubusercontent.com/u/42851186?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/lhoestq', 'html_url': 'https://github.com/lhoestq', 'followers_url': 'https://api.github.com/users/lhoestq/followers', 'following_url': 'https://api.github.com/users/lhoestq/following{/other_user}', 'gists_url': 'https://api.github.com/users/lhoestq/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/lhoestq/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/lhoestq/subscriptions', 'organizations_url': 'https://api.github.com/users/lhoestq/orgs', 'repos_url': 'https://api.github.com/users/lhoestq/repos', 'events_url': 'https://api.github.com/users/lhoestq/events{/privacy}', 'received_events_url': 'https://api.github.com/users/lhoestq/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-20T12:57:05Z', 'updated_at': '2023-06-20T12:57:05Z', 'author_association': 'MEMBER', 'body': 'The issue commes from the dataset itself and is not related to the `datasets` lib\r\n\r\nsee https://huggingface.co/datasets/mozilla-foundation/common_voice_6_1/blob/2c475b3b88e0f2e5828f830a4b91618a25ff20b7/common_voice_6_1.py#L148-L152', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1598720494/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1600562035', 'html_url': 'https://github.com/huggingface/datasets/issues/5968#issuecomment-1600562035', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5968', 'id': 1600562035, 'node_id': 'IC_kwDODunzps5fZqNz', 'user': {'login': 'patrickvonplaten', 'id': 23423619, 'node_id': 'MDQ6VXNlcjIzNDIzNjE5', 'avatar_url': 'https://avatars.githubusercontent.com/u/23423619?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/patrickvonplaten', 'html_url': 'https://github.com/patrickvonplaten', 'followers_url': 'https://api.github.com/users/patrickvonplaten/followers', 'following_url': 'https://api.github.com/users/patrickvonplaten/following{/other_user}', 'gists_url': 'https://api.github.com/users/patrickvonplaten/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/patrickvonplaten/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/patrickvonplaten/subscriptions', 'organizations_url': 'https://api.github.com/users/patrickvonplaten/orgs', 'repos_url': 'https://api.github.com/users/patrickvonplaten/repos', 'events_url': 'https://api.github.com/users/patrickvonplaten/events{/privacy}', 'received_events_url': 'https://api.github.com/users/patrickvonplaten/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-21T10:08:37Z', 'updated_at': '2023-06-21T10:08:37Z', 'author_association': 'MEMBER', 'body': "Let's remove these lines in the dataset no? cc @anton-l @Vaibhavs10 ", 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1600562035/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}]
[{'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1602744263', 'html_url': 'https://github.com/huggingface/datasets/issues/5967#issuecomment-1602744263', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5967', 'id': 1602744263, 'node_id': 'IC_kwDODunzps5fh-_H', 'user': {'login': 'lhoestq', 'id': 42851186, 'node_id': 'MDQ6VXNlcjQyODUxMTg2', 'avatar_url': 'https://avatars.githubusercontent.com/u/42851186?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/lhoestq', 'html_url': 'https://github.com/lhoestq', 'followers_url': 'https://api.github.com/users/lhoestq/followers', 'following_url': 'https://api.github.com/users/lhoestq/following{/other_user}', 'gists_url': 'https://api.github.com/users/lhoestq/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/lhoestq/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/lhoestq/subscriptions', 'organizations_url': 'https://api.github.com/users/lhoestq/orgs', 'repos_url': 'https://api.github.com/users/lhoestq/repos', 'events_url': 'https://api.github.com/users/lhoestq/events{/privacy}', 'received_events_url': 'https://api.github.com/users/lhoestq/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-22T14:30:02Z', 'updated_at': '2023-06-22T14:30:02Z', 'author_association': 'MEMBER', 'body': "This must be due to DatasetInfo.from_merge which drops them and is used in `concatenate_datasets`.\r\n\r\nAnd you're experiencing this issue because multiprocessing does concatenate the resulting datasets from each process.\r\n\r\nMaybe they should be kept if all the subdatasets share the same values for config_name and split", 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1602744263/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1611026405', 'html_url': 'https://github.com/huggingface/datasets/issues/5967#issuecomment-1611026405', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5967', 'id': 1611026405, 'node_id': 'IC_kwDODunzps5gBk_l', 'user': {'login': 'sanchit-gandhi', 'id': 93869735, 'node_id': 'U_kgDOBZhWpw', 'avatar_url': 'https://avatars.githubusercontent.com/u/93869735?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/sanchit-gandhi', 'html_url': 'https://github.com/sanchit-gandhi', 'followers_url': 'https://api.github.com/users/sanchit-gandhi/followers', 'following_url': 'https://api.github.com/users/sanchit-gandhi/following{/other_user}', 'gists_url': 'https://api.github.com/users/sanchit-gandhi/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/sanchit-gandhi/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/sanchit-gandhi/subscriptions', 'organizations_url': 'https://api.github.com/users/sanchit-gandhi/orgs', 'repos_url': 'https://api.github.com/users/sanchit-gandhi/repos', 'events_url': 'https://api.github.com/users/sanchit-gandhi/events{/privacy}', 'received_events_url': 'https://api.github.com/users/sanchit-gandhi/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-28T08:55:25Z', 'updated_at': '2023-06-28T08:55:25Z', 'author_association': 'CONTRIBUTOR', 'body': 'That sounds like a clean workaround!', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1611026405/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}]

[{'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1597497151', 'html_url': 'https://github.com/huggingface/datasets/pull/5966#issuecomment-1597497151', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5966', 'id': 1597497151, 'node_id': 'IC_kwDODunzps5fN98_', 'user': {'login': 'github-actions[bot]', 'id': 41898282, 'node_id': 'MDM6Qm90NDE4OTgyODI=', 'avatar_url': 'https://avatars.githubusercontent.com/in/15368?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/github-actions%5Bbot%5D', 'html_url': 'https://github.com/apps/github-actions', 'followers_url': 'https://api.github.com/users/github-actions%5Bbot%5D/followers', 'following_url': 'https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}', 'gists_url': 'https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/github-actions%5Bbot%5D/subscriptions', 'organizations_url': 'https://api.github.com/users/github-actions%5Bbot%5D/orgs', 'repos_url': 'https://api.github.com/users/github-actions%5Bbot%5D/repos', 'events_url': 'https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}', 'received_events_url': 'https://api.github.com/users/github-actions%5Bbot%5D/received_events', 'type': 'Bot', 'site_admin': False}, 'created_at': '2023-06-19T17:02:23Z', 'updated_at': '2023-06-19T17:02:23Z', 'author_association': 'NONE', 'body': '<details>\n<summary>Show benchmarks</summary>\n\nPyArrow==8.0.0\n\n<details>\n<summary>Show updated benchmarks!</summary>\n\n### Benchmark: benchmark_array_xd.json\n\n| metric | read_batch_formatted_as_numpy after write_array2d | read_batch_formatted_as_numpy after write_flattened_sequence | read_batch_formatted_as_numpy after write_nested_sequence | read_batch_unformated after write_array2d | read_batch_unformated after write_flattened_sequence | read_batch_unformated after write_nested_sequence | read_col_formatted_as_numpy after write_array2d | read_col_formatted_as_numpy after write_flattened_sequence | read_col_formatted_as_numpy after write_nested_sequence | read_col_unformated after write_array2d | read_col_unformated after write_flattened_sequence | read_col_unformated after write_nested_sequence | read_formatted_as_numpy after write_array2d | read_formatted_as_numpy after write_flattened_sequence | read_formatted_as_numpy after write_nested_sequence | read_unformated after write_array2d | read_unformated after write_flattened_sequence | read_unformated after write_nested_sequence | write_array2d | write_flattened_sequence | write_nested_sequence |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.006186 / 0.011353 (-0.005167) | 0.003744 / 0.011008 (-0.007264) | 0.097295 / 0.038508 (0.058787) | 0.037106 / 0.023109 (0.013997) | 0.424154 / 0.275898 (0.148256) | 0.474536 / 0.323480 (0.151057) | 0.003454 / 0.007986 (-0.004532) | 0.003865 / 0.004328 (-0.000463) | 0.077348 / 0.004250 (0.073097) | 0.051728 / 0.037052 (0.014675) | 0.437120 / 0.258489 (0.178631) | 0.478379 / 0.293841 (0.184538) | 0.028939 / 0.128546 (-0.099608) | 0.008376 / 0.075646 (-0.067270) | 0.312002 / 0.419271 (-0.107270) | 0.053723 / 0.043533 (0.010190) | 0.424815 / 0.255139 (0.169676) | 0.446203 / 0.283200 (0.163004) | 0.026553 / 0.141683 (-0.115130) | 1.479983 / 1.452155 (0.027828) | 1.530613 / 1.492716 (0.037896) |\n\n### Benchmark: benchmark_getitem\\_100B.json\n\n| metric | get_batch_of\\_1024\\_random_rows | get_batch_of\\_1024\\_rows | get_first_row | get_last_row |\n|--------|---|---|---|---|\n| new / old (diff) | 0.196627 / 0.018006 (0.178620) | 0.422361 / 0.000490 (0.421871) | 0.003442 / 0.000200 (0.003242) | 0.000077 / 0.000054 (0.000023) |\n\n### Benchmark: benchmark_indices_mapping.json\n\n| metric | select | shard | shuffle | sort | train_test_split |\n|--------|---|---|---|---|---|\n| new / old (diff) | 0.022913 / 0.037411 (-0.014499) | 0.096011 / 0.014526 (0.081485) | 0.104091 / 0.176557 (-0.072466) | 0.163273 / 0.737135 (-0.573862) | 0.109142 / 0.296338 (-0.187197) |\n\n### Benchmark: benchmark_iterating.json\n\n| metric | read 5000 | read 50000 | read_batch 50000 10 | read_batch 50000 100 | read_batch 50000 1000 | read_formatted numpy 5000 | read_formatted pandas 5000 | read_formatted tensorflow 5000 | read_formatted torch 5000 | read_formatted_batch numpy 5000 10 | read_formatted_batch numpy 5000 1000 | shuffled read 5000 | shuffled read 50000 | shuffled read_batch 50000 10 | shuffled read_batch 50000 100 | shuffled read_batch 50000 1000 | shuffled read_formatted numpy 5000 | shuffled read_formatted_batch numpy 5000 10 | shuffled read_formatted_batch numpy 5000 1000 |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.431032 / 0.215209 (0.215823) | 4.314391 / 2.077655 (2.236737) | 2.003812 / 1.504120 (0.499692) | 1.799538 / 1.541195 (0.258344) | 1.830026 / 1.468490 (0.361536) | 0.560131 / 4.584777 (-4.024646) | 3.368997 / 3.745712 (-0.376715) | 1.703032 / 5.269862 (-3.566830) | 1.026949 / 4.565676 (-3.538727) | 0.067507 / 0.424275 (-0.356768) | 0.010910 / 0.007607 (0.003303) | 0.532606 / 0.226044 (0.306562) | 5.345179 / 2.268929 (3.076250) | 2.368077 / 55.444624 (-53.076548) | 2.028913 / 6.876477 (-4.847564) | 2.147621 / 2.142072 (0.005549) | 0.675696 / 4.805227 (-4.129531) | 0.134902 / 6.500664 (-6.365762) | 0.065004 / 0.075469 (-0.010465) |\n\n### Benchmark: benchmark_map_filter.json\n\n| metric | filter | map fast-tokenizer batched | map identity | map identity batched | map no-op batched | map no-op batched numpy | map no-op batched pandas | map no-op batched pytorch | map no-op batched tensorflow |\n|--------|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 1.233412 / 1.841788 (-0.608376) | 13.767465 / 8.074308 (5.693157) | 13.933653 / 10.191392 (3.742261) | 0.129010 / 0.680424 (-0.551414) | 0.016708 / 0.534201 (-0.517493) | 0.362341 / 0.579283 (-0.216942) | 0.390902 / 0.434364 (-0.043462) | 0.429156 / 0.540337 (-0.111182) | 0.521166 / 1.386936 (-0.865770) |\n\n</details>\nPyArrow==latest\n\n<details>\n<summary>Show updated benchmarks!</summary>\n\n### Benchmark: benchmark_array_xd.json\n\n| metric | read_batch_formatted_as_numpy after write_array2d | read_batch_formatted_as_numpy after write_flattened_sequence | read_batch_formatted_as_numpy after write_nested_sequence | read_batch_unformated after write_array2d | read_batch_unformated after write_flattened_sequence | read_batch_unformated after write_nested_sequence | read_col_formatted_as_numpy after write_array2d | read_col_formatted_as_numpy after write_flattened_sequence | read_col_formatted_as_numpy after write_nested_sequence | read_col_unformated after write_array2d | read_col_unformated after write_flattened_sequence | read_col_unformated after write_nested_sequence | read_formatted_as_numpy after write_array2d | read_formatted_as_numpy after write_flattened_sequence | read_formatted_as_numpy after write_nested_sequence | read_unformated after write_array2d | read_unformated after write_flattened_sequence | read_unformated after write_nested_sequence | write_array2d | write_flattened_sequence | write_nested_sequence |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.006169 / 0.011353 (-0.005184) | 0.003839 / 0.011008 (-0.007169) | 0.078784 / 0.038508 (0.040276) | 0.040218 / 0.023109 (0.017109) | 0.360439 / 0.275898 (0.084541) | 0.423957 / 0.323480 (0.100477) | 0.003456 / 0.007986 (-0.004529) | 0.002900 / 0.004328 (-0.001428) | 0.078820 / 0.004250 (0.074569) | 0.047240 / 0.037052 (0.010187) | 0.372081 / 0.258489 (0.113592) | 0.424263 / 0.293841 (0.130422) | 0.027977 / 0.128546 (-0.100569) | 0.008400 / 0.075646 (-0.067246) | 0.084399 / 0.419271 (-0.334872) | 0.043303 / 0.043533 (-0.000230) | 0.361583 / 0.255139 (0.106444) | 0.394987 / 0.283200 (0.111787) | 0.020006 / 0.141683 (-0.121677) | 1.520208 / 1.452155 (0.068053) | 1.587335 / 1.492716 (0.094619) |\n\n### Benchmark: benchmark_getitem\\_100B.json\n\n| metric | get_batch_of\\_1024\\_random_rows | get_batch_of\\_1024\\_rows | get_first_row | get_last_row |\n|--------|---|---|---|---|\n| new / old (diff) | 0.223847 / 0.018006 (0.205840) | 0.402194 / 0.000490 (0.401704) | 0.000384 / 0.000200 (0.000184) | 0.000057 / 0.000054 (0.000003) |\n\n### Benchmark: benchmark_indices_mapping.json\n\n| metric | select | shard | shuffle | sort | train_test_split |\n|--------|---|---|---|---|---|\n| new / old (diff) | 0.024902 / 0.037411 (-0.012509) | 0.099076 / 0.014526 (0.084550) | 0.108041 / 0.176557 (-0.068516) | 0.159385 / 0.737135 (-0.577750) | 0.111442 / 0.296338 (-0.184896) |\n\n### Benchmark: benchmark_iterating.json\n\n| metric | read 5000 | read 50000 | read_batch 50000 10 | read_batch 50000 100 | read_batch 50000 1000 | read_formatted numpy 5000 | read_formatted pandas 5000 | read_formatted tensorflow 5000 | read_formatted torch 5000 | read_formatted_batch numpy 5000 10 | read_formatted_batch numpy 5000 1000 | shuffled read 5000 | shuffled read 50000 | shuffled read_batch 50000 10 | shuffled read_batch 50000 100 | shuffled read_batch 50000 1000 | shuffled read_formatted numpy 5000 | shuffled read_formatted_batch numpy 5000 10 | shuffled read_formatted_batch numpy 5000 1000 |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.446232 / 0.215209 (0.231023) | 4.464927 / 2.077655 (2.387272) | 2.155234 / 1.504120 (0.651114) | 1.953645 / 1.541195 (0.412450) | 1.965991 / 1.468490 (0.497501) | 0.553473 / 4.584777 (-4.031304) | 3.321397 / 3.745712 (-0.424315) | 1.693761 / 5.269862 (-3.576101) | 1.006299 / 4.565676 (-3.559378) | 0.067013 / 0.424275 (-0.357262) | 0.011116 / 0.007607 (0.003509) | 0.555014 / 0.226044 (0.328970) | 5.535694 / 2.268929 (3.266765) | 2.598339 / 55.444624 (-52.846285) | 2.249298 / 6.876477 (-4.627179) | 2.243419 / 2.142072 (0.101347) | 0.667603 / 4.805227 (-4.137624) | 0.133322 / 6.500664 (-6.367343) | 0.065473 / 0.075469 (-0.009996) |\n\n### Benchmark: benchmark_map_filter.json\n\n| metric | filter | map fast-tokenizer batched | map identity | map identity batched | map no-op batched | map no-op batched numpy | map no-op batched pandas | map no-op batched pytorch | map no-op batched tensorflow |\n|--------|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 1.293051 / 1.841788 (-0.548737) | 14.103731 / 8.074308 (6.029423) | 14.215204 / 10.191392 (4.023812) | 0.143990 / 0.680424 (-0.536434) | 0.016805 / 0.534201 (-0.517396) | 0.363264 / 0.579283 (-0.216019) | 0.392769 / 0.434364 (-0.041594) | 0.425291 / 0.540337 (-0.115046) | 0.515479 / 1.386936 (-0.871457) |\n\n</details>\n</details>\n\n![](https://cml.dev/watermark.png#e03a58f3f5d7e6f07279fb833e62d859a0babaad "CML watermark")\n', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1597497151/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1597497412', 'html_url': 'https://github.com/huggingface/datasets/pull/5966#issuecomment-1597497412', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5966', 'id': 1597497412, 'node_id': 'IC_kwDODunzps5fN-BE', 'user': {'login': 'HuggingFaceDocBuilderDev', 'id': 99929124, 'node_id': 'U_kgDOBfTMJA', 'avatar_url': 'https://avatars.githubusercontent.com/u/99929124?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/HuggingFaceDocBuilderDev', 'html_url': 'https://github.com/HuggingFaceDocBuilderDev', 'followers_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/followers', 'following_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/following{/other_user}', 'gists_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/subscriptions', 'organizations_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/orgs', 'repos_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/repos', 'events_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/events{/privacy}', 'received_events_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-19T17:02:34Z', 'updated_at': '2023-06-19T17:22:36Z', 'author_association': 'NONE', 'body': '_The documentation is not available anymore as the PR was closed or merged._', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1597497412/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1597524920', 'html_url': 'https://github.com/huggingface/datasets/pull/5966#issuecomment-1597524920', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5966', 'id': 1597524920, 'node_id': 'IC_kwDODunzps5fOEu4', 'user': {'login': 'github-actions[bot]', 'id': 41898282, 'node_id': 'MDM6Qm90NDE4OTgyODI=', 'avatar_url': 'https://avatars.githubusercontent.com/in/15368?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/github-actions%5Bbot%5D', 'html_url': 'https://github.com/apps/github-actions', 'followers_url': 'https://api.github.com/users/github-actions%5Bbot%5D/followers', 'following_url': 'https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}', 'gists_url': 'https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/github-actions%5Bbot%5D/subscriptions', 'organizations_url': 'https://api.github.com/users/github-actions%5Bbot%5D/orgs', 'repos_url': 'https://api.github.com/users/github-actions%5Bbot%5D/repos', 'events_url': 'https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}', 'received_events_url': 'https://api.github.com/users/github-actions%5Bbot%5D/received_events', 'type': 'Bot', 'site_admin': False}, 'created_at': '2023-06-19T17:29:11Z', 'updated_at': '2023-06-19T17:29:11Z', 'author_association': 'NONE', 'body': '<details>\n<summary>Show benchmarks</summary>\n\nPyArrow==8.0.0\n\n<details>\n<summary>Show updated benchmarks!</summary>\n\n### Benchmark: benchmark_array_xd.json\n\n| metric | read_batch_formatted_as_numpy after write_array2d | read_batch_formatted_as_numpy after write_flattened_sequence | read_batch_formatted_as_numpy after write_nested_sequence | read_batch_unformated after write_array2d | read_batch_unformated after write_flattened_sequence | read_batch_unformated after write_nested_sequence | read_col_formatted_as_numpy after write_array2d | read_col_formatted_as_numpy after write_flattened_sequence | read_col_formatted_as_numpy after write_nested_sequence | read_col_unformated after write_array2d | read_col_unformated after write_flattened_sequence | read_col_unformated after write_nested_sequence | read_formatted_as_numpy after write_array2d | read_formatted_as_numpy after write_flattened_sequence | read_formatted_as_numpy after write_nested_sequence | read_unformated after write_array2d | read_unformated after write_flattened_sequence | read_unformated after write_nested_sequence | write_array2d | write_flattened_sequence | write_nested_sequence |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.006346 / 0.011353 (-0.005006) | 0.004130 / 0.011008 (-0.006878) | 0.096898 / 0.038508 (0.058390) | 0.042564 / 0.023109 (0.019455) | 0.343748 / 0.275898 (0.067850) | 0.412515 / 0.323480 (0.089035) | 0.006153 / 0.007986 (-0.001833) | 0.003345 / 0.004328 (-0.000984) | 0.075314 / 0.004250 (0.071064) | 0.061478 / 0.037052 (0.024426) | 0.362948 / 0.258489 (0.104459) | 0.401533 / 0.293841 (0.107692) | 0.032363 / 0.128546 (-0.096184) | 0.008780 / 0.075646 (-0.066867) | 0.328691 / 0.419271 (-0.090580) | 0.054253 / 0.043533 (0.010721) | 0.340783 / 0.255139 (0.085644) | 0.360705 / 0.283200 (0.077505) | 0.023183 / 0.141683 (-0.118500) | 1.484078 / 1.452155 (0.031924) | 1.528581 / 1.492716 (0.035865) |\n\n### Benchmark: benchmark_getitem\\_100B.json\n\n| metric | get_batch_of\\_1024\\_random_rows | get_batch_of\\_1024\\_rows | get_first_row | get_last_row |\n|--------|---|---|---|---|\n| new / old (diff) | 0.208732 / 0.018006 (0.190726) | 0.452572 / 0.000490 (0.452082) | 0.002936 / 0.000200 (0.002737) | 0.000082 / 0.000054 (0.000028) |\n\n### Benchmark: benchmark_indices_mapping.json\n\n| metric | select | shard | shuffle | sort | train_test_split |\n|--------|---|---|---|---|---|\n| new / old (diff) | 0.024616 / 0.037411 (-0.012795) | 0.107547 / 0.014526 (0.093021) | 0.114492 / 0.176557 (-0.062065) | 0.171770 / 0.737135 (-0.565365) | 0.122538 / 0.296338 (-0.173800) |\n\n### Benchmark: benchmark_iterating.json\n\n| metric | read 5000 | read 50000 | read_batch 50000 10 | read_batch 50000 100 | read_batch 50000 1000 | read_formatted numpy 5000 | read_formatted pandas 5000 | read_formatted tensorflow 5000 | read_formatted torch 5000 | read_formatted_batch numpy 5000 10 | read_formatted_batch numpy 5000 1000 | shuffled read 5000 | shuffled read 50000 | shuffled read_batch 50000 10 | shuffled read_batch 50000 100 | shuffled read_batch 50000 1000 | shuffled read_formatted numpy 5000 | shuffled read_formatted_batch numpy 5000 10 | shuffled read_formatted_batch numpy 5000 1000 |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.406140 / 0.215209 (0.190930) | 4.062391 / 2.077655 (1.984736) | 1.865962 / 1.504120 (0.361842) | 1.682236 / 1.541195 (0.141041) | 1.738119 / 1.468490 (0.269629) | 0.532244 / 4.584777 (-4.052533) | 3.816421 / 3.745712 (0.070709) | 2.981205 / 5.269862 (-2.288656) | 1.519497 / 4.565676 (-3.046179) | 0.065904 / 0.424275 (-0.358371) | 0.011277 / 0.007607 (0.003670) | 0.512789 / 0.226044 (0.286745) | 5.107618 / 2.268929 (2.838690) | 2.419399 / 55.444624 (-53.025226) | 2.079262 / 6.876477 (-4.797214) | 2.150447 / 2.142072 (0.008375) | 0.696737 / 4.805227 (-4.108490) | 0.142497 / 6.500664 (-6.358167) | 0.063521 / 0.075469 (-0.011949) |\n\n### Benchmark: benchmark_map_filter.json\n\n| metric | filter | map fast-tokenizer batched | map identity | map identity batched | map no-op batched | map no-op batched numpy | map no-op batched pandas | map no-op batched pytorch | map no-op batched tensorflow |\n|--------|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 1.180692 / 1.841788 (-0.661095) | 14.343084 / 8.074308 (6.268776) | 13.303719 / 10.191392 (3.112327) | 0.164234 / 0.680424 (-0.516190) | 0.017439 / 0.534201 (-0.516762) | 0.399712 / 0.579283 (-0.179571) | 0.428248 / 0.434364 (-0.006115) | 0.471909 / 0.540337 (-0.068428) | 0.573853 / 1.386936 (-0.813083) |\n\n</details>\nPyArrow==latest\n\n<details>\n<summary>Show updated benchmarks!</summary>\n\n### Benchmark: benchmark_array_xd.json\n\n| metric | read_batch_formatted_as_numpy after write_array2d | read_batch_formatted_as_numpy after write_flattened_sequence | read_batch_formatted_as_numpy after write_nested_sequence | read_batch_unformated after write_array2d | read_batch_unformated after write_flattened_sequence | read_batch_unformated after write_nested_sequence | read_col_formatted_as_numpy after write_array2d | read_col_formatted_as_numpy after write_flattened_sequence | read_col_formatted_as_numpy after write_nest

[{'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1601542007', 'html_url': 'https://github.com/huggingface/datasets/issues/5965#issuecomment-1601542007', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5965', 'id': 1601542007, 'node_id': 'IC_kwDODunzps5fdZd3', 'user': {'login': 'mariosasko', 'id': 47462742, 'node_id': 'MDQ6VXNlcjQ3NDYyNzQy', 'avatar_url': 'https://avatars.githubusercontent.com/u/47462742?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/mariosasko', 'html_url': 'https://github.com/mariosasko', 'followers_url': 'https://api.github.com/users/mariosasko/followers', 'following_url': 'https://api.github.com/users/mariosasko/following{/other_user}', 'gists_url': 'https://api.github.com/users/mariosasko/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/mariosasko/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/mariosasko/subscriptions', 'organizations_url': 'https://api.github.com/users/mariosasko/orgs', 'repos_url': 'https://api.github.com/users/mariosasko/repos', 'events_url': 'https://api.github.com/users/mariosasko/events{/privacy}', 'received_events_url': 'https://api.github.com/users/mariosasko/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-21T19:21:09Z', 'updated_at': '2023-06-21T19:21:09Z', 'author_association': 'CONTRIBUTOR', 'body': 'Thanks for reporting! \r\n\r\nSpecifying the target features explicitly should avoid this error:\r\n```python\r\ndataset = dataset.map(\r\n    batch_process,\r\n    batched=True,\r\n    batch_size=1,\r\n    num_proc=1,\r\n    remove_columns=dataset.column_names,\r\n    features=datasets.Features({"texts": datasets.Sequence(datasets.Value("string"))})\r\n)\r\n```\r\n\r\nThis error stems from our type promotion not handling the nested case. But this promotion/casting allocates memory in most scenarios, which can be problematic for large datasets, so explicitly passing the features is the optimal solution.', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1601542007/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1601563320', 'html_url': 'https://github.com/huggingface/datasets/issues/5965#issuecomment-1601563320', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5965', 'id': 1601563320, 'node_id': 'IC_kwDODunzps5fdeq4', 'user': {'login': 'piercefreeman', 'id': 1712066, 'node_id': 'MDQ6VXNlcjE3MTIwNjY=', 'avatar_url': 'https://avatars.githubusercontent.com/u/1712066?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/piercefreeman', 'html_url': 'https://github.com/piercefreeman', 'followers_url': 'https://api.github.com/users/piercefreeman/followers', 'following_url': 'https://api.github.com/users/piercefreeman/following{/other_user}', 'gists_url': 'https://api.github.com/users/piercefreeman/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/piercefreeman/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/piercefreeman/subscriptions', 'organizations_url': 'https://api.github.com/users/piercefreeman/orgs', 'repos_url': 'https://api.github.com/users/piercefreeman/repos', 'events_url': 'https://api.github.com/users/piercefreeman/events{/privacy}', 'received_events_url': 'https://api.github.com/users/piercefreeman/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-21T19:35:37Z', 'updated_at': '2023-06-21T19:35:37Z', 'author_association': 'NONE', 'body': 'Hi @mariosasko thanks for the context, this is helpful to know. Would it be worth having some logic to generate this explicit feature specification automatically if a type annotation for a .map returns a dataclass that can be inferred?\r\n\r\nFeels like something that would be easy to implement and could save memory / deal with this case in a standardized way.', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1601563320/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1601590228', 'html_url': 'https://github.com/huggingface/datasets/issues/5965#issuecomment-1601590228', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5965', 'id': 1601590228, 'node_id': 'IC_kwDODunzps5fdlPU', 'user': {'login': 'mariosasko', 'id': 47462742, 'node_id': 'MDQ6VXNlcjQ3NDYyNzQy', 'avatar_url': 'https://avatars.githubusercontent.com/u/47462742?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/mariosasko', 'html_url': 'https://github.com/mariosasko', 'followers_url': 'https://api.github.com/users/mariosasko/followers', 'following_url': 'https://api.github.com/users/mariosasko/following{/other_user}', 'gists_url': 'https://api.github.com/users/mariosasko/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/mariosasko/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/mariosasko/subscriptions', 'organizations_url': 'https://api.github.com/users/mariosasko/orgs', 'repos_url': 'https://api.github.com/users/mariosasko/repos', 'events_url': 'https://api.github.com/users/mariosasko/events{/privacy}', 'received_events_url': 'https://api.github.com/users/mariosasko/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-21T19:59:53Z', 'updated_at': '2023-06-21T20:00:03Z', 'author_association': 'CONTRIBUTOR', 'body': '> . Would it be worth having some logic to generate this explicit feature specification automatically if a type annotation for a .map returns a dataclass that can be inferred?\r\n\r\nInteresting proposal! Yes, we could consider doing this if the (return) type hint is `TypedDict`, and raise an error that type hints are incorrect if the cast using the inferred types fails.', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1601590228/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}]
[{'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1597170512', 'html_url': 'https://github.com/huggingface/datasets/pull/5964#issuecomment-1597170512', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5964', 'id': 1597170512, 'node_id': 'IC_kwDODunzps5fMuNQ', 'user': {'login': 'HuggingFaceDocBuilderDev', 'id': 99929124, 'node_id': 'U_kgDOBfTMJA', 'avatar_url': 'https://avatars.githubusercontent.com/u/99929124?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/HuggingFaceDocBuilderDev', 'html_url': 'https://github.com/HuggingFaceDocBuilderDev', 'followers_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/followers', 'following_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/following{/other_user}', 'gists_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/subscriptions', 'organizations_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/orgs', 'repos_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/repos', 'events_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/events{/privacy}', 'received_events_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-19T13:12:33Z', 'updated_at': '2023-06-19T17:23:12Z', 'author_association': 'NONE', 'body': '_The documentation is not available anymore as the PR was closed or merged._', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1597170512/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1597525248', 'html_url': 'https://github.com/huggingface/datasets/pull/5964#issuecomment-1597525248', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5964', 'id': 1597525248, 'node_id': 'IC_kwDODunzps5fOE0A', 'user': {'login': 'github-actions[bot]', 'id': 41898282, 'node_id': 'MDM6Qm90NDE4OTgyODI=', 'avatar_url': 'https://avatars.githubusercontent.com/in/15368?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/github-actions%5Bbot%5D', 'html_url': 'https://github.com/apps/github-actions', 'followers_url': 'https://api.github.com/users/github-actions%5Bbot%5D/followers', 'following_url': 'https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}', 'gists_url': 'https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/github-actions%5Bbot%5D/subscriptions', 'organizations_url': 'https://api.github.com/users/github-actions%5Bbot%5D/orgs', 'repos_url': 'https://api.github.com/users/github-actions%5Bbot%5D/repos', 'events_url': 'https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}', 'received_events_url': 'https://api.github.com/users/github-actions%5Bbot%5D/received_events', 'type': 'Bot', 'site_admin': False}, 'created_at': '2023-06-19T17:29:36Z', 'updated_at': '2023-06-19T17:29:36Z', 'author_association': 'NONE', 'body': '<details>\n<summary>Show benchmarks</summary>\n\nPyArrow==8.0.0\n\n<details>\n<summary>Show updated benchmarks!</summary>\n\n### Benchmark: benchmark_array_xd.json\n\n| metric | read_batch_formatted_as_numpy after write_array2d | read_batch_formatted_as_numpy after write_flattened_sequence | read_batch_formatted_as_numpy after write_nested_sequence | read_batch_unformated after write_array2d | read_batch_unformated after write_flattened_sequence | read_batch_unformated after write_nested_sequence | read_col_formatted_as_numpy after write_array2d | read_col_formatted_as_numpy after write_flattened_sequence | read_col_formatted_as_numpy after write_nested_sequence | read_col_unformated after write_array2d | read_col_unformated after write_flattened_sequence | read_col_unformated after write_nested_sequence | read_formatted_as_numpy after write_array2d | read_formatted_as_numpy after write_flattened_sequence | read_formatted_as_numpy after write_nested_sequence | read_unformated after write_array2d | read_unformated after write_flattened_sequence | read_unformated after write_nested_sequence | write_array2d | write_flattened_sequence | write_nested_sequence |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.006795 / 0.011353 (-0.004558) | 0.004170 / 0.011008 (-0.006838) | 0.098698 / 0.038508 (0.060190) | 0.045393 / 0.023109 (0.022284) | 0.309205 / 0.275898 (0.033307) | 0.361333 / 0.323480 (0.037853) | 0.006009 / 0.007986 (-0.001977) | 0.003334 / 0.004328 (-0.000995) | 0.075071 / 0.004250 (0.070821) | 0.062587 / 0.037052 (0.025535) | 0.322395 / 0.258489 (0.063906) | 0.360499 / 0.293841 (0.066659) | 0.032243 / 0.128546 (-0.096303) | 0.008768 / 0.075646 (-0.066878) | 0.329799 / 0.419271 (-0.089472) | 0.062261 / 0.043533 (0.018728) | 0.298112 / 0.255139 (0.042973) | 0.322815 / 0.283200 (0.039615) | 0.032348 / 0.141683 (-0.109335) | 1.445807 / 1.452155 (-0.006347) | 1.528768 / 1.492716 (0.036051) |\n\n### Benchmark: benchmark_getitem\\_100B.json\n\n| metric | get_batch_of\\_1024\\_random_rows | get_batch_of\\_1024\\_rows | get_first_row | get_last_row |\n|--------|---|---|---|---|\n| new / old (diff) | 0.195701 / 0.018006 (0.177695) | 0.437042 / 0.000490 (0.436552) | 0.003867 / 0.000200 (0.003667) | 0.000080 / 0.000054 (0.000026) |\n\n### Benchmark: benchmark_indices_mapping.json\n\n| metric | select | shard | shuffle | sort | train_test_split |\n|--------|---|---|---|---|---|\n| new / old (diff) | 0.026713 / 0.037411 (-0.010698) | 0.109548 / 0.014526 (0.095022) | 0.119216 / 0.176557 (-0.057341) | 0.178947 / 0.737135 (-0.558188) | 0.125224 / 0.296338 (-0.171114) |\n\n### Benchmark: benchmark_iterating.json\n\n| metric | read 5000 | read 50000 | read_batch 50000 10 | read_batch 50000 100 | read_batch 50000 1000 | read_formatted numpy 5000 | read_formatted pandas 5000 | read_formatted tensorflow 5000 | read_formatted torch 5000 | read_formatted_batch numpy 5000 10 | read_formatted_batch numpy 5000 1000 | shuffled read 5000 | shuffled read 50000 | shuffled read_batch 50000 10 | shuffled read_batch 50000 100 | shuffled read_batch 50000 1000 | shuffled read_formatted numpy 5000 | shuffled read_formatted_batch numpy 5000 10 | shuffled read_formatted_batch numpy 5000 1000 |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.400885 / 0.215209 (0.185676) | 3.991223 / 2.077655 (1.913568) | 1.818449 / 1.504120 (0.314329) | 1.609285 / 1.541195 (0.068090) | 1.666675 / 1.468490 (0.198184) | 0.531486 / 4.584777 (-4.053291) | 3.770142 / 3.745712 (0.024430) | 3.057189 / 5.269862 (-2.212673) | 1.517491 / 4.565676 (-3.048186) | 0.065782 / 0.424275 (-0.358493) | 0.011251 / 0.007607 (0.003644) | 0.504277 / 0.226044 (0.278233) | 5.038979 / 2.268929 (2.770050) | 2.254717 / 55.444624 (-53.189908) | 1.929743 / 6.876477 (-4.946734) | 2.080051 / 2.142072 (-0.062022) | 0.656831 / 4.805227 (-4.148396) | 0.142860 / 6.500664 (-6.357804) | 0.063057 / 0.075469 (-0.012412) |\n\n### Benchmark: benchmark_map_filter.json\n\n| metric | filter | map fast-tokenizer batched | map identity | map identity batched | map no-op batched | map no-op batched numpy | map no-op batched pandas | map no-op batched pytorch | map no-op batched tensorflow |\n|--------|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 1.208819 / 1.841788 (-0.632969) | 14.456966 / 8.074308 (6.382658) | 12.839799 / 10.191392 (2.648407) | 0.164361 / 0.680424 (-0.516063) | 0.017330 / 0.534201 (-0.516871) | 0.397384 / 0.579283 (-0.181899) | 0.422704 / 0.434364 (-0.011660) | 0.472065 / 0.540337 (-0.068273) | 0.576960 / 1.386936 (-0.809976) |\n\n</details>\nPyArrow==latest\n\n<details>\n<summary>Show updated benchmarks!</summary>\n\n### Benchmark: benchmark_array_xd.json\n\n| metric | read_batch_formatted_as_numpy after write_array2d | read_batch_formatted_as_numpy after write_flattened_sequence | read_batch_formatted_as_numpy after write_nested_sequence | read_batch_unformated after write_array2d | read_batch_unformated after write_flattened_sequence | read_batch_unformated after write_nested_sequence | read_col_formatted_as_numpy after write_array2d | read_col_formatted_as_numpy after write_flattened_sequence | read_col_formatted_as_numpy after write_nested_sequence | read_col_unformated after write_array2d | read_col_unformated after write_flattened_sequence | read_col_unformated after write_nested_sequence | read_formatted_as_numpy after write_array2d | read_formatted_as_numpy after write_flattened_sequence | read_formatted_as_numpy after write_nested_sequence | read_unformated after write_array2d | read_unformated after write_flattened_sequence | read_unformated after write_nested_sequence | write_array2d | write_flattened_sequence | write_nested_sequence |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.006950 / 0.011353 (-0.004403) | 0.004012 / 0.011008 (-0.006997) | 0.076050 / 0.038508 (0.037542) | 0.046646 / 0.023109 (0.023537) | 0.353813 / 0.275898 (0.077915) | 0.417111 / 0.323480 (0.093631) | 0.005422 / 0.007986 (-0.002564) | 0.003356 / 0.004328 (-0.000972) | 0.076662 / 0.004250 (0.072411) | 0.055018 / 0.037052 (0.017966) | 0.371561 / 0.258489 (0.113072) | 0.410471 / 0.293841 (0.116630) | 0.031860 / 0.128546 (-0.096686) | 0.008754 / 0.075646 (-0.066893) | 0.083192 / 0.419271 (-0.336079) | 0.050479 / 0.043533 (0.006946) | 0.351725 / 0.255139 (0.096586) | 0.371596 / 0.283200 (0.088396) | 0.023042 / 0.141683 (-0.118641) | 1.480533 / 1.452155 (0.028379) | 1.545970 / 1.492716 (0.053254) |\n\n### Benchmark: benchmark_getitem\\_100B.json\n\n| metric | get_batch_of\\_1024\\_random_rows | get_batch_of\\_1024\\_rows | get_first_row | get_last_row |\n|--------|---|---|---|---|\n| new / old (diff) | 0.220095 / 0.018006 (0.202089) | 0.441550 / 0.000490 (0.441061) | 0.000375 / 0.000200 (0.000175) | 0.000056 / 0.000054 (0.000002) |\n\n### Benchmark: benchmark_indices_mapping.json\n\n| metric | select | shard | shuffle | sort | train_test_split |\n|--------|---|---|---|---|---|\n| new / old (diff) | 0.029527 / 0.037411 (-0.007884) | 0.111645 / 0.014526 (0.097119) | 0.125732 / 0.176557 (-0.050825) | 0.177322 / 0.737135 (-0.559813) | 0.128620 / 0.296338 (-0.167718) |\n\n### Benchmark: benchmark_iterating.json\n\n| metric | read 5000 | read 50000 | read_batch 50000 10 | read_batch 50000 100 | read_batch 50000 1000 | read_formatted numpy 5000 | read_formatted pandas 5000 | read_formatted tensorflow 5000 | read_formatted torch 5000 | read_formatted_batch numpy 5000 10 | read_formatted_batch numpy 5000 1000 | shuffled read 5000 | shuffled read 50000 | shuffled read_batch 50000 10 | shuffled read_batch 50000 100 | shuffled read_batch 50000 1000 | shuffled read_formatted numpy 5000 | shuffled read_formatted_batch numpy 5000 10 | shuffled read_formatted_batch numpy 5000 1000 |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.432415 / 0.215209 (0.217206) | 4.314381 / 2.077655 (2.236726) | 2.079450 / 1.504120 (0.575331) | 1.893139 / 1.541195 (0.351944) | 1.951363 / 1.468490 (0.482873) | 0.531466 / 4.584777 (-4.053311) | 3.716860 / 3.745712 (-0.028852) | 1.850111 / 5.269862 (-3.419750) | 1.100676 / 4.565676 (-3.465000) | 0.066247 / 0.424275 (-0.358028) | 0.011503 / 0.007607 (0.003896) | 0.537208 / 0.226044 (0.311164) | 5.367560 / 2.268929 (3.098631) | 2.543697 / 55.444624 (-52.900927) | 2.221670 / 6.876477 (-4.654806) | 2.252009 / 2.142072 (0.109937) | 0.658509 / 4.805227 (-4.146718) | 0.142345 / 6.500664 (-6.358319) | 0.064701 / 0.075469 (-0.010768) |\n\n### Benchmark: benchmark_map_filter.json\n\n| metric | filter | map fast-tokenizer batched | map identity | map identity batched | map no-op batched | map no-op batched numpy | map no-op batched pandas | map no-op batched pytorch | map no-op batched tensorflow |\n|--------|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 1.266442 / 1.841788 (-0.575346) | 15.105953 / 8.074308 (7.031645) | 14.288229 / 10.191392 (4.096837) | 0.161182 / 0.680424 (-0.519242) | 0.017074 / 0.534201 (-0.517127) | 0.399464 / 0.579283 (-0.179819) | 0.419459 / 0.434364 (-0.014905) | 0.467553 / 0.540337 (-0.072784) | 0.566337 / 1.386936 (-0.820599) |\n\n</details>\n</details>\n\n![](https://cml.dev/watermark.png#53ac2d9662f9e5923ae7c52199eaa620d82f0043 "CML watermark")\n', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1597525248/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}]

[{'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1596531677', 'html_url': 'https://github.com/huggingface/datasets/issues/5963#issuecomment-1596531677', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5963', 'id': 1596531677, 'node_id': 'IC_kwDODunzps5fKSPd', 'user': {'login': 'yanzia12138', 'id': 112800614, 'node_id': 'U_kgDOBrkzZg', 'avatar_url': 'https://avatars.githubusercontent.com/u/112800614?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/yanzia12138', 'html_url': 'https://github.com/yanzia12138', 'followers_url': 'https://api.github.com/users/yanzia12138/followers', 'following_url': 'https://api.github.com/users/yanzia12138/following{/other_user}', 'gists_url': 'https://api.github.com/users/yanzia12138/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/yanzia12138/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/yanzia12138/subscriptions', 'organizations_url': 'https://api.github.com/users/yanzia12138/orgs', 'repos_url': 'https://api.github.com/users/yanzia12138/repos', 'events_url': 'https://api.github.com/users/yanzia12138/events{/privacy}', 'received_events_url': 'https://api.github.com/users/yanzia12138/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-19T05:31:46Z', 'updated_at': '2023-06-19T05:33:39Z', 'author_association': 'NONE', 'body': 'i got error using method from_spark  when using multi-node Spark cluster. seems could only use "from_spark" in local?', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1596531677/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1596700502', 'html_url': 'https://github.com/huggingface/datasets/issues/5963#issuecomment-1596700502', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5963', 'id': 1596700502, 'node_id': 'IC_kwDODunzps5fK7dW', 'user': {'login': 'yanzia12138', 'id': 112800614, 'node_id': 'U_kgDOBrkzZg', 'avatar_url': 'https://avatars.githubusercontent.com/u/112800614?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/yanzia12138', 'html_url': 'https://github.com/yanzia12138', 'followers_url': 'https://api.github.com/users/yanzia12138/followers', 'following_url': 'https://api.github.com/users/yanzia12138/following{/other_user}', 'gists_url': 'https://api.github.com/users/yanzia12138/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/yanzia12138/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/yanzia12138/subscriptions', 'organizations_url': 'https://api.github.com/users/yanzia12138/orgs', 'repos_url': 'https://api.github.com/users/yanzia12138/repos', 'events_url': 'https://api.github.com/users/yanzia12138/events{/privacy}', 'received_events_url': 'https://api.github.com/users/yanzia12138/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-19T08:01:40Z', 'updated_at': '2023-06-19T08:01:40Z', 'author_association': 'NONE', 'body': '@lhoestq ', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1596700502/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1596951620', 'html_url': 'https://github.com/huggingface/datasets/issues/5963#issuecomment-1596951620', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5963', 'id': 1596951620, 'node_id': 'IC_kwDODunzps5fL4xE', 'user': {'login': 'lhoestq', 'id': 42851186, 'node_id': 'MDQ6VXNlcjQyODUxMTg2', 'avatar_url': 'https://avatars.githubusercontent.com/u/42851186?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/lhoestq', 'html_url': 'https://github.com/lhoestq', 'followers_url': 'https://api.github.com/users/lhoestq/followers', 'following_url': 'https://api.github.com/users/lhoestq/following{/other_user}', 'gists_url': 'https://api.github.com/users/lhoestq/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/lhoestq/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/lhoestq/subscriptions', 'organizations_url': 'https://api.github.com/users/lhoestq/orgs', 'repos_url': 'https://api.github.com/users/lhoestq/repos', 'events_url': 'https://api.github.com/users/lhoestq/events{/privacy}', 'received_events_url': 'https://api.github.com/users/lhoestq/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-19T10:44:30Z', 'updated_at': '2023-06-19T10:44:30Z', 'author_association': 'MEMBER', 'body': 'cc @maddiedawson it looks like there an issue with `_validate_cache_dir` ?\r\n\r\nIt looks like the function passed to mapPartitions has a reference to the Spark dataset builder, and therefore contains the SparkContext itself.\r\n\r\nI think it can be fixed by defining `create_cache_and_write_probe` outside the Spark dataset builder, and pass a `partial(create_cache_and_write_probe, cache_dir=self._cache_dir)` to `mapPartitions`', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1596951620/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1608421944', 'html_url': 'https://github.com/huggingface/datasets/issues/5963#issuecomment-1608421944', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5963', 'id': 1608421944, 'node_id': 'IC_kwDODunzps5f3pI4', 'user': {'login': 'maddiedawson', 'id': 106995444, 'node_id': 'U_kgDOBmCe9A', 'avatar_url': 'https://avatars.githubusercontent.com/u/106995444?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/maddiedawson', 'html_url': 'https://github.com/maddiedawson', 'followers_url': 'https://api.github.com/users/maddiedawson/followers', 'following_url': 'https://api.github.com/users/maddiedawson/following{/other_user}', 'gists_url': 'https://api.github.com/users/maddiedawson/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/maddiedawson/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/maddiedawson/subscriptions', 'organizations_url': 'https://api.github.com/users/maddiedawson/orgs', 'repos_url': 'https://api.github.com/users/maddiedawson/repos', 'events_url': 'https://api.github.com/users/maddiedawson/events{/privacy}', 'received_events_url': 'https://api.github.com/users/maddiedawson/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-26T22:48:38Z', 'updated_at': '2023-06-26T22:48:38Z', 'author_association': 'CONTRIBUTOR', 'body': 'Just saw this; thanks for flagging! Your proposed solution sounds good. I can prepare a PR', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1608421944/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1612321233', 'html_url': 'https://github.com/huggingface/datasets/issues/5963#issuecomment-1612321233', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5963', 'id': 1612321233, 'node_id': 'IC_kwDODunzps5gGhHR', 'user': {'login': 'yanzia12138', 'id': 112800614, 'node_id': 'U_kgDOBrkzZg', 'avatar_url': 'https://avatars.githubusercontent.com/u/112800614?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/yanzia12138', 'html_url': 'https://github.com/yanzia12138', 'followers_url': 'https://api.github.com/users/yanzia12138/followers', 'following_url': 'https://api.github.com/users/yanzia12138/following{/other_user}', 'gists_url': 'https://api.github.com/users/yanzia12138/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/yanzia12138/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/yanzia12138/subscriptions', 'organizations_url': 'https://api.github.com/users/yanzia12138/orgs', 'repos_url': 'https://api.github.com/users/yanzia12138/repos', 'events_url': 'https://api.github.com/users/yanzia12138/events{/privacy}', 'received_events_url': 'https://api.github.com/users/yanzia12138/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-29T01:58:26Z', 'updated_at': '2023-06-29T01:58:26Z', 'author_association': 'NONE', 'body': '@maddiedawson  can you show me the demo ,so i can test in local .before your PR', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1612321233/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}]

[]
[{'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1592811547', 'html_url': 'https://github.com/huggingface/datasets/issues/5961#issuecomment-1592811547', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5961', 'id': 1592811547, 'node_id': 'IC_kwDODunzps5e8GAb', 'user': {'login': 'johnchienbronci', 'id': 27708347, 'node_id': 'MDQ6VXNlcjI3NzA4MzQ3', 'avatar_url': 'https://avatars.githubusercontent.com/u/27708347?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/johnchienbronci', 'html_url': 'https://github.com/johnchienbronci', 'followers_url': 'https://api.github.com/users/johnchienbronci/followers', 'following_url': 'https://api.github.com/users/johnchienbronci/following{/other_user}', 'gists_url': 'https://api.github.com/users/johnchienbronci/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/johnchienbronci/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/johnchienbronci/subscriptions', 'organizations_url': 'https://api.github.com/users/johnchienbronci/orgs', 'repos_url': 'https://api.github.com/users/johnchienbronci/repos', 'events_url': 'https://api.github.com/users/johnchienbronci/events{/privacy}', 'received_events_url': 'https://api.github.com/users/johnchienbronci/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-15T10:50:41Z', 'updated_at': '2023-06-15T10:50:41Z', 'author_association': 'NONE', 'body': 'Does "number of shards" refer to the total number of data?\r\n\r\nmy config:\r\nnproc_per_node=2\r\nds=ds[\'train\'] = load_dataset(streaming=True).take(50000)\r\n\r\nI\'m test again: in prepare_data(),  data have the same for each GPU\r\n', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1592811547/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1592831128', 'html_url': 'https://github.com/huggingface/datasets/issues/5961#issuecomment-1592831128', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5961', 'id': 1592831128, 'node_id': 'IC_kwDODunzps5e8KyY', 'user': {'login': 'lhoestq', 'id': 42851186, 'node_id': 'MDQ6VXNlcjQyODUxMTg2', 'avatar_url': 'https://avatars.githubusercontent.com/u/42851186?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/lhoestq', 'html_url': 'https://github.com/lhoestq', 'followers_url': 'https://api.github.com/users/lhoestq/followers', 'following_url': 'https://api.github.com/users/lhoestq/following{/other_user}', 'gists_url': 'https://api.github.com/users/lhoestq/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/lhoestq/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/lhoestq/subscriptions', 'organizations_url': 'https://api.github.com/users/lhoestq/orgs', 'repos_url': 'https://api.github.com/users/lhoestq/repos', 'events_url': 'https://api.github.com/users/lhoestq/events{/privacy}', 'received_events_url': 'https://api.github.com/users/lhoestq/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-15T11:00:31Z', 'updated_at': '2023-06-15T11:00:31Z', 'author_association': 'MEMBER', 'body': "The number of shards is `ds.n_shards`. It corresponds generally to the number of files the dataset is made of, to be able to distribute to several nodes.\r\n\r\n**You don't end up with the same data per GPU**. But all the samples are going through your preprocessing function you pass to map. They are just skipped afterwards to only keep 1 sample out of n(GPUs)", 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1592831128/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1592854470', 'html_url': 'https://github.com/huggingface/datasets/issues/5961#issuecomment-1592854470', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5961', 'id': 1592854470, 'node_id': 'IC_kwDODunzps5e8QfG', 'user': {'login': 'johnchienbronci', 'id': 27708347, 'node_id': 'MDQ6VXNlcjI3NzA4MzQ3', 'avatar_url': 'https://avatars.githubusercontent.com/u/27708347?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/johnchienbronci', 'html_url': 'https://github.com/johnchienbronci', 'followers_url': 'https://api.github.com/users/johnchienbronci/followers', 'following_url': 'https://api.github.com/users/johnchienbronci/following{/other_user}', 'gists_url': 'https://api.github.com/users/johnchienbronci/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/johnchienbronci/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/johnchienbronci/subscriptions', 'organizations_url': 'https://api.github.com/users/johnchienbronci/orgs', 'repos_url': 'https://api.github.com/users/johnchienbronci/repos', 'events_url': 'https://api.github.com/users/johnchienbronci/events{/privacy}', 'received_events_url': 'https://api.github.com/users/johnchienbronci/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-15T11:17:36Z', 'updated_at': '2023-06-15T11:17:36Z', 'author_association': 'NONE', 'body': 'For each GPU, although see the same data in prepare_data(), the actual training data will not be the same in the end. \r\nIs my understanding correct?\r\n\r\nWhere can I print the actual training data for each GPU?', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1592854470/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1592880136', 'html_url': 'https://github.com/huggingface/datasets/issues/5961#issuecomment-1592880136', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5961', 'id': 1592880136, 'node_id': 'IC_kwDODunzps5e8WwI', 'user': {'login': 'lhoestq', 'id': 42851186, 'node_id': 'MDQ6VXNlcjQyODUxMTg2', 'avatar_url': 'https://avatars.githubusercontent.com/u/42851186?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/lhoestq', 'html_url': 'https://github.com/lhoestq', 'followers_url': 'https://api.github.com/users/lhoestq/followers', 'following_url': 'https://api.github.com/users/lhoestq/following{/other_user}', 'gists_url': 'https://api.github.com/users/lhoestq/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/lhoestq/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/lhoestq/subscriptions', 'organizations_url': 'https://api.github.com/users/lhoestq/orgs', 'repos_url': 'https://api.github.com/users/lhoestq/repos', 'events_url': 'https://api.github.com/users/lhoestq/events{/privacy}', 'received_events_url': 'https://api.github.com/users/lhoestq/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-15T11:39:25Z', 'updated_at': '2023-06-15T11:39:25Z', 'author_association': 'MEMBER', 'body': '> For each GPU, although see the same data in prepare_data(), the actual training data will not be the same in the end.\r\nIs my understanding correct?\r\n\r\nYes exactly :)\r\n\r\n> Where can I print the actual training data for each GPU?\r\n\r\nYou should call print in the data_collator', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1592880136/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1595674774', 'html_url': 'https://github.com/huggingface/datasets/issues/5961#issuecomment-1595674774', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5961', 'id': 1595674774, 'node_id': 'IC_kwDODunzps5fHBCW', 'user': {'login': 'johnchienbronci', 'id': 27708347, 'node_id': 'MDQ6VXNlcjI3NzA4MzQ3', 'avatar_url': 'https://avatars.githubusercontent.com/u/27708347?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/johnchienbronci', 'html_url': 'https://github.com/johnchienbronci', 'followers_url': 'https://api.github.com/users/johnchienbronci/followers', 'following_url': 'https://api.github.com/users/johnchienbronci/following{/other_user}', 'gists_url': 'https://api.github.com/users/johnchienbronci/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/johnchienbronci/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/johnchienbronci/subscriptions', 'organizations_url': 'https://api.github.com/users/johnchienbronci/orgs', 'repos_url': 'https://api.github.com/users/johnchienbronci/repos', 'events_url': 'https://api.github.com/users/johnchienbronci/events{/privacy}', 'received_events_url': 'https://api.github.com/users/johnchienbronci/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-17T08:45:06Z', 'updated_at': '2023-06-17T08:45:06Z', 'author_association': 'NONE', 'body': 'I print out n_shards, and under multiple GPUs, this value is always 1.\r\nIs this value correct?', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1595674774/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1596987676', 'html_url': 'https://github.com/huggingface/datasets/issues/5961#issuecomment-1596987676', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5961', 'id': 1596987676, 'node_id': 'IC_kwDODunzps5fMBkc', 'user': {'login': 'lhoestq', 'id': 42851186, 'node_id': 'MDQ6VXNlcjQyODUxMTg2', 'avatar_url': 'https://avatars.githubusercontent.com/u/42851186?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/lhoestq', 'html_url': 'https://github.com/lhoestq', 'followers_url': 'https://api.github.com/users/lhoestq/followers', 'following_url': 'https://api.github.com/users/lhoestq/following{/other_user}', 'gists_url': 'https://api.github.com/users/lhoestq/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/lhoestq/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/lhoestq/subscriptions', 'organizations_url': 'https://api.github.com/users/lhoestq/orgs', 'repos_url': 'https://api.github.com/users/lhoestq/repos', 'events_url': 'https://api.github.com/users/lhoestq/events{/privacy}', 'received_events_url': 'https://api.github.com/users/lhoestq/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-19T11:08:52Z', 'updated_at': '2023-06-19T11:08:52Z', 'author_association': 'MEMBER', 'body': "Yes it's correct, and it explains why you always have the same data passed to your map function (the data can't be split).\r\n\r\nBut after being passed to `map`, each GPU keeps one example out of n(GPUs) so that you don't end up with duplicate data across GPUs", 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1596987676/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1597994829', 'html_url': 'https://github.com/huggingface/datasets/issues/5961#issuecomment-1597994829', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5961', 'id': 1597994829, 'node_id': 'IC_kwDODunzps5fP3dN', 'user': {'login': 'johnchienbronci', 'id': 27708347, 'node_id': 'MDQ6VXNlcjI3NzA4MzQ3', 'avatar_url': 'https://avatars.githubusercontent.com/u/27708347?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/johnchienbronci', 'html_url': 'https://github.com/johnchienbronci', 'followers_url': 'https://api.github.com/users/johnchienbronci/followers', 'following_url': 'https://api.github.com/users/johnchienbronci/following{/other_user}', 'gists_url': 'https://api.github.com/users/johnchienbronci/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/johnchienbronci/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/johnchienbronci/subscriptions', 'organizations_url': 'https://api.github.com/users/johnchienbronci/orgs', 'repos_url': 'https://api.github.com/users/johnchienbronci/repos', 'events_url': 'https://api.github.com/users/johnchienbronci/events{/privacy}', 'received_events_url': 'https://api.github.com/users/johnchienbronci/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-20T01:30:40Z', 'updated_at': '2023-06-20T01:30:40Z', 'author_association': 'NONE', 'body': '> > For each GPU, although see the same data in prepare_data(), the actual training data will not be the same in the end.\r\n> > Is my understanding correct?\r\n> \r\n> Yes exactly :)\r\n> \r\n> > Where can I print the actual training data for each GPU?\r\n> \r\n> You should call print in the data_collator\r\n\r\nOK, when printing the train data in the data collator, each GPU sees different data.\r\n\r\nThanks for your reply', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1597994829/reactions', 'total_count': 1, '+1': 1, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}]

[{'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1591751779', 'html_url': 'https://github.com/huggingface/datasets/issues/5959#issuecomment-1591751779', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5959', 'id': 1591751779, 'node_id': 'IC_kwDODunzps5e4DRj', 'user': {'login': 'JiazhaoLi', 'id': 31148397, 'node_id': 'MDQ6VXNlcjMxMTQ4Mzk3', 'avatar_url': 'https://avatars.githubusercontent.com/u/31148397?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/JiazhaoLi', 'html_url': 'https://github.com/JiazhaoLi', 'followers_url': 'https://api.github.com/users/JiazhaoLi/followers', 'following_url': 'https://api.github.com/users/JiazhaoLi/following{/other_user}', 'gists_url': 'https://api.github.com/users/JiazhaoLi/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/JiazhaoLi/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/JiazhaoLi/subscriptions', 'organizations_url': 'https://api.github.com/users/JiazhaoLi/orgs', 'repos_url': 'https://api.github.com/users/JiazhaoLi/repos', 'events_url': 'https://api.github.com/users/JiazhaoLi/events{/privacy}', 'received_events_url': 'https://api.github.com/users/JiazhaoLi/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-14T18:04:01Z', 'updated_at': '2023-06-14T18:04:01Z', 'author_association': 'NONE', 'body': "Sorry, I solve this by call `evaluate.load('glue_metric.py','sst-2')`\r\n", 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1591751779/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}]

[{'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1591599974', 'html_url': 'https://github.com/huggingface/datasets/pull/5957#issuecomment-1591599974', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5957', 'id': 1591599974, 'node_id': 'IC_kwDODunzps5e3eNm', 'user': {'login': 'github-actions[bot]', 'id': 41898282, 'node_id': 'MDM6Qm90NDE4OTgyODI=', 'avatar_url': 'https://avatars.githubusercontent.com/in/15368?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/github-actions%5Bbot%5D', 'html_url': 'https://github.com/apps/github-actions', 'followers_url': 'https://api.github.com/users/github-actions%5Bbot%5D/followers', 'following_url': 'https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}', 'gists_url': 'https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/github-actions%5Bbot%5D/subscriptions', 'organizations_url': 'https://api.github.com/users/github-actions%5Bbot%5D/orgs', 'repos_url': 'https://api.github.com/users/github-actions%5Bbot%5D/repos', 'events_url': 'https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}', 'received_events_url': 'https://api.github.com/users/github-actions%5Bbot%5D/received_events', 'type': 'Bot', 'site_admin': False}, 'created_at': '2023-06-14T16:24:30Z', 'updated_at': '2023-06-14T16:24:30Z', 'author_association': 'NONE', 'body': '<details>\n<summary>Show benchmarks</summary>\n\nPyArrow==8.0.0\n\n<details>\n<summary>Show updated benchmarks!</summary>\n\n### Benchmark: benchmark_array_xd.json\n\n| metric | read_batch_formatted_as_numpy after write_array2d | read_batch_formatted_as_numpy after write_flattened_sequence | read_batch_formatted_as_numpy after write_nested_sequence | read_batch_unformated after write_array2d | read_batch_unformated after write_flattened_sequence | read_batch_unformated after write_nested_sequence | read_col_formatted_as_numpy after write_array2d | read_col_formatted_as_numpy after write_flattened_sequence | read_col_formatted_as_numpy after write_nested_sequence | read_col_unformated after write_array2d | read_col_unformated after write_flattened_sequence | read_col_unformated after write_nested_sequence | read_formatted_as_numpy after write_array2d | read_formatted_as_numpy after write_flattened_sequence | read_formatted_as_numpy after write_nested_sequence | read_unformated after write_array2d | read_unformated after write_flattened_sequence | read_unformated after write_nested_sequence | write_array2d | write_flattened_sequence | write_nested_sequence |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.006498 / 0.011353 (-0.004855) | 0.003970 / 0.011008 (-0.007038) | 0.099242 / 0.038508 (0.060734) | 0.044363 / 0.023109 (0.021254) | 0.313900 / 0.275898 (0.038002) | 0.386562 / 0.323480 (0.063082) | 0.003837 / 0.007986 (-0.004149) | 0.004203 / 0.004328 (-0.000125) | 0.076191 / 0.004250 (0.071940) | 0.058823 / 0.037052 (0.021771) | 0.333838 / 0.258489 (0.075349) | 0.368235 / 0.293841 (0.074394) | 0.030774 / 0.128546 (-0.097772) | 0.008787 / 0.075646 (-0.066860) | 0.326474 / 0.419271 (-0.092798) | 0.050903 / 0.043533 (0.007370) | 0.303928 / 0.255139 (0.048789) | 0.321532 / 0.283200 (0.038333) | 0.024162 / 0.141683 (-0.117520) | 1.479662 / 1.452155 (0.027507) | 1.520300 / 1.492716 (0.027584) |\n\n### Benchmark: benchmark_getitem\\_100B.json\n\n| metric | get_batch_of\\_1024\\_random_rows | get_batch_of\\_1024\\_rows | get_first_row | get_last_row |\n|--------|---|---|---|---|\n| new / old (diff) | 0.212403 / 0.018006 (0.194397) | 0.448019 / 0.000490 (0.447529) | 0.005465 / 0.000200 (0.005265) | 0.000388 / 0.000054 (0.000334) |\n\n### Benchmark: benchmark_indices_mapping.json\n\n| metric | select | shard | shuffle | sort | train_test_split |\n|--------|---|---|---|---|---|\n| new / old (diff) | 0.027533 / 0.037411 (-0.009878) | 0.117477 / 0.014526 (0.102952) | 0.121182 / 0.176557 (-0.055374) | 0.181150 / 0.737135 (-0.555985) | 0.128557 / 0.296338 (-0.167782) |\n\n### Benchmark: benchmark_iterating.json\n\n| metric | read 5000 | read 50000 | read_batch 50000 10 | read_batch 50000 100 | read_batch 50000 1000 | read_formatted numpy 5000 | read_formatted pandas 5000 | read_formatted tensorflow 5000 | read_formatted torch 5000 | read_formatted_batch numpy 5000 10 | read_formatted_batch numpy 5000 1000 | shuffled read 5000 | shuffled read 50000 | shuffled read_batch 50000 10 | shuffled read_batch 50000 100 | shuffled read_batch 50000 1000 | shuffled read_formatted numpy 5000 | shuffled read_formatted_batch numpy 5000 10 | shuffled read_formatted_batch numpy 5000 1000 |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.397763 / 0.215209 (0.182554) | 3.959460 / 2.077655 (1.881805) | 1.822057 / 1.504120 (0.317937) | 1.627020 / 1.541195 (0.085826) | 1.695394 / 1.468490 (0.226904) | 0.536848 / 4.584777 (-4.047929) | 3.765205 / 3.745712 (0.019493) | 3.196300 / 5.269862 (-2.073561) | 1.623583 / 4.565676 (-2.942094) | 0.065823 / 0.424275 (-0.358452) | 0.011062 / 0.007607 (0.003455) | 0.500428 / 0.226044 (0.274384) | 5.008816 / 2.268929 (2.739888) | 2.314660 / 55.444624 (-53.129965) | 2.007429 / 6.876477 (-4.869047) | 2.141438 / 2.142072 (-0.000635) | 0.656697 / 4.805227 (-4.148530) | 0.143555 / 6.500664 (-6.357109) | 0.063928 / 0.075469 (-0.011541) |\n\n### Benchmark: benchmark_map_filter.json\n\n| metric | filter | map fast-tokenizer batched | map identity | map identity batched | map no-op batched | map no-op batched numpy | map no-op batched pandas | map no-op batched pytorch | map no-op batched tensorflow |\n|--------|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 1.169038 / 1.841788 (-0.672750) | 15.027186 / 8.074308 (6.952878) | 13.571484 / 10.191392 (3.380092) | 0.166437 / 0.680424 (-0.513986) | 0.017656 / 0.534201 (-0.516545) | 0.397725 / 0.579283 (-0.181558) | 0.451019 / 0.434364 (0.016655) | 0.469134 / 0.540337 (-0.071203) | 0.575885 / 1.386936 (-0.811051) |\n\n</details>\nPyArrow==latest\n\n<details>\n<summary>Show updated benchmarks!</summary>\n\n### Benchmark: benchmark_array_xd.json\n\n| metric | read_batch_formatted_as_numpy after write_array2d | read_batch_formatted_as_numpy after write_flattened_sequence | read_batch_formatted_as_numpy after write_nested_sequence | read_batch_unformated after write_array2d | read_batch_unformated after write_flattened_sequence | read_batch_unformated after write_nested_sequence | read_col_formatted_as_numpy after write_array2d | read_col_formatted_as_numpy after write_flattened_sequence | read_col_formatted_as_numpy after write_nested_sequence | read_col_unformated after write_array2d | read_col_unformated after write_flattened_sequence | read_col_unformated after write_nested_sequence | read_formatted_as_numpy after write_array2d | read_formatted_as_numpy after write_flattened_sequence | read_formatted_as_numpy after write_nested_sequence | read_unformated after write_array2d | read_unformated after write_flattened_sequence | read_unformated after write_nested_sequence | write_array2d | write_flattened_sequence | write_nested_sequence |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.006887 / 0.011353 (-0.004465) | 0.004166 / 0.011008 (-0.006842) | 0.077137 / 0.038508 (0.038629) | 0.055631 / 0.023109 (0.032522) | 0.397658 / 0.275898 (0.121760) | 0.473981 / 0.323480 (0.150502) | 0.005365 / 0.007986 (-0.002621) | 0.003401 / 0.004328 (-0.000928) | 0.076481 / 0.004250 (0.072231) | 0.056014 / 0.037052 (0.018961) | 0.415253 / 0.258489 (0.156764) | 0.457620 / 0.293841 (0.163779) | 0.031850 / 0.128546 (-0.096696) | 0.008869 / 0.075646 (-0.066777) | 0.083475 / 0.419271 (-0.335796) | 0.049232 / 0.043533 (0.005699) | 0.392947 / 0.255139 (0.137808) | 0.417243 / 0.283200 (0.134043) | 0.024554 / 0.141683 (-0.117129) | 1.508081 / 1.452155 (0.055926) | 1.541845 / 1.492716 (0.049129) |\n\n### Benchmark: benchmark_getitem\\_100B.json\n\n| metric | get_batch_of\\_1024\\_random_rows | get_batch_of\\_1024\\_rows | get_first_row | get_last_row |\n|--------|---|---|---|---|\n| new / old (diff) | 0.228470 / 0.018006 (0.210464) | 0.450933 / 0.000490 (0.450443) | 0.001508 / 0.000200 (0.001308) | 0.000083 / 0.000054 (0.000029) |\n\n### Benchmark: benchmark_indices_mapping.json\n\n| metric | select | shard | shuffle | sort | train_test_split |\n|--------|---|---|---|---|---|\n| new / old (diff) | 0.030189 / 0.037411 (-0.007222) | 0.118853 / 0.014526 (0.104327) | 0.124809 / 0.176557 (-0.051747) | 0.175066 / 0.737135 (-0.562069) | 0.129819 / 0.296338 (-0.166519) |\n\n### Benchmark: benchmark_iterating.json\n\n| metric | read 5000 | read 50000 | read_batch 50000 10 | read_batch 50000 100 | read_batch 50000 1000 | read_formatted numpy 5000 | read_formatted pandas 5000 | read_formatted tensorflow 5000 | read_formatted torch 5000 | read_formatted_batch numpy 5000 10 | read_formatted_batch numpy 5000 1000 | shuffled read 5000 | shuffled read 50000 | shuffled read_batch 50000 10 | shuffled read_batch 50000 100 | shuffled read_batch 50000 1000 | shuffled read_formatted numpy 5000 | shuffled read_formatted_batch numpy 5000 10 | shuffled read_formatted_batch numpy 5000 1000 |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.451830 / 0.215209 (0.236621) | 4.505352 / 2.077655 (2.427698) | 2.309303 / 1.504120 (0.805183) | 2.120983 / 1.541195 (0.579789) | 2.198808 / 1.468490 (0.730317) | 0.543836 / 4.584777 (-4.040940) | 3.836650 / 3.745712 (0.090938) | 1.872293 / 5.269862 (-3.397568) | 1.122335 / 4.565676 (-3.443342) | 0.067463 / 0.424275 (-0.356812) | 0.012143 / 0.007607 (0.004536) | 0.553674 / 0.226044 (0.327630) | 5.572101 / 2.268929 (3.303173) | 2.772151 / 55.444624 (-52.672473) | 2.451557 / 6.876477 (-4.424920) | 2.521241 / 2.142072 (0.379169) | 0.665799 / 4.805227 (-4.139428) | 0.143842 / 6.500664 (-6.356822) | 0.065373 / 0.075469 (-0.010096) |\n\n### Benchmark: benchmark_map_filter.json\n\n| metric | filter | map fast-tokenizer batched | map identity | map identity batched | map no-op batched | map no-op batched numpy | map no-op batched pandas | map no-op batched pytorch | map no-op batched tensorflow |\n|--------|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 1.271013 / 1.841788 (-0.570775) | 15.290054 / 8.074308 (7.215746) | 14.807044 / 10.191392 (4.615652) | 0.163767 / 0.680424 (-0.516657) | 0.017383 / 0.534201 (-0.516818) | 0.393046 / 0.579283 (-0.186237) | 0.423056 / 0.434364 (-0.011308) | 0.459193 / 0.540337 (-0.081145) | 0.559964 / 1.386936 (-0.826972) |\n\n</details>\n</details>\n\n![](https://cml.dev/watermark.png#011b75f044ef7fa6b8981ef3496615296aeb315b "CML watermark")\n', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1591599974/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1591600364', 'html_url': 'https://github.com/huggingface/datasets/pull/5957#issuecomment-1591600364', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5957', 'id': 1591600364, 'node_id': 'IC_kwDODunzps5e3eTs', 'user': {'login': 'HuggingFaceDocBuilderDev', 'id': 99929124, 'node_id': 'U_kgDOBfTMJA', 'avatar_url': 'https://avatars.githubusercontent.com/u/99929124?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/HuggingFaceDocBuilderDev', 'html_url': 'https://github.com/HuggingFaceDocBuilderDev', 'followers_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/followers', 'following_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/following{/other_user}', 'gists_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/subscriptions', 'organizations_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/orgs', 'repos_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/repos', 'events_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/events{/privacy}', 'received_events_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-14T16:24:46Z', 'updated_at': '2023-06-14T16:25:05Z', 'author_association': 'NONE', 'body': '_The documentation is not available anymore as the PR was closed or merged._', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1591600364/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1591613383', 'html_url': 'https://github.com/huggingface/datasets/pull/5957#issuecomment-1591613383', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5957', 'id': 1591613383, 'node_id': 'IC_kwDODunzps5e3hfH', 'user': {'login': 'github-actions[bot]', 'id': 41898282, 'node_id': 'MDM6Qm90NDE4OTgyODI=', 'avatar_url': 'https://avatars.githubusercontent.com/in/15368?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/github-actions%5Bbot%5D', 'html_url': 'https://github.com/apps/github-actions', 'followers_url': 'https://api.github.com/users/github-actions%5Bbot%5D/followers', 'following_url': 'https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}', 'gists_url': 'https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/github-actions%5Bbot%5D/subscriptions', 'organizations_url': 'https://api.github.com/users/github-actions%5Bbot%5D/orgs', 'repos_url': 'https://api.github.com/users/github-actions%5Bbot%5D/repos', 'events_url': 'https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}', 'received_events_url': 'https://api.github.com/users/github-actions%5Bbot%5D/received_events', 'type': 'Bot', 'site_admin': False}, 'created_at': '2023-06-14T16:32:18Z', 'updated_at': '2023-06-14T16:32:18Z', 'author_association': 'NONE', 'body': '<details>\n<summary>Show benchmarks</summary>\n\nPyArrow==8.0.0\n\n<details>\n<summary>Show updated benchmarks!</summary>\n\n### Benchmark: benchmark_array_xd.json\n\n| metric | read_batch_formatted_as_numpy after write_array2d | read_batch_formatted_as_numpy after write_flattened_sequence | read_batch_formatted_as_numpy after write_nested_sequence | read_batch_unformated after write_array2d | read_batch_unformated after write_flattened_sequence | read_batch_unformated after write_nested_sequence | read_col_formatted_as_numpy after write_array2d | read_col_formatted_as_numpy after write_flattened_sequence | read_col_formatted_as_numpy after write_nested_sequence | read_col_unformated after write_array2d | read_col_unformated after write_flattened_sequence | read_col_unformated after write_nested_sequence | read_formatted_as_numpy after write_array2d | read_formatted_as_numpy after write_flattened_sequence | read_formatted_as_numpy after write_nested_sequence | read_unformated after write_array2d | read_unformated after write_flattened_sequence | read_unformated after write_nested_sequence | write_array2d | write_flattened_sequence | write_nested_sequence |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.006112 / 0.011353 (-0.005241) | 0.003712 / 0.011008 (-0.007297) | 0.099996 / 0.038508 (0.061488) | 0.037526 / 0.023109 (0.014417) | 0.305834 / 0.275898 (0.029936) | 0.361368 / 0.323480 (0.037888) | 0.004849 / 0.007986 (-0.003136) | 0.002912 / 0.004328 (-0.001417) | 0.077729 / 0.004250 (0.073479) | 0.053203 / 0.037052 (0.016151) | 0.318088 / 0.258489 (0.059599) | 0.371745 / 0.293841 (0.077904) | 0.029384 / 0.128546 (-0.099162) | 0.008504 / 0.075646 (-0.067142) | 0.318472 / 0.419271 (-0.100799) | 0.046043 / 0.043533 (0.002510) | 0.310418 / 0.255139 (0.055279) | 0.335044 / 0.283200 (0.051844) | 0.020364 / 0.141683 (-0.121319) | 1.503201 / 1.452155 (0.051047) | 1.556408 / 1.492716 (0.063692) |\n\n### Benchmark: benchmark_getitem\\_100B.json\n\n| metric | get_batch_of\\_1024\\_random_rows | get_batch_of\\_1024\\_rows | get_first_row | get_last_row |\n|--------|---|---|---|---|\n| new / old (diff) | 0.210245 / 0.018006 (0.192239) | 0.418918 / 0.000490 (0.418428) | 0.002552 / 0.000200 (0.002352) | 0.000084 / 0.000054 (0.000030) |\n\n### Benchmark: benchmark_indices_mapping.json\n\n| metric | select | shard | shuffle | sort | train_test_split |\n|--------|---|---|---|---|---|\n| new / old (diff) | 0.022295 / 0.037411 (-0.015116) | 0.099534 / 0.014526 (0.085008) | 0.106432 / 0.176557 (-0.070124) | 0.165110 / 0.737135 (-0.572026) | 0.109851 / 0.296338 (-0.186488) |\n\n### Benchmark: benchmark_iterating.json\n\n| metric | read 5000 | read 50000 | read_batch 50000 10 | read_batch 50000 100 | read_batch 50000 1000 | read_formatted numpy 5000 | read_formatted pandas 5000 | read_formatted tensorflow 5000 | read_formatted torch 5000 | read_formatted_batch numpy 5000 10 | read_formatted_batch numpy 5000 1000 | shuffled read 5000 | shuffled read 50000 | shuffled read_batch 50000 10 | shuffled read_batch 50000 100 | shuffled read_batch 50000 1000 | shuffled read_formatted numpy 5000 | shuffled read_formatted_batch numpy 5000 10 | shuffled read_formatted_batch numpy 5000 1000 |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.423947 / 0.215209 (0.208738) | 4.232978 / 2.077655 (2.155323) | 2.004849 / 1.504120 (0.500729) | 1.814345 / 1.541195 (0.273151) | 1.809192 / 1.468490 (0.340702) | 0.561146 / 4.584777 (-4.023631) | 3.385043 / 3.745712 (-0.360669) | 1.708265 / 5.269862 (-3.561597) | 1.030290 / 4.565676 (-3.535387) | 0.067095 / 0.424275 (-0.357180) | 0.011052 / 0.007607 (0.003445) | 0.522416 / 0.226044 (0.296371) | 5.207003 / 2.268929 (2.938075) | 2.367067 / 55.444624 (-53.077558) | 1.998705 / 6.876477 (-4.877772) | 2.068633 / 2.142072 (-0.073439) | 0.672396 / 4.805227 (-4.132831) | 0.135818 / 6.500664 (-6.364846) | 0.065229 / 0.075469 (-0.010240) |\n\n### Benchmark: benchmark_map_filter.json\n\n| metric | filter | map fast-tokenizer batched | map identity | map identity batched | map no-op batched | map no-op batched numpy | map no-op batched pandas | map no-op batched pytorch | map no-op batched tensorflow |\n|--------|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 1.187079 / 1.841788 (-0.654709) | 13.893153 / 8.074308 (5.818845) | 13.951328 / 10.191392 (3.759936) | 0.142519 / 0.680424 (-0.537905) | 0.016546 / 0.534201 (-0.517655) | 0.364008 / 0.579283 (-0.215275) | 0.385957 / 0.434364 (-0.048407) | 0.425218 / 0.540337 (-0.115120) | 0.519586 / 1.386936 (-0.867350) |\n\n</details>\nPyArrow==latest\n\n<details>\n<summary>Show updated benchmarks!</summary>\n\n### Benchmark: benchmark_array_xd.json\n\n| metric | read_batch_formatted_as_numpy after write_array2d | read_batch_formatted_as_numpy after write_flattened_sequence | read_batch_formatted_as_numpy after write_nested_sequence | read_batch_unformated after write_array2d | read_batch_unformated after write_flattened_sequence | read_batch_unformated after write_nested_sequence | read_col_formatted_as_numpy after write_array2d | read_col_formatted_as_numpy after write_flattened_sequence | read_col_formatted_as_numpy after write_neste

[{'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1591262393', 'html_url': 'https://github.com/huggingface/datasets/pull/5956#issuecomment-1591262393', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5956', 'id': 1591262393, 'node_id': 'IC_kwDODunzps5e2Ly5', 'user': {'login': 'HuggingFaceDocBuilderDev', 'id': 99929124, 'node_id': 'U_kgDOBfTMJA', 'avatar_url': 'https://avatars.githubusercontent.com/u/99929124?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/HuggingFaceDocBuilderDev', 'html_url': 'https://github.com/HuggingFaceDocBuilderDev', 'followers_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/followers', 'following_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/following{/other_user}', 'gists_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/subscriptions', 'organizations_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/orgs', 'repos_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/repos', 'events_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/events{/privacy}', 'received_events_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-14T13:56:16Z', 'updated_at': '2023-06-14T14:34:12Z', 'author_association': 'NONE', 'body': '_The documentation is not available anymore as the PR was closed or merged._', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1591262393/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1591263440', 'html_url': 'https://github.com/huggingface/datasets/pull/5956#issuecomment-1591263440', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5956', 'id': 1591263440, 'node_id': 'IC_kwDODunzps5e2MDQ', 'user': {'login': 'github-actions[bot]', 'id': 41898282, 'node_id': 'MDM6Qm90NDE4OTgyODI=', 'avatar_url': 'https://avatars.githubusercontent.com/in/15368?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/github-actions%5Bbot%5D', 'html_url': 'https://github.com/apps/github-actions', 'followers_url': 'https://api.github.com/users/github-actions%5Bbot%5D/followers', 'following_url': 'https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}', 'gists_url': 'https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/github-actions%5Bbot%5D/subscriptions', 'organizations_url': 'https://api.github.com/users/github-actions%5Bbot%5D/orgs', 'repos_url': 'https://api.github.com/users/github-actions%5Bbot%5D/repos', 'events_url': 'https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}', 'received_events_url': 'https://api.github.com/users/github-actions%5Bbot%5D/received_events', 'type': 'Bot', 'site_admin': False}, 'created_at': '2023-06-14T13:56:53Z', 'updated_at': '2023-06-14T13:56:53Z', 'author_association': 'NONE', 'body': '<details>\n<summary>Show benchmarks</summary>\n\nPyArrow==8.0.0\n\n<details>\n<summary>Show updated benchmarks!</summary>\n\n### Benchmark: benchmark_array_xd.json\n\n| metric | read_batch_formatted_as_numpy after write_array2d | read_batch_formatted_as_numpy after write_flattened_sequence | read_batch_formatted_as_numpy after write_nested_sequence | read_batch_unformated after write_array2d | read_batch_unformated after write_flattened_sequence | read_batch_unformated after write_nested_sequence | read_col_formatted_as_numpy after write_array2d | read_col_formatted_as_numpy after write_flattened_sequence | read_col_formatted_as_numpy after write_nested_sequence | read_col_unformated after write_array2d | read_col_unformated after write_flattened_sequence | read_col_unformated after write_nested_sequence | read_formatted_as_numpy after write_array2d | read_formatted_as_numpy after write_flattened_sequence | read_formatted_as_numpy after write_nested_sequence | read_unformated after write_array2d | read_unformated after write_flattened_sequence | read_unformated after write_nested_sequence | write_array2d | write_flattened_sequence | write_nested_sequence |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.005893 / 0.011353 (-0.005460) | 0.003682 / 0.011008 (-0.007327) | 0.098358 / 0.038508 (0.059850) | 0.028130 / 0.023109 (0.005020) | 0.305960 / 0.275898 (0.030062) | 0.334869 / 0.323480 (0.011390) | 0.003522 / 0.007986 (-0.004463) | 0.003683 / 0.004328 (-0.000645) | 0.079418 / 0.004250 (0.075168) | 0.037662 / 0.037052 (0.000609) | 0.310893 / 0.258489 (0.052404) | 0.341347 / 0.293841 (0.047506) | 0.027450 / 0.128546 (-0.101096) | 0.008381 / 0.075646 (-0.067265) | 0.316020 / 0.419271 (-0.103252) | 0.045079 / 0.043533 (0.001546) | 0.307806 / 0.255139 (0.052667) | 0.331804 / 0.283200 (0.048604) | 0.091806 / 0.141683 (-0.049877) | 1.492611 / 1.452155 (0.040457) | 1.551762 / 1.492716 (0.059046) |\n\n### Benchmark: benchmark_getitem\\_100B.json\n\n| metric | get_batch_of\\_1024\\_random_rows | get_batch_of\\_1024\\_rows | get_first_row | get_last_row |\n|--------|---|---|---|---|\n| new / old (diff) | 0.201640 / 0.018006 (0.183634) | 0.422776 / 0.000490 (0.422286) | 0.003734 / 0.000200 (0.003535) | 0.000080 / 0.000054 (0.000026) |\n\n### Benchmark: benchmark_indices_mapping.json\n\n| metric | select | shard | shuffle | sort | train_test_split |\n|--------|---|---|---|---|---|\n| new / old (diff) | 0.025429 / 0.037411 (-0.011982) | 0.104699 / 0.014526 (0.090173) | 0.110505 / 0.176557 (-0.066051) | 0.171252 / 0.737135 (-0.565883) | 0.113131 / 0.296338 (-0.183208) |\n\n### Benchmark: benchmark_iterating.json\n\n| metric | read 5000 | read 50000 | read_batch 50000 10 | read_batch 50000 100 | read_batch 50000 1000 | read_formatted numpy 5000 | read_formatted pandas 5000 | read_formatted tensorflow 5000 | read_formatted torch 5000 | read_formatted_batch numpy 5000 10 | read_formatted_batch numpy 5000 1000 | shuffled read 5000 | shuffled read 50000 | shuffled read_batch 50000 10 | shuffled read_batch 50000 100 | shuffled read_batch 50000 1000 | shuffled read_formatted numpy 5000 | shuffled read_formatted_batch numpy 5000 10 | shuffled read_formatted_batch numpy 5000 1000 |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.419914 / 0.215209 (0.204705) | 4.184414 / 2.077655 (2.106760) | 1.999263 / 1.504120 (0.495143) | 1.828669 / 1.541195 (0.287474) | 1.940366 / 1.468490 (0.471876) | 0.556939 / 4.584777 (-4.027838) | 3.389164 / 3.745712 (-0.356548) | 1.796323 / 5.269862 (-3.473538) | 1.048843 / 4.565676 (-3.516833) | 0.067315 / 0.424275 (-0.356960) | 0.011531 / 0.007607 (0.003923) | 0.517226 / 0.226044 (0.291182) | 5.167255 / 2.268929 (2.898326) | 2.431129 / 55.444624 (-53.013495) | 2.133913 / 6.876477 (-4.742564) | 2.359021 / 2.142072 (0.216948) | 0.666390 / 4.805227 (-4.138838) | 0.135147 / 6.500664 (-6.365517) | 0.064855 / 0.075469 (-0.010614) |\n\n### Benchmark: benchmark_map_filter.json\n\n| metric | filter | map fast-tokenizer batched | map identity | map identity batched | map no-op batched | map no-op batched numpy | map no-op batched pandas | map no-op batched pytorch | map no-op batched tensorflow |\n|--------|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 1.166530 / 1.841788 (-0.675258) | 14.060551 / 8.074308 (5.986242) | 14.171663 / 10.191392 (3.980271) | 0.285821 / 0.680424 (-0.394603) | 0.016867 / 0.534201 (-0.517334) | 0.369102 / 0.579283 (-0.210181) | 0.393580 / 0.434364 (-0.040784) | 0.423721 / 0.540337 (-0.116616) | 0.512559 / 1.386936 (-0.874377) |\n\n</details>\nPyArrow==latest\n\n<details>\n<summary>Show updated benchmarks!</summary>\n\n### Benchmark: benchmark_array_xd.json\n\n| metric | read_batch_formatted_as_numpy after write_array2d | read_batch_formatted_as_numpy after write_flattened_sequence | read_batch_formatted_as_numpy after write_nested_sequence | read_batch_unformated after write_array2d | read_batch_unformated after write_flattened_sequence | read_batch_unformated after write_nested_sequence | read_col_formatted_as_numpy after write_array2d | read_col_formatted_as_numpy after write_flattened_sequence | read_col_formatted_as_numpy after write_nested_sequence | read_col_unformated after write_array2d | read_col_unformated after write_flattened_sequence | read_col_unformated after write_nested_sequence | read_formatted_as_numpy after write_array2d | read_formatted_as_numpy after write_flattened_sequence | read_formatted_as_numpy after write_nested_sequence | read_unformated after write_array2d | read_unformated after write_flattened_sequence | read_unformated after write_nested_sequence | write_array2d | write_flattened_sequence | write_nested_sequence |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.006674 / 0.011353 (-0.004679) | 0.004006 / 0.011008 (-0.007002) | 0.080160 / 0.038508 (0.041652) | 0.032508 / 0.023109 (0.009399) | 0.378168 / 0.275898 (0.102270) | 0.417796 / 0.323480 (0.094316) | 0.003706 / 0.007986 (-0.004280) | 0.002995 / 0.004328 (-0.001333) | 0.079275 / 0.004250 (0.075025) | 0.043690 / 0.037052 (0.006638) | 0.377717 / 0.258489 (0.119228) | 0.439801 / 0.293841 (0.145961) | 0.028438 / 0.128546 (-0.100108) | 0.008661 / 0.075646 (-0.066985) | 0.085280 / 0.419271 (-0.333991) | 0.043716 / 0.043533 (0.000183) | 0.370086 / 0.255139 (0.114947) | 0.403763 / 0.283200 (0.120563) | 0.095022 / 0.141683 (-0.046661) | 1.534376 / 1.452155 (0.082221) | 1.597658 / 1.492716 (0.104942) |\n\n### Benchmark: benchmark_getitem\\_100B.json\n\n| metric | get_batch_of\\_1024\\_random_rows | get_batch_of\\_1024\\_rows | get_first_row | get_last_row |\n|--------|---|---|---|---|\n| new / old (diff) | 0.240229 / 0.018006 (0.222223) | 0.496281 / 0.000490 (0.495792) | 0.002165 / 0.000200 (0.001965) | 0.000075 / 0.000054 (0.000020) |\n\n### Benchmark: benchmark_indices_mapping.json\n\n| metric | select | shard | shuffle | sort | train_test_split |\n|--------|---|---|---|---|---|\n| new / old (diff) | 0.025330 / 0.037411 (-0.012081) | 0.102414 / 0.014526 (0.087888) | 0.112733 / 0.176557 (-0.063824) | 0.161181 / 0.737135 (-0.575955) | 0.114196 / 0.296338 (-0.182143) |\n\n### Benchmark: benchmark_iterating.json\n\n| metric | read 5000 | read 50000 | read_batch 50000 10 | read_batch 50000 100 | read_batch 50000 1000 | read_formatted numpy 5000 | read_formatted pandas 5000 | read_formatted tensorflow 5000 | read_formatted torch 5000 | read_formatted_batch numpy 5000 10 | read_formatted_batch numpy 5000 1000 | shuffled read 5000 | shuffled read 50000 | shuffled read_batch 50000 10 | shuffled read_batch 50000 100 | shuffled read_batch 50000 1000 | shuffled read_formatted numpy 5000 | shuffled read_formatted_batch numpy 5000 10 | shuffled read_formatted_batch numpy 5000 1000 |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.456808 / 0.215209 (0.241599) | 4.534937 / 2.077655 (2.457283) | 2.318834 / 1.504120 (0.814714) | 2.074085 / 1.541195 (0.532890) | 2.117409 / 1.468490 (0.648919) | 0.559110 / 4.584777 (-4.025667) | 3.371695 / 3.745712 (-0.374017) | 2.543154 / 5.269862 (-2.726708) | 1.360552 / 4.565676 (-3.205125) | 0.067602 / 0.424275 (-0.356674) | 0.011396 / 0.007607 (0.003789) | 0.561666 / 0.226044 (0.335622) | 5.607666 / 2.268929 (3.338737) | 2.802775 / 55.444624 (-52.641849) | 2.486162 / 6.876477 (-4.390315) | 2.390885 / 2.142072 (0.248813) | 0.667407 / 4.805227 (-4.137820) | 0.135948 / 6.500664 (-6.364717) | 0.067272 / 0.075469 (-0.008197) |\n\n### Benchmark: benchmark_map_filter.json\n\n| metric | filter | map fast-tokenizer batched | map identity | map identity batched | map no-op batched | map no-op batched numpy | map no-op batched pandas | map no-op batched pytorch | map no-op batched tensorflow |\n|--------|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 1.279664 / 1.841788 (-0.562124) | 15.188099 / 8.074308 (7.113791) | 14.380355 / 10.191392 (4.188963) | 0.140344 / 0.680424 (-0.540080) | 0.016832 / 0.534201 (-0.517369) | 0.364631 / 0.579283 (-0.214652) | 0.400306 / 0.434364 (-0.034058) | 0.430793 / 0.540337 (-0.109545) | 0.525923 / 1.386936 (-0.861013) |\n\n</details>\n</details>\n\n![](https://cml.dev/watermark.png#48ca19cf1f4d1c99765a1f847c1f6b849496d99d "CML watermark")\n', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1591263440/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1591321614', 'html_url': 'https://github.com/huggingface/datasets/pull/5956#issuecomment-1591321614', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5956', 'id': 1591321614, 'node_id': 'IC_kwDODunzps5e2aQO', 'user': {'login': 'github-actions[bot]', 'id': 41898282, 'node_id': 'MDM6Qm90NDE4OTgyODI=', 'avatar_url': 'https://avatars.githubusercontent.com/in/15368?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/github-actions%5Bbot%5D', 'html_url': 'https://github.com/apps/github-actions', 'followers_url': 'https://api.github.com/users/github-actions%5Bbot%5D/followers', 'following_url': 'https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}', 'gists_url': 'https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/github-actions%5Bbot%5D/subscriptions', 'organizations_url': 'https://api.github.com/users/github-actions%5Bbot%5D/orgs', 'repos_url': 'https://api.github.com/users/github-actions%5Bbot%5D/repos', 'events_url': 'https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}', 'received_events_url': 'https://api.github.com/users/github-actions%5Bbot%5D/received_events', 'type': 'Bot', 'site_admin': False}, 'created_at': '2023-06-14T14:22:58Z', 'updated_at': '2023-06-14T14:22:58Z', 'author_association': 'NONE', 'body': '<details>\n<summary>Show benchmarks</summary>\n\nPyArrow==8.0.0\n\n<details>\n<summary>Show updated benchmarks!</summary>\n\n### Benchmark: benchmark_array_xd.json\n\n| metric | read_batch_formatted_as_numpy after write_array2d | read_batch_formatted_as_numpy after write_flattened_sequence | read_batch_formatted_as_numpy after write_nested_sequence | read_batch_unformated after write_array2d | read_batch_unformated after write_flattened_sequence | read_batch_unformated after write_nested_sequence | read_col_formatted_as_numpy after write_array2d | read_col_formatted_as_numpy after write_flattened_sequence | read_col_formatted_as_numpy after write_nested_sequence | read_col_unformated after write_array2d | read_col_unformated after write_flattened_sequence | read_col_unformated after write_nested_sequence | read_formatted_as_numpy after write_array2d | read_formatted_as_numpy after write_flattened_sequence | read_formatted_as_numpy after write_nested_sequence | read_unformated after write_array2d | read_unformated after write_flattened_sequence | read_unformated after write_nested_sequence | write_array2d | write_flattened_sequence | write_nested_sequence |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.008502 / 0.011353 (-0.002851) | 0.005946 / 0.011008 (-0.005062) | 0.131279 / 0.038508 (0.092771) | 0.035400 / 0.023109 (0.012291) | 0.423240 / 0.275898 (0.147342) | 0.470248 / 0.323480 (0.146768) | 0.004949 / 0.007986 (-0.003037) | 0.004544 / 0.004328 (0.000215) | 0.106856 / 0.004250 (0.102605) | 0.046579 / 0.037052 (0.009527) | 0.441135 / 0.258489 (0.182646) | 0.470401 / 0.293841 (0.176561) | 0.047231 / 0.128546 (-0.081315) | 0.017278 / 0.075646 (-0.058368) | 0.401937 / 0.419271 (-0.017335) | 0.067151 / 0.043533 (0.023619) | 0.453908 / 0.255139 (0.198769) | 0.422171 / 0.283200 (0.138971) | 0.123583 / 0.141683 (-0.018100) | 1.852895 / 1.452155 (0.400740) | 1.827282 / 1.492716 (0.334566) |\n\n### Benchmark: benchmark_getitem\\_100B.json\n\n| metric | get_batch_of\\_1024\\_random_rows | get_batch_of\\_1024\\_rows | get_first_row | get_last_row |\n|--------|---|---|---|---|\n| new / old (diff) | 0.246419 / 0.018006 (0.228413) | 0.576930 / 0.000490 (0.576440) | 0.007511 / 0.000200 (0.007312) | 0.000165 / 0.000054 (0.000111) |\n\n### Benchmark: benchmark_indices_mapping.json\n\n| metric | select | shard | shuffle | sort | train_test_split |\n|--------|---|---|---|---|---|\n| new / old (diff) | 0.032732 / 0.037411 (-0.004680) | 0.130266 / 0.014526 (0.115740) | 0.150537 / 0.176557 (-0.026019) | 0.218554 / 0.737135 (-0.518582) | 0.148572 / 0.296338 (-0.147766) |\n\n### Benchmark: benchmark_iterating.json\n\n| metric | read 5000 | read 50000 | read_batch 50000 10 | read_batch 50000 100 | read_batch 50000 1000 | read_formatted numpy 5000 | read_formatted pandas 5000 | read_formatted tensorflow 5000 | read_formatted torch 5000 | read_formatted_batch numpy 5000 10 | read_formatted_batch numpy 5000 1000 | shuffled read 5000 | shuffled read 50000 | shuffled read_batch 50000 10 | shuffled read_batch 50000 100 | shuffled read_batch 50000 1000 | shuffled read_formatted numpy 5000 | shuffled read_formatted_batch numpy 5000 10 | shuffled read_formatted_batch numpy 5000 1000 |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.598611 / 0.215209 (0.383402) | 6.181219 / 2.077655 (4.103564) | 2.473468 / 1.504120 (0.969348) | 2.206374 / 1.541195 (0.665179) | 2.216707 / 1.468490 (0.748217) | 0.981295 / 4.584777 (-3.603482) | 5.716384 / 3.745712 (1.970672) | 5.882327 / 5.269862 (0.612466) | 2.761081 / 4.565676 (-1.804595) | 0.113544 / 0.424275 (-0.310731) | 0.015131 / 0.007607 (0.007524) | 0.850939 / 0.226044 (0.624894) | 8.046611 / 2.268929 (5.777682) | 3.340542 / 55.444624 (-52.104083) | 2.673692 / 6.876477 (-4.202785) | 2.926330 / 2.142072 (0.784257) | 1.176164 / 4.805227 (-3.629064) | 0.226745 / 6.500664 (-6.273919) | 0.085910 / 0.075469 (0.010441) |\n\n### Benchmark: benchmark_map_filter.json\n\n| metric | filter | map fast-tokenizer batched | map identity | map identity batched | map no-op batched | map no-op batched numpy | map no-op batched pandas | map no-op batched pytorch | map no-op batched tensorflow |\n|--------|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 1.483792 / 1.841788 (-0.357995) | 18.895009 / 8.074308 (10.820701) | 20.982461 / 10.191392 (10.791069) | 0.253085 / 0.680424 (-0.427339) | 0.031284 / 0.534201 (-0.502917) | 0.516569 / 0.579283 (-0.062714) | 0.635781 / 0.434364 (0.201417) | 0.604359 / 0.540337 (0.064022) | 0.725278 / 1.386936 (-0.661658) |\n\n</details>\nPyArrow==latest\n\n<details>\n<summary>Show updated benchmarks!</summary>\n\n### Benchmark: benchmark_array_xd.json\n\n| metric | read_batch_formatted_as_numpy after write_array2d | read_batch_formatted_as_numpy after write_flattened_sequence | read_batch_formatted_as_numpy after write_nested_sequence | read_batch_unformated after write_array2d | read_batch_unformated after write_flattened_sequence | read_batch_unformated after write_nested_sequence | read_col_formatted_as_numpy after write_array2d | read_col_formatted_as_numpy after write_flattened_sequence | read_col_formatted_as_numpy after write_nested_s

[{'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1591627100', 'html_url': 'https://github.com/huggingface/datasets/issues/5955#issuecomment-1591627100', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5955', 'id': 1591627100, 'node_id': 'IC_kwDODunzps5e3k1c', 'user': {'login': 'mariosasko', 'id': 47462742, 'node_id': 'MDQ6VXNlcjQ3NDYyNzQy', 'avatar_url': 'https://avatars.githubusercontent.com/u/47462742?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/mariosasko', 'html_url': 'https://github.com/mariosasko', 'followers_url': 'https://api.github.com/users/mariosasko/followers', 'following_url': 'https://api.github.com/users/mariosasko/following{/other_user}', 'gists_url': 'https://api.github.com/users/mariosasko/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/mariosasko/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/mariosasko/subscriptions', 'organizations_url': 'https://api.github.com/users/mariosasko/orgs', 'repos_url': 'https://api.github.com/users/mariosasko/repos', 'events_url': 'https://api.github.com/users/mariosasko/events{/privacy}', 'received_events_url': 'https://api.github.com/users/mariosasko/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-14T16:39:55Z', 'updated_at': '2023-06-14T16:39:55Z', 'author_association': 'CONTRIBUTOR', 'body': "This is the actual error:\r\n```\r\nFailed to read file '/home/lakala/hjc/code/pycode/glm/temp.json' with error <class 'pyarrow.lib.ArrowInvalid'>: cannot mix list and non-list, non-null values\r\n```\r\nWhich means some samples are incorrectly formatted.\r\n\r\nPyArrow, a storage backend that we use under the hood, requires that all the list elements have the same level of nesting (same number of dimensions) or are `None`.\r\n```python\r\nimport pyarrow as pa\r\npa.array([[1, 2, 3], 2]) # ArrowInvalid: cannot mix list and non-list, non-null values\r\npa.array([[1, 2, 3], [2]]) # works\r\n``` ", 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1591627100/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1592175484', 'html_url': 'https://github.com/huggingface/datasets/issues/5955#issuecomment-1592175484', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5955', 'id': 1592175484, 'node_id': 'IC_kwDODunzps5e5qt8', 'user': {'login': 'Night-Quiet', 'id': 73934131, 'node_id': 'MDQ6VXNlcjczOTM0MTMx', 'avatar_url': 'https://avatars.githubusercontent.com/u/73934131?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/Night-Quiet', 'html_url': 'https://github.com/Night-Quiet', 'followers_url': 'https://api.github.com/users/Night-Quiet/followers', 'following_url': 'https://api.github.com/users/Night-Quiet/following{/other_user}', 'gists_url': 'https://api.github.com/users/Night-Quiet/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/Night-Quiet/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/Night-Quiet/subscriptions', 'organizations_url': 'https://api.github.com/users/Night-Quiet/orgs', 'repos_url': 'https://api.github.com/users/Night-Quiet/repos', 'events_url': 'https://api.github.com/users/Night-Quiet/events{/privacy}', 'received_events_url': 'https://api.github.com/users/Night-Quiet/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-15T00:57:11Z', 'updated_at': '2023-06-15T00:57:11Z', 'author_association': 'NONE', 'body': "@mariosasko \r\nI used the same operation to check the original data before and after slicing.\r\nThis is reflected in my code.\r\n160000 is not a specific number.\r\nI can also get output using 150000.\r\nThis doesn't seem to align very well with what you said.\r\nBecause if only some sample formats are incorrect.\r\nSo there should be an error in one of the front and back slices.\r\nthank you for your reply.", 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1592175484/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1593095764', 'html_url': 'https://github.com/huggingface/datasets/issues/5955#issuecomment-1593095764', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5955', 'id': 1593095764, 'node_id': 'IC_kwDODunzps5e9LZU', 'user': {'login': 'mariosasko', 'id': 47462742, 'node_id': 'MDQ6VXNlcjQ3NDYyNzQy', 'avatar_url': 'https://avatars.githubusercontent.com/u/47462742?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/mariosasko', 'html_url': 'https://github.com/mariosasko', 'followers_url': 'https://api.github.com/users/mariosasko/followers', 'following_url': 'https://api.github.com/users/mariosasko/following{/other_user}', 'gists_url': 'https://api.github.com/users/mariosasko/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/mariosasko/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/mariosasko/subscriptions', 'organizations_url': 'https://api.github.com/users/mariosasko/orgs', 'repos_url': 'https://api.github.com/users/mariosasko/repos', 'events_url': 'https://api.github.com/users/mariosasko/events{/privacy}', 'received_events_url': 'https://api.github.com/users/mariosasko/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-15T13:44:29Z', 'updated_at': '2023-06-15T13:44:29Z', 'author_association': 'CONTRIBUTOR', 'body': 'Our JSON loader does the following in your case:\r\n\r\n```python\r\nimport json\r\nimport pyarrow as pa\r\n\r\nwith open(file, encoding="utf-8") as f:\r\n    dataset = json.load(f)\r\nkeys = set().union(*[row.keys() for row in dataset])\r\nmapping = {col: [row.get(col) for row in dataset] for col in keys}\r\npa_table = pa.Table.from_pydict(mapping) # the ArrowInvalid error comes from here\r\n```\r\n\r\nSo if this code throws an error with correctly-formatted JSON, then this is an Arrow bug and should be reported in their repo.\r\n\r\n> I used the same operation to check the original data before and after slicing.\r\nThis is reflected in my code.\r\n160000 is not a specific number.\r\nI can also get output using 150000.\r\nThis doesn\'t seem to align very well with what you said.\r\nBecause if only some sample formats are incorrect.\r\nSo there should be an error in one of the front and back slices.\r\n\r\nYou should shuffle the data to make sure that\'s not the case', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1593095764/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1594377464', 'html_url': 'https://github.com/huggingface/datasets/issues/5955#issuecomment-1594377464', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5955', 'id': 1594377464, 'node_id': 'IC_kwDODunzps5fCET4', 'user': {'login': 'Night-Quiet', 'id': 73934131, 'node_id': 'MDQ6VXNlcjczOTM0MTMx', 'avatar_url': 'https://avatars.githubusercontent.com/u/73934131?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/Night-Quiet', 'html_url': 'https://github.com/Night-Quiet', 'followers_url': 'https://api.github.com/users/Night-Quiet/followers', 'following_url': 'https://api.github.com/users/Night-Quiet/following{/other_user}', 'gists_url': 'https://api.github.com/users/Night-Quiet/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/Night-Quiet/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/Night-Quiet/subscriptions', 'organizations_url': 'https://api.github.com/users/Night-Quiet/orgs', 'repos_url': 'https://api.github.com/users/Night-Quiet/repos', 'events_url': 'https://api.github.com/users/Night-Quiet/events{/privacy}', 'received_events_url': 'https://api.github.com/users/Night-Quiet/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-16T09:15:16Z', 'updated_at': '2023-06-16T09:15:16Z', 'author_association': 'NONE', 'body': '@mariosasko \r\nThank you.\r\nI will try again.', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1594377464/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}]

[{'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1590943012', 'html_url': 'https://github.com/huggingface/datasets/pull/5954#issuecomment-1590943012', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5954', 'id': 1590943012, 'node_id': 'IC_kwDODunzps5e090k', 'user': {'login': 'HuggingFaceDocBuilderDev', 'id': 99929124, 'node_id': 'U_kgDOBfTMJA', 'avatar_url': 'https://avatars.githubusercontent.com/u/99929124?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/HuggingFaceDocBuilderDev', 'html_url': 'https://github.com/HuggingFaceDocBuilderDev', 'followers_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/followers', 'following_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/following{/other_user}', 'gists_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/subscriptions', 'organizations_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/orgs', 'repos_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/repos', 'events_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/events{/privacy}', 'received_events_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-14T10:38:33Z', 'updated_at': '2023-06-14T12:27:01Z', 'author_association': 'NONE', 'body': '_The documentation is not available anymore as the PR was closed or merged._', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1590943012/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1590944890', 'html_url': 'https://github.com/huggingface/datasets/pull/5954#issuecomment-1590944890', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5954', 'id': 1590944890, 'node_id': 'IC_kwDODunzps5e0-R6', 'user': {'login': 'github-actions[bot]', 'id': 41898282, 'node_id': 'MDM6Qm90NDE4OTgyODI=', 'avatar_url': 'https://avatars.githubusercontent.com/in/15368?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/github-actions%5Bbot%5D', 'html_url': 'https://github.com/apps/github-actions', 'followers_url': 'https://api.github.com/users/github-actions%5Bbot%5D/followers', 'following_url': 'https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}', 'gists_url': 'https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/github-actions%5Bbot%5D/subscriptions', 'organizations_url': 'https://api.github.com/users/github-actions%5Bbot%5D/orgs', 'repos_url': 'https://api.github.com/users/github-actions%5Bbot%5D/repos', 'events_url': 'https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}', 'received_events_url': 'https://api.github.com/users/github-actions%5Bbot%5D/received_events', 'type': 'Bot', 'site_admin': False}, 'created_at': '2023-06-14T10:40:05Z', 'updated_at': '2023-06-14T10:40:05Z', 'author_association': 'NONE', 'body': '<details>\n<summary>Show benchmarks</summary>\n\nPyArrow==8.0.0\n\n<details>\n<summary>Show updated benchmarks!</summary>\n\n### Benchmark: benchmark_array_xd.json\n\n| metric | read_batch_formatted_as_numpy after write_array2d | read_batch_formatted_as_numpy after write_flattened_sequence | read_batch_formatted_as_numpy after write_nested_sequence | read_batch_unformated after write_array2d | read_batch_unformated after write_flattened_sequence | read_batch_unformated after write_nested_sequence | read_col_formatted_as_numpy after write_array2d | read_col_formatted_as_numpy after write_flattened_sequence | read_col_formatted_as_numpy after write_nested_sequence | read_col_unformated after write_array2d | read_col_unformated after write_flattened_sequence | read_col_unformated after write_nested_sequence | read_formatted_as_numpy after write_array2d | read_formatted_as_numpy after write_flattened_sequence | read_formatted_as_numpy after write_nested_sequence | read_unformated after write_array2d | read_unformated after write_flattened_sequence | read_unformated after write_nested_sequence | write_array2d | write_flattened_sequence | write_nested_sequence |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.006374 / 0.011353 (-0.004979) | 0.004100 / 0.011008 (-0.006909) | 0.104031 / 0.038508 (0.065523) | 0.035186 / 0.023109 (0.012076) | 0.328904 / 0.275898 (0.053006) | 0.361409 / 0.323480 (0.037929) | 0.003855 / 0.007986 (-0.004130) | 0.004140 / 0.004328 (-0.000189) | 0.080406 / 0.004250 (0.076156) | 0.045658 / 0.037052 (0.008606) | 0.341133 / 0.258489 (0.082644) | 0.372688 / 0.293841 (0.078847) | 0.032025 / 0.128546 (-0.096521) | 0.008877 / 0.075646 (-0.066769) | 0.354784 / 0.419271 (-0.064488) | 0.068874 / 0.043533 (0.025341) | 0.335441 / 0.255139 (0.080302) | 0.356498 / 0.283200 (0.073298) | 0.113367 / 0.141683 (-0.028316) | 1.522458 / 1.452155 (0.070304) | 1.608046 / 1.492716 (0.115329) |\n\n### Benchmark: benchmark_getitem\\_100B.json\n\n| metric | get_batch_of\\_1024\\_random_rows | get_batch_of\\_1024\\_rows | get_first_row | get_last_row |\n|--------|---|---|---|---|\n| new / old (diff) | 0.231653 / 0.018006 (0.213647) | 0.446678 / 0.000490 (0.446188) | 0.003246 / 0.000200 (0.003046) | 0.000085 / 0.000054 (0.000030) |\n\n### Benchmark: benchmark_indices_mapping.json\n\n| metric | select | shard | shuffle | sort | train_test_split |\n|--------|---|---|---|---|---|\n| new / old (diff) | 0.025299 / 0.037411 (-0.012112) | 0.111440 / 0.014526 (0.096914) | 0.118758 / 0.176557 (-0.057799) | 0.175037 / 0.737135 (-0.562098) | 0.124583 / 0.296338 (-0.171755) |\n\n### Benchmark: benchmark_iterating.json\n\n| metric | read 5000 | read 50000 | read_batch 50000 10 | read_batch 50000 100 | read_batch 50000 1000 | read_formatted numpy 5000 | read_formatted pandas 5000 | read_formatted tensorflow 5000 | read_formatted torch 5000 | read_formatted_batch numpy 5000 10 | read_formatted_batch numpy 5000 1000 | shuffled read 5000 | shuffled read 50000 | shuffled read_batch 50000 10 | shuffled read_batch 50000 100 | shuffled read_batch 50000 1000 | shuffled read_formatted numpy 5000 | shuffled read_formatted_batch numpy 5000 10 | shuffled read_formatted_batch numpy 5000 1000 |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.418694 / 0.215209 (0.203484) | 4.174695 / 2.077655 (2.097041) | 1.890323 / 1.504120 (0.386203) | 1.683300 / 1.541195 (0.142106) | 1.781954 / 1.468490 (0.313464) | 0.546131 / 4.584777 (-4.038645) | 3.768055 / 3.745712 (0.022343) | 1.839878 / 5.269862 (-3.429983) | 1.111877 / 4.565676 (-3.453800) | 0.068568 / 0.424275 (-0.355707) | 0.011950 / 0.007607 (0.004343) | 0.527469 / 0.226044 (0.301425) | 5.274887 / 2.268929 (3.005958) | 2.391274 / 55.444624 (-53.053351) | 2.063837 / 6.876477 (-4.812640) | 2.140627 / 2.142072 (-0.001445) | 0.681508 / 4.805227 (-4.123719) | 0.148203 / 6.500664 (-6.352461) | 0.064456 / 0.075469 (-0.011013) |\n\n### Benchmark: benchmark_map_filter.json\n\n| metric | filter | map fast-tokenizer batched | map identity | map identity batched | map no-op batched | map no-op batched numpy | map no-op batched pandas | map no-op batched pytorch | map no-op batched tensorflow |\n|--------|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 1.221478 / 1.841788 (-0.620310) | 14.713705 / 8.074308 (6.639397) | 14.674184 / 10.191392 (4.482792) | 0.148411 / 0.680424 (-0.532012) | 0.017858 / 0.534201 (-0.516343) | 0.436166 / 0.579283 (-0.143117) | 0.437290 / 0.434364 (0.002926) | 0.521994 / 0.540337 (-0.018343) | 0.635488 / 1.386936 (-0.751448) |\n\n</details>\nPyArrow==latest\n\n<details>\n<summary>Show updated benchmarks!</summary>\n\n### Benchmark: benchmark_array_xd.json\n\n| metric | read_batch_formatted_as_numpy after write_array2d | read_batch_formatted_as_numpy after write_flattened_sequence | read_batch_formatted_as_numpy after write_nested_sequence | read_batch_unformated after write_array2d | read_batch_unformated after write_flattened_sequence | read_batch_unformated after write_nested_sequence | read_col_formatted_as_numpy after write_array2d | read_col_formatted_as_numpy after write_flattened_sequence | read_col_formatted_as_numpy after write_nested_sequence | read_col_unformated after write_array2d | read_col_unformated after write_flattened_sequence | read_col_unformated after write_nested_sequence | read_formatted_as_numpy after write_array2d | read_formatted_as_numpy after write_flattened_sequence | read_formatted_as_numpy after write_nested_sequence | read_unformated after write_array2d | read_unformated after write_flattened_sequence | read_unformated after write_nested_sequence | write_array2d | write_flattened_sequence | write_nested_sequence |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.006108 / 0.011353 (-0.005245) | 0.003888 / 0.011008 (-0.007120) | 0.078424 / 0.038508 (0.039916) | 0.033618 / 0.023109 (0.010509) | 0.376284 / 0.275898 (0.100386) | 0.396957 / 0.323480 (0.073477) | 0.003799 / 0.007986 (-0.004187) | 0.003160 / 0.004328 (-0.001168) | 0.078358 / 0.004250 (0.074107) | 0.045597 / 0.037052 (0.008545) | 0.386396 / 0.258489 (0.127907) | 0.412985 / 0.293841 (0.119144) | 0.031610 / 0.128546 (-0.096936) | 0.008720 / 0.075646 (-0.066926) | 0.085944 / 0.419271 (-0.333328) | 0.050780 / 0.043533 (0.007247) | 0.378099 / 0.255139 (0.122960) | 0.381894 / 0.283200 (0.098694) | 0.098926 / 0.141683 (-0.042756) | 1.513842 / 1.452155 (0.061688) | 1.595040 / 1.492716 (0.102323) |\n\n### Benchmark: benchmark_getitem\\_100B.json\n\n| metric | get_batch_of\\_1024\\_random_rows | get_batch_of\\_1024\\_rows | get_first_row | get_last_row |\n|--------|---|---|---|---|\n| new / old (diff) | 0.208169 / 0.018006 (0.190163) | 0.431653 / 0.000490 (0.431163) | 0.000935 / 0.000200 (0.000735) | 0.000088 / 0.000054 (0.000034) |\n\n### Benchmark: benchmark_indices_mapping.json\n\n| metric | select | shard | shuffle | sort | train_test_split |\n|--------|---|---|---|---|---|\n| new / old (diff) | 0.029600 / 0.037411 (-0.007812) | 0.116936 / 0.014526 (0.102410) | 0.125603 / 0.176557 (-0.050953) | 0.177007 / 0.737135 (-0.560129) | 0.130602 / 0.296338 (-0.165736) |\n\n### Benchmark: benchmark_iterating.json\n\n| metric | read 5000 | read 50000 | read_batch 50000 10 | read_batch 50000 100 | read_batch 50000 1000 | read_formatted numpy 5000 | read_formatted pandas 5000 | read_formatted tensorflow 5000 | read_formatted torch 5000 | read_formatted_batch numpy 5000 10 | read_formatted_batch numpy 5000 1000 | shuffled read 5000 | shuffled read 50000 | shuffled read_batch 50000 10 | shuffled read_batch 50000 100 | shuffled read_batch 50000 1000 | shuffled read_formatted numpy 5000 | shuffled read_formatted_batch numpy 5000 10 | shuffled read_formatted_batch numpy 5000 1000 |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.457158 / 0.215209 (0.241949) | 4.563254 / 2.077655 (2.485599) | 2.303549 / 1.504120 (0.799429) | 2.107269 / 1.541195 (0.566074) | 2.130861 / 1.468490 (0.662371) | 0.548931 / 4.584777 (-4.035846) | 3.745578 / 3.745712 (-0.000134) | 1.820372 / 5.269862 (-3.449490) | 1.099316 / 4.565676 (-3.466361) | 0.068218 / 0.424275 (-0.356057) | 0.012336 / 0.007607 (0.004728) | 0.569721 / 0.226044 (0.343676) | 5.691312 / 2.268929 (3.422384) | 2.797483 / 55.444624 (-52.647141) | 2.422621 / 6.876477 (-4.453855) | 2.426187 / 2.142072 (0.284115) | 0.674777 / 4.805227 (-4.130451) | 0.144855 / 6.500664 (-6.355809) | 0.065805 / 0.075469 (-0.009664) |\n\n### Benchmark: benchmark_map_filter.json\n\n| metric | filter | map fast-tokenizer batched | map identity | map identity batched | map no-op batched | map no-op batched numpy | map no-op batched pandas | map no-op batched pytorch | map no-op batched tensorflow |\n|--------|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 1.305078 / 1.841788 (-0.536709) | 14.874315 / 8.074308 (6.800007) | 14.541301 / 10.191392 (4.349909) | 0.175818 / 0.680424 (-0.504606) | 0.018169 / 0.534201 (-0.516032) | 0.435836 / 0.579283 (-0.143447) | 0.458397 / 0.434364 (0.024033) | 0.506232 / 0.540337 (-0.034106) | 0.605306 / 1.386936 (-0.781630) |\n\n</details>\n</details>\n\n![](https://cml.dev/watermark.png#7e0c1ceab96821c7c6557482d25a9bd2078d716a "CML watermark")\n', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1590944890/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1591106129', 'html_url': 'https://github.com/huggingface/datasets/pull/5954#issuecomment-1591106129', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5954', 'id': 1591106129, 'node_id': 'IC_kwDODunzps5e1lpR', 'user': {'login': 'github-actions[bot]', 'id': 41898282, 'node_id': 'MDM6Qm90NDE4OTgyODI=', 'avatar_url': 'https://avatars.githubusercontent.com/in/15368?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/github-actions%5Bbot%5D', 'html_url': 'https://github.com/apps/github-actions', 'followers_url': 'https://api.github.com/users/github-actions%5Bbot%5D/followers', 'following_url': 'https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}', 'gists_url': 'https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/github-actions%5Bbot%5D/subscriptions', 'organizations_url': 'https://api.github.com/users/github-actions%5Bbot%5D/orgs', 'repos_url': 'https://api.github.com/users/github-actions%5Bbot%5D/repos', 'events_url': 'https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}', 'received_events_url': 'https://api.github.com/users/github-actions%5Bbot%5D/received_events', 'type': 'Bot', 'site_admin': False}, 'created_at': '2023-06-14T12:33:26Z', 'updated_at': '2023-06-14T12:33:26Z', 'author_association': 'NONE', 'body': '<details>\n<summary>Show benchmarks</summary>\n\nPyArrow==8.0.0\n\n<details>\n<summary>Show updated benchmarks!</summary>\n\n### Benchmark: benchmark_array_xd.json\n\n| metric | read_batch_formatted_as_numpy after write_array2d | read_batch_formatted_as_numpy after write_flattened_sequence | read_batch_formatted_as_numpy after write_nested_sequence | read_batch_unformated after write_array2d | read_batch_unformated after write_flattened_sequence | read_batch_unformated after write_nested_sequence | read_col_formatted_as_numpy after write_array2d | read_col_formatted_as_numpy after write_flattened_sequence | read_col_formatted_as_numpy after write_nested_sequence | read_col_unformated after write_array2d | read_col_unformated after write_flattened_sequence | read_col_unformated after write_nested_sequence | read_formatted_as_numpy after write_array2d | read_formatted_as_numpy after write_flattened_sequence | read_formatted_as_numpy after write_nested_sequence | read_unformated after write_array2d | read_unformated after write_flattened_sequence | read_unformated after write_nested_sequence | write_array2d | write_flattened_sequence | write_nested_sequence |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.006138 / 0.011353 (-0.005215) | 0.003792 / 0.011008 (-0.007216) | 0.099417 / 0.038508 (0.060908) | 0.028739 / 0.023109 (0.005630) | 0.302835 / 0.275898 (0.026937) | 0.336397 / 0.323480 (0.012918) | 0.003537 / 0.007986 (-0.004449) | 0.002973 / 0.004328 (-0.001355) | 0.077461 / 0.004250 (0.073211) | 0.039493 / 0.037052 (0.002440) | 0.302367 / 0.258489 (0.043878) | 0.344936 / 0.293841 (0.051095) | 0.027813 / 0.128546 (-0.100733) | 0.008591 / 0.075646 (-0.067055) | 0.318975 / 0.419271 (-0.100297) | 0.045971 / 0.043533 (0.002438) | 0.301672 / 0.255139 (0.046533) | 0.328202 / 0.283200 (0.045003) | 0.091400 / 0.141683 (-0.050282) | 1.487215 / 1.452155 (0.035060) | 1.557730 / 1.492716 (0.065014) |\n\n### Benchmark: benchmark_getitem\\_100B.json\n\n| metric | get_batch_of\\_1024\\_random_rows | get_batch_of\\_1024\\_rows | get_first_row | get_last_row |\n|--------|---|---|---|---|\n| new / old (diff) | 0.208343 / 0.018006 (0.190336) | 0.426764 / 0.000490 (0.426275) | 0.001196 / 0.000200 (0.000996) | 0.000069 / 0.000054 (0.000015) |\n\n### Benchmark: benchmark_indices_mapping.json\n\n| metric | select | shard | shuffle | sort | train_test_split |\n|--------|---|---|---|---|---|\n| new / old (diff) | 0.024332 / 0.037411 (-0.013079) | 0.101861 / 0.014526 (0.087335) | 0.108669 / 0.176557 (-0.067888) | 0.172042 / 0.737135 (-0.565093) | 0.113048 / 0.296338 (-0.183290) |\n\n### Benchmark: benchmark_iterating.json\n\n| metric | read 5000 | read 50000 | read_batch 50000 10 | read_batch 50000 100 | read_batch 50000 1000 | read_formatted numpy 5000 | read_formatted pandas 5000 | read_formatted tensorflow 5000 | read_formatted torch 5000 | read_formatted_batch numpy 5000 10 | read_formatted_batch numpy 5000 1000 | shuffled read 5000 | shuffled read 50000 | shuffled read_batch 50000 10 | shuffled read_batch 50000 100 | shuffled read_batch 50000 1000 | shuffled read_formatted numpy 5000 | shuffled read_formatted_batch numpy 5000 10 | shuffled read_formatted_batch numpy 5000 1000 |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.421419 / 0.215209 (0.206210) | 4.200816 / 2.077655 (2.123162) | 1.913516 / 1.504120 (0.409396) | 1.712167 / 1.541195 (0.170972) | 1.762129 / 1.468490 (0.293639) | 0.561616 / 4.584777 (-4.023161) | 3.398122 / 3.745712 (-0.347590) | 1.744323 / 5.269862 (-3.525538) | 1.036023 / 4.565676 (-3.529653) | 0.067658 / 0.424275 (-0.356617) | 0.011145 / 0.007607 (0.003538) | 0.522803 / 0.226044 (0.296759) | 5.226245 / 2.268929 (2.957317) | 2.355148 / 55.444624 (-53.089476) | 2.014939 / 6.876477 (-4.861538) | 2.140028 / 2.142072 (-0.002044) | 0.695049 / 4.805227 (-4.110178) | 0.138428 / 6.500664 (-6.362236) | 0.066721 / 0.075469 (-0.008748) |\n\n### Benchmark: benchmark_map_filter.json\n\n| metric | filter | map fast-tokenizer batched | map identity | map identity batched | map no-op batched | map no-op batched numpy | map no-op batched pandas | map no-op batched pytorch | map no-op batched tensorflow |\n|--------|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 1.219610 / 1.841788 (-0.622177) | 14.239576 / 8.074308 (6.165268) | 14.381955 / 10.191392 (4.190563) | 0.131208 / 0.680424 (-0.549216) | 0.016698 / 0.534201 (-0.517503) | 0.361373 / 0.579283 (-0.217910) | 0.382560 / 0.434364 (-0.051804) | 0.419427 / 0.540337 (-0.120911) | 0.508314 / 1.386936 (-0.878622) |\n\n</details>\nPyArrow==latest\n\n<details>\n<summary>Show updated benchmarks!</summary>\n\n### Benchmark: benchmark_array_xd.json\n\n| metric | read_batch_formatted_as_numpy after write_array2d | read_batch_formatted_as_numpy after write_flattened_sequence | read_batch_formatted_as_numpy after write_nested_sequence | read_batch_unformated after write_array2d | read_batch_unformated after write_flattened_sequence | read_batch_unformated after write_nested_sequence | read_col_formatted_as_numpy after write_array2d | read_col_formatted_as_numpy after write_flattened_sequence | read_col_formatted_as_numpy after write_neste

[{'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1590891684', 'html_url': 'https://github.com/huggingface/datasets/issues/5953#issuecomment-1590891684', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5953', 'id': 1590891684, 'node_id': 'IC_kwDODunzps5e0xSk', 'user': {'login': 'patrickvonplaten', 'id': 23423619, 'node_id': 'MDQ6VXNlcjIzNDIzNjE5', 'avatar_url': 'https://avatars.githubusercontent.com/u/23423619?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/patrickvonplaten', 'html_url': 'https://github.com/patrickvonplaten', 'followers_url': 'https://api.github.com/users/patrickvonplaten/followers', 'following_url': 'https://api.github.com/users/patrickvonplaten/following{/other_user}', 'gists_url': 'https://api.github.com/users/patrickvonplaten/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/patrickvonplaten/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/patrickvonplaten/subscriptions', 'organizations_url': 'https://api.github.com/users/patrickvonplaten/orgs', 'repos_url': 'https://api.github.com/users/patrickvonplaten/repos', 'events_url': 'https://api.github.com/users/patrickvonplaten/events{/privacy}', 'received_events_url': 'https://api.github.com/users/patrickvonplaten/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-14T10:04:36Z', 'updated_at': '2023-06-14T10:04:36Z', 'author_association': 'MEMBER', 'body': 'cc @sanchit-gandhi @Vaibhavs10 @lhoestq - this is mainly for demos that use Common Voice datasets as done here: https://github.com/facebookresearch/fairseq/tree/main/examples/mms#-transformers\r\n', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1590891684/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1590900665', 'html_url': 'https://github.com/huggingface/datasets/issues/5953#issuecomment-1590900665', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5953', 'id': 1590900665, 'node_id': 'IC_kwDODunzps5e0ze5', 'user': {'login': 'lhoestq', 'id': 42851186, 'node_id': 'MDQ6VXNlcjQyODUxMTg2', 'avatar_url': 'https://avatars.githubusercontent.com/u/42851186?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/lhoestq', 'html_url': 'https://github.com/lhoestq', 'followers_url': 'https://api.github.com/users/lhoestq/followers', 'following_url': 'https://api.github.com/users/lhoestq/following{/other_user}', 'gists_url': 'https://api.github.com/users/lhoestq/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/lhoestq/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/lhoestq/subscriptions', 'organizations_url': 'https://api.github.com/users/lhoestq/orgs', 'repos_url': 'https://api.github.com/users/lhoestq/repos', 'events_url': 'https://api.github.com/users/lhoestq/events{/privacy}', 'received_events_url': 'https://api.github.com/users/lhoestq/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-14T10:10:06Z', 'updated_at': '2023-06-14T10:10:06Z', 'author_association': 'MEMBER', 'body': 'Hi ! the error for me is\r\n\r\n```\r\nFileNotFoundError: Couldn\'t find a dataset script at /content/mozilla-foundation/common_voice_13_0/common_voice_13_0.py or any data file in the same directory. Couldn\'t find \'mozilla-foundation/common_voice_13_0\' on the Hugging Face Hub either: FileNotFoundError: Dataset \'mozilla-foundation/common_voice_13_0\' doesn\'t exist on the Hub. If the repo is private or gated, make sure to log in with `huggingface-cli login`.\r\n```\r\n\r\nAnd tbh idk how you managed to get your error. "n_shards.json" is not even a thing in `datasets`', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1590900665/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1590912854', 'html_url': 'https://github.com/huggingface/datasets/issues/5953#issuecomment-1590912854', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5953', 'id': 1590912854, 'node_id': 'IC_kwDODunzps5e02dW', 'user': {'login': 'Vaibhavs10', 'id': 18682411, 'node_id': 'MDQ6VXNlcjE4NjgyNDEx', 'avatar_url': 'https://avatars.githubusercontent.com/u/18682411?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/Vaibhavs10', 'html_url': 'https://github.com/Vaibhavs10', 'followers_url': 'https://api.github.com/users/Vaibhavs10/followers', 'following_url': 'https://api.github.com/users/Vaibhavs10/following{/other_user}', 'gists_url': 'https://api.github.com/users/Vaibhavs10/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/Vaibhavs10/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/Vaibhavs10/subscriptions', 'organizations_url': 'https://api.github.com/users/Vaibhavs10/orgs', 'repos_url': 'https://api.github.com/users/Vaibhavs10/repos', 'events_url': 'https://api.github.com/users/Vaibhavs10/events{/privacy}', 'received_events_url': 'https://api.github.com/users/Vaibhavs10/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-14T10:17:06Z', 'updated_at': '2023-06-14T10:17:06Z', 'author_association': 'MEMBER', 'body': "Okay, I am able to reproduce @patrickvonplaten's original error: https://github.com/Vaibhavs10/scratchpad/blob/main/cv13_datasets_test.ipynb\r\n\r\nAlso not sure why it looks for `n_shards.json`", 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1590912854/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1590917492', 'html_url': 'https://github.com/huggingface/datasets/issues/5953#issuecomment-1590917492', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5953', 'id': 1590917492, 'node_id': 'IC_kwDODunzps5e03l0', 'user': {'login': 'lhoestq', 'id': 42851186, 'node_id': 'MDQ6VXNlcjQyODUxMTg2', 'avatar_url': 'https://avatars.githubusercontent.com/u/42851186?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/lhoestq', 'html_url': 'https://github.com/lhoestq', 'followers_url': 'https://api.github.com/users/lhoestq/followers', 'following_url': 'https://api.github.com/users/lhoestq/following{/other_user}', 'gists_url': 'https://api.github.com/users/lhoestq/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/lhoestq/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/lhoestq/subscriptions', 'organizations_url': 'https://api.github.com/users/lhoestq/orgs', 'repos_url': 'https://api.github.com/users/lhoestq/repos', 'events_url': 'https://api.github.com/users/lhoestq/events{/privacy}', 'received_events_url': 'https://api.github.com/users/lhoestq/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-14T10:19:12Z', 'updated_at': '2023-06-14T10:19:12Z', 'author_association': 'MEMBER', 'body': 'Ok I see, this file is downloaded from the CV dataset script - let me investigate', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1590917492/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1590919623', 'html_url': 'https://github.com/huggingface/datasets/issues/5953#issuecomment-1590919623', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5953', 'id': 1590919623, 'node_id': 'IC_kwDODunzps5e04HH', 'user': {'login': 'lhoestq', 'id': 42851186, 'node_id': 'MDQ6VXNlcjQyODUxMTg2', 'avatar_url': 'https://avatars.githubusercontent.com/u/42851186?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/lhoestq', 'html_url': 'https://github.com/lhoestq', 'followers_url': 'https://api.github.com/users/lhoestq/followers', 'following_url': 'https://api.github.com/users/lhoestq/following{/other_user}', 'gists_url': 'https://api.github.com/users/lhoestq/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/lhoestq/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/lhoestq/subscriptions', 'organizations_url': 'https://api.github.com/users/lhoestq/orgs', 'repos_url': 'https://api.github.com/users/lhoestq/repos', 'events_url': 'https://api.github.com/users/lhoestq/events{/privacy}', 'received_events_url': 'https://api.github.com/users/lhoestq/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-14T10:20:44Z', 'updated_at': '2023-06-14T10:20:44Z', 'author_association': 'MEMBER', 'body': "Ok I see: when you log out you no longer have access to the repository.\r\n\r\nTherefore the dataset script is loaded from cache:\r\n```\r\nWARNING:datasets.load:Using the latest cached version of the module from /root/.cache/huggingface/modules/datasets_modules/datasets/mozilla-foundation--common_voice_13_0/22809012aac1fc9803eaffc44122e4149043748e93933935d5ea19898587e4d7 (last modified on Wed Jun 14 10:13:17 2023) since it couldn't be found locally at mozilla-foundation/common_voice_13_0., or remotely on the Hugging Face Hub.\r\n```\r\n\r\nand the script tries to download the n_shards.json but fails", 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1590919623/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1591069057', 'html_url': 'https://github.com/huggingface/datasets/issues/5953#issuecomment-1591069057', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5953', 'id': 1591069057, 'node_id': 'IC_kwDODunzps5e1cmB', 'user': {'login': 'lhoestq', 'id': 42851186, 'node_id': 'MDQ6VXNlcjQyODUxMTg2', 'avatar_url': 'https://avatars.githubusercontent.com/u/42851186?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/lhoestq', 'html_url': 'https://github.com/lhoestq', 'followers_url': 'https://api.github.com/users/lhoestq/followers', 'following_url': 'https://api.github.com/users/lhoestq/following{/other_user}', 'gists_url': 'https://api.github.com/users/lhoestq/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/lhoestq/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/lhoestq/subscriptions', 'organizations_url': 'https://api.github.com/users/lhoestq/orgs', 'repos_url': 'https://api.github.com/users/lhoestq/repos', 'events_url': 'https://api.github.com/users/lhoestq/events{/privacy}', 'received_events_url': 'https://api.github.com/users/lhoestq/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-14T12:08:52Z', 'updated_at': '2023-06-14T12:08:52Z', 'author_association': 'MEMBER', 'body': "Is this ok for you https://github.com/huggingface/datasets/pull/5954 ?\r\n\r\nI'll do a release this afternoon", 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1591069057/reactions', 'total_count': 1, '+1': 1, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1591597719', 'html_url': 'https://github.com/huggingface/datasets/issues/5953#issuecomment-1591597719', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5953', 'id': 1591597719, 'node_id': 'IC_kwDODunzps5e3dqX', 'user': {'login': 'patrickvonplaten', 'id': 23423619, 'node_id': 'MDQ6VXNlcjIzNDIzNjE5', 'avatar_url': 'https://avatars.githubusercontent.com/u/23423619?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/patrickvonplaten', 'html_url': 'https://github.com/patrickvonplaten', 'followers_url': 'https://api.github.com/users/patrickvonplaten/followers', 'following_url': 'https://api.github.com/users/patrickvonplaten/following{/other_user}', 'gists_url': 'https://api.github.com/users/patrickvonplaten/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/patrickvonplaten/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/patrickvonplaten/subscriptions', 'organizations_url': 'https://api.github.com/users/patrickvonplaten/orgs', 'repos_url': 'https://api.github.com/users/patrickvonplaten/repos', 'events_url': 'https://api.github.com/users/patrickvonplaten/events{/privacy}', 'received_events_url': 'https://api.github.com/users/patrickvonplaten/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-14T16:22:55Z', 'updated_at': '2023-06-14T16:22:55Z', 'author_association': 'MEMBER', 'body': 'Cool! ', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1591597719/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1591621991', 'html_url': 'https://github.com/huggingface/datasets/issues/5953#issuecomment-1591621991', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5953', 'id': 1591621991, 'node_id': 'IC_kwDODunzps5e3jln', 'user': {'login': 'lhoestq', 'id': 42851186, 'node_id': 'MDQ6VXNlcjQyODUxMTg2', 'avatar_url': 'https://avatars.githubusercontent.com/u/42851186?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/lhoestq', 'html_url': 'https://github.com/lhoestq', 'followers_url': 'https://api.github.com/users/lhoestq/followers', 'following_url': 'https://api.github.com/users/lhoestq/following{/other_user}', 'gists_url': 'https://api.github.com/users/lhoestq/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/lhoestq/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/lhoestq/subscriptions', 'organizations_url': 'https://api.github.com/users/lhoestq/orgs', 'repos_url': 'https://api.github.com/users/lhoestq/repos', 'events_url': 'https://api.github.com/users/lhoestq/events{/privacy}', 'received_events_url': 'https://api.github.com/users/lhoestq/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-14T16:36:51Z', 'updated_at': '2023-06-14T16:36:51Z', 'author_association': 'MEMBER', 'body': 'this is included in the new release 2.13.0', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1591621991/reactions', 'total_count': 1, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 1, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}]

[{'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1590863966', 'html_url': 'https://github.com/huggingface/datasets/pull/5952#issuecomment-1590863966', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5952', 'id': 1590863966, 'node_id': 'IC_kwDODunzps5e0qhe', 'user': {'login': 'HuggingFaceDocBuilderDev', 'id': 99929124, 'node_id': 'U_kgDOBfTMJA', 'avatar_url': 'https://avatars.githubusercontent.com/u/99929124?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/HuggingFaceDocBuilderDev', 'html_url': 'https://github.com/HuggingFaceDocBuilderDev', 'followers_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/followers', 'following_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/following{/other_user}', 'gists_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/subscriptions', 'organizations_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/orgs', 'repos_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/repos', 'events_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/events{/privacy}', 'received_events_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-14T09:47:57Z', 'updated_at': '2023-06-14T14:35:09Z', 'author_association': 'NONE', 'body': '_The documentation is not available anymore as the PR was closed or merged._', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1590863966/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1590866332', 'html_url': 'https://github.com/huggingface/datasets/pull/5952#issuecomment-1590866332', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5952', 'id': 1590866332, 'node_id': 'IC_kwDODunzps5e0rGc', 'user': {'login': 'github-actions[bot]', 'id': 41898282, 'node_id': 'MDM6Qm90NDE4OTgyODI=', 'avatar_url': 'https://avatars.githubusercontent.com/in/15368?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/github-actions%5Bbot%5D', 'html_url': 'https://github.com/apps/github-actions', 'followers_url': 'https://api.github.com/users/github-actions%5Bbot%5D/followers', 'following_url': 'https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}', 'gists_url': 'https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/github-actions%5Bbot%5D/subscriptions', 'organizations_url': 'https://api.github.com/users/github-actions%5Bbot%5D/orgs', 'repos_url': 'https://api.github.com/users/github-actions%5Bbot%5D/repos', 'events_url': 'https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}', 'received_events_url': 'https://api.github.com/users/github-actions%5Bbot%5D/received_events', 'type': 'Bot', 'site_admin': False}, 'created_at': '2023-06-14T09:49:35Z', 'updated_at': '2023-06-14T09:49:35Z', 'author_association': 'NONE', 'body': '<details>\n<summary>Show benchmarks</summary>\n\nPyArrow==8.0.0\n\n<details>\n<summary>Show updated benchmarks!</summary>\n\n### Benchmark: benchmark_array_xd.json\n\n| metric | read_batch_formatted_as_numpy after write_array2d | read_batch_formatted_as_numpy after write_flattened_sequence | read_batch_formatted_as_numpy after write_nested_sequence | read_batch_unformated after write_array2d | read_batch_unformated after write_flattened_sequence | read_batch_unformated after write_nested_sequence | read_col_formatted_as_numpy after write_array2d | read_col_formatted_as_numpy after write_flattened_sequence | read_col_formatted_as_numpy after write_nested_sequence | read_col_unformated after write_array2d | read_col_unformated after write_flattened_sequence | read_col_unformated after write_nested_sequence | read_formatted_as_numpy after write_array2d | read_formatted_as_numpy after write_flattened_sequence | read_formatted_as_numpy after write_nested_sequence | read_unformated after write_array2d | read_unformated after write_flattened_sequence | read_unformated after write_nested_sequence | write_array2d | write_flattened_sequence | write_nested_sequence |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.006522 / 0.011353 (-0.004831) | 0.004319 / 0.011008 (-0.006690) | 0.099280 / 0.038508 (0.060772) | 0.033117 / 0.023109 (0.010007) | 0.339392 / 0.275898 (0.063494) | 0.366219 / 0.323480 (0.042739) | 0.003896 / 0.007986 (-0.004090) | 0.003412 / 0.004328 (-0.000916) | 0.076655 / 0.004250 (0.072404) | 0.045203 / 0.037052 (0.008150) | 0.355800 / 0.258489 (0.097311) | 0.372533 / 0.293841 (0.078692) | 0.032318 / 0.128546 (-0.096229) | 0.009030 / 0.075646 (-0.066616) | 0.328701 / 0.419271 (-0.090571) | 0.052891 / 0.043533 (0.009358) | 0.341131 / 0.255139 (0.085992) | 0.351593 / 0.283200 (0.068393) | 0.105136 / 0.141683 (-0.036546) | 1.475953 / 1.452155 (0.023798) | 1.566074 / 1.492716 (0.073357) |\n\n### Benchmark: benchmark_getitem\\_100B.json\n\n| metric | get_batch_of\\_1024\\_random_rows | get_batch_of\\_1024\\_rows | get_first_row | get_last_row |\n|--------|---|---|---|---|\n| new / old (diff) | 0.216671 / 0.018006 (0.198664) | 0.446952 / 0.000490 (0.446462) | 0.006340 / 0.000200 (0.006140) | 0.000096 / 0.000054 (0.000042) |\n\n### Benchmark: benchmark_indices_mapping.json\n\n| metric | select | shard | shuffle | sort | train_test_split |\n|--------|---|---|---|---|---|\n| new / old (diff) | 0.028293 / 0.037411 (-0.009118) | 0.112298 / 0.014526 (0.097773) | 0.118634 / 0.176557 (-0.057923) | 0.175542 / 0.737135 (-0.561593) | 0.124773 / 0.296338 (-0.171565) |\n\n### Benchmark: benchmark_iterating.json\n\n| metric | read 5000 | read 50000 | read_batch 50000 10 | read_batch 50000 100 | read_batch 50000 1000 | read_formatted numpy 5000 | read_formatted pandas 5000 | read_formatted tensorflow 5000 | read_formatted torch 5000 | read_formatted_batch numpy 5000 10 | read_formatted_batch numpy 5000 1000 | shuffled read 5000 | shuffled read 50000 | shuffled read_batch 50000 10 | shuffled read_batch 50000 100 | shuffled read_batch 50000 1000 | shuffled read_formatted numpy 5000 | shuffled read_formatted_batch numpy 5000 10 | shuffled read_formatted_batch numpy 5000 1000 |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.435209 / 0.215209 (0.220000) | 4.344361 / 2.077655 (2.266706) | 2.128943 / 1.504120 (0.624823) | 1.945465 / 1.541195 (0.404271) | 2.049932 / 1.468490 (0.581442) | 0.547126 / 4.584777 (-4.037651) | 3.768698 / 3.745712 (0.022986) | 1.924441 / 5.269862 (-3.345420) | 1.146364 / 4.565676 (-3.419312) | 0.067466 / 0.424275 (-0.356809) | 0.011175 / 0.007607 (0.003568) | 0.540978 / 0.226044 (0.314933) | 5.393120 / 2.268929 (3.124191) | 2.639027 / 55.444624 (-52.805597) | 2.327216 / 6.876477 (-4.549261) | 2.500532 / 2.142072 (0.358460) | 0.679120 / 4.805227 (-4.126107) | 0.148824 / 6.500664 (-6.351840) | 0.064195 / 0.075469 (-0.011274) |\n\n### Benchmark: benchmark_map_filter.json\n\n| metric | filter | map fast-tokenizer batched | map identity | map identity batched | map no-op batched | map no-op batched numpy | map no-op batched pandas | map no-op batched pytorch | map no-op batched tensorflow |\n|--------|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 1.158387 / 1.841788 (-0.683401) | 14.880751 / 8.074308 (6.806443) | 14.725249 / 10.191392 (4.533857) | 0.149785 / 0.680424 (-0.530639) | 0.017338 / 0.534201 (-0.516863) | 0.390980 / 0.579283 (-0.188303) | 0.425611 / 0.434364 (-0.008753) | 0.458851 / 0.540337 (-0.081487) | 0.559209 / 1.386936 (-0.827727) |\n\n</details>\nPyArrow==latest\n\n<details>\n<summary>Show updated benchmarks!</summary>\n\n### Benchmark: benchmark_array_xd.json\n\n| metric | read_batch_formatted_as_numpy after write_array2d | read_batch_formatted_as_numpy after write_flattened_sequence | read_batch_formatted_as_numpy after write_nested_sequence | read_batch_unformated after write_array2d | read_batch_unformated after write_flattened_sequence | read_batch_unformated after write_nested_sequence | read_col_formatted_as_numpy after write_array2d | read_col_formatted_as_numpy after write_flattened_sequence | read_col_formatted_as_numpy after write_nested_sequence | read_col_unformated after write_array2d | read_col_unformated after write_flattened_sequence | read_col_unformated after write_nested_sequence | read_formatted_as_numpy after write_array2d | read_formatted_as_numpy after write_flattened_sequence | read_formatted_as_numpy after write_nested_sequence | read_unformated after write_array2d | read_unformated after write_flattened_sequence | read_unformated after write_nested_sequence | write_array2d | write_flattened_sequence | write_nested_sequence |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.006835 / 0.011353 (-0.004518) | 0.004318 / 0.011008 (-0.006690) | 0.076715 / 0.038508 (0.038207) | 0.033528 / 0.023109 (0.010419) | 0.411986 / 0.275898 (0.136087) | 0.438752 / 0.323480 (0.115272) | 0.004039 / 0.007986 (-0.003947) | 0.003509 / 0.004328 (-0.000819) | 0.077924 / 0.004250 (0.073673) | 0.049519 / 0.037052 (0.012467) | 0.420595 / 0.258489 (0.162106) | 0.450536 / 0.293841 (0.156695) | 0.032817 / 0.128546 (-0.095729) | 0.008963 / 0.075646 (-0.066684) | 0.083818 / 0.419271 (-0.335454) | 0.057591 / 0.043533 (0.014058) | 0.404605 / 0.255139 (0.149466) | 0.423661 / 0.283200 (0.140462) | 0.110698 / 0.141683 (-0.030984) | 1.512515 / 1.452155 (0.060361) | 1.569207 / 1.492716 (0.076490) |\n\n### Benchmark: benchmark_getitem\\_100B.json\n\n| metric | get_batch_of\\_1024\\_random_rows | get_batch_of\\_1024\\_rows | get_first_row | get_last_row |\n|--------|---|---|---|---|\n| new / old (diff) | 0.200795 / 0.018006 (0.182789) | 0.448853 / 0.000490 (0.448363) | 0.003657 / 0.000200 (0.003457) | 0.000102 / 0.000054 (0.000048) |\n\n### Benchmark: benchmark_indices_mapping.json\n\n| metric | select | shard | shuffle | sort | train_test_split |\n|--------|---|---|---|---|---|\n| new / old (diff) | 0.031612 / 0.037411 (-0.005799) | 0.116712 / 0.014526 (0.102186) | 0.126162 / 0.176557 (-0.050395) | 0.180522 / 0.737135 (-0.556614) | 0.129768 / 0.296338 (-0.166570) |\n\n### Benchmark: benchmark_iterating.json\n\n| metric | read 5000 | read 50000 | read_batch 50000 10 | read_batch 50000 100 | read_batch 50000 1000 | read_formatted numpy 5000 | read_formatted pandas 5000 | read_formatted tensorflow 5000 | read_formatted torch 5000 | read_formatted_batch numpy 5000 10 | read_formatted_batch numpy 5000 1000 | shuffled read 5000 | shuffled read 50000 | shuffled read_batch 50000 10 | shuffled read_batch 50000 100 | shuffled read_batch 50000 1000 | shuffled read_formatted numpy 5000 | shuffled read_formatted_batch numpy 5000 10 | shuffled read_formatted_batch numpy 5000 1000 |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.433797 / 0.215209 (0.218588) | 4.353099 / 2.077655 (2.275444) | 2.117582 / 1.504120 (0.613462) | 1.934487 / 1.541195 (0.393292) | 2.016988 / 1.468490 (0.548498) | 0.531387 / 4.584777 (-4.053390) | 3.843520 / 3.745712 (0.097807) | 1.879560 / 5.269862 (-3.390301) | 1.129445 / 4.565676 (-3.436231) | 0.065952 / 0.424275 (-0.358323) | 0.011566 / 0.007607 (0.003959) | 0.533949 / 0.226044 (0.307904) | 5.327447 / 2.268929 (3.058518) | 2.572202 / 55.444624 (-52.872422) | 2.240723 / 6.876477 (-4.635753) | 2.329290 / 2.142072 (0.187217) | 0.662162 / 4.805227 (-4.143066) | 0.143191 / 6.500664 (-6.357473) | 0.065273 / 0.075469 (-0.010196) |\n\n### Benchmark: benchmark_map_filter.json\n\n| metric | filter | map fast-tokenizer batched | map identity | map identity batched | map no-op batched | map no-op batched numpy | map no-op batched pandas | map no-op batched pytorch | map no-op batched tensorflow |\n|--------|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 1.274945 / 1.841788 (-0.566843) | 15.444511 / 8.074308 (7.370203) | 14.793524 / 10.191392 (4.602132) | 0.175607 / 0.680424 (-0.504817) | 0.017324 / 0.534201 (-0.516877) | 0.396172 / 0.579283 (-0.183111) | 0.437334 / 0.434364 (0.002970) | 0.472621 / 0.540337 (-0.067716) | 0.574888 / 1.386936 (-0.812048) |\n\n</details>\n</details>\n\n![](https://cml.dev/watermark.png#b4ab1b3ed7257b0e0ad075d7271a51835f320a5e "CML watermark")\n', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1590866332/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1591366071', 'html_url': 'https://github.com/huggingface/datasets/pull/5952#issuecomment-1591366071', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5952', 'id': 1591366071, 'node_id': 'IC_kwDODunzps5e2lG3', 'user': {'login': 'github-actions[bot]', 'id': 41898282, 'node_id': 'MDM6Qm90NDE4OTgyODI=', 'avatar_url': 'https://avatars.githubusercontent.com/in/15368?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/github-actions%5Bbot%5D', 'html_url': 'https://github.com/apps/github-actions', 'followers_url': 'https://api.github.com/users/github-actions%5Bbot%5D/followers', 'following_url': 'https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}', 'gists_url': 'https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/github-actions%5Bbot%5D/subscriptions', 'organizations_url': 'https://api.github.com/users/github-actions%5Bbot%5D/orgs', 'repos_url': 'https://api.github.com/users/github-actions%5Bbot%5D/repos', 'events_url': 'https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}', 'received_events_url': 'https://api.github.com/users/github-actions%5Bbot%5D/received_events', 'type': 'Bot', 'site_admin': False}, 'created_at': '2023-06-14T14:42:30Z', 'updated_at': '2023-06-14T14:42:30Z', 'author_association': 'NONE', 'body': '<details>\n<summary>Show benchmarks</summary>\n\nPyArrow==8.0.0\n\n<details>\n<summary>Show updated benchmarks!</summary>\n\n### Benchmark: benchmark_array_xd.json\n\n| metric | read_batch_formatted_as_numpy after write_array2d | read_batch_formatted_as_numpy after write_flattened_sequence | read_batch_formatted_as_numpy after write_nested_sequence | read_batch_unformated after write_array2d | read_batch_unformated after write_flattened_sequence | read_batch_unformated after write_nested_sequence | read_col_formatted_as_numpy after write_array2d | read_col_formatted_as_numpy after write_flattened_sequence | read_col_formatted_as_numpy after write_nested_sequence | read_col_unformated after write_array2d | read_col_unformated after write_flattened_sequence | read_col_unformated after write_nested_sequence | read_formatted_as_numpy after write_array2d | read_formatted_as_numpy after write_flattened_sequence | read_formatted_as_numpy after write_nested_sequence | read_unformated after write_array2d | read_unformated after write_flattened_sequence | read_unformated after write_nested_sequence | write_array2d | write_flattened_sequence | write_nested_sequence |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.006976 / 0.011353 (-0.004377) | 0.004541 / 0.011008 (-0.006467) | 0.106085 / 0.038508 (0.067577) | 0.029148 / 0.023109 (0.006039) | 0.306386 / 0.275898 (0.030488) | 0.351474 / 0.323480 (0.027994) | 0.003924 / 0.007986 (-0.004062) | 0.004588 / 0.004328 (0.000260) | 0.090479 / 0.004250 (0.086229) | 0.041195 / 0.037052 (0.004142) | 0.346020 / 0.258489 (0.087531) | 0.362526 / 0.293841 (0.068685) | 0.041020 / 0.128546 (-0.087526) | 0.012536 / 0.075646 (-0.063110) | 0.333247 / 0.419271 (-0.086024) | 0.059786 / 0.043533 (0.016253) | 0.318094 / 0.255139 (0.062955) | 0.343879 / 0.283200 (0.060679) | 0.110083 / 0.141683 (-0.031600) | 1.514027 / 1.452155 (0.061872) | 1.551435 / 1.492716 (0.058719) |\n\n### Benchmark: benchmark_getitem\\_100B.json\n\n| metric | get_batch_of\\_1024\\_random_rows | get_batch_of\\_1024\\_rows | get_first_row | get_last_row |\n|--------|---|---|---|---|\n| new / old (diff) | 0.235401 / 0.018006 (0.217395) | 0.544292 / 0.000490 (0.543803) | 0.005284 / 0.000200 (0.005084) | 0.000112 / 0.000054 (0.000057) |\n\n### Benchmark: benchmark_indices_mapping.json\n\n| metric | select | shard | shuffle | sort | train_test_split |\n|--------|---|---|---|---|---|\n| new / old (diff) | 0.025008 / 0.037411 (-0.012403) | 0.102235 / 0.014526 (0.087709) | 0.105523 / 0.176557 (-0.071034) | 0.180846 / 0.737135 (-0.556289) | 0.107078 / 0.296338 (-0.189261) |\n\n### Benchmark: benchmark_iterating.json\n\n| metric | read 5000 | read 50000 | read_batch 50000 10 | read_batch 50000 100 | read_batch 50000 1000 | read_formatted numpy 5000 | read_formatted pandas 5000 | read_formatted tensorflow 5000 | read_formatted torch 5000 | read_formatted_batch numpy 5000 10 | read_formatted_batch numpy 5000 1000 | shuffled read 5000 | shuffled read 50000 | shuffled read_batch 50000 10 | shuffled read_batch 50000 100 | shuffled read_batch 50000 1000 | shuffled read_formatted numpy 5000 | shuffled read_formatted_batch numpy 5000 10 | shuffled read_formatted_batch numpy 5000 1000 |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.502374 / 0.215209 (0.287165) | 5.224254 / 2.077655 (3.146600) | 1.987193 / 1.504120 (0.483073) | 1.694680 / 1.541195 (0.153485) | 1.663907 / 1.468490 (0.195417) | 0.786470 / 4.584777 (-3.798307) | 4.977895 / 3.745712 (1.232183) | 4.713451 / 5.269862 (-0.556410) | 2.298763 / 4.565676 (-2.266913) | 0.090225 / 0.424275 (-0.334051) | 0.011427 / 0.007607 (0.003820) | 0.640686 / 0.226044 (0.414641) | 6.351727 / 2.268929 (4.082798) | 2.636912 / 55.444624 (-52.807712) | 2.075566 / 6.876477 (-4.800911) | 2.080260 / 2.142072 (-0.061812) | 0.952727 / 4.805227 (-3.852500) | 0.188651 / 6.500664 (-6.312013) | 0.068997 / 0.075469 (-0.006472) |\n\n### Benchmark: benchmark_map_filter.json\n\n| metric | filter | map fast-tokenizer batched | map identity | map identity batched | map no-op batched | map no-op batched numpy | map no-op batched pandas | map no-op batched pytorch | map no-op batched tensorflow |\n|--------|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 1.258878 / 1.841788 (-0.582910) | 15.444724 / 8.074308 (7.370416) | 17.521918 / 10.191392 (7.330526) | 0.189732 / 0.680424 (-0.490692) | 0.031084 / 0.534201 (-0.503117) | 0.445150 / 0.579283 (-0.134133) | 0.575844 / 0.434364 (0.141480) | 0.498162 / 0.540337 (-0.042176) | 0.635885 / 1.386936 (-0.751051) |\n\n</details>\nPyArrow==latest\n\n<details>\n<summary>Show updated benchmarks!</summary>\n\n### Benchmark: benchmark_array_xd.json\n\n| metric | read_batch_formatted_as_numpy after write_array2d | read_batch_formatted_as_numpy after write_flattened_sequence | read_batch_formatted_as_numpy after write_nested_sequence | read_batch_unformated after write_array2d | read_batch_unformated after write_flattened_sequence | read_batch_unformated after write_nested_sequence | read_col_formatted_as_numpy after write_array2d | read_col_formatted_as_numpy after write_flattened_sequence | read_col_formatted_as_numpy after write_nested_se

[{'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1591070908', 'html_url': 'https://github.com/huggingface/datasets/issues/5951#issuecomment-1591070908', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5951', 'id': 1591070908, 'node_id': 'IC_kwDODunzps5e1dC8', 'user': {'login': 'lhoestq', 'id': 42851186, 'node_id': 'MDQ6VXNlcjQyODUxMTg2', 'avatar_url': 'https://avatars.githubusercontent.com/u/42851186?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/lhoestq', 'html_url': 'https://github.com/lhoestq', 'followers_url': 'https://api.github.com/users/lhoestq/followers', 'following_url': 'https://api.github.com/users/lhoestq/following{/other_user}', 'gists_url': 'https://api.github.com/users/lhoestq/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/lhoestq/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/lhoestq/subscriptions', 'organizations_url': 'https://api.github.com/users/lhoestq/orgs', 'repos_url': 'https://api.github.com/users/lhoestq/repos', 'events_url': 'https://api.github.com/users/lhoestq/events{/privacy}', 'received_events_url': 'https://api.github.com/users/lhoestq/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-14T12:10:16Z', 'updated_at': '2023-06-14T12:10:16Z', 'author_association': 'MEMBER', 'body': "Thanks for opening https://huggingface.co/datasets/discofuse/discussions/3, let's continue the discussion over there if you don't mind", 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1591070908/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1591205426', 'html_url': 'https://github.com/huggingface/datasets/issues/5951#issuecomment-1591205426', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5951', 'id': 1591205426, 'node_id': 'IC_kwDODunzps5e194y', 'user': {'login': 'akesh1235', 'id': 125154243, 'node_id': 'U_kgDOB3Wzww', 'avatar_url': 'https://avatars.githubusercontent.com/u/125154243?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/akesh1235', 'html_url': 'https://github.com/akesh1235', 'followers_url': 'https://api.github.com/users/akesh1235/followers', 'following_url': 'https://api.github.com/users/akesh1235/following{/other_user}', 'gists_url': 'https://api.github.com/users/akesh1235/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/akesh1235/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/akesh1235/subscriptions', 'organizations_url': 'https://api.github.com/users/akesh1235/orgs', 'repos_url': 'https://api.github.com/users/akesh1235/repos', 'events_url': 'https://api.github.com/users/akesh1235/events{/privacy}', 'received_events_url': 'https://api.github.com/users/akesh1235/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-14T13:24:33Z', 'updated_at': '2023-06-14T13:25:06Z', 'author_association': 'NONE', 'body': 'I have posted there also sir, please check\r\n@lhoestq', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1591205426/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}]
[{'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1591075911', 'html_url': 'https://github.com/huggingface/datasets/issues/5950#issuecomment-1591075911', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5950', 'id': 1591075911, 'node_id': 'IC_kwDODunzps5e1eRH', 'user': {'login': 'lhoestq', 'id': 42851186, 'node_id': 'MDQ6VXNlcjQyODUxMTg2', 'avatar_url': 'https://avatars.githubusercontent.com/u/42851186?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/lhoestq', 'html_url': 'https://github.com/lhoestq', 'followers_url': 'https://api.github.com/users/lhoestq/followers', 'following_url': 'https://api.github.com/users/lhoestq/following{/other_user}', 'gists_url': 'https://api.github.com/users/lhoestq/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/lhoestq/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/lhoestq/subscriptions', 'organizations_url': 'https://api.github.com/users/lhoestq/orgs', 'repos_url': 'https://api.github.com/users/lhoestq/repos', 'events_url': 'https://api.github.com/users/lhoestq/events{/privacy}', 'received_events_url': 'https://api.github.com/users/lhoestq/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-14T12:13:38Z', 'updated_at': '2023-06-14T12:13:38Z', 'author_association': 'MEMBER', 'body': 'Hi ! We use the Arrow columnar format under the hood, which doesn\'t support such dictionaries: each field must have a fixed type and exist in each sample.\r\n\r\nInstead you can restructure your data like\r\n```\r\n{\r\n    "index": 0,\r\n    "keys": ["2 * x + y >= 3"],\r\n    "values": [["2 * x + y >= 3", "4 * x + 2 * y >= 6"]],\r\n    }\r\n},\r\n...\r\n{\r\n    "index": 9999,\r\n    "keys": ["x >= 6"],\r\n    "values": [["x >= 6", "x >= 0", "x >= -1"]],\r\n},\r\n...\r\n```', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1591075911/reactions', 'total_count': 1, '+1': 1, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}]

[{'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1589241316', 'html_url': 'https://github.com/huggingface/datasets/pull/5948#issuecomment-1589241316', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5948', 'id': 1589241316, 'node_id': 'IC_kwDODunzps5eueXk', 'user': {'login': 'HuggingFaceDocBuilderDev', 'id': 99929124, 'node_id': 'U_kgDOBfTMJA', 'avatar_url': 'https://avatars.githubusercontent.com/u/99929124?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/HuggingFaceDocBuilderDev', 'html_url': 'https://github.com/HuggingFaceDocBuilderDev', 'followers_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/followers', 'following_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/following{/other_user}', 'gists_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/subscriptions', 'organizations_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/orgs', 'repos_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/repos', 'events_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/events{/privacy}', 'received_events_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-13T12:44:25Z', 'updated_at': '2023-06-14T15:04:22Z', 'author_association': 'NONE', 'body': '_The documentation is not available anymore as the PR was closed or merged._', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1589241316/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1591437857', 'html_url': 'https://github.com/huggingface/datasets/pull/5948#issuecomment-1591437857', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5948', 'id': 1591437857, 'node_id': 'IC_kwDODunzps5e22oh', 'user': {'login': 'github-actions[bot]', 'id': 41898282, 'node_id': 'MDM6Qm90NDE4OTgyODI=', 'avatar_url': 'https://avatars.githubusercontent.com/in/15368?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/github-actions%5Bbot%5D', 'html_url': 'https://github.com/apps/github-actions', 'followers_url': 'https://api.github.com/users/github-actions%5Bbot%5D/followers', 'following_url': 'https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}', 'gists_url': 'https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/github-actions%5Bbot%5D/subscriptions', 'organizations_url': 'https://api.github.com/users/github-actions%5Bbot%5D/orgs', 'repos_url': 'https://api.github.com/users/github-actions%5Bbot%5D/repos', 'events_url': 'https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}', 'received_events_url': 'https://api.github.com/users/github-actions%5Bbot%5D/received_events', 'type': 'Bot', 'site_admin': False}, 'created_at': '2023-06-14T15:11:54Z', 'updated_at': '2023-06-14T15:11:54Z', 'author_association': 'NONE', 'body': '<details>\n<summary>Show benchmarks</summary>\n\nPyArrow==8.0.0\n\n<details>\n<summary>Show updated benchmarks!</summary>\n\n### Benchmark: benchmark_array_xd.json\n\n| metric | read_batch_formatted_as_numpy after write_array2d | read_batch_formatted_as_numpy after write_flattened_sequence | read_batch_formatted_as_numpy after write_nested_sequence | read_batch_unformated after write_array2d | read_batch_unformated after write_flattened_sequence | read_batch_unformated after write_nested_sequence | read_col_formatted_as_numpy after write_array2d | read_col_formatted_as_numpy after write_flattened_sequence | read_col_formatted_as_numpy after write_nested_sequence | read_col_unformated after write_array2d | read_col_unformated after write_flattened_sequence | read_col_unformated after write_nested_sequence | read_formatted_as_numpy after write_array2d | read_formatted_as_numpy after write_flattened_sequence | read_formatted_as_numpy after write_nested_sequence | read_unformated after write_array2d | read_unformated after write_flattened_sequence | read_unformated after write_nested_sequence | write_array2d | write_flattened_sequence | write_nested_sequence |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.007220 / 0.011353 (-0.004133) | 0.004558 / 0.011008 (-0.006451) | 0.116647 / 0.038508 (0.078139) | 0.046845 / 0.023109 (0.023736) | 0.352429 / 0.275898 (0.076531) | 0.429739 / 0.323480 (0.106259) | 0.006620 / 0.007986 (-0.001366) | 0.003731 / 0.004328 (-0.000597) | 0.088683 / 0.004250 (0.084433) | 0.070583 / 0.037052 (0.033530) | 0.366699 / 0.258489 (0.108210) | 0.420730 / 0.293841 (0.126889) | 0.037342 / 0.128546 (-0.091204) | 0.010041 / 0.075646 (-0.065605) | 0.383477 / 0.419271 (-0.035795) | 0.060279 / 0.043533 (0.016746) | 0.349988 / 0.255139 (0.094849) | 0.371423 / 0.283200 (0.088224) | 0.026725 / 0.141683 (-0.114958) | 1.736886 / 1.452155 (0.284731) | 1.812874 / 1.492716 (0.320157) |\n\n### Benchmark: benchmark_getitem\\_100B.json\n\n| metric | get_batch_of\\_1024\\_random_rows | get_batch_of\\_1024\\_rows | get_first_row | get_last_row |\n|--------|---|---|---|---|\n| new / old (diff) | 0.253256 / 0.018006 (0.235250) | 0.563470 / 0.000490 (0.562980) | 0.010475 / 0.000200 (0.010275) | 0.000164 / 0.000054 (0.000110) |\n\n### Benchmark: benchmark_indices_mapping.json\n\n| metric | select | shard | shuffle | sort | train_test_split |\n|--------|---|---|---|---|---|\n| new / old (diff) | 0.030518 / 0.037411 (-0.006893) | 0.133324 / 0.014526 (0.118798) | 0.137095 / 0.176557 (-0.039461) | 0.202227 / 0.737135 (-0.534909) | 0.144195 / 0.296338 (-0.152143) |\n\n### Benchmark: benchmark_iterating.json\n\n| metric | read 5000 | read 50000 | read_batch 50000 10 | read_batch 50000 100 | read_batch 50000 1000 | read_formatted numpy 5000 | read_formatted pandas 5000 | read_formatted tensorflow 5000 | read_formatted torch 5000 | read_formatted_batch numpy 5000 10 | read_formatted_batch numpy 5000 1000 | shuffled read 5000 | shuffled read 50000 | shuffled read_batch 50000 10 | shuffled read_batch 50000 100 | shuffled read_batch 50000 1000 | shuffled read_formatted numpy 5000 | shuffled read_formatted_batch numpy 5000 10 | shuffled read_formatted_batch numpy 5000 1000 |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.480870 / 0.215209 (0.265661) | 4.822713 / 2.077655 (2.745058) | 2.124183 / 1.504120 (0.620064) | 1.910733 / 1.541195 (0.369538) | 1.970266 / 1.468490 (0.501776) | 0.624695 / 4.584777 (-3.960082) | 4.459659 / 3.745712 (0.713947) | 2.210123 / 5.269862 (-3.059739) | 1.300520 / 4.565676 (-3.265157) | 0.077096 / 0.424275 (-0.347180) | 0.013333 / 0.007607 (0.005726) | 0.596841 / 0.226044 (0.370797) | 5.917397 / 2.268929 (3.648469) | 2.699397 / 55.444624 (-52.745228) | 2.274833 / 6.876477 (-4.601644) | 2.525376 / 2.142072 (0.383304) | 0.755718 / 4.805227 (-4.049510) | 0.163587 / 6.500664 (-6.337077) | 0.072817 / 0.075469 (-0.002653) |\n\n### Benchmark: benchmark_map_filter.json\n\n| metric | filter | map fast-tokenizer batched | map identity | map identity batched | map no-op batched | map no-op batched numpy | map no-op batched pandas | map no-op batched pytorch | map no-op batched tensorflow |\n|--------|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 1.524306 / 1.841788 (-0.317481) | 18.843312 / 8.074308 (10.769004) | 15.694644 / 10.191392 (5.503252) | 0.177400 / 0.680424 (-0.503024) | 0.020104 / 0.534201 (-0.514097) | 0.466421 / 0.579283 (-0.112862) | 0.537274 / 0.434364 (0.102910) | 0.576920 / 0.540337 (0.036583) | 0.718889 / 1.386936 (-0.668047) |\n\n</details>\nPyArrow==latest\n\n<details>\n<summary>Show updated benchmarks!</summary>\n\n### Benchmark: benchmark_array_xd.json\n\n| metric | read_batch_formatted_as_numpy after write_array2d | read_batch_formatted_as_numpy after write_flattened_sequence | read_batch_formatted_as_numpy after write_nested_sequence | read_batch_unformated after write_array2d | read_batch_unformated after write_flattened_sequence | read_batch_unformated after write_nested_sequence | read_col_formatted_as_numpy after write_array2d | read_col_formatted_as_numpy after write_flattened_sequence | read_col_formatted_as_numpy after write_nested_sequence | read_col_unformated after write_array2d | read_col_unformated after write_flattened_sequence | read_col_unformated after write_nested_sequence | read_formatted_as_numpy after write_array2d | read_formatted_as_numpy after write_flattened_sequence | read_formatted_as_numpy after write_nested_sequence | read_unformated after write_array2d | read_unformated after write_flattened_sequence | read_unformated after write_nested_sequence | write_array2d | write_flattened_sequence | write_nested_sequence |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.007671 / 0.011353 (-0.003682) | 0.004850 / 0.011008 (-0.006158) | 0.090085 / 0.038508 (0.051576) | 0.052023 / 0.023109 (0.028914) | 0.508575 / 0.275898 (0.232677) | 0.590024 / 0.323480 (0.266544) | 0.004564 / 0.007986 (-0.003422) | 0.005345 / 0.004328 (0.001017) | 0.087904 / 0.004250 (0.083653) | 0.064446 / 0.037052 (0.027394) | 0.525625 / 0.258489 (0.267136) | 0.584307 / 0.293841 (0.290466) | 0.037221 / 0.128546 (-0.091325) | 0.010588 / 0.075646 (-0.065059) | 0.098612 / 0.419271 (-0.320659) | 0.059597 / 0.043533 (0.016064) | 0.488064 / 0.255139 (0.232925) | 0.522330 / 0.283200 (0.239131) | 0.030004 / 0.141683 (-0.111679) | 1.732512 / 1.452155 (0.280357) | 1.809027 / 1.492716 (0.316310) |\n\n### Benchmark: benchmark_getitem\\_100B.json\n\n| metric | get_batch_of\\_1024\\_random_rows | get_batch_of\\_1024\\_rows | get_first_row | get_last_row |\n|--------|---|---|---|---|\n| new / old (diff) | 0.218741 / 0.018006 (0.200735) | 0.494946 / 0.000490 (0.494456) | 0.004580 / 0.000200 (0.004380) | 0.000104 / 0.000054 (0.000049) |\n\n### Benchmark: benchmark_indices_mapping.json\n\n| metric | select | shard | shuffle | sort | train_test_split |\n|--------|---|---|---|---|---|\n| new / old (diff) | 0.034916 / 0.037411 (-0.002495) | 0.133695 / 0.014526 (0.119169) | 0.147964 / 0.176557 (-0.028592) | 0.213210 / 0.737135 (-0.523926) | 0.148850 / 0.296338 (-0.147488) |\n\n### Benchmark: benchmark_iterating.json\n\n| metric | read 5000 | read 50000 | read_batch 50000 10 | read_batch 50000 100 | read_batch 50000 1000 | read_formatted numpy 5000 | read_formatted pandas 5000 | read_formatted tensorflow 5000 | read_formatted torch 5000 | read_formatted_batch numpy 5000 10 | read_formatted_batch numpy 5000 1000 | shuffled read 5000 | shuffled read 50000 | shuffled read_batch 50000 10 | shuffled read_batch 50000 100 | shuffled read_batch 50000 1000 | shuffled read_formatted numpy 5000 | shuffled read_formatted_batch numpy 5000 10 | shuffled read_formatted_batch numpy 5000 1000 |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.508855 / 0.215209 (0.293646) | 5.065088 / 2.077655 (2.987433) | 2.473110 / 1.504120 (0.968990) | 2.259765 / 1.541195 (0.718570) | 2.359189 / 1.468490 (0.890699) | 0.639082 / 4.584777 (-3.945695) | 4.768195 / 3.745712 (1.022482) | 2.253803 / 5.269862 (-3.016059) | 1.442996 / 4.565676 (-3.122680) | 0.078761 / 0.424275 (-0.345514) | 0.013936 / 0.007607 (0.006329) | 0.625977 / 0.226044 (0.399933) | 6.260817 / 2.268929 (3.991888) | 3.149640 / 55.444624 (-52.294985) | 2.753555 / 6.876477 (-4.122921) | 2.831872 / 2.142072 (0.689799) | 0.781294 / 4.805227 (-4.023933) | 0.169109 / 6.500664 (-6.331555) | 0.075810 / 0.075469 (0.000341) |\n\n### Benchmark: benchmark_map_filter.json\n\n| metric | filter | map fast-tokenizer batched | map identity | map identity batched | map no-op batched | map no-op batched numpy | map no-op batched pandas | map no-op batched pytorch | map no-op batched tensorflow |\n|--------|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 1.533282 / 1.841788 (-0.308506) | 19.460579 / 8.074308 (11.386271) | 17.250424 / 10.191392 (7.059032) | 0.193485 / 0.680424 (-0.486939) | 0.020650 / 0.534201 (-0.513551) | 0.472110 / 0.579283 (-0.107173) | 0.532276 / 0.434364 (0.097912) | 0.613152 / 0.540337 (0.072814) | 0.684684 / 1.386936 (-0.702252) |\n\n</details>\n</details>\n\n![](https://cml.dev/watermark.png#650a86ee122209d4a8c8e8068c01ebfd3ba553f5 "CML watermark")\n', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1591437857/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}]

[{'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1591081260', 'html_url': 'https://github.com/huggingface/datasets/issues/5947#issuecomment-1591081260', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5947', 'id': 1591081260, 'node_id': 'IC_kwDODunzps5e1fks', 'user': {'login': 'lhoestq', 'id': 42851186, 'node_id': 'MDQ6VXNlcjQyODUxMTg2', 'avatar_url': 'https://avatars.githubusercontent.com/u/42851186?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/lhoestq', 'html_url': 'https://github.com/lhoestq', 'followers_url': 'https://api.github.com/users/lhoestq/followers', 'following_url': 'https://api.github.com/users/lhoestq/following{/other_user}', 'gists_url': 'https://api.github.com/users/lhoestq/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/lhoestq/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/lhoestq/subscriptions', 'organizations_url': 'https://api.github.com/users/lhoestq/orgs', 'repos_url': 'https://api.github.com/users/lhoestq/repos', 'events_url': 'https://api.github.com/users/lhoestq/events{/privacy}', 'received_events_url': 'https://api.github.com/users/lhoestq/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-14T12:17:36Z', 'updated_at': '2023-06-14T12:17:36Z', 'author_association': 'MEMBER', 'body': 'Hi ! The audio data don\'t always exist as files on disk - the blobs are often stored in the Arrow files. For now I\'d suggest disabling decoding with `.cast_column("audio", Audio(decode=False))` and apply your own decoding that handles corrupted files (maybe to filter them out ?)\r\n\r\ncc @sanchit-gandhi since it\'s related to our discussion about allowing users to make decoding return `None` and show a warning when there are corrupted files', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1591081260/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1591121455', 'html_url': 'https://github.com/huggingface/datasets/issues/5947#issuecomment-1591121455', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5947', 'id': 1591121455, 'node_id': 'IC_kwDODunzps5e1pYv', 'user': {'login': 'wetdog', 'id': 8949105, 'node_id': 'MDQ6VXNlcjg5NDkxMDU=', 'avatar_url': 'https://avatars.githubusercontent.com/u/8949105?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/wetdog', 'html_url': 'https://github.com/wetdog', 'followers_url': 'https://api.github.com/users/wetdog/followers', 'following_url': 'https://api.github.com/users/wetdog/following{/other_user}', 'gists_url': 'https://api.github.com/users/wetdog/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/wetdog/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/wetdog/subscriptions', 'organizations_url': 'https://api.github.com/users/wetdog/orgs', 'repos_url': 'https://api.github.com/users/wetdog/repos', 'events_url': 'https://api.github.com/users/wetdog/events{/privacy}', 'received_events_url': 'https://api.github.com/users/wetdog/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-14T12:44:02Z', 'updated_at': '2023-06-14T12:45:01Z', 'author_association': 'NONE', 'body': 'Thanks @lhoestq, I wasn\'t aware of the decode flag. It makes more sense as you say to show a warning when there are corrupted files together with some metadata of the file that allows to filter them from the dataset.\r\n\r\nMy workaround was to catch the LibsndfileError and generate a dummy audio with an unsual sample rate to filter it later. However returning `None` seems better. \r\n\r\n`try:\r\n    array, sampling_rate = sf.read(file)\r\nexcept sf.LibsndfileError:\r\n    print("bad file")\r\n    array = np.array([0.0])\r\n    sampling_rate = 99.000` \r\n\r\n', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1591121455/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}]
[{'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1589080032', 'html_url': 'https://github.com/huggingface/datasets/issues/5946#issuecomment-1589080032', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5946', 'id': 1589080032, 'node_id': 'IC_kwDODunzps5et2_g', 'user': {'login': 'syngokhan', 'id': 70565543, 'node_id': 'MDQ6VXNlcjcwNTY1NTQz', 'avatar_url': 'https://avatars.githubusercontent.com/u/70565543?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/syngokhan', 'html_url': 'https://github.com/syngokhan', 'followers_url': 'https://api.github.com/users/syngokhan/followers', 'following_url': 'https://api.github.com/users/syngokhan/following{/other_user}', 'gists_url': 'https://api.github.com/users/syngokhan/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/syngokhan/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/syngokhan/subscriptions', 'organizations_url': 'https://api.github.com/users/syngokhan/orgs', 'repos_url': 'https://api.github.com/users/syngokhan/repos', 'events_url': 'https://api.github.com/users/syngokhan/events{/privacy}', 'received_events_url': 'https://api.github.com/users/syngokhan/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-13T11:06:43Z', 'updated_at': '2023-06-13T11:06:43Z', 'author_association': 'NONE', 'body': 'https://colab.research.google.com/#scrollTo=AQ_HCYruWIHU&fileId=https%3A//huggingface.co/dfurman/falcon-40b-chat-oasst1/blob/main/finetune_falcon40b_oasst1_with_bnb_peft.ipynb\r\n\r\nI ran the same administration exactly the same but got the same error', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1589080032/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1591085621', 'html_url': 'https://github.com/huggingface/datasets/issues/5946#issuecomment-1591085621', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5946', 'id': 1591085621, 'node_id': 'IC_kwDODunzps5e1go1', 'user': {'login': 'lhoestq', 'id': 42851186, 'node_id': 'MDQ6VXNlcjQyODUxMTg2', 'avatar_url': 'https://avatars.githubusercontent.com/u/42851186?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/lhoestq', 'html_url': 'https://github.com/lhoestq', 'followers_url': 'https://api.github.com/users/lhoestq/followers', 'following_url': 'https://api.github.com/users/lhoestq/following{/other_user}', 'gists_url': 'https://api.github.com/users/lhoestq/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/lhoestq/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/lhoestq/subscriptions', 'organizations_url': 'https://api.github.com/users/lhoestq/orgs', 'repos_url': 'https://api.github.com/users/lhoestq/repos', 'events_url': 'https://api.github.com/users/lhoestq/events{/privacy}', 'received_events_url': 'https://api.github.com/users/lhoestq/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-14T12:20:12Z', 'updated_at': '2023-06-14T12:20:12Z', 'author_association': 'MEMBER', 'body': 'Looks related to https://discuss.huggingface.co/t/indexerror-invalid-key-16-is-out-of-bounds-for-size-0/14298/4?u=lhoestq', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1591085621/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1595661238', 'html_url': 'https://github.com/huggingface/datasets/issues/5946#issuecomment-1595661238', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5946', 'id': 1595661238, 'node_id': 'IC_kwDODunzps5fG9u2', 'user': {'login': 'syngokhan', 'id': 70565543, 'node_id': 'MDQ6VXNlcjcwNTY1NTQz', 'avatar_url': 'https://avatars.githubusercontent.com/u/70565543?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/syngokhan', 'html_url': 'https://github.com/syngokhan', 'followers_url': 'https://api.github.com/users/syngokhan/followers', 'following_url': 'https://api.github.com/users/syngokhan/following{/other_user}', 'gists_url': 'https://api.github.com/users/syngokhan/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/syngokhan/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/syngokhan/subscriptions', 'organizations_url': 'https://api.github.com/users/syngokhan/orgs', 'repos_url': 'https://api.github.com/users/syngokhan/repos', 'events_url': 'https://api.github.com/users/syngokhan/events{/privacy}', 'received_events_url': 'https://api.github.com/users/syngokhan/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-17T07:51:58Z', 'updated_at': '2023-06-17T07:52:31Z', 'author_association': 'NONE', 'body': '> Looks related to https://discuss.huggingface.co/t/indexerror-invalid-key-16-is-out-of-bounds-for-size-0/14298/4?u=lhoestq\n\nThe problem has not been solved, I have tried this before, but the problem is the same', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1595661238/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1634503846', 'html_url': 'https://github.com/huggingface/datasets/issues/5946#issuecomment-1634503846', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5946', 'id': 1634503846, 'node_id': 'IC_kwDODunzps5hbIym', 'user': {'login': 'serino28', 'id': 61455975, 'node_id': 'MDQ6VXNlcjYxNDU1OTc1', 'avatar_url': 'https://avatars.githubusercontent.com/u/61455975?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/serino28', 'html_url': 'https://github.com/serino28', 'followers_url': 'https://api.github.com/users/serino28/followers', 'following_url': 'https://api.github.com/users/serino28/following{/other_user}', 'gists_url': 'https://api.github.com/users/serino28/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/serino28/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/serino28/subscriptions', 'organizations_url': 'https://api.github.com/users/serino28/orgs', 'repos_url': 'https://api.github.com/users/serino28/repos', 'events_url': 'https://api.github.com/users/serino28/events{/privacy}', 'received_events_url': 'https://api.github.com/users/serino28/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-07-13T15:59:42Z', 'updated_at': '2023-07-13T15:59:42Z', 'author_association': 'NONE', 'body': '> \r\n\r\n@syngokhan did u solve it? \r\nI am desperate ', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1634503846/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}]

[{'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1591082689', 'html_url': 'https://github.com/huggingface/datasets/issues/5945#issuecomment-1591082689', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5945', 'id': 1591082689, 'node_id': 'IC_kwDODunzps5e1f7B', 'user': {'login': 'lhoestq', 'id': 42851186, 'node_id': 'MDQ6VXNlcjQyODUxMTg2', 'avatar_url': 'https://avatars.githubusercontent.com/u/42851186?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/lhoestq', 'html_url': 'https://github.com/lhoestq', 'followers_url': 'https://api.github.com/users/lhoestq/followers', 'following_url': 'https://api.github.com/users/lhoestq/following{/other_user}', 'gists_url': 'https://api.github.com/users/lhoestq/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/lhoestq/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/lhoestq/subscriptions', 'organizations_url': 'https://api.github.com/users/lhoestq/orgs', 'repos_url': 'https://api.github.com/users/lhoestq/repos', 'events_url': 'https://api.github.com/users/lhoestq/events{/privacy}', 'received_events_url': 'https://api.github.com/users/lhoestq/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-14T12:18:30Z', 'updated_at': '2023-06-14T12:18:30Z', 'author_association': 'MEMBER', 'body': 'Hi ! Feel free to re-run your code later, it will resume automatically where you left', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1591082689/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1596191510', 'html_url': 'https://github.com/huggingface/datasets/issues/5945#issuecomment-1596191510', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5945', 'id': 1596191510, 'node_id': 'IC_kwDODunzps5fI_MW', 'user': {'login': 'Ar770', 'id': 77382661, 'node_id': 'MDQ6VXNlcjc3MzgyNjYx', 'avatar_url': 'https://avatars.githubusercontent.com/u/77382661?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/Ar770', 'html_url': 'https://github.com/Ar770', 'followers_url': 'https://api.github.com/users/Ar770/followers', 'following_url': 'https://api.github.com/users/Ar770/following{/other_user}', 'gists_url': 'https://api.github.com/users/Ar770/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/Ar770/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/Ar770/subscriptions', 'organizations_url': 'https://api.github.com/users/Ar770/orgs', 'repos_url': 'https://api.github.com/users/Ar770/repos', 'events_url': 'https://api.github.com/users/Ar770/events{/privacy}', 'received_events_url': 'https://api.github.com/users/Ar770/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-18T16:00:13Z', 'updated_at': '2023-06-18T16:00:13Z', 'author_association': 'NONE', 'body': 'Tried many times in the last 2 weeks, problem remains.', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1596191510/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1596964827', 'html_url': 'https://github.com/huggingface/datasets/issues/5945#issuecomment-1596964827', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5945', 'id': 1596964827, 'node_id': 'IC_kwDODunzps5fL7_b', 'user': {'login': 'lhoestq', 'id': 42851186, 'node_id': 'MDQ6VXNlcjQyODUxMTg2', 'avatar_url': 'https://avatars.githubusercontent.com/u/42851186?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/lhoestq', 'html_url': 'https://github.com/lhoestq', 'followers_url': 'https://api.github.com/users/lhoestq/followers', 'following_url': 'https://api.github.com/users/lhoestq/following{/other_user}', 'gists_url': 'https://api.github.com/users/lhoestq/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/lhoestq/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/lhoestq/subscriptions', 'organizations_url': 'https://api.github.com/users/lhoestq/orgs', 'repos_url': 'https://api.github.com/users/lhoestq/repos', 'events_url': 'https://api.github.com/users/lhoestq/events{/privacy}', 'received_events_url': 'https://api.github.com/users/lhoestq/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-19T10:54:54Z', 'updated_at': '2023-06-19T10:54:54Z', 'author_association': 'MEMBER', 'body': 'Alternatively you can save your dataset in parquet files locally and upload them to the hub manually\r\n\r\n```python\r\nfrom tqdm import tqdm\r\nnum_shards = 60\r\nfor index in tqdm(range(num_shards)):\r\n    ds.shard(num_shards=num_shards, index=index, contiguous=True).to_parquet(f"{index:05d}.parquet")\r\n````', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1596964827/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}]

[]
[{'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1591088082', 'html_url': 'https://github.com/huggingface/datasets/issues/5941#issuecomment-1591088082', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5941', 'id': 1591088082, 'node_id': 'IC_kwDODunzps5e1hPS', 'user': {'login': 'lhoestq', 'id': 42851186, 'node_id': 'MDQ6VXNlcjQyODUxMTg2', 'avatar_url': 'https://avatars.githubusercontent.com/u/42851186?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/lhoestq', 'html_url': 'https://github.com/lhoestq', 'followers_url': 'https://api.github.com/users/lhoestq/followers', 'following_url': 'https://api.github.com/users/lhoestq/following{/other_user}', 'gists_url': 'https://api.github.com/users/lhoestq/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/lhoestq/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/lhoestq/subscriptions', 'organizations_url': 'https://api.github.com/users/lhoestq/orgs', 'repos_url': 'https://api.github.com/users/lhoestq/repos', 'events_url': 'https://api.github.com/users/lhoestq/events{/privacy}', 'received_events_url': 'https://api.github.com/users/lhoestq/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-14T12:22:00Z', 'updated_at': '2023-06-14T12:22:00Z', 'author_association': 'MEMBER', 'body': 'Hi ! you can speed it up using multiprocessing by passing `num_proc=` to `load_dataset()`', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1591088082/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1592173628', 'html_url': 'https://github.com/huggingface/datasets/issues/5941#issuecomment-1592173628', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5941', 'id': 1592173628, 'node_id': 'IC_kwDODunzps5e5qQ8', 'user': {'login': 'xyx361100238', 'id': 19569322, 'node_id': 'MDQ6VXNlcjE5NTY5MzIy', 'avatar_url': 'https://avatars.githubusercontent.com/u/19569322?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/xyx361100238', 'html_url': 'https://github.com/xyx361100238', 'followers_url': 'https://api.github.com/users/xyx361100238/followers', 'following_url': 'https://api.github.com/users/xyx361100238/following{/other_user}', 'gists_url': 'https://api.github.com/users/xyx361100238/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/xyx361100238/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/xyx361100238/subscriptions', 'organizations_url': 'https://api.github.com/users/xyx361100238/orgs', 'repos_url': 'https://api.github.com/users/xyx361100238/repos', 'events_url': 'https://api.github.com/users/xyx361100238/events{/privacy}', 'received_events_url': 'https://api.github.com/users/xyx361100238/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-15T00:53:46Z', 'updated_at': '2023-06-15T00:53:46Z', 'author_association': 'NONE', 'body': 'already did，but not useful for step Generating train split，it works in step "Resolving data files" & "Downloading data files" ', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1592173628/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1592174718', 'html_url': 'https://github.com/huggingface/datasets/issues/5941#issuecomment-1592174718', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5941', 'id': 1592174718, 'node_id': 'IC_kwDODunzps5e5qh-', 'user': {'login': 'xyx361100238', 'id': 19569322, 'node_id': 'MDQ6VXNlcjE5NTY5MzIy', 'avatar_url': 'https://avatars.githubusercontent.com/u/19569322?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/xyx361100238', 'html_url': 'https://github.com/xyx361100238', 'followers_url': 'https://api.github.com/users/xyx361100238/followers', 'following_url': 'https://api.github.com/users/xyx361100238/following{/other_user}', 'gists_url': 'https://api.github.com/users/xyx361100238/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/xyx361100238/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/xyx361100238/subscriptions', 'organizations_url': 'https://api.github.com/users/xyx361100238/orgs', 'repos_url': 'https://api.github.com/users/xyx361100238/repos', 'events_url': 'https://api.github.com/users/xyx361100238/events{/privacy}', 'received_events_url': 'https://api.github.com/users/xyx361100238/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-15T00:55:58Z', 'updated_at': '2023-06-15T00:55:58Z', 'author_association': 'NONE', 'body': '@mariosasko some advice ， thanks！', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1592174718/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1595807119', 'html_url': 'https://github.com/huggingface/datasets/issues/5941#issuecomment-1595807119', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5941', 'id': 1595807119, 'node_id': 'IC_kwDODunzps5fHhWP', 'user': {'login': 'mengban', 'id': 14243491, 'node_id': 'MDQ6VXNlcjE0MjQzNDkx', 'avatar_url': 'https://avatars.githubusercontent.com/u/14243491?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/mengban', 'html_url': 'https://github.com/mengban', 'followers_url': 'https://api.github.com/users/mengban/followers', 'following_url': 'https://api.github.com/users/mengban/following{/other_user}', 'gists_url': 'https://api.github.com/users/mengban/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/mengban/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/mengban/subscriptions', 'organizations_url': 'https://api.github.com/users/mengban/orgs', 'repos_url': 'https://api.github.com/users/mengban/repos', 'events_url': 'https://api.github.com/users/mengban/events{/privacy}', 'received_events_url': 'https://api.github.com/users/mengban/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-17T17:00:58Z', 'updated_at': '2023-06-17T17:00:58Z', 'author_association': 'NONE', 'body': 'I met the same problem,  terrible  experience', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1595807119/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1633407402', 'html_url': 'https://github.com/huggingface/datasets/issues/5941#issuecomment-1633407402', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5941', 'id': 1633407402, 'node_id': 'IC_kwDODunzps5hW9Gq', 'user': {'login': 'xyx361100238', 'id': 19569322, 'node_id': 'MDQ6VXNlcjE5NTY5MzIy', 'avatar_url': 'https://avatars.githubusercontent.com/u/19569322?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/xyx361100238', 'html_url': 'https://github.com/xyx361100238', 'followers_url': 'https://api.github.com/users/xyx361100238/followers', 'following_url': 'https://api.github.com/users/xyx361100238/following{/other_user}', 'gists_url': 'https://api.github.com/users/xyx361100238/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/xyx361100238/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/xyx361100238/subscriptions', 'organizations_url': 'https://api.github.com/users/xyx361100238/orgs', 'repos_url': 'https://api.github.com/users/xyx361100238/repos', 'events_url': 'https://api.github.com/users/xyx361100238/events{/privacy}', 'received_events_url': 'https://api.github.com/users/xyx361100238/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-07-13T01:32:53Z', 'updated_at': '2023-07-13T01:32:53Z', 'author_association': 'NONE', 'body': '@mariosasko ', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1633407402/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1634763738', 'html_url': 'https://github.com/huggingface/datasets/issues/5941#issuecomment-1634763738', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5941', 'id': 1634763738, 'node_id': 'IC_kwDODunzps5hcIPa', 'user': {'login': 'mariosasko', 'id': 47462742, 'node_id': 'MDQ6VXNlcjQ3NDYyNzQy', 'avatar_url': 'https://avatars.githubusercontent.com/u/47462742?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/mariosasko', 'html_url': 'https://github.com/mariosasko', 'followers_url': 'https://api.github.com/users/mariosasko/followers', 'following_url': 'https://api.github.com/users/mariosasko/following{/other_user}', 'gists_url': 'https://api.github.com/users/mariosasko/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/mariosasko/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/mariosasko/subscriptions', 'organizations_url': 'https://api.github.com/users/mariosasko/orgs', 'repos_url': 'https://api.github.com/users/mariosasko/repos', 'events_url': 'https://api.github.com/users/mariosasko/events{/privacy}', 'received_events_url': 'https://api.github.com/users/mariosasko/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-07-13T19:15:10Z', 'updated_at': '2023-07-13T19:15:41Z', 'author_association': 'CONTRIBUTOR', 'body': "We need more info about the issue to provide help. \r\n\r\nCan you interrupt the process (with `num_proc=None`) after the `load_dataset` call when the slowdown occurs? So we can know what part of the code is causing it.\r\n\r\nThe `audiofolder` \\ `imagefolder` with metadata is not performant for large datasets. Luckily, we can make them much faster if drop the nested metadata files feature (not that useful). I plan to work on this soon.\r\n\r\nIn the meantime, it's better to use `Dataset.from_generator` (requires replacing the `load_dataset` calls in the transformers script with `Dataset.from_generator`) or write a dataset loading script for large datasets.", 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1634763738/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}]

[{'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1607120155', 'html_url': 'https://github.com/huggingface/datasets/issues/5990#issuecomment-1607120155', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5990', 'id': 1607120155, 'node_id': 'IC_kwDODunzps5fyrUb', 'user': {'login': 'Wauplin', 'id': 11801849, 'node_id': 'MDQ6VXNlcjExODAxODQ5', 'avatar_url': 'https://avatars.githubusercontent.com/u/11801849?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/Wauplin', 'html_url': 'https://github.com/Wauplin', 'followers_url': 'https://api.github.com/users/Wauplin/followers', 'following_url': 'https://api.github.com/users/Wauplin/following{/other_user}', 'gists_url': 'https://api.github.com/users/Wauplin/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/Wauplin/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/Wauplin/subscriptions', 'organizations_url': 'https://api.github.com/users/Wauplin/orgs', 'repos_url': 'https://api.github.com/users/Wauplin/repos', 'events_url': 'https://api.github.com/users/Wauplin/events{/privacy}', 'received_events_url': 'https://api.github.com/users/Wauplin/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-13T09:50:49Z', 'updated_at': '2023-06-13T09:51:03Z', 'author_association': 'CONTRIBUTOR', 'body': "Hi @AntreasAntoniou , sorry to know you are facing this issue. To help debugging it, could you tell me:\r\n- What is the total dataset size?\r\n- Is it always failing on the same shard or is the hanging problem happening randomly?\r\n- Were you able to save the dataset as parquet locally? This would help us determine if the problem comes from the upload or the file generation.\r\n\r\nI'm cc-ing @lhoestq who might have some insights from a `datasets` perspective.", 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1607120155/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1607120168', 'html_url': 'https://github.com/huggingface/datasets/issues/5990#issuecomment-1607120168', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5990', 'id': 1607120168, 'node_id': 'IC_kwDODunzps5fyrUo', 'user': {'login': 'lhoestq', 'id': 42851186, 'node_id': 'MDQ6VXNlcjQyODUxMTg2', 'avatar_url': 'https://avatars.githubusercontent.com/u/42851186?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/lhoestq', 'html_url': 'https://github.com/lhoestq', 'followers_url': 'https://api.github.com/users/lhoestq/followers', 'following_url': 'https://api.github.com/users/lhoestq/following{/other_user}', 'gists_url': 'https://api.github.com/users/lhoestq/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/lhoestq/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/lhoestq/subscriptions', 'organizations_url': 'https://api.github.com/users/lhoestq/orgs', 'repos_url': 'https://api.github.com/users/lhoestq/repos', 'events_url': 'https://api.github.com/users/lhoestq/events{/privacy}', 'received_events_url': 'https://api.github.com/users/lhoestq/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-13T16:18:12Z', 'updated_at': '2023-06-13T16:18:12Z', 'author_association': 'MEMBER', 'body': 'One trick that can also help is to check the traceback when you kill your python process: it will show where in the code it was hanging', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1607120168/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1607120179', 'html_url': 'https://github.com/huggingface/datasets/issues/5990#issuecomment-1607120179', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5990', 'id': 1607120179, 'node_id': 'IC_kwDODunzps5fyrUz', 'user': {'login': 'AntreasAntoniou', 'id': 10792502, 'node_id': 'MDQ6VXNlcjEwNzkyNTAy', 'avatar_url': 'https://avatars.githubusercontent.com/u/10792502?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/AntreasAntoniou', 'html_url': 'https://github.com/AntreasAntoniou', 'followers_url': 'https://api.github.com/users/AntreasAntoniou/followers', 'following_url': 'https://api.github.com/users/AntreasAntoniou/following{/other_user}', 'gists_url': 'https://api.github.com/users/AntreasAntoniou/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/AntreasAntoniou/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/AntreasAntoniou/subscriptions', 'organizations_url': 'https://api.github.com/users/AntreasAntoniou/orgs', 'repos_url': 'https://api.github.com/users/AntreasAntoniou/repos', 'events_url': 'https://api.github.com/users/AntreasAntoniou/events{/privacy}', 'received_events_url': 'https://api.github.com/users/AntreasAntoniou/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-16T17:10:16Z', 'updated_at': '2023-06-16T17:10:16Z', 'author_association': 'NONE', 'body': 'Right. So I did the trick @lhoestq suggested. Here is where things seem to hang\r\n\r\n```\r\nError while uploading \'data/train-00120-of-00195-466c2dbab2eb9989.parquet\' to the Hub.                                                                                                     \r\nPushing split train to the Hub.                                                                                                                                                            \r\nCreating parquet from Arrow format: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:03<00:00,  1.15s/ba]\r\nUpload 1 LFS files: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:52<00:00, 52.12s/it]\r\nCreating parquet from Arrow format: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:03<00:00,  1.08s/ba]\r\nUpload 1 LFS files: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:45<00:00, 45.54s/it]\r\nCreating parquet from Arrow format: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:03<00:00,  1.08s/ba]\r\nCreating parquet from Arrow format: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:03<00:00,  1.03s/ba^Upload 1 LFS files:   0%|                                                                                                                                         | 0/1 [\r\n21:27:35<?, ?it/s]                                                                                                                                                                         \r\nPushing dataset shards to the dataset hub:  63%|█████████████████████████████████████████████████████████████▎                                    | 122/195 [23:37:11<14:07:59, 696.98s/it]\r\n^CError in sys.excepthook:                                                                                                                                                                 \r\nTraceback (most recent call last):                                                                                                                                                         \r\n  File "/opt/conda/envs/main/lib/python3.10/site-packages/rich/console.py", line 1699, in print                                                                                            \r\n    extend(render(renderable, render_options))                                                                                                                                             \r\n  File "/opt/conda/envs/main/lib/python3.10/site-packages/rich/console.py", line 1335, in render                                                                                           \r\n    yield from self.render(render_output, _options)                                                                                                                                        \r\n  File "/opt/conda/envs/main/lib/python3.10/site-packages/rich/console.py", line 1331, in render                                                                                           \r\n    for render_output in iter_render:                                                                                                                                                      \r\n  File "/opt/conda/envs/main/lib/python3.10/site-packages/rich/constrain.py", line 29, in __rich_console__                                                                                 \r\n    yield from console.render(self.renderable, child_options)                                                                                                                              \r\n  File "/opt/conda/envs/main/lib/python3.10/site-packages/rich/console.py", line 1331, in render                                                                                           \r\n    for render_output in iter_render:                                                                                                                                                      \r\n  File "/opt/conda/envs/main/lib/python3.10/site-packages/rich/panel.py", line 220, in __rich_console__                                                                                    \r\n    lines = console.render_lines(renderable, child_options, style=style)                                                                                                                   \r\n  File "/opt/conda/envs/main/lib/python3.10/site-packages/rich/console.py", line 1371, in render_lines                                                                                     \r\n    lines = list(                                                                                                                                                                          \r\n  File "/opt/conda/envs/main/lib/python3.10/site-packages/rich/segment.py", line 292, in split_and_crop_lines                                                                              \r\n    for segment in segments:                                                                                                                                                               \r\n  File "/opt/conda/envs/main/lib/python3.10/site-packages/rich/console.py", line 1331, in render                                                                                           \r\n    for render_output in iter_render:                                                                                                                                                      \r\n  File "/opt/conda/envs/main/lib/python3.10/site-packages/rich/padding.py", line 97, in __rich_console__                                                                                   \r\n    lines = console.render_lines(                                                                                                                                                          \r\n  File "/opt/conda/envs/main/lib/python3.10/site-packages/rich/console.py", line 1371, in render_lines                                                                                     \r\n    lines = list(                                                                                                                                                                          \r\n  File "/opt/conda/envs/main/lib/python3.10/site-packages/rich/segment.py", line 292, in split_and_crop_lines                                                                              \r\n    for segment in segments:                                                                                                                                                               \r\n  File "/opt/conda/envs/main/lib/python3.10/site-packages/rich/console.py", line 1335, in render                                                                                           \r\n    yield from self.render(render_output, _options)                                                                                                                                        \r\n  File "/opt/conda/envs/main/lib/python3.10/site-packages/rich/console.py", line 1331, in render                                                                                           \r\n    for render_output in iter_render:                                                                                                                                                      \r\n  File "/opt/conda/envs/main/lib/python3.10/site-packages/rich/syntax.py", line 611, in __rich_console__                                                                                   \r\n    segments = Segments(self._get_syntax(console, options))                                                                                                                                \r\n  File "/opt/conda/envs/main/lib/python3.10/site-packages/rich/segment.py", line 668, in __init__                                                                                          \r\n    self.segments = list(segments)                                                                                                                                                         \r\n  File "/opt/conda/envs/main/lib/python3.10/site-packages/rich/syntax.py", line 674, in _get_syntax                                                                                        \r\n    lines: Union[List[Text], Lines] = text.split("\\n", allow_blank=ends_on_nl)                                                                                                             \r\n  File "/opt/conda/envs/main/lib/python3.10/site-packages/rich/text.py", line 1042, in split                                                                                               \r\n    lines = Lines(                                                                                                                                                                         \r\n  File "/opt/conda/envs/main/lib/python3.10/site-packages/rich/containers.py", line 70, in __init__                                                                                        \r\n    self._lines: List["Text"] = list(lines)                                                                                                                                                \r\n  File "/opt/conda/envs/main/lib/python3.10/site-packages/rich/text.py", line 1043, in <genexpr>                                                                                           \r\n    line for line in self.divide(flatten_spans()) if line.plain != separator                                                                                                               \r\n  File "/opt/conda/envs/main/lib/python3.10/site-packages/rich/text.py", line 385, in plain                                                    \r\n    if len(self._text) != 1:                                                                                                                                                               \r\nKeyboardInterrupt                                                                                                                                                                                                                                                                              \r\n                                                                                                                                                                                                                                            \r\nOriginal exception was:                                                                                                                                                                                                                                                                        \r\nTraceback (most recent call last):                                                                                                                                                                                                          \r\n  File "/opt/conda/envs/main/lib/python3.10/site-packages/tqdm/contrib/concurrent.py", line 51, in _executor_map                                                                                                                                                                               \r\n    return list(tqdm_class(ex.map(fn, *iterables, chunksize=chunksize), **kwargs))                                                                                                                                                          \r\n  File "/opt/conda/envs/main/lib/python3.10/site-packages/tqdm/std.py", line 1178, in __iter__                                                                                                                                                                                                 \r\n    for obj in iterable:                                                                                                                                                                   \r\n  File "/opt/conda/envs/main/lib/python3.10/concurrent/futures/_base.py", line 621, in result_iterator                                                                                                                                                                                         \r\n    yield _result_or_cancel(fs.pop())                                                                                                                                                      \r\n  File "/opt/conda/envs/main/lib/python3.10/concurrent/futures/_base.py", line 319, in _result_or_cancel                                                                                                                                                                                       \r\n    return fut.result(timeout)                                                                                                                                                             \r\n  File "/opt/conda/envs/main/lib/python3.10/concurrent/futures/_base.py", line 453, in result                                                                                                                                                                                                  \r\n    self._condition.wait(timeout)                                                                                                                                                                                                           \r\n  File "/opt/conda/envs/main/lib/python3.10/threading.py", line 320, in wait                                                                                                                                                                                                                   \r\n    waiter.acquire()                                                                                                                                                                                                                        \r\nKeyboardInterrupt                       

[]
[{'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1591183246', 'html_url': 'https://github.com/huggingface/datasets/pull/5938#issuecomment-1591183246', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5938', 'id': 1591183246, 'node_id': 'IC_kwDODunzps5e14eO', 'user': {'login': 'HuggingFaceDocBuilderDev', 'id': 99929124, 'node_id': 'U_kgDOBfTMJA', 'avatar_url': 'https://avatars.githubusercontent.com/u/99929124?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/HuggingFaceDocBuilderDev', 'html_url': 'https://github.com/HuggingFaceDocBuilderDev', 'followers_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/followers', 'following_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/following{/other_user}', 'gists_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/subscriptions', 'organizations_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/orgs', 'repos_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/repos', 'events_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/events{/privacy}', 'received_events_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-14T13:11:48Z', 'updated_at': '2023-06-14T13:27:51Z', 'author_association': 'NONE', 'body': '_The documentation is not available anymore as the PR was closed or merged._', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1591183246/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1591224238', 'html_url': 'https://github.com/huggingface/datasets/pull/5938#issuecomment-1591224238', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5938', 'id': 1591224238, 'node_id': 'IC_kwDODunzps5e2Ceu', 'user': {'login': 'github-actions[bot]', 'id': 41898282, 'node_id': 'MDM6Qm90NDE4OTgyODI=', 'avatar_url': 'https://avatars.githubusercontent.com/in/15368?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/github-actions%5Bbot%5D', 'html_url': 'https://github.com/apps/github-actions', 'followers_url': 'https://api.github.com/users/github-actions%5Bbot%5D/followers', 'following_url': 'https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}', 'gists_url': 'https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/github-actions%5Bbot%5D/subscriptions', 'organizations_url': 'https://api.github.com/users/github-actions%5Bbot%5D/orgs', 'repos_url': 'https://api.github.com/users/github-actions%5Bbot%5D/repos', 'events_url': 'https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}', 'received_events_url': 'https://api.github.com/users/github-actions%5Bbot%5D/received_events', 'type': 'Bot', 'site_admin': False}, 'created_at': '2023-06-14T13:35:37Z', 'updated_at': '2023-06-14T13:35:37Z', 'author_association': 'NONE', 'body': '<details>\n<summary>Show benchmarks</summary>\n\nPyArrow==8.0.0\n\n<details>\n<summary>Show updated benchmarks!</summary>\n\n### Benchmark: benchmark_array_xd.json\n\n| metric | read_batch_formatted_as_numpy after write_array2d | read_batch_formatted_as_numpy after write_flattened_sequence | read_batch_formatted_as_numpy after write_nested_sequence | read_batch_unformated after write_array2d | read_batch_unformated after write_flattened_sequence | read_batch_unformated after write_nested_sequence | read_col_formatted_as_numpy after write_array2d | read_col_formatted_as_numpy after write_flattened_sequence | read_col_formatted_as_numpy after write_nested_sequence | read_col_unformated after write_array2d | read_col_unformated after write_flattened_sequence | read_col_unformated after write_nested_sequence | read_formatted_as_numpy after write_array2d | read_formatted_as_numpy after write_flattened_sequence | read_formatted_as_numpy after write_nested_sequence | read_unformated after write_array2d | read_unformated after write_flattened_sequence | read_unformated after write_nested_sequence | write_array2d | write_flattened_sequence | write_nested_sequence |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.007241 / 0.011353 (-0.004112) | 0.004574 / 0.011008 (-0.006434) | 0.120481 / 0.038508 (0.081973) | 0.040492 / 0.023109 (0.017383) | 0.391399 / 0.275898 (0.115501) | 0.422844 / 0.323480 (0.099365) | 0.004441 / 0.007986 (-0.003545) | 0.004544 / 0.004328 (0.000216) | 0.089482 / 0.004250 (0.085231) | 0.052939 / 0.037052 (0.015887) | 0.393649 / 0.258489 (0.135160) | 0.433852 / 0.293841 (0.140011) | 0.035882 / 0.128546 (-0.092664) | 0.010172 / 0.075646 (-0.065474) | 0.410331 / 0.419271 (-0.008940) | 0.061481 / 0.043533 (0.017948) | 0.405066 / 0.255139 (0.149927) | 0.417732 / 0.283200 (0.134532) | 0.121647 / 0.141683 (-0.020035) | 1.790624 / 1.452155 (0.338469) | 1.863398 / 1.492716 (0.370681) |\n\n### Benchmark: benchmark_getitem\\_100B.json\n\n| metric | get_batch_of\\_1024\\_random_rows | get_batch_of\\_1024\\_rows | get_first_row | get_last_row |\n|--------|---|---|---|---|\n| new / old (diff) | 0.250650 / 0.018006 (0.232644) | 0.489044 / 0.000490 (0.488554) | 0.010421 / 0.000200 (0.010222) | 0.000106 / 0.000054 (0.000051) |\n\n### Benchmark: benchmark_indices_mapping.json\n\n| metric | select | shard | shuffle | sort | train_test_split |\n|--------|---|---|---|---|---|\n| new / old (diff) | 0.030340 / 0.037411 (-0.007071) | 0.128318 / 0.014526 (0.113792) | 0.140463 / 0.176557 (-0.036093) | 0.205762 / 0.737135 (-0.531373) | 0.147996 / 0.296338 (-0.148342) |\n\n### Benchmark: benchmark_iterating.json\n\n| metric | read 5000 | read 50000 | read_batch 50000 10 | read_batch 50000 100 | read_batch 50000 1000 | read_formatted numpy 5000 | read_formatted pandas 5000 | read_formatted tensorflow 5000 | read_formatted torch 5000 | read_formatted_batch numpy 5000 10 | read_formatted_batch numpy 5000 1000 | shuffled read 5000 | shuffled read 50000 | shuffled read_batch 50000 10 | shuffled read_batch 50000 100 | shuffled read_batch 50000 1000 | shuffled read_formatted numpy 5000 | shuffled read_formatted_batch numpy 5000 10 | shuffled read_formatted_batch numpy 5000 1000 |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.493158 / 0.215209 (0.277949) | 4.858346 / 2.077655 (2.780691) | 2.242942 / 1.504120 (0.738822) | 2.010092 / 1.541195 (0.468897) | 2.076765 / 1.468490 (0.608275) | 0.636669 / 4.584777 (-3.948108) | 4.478027 / 3.745712 (0.732314) | 2.157843 / 5.269862 (-3.112019) | 1.305133 / 4.565676 (-3.260543) | 0.079220 / 0.424275 (-0.345055) | 0.013858 / 0.007607 (0.006251) | 0.604501 / 0.226044 (0.378457) | 5.950071 / 2.268929 (3.681143) | 2.738373 / 55.444624 (-52.706251) | 2.380275 / 6.876477 (-4.496201) | 2.517108 / 2.142072 (0.375035) | 0.772249 / 4.805227 (-4.032979) | 0.169874 / 6.500664 (-6.330790) | 0.078026 / 0.075469 (0.002557) |\n\n### Benchmark: benchmark_map_filter.json\n\n| metric | filter | map fast-tokenizer batched | map identity | map identity batched | map no-op batched | map no-op batched numpy | map no-op batched pandas | map no-op batched pytorch | map no-op batched tensorflow |\n|--------|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 1.450200 / 1.841788 (-0.391588) | 17.810965 / 8.074308 (9.736657) | 15.518998 / 10.191392 (5.327606) | 0.200469 / 0.680424 (-0.479954) | 0.020777 / 0.534201 (-0.513424) | 0.504556 / 0.579283 (-0.074727) | 0.518493 / 0.434364 (0.084129) | 0.615335 / 0.540337 (0.074998) | 0.754065 / 1.386936 (-0.632871) |\n\n</details>\nPyArrow==latest\n\n<details>\n<summary>Show updated benchmarks!</summary>\n\n### Benchmark: benchmark_array_xd.json\n\n| metric | read_batch_formatted_as_numpy after write_array2d | read_batch_formatted_as_numpy after write_flattened_sequence | read_batch_formatted_as_numpy after write_nested_sequence | read_batch_unformated after write_array2d | read_batch_unformated after write_flattened_sequence | read_batch_unformated after write_nested_sequence | read_col_formatted_as_numpy after write_array2d | read_col_formatted_as_numpy after write_flattened_sequence | read_col_formatted_as_numpy after write_nested_sequence | read_col_unformated after write_array2d | read_col_unformated after write_flattened_sequence | read_col_unformated after write_nested_sequence | read_formatted_as_numpy after write_array2d | read_formatted_as_numpy after write_flattened_sequence | read_formatted_as_numpy after write_nested_sequence | read_unformated after write_array2d | read_unformated after write_flattened_sequence | read_unformated after write_nested_sequence | write_array2d | write_flattened_sequence | write_nested_sequence |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.007224 / 0.011353 (-0.004129) | 0.004663 / 0.011008 (-0.006345) | 0.092151 / 0.038508 (0.053643) | 0.038359 / 0.023109 (0.015250) | 0.486413 / 0.275898 (0.210515) | 0.521596 / 0.323480 (0.198116) | 0.004207 / 0.007986 (-0.003778) | 0.003745 / 0.004328 (-0.000583) | 0.089840 / 0.004250 (0.085589) | 0.050996 / 0.037052 (0.013943) | 0.498090 / 0.258489 (0.239601) | 0.533647 / 0.293841 (0.239806) | 0.035151 / 0.128546 (-0.093395) | 0.010293 / 0.075646 (-0.065354) | 0.099056 / 0.419271 (-0.320215) | 0.057365 / 0.043533 (0.013833) | 0.470652 / 0.255139 (0.215513) | 0.509801 / 0.283200 (0.226602) | 0.115650 / 0.141683 (-0.026033) | 1.810860 / 1.452155 (0.358705) | 1.896775 / 1.492716 (0.404059) |\n\n### Benchmark: benchmark_getitem\\_100B.json\n\n| metric | get_batch_of\\_1024\\_random_rows | get_batch_of\\_1024\\_rows | get_first_row | get_last_row |\n|--------|---|---|---|---|\n| new / old (diff) | 0.261887 / 0.018006 (0.243880) | 0.489919 / 0.000490 (0.489430) | 0.006117 / 0.000200 (0.005917) | 0.000134 / 0.000054 (0.000079) |\n\n### Benchmark: benchmark_indices_mapping.json\n\n| metric | select | shard | shuffle | sort | train_test_split |\n|--------|---|---|---|---|---|\n| new / old (diff) | 0.035033 / 0.037411 (-0.002378) | 0.141093 / 0.014526 (0.126567) | 0.152613 / 0.176557 (-0.023943) | 0.218351 / 0.737135 (-0.518785) | 0.158366 / 0.296338 (-0.137972) |\n\n### Benchmark: benchmark_iterating.json\n\n| metric | read 5000 | read 50000 | read_batch 50000 10 | read_batch 50000 100 | read_batch 50000 1000 | read_formatted numpy 5000 | read_formatted pandas 5000 | read_formatted tensorflow 5000 | read_formatted torch 5000 | read_formatted_batch numpy 5000 10 | read_formatted_batch numpy 5000 1000 | shuffled read 5000 | shuffled read 50000 | shuffled read_batch 50000 10 | shuffled read_batch 50000 100 | shuffled read_batch 50000 1000 | shuffled read_formatted numpy 5000 | shuffled read_formatted_batch numpy 5000 10 | shuffled read_formatted_batch numpy 5000 1000 |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.542219 / 0.215209 (0.327010) | 5.479358 / 2.077655 (3.401703) | 2.749586 / 1.504120 (1.245466) | 2.537686 / 1.541195 (0.996491) | 2.582351 / 1.468490 (1.113861) | 0.636750 / 4.584777 (-3.948027) | 4.537501 / 3.745712 (0.791789) | 2.141392 / 5.269862 (-3.128469) | 1.279711 / 4.565676 (-3.285965) | 0.079227 / 0.424275 (-0.345048) | 0.014141 / 0.007607 (0.006534) | 0.662070 / 0.226044 (0.436025) | 6.572144 / 2.268929 (4.303215) | 3.321349 / 55.444624 (-52.123275) | 2.928219 / 6.876477 (-3.948258) | 3.002732 / 2.142072 (0.860659) | 0.773808 / 4.805227 (-4.031419) | 0.166017 / 6.500664 (-6.334647) | 0.076424 / 0.075469 (0.000955) |\n\n### Benchmark: benchmark_map_filter.json\n\n| metric | filter | map fast-tokenizer batched | map identity | map identity batched | map no-op batched | map no-op batched numpy | map no-op batched pandas | map no-op batched pytorch | map no-op batched tensorflow |\n|--------|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 1.584325 / 1.841788 (-0.257463) | 18.359247 / 8.074308 (10.284938) | 16.977875 / 10.191392 (6.786483) | 0.195381 / 0.680424 (-0.485043) | 0.021048 / 0.534201 (-0.513153) | 0.512237 / 0.579283 (-0.067047) | 0.511435 / 0.434364 (0.077071) | 0.592856 / 0.540337 (0.052518) | 0.711905 / 1.386936 (-0.675031) |\n\n</details>\n</details>\n\n![](https://cml.dev/watermark.png#d536e37b21a6dd5c122b6d8113994ec50846c5b5 "CML watermark")\n', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1591224238/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}]

[{'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1584311735', 'html_url': 'https://github.com/huggingface/datasets/pull/5937#issuecomment-1584311735', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5937', 'id': 1584311735, 'node_id': 'IC_kwDODunzps5ebq23', 'user': {'login': 'HuggingFaceDocBuilderDev', 'id': 99929124, 'node_id': 'U_kgDOBfTMJA', 'avatar_url': 'https://avatars.githubusercontent.com/u/99929124?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/HuggingFaceDocBuilderDev', 'html_url': 'https://github.com/HuggingFaceDocBuilderDev', 'followers_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/followers', 'following_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/following{/other_user}', 'gists_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/subscriptions', 'organizations_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/orgs', 'repos_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/repos', 'events_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/events{/privacy}', 'received_events_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-09T10:02:26Z', 'updated_at': '2023-06-14T12:24:26Z', 'author_association': 'NONE', 'body': '_The documentation is not available anymore as the PR was closed or merged._', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1584311735/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1591101762', 'html_url': 'https://github.com/huggingface/datasets/pull/5937#issuecomment-1591101762', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5937', 'id': 1591101762, 'node_id': 'IC_kwDODunzps5e1klC', 'user': {'login': 'github-actions[bot]', 'id': 41898282, 'node_id': 'MDM6Qm90NDE4OTgyODI=', 'avatar_url': 'https://avatars.githubusercontent.com/in/15368?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/github-actions%5Bbot%5D', 'html_url': 'https://github.com/apps/github-actions', 'followers_url': 'https://api.github.com/users/github-actions%5Bbot%5D/followers', 'following_url': 'https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}', 'gists_url': 'https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/github-actions%5Bbot%5D/subscriptions', 'organizations_url': 'https://api.github.com/users/github-actions%5Bbot%5D/orgs', 'repos_url': 'https://api.github.com/users/github-actions%5Bbot%5D/repos', 'events_url': 'https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}', 'received_events_url': 'https://api.github.com/users/github-actions%5Bbot%5D/received_events', 'type': 'Bot', 'site_admin': False}, 'created_at': '2023-06-14T12:30:58Z', 'updated_at': '2023-06-14T12:30:58Z', 'author_association': 'NONE', 'body': '<details>\n<summary>Show benchmarks</summary>\n\nPyArrow==8.0.0\n\n<details>\n<summary>Show updated benchmarks!</summary>\n\n### Benchmark: benchmark_array_xd.json\n\n| metric | read_batch_formatted_as_numpy after write_array2d | read_batch_formatted_as_numpy after write_flattened_sequence | read_batch_formatted_as_numpy after write_nested_sequence | read_batch_unformated after write_array2d | read_batch_unformated after write_flattened_sequence | read_batch_unformated after write_nested_sequence | read_col_formatted_as_numpy after write_array2d | read_col_formatted_as_numpy after write_flattened_sequence | read_col_formatted_as_numpy after write_nested_sequence | read_col_unformated after write_array2d | read_col_unformated after write_flattened_sequence | read_col_unformated after write_nested_sequence | read_formatted_as_numpy after write_array2d | read_formatted_as_numpy after write_flattened_sequence | read_formatted_as_numpy after write_nested_sequence | read_unformated after write_array2d | read_unformated after write_flattened_sequence | read_unformated after write_nested_sequence | write_array2d | write_flattened_sequence | write_nested_sequence |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.006157 / 0.011353 (-0.005196) | 0.003790 / 0.011008 (-0.007219) | 0.097889 / 0.038508 (0.059381) | 0.029038 / 0.023109 (0.005929) | 0.306918 / 0.275898 (0.031020) | 0.339637 / 0.323480 (0.016157) | 0.003526 / 0.007986 (-0.004460) | 0.003102 / 0.004328 (-0.001227) | 0.076908 / 0.004250 (0.072658) | 0.039254 / 0.037052 (0.002201) | 0.309197 / 0.258489 (0.050708) | 0.345635 / 0.293841 (0.051794) | 0.027954 / 0.128546 (-0.100593) | 0.008510 / 0.075646 (-0.067136) | 0.314674 / 0.419271 (-0.104598) | 0.057102 / 0.043533 (0.013569) | 0.307495 / 0.255139 (0.052356) | 0.329501 / 0.283200 (0.046302) | 0.098450 / 0.141683 (-0.043233) | 1.480102 / 1.452155 (0.027948) | 1.550554 / 1.492716 (0.057838) |\n\n### Benchmark: benchmark_getitem\\_100B.json\n\n| metric | get_batch_of\\_1024\\_random_rows | get_batch_of\\_1024\\_rows | get_first_row | get_last_row |\n|--------|---|---|---|---|\n| new / old (diff) | 0.207440 / 0.018006 (0.189434) | 0.426560 / 0.000490 (0.426071) | 0.003250 / 0.000200 (0.003050) | 0.000074 / 0.000054 (0.000019) |\n\n### Benchmark: benchmark_indices_mapping.json\n\n| metric | select | shard | shuffle | sort | train_test_split |\n|--------|---|---|---|---|---|\n| new / old (diff) | 0.023777 / 0.037411 (-0.013634) | 0.103905 / 0.014526 (0.089379) | 0.108324 / 0.176557 (-0.068233) | 0.167223 / 0.737135 (-0.569913) | 0.113529 / 0.296338 (-0.182810) |\n\n### Benchmark: benchmark_iterating.json\n\n| metric | read 5000 | read 50000 | read_batch 50000 10 | read_batch 50000 100 | read_batch 50000 1000 | read_formatted numpy 5000 | read_formatted pandas 5000 | read_formatted tensorflow 5000 | read_formatted torch 5000 | read_formatted_batch numpy 5000 10 | read_formatted_batch numpy 5000 1000 | shuffled read 5000 | shuffled read 50000 | shuffled read_batch 50000 10 | shuffled read_batch 50000 100 | shuffled read_batch 50000 1000 | shuffled read_formatted numpy 5000 | shuffled read_formatted_batch numpy 5000 10 | shuffled read_formatted_batch numpy 5000 1000 |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.426770 / 0.215209 (0.211561) | 4.251806 / 2.077655 (2.174151) | 2.010426 / 1.504120 (0.506306) | 1.858630 / 1.541195 (0.317435) | 1.941318 / 1.468490 (0.472828) | 0.558056 / 4.584777 (-4.026721) | 3.399107 / 3.745712 (-0.346606) | 1.758386 / 5.269862 (-3.511476) | 1.036305 / 4.565676 (-3.529372) | 0.067094 / 0.424275 (-0.357182) | 0.011167 / 0.007607 (0.003560) | 0.526705 / 0.226044 (0.300661) | 5.250319 / 2.268929 (2.981390) | 2.496723 / 55.444624 (-52.947902) | 2.154013 / 6.876477 (-4.722464) | 2.394724 / 2.142072 (0.252652) | 0.669723 / 4.805227 (-4.135504) | 0.136367 / 6.500664 (-6.364297) | 0.067080 / 0.075469 (-0.008389) |\n\n### Benchmark: benchmark_map_filter.json\n\n| metric | filter | map fast-tokenizer batched | map identity | map identity batched | map no-op batched | map no-op batched numpy | map no-op batched pandas | map no-op batched pytorch | map no-op batched tensorflow |\n|--------|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 1.269700 / 1.841788 (-0.572088) | 14.099775 / 8.074308 (6.025467) | 14.422936 / 10.191392 (4.231544) | 0.132344 / 0.680424 (-0.548080) | 0.016744 / 0.534201 (-0.517457) | 0.378286 / 0.579283 (-0.200997) | 0.392282 / 0.434364 (-0.042082) | 0.437648 / 0.540337 (-0.102689) | 0.528554 / 1.386936 (-0.858382) |\n\n</details>\nPyArrow==latest\n\n<details>\n<summary>Show updated benchmarks!</summary>\n\n### Benchmark: benchmark_array_xd.json\n\n| metric | read_batch_formatted_as_numpy after write_array2d | read_batch_formatted_as_numpy after write_flattened_sequence | read_batch_formatted_as_numpy after write_nested_sequence | read_batch_unformated after write_array2d | read_batch_unformated after write_flattened_sequence | read_batch_unformated after write_nested_sequence | read_col_formatted_as_numpy after write_array2d | read_col_formatted_as_numpy after write_flattened_sequence | read_col_formatted_as_numpy after write_nested_sequence | read_col_unformated after write_array2d | read_col_unformated after write_flattened_sequence | read_col_unformated after write_nested_sequence | read_formatted_as_numpy after write_array2d | read_formatted_as_numpy after write_flattened_sequence | read_formatted_as_numpy after write_nested_sequence | read_unformated after write_array2d | read_unformated after write_flattened_sequence | read_unformated after write_nested_sequence | write_array2d | write_flattened_sequence | write_nested_sequence |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.006086 / 0.011353 (-0.005267) | 0.003769 / 0.011008 (-0.007239) | 0.077414 / 0.038508 (0.038906) | 0.027806 / 0.023109 (0.004697) | 0.360333 / 0.275898 (0.084434) | 0.404725 / 0.323480 (0.081245) | 0.003443 / 0.007986 (-0.004543) | 0.004434 / 0.004328 (0.000106) | 0.077309 / 0.004250 (0.073059) | 0.040441 / 0.037052 (0.003388) | 0.358627 / 0.258489 (0.100138) | 0.415246 / 0.293841 (0.121405) | 0.027718 / 0.128546 (-0.100829) | 0.008495 / 0.075646 (-0.067151) | 0.082874 / 0.419271 (-0.336397) | 0.042323 / 0.043533 (-0.001210) | 0.354895 / 0.255139 (0.099756) | 0.390032 / 0.283200 (0.106832) | 0.092377 / 0.141683 (-0.049306) | 1.492817 / 1.452155 (0.040662) | 1.551859 / 1.492716 (0.059143) |\n\n### Benchmark: benchmark_getitem\\_100B.json\n\n| metric | get_batch_of\\_1024\\_random_rows | get_batch_of\\_1024\\_rows | get_first_row | get_last_row |\n|--------|---|---|---|---|\n| new / old (diff) | 0.198921 / 0.018006 (0.180915) | 0.417699 / 0.000490 (0.417209) | 0.001349 / 0.000200 (0.001149) | 0.000071 / 0.000054 (0.000016) |\n\n### Benchmark: benchmark_indices_mapping.json\n\n| metric | select | shard | shuffle | sort | train_test_split |\n|--------|---|---|---|---|---|\n| new / old (diff) | 0.026349 / 0.037411 (-0.011062) | 0.105712 / 0.014526 (0.091186) | 0.111792 / 0.176557 (-0.064765) | 0.163677 / 0.737135 (-0.573459) | 0.116864 / 0.296338 (-0.179474) |\n\n### Benchmark: benchmark_iterating.json\n\n| metric | read 5000 | read 50000 | read_batch 50000 10 | read_batch 50000 100 | read_batch 50000 1000 | read_formatted numpy 5000 | read_formatted pandas 5000 | read_formatted tensorflow 5000 | read_formatted torch 5000 | read_formatted_batch numpy 5000 10 | read_formatted_batch numpy 5000 1000 | shuffled read 5000 | shuffled read 50000 | shuffled read_batch 50000 10 | shuffled read_batch 50000 100 | shuffled read_batch 50000 1000 | shuffled read_formatted numpy 5000 | shuffled read_formatted_batch numpy 5000 10 | shuffled read_formatted_batch numpy 5000 1000 |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.447532 / 0.215209 (0.232323) | 4.468770 / 2.077655 (2.391116) | 2.403820 / 1.504120 (0.899700) | 2.273640 / 1.541195 (0.732445) | 2.337505 / 1.468490 (0.869015) | 0.560729 / 4.584777 (-4.024048) | 3.389165 / 3.745712 (-0.356547) | 2.697614 / 5.269862 (-2.572247) | 1.351909 / 4.565676 (-3.213768) | 0.068089 / 0.424275 (-0.356186) | 0.011639 / 0.007607 (0.004032) | 0.555277 / 0.226044 (0.329233) | 5.559291 / 2.268929 (3.290363) | 2.657609 / 55.444624 (-52.787015) | 2.346667 / 6.876477 (-4.529809) | 2.615823 / 2.142072 (0.473751) | 0.668662 / 4.805227 (-4.136566) | 0.136593 / 6.500664 (-6.364071) | 0.068384 / 0.075469 (-0.007085) |\n\n### Benchmark: benchmark_map_filter.json\n\n| metric | filter | map fast-tokenizer batched | map identity | map identity batched | map no-op batched | map no-op batched numpy | map no-op batched pandas | map no-op batched pytorch | map no-op batched tensorflow |\n|--------|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 1.312089 / 1.841788 (-0.529699) | 14.477510 / 8.074308 (6.403202) | 14.231432 / 10.191392 (4.040040) | 0.132015 / 0.680424 (-0.548409) | 0.016908 / 0.534201 (-0.517293) | 0.368315 / 0.579283 (-0.210968) | 0.397964 / 0.434364 (-0.036400) | 0.432446 / 0.540337 (-0.107891) | 0.526349 / 1.386936 (-0.860587) |\n\n</details>\n</details>\n\n![](https://cml.dev/watermark.png#78b4d55c3cfc60e309eb033d3ed0aba5e796b6ce "CML watermark")\n', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1591101762/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}]

[{'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1584156198', 'html_url': 'https://github.com/huggingface/datasets/issues/5936#issuecomment-1584156198', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5936', 'id': 1584156198, 'node_id': 'IC_kwDODunzps5ebE4m', 'user': {'login': 'qgallouedec', 'id': 45557362, 'node_id': 'MDQ6VXNlcjQ1NTU3MzYy', 'avatar_url': 'https://avatars.githubusercontent.com/u/45557362?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/qgallouedec', 'html_url': 'https://github.com/qgallouedec', 'followers_url': 'https://api.github.com/users/qgallouedec/followers', 'following_url': 'https://api.github.com/users/qgallouedec/following{/other_user}', 'gists_url': 'https://api.github.com/users/qgallouedec/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/qgallouedec/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/qgallouedec/subscriptions', 'organizations_url': 'https://api.github.com/users/qgallouedec/orgs', 'repos_url': 'https://api.github.com/users/qgallouedec/repos', 'events_url': 'https://api.github.com/users/qgallouedec/events{/privacy}', 'received_events_url': 'https://api.github.com/users/qgallouedec/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-09T08:09:50Z', 'updated_at': '2023-06-09T08:10:03Z', 'author_association': 'CONTRIBUTOR', 'body': 'Related, `float16` is the only dtype not supported by `Array2D` (probably by every `ArrayND`):\r\n\r\n```python\r\nfrom datasets import Array2D, Features, Dataset\r\n\r\nimport numpy as np\r\n\r\nfor dtype in [\r\n    "bool",  # ok\r\n    "int8",  # ok\r\n    "int16",  # ok\r\n    "int32",  # ok\r\n    "int64",  # ok\r\n    "uint8",  # ok\r\n    "uint16",  # ok\r\n    "uint32",  # ok\r\n    "uint64",  # ok\r\n    "float16",  # failed\r\n    "float32",  # ok\r\n    "float64",  # ok\r\n]:\r\n    features = Features({"foo": Array2D(dtype=dtype, shape=(3, 4))})\r\n    array = np.zeros((3, 4), dtype=dtype)\r\n    try:\r\n        dataset = Dataset.from_dict({"foo": [array]}, features=features)\r\n    except Exception as e:\r\n        print(f"Failed for dtype={dtype}")\r\n```', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1584156198/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1584301900', 'html_url': 'https://github.com/huggingface/datasets/issues/5936#issuecomment-1584301900', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5936', 'id': 1584301900, 'node_id': 'IC_kwDODunzps5ebodM', 'user': {'login': 'qgallouedec', 'id': 45557362, 'node_id': 'MDQ6VXNlcjQ1NTU3MzYy', 'avatar_url': 'https://avatars.githubusercontent.com/u/45557362?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/qgallouedec', 'html_url': 'https://github.com/qgallouedec', 'followers_url': 'https://api.github.com/users/qgallouedec/followers', 'following_url': 'https://api.github.com/users/qgallouedec/following{/other_user}', 'gists_url': 'https://api.github.com/users/qgallouedec/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/qgallouedec/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/qgallouedec/subscriptions', 'organizations_url': 'https://api.github.com/users/qgallouedec/orgs', 'repos_url': 'https://api.github.com/users/qgallouedec/repos', 'events_url': 'https://api.github.com/users/qgallouedec/events{/privacy}', 'received_events_url': 'https://api.github.com/users/qgallouedec/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-09T09:55:41Z', 'updated_at': '2023-06-09T11:05:02Z', 'author_association': 'CONTRIBUTOR', 'body': "Here's something I can't explain:\r\n\r\nWhen an array is encoded in the `from_dict` method, the numpy array is converted to a list (thus losing the original dtype, which is transfromed to the nearest builtin Python type)\r\n\r\nhttps://github.com/huggingface/datasets/blob/6ee61e6e695b1df9f232d47faf3a5e2b30b33737/src/datasets/features/features.py#L524-L525\r\n\r\nHowever, later on, this same data is written to memory, and it seems authorized that the data is an array (or in this case, a list of arrays). \r\n\r\nhttps://github.com/huggingface/datasets/blob/6ee61e6e695b1df9f232d47faf3a5e2b30b33737/src/datasets/arrow_writer.py#L185-L186\r\n\r\nSo the question is: why convert it to a Python list? This seems to be quite expensive both in terms of write time (all data is copied) and memory (e.g., an int8 is converted to an int64).\r\n\r\nFinally, if I try to remove this step, it solves all the previous problems, and it seems to me that it doesn't break anything (the CI passes without problem).", 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1584301900/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1588898420', 'html_url': 'https://github.com/huggingface/datasets/issues/5936#issuecomment-1588898420', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5936', 'id': 1588898420, 'node_id': 'IC_kwDODunzps5etKp0', 'user': {'login': 'lhoestq', 'id': 42851186, 'node_id': 'MDQ6VXNlcjQyODUxMTg2', 'avatar_url': 'https://avatars.githubusercontent.com/u/42851186?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/lhoestq', 'html_url': 'https://github.com/lhoestq', 'followers_url': 'https://api.github.com/users/lhoestq/followers', 'following_url': 'https://api.github.com/users/lhoestq/following{/other_user}', 'gists_url': 'https://api.github.com/users/lhoestq/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/lhoestq/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/lhoestq/subscriptions', 'organizations_url': 'https://api.github.com/users/lhoestq/orgs', 'repos_url': 'https://api.github.com/users/lhoestq/repos', 'events_url': 'https://api.github.com/users/lhoestq/events{/privacy}', 'received_events_url': 'https://api.github.com/users/lhoestq/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-13T09:23:38Z', 'updated_at': '2023-06-13T09:23:38Z', 'author_association': 'MEMBER', 'body': "Arrow only support 1d numpy arrays, so we convert multidim arrays to lists of 1s arrays (and keep the dtype).\r\n\r\nThough you noticed that it's concerting to lists and lose the dtype. If it's the case then it's a bug.", 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1588898420/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1588901420', 'html_url': 'https://github.com/huggingface/datasets/issues/5936#issuecomment-1588901420', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5936', 'id': 1588901420, 'node_id': 'IC_kwDODunzps5etLYs', 'user': {'login': 'lhoestq', 'id': 42851186, 'node_id': 'MDQ6VXNlcjQyODUxMTg2', 'avatar_url': 'https://avatars.githubusercontent.com/u/42851186?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/lhoestq', 'html_url': 'https://github.com/lhoestq', 'followers_url': 'https://api.github.com/users/lhoestq/followers', 'following_url': 'https://api.github.com/users/lhoestq/following{/other_user}', 'gists_url': 'https://api.github.com/users/lhoestq/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/lhoestq/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/lhoestq/subscriptions', 'organizations_url': 'https://api.github.com/users/lhoestq/orgs', 'repos_url': 'https://api.github.com/users/lhoestq/repos', 'events_url': 'https://api.github.com/users/lhoestq/events{/privacy}', 'received_events_url': 'https://api.github.com/users/lhoestq/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-13T09:25:34Z', 'updated_at': '2023-06-13T09:25:34Z', 'author_association': 'MEMBER', 'body': "Ok the conversion to list shouldn't be there indeed ! Could you open a PR to remove it ?", 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1588901420/reactions', 'total_count': 1, '+1': 1, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}]

[{'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1582771831', 'html_url': 'https://github.com/huggingface/datasets/pull/5935#issuecomment-1582771831', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5935', 'id': 1582771831, 'node_id': 'IC_kwDODunzps5eVy53', 'user': {'login': 'github-actions[bot]', 'id': 41898282, 'node_id': 'MDM6Qm90NDE4OTgyODI=', 'avatar_url': 'https://avatars.githubusercontent.com/in/15368?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/github-actions%5Bbot%5D', 'html_url': 'https://github.com/apps/github-actions', 'followers_url': 'https://api.github.com/users/github-actions%5Bbot%5D/followers', 'following_url': 'https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}', 'gists_url': 'https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/github-actions%5Bbot%5D/subscriptions', 'organizations_url': 'https://api.github.com/users/github-actions%5Bbot%5D/orgs', 'repos_url': 'https://api.github.com/users/github-actions%5Bbot%5D/repos', 'events_url': 'https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}', 'received_events_url': 'https://api.github.com/users/github-actions%5Bbot%5D/received_events', 'type': 'Bot', 'site_admin': False}, 'created_at': '2023-06-08T15:08:20Z', 'updated_at': '2023-06-08T15:08:20Z', 'author_association': 'NONE', 'body': '<details>\n<summary>Show benchmarks</summary>\n\nPyArrow==8.0.0\n\n<details>\n<summary>Show updated benchmarks!</summary>\n\n### Benchmark: benchmark_array_xd.json\n\n| metric | read_batch_formatted_as_numpy after write_array2d | read_batch_formatted_as_numpy after write_flattened_sequence | read_batch_formatted_as_numpy after write_nested_sequence | read_batch_unformated after write_array2d | read_batch_unformated after write_flattened_sequence | read_batch_unformated after write_nested_sequence | read_col_formatted_as_numpy after write_array2d | read_col_formatted_as_numpy after write_flattened_sequence | read_col_formatted_as_numpy after write_nested_sequence | read_col_unformated after write_array2d | read_col_unformated after write_flattened_sequence | read_col_unformated after write_nested_sequence | read_formatted_as_numpy after write_array2d | read_formatted_as_numpy after write_flattened_sequence | read_formatted_as_numpy after write_nested_sequence | read_unformated after write_array2d | read_unformated after write_flattened_sequence | read_unformated after write_nested_sequence | write_array2d | write_flattened_sequence | write_nested_sequence |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.007489 / 0.011353 (-0.003864) | 0.004914 / 0.011008 (-0.006095) | 0.111626 / 0.038508 (0.073117) | 0.037920 / 0.023109 (0.014811) | 0.350571 / 0.275898 (0.074673) | 0.389667 / 0.323480 (0.066187) | 0.006309 / 0.007986 (-0.001676) | 0.005488 / 0.004328 (0.001160) | 0.083962 / 0.004250 (0.079712) | 0.050728 / 0.037052 (0.013675) | 0.360997 / 0.258489 (0.102508) | 0.392736 / 0.293841 (0.098895) | 0.031975 / 0.128546 (-0.096571) | 0.009941 / 0.075646 (-0.065705) | 0.379840 / 0.419271 (-0.039432) | 0.056522 / 0.043533 (0.012989) | 0.359379 / 0.255139 (0.104240) | 0.384487 / 0.283200 (0.101287) | 0.117523 / 0.141683 (-0.024160) | 1.683639 / 1.452155 (0.231485) | 1.791645 / 1.492716 (0.298929) |\n\n### Benchmark: benchmark_getitem\\_100B.json\n\n| metric | get_batch_of\\_1024\\_random_rows | get_batch_of\\_1024\\_rows | get_first_row | get_last_row |\n|--------|---|---|---|---|\n| new / old (diff) | 0.236862 / 0.018006 (0.218856) | 0.481208 / 0.000490 (0.480719) | 0.007455 / 0.000200 (0.007255) | 0.000111 / 0.000054 (0.000057) |\n\n### Benchmark: benchmark_indices_mapping.json\n\n| metric | select | shard | shuffle | sort | train_test_split |\n|--------|---|---|---|---|---|\n| new / old (diff) | 0.030854 / 0.037411 (-0.006557) | 0.126892 / 0.014526 (0.112367) | 0.139207 / 0.176557 (-0.037350) | 0.206447 / 0.737135 (-0.530689) | 0.143095 / 0.296338 (-0.153244) |\n\n### Benchmark: benchmark_iterating.json\n\n| metric | read 5000 | read 50000 | read_batch 50000 10 | read_batch 50000 100 | read_batch 50000 1000 | read_formatted numpy 5000 | read_formatted pandas 5000 | read_formatted tensorflow 5000 | read_formatted torch 5000 | read_formatted_batch numpy 5000 10 | read_formatted_batch numpy 5000 1000 | shuffled read 5000 | shuffled read 50000 | shuffled read_batch 50000 10 | shuffled read_batch 50000 100 | shuffled read_batch 50000 1000 | shuffled read_formatted numpy 5000 | shuffled read_formatted_batch numpy 5000 10 | shuffled read_formatted_batch numpy 5000 1000 |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.474677 / 0.215209 (0.259468) | 4.699534 / 2.077655 (2.621879) | 2.152102 / 1.504120 (0.647983) | 1.934815 / 1.541195 (0.393620) | 1.986448 / 1.468490 (0.517958) | 0.607184 / 4.584777 (-3.977593) | 4.480385 / 3.745712 (0.734673) | 2.074729 / 5.269862 (-3.195132) | 1.182383 / 4.565676 (-3.383294) | 0.075624 / 0.424275 (-0.348651) | 0.014046 / 0.007607 (0.006439) | 0.598859 / 0.226044 (0.372814) | 5.959551 / 2.268929 (3.690622) | 2.700851 / 55.444624 (-52.743773) | 2.303775 / 6.876477 (-4.572702) | 2.456441 / 2.142072 (0.314369) | 0.747185 / 4.805227 (-4.058042) | 0.165787 / 6.500664 (-6.334878) | 0.075817 / 0.075469 (0.000348) |\n\n### Benchmark: benchmark_map_filter.json\n\n| metric | filter | map fast-tokenizer batched | map identity | map identity batched | map no-op batched | map no-op batched numpy | map no-op batched pandas | map no-op batched pytorch | map no-op batched tensorflow |\n|--------|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 1.411859 / 1.841788 (-0.429928) | 17.375495 / 8.074308 (9.301187) | 15.187098 / 10.191392 (4.995706) | 0.169953 / 0.680424 (-0.510471) | 0.020204 / 0.534201 (-0.513997) | 0.461424 / 0.579283 (-0.117859) | 0.494443 / 0.434364 (0.060080) | 0.544583 / 0.540337 (0.004246) | 0.648231 / 1.386936 (-0.738705) |\n\n</details>\nPyArrow==latest\n\n<details>\n<summary>Show updated benchmarks!</summary>\n\n### Benchmark: benchmark_array_xd.json\n\n| metric | read_batch_formatted_as_numpy after write_array2d | read_batch_formatted_as_numpy after write_flattened_sequence | read_batch_formatted_as_numpy after write_nested_sequence | read_batch_unformated after write_array2d | read_batch_unformated after write_flattened_sequence | read_batch_unformated after write_nested_sequence | read_col_formatted_as_numpy after write_array2d | read_col_formatted_as_numpy after write_flattened_sequence | read_col_formatted_as_numpy after write_nested_sequence | read_col_unformated after write_array2d | read_col_unformated after write_flattened_sequence | read_col_unformated after write_nested_sequence | read_formatted_as_numpy after write_array2d | read_formatted_as_numpy after write_flattened_sequence | read_formatted_as_numpy after write_nested_sequence | read_unformated after write_array2d | read_unformated after write_flattened_sequence | read_unformated after write_nested_sequence | write_array2d | write_flattened_sequence | write_nested_sequence |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.007785 / 0.011353 (-0.003568) | 0.005314 / 0.011008 (-0.005694) | 0.087273 / 0.038508 (0.048765) | 0.037810 / 0.023109 (0.014701) | 0.425473 / 0.275898 (0.149575) | 0.459976 / 0.323480 (0.136497) | 0.007270 / 0.007986 (-0.000716) | 0.004631 / 0.004328 (0.000303) | 0.087063 / 0.004250 (0.082812) | 0.052630 / 0.037052 (0.015578) | 0.432384 / 0.258489 (0.173895) | 0.500291 / 0.293841 (0.206450) | 0.033144 / 0.128546 (-0.095402) | 0.010101 / 0.075646 (-0.065545) | 0.096068 / 0.419271 (-0.323204) | 0.062750 / 0.043533 (0.019217) | 0.419308 / 0.255139 (0.164169) | 0.437099 / 0.283200 (0.153900) | 0.122289 / 0.141683 (-0.019394) | 1.737829 / 1.452155 (0.285674) | 1.851481 / 1.492716 (0.358765) |\n\n### Benchmark: benchmark_getitem\\_100B.json\n\n| metric | get_batch_of\\_1024\\_random_rows | get_batch_of\\_1024\\_rows | get_first_row | get_last_row |\n|--------|---|---|---|---|\n| new / old (diff) | 0.014277 / 0.018006 (-0.003729) | 0.489835 / 0.000490 (0.489345) | 0.008423 / 0.000200 (0.008223) | 0.000188 / 0.000054 (0.000134) |\n\n### Benchmark: benchmark_indices_mapping.json\n\n| metric | select | shard | shuffle | sort | train_test_split |\n|--------|---|---|---|---|---|\n| new / old (diff) | 0.032966 / 0.037411 (-0.004445) | 0.130069 / 0.014526 (0.115544) | 0.144372 / 0.176557 (-0.032185) | 0.200400 / 0.737135 (-0.536735) | 0.149384 / 0.296338 (-0.146954) |\n\n### Benchmark: benchmark_iterating.json\n\n| metric | read 5000 | read 50000 | read_batch 50000 10 | read_batch 50000 100 | read_batch 50000 1000 | read_formatted numpy 5000 | read_formatted pandas 5000 | read_formatted tensorflow 5000 | read_formatted torch 5000 | read_formatted_batch numpy 5000 10 | read_formatted_batch numpy 5000 1000 | shuffled read 5000 | shuffled read 50000 | shuffled read_batch 50000 10 | shuffled read_batch 50000 100 | shuffled read_batch 50000 1000 | shuffled read_formatted numpy 5000 | shuffled read_formatted_batch numpy 5000 10 | shuffled read_formatted_batch numpy 5000 1000 |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.511542 / 0.215209 (0.296333) | 5.093879 / 2.077655 (3.016225) | 2.572088 / 1.504120 (1.067968) | 2.339118 / 1.541195 (0.797923) | 2.441637 / 1.468490 (0.973147) | 0.614818 / 4.584777 (-3.969959) | 4.724441 / 3.745712 (0.978729) | 5.431978 / 5.269862 (0.162116) | 2.257794 / 4.565676 (-2.307883) | 0.078109 / 0.424275 (-0.346166) | 0.013821 / 0.007607 (0.006214) | 0.639232 / 0.226044 (0.413188) | 6.424623 / 2.268929 (4.155694) | 3.163018 / 55.444624 (-52.281606) | 2.756786 / 6.876477 (-4.119690) | 2.808655 / 2.142072 (0.666583) | 0.745843 / 4.805227 (-4.059385) | 0.165562 / 6.500664 (-6.335102) | 0.076610 / 0.075469 (0.001141) |\n\n### Benchmark: benchmark_map_filter.json\n\n| metric | filter | map fast-tokenizer batched | map identity | map identity batched | map no-op batched | map no-op batched numpy | map no-op batched pandas | map no-op batched pytorch | map no-op batched tensorflow |\n|--------|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 1.738630 / 1.841788 (-0.103158) | 18.073573 / 8.074308 (9.999265) | 16.482820 / 10.191392 (6.291428) | 0.213233 / 0.680424 (-0.467191) | 0.022839 / 0.534201 (-0.511362) | 0.487043 / 0.579283 (-0.092240) | 0.512518 / 0.434364 (0.078154) | 0.549365 / 0.540337 (0.009028) | 0.656612 / 1.386936 (-0.730324) |\n\n</details>\n</details>\n\n![](https://cml.dev/watermark.png#288e92b03bd4ec91c10c8a529b32631cfaba9fb7 "CML watermark")\n', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1582771831/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1582772683', 'html_url': 'https://github.com/huggingface/datasets/pull/5935#issuecomment-1582772683', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5935', 'id': 1582772683, 'node_id': 'IC_kwDODunzps5eVzHL', 'user': {'login': 'severo', 'id': 1676121, 'node_id': 'MDQ6VXNlcjE2NzYxMjE=', 'avatar_url': 'https://avatars.githubusercontent.com/u/1676121?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/severo', 'html_url': 'https://github.com/severo', 'followers_url': 'https://api.github.com/users/severo/followers', 'following_url': 'https://api.github.com/users/severo/following{/other_user}', 'gists_url': 'https://api.github.com/users/severo/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/severo/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/severo/subscriptions', 'organizations_url': 'https://api.github.com/users/severo/orgs', 'repos_url': 'https://api.github.com/users/severo/repos', 'events_url': 'https://api.github.com/users/severo/events{/privacy}', 'received_events_url': 'https://api.github.com/users/severo/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-08T15:08:44Z', 'updated_at': '2023-06-08T15:08:44Z', 'author_association': 'CONTRIBUTOR', 'body': 'Good idea!\r\n\r\nI was wondering: if we want to optimize the balance between the size of downloading a row group, and the number of rows in the group, would it make sense to compute the row group size by checking the average size of the rows?\r\n\r\neg. 32x32 images could have a larger row group size than full HD images, no? Relying on the size would even remove the need to check the column types.\r\n\r\n(in this proposal, we could use the computed row group size, eg 837, or use the nearest row group size in a list of values: 10, 100, 1000, 10000)', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1582772683/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1582796509', 'html_url': 'https://github.com/huggingface/datasets/pull/5935#issuecomment-1582796509', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5935', 'id': 1582796509, 'node_id': 'IC_kwDODunzps5eV47d', 'user': {'login': 'lhoestq', 'id': 42851186, 'node_id': 'MDQ6VXNlcjQyODUxMTg2', 'avatar_url': 'https://avatars.githubusercontent.com/u/42851186?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/lhoestq', 'html_url': 'https://github.com/lhoestq', 'followers_url': 'https://api.github.com/users/lhoestq/followers', 'following_url': 'https://api.github.com/users/lhoestq/following{/other_user}', 'gists_url': 'https://api.github.com/users/lhoestq/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/lhoestq/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/lhoestq/subscriptions', 'organizations_url': 'https://api.github.com/users/lhoestq/orgs', 'repos_url': 'https://api.github.com/users/lhoestq/repos', 'events_url': 'https://api.github.com/users/lhoestq/events{/privacy}', 'received_events_url': 'https://api.github.com/users/lhoestq/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-08T15:18:00Z', 'updated_at': '2023-06-08T15:18:00Z', 'author_association': 'MEMBER', 'body': 'Probably, but I would go for a simpler solution first :p', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1582796509/reactions', 'total_count': 1, '+1': 1, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1582820421', 'html_url': 'https://github.com/huggingface/datasets/pull/5935#issuecomment-1582820421', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5935', 'id': 1582820421, 'node_id': 'IC_kwDODunzps5eV-xF', 'user': {'login': 'severo', 'id': 1676121, 'node_id': 'MDQ6VXNlcjE2NzYxMjE=', 'avatar_url': 'https://avatars.githubusercontent.com/u/1676121?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/severo', 'html_url': 'https://github.com/severo', 'followers_url': 'https://api.github.com/users/severo/followers', 'following_url': 'https://api.github.com/users/severo/following{/other_user}', 'gists_url': 'https://api.github.com/users/severo/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/severo/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/severo/subscriptions', 'organizations_url': 'https://api.github.com/users/severo/orgs', 'repos_url': 'https://api.github.com/users/severo/repos', 'events_url': 'https://api.github.com/users/severo/events{/privacy}', 'received_events_url': 'https://api.github.com/users/severo/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-08T15:26:54Z', 'updated_at': '2023-06-08T15:27:05Z', 'author_association': 'CONTRIBUTOR', 'body': "Sure! I wanted to understand if the idea made sense or not, but it's not for this PR.", 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1582820421/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1584647951', 'html_url': 'https://github.com/huggingface/datasets/pull/5935#issuecomment-1584647951', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5935', 'id': 1584647951, 'node_id': 'IC_kwDODunzps5ec88P', 'user': {'login': 'lhoestq', 'id': 42851186, 'node_id': 'MDQ6VXNlcjQyODUxMTg2', 'avatar_url': 'https://avatars.githubusercontent.com/u/42851186?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/lhoestq', 'html_url': 'https://github.com/lhoestq', 'followers_url': 'https://api.github.com/users/lhoestq/followers', 'following_url': 'https://api.github.com/users/lhoestq/following{/other_user}', 'gists_url': 'https://api.github.com/users/lhoestq/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/lhoestq/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/lhoestq/subscriptions', 'organizations_url': 'https://api.github.com/users/lhoestq/orgs', 'repos_url': 'https://api.github.com/users/lhoestq/repos', 'events_url': 'https://api.github.com/users/lhoestq/events{/privacy}', 'received_events_url': 'https://api.github.com/users/lhoestq/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-09T14:13:34Z', 'updated_at': '2023-06-09T14:13:34Z', 'author_association': 'MEMBER', 'body': "I think it will be more useful for people who use the viewer and won't impact sequential io that much.", 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1584647951/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1584827426', 'html_url': 'https://github.com/huggingface/datasets/pull/5935#issuecomment-1584827426', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5935', 'id': 1584827426, 'node_id': 'IC_kwDODunzps5edowi', 'user': {'login': 'mariosasko', 'id': 47462742, 'node_id': 'MDQ6VXNlcjQ3NDYyNzQy', 'avatar_url': 'https://avatars.githubusercontent.com/u/47462742?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/mariosasko', 'html_url': 'https://github.com/mariosasko', 'followers_url': 'https://api.github.com/users/mariosasko/followers', 'following_url': 'https://api.github.com/users/mariosasko/following{/other_user}', 'gists_url': 'https://api.github.com/users/mariosasko/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/mariosasko/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/mariosasko/subscriptions', 'organizations_url': 'https://api.github.com/users/mariosasko/orgs', 'repos_url': 'https://api.github.com/users/mariosasko/repos', 'events_url': 'https://api.github.com/users/mariosasko/events{/privacy}', 'received_events_url': 'https://api.github.com/users/mariosasko/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-09T16:10:49Z', 'updated_at': '2023-06-09T16:10:49Z', 'author_association': 'CONTRIBUTOR', 'body': "DuckDB [paragraph](https://duckdb.org/docs/data/parquet/tips.html#s

[{'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1633001666', 'html_url': 'https://github.com/huggingface/datasets/pull/5934#issuecomment-1633001666', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5934', 'id': 1633001666, 'node_id': 'IC_kwDODunzps5hVaDC', 'user': {'login': 'mariosasko', 'id': 47462742, 'node_id': 'MDQ6VXNlcjQ3NDYyNzQy', 'avatar_url': 'https://avatars.githubusercontent.com/u/47462742?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/mariosasko', 'html_url': 'https://github.com/mariosasko', 'followers_url': 'https://api.github.com/users/mariosasko/followers', 'following_url': 'https://api.github.com/users/mariosasko/following{/other_user}', 'gists_url': 'https://api.github.com/users/mariosasko/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/mariosasko/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/mariosasko/subscriptions', 'organizations_url': 'https://api.github.com/users/mariosasko/orgs', 'repos_url': 'https://api.github.com/users/mariosasko/repos', 'events_url': 'https://api.github.com/users/mariosasko/events{/privacy}', 'received_events_url': 'https://api.github.com/users/mariosasko/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-07-12T18:17:39Z', 'updated_at': '2023-07-12T18:17:39Z', 'author_association': 'CONTRIBUTOR', 'body': "I've addressed this as part of #6019, so feel free to close this PR. ", 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1633001666/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1633005976', 'html_url': 'https://github.com/huggingface/datasets/pull/5934#issuecomment-1633005976', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5934', 'id': 1633005976, 'node_id': 'IC_kwDODunzps5hVbGY', 'user': {'login': 'Laurent2916', 'id': 21087104, 'node_id': 'MDQ6VXNlcjIxMDg3MTA0', 'avatar_url': 'https://avatars.githubusercontent.com/u/21087104?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/Laurent2916', 'html_url': 'https://github.com/Laurent2916', 'followers_url': 'https://api.github.com/users/Laurent2916/followers', 'following_url': 'https://api.github.com/users/Laurent2916/following{/other_user}', 'gists_url': 'https://api.github.com/users/Laurent2916/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/Laurent2916/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/Laurent2916/subscriptions', 'organizations_url': 'https://api.github.com/users/Laurent2916/orgs', 'repos_url': 'https://api.github.com/users/Laurent2916/repos', 'events_url': 'https://api.github.com/users/Laurent2916/events{/privacy}', 'received_events_url': 'https://api.github.com/users/Laurent2916/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-07-12T18:21:02Z', 'updated_at': '2023-07-12T18:21:02Z', 'author_association': 'CONTRIBUTOR', 'body': 'Thanks !', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1633005976/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}]

[{'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1581148696', 'html_url': 'https://github.com/huggingface/datasets/pull/5932#issuecomment-1581148696', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5932', 'id': 1581148696, 'node_id': 'IC_kwDODunzps5ePmoY', 'user': {'login': 'github-actions[bot]', 'id': 41898282, 'node_id': 'MDM6Qm90NDE4OTgyODI=', 'avatar_url': 'https://avatars.githubusercontent.com/in/15368?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/github-actions%5Bbot%5D', 'html_url': 'https://github.com/apps/github-actions', 'followers_url': 'https://api.github.com/users/github-actions%5Bbot%5D/followers', 'following_url': 'https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}', 'gists_url': 'https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/github-actions%5Bbot%5D/subscriptions', 'organizations_url': 'https://api.github.com/users/github-actions%5Bbot%5D/orgs', 'repos_url': 'https://api.github.com/users/github-actions%5Bbot%5D/repos', 'events_url': 'https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}', 'received_events_url': 'https://api.github.com/users/github-actions%5Bbot%5D/received_events', 'type': 'Bot', 'site_admin': False}, 'created_at': '2023-06-07T16:18:59Z', 'updated_at': '2023-06-07T16:18:59Z', 'author_association': 'NONE', 'body': '<details>\n<summary>Show benchmarks</summary>\n\nPyArrow==8.0.0\n\n<details>\n<summary>Show updated benchmarks!</summary>\n\n### Benchmark: benchmark_array_xd.json\n\n| metric | read_batch_formatted_as_numpy after write_array2d | read_batch_formatted_as_numpy after write_flattened_sequence | read_batch_formatted_as_numpy after write_nested_sequence | read_batch_unformated after write_array2d | read_batch_unformated after write_flattened_sequence | read_batch_unformated after write_nested_sequence | read_col_formatted_as_numpy after write_array2d | read_col_formatted_as_numpy after write_flattened_sequence | read_col_formatted_as_numpy after write_nested_sequence | read_col_unformated after write_array2d | read_col_unformated after write_flattened_sequence | read_col_unformated after write_nested_sequence | read_formatted_as_numpy after write_array2d | read_formatted_as_numpy after write_flattened_sequence | read_formatted_as_numpy after write_nested_sequence | read_unformated after write_array2d | read_unformated after write_flattened_sequence | read_unformated after write_nested_sequence | write_array2d | write_flattened_sequence | write_nested_sequence |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.008499 / 0.011353 (-0.002854) | 0.006155 / 0.011008 (-0.004853) | 0.124032 / 0.038508 (0.085524) | 0.037337 / 0.023109 (0.014228) | 0.389274 / 0.275898 (0.113376) | 0.427736 / 0.323480 (0.104257) | 0.006929 / 0.007986 (-0.001057) | 0.005017 / 0.004328 (0.000689) | 0.096356 / 0.004250 (0.092105) | 0.055694 / 0.037052 (0.018642) | 0.391417 / 0.258489 (0.132928) | 0.448098 / 0.293841 (0.154257) | 0.042442 / 0.128546 (-0.086105) | 0.013456 / 0.075646 (-0.062190) | 0.423502 / 0.419271 (0.004230) | 0.062919 / 0.043533 (0.019386) | 0.384317 / 0.255139 (0.129178) | 0.410851 / 0.283200 (0.127652) | 0.112807 / 0.141683 (-0.028875) | 1.746050 / 1.452155 (0.293895) | 1.977974 / 1.492716 (0.485257) |\n\n### Benchmark: benchmark_getitem\\_100B.json\n\n| metric | get_batch_of\\_1024\\_random_rows | get_batch_of\\_1024\\_rows | get_first_row | get_last_row |\n|--------|---|---|---|---|\n| new / old (diff) | 0.306382 / 0.018006 (0.288375) | 0.620310 / 0.000490 (0.619820) | 0.009309 / 0.000200 (0.009109) | 0.000106 / 0.000054 (0.000052) |\n\n### Benchmark: benchmark_indices_mapping.json\n\n| metric | select | shard | shuffle | sort | train_test_split |\n|--------|---|---|---|---|---|\n| new / old (diff) | 0.026900 / 0.037411 (-0.010511) | 0.140125 / 0.014526 (0.125599) | 0.136295 / 0.176557 (-0.040261) | 0.207721 / 0.737135 (-0.529414) | 0.146328 / 0.296338 (-0.150011) |\n\n### Benchmark: benchmark_iterating.json\n\n| metric | read 5000 | read 50000 | read_batch 50000 10 | read_batch 50000 100 | read_batch 50000 1000 | read_formatted numpy 5000 | read_formatted pandas 5000 | read_formatted tensorflow 5000 | read_formatted torch 5000 | read_formatted_batch numpy 5000 10 | read_formatted_batch numpy 5000 1000 | shuffled read 5000 | shuffled read 50000 | shuffled read_batch 50000 10 | shuffled read_batch 50000 100 | shuffled read_batch 50000 1000 | shuffled read_formatted numpy 5000 | shuffled read_formatted_batch numpy 5000 10 | shuffled read_formatted_batch numpy 5000 1000 |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.616712 / 0.215209 (0.401503) | 6.237820 / 2.077655 (4.160166) | 2.503809 / 1.504120 (0.999689) | 2.129739 / 1.541195 (0.588544) | 2.160768 / 1.468490 (0.692277) | 0.971273 / 4.584777 (-3.613504) | 5.687161 / 3.745712 (1.941449) | 2.738148 / 5.269862 (-2.531713) | 1.692695 / 4.565676 (-2.872981) | 0.113701 / 0.424275 (-0.310574) | 0.014809 / 0.007607 (0.007202) | 0.774795 / 0.226044 (0.548750) | 7.660012 / 2.268929 (5.391083) | 3.253036 / 55.444624 (-52.191588) | 2.607498 / 6.876477 (-4.268979) | 2.681678 / 2.142072 (0.539606) | 1.095275 / 4.805227 (-3.709952) | 0.239078 / 6.500664 (-6.261586) | 0.081034 / 0.075469 (0.005565) |\n\n### Benchmark: benchmark_map_filter.json\n\n| metric | filter | map fast-tokenizer batched | map identity | map identity batched | map no-op batched | map no-op batched numpy | map no-op batched pandas | map no-op batched pytorch | map no-op batched tensorflow |\n|--------|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 1.574547 / 1.841788 (-0.267240) | 18.323566 / 8.074308 (10.249258) | 19.274482 / 10.191392 (9.083090) | 0.210275 / 0.680424 (-0.470149) | 0.031843 / 0.534201 (-0.502358) | 0.514843 / 0.579283 (-0.064440) | 0.633782 / 0.434364 (0.199418) | 0.588569 / 0.540337 (0.048232) | 0.721401 / 1.386936 (-0.665535) |\n\n</details>\nPyArrow==latest\n\n<details>\n<summary>Show updated benchmarks!</summary>\n\n### Benchmark: benchmark_array_xd.json\n\n| metric | read_batch_formatted_as_numpy after write_array2d | read_batch_formatted_as_numpy after write_flattened_sequence | read_batch_formatted_as_numpy after write_nested_sequence | read_batch_unformated after write_array2d | read_batch_unformated after write_flattened_sequence | read_batch_unformated after write_nested_sequence | read_col_formatted_as_numpy after write_array2d | read_col_formatted_as_numpy after write_flattened_sequence | read_col_formatted_as_numpy after write_nested_sequence | read_col_unformated after write_array2d | read_col_unformated after write_flattened_sequence | read_col_unformated after write_nested_sequence | read_formatted_as_numpy after write_array2d | read_formatted_as_numpy after write_flattened_sequence | read_formatted_as_numpy after write_nested_sequence | read_unformated after write_array2d | read_unformated after write_flattened_sequence | read_unformated after write_nested_sequence | write_array2d | write_flattened_sequence | write_nested_sequence |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.008866 / 0.011353 (-0.002487) | 0.006460 / 0.011008 (-0.004548) | 0.121337 / 0.038508 (0.082829) | 0.033896 / 0.023109 (0.010786) | 0.455702 / 0.275898 (0.179804) | 0.509685 / 0.323480 (0.186205) | 0.007650 / 0.007986 (-0.000336) | 0.005578 / 0.004328 (0.001250) | 0.098505 / 0.004250 (0.094255) | 0.056122 / 0.037052 (0.019069) | 0.478483 / 0.258489 (0.219994) | 0.560008 / 0.293841 (0.266167) | 0.044926 / 0.128546 (-0.083620) | 0.014562 / 0.075646 (-0.061085) | 0.115027 / 0.419271 (-0.304244) | 0.066494 / 0.043533 (0.022961) | 0.463434 / 0.255139 (0.208296) | 0.513856 / 0.283200 (0.230656) | 0.126436 / 0.141683 (-0.015247) | 1.874729 / 1.452155 (0.422575) | 1.925080 / 1.492716 (0.432364) |\n\n### Benchmark: benchmark_getitem\\_100B.json\n\n| metric | get_batch_of\\_1024\\_random_rows | get_batch_of\\_1024\\_rows | get_first_row | get_last_row |\n|--------|---|---|---|---|\n| new / old (diff) | 0.012672 / 0.018006 (-0.005334) | 0.615797 / 0.000490 (0.615307) | 0.001606 / 0.000200 (0.001406) | 0.000118 / 0.000054 (0.000064) |\n\n### Benchmark: benchmark_indices_mapping.json\n\n| metric | select | shard | shuffle | sort | train_test_split |\n|--------|---|---|---|---|---|\n| new / old (diff) | 0.031104 / 0.037411 (-0.006307) | 0.130107 / 0.014526 (0.115581) | 0.140587 / 0.176557 (-0.035970) | 0.205081 / 0.737135 (-0.532054) | 0.144068 / 0.296338 (-0.152270) |\n\n### Benchmark: benchmark_iterating.json\n\n| metric | read 5000 | read 50000 | read_batch 50000 10 | read_batch 50000 100 | read_batch 50000 1000 | read_formatted numpy 5000 | read_formatted pandas 5000 | read_formatted tensorflow 5000 | read_formatted torch 5000 | read_formatted_batch numpy 5000 10 | read_formatted_batch numpy 5000 1000 | shuffled read 5000 | shuffled read 50000 | shuffled read_batch 50000 10 | shuffled read_batch 50000 100 | shuffled read_batch 50000 1000 | shuffled read_formatted numpy 5000 | shuffled read_formatted_batch numpy 5000 10 | shuffled read_formatted_batch numpy 5000 1000 |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.646549 / 0.215209 (0.431340) | 6.403962 / 2.077655 (4.326307) | 2.812594 / 1.504120 (1.308474) | 2.478480 / 1.541195 (0.937285) | 2.552385 / 1.468490 (1.083895) | 0.991987 / 4.584777 (-3.592790) | 5.777917 / 3.745712 (2.032205) | 5.697830 / 5.269862 (0.427969) | 2.370583 / 4.565676 (-2.195094) | 0.109905 / 0.424275 (-0.314370) | 0.013801 / 0.007607 (0.006193) | 0.799932 / 0.226044 (0.573888) | 8.155672 / 2.268929 (5.886743) | 3.711662 / 55.444624 (-51.732963) | 3.042164 / 6.876477 (-3.834312) | 3.073549 / 2.142072 (0.931477) | 1.137515 / 4.805227 (-3.667712) | 0.231266 / 6.500664 (-6.269398) | 0.080893 / 0.075469 (0.005424) |\n\n### Benchmark: benchmark_map_filter.json\n\n| metric | filter | map fast-tokenizer batched | map identity | map identity batched | map no-op batched | map no-op batched numpy | map no-op batched pandas | map no-op batched pytorch | map no-op batched tensorflow |\n|--------|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 1.669210 / 1.841788 (-0.172577) | 18.747144 / 8.074308 (10.672836) | 21.084589 / 10.191392 (10.893197) | 0.241379 / 0.680424 (-0.439045) | 0.029473 / 0.534201 (-0.504728) | 0.524605 / 0.579283 (-0.054678) | 0.622852 / 0.434364 (0.188488) | 0.604941 / 0.540337 (0.064604) | 0.715978 / 1.386936 (-0.670958) |\n\n</details>\n</details>\n\n![](https://cml.dev/watermark.png#142484a60b1330359d7713e906fc9e5e30aa9f64 "CML watermark")\n', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1581148696/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1582302609', 'html_url': 'https://github.com/huggingface/datasets/pull/5932#issuecomment-1582302609', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5932', 'id': 1582302609, 'node_id': 'IC_kwDODunzps5eUAWR', 'user': {'login': 'lhoestq', 'id': 42851186, 'node_id': 'MDQ6VXNlcjQyODUxMTg2', 'avatar_url': 'https://avatars.githubusercontent.com/u/42851186?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/lhoestq', 'html_url': 'https://github.com/lhoestq', 'followers_url': 'https://api.github.com/users/lhoestq/followers', 'following_url': 'https://api.github.com/users/lhoestq/following{/other_user}', 'gists_url': 'https://api.github.com/users/lhoestq/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/lhoestq/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/lhoestq/subscriptions', 'organizations_url': 'https://api.github.com/users/lhoestq/orgs', 'repos_url': 'https://api.github.com/users/lhoestq/repos', 'events_url': 'https://api.github.com/users/lhoestq/events{/privacy}', 'received_events_url': 'https://api.github.com/users/lhoestq/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-08T10:14:19Z', 'updated_at': '2023-06-08T10:14:19Z', 'author_association': 'MEMBER', 'body': 'Cool ! what about `.github/workflows/build_pr_documentation.yml` and `.github/workflows/delete_doc_comment.yml` ?', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1582302609/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1584308014', 'html_url': 'https://github.com/huggingface/datasets/pull/5932#issuecomment-1584308014', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5932', 'id': 1584308014, 'node_id': 'IC_kwDODunzps5ebp8u', 'user': {'login': 'github-actions[bot]', 'id': 41898282, 'node_id': 'MDM6Qm90NDE4OTgyODI=', 'avatar_url': 'https://avatars.githubusercontent.com/in/15368?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/github-actions%5Bbot%5D', 'html_url': 'https://github.com/apps/github-actions', 'followers_url': 'https://api.github.com/users/github-actions%5Bbot%5D/followers', 'following_url': 'https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}', 'gists_url': 'https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/github-actions%5Bbot%5D/subscriptions', 'organizations_url': 'https://api.github.com/users/github-actions%5Bbot%5D/orgs', 'repos_url': 'https://api.github.com/users/github-actions%5Bbot%5D/repos', 'events_url': 'https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}', 'received_events_url': 'https://api.github.com/users/github-actions%5Bbot%5D/received_events', 'type': 'Bot', 'site_admin': False}, 'created_at': '2023-06-09T10:00:14Z', 'updated_at': '2023-06-09T10:00:14Z', 'author_association': 'NONE', 'body': '<details>\n<summary>Show benchmarks</summary>\n\nPyArrow==8.0.0\n\n<details>\n<summary>Show updated benchmarks!</summary>\n\n### Benchmark: benchmark_array_xd.json\n\n| metric | read_batch_formatted_as_numpy after write_array2d | read_batch_formatted_as_numpy after write_flattened_sequence | read_batch_formatted_as_numpy after write_nested_sequence | read_batch_unformated after write_array2d | read_batch_unformated after write_flattened_sequence | read_batch_unformated after write_nested_sequence | read_col_formatted_as_numpy after write_array2d | read_col_formatted_as_numpy after write_flattened_sequence | read_col_formatted_as_numpy after write_nested_sequence | read_col_unformated after write_array2d | read_col_unformated after write_flattened_sequence | read_col_unformated after write_nested_sequence | read_formatted_as_numpy after write_array2d | read_formatted_as_numpy after write_flattened_sequence | read_formatted_as_numpy after write_nested_sequence | read_unformated after write_array2d | read_unformated after write_flattened_sequence | read_unformated after write_nested_sequence | write_array2d | write_flattened_sequence | write_nested_sequence |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.005973 / 0.011353 (-0.005380) | 0.004389 / 0.011008 (-0.006620) | 0.096076 / 0.038508 (0.057568) | 0.031569 / 0.023109 (0.008460) | 0.328300 / 0.275898 (0.052402) | 0.359356 / 0.323480 (0.035876) | 0.005378 / 0.007986 (-0.002607) | 0.003703 / 0.004328 (-0.000625) | 0.075251 / 0.004250 (0.071000) | 0.042340 / 0.037052 (0.005287) | 0.346103 / 0.258489 (0.087614) | 0.379896 / 0.293841 (0.086055) | 0.027493 / 0.128546 (-0.101053) | 0.009033 / 0.075646 (-0.066613) | 0.327829 / 0.419271 (-0.091442) | 0.064074 / 0.043533 (0.020541) | 0.337703 / 0.255139 (0.082564) | 0.355335 / 0.283200 (0.072136) | 0.101179 / 0.141683 (-0.040504) | 1.471738 / 1.452155 (0.019584) | 1.539031 / 1.492716 (0.046315) |\n\n### Benchmark: benchmark_getitem\\_100B.json\n\n| metric | get_batch_of\\_1024\\_random_rows | get_batch_of\\_1024\\_rows | get_first_row | get_last_row |\n|--------|---|---|---|---|\n| new / old (diff) | 0.194097 / 0.018006 (0.176091) | 0.434190 / 0.000490 (0.433701) | 0.005730 / 0.000200 (0.005530) | 0.000088 / 0.000054 (0.000033) |\n\n### Benchmark: benchmark_indices_mapping.json\n\n| metric | select | shard | shuffle | sort | train_test_split |\n|--------|---|---|---|---|---|\n| new / old (diff) | 0.025634 / 0.037411 (-0.011778) | 0.105080 / 0.014526 (0.090555) | 0.116508 / 0.176557 (-0.060049) | 0.173867 / 0.737135 (-0.563269) | 0.117749 / 0.296338 (-0.178590) |\n\n### Benchmark: benchmark_iterating.json\n\n| metric | read 5000 | read 50000 | read_batch 50000 10 | read_batch 50000 100 | read_batch 50000 1000 | read_formatted numpy 5000 | read_formatted pandas 5000 | read_formatted tensorflow 5000 | read_formatted torch 5000 | read_formatted_batch numpy 5000 10 | read_formatted_batch numpy 5000 1000 | shuffled read 5000 | shuffled read 50000 | shuffled read_batch 50000 10 | shuffled read_batch 50000 100 | shuffled read_batch 50000 1000 | shuffled read_formatted numpy 5000 | shuffled read_formatted_batch numpy 5000 10 | shuffled read_formatted_batch numpy 5000 1000 |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.401566 / 0.215209 (0.186357) | 4.003558 / 2.077655 (1.925903) | 1.802756 / 1.504120 (0.298636) | 1.604222 / 1.541195 (0.063027) | 1.656617 / 1.468490 (0.188127) | 0.523385 / 4.584777 (-4.061392) | 3.744292 / 3.745712 (-0.001420) | 1.794295 / 5.269862 (-3.475567) | 1.044690 / 4.565676 (-3.520987) | 0.064992 / 0.424275 (-0.359284) | 0.011542 / 0.007607 (0.003935) | 0.507830 / 0.226044 (0.281785) | 5.061574 / 2.268929 (2.792645) | 2.252896 / 55.444624 (-53.191729) | 1.912551 / 6.876477 (-4.963926) | 2.073510 / 2.142072 (-0.068562) | 0.642148 / 4.805227 (-4.163079) | 0.140151 / 6.500664 (-6.360513) | 0.062623 / 0.075469 (-0.012846) |\n\n### Benchmark: benchmark_map_filter.json\n\n| metric | filter | map fast-tokenizer batched | map identity | map identity batched | map no-op batched | map no-op batched numpy | map no-op batched pandas | map no-op batched pytorch | map no-op batched tensorflow |\n|--------|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 1.180367 / 1.841788 (-0.661421) | 14.263475 / 8.074308 (6.189167) | 12.917251 / 10.191392 (2.725859) | 0.143815 / 0.680424 (-0.536608) | 0.017286 / 0.534201 (-0.516915) | 0.388411 / 0.579283 (-0.190872) | 0.430512 / 0.434364 (-0.003851) | 0.466595 / 0.540337 (-0.073742) | 0.564545 / 1.386936 (-0.822391) |\n\n</details>\nPyArrow==latest\n\n<details>\n<summary>Show updated benchmarks!</summary>\n\n### Benchmark: benchmark_array_xd.json\n\n| metric | read_batch_formatted_as_numpy after write_array2d | read_batch_formatted_as_numpy after write_flattened_sequence | read_batch_formatted_as_numpy after write_nested_sequence | read_batch_unformated after write_array2d | read_batch_unformated after write_flattened_sequence | read_batch_unformated after write_nested_sequence | read_col_formatted_as_numpy after write_array2d | read_col_formatted_as_numpy after write_flattened_sequence | read_col_formatted_as_numpy after write_nested_sequence | read_col_unformated after write_array2d | read_col_unformated after write_flattened_sequence | read_col_unformated after write_nested_sequence | read_

[{'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1591892826', 'html_url': 'https://github.com/huggingface/datasets/issues/5931#issuecomment-1591892826', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5931', 'id': 1591892826, 'node_id': 'IC_kwDODunzps5e4lta', 'user': {'login': 'mariosasko', 'id': 47462742, 'node_id': 'MDQ6VXNlcjQ3NDYyNzQy', 'avatar_url': 'https://avatars.githubusercontent.com/u/47462742?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/mariosasko', 'html_url': 'https://github.com/mariosasko', 'followers_url': 'https://api.github.com/users/mariosasko/followers', 'following_url': 'https://api.github.com/users/mariosasko/following{/other_user}', 'gists_url': 'https://api.github.com/users/mariosasko/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/mariosasko/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/mariosasko/subscriptions', 'organizations_url': 'https://api.github.com/users/mariosasko/orgs', 'repos_url': 'https://api.github.com/users/mariosasko/repos', 'events_url': 'https://api.github.com/users/mariosasko/events{/privacy}', 'received_events_url': 'https://api.github.com/users/mariosasko/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-14T20:00:37Z', 'updated_at': '2023-06-14T20:01:55Z', 'author_association': 'CONTRIBUTOR', 'body': 'This can happen when a map transform cannot be hashed deterministically (e.g., an object referenced by the transform changes its state after the first call - an issue with fast tokenizers). The solution is to provide `cache_file_name` in the `map` call to check this file for the cached result instead of relying on the default caching mechanism.', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1591892826/reactions', 'total_count': 1, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 1, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}]
[{'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1593215945', 'html_url': 'https://github.com/huggingface/datasets/issues/5930#issuecomment-1593215945', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5930', 'id': 1593215945, 'node_id': 'IC_kwDODunzps5e9ovJ', 'user': {'login': 'mariosasko', 'id': 47462742, 'node_id': 'MDQ6VXNlcjQ3NDYyNzQy', 'avatar_url': 'https://avatars.githubusercontent.com/u/47462742?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/mariosasko', 'html_url': 'https://github.com/mariosasko', 'followers_url': 'https://api.github.com/users/mariosasko/followers', 'following_url': 'https://api.github.com/users/mariosasko/following{/other_user}', 'gists_url': 'https://api.github.com/users/mariosasko/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/mariosasko/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/mariosasko/subscriptions', 'organizations_url': 'https://api.github.com/users/mariosasko/orgs', 'repos_url': 'https://api.github.com/users/mariosasko/repos', 'events_url': 'https://api.github.com/users/mariosasko/events{/privacy}', 'received_events_url': 'https://api.github.com/users/mariosasko/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-15T14:49:20Z', 'updated_at': '2023-06-15T14:49:20Z', 'author_association': 'CONTRIBUTOR', 'body': "This issue seems to have been resolved, so I'm closing it.", 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1593215945/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}]
[{'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1593173095', 'html_url': 'https://github.com/huggingface/datasets/issues/5929#issuecomment-1593173095', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5929', 'id': 1593173095, 'node_id': 'IC_kwDODunzps5e9eRn', 'user': {'login': 'mariosasko', 'id': 47462742, 'node_id': 'MDQ6VXNlcjQ3NDYyNzQy', 'avatar_url': 'https://avatars.githubusercontent.com/u/47462742?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/mariosasko', 'html_url': 'https://github.com/mariosasko', 'followers_url': 'https://api.github.com/users/mariosasko/followers', 'following_url': 'https://api.github.com/users/mariosasko/following{/other_user}', 'gists_url': 'https://api.github.com/users/mariosasko/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/mariosasko/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/mariosasko/subscriptions', 'organizations_url': 'https://api.github.com/users/mariosasko/orgs', 'repos_url': 'https://api.github.com/users/mariosasko/repos', 'events_url': 'https://api.github.com/users/mariosasko/events{/privacy}', 'received_events_url': 'https://api.github.com/users/mariosasko/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-15T14:25:59Z', 'updated_at': '2023-06-15T14:25:59Z', 'author_association': 'CONTRIBUTOR', 'body': "Hi! The times match when I run this code locally or on Colab.\r\n\r\nAlso, we use `multiprocess`, not `multiprocessing`, for parallelization, and torch's `__init__.py` (executed on `import torch` ) slightly modifies the latter.", 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1593173095/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1594652793', 'html_url': 'https://github.com/huggingface/datasets/issues/5929#issuecomment-1594652793', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5929', 'id': 1594652793, 'node_id': 'IC_kwDODunzps5fDHh5', 'user': {'login': 'Maxscha', 'id': 12814709, 'node_id': 'MDQ6VXNlcjEyODE0NzA5', 'avatar_url': 'https://avatars.githubusercontent.com/u/12814709?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/Maxscha', 'html_url': 'https://github.com/Maxscha', 'followers_url': 'https://api.github.com/users/Maxscha/followers', 'following_url': 'https://api.github.com/users/Maxscha/following{/other_user}', 'gists_url': 'https://api.github.com/users/Maxscha/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/Maxscha/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/Maxscha/subscriptions', 'organizations_url': 'https://api.github.com/users/Maxscha/orgs', 'repos_url': 'https://api.github.com/users/Maxscha/repos', 'events_url': 'https://api.github.com/users/Maxscha/events{/privacy}', 'received_events_url': 'https://api.github.com/users/Maxscha/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-16T13:09:12Z', 'updated_at': '2023-06-16T13:09:12Z', 'author_association': 'NONE', 'body': "Hey Mariosasko,\r\n\r\nThanks for looking into it. We further did some investigations after your comment and figured out it's only affecting some hardware/software configurations with the `pytorch` installation of `conda-forge`. Based on this we found the following issue in PyTorch: https://github.com/pytorch/pytorch/issues/102269 with a quick fix for now.\r\n\r\nSince it seems to be a deeper issue with forking processes, the difference between`multiprocess` and `multiprocessing` didn't make a difference.\r\n\r\nClosing this, since the issue comes from `pytorch` not `dataset`. \r\n", 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1594652793/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}]

[{'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1578952220', 'html_url': 'https://github.com/huggingface/datasets/issues/5927#issuecomment-1578952220', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5927', 'id': 1578952220, 'node_id': 'IC_kwDODunzps5eHOYc', 'user': {'login': 'qgallouedec', 'id': 45557362, 'node_id': 'MDQ6VXNlcjQ1NTU3MzYy', 'avatar_url': 'https://avatars.githubusercontent.com/u/45557362?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/qgallouedec', 'html_url': 'https://github.com/qgallouedec', 'followers_url': 'https://api.github.com/users/qgallouedec/followers', 'following_url': 'https://api.github.com/users/qgallouedec/following{/other_user}', 'gists_url': 'https://api.github.com/users/qgallouedec/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/qgallouedec/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/qgallouedec/subscriptions', 'organizations_url': 'https://api.github.com/users/qgallouedec/orgs', 'repos_url': 'https://api.github.com/users/qgallouedec/repos', 'events_url': 'https://api.github.com/users/qgallouedec/events{/privacy}', 'received_events_url': 'https://api.github.com/users/qgallouedec/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-06T15:11:39Z', 'updated_at': '2023-06-06T15:11:39Z', 'author_association': 'CONTRIBUTOR', 'body': "Easy fix would be to add:\r\n\r\n```python\r\nnull_indices -= np.arange(len(null_indices))\r\n```\r\n\r\nbefore L279, but I'm not sure it's the most intuitive way to fix it.", 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1578952220/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1589229304', 'html_url': 'https://github.com/huggingface/datasets/issues/5927#issuecomment-1589229304', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5927', 'id': 1589229304, 'node_id': 'IC_kwDODunzps5eubb4', 'user': {'login': 'qgallouedec', 'id': 45557362, 'node_id': 'MDQ6VXNlcjQ1NTU3MzYy', 'avatar_url': 'https://avatars.githubusercontent.com/u/45557362?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/qgallouedec', 'html_url': 'https://github.com/qgallouedec', 'followers_url': 'https://api.github.com/users/qgallouedec/followers', 'following_url': 'https://api.github.com/users/qgallouedec/following{/other_user}', 'gists_url': 'https://api.github.com/users/qgallouedec/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/qgallouedec/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/qgallouedec/subscriptions', 'organizations_url': 'https://api.github.com/users/qgallouedec/orgs', 'repos_url': 'https://api.github.com/users/qgallouedec/repos', 'events_url': 'https://api.github.com/users/qgallouedec/events{/privacy}', 'received_events_url': 'https://api.github.com/users/qgallouedec/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-13T12:39:17Z', 'updated_at': '2023-06-13T12:39:39Z', 'author_association': 'CONTRIBUTOR', 'body': 'Same issue here:\r\n\r\nhttps://github.com/huggingface/datasets/blob/7fcbe5b1575c8d162b65b9397b3dfda995a4e048/src/datasets/features/features.py#L1398\r\n\r\nFixed in #5948 ', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1589229304/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}]
[{'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1578898800', 'html_url': 'https://github.com/huggingface/datasets/issues/5926#issuecomment-1578898800', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5926', 'id': 1578898800, 'node_id': 'IC_kwDODunzps5eHBVw', 'user': {'login': 'albertvillanova', 'id': 8515462, 'node_id': 'MDQ6VXNlcjg1MTU0NjI=', 'avatar_url': 'https://avatars.githubusercontent.com/u/8515462?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/albertvillanova', 'html_url': 'https://github.com/albertvillanova', 'followers_url': 'https://api.github.com/users/albertvillanova/followers', 'following_url': 'https://api.github.com/users/albertvillanova/following{/other_user}', 'gists_url': 'https://api.github.com/users/albertvillanova/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/albertvillanova/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/albertvillanova/subscriptions', 'organizations_url': 'https://api.github.com/users/albertvillanova/orgs', 'repos_url': 'https://api.github.com/users/albertvillanova/repos', 'events_url': 'https://api.github.com/users/albertvillanova/events{/privacy}', 'received_events_url': 'https://api.github.com/users/albertvillanova/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-06T14:41:50Z', 'updated_at': '2023-06-06T14:41:50Z', 'author_association': 'MEMBER', 'body': 'Thanks for reporting, @severo.\r\n\r\nThis is a known issue with `fsspec`:\r\n- #5862\r\n- https://github.com/fsspec/filesystem_spec/issues/1265', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1578898800/reactions', 'total_count': 1, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 1, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}]
[]

[{'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1573979908', 'html_url': 'https://github.com/huggingface/datasets/issues/5923#issuecomment-1573979908', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5923', 'id': 1573979908, 'node_id': 'IC_kwDODunzps5d0QcE', 'user': {'login': 'mariosasko', 'id': 47462742, 'node_id': 'MDQ6VXNlcjQ3NDYyNzQy', 'avatar_url': 'https://avatars.githubusercontent.com/u/47462742?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/mariosasko', 'html_url': 'https://github.com/mariosasko', 'followers_url': 'https://api.github.com/users/mariosasko/followers', 'following_url': 'https://api.github.com/users/mariosasko/following{/other_user}', 'gists_url': 'https://api.github.com/users/mariosasko/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/mariosasko/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/mariosasko/subscriptions', 'organizations_url': 'https://api.github.com/users/mariosasko/orgs', 'repos_url': 'https://api.github.com/users/mariosasko/repos', 'events_url': 'https://api.github.com/users/mariosasko/events{/privacy}', 'received_events_url': 'https://api.github.com/users/mariosasko/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-02T16:11:03Z', 'updated_at': '2023-06-02T16:11:03Z', 'author_association': 'CONTRIBUTOR', 'body': 'Based on https://github.com/rapidsai/cudf/issues/10187, this probably means your `pyarrow` installation is not compatible with `datasets`.\r\n\r\nCan you please execute the following commands in the terminal and paste the output here?\r\n```\r\nconda list | grep arrow\r\n``` \r\n```\r\npython -c "import pyarrow; print(pyarrow.__file__)"\r\n```\r\n\r\n\r\n', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1573979908/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1574233233', 'html_url': 'https://github.com/huggingface/datasets/issues/5923#issuecomment-1574233233', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5923', 'id': 1574233233, 'node_id': 'IC_kwDODunzps5d1OSR', 'user': {'login': 'ehuangc', 'id': 71412682, 'node_id': 'MDQ6VXNlcjcxNDEyNjgy', 'avatar_url': 'https://avatars.githubusercontent.com/u/71412682?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/ehuangc', 'html_url': 'https://github.com/ehuangc', 'followers_url': 'https://api.github.com/users/ehuangc/followers', 'following_url': 'https://api.github.com/users/ehuangc/following{/other_user}', 'gists_url': 'https://api.github.com/users/ehuangc/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/ehuangc/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/ehuangc/subscriptions', 'organizations_url': 'https://api.github.com/users/ehuangc/orgs', 'repos_url': 'https://api.github.com/users/ehuangc/repos', 'events_url': 'https://api.github.com/users/ehuangc/events{/privacy}', 'received_events_url': 'https://api.github.com/users/ehuangc/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-02T19:47:30Z', 'updated_at': '2023-06-02T19:47:30Z', 'author_association': 'NONE', 'body': '> Based on [rapidsai/cudf#10187](https://github.com/rapidsai/cudf/issues/10187), this probably means your `pyarrow` installation is not compatible with `datasets`.\r\n> \r\n> Can you please execute the following commands in the terminal and paste the output here?\r\n> \r\n> ```\r\n> conda list | grep arrow\r\n> ```\r\n> \r\n> ```\r\n> python -c "import pyarrow; print(pyarrow.__file__)"\r\n> ```\r\n\r\n\r\nHere is the output to the first command:\r\n```\r\narrow-cpp                 11.0.0           py39h7f74497_0  \r\npyarrow                   12.0.0                   pypi_0    pypi\r\n```\r\nand the second:\r\n```\r\n/Users/edward/opt/anaconda3/envs/cs235/lib/python3.9/site-packages/pyarrow/__init__.py\r\n```\r\nThanks!\r\n\r\n\r\n\r\n', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1574233233/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1574636248', 'html_url': 'https://github.com/huggingface/datasets/issues/5923#issuecomment-1574636248', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5923', 'id': 1574636248, 'node_id': 'IC_kwDODunzps5d2wrY', 'user': {'login': 'Joheun-Kang', 'id': 57236540, 'node_id': 'MDQ6VXNlcjU3MjM2NTQw', 'avatar_url': 'https://avatars.githubusercontent.com/u/57236540?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/Joheun-Kang', 'html_url': 'https://github.com/Joheun-Kang', 'followers_url': 'https://api.github.com/users/Joheun-Kang/followers', 'following_url': 'https://api.github.com/users/Joheun-Kang/following{/other_user}', 'gists_url': 'https://api.github.com/users/Joheun-Kang/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/Joheun-Kang/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/Joheun-Kang/subscriptions', 'organizations_url': 'https://api.github.com/users/Joheun-Kang/orgs', 'repos_url': 'https://api.github.com/users/Joheun-Kang/repos', 'events_url': 'https://api.github.com/users/Joheun-Kang/events{/privacy}', 'received_events_url': 'https://api.github.com/users/Joheun-Kang/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-03T04:28:57Z', 'updated_at': '2023-06-03T04:28:57Z', 'author_association': 'NONE', 'body': 'after installing pytesseract 0.3.10, I got the above error. FYI ', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1574636248/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1574652229', 'html_url': 'https://github.com/huggingface/datasets/issues/5923#issuecomment-1574652229', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5923', 'id': 1574652229, 'node_id': 'IC_kwDODunzps5d20lF', 'user': {'login': 'Joheun-Kang', 'id': 57236540, 'node_id': 'MDQ6VXNlcjU3MjM2NTQw', 'avatar_url': 'https://avatars.githubusercontent.com/u/57236540?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/Joheun-Kang', 'html_url': 'https://github.com/Joheun-Kang', 'followers_url': 'https://api.github.com/users/Joheun-Kang/followers', 'following_url': 'https://api.github.com/users/Joheun-Kang/following{/other_user}', 'gists_url': 'https://api.github.com/users/Joheun-Kang/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/Joheun-Kang/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/Joheun-Kang/subscriptions', 'organizations_url': 'https://api.github.com/users/Joheun-Kang/orgs', 'repos_url': 'https://api.github.com/users/Joheun-Kang/repos', 'events_url': 'https://api.github.com/users/Joheun-Kang/events{/privacy}', 'received_events_url': 'https://api.github.com/users/Joheun-Kang/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-03T04:45:14Z', 'updated_at': '2023-06-03T04:45:14Z', 'author_association': 'NONE', 'body': 'RuntimeError: Failed to import transformers.trainer because of the following error (look up to see its traceback):\r\npyarrow.lib.IpcWriteOptions size changed, may indicate binary incompatibility. Expected 88 from C header, got 72 from PyObject', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1574652229/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1575788697', 'html_url': 'https://github.com/huggingface/datasets/issues/5923#issuecomment-1575788697', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5923', 'id': 1575788697, 'node_id': 'IC_kwDODunzps5d7KCZ', 'user': {'login': 'ssydyc', 'id': 6045564, 'node_id': 'MDQ6VXNlcjYwNDU1NjQ=', 'avatar_url': 'https://avatars.githubusercontent.com/u/6045564?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/ssydyc', 'html_url': 'https://github.com/ssydyc', 'followers_url': 'https://api.github.com/users/ssydyc/followers', 'following_url': 'https://api.github.com/users/ssydyc/following{/other_user}', 'gists_url': 'https://api.github.com/users/ssydyc/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/ssydyc/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/ssydyc/subscriptions', 'organizations_url': 'https://api.github.com/users/ssydyc/orgs', 'repos_url': 'https://api.github.com/users/ssydyc/repos', 'events_url': 'https://api.github.com/users/ssydyc/events{/privacy}', 'received_events_url': 'https://api.github.com/users/ssydyc/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-04T23:32:19Z', 'updated_at': '2023-06-05T15:33:20Z', 'author_association': 'NONE', 'body': 'I got the same error, pyarrow 12.0.0 released May/2023 (https://pypi.org/project/pyarrow/) is not compatible, running `pip install pyarrow==11.0.0` to force install the previous version solved the problem.\r\n\r\nDo we need to update dependencies? ', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1575788697/reactions', 'total_count': 4, '+1': 4, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1576070619', 'html_url': 'https://github.com/huggingface/datasets/issues/5923#issuecomment-1576070619', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5923', 'id': 1576070619, 'node_id': 'IC_kwDODunzps5d8O3b', 'user': {'login': 'albertvillanova', 'id': 8515462, 'node_id': 'MDQ6VXNlcjg1MTU0NjI=', 'avatar_url': 'https://avatars.githubusercontent.com/u/8515462?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/albertvillanova', 'html_url': 'https://github.com/albertvillanova', 'followers_url': 'https://api.github.com/users/albertvillanova/followers', 'following_url': 'https://api.github.com/users/albertvillanova/following{/other_user}', 'gists_url': 'https://api.github.com/users/albertvillanova/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/albertvillanova/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/albertvillanova/subscriptions', 'organizations_url': 'https://api.github.com/users/albertvillanova/orgs', 'repos_url': 'https://api.github.com/users/albertvillanova/repos', 'events_url': 'https://api.github.com/users/albertvillanova/events{/privacy}', 'received_events_url': 'https://api.github.com/users/albertvillanova/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-05T05:31:55Z', 'updated_at': '2023-06-05T05:31:55Z', 'author_association': 'MEMBER', 'body': 'Please note that our CI properly passes all tests with `pyarrow-12.0.0`, for Python 3.7 and Python 3.10, for Ubuntu and Windows: see for example https://github.com/huggingface/datasets/actions/runs/5157324334/jobs/9289582291', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1576070619/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1576239034', 'html_url': 'https://github.com/huggingface/datasets/issues/5923#issuecomment-1576239034', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5923', 'id': 1576239034, 'node_id': 'IC_kwDODunzps5d83-6', 'user': {'login': 'Joheun-Kang', 'id': 57236540, 'node_id': 'MDQ6VXNlcjU3MjM2NTQw', 'avatar_url': 'https://avatars.githubusercontent.com/u/57236540?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/Joheun-Kang', 'html_url': 'https://github.com/Joheun-Kang', 'followers_url': 'https://api.github.com/users/Joheun-Kang/followers', 'following_url': 'https://api.github.com/users/Joheun-Kang/following{/other_user}', 'gists_url': 'https://api.github.com/users/Joheun-Kang/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/Joheun-Kang/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/Joheun-Kang/subscriptions', 'organizations_url': 'https://api.github.com/users/Joheun-Kang/orgs', 'repos_url': 'https://api.github.com/users/Joheun-Kang/repos', 'events_url': 'https://api.github.com/users/Joheun-Kang/events{/privacy}', 'received_events_url': 'https://api.github.com/users/Joheun-Kang/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-05T07:41:21Z', 'updated_at': '2023-06-05T07:43:31Z', 'author_association': 'NONE', 'body': 'For conda with python3.8.16 this solved my problem! thanks!\r\n\r\n> I got the same error, pyarrow 12.0.0 released May/2023 (https://pypi.org/project/pyarrow/) is not compatible, running `pip install pyarrow==11.0.0` to force install the previous version solved the problem.\r\n> \r\n> Do we need to update dependencies? I can work on that if no one else is working on it.\r\n\r\n', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1576239034/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1576241508', 'html_url': 'https://github.com/huggingface/datasets/issues/5923#issuecomment-1576241508', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5923', 'id': 1576241508, 'node_id': 'IC_kwDODunzps5d84lk', 'user': {'login': 'Joheun-Kang', 'id': 57236540, 'node_id': 'MDQ6VXNlcjU3MjM2NTQw', 'avatar_url': 'https://avatars.githubusercontent.com/u/57236540?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/Joheun-Kang', 'html_url': 'https://github.com/Joheun-Kang', 'followers_url': 'https://api.github.com/users/Joheun-Kang/followers', 'following_url': 'https://api.github.com/users/Joheun-Kang/following{/other_user}', 'gists_url': 'https://api.github.com/users/Joheun-Kang/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/Joheun-Kang/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/Joheun-Kang/subscriptions', 'organizations_url': 'https://api.github.com/users/Joheun-Kang/orgs', 'repos_url': 'https://api.github.com/users/Joheun-Kang/repos', 'events_url': 'https://api.github.com/users/Joheun-Kang/events{/privacy}', 'received_events_url': 'https://api.github.com/users/Joheun-Kang/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-05T07:42:29Z', 'updated_at': '2023-06-05T07:42:29Z', 'author_association': 'NONE', 'body': 'Thanks for replying. I am not sure about those environments but it seems like pyarrow-12.0.0 does not work for conda with python 3.8.16. \r\n\r\n> Please note that our CI properly passes all tests with `pyarrow-12.0.0`, for Python 3.7 and Python 3.10, for Ubuntu and Windows: see for example https://github.com/huggingface/datasets/actions/runs/5157324334/jobs/9289582291\r\n\r\n', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1576241508/reactions', 'total_count': 1, '+1': 1, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1596904395', 'html_url': 'https://github.com/huggingface/datasets/issues/5923#issuecomment-1596904395', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5923', 'id': 1596904395, 'node_id': 'IC_kwDODunzps5fLtPL', 'user': {'login': 'lorelupo', 'id': 26467076, 'node_id': 'MDQ6VXNlcjI2NDY3MDc2', 'avatar_url': 'https://avatars.githubusercontent.com/u/26467076?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/lorelupo', 'html_url': 'https://github.com/lorelupo', 'followers_url': 'https://api.github.com/users/lorelupo/followers', 'following_url': 'https://api.github.com/users/lorelupo/following{/other_user}', 'gists_url': 'https://api.github.com/users/lorelupo/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/lorelupo/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/lorelupo/subscriptions', 'organizations_url': 'https://api.github.com/users/lorelupo/orgs', 'repos_url': 'https://api.github.com/users/lorelupo/repos', 'events_url': 'https://api.github.com/users/lorelupo/events{/privacy}', 'received_events_url': 'https://api.github.com/users/lorelupo/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-19T10:10:13Z', 'updated_at': '2023-06-19T10:10:13Z', 'author_association': 'NONE', 'body': 'Got the same error with:\r\n\r\n```\r\narrow-cpp                 11.0.0          py310h7516544_0  \r\npyarrow                   12.0.0                   pypi_0    pypi\r\n\r\npython                    3.10.11              h7a1cb2a_2  \r\n\r\ndatasets                  2.13.0             pyhd8ed1ab_0    conda-forge\r\n```', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1596904395/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1596914519', 'html_url': 'https://github.com/huggingface/datasets/issues/5923#issuecomment-1596914519', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5923', 'id': 1596914519, 'node_id': 'IC_kwDODunzps5fLvtX', 'user': {'login': 'lorelupo', 'id': 26467076, 'node_id': 'MDQ6VXNlcjI2NDY3MDc2', 'avatar_url': 'https://avatars.githubusercontent.com/u/26467076?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/lorelupo', 'html_url': 'https://github.com/lorelupo', 'followers_url': 'https://api.github.com/users/lorelupo/followers', 'following_url': 'https://api.github.com/users/lorelupo/following{/other_user}', 'gists_url': 'https://api.github.com/users/lorelupo/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/lorelupo/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/lorelupo/subscriptions', 'organizations_url': 'https://api.github.com/users/lorelupo/orgs', 'repos_url': 'https://api.github.com/users/lorelupo/repos', 'events_url': 'https://api.github.com/users/lorelupo/events{/privacy}', 'received_events_url': 'https://api.github.com/users/lorelupo/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-19T10:16:04Z', 'updated_at': '2023-06-19T10:16:04Z', 'author_association': 'NONE', 'body': '> I got the same error, pyarrow 12.0.0 released May/2023 (https://pypi.org/project/pyarrow/) is not compatible, running `pip install pyarrow==11.0.0` to force install the previous version solved the problem.\r\n> \r\n> Do we need to update dependencies?\r\n\r\nThis solved the issue for me as well.', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1596914519/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1607895634', 'html_url': 'https://github.com/huggingface/datase

[{'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1573616652', 'html_url': 'https://github.com/huggingface/datasets/issues/5922#issuecomment-1573616652', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5922', 'id': 1573616652, 'node_id': 'IC_kwDODunzps5dy3wM', 'user': {'login': 'albertvillanova', 'id': 8515462, 'node_id': 'MDQ6VXNlcjg1MTU0NjI=', 'avatar_url': 'https://avatars.githubusercontent.com/u/8515462?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/albertvillanova', 'html_url': 'https://github.com/albertvillanova', 'followers_url': 'https://api.github.com/users/albertvillanova/followers', 'following_url': 'https://api.github.com/users/albertvillanova/following{/other_user}', 'gists_url': 'https://api.github.com/users/albertvillanova/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/albertvillanova/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/albertvillanova/subscriptions', 'organizations_url': 'https://api.github.com/users/albertvillanova/orgs', 'repos_url': 'https://api.github.com/users/albertvillanova/repos', 'events_url': 'https://api.github.com/users/albertvillanova/events{/privacy}', 'received_events_url': 'https://api.github.com/users/albertvillanova/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-02T11:57:14Z', 'updated_at': '2023-06-02T11:57:14Z', 'author_association': 'MEMBER', 'body': "As already replied by @lhoestq (private channel):\r\n> `.train_test_split` (as well as `.shard`, `.select`) doesn't create a new arrow table to save time and disk space. Instead, it uses an indices mapping on top of the table that locate which examples are part of train or test.", 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1573616652/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1573984625', 'html_url': 'https://github.com/huggingface/datasets/issues/5922#issuecomment-1573984625', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5922', 'id': 1573984625, 'node_id': 'IC_kwDODunzps5d0Rlx', 'user': {'login': 'mariosasko', 'id': 47462742, 'node_id': 'MDQ6VXNlcjQ3NDYyNzQy', 'avatar_url': 'https://avatars.githubusercontent.com/u/47462742?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/mariosasko', 'html_url': 'https://github.com/mariosasko', 'followers_url': 'https://api.github.com/users/mariosasko/followers', 'following_url': 'https://api.github.com/users/mariosasko/following{/other_user}', 'gists_url': 'https://api.github.com/users/mariosasko/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/mariosasko/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/mariosasko/subscriptions', 'organizations_url': 'https://api.github.com/users/mariosasko/orgs', 'repos_url': 'https://api.github.com/users/mariosasko/repos', 'events_url': 'https://api.github.com/users/mariosasko/events{/privacy}', 'received_events_url': 'https://api.github.com/users/mariosasko/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-02T16:13:27Z', 'updated_at': '2023-06-02T16:13:27Z', 'author_association': 'CONTRIBUTOR', 'body': 'This is an optimization that we don\'t plan to "fix", so I\'m closing this issue.', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1573984625/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}]

[{'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1571952344', 'html_url': 'https://github.com/huggingface/datasets/pull/5920#issuecomment-1571952344', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5920', 'id': 1571952344, 'node_id': 'IC_kwDODunzps5dshbY', 'user': {'login': 'HuggingFaceDocBuilderDev', 'id': 99929124, 'node_id': 'U_kgDOBfTMJA', 'avatar_url': 'https://avatars.githubusercontent.com/u/99929124?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/HuggingFaceDocBuilderDev', 'html_url': 'https://github.com/HuggingFaceDocBuilderDev', 'followers_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/followers', 'following_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/following{/other_user}', 'gists_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/subscriptions', 'organizations_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/orgs', 'repos_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/repos', 'events_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/events{/privacy}', 'received_events_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-01T12:19:12Z', 'updated_at': '2023-06-01T12:38:38Z', 'author_association': 'NONE', 'body': '_The documentation is not available anymore as the PR was closed or merged._', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1571952344/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1571956089', 'html_url': 'https://github.com/huggingface/datasets/pull/5920#issuecomment-1571956089', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5920', 'id': 1571956089, 'node_id': 'IC_kwDODunzps5dsiV5', 'user': {'login': 'github-actions[bot]', 'id': 41898282, 'node_id': 'MDM6Qm90NDE4OTgyODI=', 'avatar_url': 'https://avatars.githubusercontent.com/in/15368?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/github-actions%5Bbot%5D', 'html_url': 'https://github.com/apps/github-actions', 'followers_url': 'https://api.github.com/users/github-actions%5Bbot%5D/followers', 'following_url': 'https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}', 'gists_url': 'https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/github-actions%5Bbot%5D/subscriptions', 'organizations_url': 'https://api.github.com/users/github-actions%5Bbot%5D/orgs', 'repos_url': 'https://api.github.com/users/github-actions%5Bbot%5D/repos', 'events_url': 'https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}', 'received_events_url': 'https://api.github.com/users/github-actions%5Bbot%5D/received_events', 'type': 'Bot', 'site_admin': False}, 'created_at': '2023-06-01T12:22:06Z', 'updated_at': '2023-06-01T12:22:06Z', 'author_association': 'NONE', 'body': '<details>\n<summary>Show benchmarks</summary>\n\nPyArrow==8.0.0\n\n<details>\n<summary>Show updated benchmarks!</summary>\n\n### Benchmark: benchmark_array_xd.json\n\n| metric | read_batch_formatted_as_numpy after write_array2d | read_batch_formatted_as_numpy after write_flattened_sequence | read_batch_formatted_as_numpy after write_nested_sequence | read_batch_unformated after write_array2d | read_batch_unformated after write_flattened_sequence | read_batch_unformated after write_nested_sequence | read_col_formatted_as_numpy after write_array2d | read_col_formatted_as_numpy after write_flattened_sequence | read_col_formatted_as_numpy after write_nested_sequence | read_col_unformated after write_array2d | read_col_unformated after write_flattened_sequence | read_col_unformated after write_nested_sequence | read_formatted_as_numpy after write_array2d | read_formatted_as_numpy after write_flattened_sequence | read_formatted_as_numpy after write_nested_sequence | read_unformated after write_array2d | read_unformated after write_flattened_sequence | read_unformated after write_nested_sequence | write_array2d | write_flattened_sequence | write_nested_sequence |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.007439 / 0.011353 (-0.003914) | 0.004884 / 0.011008 (-0.006124) | 0.098750 / 0.038508 (0.060242) | 0.040723 / 0.023109 (0.017613) | 0.347242 / 0.275898 (0.071344) | 0.381202 / 0.323480 (0.057722) | 0.006814 / 0.007986 (-0.001171) | 0.004543 / 0.004328 (0.000215) | 0.075338 / 0.004250 (0.071088) | 0.058976 / 0.037052 (0.021924) | 0.344746 / 0.258489 (0.086257) | 0.406761 / 0.293841 (0.112920) | 0.028961 / 0.128546 (-0.099585) | 0.009531 / 0.075646 (-0.066115) | 0.337324 / 0.419271 (-0.081947) | 0.051071 / 0.043533 (0.007538) | 0.341251 / 0.255139 (0.086112) | 0.362773 / 0.283200 (0.079573) | 0.109423 / 0.141683 (-0.032260) | 1.457420 / 1.452155 (0.005266) | 1.588824 / 1.492716 (0.096108) |\n\n### Benchmark: benchmark_getitem\\_100B.json\n\n| metric | get_batch_of\\_1024\\_random_rows | get_batch_of\\_1024\\_rows | get_first_row | get_last_row |\n|--------|---|---|---|---|\n| new / old (diff) | 0.288620 / 0.018006 (0.270614) | 0.568975 / 0.000490 (0.568485) | 0.003350 / 0.000200 (0.003150) | 0.000088 / 0.000054 (0.000034) |\n\n### Benchmark: benchmark_indices_mapping.json\n\n| metric | select | shard | shuffle | sort | train_test_split |\n|--------|---|---|---|---|---|\n| new / old (diff) | 0.028732 / 0.037411 (-0.008680) | 0.117820 / 0.014526 (0.103294) | 0.120180 / 0.176557 (-0.056376) | 0.178736 / 0.737135 (-0.558399) | 0.126399 / 0.296338 (-0.169939) |\n\n### Benchmark: benchmark_iterating.json\n\n| metric | read 5000 | read 50000 | read_batch 50000 10 | read_batch 50000 100 | read_batch 50000 1000 | read_formatted numpy 5000 | read_formatted pandas 5000 | read_formatted tensorflow 5000 | read_formatted torch 5000 | read_formatted_batch numpy 5000 10 | read_formatted_batch numpy 5000 1000 | shuffled read 5000 | shuffled read 50000 | shuffled read_batch 50000 10 | shuffled read_batch 50000 100 | shuffled read_batch 50000 1000 | shuffled read_formatted numpy 5000 | shuffled read_formatted_batch numpy 5000 10 | shuffled read_formatted_batch numpy 5000 1000 |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.428357 / 0.215209 (0.213148) | 4.251989 / 2.077655 (2.174334) | 2.005239 / 1.504120 (0.501119) | 1.784009 / 1.541195 (0.242815) | 1.883763 / 1.468490 (0.415272) | 0.555429 / 4.584777 (-4.029348) | 3.868146 / 3.745712 (0.122434) | 2.081896 / 5.269862 (-3.187965) | 1.126047 / 4.565676 (-3.439629) | 0.069496 / 0.424275 (-0.354779) | 0.012926 / 0.007607 (0.005318) | 0.536989 / 0.226044 (0.310944) | 5.256052 / 2.268929 (2.987124) | 2.526802 / 55.444624 (-52.917822) | 2.233346 / 6.876477 (-4.643131) | 2.389063 / 2.142072 (0.246990) | 0.677107 / 4.805227 (-4.128120) | 0.147212 / 6.500664 (-6.353452) | 0.067061 / 0.075469 (-0.008408) |\n\n### Benchmark: benchmark_map_filter.json\n\n| metric | filter | map fast-tokenizer batched | map identity | map identity batched | map no-op batched | map no-op batched numpy | map no-op batched pandas | map no-op batched pytorch | map no-op batched tensorflow |\n|--------|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 1.210651 / 1.841788 (-0.631137) | 17.236898 / 8.074308 (9.162589) | 14.427301 / 10.191392 (4.235909) | 0.207194 / 0.680424 (-0.473229) | 0.018079 / 0.534201 (-0.516122) | 0.398355 / 0.579283 (-0.180929) | 0.462453 / 0.434364 (0.028089) | 0.484544 / 0.540337 (-0.055794) | 0.590119 / 1.386936 (-0.796817) |\n\n</details>\nPyArrow==latest\n\n<details>\n<summary>Show updated benchmarks!</summary>\n\n### Benchmark: benchmark_array_xd.json\n\n| metric | read_batch_formatted_as_numpy after write_array2d | read_batch_formatted_as_numpy after write_flattened_sequence | read_batch_formatted_as_numpy after write_nested_sequence | read_batch_unformated after write_array2d | read_batch_unformated after write_flattened_sequence | read_batch_unformated after write_nested_sequence | read_col_formatted_as_numpy after write_array2d | read_col_formatted_as_numpy after write_flattened_sequence | read_col_formatted_as_numpy after write_nested_sequence | read_col_unformated after write_array2d | read_col_unformated after write_flattened_sequence | read_col_unformated after write_nested_sequence | read_formatted_as_numpy after write_array2d | read_formatted_as_numpy after write_flattened_sequence | read_formatted_as_numpy after write_nested_sequence | read_unformated after write_array2d | read_unformated after write_flattened_sequence | read_unformated after write_nested_sequence | write_array2d | write_flattened_sequence | write_nested_sequence |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.007392 / 0.011353 (-0.003961) | 0.005614 / 0.011008 (-0.005394) | 0.075587 / 0.038508 (0.037079) | 0.040429 / 0.023109 (0.017320) | 0.389901 / 0.275898 (0.114003) | 0.429466 / 0.323480 (0.105986) | 0.006790 / 0.007986 (-0.001196) | 0.006627 / 0.004328 (0.002299) | 0.075227 / 0.004250 (0.070976) | 0.060298 / 0.037052 (0.023246) | 0.391905 / 0.258489 (0.133416) | 0.449385 / 0.293841 (0.155544) | 0.028794 / 0.128546 (-0.099753) | 0.009461 / 0.075646 (-0.066185) | 0.083386 / 0.419271 (-0.335886) | 0.057968 / 0.043533 (0.014435) | 0.377327 / 0.255139 (0.122188) | 0.402825 / 0.283200 (0.119626) | 0.125477 / 0.141683 (-0.016206) | 1.462986 / 1.452155 (0.010832) | 1.595959 / 1.492716 (0.103243) |\n\n### Benchmark: benchmark_getitem\\_100B.json\n\n| metric | get_batch_of\\_1024\\_random_rows | get_batch_of\\_1024\\_rows | get_first_row | get_last_row |\n|--------|---|---|---|---|\n| new / old (diff) | 0.304179 / 0.018006 (0.286173) | 0.543113 / 0.000490 (0.542623) | 0.004136 / 0.000200 (0.003936) | 0.000109 / 0.000054 (0.000054) |\n\n### Benchmark: benchmark_indices_mapping.json\n\n| metric | select | shard | shuffle | sort | train_test_split |\n|--------|---|---|---|---|---|\n| new / old (diff) | 0.032617 / 0.037411 (-0.004794) | 0.123596 / 0.014526 (0.109070) | 0.128714 / 0.176557 (-0.047842) | 0.176344 / 0.737135 (-0.560792) | 0.132525 / 0.296338 (-0.163813) |\n\n### Benchmark: benchmark_iterating.json\n\n| metric | read 5000 | read 50000 | read_batch 50000 10 | read_batch 50000 100 | read_batch 50000 1000 | read_formatted numpy 5000 | read_formatted pandas 5000 | read_formatted tensorflow 5000 | read_formatted torch 5000 | read_formatted_batch numpy 5000 10 | read_formatted_batch numpy 5000 1000 | shuffled read 5000 | shuffled read 50000 | shuffled read_batch 50000 10 | shuffled read_batch 50000 100 | shuffled read_batch 50000 1000 | shuffled read_formatted numpy 5000 | shuffled read_formatted_batch numpy 5000 10 | shuffled read_formatted_batch numpy 5000 1000 |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.446041 / 0.215209 (0.230832) | 4.438799 / 2.077655 (2.361144) | 2.210815 / 1.504120 (0.706695) | 2.052025 / 1.541195 (0.510830) | 2.204687 / 1.468490 (0.736197) | 0.535219 / 4.584777 (-4.049558) | 3.858407 / 3.745712 (0.112695) | 3.826043 / 5.269862 (-1.443819) | 1.334149 / 4.565676 (-3.231527) | 0.067454 / 0.424275 (-0.356821) | 0.012566 / 0.007607 (0.004958) | 0.551597 / 0.226044 (0.325553) | 5.520054 / 2.268929 (3.251126) | 2.817976 / 55.444624 (-52.626649) | 2.528074 / 6.876477 (-4.348403) | 2.622391 / 2.142072 (0.480319) | 0.657632 / 4.805227 (-4.147595) | 0.147039 / 6.500664 (-6.353625) | 0.069603 / 0.075469 (-0.005866) |\n\n### Benchmark: benchmark_map_filter.json\n\n| metric | filter | map fast-tokenizer batched | map identity | map identity batched | map no-op batched | map no-op batched numpy | map no-op batched pandas | map no-op batched pytorch | map no-op batched tensorflow |\n|--------|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 1.300140 / 1.841788 (-0.541648) | 17.303907 / 8.074308 (9.229599) | 15.657887 / 10.191392 (5.466495) | 0.168991 / 0.680424 (-0.511433) | 0.021332 / 0.534201 (-0.512869) | 0.487261 / 0.579283 (-0.092022) | 0.450073 / 0.434364 (0.015709) | 0.465865 / 0.540337 (-0.074473) | 0.565501 / 1.386936 (-0.821435) |\n\n</details>\n</details>\n\n![](https://cml.dev/watermark.png#f1723ab75a6b3a5e156ea0a41651e80e91fa9cc6 "CML watermark")\n', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1571956089/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1571981818', 'html_url': 'https://github.com/huggingface/datasets/pull/5920#issuecomment-1571981818', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5920', 'id': 1571981818, 'node_id': 'IC_kwDODunzps5dson6', 'user': {'login': 'github-actions[bot]', 'id': 41898282, 'node_id': 'MDM6Qm90NDE4OTgyODI=', 'avatar_url': 'https://avatars.githubusercontent.com/in/15368?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/github-actions%5Bbot%5D', 'html_url': 'https://github.com/apps/github-actions', 'followers_url': 'https://api.github.com/users/github-actions%5Bbot%5D/followers', 'following_url': 'https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}', 'gists_url': 'https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/github-actions%5Bbot%5D/subscriptions', 'organizations_url': 'https://api.github.com/users/github-actions%5Bbot%5D/orgs', 'repos_url': 'https://api.github.com/users/github-actions%5Bbot%5D/repos', 'events_url': 'https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}', 'received_events_url': 'https://api.github.com/users/github-actions%5Bbot%5D/received_events', 'type': 'Bot', 'site_admin': False}, 'created_at': '2023-06-01T12:42:10Z', 'updated_at': '2023-06-01T12:42:10Z', 'author_association': 'NONE', 'body': '<details>\n<summary>Show benchmarks</summary>\n\nPyArrow==8.0.0\n\n<details>\n<summary>Show updated benchmarks!</summary>\n\n### Benchmark: benchmark_array_xd.json\n\n| metric | read_batch_formatted_as_numpy after write_array2d | read_batch_formatted_as_numpy after write_flattened_sequence | read_batch_formatted_as_numpy after write_nested_sequence | read_batch_unformated after write_array2d | read_batch_unformated after write_flattened_sequence | read_batch_unformated after write_nested_sequence | read_col_formatted_as_numpy after write_array2d | read_col_formatted_as_numpy after write_flattened_sequence | read_col_formatted_as_numpy after write_nested_sequence | read_col_unformated after write_array2d | read_col_unformated after write_flattened_sequence | read_col_unformated after write_nested_sequence | read_formatted_as_numpy after write_array2d | read_formatted_as_numpy after write_flattened_sequence | read_formatted_as_numpy after write_nested_sequence | read_unformated after write_array2d | read_unformated after write_flattened_sequence | read_unformated after write_nested_sequence | write_array2d | write_flattened_sequence | write_nested_sequence |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.006536 / 0.011353 (-0.004817) | 0.004254 / 0.011008 (-0.006755) | 0.095387 / 0.038508 (0.056878) | 0.032885 / 0.023109 (0.009776) | 0.298580 / 0.275898 (0.022682) | 0.319771 / 0.323480 (-0.003709) | 0.005510 / 0.007986 (-0.002476) | 0.003891 / 0.004328 (-0.000437) | 0.073763 / 0.004250 (0.069513) | 0.041625 / 0.037052 (0.004573) | 0.294896 / 0.258489 (0.036407) | 0.341308 / 0.293841 (0.047467) | 0.027898 / 0.128546 (-0.100648) | 0.008837 / 0.075646 (-0.066809) | 0.325055 / 0.419271 (-0.094216) | 0.050652 / 0.043533 (0.007119) | 0.298756 / 0.255139 (0.043617) | 0.318261 / 0.283200 (0.035061) | 0.098927 / 0.141683 (-0.042756) | 1.450356 / 1.452155 (-0.001798) | 1.508034 / 1.492716 (0.015318) |\n\n### Benchmark: benchmark_getitem\\_100B.json\n\n| metric | get_batch_of\\_1024\\_random_rows | get_batch_of\\_1024\\_rows | get_first_row | get_last_row |\n|--------|---|---|---|---|\n| new / old (diff) | 0.209009 / 0.018006 (0.191003) | 0.439154 / 0.000490 (0.438665) | 0.004299 / 0.000200 (0.004099) | 0.000142 / 0.000054 (0.000087) |\n\n### Benchmark: benchmark_indices_mapping.json\n\n| metric | select | shard | shuffle | sort | train_test_split |\n|--------|---|---|---|---|---|\n| new / old (diff) | 0.025938 / 0.037411 (-0.011473) | 0.105954 / 0.014526 (0.091429) | 0.113858 / 0.176557 (-0.062698) | 0.168887 / 0.737135 (-0.568249) | 0.121292 / 0.296338 (-0.175046) |\n\n### Benchmark: benchmark_iterating.json\n\n| metric | read 5000 | read 50000 | read_batch 50000 10 | read_batch 50000 100 | read_batch 50000 1000 | read_formatted numpy 5000 | read_formatted pandas 5000 | read_formatted tensorflow 5000 | read_formatted torch 5000 | read_formatted_batch numpy 5000 10 | read_formatted_batch numpy 5000 1000 | shuffled read 5000 | shuffled read 50000 | shuffled read_batch 50000 10 | shuffled read_batch 50000 100 | shuffled read_batch 50000 1000 | shuffled read_formatted numpy 5000 | shuffled read_formatted_batch numpy 5000 10 | shuffled read_formatted_batch numpy 5000 1000 |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.402050 / 0.215209 (0.186841) | 4.002310 / 2.077655 (1.924655) | 1.816190 / 1.504120 (0.312070) | 1.634404 / 1.541195 (0.093209) | 1.713632 / 1.468490 (0.245142) | 0.519633 / 4.584777 (-4.065144) | 3.740291 / 3.745712 (-0.005421) | 1.787602 / 5.269862 (-3.482260) | 1.038844 / 4.565676 (-3.526833) | 0.064973 / 0.424275 (-0.359302) | 0.012475 / 0.007607 (0.004868) | 0.498152 / 0.226044 (0.272108) | 4.970941 / 2.268929 (2.702013) | 2.287429 / 55.444624 (-53.157195) | 1.998050 / 6.876477 (-4.878427) | 2.091903 / 2.142072 (-0.050169) | 0.630363 / 4.805227 (-4.174864) | 0.138623 / 6.500664 (-6.362041) | 0.063293 / 0.075469 (-0.012176) |\n\n### Benchmark: benchmark_map_filter.json\n\n| metric | filter | map fast-tokenizer batched | map identity | map identity batched | map no-op batched | map no-op batched numpy | map no-op batched pandas | map no-op batched pytorch | map no-op batched tensorflow |\n|--------|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 1.201802 / 1.841788 (-0.639986) | 14.073836 / 8.074308 (5.999528) | 12.968665 / 10.191392 (2.777273) | 0.144653 / 0.680424 (-0.535771) | 0.017613 / 0.534201 (-0.516588) | 0.392067 / 0.579283 (-0.187216) | 0.416955 / 0.434364 (-0.017409) | 0.471492 / 0.540337 (-0.068845) | 0.554576 / 1.386936 (-0.832360) |\n\n</details>\nPyArrow==latest\n\n<details>\n<summary>Show updated benchmarks!</summary>\n\n### Benchmark: benchmark_array_xd.json\n\n| metric | read_batch_formatted_as_numpy after write_array2d | read_batch_formatted_as_numpy after write_flattened_sequence | read_batch_formatted_as_numpy after write_nested_sequence | read_batch_unformated after write_array2d | read_batch_unformated after write_flattened_sequence | read_batch_unformated after write_nested_sequence | read_col_formatted_as_numpy after write_array2d | read_col_formatted_as_numpy after write_flattened_sequence | read_col_formatted_as_numpy after write_nested_

[{'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1585812835', 'html_url': 'https://github.com/huggingface/datasets/pull/5919#issuecomment-1585812835', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5919', 'id': 1585812835, 'node_id': 'IC_kwDODunzps5ehZVj', 'user': {'login': 'janineguo', 'id': 59083384, 'node_id': 'MDQ6VXNlcjU5MDgzMzg0', 'avatar_url': 'https://avatars.githubusercontent.com/u/59083384?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/janineguo', 'html_url': 'https://github.com/janineguo', 'followers_url': 'https://api.github.com/users/janineguo/followers', 'following_url': 'https://api.github.com/users/janineguo/following{/other_user}', 'gists_url': 'https://api.github.com/users/janineguo/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/janineguo/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/janineguo/subscriptions', 'organizations_url': 'https://api.github.com/users/janineguo/orgs', 'repos_url': 'https://api.github.com/users/janineguo/repos', 'events_url': 'https://api.github.com/users/janineguo/events{/privacy}', 'received_events_url': 'https://api.github.com/users/janineguo/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-10T20:45:33Z', 'updated_at': '2023-06-10T20:46:15Z', 'author_association': 'NONE', 'body': "hi @lhoestq,\r\nI saw some errors in my test and found all the failed reasons are `FileNotFoundError`  about `test_load_streaming_private_dataset_with_zipped_data` and `test_load_dataset_private_zipped_images` in `test_load.py `, I run pytest on my own Wins and Ubuntu system all the test in `test_load.py ` are succeed. could you help me to check the test environment of our server?\r\n\r\n`2023-06-08T16:50:48.0828281Z FAILED tests/test_load.py::test_load_streaming_private_dataset_with_zipped_data - FileNotFoundError: Couldn't find a dataset script at D:\\a\\datasets\\datasets\\__DUMMY_TRANSFORMERS_USER__\\repo_zipped_txt_data-16862429577813\\repo_zipped_txt_data-16862429577813.py or any data file in the same directory. Couldn't find '__DUMMY_TRANSFORMERS_USER__/repo_zipped_txt_data-16862429577813' on the Hugging Face Hub either: FileNotFoundError: No (supported) data files or dataset script found in __DUMMY_TRANSFORMERS_USER__/repo_zipped_txt_data-16862429577813`\r\n`2023-06-08T16:50:48.0830602Z FAILED tests/test_load.py::test_load_dataset_private_zipped_images[False-False] - FileNotFoundError: Couldn't find a dataset script at D:\\a\\datasets\\datasets\\__DUMMY_TRANSFORMERS_USER__\\repo_zipped_img_data-16862429594168\\repo_zipped_img_data-16862429594168.py or any data file in the same directory. Couldn't find '__DUMMY_TRANSFORMERS_USER__/repo_zipped_img_data-16862429594168' on the Hugging Face Hub either: FileNotFoundError: No (supported) data files or dataset script found in __DUMMY_TRANSFORMERS_USER__/repo_zipped_img_data-16862429594168`", 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1585812835/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1589081453', 'html_url': 'https://github.com/huggingface/datasets/pull/5919#issuecomment-1589081453', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5919', 'id': 1589081453, 'node_id': 'IC_kwDODunzps5et3Vt', 'user': {'login': 'lhoestq', 'id': 42851186, 'node_id': 'MDQ6VXNlcjQyODUxMTg2', 'avatar_url': 'https://avatars.githubusercontent.com/u/42851186?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/lhoestq', 'html_url': 'https://github.com/lhoestq', 'followers_url': 'https://api.github.com/users/lhoestq/followers', 'following_url': 'https://api.github.com/users/lhoestq/following{/other_user}', 'gists_url': 'https://api.github.com/users/lhoestq/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/lhoestq/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/lhoestq/subscriptions', 'organizations_url': 'https://api.github.com/users/lhoestq/orgs', 'repos_url': 'https://api.github.com/users/lhoestq/repos', 'events_url': 'https://api.github.com/users/lhoestq/events{/privacy}', 'received_events_url': 'https://api.github.com/users/lhoestq/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-13T11:07:47Z', 'updated_at': '2023-06-13T11:07:47Z', 'author_association': 'MEMBER', 'body': "I just re-ran the CI, hopefully it's fixed", 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1589081453/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1589090107', 'html_url': 'https://github.com/huggingface/datasets/pull/5919#issuecomment-1589090107', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5919', 'id': 1589090107, 'node_id': 'IC_kwDODunzps5et5c7', 'user': {'login': 'HuggingFaceDocBuilderDev', 'id': 99929124, 'node_id': 'U_kgDOBfTMJA', 'avatar_url': 'https://avatars.githubusercontent.com/u/99929124?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/HuggingFaceDocBuilderDev', 'html_url': 'https://github.com/HuggingFaceDocBuilderDev', 'followers_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/followers', 'following_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/following{/other_user}', 'gists_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/subscriptions', 'organizations_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/orgs', 'repos_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/repos', 'events_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/events{/privacy}', 'received_events_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-13T11:13:52Z', 'updated_at': '2023-07-10T09:52:59Z', 'author_association': 'NONE', 'body': '_The documentation is not available anymore as the PR was closed or merged._', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1589090107/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1589257967', 'html_url': 'https://github.com/huggingface/datasets/pull/5919#issuecomment-1589257967', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5919', 'id': 1589257967, 'node_id': 'IC_kwDODunzps5euibv', 'user': {'login': 'janineguo', 'id': 59083384, 'node_id': 'MDQ6VXNlcjU5MDgzMzg0', 'avatar_url': 'https://avatars.githubusercontent.com/u/59083384?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/janineguo', 'html_url': 'https://github.com/janineguo', 'followers_url': 'https://api.github.com/users/janineguo/followers', 'following_url': 'https://api.github.com/users/janineguo/following{/other_user}', 'gists_url': 'https://api.github.com/users/janineguo/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/janineguo/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/janineguo/subscriptions', 'organizations_url': 'https://api.github.com/users/janineguo/orgs', 'repos_url': 'https://api.github.com/users/janineguo/repos', 'events_url': 'https://api.github.com/users/janineguo/events{/privacy}', 'received_events_url': 'https://api.github.com/users/janineguo/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-13T12:55:07Z', 'updated_at': '2023-06-13T12:55:07Z', 'author_association': 'NONE', 'body': "> I just re-ran the CI, hopefully it's fixed\r\n\r\nI just checked, still has the same error, maybe need someone to fix it", 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1589257967/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1589562037', 'html_url': 'https://github.com/huggingface/datasets/pull/5919#issuecomment-1589562037', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5919', 'id': 1589562037, 'node_id': 'IC_kwDODunzps5evsq1', 'user': {'login': 'lhoestq', 'id': 42851186, 'node_id': 'MDQ6VXNlcjQyODUxMTg2', 'avatar_url': 'https://avatars.githubusercontent.com/u/42851186?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/lhoestq', 'html_url': 'https://github.com/lhoestq', 'followers_url': 'https://api.github.com/users/lhoestq/followers', 'following_url': 'https://api.github.com/users/lhoestq/following{/other_user}', 'gists_url': 'https://api.github.com/users/lhoestq/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/lhoestq/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/lhoestq/subscriptions', 'organizations_url': 'https://api.github.com/users/lhoestq/orgs', 'repos_url': 'https://api.github.com/users/lhoestq/repos', 'events_url': 'https://api.github.com/users/lhoestq/events{/privacy}', 'received_events_url': 'https://api.github.com/users/lhoestq/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-13T15:38:23Z', 'updated_at': '2023-06-13T16:11:49Z', 'author_association': 'MEMBER', 'body': "I think the issue comes from this PR somehow, since the CI fail is related to loading private repositories and this PR touches authentication related code. Let me check what's the issue, and I'll also review your PR later (sorry I don't have a ton of bandwidth atm)", 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1589562037/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1628625808', 'html_url': 'https://github.com/huggingface/datasets/pull/5919#issuecomment-1628625808', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5919', 'id': 1628625808, 'node_id': 'IC_kwDODunzps5hEtuQ', 'user': {'login': 'HuggingFaceDocBuilderDev', 'id': 99929124, 'node_id': 'U_kgDOBfTMJA', 'avatar_url': 'https://avatars.githubusercontent.com/u/99929124?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/HuggingFaceDocBuilderDev', 'html_url': 'https://github.com/HuggingFaceDocBuilderDev', 'followers_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/followers', 'following_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/following{/other_user}', 'gists_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/subscriptions', 'organizations_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/orgs', 'repos_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/repos', 'events_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/events{/privacy}', 'received_events_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-07-10T09:58:06Z', 'updated_at': '2023-07-10T09:58:06Z', 'author_association': 'NONE', 'body': 'The docs for this PR live [here](https://moon-ci-docs.huggingface.co/docs/datasets/pr_5919). All of your documentation changes will be reflected on that endpoint.', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1628625808/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1630384751', 'html_url': 'https://github.com/huggingface/datasets/pull/5919#issuecomment-1630384751', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5919', 'id': 1630384751, 'node_id': 'IC_kwDODunzps5hLbJv', 'user': {'login': 'janineguo', 'id': 59083384, 'node_id': 'MDQ6VXNlcjU5MDgzMzg0', 'avatar_url': 'https://avatars.githubusercontent.com/u/59083384?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/janineguo', 'html_url': 'https://github.com/janineguo', 'followers_url': 'https://api.github.com/users/janineguo/followers', 'following_url': 'https://api.github.com/users/janineguo/following{/other_user}', 'gists_url': 'https://api.github.com/users/janineguo/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/janineguo/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/janineguo/subscriptions', 'organizations_url': 'https://api.github.com/users/janineguo/orgs', 'repos_url': 'https://api.github.com/users/janineguo/repos', 'events_url': 'https://api.github.com/users/janineguo/events{/privacy}', 'received_events_url': 'https://api.github.com/users/janineguo/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-07-11T08:29:47Z', 'updated_at': '2023-07-11T08:30:04Z', 'author_association': 'NONE', 'body': "@lhoestq Hi sorry to bother you, the CI check_code_quality failed and it said `would reformat /home/runner/work/datasets/datasets/src/datasets/download/streaming_download_manager.py` but I cant see any changes when I run `python3 -m black --check tests src benchmarks metrics` and `python3 -m ruff tests src benchmarks metrics` on my own computer, is there any version requirements on the tools? I didn't specific the version.", 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1630384751/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1630835614', 'html_url': 'https://github.com/huggingface/datasets/pull/5919#issuecomment-1630835614', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5919', 'id': 1630835614, 'node_id': 'IC_kwDODunzps5hNJOe', 'user': {'login': 'lhoestq', 'id': 42851186, 'node_id': 'MDQ6VXNlcjQyODUxMTg2', 'avatar_url': 'https://avatars.githubusercontent.com/u/42851186?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/lhoestq', 'html_url': 'https://github.com/lhoestq', 'followers_url': 'https://api.github.com/users/lhoestq/followers', 'following_url': 'https://api.github.com/users/lhoestq/following{/other_user}', 'gists_url': 'https://api.github.com/users/lhoestq/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/lhoestq/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/lhoestq/subscriptions', 'organizations_url': 'https://api.github.com/users/lhoestq/orgs', 'repos_url': 'https://api.github.com/users/lhoestq/repos', 'events_url': 'https://api.github.com/users/lhoestq/events{/privacy}', 'received_events_url': 'https://api.github.com/users/lhoestq/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-07-11T13:28:20Z', 'updated_at': '2023-07-11T13:28:20Z', 'author_association': 'MEMBER', 'body': 'I just ran `make style` and pushed the changes.\r\nYou can install the right versions of black and ruff using `pip install -e .[quality]` ;)', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1630835614/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1632274377', 'html_url': 'https://github.com/huggingface/datasets/pull/5919#issuecomment-1632274377', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5919', 'id': 1632274377, 'node_id': 'IC_kwDODunzps5hSofJ', 'user': {'login': 'lhoestq', 'id': 42851186, 'node_id': 'MDQ6VXNlcjQyODUxMTg2', 'avatar_url': 'https://avatars.githubusercontent.com/u/42851186?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/lhoestq', 'html_url': 'https://github.com/lhoestq', 'followers_url': 'https://api.github.com/users/lhoestq/followers', 'following_url': 'https://api.github.com/users/lhoestq/following{/other_user}', 'gists_url': 'https://api.github.com/users/lhoestq/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/lhoestq/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/lhoestq/subscriptions', 'organizations_url': 'https://api.github.com/users/lhoestq/orgs', 'repos_url': 'https://api.github.com/users/lhoestq/repos', 'events_url': 'https://api.github.com/users/lhoestq/events{/privacy}', 'received_events_url': 'https://api.github.com/users/lhoestq/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-07-12T10:45:30Z', 'updated_at': '2023-07-12T10:45:30Z', 'author_association': 'MEMBER', 'body': 'I am working on this issue right now https://github.com/huggingface/datasets/issues/6017 which is strongly connected to your PR, and I might end up cherry-picking some of your commits (keeping attribution of course !). Would you be ok with that ?', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1632274377/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1633586236', 'html_url': 'https://github.com/huggingface/datasets/pull/5919#issuecomment-1633586236', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5919', 'id': 1633586236, 'node_id': 'IC_kwDODunzps5hXow8', 'user': {'login': 'janineguo', 'id': 59083384, 'node_id': 'MDQ6VXNlcjU5MDgzMzg0', 'avatar_url': 'https://avatars.githubusercontent.com/u/59083384?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/janineguo', 'html_url': 'https://github.com/janineguo', 'followers_url': 'https://api.github.com/users/janineguo/followers', 'following_url': 'https://api.github.com/users/janineguo/following{/other_user}', 'gists_url': 'https://api.github.com/users/janineguo/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/janineguo/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/janineguo/subscriptions', 'organizations_url': 'https://api.github.com/users/janineguo/orgs', 'repos_url': 'https://api.github.com/users/janineguo/repos', 'events_url': 'https://api.github.com/users/janineguo/events{/privacy}', 'received_events_url': 'https://api.github.com/users/janineguo/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-07-13T05:43:17Z', 'updated_at': '2023-07-13T05:43:17Z', 'author_association': 'NONE', 'body': "it's totally ok for me, I just wish the S3 File system could support streaming too.\r\n", 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1633586236/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1633593763', 'html_url': 'https://github.com/huggingface/

[{'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1586031911', 'html_url': 'https://github.com/huggingface/datasets/issues/5918#issuecomment-1586031911', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5918', 'id': 1586031911, 'node_id': 'IC_kwDODunzps5eiO0n', 'user': {'login': 'flckv', 'id': 103381497, 'node_id': 'U_kgDOBil5-Q', 'avatar_url': 'https://avatars.githubusercontent.com/u/103381497?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/flckv', 'html_url': 'https://github.com/flckv', 'followers_url': 'https://api.github.com/users/flckv/followers', 'following_url': 'https://api.github.com/users/flckv/following{/other_user}', 'gists_url': 'https://api.github.com/users/flckv/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/flckv/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/flckv/subscriptions', 'organizations_url': 'https://api.github.com/users/flckv/orgs', 'repos_url': 'https://api.github.com/users/flckv/repos', 'events_url': 'https://api.github.com/users/flckv/events{/privacy}', 'received_events_url': 'https://api.github.com/users/flckv/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-11T06:02:24Z', 'updated_at': '2023-06-11T06:02:24Z', 'author_association': 'NONE', 'body': 'load_dataset () did not work for loading local files either ', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1586031911/reactions', 'total_count': 1, '+1': 1, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}]
[{'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1569748422', 'html_url': 'https://github.com/huggingface/datasets/pull/5917#issuecomment-1569748422', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5917', 'id': 1569748422, 'node_id': 'IC_kwDODunzps5dkHXG', 'user': {'login': 'HuggingFaceDocBuilderDev', 'id': 99929124, 'node_id': 'U_kgDOBfTMJA', 'avatar_url': 'https://avatars.githubusercontent.com/u/99929124?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/HuggingFaceDocBuilderDev', 'html_url': 'https://github.com/HuggingFaceDocBuilderDev', 'followers_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/followers', 'following_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/following{/other_user}', 'gists_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/subscriptions', 'organizations_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/orgs', 'repos_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/repos', 'events_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/events{/privacy}', 'received_events_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-05-31T08:37:50Z', 'updated_at': '2023-05-31T13:29:20Z', 'author_association': 'NONE', 'body': '_The documentation is not available anymore as the PR was closed or merged._', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1569748422/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1570249315', 'html_url': 'https://github.com/huggingface/datasets/pull/5917#issuecomment-1570249315', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5917', 'id': 1570249315, 'node_id': 'IC_kwDODunzps5dmBpj', 'user': {'login': 'github-actions[bot]', 'id': 41898282, 'node_id': 'MDM6Qm90NDE4OTgyODI=', 'avatar_url': 'https://avatars.githubusercontent.com/in/15368?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/github-actions%5Bbot%5D', 'html_url': 'https://github.com/apps/github-actions', 'followers_url': 'https://api.github.com/users/github-actions%5Bbot%5D/followers', 'following_url': 'https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}', 'gists_url': 'https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/github-actions%5Bbot%5D/subscriptions', 'organizations_url': 'https://api.github.com/users/github-actions%5Bbot%5D/orgs', 'repos_url': 'https://api.github.com/users/github-actions%5Bbot%5D/repos', 'events_url': 'https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}', 'received_events_url': 'https://api.github.com/users/github-actions%5Bbot%5D/received_events', 'type': 'Bot', 'site_admin': False}, 'created_at': '2023-05-31T13:34:35Z', 'updated_at': '2023-05-31T13:34:35Z', 'author_association': 'NONE', 'body': '<details>\n<summary>Show benchmarks</summary>\n\nPyArrow==8.0.0\n\n<details>\n<summary>Show updated benchmarks!</summary>\n\n### Benchmark: benchmark_array_xd.json\n\n| metric | read_batch_formatted_as_numpy after write_array2d | read_batch_formatted_as_numpy after write_flattened_sequence | read_batch_formatted_as_numpy after write_nested_sequence | read_batch_unformated after write_array2d | read_batch_unformated after write_flattened_sequence | read_batch_unformated after write_nested_sequence | read_col_formatted_as_numpy after write_array2d | read_col_formatted_as_numpy after write_flattened_sequence | read_col_formatted_as_numpy after write_nested_sequence | read_col_unformated after write_array2d | read_col_unformated after write_flattened_sequence | read_col_unformated after write_nested_sequence | read_formatted_as_numpy after write_array2d | read_formatted_as_numpy after write_flattened_sequence | read_formatted_as_numpy after write_nested_sequence | read_unformated after write_array2d | read_unformated after write_flattened_sequence | read_unformated after write_nested_sequence | write_array2d | write_flattened_sequence | write_nested_sequence |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.008358 / 0.011353 (-0.002995) | 0.005673 / 0.011008 (-0.005335) | 0.124034 / 0.038508 (0.085526) | 0.037550 / 0.023109 (0.014441) | 0.331301 / 0.275898 (0.055403) | 0.383542 / 0.323480 (0.060062) | 0.006940 / 0.007986 (-0.001046) | 0.005959 / 0.004328 (0.001631) | 0.084670 / 0.004250 (0.080419) | 0.054214 / 0.037052 (0.017162) | 0.359897 / 0.258489 (0.101408) | 0.383260 / 0.293841 (0.089419) | 0.047642 / 0.128546 (-0.080904) | 0.013902 / 0.075646 (-0.061744) | 0.380232 / 0.419271 (-0.039040) | 0.077790 / 0.043533 (0.034257) | 0.376648 / 0.255139 (0.121509) | 0.387536 / 0.283200 (0.104336) | 0.104644 / 0.141683 (-0.037038) | 1.618560 / 1.452155 (0.166406) | 1.742569 / 1.492716 (0.249853) |\n\n### Benchmark: benchmark_getitem\\_100B.json\n\n| metric | get_batch_of\\_1024\\_random_rows | get_batch_of\\_1024\\_rows | get_first_row | get_last_row |\n|--------|---|---|---|---|\n| new / old (diff) | 0.257218 / 0.018006 (0.239212) | 0.636801 / 0.000490 (0.636311) | 0.000634 / 0.000200 (0.000434) | 0.000101 / 0.000054 (0.000047) |\n\n### Benchmark: benchmark_indices_mapping.json\n\n| metric | select | shard | shuffle | sort | train_test_split |\n|--------|---|---|---|---|---|\n| new / old (diff) | 0.037874 / 0.037411 (0.000462) | 0.107454 / 0.014526 (0.092928) | 0.117855 / 0.176557 (-0.058702) | 0.204067 / 0.737135 (-0.533068) | 0.134029 / 0.296338 (-0.162310) |\n\n### Benchmark: benchmark_iterating.json\n\n| metric | read 5000 | read 50000 | read_batch 50000 10 | read_batch 50000 100 | read_batch 50000 1000 | read_formatted numpy 5000 | read_formatted pandas 5000 | read_formatted tensorflow 5000 | read_formatted torch 5000 | read_formatted_batch numpy 5000 10 | read_formatted_batch numpy 5000 1000 | shuffled read 5000 | shuffled read 50000 | shuffled read_batch 50000 10 | shuffled read_batch 50000 100 | shuffled read_batch 50000 1000 | shuffled read_formatted numpy 5000 | shuffled read_formatted_batch numpy 5000 10 | shuffled read_formatted_batch numpy 5000 1000 |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.583657 / 0.215209 (0.368447) | 5.761289 / 2.077655 (3.683635) | 2.280201 / 1.504120 (0.776081) | 2.033442 / 1.541195 (0.492247) | 2.035343 / 1.468490 (0.566853) | 0.868122 / 4.584777 (-3.716655) | 5.352591 / 3.745712 (1.606879) | 2.432814 / 5.269862 (-2.837047) | 1.560765 / 4.565676 (-3.004911) | 0.098793 / 0.424275 (-0.325482) | 0.017327 / 0.007607 (0.009720) | 0.734676 / 0.226044 (0.508631) | 7.070318 / 2.268929 (4.801390) | 2.972701 / 55.444624 (-52.471924) | 2.442189 / 6.876477 (-4.434288) | 2.604379 / 2.142072 (0.462307) | 1.028853 / 4.805227 (-3.776374) | 0.210390 / 6.500664 (-6.290274) | 0.069329 / 0.075469 (-0.006140) |\n\n### Benchmark: benchmark_map_filter.json\n\n| metric | filter | map fast-tokenizer batched | map identity | map identity batched | map no-op batched | map no-op batched numpy | map no-op batched pandas | map no-op batched pytorch | map no-op batched tensorflow |\n|--------|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 1.469586 / 1.841788 (-0.372202) | 16.570305 / 8.074308 (8.495997) | 19.187845 / 10.191392 (8.996453) | 0.219162 / 0.680424 (-0.461262) | 0.026356 / 0.534201 (-0.507845) | 0.447370 / 0.579283 (-0.131913) | 0.555893 / 0.434364 (0.121529) | 0.574958 / 0.540337 (0.034621) | 0.639166 / 1.386936 (-0.747770) |\n\n</details>\nPyArrow==latest\n\n<details>\n<summary>Show updated benchmarks!</summary>\n\n### Benchmark: benchmark_array_xd.json\n\n| metric | read_batch_formatted_as_numpy after write_array2d | read_batch_formatted_as_numpy after write_flattened_sequence | read_batch_formatted_as_numpy after write_nested_sequence | read_batch_unformated after write_array2d | read_batch_unformated after write_flattened_sequence | read_batch_unformated after write_nested_sequence | read_col_formatted_as_numpy after write_array2d | read_col_formatted_as_numpy after write_flattened_sequence | read_col_formatted_as_numpy after write_nested_sequence | read_col_unformated after write_array2d | read_col_unformated after write_flattened_sequence | read_col_unformated after write_nested_sequence | read_formatted_as_numpy after write_array2d | read_formatted_as_numpy after write_flattened_sequence | read_formatted_as_numpy after write_nested_sequence | read_unformated after write_array2d | read_unformated after write_flattened_sequence | read_unformated after write_nested_sequence | write_array2d | write_flattened_sequence | write_nested_sequence |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.008166 / 0.011353 (-0.003187) | 0.005577 / 0.011008 (-0.005431) | 0.103578 / 0.038508 (0.065070) | 0.040563 / 0.023109 (0.017454) | 0.441996 / 0.275898 (0.166098) | 0.483594 / 0.323480 (0.160114) | 0.007329 / 0.007986 (-0.000657) | 0.004546 / 0.004328 (0.000218) | 0.090471 / 0.004250 (0.086220) | 0.052740 / 0.037052 (0.015688) | 0.442197 / 0.258489 (0.183708) | 0.524310 / 0.293841 (0.230469) | 0.042487 / 0.128546 (-0.086060) | 0.012917 / 0.075646 (-0.062730) | 0.103992 / 0.419271 (-0.315280) | 0.060570 / 0.043533 (0.017037) | 0.441956 / 0.255139 (0.186817) | 0.477084 / 0.283200 (0.193885) | 0.103815 / 0.141683 (-0.037868) | 1.696963 / 1.452155 (0.244809) | 1.747849 / 1.492716 (0.255132) |\n\n### Benchmark: benchmark_getitem\\_100B.json\n\n| metric | get_batch_of\\_1024\\_random_rows | get_batch_of\\_1024\\_rows | get_first_row | get_last_row |\n|--------|---|---|---|---|\n| new / old (diff) | 0.292465 / 0.018006 (0.274458) | 0.571518 / 0.000490 (0.571028) | 0.000476 / 0.000200 (0.000276) | 0.000077 / 0.000054 (0.000022) |\n\n### Benchmark: benchmark_indices_mapping.json\n\n| metric | select | shard | shuffle | sort | train_test_split |\n|--------|---|---|---|---|---|\n| new / old (diff) | 0.028697 / 0.037411 (-0.008714) | 0.111671 / 0.014526 (0.097145) | 0.138826 / 0.176557 (-0.037731) | 0.189697 / 0.737135 (-0.547439) | 0.125454 / 0.296338 (-0.170884) |\n\n### Benchmark: benchmark_iterating.json\n\n| metric | read 5000 | read 50000 | read_batch 50000 10 | read_batch 50000 100 | read_batch 50000 1000 | read_formatted numpy 5000 | read_formatted pandas 5000 | read_formatted tensorflow 5000 | read_formatted torch 5000 | read_formatted_batch numpy 5000 10 | read_formatted_batch numpy 5000 1000 | shuffled read 5000 | shuffled read 50000 | shuffled read_batch 50000 10 | shuffled read_batch 50000 100 | shuffled read_batch 50000 1000 | shuffled read_formatted numpy 5000 | shuffled read_formatted_batch numpy 5000 10 | shuffled read_formatted_batch numpy 5000 1000 |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.619273 / 0.215209 (0.404064) | 6.138669 / 2.077655 (4.061015) | 2.558622 / 1.504120 (1.054502) | 2.201550 / 1.541195 (0.660356) | 2.279034 / 1.468490 (0.810544) | 0.850752 / 4.584777 (-3.734025) | 5.438185 / 3.745712 (1.692473) | 2.529343 / 5.269862 (-2.740518) | 1.572178 / 4.565676 (-2.993499) | 0.100768 / 0.424275 (-0.323507) | 0.013902 / 0.007607 (0.006295) | 0.726660 / 0.226044 (0.500616) | 7.794918 / 2.268929 (5.525990) | 3.311695 / 55.444624 (-52.132930) | 2.729167 / 6.876477 (-4.147310) | 2.630984 / 2.142072 (0.488911) | 1.018534 / 4.805227 (-3.786693) | 0.194602 / 6.500664 (-6.306062) | 0.070876 / 0.075469 (-0.004593) |\n\n### Benchmark: benchmark_map_filter.json\n\n| metric | filter | map fast-tokenizer batched | map identity | map identity batched | map no-op batched | map no-op batched numpy | map no-op batched pandas | map no-op batched pytorch | map no-op batched tensorflow |\n|--------|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 1.573005 / 1.841788 (-0.268783) | 17.042710 / 8.074308 (8.968401) | 19.615320 / 10.191392 (9.423928) | 0.229405 / 0.680424 (-0.451019) | 0.027560 / 0.534201 (-0.506641) | 0.447984 / 0.579283 (-0.131299) | 0.598392 / 0.434364 (0.164028) | 0.571769 / 0.540337 (0.031431) | 0.653025 / 1.386936 (-0.733911) |\n\n</details>\n</details>\n\n![](https://cml.dev/watermark.png#9dca2ff89a8589595313e9535d16597ce10e3700 "CML watermark")\n', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1570249315/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}]

[{'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1568604401', 'html_url': 'https://github.com/huggingface/datasets/pull/5916#issuecomment-1568604401', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5916', 'id': 1568604401, 'node_id': 'IC_kwDODunzps5dfwDx', 'user': {'login': 'HuggingFaceDocBuilderDev', 'id': 99929124, 'node_id': 'U_kgDOBfTMJA', 'avatar_url': 'https://avatars.githubusercontent.com/u/99929124?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/HuggingFaceDocBuilderDev', 'html_url': 'https://github.com/HuggingFaceDocBuilderDev', 'followers_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/followers', 'following_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/following{/other_user}', 'gists_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/subscriptions', 'organizations_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/orgs', 'repos_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/repos', 'events_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/events{/privacy}', 'received_events_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-05-30T15:04:26Z', 'updated_at': '2023-05-30T17:57:17Z', 'author_association': 'NONE', 'body': '_The documentation is not available anymore as the PR was closed or merged._', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1568604401/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1568606764', 'html_url': 'https://github.com/huggingface/datasets/pull/5916#issuecomment-1568606764', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5916', 'id': 1568606764, 'node_id': 'IC_kwDODunzps5dfwos', 'user': {'login': 'github-actions[bot]', 'id': 41898282, 'node_id': 'MDM6Qm90NDE4OTgyODI=', 'avatar_url': 'https://avatars.githubusercontent.com/in/15368?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/github-actions%5Bbot%5D', 'html_url': 'https://github.com/apps/github-actions', 'followers_url': 'https://api.github.com/users/github-actions%5Bbot%5D/followers', 'following_url': 'https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}', 'gists_url': 'https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/github-actions%5Bbot%5D/subscriptions', 'organizations_url': 'https://api.github.com/users/github-actions%5Bbot%5D/orgs', 'repos_url': 'https://api.github.com/users/github-actions%5Bbot%5D/repos', 'events_url': 'https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}', 'received_events_url': 'https://api.github.com/users/github-actions%5Bbot%5D/received_events', 'type': 'Bot', 'site_admin': False}, 'created_at': '2023-05-30T15:05:47Z', 'updated_at': '2023-05-30T15:05:47Z', 'author_association': 'NONE', 'body': '<details>\n<summary>Show benchmarks</summary>\n\nPyArrow==8.0.0\n\n<details>\n<summary>Show updated benchmarks!</summary>\n\n### Benchmark: benchmark_array_xd.json\n\n| metric | read_batch_formatted_as_numpy after write_array2d | read_batch_formatted_as_numpy after write_flattened_sequence | read_batch_formatted_as_numpy after write_nested_sequence | read_batch_unformated after write_array2d | read_batch_unformated after write_flattened_sequence | read_batch_unformated after write_nested_sequence | read_col_formatted_as_numpy after write_array2d | read_col_formatted_as_numpy after write_flattened_sequence | read_col_formatted_as_numpy after write_nested_sequence | read_col_unformated after write_array2d | read_col_unformated after write_flattened_sequence | read_col_unformated after write_nested_sequence | read_formatted_as_numpy after write_array2d | read_formatted_as_numpy after write_flattened_sequence | read_formatted_as_numpy after write_nested_sequence | read_unformated after write_array2d | read_unformated after write_flattened_sequence | read_unformated after write_nested_sequence | write_array2d | write_flattened_sequence | write_nested_sequence |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.006113 / 0.011353 (-0.005239) | 0.004195 / 0.011008 (-0.006813) | 0.098103 / 0.038508 (0.059595) | 0.027970 / 0.023109 (0.004860) | 0.300992 / 0.275898 (0.025094) | 0.335402 / 0.323480 (0.011922) | 0.005079 / 0.007986 (-0.002906) | 0.003516 / 0.004328 (-0.000813) | 0.077311 / 0.004250 (0.073061) | 0.037863 / 0.037052 (0.000810) | 0.302638 / 0.258489 (0.044149) | 0.346554 / 0.293841 (0.052713) | 0.025218 / 0.128546 (-0.103328) | 0.008630 / 0.075646 (-0.067017) | 0.319748 / 0.419271 (-0.099523) | 0.049182 / 0.043533 (0.005650) | 0.306233 / 0.255139 (0.051094) | 0.331040 / 0.283200 (0.047840) | 0.089203 / 0.141683 (-0.052480) | 1.496104 / 1.452155 (0.043949) | 1.567878 / 1.492716 (0.075162) |\n\n### Benchmark: benchmark_getitem\\_100B.json\n\n| metric | get_batch_of\\_1024\\_random_rows | get_batch_of\\_1024\\_rows | get_first_row | get_last_row |\n|--------|---|---|---|---|\n| new / old (diff) | 0.215774 / 0.018006 (0.197768) | 0.436810 / 0.000490 (0.436320) | 0.000307 / 0.000200 (0.000107) | 0.000059 / 0.000054 (0.000005) |\n\n### Benchmark: benchmark_indices_mapping.json\n\n| metric | select | shard | shuffle | sort | train_test_split |\n|--------|---|---|---|---|---|\n| new / old (diff) | 0.024102 / 0.037411 (-0.013310) | 0.095459 / 0.014526 (0.080933) | 0.106564 / 0.176557 (-0.069992) | 0.169894 / 0.737135 (-0.567241) | 0.109152 / 0.296338 (-0.187186) |\n\n### Benchmark: benchmark_iterating.json\n\n| metric | read 5000 | read 50000 | read_batch 50000 10 | read_batch 50000 100 | read_batch 50000 1000 | read_formatted numpy 5000 | read_formatted pandas 5000 | read_formatted tensorflow 5000 | read_formatted torch 5000 | read_formatted_batch numpy 5000 10 | read_formatted_batch numpy 5000 1000 | shuffled read 5000 | shuffled read 50000 | shuffled read_batch 50000 10 | shuffled read_batch 50000 100 | shuffled read_batch 50000 1000 | shuffled read_formatted numpy 5000 | shuffled read_formatted_batch numpy 5000 10 | shuffled read_formatted_batch numpy 5000 1000 |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.429066 / 0.215209 (0.213857) | 4.297385 / 2.077655 (2.219730) | 2.054854 / 1.504120 (0.550734) | 1.846844 / 1.541195 (0.305649) | 1.840807 / 1.468490 (0.372317) | 0.553193 / 4.584777 (-4.031584) | 3.366788 / 3.745712 (-0.378924) | 1.727337 / 5.269862 (-3.542525) | 0.994357 / 4.565676 (-3.571319) | 0.067790 / 0.424275 (-0.356485) | 0.012002 / 0.007607 (0.004395) | 0.533335 / 0.226044 (0.307291) | 5.341341 / 2.268929 (3.072412) | 2.543581 / 55.444624 (-52.901043) | 2.220374 / 6.876477 (-4.656103) | 2.321656 / 2.142072 (0.179583) | 0.654408 / 4.805227 (-4.150819) | 0.134693 / 6.500664 (-6.365971) | 0.066926 / 0.075469 (-0.008544) |\n\n### Benchmark: benchmark_map_filter.json\n\n| metric | filter | map fast-tokenizer batched | map identity | map identity batched | map no-op batched | map no-op batched numpy | map no-op batched pandas | map no-op batched pytorch | map no-op batched tensorflow |\n|--------|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 1.209463 / 1.841788 (-0.632325) | 13.568221 / 8.074308 (5.493913) | 13.965418 / 10.191392 (3.774026) | 0.145049 / 0.680424 (-0.535375) | 0.016936 / 0.534201 (-0.517265) | 0.371587 / 0.579283 (-0.207696) | 0.386363 / 0.434364 (-0.048001) | 0.437137 / 0.540337 (-0.103201) | 0.514779 / 1.386936 (-0.872157) |\n\n</details>\nPyArrow==latest\n\n<details>\n<summary>Show updated benchmarks!</summary>\n\n### Benchmark: benchmark_array_xd.json\n\n| metric | read_batch_formatted_as_numpy after write_array2d | read_batch_formatted_as_numpy after write_flattened_sequence | read_batch_formatted_as_numpy after write_nested_sequence | read_batch_unformated after write_array2d | read_batch_unformated after write_flattened_sequence | read_batch_unformated after write_nested_sequence | read_col_formatted_as_numpy after write_array2d | read_col_formatted_as_numpy after write_flattened_sequence | read_col_formatted_as_numpy after write_nested_sequence | read_col_unformated after write_array2d | read_col_unformated after write_flattened_sequence | read_col_unformated after write_nested_sequence | read_formatted_as_numpy after write_array2d | read_formatted_as_numpy after write_flattened_sequence | read_formatted_as_numpy after write_nested_sequence | read_unformated after write_array2d | read_unformated after write_flattened_sequence | read_unformated after write_nested_sequence | write_array2d | write_flattened_sequence | write_nested_sequence |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.006245 / 0.011353 (-0.005108) | 0.004232 / 0.011008 (-0.006776) | 0.075682 / 0.038508 (0.037174) | 0.027858 / 0.023109 (0.004749) | 0.425325 / 0.275898 (0.149427) | 0.466732 / 0.323480 (0.143253) | 0.005240 / 0.007986 (-0.002745) | 0.003506 / 0.004328 (-0.000823) | 0.075294 / 0.004250 (0.071044) | 0.041677 / 0.037052 (0.004624) | 0.426552 / 0.258489 (0.168063) | 0.469452 / 0.293841 (0.175611) | 0.025443 / 0.128546 (-0.103104) | 0.008526 / 0.075646 (-0.067120) | 0.082190 / 0.419271 (-0.337081) | 0.040906 / 0.043533 (-0.002626) | 0.428406 / 0.255139 (0.173267) | 0.446795 / 0.283200 (0.163595) | 0.093837 / 0.141683 (-0.047846) | 1.518639 / 1.452155 (0.066484) | 1.620214 / 1.492716 (0.127498) |\n\n### Benchmark: benchmark_getitem\\_100B.json\n\n| metric | get_batch_of\\_1024\\_random_rows | get_batch_of\\_1024\\_rows | get_first_row | get_last_row |\n|--------|---|---|---|---|\n| new / old (diff) | 0.223259 / 0.018006 (0.205253) | 0.425077 / 0.000490 (0.424588) | 0.001980 / 0.000200 (0.001780) | 0.000077 / 0.000054 (0.000023) |\n\n### Benchmark: benchmark_indices_mapping.json\n\n| metric | select | shard | shuffle | sort | train_test_split |\n|--------|---|---|---|---|---|\n| new / old (diff) | 0.025813 / 0.037411 (-0.011599) | 0.103062 / 0.014526 (0.088536) | 0.108958 / 0.176557 (-0.067598) | 0.161591 / 0.737135 (-0.575544) | 0.112130 / 0.296338 (-0.184209) |\n\n### Benchmark: benchmark_iterating.json\n\n| metric | read 5000 | read 50000 | read_batch 50000 10 | read_batch 50000 100 | read_batch 50000 1000 | read_formatted numpy 5000 | read_formatted pandas 5000 | read_formatted tensorflow 5000 | read_formatted torch 5000 | read_formatted_batch numpy 5000 10 | read_formatted_batch numpy 5000 1000 | shuffled read 5000 | shuffled read 50000 | shuffled read_batch 50000 10 | shuffled read_batch 50000 100 | shuffled read_batch 50000 1000 | shuffled read_formatted numpy 5000 | shuffled read_formatted_batch numpy 5000 10 | shuffled read_formatted_batch numpy 5000 1000 |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.472843 / 0.215209 (0.257634) | 4.713281 / 2.077655 (2.635626) | 2.458216 / 1.504120 (0.954096) | 2.272467 / 1.541195 (0.731273) | 2.324456 / 1.468490 (0.855965) | 0.554686 / 4.584777 (-4.030091) | 3.445079 / 3.745712 (-0.300634) | 3.451896 / 5.269862 (-1.817966) | 1.431065 / 4.565676 (-3.134612) | 0.067868 / 0.424275 (-0.356407) | 0.012093 / 0.007607 (0.004486) | 0.573571 / 0.226044 (0.347526) | 5.820452 / 2.268929 (3.551523) | 2.934858 / 55.444624 (-52.509767) | 2.602719 / 6.876477 (-4.273758) | 2.645999 / 2.142072 (0.503927) | 0.660688 / 4.805227 (-4.144540) | 0.137490 / 6.500664 (-6.363174) | 0.068311 / 0.075469 (-0.007158) |\n\n### Benchmark: benchmark_map_filter.json\n\n| metric | filter | map fast-tokenizer batched | map identity | map identity batched | map no-op batched | map no-op batched numpy | map no-op batched pandas | map no-op batched pytorch | map no-op batched tensorflow |\n|--------|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 1.321709 / 1.841788 (-0.520079) | 14.592346 / 8.074308 (6.518038) | 14.520748 / 10.191392 (4.329356) | 0.132689 / 0.680424 (-0.547735) | 0.016422 / 0.534201 (-0.517779) | 0.370071 / 0.579283 (-0.209212) | 0.397091 / 0.434364 (-0.037273) | 0.431979 / 0.540337 (-0.108358) | 0.509965 / 1.386936 (-0.876971) |\n\n</details>\n</details>\n\n![](https://cml.dev/watermark.png#8bcd061ab2082a0862f30329bc52f6e0d321805c "CML watermark")\n', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1568606764/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1568659653', 'html_url': 'https://github.com/huggingface/datasets/pull/5916#issuecomment-1568659653', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5916', 'id': 1568659653, 'node_id': 'IC_kwDODunzps5df9jF', 'user': {'login': 'github-actions[bot]', 'id': 41898282, 'node_id': 'MDM6Qm90NDE4OTgyODI=', 'avatar_url': 'https://avatars.githubusercontent.com/in/15368?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/github-actions%5Bbot%5D', 'html_url': 'https://github.com/apps/github-actions', 'followers_url': 'https://api.github.com/users/github-actions%5Bbot%5D/followers', 'following_url': 'https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}', 'gists_url': 'https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/github-actions%5Bbot%5D/subscriptions', 'organizations_url': 'https://api.github.com/users/github-actions%5Bbot%5D/orgs', 'repos_url': 'https://api.github.com/users/github-actions%5Bbot%5D/repos', 'events_url': 'https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}', 'received_events_url': 'https://api.github.com/users/github-actions%5Bbot%5D/received_events', 'type': 'Bot', 'site_admin': False}, 'created_at': '2023-05-30T15:39:24Z', 'updated_at': '2023-05-30T15:39:24Z', 'author_association': 'NONE', 'body': '<details>\n<summary>Show benchmarks</summary>\n\nPyArrow==8.0.0\n\n<details>\n<summary>Show updated benchmarks!</summary>\n\n### Benchmark: benchmark_array_xd.json\n\n| metric | read_batch_formatted_as_numpy after write_array2d | read_batch_formatted_as_numpy after write_flattened_sequence | read_batch_formatted_as_numpy after write_nested_sequence | read_batch_unformated after write_array2d | read_batch_unformated after write_flattened_sequence | read_batch_unformated after write_nested_sequence | read_col_formatted_as_numpy after write_array2d | read_col_formatted_as_numpy after write_flattened_sequence | read_col_formatted_as_numpy after write_nested_sequence | read_col_unformated after write_array2d | read_col_unformated after write_flattened_sequence | read_col_unformated after write_nested_sequence | read_formatted_as_numpy after write_array2d | read_formatted_as_numpy after write_flattened_sequence | read_formatted_as_numpy after write_nested_sequence | read_unformated after write_array2d | read_unformated after write_flattened_sequence | read_unformated after write_nested_sequence | write_array2d | write_flattened_sequence | write_nested_sequence |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.006182 / 0.011353 (-0.005171) | 0.004153 / 0.011008 (-0.006855) | 0.095715 / 0.038508 (0.057207) | 0.032457 / 0.023109 (0.009347) | 0.314961 / 0.275898 (0.039063) | 0.353696 / 0.323480 (0.030216) | 0.005256 / 0.007986 (-0.002729) | 0.004870 / 0.004328 (0.000541) | 0.072442 / 0.004250 (0.068192) | 0.046102 / 0.037052 (0.009050) | 0.324410 / 0.258489 (0.065921) | 0.366861 / 0.293841 (0.073020) | 0.027088 / 0.128546 (-0.101458) | 0.008572 / 0.075646 (-0.067075) | 0.325988 / 0.419271 (-0.093284) | 0.049494 / 0.043533 (0.005961) | 0.311221 / 0.255139 (0.056082) | 0.359720 / 0.283200 (0.076521) | 0.095101 / 0.141683 (-0.046581) | 1.472821 / 1.452155 (0.020667) | 1.516157 / 1.492716 (0.023441) |\n\n### Benchmark: benchmark_getitem\\_100B.json\n\n| metric | get_batch_of\\_1024\\_random_rows | get_batch_of\\_1024\\_rows | get_first_row | get_last_row |\n|--------|---|---|---|---|\n| new / old (diff) | 0.210456 / 0.018006 (0.192450) | 0.439440 / 0.000490 (0.438950) | 0.003764 / 0.000200 (0.003564) | 0.000087 / 0.000054 (0.000033) |\n\n### Benchmark: benchmark_indices_mapping.json\n\n| metric | select | shard | shuffle | sort | train_test_split |\n|--------|---|---|---|---|---|\n| new / old (diff) | 0.024076 / 0.037411 (-0.013335) | 0.104886 / 0.014526 (0.090360) | 0.114164 / 0.176557 (-0.062393) | 0.167289 / 0.737135 (-0.569847) | 0.116457 / 0.296338 (-0.179882) |\n\n### Benchmark: benchmark_iterating.json\n\n| metric | read 5000 | read 50000 | read_batch 50000 10 | read_batch 50000 100 | read_batch 50000 1000 | read_formatted numpy 5000 | read_formatted pandas 5000 | read_formatted tensorflow 5000 | read_formatted torch 5000 | read_formatted_batch numpy 5000 10 | read_formatted_batch numpy 5000 1000 | shuffled read 5000 | shuffled read 50000 | shuffled read_batch 50000 10 | shuffled read_batch 50000 100 | shuffled read_batch 50000 1000 | shuffled read_formatted numpy 5000 | shuffled read_formatted_batch numpy 5000 10 | shuffled read_formatted_batch numpy 5000 1000 |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.400039 / 0.215209 (0.184830) | 3.973243 / 2.077655 (1.895588) | 1.801991 / 1.504120 (0.297871) | 1.592017 / 1.541195 (0.050822) | 1.612564 / 1.468490 (0.144074) | 0.527475 / 4.584777 (-4.057302) | 3.676246 / 3.745712 (-0.069466) | 1.806423 / 5.269862 (-3.463438) | 1.176921 / 4.565676 (-3.388756) | 0.065902 / 0.424275 (-0.358373) | 0.012245 / 0.007607 (0.004638) | 0.490883 / 0.226044 (0.264838) | 4.905270 / 2.268929 (2.636341) | 2.218694 / 55.444624 (-53.225930) | 1.903074 / 6.876477 (-4.973403) | 1.979505 / 2.142072 (-0.162567) | 0.644415 / 4.805227 (-4.160812) | 0.142433 / 6.500664 (-6.358231) | 0.063564 / 0.075469 (-0.011905) |\n\n### Benchmark: benchmark_map_filter.json\n\n| metric | filter | map fast-tokenizer batched | map identity | map identity batched | map no-op batched | map no-op batched numpy | map no-op batched pandas | map no-op batched pytorch | map no-op batched tensorflow |\n|--------|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 1.193756 / 1.841788 (-0.648032) | 14.673103 / 8.074308 (6.598795) | 13.410951 / 10.191392 (3.219559) | 0.159175 / 0.680424 (-0.521249) | 0.017076 / 0.534201 (-0.517125) | 0.388880 / 0.579283 (-0.190403) | 0.409974 / 0.434364 (-0.024390) | 0.454494 / 0.540337 (-0.085844) | 0.556873 / 1.386936 (-0.830063) |\n\n</details>\nPyArrow==latest\n\n<details>\n<summary>Show updated benchmarks!</summary>\n\n### Benchmark: benchmark_array_xd.json\n\n| metric | read_batch_formatted_as_numpy after write_array2d | read_batch_formatted_as_numpy after write_flattened_sequence | read_batch_formatted_as_numpy after write_nested_sequence | read_batch_unformated after write_array2d | read_batch_unformated after write_flattened_sequence | read_batch_unformated after write_nested_sequence | read_col_formatted_as_numpy after write_array2d | read_col_formatted_as_numpy after write_flattened_sequence | read_col_formatted_as_numpy after write_nes

[{'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1568543437', 'html_url': 'https://github.com/huggingface/datasets/pull/5915#issuecomment-1568543437', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5915', 'id': 1568543437, 'node_id': 'IC_kwDODunzps5dfhLN', 'user': {'login': 'HuggingFaceDocBuilderDev', 'id': 99929124, 'node_id': 'U_kgDOBfTMJA', 'avatar_url': 'https://avatars.githubusercontent.com/u/99929124?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/HuggingFaceDocBuilderDev', 'html_url': 'https://github.com/HuggingFaceDocBuilderDev', 'followers_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/followers', 'following_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/following{/other_user}', 'gists_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/subscriptions', 'organizations_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/orgs', 'repos_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/repos', 'events_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/events{/privacy}', 'received_events_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-05-30T14:32:35Z', 'updated_at': '2023-05-31T13:27:35Z', 'author_association': 'NONE', 'body': '_The documentation is not available anymore as the PR was closed or merged._', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1568543437/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1568544549', 'html_url': 'https://github.com/huggingface/datasets/pull/5915#issuecomment-1568544549', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5915', 'id': 1568544549, 'node_id': 'IC_kwDODunzps5dfhcl', 'user': {'login': 'github-actions[bot]', 'id': 41898282, 'node_id': 'MDM6Qm90NDE4OTgyODI=', 'avatar_url': 'https://avatars.githubusercontent.com/in/15368?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/github-actions%5Bbot%5D', 'html_url': 'https://github.com/apps/github-actions', 'followers_url': 'https://api.github.com/users/github-actions%5Bbot%5D/followers', 'following_url': 'https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}', 'gists_url': 'https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/github-actions%5Bbot%5D/subscriptions', 'organizations_url': 'https://api.github.com/users/github-actions%5Bbot%5D/orgs', 'repos_url': 'https://api.github.com/users/github-actions%5Bbot%5D/repos', 'events_url': 'https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}', 'received_events_url': 'https://api.github.com/users/github-actions%5Bbot%5D/received_events', 'type': 'Bot', 'site_admin': False}, 'created_at': '2023-05-30T14:33:06Z', 'updated_at': '2023-05-30T14:33:06Z', 'author_association': 'NONE', 'body': '<details>\n<summary>Show benchmarks</summary>\n\nPyArrow==8.0.0\n\n<details>\n<summary>Show updated benchmarks!</summary>\n\n### Benchmark: benchmark_array_xd.json\n\n| metric | read_batch_formatted_as_numpy after write_array2d | read_batch_formatted_as_numpy after write_flattened_sequence | read_batch_formatted_as_numpy after write_nested_sequence | read_batch_unformated after write_array2d | read_batch_unformated after write_flattened_sequence | read_batch_unformated after write_nested_sequence | read_col_formatted_as_numpy after write_array2d | read_col_formatted_as_numpy after write_flattened_sequence | read_col_formatted_as_numpy after write_nested_sequence | read_col_unformated after write_array2d | read_col_unformated after write_flattened_sequence | read_col_unformated after write_nested_sequence | read_formatted_as_numpy after write_array2d | read_formatted_as_numpy after write_flattened_sequence | read_formatted_as_numpy after write_nested_sequence | read_unformated after write_array2d | read_unformated after write_flattened_sequence | read_unformated after write_nested_sequence | write_array2d | write_flattened_sequence | write_nested_sequence |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.006416 / 0.011353 (-0.004937) | 0.004278 / 0.011008 (-0.006731) | 0.097562 / 0.038508 (0.059054) | 0.029488 / 0.023109 (0.006379) | 0.308648 / 0.275898 (0.032750) | 0.339879 / 0.323480 (0.016399) | 0.005288 / 0.007986 (-0.002697) | 0.005033 / 0.004328 (0.000704) | 0.074666 / 0.004250 (0.070416) | 0.034888 / 0.037052 (-0.002164) | 0.309960 / 0.258489 (0.051471) | 0.344276 / 0.293841 (0.050435) | 0.025564 / 0.128546 (-0.102982) | 0.008579 / 0.075646 (-0.067067) | 0.319796 / 0.419271 (-0.099476) | 0.044786 / 0.043533 (0.001253) | 0.308888 / 0.255139 (0.053749) | 0.334001 / 0.283200 (0.050802) | 0.089917 / 0.141683 (-0.051766) | 1.456696 / 1.452155 (0.004541) | 1.542273 / 1.492716 (0.049557) |\n\n### Benchmark: benchmark_getitem\\_100B.json\n\n| metric | get_batch_of\\_1024\\_random_rows | get_batch_of\\_1024\\_rows | get_first_row | get_last_row |\n|--------|---|---|---|---|\n| new / old (diff) | 0.213236 / 0.018006 (0.195230) | 0.425139 / 0.000490 (0.424650) | 0.008831 / 0.000200 (0.008631) | 0.000209 / 0.000054 (0.000155) |\n\n### Benchmark: benchmark_indices_mapping.json\n\n| metric | select | shard | shuffle | sort | train_test_split |\n|--------|---|---|---|---|---|\n| new / old (diff) | 0.023990 / 0.037411 (-0.013421) | 0.096787 / 0.014526 (0.082261) | 0.105783 / 0.176557 (-0.070774) | 0.167182 / 0.737135 (-0.569954) | 0.108896 / 0.296338 (-0.187442) |\n\n### Benchmark: benchmark_iterating.json\n\n| metric | read 5000 | read 50000 | read_batch 50000 10 | read_batch 50000 100 | read_batch 50000 1000 | read_formatted numpy 5000 | read_formatted pandas 5000 | read_formatted tensorflow 5000 | read_formatted torch 5000 | read_formatted_batch numpy 5000 10 | read_formatted_batch numpy 5000 1000 | shuffled read 5000 | shuffled read 50000 | shuffled read_batch 50000 10 | shuffled read_batch 50000 100 | shuffled read_batch 50000 1000 | shuffled read_formatted numpy 5000 | shuffled read_formatted_batch numpy 5000 10 | shuffled read_formatted_batch numpy 5000 1000 |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.419844 / 0.215209 (0.204635) | 4.201909 / 2.077655 (2.124254) | 1.910784 / 1.504120 (0.406664) | 1.685183 / 1.541195 (0.143988) | 1.716927 / 1.468490 (0.248437) | 0.548261 / 4.584777 (-4.036516) | 3.414168 / 3.745712 (-0.331544) | 1.695446 / 5.269862 (-3.574415) | 0.989668 / 4.565676 (-3.576008) | 0.067328 / 0.424275 (-0.356948) | 0.012084 / 0.007607 (0.004477) | 0.523799 / 0.226044 (0.297754) | 5.240589 / 2.268929 (2.971661) | 2.331618 / 55.444624 (-53.113007) | 1.996094 / 6.876477 (-4.880383) | 2.105450 / 2.142072 (-0.036623) | 0.654614 / 4.805227 (-4.150613) | 0.134721 / 6.500664 (-6.365943) | 0.066227 / 0.075469 (-0.009242) |\n\n### Benchmark: benchmark_map_filter.json\n\n| metric | filter | map fast-tokenizer batched | map identity | map identity batched | map no-op batched | map no-op batched numpy | map no-op batched pandas | map no-op batched pytorch | map no-op batched tensorflow |\n|--------|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 1.196266 / 1.841788 (-0.645521) | 13.990045 / 8.074308 (5.915737) | 13.928126 / 10.191392 (3.736734) | 0.142600 / 0.680424 (-0.537824) | 0.016462 / 0.534201 (-0.517739) | 0.363113 / 0.579283 (-0.216170) | 0.428590 / 0.434364 (-0.005773) | 0.452594 / 0.540337 (-0.087743) | 0.551678 / 1.386936 (-0.835258) |\n\n</details>\nPyArrow==latest\n\n<details>\n<summary>Show updated benchmarks!</summary>\n\n### Benchmark: benchmark_array_xd.json\n\n| metric | read_batch_formatted_as_numpy after write_array2d | read_batch_formatted_as_numpy after write_flattened_sequence | read_batch_formatted_as_numpy after write_nested_sequence | read_batch_unformated after write_array2d | read_batch_unformated after write_flattened_sequence | read_batch_unformated after write_nested_sequence | read_col_formatted_as_numpy after write_array2d | read_col_formatted_as_numpy after write_flattened_sequence | read_col_formatted_as_numpy after write_nested_sequence | read_col_unformated after write_array2d | read_col_unformated after write_flattened_sequence | read_col_unformated after write_nested_sequence | read_formatted_as_numpy after write_array2d | read_formatted_as_numpy after write_flattened_sequence | read_formatted_as_numpy after write_nested_sequence | read_unformated after write_array2d | read_unformated after write_flattened_sequence | read_unformated after write_nested_sequence | write_array2d | write_flattened_sequence | write_nested_sequence |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.005992 / 0.011353 (-0.005361) | 0.004161 / 0.011008 (-0.006847) | 0.076098 / 0.038508 (0.037589) | 0.028559 / 0.023109 (0.005450) | 0.411696 / 0.275898 (0.135798) | 0.444519 / 0.323480 (0.121040) | 0.004965 / 0.007986 (-0.003021) | 0.003452 / 0.004328 (-0.000876) | 0.075107 / 0.004250 (0.070857) | 0.037305 / 0.037052 (0.000252) | 0.429728 / 0.258489 (0.171239) | 0.444313 / 0.293841 (0.150472) | 0.025278 / 0.128546 (-0.103268) | 0.008527 / 0.075646 (-0.067120) | 0.081502 / 0.419271 (-0.337770) | 0.041237 / 0.043533 (-0.002296) | 0.417848 / 0.255139 (0.162709) | 0.426615 / 0.283200 (0.143415) | 0.094641 / 0.141683 (-0.047041) | 1.525141 / 1.452155 (0.072987) | 1.615608 / 1.492716 (0.122892) |\n\n### Benchmark: benchmark_getitem\\_100B.json\n\n| metric | get_batch_of\\_1024\\_random_rows | get_batch_of\\_1024\\_rows | get_first_row | get_last_row |\n|--------|---|---|---|---|\n| new / old (diff) | 0.192867 / 0.018006 (0.174861) | 0.414979 / 0.000490 (0.414490) | 0.000815 / 0.000200 (0.000615) | 0.000068 / 0.000054 (0.000013) |\n\n### Benchmark: benchmark_indices_mapping.json\n\n| metric | select | shard | shuffle | sort | train_test_split |\n|--------|---|---|---|---|---|\n| new / old (diff) | 0.025354 / 0.037411 (-0.012058) | 0.102085 / 0.014526 (0.087559) | 0.107930 / 0.176557 (-0.068626) | 0.160483 / 0.737135 (-0.576652) | 0.112341 / 0.296338 (-0.183997) |\n\n### Benchmark: benchmark_iterating.json\n\n| metric | read 5000 | read 50000 | read_batch 50000 10 | read_batch 50000 100 | read_batch 50000 1000 | read_formatted numpy 5000 | read_formatted pandas 5000 | read_formatted tensorflow 5000 | read_formatted torch 5000 | read_formatted_batch numpy 5000 10 | read_formatted_batch numpy 5000 1000 | shuffled read 5000 | shuffled read 50000 | shuffled read_batch 50000 10 | shuffled read_batch 50000 100 | shuffled read_batch 50000 1000 | shuffled read_formatted numpy 5000 | shuffled read_formatted_batch numpy 5000 10 | shuffled read_formatted_batch numpy 5000 1000 |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.446938 / 0.215209 (0.231728) | 4.480057 / 2.077655 (2.402402) | 2.154825 / 1.504120 (0.650705) | 1.942774 / 1.541195 (0.401580) | 1.996418 / 1.468490 (0.527928) | 0.556728 / 4.584777 (-4.028049) | 3.441228 / 3.745712 (-0.304484) | 3.004179 / 5.269862 (-2.265683) | 1.314104 / 4.565676 (-3.251573) | 0.068670 / 0.424275 (-0.355606) | 0.011972 / 0.007607 (0.004365) | 0.556604 / 0.226044 (0.330560) | 5.561783 / 2.268929 (3.292855) | 2.631262 / 55.444624 (-52.813363) | 2.262143 / 6.876477 (-4.614333) | 2.364243 / 2.142072 (0.222170) | 0.660621 / 4.805227 (-4.144607) | 0.137371 / 6.500664 (-6.363293) | 0.069104 / 0.075469 (-0.006365) |\n\n### Benchmark: benchmark_map_filter.json\n\n| metric | filter | map fast-tokenizer batched | map identity | map identity batched | map no-op batched | map no-op batched numpy | map no-op batched pandas | map no-op batched pytorch | map no-op batched tensorflow |\n|--------|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 1.305706 / 1.841788 (-0.536081) | 14.015932 / 8.074308 (5.941624) | 14.353580 / 10.191392 (4.162187) | 0.146172 / 0.680424 (-0.534251) | 0.016699 / 0.534201 (-0.517502) | 0.357970 / 0.579283 (-0.221313) | 0.389067 / 0.434364 (-0.045297) | 0.415470 / 0.540337 (-0.124867) | 0.501359 / 1.386936 (-0.885577) |\n\n</details>\n</details>\n\n![](https://cml.dev/watermark.png#b2b837b4e7267db9e32d2613d8bf8d70d2ce0b47 "CML watermark")\n', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1568544549/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1568578266', 'html_url': 'https://github.com/huggingface/datasets/pull/5915#issuecomment-1568578266', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5915', 'id': 1568578266, 'node_id': 'IC_kwDODunzps5dfpra', 'user': {'login': 'github-actions[bot]', 'id': 41898282, 'node_id': 'MDM6Qm90NDE4OTgyODI=', 'avatar_url': 'https://avatars.githubusercontent.com/in/15368?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/github-actions%5Bbot%5D', 'html_url': 'https://github.com/apps/github-actions', 'followers_url': 'https://api.github.com/users/github-actions%5Bbot%5D/followers', 'following_url': 'https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}', 'gists_url': 'https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/github-actions%5Bbot%5D/subscriptions', 'organizations_url': 'https://api.github.com/users/github-actions%5Bbot%5D/orgs', 'repos_url': 'https://api.github.com/users/github-actions%5Bbot%5D/repos', 'events_url': 'https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}', 'received_events_url': 'https://api.github.com/users/github-actions%5Bbot%5D/received_events', 'type': 'Bot', 'site_admin': False}, 'created_at': '2023-05-30T14:50:56Z', 'updated_at': '2023-05-30T14:50:56Z', 'author_association': 'NONE', 'body': '<details>\n<summary>Show benchmarks</summary>\n\nPyArrow==8.0.0\n\n<details>\n<summary>Show updated benchmarks!</summary>\n\n### Benchmark: benchmark_array_xd.json\n\n| metric | read_batch_formatted_as_numpy after write_array2d | read_batch_formatted_as_numpy after write_flattened_sequence | read_batch_formatted_as_numpy after write_nested_sequence | read_batch_unformated after write_array2d | read_batch_unformated after write_flattened_sequence | read_batch_unformated after write_nested_sequence | read_col_formatted_as_numpy after write_array2d | read_col_formatted_as_numpy after write_flattened_sequence | read_col_formatted_as_numpy after write_nested_sequence | read_col_unformated after write_array2d | read_col_unformated after write_flattened_sequence | read_col_unformated after write_nested_sequence | read_formatted_as_numpy after write_array2d | read_formatted_as_numpy after write_flattened_sequence | read_formatted_as_numpy after write_nested_sequence | read_unformated after write_array2d | read_unformated after write_flattened_sequence | read_unformated after write_nested_sequence | write_array2d | write_flattened_sequence | write_nested_sequence |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.006800 / 0.011353 (-0.004552) | 0.004721 / 0.011008 (-0.006287) | 0.097760 / 0.038508 (0.059252) | 0.034192 / 0.023109 (0.011083) | 0.298240 / 0.275898 (0.022342) | 0.331119 / 0.323480 (0.007639) | 0.005826 / 0.007986 (-0.002160) | 0.003968 / 0.004328 (-0.000360) | 0.073833 / 0.004250 (0.069582) | 0.046288 / 0.037052 (0.009236) | 0.303018 / 0.258489 (0.044529) | 0.342163 / 0.293841 (0.048322) | 0.028504 / 0.128546 (-0.100042) | 0.009031 / 0.075646 (-0.066615) | 0.331617 / 0.419271 (-0.087655) | 0.060911 / 0.043533 (0.017379) | 0.304044 / 0.255139 (0.048905) | 0.328959 / 0.283200 (0.045759) | 0.113174 / 0.141683 (-0.028509) | 1.424652 / 1.452155 (-0.027502) | 1.531392 / 1.492716 (0.038676) |\n\n### Benchmark: benchmark_getitem\\_100B.json\n\n| metric | get_batch_of\\_1024\\_random_rows | get_batch_of\\_1024\\_rows | get_first_row | get_last_row |\n|--------|---|---|---|---|\n| new / old (diff) | 0.206175 / 0.018006 (0.188169) | 0.435916 / 0.000490 (0.435426) | 0.002587 / 0.000200 (0.002387) | 0.000083 / 0.000054 (0.000029) |\n\n### Benchmark: benchmark_indices_mapping.json\n\n| metric | select | shard | shuffle | sort | train_test_split |\n|--------|---|---|---|---|---|\n| new / old (diff) | 0.026996 / 0.037411 (-0.010415) | 0.106722 / 0.014526 (0.092196) | 0.117655 / 0.176557 (-0.058902) | 0.176969 / 0.737135 (-0.560166) | 0.122577 / 0.296338 (-0.173762) |\n\n### Benchmark: benchmark_iterating.json\n\n| metric | read 5000 | read 50000 | read_batch 50000 10 | read_batch 50000 100 | read_batch 50000 1000 | read_formatted numpy 5000 | read_formatted pandas 5000 | read_formatted tensorflow 5000 | read_formatted torch 5000 | read_formatted_batch numpy 5000 10 | read_formatted_batch numpy 5000 1000 | shuffled read 5000 | shuffled read 50000 | shuffled read_batch 50000 10 | shuffled read_batch 50000 100 | shuffled read_batch 50000 1000 | shuffled read_formatted numpy 5000 | shuffled read_formatted_batch numpy 5000 10 | shuffled read_formatted_batch numpy 5000 1000 |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.396086 / 0.215209 (0.180877) | 3.972465 / 2.077655 (1.894811) | 1.800798 / 1.504120 (0.296678) | 1.616747 / 1.541195 (0.075552) | 1.680711 / 1.468490 (0.212221) | 0.526479 / 4.584777 (-4.058298) | 3.791528 / 3.745712 (0.045816) | 2.989518 / 5.269862 (-2.280344) | 1.463221 / 4.565676 (-3.102455) | 0.065649 / 0.424275 (-0.358626) | 0.012155 / 0.007607 (0.004548) | 0.500241 / 0.226044 (0.274197) | 5.008895 / 2.268929 (2.739966) | 2.315288 / 55.444624 (-53.129336) | 1.959409 / 6.876477 (-4.917067) | 2.102371 / 2.142072 (-0.039701) | 0.639611 / 4.805227 (-4.165617) | 0.140101 / 6.500664 (-6.360563) | 0.063599 / 0.075469 (-0.011870) |\n\n### Benchmark: benchmark_map_filter.json\n\n| metric | filter | map fast-tokenizer batched | map identity | map identity batched | map no-op batched | map no-op batched numpy | map no-op batched pandas | map no-op batched pytorch | map no-op batched tensorflow |\n|--------|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 1.206729 / 1.841788 (-0.635059) | 15.127250 / 8.074308 (7.052942) | 14.397228 / 10.191392 (4.205836) | 0.148802 / 0.680424 (-0.531622) | 0.017628 / 0.534201 (-0.516573) | 0.396150 / 0.579283 (-0.183133) | 0.435826 / 0.434364 (0.001462) | 0.471215 / 0.540337 (-0.069122) | 0.559413 / 1.386936 (-0.827523) |\n\n</details>\nPyArrow==latest\n\n<details>\n<summary>Show updated benchmarks!</summary>\n\n### Benchmark: benchmark_array_xd.json\n\n| metric | read_batch_formatted_as_numpy after write_array2d | read_batch_formatted_as_numpy after write_flattened_sequence | read_batch_formatted_as_numpy after write_nested_sequence | read_batch_unformated after write_array2d | read_batch_unformated after write_flattened_sequence | read_batch_unformated after write_nested_sequence | read_col_formatted_as_numpy after write_array2d | read_col_formatted_as_numpy after write_flattened_sequence | read_col_formatted_as_numpy after write_ne

[]
[{'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1567797327', 'html_url': 'https://github.com/huggingface/datasets/issues/5913#issuecomment-1567797327', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5913', 'id': 1567797327, 'node_id': 'IC_kwDODunzps5dcrBP', 'user': {'login': 'albertvillanova', 'id': 8515462, 'node_id': 'MDQ6VXNlcjg1MTU0NjI=', 'avatar_url': 'https://avatars.githubusercontent.com/u/8515462?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/albertvillanova', 'html_url': 'https://github.com/albertvillanova', 'followers_url': 'https://api.github.com/users/albertvillanova/followers', 'following_url': 'https://api.github.com/users/albertvillanova/following{/other_user}', 'gists_url': 'https://api.github.com/users/albertvillanova/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/albertvillanova/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/albertvillanova/subscriptions', 'organizations_url': 'https://api.github.com/users/albertvillanova/orgs', 'repos_url': 'https://api.github.com/users/albertvillanova/repos', 'events_url': 'https://api.github.com/users/albertvillanova/events{/privacy}', 'received_events_url': 'https://api.github.com/users/albertvillanova/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-05-30T06:00:23Z', 'updated_at': '2023-05-30T06:00:23Z', 'author_association': 'MEMBER', 'body': 'Thanks for reporting, @cjt222.\r\n\r\nWhat is the structure of your JSON files. Please note that it is normally simpler if the data file format is JSON-Lines instead. ', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1567797327/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1585560673', 'html_url': 'https://github.com/huggingface/datasets/issues/5913#issuecomment-1585560673', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5913', 'id': 1585560673, 'node_id': 'IC_kwDODunzps5egbxh', 'user': {'login': 'BUAADreamer', 'id': 64362896, 'node_id': 'MDQ6VXNlcjY0MzYyODk2', 'avatar_url': 'https://avatars.githubusercontent.com/u/64362896?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/BUAADreamer', 'html_url': 'https://github.com/BUAADreamer', 'followers_url': 'https://api.github.com/users/BUAADreamer/followers', 'following_url': 'https://api.github.com/users/BUAADreamer/following{/other_user}', 'gists_url': 'https://api.github.com/users/BUAADreamer/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/BUAADreamer/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/BUAADreamer/subscriptions', 'organizations_url': 'https://api.github.com/users/BUAADreamer/orgs', 'repos_url': 'https://api.github.com/users/BUAADreamer/repos', 'events_url': 'https://api.github.com/users/BUAADreamer/events{/privacy}', 'received_events_url': 'https://api.github.com/users/BUAADreamer/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-10T08:25:11Z', 'updated_at': '2023-06-10T08:25:11Z', 'author_association': 'NONE', 'body': '> Thanks for reporting, @cjt222.\r\n> \r\n> What is the structure of your JSON files. Please note that it is normally simpler if the data file format is JSON-Lines instead.\r\n\r\nThanks! I have encountered similar problems. I modify the json format from list to line and works!', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1585560673/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}]
[{'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1568817123', 'html_url': 'https://github.com/huggingface/datasets/issues/5912#issuecomment-1568817123', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5912', 'id': 1568817123, 'node_id': 'IC_kwDODunzps5dgj_j', 'user': {'login': 'lhoestq', 'id': 42851186, 'node_id': 'MDQ6VXNlcjQyODUxMTg2', 'avatar_url': 'https://avatars.githubusercontent.com/u/42851186?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/lhoestq', 'html_url': 'https://github.com/lhoestq', 'followers_url': 'https://api.github.com/users/lhoestq/followers', 'following_url': 'https://api.github.com/users/lhoestq/following{/other_user}', 'gists_url': 'https://api.github.com/users/lhoestq/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/lhoestq/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/lhoestq/subscriptions', 'organizations_url': 'https://api.github.com/users/lhoestq/orgs', 'repos_url': 'https://api.github.com/users/lhoestq/repos', 'events_url': 'https://api.github.com/users/lhoestq/events{/privacy}', 'received_events_url': 'https://api.github.com/users/lhoestq/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-05-30T17:35:21Z', 'updated_at': '2023-05-30T17:35:33Z', 'author_association': 'MEMBER', 'body': 'Hi ! in your code batching is **only used within** `map`, to process examples in batch. The dataset itself however is not batched and returns elements one by one.\r\n\r\nTo iterate on batches, you can do\r\n```python\r\nfor batch in dataset.iter(batch_size=8):\r\n    ...\r\n```', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1568817123/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}]
[{'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1589775056', 'html_url': 'https://github.com/huggingface/datasets/issues/5910#issuecomment-1589775056', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5910', 'id': 1589775056, 'node_id': 'IC_kwDODunzps5ewgrQ', 'user': {'login': 'mariosasko', 'id': 47462742, 'node_id': 'MDQ6VXNlcjQ3NDYyNzQy', 'avatar_url': 'https://avatars.githubusercontent.com/u/47462742?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/mariosasko', 'html_url': 'https://github.com/mariosasko', 'followers_url': 'https://api.github.com/users/mariosasko/followers', 'following_url': 'https://api.github.com/users/mariosasko/following{/other_user}', 'gists_url': 'https://api.github.com/users/mariosasko/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/mariosasko/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/mariosasko/subscriptions', 'organizations_url': 'https://api.github.com/users/mariosasko/orgs', 'repos_url': 'https://api.github.com/users/mariosasko/repos', 'events_url': 'https://api.github.com/users/mariosasko/events{/privacy}', 'received_events_url': 'https://api.github.com/users/mariosasko/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-13T17:52:17Z', 'updated_at': '2023-06-13T17:52:17Z', 'author_association': 'CONTRIBUTOR', 'body': 'Currently, it\'s not possible to chain `set_format`/`set_transform` calls (plus, this is a breaking change if we decide to implement it), so I see two possible solutions:\r\n* using `set_format`/`set_transform` for the 1st transform and then passing the transformed example/batch to the 2nd transform\r\n* implementing and registering a custom formatter (the relevant code is [here](https://github.com/huggingface/datasets/tree/main/src/datasets/formatting))\r\n\r\nBtw, your example requires a single `set_format` call:\r\n```python\r\nds.set_format("torch", columns=["image"], output_all_columns=True, dtype=torch.double)\r\n```', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1589775056/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1593282476', 'html_url': 'https://github.com/huggingface/datasets/issues/5910#issuecomment-1593282476', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5910', 'id': 1593282476, 'node_id': 'IC_kwDODunzps5e94-s', 'user': {'login': 'ybouane', 'id': 14046002, 'node_id': 'MDQ6VXNlcjE0MDQ2MDAy', 'avatar_url': 'https://avatars.githubusercontent.com/u/14046002?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/ybouane', 'html_url': 'https://github.com/ybouane', 'followers_url': 'https://api.github.com/users/ybouane/followers', 'following_url': 'https://api.github.com/users/ybouane/following{/other_user}', 'gists_url': 'https://api.github.com/users/ybouane/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/ybouane/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/ybouane/subscriptions', 'organizations_url': 'https://api.github.com/users/ybouane/orgs', 'repos_url': 'https://api.github.com/users/ybouane/repos', 'events_url': 'https://api.github.com/users/ybouane/events{/privacy}', 'received_events_url': 'https://api.github.com/users/ybouane/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-15T15:23:59Z', 'updated_at': '2023-06-15T15:24:21Z', 'author_association': 'NONE', 'body': "Hey Mario,\r\nThanks, for getting back to me. the toDouble was just an example my real life case requires many more transforms.\r\n\r\nWhat do you mean by:\r\n> using set_format/set_transform for the 1st transform and then passing the transformed example/batch to the 2nd transform\r\n\r\nHow would that go, I thought you can't chain them?\r\n\r\nAs for the custom formatter, is it possible to reference an existing formatter, in my case `torch_formatter` inside of my custom formatter?\r\n\r\nmaybe I can inherit from it and just call `super.recursive_tensorize()`?", 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1593282476/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1593702421', 'html_url': 'https://github.com/huggingface/datasets/issues/5910#issuecomment-1593702421', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5910', 'id': 1593702421, 'node_id': 'IC_kwDODunzps5e_fgV', 'user': {'login': 'mariosasko', 'id': 47462742, 'node_id': 'MDQ6VXNlcjQ3NDYyNzQy', 'avatar_url': 'https://avatars.githubusercontent.com/u/47462742?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/mariosasko', 'html_url': 'https://github.com/mariosasko', 'followers_url': 'https://api.github.com/users/mariosasko/followers', 'following_url': 'https://api.github.com/users/mariosasko/following{/other_user}', 'gists_url': 'https://api.github.com/users/mariosasko/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/mariosasko/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/mariosasko/subscriptions', 'organizations_url': 'https://api.github.com/users/mariosasko/orgs', 'repos_url': 'https://api.github.com/users/mariosasko/repos', 'events_url': 'https://api.github.com/users/mariosasko/events{/privacy}', 'received_events_url': 'https://api.github.com/users/mariosasko/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-15T20:45:18Z', 'updated_at': '2023-06-15T20:45:18Z', 'author_association': 'CONTRIBUTOR', 'body': "> How would that go, I thought you can't chain them?\r\n\r\nYes, they cannot be chained. This is what I meant:\r\n```python\r\nds.set_transform(first_transform)\r\n# calling the 2nd transform on each accessed batch\r\nsecond_transform(ds[2:3])\r\n```\r\n\r\n> As for the custom formatter, is it possible to reference an existing formatter, in my case torch_formatter inside of my custom formatter?\r\n>\r\n>maybe I can inherit from it and just call super.recursive_tensorize()?\r\n\r\nYes, subclassing makes the most sense.", 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1593702421/reactions', 'total_count': 1, '+1': 1, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1594808203', 'html_url': 'https://github.com/huggingface/datasets/issues/5910#issuecomment-1594808203', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5910', 'id': 1594808203, 'node_id': 'IC_kwDODunzps5fDteL', 'user': {'login': 'ybouane', 'id': 14046002, 'node_id': 'MDQ6VXNlcjE0MDQ2MDAy', 'avatar_url': 'https://avatars.githubusercontent.com/u/14046002?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/ybouane', 'html_url': 'https://github.com/ybouane', 'followers_url': 'https://api.github.com/users/ybouane/followers', 'following_url': 'https://api.github.com/users/ybouane/following{/other_user}', 'gists_url': 'https://api.github.com/users/ybouane/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/ybouane/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/ybouane/subscriptions', 'organizations_url': 'https://api.github.com/users/ybouane/orgs', 'repos_url': 'https://api.github.com/users/ybouane/repos', 'events_url': 'https://api.github.com/users/ybouane/events{/privacy}', 'received_events_url': 'https://api.github.com/users/ybouane/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-16T14:41:24Z', 'updated_at': '2023-06-16T14:41:24Z', 'author_association': 'NONE', 'body': 'Great, thank you for the details.', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1594808203/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1627832475', 'html_url': 'https://github.com/huggingface/datasets/issues/5910#issuecomment-1627832475', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5910', 'id': 1627832475, 'node_id': 'IC_kwDODunzps5hBsCb', 'user': {'login': 'NightMachinery', 'id': 36224762, 'node_id': 'MDQ6VXNlcjM2MjI0NzYy', 'avatar_url': 'https://avatars.githubusercontent.com/u/36224762?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/NightMachinery', 'html_url': 'https://github.com/NightMachinery', 'followers_url': 'https://api.github.com/users/NightMachinery/followers', 'following_url': 'https://api.github.com/users/NightMachinery/following{/other_user}', 'gists_url': 'https://api.github.com/users/NightMachinery/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/NightMachinery/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/NightMachinery/subscriptions', 'organizations_url': 'https://api.github.com/users/NightMachinery/orgs', 'repos_url': 'https://api.github.com/users/NightMachinery/repos', 'events_url': 'https://api.github.com/users/NightMachinery/events{/privacy}', 'received_events_url': 'https://api.github.com/users/NightMachinery/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-07-09T21:40:54Z', 'updated_at': '2023-07-09T21:40:54Z', 'author_association': 'CONTRIBUTOR', 'body': 'https://github.com/huggingface/datasets/issues/6012', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1627832475/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}]

[{'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1570220203', 'html_url': 'https://github.com/huggingface/datasets/pull/5909#issuecomment-1570220203', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5909', 'id': 1570220203, 'node_id': 'IC_kwDODunzps5dl6ir', 'user': {'login': 'HuggingFaceDocBuilderDev', 'id': 99929124, 'node_id': 'U_kgDOBfTMJA', 'avatar_url': 'https://avatars.githubusercontent.com/u/99929124?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/HuggingFaceDocBuilderDev', 'html_url': 'https://github.com/HuggingFaceDocBuilderDev', 'followers_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/followers', 'following_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/following{/other_user}', 'gists_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/subscriptions', 'organizations_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/orgs', 'repos_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/repos', 'events_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/events{/privacy}', 'received_events_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-05-31T13:17:53Z', 'updated_at': '2023-05-31T13:31:30Z', 'author_association': 'NONE', 'body': '_The documentation is not available anymore as the PR was closed or merged._', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1570220203/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1570253259', 'html_url': 'https://github.com/huggingface/datasets/pull/5909#issuecomment-1570253259', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5909', 'id': 1570253259, 'node_id': 'IC_kwDODunzps5dmCnL', 'user': {'login': 'github-actions[bot]', 'id': 41898282, 'node_id': 'MDM6Qm90NDE4OTgyODI=', 'avatar_url': 'https://avatars.githubusercontent.com/in/15368?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/github-actions%5Bbot%5D', 'html_url': 'https://github.com/apps/github-actions', 'followers_url': 'https://api.github.com/users/github-actions%5Bbot%5D/followers', 'following_url': 'https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}', 'gists_url': 'https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/github-actions%5Bbot%5D/subscriptions', 'organizations_url': 'https://api.github.com/users/github-actions%5Bbot%5D/orgs', 'repos_url': 'https://api.github.com/users/github-actions%5Bbot%5D/repos', 'events_url': 'https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}', 'received_events_url': 'https://api.github.com/users/github-actions%5Bbot%5D/received_events', 'type': 'Bot', 'site_admin': False}, 'created_at': '2023-05-31T13:36:53Z', 'updated_at': '2023-05-31T13:36:53Z', 'author_association': 'NONE', 'body': '<details>\n<summary>Show benchmarks</summary>\n\nPyArrow==8.0.0\n\n<details>\n<summary>Show updated benchmarks!</summary>\n\n### Benchmark: benchmark_array_xd.json\n\n| metric | read_batch_formatted_as_numpy after write_array2d | read_batch_formatted_as_numpy after write_flattened_sequence | read_batch_formatted_as_numpy after write_nested_sequence | read_batch_unformated after write_array2d | read_batch_unformated after write_flattened_sequence | read_batch_unformated after write_nested_sequence | read_col_formatted_as_numpy after write_array2d | read_col_formatted_as_numpy after write_flattened_sequence | read_col_formatted_as_numpy after write_nested_sequence | read_col_unformated after write_array2d | read_col_unformated after write_flattened_sequence | read_col_unformated after write_nested_sequence | read_formatted_as_numpy after write_array2d | read_formatted_as_numpy after write_flattened_sequence | read_formatted_as_numpy after write_nested_sequence | read_unformated after write_array2d | read_unformated after write_flattened_sequence | read_unformated after write_nested_sequence | write_array2d | write_flattened_sequence | write_nested_sequence |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.008156 / 0.011353 (-0.003197) | 0.005563 / 0.011008 (-0.005445) | 0.118319 / 0.038508 (0.079810) | 0.044305 / 0.023109 (0.021195) | 0.366221 / 0.275898 (0.090323) | 0.407585 / 0.323480 (0.084105) | 0.006961 / 0.007986 (-0.001024) | 0.004841 / 0.004328 (0.000513) | 0.089949 / 0.004250 (0.085698) | 0.062197 / 0.037052 (0.025144) | 0.360721 / 0.258489 (0.102232) | 0.415332 / 0.293841 (0.121491) | 0.035709 / 0.128546 (-0.092837) | 0.010617 / 0.075646 (-0.065030) | 0.397454 / 0.419271 (-0.021817) | 0.063490 / 0.043533 (0.019958) | 0.374289 / 0.255139 (0.119150) | 0.382827 / 0.283200 (0.099628) | 0.121014 / 0.141683 (-0.020669) | 1.729933 / 1.452155 (0.277779) | 1.896222 / 1.492716 (0.403506) |\n\n### Benchmark: benchmark_getitem\\_100B.json\n\n| metric | get_batch_of\\_1024\\_random_rows | get_batch_of\\_1024\\_rows | get_first_row | get_last_row |\n|--------|---|---|---|---|\n| new / old (diff) | 0.254030 / 0.018006 (0.236023) | 0.491225 / 0.000490 (0.490736) | 0.018933 / 0.000200 (0.018734) | 0.000413 / 0.000054 (0.000358) |\n\n### Benchmark: benchmark_indices_mapping.json\n\n| metric | select | shard | shuffle | sort | train_test_split |\n|--------|---|---|---|---|---|\n| new / old (diff) | 0.033085 / 0.037411 (-0.004327) | 0.132837 / 0.014526 (0.118311) | 0.143275 / 0.176557 (-0.033282) | 0.215800 / 0.737135 (-0.521335) | 0.149802 / 0.296338 (-0.146536) |\n\n### Benchmark: benchmark_iterating.json\n\n| metric | read 5000 | read 50000 | read_batch 50000 10 | read_batch 50000 100 | read_batch 50000 1000 | read_formatted numpy 5000 | read_formatted pandas 5000 | read_formatted tensorflow 5000 | read_formatted torch 5000 | read_formatted_batch numpy 5000 10 | read_formatted_batch numpy 5000 1000 | shuffled read 5000 | shuffled read 50000 | shuffled read_batch 50000 10 | shuffled read_batch 50000 100 | shuffled read_batch 50000 1000 | shuffled read_formatted numpy 5000 | shuffled read_formatted_batch numpy 5000 10 | shuffled read_formatted_batch numpy 5000 1000 |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.474688 / 0.215209 (0.259479) | 4.743223 / 2.077655 (2.665569) | 2.163107 / 1.504120 (0.658988) | 1.946396 / 1.541195 (0.405201) | 2.057538 / 1.468490 (0.589047) | 0.618836 / 4.584777 (-3.965941) | 4.605934 / 3.745712 (0.860222) | 2.201537 / 5.269862 (-3.068324) | 1.275758 / 4.565676 (-3.289919) | 0.077782 / 0.424275 (-0.346493) | 0.014830 / 0.007607 (0.007223) | 0.593372 / 0.226044 (0.367328) | 5.927000 / 2.268929 (3.658072) | 2.687293 / 55.444624 (-52.757331) | 2.301797 / 6.876477 (-4.574679) | 2.489928 / 2.142072 (0.347856) | 0.756779 / 4.805227 (-4.048449) | 0.168065 / 6.500664 (-6.332600) | 0.077276 / 0.075469 (0.001807) |\n\n### Benchmark: benchmark_map_filter.json\n\n| metric | filter | map fast-tokenizer batched | map identity | map identity batched | map no-op batched | map no-op batched numpy | map no-op batched pandas | map no-op batched pytorch | map no-op batched tensorflow |\n|--------|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 1.608169 / 1.841788 (-0.233619) | 19.048790 / 8.074308 (10.974482) | 16.100228 / 10.191392 (5.908836) | 0.215346 / 0.680424 (-0.465077) | 0.022293 / 0.534201 (-0.511907) | 0.535899 / 0.579283 (-0.043384) | 0.533729 / 0.434364 (0.099365) | 0.562697 / 0.540337 (0.022360) | 0.764082 / 1.386936 (-0.622854) |\n\n</details>\nPyArrow==latest\n\n<details>\n<summary>Show updated benchmarks!</summary>\n\n### Benchmark: benchmark_array_xd.json\n\n| metric | read_batch_formatted_as_numpy after write_array2d | read_batch_formatted_as_numpy after write_flattened_sequence | read_batch_formatted_as_numpy after write_nested_sequence | read_batch_unformated after write_array2d | read_batch_unformated after write_flattened_sequence | read_batch_unformated after write_nested_sequence | read_col_formatted_as_numpy after write_array2d | read_col_formatted_as_numpy after write_flattened_sequence | read_col_formatted_as_numpy after write_nested_sequence | read_col_unformated after write_array2d | read_col_unformated after write_flattened_sequence | read_col_unformated after write_nested_sequence | read_formatted_as_numpy after write_array2d | read_formatted_as_numpy after write_flattened_sequence | read_formatted_as_numpy after write_nested_sequence | read_unformated after write_array2d | read_unformated after write_flattened_sequence | read_unformated after write_nested_sequence | write_array2d | write_flattened_sequence | write_nested_sequence |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.010087 / 0.011353 (-0.001266) | 0.005357 / 0.011008 (-0.005651) | 0.092678 / 0.038508 (0.054170) | 0.041207 / 0.023109 (0.018098) | 0.437464 / 0.275898 (0.161566) | 0.527867 / 0.323480 (0.204387) | 0.006861 / 0.007986 (-0.001125) | 0.006131 / 0.004328 (0.001802) | 0.093741 / 0.004250 (0.089490) | 0.064142 / 0.037052 (0.027090) | 0.433577 / 0.258489 (0.175088) | 0.537148 / 0.293841 (0.243307) | 0.035339 / 0.128546 (-0.093207) | 0.010432 / 0.075646 (-0.065214) | 0.102838 / 0.419271 (-0.316434) | 0.057905 / 0.043533 (0.014372) | 0.437956 / 0.255139 (0.182817) | 0.509562 / 0.283200 (0.226362) | 0.120620 / 0.141683 (-0.021063) | 1.798686 / 1.452155 (0.346531) | 2.013290 / 1.492716 (0.520574) |\n\n### Benchmark: benchmark_getitem\\_100B.json\n\n| metric | get_batch_of\\_1024\\_random_rows | get_batch_of\\_1024\\_rows | get_first_row | get_last_row |\n|--------|---|---|---|---|\n| new / old (diff) | 0.249067 / 0.018006 (0.231061) | 0.462219 / 0.000490 (0.461729) | 0.000476 / 0.000200 (0.000276) | 0.000068 / 0.000054 (0.000013) |\n\n### Benchmark: benchmark_indices_mapping.json\n\n| metric | select | shard | shuffle | sort | train_test_split |\n|--------|---|---|---|---|---|\n| new / old (diff) | 0.033988 / 0.037411 (-0.003424) | 0.135863 / 0.014526 (0.121337) | 0.144082 / 0.176557 (-0.032474) | 0.201715 / 0.737135 (-0.535421) | 0.152079 / 0.296338 (-0.144259) |\n\n### Benchmark: benchmark_iterating.json\n\n| metric | read 5000 | read 50000 | read_batch 50000 10 | read_batch 50000 100 | read_batch 50000 1000 | read_formatted numpy 5000 | read_formatted pandas 5000 | read_formatted tensorflow 5000 | read_formatted torch 5000 | read_formatted_batch numpy 5000 10 | read_formatted_batch numpy 5000 1000 | shuffled read 5000 | shuffled read 50000 | shuffled read_batch 50000 10 | shuffled read_batch 50000 100 | shuffled read_batch 50000 1000 | shuffled read_formatted numpy 5000 | shuffled read_formatted_batch numpy 5000 10 | shuffled read_formatted_batch numpy 5000 1000 |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.522820 / 0.215209 (0.307611) | 5.216723 / 2.077655 (3.139068) | 2.582355 / 1.504120 (1.078235) | 2.352799 / 1.541195 (0.811604) | 2.451943 / 1.468490 (0.983453) | 0.620381 / 4.584777 (-3.964396) | 4.537841 / 3.745712 (0.792129) | 2.206431 / 5.269862 (-3.063431) | 1.269865 / 4.565676 (-3.295811) | 0.078744 / 0.424275 (-0.345531) | 0.014375 / 0.007607 (0.006768) | 0.648215 / 0.226044 (0.422171) | 6.482809 / 2.268929 (4.213881) | 3.210670 / 55.444624 (-52.233954) | 2.847485 / 6.876477 (-4.028992) | 2.820946 / 2.142072 (0.678873) | 0.762711 / 4.805227 (-4.042516) | 0.171235 / 6.500664 (-6.329429) | 0.080230 / 0.075469 (0.004761) |\n\n### Benchmark: benchmark_map_filter.json\n\n| metric | filter | map fast-tokenizer batched | map identity | map identity batched | map no-op batched | map no-op batched numpy | map no-op batched pandas | map no-op batched pytorch | map no-op batched tensorflow |\n|--------|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 1.646840 / 1.841788 (-0.194948) | 19.400451 / 8.074308 (11.326142) | 16.758845 / 10.191392 (6.567453) | 0.171377 / 0.680424 (-0.509046) | 0.020400 / 0.534201 (-0.513801) | 0.467675 / 0.579283 (-0.111608) | 0.529745 / 0.434364 (0.095381) | 0.605989 / 0.540337 (0.065652) | 0.694659 / 1.386936 (-0.692277) |\n\n</details>\n</details>\n\n![](https://cml.dev/watermark.png#006bf33ac5c308f9c70f4df4868abd539eb6c366 "CML watermark")\n', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1570253259/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1570254673', 'html_url': 'https://github.com/huggingface/datasets/pull/5909#issuecomment-1570254673', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5909', 'id': 1570254673, 'node_id': 'IC_kwDODunzps5dmC9R', 'user': {'login': 'mariosasko', 'id': 47462742, 'node_id': 'MDQ6VXNlcjQ3NDYyNzQy', 'avatar_url': 'https://avatars.githubusercontent.com/u/47462742?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/mariosasko', 'html_url': 'https://github.com/mariosasko', 'followers_url': 'https://api.github.com/users/mariosasko/followers', 'following_url': 'https://api.github.com/users/mariosasko/following{/other_user}', 'gists_url': 'https://api.github.com/users/mariosasko/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/mariosasko/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/mariosasko/subscriptions', 'organizations_url': 'https://api.github.com/users/mariosasko/orgs', 'repos_url': 'https://api.github.com/users/mariosasko/repos', 'events_url': 'https://api.github.com/users/mariosasko/events{/privacy}', 'received_events_url': 'https://api.github.com/users/mariosasko/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-05-31T13:37:43Z', 'updated_at': '2023-05-31T13:37:43Z', 'author_association': 'CONTRIBUTOR', 'body': "It's faster because all the items are the same object, but this also means modifying one of them will alter each unless these items are immutable, and they are in this case (tuples). So we should be careful when using this idiom.", 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1570254673/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}]

[{'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1568819853', 'html_url': 'https://github.com/huggingface/datasets/issues/5908#issuecomment-1568819853', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5908', 'id': 1568819853, 'node_id': 'IC_kwDODunzps5dgkqN', 'user': {'login': 'lhoestq', 'id': 42851186, 'node_id': 'MDQ6VXNlcjQyODUxMTg2', 'avatar_url': 'https://avatars.githubusercontent.com/u/42851186?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/lhoestq', 'html_url': 'https://github.com/lhoestq', 'followers_url': 'https://api.github.com/users/lhoestq/followers', 'following_url': 'https://api.github.com/users/lhoestq/following{/other_user}', 'gists_url': 'https://api.github.com/users/lhoestq/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/lhoestq/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/lhoestq/subscriptions', 'organizations_url': 'https://api.github.com/users/lhoestq/orgs', 'repos_url': 'https://api.github.com/users/lhoestq/repos', 'events_url': 'https://api.github.com/users/lhoestq/events{/privacy}', 'received_events_url': 'https://api.github.com/users/lhoestq/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-05-30T17:37:48Z', 'updated_at': '2023-05-30T17:38:13Z', 'author_association': 'MEMBER', 'body': "Hi ! `shard` currently returns a slow dataset by default, with examples evenly distributed in the dataset.\r\n\r\nYou can get a fast dataset using `contiguous=True` (which should be the default imo):\r\n\r\n```python\r\ndataset = dataset.shard(10, 0, contiguous=True)\r\n```\r\n\r\nThis way you don't need to flatten_indices() and sort should be fast as well", 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1568819853/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1589299018', 'html_url': 'https://github.com/huggingface/datasets/issues/5908#issuecomment-1589299018', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5908', 'id': 1589299018, 'node_id': 'IC_kwDODunzps5eusdK', 'user': {'login': 'mariosasko', 'id': 47462742, 'node_id': 'MDQ6VXNlcjQ3NDYyNzQy', 'avatar_url': 'https://avatars.githubusercontent.com/u/47462742?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/mariosasko', 'html_url': 'https://github.com/mariosasko', 'followers_url': 'https://api.github.com/users/mariosasko/followers', 'following_url': 'https://api.github.com/users/mariosasko/following{/other_user}', 'gists_url': 'https://api.github.com/users/mariosasko/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/mariosasko/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/mariosasko/subscriptions', 'organizations_url': 'https://api.github.com/users/mariosasko/orgs', 'repos_url': 'https://api.github.com/users/mariosasko/repos', 'events_url': 'https://api.github.com/users/mariosasko/events{/privacy}', 'received_events_url': 'https://api.github.com/users/mariosasko/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-13T13:17:38Z', 'updated_at': '2023-06-13T13:17:38Z', 'author_association': 'CONTRIBUTOR', 'body': "@lhoestq \r\n\r\n> contiguous=True (which should be the default imo)\r\n\r\nFor `IterableDataset`, it's not possible to implement contiguous sharding without knowing the number of examples in advance, so setting the default value to `contiguous=True` would result in an inconsistency between `Dataset` and `IterableDataset` (when we add `IterableDataset.shard`)", 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1589299018/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1589627337', 'html_url': 'https://github.com/huggingface/datasets/issues/5908#issuecomment-1589627337', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5908', 'id': 1589627337, 'node_id': 'IC_kwDODunzps5ev8nJ', 'user': {'login': 'lhoestq', 'id': 42851186, 'node_id': 'MDQ6VXNlcjQyODUxMTg2', 'avatar_url': 'https://avatars.githubusercontent.com/u/42851186?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/lhoestq', 'html_url': 'https://github.com/lhoestq', 'followers_url': 'https://api.github.com/users/lhoestq/followers', 'following_url': 'https://api.github.com/users/lhoestq/following{/other_user}', 'gists_url': 'https://api.github.com/users/lhoestq/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/lhoestq/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/lhoestq/subscriptions', 'organizations_url': 'https://api.github.com/users/lhoestq/orgs', 'repos_url': 'https://api.github.com/users/lhoestq/repos', 'events_url': 'https://api.github.com/users/lhoestq/events{/privacy}', 'received_events_url': 'https://api.github.com/users/lhoestq/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-13T16:16:15Z', 'updated_at': '2023-06-13T16:16:15Z', 'author_association': 'MEMBER', 'body': "Actually sharded iterable datasets are made of sub iterables that generally yield contiguous data no ? So in a way it's possible to shard an iterable dataset contiguously.\r\n\r\nIf the dataset is made of one shard it's indeed not possible to shard it contiguously though", 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1589627337/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1589685953', 'html_url': 'https://github.com/huggingface/datasets/issues/5908#issuecomment-1589685953', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5908', 'id': 1589685953, 'node_id': 'IC_kwDODunzps5ewK7B', 'user': {'login': 'mariosasko', 'id': 47462742, 'node_id': 'MDQ6VXNlcjQ3NDYyNzQy', 'avatar_url': 'https://avatars.githubusercontent.com/u/47462742?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/mariosasko', 'html_url': 'https://github.com/mariosasko', 'followers_url': 'https://api.github.com/users/mariosasko/followers', 'following_url': 'https://api.github.com/users/mariosasko/following{/other_user}', 'gists_url': 'https://api.github.com/users/mariosasko/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/mariosasko/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/mariosasko/subscriptions', 'organizations_url': 'https://api.github.com/users/mariosasko/orgs', 'repos_url': 'https://api.github.com/users/mariosasko/repos', 'events_url': 'https://api.github.com/users/mariosasko/events{/privacy}', 'received_events_url': 'https://api.github.com/users/mariosasko/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-13T16:51:53Z', 'updated_at': '2023-06-13T16:51:53Z', 'author_association': 'CONTRIBUTOR', 'body': "> Actually sharded iterable datasets are made of sub iterables that generally yield contiguous data no ? So in a way it's possible to shard an iterable dataset contiguously.\r\n\r\nBut sharding an iterable dataset by sharding its `gen_kwargs` would still yield approximate shards(not equal to `Dataset.shard`), no? ", 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1589685953/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1589730759', 'html_url': 'https://github.com/huggingface/datasets/issues/5908#issuecomment-1589730759', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5908', 'id': 1589730759, 'node_id': 'IC_kwDODunzps5ewV3H', 'user': {'login': 'lhoestq', 'id': 42851186, 'node_id': 'MDQ6VXNlcjQyODUxMTg2', 'avatar_url': 'https://avatars.githubusercontent.com/u/42851186?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/lhoestq', 'html_url': 'https://github.com/lhoestq', 'followers_url': 'https://api.github.com/users/lhoestq/followers', 'following_url': 'https://api.github.com/users/lhoestq/following{/other_user}', 'gists_url': 'https://api.github.com/users/lhoestq/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/lhoestq/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/lhoestq/subscriptions', 'organizations_url': 'https://api.github.com/users/lhoestq/orgs', 'repos_url': 'https://api.github.com/users/lhoestq/repos', 'events_url': 'https://api.github.com/users/lhoestq/events{/privacy}', 'received_events_url': 'https://api.github.com/users/lhoestq/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-13T17:24:29Z', 'updated_at': '2023-06-13T17:24:29Z', 'author_association': 'MEMBER', 'body': 'Yes indeed !', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1589730759/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1589764375', 'html_url': 'https://github.com/huggingface/datasets/issues/5908#issuecomment-1589764375', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5908', 'id': 1589764375, 'node_id': 'IC_kwDODunzps5eweEX', 'user': {'login': 'maximxlss', 'id': 29152154, 'node_id': 'MDQ6VXNlcjI5MTUyMTU0', 'avatar_url': 'https://avatars.githubusercontent.com/u/29152154?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/maximxlss', 'html_url': 'https://github.com/maximxlss', 'followers_url': 'https://api.github.com/users/maximxlss/followers', 'following_url': 'https://api.github.com/users/maximxlss/following{/other_user}', 'gists_url': 'https://api.github.com/users/maximxlss/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/maximxlss/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/maximxlss/subscriptions', 'organizations_url': 'https://api.github.com/users/maximxlss/orgs', 'repos_url': 'https://api.github.com/users/maximxlss/repos', 'events_url': 'https://api.github.com/users/maximxlss/events{/privacy}', 'received_events_url': 'https://api.github.com/users/maximxlss/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-13T17:45:10Z', 'updated_at': '2023-06-13T17:45:10Z', 'author_association': 'CONTRIBUTOR', 'body': "I understand the issue doesn't exist with non-mapped datasets, but if flattening is so much more efficient than sorting the indices, that's an issue in itself.\n\nThere are plenty of issues people posted for which the root cause turns out to be the same. It seems like mapped datasets are terribly inefficient. I think I saw some issue like that somewhere (about the mapped datasets in general), but can't find it now.\n\nMaybe indices should be flattened before any additional processing, then.", 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1589764375/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}]

[{'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1570264313', 'html_url': 'https://github.com/huggingface/datasets/pull/5907#issuecomment-1570264313', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5907', 'id': 1570264313, 'node_id': 'IC_kwDODunzps5dmFT5', 'user': {'login': 'HuggingFaceDocBuilderDev', 'id': 99929124, 'node_id': 'U_kgDOBfTMJA', 'avatar_url': 'https://avatars.githubusercontent.com/u/99929124?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/HuggingFaceDocBuilderDev', 'html_url': 'https://github.com/HuggingFaceDocBuilderDev', 'followers_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/followers', 'following_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/following{/other_user}', 'gists_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/subscriptions', 'organizations_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/orgs', 'repos_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/repos', 'events_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/events{/privacy}', 'received_events_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-05-31T13:43:41Z', 'updated_at': '2023-06-01T11:42:42Z', 'author_association': 'NONE', 'body': '_The documentation is not available anymore as the PR was closed or merged._', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1570264313/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1571900072', 'html_url': 'https://github.com/huggingface/datasets/pull/5907#issuecomment-1571900072', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5907', 'id': 1571900072, 'node_id': 'IC_kwDODunzps5dsUqo', 'user': {'login': 'github-actions[bot]', 'id': 41898282, 'node_id': 'MDM6Qm90NDE4OTgyODI=', 'avatar_url': 'https://avatars.githubusercontent.com/in/15368?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/github-actions%5Bbot%5D', 'html_url': 'https://github.com/apps/github-actions', 'followers_url': 'https://api.github.com/users/github-actions%5Bbot%5D/followers', 'following_url': 'https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}', 'gists_url': 'https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/github-actions%5Bbot%5D/subscriptions', 'organizations_url': 'https://api.github.com/users/github-actions%5Bbot%5D/orgs', 'repos_url': 'https://api.github.com/users/github-actions%5Bbot%5D/repos', 'events_url': 'https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}', 'received_events_url': 'https://api.github.com/users/github-actions%5Bbot%5D/received_events', 'type': 'Bot', 'site_admin': False}, 'created_at': '2023-06-01T11:46:35Z', 'updated_at': '2023-06-01T11:46:35Z', 'author_association': 'NONE', 'body': '<details>\n<summary>Show benchmarks</summary>\n\nPyArrow==8.0.0\n\n<details>\n<summary>Show updated benchmarks!</summary>\n\n### Benchmark: benchmark_array_xd.json\n\n| metric | read_batch_formatted_as_numpy after write_array2d | read_batch_formatted_as_numpy after write_flattened_sequence | read_batch_formatted_as_numpy after write_nested_sequence | read_batch_unformated after write_array2d | read_batch_unformated after write_flattened_sequence | read_batch_unformated after write_nested_sequence | read_col_formatted_as_numpy after write_array2d | read_col_formatted_as_numpy after write_flattened_sequence | read_col_formatted_as_numpy after write_nested_sequence | read_col_unformated after write_array2d | read_col_unformated after write_flattened_sequence | read_col_unformated after write_nested_sequence | read_formatted_as_numpy after write_array2d | read_formatted_as_numpy after write_flattened_sequence | read_formatted_as_numpy after write_nested_sequence | read_unformated after write_array2d | read_unformated after write_flattened_sequence | read_unformated after write_nested_sequence | write_array2d | write_flattened_sequence | write_nested_sequence |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.006192 / 0.011353 (-0.005161) | 0.004410 / 0.011008 (-0.006598) | 0.095990 / 0.038508 (0.057482) | 0.032662 / 0.023109 (0.009553) | 0.322827 / 0.275898 (0.046929) | 0.352542 / 0.323480 (0.029062) | 0.005398 / 0.007986 (-0.002588) | 0.003926 / 0.004328 (-0.000403) | 0.075131 / 0.004250 (0.070880) | 0.046205 / 0.037052 (0.009153) | 0.330957 / 0.258489 (0.072468) | 0.360166 / 0.293841 (0.066325) | 0.027880 / 0.128546 (-0.100666) | 0.008813 / 0.075646 (-0.066833) | 0.327316 / 0.419271 (-0.091955) | 0.050071 / 0.043533 (0.006539) | 0.319939 / 0.255139 (0.064800) | 0.331593 / 0.283200 (0.048393) | 0.096745 / 0.141683 (-0.044938) | 1.445165 / 1.452155 (-0.006990) | 1.515538 / 1.492716 (0.022821) |\n\n### Benchmark: benchmark_getitem\\_100B.json\n\n| metric | get_batch_of\\_1024\\_random_rows | get_batch_of\\_1024\\_rows | get_first_row | get_last_row |\n|--------|---|---|---|---|\n| new / old (diff) | 0.209365 / 0.018006 (0.191358) | 0.437007 / 0.000490 (0.436518) | 0.003207 / 0.000200 (0.003007) | 0.000088 / 0.000054 (0.000033) |\n\n### Benchmark: benchmark_indices_mapping.json\n\n| metric | select | shard | shuffle | sort | train_test_split |\n|--------|---|---|---|---|---|\n| new / old (diff) | 0.027261 / 0.037411 (-0.010151) | 0.105101 / 0.014526 (0.090575) | 0.117163 / 0.176557 (-0.059394) | 0.176237 / 0.737135 (-0.560898) | 0.122559 / 0.296338 (-0.173779) |\n\n### Benchmark: benchmark_iterating.json\n\n| metric | read 5000 | read 50000 | read_batch 50000 10 | read_batch 50000 100 | read_batch 50000 1000 | read_formatted numpy 5000 | read_formatted pandas 5000 | read_formatted tensorflow 5000 | read_formatted torch 5000 | read_formatted_batch numpy 5000 10 | read_formatted_batch numpy 5000 1000 | shuffled read 5000 | shuffled read 50000 | shuffled read_batch 50000 10 | shuffled read_batch 50000 100 | shuffled read_batch 50000 1000 | shuffled read_formatted numpy 5000 | shuffled read_formatted_batch numpy 5000 10 | shuffled read_formatted_batch numpy 5000 1000 |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.406792 / 0.215209 (0.191583) | 4.060831 / 2.077655 (1.983176) | 1.829691 / 1.504120 (0.325571) | 1.633155 / 1.541195 (0.091960) | 1.704817 / 1.468490 (0.236327) | 0.525325 / 4.584777 (-4.059452) | 3.752907 / 3.745712 (0.007194) | 1.857513 / 5.269862 (-3.412349) | 1.222237 / 4.565676 (-3.343439) | 0.065941 / 0.424275 (-0.358334) | 0.012498 / 0.007607 (0.004891) | 0.495009 / 0.226044 (0.268965) | 4.968074 / 2.268929 (2.699145) | 2.277898 / 55.444624 (-53.166727) | 1.936656 / 6.876477 (-4.939821) | 1.970698 / 2.142072 (-0.171374) | 0.635221 / 4.805227 (-4.170006) | 0.140539 / 6.500664 (-6.360125) | 0.064111 / 0.075469 (-0.011358) |\n\n### Benchmark: benchmark_map_filter.json\n\n| metric | filter | map fast-tokenizer batched | map identity | map identity batched | map no-op batched | map no-op batched numpy | map no-op batched pandas | map no-op batched pytorch | map no-op batched tensorflow |\n|--------|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 1.238151 / 1.841788 (-0.603637) | 14.681262 / 8.074308 (6.606954) | 13.405525 / 10.191392 (3.214133) | 0.163225 / 0.680424 (-0.517199) | 0.017282 / 0.534201 (-0.516918) | 0.395526 / 0.579283 (-0.183757) | 0.429156 / 0.434364 (-0.005208) | 0.470806 / 0.540337 (-0.069531) | 0.571290 / 1.386936 (-0.815646) |\n\n</details>\nPyArrow==latest\n\n<details>\n<summary>Show updated benchmarks!</summary>\n\n### Benchmark: benchmark_array_xd.json\n\n| metric | read_batch_formatted_as_numpy after write_array2d | read_batch_formatted_as_numpy after write_flattened_sequence | read_batch_formatted_as_numpy after write_nested_sequence | read_batch_unformated after write_array2d | read_batch_unformated after write_flattened_sequence | read_batch_unformated after write_nested_sequence | read_col_formatted_as_numpy after write_array2d | read_col_formatted_as_numpy after write_flattened_sequence | read_col_formatted_as_numpy after write_nested_sequence | read_col_unformated after write_array2d | read_col_unformated after write_flattened_sequence | read_col_unformated after write_nested_sequence | read_formatted_as_numpy after write_array2d | read_formatted_as_numpy after write_flattened_sequence | read_formatted_as_numpy after write_nested_sequence | read_unformated after write_array2d | read_unformated after write_flattened_sequence | read_unformated after write_nested_sequence | write_array2d | write_flattened_sequence | write_nested_sequence |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.006444 / 0.011353 (-0.004909) | 0.004388 / 0.011008 (-0.006621) | 0.075004 / 0.038508 (0.036496) | 0.032904 / 0.023109 (0.009795) | 0.375360 / 0.275898 (0.099462) | 0.413684 / 0.323480 (0.090204) | 0.005854 / 0.007986 (-0.002132) | 0.005504 / 0.004328 (0.001175) | 0.075049 / 0.004250 (0.070799) | 0.047973 / 0.037052 (0.010920) | 0.377943 / 0.258489 (0.119454) | 0.427039 / 0.293841 (0.133198) | 0.028248 / 0.128546 (-0.100298) | 0.008972 / 0.075646 (-0.066674) | 0.081848 / 0.419271 (-0.337424) | 0.047935 / 0.043533 (0.004402) | 0.377980 / 0.255139 (0.122841) | 0.407856 / 0.283200 (0.124656) | 0.103454 / 0.141683 (-0.038229) | 1.469051 / 1.452155 (0.016896) | 1.590657 / 1.492716 (0.097941) |\n\n### Benchmark: benchmark_getitem\\_100B.json\n\n| metric | get_batch_of\\_1024\\_random_rows | get_batch_of\\_1024\\_rows | get_first_row | get_last_row |\n|--------|---|---|---|---|\n| new / old (diff) | 0.192380 / 0.018006 (0.174374) | 0.440995 / 0.000490 (0.440505) | 0.004082 / 0.000200 (0.003882) | 0.000096 / 0.000054 (0.000042) |\n\n### Benchmark: benchmark_indices_mapping.json\n\n| metric | select | shard | shuffle | sort | train_test_split |\n|--------|---|---|---|---|---|\n| new / old (diff) | 0.029584 / 0.037411 (-0.007828) | 0.110051 / 0.014526 (0.095525) | 0.121196 / 0.176557 (-0.055361) | 0.172249 / 0.737135 (-0.564886) | 0.125380 / 0.296338 (-0.170958) |\n\n### Benchmark: benchmark_iterating.json\n\n| metric | read 5000 | read 50000 | read_batch 50000 10 | read_batch 50000 100 | read_batch 50000 1000 | read_formatted numpy 5000 | read_formatted pandas 5000 | read_formatted tensorflow 5000 | read_formatted torch 5000 | read_formatted_batch numpy 5000 10 | read_formatted_batch numpy 5000 1000 | shuffled read 5000 | shuffled read 50000 | shuffled read_batch 50000 10 | shuffled read_batch 50000 100 | shuffled read_batch 50000 1000 | shuffled read_formatted numpy 5000 | shuffled read_formatted_batch numpy 5000 10 | shuffled read_formatted_batch numpy 5000 1000 |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.435218 / 0.215209 (0.220009) | 4.354811 / 2.077655 (2.277156) | 2.102050 / 1.504120 (0.597930) | 1.913454 / 1.541195 (0.372260) | 1.974624 / 1.468490 (0.506134) | 0.529975 / 4.584777 (-4.054802) | 3.801605 / 3.745712 (0.055893) | 3.162408 / 5.269862 (-2.107454) | 1.599576 / 4.565676 (-2.966101) | 0.066710 / 0.424275 (-0.357565) | 0.012158 / 0.007607 (0.004551) | 0.549187 / 0.226044 (0.323142) | 5.489930 / 2.268929 (3.221002) | 2.646787 / 55.444624 (-52.797837) | 2.311915 / 6.876477 (-4.564562) | 2.335645 / 2.142072 (0.193572) | 0.641067 / 4.805227 (-4.164160) | 0.142227 / 6.500664 (-6.358437) | 0.065303 / 0.075469 (-0.010166) |\n\n### Benchmark: benchmark_map_filter.json\n\n| metric | filter | map fast-tokenizer batched | map identity | map identity batched | map no-op batched | map no-op batched numpy | map no-op batched pandas | map no-op batched pytorch | map no-op batched tensorflow |\n|--------|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 1.283209 / 1.841788 (-0.558579) | 15.241809 / 8.074308 (7.167501) | 14.131471 / 10.191392 (3.940079) | 0.143921 / 0.680424 (-0.536503) | 0.017497 / 0.534201 (-0.516704) | 0.402236 / 0.579283 (-0.177047) | 0.418917 / 0.434364 (-0.015447) | 0.461745 / 0.540337 (-0.078593) | 0.560212 / 1.386936 (-0.826724) |\n\n</details>\n</details>\n\n![](https://cml.dev/watermark.png#7098922130cabfbfa6b8a3885ff2e6f032d6203d "CML watermark")\n', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1571900072/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}]

[]
[{'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1593076819', 'html_url': 'https://github.com/huggingface/datasets/issues/5905#issuecomment-1593076819', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5905', 'id': 1593076819, 'node_id': 'IC_kwDODunzps5e9GxT', 'user': {'login': 'mariosasko', 'id': 47462742, 'node_id': 'MDQ6VXNlcjQ3NDYyNzQy', 'avatar_url': 'https://avatars.githubusercontent.com/u/47462742?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/mariosasko', 'html_url': 'https://github.com/mariosasko', 'followers_url': 'https://api.github.com/users/mariosasko/followers', 'following_url': 'https://api.github.com/users/mariosasko/following{/other_user}', 'gists_url': 'https://api.github.com/users/mariosasko/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/mariosasko/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/mariosasko/subscriptions', 'organizations_url': 'https://api.github.com/users/mariosasko/orgs', 'repos_url': 'https://api.github.com/users/mariosasko/repos', 'events_url': 'https://api.github.com/users/mariosasko/events{/privacy}', 'received_events_url': 'https://api.github.com/users/mariosasko/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-15T13:34:17Z', 'updated_at': '2023-06-15T13:34:17Z', 'author_association': 'CONTRIBUTOR', 'body': 'We plan to improve this eventually (see https://github.com/huggingface/datasets/issues/5454 and https://github.com/huggingface/datasets/issues/5380).\r\n\r\n> Is it possible to lazily load samples of a mapped dataset ? I\'m used to [dataset scripts](https://huggingface.co/docs/datasets/dataset_script), maybe something can be done there.\r\nIf not, I could do it using a plain Pytorch dataset. Then I would need to convert it to a datasets\' dataset to get all the features of datasets. Is it something possible ?\r\n\r\nYes, by creating a mapped dataset that stores audio URLs. Indexing a dataset in such format only downloads and decodes the bytes of the accessed samples (without storing them on disk).\r\n\r\nYou can do the following to create this dataset:\r\n```python\r\n\r\ndef gen():\r\n    # Generator that yields (audio URL, text) pairs as dict\r\n    ...\r\n    yield {"audio": "audio_url", "text": "some text"}\r\n\r\nfeatures = Features({"audio": datasets.Audio(), "text": datasets.Value("string")})\r\nds = Dataset.from_generator(gen, features=features)\r\nds[2:5] # downloads and decodes the samples each time they are accessed\r\n```', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1593076819/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}]
[{'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1564237630', 'html_url': 'https://github.com/huggingface/datasets/pull/5904#issuecomment-1564237630', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5904', 'id': 1564237630, 'node_id': 'IC_kwDODunzps5dPF8-', 'user': {'login': 'HuggingFaceDocBuilderDev', 'id': 99929124, 'node_id': 'U_kgDOBfTMJA', 'avatar_url': 'https://avatars.githubusercontent.com/u/99929124?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/HuggingFaceDocBuilderDev', 'html_url': 'https://github.com/HuggingFaceDocBuilderDev', 'followers_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/followers', 'following_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/following{/other_user}', 'gists_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/subscriptions', 'organizations_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/orgs', 'repos_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/repos', 'events_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/events{/privacy}', 'received_events_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-05-26T11:17:19Z', 'updated_at': '2023-05-31T07:38:35Z', 'author_association': 'NONE', 'body': '_The documentation is not available anymore as the PR was closed or merged._', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1564237630/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1569663975', 'html_url': 'https://github.com/huggingface/datasets/pull/5904#issuecomment-1569663975', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5904', 'id': 1569663975, 'node_id': 'IC_kwDODunzps5djyvn', 'user': {'login': 'github-actions[bot]', 'id': 41898282, 'node_id': 'MDM6Qm90NDE4OTgyODI=', 'avatar_url': 'https://avatars.githubusercontent.com/in/15368?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/github-actions%5Bbot%5D', 'html_url': 'https://github.com/apps/github-actions', 'followers_url': 'https://api.github.com/users/github-actions%5Bbot%5D/followers', 'following_url': 'https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}', 'gists_url': 'https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/github-actions%5Bbot%5D/subscriptions', 'organizations_url': 'https://api.github.com/users/github-actions%5Bbot%5D/orgs', 'repos_url': 'https://api.github.com/users/github-actions%5Bbot%5D/repos', 'events_url': 'https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}', 'received_events_url': 'https://api.github.com/users/github-actions%5Bbot%5D/received_events', 'type': 'Bot', 'site_admin': False}, 'created_at': '2023-05-31T07:43:32Z', 'updated_at': '2023-05-31T07:43:32Z', 'author_association': 'NONE', 'body': '<details>\n<summary>Show benchmarks</summary>\n\nPyArrow==8.0.0\n\n<details>\n<summary>Show updated benchmarks!</summary>\n\n### Benchmark: benchmark_array_xd.json\n\n| metric | read_batch_formatted_as_numpy after write_array2d | read_batch_formatted_as_numpy after write_flattened_sequence | read_batch_formatted_as_numpy after write_nested_sequence | read_batch_unformated after write_array2d | read_batch_unformated after write_flattened_sequence | read_batch_unformated after write_nested_sequence | read_col_formatted_as_numpy after write_array2d | read_col_formatted_as_numpy after write_flattened_sequence | read_col_formatted_as_numpy after write_nested_sequence | read_col_unformated after write_array2d | read_col_unformated after write_flattened_sequence | read_col_unformated after write_nested_sequence | read_formatted_as_numpy after write_array2d | read_formatted_as_numpy after write_flattened_sequence | read_formatted_as_numpy after write_nested_sequence | read_unformated after write_array2d | read_unformated after write_flattened_sequence | read_unformated after write_nested_sequence | write_array2d | write_flattened_sequence | write_nested_sequence |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.007401 / 0.011353 (-0.003952) | 0.005198 / 0.011008 (-0.005810) | 0.112317 / 0.038508 (0.073809) | 0.038406 / 0.023109 (0.015297) | 0.358008 / 0.275898 (0.082110) | 0.395350 / 0.323480 (0.071870) | 0.006201 / 0.007986 (-0.001785) | 0.004368 / 0.004328 (0.000039) | 0.087718 / 0.004250 (0.083467) | 0.055299 / 0.037052 (0.018247) | 0.350481 / 0.258489 (0.091992) | 0.419876 / 0.293841 (0.126035) | 0.032459 / 0.128546 (-0.096087) | 0.010635 / 0.075646 (-0.065011) | 0.383282 / 0.419271 (-0.035989) | 0.059241 / 0.043533 (0.015708) | 0.365101 / 0.255139 (0.109962) | 0.378144 / 0.283200 (0.094944) | 0.114287 / 0.141683 (-0.027396) | 1.680870 / 1.452155 (0.228715) | 1.788183 / 1.492716 (0.295467) |\n\n### Benchmark: benchmark_getitem\\_100B.json\n\n| metric | get_batch_of\\_1024\\_random_rows | get_batch_of\\_1024\\_rows | get_first_row | get_last_row |\n|--------|---|---|---|---|\n| new / old (diff) | 0.242919 / 0.018006 (0.224913) | 0.489850 / 0.000490 (0.489360) | 0.011408 / 0.000200 (0.011208) | 0.000444 / 0.000054 (0.000389) |\n\n### Benchmark: benchmark_indices_mapping.json\n\n| metric | select | shard | shuffle | sort | train_test_split |\n|--------|---|---|---|---|---|\n| new / old (diff) | 0.030742 / 0.037411 (-0.006669) | 0.123092 / 0.014526 (0.108566) | 0.138246 / 0.176557 (-0.038311) | 0.207299 / 0.737135 (-0.529836) | 0.142647 / 0.296338 (-0.153691) |\n\n### Benchmark: benchmark_iterating.json\n\n| metric | read 5000 | read 50000 | read_batch 50000 10 | read_batch 50000 100 | read_batch 50000 1000 | read_formatted numpy 5000 | read_formatted pandas 5000 | read_formatted tensorflow 5000 | read_formatted torch 5000 | read_formatted_batch numpy 5000 10 | read_formatted_batch numpy 5000 1000 | shuffled read 5000 | shuffled read 50000 | shuffled read_batch 50000 10 | shuffled read_batch 50000 100 | shuffled read_batch 50000 1000 | shuffled read_formatted numpy 5000 | shuffled read_formatted_batch numpy 5000 10 | shuffled read_formatted_batch numpy 5000 1000 |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.472553 / 0.215209 (0.257344) | 4.671763 / 2.077655 (2.594108) | 2.119986 / 1.504120 (0.615866) | 1.891851 / 1.541195 (0.350656) | 1.979094 / 1.468490 (0.510604) | 0.617956 / 4.584777 (-3.966821) | 4.969418 / 3.745712 (1.223706) | 4.672083 / 5.269862 (-0.597779) | 2.119049 / 4.565676 (-2.446627) | 0.077466 / 0.424275 (-0.346809) | 0.014434 / 0.007607 (0.006827) | 0.580746 / 0.226044 (0.354701) | 5.805458 / 2.268929 (3.536530) | 2.622498 / 55.444624 (-52.822126) | 2.259499 / 6.876477 (-4.616978) | 2.362078 / 2.142072 (0.220006) | 0.719911 / 4.805227 (-4.085317) | 0.164939 / 6.500664 (-6.335725) | 0.074762 / 0.075469 (-0.000707) |\n\n### Benchmark: benchmark_map_filter.json\n\n| metric | filter | map fast-tokenizer batched | map identity | map identity batched | map no-op batched | map no-op batched numpy | map no-op batched pandas | map no-op batched pytorch | map no-op batched tensorflow |\n|--------|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 1.496709 / 1.841788 (-0.345079) | 18.247499 / 8.074308 (10.173191) | 15.397075 / 10.191392 (5.205683) | 0.181163 / 0.680424 (-0.499261) | 0.022604 / 0.534201 (-0.511597) | 0.462791 / 0.579283 (-0.116492) | 0.504473 / 0.434364 (0.070109) | 0.582254 / 0.540337 (0.041917) | 0.673849 / 1.386936 (-0.713087) |\n\n</details>\nPyArrow==latest\n\n<details>\n<summary>Show updated benchmarks!</summary>\n\n### Benchmark: benchmark_array_xd.json\n\n| metric | read_batch_formatted_as_numpy after write_array2d | read_batch_formatted_as_numpy after write_flattened_sequence | read_batch_formatted_as_numpy after write_nested_sequence | read_batch_unformated after write_array2d | read_batch_unformated after write_flattened_sequence | read_batch_unformated after write_nested_sequence | read_col_formatted_as_numpy after write_array2d | read_col_formatted_as_numpy after write_flattened_sequence | read_col_formatted_as_numpy after write_nested_sequence | read_col_unformated after write_array2d | read_col_unformated after write_flattened_sequence | read_col_unformated after write_nested_sequence | read_formatted_as_numpy after write_array2d | read_formatted_as_numpy after write_flattened_sequence | read_formatted_as_numpy after write_nested_sequence | read_unformated after write_array2d | read_unformated after write_flattened_sequence | read_unformated after write_nested_sequence | write_array2d | write_flattened_sequence | write_nested_sequence |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.007633 / 0.011353 (-0.003720) | 0.004859 / 0.011008 (-0.006149) | 0.091194 / 0.038508 (0.052686) | 0.038255 / 0.023109 (0.015146) | 0.460972 / 0.275898 (0.185074) | 0.470441 / 0.323480 (0.146961) | 0.006482 / 0.007986 (-0.001504) | 0.004500 / 0.004328 (0.000172) | 0.089998 / 0.004250 (0.085748) | 0.055470 / 0.037052 (0.018418) | 0.459188 / 0.258489 (0.200699) | 0.491255 / 0.293841 (0.197414) | 0.032200 / 0.128546 (-0.096346) | 0.010372 / 0.075646 (-0.065274) | 0.097429 / 0.419271 (-0.321843) | 0.052469 / 0.043533 (0.008936) | 0.452492 / 0.255139 (0.197353) | 0.475210 / 0.283200 (0.192010) | 0.116976 / 0.141683 (-0.024707) | 1.752742 / 1.452155 (0.300587) | 1.849535 / 1.492716 (0.356819) |\n\n### Benchmark: benchmark_getitem\\_100B.json\n\n| metric | get_batch_of\\_1024\\_random_rows | get_batch_of\\_1024\\_rows | get_first_row | get_last_row |\n|--------|---|---|---|---|\n| new / old (diff) | 0.229822 / 0.018006 (0.211816) | 0.472259 / 0.000490 (0.471770) | 0.000455 / 0.000200 (0.000255) | 0.000067 / 0.000054 (0.000013) |\n\n### Benchmark: benchmark_indices_mapping.json\n\n| metric | select | shard | shuffle | sort | train_test_split |\n|--------|---|---|---|---|---|\n| new / old (diff) | 0.033796 / 0.037411 (-0.003615) | 0.136151 / 0.014526 (0.121625) | 0.144015 / 0.176557 (-0.032542) | 0.199337 / 0.737135 (-0.537798) | 0.150024 / 0.296338 (-0.146315) |\n\n### Benchmark: benchmark_iterating.json\n\n| metric | read 5000 | read 50000 | read_batch 50000 10 | read_batch 50000 100 | read_batch 50000 1000 | read_formatted numpy 5000 | read_formatted pandas 5000 | read_formatted tensorflow 5000 | read_formatted torch 5000 | read_formatted_batch numpy 5000 10 | read_formatted_batch numpy 5000 1000 | shuffled read 5000 | shuffled read 50000 | shuffled read_batch 50000 10 | shuffled read_batch 50000 100 | shuffled read_batch 50000 1000 | shuffled read_formatted numpy 5000 | shuffled read_formatted_batch numpy 5000 10 | shuffled read_formatted_batch numpy 5000 1000 |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.522737 / 0.215209 (0.307528) | 5.165223 / 2.077655 (3.087568) | 2.630334 / 1.504120 (1.126214) | 2.392383 / 1.541195 (0.851188) | 2.488966 / 1.468490 (1.020476) | 0.608981 / 4.584777 (-3.975796) | 4.711545 / 3.745712 (0.965833) | 2.121537 / 5.269862 (-3.148325) | 1.205477 / 4.565676 (-3.360199) | 0.078277 / 0.424275 (-0.345998) | 0.014175 / 0.007607 (0.006568) | 0.640720 / 0.226044 (0.414675) | 6.391173 / 2.268929 (4.122245) | 3.265131 / 55.444624 (-52.179493) | 2.939188 / 6.876477 (-3.937289) | 2.919217 / 2.142072 (0.777145) | 0.745095 / 4.805227 (-4.060132) | 0.164065 / 6.500664 (-6.336599) | 0.076993 / 0.075469 (0.001524) |\n\n### Benchmark: benchmark_map_filter.json\n\n| metric | filter | map fast-tokenizer batched | map identity | map identity batched | map no-op batched | map no-op batched numpy | map no-op batched pandas | map no-op batched pytorch | map no-op batched tensorflow |\n|--------|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 1.539971 / 1.841788 (-0.301817) | 18.597296 / 8.074308 (10.522988) | 16.899330 / 10.191392 (6.707938) | 0.169005 / 0.680424 (-0.511419) | 0.020447 / 0.534201 (-0.513754) | 0.465862 / 0.579283 (-0.113421) | 0.522819 / 0.434364 (0.088455) | 0.547111 / 0.540337 (0.006773) | 0.657777 / 1.386936 (-0.729159) |\n\n</details>\n</details>\n\n![](https://cml.dev/watermark.png#56aff9ecb4e565eb95faad525558914648cc22f1 "CML watermark")\n', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1569663975/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}]

[{'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1564202336', 'html_url': 'https://github.com/huggingface/datasets/pull/5903#issuecomment-1564202336', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5903', 'id': 1564202336, 'node_id': 'IC_kwDODunzps5dO9Vg', 'user': {'login': 'alvarobartt', 'id': 36760800, 'node_id': 'MDQ6VXNlcjM2NzYwODAw', 'avatar_url': 'https://avatars.githubusercontent.com/u/36760800?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/alvarobartt', 'html_url': 'https://github.com/alvarobartt', 'followers_url': 'https://api.github.com/users/alvarobartt/followers', 'following_url': 'https://api.github.com/users/alvarobartt/following{/other_user}', 'gists_url': 'https://api.github.com/users/alvarobartt/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/alvarobartt/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/alvarobartt/subscriptions', 'organizations_url': 'https://api.github.com/users/alvarobartt/orgs', 'repos_url': 'https://api.github.com/users/alvarobartt/repos', 'events_url': 'https://api.github.com/users/alvarobartt/events{/privacy}', 'received_events_url': 'https://api.github.com/users/alvarobartt/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-05-26T10:47:52Z', 'updated_at': '2023-05-26T10:47:52Z', 'author_association': 'CONTRIBUTOR', 'body': 'Also this could be extended to the rest of the GitHub Action `yml` files, so let me know whether you want me to have a look into it! 🤗', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1564202336/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1564206460', 'html_url': 'https://github.com/huggingface/datasets/pull/5903#issuecomment-1564206460', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5903', 'id': 1564206460, 'node_id': 'IC_kwDODunzps5dO-V8', 'user': {'login': 'HuggingFaceDocBuilderDev', 'id': 99929124, 'node_id': 'U_kgDOBfTMJA', 'avatar_url': 'https://avatars.githubusercontent.com/u/99929124?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/HuggingFaceDocBuilderDev', 'html_url': 'https://github.com/HuggingFaceDocBuilderDev', 'followers_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/followers', 'following_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/following{/other_user}', 'gists_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/subscriptions', 'organizations_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/orgs', 'repos_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/repos', 'events_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/events{/privacy}', 'received_events_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-05-26T10:51:37Z', 'updated_at': '2023-05-26T10:51:37Z', 'author_association': 'NONE', 'body': 'The docs for this PR live [here](https://moon-ci-docs.huggingface.co/docs/datasets/pr_5903). All of your documentation changes will be reflected on that endpoint.', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1564206460/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}]

[{'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1564043931', 'html_url': 'https://github.com/huggingface/datasets/pull/5901#issuecomment-1564043931', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5901', 'id': 1564043931, 'node_id': 'IC_kwDODunzps5dOWqb', 'user': {'login': 'HuggingFaceDocBuilderDev', 'id': 99929124, 'node_id': 'U_kgDOBfTMJA', 'avatar_url': 'https://avatars.githubusercontent.com/u/99929124?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/HuggingFaceDocBuilderDev', 'html_url': 'https://github.com/HuggingFaceDocBuilderDev', 'followers_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/followers', 'following_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/following{/other_user}', 'gists_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/subscriptions', 'organizations_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/orgs', 'repos_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/repos', 'events_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/events{/privacy}', 'received_events_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-05-26T08:53:00Z', 'updated_at': '2023-06-01T13:42:41Z', 'author_association': 'NONE', 'body': '_The documentation is not available anymore as the PR was closed or merged._', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1564043931/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1572090016', 'html_url': 'https://github.com/huggingface/datasets/pull/5901#issuecomment-1572090016', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5901', 'id': 1572090016, 'node_id': 'IC_kwDODunzps5dtDCg', 'user': {'login': 'github-actions[bot]', 'id': 41898282, 'node_id': 'MDM6Qm90NDE4OTgyODI=', 'avatar_url': 'https://avatars.githubusercontent.com/in/15368?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/github-actions%5Bbot%5D', 'html_url': 'https://github.com/apps/github-actions', 'followers_url': 'https://api.github.com/users/github-actions%5Bbot%5D/followers', 'following_url': 'https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}', 'gists_url': 'https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/github-actions%5Bbot%5D/subscriptions', 'organizations_url': 'https://api.github.com/users/github-actions%5Bbot%5D/orgs', 'repos_url': 'https://api.github.com/users/github-actions%5Bbot%5D/repos', 'events_url': 'https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}', 'received_events_url': 'https://api.github.com/users/github-actions%5Bbot%5D/received_events', 'type': 'Bot', 'site_admin': False}, 'created_at': '2023-06-01T13:49:11Z', 'updated_at': '2023-06-01T13:49:11Z', 'author_association': 'NONE', 'body': '<details>\n<summary>Show benchmarks</summary>\n\nPyArrow==8.0.0\n\n<details>\n<summary>Show updated benchmarks!</summary>\n\n### Benchmark: benchmark_array_xd.json\n\n| metric | read_batch_formatted_as_numpy after write_array2d | read_batch_formatted_as_numpy after write_flattened_sequence | read_batch_formatted_as_numpy after write_nested_sequence | read_batch_unformated after write_array2d | read_batch_unformated after write_flattened_sequence | read_batch_unformated after write_nested_sequence | read_col_formatted_as_numpy after write_array2d | read_col_formatted_as_numpy after write_flattened_sequence | read_col_formatted_as_numpy after write_nested_sequence | read_col_unformated after write_array2d | read_col_unformated after write_flattened_sequence | read_col_unformated after write_nested_sequence | read_formatted_as_numpy after write_array2d | read_formatted_as_numpy after write_flattened_sequence | read_formatted_as_numpy after write_nested_sequence | read_unformated after write_array2d | read_unformated after write_flattened_sequence | read_unformated after write_nested_sequence | write_array2d | write_flattened_sequence | write_nested_sequence |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.008809 / 0.011353 (-0.002544) | 0.005641 / 0.011008 (-0.005367) | 0.124986 / 0.038508 (0.086477) | 0.037311 / 0.023109 (0.014202) | 0.388915 / 0.275898 (0.113017) | 0.430123 / 0.323480 (0.106643) | 0.007447 / 0.007986 (-0.000538) | 0.009593 / 0.004328 (0.005264) | 0.099148 / 0.004250 (0.094898) | 0.052393 / 0.037052 (0.015341) | 0.399779 / 0.258489 (0.141290) | 0.439109 / 0.293841 (0.145268) | 0.043409 / 0.128546 (-0.085137) | 0.016286 / 0.075646 (-0.059360) | 0.431198 / 0.419271 (0.011927) | 0.064932 / 0.043533 (0.021400) | 0.390650 / 0.255139 (0.135511) | 0.432883 / 0.283200 (0.149684) | 0.110978 / 0.141683 (-0.030705) | 1.796121 / 1.452155 (0.343967) | 1.960097 / 1.492716 (0.467381) |\n\n### Benchmark: benchmark_getitem\\_100B.json\n\n| metric | get_batch_of\\_1024\\_random_rows | get_batch_of\\_1024\\_rows | get_first_row | get_last_row |\n|--------|---|---|---|---|\n| new / old (diff) | 0.286292 / 0.018006 (0.268286) | 0.659495 / 0.000490 (0.659005) | 0.008294 / 0.000200 (0.008094) | 0.000485 / 0.000054 (0.000431) |\n\n### Benchmark: benchmark_indices_mapping.json\n\n| metric | select | shard | shuffle | sort | train_test_split |\n|--------|---|---|---|---|---|\n| new / old (diff) | 0.029325 / 0.037411 (-0.008086) | 0.125454 / 0.014526 (0.110928) | 0.136459 / 0.176557 (-0.040097) | 0.221075 / 0.737135 (-0.516060) | 0.140281 / 0.296338 (-0.156058) |\n\n### Benchmark: benchmark_iterating.json\n\n| metric | read 5000 | read 50000 | read_batch 50000 10 | read_batch 50000 100 | read_batch 50000 1000 | read_formatted numpy 5000 | read_formatted pandas 5000 | read_formatted tensorflow 5000 | read_formatted torch 5000 | read_formatted_batch numpy 5000 10 | read_formatted_batch numpy 5000 1000 | shuffled read 5000 | shuffled read 50000 | shuffled read_batch 50000 10 | shuffled read_batch 50000 100 | shuffled read_batch 50000 1000 | shuffled read_formatted numpy 5000 | shuffled read_formatted_batch numpy 5000 10 | shuffled read_formatted_batch numpy 5000 1000 |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.602401 / 0.215209 (0.387192) | 6.124553 / 2.077655 (4.046898) | 2.453141 / 1.504120 (0.949021) | 2.038611 / 1.541195 (0.497416) | 2.073611 / 1.468490 (0.605121) | 0.938040 / 4.584777 (-3.646737) | 5.755972 / 3.745712 (2.010260) | 4.450935 / 5.269862 (-0.818926) | 2.337219 / 4.565676 (-2.228457) | 0.107118 / 0.424275 (-0.317157) | 0.015201 / 0.007607 (0.007594) | 0.785833 / 0.226044 (0.559788) | 7.732984 / 2.268929 (5.464055) | 3.236892 / 55.444624 (-52.207733) | 2.696402 / 6.876477 (-4.180074) | 2.805036 / 2.142072 (0.662964) | 1.108612 / 4.805227 (-3.696616) | 0.221067 / 6.500664 (-6.279597) | 0.085538 / 0.075469 (0.010068) |\n\n### Benchmark: benchmark_map_filter.json\n\n| metric | filter | map fast-tokenizer batched | map identity | map identity batched | map no-op batched | map no-op batched numpy | map no-op batched pandas | map no-op batched pytorch | map no-op batched tensorflow |\n|--------|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 1.600311 / 1.841788 (-0.241476) | 18.528118 / 8.074308 (10.453810) | 21.107199 / 10.191392 (10.915807) | 0.219489 / 0.680424 (-0.460934) | 0.028927 / 0.534201 (-0.505274) | 0.503446 / 0.579283 (-0.075837) | 0.619833 / 0.434364 (0.185469) | 0.582454 / 0.540337 (0.042117) | 0.709154 / 1.386936 (-0.677782) |\n\n</details>\nPyArrow==latest\n\n<details>\n<summary>Show updated benchmarks!</summary>\n\n### Benchmark: benchmark_array_xd.json\n\n| metric | read_batch_formatted_as_numpy after write_array2d | read_batch_formatted_as_numpy after write_flattened_sequence | read_batch_formatted_as_numpy after write_nested_sequence | read_batch_unformated after write_array2d | read_batch_unformated after write_flattened_sequence | read_batch_unformated after write_nested_sequence | read_col_formatted_as_numpy after write_array2d | read_col_formatted_as_numpy after write_flattened_sequence | read_col_formatted_as_numpy after write_nested_sequence | read_col_unformated after write_array2d | read_col_unformated after write_flattened_sequence | read_col_unformated after write_nested_sequence | read_formatted_as_numpy after write_array2d | read_formatted_as_numpy after write_flattened_sequence | read_formatted_as_numpy after write_nested_sequence | read_unformated after write_array2d | read_unformated after write_flattened_sequence | read_unformated after write_nested_sequence | write_array2d | write_flattened_sequence | write_nested_sequence |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.008516 / 0.011353 (-0.002837) | 0.006090 / 0.011008 (-0.004918) | 0.104574 / 0.038508 (0.066066) | 0.042676 / 0.023109 (0.019566) | 0.458623 / 0.275898 (0.182725) | 0.568479 / 0.323480 (0.244999) | 0.008374 / 0.007986 (0.000389) | 0.004677 / 0.004328 (0.000349) | 0.105946 / 0.004250 (0.101695) | 0.055256 / 0.037052 (0.018204) | 0.511036 / 0.258489 (0.252547) | 0.598383 / 0.293841 (0.304542) | 0.043612 / 0.128546 (-0.084934) | 0.014707 / 0.075646 (-0.060940) | 0.116350 / 0.419271 (-0.302921) | 0.061413 / 0.043533 (0.017880) | 0.477785 / 0.255139 (0.222646) | 0.542643 / 0.283200 (0.259443) | 0.120431 / 0.141683 (-0.021252) | 1.994083 / 1.452155 (0.541928) | 2.100600 / 1.492716 (0.607883) |\n\n### Benchmark: benchmark_getitem\\_100B.json\n\n| metric | get_batch_of\\_1024\\_random_rows | get_batch_of\\_1024\\_rows | get_first_row | get_last_row |\n|--------|---|---|---|---|\n| new / old (diff) | 0.298480 / 0.018006 (0.280474) | 0.601921 / 0.000490 (0.601432) | 0.000445 / 0.000200 (0.000245) | 0.000086 / 0.000054 (0.000032) |\n\n### Benchmark: benchmark_indices_mapping.json\n\n| metric | select | shard | shuffle | sort | train_test_split |\n|--------|---|---|---|---|---|\n| new / old (diff) | 0.034784 / 0.037411 (-0.002627) | 0.133555 / 0.014526 (0.119029) | 0.138541 / 0.176557 (-0.038015) | 0.203114 / 0.737135 (-0.534021) | 0.153477 / 0.296338 (-0.142861) |\n\n### Benchmark: benchmark_iterating.json\n\n| metric | read 5000 | read 50000 | read_batch 50000 10 | read_batch 50000 100 | read_batch 50000 1000 | read_formatted numpy 5000 | read_formatted pandas 5000 | read_formatted tensorflow 5000 | read_formatted torch 5000 | read_formatted_batch numpy 5000 10 | read_formatted_batch numpy 5000 1000 | shuffled read 5000 | shuffled read 50000 | shuffled read_batch 50000 10 | shuffled read_batch 50000 100 | shuffled read_batch 50000 1000 | shuffled read_formatted numpy 5000 | shuffled read_formatted_batch numpy 5000 10 | shuffled read_formatted_batch numpy 5000 1000 |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.780484 / 0.215209 (0.565275) | 7.150876 / 2.077655 (5.073222) | 3.168590 / 1.504120 (1.664470) | 2.698746 / 1.541195 (1.157552) | 2.695678 / 1.468490 (1.227188) | 1.037706 / 4.584777 (-3.547071) | 5.672631 / 3.745712 (1.926918) | 2.798137 / 5.269862 (-2.471725) | 1.738588 / 4.565676 (-2.827088) | 0.111160 / 0.424275 (-0.313115) | 0.013878 / 0.007607 (0.006271) | 0.800191 / 0.226044 (0.574146) | 8.546676 / 2.268929 (6.277748) | 4.116852 / 55.444624 (-51.327773) | 3.331271 / 6.876477 (-3.545206) | 3.307410 / 2.142072 (1.165337) | 1.191019 / 4.805227 (-3.614208) | 0.248953 / 6.500664 (-6.251711) | 0.086632 / 0.075469 (0.011162) |\n\n### Benchmark: benchmark_map_filter.json\n\n| metric | filter | map fast-tokenizer batched | map identity | map identity batched | map no-op batched | map no-op batched numpy | map no-op batched pandas | map no-op batched pytorch | map no-op batched tensorflow |\n|--------|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 1.795057 / 1.841788 (-0.046730) | 18.038785 / 8.074308 (9.964476) | 21.865566 / 10.191392 (11.674174) | 0.211058 / 0.680424 (-0.469366) | 0.026956 / 0.534201 (-0.507245) | 0.518855 / 0.579283 (-0.060428) | 0.618105 / 0.434364 (0.183741) | 0.569227 / 0.540337 (0.028889) | 0.705431 / 1.386936 (-0.681505) |\n\n</details>\n</details>\n\n![](https://cml.dev/watermark.png#074925b9b7c1dfd33b8675aa99c07cc26375665c "CML watermark")\n', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1572090016/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1573202972', 'html_url': 'https://github.com/huggingface/datasets/pull/5901#issuecomment-1573202972', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5901', 'id': 1573202972, 'node_id': 'IC_kwDODunzps5dxSwc', 'user': {'login': 'github-actions[bot]', 'id': 41898282, 'node_id': 'MDM6Qm90NDE4OTgyODI=', 'avatar_url': 'https://avatars.githubusercontent.com/in/15368?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/github-actions%5Bbot%5D', 'html_url': 'https://github.com/apps/github-actions', 'followers_url': 'https://api.github.com/users/github-actions%5Bbot%5D/followers', 'following_url': 'https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}', 'gists_url': 'https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/github-actions%5Bbot%5D/subscriptions', 'organizations_url': 'https://api.github.com/users/github-actions%5Bbot%5D/orgs', 'repos_url': 'https://api.github.com/users/github-actions%5Bbot%5D/repos', 'events_url': 'https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}', 'received_events_url': 'https://api.github.com/users/github-actions%5Bbot%5D/received_events', 'type': 'Bot', 'site_admin': False}, 'created_at': '2023-06-02T06:06:37Z', 'updated_at': '2023-06-02T06:06:37Z', 'author_association': 'NONE', 'body': '<details>\n<summary>Show benchmarks</summary>\n\nPyArrow==8.0.0\n\n<details>\n<summary>Show updated benchmarks!</summary>\n\n### Benchmark: benchmark_array_xd.json\n\n| metric | read_batch_formatted_as_numpy after write_array2d | read_batch_formatted_as_numpy after write_flattened_sequence | read_batch_formatted_as_numpy after write_nested_sequence | read_batch_unformated after write_array2d | read_batch_unformated after write_flattened_sequence | read_batch_unformated after write_nested_sequence | read_col_formatted_as_numpy after write_array2d | read_col_formatted_as_numpy after write_flattened_sequence | read_col_formatted_as_numpy after write_nested_sequence | read_col_unformated after write_array2d | read_col_unformated after write_flattened_sequence | read_col_unformated after write_nested_sequence | read_formatted_as_numpy after write_array2d | read_formatted_as_numpy after write_flattened_sequence | read_formatted_as_numpy after write_nested_sequence | read_unformated after write_array2d | read_unformated after write_flattened_sequence | read_unformated after write_nested_sequence | write_array2d | write_flattened_sequence | write_nested_sequence |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.008900 / 0.011353 (-0.002453) | 0.005726 / 0.011008 (-0.005283) | 0.131747 / 0.038508 (0.093239) | 0.040585 / 0.023109 (0.017476) | 0.420531 / 0.275898 (0.144633) | 0.459430 / 0.323480 (0.135950) | 0.007642 / 0.007986 (-0.000344) | 0.006750 / 0.004328 (0.002421) | 0.099147 / 0.004250 (0.094897) | 0.055852 / 0.037052 (0.018799) | 0.423653 / 0.258489 (0.165164) | 0.453304 / 0.293841 (0.159463) | 0.045247 / 0.128546 (-0.083300) | 0.016034 / 0.075646 (-0.059612) | 0.443115 / 0.419271 (0.023843) | 0.078853 / 0.043533 (0.035320) | 0.417508 / 0.255139 (0.162369) | 0.440936 / 0.283200 (0.157736) | 0.115603 / 0.141683 (-0.026080) | 1.844610 / 1.452155 (0.392456) | 1.998497 / 1.492716 (0.505781) |\n\n### Benchmark: benchmark_getitem\\_100B.json\n\n| metric | get_batch_of\\_1024\\_random_rows | get_batch_of\\_1024\\_rows | get_first_row | get_last_row |\n|--------|---|---|---|---|\n| new / old (diff) | 0.272622 / 0.018006 (0.254616) | 0.598045 / 0.000490 (0.597556) | 0.007088 / 0.000200 (0.006888) | 0.000159 / 0.000054 (0.000105) |\n\n### Benchmark: benchmark_indices_mapping.json\n\n| metric | select | shard | shuffle | sort | train_test_split |\n|--------|---|---|---|---|---|\n| new / old (diff) | 0.032976 / 0.037411 (-0.004436) | 0.143970 / 0.014526 (0.129444) | 0.142172 / 0.176557 (-0.034384) | 0.216747 / 0.737135 (-0.520389) | 0.146004 / 0.296338 (-0.150334) |\n\n### Benchmark: benchmark_iterating.json\n\n| metric | read 5000 | read 50000 | read_batch 50000 10 | read_batch 50000 100 | read_batch 50000 1000 | read_formatted numpy 5000 | read_formatted pandas 5000 | read_formatted tensorflow 5000 | read_formatted torch 5000 | read_formatted_batch numpy 5000 10 | read_formatted_batch numpy 5000 1000 | shuffled read 5000 | shuffled read 50000 | shuffled read_batch 50000 10 | shuffled read_batch 50000 100 | shuffled read_batch 50000 1000 | shuffled read_formatted numpy 5000 | shuffled read_formatted_batch numpy 5000 10 | shuffled read_formatted_batch numpy 5000 1000 |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.687507 / 0.215209 (0.472298) | 6.549524 / 2.077655 (4.471870) | 2.924142 / 1.504120 (1.420022) | 2.504471 / 1.541195 (0.963277) | 2.496280 / 1.468490 (1.027790) | 0.959054 / 4.584777 (-3.625723) | 5.851742 / 3.745712 (2.106030) | 4.983357 / 5.269862 (-0.286504) | 2.627403 / 4.565676 (-1.938274) | 0.112955 / 0.424275 (-0.311320) | 0.016206 / 0.007607 (0.008599) | 0.819158 / 0.226044 (0.593114) | 8.416949 / 2.268929 (6.148020) | 3.776765 / 55.444624 (-51.667859) | 3.002397 / 6.876477 (-3.874080) | 3.158852 / 2.142072 (1.016779) | 1.197099 / 4.805227 (-3.608129) | 0.280654 / 6.500664 (-6.220010) | 0.099471 / 0.075469 (0.024002) |\n\n### Benchmark: benchmark_map_filter.json\n\n| metric | filter | map fast-tokenizer batched | map identity | map identity batched | map no-op batched | map no-op batched numpy | map no-op batched pandas | map no-op batched pytorch | map no-op batched tensorflow |\n|--------|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 1.687007 / 1.841788 (-0.154781) | 19.411976 / 8.074308 (11.337668) | 22.053482 / 10.191392 (11.862090) | 0.228038 / 0.680424 (-0.452386) | 0.028226 / 0.534201 (-0.505975) | 0.527695 / 0.579283 (-0.051588) | 0.635911 / 0.434364 (0.201547) | 0.618205 / 0.540337 (0.077868) | 0.735164 / 1.386936 (-0.651772) |\n\n</details>\nPyArrow==latest\n\n<details>\n<summary>Show updated benchmarks!</summary>\n\n### Benchmark: benchmark_array_xd.json\n\n| metric | read_batch_formatted_as_numpy after write_array2d | read_batch_formatted_as_numpy after write_flattened_sequence | read_batch_formatted_as_numpy after write_nested_sequence | read_batch_unformated after write_array2d | read_batch_unformated after write_flattened_sequence | read_batch_unformated after write_nested_sequence | read_col_formatted_as_numpy after write_array2d | read_col_formatted_as_numpy after write_flattened_sequence | read_col_formatted_as_numpy after write_nested_sequence |

[{'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1563993136', 'html_url': 'https://github.com/huggingface/datasets/pull/5900#issuecomment-1563993136', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5900', 'id': 1563993136, 'node_id': 'IC_kwDODunzps5dOKQw', 'user': {'login': 'HuggingFaceDocBuilderDev', 'id': 99929124, 'node_id': 'U_kgDOBfTMJA', 'avatar_url': 'https://avatars.githubusercontent.com/u/99929124?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/HuggingFaceDocBuilderDev', 'html_url': 'https://github.com/HuggingFaceDocBuilderDev', 'followers_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/followers', 'following_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/following{/other_user}', 'gists_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/subscriptions', 'organizations_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/orgs', 'repos_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/repos', 'events_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/events{/privacy}', 'received_events_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-05-26T08:15:32Z', 'updated_at': '2023-05-26T09:28:46Z', 'author_association': 'NONE', 'body': '_The documentation is not available anymore as the PR was closed or merged._', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1563993136/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1563995856', 'html_url': 'https://github.com/huggingface/datasets/pull/5900#issuecomment-1563995856', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5900', 'id': 1563995856, 'node_id': 'IC_kwDODunzps5dOK7Q', 'user': {'login': 'github-actions[bot]', 'id': 41898282, 'node_id': 'MDM6Qm90NDE4OTgyODI=', 'avatar_url': 'https://avatars.githubusercontent.com/in/15368?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/github-actions%5Bbot%5D', 'html_url': 'https://github.com/apps/github-actions', 'followers_url': 'https://api.github.com/users/github-actions%5Bbot%5D/followers', 'following_url': 'https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}', 'gists_url': 'https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/github-actions%5Bbot%5D/subscriptions', 'organizations_url': 'https://api.github.com/users/github-actions%5Bbot%5D/orgs', 'repos_url': 'https://api.github.com/users/github-actions%5Bbot%5D/repos', 'events_url': 'https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}', 'received_events_url': 'https://api.github.com/users/github-actions%5Bbot%5D/received_events', 'type': 'Bot', 'site_admin': False}, 'created_at': '2023-05-26T08:17:41Z', 'updated_at': '2023-05-26T08:17:41Z', 'author_association': 'NONE', 'body': '<details>\n<summary>Show benchmarks</summary>\n\nPyArrow==8.0.0\n\n<details>\n<summary>Show updated benchmarks!</summary>\n\n### Benchmark: benchmark_array_xd.json\n\n| metric | read_batch_formatted_as_numpy after write_array2d | read_batch_formatted_as_numpy after write_flattened_sequence | read_batch_formatted_as_numpy after write_nested_sequence | read_batch_unformated after write_array2d | read_batch_unformated after write_flattened_sequence | read_batch_unformated after write_nested_sequence | read_col_formatted_as_numpy after write_array2d | read_col_formatted_as_numpy after write_flattened_sequence | read_col_formatted_as_numpy after write_nested_sequence | read_col_unformated after write_array2d | read_col_unformated after write_flattened_sequence | read_col_unformated after write_nested_sequence | read_formatted_as_numpy after write_array2d | read_formatted_as_numpy after write_flattened_sequence | read_formatted_as_numpy after write_nested_sequence | read_unformated after write_array2d | read_unformated after write_flattened_sequence | read_unformated after write_nested_sequence | write_array2d | write_flattened_sequence | write_nested_sequence |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.006763 / 0.011353 (-0.004589) | 0.004548 / 0.011008 (-0.006460) | 0.095631 / 0.038508 (0.057123) | 0.034046 / 0.023109 (0.010936) | 0.298064 / 0.275898 (0.022166) | 0.330391 / 0.323480 (0.006911) | 0.006058 / 0.007986 (-0.001928) | 0.004163 / 0.004328 (-0.000165) | 0.073260 / 0.004250 (0.069010) | 0.048885 / 0.037052 (0.011832) | 0.304651 / 0.258489 (0.046162) | 0.345882 / 0.293841 (0.052042) | 0.028061 / 0.128546 (-0.100485) | 0.008823 / 0.075646 (-0.066823) | 0.325620 / 0.419271 (-0.093651) | 0.064480 / 0.043533 (0.020948) | 0.303373 / 0.255139 (0.048234) | 0.321672 / 0.283200 (0.038472) | 0.116353 / 0.141683 (-0.025330) | 1.442327 / 1.452155 (-0.009827) | 1.567553 / 1.492716 (0.074837) |\n\n### Benchmark: benchmark_getitem\\_100B.json\n\n| metric | get_batch_of\\_1024\\_random_rows | get_batch_of\\_1024\\_rows | get_first_row | get_last_row |\n|--------|---|---|---|---|\n| new / old (diff) | 0.213042 / 0.018006 (0.195035) | 0.457646 / 0.000490 (0.457156) | 0.003989 / 0.000200 (0.003789) | 0.000078 / 0.000054 (0.000023) |\n\n### Benchmark: benchmark_indices_mapping.json\n\n| metric | select | shard | shuffle | sort | train_test_split |\n|--------|---|---|---|---|---|\n| new / old (diff) | 0.028068 / 0.037411 (-0.009344) | 0.114791 / 0.014526 (0.100265) | 0.120870 / 0.176557 (-0.055686) | 0.183006 / 0.737135 (-0.554130) | 0.126772 / 0.296338 (-0.169567) |\n\n### Benchmark: benchmark_iterating.json\n\n| metric | read 5000 | read 50000 | read_batch 50000 10 | read_batch 50000 100 | read_batch 50000 1000 | read_formatted numpy 5000 | read_formatted pandas 5000 | read_formatted tensorflow 5000 | read_formatted torch 5000 | read_formatted_batch numpy 5000 10 | read_formatted_batch numpy 5000 1000 | shuffled read 5000 | shuffled read 50000 | shuffled read_batch 50000 10 | shuffled read_batch 50000 100 | shuffled read_batch 50000 1000 | shuffled read_formatted numpy 5000 | shuffled read_formatted_batch numpy 5000 10 | shuffled read_formatted_batch numpy 5000 1000 |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.406438 / 0.215209 (0.191229) | 4.041890 / 2.077655 (1.964235) | 1.839967 / 1.504120 (0.335847) | 1.646857 / 1.541195 (0.105662) | 1.729372 / 1.468490 (0.260882) | 0.525540 / 4.584777 (-4.059237) | 3.809996 / 3.745712 (0.064284) | 1.842598 / 5.269862 (-3.427263) | 1.062815 / 4.565676 (-3.502862) | 0.065301 / 0.424275 (-0.358974) | 0.012027 / 0.007607 (0.004420) | 0.505459 / 0.226044 (0.279415) | 5.051177 / 2.268929 (2.782248) | 2.354368 / 55.444624 (-53.090256) | 2.035482 / 6.876477 (-4.840995) | 2.120493 / 2.142072 (-0.021579) | 0.642233 / 4.805227 (-4.162994) | 0.141690 / 6.500664 (-6.358974) | 0.063933 / 0.075469 (-0.011536) |\n\n### Benchmark: benchmark_map_filter.json\n\n| metric | filter | map fast-tokenizer batched | map identity | map identity batched | map no-op batched | map no-op batched numpy | map no-op batched pandas | map no-op batched pytorch | map no-op batched tensorflow |\n|--------|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 1.186261 / 1.841788 (-0.655527) | 14.919653 / 8.074308 (6.845345) | 14.534003 / 10.191392 (4.342611) | 0.183165 / 0.680424 (-0.497259) | 0.017581 / 0.534201 (-0.516620) | 0.397284 / 0.579283 (-0.181999) | 0.431363 / 0.434364 (-0.003001) | 0.510774 / 0.540337 (-0.029564) | 0.614421 / 1.386936 (-0.772516) |\n\n</details>\nPyArrow==latest\n\n<details>\n<summary>Show updated benchmarks!</summary>\n\n### Benchmark: benchmark_array_xd.json\n\n| metric | read_batch_formatted_as_numpy after write_array2d | read_batch_formatted_as_numpy after write_flattened_sequence | read_batch_formatted_as_numpy after write_nested_sequence | read_batch_unformated after write_array2d | read_batch_unformated after write_flattened_sequence | read_batch_unformated after write_nested_sequence | read_col_formatted_as_numpy after write_array2d | read_col_formatted_as_numpy after write_flattened_sequence | read_col_formatted_as_numpy after write_nested_sequence | read_col_unformated after write_array2d | read_col_unformated after write_flattened_sequence | read_col_unformated after write_nested_sequence | read_formatted_as_numpy after write_array2d | read_formatted_as_numpy after write_flattened_sequence | read_formatted_as_numpy after write_nested_sequence | read_unformated after write_array2d | read_unformated after write_flattened_sequence | read_unformated after write_nested_sequence | write_array2d | write_flattened_sequence | write_nested_sequence |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.006682 / 0.011353 (-0.004671) | 0.004558 / 0.011008 (-0.006450) | 0.076272 / 0.038508 (0.037764) | 0.034285 / 0.023109 (0.011176) | 0.395594 / 0.275898 (0.119696) | 0.402702 / 0.323480 (0.079222) | 0.006093 / 0.007986 (-0.001893) | 0.005538 / 0.004328 (0.001209) | 0.075797 / 0.004250 (0.071547) | 0.051638 / 0.037052 (0.014585) | 0.396071 / 0.258489 (0.137582) | 0.409282 / 0.293841 (0.115441) | 0.028193 / 0.128546 (-0.100354) | 0.008827 / 0.075646 (-0.066819) | 0.083182 / 0.419271 (-0.336089) | 0.047605 / 0.043533 (0.004072) | 0.391148 / 0.255139 (0.136009) | 0.386784 / 0.283200 (0.103584) | 0.115303 / 0.141683 (-0.026380) | 1.463666 / 1.452155 (0.011512) | 1.566147 / 1.492716 (0.073431) |\n\n### Benchmark: benchmark_getitem\\_100B.json\n\n| metric | get_batch_of\\_1024\\_random_rows | get_batch_of\\_1024\\_rows | get_first_row | get_last_row |\n|--------|---|---|---|---|\n| new / old (diff) | 0.213846 / 0.018006 (0.195839) | 0.454769 / 0.000490 (0.454279) | 0.004767 / 0.000200 (0.004567) | 0.000099 / 0.000054 (0.000045) |\n\n### Benchmark: benchmark_indices_mapping.json\n\n| metric | select | shard | shuffle | sort | train_test_split |\n|--------|---|---|---|---|---|\n| new / old (diff) | 0.030369 / 0.037411 (-0.007042) | 0.115585 / 0.014526 (0.101059) | 0.125181 / 0.176557 (-0.051376) | 0.179247 / 0.737135 (-0.557888) | 0.129336 / 0.296338 (-0.167003) |\n\n### Benchmark: benchmark_iterating.json\n\n| metric | read 5000 | read 50000 | read_batch 50000 10 | read_batch 50000 100 | read_batch 50000 1000 | read_formatted numpy 5000 | read_formatted pandas 5000 | read_formatted tensorflow 5000 | read_formatted torch 5000 | read_formatted_batch numpy 5000 10 | read_formatted_batch numpy 5000 1000 | shuffled read 5000 | shuffled read 50000 | shuffled read_batch 50000 10 | shuffled read_batch 50000 100 | shuffled read_batch 50000 1000 | shuffled read_formatted numpy 5000 | shuffled read_formatted_batch numpy 5000 10 | shuffled read_formatted_batch numpy 5000 1000 |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.446040 / 0.215209 (0.230831) | 4.462644 / 2.077655 (2.384989) | 2.254511 / 1.504120 (0.750392) | 2.062679 / 1.541195 (0.521484) | 2.180766 / 1.468490 (0.712276) | 0.530928 / 4.584777 (-4.053849) | 3.781392 / 3.745712 (0.035680) | 3.522539 / 5.269862 (-1.747322) | 1.506960 / 4.565676 (-3.058717) | 0.067101 / 0.424275 (-0.357174) | 0.012011 / 0.007607 (0.004404) | 0.546407 / 0.226044 (0.320362) | 5.429894 / 2.268929 (3.160965) | 2.702244 / 55.444624 (-52.742381) | 2.367559 / 6.876477 (-4.508917) | 2.556032 / 2.142072 (0.413960) | 0.639690 / 4.805227 (-4.165538) | 0.144538 / 6.500664 (-6.356126) | 0.067822 / 0.075469 (-0.007647) |\n\n### Benchmark: benchmark_map_filter.json\n\n| metric | filter | map fast-tokenizer batched | map identity | map identity batched | map no-op batched | map no-op batched numpy | map no-op batched pandas | map no-op batched pytorch | map no-op batched tensorflow |\n|--------|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 1.284977 / 1.841788 (-0.556811) | 15.546489 / 8.074308 (7.472181) | 14.747519 / 10.191392 (4.556127) | 0.160044 / 0.680424 (-0.520380) | 0.017746 / 0.534201 (-0.516454) | 0.390140 / 0.579283 (-0.189143) | 0.420342 / 0.434364 (-0.014021) | 0.459788 / 0.540337 (-0.080549) | 0.556360 / 1.386936 (-0.830576) |\n\n</details>\n</details>\n\n![](https://cml.dev/watermark.png#d646afbac7ea3dc0996fa2cb6ffd8a98e158e742 "CML watermark")\n', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1563995856/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1564103158', 'html_url': 'https://github.com/huggingface/datasets/pull/5900#issuecomment-1564103158', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5900', 'id': 1564103158, 'node_id': 'IC_kwDODunzps5dOlH2', 'user': {'login': 'github-actions[bot]', 'id': 41898282, 'node_id': 'MDM6Qm90NDE4OTgyODI=', 'avatar_url': 'https://avatars.githubusercontent.com/in/15368?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/github-actions%5Bbot%5D', 'html_url': 'https://github.com/apps/github-actions', 'followers_url': 'https://api.github.com/users/github-actions%5Bbot%5D/followers', 'following_url': 'https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}', 'gists_url': 'https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/github-actions%5Bbot%5D/subscriptions', 'organizations_url': 'https://api.github.com/users/github-actions%5Bbot%5D/orgs', 'repos_url': 'https://api.github.com/users/github-actions%5Bbot%5D/repos', 'events_url': 'https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}', 'received_events_url': 'https://api.github.com/users/github-actions%5Bbot%5D/received_events', 'type': 'Bot', 'site_admin': False}, 'created_at': '2023-05-26T09:34:14Z', 'updated_at': '2023-05-26T09:34:14Z', 'author_association': 'NONE', 'body': '<details>\n<summary>Show benchmarks</summary>\n\nPyArrow==8.0.0\n\n<details>\n<summary>Show updated benchmarks!</summary>\n\n### Benchmark: benchmark_array_xd.json\n\n| metric | read_batch_formatted_as_numpy after write_array2d | read_batch_formatted_as_numpy after write_flattened_sequence | read_batch_formatted_as_numpy after write_nested_sequence | read_batch_unformated after write_array2d | read_batch_unformated after write_flattened_sequence | read_batch_unformated after write_nested_sequence | read_col_formatted_as_numpy after write_array2d | read_col_formatted_as_numpy after write_flattened_sequence | read_col_formatted_as_numpy after write_nested_sequence | read_col_unformated after write_array2d | read_col_unformated after write_flattened_sequence | read_col_unformated after write_nested_sequence | read_formatted_as_numpy after write_array2d | read_formatted_as_numpy after write_flattened_sequence | read_formatted_as_numpy after write_nested_sequence | read_unformated after write_array2d | read_unformated after write_flattened_sequence | read_unformated after write_nested_sequence | write_array2d | write_flattened_sequence | write_nested_sequence |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.006493 / 0.011353 (-0.004860) | 0.004532 / 0.011008 (-0.006476) | 0.096509 / 0.038508 (0.058001) | 0.033084 / 0.023109 (0.009974) | 0.297802 / 0.275898 (0.021904) | 0.345880 / 0.323480 (0.022400) | 0.005461 / 0.007986 (-0.002525) | 0.005282 / 0.004328 (0.000954) | 0.073719 / 0.004250 (0.069469) | 0.045035 / 0.037052 (0.007983) | 0.295504 / 0.258489 (0.037015) | 0.345400 / 0.293841 (0.051559) | 0.027880 / 0.128546 (-0.100666) | 0.008804 / 0.075646 (-0.066842) | 0.328017 / 0.419271 (-0.091255) | 0.050169 / 0.043533 (0.006637) | 0.299642 / 0.255139 (0.044503) | 0.313573 / 0.283200 (0.030374) | 0.103359 / 0.141683 (-0.038323) | 1.482145 / 1.452155 (0.029990) | 1.554584 / 1.492716 (0.061867) |\n\n### Benchmark: benchmark_getitem\\_100B.json\n\n| metric | get_batch_of\\_1024\\_random_rows | get_batch_of\\_1024\\_rows | get_first_row | get_last_row |\n|--------|---|---|---|---|\n| new / old (diff) | 0.212860 / 0.018006 (0.194853) | 0.444823 / 0.000490 (0.444334) | 0.003014 / 0.000200 (0.002815) | 0.000108 / 0.000054 (0.000053) |\n\n### Benchmark: benchmark_indices_mapping.json\n\n| metric | select | shard | shuffle | sort | train_test_split |\n|--------|---|---|---|---|---|\n| new / old (diff) | 0.026906 / 0.037411 (-0.010506) | 0.108056 / 0.014526 (0.093530) | 0.118721 / 0.176557 (-0.057835) | 0.176646 / 0.737135 (-0.560489) | 0.123285 / 0.296338 (-0.173053) |\n\n### Benchmark: benchmark_iterating.json\n\n| metric | read 5000 | read 50000 | read_batch 50000 10 | read_batch 50000 100 | read_batch 50000 1000 | read_formatted numpy 5000 | read_formatted pandas 5000 | read_formatted tensorflow 5000 | read_formatted torch 5000 | read_formatted_batch numpy 5000 10 | read_formatted_batch numpy 5000 1000 | shuffled read 5000 | shuffled read 50000 | shuffled read_batch 50000 10 | shuffled read_batch 50000 100 | shuffled read_batch 50000 1000 | shuffled read_formatted numpy 5000 | shuffled read_formatted_batch numpy 5000 10 | shuffled read_formatted_batch numpy 5000 1000 |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.430157 / 0.215209 (0.214948) | 4.279362 / 2.077655 (2.201707) | 1.999732 / 1.504120 (0.495612) | 1.803787 / 1.541195 (0.262592) | 1.868322 / 1.468490 (0.399832) | 0.529314 / 4.584777 (-4.055463) | 3.785101 / 3.745712 (0.039389) | 2.812608 / 5.269862 (-2.457254) | 1.373460 / 4.565676 (-3.192216) | 0.066208 / 0.424275 (-0.358067) | 0.012173 / 0.007607 (0.004566) | 0.528716 / 0.226044 (0.302672) | 5.295003 / 2.268929 (3.026074) | 2.450188 / 55.444624 (-52.994437) | 2.114560 / 6.876477 (-4.761917) | 2.268468 / 2.142072 (0.126395) | 0.651706 / 4.805227 (-4.153521) | 0.142185 / 6.500664 (-6.358479) | 0.064862 / 0.075469 (-0.010607) |\n\n### Benchmark: benchmark_map_filter.json\n\n| metric | filter | map fast-tokenizer batched | map identity | map identity batched | map no-op batched | map no-op batched numpy | map no-op batched pandas | map no-op batched pytorch | map no-op batched tensorflow |\n|--------|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 1.184933 / 1.841788 (-0.656854) | 14.503903 / 8.074308 (6.429595) | 13.928965 / 10.191392 (3.737573) | 0.156788 / 0.680424 (-0.523636) | 0.017320 / 0.534201 (-0.516881) | 0.391366 / 0.579283 (-0.187918) | 0.416261 / 0.434364 (-0.018103) | 0.461951 / 0.540337 (-0.078387) | 0.553496 / 1.386936 (-0.833440) |\n\n</details>\nPyArrow==latest\n\n<details>\n<summary>Show updated benchmarks!</summary>\n\n### Benchmark: benchmark_array_xd.json\n\n| metric | read_batch_formatted_as_numpy after write_array2d | read_batch_formatted_as_numpy after write_flattened_sequence | read_batch_formatted_as_numpy after write_nested_sequence | read_batch_unformated after write_array2d | read_batch_unformated after write_flattened_sequence | read_batch_unformated after write_nested_sequence | read_col_formatted_as_numpy after write_array2d | read_col_formatted_as_numpy after write_flattened_sequence | read_col_formatted_as_numpy after write_nested_

[{'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1572038397', 'html_url': 'https://github.com/huggingface/datasets/pull/5899#issuecomment-1572038397', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5899', 'id': 1572038397, 'node_id': 'IC_kwDODunzps5ds2b9', 'user': {'login': 'HuggingFaceDocBuilderDev', 'id': 99929124, 'node_id': 'U_kgDOBfTMJA', 'avatar_url': 'https://avatars.githubusercontent.com/u/99929124?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/HuggingFaceDocBuilderDev', 'html_url': 'https://github.com/HuggingFaceDocBuilderDev', 'followers_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/followers', 'following_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/following{/other_user}', 'gists_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/subscriptions', 'organizations_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/orgs', 'repos_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/repos', 'events_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/events{/privacy}', 'received_events_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-01T13:17:32Z', 'updated_at': '2023-06-02T15:54:58Z', 'author_association': 'NONE', 'body': '_The documentation is not available anymore as the PR was closed or merged._', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1572038397/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1573968728', 'html_url': 'https://github.com/huggingface/datasets/pull/5899#issuecomment-1573968728', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5899', 'id': 1573968728, 'node_id': 'IC_kwDODunzps5d0NtY', 'user': {'login': 'github-actions[bot]', 'id': 41898282, 'node_id': 'MDM6Qm90NDE4OTgyODI=', 'avatar_url': 'https://avatars.githubusercontent.com/in/15368?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/github-actions%5Bbot%5D', 'html_url': 'https://github.com/apps/github-actions', 'followers_url': 'https://api.github.com/users/github-actions%5Bbot%5D/followers', 'following_url': 'https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}', 'gists_url': 'https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/github-actions%5Bbot%5D/subscriptions', 'organizations_url': 'https://api.github.com/users/github-actions%5Bbot%5D/orgs', 'repos_url': 'https://api.github.com/users/github-actions%5Bbot%5D/repos', 'events_url': 'https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}', 'received_events_url': 'https://api.github.com/users/github-actions%5Bbot%5D/received_events', 'type': 'Bot', 'site_admin': False}, 'created_at': '2023-06-02T16:02:15Z', 'updated_at': '2023-06-02T16:02:15Z', 'author_association': 'NONE', 'body': '<details>\n<summary>Show benchmarks</summary>\n\nPyArrow==8.0.0\n\n<details>\n<summary>Show updated benchmarks!</summary>\n\n### Benchmark: benchmark_array_xd.json\n\n| metric | read_batch_formatted_as_numpy after write_array2d | read_batch_formatted_as_numpy after write_flattened_sequence | read_batch_formatted_as_numpy after write_nested_sequence | read_batch_unformated after write_array2d | read_batch_unformated after write_flattened_sequence | read_batch_unformated after write_nested_sequence | read_col_formatted_as_numpy after write_array2d | read_col_formatted_as_numpy after write_flattened_sequence | read_col_formatted_as_numpy after write_nested_sequence | read_col_unformated after write_array2d | read_col_unformated after write_flattened_sequence | read_col_unformated after write_nested_sequence | read_formatted_as_numpy after write_array2d | read_formatted_as_numpy after write_flattened_sequence | read_formatted_as_numpy after write_nested_sequence | read_unformated after write_array2d | read_unformated after write_flattened_sequence | read_unformated after write_nested_sequence | write_array2d | write_flattened_sequence | write_nested_sequence |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.009137 / 0.011353 (-0.002216) | 0.006119 / 0.011008 (-0.004889) | 0.136530 / 0.038508 (0.098022) | 0.038434 / 0.023109 (0.015325) | 0.427900 / 0.275898 (0.152002) | 0.449757 / 0.323480 (0.126277) | 0.007673 / 0.007986 (-0.000313) | 0.007147 / 0.004328 (0.002818) | 0.108029 / 0.004250 (0.103778) | 0.055072 / 0.037052 (0.018020) | 0.439245 / 0.258489 (0.180756) | 0.477285 / 0.293841 (0.183444) | 0.044838 / 0.128546 (-0.083708) | 0.020814 / 0.075646 (-0.054832) | 0.436098 / 0.419271 (0.016826) | 0.067459 / 0.043533 (0.023926) | 0.427470 / 0.255139 (0.172331) | 0.443260 / 0.283200 (0.160060) | 0.125466 / 0.141683 (-0.016216) | 1.996756 / 1.452155 (0.544601) | 2.100679 / 1.492716 (0.607962) |\n\n### Benchmark: benchmark_getitem\\_100B.json\n\n| metric | get_batch_of\\_1024\\_random_rows | get_batch_of\\_1024\\_rows | get_first_row | get_last_row |\n|--------|---|---|---|---|\n| new / old (diff) | 0.278407 / 0.018006 (0.260401) | 0.625855 / 0.000490 (0.625365) | 0.005544 / 0.000200 (0.005344) | 0.000107 / 0.000054 (0.000053) |\n\n### Benchmark: benchmark_indices_mapping.json\n\n| metric | select | shard | shuffle | sort | train_test_split |\n|--------|---|---|---|---|---|\n| new / old (diff) | 0.033495 / 0.037411 (-0.003916) | 0.134718 / 0.014526 (0.120192) | 0.150151 / 0.176557 (-0.026406) | 0.221385 / 0.737135 (-0.515751) | 0.150932 / 0.296338 (-0.145406) |\n\n### Benchmark: benchmark_iterating.json\n\n| metric | read 5000 | read 50000 | read_batch 50000 10 | read_batch 50000 100 | read_batch 50000 1000 | read_formatted numpy 5000 | read_formatted pandas 5000 | read_formatted tensorflow 5000 | read_formatted torch 5000 | read_formatted_batch numpy 5000 10 | read_formatted_batch numpy 5000 1000 | shuffled read 5000 | shuffled read 50000 | shuffled read_batch 50000 10 | shuffled read_batch 50000 100 | shuffled read_batch 50000 1000 | shuffled read_formatted numpy 5000 | shuffled read_formatted_batch numpy 5000 10 | shuffled read_formatted_batch numpy 5000 1000 |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.668845 / 0.215209 (0.453636) | 6.678436 / 2.077655 (4.600781) | 2.714074 / 1.504120 (1.209954) | 2.275784 / 1.541195 (0.734589) | 2.332852 / 1.468490 (0.864361) | 1.014877 / 4.584777 (-3.569900) | 6.086455 / 3.745712 (2.340743) | 2.990029 / 5.269862 (-2.279832) | 1.862236 / 4.565676 (-2.703441) | 0.122179 / 0.424275 (-0.302096) | 0.015706 / 0.007607 (0.008099) | 0.873473 / 0.226044 (0.647429) | 8.580109 / 2.268929 (6.311180) | 3.458360 / 55.444624 (-51.986264) | 2.738801 / 6.876477 (-4.137676) | 2.918428 / 2.142072 (0.776356) | 1.224910 / 4.805227 (-3.580317) | 0.243006 / 6.500664 (-6.257658) | 0.087121 / 0.075469 (0.011652) |\n\n### Benchmark: benchmark_map_filter.json\n\n| metric | filter | map fast-tokenizer batched | map identity | map identity batched | map no-op batched | map no-op batched numpy | map no-op batched pandas | map no-op batched pytorch | map no-op batched tensorflow |\n|--------|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 1.757802 / 1.841788 (-0.083986) | 19.447999 / 8.074308 (11.373691) | 24.518157 / 10.191392 (14.326765) | 0.245013 / 0.680424 (-0.435411) | 0.032290 / 0.534201 (-0.501911) | 0.542043 / 0.579283 (-0.037240) | 0.708154 / 0.434364 (0.273790) | 0.660584 / 0.540337 (0.120247) | 0.794868 / 1.386936 (-0.592068) |\n\n</details>\nPyArrow==latest\n\n<details>\n<summary>Show updated benchmarks!</summary>\n\n### Benchmark: benchmark_array_xd.json\n\n| metric | read_batch_formatted_as_numpy after write_array2d | read_batch_formatted_as_numpy after write_flattened_sequence | read_batch_formatted_as_numpy after write_nested_sequence | read_batch_unformated after write_array2d | read_batch_unformated after write_flattened_sequence | read_batch_unformated after write_nested_sequence | read_col_formatted_as_numpy after write_array2d | read_col_formatted_as_numpy after write_flattened_sequence | read_col_formatted_as_numpy after write_nested_sequence | read_col_unformated after write_array2d | read_col_unformated after write_flattened_sequence | read_col_unformated after write_nested_sequence | read_formatted_as_numpy after write_array2d | read_formatted_as_numpy after write_flattened_sequence | read_formatted_as_numpy after write_nested_sequence | read_unformated after write_array2d | read_unformated after write_flattened_sequence | read_unformated after write_nested_sequence | write_array2d | write_flattened_sequence | write_nested_sequence |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.009496 / 0.011353 (-0.001857) | 0.005842 / 0.011008 (-0.005166) | 0.112813 / 0.038508 (0.074305) | 0.039120 / 0.023109 (0.016011) | 0.489717 / 0.275898 (0.213819) | 0.532586 / 0.323480 (0.209107) | 0.007681 / 0.007986 (-0.000304) | 0.005337 / 0.004328 (0.001009) | 0.107244 / 0.004250 (0.102994) | 0.056847 / 0.037052 (0.019794) | 0.499447 / 0.258489 (0.240958) | 0.548995 / 0.293841 (0.255154) | 0.058047 / 0.128546 (-0.070499) | 0.015468 / 0.075646 (-0.060179) | 0.124600 / 0.419271 (-0.294671) | 0.060940 / 0.043533 (0.017407) | 0.488370 / 0.255139 (0.233231) | 0.518540 / 0.283200 (0.235341) | 0.124147 / 0.141683 (-0.017536) | 1.902922 / 1.452155 (0.450767) | 2.033519 / 1.492716 (0.540803) |\n\n### Benchmark: benchmark_getitem\\_100B.json\n\n| metric | get_batch_of\\_1024\\_random_rows | get_batch_of\\_1024\\_rows | get_first_row | get_last_row |\n|--------|---|---|---|---|\n| new / old (diff) | 0.319527 / 0.018006 (0.301521) | 0.629641 / 0.000490 (0.629152) | 0.000721 / 0.000200 (0.000521) | 0.000101 / 0.000054 (0.000046) |\n\n### Benchmark: benchmark_indices_mapping.json\n\n| metric | select | shard | shuffle | sort | train_test_split |\n|--------|---|---|---|---|---|\n| new / old (diff) | 0.033150 / 0.037411 (-0.004262) | 0.134250 / 0.014526 (0.119724) | 0.161273 / 0.176557 (-0.015283) | 0.211471 / 0.737135 (-0.525664) | 0.155326 / 0.296338 (-0.141012) |\n\n### Benchmark: benchmark_iterating.json\n\n| metric | read 5000 | read 50000 | read_batch 50000 10 | read_batch 50000 100 | read_batch 50000 1000 | read_formatted numpy 5000 | read_formatted pandas 5000 | read_formatted tensorflow 5000 | read_formatted torch 5000 | read_formatted_batch numpy 5000 10 | read_formatted_batch numpy 5000 1000 | shuffled read 5000 | shuffled read 50000 | shuffled read_batch 50000 10 | shuffled read_batch 50000 100 | shuffled read_batch 50000 1000 | shuffled read_formatted numpy 5000 | shuffled read_formatted_batch numpy 5000 10 | shuffled read_formatted_batch numpy 5000 1000 |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.705244 / 0.215209 (0.490035) | 7.043040 / 2.077655 (4.965386) | 3.308948 / 1.504120 (1.804828) | 2.885050 / 1.541195 (1.343855) | 2.810260 / 1.468490 (1.341770) | 1.027095 / 4.584777 (-3.557682) | 6.111398 / 3.745712 (2.365686) | 5.385545 / 5.269862 (0.115684) | 2.521668 / 4.565676 (-2.044009) | 0.122419 / 0.424275 (-0.301856) | 0.016376 / 0.007607 (0.008768) | 0.830856 / 0.226044 (0.604811) | 8.952199 / 2.268929 (6.683271) | 4.207875 / 55.444624 (-51.236749) | 3.346624 / 6.876477 (-3.529853) | 3.395316 / 2.142072 (1.253244) | 1.351816 / 4.805227 (-3.453411) | 0.303056 / 6.500664 (-6.197608) | 0.098713 / 0.075469 (0.023244) |\n\n### Benchmark: benchmark_map_filter.json\n\n| metric | filter | map fast-tokenizer batched | map identity | map identity batched | map no-op batched | map no-op batched numpy | map no-op batched pandas | map no-op batched pytorch | map no-op batched tensorflow |\n|--------|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 1.841903 / 1.841788 (0.000116) | 20.472125 / 8.074308 (12.397817) | 23.433200 / 10.191392 (13.241808) | 0.242599 / 0.680424 (-0.437825) | 0.030701 / 0.534201 (-0.503500) | 0.541614 / 0.579283 (-0.037669) | 0.657827 / 0.434364 (0.223463) | 0.652448 / 0.540337 (0.112111) | 0.773743 / 1.386936 (-0.613193) |\n\n</details>\n</details>\n\n![](https://cml.dev/watermark.png#02ee418831aba68d0be93227bce8b3f42ef8980f "CML watermark")\n', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1573968728/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}]

[{'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1563255445', 'html_url': 'https://github.com/huggingface/datasets/issues/5898#issuecomment-1563255445', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5898', 'id': 1563255445, 'node_id': 'IC_kwDODunzps5dLWKV', 'user': {'login': '106AbdulBasit', 'id': 36159918, 'node_id': 'MDQ6VXNlcjM2MTU5OTE4', 'avatar_url': 'https://avatars.githubusercontent.com/u/36159918?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/106AbdulBasit', 'html_url': 'https://github.com/106AbdulBasit', 'followers_url': 'https://api.github.com/users/106AbdulBasit/followers', 'following_url': 'https://api.github.com/users/106AbdulBasit/following{/other_user}', 'gists_url': 'https://api.github.com/users/106AbdulBasit/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/106AbdulBasit/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/106AbdulBasit/subscriptions', 'organizations_url': 'https://api.github.com/users/106AbdulBasit/orgs', 'repos_url': 'https://api.github.com/users/106AbdulBasit/repos', 'events_url': 'https://api.github.com/users/106AbdulBasit/events{/privacy}', 'received_events_url': 'https://api.github.com/users/106AbdulBasit/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-05-25T17:21:37Z', 'updated_at': '2023-05-25T17:21:37Z', 'author_association': 'NONE', 'body': 'got that the syntax is like this\r\n\r\ndataset = load_dataset("facebook/flores", "ace_Arab")', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1563255445/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}]

[]
[{'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1563936736', 'html_url': 'https://github.com/huggingface/datasets/issues/5895#issuecomment-1563936736', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5895', 'id': 1563936736, 'node_id': 'IC_kwDODunzps5dN8fg', 'user': {'login': 'albertvillanova', 'id': 8515462, 'node_id': 'MDQ6VXNlcjg1MTU0NjI=', 'avatar_url': 'https://avatars.githubusercontent.com/u/8515462?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/albertvillanova', 'html_url': 'https://github.com/albertvillanova', 'followers_url': 'https://api.github.com/users/albertvillanova/followers', 'following_url': 'https://api.github.com/users/albertvillanova/following{/other_user}', 'gists_url': 'https://api.github.com/users/albertvillanova/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/albertvillanova/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/albertvillanova/subscriptions', 'organizations_url': 'https://api.github.com/users/albertvillanova/orgs', 'repos_url': 'https://api.github.com/users/albertvillanova/repos', 'events_url': 'https://api.github.com/users/albertvillanova/events{/privacy}', 'received_events_url': 'https://api.github.com/users/albertvillanova/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-05-26T07:32:53Z', 'updated_at': '2023-05-26T08:36:06Z', 'author_association': 'MEMBER', 'body': 'Thanks for reporting, @DongHande.\r\n\r\nI think the issue is caused by the metadata in the dataset card: in the header of the `README.md`, they state that the dataset has 4 splits ("finetune", "reward", "rl", "evaluation"). \r\n```yaml\r\n  splits:\r\n    - name: finetune\r\n      num_bytes: 6674567576\r\n      num_examples: 3000000\r\n    - name: reward\r\n      num_bytes: 6674341521\r\n      num_examples: 3000000\r\n    - name: rl\r\n      num_bytes: 6679279968\r\n      num_examples: 3000000\r\n    - name: evaluation\r\n      num_bytes: 4022714493\r\n      num_examples: 1807695\r\n```\r\n\r\n\r\nI guess the user wanted to define these as configs, instead of splits. This is not yet supported for no-script datasets, but will be soon supported. See:\r\n- #5331\r\n\r\nI think we should contact the dataset author to inform about the issue with the split names, as you already did: https://huggingface.co/datasets/ArmelR/stack-exchange-instruction/discussions/1\r\nLet\'s continue the discussion there!', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1563936736/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1566409215', 'html_url': 'https://github.com/huggingface/datasets/issues/5895#issuecomment-1566409215', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5895', 'id': 1566409215, 'node_id': 'IC_kwDODunzps5dXYH_', 'user': {'login': 'DongHande', 'id': 45357817, 'node_id': 'MDQ6VXNlcjQ1MzU3ODE3', 'avatar_url': 'https://avatars.githubusercontent.com/u/45357817?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/DongHande', 'html_url': 'https://github.com/DongHande', 'followers_url': 'https://api.github.com/users/DongHande/followers', 'following_url': 'https://api.github.com/users/DongHande/following{/other_user}', 'gists_url': 'https://api.github.com/users/DongHande/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/DongHande/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/DongHande/subscriptions', 'organizations_url': 'https://api.github.com/users/DongHande/orgs', 'repos_url': 'https://api.github.com/users/DongHande/repos', 'events_url': 'https://api.github.com/users/DongHande/events{/privacy}', 'received_events_url': 'https://api.github.com/users/DongHande/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-05-29T02:32:12Z', 'updated_at': '2023-05-29T02:32:12Z', 'author_association': 'NONE', 'body': 'Thank you! It has been fixed. ', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1566409215/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}]
[{'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1562236819', 'html_url': 'https://github.com/huggingface/datasets/pull/5894#issuecomment-1562236819', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5894', 'id': 1562236819, 'node_id': 'IC_kwDODunzps5dHdeT', 'user': {'login': 'HuggingFaceDocBuilderDev', 'id': 99929124, 'node_id': 'U_kgDOBfTMJA', 'avatar_url': 'https://avatars.githubusercontent.com/u/99929124?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/HuggingFaceDocBuilderDev', 'html_url': 'https://github.com/HuggingFaceDocBuilderDev', 'followers_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/followers', 'following_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/following{/other_user}', 'gists_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/subscriptions', 'organizations_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/orgs', 'repos_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/repos', 'events_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/events{/privacy}', 'received_events_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-05-25T04:13:07Z', 'updated_at': '2023-05-25T06:46:04Z', 'author_association': 'NONE', 'body': '_The documentation is not available anymore as the PR was closed or merged._', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1562236819/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1562372802', 'html_url': 'https://github.com/huggingface/datasets/pull/5894#issuecomment-1562372802', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5894', 'id': 1562372802, 'node_id': 'IC_kwDODunzps5dH-rC', 'user': {'login': 'github-actions[bot]', 'id': 41898282, 'node_id': 'MDM6Qm90NDE4OTgyODI=', 'avatar_url': 'https://avatars.githubusercontent.com/in/15368?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/github-actions%5Bbot%5D', 'html_url': 'https://github.com/apps/github-actions', 'followers_url': 'https://api.github.com/users/github-actions%5Bbot%5D/followers', 'following_url': 'https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}', 'gists_url': 'https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/github-actions%5Bbot%5D/subscriptions', 'organizations_url': 'https://api.github.com/users/github-actions%5Bbot%5D/orgs', 'repos_url': 'https://api.github.com/users/github-actions%5Bbot%5D/repos', 'events_url': 'https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}', 'received_events_url': 'https://api.github.com/users/github-actions%5Bbot%5D/received_events', 'type': 'Bot', 'site_admin': False}, 'created_at': '2023-05-25T06:52:08Z', 'updated_at': '2023-05-25T06:52:08Z', 'author_association': 'NONE', 'body': '<details>\n<summary>Show benchmarks</summary>\n\nPyArrow==8.0.0\n\n<details>\n<summary>Show updated benchmarks!</summary>\n\n### Benchmark: benchmark_array_xd.json\n\n| metric | read_batch_formatted_as_numpy after write_array2d | read_batch_formatted_as_numpy after write_flattened_sequence | read_batch_formatted_as_numpy after write_nested_sequence | read_batch_unformated after write_array2d | read_batch_unformated after write_flattened_sequence | read_batch_unformated after write_nested_sequence | read_col_formatted_as_numpy after write_array2d | read_col_formatted_as_numpy after write_flattened_sequence | read_col_formatted_as_numpy after write_nested_sequence | read_col_unformated after write_array2d | read_col_unformated after write_flattened_sequence | read_col_unformated after write_nested_sequence | read_formatted_as_numpy after write_array2d | read_formatted_as_numpy after write_flattened_sequence | read_formatted_as_numpy after write_nested_sequence | read_unformated after write_array2d | read_unformated after write_flattened_sequence | read_unformated after write_nested_sequence | write_array2d | write_flattened_sequence | write_nested_sequence |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.009139 / 0.011353 (-0.002214) | 0.005634 / 0.011008 (-0.005374) | 0.129587 / 0.038508 (0.091079) | 0.038298 / 0.023109 (0.015189) | 0.428149 / 0.275898 (0.152251) | 0.443744 / 0.323480 (0.120264) | 0.007501 / 0.007986 (-0.000485) | 0.005999 / 0.004328 (0.001671) | 0.100796 / 0.004250 (0.096546) | 0.053236 / 0.037052 (0.016184) | 0.423868 / 0.258489 (0.165379) | 0.460110 / 0.293841 (0.166269) | 0.041255 / 0.128546 (-0.087291) | 0.013790 / 0.075646 (-0.061856) | 0.438398 / 0.419271 (0.019127) | 0.063086 / 0.043533 (0.019553) | 0.414826 / 0.255139 (0.159687) | 0.460652 / 0.283200 (0.177453) | 0.121223 / 0.141683 (-0.020460) | 1.754430 / 1.452155 (0.302275) | 1.900037 / 1.492716 (0.407320) |\n\n### Benchmark: benchmark_getitem\\_100B.json\n\n| metric | get_batch_of\\_1024\\_random_rows | get_batch_of\\_1024\\_rows | get_first_row | get_last_row |\n|--------|---|---|---|---|\n| new / old (diff) | 0.027222 / 0.018006 (0.009216) | 0.617666 / 0.000490 (0.617176) | 0.022443 / 0.000200 (0.022243) | 0.000820 / 0.000054 (0.000766) |\n\n### Benchmark: benchmark_indices_mapping.json\n\n| metric | select | shard | shuffle | sort | train_test_split |\n|--------|---|---|---|---|---|\n| new / old (diff) | 0.030397 / 0.037411 (-0.007014) | 0.125732 / 0.014526 (0.111206) | 0.149805 / 0.176557 (-0.026752) | 0.234048 / 0.737135 (-0.503087) | 0.143108 / 0.296338 (-0.153231) |\n\n### Benchmark: benchmark_iterating.json\n\n| metric | read 5000 | read 50000 | read_batch 50000 10 | read_batch 50000 100 | read_batch 50000 1000 | read_formatted numpy 5000 | read_formatted pandas 5000 | read_formatted tensorflow 5000 | read_formatted torch 5000 | read_formatted_batch numpy 5000 10 | read_formatted_batch numpy 5000 1000 | shuffled read 5000 | shuffled read 50000 | shuffled read_batch 50000 10 | shuffled read_batch 50000 100 | shuffled read_batch 50000 1000 | shuffled read_formatted numpy 5000 | shuffled read_formatted_batch numpy 5000 10 | shuffled read_formatted_batch numpy 5000 1000 |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.631189 / 0.215209 (0.415980) | 6.182871 / 2.077655 (4.105216) | 2.635730 / 1.504120 (1.131610) | 2.231429 / 1.541195 (0.690235) | 2.438360 / 1.468490 (0.969870) | 0.861170 / 4.584777 (-3.723607) | 5.785984 / 3.745712 (2.040272) | 2.758358 / 5.269862 (-2.511504) | 1.678095 / 4.565676 (-2.887582) | 0.105961 / 0.424275 (-0.318314) | 0.013659 / 0.007607 (0.006052) | 0.762943 / 0.226044 (0.536898) | 7.774399 / 2.268929 (5.505471) | 3.319027 / 55.444624 (-52.125598) | 2.700248 / 6.876477 (-4.176229) | 3.008581 / 2.142072 (0.866509) | 1.122522 / 4.805227 (-3.682705) | 0.214832 / 6.500664 (-6.285832) | 0.085281 / 0.075469 (0.009811) |\n\n### Benchmark: benchmark_map_filter.json\n\n| metric | filter | map fast-tokenizer batched | map identity | map identity batched | map no-op batched | map no-op batched numpy | map no-op batched pandas | map no-op batched pytorch | map no-op batched tensorflow |\n|--------|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 1.647610 / 1.841788 (-0.194177) | 18.178316 / 8.074308 (10.104008) | 21.199177 / 10.191392 (11.007785) | 0.247063 / 0.680424 (-0.433361) | 0.030443 / 0.534201 (-0.503758) | 0.512527 / 0.579283 (-0.066757) | 0.640758 / 0.434364 (0.206394) | 0.639986 / 0.540337 (0.099649) | 0.760113 / 1.386936 (-0.626823) |\n\n</details>\nPyArrow==latest\n\n<details>\n<summary>Show updated benchmarks!</summary>\n\n### Benchmark: benchmark_array_xd.json\n\n| metric | read_batch_formatted_as_numpy after write_array2d | read_batch_formatted_as_numpy after write_flattened_sequence | read_batch_formatted_as_numpy after write_nested_sequence | read_batch_unformated after write_array2d | read_batch_unformated after write_flattened_sequence | read_batch_unformated after write_nested_sequence | read_col_formatted_as_numpy after write_array2d | read_col_formatted_as_numpy after write_flattened_sequence | read_col_formatted_as_numpy after write_nested_sequence | read_col_unformated after write_array2d | read_col_unformated after write_flattened_sequence | read_col_unformated after write_nested_sequence | read_formatted_as_numpy after write_array2d | read_formatted_as_numpy after write_flattened_sequence | read_formatted_as_numpy after write_nested_sequence | read_unformated after write_array2d | read_unformated after write_flattened_sequence | read_unformated after write_nested_sequence | write_array2d | write_flattened_sequence | write_nested_sequence |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.008293 / 0.011353 (-0.003060) | 0.005360 / 0.011008 (-0.005648) | 0.102932 / 0.038508 (0.064424) | 0.037457 / 0.023109 (0.014347) | 0.444114 / 0.275898 (0.168216) | 0.512855 / 0.323480 (0.189375) | 0.007030 / 0.007986 (-0.000956) | 0.004954 / 0.004328 (0.000625) | 0.095757 / 0.004250 (0.091507) | 0.051239 / 0.037052 (0.014187) | 0.471118 / 0.258489 (0.212629) | 0.517764 / 0.293841 (0.223923) | 0.041953 / 0.128546 (-0.086593) | 0.013748 / 0.075646 (-0.061898) | 0.118089 / 0.419271 (-0.301182) | 0.060159 / 0.043533 (0.016626) | 0.466011 / 0.255139 (0.210872) | 0.489180 / 0.283200 (0.205980) | 0.123250 / 0.141683 (-0.018433) | 1.714738 / 1.452155 (0.262584) | 1.838571 / 1.492716 (0.345855) |\n\n### Benchmark: benchmark_getitem\\_100B.json\n\n| metric | get_batch_of\\_1024\\_random_rows | get_batch_of\\_1024\\_rows | get_first_row | get_last_row |\n|--------|---|---|---|---|\n| new / old (diff) | 0.267792 / 0.018006 (0.249785) | 0.624313 / 0.000490 (0.623824) | 0.007315 / 0.000200 (0.007115) | 0.000136 / 0.000054 (0.000082) |\n\n### Benchmark: benchmark_indices_mapping.json\n\n| metric | select | shard | shuffle | sort | train_test_split |\n|--------|---|---|---|---|---|\n| new / old (diff) | 0.033751 / 0.037411 (-0.003661) | 0.122819 / 0.014526 (0.108293) | 0.148270 / 0.176557 (-0.028286) | 0.198581 / 0.737135 (-0.538554) | 0.144845 / 0.296338 (-0.151494) |\n\n### Benchmark: benchmark_iterating.json\n\n| metric | read 5000 | read 50000 | read_batch 50000 10 | read_batch 50000 100 | read_batch 50000 1000 | read_formatted numpy 5000 | read_formatted pandas 5000 | read_formatted tensorflow 5000 | read_formatted torch 5000 | read_formatted_batch numpy 5000 10 | read_formatted_batch numpy 5000 1000 | shuffled read 5000 | shuffled read 50000 | shuffled read_batch 50000 10 | shuffled read_batch 50000 100 | shuffled read_batch 50000 1000 | shuffled read_formatted numpy 5000 | shuffled read_formatted_batch numpy 5000 10 | shuffled read_formatted_batch numpy 5000 1000 |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.620631 / 0.215209 (0.405422) | 6.224665 / 2.077655 (4.147010) | 2.856592 / 1.504120 (1.352473) | 2.525089 / 1.541195 (0.983894) | 2.600198 / 1.468490 (1.131708) | 0.872038 / 4.584777 (-3.712739) | 5.571650 / 3.745712 (1.825937) | 5.907643 / 5.269862 (0.637782) | 2.348770 / 4.565676 (-2.216906) | 0.111665 / 0.424275 (-0.312610) | 0.013886 / 0.007607 (0.006278) | 0.762154 / 0.226044 (0.536109) | 7.792686 / 2.268929 (5.523758) | 3.601122 / 55.444624 (-51.843503) | 2.939412 / 6.876477 (-3.937064) | 2.973430 / 2.142072 (0.831358) | 1.065016 / 4.805227 (-3.740211) | 0.221701 / 6.500664 (-6.278963) | 0.088157 / 0.075469 (0.012688) |\n\n### Benchmark: benchmark_map_filter.json\n\n| metric | filter | map fast-tokenizer batched | map identity | map identity batched | map no-op batched | map no-op batched numpy | map no-op batched pandas | map no-op batched pytorch | map no-op batched tensorflow |\n|--------|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 1.771061 / 1.841788 (-0.070727) | 18.826926 / 8.074308 (10.752618) | 21.283830 / 10.191392 (11.092438) | 0.239233 / 0.680424 (-0.441191) | 0.026159 / 0.534201 (-0.508042) | 0.487074 / 0.579283 (-0.092209) | 0.623241 / 0.434364 (0.188877) | 0.600506 / 0.540337 (0.060169) | 0.691271 / 1.386936 (-0.695665) |\n\n</details>\n</details>\n\n![](https://cml.dev/watermark.png#1bbe2c3496498a6415765b517ac4bc600a02ad06 "CML watermark")\n', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1562372802/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}]

[{'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1559882746', 'html_url': 'https://github.com/huggingface/datasets/pull/5893#issuecomment-1559882746', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5893', 'id': 1559882746, 'node_id': 'IC_kwDODunzps5c-ev6', 'user': {'login': 'mariusz-jachimowicz-83', 'id': 10278877, 'node_id': 'MDQ6VXNlcjEwMjc4ODc3', 'avatar_url': 'https://avatars.githubusercontent.com/u/10278877?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/mariusz-jachimowicz-83', 'html_url': 'https://github.com/mariusz-jachimowicz-83', 'followers_url': 'https://api.github.com/users/mariusz-jachimowicz-83/followers', 'following_url': 'https://api.github.com/users/mariusz-jachimowicz-83/following{/other_user}', 'gists_url': 'https://api.github.com/users/mariusz-jachimowicz-83/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/mariusz-jachimowicz-83/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/mariusz-jachimowicz-83/subscriptions', 'organizations_url': 'https://api.github.com/users/mariusz-jachimowicz-83/orgs', 'repos_url': 'https://api.github.com/users/mariusz-jachimowicz-83/repos', 'events_url': 'https://api.github.com/users/mariusz-jachimowicz-83/events{/privacy}', 'received_events_url': 'https://api.github.com/users/mariusz-jachimowicz-83/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-05-23T17:42:20Z', 'updated_at': '2023-05-23T17:42:20Z', 'author_association': 'CONTRIBUTOR', 'body': '@lhoestq Could you please look into that and review?', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1559882746/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1561336862', 'html_url': 'https://github.com/huggingface/datasets/pull/5893#issuecomment-1561336862', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5893', 'id': 1561336862, 'node_id': 'IC_kwDODunzps5dEBwe', 'user': {'login': 'HuggingFaceDocBuilderDev', 'id': 99929124, 'node_id': 'U_kgDOBfTMJA', 'avatar_url': 'https://avatars.githubusercontent.com/u/99929124?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/HuggingFaceDocBuilderDev', 'html_url': 'https://github.com/HuggingFaceDocBuilderDev', 'followers_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/followers', 'following_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/following{/other_user}', 'gists_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/subscriptions', 'organizations_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/orgs', 'repos_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/repos', 'events_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/events{/privacy}', 'received_events_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-05-24T15:07:04Z', 'updated_at': '2023-06-01T11:54:33Z', 'author_association': 'NONE', 'body': '_The documentation is not available anymore as the PR was closed or merged._', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1561336862/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1565104854', 'html_url': 'https://github.com/huggingface/datasets/pull/5893#issuecomment-1565104854', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5893', 'id': 1565104854, 'node_id': 'IC_kwDODunzps5dSZrW', 'user': {'login': 'mariusz-jachimowicz-83', 'id': 10278877, 'node_id': 'MDQ6VXNlcjEwMjc4ODc3', 'avatar_url': 'https://avatars.githubusercontent.com/u/10278877?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/mariusz-jachimowicz-83', 'html_url': 'https://github.com/mariusz-jachimowicz-83', 'followers_url': 'https://api.github.com/users/mariusz-jachimowicz-83/followers', 'following_url': 'https://api.github.com/users/mariusz-jachimowicz-83/following{/other_user}', 'gists_url': 'https://api.github.com/users/mariusz-jachimowicz-83/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/mariusz-jachimowicz-83/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/mariusz-jachimowicz-83/subscriptions', 'organizations_url': 'https://api.github.com/users/mariusz-jachimowicz-83/orgs', 'repos_url': 'https://api.github.com/users/mariusz-jachimowicz-83/repos', 'events_url': 'https://api.github.com/users/mariusz-jachimowicz-83/events{/privacy}', 'received_events_url': 'https://api.github.com/users/mariusz-jachimowicz-83/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-05-27T00:32:27Z', 'updated_at': '2023-05-27T00:32:27Z', 'author_association': 'CONTRIBUTOR', 'body': '@lhoestq I refactored the code. Could you please check is it what you requested?', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1565104854/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1568234498', 'html_url': 'https://github.com/huggingface/datasets/pull/5893#issuecomment-1568234498', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5893', 'id': 1568234498, 'node_id': 'IC_kwDODunzps5deVwC', 'user': {'login': 'mariusz-jachimowicz-83', 'id': 10278877, 'node_id': 'MDQ6VXNlcjEwMjc4ODc3', 'avatar_url': 'https://avatars.githubusercontent.com/u/10278877?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/mariusz-jachimowicz-83', 'html_url': 'https://github.com/mariusz-jachimowicz-83', 'followers_url': 'https://api.github.com/users/mariusz-jachimowicz-83/followers', 'following_url': 'https://api.github.com/users/mariusz-jachimowicz-83/following{/other_user}', 'gists_url': 'https://api.github.com/users/mariusz-jachimowicz-83/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/mariusz-jachimowicz-83/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/mariusz-jachimowicz-83/subscriptions', 'organizations_url': 'https://api.github.com/users/mariusz-jachimowicz-83/orgs', 'repos_url': 'https://api.github.com/users/mariusz-jachimowicz-83/repos', 'events_url': 'https://api.github.com/users/mariusz-jachimowicz-83/events{/privacy}', 'received_events_url': 'https://api.github.com/users/mariusz-jachimowicz-83/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-05-30T11:04:50Z', 'updated_at': '2023-05-30T11:04:50Z', 'author_association': 'CONTRIBUTOR', 'body': '@lhoestq  Thanks for a review. Excellent tips. All tips applied. ', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1568234498/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1570417355', 'html_url': 'https://github.com/huggingface/datasets/pull/5893#issuecomment-1570417355', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5893', 'id': 1570417355, 'node_id': 'IC_kwDODunzps5dmqrL', 'user': {'login': 'lhoestq', 'id': 42851186, 'node_id': 'MDQ6VXNlcjQyODUxMTg2', 'avatar_url': 'https://avatars.githubusercontent.com/u/42851186?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/lhoestq', 'html_url': 'https://github.com/lhoestq', 'followers_url': 'https://api.github.com/users/lhoestq/followers', 'following_url': 'https://api.github.com/users/lhoestq/following{/other_user}', 'gists_url': 'https://api.github.com/users/lhoestq/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/lhoestq/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/lhoestq/subscriptions', 'organizations_url': 'https://api.github.com/users/lhoestq/orgs', 'repos_url': 'https://api.github.com/users/lhoestq/repos', 'events_url': 'https://api.github.com/users/lhoestq/events{/privacy}', 'received_events_url': 'https://api.github.com/users/lhoestq/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-05-31T15:06:55Z', 'updated_at': '2023-05-31T15:06:55Z', 'author_association': 'MEMBER', 'body': 'I think there is just PythonFormatter that needs to be imported in the test file and we should be good to merge', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1570417355/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1570593825', 'html_url': 'https://github.com/huggingface/datasets/pull/5893#issuecomment-1570593825', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5893', 'id': 1570593825, 'node_id': 'IC_kwDODunzps5dnVwh', 'user': {'login': 'mariusz-jachimowicz-83', 'id': 10278877, 'node_id': 'MDQ6VXNlcjEwMjc4ODc3', 'avatar_url': 'https://avatars.githubusercontent.com/u/10278877?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/mariusz-jachimowicz-83', 'html_url': 'https://github.com/mariusz-jachimowicz-83', 'followers_url': 'https://api.github.com/users/mariusz-jachimowicz-83/followers', 'following_url': 'https://api.github.com/users/mariusz-jachimowicz-83/following{/other_user}', 'gists_url': 'https://api.github.com/users/mariusz-jachimowicz-83/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/mariusz-jachimowicz-83/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/mariusz-jachimowicz-83/subscriptions', 'organizations_url': 'https://api.github.com/users/mariusz-jachimowicz-83/orgs', 'repos_url': 'https://api.github.com/users/mariusz-jachimowicz-83/repos', 'events_url': 'https://api.github.com/users/mariusz-jachimowicz-83/events{/privacy}', 'received_events_url': 'https://api.github.com/users/mariusz-jachimowicz-83/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-05-31T17:01:07Z', 'updated_at': '2023-05-31T17:01:07Z', 'author_association': 'CONTRIBUTOR', 'body': '@lhoestq that is weird. I have linter error when I do it.', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1570593825/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1570796423', 'html_url': 'https://github.com/huggingface/datasets/pull/5893#issuecomment-1570796423', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5893', 'id': 1570796423, 'node_id': 'IC_kwDODunzps5doHOH', 'user': {'login': 'mariusz-jachimowicz-83', 'id': 10278877, 'node_id': 'MDQ6VXNlcjEwMjc4ODc3', 'avatar_url': 'https://avatars.githubusercontent.com/u/10278877?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/mariusz-jachimowicz-83', 'html_url': 'https://github.com/mariusz-jachimowicz-83', 'followers_url': 'https://api.github.com/users/mariusz-jachimowicz-83/followers', 'following_url': 'https://api.github.com/users/mariusz-jachimowicz-83/following{/other_user}', 'gists_url': 'https://api.github.com/users/mariusz-jachimowicz-83/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/mariusz-jachimowicz-83/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/mariusz-jachimowicz-83/subscriptions', 'organizations_url': 'https://api.github.com/users/mariusz-jachimowicz-83/orgs', 'repos_url': 'https://api.github.com/users/mariusz-jachimowicz-83/repos', 'events_url': 'https://api.github.com/users/mariusz-jachimowicz-83/events{/privacy}', 'received_events_url': 'https://api.github.com/users/mariusz-jachimowicz-83/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-05-31T19:18:03Z', 'updated_at': '2023-05-31T19:18:03Z', 'author_association': 'CONTRIBUTOR', 'body': '@lhoestq Now it should work properly.', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1570796423/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1571916867', 'html_url': 'https://github.com/huggingface/datasets/pull/5893#issuecomment-1571916867', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5893', 'id': 1571916867, 'node_id': 'IC_kwDODunzps5dsYxD', 'user': {'login': 'github-actions[bot]', 'id': 41898282, 'node_id': 'MDM6Qm90NDE4OTgyODI=', 'avatar_url': 'https://avatars.githubusercontent.com/in/15368?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/github-actions%5Bbot%5D', 'html_url': 'https://github.com/apps/github-actions', 'followers_url': 'https://api.github.com/users/github-actions%5Bbot%5D/followers', 'following_url': 'https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}', 'gists_url': 'https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/github-actions%5Bbot%5D/subscriptions', 'organizations_url': 'https://api.github.com/users/github-actions%5Bbot%5D/orgs', 'repos_url': 'https://api.github.com/users/github-actions%5Bbot%5D/repos', 'events_url': 'https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}', 'received_events_url': 'https://api.github.com/users/github-actions%5Bbot%5D/received_events', 'type': 'Bot', 'site_admin': False}, 'created_at': '2023-06-01T11:58:23Z', 'updated_at': '2023-06-01T11:58:23Z', 'author_association': 'NONE', 'body': '<details>\n<summary>Show benchmarks</summary>\n\nPyArrow==8.0.0\n\n<details>\n<summary>Show updated benchmarks!</summary>\n\n### Benchmark: benchmark_array_xd.json\n\n| metric | read_batch_formatted_as_numpy after write_array2d | read_batch_formatted_as_numpy after write_flattened_sequence | read_batch_formatted_as_numpy after write_nested_sequence | read_batch_unformated after write_array2d | read_batch_unformated after write_flattened_sequence | read_batch_unformated after write_nested_sequence | read_col_formatted_as_numpy after write_array2d | read_col_formatted_as_numpy after write_flattened_sequence | read_col_formatted_as_numpy after write_nested_sequence | read_col_unformated after write_array2d | read_col_unformated after write_flattened_sequence | read_col_unformated after write_nested_sequence | read_formatted_as_numpy after write_array2d | read_formatted_as_numpy after write_flattened_sequence | read_formatted_as_numpy after write_nested_sequence | read_unformated after write_array2d | read_unformated after write_flattened_sequence | read_unformated after write_nested_sequence | write_array2d | write_flattened_sequence | write_nested_sequence |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.006152 / 0.011353 (-0.005201) | 0.004169 / 0.011008 (-0.006839) | 0.097968 / 0.038508 (0.059460) | 0.028325 / 0.023109 (0.005216) | 0.308958 / 0.275898 (0.033060) | 0.341832 / 0.323480 (0.018352) | 0.005098 / 0.007986 (-0.002887) | 0.004721 / 0.004328 (0.000393) | 0.075067 / 0.004250 (0.070817) | 0.040514 / 0.037052 (0.003462) | 0.308355 / 0.258489 (0.049866) | 0.351063 / 0.293841 (0.057222) | 0.025261 / 0.128546 (-0.103285) | 0.008483 / 0.075646 (-0.067163) | 0.321219 / 0.419271 (-0.098052) | 0.058258 / 0.043533 (0.014725) | 0.312572 / 0.255139 (0.057433) | 0.330667 / 0.283200 (0.047467) | 0.091047 / 0.141683 (-0.050635) | 1.536541 / 1.452155 (0.084387) | 1.606566 / 1.492716 (0.113850) |\n\n### Benchmark: benchmark_getitem\\_100B.json\n\n| metric | get_batch_of\\_1024\\_random_rows | get_batch_of\\_1024\\_rows | get_first_row | get_last_row |\n|--------|---|---|---|---|\n| new / old (diff) | 0.213234 / 0.018006 (0.195228) | 0.494801 / 0.000490 (0.494311) | 0.003764 / 0.000200 (0.003564) | 0.000074 / 0.000054 (0.000019) |\n\n### Benchmark: benchmark_indices_mapping.json\n\n| metric | select | shard | shuffle | sort | train_test_split |\n|--------|---|---|---|---|---|\n| new / old (diff) | 0.023653 / 0.037411 (-0.013758) | 0.097176 / 0.014526 (0.082650) | 0.102961 / 0.176557 (-0.073595) | 0.164285 / 0.737135 (-0.572851) | 0.107586 / 0.296338 (-0.188753) |\n\n### Benchmark: benchmark_iterating.json\n\n| metric | read 5000 | read 50000 | read_batch 50000 10 | read_batch 50000 100 | read_batch 50000 1000 | read_formatted numpy 5000 | read_formatted pandas 5000 | read_formatted tensorflow 5000 | read_formatted torch 5000 | read_formatted_batch numpy 5000 10 | read_formatted_batch numpy 5000 1000 | shuffled read 5000 | shuffled read 50000 | shuffled read_batch 50000 10 | shuffled read_batch 50000 100 | shuffled read_batch 50000 1000 | shuffled read_formatted numpy 5000 | shuffled read_formatted_batch numpy 5000 10 | shuffled read_formatted_batch numpy 5000 1000 |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.421402 / 0.215209 (0.206193) | 4.195828 / 2.077655 (2.118174) | 1.884664 / 1.504120 (0.380544) | 1.679750 / 1.541195 (0.138556) | 1.719725 / 1.468490 (0.251235) | 0.552290 / 4.584777 (-4.032486) | 3.386337 / 3.745712 (-0.359375) | 1.771527 / 5.269862 (-3.498334) | 1.133327 / 4.565676 (-3.432349) | 0.067911 / 0.424275 (-0.356364) | 0.012572 / 0.007607 (0.004965) | 0.518004 / 0.226044 (0.291960) | 5.192381 / 2.268929 (2.923453) | 2.316032 / 55.444624 (-53.128592) | 1.993264 / 6.876477 (-4.883212) | 2.071009 / 2.142072 (-0.071063) | 0.655062 / 4.805227 (-4.150165) | 0.135488 / 6.500664 (-6.365177) | 0.067273 / 0.075469 (-0.008196) |\n\n### Benchmark: benchmark_map_filter.json\n\n| metric | filter | map fast-tokenizer batched | map identity | map identity batched | map no-op batched | map no-op batched numpy | map no-op batched pandas | map no-op batched pytorch | map no-op batched tensorflow |\n|--------|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 1.217731 / 1.841788 (-0.624056) | 13.812927 / 8.074308 (5.738619) | 13.137886 / 10.191392 (2.946494) | 0.143102 / 0.680424 (-0.537322) | 0.016884 / 0.534201 (-0.517317) | 0.370106 / 0.579283 (-0.209178) | 0.392349 / 0.434364 (-0.042015) | 0.424501 / 0.540337 (-0.115837) | 0.509830 / 1.386936 (-0.877106) |\n\n</details>\nPyArrow==latest\n\n<details>\n<summary>Show updated benchmarks!</summary>\n\n### Benchmark: benchmark_array_xd.json\n\n| metric | read_batch_formatted_as_numpy after write_array2d | read_batch_formatted_as_numpy after write_flattened_sequence | read_batch_formatted_as_numpy after write_nested_sequence | read_batch_unformated after write_array2d | read_batch_unformated after write_flattened_sequence | read_batch_unformated after write_nested_sequence | read_col_formatted_as_numpy after write_array2d | read_col_formatted_as_numpy after write_flattened_sequence | read_col_formatted_as_numpy after write_nested_sequence | read_col_unformated after write_array2d | read_col_unformated after write_flattened_sequence | read_col_unformated after write_nested_sequence | read_formatt

[{'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1559897033', 'html_url': 'https://github.com/huggingface/datasets/issues/5892#issuecomment-1559897033', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5892', 'id': 1559897033, 'node_id': 'IC_kwDODunzps5c-iPJ', 'user': {'login': 'mariosasko', 'id': 47462742, 'node_id': 'MDQ6VXNlcjQ3NDYyNzQy', 'avatar_url': 'https://avatars.githubusercontent.com/u/47462742?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/mariosasko', 'html_url': 'https://github.com/mariosasko', 'followers_url': 'https://api.github.com/users/mariosasko/followers', 'following_url': 'https://api.github.com/users/mariosasko/following{/other_user}', 'gists_url': 'https://api.github.com/users/mariosasko/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/mariosasko/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/mariosasko/subscriptions', 'organizations_url': 'https://api.github.com/users/mariosasko/orgs', 'repos_url': 'https://api.github.com/users/mariosasko/repos', 'events_url': 'https://api.github.com/users/mariosasko/events{/privacy}', 'received_events_url': 'https://api.github.com/users/mariosasko/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-05-23T17:54:48Z', 'updated_at': '2023-05-23T17:54:48Z', 'author_association': 'CONTRIBUTOR', 'body': 'cc @SBrandeis', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1559897033/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}]
[{'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1559747650', 'html_url': 'https://github.com/huggingface/datasets/pull/5891#issuecomment-1559747650', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5891', 'id': 1559747650, 'node_id': 'IC_kwDODunzps5c99xC', 'user': {'login': 'HuggingFaceDocBuilderDev', 'id': 99929124, 'node_id': 'U_kgDOBfTMJA', 'avatar_url': 'https://avatars.githubusercontent.com/u/99929124?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/HuggingFaceDocBuilderDev', 'html_url': 'https://github.com/HuggingFaceDocBuilderDev', 'followers_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/followers', 'following_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/following{/other_user}', 'gists_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/subscriptions', 'organizations_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/orgs', 'repos_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/repos', 'events_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/events{/privacy}', 'received_events_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-05-23T16:09:01Z', 'updated_at': '2023-05-23T16:09:01Z', 'author_association': 'NONE', 'body': 'The docs for this PR live [here](https://moon-ci-docs.huggingface.co/docs/datasets/pr_5891). All of your documentation changes will be reflected on that endpoint.', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1559747650/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1559750928', 'html_url': 'https://github.com/huggingface/datasets/pull/5891#issuecomment-1559750928', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5891', 'id': 1559750928, 'node_id': 'IC_kwDODunzps5c9-kQ', 'user': {'login': 'github-actions[bot]', 'id': 41898282, 'node_id': 'MDM6Qm90NDE4OTgyODI=', 'avatar_url': 'https://avatars.githubusercontent.com/in/15368?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/github-actions%5Bbot%5D', 'html_url': 'https://github.com/apps/github-actions', 'followers_url': 'https://api.github.com/users/github-actions%5Bbot%5D/followers', 'following_url': 'https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}', 'gists_url': 'https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/github-actions%5Bbot%5D/subscriptions', 'organizations_url': 'https://api.github.com/users/github-actions%5Bbot%5D/orgs', 'repos_url': 'https://api.github.com/users/github-actions%5Bbot%5D/repos', 'events_url': 'https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}', 'received_events_url': 'https://api.github.com/users/github-actions%5Bbot%5D/received_events', 'type': 'Bot', 'site_admin': False}, 'created_at': '2023-05-23T16:11:11Z', 'updated_at': '2023-05-23T16:11:11Z', 'author_association': 'NONE', 'body': '<details>\n<summary>Show benchmarks</summary>\n\nPyArrow==8.0.0\n\n<details>\n<summary>Show updated benchmarks!</summary>\n\n### Benchmark: benchmark_array_xd.json\n\n| metric | read_batch_formatted_as_numpy after write_array2d | read_batch_formatted_as_numpy after write_flattened_sequence | read_batch_formatted_as_numpy after write_nested_sequence | read_batch_unformated after write_array2d | read_batch_unformated after write_flattened_sequence | read_batch_unformated after write_nested_sequence | read_col_formatted_as_numpy after write_array2d | read_col_formatted_as_numpy after write_flattened_sequence | read_col_formatted_as_numpy after write_nested_sequence | read_col_unformated after write_array2d | read_col_unformated after write_flattened_sequence | read_col_unformated after write_nested_sequence | read_formatted_as_numpy after write_array2d | read_formatted_as_numpy after write_flattened_sequence | read_formatted_as_numpy after write_nested_sequence | read_unformated after write_array2d | read_unformated after write_flattened_sequence | read_unformated after write_nested_sequence | write_array2d | write_flattened_sequence | write_nested_sequence |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.006916 / 0.011353 (-0.004437) | 0.004749 / 0.011008 (-0.006259) | 0.096086 / 0.038508 (0.057578) | 0.035448 / 0.023109 (0.012338) | 0.299645 / 0.275898 (0.023747) | 0.331279 / 0.323480 (0.007799) | 0.006018 / 0.007986 (-0.001968) | 0.004210 / 0.004328 (-0.000118) | 0.072998 / 0.004250 (0.068747) | 0.050082 / 0.037052 (0.013030) | 0.297714 / 0.258489 (0.039225) | 0.365523 / 0.293841 (0.071682) | 0.028081 / 0.128546 (-0.100465) | 0.009072 / 0.075646 (-0.066574) | 0.327628 / 0.419271 (-0.091643) | 0.051165 / 0.043533 (0.007633) | 0.295091 / 0.255139 (0.039952) | 0.320052 / 0.283200 (0.036852) | 0.109841 / 0.141683 (-0.031842) | 1.467867 / 1.452155 (0.015712) | 1.572600 / 1.492716 (0.079884) |\n\n### Benchmark: benchmark_getitem\\_100B.json\n\n| metric | get_batch_of\\_1024\\_random_rows | get_batch_of\\_1024\\_rows | get_first_row | get_last_row |\n|--------|---|---|---|---|\n| new / old (diff) | 0.281490 / 0.018006 (0.263484) | 0.499259 / 0.000490 (0.498770) | 0.000691 / 0.000200 (0.000491) | 0.000062 / 0.000054 (0.000008) |\n\n### Benchmark: benchmark_indices_mapping.json\n\n| metric | select | shard | shuffle | sort | train_test_split |\n|--------|---|---|---|---|---|\n| new / old (diff) | 0.027548 / 0.037411 (-0.009863) | 0.106592 / 0.014526 (0.092066) | 0.118654 / 0.176557 (-0.057902) | 0.174313 / 0.737135 (-0.562822) | 0.124491 / 0.296338 (-0.171848) |\n\n### Benchmark: benchmark_iterating.json\n\n| metric | read 5000 | read 50000 | read_batch 50000 10 | read_batch 50000 100 | read_batch 50000 1000 | read_formatted numpy 5000 | read_formatted pandas 5000 | read_formatted tensorflow 5000 | read_formatted torch 5000 | read_formatted_batch numpy 5000 10 | read_formatted_batch numpy 5000 1000 | shuffled read 5000 | shuffled read 50000 | shuffled read_batch 50000 10 | shuffled read_batch 50000 100 | shuffled read_batch 50000 1000 | shuffled read_formatted numpy 5000 | shuffled read_formatted_batch numpy 5000 10 | shuffled read_formatted_batch numpy 5000 1000 |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.399674 / 0.215209 (0.184465) | 3.984092 / 2.077655 (1.906437) | 1.790935 / 1.504120 (0.286815) | 1.593612 / 1.541195 (0.052417) | 1.694595 / 1.468490 (0.226105) | 0.517588 / 4.584777 (-4.067189) | 3.724353 / 3.745712 (-0.021359) | 3.244807 / 5.269862 (-2.025054) | 1.602929 / 4.565676 (-2.962748) | 0.065334 / 0.424275 (-0.358941) | 0.012259 / 0.007607 (0.004652) | 0.501355 / 0.226044 (0.275311) | 4.996546 / 2.268929 (2.727618) | 2.279333 / 55.444624 (-53.165291) | 1.940126 / 6.876477 (-4.936351) | 2.122945 / 2.142072 (-0.019128) | 0.626104 / 4.805227 (-4.179123) | 0.141278 / 6.500664 (-6.359386) | 0.064522 / 0.075469 (-0.010947) |\n\n### Benchmark: benchmark_map_filter.json\n\n| metric | filter | map fast-tokenizer batched | map identity | map identity batched | map no-op batched | map no-op batched numpy | map no-op batched pandas | map no-op batched pytorch | map no-op batched tensorflow |\n|--------|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 1.195351 / 1.841788 (-0.646436) | 15.258932 / 8.074308 (7.184624) | 14.627623 / 10.191392 (4.436231) | 0.266897 / 0.680424 (-0.413527) | 0.017557 / 0.534201 (-0.516644) | 0.392932 / 0.579283 (-0.186351) | 0.416409 / 0.434364 (-0.017955) | 0.469100 / 0.540337 (-0.071237) | 0.556247 / 1.386936 (-0.830689) |\n\n</details>\nPyArrow==latest\n\n<details>\n<summary>Show updated benchmarks!</summary>\n\n### Benchmark: benchmark_array_xd.json\n\n| metric | read_batch_formatted_as_numpy after write_array2d | read_batch_formatted_as_numpy after write_flattened_sequence | read_batch_formatted_as_numpy after write_nested_sequence | read_batch_unformated after write_array2d | read_batch_unformated after write_flattened_sequence | read_batch_unformated after write_nested_sequence | read_col_formatted_as_numpy after write_array2d | read_col_formatted_as_numpy after write_flattened_sequence | read_col_formatted_as_numpy after write_nested_sequence | read_col_unformated after write_array2d | read_col_unformated after write_flattened_sequence | read_col_unformated after write_nested_sequence | read_formatted_as_numpy after write_array2d | read_formatted_as_numpy after write_flattened_sequence | read_formatted_as_numpy after write_nested_sequence | read_unformated after write_array2d | read_unformated after write_flattened_sequence | read_unformated after write_nested_sequence | write_array2d | write_flattened_sequence | write_nested_sequence |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.006880 / 0.011353 (-0.004473) | 0.004837 / 0.011008 (-0.006171) | 0.074518 / 0.038508 (0.036010) | 0.034204 / 0.023109 (0.011095) | 0.365100 / 0.275898 (0.089202) | 0.394976 / 0.323480 (0.071496) | 0.006364 / 0.007986 (-0.001621) | 0.004269 / 0.004328 (-0.000060) | 0.073531 / 0.004250 (0.069281) | 0.051334 / 0.037052 (0.014281) | 0.373904 / 0.258489 (0.115415) | 0.413662 / 0.293841 (0.119821) | 0.028779 / 0.128546 (-0.099767) | 0.009292 / 0.075646 (-0.066354) | 0.081574 / 0.419271 (-0.337698) | 0.046531 / 0.043533 (0.002998) | 0.368995 / 0.255139 (0.113856) | 0.376938 / 0.283200 (0.093739) | 0.112576 / 0.141683 (-0.029107) | 1.458880 / 1.452155 (0.006725) | 1.550918 / 1.492716 (0.058202) |\n\n### Benchmark: benchmark_getitem\\_100B.json\n\n| metric | get_batch_of\\_1024\\_random_rows | get_batch_of\\_1024\\_rows | get_first_row | get_last_row |\n|--------|---|---|---|---|\n| new / old (diff) | 0.319521 / 0.018006 (0.301515) | 0.510146 / 0.000490 (0.509656) | 0.000438 / 0.000200 (0.000238) | 0.000059 / 0.000054 (0.000004) |\n\n### Benchmark: benchmark_indices_mapping.json\n\n| metric | select | shard | shuffle | sort | train_test_split |\n|--------|---|---|---|---|---|\n| new / old (diff) | 0.033082 / 0.037411 (-0.004329) | 0.118009 / 0.014526 (0.103483) | 0.127108 / 0.176557 (-0.049448) | 0.176600 / 0.737135 (-0.560535) | 0.133790 / 0.296338 (-0.162549) |\n\n### Benchmark: benchmark_iterating.json\n\n| metric | read 5000 | read 50000 | read_batch 50000 10 | read_batch 50000 100 | read_batch 50000 1000 | read_formatted numpy 5000 | read_formatted pandas 5000 | read_formatted tensorflow 5000 | read_formatted torch 5000 | read_formatted_batch numpy 5000 10 | read_formatted_batch numpy 5000 1000 | shuffled read 5000 | shuffled read 50000 | shuffled read_batch 50000 10 | shuffled read_batch 50000 100 | shuffled read_batch 50000 1000 | shuffled read_formatted numpy 5000 | shuffled read_formatted_batch numpy 5000 10 | shuffled read_formatted_batch numpy 5000 1000 |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.437360 / 0.215209 (0.222151) | 4.367426 / 2.077655 (2.289771) | 2.193646 / 1.504120 (0.689526) | 2.025002 / 1.541195 (0.483808) | 2.142347 / 1.468490 (0.673856) | 0.525497 / 4.584777 (-4.059280) | 3.751275 / 3.745712 (0.005563) | 1.912271 / 5.269862 (-3.357590) | 1.087286 / 4.565676 (-3.478390) | 0.066328 / 0.424275 (-0.357947) | 0.011904 / 0.007607 (0.004297) | 0.545870 / 0.226044 (0.319825) | 5.434481 / 2.268929 (3.165552) | 2.719745 / 55.444624 (-52.724880) | 2.445001 / 6.876477 (-4.431476) | 2.500205 / 2.142072 (0.358133) | 0.645735 / 4.805227 (-4.159492) | 0.144210 / 6.500664 (-6.356455) | 0.065688 / 0.075469 (-0.009781) |\n\n### Benchmark: benchmark_map_filter.json\n\n| metric | filter | map fast-tokenizer batched | map identity | map identity batched | map no-op batched | map no-op batched numpy | map no-op batched pandas | map no-op batched pytorch | map no-op batched tensorflow |\n|--------|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 1.273522 / 1.841788 (-0.568265) | 15.771778 / 8.074308 (7.697470) | 14.685261 / 10.191392 (4.493869) | 0.176523 / 0.680424 (-0.503900) | 0.017877 / 0.534201 (-0.516324) | 0.392687 / 0.579283 (-0.186596) | 0.449992 / 0.434364 (0.015628) | 0.462851 / 0.540337 (-0.077487) | 0.560178 / 1.386936 (-0.826758) |\n\n</details>\n</details>\n\n![](https://cml.dev/watermark.png#0fa3ef6eba906ee1214e0596d15a78fc358909f4 "CML watermark")\n', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1559750928/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}]

[]
[{'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1564138267', 'html_url': 'https://github.com/huggingface/datasets/issues/5887#issuecomment-1564138267', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5887', 'id': 1564138267, 'node_id': 'IC_kwDODunzps5dOtsb', 'user': {'login': 'alvarobartt', 'id': 36760800, 'node_id': 'MDQ6VXNlcjM2NzYwODAw', 'avatar_url': 'https://avatars.githubusercontent.com/u/36760800?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/alvarobartt', 'html_url': 'https://github.com/alvarobartt', 'followers_url': 'https://api.github.com/users/alvarobartt/followers', 'following_url': 'https://api.github.com/users/alvarobartt/following{/other_user}', 'gists_url': 'https://api.github.com/users/alvarobartt/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/alvarobartt/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/alvarobartt/subscriptions', 'organizations_url': 'https://api.github.com/users/alvarobartt/orgs', 'repos_url': 'https://api.github.com/users/alvarobartt/repos', 'events_url': 'https://api.github.com/users/alvarobartt/events{/privacy}', 'received_events_url': 'https://api.github.com/users/alvarobartt/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-05-26T10:02:06Z', 'updated_at': '2023-05-26T10:12:55Z', 'author_association': 'CONTRIBUTOR', 'body': "Nice catch @donhuvy, that's because some models don't need the `token_type_ids`, as in this case, as the example is using `distilbert-base-cased`, and according to the DistilBert documentation at https://huggingface.co/transformers/v3.0.2/model_doc/distilbert.html, `DistilBert doesn’t have token_type_ids, you don’t need to indicate which token belongs to which segment. Just separate your segments with the separation token tokenizer.sep_token (or [SEP])`. `token_type_ids` are neither required in some other well known models such as RoBERTa. \r\n\r\nHere the issue comes due to a mismatch between the tokenizer and the model, as the Colab is using a BERT tokenizer (`bert-base-cased`), while the model is a DistilBERT (`distilbert-base-cased`), so aligning the tokenizer and the model solves it!", 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1564138267/reactions', 'total_count': 1, '+1': 1, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1564143239', 'html_url': 'https://github.com/huggingface/datasets/issues/5887#issuecomment-1564143239', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5887', 'id': 1564143239, 'node_id': 'IC_kwDODunzps5dOu6H', 'user': {'login': 'alvarobartt', 'id': 36760800, 'node_id': 'MDQ6VXNlcjM2NzYwODAw', 'avatar_url': 'https://avatars.githubusercontent.com/u/36760800?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/alvarobartt', 'html_url': 'https://github.com/alvarobartt', 'followers_url': 'https://api.github.com/users/alvarobartt/followers', 'following_url': 'https://api.github.com/users/alvarobartt/following{/other_user}', 'gists_url': 'https://api.github.com/users/alvarobartt/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/alvarobartt/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/alvarobartt/subscriptions', 'organizations_url': 'https://api.github.com/users/alvarobartt/orgs', 'repos_url': 'https://api.github.com/users/alvarobartt/repos', 'events_url': 'https://api.github.com/users/alvarobartt/events{/privacy}', 'received_events_url': 'https://api.github.com/users/alvarobartt/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-05-26T10:05:38Z', 'updated_at': '2023-05-26T10:05:38Z', 'author_association': 'CONTRIBUTOR', 'body': '#self-assign', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1564143239/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1564176255', 'html_url': 'https://github.com/huggingface/datasets/issues/5887#issuecomment-1564176255', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5887', 'id': 1564176255, 'node_id': 'IC_kwDODunzps5dO29_', 'user': {'login': 'alvarobartt', 'id': 36760800, 'node_id': 'MDQ6VXNlcjM2NzYwODAw', 'avatar_url': 'https://avatars.githubusercontent.com/u/36760800?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/alvarobartt', 'html_url': 'https://github.com/alvarobartt', 'followers_url': 'https://api.github.com/users/alvarobartt/followers', 'following_url': 'https://api.github.com/users/alvarobartt/following{/other_user}', 'gists_url': 'https://api.github.com/users/alvarobartt/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/alvarobartt/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/alvarobartt/subscriptions', 'organizations_url': 'https://api.github.com/users/alvarobartt/orgs', 'repos_url': 'https://api.github.com/users/alvarobartt/repos', 'events_url': 'https://api.github.com/users/alvarobartt/events{/privacy}', 'received_events_url': 'https://api.github.com/users/alvarobartt/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-05-26T10:27:53Z', 'updated_at': '2023-05-26T10:27:53Z', 'author_association': 'CONTRIBUTOR', 'body': "@donhuvy I've created https://github.com/huggingface/datasets/pull/5902 to solve it! 🤗", 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1564176255/reactions', 'total_count': 1, '+1': 1, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}]
[{'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1561375231', 'html_url': 'https://github.com/huggingface/datasets/issues/5886#issuecomment-1561375231', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5886', 'id': 1561375231, 'node_id': 'IC_kwDODunzps5dELH_', 'user': {'login': 'lhoestq', 'id': 42851186, 'node_id': 'MDQ6VXNlcjQyODUxMTg2', 'avatar_url': 'https://avatars.githubusercontent.com/u/42851186?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/lhoestq', 'html_url': 'https://github.com/lhoestq', 'followers_url': 'https://api.github.com/users/lhoestq/followers', 'following_url': 'https://api.github.com/users/lhoestq/following{/other_user}', 'gists_url': 'https://api.github.com/users/lhoestq/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/lhoestq/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/lhoestq/subscriptions', 'organizations_url': 'https://api.github.com/users/lhoestq/orgs', 'repos_url': 'https://api.github.com/users/lhoestq/repos', 'events_url': 'https://api.github.com/users/lhoestq/events{/privacy}', 'received_events_url': 'https://api.github.com/users/lhoestq/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-05-24T15:30:09Z', 'updated_at': '2023-05-24T15:30:09Z', 'author_association': 'MEMBER', 'body': "Alternatively we could set the number of shards to be a factor than the number of processes (current they're equal) - this way it will be less likely to end up with a shard that is significantly slower than all the other ones.", 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1561375231/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}]
[{'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1558312889', 'html_url': 'https://github.com/huggingface/datasets/pull/5885#issuecomment-1558312889', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5885', 'id': 1558312889, 'node_id': 'IC_kwDODunzps5c4fe5', 'user': {'login': 'HuggingFaceDocBuilderDev', 'id': 99929124, 'node_id': 'U_kgDOBfTMJA', 'avatar_url': 'https://avatars.githubusercontent.com/u/99929124?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/HuggingFaceDocBuilderDev', 'html_url': 'https://github.com/HuggingFaceDocBuilderDev', 'followers_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/followers', 'following_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/following{/other_user}', 'gists_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/subscriptions', 'organizations_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/orgs', 'repos_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/repos', 'events_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/events{/privacy}', 'received_events_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-05-23T01:12:27Z', 'updated_at': '2023-05-23T01:12:27Z', 'author_association': 'NONE', 'body': 'The docs for this PR live [here](https://moon-ci-docs.huggingface.co/docs/datasets/pr_5885). All of your documentation changes will be reflected on that endpoint.', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1558312889/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1560242889', 'html_url': 'https://github.com/huggingface/datasets/pull/5885#issuecomment-1560242889', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5885', 'id': 1560242889, 'node_id': 'IC_kwDODunzps5c_2rJ', 'user': {'login': 'maddiedawson', 'id': 106995444, 'node_id': 'U_kgDOBmCe9A', 'avatar_url': 'https://avatars.githubusercontent.com/u/106995444?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/maddiedawson', 'html_url': 'https://github.com/maddiedawson', 'followers_url': 'https://api.github.com/users/maddiedawson/followers', 'following_url': 'https://api.github.com/users/maddiedawson/following{/other_user}', 'gists_url': 'https://api.github.com/users/maddiedawson/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/maddiedawson/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/maddiedawson/subscriptions', 'organizations_url': 'https://api.github.com/users/maddiedawson/orgs', 'repos_url': 'https://api.github.com/users/maddiedawson/repos', 'events_url': 'https://api.github.com/users/maddiedawson/events{/privacy}', 'received_events_url': 'https://api.github.com/users/maddiedawson/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-05-23T23:10:51Z', 'updated_at': '2023-05-23T23:10:51Z', 'author_association': 'CONTRIBUTOR', 'body': '@lhoestq would you or another maintainer be able to review please? :)', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1560242889/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1561308480', 'html_url': 'https://github.com/huggingface/datasets/pull/5885#issuecomment-1561308480', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5885', 'id': 1561308480, 'node_id': 'IC_kwDODunzps5dD61A', 'user': {'login': 'lhoestq', 'id': 42851186, 'node_id': 'MDQ6VXNlcjQyODUxMTg2', 'avatar_url': 'https://avatars.githubusercontent.com/u/42851186?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/lhoestq', 'html_url': 'https://github.com/lhoestq', 'followers_url': 'https://api.github.com/users/lhoestq/followers', 'following_url': 'https://api.github.com/users/lhoestq/following{/other_user}', 'gists_url': 'https://api.github.com/users/lhoestq/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/lhoestq/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/lhoestq/subscriptions', 'organizations_url': 'https://api.github.com/users/lhoestq/orgs', 'repos_url': 'https://api.github.com/users/lhoestq/repos', 'events_url': 'https://api.github.com/users/lhoestq/events{/privacy}', 'received_events_url': 'https://api.github.com/users/lhoestq/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-05-24T14:51:28Z', 'updated_at': '2023-05-24T14:51:28Z', 'author_association': 'MEMBER', 'body': "Why you do need to support FUSE mounted paths ?\r\n\r\n`datasets` uses data that live on disk for fast lookups - FUSE mounted disks would lead to poor performance and I wouldn't recomment using it.", 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1561308480/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1561863436', 'html_url': 'https://github.com/huggingface/datasets/pull/5885#issuecomment-1561863436', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5885', 'id': 1561863436, 'node_id': 'IC_kwDODunzps5dGCUM', 'user': {'login': 'maddiedawson', 'id': 106995444, 'node_id': 'U_kgDOBmCe9A', 'avatar_url': 'https://avatars.githubusercontent.com/u/106995444?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/maddiedawson', 'html_url': 'https://github.com/maddiedawson', 'followers_url': 'https://api.github.com/users/maddiedawson/followers', 'following_url': 'https://api.github.com/users/maddiedawson/following{/other_user}', 'gists_url': 'https://api.github.com/users/maddiedawson/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/maddiedawson/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/maddiedawson/subscriptions', 'organizations_url': 'https://api.github.com/users/maddiedawson/orgs', 'repos_url': 'https://api.github.com/users/maddiedawson/repos', 'events_url': 'https://api.github.com/users/maddiedawson/events{/privacy}', 'received_events_url': 'https://api.github.com/users/maddiedawson/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-05-24T20:09:23Z', 'updated_at': '2023-05-24T20:09:23Z', 'author_association': 'CONTRIBUTOR', 'body': "Fuse is commonly used to mount remote file systems (e.g. S3, DBFS) as a local directory. Since it's slower than using an actual local device, it's better to treat it as remote to reduce latency.", 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1561863436/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1562528048', 'html_url': 'https://github.com/huggingface/datasets/pull/5885#issuecomment-1562528048', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5885', 'id': 1562528048, 'node_id': 'IC_kwDODunzps5dIkkw', 'user': {'login': 'lhoestq', 'id': 42851186, 'node_id': 'MDQ6VXNlcjQyODUxMTg2', 'avatar_url': 'https://avatars.githubusercontent.com/u/42851186?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/lhoestq', 'html_url': 'https://github.com/lhoestq', 'followers_url': 'https://api.github.com/users/lhoestq/followers', 'following_url': 'https://api.github.com/users/lhoestq/following{/other_user}', 'gists_url': 'https://api.github.com/users/lhoestq/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/lhoestq/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/lhoestq/subscriptions', 'organizations_url': 'https://api.github.com/users/lhoestq/orgs', 'repos_url': 'https://api.github.com/users/lhoestq/repos', 'events_url': 'https://api.github.com/users/lhoestq/events{/privacy}', 'received_events_url': 'https://api.github.com/users/lhoestq/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-05-25T08:50:48Z', 'updated_at': '2023-05-25T08:50:48Z', 'author_association': 'MEMBER', 'body': "I think people would be confused if they don't have the same dataset behavior depending on the disk type.\r\n\r\nIf they want to use a remote bucket they should use the remote URI instead, e.g. `s3://...`. Advancements on this are tracked at #5281 ", 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1562528048/reactions', 'total_count': 1, '+1': 1, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}]

[{'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1559646838', 'html_url': 'https://github.com/huggingface/datasets/issues/5888#issuecomment-1559646838', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5888', 'id': 1559646838, 'node_id': 'IC_kwDODunzps5c9lJ2', 'user': {'login': 'mariosasko', 'id': 47462742, 'node_id': 'MDQ6VXNlcjQ3NDYyNzQy', 'avatar_url': 'https://avatars.githubusercontent.com/u/47462742?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/mariosasko', 'html_url': 'https://github.com/mariosasko', 'followers_url': 'https://api.github.com/users/mariosasko/followers', 'following_url': 'https://api.github.com/users/mariosasko/following{/other_user}', 'gists_url': 'https://api.github.com/users/mariosasko/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/mariosasko/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/mariosasko/subscriptions', 'organizations_url': 'https://api.github.com/users/mariosasko/orgs', 'repos_url': 'https://api.github.com/users/mariosasko/repos', 'events_url': 'https://api.github.com/users/mariosasko/events{/privacy}', 'received_events_url': 'https://api.github.com/users/mariosasko/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-05-22T19:28:46Z', 'updated_at': '2023-05-22T19:28:46Z', 'author_association': 'CONTRIBUTOR', 'body': 'Hi! \r\n\r\nYou want to use `push_to_hub` (creates Parquet files) instead of `save_to_disk` (creates Arrow files) when creating a Hub dataset. Parquet is designed for long-term storage and takes less space than the Arrow format, and, most importantly, `load_dataset` can parse it, which should fix the viewer. \r\n\r\nRegarding the dataset generation, `Dataset.from_generator` with the video data represented as `datasets.Value("binary")` followed by `push_to_hub` should work (if the `push_to_hub` step times out, restart it to resume uploading)\r\n\r\nPS: Once the dataset is uploaded, to make working with the dataset easier, it\'s a good idea to add a [transform](https://huggingface.co/docs/datasets/main/en/process#format-transform) to the README that shows how to decode the binary video data into something a model can understand. Also, if you get an `ArrowInvalid` error (can happen when working with large binary data) in `Dataset.from_generator`, reduce the value of `writer_batch_size` (the default is 1000) to fix it.', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1559646838/reactions', 'total_count': 2, '+1': 2, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1559646852', 'html_url': 'https://github.com/huggingface/datasets/issues/5888#issuecomment-1559646852', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5888', 'id': 1559646852, 'node_id': 'IC_kwDODunzps5c9lKE', 'user': {'login': 'AntreasAntoniou', 'id': 10792502, 'node_id': 'MDQ6VXNlcjEwNzkyNTAy', 'avatar_url': 'https://avatars.githubusercontent.com/u/10792502?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/AntreasAntoniou', 'html_url': 'https://github.com/AntreasAntoniou', 'followers_url': 'https://api.github.com/users/AntreasAntoniou/followers', 'following_url': 'https://api.github.com/users/AntreasAntoniou/following{/other_user}', 'gists_url': 'https://api.github.com/users/AntreasAntoniou/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/AntreasAntoniou/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/AntreasAntoniou/subscriptions', 'organizations_url': 'https://api.github.com/users/AntreasAntoniou/orgs', 'repos_url': 'https://api.github.com/users/AntreasAntoniou/repos', 'events_url': 'https://api.github.com/users/AntreasAntoniou/events{/privacy}', 'received_events_url': 'https://api.github.com/users/AntreasAntoniou/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-05-22T23:19:13Z', 'updated_at': '2023-05-22T23:19:13Z', 'author_association': 'NONE', 'body': "One issue here is that Dataset.from_generator can work well for the non 'infinite sampling' version of the dataset. The training set for example is often sampled dynamically given the video files that I have uploaded. I worry that storing the video data as binary means that I'll end up duplicating a lot of the data. Furthermore, storing video data as anything but .mp4 would quickly make the dataset size from 1.9TB to 1PB. ", 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1559646852/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1559646858', 'html_url': 'https://github.com/huggingface/datasets/issues/5888#issuecomment-1559646858', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5888', 'id': 1559646858, 'node_id': 'IC_kwDODunzps5c9lKK', 'user': {'login': 'mariosasko', 'id': 47462742, 'node_id': 'MDQ6VXNlcjQ3NDYyNzQy', 'avatar_url': 'https://avatars.githubusercontent.com/u/47462742?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/mariosasko', 'html_url': 'https://github.com/mariosasko', 'followers_url': 'https://api.github.com/users/mariosasko/followers', 'following_url': 'https://api.github.com/users/mariosasko/following{/other_user}', 'gists_url': 'https://api.github.com/users/mariosasko/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/mariosasko/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/mariosasko/subscriptions', 'organizations_url': 'https://api.github.com/users/mariosasko/orgs', 'repos_url': 'https://api.github.com/users/mariosasko/repos', 'events_url': 'https://api.github.com/users/mariosasko/events{/privacy}', 'received_events_url': 'https://api.github.com/users/mariosasko/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-05-23T15:13:42Z', 'updated_at': '2023-05-23T15:13:42Z', 'author_association': 'CONTRIBUTOR', 'body': '> storing video data as anything but .mp4\r\n\r\nWhat I mean by storing as `datasets.Value("binary")` is embedding raw MP4 bytes in the Arrow table, but, indeed, this would waste a lot of space if there are duplicates.\r\n\r\nSo I see two options:\r\n* if one video is not mapped to too many samples, you can embed the video bytes and do "group by" on the rest of the columns (this would turn them into lists) to avoid duplicating them (then, it should be easy to define a `map` in the README that samples the video data to "unpack" the samples)\r\n* you can create a dataset script that downloads the video files and embeds their file paths into the Arrow file\r\n\r\nAlso, I misread MP4 as MP3. We need to add a `Video` feature to the `datasets` lib to support MP4 files in the viewer (a bit trickier to implement than the `Image` feature due to the Arrow limitations).', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1559646858/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1559646864', 'html_url': 'https://github.com/huggingface/datasets/issues/5888#issuecomment-1559646864', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5888', 'id': 1559646864, 'node_id': 'IC_kwDODunzps5c9lKQ', 'user': {'login': 'mariosasko', 'id': 47462742, 'node_id': 'MDQ6VXNlcjQ3NDYyNzQy', 'avatar_url': 'https://avatars.githubusercontent.com/u/47462742?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/mariosasko', 'html_url': 'https://github.com/mariosasko', 'followers_url': 'https://api.github.com/users/mariosasko/followers', 'following_url': 'https://api.github.com/users/mariosasko/following{/other_user}', 'gists_url': 'https://api.github.com/users/mariosasko/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/mariosasko/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/mariosasko/subscriptions', 'organizations_url': 'https://api.github.com/users/mariosasko/orgs', 'repos_url': 'https://api.github.com/users/mariosasko/repos', 'events_url': 'https://api.github.com/users/mariosasko/events{/privacy}', 'received_events_url': 'https://api.github.com/users/mariosasko/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-05-23T15:15:04Z', 'updated_at': '2023-05-23T15:15:04Z', 'author_association': 'CONTRIBUTOR', 'body': "I'm transferring this issue to the `datasets` repo, as it's not related to `huggingface_hub`", 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1559646864/reactions', 'total_count': 2, '+1': 2, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1560279241', 'html_url': 'https://github.com/huggingface/datasets/issues/5888#issuecomment-1560279241', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5888', 'id': 1560279241, 'node_id': 'IC_kwDODunzps5c__jJ', 'user': {'login': 'AntreasAntoniou', 'id': 10792502, 'node_id': 'MDQ6VXNlcjEwNzkyNTAy', 'avatar_url': 'https://avatars.githubusercontent.com/u/10792502?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/AntreasAntoniou', 'html_url': 'https://github.com/AntreasAntoniou', 'followers_url': 'https://api.github.com/users/AntreasAntoniou/followers', 'following_url': 'https://api.github.com/users/AntreasAntoniou/following{/other_user}', 'gists_url': 'https://api.github.com/users/AntreasAntoniou/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/AntreasAntoniou/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/AntreasAntoniou/subscriptions', 'organizations_url': 'https://api.github.com/users/AntreasAntoniou/orgs', 'repos_url': 'https://api.github.com/users/AntreasAntoniou/repos', 'events_url': 'https://api.github.com/users/AntreasAntoniou/events{/privacy}', 'received_events_url': 'https://api.github.com/users/AntreasAntoniou/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-05-24T00:10:41Z', 'updated_at': '2023-05-24T00:10:41Z', 'author_association': 'NONE', 'body': '@mariosasko Right. If I want my dataset to be streamable, what are the necessary requirements to achieve that within the context of .mp4 binaries like we have here? I guess your second point here would not support that right?', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1560279241/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1561131232', 'html_url': 'https://github.com/huggingface/datasets/issues/5888#issuecomment-1561131232', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5888', 'id': 1561131232, 'node_id': 'IC_kwDODunzps5dDPjg', 'user': {'login': 'mariosasko', 'id': 47462742, 'node_id': 'MDQ6VXNlcjQ3NDYyNzQy', 'avatar_url': 'https://avatars.githubusercontent.com/u/47462742?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/mariosasko', 'html_url': 'https://github.com/mariosasko', 'followers_url': 'https://api.github.com/users/mariosasko/followers', 'following_url': 'https://api.github.com/users/mariosasko/following{/other_user}', 'gists_url': 'https://api.github.com/users/mariosasko/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/mariosasko/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/mariosasko/subscriptions', 'organizations_url': 'https://api.github.com/users/mariosasko/orgs', 'repos_url': 'https://api.github.com/users/mariosasko/repos', 'events_url': 'https://api.github.com/users/mariosasko/events{/privacy}', 'received_events_url': 'https://api.github.com/users/mariosasko/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-05-24T13:17:10Z', 'updated_at': '2023-05-24T13:17:10Z', 'author_association': 'CONTRIBUTOR', 'body': 'The streaming would work, but the video paths would require using `fsspec.open` to get the content.', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1561131232/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1566272592', 'html_url': 'https://github.com/huggingface/datasets/issues/5888#issuecomment-1566272592', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5888', 'id': 1566272592, 'node_id': 'IC_kwDODunzps5dW2xQ', 'user': {'login': 'AntreasAntoniou', 'id': 10792502, 'node_id': 'MDQ6VXNlcjEwNzkyNTAy', 'avatar_url': 'https://avatars.githubusercontent.com/u/10792502?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/AntreasAntoniou', 'html_url': 'https://github.com/AntreasAntoniou', 'followers_url': 'https://api.github.com/users/AntreasAntoniou/followers', 'following_url': 'https://api.github.com/users/AntreasAntoniou/following{/other_user}', 'gists_url': 'https://api.github.com/users/AntreasAntoniou/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/AntreasAntoniou/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/AntreasAntoniou/subscriptions', 'organizations_url': 'https://api.github.com/users/AntreasAntoniou/orgs', 'repos_url': 'https://api.github.com/users/AntreasAntoniou/repos', 'events_url': 'https://api.github.com/users/AntreasAntoniou/events{/privacy}', 'received_events_url': 'https://api.github.com/users/AntreasAntoniou/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-05-28T21:37:45Z', 'updated_at': '2023-05-28T21:37:45Z', 'author_association': 'NONE', 'body': 'Are there any plans to make video playable on the hub?', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1566272592/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1594994055', 'html_url': 'https://github.com/huggingface/datasets/issues/5888#issuecomment-1594994055', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5888', 'id': 1594994055, 'node_id': 'IC_kwDODunzps5fEa2H', 'user': {'login': 'mariosasko', 'id': 47462742, 'node_id': 'MDQ6VXNlcjQ3NDYyNzQy', 'avatar_url': 'https://avatars.githubusercontent.com/u/47462742?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/mariosasko', 'html_url': 'https://github.com/mariosasko', 'followers_url': 'https://api.github.com/users/mariosasko/followers', 'following_url': 'https://api.github.com/users/mariosasko/following{/other_user}', 'gists_url': 'https://api.github.com/users/mariosasko/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/mariosasko/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/mariosasko/subscriptions', 'organizations_url': 'https://api.github.com/users/mariosasko/orgs', 'repos_url': 'https://api.github.com/users/mariosasko/repos', 'events_url': 'https://api.github.com/users/mariosasko/events{/privacy}', 'received_events_url': 'https://api.github.com/users/mariosasko/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-16T17:07:17Z', 'updated_at': '2023-06-16T17:07:17Z', 'author_association': 'CONTRIBUTOR', 'body': 'Not yet. The (open source) tooling for video is not great in terms of ease of use/performance, so we are discussing internally the best way to support it (one option is creating a new library for video IO, but this will require a lot of work)', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1594994055/reactions', 'total_count': 1, '+1': 1, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1603638730', 'html_url': 'https://github.com/huggingface/datasets/issues/5888#issuecomment-1603638730', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5888', 'id': 1603638730, 'node_id': 'IC_kwDODunzps5flZXK', 'user': {'login': 'AntreasAntoniou', 'id': 10792502, 'node_id': 'MDQ6VXNlcjEwNzkyNTAy', 'avatar_url': 'https://avatars.githubusercontent.com/u/10792502?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/AntreasAntoniou', 'html_url': 'https://github.com/AntreasAntoniou', 'followers_url': 'https://api.github.com/users/AntreasAntoniou/followers', 'following_url': 'https://api.github.com/users/AntreasAntoniou/following{/other_user}', 'gists_url': 'https://api.github.com/users/AntreasAntoniou/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/AntreasAntoniou/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/AntreasAntoniou/subscriptions', 'organizations_url': 'https://api.github.com/users/AntreasAntoniou/orgs', 'repos_url': 'https://api.github.com/users/AntreasAntoniou/repos', 'events_url': 'https://api.github.com/users/AntreasAntoniou/events{/privacy}', 'received_events_url': 'https://api.github.com/users/AntreasAntoniou/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-23T03:37:15Z', 'updated_at': '2023-06-23T03:37:15Z', 'author_association': 'NONE', 'body': "True. I spend a good 4 months just mixing and matching existing solutions so I could get performance that would not IO bound my model training. \r\n\r\nThis is what I ended up with, in case it's useful\r\n\r\nhttps://github.com/AntreasAntoniou/TALI/blob/045cf9e5aa75b1bf2c6d5351fb910fa10e3ff32c/tali/data/data_plus.py#L85", 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1603638730/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}]

[{'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1557097768', 'html_url': 'https://github.com/huggingface/datasets/issues/5884#issuecomment-1557097768', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5884', 'id': 1557097768, 'node_id': 'IC_kwDODunzps5cz20o', 'user': {'login': 'alvarobartt', 'id': 36760800, 'node_id': 'MDQ6VXNlcjM2NzYwODAw', 'avatar_url': 'https://avatars.githubusercontent.com/u/36760800?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/alvarobartt', 'html_url': 'https://github.com/alvarobartt', 'followers_url': 'https://api.github.com/users/alvarobartt/followers', 'following_url': 'https://api.github.com/users/alvarobartt/following{/other_user}', 'gists_url': 'https://api.github.com/users/alvarobartt/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/alvarobartt/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/alvarobartt/subscriptions', 'organizations_url': 'https://api.github.com/users/alvarobartt/orgs', 'repos_url': 'https://api.github.com/users/alvarobartt/repos', 'events_url': 'https://api.github.com/users/alvarobartt/events{/privacy}', 'received_events_url': 'https://api.github.com/users/alvarobartt/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-05-22T12:03:22Z', 'updated_at': '2023-05-22T12:09:40Z', 'author_association': 'CONTRIBUTOR', 'body': 'May eventually be solved in #5883 ', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1557097768/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1557108106', 'html_url': 'https://github.com/huggingface/datasets/issues/5884#issuecomment-1557108106', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5884', 'id': 1557108106, 'node_id': 'IC_kwDODunzps5cz5WK', 'user': {'login': 'alvarobartt', 'id': 36760800, 'node_id': 'MDQ6VXNlcjM2NzYwODAw', 'avatar_url': 'https://avatars.githubusercontent.com/u/36760800?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/alvarobartt', 'html_url': 'https://github.com/alvarobartt', 'followers_url': 'https://api.github.com/users/alvarobartt/followers', 'following_url': 'https://api.github.com/users/alvarobartt/following{/other_user}', 'gists_url': 'https://api.github.com/users/alvarobartt/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/alvarobartt/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/alvarobartt/subscriptions', 'organizations_url': 'https://api.github.com/users/alvarobartt/orgs', 'repos_url': 'https://api.github.com/users/alvarobartt/repos', 'events_url': 'https://api.github.com/users/alvarobartt/events{/privacy}', 'received_events_url': 'https://api.github.com/users/alvarobartt/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-05-22T12:09:44Z', 'updated_at': '2023-05-22T12:09:44Z', 'author_association': 'CONTRIBUTOR', 'body': '#self-assign', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1557108106/reactions', 'total_count': 1, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 1, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}]

[{'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1556979969', 'html_url': 'https://github.com/huggingface/datasets/issues/5881#issuecomment-1556979969', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5881', 'id': 1556979969, 'node_id': 'IC_kwDODunzps5czaEB', 'user': {'login': 'sanchit-gandhi', 'id': 93869735, 'node_id': 'U_kgDOBZhWpw', 'avatar_url': 'https://avatars.githubusercontent.com/u/93869735?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/sanchit-gandhi', 'html_url': 'https://github.com/sanchit-gandhi', 'followers_url': 'https://api.github.com/users/sanchit-gandhi/followers', 'following_url': 'https://api.github.com/users/sanchit-gandhi/following{/other_user}', 'gists_url': 'https://api.github.com/users/sanchit-gandhi/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/sanchit-gandhi/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/sanchit-gandhi/subscriptions', 'organizations_url': 'https://api.github.com/users/sanchit-gandhi/orgs', 'repos_url': 'https://api.github.com/users/sanchit-gandhi/repos', 'events_url': 'https://api.github.com/users/sanchit-gandhi/events{/privacy}', 'received_events_url': 'https://api.github.com/users/sanchit-gandhi/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-05-22T10:36:59Z', 'updated_at': '2023-05-22T10:50:24Z', 'author_association': 'CONTRIBUTOR', 'body': 'cc @lhoestq in case you have any ideas here! Might need a multi-host set-up to debug (can give you access to a JAX one if you need)', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1556979969/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}]
[{'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1561378427', 'html_url': 'https://github.com/huggingface/datasets/issues/5880#issuecomment-1561378427', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5880', 'id': 1561378427, 'node_id': 'IC_kwDODunzps5dEL57', 'user': {'login': 'lhoestq', 'id': 42851186, 'node_id': 'MDQ6VXNlcjQyODUxMTg2', 'avatar_url': 'https://avatars.githubusercontent.com/u/42851186?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/lhoestq', 'html_url': 'https://github.com/lhoestq', 'followers_url': 'https://api.github.com/users/lhoestq/followers', 'following_url': 'https://api.github.com/users/lhoestq/following{/other_user}', 'gists_url': 'https://api.github.com/users/lhoestq/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/lhoestq/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/lhoestq/subscriptions', 'organizations_url': 'https://api.github.com/users/lhoestq/orgs', 'repos_url': 'https://api.github.com/users/lhoestq/repos', 'events_url': 'https://api.github.com/users/lhoestq/events{/privacy}', 'received_events_url': 'https://api.github.com/users/lhoestq/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-05-24T15:32:12Z', 'updated_at': '2023-05-24T15:32:12Z', 'author_association': 'MEMBER', 'body': 'This sounds related to #5281.\r\n\r\nCan you try passing `storage_options=s3_client.storage_options` instead passing it to `use_auth_token=` ?', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1561378427/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1563858670', 'html_url': 'https://github.com/huggingface/datasets/issues/5880#issuecomment-1563858670', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5880', 'id': 1563858670, 'node_id': 'IC_kwDODunzps5dNpbu', 'user': {'login': 'janineguo', 'id': 59083384, 'node_id': 'MDQ6VXNlcjU5MDgzMzg0', 'avatar_url': 'https://avatars.githubusercontent.com/u/59083384?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/janineguo', 'html_url': 'https://github.com/janineguo', 'followers_url': 'https://api.github.com/users/janineguo/followers', 'following_url': 'https://api.github.com/users/janineguo/following{/other_user}', 'gists_url': 'https://api.github.com/users/janineguo/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/janineguo/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/janineguo/subscriptions', 'organizations_url': 'https://api.github.com/users/janineguo/orgs', 'repos_url': 'https://api.github.com/users/janineguo/repos', 'events_url': 'https://api.github.com/users/janineguo/events{/privacy}', 'received_events_url': 'https://api.github.com/users/janineguo/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-05-26T06:12:03Z', 'updated_at': '2023-05-26T06:12:03Z', 'author_association': 'NONE', 'body': 'I tried `storage_options` before, but it doesn\'t work, I checked our source code and I found that we even didn\'t pass this parameter to the following process. if I use `storage_options` instead of `use_auth_token`, then I also need to change another place of the code. the last line of `streaming_download_manager.py`. our code only passes the `use_auth_token` to the following handler, but does nothing to the `storage_options`\r\n<img width="1050" alt="image" src="https://github.com/huggingface/datasets/assets/59083384/5be90933-3331-4ecf-9e11-34f9852d8f92">\r\n', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1563858670/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1564182674', 'html_url': 'https://github.com/huggingface/datasets/issues/5880#issuecomment-1564182674', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5880', 'id': 1564182674, 'node_id': 'IC_kwDODunzps5dO4iS', 'user': {'login': 'lhoestq', 'id': 42851186, 'node_id': 'MDQ6VXNlcjQyODUxMTg2', 'avatar_url': 'https://avatars.githubusercontent.com/u/42851186?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/lhoestq', 'html_url': 'https://github.com/lhoestq', 'followers_url': 'https://api.github.com/users/lhoestq/followers', 'following_url': 'https://api.github.com/users/lhoestq/following{/other_user}', 'gists_url': 'https://api.github.com/users/lhoestq/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/lhoestq/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/lhoestq/subscriptions', 'organizations_url': 'https://api.github.com/users/lhoestq/orgs', 'repos_url': 'https://api.github.com/users/lhoestq/repos', 'events_url': 'https://api.github.com/users/lhoestq/events{/privacy}', 'received_events_url': 'https://api.github.com/users/lhoestq/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-05-26T10:33:35Z', 'updated_at': '2023-05-26T10:33:35Z', 'author_association': 'MEMBER', 'body': "Cloud storage support is still experimental indeed and you can expect some bugs.\r\n\r\nI think we need to pass the storage options anywhere use_auth_token is passed in indeed. Let me know if you'd be interested in contributing a fix !", 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1564182674/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1564348427', 'html_url': 'https://github.com/huggingface/datasets/issues/5880#issuecomment-1564348427', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5880', 'id': 1564348427, 'node_id': 'IC_kwDODunzps5dPhAL', 'user': {'login': 'janineguo', 'id': 59083384, 'node_id': 'MDQ6VXNlcjU5MDgzMzg0', 'avatar_url': 'https://avatars.githubusercontent.com/u/59083384?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/janineguo', 'html_url': 'https://github.com/janineguo', 'followers_url': 'https://api.github.com/users/janineguo/followers', 'following_url': 'https://api.github.com/users/janineguo/following{/other_user}', 'gists_url': 'https://api.github.com/users/janineguo/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/janineguo/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/janineguo/subscriptions', 'organizations_url': 'https://api.github.com/users/janineguo/orgs', 'repos_url': 'https://api.github.com/users/janineguo/repos', 'events_url': 'https://api.github.com/users/janineguo/events{/privacy}', 'received_events_url': 'https://api.github.com/users/janineguo/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-05-26T12:52:07Z', 'updated_at': '2023-05-26T12:52:07Z', 'author_association': 'NONE', 'body': "Oh, that's great, I really like to fix it. because datasets is really useful and most of our projects need to use it, but we can store our data on the internet due to security reasons. fix it not only make our own work more efficient but also can benefit others who use it.", 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1564348427/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}]

[{'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1557452172', 'html_url': 'https://github.com/huggingface/datasets/issues/5878#issuecomment-1557452172', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5878', 'id': 1557452172, 'node_id': 'IC_kwDODunzps5c1NWM', 'user': {'login': 'sanchit-gandhi', 'id': 93869735, 'node_id': 'U_kgDOBZhWpw', 'avatar_url': 'https://avatars.githubusercontent.com/u/93869735?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/sanchit-gandhi', 'html_url': 'https://github.com/sanchit-gandhi', 'followers_url': 'https://api.github.com/users/sanchit-gandhi/followers', 'following_url': 'https://api.github.com/users/sanchit-gandhi/following{/other_user}', 'gists_url': 'https://api.github.com/users/sanchit-gandhi/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/sanchit-gandhi/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/sanchit-gandhi/subscriptions', 'organizations_url': 'https://api.github.com/users/sanchit-gandhi/orgs', 'repos_url': 'https://api.github.com/users/sanchit-gandhi/repos', 'events_url': 'https://api.github.com/users/sanchit-gandhi/events{/privacy}', 'received_events_url': 'https://api.github.com/users/sanchit-gandhi/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-05-22T15:41:27Z', 'updated_at': '2023-05-22T15:41:27Z', 'author_association': 'CONTRIBUTOR', 'body': "Very cool! Do you have a link to the code that you're using to eagerly fetch the data? Would also be interested in hacking around something here for pre-fetching iterable datasets", 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1557452172/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1557565926', 'html_url': 'https://github.com/huggingface/datasets/issues/5878#issuecomment-1557565926', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5878', 'id': 1557565926, 'node_id': 'IC_kwDODunzps5c1pHm', 'user': {'login': 'vyeevani', 'id': 30946190, 'node_id': 'MDQ6VXNlcjMwOTQ2MTkw', 'avatar_url': 'https://avatars.githubusercontent.com/u/30946190?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/vyeevani', 'html_url': 'https://github.com/vyeevani', 'followers_url': 'https://api.github.com/users/vyeevani/followers', 'following_url': 'https://api.github.com/users/vyeevani/following{/other_user}', 'gists_url': 'https://api.github.com/users/vyeevani/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/vyeevani/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/vyeevani/subscriptions', 'organizations_url': 'https://api.github.com/users/vyeevani/orgs', 'repos_url': 'https://api.github.com/users/vyeevani/repos', 'events_url': 'https://api.github.com/users/vyeevani/events{/privacy}', 'received_events_url': 'https://api.github.com/users/vyeevani/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-05-22T16:50:32Z', 'updated_at': '2023-05-22T16:50:32Z', 'author_association': 'NONE', 'body': "I ended up just switching back to the pytorch dataloader and using it's multiprocessing functionality to handle this :(. I'm just not that familiar with python multiprocessing to get something to work in jupyter (kept having weird behaviors happening with zombies living after the cell finished).", 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1557565926/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1557703340', 'html_url': 'https://github.com/huggingface/datasets/issues/5878#issuecomment-1557703340', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5878', 'id': 1557703340, 'node_id': 'IC_kwDODunzps5c2Kqs', 'user': {'login': 'vyeevani', 'id': 30946190, 'node_id': 'MDQ6VXNlcjMwOTQ2MTkw', 'avatar_url': 'https://avatars.githubusercontent.com/u/30946190?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/vyeevani', 'html_url': 'https://github.com/vyeevani', 'followers_url': 'https://api.github.com/users/vyeevani/followers', 'following_url': 'https://api.github.com/users/vyeevani/following{/other_user}', 'gists_url': 'https://api.github.com/users/vyeevani/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/vyeevani/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/vyeevani/subscriptions', 'organizations_url': 'https://api.github.com/users/vyeevani/orgs', 'repos_url': 'https://api.github.com/users/vyeevani/repos', 'events_url': 'https://api.github.com/users/vyeevani/events{/privacy}', 'received_events_url': 'https://api.github.com/users/vyeevani/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-05-22T18:31:28Z', 'updated_at': '2023-05-22T18:31:28Z', 'author_association': 'NONE', 'body': 'Ultimately settled on using webdataset to circumvent huggingface datasets entirely. Would definitely switch back if: https://github.com/huggingface/datasets/issues/5337 was resolved.', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1557703340/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1559809907', 'html_url': 'https://github.com/huggingface/datasets/issues/5878#issuecomment-1559809907', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5878', 'id': 1559809907, 'node_id': 'IC_kwDODunzps5c-M9z', 'user': {'login': 'mariosasko', 'id': 47462742, 'node_id': 'MDQ6VXNlcjQ3NDYyNzQy', 'avatar_url': 'https://avatars.githubusercontent.com/u/47462742?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/mariosasko', 'html_url': 'https://github.com/mariosasko', 'followers_url': 'https://api.github.com/users/mariosasko/followers', 'following_url': 'https://api.github.com/users/mariosasko/following{/other_user}', 'gists_url': 'https://api.github.com/users/mariosasko/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/mariosasko/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/mariosasko/subscriptions', 'organizations_url': 'https://api.github.com/users/mariosasko/orgs', 'repos_url': 'https://api.github.com/users/mariosasko/repos', 'events_url': 'https://api.github.com/users/mariosasko/events{/privacy}', 'received_events_url': 'https://api.github.com/users/mariosasko/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-05-23T16:45:55Z', 'updated_at': '2023-05-23T16:45:55Z', 'author_association': 'CONTRIBUTOR', 'body': 'Hi! You can combine `datasets` with `torchdata` to prefetch `IterableDataset`\'s samples:\r\n```python\r\nfrom datasets import load_dataset\r\nfrom torchdata.datapipes.iter import IterableWrapper, HuggingFaceHubReader\r\nfrom torch.utils.data import DataLoader\r\n\r\nds = load_dataset("sst", split="train", streaming=True)\r\n# processing...\r\ndp = IterableWrapper(ds)\r\ndp = dp.prefetch(100)\r\ndl = DataLoader(dp, batch_size=8)\r\n\r\ni = iter(dl)\r\nnext(i)\r\n```', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1559809907/reactions', 'total_count': 1, '+1': 1, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1572514927', 'html_url': 'https://github.com/huggingface/datasets/issues/5878#issuecomment-1572514927', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5878', 'id': 1572514927, 'node_id': 'IC_kwDODunzps5duqxv', 'user': {'login': 'sanchit-gandhi', 'id': 93869735, 'node_id': 'U_kgDOBZhWpw', 'avatar_url': 'https://avatars.githubusercontent.com/u/93869735?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/sanchit-gandhi', 'html_url': 'https://github.com/sanchit-gandhi', 'followers_url': 'https://api.github.com/users/sanchit-gandhi/followers', 'following_url': 'https://api.github.com/users/sanchit-gandhi/following{/other_user}', 'gists_url': 'https://api.github.com/users/sanchit-gandhi/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/sanchit-gandhi/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/sanchit-gandhi/subscriptions', 'organizations_url': 'https://api.github.com/users/sanchit-gandhi/orgs', 'repos_url': 'https://api.github.com/users/sanchit-gandhi/repos', 'events_url': 'https://api.github.com/users/sanchit-gandhi/events{/privacy}', 'received_events_url': 'https://api.github.com/users/sanchit-gandhi/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-01T17:40:00Z', 'updated_at': '2023-06-01T17:40:00Z', 'author_association': 'CONTRIBUTOR', 'body': "Hey @mariosasko! Thanks for the tip here - introducing prefetch with `torchdata` didn't really give me any performance difference vs not prefetching, but the concept is definitely one that could be really beneficial. Are there any benchmarks that show the speed-up you can get with `torchdata`'s prefetch just for comparison?", 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1572514927/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}]

[{'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1570335978', 'html_url': 'https://github.com/huggingface/datasets/issues/5877#issuecomment-1570335978', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5877', 'id': 1570335978, 'node_id': 'IC_kwDODunzps5dmWzq', 'user': {'login': 'mariosasko', 'id': 47462742, 'node_id': 'MDQ6VXNlcjQ3NDYyNzQy', 'avatar_url': 'https://avatars.githubusercontent.com/u/47462742?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/mariosasko', 'html_url': 'https://github.com/mariosasko', 'followers_url': 'https://api.github.com/users/mariosasko/followers', 'following_url': 'https://api.github.com/users/mariosasko/following{/other_user}', 'gists_url': 'https://api.github.com/users/mariosasko/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/mariosasko/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/mariosasko/subscriptions', 'organizations_url': 'https://api.github.com/users/mariosasko/orgs', 'repos_url': 'https://api.github.com/users/mariosasko/repos', 'events_url': 'https://api.github.com/users/mariosasko/events{/privacy}', 'received_events_url': 'https://api.github.com/users/mariosasko/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-05-31T14:21:18Z', 'updated_at': '2023-05-31T14:21:18Z', 'author_association': 'CONTRIBUTOR', 'body': 'The "exact match" deduplication will be possible when we resolve https://github.com/huggingface/datasets/issues/2514 (first, https://github.com/apache/arrow/issues/30950 needs to be addressed on the Arrow side). In the meantime, you can use Polars or DuckDB (e.g., via [datasets-sql](https://github.com/mariosasko/datasets_sql)).\r\n\r\nFuzzy deduplication is out-of-scope for now ([splink](https://github.com/moj-analytical-services/splink) is probably the best tool for it).', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1570335978/reactions', 'total_count': 1, '+1': 1, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1572731181', 'html_url': 'https://github.com/huggingface/datasets/issues/5877#issuecomment-1572731181', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5877', 'id': 1572731181, 'node_id': 'IC_kwDODunzps5dvfkt', 'user': {'login': 'MaveriQ', 'id': 1519077, 'node_id': 'MDQ6VXNlcjE1MTkwNzc=', 'avatar_url': 'https://avatars.githubusercontent.com/u/1519077?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/MaveriQ', 'html_url': 'https://github.com/MaveriQ', 'followers_url': 'https://api.github.com/users/MaveriQ/followers', 'following_url': 'https://api.github.com/users/MaveriQ/following{/other_user}', 'gists_url': 'https://api.github.com/users/MaveriQ/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/MaveriQ/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/MaveriQ/subscriptions', 'organizations_url': 'https://api.github.com/users/MaveriQ/orgs', 'repos_url': 'https://api.github.com/users/MaveriQ/repos', 'events_url': 'https://api.github.com/users/MaveriQ/events{/privacy}', 'received_events_url': 'https://api.github.com/users/MaveriQ/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-01T20:26:18Z', 'updated_at': '2023-06-01T20:26:18Z', 'author_association': 'NONE', 'body': 'This library can be an intermediate solution : https://github.com/ChenghaoMou/text-dedup/tree/main', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1572731181/reactions', 'total_count': 1, '+1': 1, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}]
[{'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1559775445', 'html_url': 'https://github.com/huggingface/datasets/issues/5876#issuecomment-1559775445', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5876', 'id': 1559775445, 'node_id': 'IC_kwDODunzps5c-EjV', 'user': {'login': 'mariosasko', 'id': 47462742, 'node_id': 'MDQ6VXNlcjQ3NDYyNzQy', 'avatar_url': 'https://avatars.githubusercontent.com/u/47462742?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/mariosasko', 'html_url': 'https://github.com/mariosasko', 'followers_url': 'https://api.github.com/users/mariosasko/followers', 'following_url': 'https://api.github.com/users/mariosasko/following{/other_user}', 'gists_url': 'https://api.github.com/users/mariosasko/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/mariosasko/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/mariosasko/subscriptions', 'organizations_url': 'https://api.github.com/users/mariosasko/orgs', 'repos_url': 'https://api.github.com/users/mariosasko/repos', 'events_url': 'https://api.github.com/users/mariosasko/events{/privacy}', 'received_events_url': 'https://api.github.com/users/mariosasko/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-05-23T16:21:36Z', 'updated_at': '2023-05-23T16:21:36Z', 'author_association': 'CONTRIBUTOR', 'body': 'Indeed, `clobber=True` (with a warning if the existing protocol will be overwritten) should fix the issue, but maybe a better solution is to register our compression filesystem before the script is executed and unregister them afterward. WDYT @lhoestq @albertvillanova?', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1559775445/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1561335635', 'html_url': 'https://github.com/huggingface/datasets/issues/5876#issuecomment-1561335635', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5876', 'id': 1561335635, 'node_id': 'IC_kwDODunzps5dEBdT', 'user': {'login': 'lhoestq', 'id': 42851186, 'node_id': 'MDQ6VXNlcjQyODUxMTg2', 'avatar_url': 'https://avatars.githubusercontent.com/u/42851186?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/lhoestq', 'html_url': 'https://github.com/lhoestq', 'followers_url': 'https://api.github.com/users/lhoestq/followers', 'following_url': 'https://api.github.com/users/lhoestq/following{/other_user}', 'gists_url': 'https://api.github.com/users/lhoestq/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/lhoestq/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/lhoestq/subscriptions', 'organizations_url': 'https://api.github.com/users/lhoestq/orgs', 'repos_url': 'https://api.github.com/users/lhoestq/repos', 'events_url': 'https://api.github.com/users/lhoestq/events{/privacy}', 'received_events_url': 'https://api.github.com/users/lhoestq/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-05-24T15:06:18Z', 'updated_at': '2023-05-24T15:06:18Z', 'author_association': 'MEMBER', 'body': "I think we should use clobber and show a warning if it overwrote a registered filesystem indeed ! This way the user can re-register the filesystems if needed. Though they should probably be compatible (and maybe do the exact same thing) so I wouldn't de-register the `datasets` filesystems", 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1561335635/reactions', 'total_count': 2, '+1': 2, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}]
[{'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1559735753', 'html_url': 'https://github.com/huggingface/datasets/issues/5875#issuecomment-1559735753', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5875', 'id': 1559735753, 'node_id': 'IC_kwDODunzps5c963J', 'user': {'login': 'mariosasko', 'id': 47462742, 'node_id': 'MDQ6VXNlcjQ3NDYyNzQy', 'avatar_url': 'https://avatars.githubusercontent.com/u/47462742?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/mariosasko', 'html_url': 'https://github.com/mariosasko', 'followers_url': 'https://api.github.com/users/mariosasko/followers', 'following_url': 'https://api.github.com/users/mariosasko/following{/other_user}', 'gists_url': 'https://api.github.com/users/mariosasko/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/mariosasko/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/mariosasko/subscriptions', 'organizations_url': 'https://api.github.com/users/mariosasko/orgs', 'repos_url': 'https://api.github.com/users/mariosasko/repos', 'events_url': 'https://api.github.com/users/mariosasko/events{/privacy}', 'received_events_url': 'https://api.github.com/users/mariosasko/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-05-23T16:02:14Z', 'updated_at': '2023-05-23T16:02:14Z', 'author_association': 'CONTRIBUTOR', 'body': 'A duplicate of https://github.com/huggingface/datasets/issues/1774', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1559735753/reactions', 'total_count': 1, '+1': 1, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}]

[{'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1563293541', 'html_url': 'https://github.com/huggingface/datasets/issues/5874#issuecomment-1563293541', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5874', 'id': 1563293541, 'node_id': 'IC_kwDODunzps5dLfdl', 'user': {'login': 'mariosasko', 'id': 47462742, 'node_id': 'MDQ6VXNlcjQ3NDYyNzQy', 'avatar_url': 'https://avatars.githubusercontent.com/u/47462742?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/mariosasko', 'html_url': 'https://github.com/mariosasko', 'followers_url': 'https://api.github.com/users/mariosasko/followers', 'following_url': 'https://api.github.com/users/mariosasko/following{/other_user}', 'gists_url': 'https://api.github.com/users/mariosasko/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/mariosasko/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/mariosasko/subscriptions', 'organizations_url': 'https://api.github.com/users/mariosasko/orgs', 'repos_url': 'https://api.github.com/users/mariosasko/repos', 'events_url': 'https://api.github.com/users/mariosasko/events{/privacy}', 'received_events_url': 'https://api.github.com/users/mariosasko/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-05-25T17:56:09Z', 'updated_at': '2023-05-25T17:56:09Z', 'author_association': 'CONTRIBUTOR', 'body': 'Hi! You can refer to [this doc](https://huggingface.co/docs/datasets/filesystems#load-and-save-your-datasets-using-your-cloud-storage-filesystem) to see the intended usage (basically, it skips the Arrow -> Parquet conversion step in `ds = load_dataset(...); ds.to_parquet("path/to/parquet")`) and allows writing Parquet to remote storage unlike `to_parquet`).\r\n\r\n> I guess I\'d expect as_dataset to generate the dataset in arrow format if it has to, or to suggest an alternative way to load the dataset (I\'ve also tried other methods with load_dataset to no avail, probably due to misunderstandings on my part).\r\n\r\n`as_dataset` does not work with `file_format="parquet"` files as Parquet files cannot be memory-mapped, so I think we should just raise an error in that case.\r\n', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1563293541/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}]
[]
[{'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1550785770', 'html_url': 'https://github.com/huggingface/datasets/pull/5872#issuecomment-1550785770', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5872', 'id': 1550785770, 'node_id': 'IC_kwDODunzps5cbxzq', 'user': {'login': 'HuggingFaceDocBuilderDev', 'id': 99929124, 'node_id': 'U_kgDOBfTMJA', 'avatar_url': 'https://avatars.githubusercontent.com/u/99929124?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/HuggingFaceDocBuilderDev', 'html_url': 'https://github.com/HuggingFaceDocBuilderDev', 'followers_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/followers', 'following_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/following{/other_user}', 'gists_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/subscriptions', 'organizations_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/orgs', 'repos_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/repos', 'events_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/events{/privacy}', 'received_events_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-05-17T06:01:10Z', 'updated_at': '2023-05-17T14:22:04Z', 'author_association': 'NONE', 'body': '_The documentation is not available anymore as the PR was closed or merged._', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1550785770/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1551504110', 'html_url': 'https://github.com/huggingface/datasets/pull/5872#issuecomment-1551504110', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5872', 'id': 1551504110, 'node_id': 'IC_kwDODunzps5cehLu', 'user': {'login': 'github-actions[bot]', 'id': 41898282, 'node_id': 'MDM6Qm90NDE4OTgyODI=', 'avatar_url': 'https://avatars.githubusercontent.com/in/15368?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/github-actions%5Bbot%5D', 'html_url': 'https://github.com/apps/github-actions', 'followers_url': 'https://api.github.com/users/github-actions%5Bbot%5D/followers', 'following_url': 'https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}', 'gists_url': 'https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/github-actions%5Bbot%5D/subscriptions', 'organizations_url': 'https://api.github.com/users/github-actions%5Bbot%5D/orgs', 'repos_url': 'https://api.github.com/users/github-actions%5Bbot%5D/repos', 'events_url': 'https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}', 'received_events_url': 'https://api.github.com/users/github-actions%5Bbot%5D/received_events', 'type': 'Bot', 'site_admin': False}, 'created_at': '2023-05-17T14:26:58Z', 'updated_at': '2023-05-17T14:26:58Z', 'author_association': 'NONE', 'body': '<details>\n<summary>Show benchmarks</summary>\n\nPyArrow==8.0.0\n\n<details>\n<summary>Show updated benchmarks!</summary>\n\n### Benchmark: benchmark_array_xd.json\n\n| metric | read_batch_formatted_as_numpy after write_array2d | read_batch_formatted_as_numpy after write_flattened_sequence | read_batch_formatted_as_numpy after write_nested_sequence | read_batch_unformated after write_array2d | read_batch_unformated after write_flattened_sequence | read_batch_unformated after write_nested_sequence | read_col_formatted_as_numpy after write_array2d | read_col_formatted_as_numpy after write_flattened_sequence | read_col_formatted_as_numpy after write_nested_sequence | read_col_unformated after write_array2d | read_col_unformated after write_flattened_sequence | read_col_unformated after write_nested_sequence | read_formatted_as_numpy after write_array2d | read_formatted_as_numpy after write_flattened_sequence | read_formatted_as_numpy after write_nested_sequence | read_unformated after write_array2d | read_unformated after write_flattened_sequence | read_unformated after write_nested_sequence | write_array2d | write_flattened_sequence | write_nested_sequence |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.007049 / 0.011353 (-0.004304) | 0.005034 / 0.011008 (-0.005974) | 0.097737 / 0.038508 (0.059229) | 0.033280 / 0.023109 (0.010170) | 0.301017 / 0.275898 (0.025119) | 0.336593 / 0.323480 (0.013113) | 0.005567 / 0.007986 (-0.002419) | 0.005384 / 0.004328 (0.001056) | 0.072980 / 0.004250 (0.068730) | 0.045030 / 0.037052 (0.007978) | 0.303280 / 0.258489 (0.044791) | 0.367528 / 0.293841 (0.073687) | 0.034131 / 0.128546 (-0.094415) | 0.012118 / 0.075646 (-0.063528) | 0.331677 / 0.419271 (-0.087594) | 0.049211 / 0.043533 (0.005678) | 0.297535 / 0.255139 (0.042396) | 0.318136 / 0.283200 (0.034936) | 0.101574 / 0.141683 (-0.040109) | 1.472769 / 1.452155 (0.020615) | 1.541724 / 1.492716 (0.049007) |\n\n### Benchmark: benchmark_getitem\\_100B.json\n\n| metric | get_batch_of\\_1024\\_random_rows | get_batch_of\\_1024\\_rows | get_first_row | get_last_row |\n|--------|---|---|---|---|\n| new / old (diff) | 0.014646 / 0.018006 (-0.003360) | 0.439050 / 0.000490 (0.438560) | 0.008575 / 0.000200 (0.008375) | 0.000297 / 0.000054 (0.000242) |\n\n### Benchmark: benchmark_indices_mapping.json\n\n| metric | select | shard | shuffle | sort | train_test_split |\n|--------|---|---|---|---|---|\n| new / old (diff) | 0.027591 / 0.037411 (-0.009820) | 0.111639 / 0.014526 (0.097113) | 0.117098 / 0.176557 (-0.059458) | 0.173281 / 0.737135 (-0.563855) | 0.123197 / 0.296338 (-0.173141) |\n\n### Benchmark: benchmark_iterating.json\n\n| metric | read 5000 | read 50000 | read_batch 50000 10 | read_batch 50000 100 | read_batch 50000 1000 | read_formatted numpy 5000 | read_formatted pandas 5000 | read_formatted tensorflow 5000 | read_formatted torch 5000 | read_formatted_batch numpy 5000 10 | read_formatted_batch numpy 5000 1000 | shuffled read 5000 | shuffled read 50000 | shuffled read_batch 50000 10 | shuffled read_batch 50000 100 | shuffled read_batch 50000 1000 | shuffled read_formatted numpy 5000 | shuffled read_formatted_batch numpy 5000 10 | shuffled read_formatted_batch numpy 5000 1000 |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.397507 / 0.215209 (0.182298) | 3.971457 / 2.077655 (1.893803) | 1.781158 / 1.504120 (0.277038) | 1.590419 / 1.541195 (0.049224) | 1.716374 / 1.468490 (0.247884) | 0.687150 / 4.584777 (-3.897627) | 3.691009 / 3.745712 (-0.054703) | 2.050900 / 5.269862 (-3.218961) | 1.304893 / 4.565676 (-3.260784) | 0.084507 / 0.424275 (-0.339768) | 0.012231 / 0.007607 (0.004624) | 0.493033 / 0.226044 (0.266988) | 4.929957 / 2.268929 (2.661028) | 2.209069 / 55.444624 (-53.235555) | 1.885992 / 6.876477 (-4.990485) | 2.007004 / 2.142072 (-0.135069) | 0.827265 / 4.805227 (-3.977963) | 0.168225 / 6.500664 (-6.332439) | 0.064988 / 0.075469 (-0.010481) |\n\n### Benchmark: benchmark_map_filter.json\n\n| metric | filter | map fast-tokenizer batched | map identity | map identity batched | map no-op batched | map no-op batched numpy | map no-op batched pandas | map no-op batched pytorch | map no-op batched tensorflow |\n|--------|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 1.182341 / 1.841788 (-0.659447) | 14.691983 / 8.074308 (6.617674) | 14.350720 / 10.191392 (4.159328) | 0.164307 / 0.680424 (-0.516117) | 0.017480 / 0.534201 (-0.516720) | 0.421843 / 0.579283 (-0.157441) | 0.417481 / 0.434364 (-0.016883) | 0.496587 / 0.540337 (-0.043751) | 0.581208 / 1.386936 (-0.805728) |\n\n</details>\nPyArrow==latest\n\n<details>\n<summary>Show updated benchmarks!</summary>\n\n### Benchmark: benchmark_array_xd.json\n\n| metric | read_batch_formatted_as_numpy after write_array2d | read_batch_formatted_as_numpy after write_flattened_sequence | read_batch_formatted_as_numpy after write_nested_sequence | read_batch_unformated after write_array2d | read_batch_unformated after write_flattened_sequence | read_batch_unformated after write_nested_sequence | read_col_formatted_as_numpy after write_array2d | read_col_formatted_as_numpy after write_flattened_sequence | read_col_formatted_as_numpy after write_nested_sequence | read_col_unformated after write_array2d | read_col_unformated after write_flattened_sequence | read_col_unformated after write_nested_sequence | read_formatted_as_numpy after write_array2d | read_formatted_as_numpy after write_flattened_sequence | read_formatted_as_numpy after write_nested_sequence | read_unformated after write_array2d | read_unformated after write_flattened_sequence | read_unformated after write_nested_sequence | write_array2d | write_flattened_sequence | write_nested_sequence |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.007070 / 0.011353 (-0.004283) | 0.005083 / 0.011008 (-0.005926) | 0.075009 / 0.038508 (0.036500) | 0.032343 / 0.023109 (0.009234) | 0.366788 / 0.275898 (0.090890) | 0.392273 / 0.323480 (0.068794) | 0.005512 / 0.007986 (-0.002474) | 0.003999 / 0.004328 (-0.000329) | 0.073743 / 0.004250 (0.069492) | 0.046203 / 0.037052 (0.009151) | 0.367874 / 0.258489 (0.109385) | 0.409154 / 0.293841 (0.115313) | 0.035227 / 0.128546 (-0.093319) | 0.012223 / 0.075646 (-0.063424) | 0.087149 / 0.419271 (-0.332122) | 0.045648 / 0.043533 (0.002115) | 0.362414 / 0.255139 (0.107275) | 0.379970 / 0.283200 (0.096770) | 0.100631 / 0.141683 (-0.041052) | 1.439733 / 1.452155 (-0.012422) | 1.506266 / 1.492716 (0.013550) |\n\n### Benchmark: benchmark_getitem\\_100B.json\n\n| metric | get_batch_of\\_1024\\_random_rows | get_batch_of\\_1024\\_rows | get_first_row | get_last_row |\n|--------|---|---|---|---|\n| new / old (diff) | 0.227071 / 0.018006 (0.209065) | 0.451243 / 0.000490 (0.450753) | 0.000406 / 0.000200 (0.000206) | 0.000060 / 0.000054 (0.000006) |\n\n### Benchmark: benchmark_indices_mapping.json\n\n| metric | select | shard | shuffle | sort | train_test_split |\n|--------|---|---|---|---|---|\n| new / old (diff) | 0.028952 / 0.037411 (-0.008459) | 0.111934 / 0.014526 (0.097408) | 0.124080 / 0.176557 (-0.052477) | 0.174022 / 0.737135 (-0.563113) | 0.126811 / 0.296338 (-0.169527) |\n\n### Benchmark: benchmark_iterating.json\n\n| metric | read 5000 | read 50000 | read_batch 50000 10 | read_batch 50000 100 | read_batch 50000 1000 | read_formatted numpy 5000 | read_formatted pandas 5000 | read_formatted tensorflow 5000 | read_formatted torch 5000 | read_formatted_batch numpy 5000 10 | read_formatted_batch numpy 5000 1000 | shuffled read 5000 | shuffled read 50000 | shuffled read_batch 50000 10 | shuffled read_batch 50000 100 | shuffled read_batch 50000 1000 | shuffled read_formatted numpy 5000 | shuffled read_formatted_batch numpy 5000 10 | shuffled read_formatted_batch numpy 5000 1000 |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.436423 / 0.215209 (0.221214) | 4.331959 / 2.077655 (2.254304) | 2.111914 / 1.504120 (0.607794) | 1.921338 / 1.541195 (0.380143) | 1.994425 / 1.468490 (0.525935) | 0.699164 / 4.584777 (-3.885613) | 3.722143 / 3.745712 (-0.023569) | 3.516538 / 5.269862 (-1.753323) | 1.867245 / 4.565676 (-2.698431) | 0.085923 / 0.424275 (-0.338352) | 0.012059 / 0.007607 (0.004452) | 0.586147 / 0.226044 (0.360102) | 5.395823 / 2.268929 (3.126894) | 2.594430 / 55.444624 (-52.850194) | 2.275021 / 6.876477 (-4.601456) | 2.347810 / 2.142072 (0.205737) | 0.835118 / 4.805227 (-3.970109) | 0.167089 / 6.500664 (-6.333575) | 0.064893 / 0.075469 (-0.010576) |\n\n### Benchmark: benchmark_map_filter.json\n\n| metric | filter | map fast-tokenizer batched | map identity | map identity batched | map no-op batched | map no-op batched numpy | map no-op batched pandas | map no-op batched pytorch | map no-op batched tensorflow |\n|--------|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 1.291423 / 1.841788 (-0.550365) | 14.992696 / 8.074308 (6.918388) | 13.307842 / 10.191392 (3.116450) | 0.163799 / 0.680424 (-0.516625) | 0.017315 / 0.534201 (-0.516886) | 0.461319 / 0.579283 (-0.117965) | 0.430474 / 0.434364 (-0.003889) | 0.568115 / 0.540337 (0.027777) | 0.647909 / 1.386936 (-0.739027) |\n\n</details>\n</details>\n\n![](https://cml.dev/watermark.png#a5161c9ecdcdde9cc99c7f212da13523d5ba6bdb "CML watermark")\n', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1551504110/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}]

[{'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1550211454', 'html_url': 'https://github.com/huggingface/datasets/issues/5871#issuecomment-1550211454', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5871', 'id': 1550211454, 'node_id': 'IC_kwDODunzps5cZll-', 'user': {'login': 'kylrth', 'id': 5044802, 'node_id': 'MDQ6VXNlcjUwNDQ4MDI=', 'avatar_url': 'https://avatars.githubusercontent.com/u/5044802?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/kylrth', 'html_url': 'https://github.com/kylrth', 'followers_url': 'https://api.github.com/users/kylrth/followers', 'following_url': 'https://api.github.com/users/kylrth/following{/other_user}', 'gists_url': 'https://api.github.com/users/kylrth/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/kylrth/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/kylrth/subscriptions', 'organizations_url': 'https://api.github.com/users/kylrth/orgs', 'repos_url': 'https://api.github.com/users/kylrth/repos', 'events_url': 'https://api.github.com/users/kylrth/events{/privacy}', 'received_events_url': 'https://api.github.com/users/kylrth/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-05-16T19:07:58Z', 'updated_at': '2023-05-16T19:07:58Z', 'author_association': 'CONTRIBUTOR', 'body': 'It could even use `os.path.realpath` to resolve symlinks.', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1550211454/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1563099878', 'html_url': 'https://github.com/huggingface/datasets/issues/5871#issuecomment-1563099878', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5871', 'id': 1563099878, 'node_id': 'IC_kwDODunzps5dKwLm', 'user': {'login': 'mariosasko', 'id': 47462742, 'node_id': 'MDQ6VXNlcjQ3NDYyNzQy', 'avatar_url': 'https://avatars.githubusercontent.com/u/47462742?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/mariosasko', 'html_url': 'https://github.com/mariosasko', 'followers_url': 'https://api.github.com/users/mariosasko/followers', 'following_url': 'https://api.github.com/users/mariosasko/following{/other_user}', 'gists_url': 'https://api.github.com/users/mariosasko/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/mariosasko/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/mariosasko/subscriptions', 'organizations_url': 'https://api.github.com/users/mariosasko/orgs', 'repos_url': 'https://api.github.com/users/mariosasko/repos', 'events_url': 'https://api.github.com/users/mariosasko/events{/privacy}', 'received_events_url': 'https://api.github.com/users/mariosasko/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-05-25T15:24:38Z', 'updated_at': '2023-05-25T15:24:38Z', 'author_association': 'CONTRIBUTOR', 'body': 'Indeed, it makes sense to normalize `data_dir`. Feel free to submit a PR (this can be "fixed" [here](https://github.com/huggingface/datasets/blob/89f775226321ba94e5bf4670a323c0fb44f5f65c/src/datasets/builder.py#L173))', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1563099878/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1563278516', 'html_url': 'https://github.com/huggingface/datasets/issues/5871#issuecomment-1563278516', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5871', 'id': 1563278516, 'node_id': 'IC_kwDODunzps5dLby0', 'user': {'login': 'kylrth', 'id': 5044802, 'node_id': 'MDQ6VXNlcjUwNDQ4MDI=', 'avatar_url': 'https://avatars.githubusercontent.com/u/5044802?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/kylrth', 'html_url': 'https://github.com/kylrth', 'followers_url': 'https://api.github.com/users/kylrth/followers', 'following_url': 'https://api.github.com/users/kylrth/following{/other_user}', 'gists_url': 'https://api.github.com/users/kylrth/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/kylrth/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/kylrth/subscriptions', 'organizations_url': 'https://api.github.com/users/kylrth/orgs', 'repos_url': 'https://api.github.com/users/kylrth/repos', 'events_url': 'https://api.github.com/users/kylrth/events{/privacy}', 'received_events_url': 'https://api.github.com/users/kylrth/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-05-25T17:42:29Z', 'updated_at': '2023-05-25T17:42:29Z', 'author_association': 'CONTRIBUTOR', 'body': '#self-assign', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1563278516/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}]
[{'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1549803233', 'html_url': 'https://github.com/huggingface/datasets/issues/5870#issuecomment-1549803233', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5870', 'id': 1549803233, 'node_id': 'IC_kwDODunzps5cYB7h', 'user': {'login': 'llStringll', 'id': 30209072, 'node_id': 'MDQ6VXNlcjMwMjA5MDcy', 'avatar_url': 'https://avatars.githubusercontent.com/u/30209072?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/llStringll', 'html_url': 'https://github.com/llStringll', 'followers_url': 'https://api.github.com/users/llStringll/followers', 'following_url': 'https://api.github.com/users/llStringll/following{/other_user}', 'gists_url': 'https://api.github.com/users/llStringll/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/llStringll/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/llStringll/subscriptions', 'organizations_url': 'https://api.github.com/users/llStringll/orgs', 'repos_url': 'https://api.github.com/users/llStringll/repos', 'events_url': 'https://api.github.com/users/llStringll/events{/privacy}', 'received_events_url': 'https://api.github.com/users/llStringll/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-05-16T14:36:04Z', 'updated_at': '2023-05-16T14:36:04Z', 'author_association': 'NONE', 'body': "PS - some work is definitely needed for 'special cases' docs, not explanations, just usages of 'functions' under mixture of special cases, like a combination of custom databuilder + iterable dataset for large size + dynamic .map() application.", 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1549803233/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}]

[{'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1549961634', 'html_url': 'https://github.com/huggingface/datasets/issues/5868#issuecomment-1549961634', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5868', 'id': 1549961634, 'node_id': 'IC_kwDODunzps5cYomi', 'user': {'login': 'mariosasko', 'id': 47462742, 'node_id': 'MDQ6VXNlcjQ3NDYyNzQy', 'avatar_url': 'https://avatars.githubusercontent.com/u/47462742?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/mariosasko', 'html_url': 'https://github.com/mariosasko', 'followers_url': 'https://api.github.com/users/mariosasko/followers', 'following_url': 'https://api.github.com/users/mariosasko/following{/other_user}', 'gists_url': 'https://api.github.com/users/mariosasko/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/mariosasko/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/mariosasko/subscriptions', 'organizations_url': 'https://api.github.com/users/mariosasko/orgs', 'repos_url': 'https://api.github.com/users/mariosasko/repos', 'events_url': 'https://api.github.com/users/mariosasko/events{/privacy}', 'received_events_url': 'https://api.github.com/users/mariosasko/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-05-16T16:06:33Z', 'updated_at': '2023-05-16T16:06:50Z', 'author_association': 'CONTRIBUTOR', 'body': "Arrow files/primitives (tables and arrays) are immutable, so re-generating them is the only option, I'm afraid.", 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1549961634/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1550925718', 'html_url': 'https://github.com/huggingface/datasets/issues/5868#issuecomment-1550925718', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5868', 'id': 1550925718, 'node_id': 'IC_kwDODunzps5ccT-W', 'user': {'login': 'zyh3826', 'id': 31238754, 'node_id': 'MDQ6VXNlcjMxMjM4NzU0', 'avatar_url': 'https://avatars.githubusercontent.com/u/31238754?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/zyh3826', 'html_url': 'https://github.com/zyh3826', 'followers_url': 'https://api.github.com/users/zyh3826/followers', 'following_url': 'https://api.github.com/users/zyh3826/following{/other_user}', 'gists_url': 'https://api.github.com/users/zyh3826/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/zyh3826/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/zyh3826/subscriptions', 'organizations_url': 'https://api.github.com/users/zyh3826/orgs', 'repos_url': 'https://api.github.com/users/zyh3826/repos', 'events_url': 'https://api.github.com/users/zyh3826/events{/privacy}', 'received_events_url': 'https://api.github.com/users/zyh3826/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-05-17T07:53:22Z', 'updated_at': '2023-05-17T07:53:22Z', 'author_association': 'NONE', 'body': '> \r\n\r\nGot it, thanks for your reply', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1550925718/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}]

[{'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1563190607', 'html_url': 'https://github.com/huggingface/datasets/issues/5866#issuecomment-1563190607', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5866', 'id': 1563190607, 'node_id': 'IC_kwDODunzps5dLGVP', 'user': {'login': 'mariosasko', 'id': 47462742, 'node_id': 'MDQ6VXNlcjQ3NDYyNzQy', 'avatar_url': 'https://avatars.githubusercontent.com/u/47462742?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/mariosasko', 'html_url': 'https://github.com/mariosasko', 'followers_url': 'https://api.github.com/users/mariosasko/followers', 'following_url': 'https://api.github.com/users/mariosasko/following{/other_user}', 'gists_url': 'https://api.github.com/users/mariosasko/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/mariosasko/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/mariosasko/subscriptions', 'organizations_url': 'https://api.github.com/users/mariosasko/orgs', 'repos_url': 'https://api.github.com/users/mariosasko/repos', 'events_url': 'https://api.github.com/users/mariosasko/events{/privacy}', 'received_events_url': 'https://api.github.com/users/mariosasko/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-05-25T16:28:39Z', 'updated_at': '2023-05-25T16:28:39Z', 'author_association': 'CONTRIBUTOR', 'body': "Thanks for reporting! I've opened a PR with a fix.", 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1563190607/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}]

[{'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1548334225', 'html_url': 'https://github.com/huggingface/datasets/issues/5864#issuecomment-1548334225', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5864', 'id': 1548334225, 'node_id': 'IC_kwDODunzps5cSbSR', 'user': {'login': 'fecet', 'id': 41792945, 'node_id': 'MDQ6VXNlcjQxNzkyOTQ1', 'avatar_url': 'https://avatars.githubusercontent.com/u/41792945?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/fecet', 'html_url': 'https://github.com/fecet', 'followers_url': 'https://api.github.com/users/fecet/followers', 'following_url': 'https://api.github.com/users/fecet/following{/other_user}', 'gists_url': 'https://api.github.com/users/fecet/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/fecet/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/fecet/subscriptions', 'organizations_url': 'https://api.github.com/users/fecet/orgs', 'repos_url': 'https://api.github.com/users/fecet/repos', 'events_url': 'https://api.github.com/users/fecet/events{/privacy}', 'received_events_url': 'https://api.github.com/users/fecet/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-05-15T18:13:56Z', 'updated_at': '2023-05-16T03:27:38Z', 'author_association': 'NONE', 'body': 'I am highly interested performance of dataset so I ran your example as a curious user.\r\n```python\r\ntrain_dataset.cast_column("x", Array3D(shape=img_shape, dtype="float32"))\r\n```\r\nhave return values and "x" is a new column, it shoulde be\r\n```python\r\nds=train_dataset.cast_column("img", Array3D(shape=(3,32,32), dtype="float32"))\r\n```\r\nI rewrite your example as\r\n```python\r\ntrain_dataset = load_dataset(\r\n    \'cifar100\',\r\n    split=\'train\',\r\n    use_auth_token=True,\r\n)\r\ntransform_func = torchvision.transforms.Compose([\r\n    ToTensor(), \r\n    Normalize(mean=[0.485, 0.456, 0.406], std= [0.229, 0.224, 0.225]),]          \r\n)\r\n    \r\ntrain_dataset = train_dataset.map(\r\n    desc=f"Preprocessing samples",\r\n    function=lambda x: {"img": transform_func(x["img"])},\r\n)\r\nds=train_dataset.cast_column("img", Array3D(shape=(3,32,32), dtype="float32"))\r\nfor i in tqdm(ds):\r\n    pass\r\n```\r\nthat require ~11s in my environment. While\r\n```python\r\nds = load_dataset(\r\n    \'cifar100\',\r\n    split=\'train\',\r\n    use_auth_token=True,\r\n)\r\n\r\nfor i in tqdm(ds):\r\n    pass\r\n```\r\nonly need ~6s. (So I guess it\'s still undesirable)', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1548334225/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}]

[{'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1591248797', 'html_url': 'https://github.com/huggingface/datasets/issues/5862#issuecomment-1591248797', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5862', 'id': 1591248797, 'node_id': 'IC_kwDODunzps5e2Ied', 'user': {'login': 'albertvillanova', 'id': 8515462, 'node_id': 'MDQ6VXNlcjg1MTU0NjI=', 'avatar_url': 'https://avatars.githubusercontent.com/u/8515462?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/albertvillanova', 'html_url': 'https://github.com/albertvillanova', 'followers_url': 'https://api.github.com/users/albertvillanova/followers', 'following_url': 'https://api.github.com/users/albertvillanova/following{/other_user}', 'gists_url': 'https://api.github.com/users/albertvillanova/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/albertvillanova/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/albertvillanova/subscriptions', 'organizations_url': 'https://api.github.com/users/albertvillanova/orgs', 'repos_url': 'https://api.github.com/users/albertvillanova/repos', 'events_url': 'https://api.github.com/users/albertvillanova/events{/privacy}', 'received_events_url': 'https://api.github.com/users/albertvillanova/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-14T13:50:11Z', 'updated_at': '2023-06-16T14:54:02Z', 'author_association': 'MEMBER', 'body': 'This error is also raised when data is hosted on Google Drive:\r\n- https://huggingface.co/datasets/docred/discussions/5\r\n- https://huggingface.co/datasets/linnaeus/discussions/3\r\n- https://huggingface.co/datasets/poleval2019_mt/discussions/3\r\n- https://huggingface.co/datasets/reddit_tifu/discussions/2\r\n- https://huggingface.co/datasets/species_800/discussions/3\r\n- https://huggingface.co/datasets/wiki_lingua/discussions/1\r\n- https://huggingface.co/datasets/yoruba_text_c3/discussions/1', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1591248797/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}]

[{'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1547540614', 'html_url': 'https://github.com/huggingface/datasets/pull/5860#issuecomment-1547540614', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5860', 'id': 1547540614, 'node_id': 'IC_kwDODunzps5cPZiG', 'user': {'login': 'HuggingFaceDocBuilderDev', 'id': 99929124, 'node_id': 'U_kgDOBfTMJA', 'avatar_url': 'https://avatars.githubusercontent.com/u/99929124?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/HuggingFaceDocBuilderDev', 'html_url': 'https://github.com/HuggingFaceDocBuilderDev', 'followers_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/followers', 'following_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/following{/other_user}', 'gists_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/subscriptions', 'organizations_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/orgs', 'repos_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/repos', 'events_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/events{/privacy}', 'received_events_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-05-15T09:53:58Z', 'updated_at': '2023-05-17T18:43:48Z', 'author_association': 'NONE', 'body': '_The documentation is not available anymore as the PR was closed or merged._', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1547540614/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1547542816', 'html_url': 'https://github.com/huggingface/datasets/pull/5860#issuecomment-1547542816', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5860', 'id': 1547542816, 'node_id': 'IC_kwDODunzps5cPaEg', 'user': {'login': 'github-actions[bot]', 'id': 41898282, 'node_id': 'MDM6Qm90NDE4OTgyODI=', 'avatar_url': 'https://avatars.githubusercontent.com/in/15368?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/github-actions%5Bbot%5D', 'html_url': 'https://github.com/apps/github-actions', 'followers_url': 'https://api.github.com/users/github-actions%5Bbot%5D/followers', 'following_url': 'https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}', 'gists_url': 'https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/github-actions%5Bbot%5D/subscriptions', 'organizations_url': 'https://api.github.com/users/github-actions%5Bbot%5D/orgs', 'repos_url': 'https://api.github.com/users/github-actions%5Bbot%5D/repos', 'events_url': 'https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}', 'received_events_url': 'https://api.github.com/users/github-actions%5Bbot%5D/received_events', 'type': 'Bot', 'site_admin': False}, 'created_at': '2023-05-15T09:55:34Z', 'updated_at': '2023-05-15T09:55:34Z', 'author_association': 'NONE', 'body': '<details>\n<summary>Show benchmarks</summary>\n\nPyArrow==8.0.0\n\n<details>\n<summary>Show updated benchmarks!</summary>\n\n### Benchmark: benchmark_array_xd.json\n\n| metric | read_batch_formatted_as_numpy after write_array2d | read_batch_formatted_as_numpy after write_flattened_sequence | read_batch_formatted_as_numpy after write_nested_sequence | read_batch_unformated after write_array2d | read_batch_unformated after write_flattened_sequence | read_batch_unformated after write_nested_sequence | read_col_formatted_as_numpy after write_array2d | read_col_formatted_as_numpy after write_flattened_sequence | read_col_formatted_as_numpy after write_nested_sequence | read_col_unformated after write_array2d | read_col_unformated after write_flattened_sequence | read_col_unformated after write_nested_sequence | read_formatted_as_numpy after write_array2d | read_formatted_as_numpy after write_flattened_sequence | read_formatted_as_numpy after write_nested_sequence | read_unformated after write_array2d | read_unformated after write_flattened_sequence | read_unformated after write_nested_sequence | write_array2d | write_flattened_sequence | write_nested_sequence |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.006917 / 0.011353 (-0.004436) | 0.004803 / 0.011008 (-0.006205) | 0.097082 / 0.038508 (0.058574) | 0.035105 / 0.023109 (0.011996) | 0.325911 / 0.275898 (0.050013) | 0.371858 / 0.323480 (0.048378) | 0.006451 / 0.007986 (-0.001534) | 0.004421 / 0.004328 (0.000093) | 0.075738 / 0.004250 (0.071487) | 0.053624 / 0.037052 (0.016572) | 0.332661 / 0.258489 (0.074172) | 0.372729 / 0.293841 (0.078888) | 0.028279 / 0.128546 (-0.100267) | 0.009318 / 0.075646 (-0.066328) | 0.328505 / 0.419271 (-0.090766) | 0.066962 / 0.043533 (0.023429) | 0.316863 / 0.255139 (0.061724) | 0.344296 / 0.283200 (0.061096) | 0.120575 / 0.141683 (-0.021108) | 1.457867 / 1.452155 (0.005712) | 1.597361 / 1.492716 (0.104644) |\n\n### Benchmark: benchmark_getitem\\_100B.json\n\n| metric | get_batch_of\\_1024\\_random_rows | get_batch_of\\_1024\\_rows | get_first_row | get_last_row |\n|--------|---|---|---|---|\n| new / old (diff) | 0.296399 / 0.018006 (0.278392) | 0.507196 / 0.000490 (0.506706) | 0.003036 / 0.000200 (0.002836) | 0.000088 / 0.000054 (0.000034) |\n\n### Benchmark: benchmark_indices_mapping.json\n\n| metric | select | shard | shuffle | sort | train_test_split |\n|--------|---|---|---|---|---|\n| new / old (diff) | 0.028535 / 0.037411 (-0.008876) | 0.110566 / 0.014526 (0.096040) | 0.122078 / 0.176557 (-0.054479) | 0.182926 / 0.737135 (-0.554210) | 0.125546 / 0.296338 (-0.170792) |\n\n### Benchmark: benchmark_iterating.json\n\n| metric | read 5000 | read 50000 | read_batch 50000 10 | read_batch 50000 100 | read_batch 50000 1000 | read_formatted numpy 5000 | read_formatted pandas 5000 | read_formatted tensorflow 5000 | read_formatted torch 5000 | read_formatted_batch numpy 5000 10 | read_formatted_batch numpy 5000 1000 | shuffled read 5000 | shuffled read 50000 | shuffled read_batch 50000 10 | shuffled read_batch 50000 100 | shuffled read_batch 50000 1000 | shuffled read_formatted numpy 5000 | shuffled read_formatted_batch numpy 5000 10 | shuffled read_formatted_batch numpy 5000 1000 |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.426952 / 0.215209 (0.211742) | 4.255608 / 2.077655 (2.177953) | 2.063865 / 1.504120 (0.559745) | 1.867198 / 1.541195 (0.326004) | 2.058236 / 1.468490 (0.589746) | 0.525885 / 4.584777 (-4.058892) | 3.723607 / 3.745712 (-0.022105) | 1.919144 / 5.269862 (-3.350718) | 1.235308 / 4.565676 (-3.330368) | 0.066423 / 0.424275 (-0.357852) | 0.012045 / 0.007607 (0.004438) | 0.528432 / 0.226044 (0.302388) | 5.268723 / 2.268929 (2.999794) | 2.504071 / 55.444624 (-52.940553) | 2.137999 / 6.876477 (-4.738477) | 2.229987 / 2.142072 (0.087914) | 0.641739 / 4.805227 (-4.163488) | 0.142635 / 6.500664 (-6.358029) | 0.065649 / 0.075469 (-0.009820) |\n\n### Benchmark: benchmark_map_filter.json\n\n| metric | filter | map fast-tokenizer batched | map identity | map identity batched | map no-op batched | map no-op batched numpy | map no-op batched pandas | map no-op batched pytorch | map no-op batched tensorflow |\n|--------|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 1.182710 / 1.841788 (-0.659078) | 15.339777 / 8.074308 (7.265469) | 14.722308 / 10.191392 (4.530916) | 0.145914 / 0.680424 (-0.534510) | 0.017861 / 0.534201 (-0.516340) | 0.393092 / 0.579283 (-0.186191) | 0.431179 / 0.434364 (-0.003185) | 0.485712 / 0.540337 (-0.054625) | 0.602634 / 1.386936 (-0.784302) |\n\n</details>\nPyArrow==latest\n\n<details>\n<summary>Show updated benchmarks!</summary>\n\n### Benchmark: benchmark_array_xd.json\n\n| metric | read_batch_formatted_as_numpy after write_array2d | read_batch_formatted_as_numpy after write_flattened_sequence | read_batch_formatted_as_numpy after write_nested_sequence | read_batch_unformated after write_array2d | read_batch_unformated after write_flattened_sequence | read_batch_unformated after write_nested_sequence | read_col_formatted_as_numpy after write_array2d | read_col_formatted_as_numpy after write_flattened_sequence | read_col_formatted_as_numpy after write_nested_sequence | read_col_unformated after write_array2d | read_col_unformated after write_flattened_sequence | read_col_unformated after write_nested_sequence | read_formatted_as_numpy after write_array2d | read_formatted_as_numpy after write_flattened_sequence | read_formatted_as_numpy after write_nested_sequence | read_unformated after write_array2d | read_unformated after write_flattened_sequence | read_unformated after write_nested_sequence | write_array2d | write_flattened_sequence | write_nested_sequence |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.006792 / 0.011353 (-0.004561) | 0.005118 / 0.011008 (-0.005890) | 0.073440 / 0.038508 (0.034932) | 0.033751 / 0.023109 (0.010642) | 0.389243 / 0.275898 (0.113345) | 0.397083 / 0.323480 (0.073603) | 0.005989 / 0.007986 (-0.001997) | 0.004289 / 0.004328 (-0.000040) | 0.073228 / 0.004250 (0.068977) | 0.053490 / 0.037052 (0.016438) | 0.396070 / 0.258489 (0.137581) | 0.415134 / 0.293841 (0.121293) | 0.028649 / 0.128546 (-0.099897) | 0.009159 / 0.075646 (-0.066487) | 0.080813 / 0.419271 (-0.338458) | 0.048200 / 0.043533 (0.004667) | 0.388009 / 0.255139 (0.132870) | 0.382174 / 0.283200 (0.098975) | 0.107807 / 0.141683 (-0.033876) | 1.467276 / 1.452155 (0.015121) | 1.568091 / 1.492716 (0.075375) |\n\n### Benchmark: benchmark_getitem\\_100B.json\n\n| metric | get_batch_of\\_1024\\_random_rows | get_batch_of\\_1024\\_rows | get_first_row | get_last_row |\n|--------|---|---|---|---|\n| new / old (diff) | 0.328030 / 0.018006 (0.310024) | 0.498058 / 0.000490 (0.497568) | 0.002513 / 0.000200 (0.002313) | 0.000099 / 0.000054 (0.000045) |\n\n### Benchmark: benchmark_indices_mapping.json\n\n| metric | select | shard | shuffle | sort | train_test_split |\n|--------|---|---|---|---|---|\n| new / old (diff) | 0.029835 / 0.037411 (-0.007576) | 0.113859 / 0.014526 (0.099333) | 0.130813 / 0.176557 (-0.045743) | 0.183646 / 0.737135 (-0.553490) | 0.136561 / 0.296338 (-0.159777) |\n\n### Benchmark: benchmark_iterating.json\n\n| metric | read 5000 | read 50000 | read_batch 50000 10 | read_batch 50000 100 | read_batch 50000 1000 | read_formatted numpy 5000 | read_formatted pandas 5000 | read_formatted tensorflow 5000 | read_formatted torch 5000 | read_formatted_batch numpy 5000 10 | read_formatted_batch numpy 5000 1000 | shuffled read 5000 | shuffled read 50000 | shuffled read_batch 50000 10 | shuffled read_batch 50000 100 | shuffled read_batch 50000 1000 | shuffled read_formatted numpy 5000 | shuffled read_formatted_batch numpy 5000 10 | shuffled read_formatted_batch numpy 5000 1000 |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.438901 / 0.215209 (0.223692) | 4.376426 / 2.077655 (2.298771) | 2.220932 / 1.504120 (0.716812) | 2.043585 / 1.541195 (0.502390) | 2.161383 / 1.468490 (0.692893) | 0.523224 / 4.584777 (-4.061553) | 3.730589 / 3.745712 (-0.015123) | 1.859602 / 5.269862 (-3.410260) | 1.073415 / 4.565676 (-3.492261) | 0.066363 / 0.424275 (-0.357912) | 0.012491 / 0.007607 (0.004884) | 0.542052 / 0.226044 (0.316008) | 5.426246 / 2.268929 (3.157318) | 2.673884 / 55.444624 (-52.770740) | 2.372611 / 6.876477 (-4.503865) | 2.482216 / 2.142072 (0.340143) | 0.705669 / 4.805227 (-4.099558) | 0.141075 / 6.500664 (-6.359589) | 0.065339 / 0.075469 (-0.010130) |\n\n### Benchmark: benchmark_map_filter.json\n\n| metric | filter | map fast-tokenizer batched | map identity | map identity batched | map no-op batched | map no-op batched numpy | map no-op batched pandas | map no-op batched pytorch | map no-op batched tensorflow |\n|--------|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 1.316403 / 1.841788 (-0.525385) | 15.832870 / 8.074308 (7.758562) | 13.307045 / 10.191392 (3.115653) | 0.147258 / 0.680424 (-0.533166) | 0.017966 / 0.534201 (-0.516235) | 0.414396 / 0.579283 (-0.164887) | 0.431801 / 0.434364 (-0.002563) | 0.465483 / 0.540337 (-0.074855) | 0.577850 / 1.386936 (-0.809086) |\n\n</details>\n</details>\n\n![](https://cml.dev/watermark.png#c795c7e332a7c850c3e725f2034d4894b5e314f7 "CML watermark")\n', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1547542816/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1551891492', 'html_url': 'https://github.com/huggingface/datasets/pull/5860#issuecomment-1551891492', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5860', 'id': 1551891492, 'node_id': 'IC_kwDODunzps5cf_wk', 'user': {'login': 'github-actions[bot]', 'id': 41898282, 'node_id': 'MDM6Qm90NDE4OTgyODI=', 'avatar_url': 'https://avatars.githubusercontent.com/in/15368?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/github-actions%5Bbot%5D', 'html_url': 'https://github.com/apps/github-actions', 'followers_url': 'https://api.github.com/users/github-actions%5Bbot%5D/followers', 'following_url': 'https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}', 'gists_url': 'https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/github-actions%5Bbot%5D/subscriptions', 'organizations_url': 'https://api.github.com/users/github-actions%5Bbot%5D/orgs', 'repos_url': 'https://api.github.com/users/github-actions%5Bbot%5D/repos', 'events_url': 'https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}', 'received_events_url': 'https://api.github.com/users/github-actions%5Bbot%5D/received_events', 'type': 'Bot', 'site_admin': False}, 'created_at': '2023-05-17T18:46:45Z', 'updated_at': '2023-05-17T18:46:45Z', 'author_association': 'NONE', 'body': '<details>\n<summary>Show benchmarks</summary>\n\nPyArrow==8.0.0\n\n<details>\n<summary>Show updated benchmarks!</summary>\n\n### Benchmark: benchmark_array_xd.json\n\n| metric | read_batch_formatted_as_numpy after write_array2d | read_batch_formatted_as_numpy after write_flattened_sequence | read_batch_formatted_as_numpy after write_nested_sequence | read_batch_unformated after write_array2d | read_batch_unformated after write_flattened_sequence | read_batch_unformated after write_nested_sequence | read_col_formatted_as_numpy after write_array2d | read_col_formatted_as_numpy after write_flattened_sequence | read_col_formatted_as_numpy after write_nested_sequence | read_col_unformated after write_array2d | read_col_unformated after write_flattened_sequence | read_col_unformated after write_nested_sequence | read_formatted_as_numpy after write_array2d | read_formatted_as_numpy after write_flattened_sequence | read_formatted_as_numpy after write_nested_sequence | read_unformated after write_array2d | read_unformated after write_flattened_sequence | read_unformated after write_nested_sequence | write_array2d | write_flattened_sequence | write_nested_sequence |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.006368 / 0.011353 (-0.004985) | 0.004274 / 0.011008 (-0.006734) | 0.098799 / 0.038508 (0.060291) | 0.029096 / 0.023109 (0.005986) | 0.308009 / 0.275898 (0.032111) | 0.345701 / 0.323480 (0.022221) | 0.005312 / 0.007986 (-0.002674) | 0.003435 / 0.004328 (-0.000894) | 0.075912 / 0.004250 (0.071662) | 0.041993 / 0.037052 (0.004941) | 0.320075 / 0.258489 (0.061586) | 0.347506 / 0.293841 (0.053665) | 0.025456 / 0.128546 (-0.103091) | 0.008461 / 0.075646 (-0.067185) | 0.322823 / 0.419271 (-0.096448) | 0.044650 / 0.043533 (0.001117) | 0.314118 / 0.255139 (0.058979) | 0.333436 / 0.283200 (0.050237) | 0.093811 / 0.141683 (-0.047871) | 1.464464 / 1.452155 (0.012310) | 1.548098 / 1.492716 (0.055382) |\n\n### Benchmark: benchmark_getitem\\_100B.json\n\n| metric | get_batch_of\\_1024\\_random_rows | get_batch_of\\_1024\\_rows | get_first_row | get_last_row |\n|--------|---|---|---|---|\n| new / old (diff) | 0.015905 / 0.018006 (-0.002101) | 0.427847 / 0.000490 (0.427357) | 0.007600 / 0.000200 (0.007400) | 0.000421 / 0.000054 (0.000366) |\n\n### Benchmark: benchmark_indices_mapping.json\n\n| metric | select | shard | shuffle | sort | train_test_split |\n|--------|---|---|---|---|---|\n| new / old (diff) | 0.024530 / 0.037411 (-0.012882) | 0.099907 / 0.014526 (0.085381) | 0.107282 / 0.176557 (-0.069275) | 0.168332 / 0.737135 (-0.568804) | 0.109875 / 0.296338 (-0.186464) |\n\n### Benchmark: benchmark_iterating.json\n\n| metric | read 5000 | read 50000 | read_batch 50000 10 | read_batch 50000 100 | read_batch 50000 1000 | read_formatted numpy 5000 | read_formatted pandas 5000 | read_formatted tensorflow 5000 | read_formatted torch 5000 | read_formatted_batch numpy 5000 10 | read_formatted_batch numpy 5000 1000 | shuffled read 5000 | shuffled read 50000 | shuffled read_batch 50000 10 | shuffled read_batch 50000 100 | shuffled read_batch 50000 1000 | shuffled read_formatted numpy 5000 | shuffled read_formatted_batch numpy 5000 10 | shuffled read_formatted_batch numpy 5000 1000 |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.451064 / 0.215209 (0.235855) | 4.491434 / 2.077655 (2.413779) | 2.253251 / 1.504120 (0.749131) | 2.086740 / 1.541195 (0.545545) | 2.133288 / 1.468490 (0.664798) | 0.558801 / 4.584777 (-4.025976) | 3.463525 / 3.745712 (-0.282187) | 1.747657 / 5.269862 (-3.522205) | 1.005465 / 4.565676 (-3.560211) | 0.068341 / 0.424275 (-0.355934) | 0.012521 / 0.007607 (0.004914) | 0.567002 / 0.226044 (0.340957) | 5.689529 / 2.268929 (3.420601) | 2.700562 / 55.444624 (-52.744062) | 2.384888 / 6.876477 (-4.491589) | 2.503160 / 2.142072 (0.361088) | 0.667107 / 4.805227 (-4.138120) | 0.137253 / 6.500664 (-6.363412) | 0.068300 / 0.075469 (-0.007170) |\n\n### Benchmark: benchmark_map_filter.json\n\n| metric | filter | map fast-tokenizer batched | map identity | map identity batched | map no-op batched | map no-op batched numpy | map no-op batched pandas | map no-op batched pytorch | map no-op batched tensorflow |\n|--------|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 1.202916 / 1.841788 (-0.638872) | 14.163393 / 8.074308 (6.089085) | 14.402463 / 10.191392 (4.211071) | 0.145273 / 0.680424 (-0.535151) | 0.016996 / 0.534201 (-0.517205) | 0.363520 / 0.579283 (-0.215763) | 0.421595 / 0.434364 (-0.012769) | 0.438413 / 0.540337 (-0.101925) | 0.508615 / 1.386936 (-0.878321) |\n\n</details>\nPyArrow==latest\n\n<details>\n<summary>Show updated benchmarks!</summary>\n\n### Benchmark: benchmark_array_xd.json\n\n| metric | read_batch_formatted_as_numpy after write_array2d | read_batch_formatted_as_numpy after write_flattened_sequence | read_batch_formatted_as_numpy after write_nested_sequence | read_batch_unformated after write_array2d | read_batch_unformated after write_flattened_sequence | read_batch_unformated after write_nested_sequence | read_col_formatted_as_numpy after write_array2d | read_col_formatted_as_numpy after write_flattened_sequence | read_col_formatted_as_numpy after write_nest

[{'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1547394531', 'html_url': 'https://github.com/huggingface/datasets/pull/5859#issuecomment-1547394531', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5859', 'id': 1547394531, 'node_id': 'IC_kwDODunzps5cO13j', 'user': {'login': 'HuggingFaceDocBuilderDev', 'id': 99929124, 'node_id': 'U_kgDOBfTMJA', 'avatar_url': 'https://avatars.githubusercontent.com/u/99929124?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/HuggingFaceDocBuilderDev', 'html_url': 'https://github.com/HuggingFaceDocBuilderDev', 'followers_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/followers', 'following_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/following{/other_user}', 'gists_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/subscriptions', 'organizations_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/orgs', 'repos_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/repos', 'events_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/events{/privacy}', 'received_events_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-05-15T08:13:16Z', 'updated_at': '2023-05-25T16:26:13Z', 'author_association': 'NONE', 'body': '_The documentation is not available anymore as the PR was closed or merged._', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1547394531/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1562995791', 'html_url': 'https://github.com/huggingface/datasets/pull/5859#issuecomment-1562995791', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5859', 'id': 1562995791, 'node_id': 'IC_kwDODunzps5dKWxP', 'user': {'login': 'albertvillanova', 'id': 8515462, 'node_id': 'MDQ6VXNlcjg1MTU0NjI=', 'avatar_url': 'https://avatars.githubusercontent.com/u/8515462?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/albertvillanova', 'html_url': 'https://github.com/albertvillanova', 'followers_url': 'https://api.github.com/users/albertvillanova/followers', 'following_url': 'https://api.github.com/users/albertvillanova/following{/other_user}', 'gists_url': 'https://api.github.com/users/albertvillanova/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/albertvillanova/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/albertvillanova/subscriptions', 'organizations_url': 'https://api.github.com/users/albertvillanova/orgs', 'repos_url': 'https://api.github.com/users/albertvillanova/repos', 'events_url': 'https://api.github.com/users/albertvillanova/events{/privacy}', 'received_events_url': 'https://api.github.com/users/albertvillanova/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-05-25T14:19:32Z', 'updated_at': '2023-05-25T14:22:09Z', 'author_association': 'MEMBER', 'body': '@lhoestq any idea why this only fails (CI integration fails are unrelated) in "Build PR Documentation / build / build_pr_documentation" (which uses Python 3.8), with message:\r\n```\r\nTypeError: Type subscription requires python >= 3.9\r\n```\r\nwhereas the CI is green for unit tests, which use Python 3.7?', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1562995791/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1563015747', 'html_url': 'https://github.com/huggingface/datasets/pull/5859#issuecomment-1563015747', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5859', 'id': 1563015747, 'node_id': 'IC_kwDODunzps5dKbpD', 'user': {'login': 'lhoestq', 'id': 42851186, 'node_id': 'MDQ6VXNlcjQyODUxMTg2', 'avatar_url': 'https://avatars.githubusercontent.com/u/42851186?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/lhoestq', 'html_url': 'https://github.com/lhoestq', 'followers_url': 'https://api.github.com/users/lhoestq/followers', 'following_url': 'https://api.github.com/users/lhoestq/following{/other_user}', 'gists_url': 'https://api.github.com/users/lhoestq/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/lhoestq/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/lhoestq/subscriptions', 'organizations_url': 'https://api.github.com/users/lhoestq/orgs', 'repos_url': 'https://api.github.com/users/lhoestq/repos', 'events_url': 'https://api.github.com/users/lhoestq/events{/privacy}', 'received_events_url': 'https://api.github.com/users/lhoestq/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-05-25T14:32:06Z', 'updated_at': '2023-05-25T14:32:06Z', 'author_association': 'MEMBER', 'body': "Hmm I don't know sorry :/", 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1563015747/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1563054260', 'html_url': 'https://github.com/huggingface/datasets/pull/5859#issuecomment-1563054260', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5859', 'id': 1563054260, 'node_id': 'IC_kwDODunzps5dKlC0', 'user': {'login': 'albertvillanova', 'id': 8515462, 'node_id': 'MDQ6VXNlcjg1MTU0NjI=', 'avatar_url': 'https://avatars.githubusercontent.com/u/8515462?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/albertvillanova', 'html_url': 'https://github.com/albertvillanova', 'followers_url': 'https://api.github.com/users/albertvillanova/followers', 'following_url': 'https://api.github.com/users/albertvillanova/following{/other_user}', 'gists_url': 'https://api.github.com/users/albertvillanova/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/albertvillanova/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/albertvillanova/subscriptions', 'organizations_url': 'https://api.github.com/users/albertvillanova/orgs', 'repos_url': 'https://api.github.com/users/albertvillanova/repos', 'events_url': 'https://api.github.com/users/albertvillanova/events{/privacy}', 'received_events_url': 'https://api.github.com/users/albertvillanova/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-05-25T14:55:21Z', 'updated_at': '2023-05-25T14:56:59Z', 'author_association': 'MEMBER', 'body': '@lhoestq I am afraid I have to remove the generics I created for numpy and pandas (no subscriptable until Python 3.9) and just leave:\r\n```python\r\nListLike = Union[List[T], Tuple[T, ...]]\r\n```', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1563054260/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1563066961', 'html_url': 'https://github.com/huggingface/datasets/pull/5859#issuecomment-1563066961', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5859', 'id': 1563066961, 'node_id': 'IC_kwDODunzps5dKoJR', 'user': {'login': 'lhoestq', 'id': 42851186, 'node_id': 'MDQ6VXNlcjQyODUxMTg2', 'avatar_url': 'https://avatars.githubusercontent.com/u/42851186?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/lhoestq', 'html_url': 'https://github.com/lhoestq', 'followers_url': 'https://api.github.com/users/lhoestq/followers', 'following_url': 'https://api.github.com/users/lhoestq/following{/other_user}', 'gists_url': 'https://api.github.com/users/lhoestq/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/lhoestq/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/lhoestq/subscriptions', 'organizations_url': 'https://api.github.com/users/lhoestq/orgs', 'repos_url': 'https://api.github.com/users/lhoestq/repos', 'events_url': 'https://api.github.com/users/lhoestq/events{/privacy}', 'received_events_url': 'https://api.github.com/users/lhoestq/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-05-25T15:02:52Z', 'updated_at': '2023-05-25T15:02:52Z', 'author_association': 'MEMBER', 'body': 'Ok sounds good - no need to spend more time on this', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1563066961/reactions', 'total_count': 1, '+1': 1, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1563104428', 'html_url': 'https://github.com/huggingface/datasets/pull/5859#issuecomment-1563104428', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5859', 'id': 1563104428, 'node_id': 'IC_kwDODunzps5dKxSs', 'user': {'login': 'albertvillanova', 'id': 8515462, 'node_id': 'MDQ6VXNlcjg1MTU0NjI=', 'avatar_url': 'https://avatars.githubusercontent.com/u/8515462?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/albertvillanova', 'html_url': 'https://github.com/albertvillanova', 'followers_url': 'https://api.github.com/users/albertvillanova/followers', 'following_url': 'https://api.github.com/users/albertvillanova/following{/other_user}', 'gists_url': 'https://api.github.com/users/albertvillanova/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/albertvillanova/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/albertvillanova/subscriptions', 'organizations_url': 'https://api.github.com/users/albertvillanova/orgs', 'repos_url': 'https://api.github.com/users/albertvillanova/repos', 'events_url': 'https://api.github.com/users/albertvillanova/events{/privacy}', 'received_events_url': 'https://api.github.com/users/albertvillanova/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-05-25T15:27:22Z', 'updated_at': '2023-05-25T15:27:22Z', 'author_association': 'MEMBER', 'body': 'I will merge once the CI is finished. The integration errors are unrelated: `502 Server Error: Bad Gateway`', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1563104428/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1563193997', 'html_url': 'https://github.com/huggingface/datasets/pull/5859#issuecomment-1563193997', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5859', 'id': 1563193997, 'node_id': 'IC_kwDODunzps5dLHKN', 'user': {'login': 'github-actions[bot]', 'id': 41898282, 'node_id': 'MDM6Qm90NDE4OTgyODI=', 'avatar_url': 'https://avatars.githubusercontent.com/in/15368?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/github-actions%5Bbot%5D', 'html_url': 'https://github.com/apps/github-actions', 'followers_url': 'https://api.github.com/users/github-actions%5Bbot%5D/followers', 'following_url': 'https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}', 'gists_url': 'https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/github-actions%5Bbot%5D/subscriptions', 'organizations_url': 'https://api.github.com/users/github-actions%5Bbot%5D/orgs', 'repos_url': 'https://api.github.com/users/github-actions%5Bbot%5D/repos', 'events_url': 'https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}', 'received_events_url': 'https://api.github.com/users/github-actions%5Bbot%5D/received_events', 'type': 'Bot', 'site_admin': False}, 'created_at': '2023-05-25T16:31:23Z', 'updated_at': '2023-05-25T16:31:23Z', 'author_association': 'NONE', 'body': '<details>\n<summary>Show benchmarks</summary>\n\nPyArrow==8.0.0\n\n<details>\n<summary>Show updated benchmarks!</summary>\n\n### Benchmark: benchmark_array_xd.json\n\n| metric | read_batch_formatted_as_numpy after write_array2d | read_batch_formatted_as_numpy after write_flattened_sequence | read_batch_formatted_as_numpy after write_nested_sequence | read_batch_unformated after write_array2d | read_batch_unformated after write_flattened_sequence | read_batch_unformated after write_nested_sequence | read_col_formatted_as_numpy after write_array2d | read_col_formatted_as_numpy after write_flattened_sequence | read_col_formatted_as_numpy after write_nested_sequence | read_col_unformated after write_array2d | read_col_unformated after write_flattened_sequence | read_col_unformated after write_nested_sequence | read_formatted_as_numpy after write_array2d | read_formatted_as_numpy after write_flattened_sequence | read_formatted_as_numpy after write_nested_sequence | read_unformated after write_array2d | read_unformated after write_flattened_sequence | read_unformated after write_nested_sequence | write_array2d | write_flattened_sequence | write_nested_sequence |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.006637 / 0.011353 (-0.004716) | 0.004578 / 0.011008 (-0.006430) | 0.097346 / 0.038508 (0.058838) | 0.034171 / 0.023109 (0.011062) | 0.315060 / 0.275898 (0.039162) | 0.354386 / 0.323480 (0.030907) | 0.005778 / 0.007986 (-0.002207) | 0.004123 / 0.004328 (-0.000206) | 0.073839 / 0.004250 (0.069589) | 0.046418 / 0.037052 (0.009366) | 0.325910 / 0.258489 (0.067421) | 0.368909 / 0.293841 (0.075068) | 0.027975 / 0.128546 (-0.100571) | 0.008885 / 0.075646 (-0.066761) | 0.327956 / 0.419271 (-0.091316) | 0.049911 / 0.043533 (0.006378) | 0.309424 / 0.255139 (0.054285) | 0.346543 / 0.283200 (0.063343) | 0.103429 / 0.141683 (-0.038253) | 1.517606 / 1.452155 (0.065451) | 1.536685 / 1.492716 (0.043969) |\n\n### Benchmark: benchmark_getitem\\_100B.json\n\n| metric | get_batch_of\\_1024\\_random_rows | get_batch_of\\_1024\\_rows | get_first_row | get_last_row |\n|--------|---|---|---|---|\n| new / old (diff) | 0.211552 / 0.018006 (0.193546) | 0.449583 / 0.000490 (0.449094) | 0.002949 / 0.000200 (0.002750) | 0.000140 / 0.000054 (0.000086) |\n\n### Benchmark: benchmark_indices_mapping.json\n\n| metric | select | shard | shuffle | sort | train_test_split |\n|--------|---|---|---|---|---|\n| new / old (diff) | 0.027603 / 0.037411 (-0.009808) | 0.108873 / 0.014526 (0.094347) | 0.117990 / 0.176557 (-0.058567) | 0.174202 / 0.737135 (-0.562933) | 0.123793 / 0.296338 (-0.172545) |\n\n### Benchmark: benchmark_iterating.json\n\n| metric | read 5000 | read 50000 | read_batch 50000 10 | read_batch 50000 100 | read_batch 50000 1000 | read_formatted numpy 5000 | read_formatted pandas 5000 | read_formatted tensorflow 5000 | read_formatted torch 5000 | read_formatted_batch numpy 5000 10 | read_formatted_batch numpy 5000 1000 | shuffled read 5000 | shuffled read 50000 | shuffled read_batch 50000 10 | shuffled read_batch 50000 100 | shuffled read_batch 50000 1000 | shuffled read_formatted numpy 5000 | shuffled read_formatted_batch numpy 5000 10 | shuffled read_formatted_batch numpy 5000 1000 |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.418449 / 0.215209 (0.203240) | 4.177753 / 2.077655 (2.100099) | 1.923446 / 1.504120 (0.419326) | 1.720576 / 1.541195 (0.179381) | 1.783723 / 1.468490 (0.315232) | 0.530068 / 4.584777 (-4.054709) | 3.709410 / 3.745712 (-0.036302) | 1.863924 / 5.269862 (-3.405938) | 1.149906 / 4.565676 (-3.415770) | 0.066595 / 0.424275 (-0.357680) | 0.011733 / 0.007607 (0.004126) | 0.519249 / 0.226044 (0.293205) | 5.179676 / 2.268929 (2.910748) | 2.389488 / 55.444624 (-53.055137) | 2.060006 / 6.876477 (-4.816471) | 2.160668 / 2.142072 (0.018596) | 0.641081 / 4.805227 (-4.164146) | 0.141962 / 6.500664 (-6.358702) | 0.063146 / 0.075469 (-0.012323) |\n\n### Benchmark: benchmark_map_filter.json\n\n| metric | filter | map fast-tokenizer batched | map identity | map identity batched | map no-op batched | map no-op batched numpy | map no-op batched pandas | map no-op batched pytorch | map no-op batched tensorflow |\n|--------|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 1.197424 / 1.841788 (-0.644364) | 14.915321 / 8.074308 (6.841013) | 14.792302 / 10.191392 (4.600910) | 0.145436 / 0.680424 (-0.534988) | 0.017669 / 0.534201 (-0.516532) | 0.399060 / 0.579283 (-0.180223) | 0.416282 / 0.434364 (-0.018082) | 0.498392 / 0.540337 (-0.041946) | 0.600242 / 1.386936 (-0.786694) |\n\n</details>\nPyArrow==latest\n\n<details>\n<summary>Show updated benchmarks!</summary>\n\n### Benchmark: benchmark_array_xd.json\n\n| metric | read_batch_formatted_as_numpy after write_array2d | read_batch_formatted_as_numpy after write_flattened_sequence | read_batch_formatted_as_numpy after write_nested_sequence | read_batch_unformated after write_array2d | read_batch_unformated after write_flattened_sequence | read_batch_unformated after write_nested_sequence | read_col_formatted_as_numpy after write_array2d | read_col_formatted_as_numpy after write_flattened_sequence | read_col_formatted_as_numpy after write_nested_sequence | read_col_unformated after write_array2d | read_col_unformated after write_flattened_sequence | read_col_unformated after write_nested_sequence | read_formatted_as_numpy after write_array2d | read_formatted_as_numpy after write_flattened_sequence | read_formatted_as_numpy after write_nested_sequence | read_unformated after write_array2d | read_unformated after write_flattened_sequence | read_unformated after write_nested_sequence | write_array2d | write_flattened_sequence | write_nested_sequence |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.007246 / 0.011353 (-0.004106) | 0.005353 / 0.011008 (-0.005656) | 0.076357 / 0.038508 (0.037849) | 0.037662 / 0.023109 (0.014553) | 0.387862 / 0.275898 (0.111964) | 0.421610 / 0.323480 (0.098130) | 0.006424 / 0.007986 (-0.001561) | 0.004397 / 0.004328 (0.000069) | 0.074212 / 0.004250 (0.069961) | 0.054147 / 0.037052 (0.017095) | 0.393171 / 0.258489 (0.134682) | 0.424082 / 0.293841 (0.130241) | 0.029001 / 0.128546 (-0.099546) | 0.009381 / 0.075646 (-0.066265) | 0.082562 / 0.419271 (-0.336710) | 0.048004 / 0.043533 (0.004472) | 0.386895 / 0.255139 (0.131756) | 0.386104 / 0.283200 (0.102904) | 0.113714 / 0.141683 (-0.027969) | 1.435601 / 1.452155 (-0.016553) | 1.554940 / 1.492716 (0.062224) |\n\n### Benchmark: benchmark_getitem\\_100B.json\n\n| metric | get_batch_of\\_1024\\_random_rows | get_batch_of\\_1024\\_rows | get_first_row | get_last_row |\n|--------|---|---|---|---|\n| new / old (diff) | 0.179288 / 0.018006 (0.161282) | 0.455301 / 0.000490 (0.454811) | 0.001469 / 0.000200 (0.001269) | 0.000091 / 0.000054 (0.000036) |\n\n### Benchmark: benchmark_indices_mapping.json\n\n| metric | select | shard | shuffle | sort | train_test_split |\n|--------|---|---|---|---|---|\n| new / old (diff) | 0.030928 / 0.037411 (-0.006484) | 0.117833 / 0.014526 (0.103307) | 0.125088 / 0.176557 (-0.051468) | 0.178906 / 0.737135 (-0.558230) | 0.131264 / 0.296338 (-0.165075) |\n\n### Benchmark: benchmark_iterating.json\n\n| metric | read 5000 | read 50000 | read_batch 50000 10 | read_batch 50000 100 | read_batch 50

[{'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1547312692', 'html_url': 'https://github.com/huggingface/datasets/issues/5858#issuecomment-1547312692', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5858', 'id': 1547312692, 'node_id': 'IC_kwDODunzps5cOh40', 'user': {'login': 'albertvillanova', 'id': 8515462, 'node_id': 'MDQ6VXNlcjg1MTU0NjI=', 'avatar_url': 'https://avatars.githubusercontent.com/u/8515462?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/albertvillanova', 'html_url': 'https://github.com/albertvillanova', 'followers_url': 'https://api.github.com/users/albertvillanova/followers', 'following_url': 'https://api.github.com/users/albertvillanova/following{/other_user}', 'gists_url': 'https://api.github.com/users/albertvillanova/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/albertvillanova/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/albertvillanova/subscriptions', 'organizations_url': 'https://api.github.com/users/albertvillanova/orgs', 'repos_url': 'https://api.github.com/users/albertvillanova/repos', 'events_url': 'https://api.github.com/users/albertvillanova/events{/privacy}', 'received_events_url': 'https://api.github.com/users/albertvillanova/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-05-15T07:15:08Z', 'updated_at': '2023-05-15T07:15:08Z', 'author_association': 'MEMBER', 'body': 'Thanks for reporting, @sarahwie.\r\n\r\nPlease note that in `datasets` we do not have vectorized operation like `pandas`. Therefore, your equality comparisons above are `False`:\r\n- For example: `squad[\'question\']` returns a `list`, and this list is not equal to `"Who was the Norse leader?"`\r\n\r\nThe `False` value is equivalent to `0` when indexing a dataset, thus the reason why you get the first element (with index 0): \r\n- For example: `squad[False]` is equivalent to `squad[0]`\r\n\r\nMaybe we should an exception instead of assuming that `False` is equivalent to `0` (and `True` is equivalent to `1`) in the context of indexing.', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1547312692/reactions', 'total_count': 1, '+1': 1, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}]
[{'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1563217366', 'html_url': 'https://github.com/huggingface/datasets/issues/5857#issuecomment-1563217366', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5857', 'id': 1563217366, 'node_id': 'IC_kwDODunzps5dLM3W', 'user': {'login': 'mariosasko', 'id': 47462742, 'node_id': 'MDQ6VXNlcjQ3NDYyNzQy', 'avatar_url': 'https://avatars.githubusercontent.com/u/47462742?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/mariosasko', 'html_url': 'https://github.com/mariosasko', 'followers_url': 'https://api.github.com/users/mariosasko/followers', 'following_url': 'https://api.github.com/users/mariosasko/following{/other_user}', 'gists_url': 'https://api.github.com/users/mariosasko/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/mariosasko/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/mariosasko/subscriptions', 'organizations_url': 'https://api.github.com/users/mariosasko/orgs', 'repos_url': 'https://api.github.com/users/mariosasko/repos', 'events_url': 'https://api.github.com/users/mariosasko/events{/privacy}', 'received_events_url': 'https://api.github.com/users/mariosasko/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-05-25T16:50:38Z', 'updated_at': '2023-05-25T16:50:38Z', 'author_association': 'CONTRIBUTOR', 'body': 'Hi! \r\n\r\nThis would be a nice addition to the Hub! You can find the existing chemistry datasets/models on the Hub (using the `chemistry` tag) [here](https://huggingface.co/search/full-text?q=chemistry&type=model&type=dataset).\r\n\r\nFeel free to ping us here on the Hub if you need help adding the datasets.\r\n', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1563217366/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}]
[{'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1568837744', 'html_url': 'https://github.com/huggingface/datasets/issues/5856#issuecomment-1568837744', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5856', 'id': 1568837744, 'node_id': 'IC_kwDODunzps5dgpBw', 'user': {'login': 'mariosasko', 'id': 47462742, 'node_id': 'MDQ6VXNlcjQ3NDYyNzQy', 'avatar_url': 'https://avatars.githubusercontent.com/u/47462742?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/mariosasko', 'html_url': 'https://github.com/mariosasko', 'followers_url': 'https://api.github.com/users/mariosasko/followers', 'following_url': 'https://api.github.com/users/mariosasko/following{/other_user}', 'gists_url': 'https://api.github.com/users/mariosasko/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/mariosasko/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/mariosasko/subscriptions', 'organizations_url': 'https://api.github.com/users/mariosasko/orgs', 'repos_url': 'https://api.github.com/users/mariosasko/repos', 'events_url': 'https://api.github.com/users/mariosasko/events{/privacy}', 'received_events_url': 'https://api.github.com/users/mariosasko/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-05-30T17:51:57Z', 'updated_at': '2023-05-30T17:51:57Z', 'author_association': 'CONTRIBUTOR', 'body': "Hi! You can avoid this error by using the preprocessed version:\r\n```python\r\nimport datasets\r\nds = datasets.load_dataset('natural_questions')\r\n```\r\n\r\nPS: Once we finish https://github.com/huggingface/datasets/pull/5364, this error will no longer be a problem.", 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1568837744/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1576424218', 'html_url': 'https://github.com/huggingface/datasets/issues/5856#issuecomment-1576424218', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5856', 'id': 1576424218, 'node_id': 'IC_kwDODunzps5d9lMa', 'user': {'login': 'Crownor', 'id': 19185508, 'node_id': 'MDQ6VXNlcjE5MTg1NTA4', 'avatar_url': 'https://avatars.githubusercontent.com/u/19185508?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/Crownor', 'html_url': 'https://github.com/Crownor', 'followers_url': 'https://api.github.com/users/Crownor/followers', 'following_url': 'https://api.github.com/users/Crownor/following{/other_user}', 'gists_url': 'https://api.github.com/users/Crownor/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/Crownor/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/Crownor/subscriptions', 'organizations_url': 'https://api.github.com/users/Crownor/orgs', 'repos_url': 'https://api.github.com/users/Crownor/repos', 'events_url': 'https://api.github.com/users/Crownor/events{/privacy}', 'received_events_url': 'https://api.github.com/users/Crownor/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-05T09:11:18Z', 'updated_at': '2023-06-05T09:11:18Z', 'author_association': 'NONE', 'body': "> Hi! You can avoid this error by using the preprocessed version:\r\n> \r\n> ```python\r\n> import datasets\r\n> ds = datasets.load_dataset('natural_questions')\r\n> ```\r\n> \r\n> PS: Once we finish #5364, this error will no longer be a problem.\r\n\r\nThanks, wish #5364  finish early", 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1576424218/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}]

[{'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1547544863', 'html_url': 'https://github.com/huggingface/datasets/issues/5855#issuecomment-1547544863', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5855', 'id': 1547544863, 'node_id': 'IC_kwDODunzps5cPakf', 'user': {'login': 'lhoestq', 'id': 42851186, 'node_id': 'MDQ6VXNlcjQyODUxMTg2', 'avatar_url': 'https://avatars.githubusercontent.com/u/42851186?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/lhoestq', 'html_url': 'https://github.com/lhoestq', 'followers_url': 'https://api.github.com/users/lhoestq/followers', 'following_url': 'https://api.github.com/users/lhoestq/following{/other_user}', 'gists_url': 'https://api.github.com/users/lhoestq/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/lhoestq/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/lhoestq/subscriptions', 'organizations_url': 'https://api.github.com/users/lhoestq/orgs', 'repos_url': 'https://api.github.com/users/lhoestq/repos', 'events_url': 'https://api.github.com/users/lhoestq/events{/privacy}', 'received_events_url': 'https://api.github.com/users/lhoestq/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-05-15T09:57:03Z', 'updated_at': '2023-05-15T09:57:03Z', 'author_association': 'MEMBER', 'body': "Cc @amyeroberts @Rocketknight1 \r\n\r\nIndded I think it's because it does something like this under the hood when there's no multiprocessing:\r\n\r\n```python\r\ntf_dataset = tf_dataset.shuffle(len(dataset))\r\n```\r\n\r\nPS: with multiprocessing it appears to be different:\r\n\r\n```python\r\nindices = np.arange(len(dataset))\r\nif shuffle:\r\n    np.random.shuffle(indices)\r\n```", 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1547544863/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1547756997', 'html_url': 'https://github.com/huggingface/datasets/issues/5855#issuecomment-1547756997', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5855', 'id': 1547756997, 'node_id': 'IC_kwDODunzps5cQOXF', 'user': {'login': 'Rocketknight1', 'id': 12866554, 'node_id': 'MDQ6VXNlcjEyODY2NTU0', 'avatar_url': 'https://avatars.githubusercontent.com/u/12866554?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/Rocketknight1', 'html_url': 'https://github.com/Rocketknight1', 'followers_url': 'https://api.github.com/users/Rocketknight1/followers', 'following_url': 'https://api.github.com/users/Rocketknight1/following{/other_user}', 'gists_url': 'https://api.github.com/users/Rocketknight1/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/Rocketknight1/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/Rocketknight1/subscriptions', 'organizations_url': 'https://api.github.com/users/Rocketknight1/orgs', 'repos_url': 'https://api.github.com/users/Rocketknight1/repos', 'events_url': 'https://api.github.com/users/Rocketknight1/events{/privacy}', 'received_events_url': 'https://api.github.com/users/Rocketknight1/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-05-15T12:20:20Z', 'updated_at': '2023-05-15T12:20:20Z', 'author_association': 'MEMBER', 'body': "Hi @massquantity, the dataset being shuffled there is not the full dataset. If you look at [the line above](https://github.com/huggingface/datasets/blob/main/src/datasets/utils/tf_utils.py#L182), the dataset is actually just a single indices array at that point, and that array is the only thing that gets fully loaded into memory and shuffled. We then load samples from the dataset by applying a transform function to the shuffled dataset, which fetches samples based on the indices it receives.\r\n\r\nIf your dataset is **really** gigantic, then this index tensor might be a memory issue, but since it's just an int64 tensor it will only use 1GB of memory per 125 million samples.\r\n\r\nStill, if you're encountering memory issues, there might be another cause here - can you share some code to reproduce the error, or does it depend on some internal/proprietary dataset?", 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1547756997/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1547828178', 'html_url': 'https://github.com/huggingface/datasets/issues/5855#issuecomment-1547828178', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5855', 'id': 1547828178, 'node_id': 'IC_kwDODunzps5cQfvS', 'user': {'login': 'massquantity', 'id': 28751760, 'node_id': 'MDQ6VXNlcjI4NzUxNzYw', 'avatar_url': 'https://avatars.githubusercontent.com/u/28751760?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/massquantity', 'html_url': 'https://github.com/massquantity', 'followers_url': 'https://api.github.com/users/massquantity/followers', 'following_url': 'https://api.github.com/users/massquantity/following{/other_user}', 'gists_url': 'https://api.github.com/users/massquantity/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/massquantity/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/massquantity/subscriptions', 'organizations_url': 'https://api.github.com/users/massquantity/orgs', 'repos_url': 'https://api.github.com/users/massquantity/repos', 'events_url': 'https://api.github.com/users/massquantity/events{/privacy}', 'received_events_url': 'https://api.github.com/users/massquantity/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-05-15T13:06:47Z', 'updated_at': '2023-05-15T13:26:20Z', 'author_association': 'NONE', 'body': 'Hi @Rocketknight1, you\'re right and I also noticed that only indices are used in shuffling. My data has shape (50000000, 10), but really the problem doesn\'t relate to a specific dataset. Simply running the following code costs me 10GB of memory.\r\n\r\n```python\r\nfrom datasets import Dataset\r\n\r\ndef gen():\r\n    for i in range(50000000):\r\n        yield {"data": i}\r\n\r\nds = Dataset.from_generator(gen, cache_dir="./huggingface")\r\n\r\ntf_ds = ds.to_tf_dataset(\r\n    batch_size=1,\r\n    shuffle=True,\r\n    drop_remainder=False,\r\n    prefetch=True,\r\n)\r\ntf_ds = iter(tf_ds)\r\nnext(tf_ds)\r\n# {\'data\': <tf.Tensor: shape=(1,), dtype=int64, numpy=array([0])>}\r\n```\r\n\r\nI just realized maybe it was an issue from tensorflow (I\'m using tf 2.12). So I tried the following code, and it used 10GB of memory too.\r\n```python\r\nimport numpy as np\r\nimport tensorflow as tf\r\n\r\ndata_size = 50000000\r\ntf_dataset = tf.data.Dataset.from_tensor_slices(np.arange(data_size))\r\ntf_dataset = iter(tf_dataset.shuffle(data_size))\r\nnext(tf_dataset)\r\n# <tf.Tensor: shape=(), dtype=int64, numpy=24774043>\r\n```\r\n\r\nBy the way, as @lhoestq mentioned, multiprocessing uses numpy shuffling, and it uses less than 1 GB of memory:\r\n```python\r\ntf_ds_mp = ds.to_tf_dataset(\r\n    batch_size=1,\r\n    shuffle=True,\r\n    drop_remainder=False,\r\n    prefetch=True,\r\n    num_workers=2,\r\n)\r\n```', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1547828178/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1547857482', 'html_url': 'https://github.com/huggingface/datasets/issues/5855#issuecomment-1547857482', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5855', 'id': 1547857482, 'node_id': 'IC_kwDODunzps5cQm5K', 'user': {'login': 'Rocketknight1', 'id': 12866554, 'node_id': 'MDQ6VXNlcjEyODY2NTU0', 'avatar_url': 'https://avatars.githubusercontent.com/u/12866554?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/Rocketknight1', 'html_url': 'https://github.com/Rocketknight1', 'followers_url': 'https://api.github.com/users/Rocketknight1/followers', 'following_url': 'https://api.github.com/users/Rocketknight1/following{/other_user}', 'gists_url': 'https://api.github.com/users/Rocketknight1/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/Rocketknight1/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/Rocketknight1/subscriptions', 'organizations_url': 'https://api.github.com/users/Rocketknight1/orgs', 'repos_url': 'https://api.github.com/users/Rocketknight1/repos', 'events_url': 'https://api.github.com/users/Rocketknight1/events{/privacy}', 'received_events_url': 'https://api.github.com/users/Rocketknight1/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-05-15T13:25:30Z', 'updated_at': '2023-05-15T13:25:30Z', 'author_association': 'MEMBER', 'body': "Thanks for that reproduction script - I've confirmed the same issue is occurring for me. Investigating it now!", 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1547857482/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1547887714', 'html_url': 'https://github.com/huggingface/datasets/issues/5855#issuecomment-1547887714', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5855', 'id': 1547887714, 'node_id': 'IC_kwDODunzps5cQuRi', 'user': {'login': 'Rocketknight1', 'id': 12866554, 'node_id': 'MDQ6VXNlcjEyODY2NTU0', 'avatar_url': 'https://avatars.githubusercontent.com/u/12866554?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/Rocketknight1', 'html_url': 'https://github.com/Rocketknight1', 'followers_url': 'https://api.github.com/users/Rocketknight1/followers', 'following_url': 'https://api.github.com/users/Rocketknight1/following{/other_user}', 'gists_url': 'https://api.github.com/users/Rocketknight1/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/Rocketknight1/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/Rocketknight1/subscriptions', 'organizations_url': 'https://api.github.com/users/Rocketknight1/orgs', 'repos_url': 'https://api.github.com/users/Rocketknight1/repos', 'events_url': 'https://api.github.com/users/Rocketknight1/events{/privacy}', 'received_events_url': 'https://api.github.com/users/Rocketknight1/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-05-15T13:45:15Z', 'updated_at': '2023-05-15T13:45:15Z', 'author_association': 'MEMBER', 'body': "Update: The memory usage is occurring in creation of the index and shuffle buffer. You can reproduce it very simply with:\r\n\r\n```python\r\nimport tensorflow as tf\r\nindices = tf.range(50_000_000, dtype=tf.int64)\r\ndataset = tf.data.Dataset.from_tensor_slices(indices)\r\ndataset = dataset.shuffle(len(dataset))\r\nprint(next(iter(dataset))\r\n```\r\nWhen I wrote this code I thought `tf.data` had an optimization for shuffling an entire tensor that wouldn't create the entire shuffle buffer, but evidently it's just creating the enormous buffer in memory. I'll see if I can find a more efficient way to do this - we might end up moving everything to the `numpy` multiprocessing path to avoid it.", 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1547887714/reactions', 'total_count': 2, '+1': 2, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1548095696', 'html_url': 'https://github.com/huggingface/datasets/issues/5855#issuecomment-1548095696', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5855', 'id': 1548095696, 'node_id': 'IC_kwDODunzps5cRhDQ', 'user': {'login': 'Rocketknight1', 'id': 12866554, 'node_id': 'MDQ6VXNlcjEyODY2NTU0', 'avatar_url': 'https://avatars.githubusercontent.com/u/12866554?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/Rocketknight1', 'html_url': 'https://github.com/Rocketknight1', 'followers_url': 'https://api.github.com/users/Rocketknight1/followers', 'following_url': 'https://api.github.com/users/Rocketknight1/following{/other_user}', 'gists_url': 'https://api.github.com/users/Rocketknight1/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/Rocketknight1/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/Rocketknight1/subscriptions', 'organizations_url': 'https://api.github.com/users/Rocketknight1/orgs', 'repos_url': 'https://api.github.com/users/Rocketknight1/repos', 'events_url': 'https://api.github.com/users/Rocketknight1/events{/privacy}', 'received_events_url': 'https://api.github.com/users/Rocketknight1/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-05-15T15:36:23Z', 'updated_at': '2023-05-15T15:36:23Z', 'author_association': 'MEMBER', 'body': 'I opened a PR to fix this - will continue the discussion there!', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1548095696/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}]

[{'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1546893884', 'html_url': 'https://github.com/huggingface/datasets/issues/5854#issuecomment-1546893884', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5854', 'id': 1546893884, 'node_id': 'IC_kwDODunzps5cM7o8', 'user': {'login': 'mariosasko', 'id': 47462742, 'node_id': 'MDQ6VXNlcjQ3NDYyNzQy', 'avatar_url': 'https://avatars.githubusercontent.com/u/47462742?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/mariosasko', 'html_url': 'https://github.com/mariosasko', 'followers_url': 'https://api.github.com/users/mariosasko/followers', 'following_url': 'https://api.github.com/users/mariosasko/following{/other_user}', 'gists_url': 'https://api.github.com/users/mariosasko/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/mariosasko/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/mariosasko/subscriptions', 'organizations_url': 'https://api.github.com/users/mariosasko/orgs', 'repos_url': 'https://api.github.com/users/mariosasko/repos', 'events_url': 'https://api.github.com/users/mariosasko/events{/privacy}', 'received_events_url': 'https://api.github.com/users/mariosasko/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-05-14T12:53:36Z', 'updated_at': '2023-05-14T12:53:36Z', 'author_association': 'CONTRIBUTOR', 'body': "Hi! `audiofolder` requires `datasets>=2.5.0`, so please update the `datasets`' installation (`pip install -U datasets`) in the environment to resolve the issue.", 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1546893884/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1546905207', 'html_url': 'https://github.com/huggingface/datasets/issues/5854#issuecomment-1546905207', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5854', 'id': 1546905207, 'node_id': 'IC_kwDODunzps5cM-Z3', 'user': {'login': 'ILG2021', 'id': 93691919, 'node_id': 'U_kgDOBZWgDw', 'avatar_url': 'https://avatars.githubusercontent.com/u/93691919?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/ILG2021', 'html_url': 'https://github.com/ILG2021', 'followers_url': 'https://api.github.com/users/ILG2021/followers', 'following_url': 'https://api.github.com/users/ILG2021/following{/other_user}', 'gists_url': 'https://api.github.com/users/ILG2021/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/ILG2021/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/ILG2021/subscriptions', 'organizations_url': 'https://api.github.com/users/ILG2021/orgs', 'repos_url': 'https://api.github.com/users/ILG2021/repos', 'events_url': 'https://api.github.com/users/ILG2021/events{/privacy}', 'received_events_url': 'https://api.github.com/users/ILG2021/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-05-14T13:50:54Z', 'updated_at': '2023-05-14T13:50:54Z', 'author_association': 'NONE', 'body': "> Hi! `audiofolder` requires `datasets>=2.5.0`, so please update the `datasets`' installation (`pip install -U datasets`) in the environment to resolve the issue.\r\n\r\nI don't think it is a problem of the version. It runs ok on colab or local machine. Only on kaggle will has this bug.", 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1546905207/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}]
[{'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1546178628', 'html_url': 'https://github.com/huggingface/datasets/pull/5853#issuecomment-1546178628', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5853', 'id': 1546178628, 'node_id': 'IC_kwDODunzps5cKNBE', 'user': {'login': 'HuggingFaceDocBuilderDev', 'id': 99929124, 'node_id': 'U_kgDOBfTMJA', 'avatar_url': 'https://avatars.githubusercontent.com/u/99929124?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/HuggingFaceDocBuilderDev', 'html_url': 'https://github.com/HuggingFaceDocBuilderDev', 'followers_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/followers', 'following_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/following{/other_user}', 'gists_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/subscriptions', 'organizations_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/orgs', 'repos_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/repos', 'events_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/events{/privacy}', 'received_events_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-05-12T19:23:43Z', 'updated_at': '2023-05-15T10:33:21Z', 'author_association': 'NONE', 'body': '_The documentation is not available anymore as the PR was closed or merged._', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1546178628/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1547602063', 'html_url': 'https://github.com/huggingface/datasets/pull/5853#issuecomment-1547602063', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5853', 'id': 1547602063, 'node_id': 'IC_kwDODunzps5cPoiP', 'user': {'login': 'julien-c', 'id': 326577, 'node_id': 'MDQ6VXNlcjMyNjU3Nw==', 'avatar_url': 'https://avatars.githubusercontent.com/u/326577?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/julien-c', 'html_url': 'https://github.com/julien-c', 'followers_url': 'https://api.github.com/users/julien-c/followers', 'following_url': 'https://api.github.com/users/julien-c/following{/other_user}', 'gists_url': 'https://api.github.com/users/julien-c/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/julien-c/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/julien-c/subscriptions', 'organizations_url': 'https://api.github.com/users/julien-c/orgs', 'repos_url': 'https://api.github.com/users/julien-c/repos', 'events_url': 'https://api.github.com/users/julien-c/events{/privacy}', 'received_events_url': 'https://api.github.com/users/julien-c/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-05-15T10:30:07Z', 'updated_at': '2023-05-15T10:30:07Z', 'author_association': 'MEMBER', 'body': "@mishig25 note that it's not exactly the same behavior as in nginx as here it interacts a bit with the `version` and the `language`\r\n\r\nShould be close enough, though.", 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1547602063/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1547611932', 'html_url': 'https://github.com/huggingface/datasets/pull/5853#issuecomment-1547611932', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5853', 'id': 1547611932, 'node_id': 'IC_kwDODunzps5cPq8c', 'user': {'login': 'github-actions[bot]', 'id': 41898282, 'node_id': 'MDM6Qm90NDE4OTgyODI=', 'avatar_url': 'https://avatars.githubusercontent.com/in/15368?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/github-actions%5Bbot%5D', 'html_url': 'https://github.com/apps/github-actions', 'followers_url': 'https://api.github.com/users/github-actions%5Bbot%5D/followers', 'following_url': 'https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}', 'gists_url': 'https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/github-actions%5Bbot%5D/subscriptions', 'organizations_url': 'https://api.github.com/users/github-actions%5Bbot%5D/orgs', 'repos_url': 'https://api.github.com/users/github-actions%5Bbot%5D/repos', 'events_url': 'https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}', 'received_events_url': 'https://api.github.com/users/github-actions%5Bbot%5D/received_events', 'type': 'Bot', 'site_admin': False}, 'created_at': '2023-05-15T10:37:19Z', 'updated_at': '2023-05-15T10:37:19Z', 'author_association': 'NONE', 'body': '<details>\n<summary>Show benchmarks</summary>\n\nPyArrow==8.0.0\n\n<details>\n<summary>Show updated benchmarks!</summary>\n\n### Benchmark: benchmark_array_xd.json\n\n| metric | read_batch_formatted_as_numpy after write_array2d | read_batch_formatted_as_numpy after write_flattened_sequence | read_batch_formatted_as_numpy after write_nested_sequence | read_batch_unformated after write_array2d | read_batch_unformated after write_flattened_sequence | read_batch_unformated after write_nested_sequence | read_col_formatted_as_numpy after write_array2d | read_col_formatted_as_numpy after write_flattened_sequence | read_col_formatted_as_numpy after write_nested_sequence | read_col_unformated after write_array2d | read_col_unformated after write_flattened_sequence | read_col_unformated after write_nested_sequence | read_formatted_as_numpy after write_array2d | read_formatted_as_numpy after write_flattened_sequence | read_formatted_as_numpy after write_nested_sequence | read_unformated after write_array2d | read_unformated after write_flattened_sequence | read_unformated after write_nested_sequence | write_array2d | write_flattened_sequence | write_nested_sequence |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.007212 / 0.011353 (-0.004141) | 0.005125 / 0.011008 (-0.005883) | 0.098460 / 0.038508 (0.059952) | 0.034040 / 0.023109 (0.010931) | 0.320203 / 0.275898 (0.044305) | 0.357787 / 0.323480 (0.034307) | 0.006000 / 0.007986 (-0.001986) | 0.005644 / 0.004328 (0.001316) | 0.072654 / 0.004250 (0.068403) | 0.049393 / 0.037052 (0.012341) | 0.345686 / 0.258489 (0.087196) | 0.362345 / 0.293841 (0.068504) | 0.036597 / 0.128546 (-0.091949) | 0.012303 / 0.075646 (-0.063343) | 0.334374 / 0.419271 (-0.084897) | 0.062010 / 0.043533 (0.018477) | 0.312547 / 0.255139 (0.057408) | 0.336021 / 0.283200 (0.052821) | 0.112304 / 0.141683 (-0.029378) | 1.446706 / 1.452155 (-0.005449) | 1.523256 / 1.492716 (0.030540) |\n\n### Benchmark: benchmark_getitem\\_100B.json\n\n| metric | get_batch_of\\_1024\\_random_rows | get_batch_of\\_1024\\_rows | get_first_row | get_last_row |\n|--------|---|---|---|---|\n| new / old (diff) | 0.217658 / 0.018006 (0.199652) | 0.449208 / 0.000490 (0.448718) | 0.002878 / 0.000200 (0.002679) | 0.000091 / 0.000054 (0.000036) |\n\n### Benchmark: benchmark_indices_mapping.json\n\n| metric | select | shard | shuffle | sort | train_test_split |\n|--------|---|---|---|---|---|\n| new / old (diff) | 0.025735 / 0.037411 (-0.011676) | 0.105876 / 0.014526 (0.091350) | 0.114887 / 0.176557 (-0.061669) | 0.170984 / 0.737135 (-0.566152) | 0.121420 / 0.296338 (-0.174918) |\n\n### Benchmark: benchmark_iterating.json\n\n| metric | read 5000 | read 50000 | read_batch 50000 10 | read_batch 50000 100 | read_batch 50000 1000 | read_formatted numpy 5000 | read_formatted pandas 5000 | read_formatted tensorflow 5000 | read_formatted torch 5000 | read_formatted_batch numpy 5000 10 | read_formatted_batch numpy 5000 1000 | shuffled read 5000 | shuffled read 50000 | shuffled read_batch 50000 10 | shuffled read_batch 50000 100 | shuffled read_batch 50000 1000 | shuffled read_formatted numpy 5000 | shuffled read_formatted_batch numpy 5000 10 | shuffled read_formatted_batch numpy 5000 1000 |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.419670 / 0.215209 (0.204461) | 4.189453 / 2.077655 (2.111798) | 1.938236 / 1.504120 (0.434116) | 1.769747 / 1.541195 (0.228553) | 1.910919 / 1.468490 (0.442429) | 0.705046 / 4.584777 (-3.879730) | 3.783774 / 3.745712 (0.038062) | 2.096504 / 5.269862 (-3.173358) | 1.339265 / 4.565676 (-3.226412) | 0.086670 / 0.424275 (-0.337605) | 0.012243 / 0.007607 (0.004636) | 0.524701 / 0.226044 (0.298657) | 5.240689 / 2.268929 (2.971760) | 2.473622 / 55.444624 (-52.971003) | 2.170568 / 6.876477 (-4.705909) | 2.289653 / 2.142072 (0.147581) | 0.848913 / 4.805227 (-3.956314) | 0.168332 / 6.500664 (-6.332332) | 0.064926 / 0.075469 (-0.010543) |\n\n### Benchmark: benchmark_map_filter.json\n\n| metric | filter | map fast-tokenizer batched | map identity | map identity batched | map no-op batched | map no-op batched numpy | map no-op batched pandas | map no-op batched pytorch | map no-op batched tensorflow |\n|--------|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 1.193614 / 1.841788 (-0.648173) | 14.920403 / 8.074308 (6.846095) | 14.475059 / 10.191392 (4.283667) | 0.164458 / 0.680424 (-0.515966) | 0.017613 / 0.534201 (-0.516588) | 0.426311 / 0.579283 (-0.152972) | 0.431478 / 0.434364 (-0.002886) | 0.520280 / 0.540337 (-0.020057) | 0.627738 / 1.386936 (-0.759198) |\n\n</details>\nPyArrow==latest\n\n<details>\n<summary>Show updated benchmarks!</summary>\n\n### Benchmark: benchmark_array_xd.json\n\n| metric | read_batch_formatted_as_numpy after write_array2d | read_batch_formatted_as_numpy after write_flattened_sequence | read_batch_formatted_as_numpy after write_nested_sequence | read_batch_unformated after write_array2d | read_batch_unformated after write_flattened_sequence | read_batch_unformated after write_nested_sequence | read_col_formatted_as_numpy after write_array2d | read_col_formatted_as_numpy after write_flattened_sequence | read_col_formatted_as_numpy after write_nested_sequence | read_col_unformated after write_array2d | read_col_unformated after write_flattened_sequence | read_col_unformated after write_nested_sequence | read_formatted_as_numpy after write_array2d | read_formatted_as_numpy after write_flattened_sequence | read_formatted_as_numpy after write_nested_sequence | read_unformated after write_array2d | read_unformated after write_flattened_sequence | read_unformated after write_nested_sequence | write_array2d | write_flattened_sequence | write_nested_sequence |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.007458 / 0.011353 (-0.003895) | 0.005363 / 0.011008 (-0.005645) | 0.076713 / 0.038508 (0.038205) | 0.034189 / 0.023109 (0.011079) | 0.359938 / 0.275898 (0.084040) | 0.395532 / 0.323480 (0.072052) | 0.005977 / 0.007986 (-0.002008) | 0.004263 / 0.004328 (-0.000065) | 0.075971 / 0.004250 (0.071721) | 0.051924 / 0.037052 (0.014871) | 0.362818 / 0.258489 (0.104329) | 0.409897 / 0.293841 (0.116056) | 0.035494 / 0.128546 (-0.093053) | 0.012399 / 0.075646 (-0.063247) | 0.088335 / 0.419271 (-0.330937) | 0.047968 / 0.043533 (0.004435) | 0.355744 / 0.255139 (0.100606) | 0.376339 / 0.283200 (0.093139) | 0.104542 / 0.141683 (-0.037141) | 1.464826 / 1.452155 (0.012672) | 1.600665 / 1.492716 (0.107948) |\n\n### Benchmark: benchmark_getitem\\_100B.json\n\n| metric | get_batch_of\\_1024\\_random_rows | get_batch_of\\_1024\\_rows | get_first_row | get_last_row |\n|--------|---|---|---|---|\n| new / old (diff) | 0.220841 / 0.018006 (0.202834) | 0.446444 / 0.000490 (0.445954) | 0.000392 / 0.000200 (0.000192) | 0.000057 / 0.000054 (0.000003) |\n\n### Benchmark: benchmark_indices_mapping.json\n\n| metric | select | shard | shuffle | sort | train_test_split |\n|--------|---|---|---|---|---|\n| new / old (diff) | 0.029402 / 0.037411 (-0.008009) | 0.116511 / 0.014526 (0.101986) | 0.122959 / 0.176557 (-0.053598) | 0.171674 / 0.737135 (-0.565462) | 0.129871 / 0.296338 (-0.166468) |\n\n### Benchmark: benchmark_iterating.json\n\n| metric | read 5000 | read 50000 | read_batch 50000 10 | read_batch 50000 100 | read_batch 50000 1000 | read_formatted numpy 5000 | read_formatted pandas 5000 | read_formatted tensorflow 5000 | read_formatted torch 5000 | read_formatted_batch numpy 5000 10 | read_formatted_batch numpy 5000 1000 | shuffled read 5000 | shuffled read 50000 | shuffled read_batch 50000 10 | shuffled read_batch 50000 100 | shuffled read_batch 50000 1000 | shuffled read_formatted numpy 5000 | shuffled read_formatted_batch numpy 5000 10 | shuffled read_formatted_batch numpy 5000 1000 |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.450411 / 0.215209 (0.235202) | 4.471859 / 2.077655 (2.394205) | 2.229439 / 1.504120 (0.725319) | 2.053308 / 1.541195 (0.512114) | 2.142476 / 1.468490 (0.673986) | 0.708299 / 4.584777 (-3.876478) | 3.797830 / 3.745712 (0.052118) | 2.142509 / 5.269862 (-3.127352) | 1.333357 / 4.565676 (-3.232320) | 0.086837 / 0.424275 (-0.337439) | 0.012102 / 0.007607 (0.004495) | 0.548428 / 0.226044 (0.322384) | 5.490611 / 2.268929 (3.221682) | 2.713882 / 55.444624 (-52.730742) | 2.399638 / 6.876477 (-4.476839) | 2.481549 / 2.142072 (0.339477) | 0.839812 / 4.805227 (-3.965415) | 0.168890 / 6.500664 (-6.331774) | 0.065564 / 0.075469 (-0.009906) |\n\n### Benchmark: benchmark_map_filter.json\n\n| metric | filter | map fast-tokenizer batched | map identity | map identity batched | map no-op batched | map no-op batched numpy | map no-op batched pandas | map no-op batched pytorch | map no-op batched tensorflow |\n|--------|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 1.275507 / 1.841788 (-0.566281) | 14.896343 / 8.074308 (6.822035) | 13.159701 / 10.191392 (2.968309) | 0.172065 / 0.680424 (-0.508359) | 0.017507 / 0.534201 (-0.516694) | 0.420031 / 0.579283 (-0.159252) | 0.438835 / 0.434364 (0.004471) | 0.490597 / 0.540337 (-0.049741) | 0.583952 / 1.386936 (-0.802984) |\n\n</details>\n</details>\n\n![](https://cml.dev/watermark.png#48c9755d0ae9abe4c4d6cd8c1ce76eff849f0e5c "CML watermark")\n', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1547611932/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}]

[{'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1546025521', 'html_url': 'https://github.com/huggingface/datasets/pull/5852#issuecomment-1546025521', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5852', 'id': 1546025521, 'node_id': 'IC_kwDODunzps5cJnox', 'user': {'login': 'github-actions[bot]', 'id': 41898282, 'node_id': 'MDM6Qm90NDE4OTgyODI=', 'avatar_url': 'https://avatars.githubusercontent.com/in/15368?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/github-actions%5Bbot%5D', 'html_url': 'https://github.com/apps/github-actions', 'followers_url': 'https://api.github.com/users/github-actions%5Bbot%5D/followers', 'following_url': 'https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}', 'gists_url': 'https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/github-actions%5Bbot%5D/subscriptions', 'organizations_url': 'https://api.github.com/users/github-actions%5Bbot%5D/orgs', 'repos_url': 'https://api.github.com/users/github-actions%5Bbot%5D/repos', 'events_url': 'https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}', 'received_events_url': 'https://api.github.com/users/github-actions%5Bbot%5D/received_events', 'type': 'Bot', 'site_admin': False}, 'created_at': '2023-05-12T16:53:48Z', 'updated_at': '2023-05-12T16:53:48Z', 'author_association': 'NONE', 'body': '<details>\n<summary>Show benchmarks</summary>\n\nPyArrow==8.0.0\n\n<details>\n<summary>Show updated benchmarks!</summary>\n\n### Benchmark: benchmark_array_xd.json\n\n| metric | read_batch_formatted_as_numpy after write_array2d | read_batch_formatted_as_numpy after write_flattened_sequence | read_batch_formatted_as_numpy after write_nested_sequence | read_batch_unformated after write_array2d | read_batch_unformated after write_flattened_sequence | read_batch_unformated after write_nested_sequence | read_col_formatted_as_numpy after write_array2d | read_col_formatted_as_numpy after write_flattened_sequence | read_col_formatted_as_numpy after write_nested_sequence | read_col_unformated after write_array2d | read_col_unformated after write_flattened_sequence | read_col_unformated after write_nested_sequence | read_formatted_as_numpy after write_array2d | read_formatted_as_numpy after write_flattened_sequence | read_formatted_as_numpy after write_nested_sequence | read_unformated after write_array2d | read_unformated after write_flattened_sequence | read_unformated after write_nested_sequence | write_array2d | write_flattened_sequence | write_nested_sequence |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.006567 / 0.011353 (-0.004786) | 0.004479 / 0.011008 (-0.006530) | 0.028286 / 0.038508 (-0.010222) | 0.033137 / 0.023109 (0.010028) | 0.305249 / 0.275898 (0.029351) | 0.330306 / 0.323480 (0.006826) | 0.003747 / 0.007986 (-0.004238) | 0.004409 / 0.004328 (0.000081) | 0.004742 / 0.004250 (0.000491) | 0.040780 / 0.037052 (0.003728) | 0.302879 / 0.258489 (0.044390) | 0.346880 / 0.293841 (0.053039) | 0.032908 / 0.128546 (-0.095638) | 0.010617 / 0.075646 (-0.065029) | 0.257996 / 0.419271 (-0.161275) | 0.051044 / 0.043533 (0.007511) | 0.306113 / 0.255139 (0.050974) | 0.324444 / 0.283200 (0.041244) | 0.100820 / 0.141683 (-0.040863) | 1.478402 / 1.452155 (0.026248) | 1.599398 / 1.492716 (0.106682) |\n\n### Benchmark: benchmark_getitem\\_100B.json\n\n| metric | get_batch_of\\_1024\\_random_rows | get_batch_of\\_1024\\_rows | get_first_row | get_last_row |\n|--------|---|---|---|---|\n| new / old (diff) | 0.216540 / 0.018006 (0.198534) | 0.433480 / 0.000490 (0.432991) | 0.004032 / 0.000200 (0.003832) | 0.000084 / 0.000054 (0.000029) |\n\n### Benchmark: benchmark_indices_mapping.json\n\n| metric | select | shard | shuffle | sort | train_test_split |\n|--------|---|---|---|---|---|\n| new / old (diff) | 0.027807 / 0.037411 (-0.009604) | 0.107225 / 0.014526 (0.092699) | 0.120157 / 0.176557 (-0.056400) | 0.174130 / 0.737135 (-0.563005) | 0.128902 / 0.296338 (-0.167437) |\n\n### Benchmark: benchmark_iterating.json\n\n| metric | read 5000 | read 50000 | read_batch 50000 10 | read_batch 50000 100 | read_batch 50000 1000 | read_formatted numpy 5000 | read_formatted pandas 5000 | read_formatted tensorflow 5000 | read_formatted torch 5000 | read_formatted_batch numpy 5000 10 | read_formatted_batch numpy 5000 1000 | shuffled read 5000 | shuffled read 50000 | shuffled read_batch 50000 10 | shuffled read_batch 50000 100 | shuffled read_batch 50000 1000 | shuffled read_formatted numpy 5000 | shuffled read_formatted_batch numpy 5000 10 | shuffled read_formatted_batch numpy 5000 1000 |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.395996 / 0.215209 (0.180787) | 3.936254 / 2.077655 (1.858599) | 1.808864 / 1.504120 (0.304744) | 1.608935 / 1.541195 (0.067741) | 1.646427 / 1.468490 (0.177937) | 0.716026 / 4.584777 (-3.868751) | 3.815045 / 3.745712 (0.069333) | 2.271534 / 5.269862 (-2.998327) | 1.548728 / 4.565676 (-3.016948) | 0.076743 / 0.424275 (-0.347532) | 0.011575 / 0.007607 (0.003968) | 0.499202 / 0.226044 (0.273158) | 4.983754 / 2.268929 (2.714825) | 2.239319 / 55.444624 (-53.205306) | 1.919427 / 6.876477 (-4.957050) | 2.019664 / 2.142072 (-0.122408) | 0.866318 / 4.805227 (-3.938910) | 0.157309 / 6.500664 (-6.343355) | 0.063341 / 0.075469 (-0.012128) |\n\n### Benchmark: benchmark_map_filter.json\n\n| metric | filter | map fast-tokenizer batched | map identity | map identity batched | map no-op batched | map no-op batched numpy | map no-op batched pandas | map no-op batched pytorch | map no-op batched tensorflow |\n|--------|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 1.180817 / 1.841788 (-0.660971) | 14.579869 / 8.074308 (6.505561) | 14.277848 / 10.191392 (4.086456) | 0.182560 / 0.680424 (-0.497863) | 0.017402 / 0.534201 (-0.516799) | 0.411549 / 0.579283 (-0.167734) | 0.432938 / 0.434364 (-0.001426) | 0.545067 / 0.540337 (0.004730) | 0.642173 / 1.386936 (-0.744763) |\n\n</details>\nPyArrow==latest\n\n<details>\n<summary>Show updated benchmarks!</summary>\n\n### Benchmark: benchmark_array_xd.json\n\n| metric | read_batch_formatted_as_numpy after write_array2d | read_batch_formatted_as_numpy after write_flattened_sequence | read_batch_formatted_as_numpy after write_nested_sequence | read_batch_unformated after write_array2d | read_batch_unformated after write_flattened_sequence | read_batch_unformated after write_nested_sequence | read_col_formatted_as_numpy after write_array2d | read_col_formatted_as_numpy after write_flattened_sequence | read_col_formatted_as_numpy after write_nested_sequence | read_col_unformated after write_array2d | read_col_unformated after write_flattened_sequence | read_col_unformated after write_nested_sequence | read_formatted_as_numpy after write_array2d | read_formatted_as_numpy after write_flattened_sequence | read_formatted_as_numpy after write_nested_sequence | read_unformated after write_array2d | read_unformated after write_flattened_sequence | read_unformated after write_nested_sequence | write_array2d | write_flattened_sequence | write_nested_sequence |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.006753 / 0.011353 (-0.004600) | 0.004590 / 0.011008 (-0.006418) | 0.006111 / 0.038508 (-0.032397) | 0.032763 / 0.023109 (0.009654) | 0.401001 / 0.275898 (0.125103) | 0.428063 / 0.323480 (0.104583) | 0.003730 / 0.007986 (-0.004255) | 0.004617 / 0.004328 (0.000289) | 0.004770 / 0.004250 (0.000519) | 0.049718 / 0.037052 (0.012666) | 0.399724 / 0.258489 (0.141235) | 0.440292 / 0.293841 (0.146451) | 0.032846 / 0.128546 (-0.095700) | 0.010842 / 0.075646 (-0.064804) | 0.012642 / 0.419271 (-0.406630) | 0.046043 / 0.043533 (0.002510) | 0.390862 / 0.255139 (0.135723) | 0.407027 / 0.283200 (0.123828) | 0.099349 / 0.141683 (-0.042334) | 1.455739 / 1.452155 (0.003584) | 1.572214 / 1.492716 (0.079497) |\n\n### Benchmark: benchmark_getitem\\_100B.json\n\n| metric | get_batch_of\\_1024\\_random_rows | get_batch_of\\_1024\\_rows | get_first_row | get_last_row |\n|--------|---|---|---|---|\n| new / old (diff) | 0.227186 / 0.018006 (0.209180) | 0.447404 / 0.000490 (0.446914) | 0.000400 / 0.000200 (0.000200) | 0.000055 / 0.000054 (0.000000) |\n\n### Benchmark: benchmark_indices_mapping.json\n\n| metric | select | shard | shuffle | sort | train_test_split |\n|--------|---|---|---|---|---|\n| new / old (diff) | 0.029830 / 0.037411 (-0.007581) | 0.112365 / 0.014526 (0.097839) | 0.125736 / 0.176557 (-0.050821) | 0.174781 / 0.737135 (-0.562354) | 0.129439 / 0.296338 (-0.166900) |\n\n### Benchmark: benchmark_iterating.json\n\n| metric | read 5000 | read 50000 | read_batch 50000 10 | read_batch 50000 100 | read_batch 50000 1000 | read_formatted numpy 5000 | read_formatted pandas 5000 | read_formatted tensorflow 5000 | read_formatted torch 5000 | read_formatted_batch numpy 5000 10 | read_formatted_batch numpy 5000 1000 | shuffled read 5000 | shuffled read 50000 | shuffled read_batch 50000 10 | shuffled read_batch 50000 100 | shuffled read_batch 50000 1000 | shuffled read_formatted numpy 5000 | shuffled read_formatted_batch numpy 5000 10 | shuffled read_formatted_batch numpy 5000 1000 |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.444438 / 0.215209 (0.229229) | 4.459381 / 2.077655 (2.381726) | 2.264541 / 1.504120 (0.760421) | 2.075257 / 1.541195 (0.534062) | 2.181289 / 1.468490 (0.712799) | 0.725279 / 4.584777 (-3.859498) | 3.863253 / 3.745712 (0.117541) | 2.132498 / 5.269862 (-3.137364) | 1.402003 / 4.565676 (-3.163673) | 0.084268 / 0.424275 (-0.340007) | 0.011762 / 0.007607 (0.004155) | 0.556239 / 0.226044 (0.330194) | 5.617998 / 2.268929 (3.349070) | 2.754789 / 55.444624 (-52.689835) | 2.418418 / 6.876477 (-4.458059) | 2.479696 / 2.142072 (0.337624) | 0.870037 / 4.805227 (-3.935190) | 0.160480 / 6.500664 (-6.340184) | 0.064464 / 0.075469 (-0.011005) |\n\n### Benchmark: benchmark_map_filter.json\n\n| metric | filter | map fast-tokenizer batched | map identity | map identity batched | map no-op batched | map no-op batched numpy | map no-op batched pandas | map no-op batched pytorch | map no-op batched tensorflow |\n|--------|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 1.290916 / 1.841788 (-0.550872) | 14.783173 / 8.074308 (6.708865) | 13.355883 / 10.191392 (3.164491) | 0.169963 / 0.680424 (-0.510461) | 0.017657 / 0.534201 (-0.516544) | 0.409218 / 0.579283 (-0.170065) | 0.422942 / 0.434364 (-0.011422) | 0.494968 / 0.540337 (-0.045369) | 0.587044 / 1.386936 (-0.799892) |\n\n</details>\n</details>\n\n![](https://cml.dev/watermark.png#2051e912d9525bc38a1caf295df0620619c488eb "CML watermark")\n', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1546025521/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1561366742', 'html_url': 'https://github.com/huggingface/datasets/pull/5852#issuecomment-1561366742', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5852', 'id': 1561366742, 'node_id': 'IC_kwDODunzps5dEJDW', 'user': {'login': 'HuggingFaceDocBuilderDev', 'id': 99929124, 'node_id': 'U_kgDOBfTMJA', 'avatar_url': 'https://avatars.githubusercontent.com/u/99929124?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/HuggingFaceDocBuilderDev', 'html_url': 'https://github.com/HuggingFaceDocBuilderDev', 'followers_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/followers', 'following_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/following{/other_user}', 'gists_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/subscriptions', 'organizations_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/orgs', 'repos_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/repos', 'events_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/events{/privacy}', 'received_events_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-05-24T15:24:46Z', 'updated_at': '2023-06-13T15:57:38Z', 'author_association': 'NONE', 'body': '_The documentation is not available anymore as the PR was closed or merged._', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1561366742/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1561369891', 'html_url': 'https://github.com/huggingface/datasets/pull/5852#issuecomment-1561369891', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5852', 'id': 1561369891, 'node_id': 'IC_kwDODunzps5dEJ0j', 'user': {'login': 'github-actions[bot]', 'id': 41898282, 'node_id': 'MDM6Qm90NDE4OTgyODI=', 'avatar_url': 'https://avatars.githubusercontent.com/in/15368?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/github-actions%5Bbot%5D', 'html_url': 'https://github.com/apps/github-actions', 'followers_url': 'https://api.github.com/users/github-actions%5Bbot%5D/followers', 'following_url': 'https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}', 'gists_url': 'https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/github-actions%5Bbot%5D/subscriptions', 'organizations_url': 'https://api.github.com/users/github-actions%5Bbot%5D/orgs', 'repos_url': 'https://api.github.com/users/github-actions%5Bbot%5D/repos', 'events_url': 'https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}', 'received_events_url': 'https://api.github.com/users/github-actions%5Bbot%5D/received_events', 'type': 'Bot', 'site_admin': False}, 'created_at': '2023-05-24T15:26:48Z', 'updated_at': '2023-05-24T15:26:48Z', 'author_association': 'NONE', 'body': '<details>\n<summary>Show benchmarks</summary>\n\nPyArrow==8.0.0\n\n<details>\n<summary>Show updated benchmarks!</summary>\n\n### Benchmark: benchmark_array_xd.json\n\n| metric | read_batch_formatted_as_numpy after write_array2d | read_batch_formatted_as_numpy after write_flattened_sequence | read_batch_formatted_as_numpy after write_nested_sequence | read_batch_unformated after write_array2d | read_batch_unformated after write_flattened_sequence | read_batch_unformated after write_nested_sequence | read_col_formatted_as_numpy after write_array2d | read_col_formatted_as_numpy after write_flattened_sequence | read_col_formatted_as_numpy after write_nested_sequence | read_col_unformated after write_array2d | read_col_unformated after write_flattened_sequence | read_col_unformated after write_nested_sequence | read_formatted_as_numpy after write_array2d | read_formatted_as_numpy after write_flattened_sequence | read_formatted_as_numpy after write_nested_sequence | read_unformated after write_array2d | read_unformated after write_flattened_sequence | read_unformated after write_nested_sequence | write_array2d | write_flattened_sequence | write_nested_sequence |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.007183 / 0.011353 (-0.004169) | 0.004586 / 0.011008 (-0.006423) | 0.032668 / 0.038508 (-0.005840) | 0.040896 / 0.023109 (0.017787) | 0.358225 / 0.275898 (0.082327) | 0.395063 / 0.323480 (0.071583) | 0.004540 / 0.007986 (-0.003446) | 0.003849 / 0.004328 (-0.000480) | 0.005521 / 0.004250 (0.001271) | 0.053314 / 0.037052 (0.016262) | 0.362417 / 0.258489 (0.103928) | 0.414337 / 0.293841 (0.120496) | 0.030698 / 0.128546 (-0.097849) | 0.008823 / 0.075646 (-0.066823) | 0.303583 / 0.419271 (-0.115689) | 0.060277 / 0.043533 (0.016744) | 0.365938 / 0.255139 (0.110799) | 0.379554 / 0.283200 (0.096354) | 0.122545 / 0.141683 (-0.019138) | 1.712098 / 1.452155 (0.259943) | 1.802036 / 1.492716 (0.309319) |\n\n### Benchmark: benchmark_getitem\\_100B.json\n\n| metric | get_batch_of\\_1024\\_random_rows | get_batch_of\\_1024\\_rows | get_first_row | get_last_row |\n|--------|---|---|---|---|\n| new / old (diff) | 0.239508 / 0.018006 (0.221502) | 0.492194 / 0.000490 (0.491704) | 0.003280 / 0.000200 (0.003081) | 0.000096 / 0.000054 (0.000042) |\n\n### Benchmark: benchmark_indices_mapping.json\n\n| metric | select | shard | shuffle | sort | train_test_split |\n|--------|---|---|---|---|---|\n| new / old (diff) | 0.033301 / 0.037411 (-0.004110) | 0.125851 / 0.014526 (0.111325) | 0.137757 / 0.176557 (-0.038799) | 0.207603 / 0.737135 (-0.529533) | 0.143507 / 0.296338 (-0.152831) |\n\n### Benchmark: benchmark_iterating.json\n\n| metric | read 5000 | read 50000 | read_batch 50000 10 | read_batch 50000 100 | read_batch 50000 1000 | read_formatted numpy 5000 | read_formatted pandas 5000 | read_formatted tensorflow 5000 | read_formatted torch 5000 | read_formatted_batch numpy 5000 10 | read_formatted_batch numpy 5000 1000 | shuffled read 5000 | shuffled read 50000 | shuffled read_batch 50000 10 | shuffled read_batch 50000 100 | shuffled read_batch 50000 1000 | shuffled read_formatted numpy 5000 | shuffled read_formatted_batch numpy 5000 10 | shuffled read_formatted_batch numpy 5000 1000 |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.470662 / 0.215209 (0.255453) | 4.736017 / 2.077655 (2.658363) | 2.154152 / 1.504120 (0.650032) | 1.954243 / 1.541195 (0.413048) | 2.080186 / 1.468490 (0.611696) | 0.622884 / 4.584777 (-3.961893) | 4.385885 / 3.745712 (0.640173) | 2.262085 / 5.269862 (-3.007776) | 1.454215 / 4.565676 (-3.111462) | 0.067342 / 0.424275 (-0.356933) | 0.012913 / 0.007607 (0.005306) | 0.600676 / 0.226044 (0.374631) | 5.915093 / 2.268929 (3.646164) | 2.664915 / 55.444624 (-52.779709) | 2.286986 / 6.876477 (-4.589490) | 2.387776 / 2.142072 (0.245704) | 0.757067 / 4.805227 (-4.048160) | 0.154625 / 6.500664 (-6.346039) | 0.074632 / 0.075469 (-0.000838) |\n\n### Benchmark: benchmark_map_filter.json\n\n| metric | filter | map fast-tokenizer batched | map identity | map identity batched | map no-op batched | map no-op batched numpy | map no-op batched pandas | map no-op batched pytorch | map no-op batched tensorflow |\n|--------|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 1.413229 / 1.841788 (-0.428558) | 17.433012 / 8.074308 (9.358704) | 16.980340 / 10.191392 (6.788948) | 0.218943 / 0.680424 (-0.461481) | 0.020525 / 0.534201 (-0.513676) | 0.451847 / 0.579283 (-0.127436) | 0.495587 / 0.434364 (0.061223) | 0.548739 / 0.540337 (0.008402) | 0.662120 / 1.386936 (-0.724816) |\n\n</details>\nPyArrow==latest\n\n<details>\n<summary>Show updated benchmarks!</summary>\n\n### Benchmark: benchmark_array_xd.json\n\n| metric | read_batch_formatted_as_numpy after write_array2d | read_batch_formatted_as_numpy after write_flattened_sequence | read_batch_formatted_as_numpy after write_nested_sequence | read_batch_unformated after write_array2d | read_batch_unformated after write_flattened_sequence | read_batch_unformated after write_nested_sequence | read_col_formatted_as_numpy after write_array2d | read_col_formatted_as_numpy after write_flattened_sequence | read_col_formatted_as_numpy after write_nested_s

[{'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1545790902', 'html_url': 'https://github.com/huggingface/datasets/pull/5850#issuecomment-1545790902', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5850', 'id': 1545790902, 'node_id': 'IC_kwDODunzps5cIuW2', 'user': {'login': 'HuggingFaceDocBuilderDev', 'id': 99929124, 'node_id': 'U_kgDOBfTMJA', 'avatar_url': 'https://avatars.githubusercontent.com/u/99929124?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/HuggingFaceDocBuilderDev', 'html_url': 'https://github.com/HuggingFaceDocBuilderDev', 'followers_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/followers', 'following_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/following{/other_user}', 'gists_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/subscriptions', 'organizations_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/orgs', 'repos_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/repos', 'events_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/events{/privacy}', 'received_events_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-05-12T13:56:51Z', 'updated_at': '2023-05-12T13:56:51Z', 'author_association': 'NONE', 'body': 'The docs for this PR live [here](https://moon-ci-docs.huggingface.co/docs/datasets/pr_5850). All of your documentation changes will be reflected on that endpoint.', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1545790902/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1546048916', 'html_url': 'https://github.com/huggingface/datasets/pull/5850#issuecomment-1546048916', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5850', 'id': 1546048916, 'node_id': 'IC_kwDODunzps5cJtWU', 'user': {'login': 'albertvillanova', 'id': 8515462, 'node_id': 'MDQ6VXNlcjg1MTU0NjI=', 'avatar_url': 'https://avatars.githubusercontent.com/u/8515462?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/albertvillanova', 'html_url': 'https://github.com/albertvillanova', 'followers_url': 'https://api.github.com/users/albertvillanova/followers', 'following_url': 'https://api.github.com/users/albertvillanova/following{/other_user}', 'gists_url': 'https://api.github.com/users/albertvillanova/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/albertvillanova/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/albertvillanova/subscriptions', 'organizations_url': 'https://api.github.com/users/albertvillanova/orgs', 'repos_url': 'https://api.github.com/users/albertvillanova/repos', 'events_url': 'https://api.github.com/users/albertvillanova/events{/privacy}', 'received_events_url': 'https://api.github.com/users/albertvillanova/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-05-12T17:14:38Z', 'updated_at': '2023-05-12T17:20:15Z', 'author_association': 'MEMBER', 'body': 'Good idea. @mariosasko!!!\r\n\r\nPlease note that before this PR, the files are not evenly distributed for archives: `_generate_examples` gets a list of iterators, one for each archive (uncompressed to a directory).', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1546048916/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1547577229', 'html_url': 'https://github.com/huggingface/datasets/pull/5850#issuecomment-1547577229', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5850', 'id': 1547577229, 'node_id': 'IC_kwDODunzps5cPieN', 'user': {'login': 'lhoestq', 'id': 42851186, 'node_id': 'MDQ6VXNlcjQyODUxMTg2', 'avatar_url': 'https://avatars.githubusercontent.com/u/42851186?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/lhoestq', 'html_url': 'https://github.com/lhoestq', 'followers_url': 'https://api.github.com/users/lhoestq/followers', 'following_url': 'https://api.github.com/users/lhoestq/following{/other_user}', 'gists_url': 'https://api.github.com/users/lhoestq/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/lhoestq/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/lhoestq/subscriptions', 'organizations_url': 'https://api.github.com/users/lhoestq/orgs', 'repos_url': 'https://api.github.com/users/lhoestq/repos', 'events_url': 'https://api.github.com/users/lhoestq/events{/privacy}', 'received_events_url': 'https://api.github.com/users/lhoestq/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-05-15T10:12:15Z', 'updated_at': '2023-05-15T10:12:15Z', 'author_association': 'MEMBER', 'body': 'This change could create silent problems when loading files with extensions that are not listed here. For example\r\n\r\n```python\r\nload_dataset("text", data_files=["20230515.log"])\r\n```\r\n\r\nwouldn\'t even log anything to say that the file was ignored.\r\n\r\nMaybe it\'s possible to do this at data files patterns resolution ?\r\n\r\ne.g. in get_data_patterns_in_dataset_repository / get_data_patterns_locally we could return patterns that include the most common extension', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1547577229/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1549300668', 'html_url': 'https://github.com/huggingface/datasets/pull/5850#issuecomment-1549300668', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5850', 'id': 1549300668, 'node_id': 'IC_kwDODunzps5cWHO8', 'user': {'login': 'albertvillanova', 'id': 8515462, 'node_id': 'MDQ6VXNlcjg1MTU0NjI=', 'avatar_url': 'https://avatars.githubusercontent.com/u/8515462?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/albertvillanova', 'html_url': 'https://github.com/albertvillanova', 'followers_url': 'https://api.github.com/users/albertvillanova/followers', 'following_url': 'https://api.github.com/users/albertvillanova/following{/other_user}', 'gists_url': 'https://api.github.com/users/albertvillanova/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/albertvillanova/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/albertvillanova/subscriptions', 'organizations_url': 'https://api.github.com/users/albertvillanova/orgs', 'repos_url': 'https://api.github.com/users/albertvillanova/repos', 'events_url': 'https://api.github.com/users/albertvillanova/events{/privacy}', 'received_events_url': 'https://api.github.com/users/albertvillanova/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-05-16T09:17:24Z', 'updated_at': '2023-05-16T09:18:41Z', 'author_association': 'MEMBER', 'body': '@lhoestq the issue you evoke (.log files skipped by text builder if .log is not added to .txt as supported extension) persists whether you perform the skip at the pattern resolution or in the builder itself.\r\n\r\nThe solution is to add the .log extension (besides the .txt) as supported by text, independently of where we perform the skip (at pattern resolution or in the builder itself).\r\n\r\nAdditionally, at the time we call for pattern resolution, we do not know the builder class yet, so that we cannot pass specific file extensions. First we call data files pattern resolution, and afterwards we call `infer_module_for_data_files` and then know the builder class.', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1549300668/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1549622184', 'html_url': 'https://github.com/huggingface/datasets/pull/5850#issuecomment-1549622184', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5850', 'id': 1549622184, 'node_id': 'IC_kwDODunzps5cXVuo', 'user': {'login': 'lhoestq', 'id': 42851186, 'node_id': 'MDQ6VXNlcjQyODUxMTg2', 'avatar_url': 'https://avatars.githubusercontent.com/u/42851186?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/lhoestq', 'html_url': 'https://github.com/lhoestq', 'followers_url': 'https://api.github.com/users/lhoestq/followers', 'following_url': 'https://api.github.com/users/lhoestq/following{/other_user}', 'gists_url': 'https://api.github.com/users/lhoestq/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/lhoestq/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/lhoestq/subscriptions', 'organizations_url': 'https://api.github.com/users/lhoestq/orgs', 'repos_url': 'https://api.github.com/users/lhoestq/repos', 'events_url': 'https://api.github.com/users/lhoestq/events{/privacy}', 'received_events_url': 'https://api.github.com/users/lhoestq/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-05-16T13:02:17Z', 'updated_at': '2023-05-16T13:02:17Z', 'author_association': 'MEMBER', 'body': '> @lhoestq the issue you evoke (.log files skipped by text builder if .log is not added to .txt as supported extension) persists whether you perform the skip at the pattern resolution or in the builder itself.\r\n\r\nNo I simply think it\'s a bad breaking change to not support\r\n\r\n```python\r\nload_dataset("<builder_name>", data_files=["path/to/file_with_unknown_or_no_extension"])\r\n# or\r\nload_dataset("<builder_name>", data_files=["https://url.to/file_with_unknown_or_no_extension"])\r\n```\r\n\r\nIdk if it\'s the easiest solution, but maybe it\'s possible to do the change only when inferring the patterns of dataset repositories. This should avoid this breaking change.\r\n\r\nFor example it could do something like that in `get_data_patterns_locally`\r\n\r\n```python\r\n    Input:\r\n\r\n        my_dataset_repository/\r\n        ├── README.md\r\n        ├── banner.png\r\n        ├── data0.csv\r\n        ├── data1.csv\r\n        └── data2.csv\r\n\r\n    Output:\r\n\r\n        {"train": ["**.csv"]}\r\n```\r\n\r\ninstead of \r\n\r\n```python\r\n    Output:\r\n\r\n        {"train": ["**"]}\r\n```', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1549622184/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1549830365', 'html_url': 'https://github.com/huggingface/datasets/pull/5850#issuecomment-1549830365', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5850', 'id': 1549830365, 'node_id': 'IC_kwDODunzps5cYIjd', 'user': {'login': 'mariosasko', 'id': 47462742, 'node_id': 'MDQ6VXNlcjQ3NDYyNzQy', 'avatar_url': 'https://avatars.githubusercontent.com/u/47462742?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/mariosasko', 'html_url': 'https://github.com/mariosasko', 'followers_url': 'https://api.github.com/users/mariosasko/followers', 'following_url': 'https://api.github.com/users/mariosasko/following{/other_user}', 'gists_url': 'https://api.github.com/users/mariosasko/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/mariosasko/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/mariosasko/subscriptions', 'organizations_url': 'https://api.github.com/users/mariosasko/orgs', 'repos_url': 'https://api.github.com/users/mariosasko/repos', 'events_url': 'https://api.github.com/users/mariosasko/events{/privacy}', 'received_events_url': 'https://api.github.com/users/mariosasko/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-05-16T14:51:43Z', 'updated_at': '2023-05-16T14:51:43Z', 'author_association': 'CONTRIBUTOR', 'body': 'I agree with @lhoestq - it should still be possible to request parsing a file with a specific builder even if the file\'s extension is "invalid" for the builder, and only ignore non-supported file formats when inferring the patterns.', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1549830365/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1550740126', 'html_url': 'https://github.com/huggingface/datasets/pull/5850#issuecomment-1550740126', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5850', 'id': 1550740126, 'node_id': 'IC_kwDODunzps5cbmqe', 'user': {'login': 'albertvillanova', 'id': 8515462, 'node_id': 'MDQ6VXNlcjg1MTU0NjI=', 'avatar_url': 'https://avatars.githubusercontent.com/u/8515462?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/albertvillanova', 'html_url': 'https://github.com/albertvillanova', 'followers_url': 'https://api.github.com/users/albertvillanova/followers', 'following_url': 'https://api.github.com/users/albertvillanova/following{/other_user}', 'gists_url': 'https://api.github.com/users/albertvillanova/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/albertvillanova/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/albertvillanova/subscriptions', 'organizations_url': 'https://api.github.com/users/albertvillanova/orgs', 'repos_url': 'https://api.github.com/users/albertvillanova/repos', 'events_url': 'https://api.github.com/users/albertvillanova/events{/privacy}', 'received_events_url': 'https://api.github.com/users/albertvillanova/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-05-17T05:05:49Z', 'updated_at': '2023-05-17T05:14:39Z', 'author_association': 'MEMBER', 'body': 'Therefore, if I understand correctly, what you suggest is:\r\n- if the user passes a packaged builder to `load_dataset` (e.g. `load_dataset("csv",...`), then the *passed* `data_files` should not be filtered to remove unsupported extensions. No breaking change in this case\r\n- if the user passes a no-script repo/folder to `load_dataset` (e.g. `load_dataset("my_dataset_repository",...`), then the *inferred* data files should be filtered to remove the extensions that are not supported by the inferred module name builder\r\n  - if the user passes `data_files` as well, then I guess these should not be filtered, to avoid any breaking change as in the first case above', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1550740126/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1551276380', 'html_url': 'https://github.com/huggingface/datasets/pull/5850#issuecomment-1551276380', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5850', 'id': 1551276380, 'node_id': 'IC_kwDODunzps5cdplc', 'user': {'login': 'lhoestq', 'id': 42851186, 'node_id': 'MDQ6VXNlcjQyODUxMTg2', 'avatar_url': 'https://avatars.githubusercontent.com/u/42851186?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/lhoestq', 'html_url': 'https://github.com/lhoestq', 'followers_url': 'https://api.github.com/users/lhoestq/followers', 'following_url': 'https://api.github.com/users/lhoestq/following{/other_user}', 'gists_url': 'https://api.github.com/users/lhoestq/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/lhoestq/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/lhoestq/subscriptions', 'organizations_url': 'https://api.github.com/users/lhoestq/orgs', 'repos_url': 'https://api.github.com/users/lhoestq/repos', 'events_url': 'https://api.github.com/users/lhoestq/events{/privacy}', 'received_events_url': 'https://api.github.com/users/lhoestq/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-05-17T12:08:25Z', 'updated_at': '2023-05-17T12:08:25Z', 'author_association': 'MEMBER', 'body': 'Yes that would be ideal imo !', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1551276380/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1576599610', 'html_url': 'https://github.com/huggingface/datasets/pull/5850#issuecomment-1576599610', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5850', 'id': 1576599610, 'node_id': 'IC_kwDODunzps5d-QA6', 'user': {'login': 'albertvillanova', 'id': 8515462, 'node_id': 'MDQ6VXNlcjg1MTU0NjI=', 'avatar_url': 'https://avatars.githubusercontent.com/u/8515462?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/albertvillanova', 'html_url': 'https://github.com/albertvillanova', 'followers_url': 'https://api.github.com/users/albertvillanova/followers', 'following_url': 'https://api.github.com/users/albertvillanova/following{/other_user}', 'gists_url': 'https://api.github.com/users/albertvillanova/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/albertvillanova/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/albertvillanova/subscriptions', 'organizations_url': 'https://api.github.com/users/albertvillanova/orgs', 'repos_url': 'https://api.github.com/users/albertvillanova/repos', 'events_url': 'https://api.github.com/users/albertvillanova/events{/privacy}', 'received_events_url': 'https://api.github.com/users/albertvillanova/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-05T11:15:35Z', 'updated_at': '2023-06-05T11:15:35Z', 'author_association': 'MEMBER', 'body': 'I think this now fulfills all the requirements.', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1576599610/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1580280565', 'html_url': 'https://github.com/huggingface/datasets/pull/5850#issuecomment-1580280565', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5850', 'id': 1580280565, 'node_id': 'IC_kwDODunzps5eMSr1', 'user': {'login': 'lhoestq', 'id': 42851186, 'node_id': 'MDQ6VXNlcjQyODUxMTg2', 'avatar_url': 'https://avatars.githubusercontent.com/u/42851186?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/lhoestq', 'html_url': 'https://github.com/lhoestq', 'followers_url': 'https://api.github.com/users/lhoestq/followers', 'following_url': 'https://api.github.com/users/lhoestq/following{/other_user}', 'gists_url': 'https://api.github.com/users/lhoestq/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/lhoestq/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/lhoestq/subscriptions', 'organizations_url': 'https://api.github.com/users/lhoestq/orgs', 'repos_url': 'https://api.github.com/users/lhoestq/repos', 'events_url': 'https://api.github.com/users/lhoestq/events{/privacy}', '

[]

[{'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1544735245', 'html_url': 'https://github.com/huggingface/datasets/issues/5847#issuecomment-1544735245', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5847', 'id': 1544735245, 'node_id': 'IC_kwDODunzps5cEsoN', 'user': {'login': 'jlquinn', 'id': 826841, 'node_id': 'MDQ6VXNlcjgyNjg0MQ==', 'avatar_url': 'https://avatars.githubusercontent.com/u/826841?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/jlquinn', 'html_url': 'https://github.com/jlquinn', 'followers_url': 'https://api.github.com/users/jlquinn/followers', 'following_url': 'https://api.github.com/users/jlquinn/following{/other_user}', 'gists_url': 'https://api.github.com/users/jlquinn/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/jlquinn/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/jlquinn/subscriptions', 'organizations_url': 'https://api.github.com/users/jlquinn/orgs', 'repos_url': 'https://api.github.com/users/jlquinn/repos', 'events_url': 'https://api.github.com/users/jlquinn/events{/privacy}', 'received_events_url': 'https://api.github.com/users/jlquinn/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-05-11T21:54:15Z', 'updated_at': '2023-05-11T21:54:15Z', 'author_association': 'NONE', 'body': "I wasn't sure to file this against transformers or datasets.", 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1544735245/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1545902306', 'html_url': 'https://github.com/huggingface/datasets/issues/5847#issuecomment-1545902306', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5847', 'id': 1545902306, 'node_id': 'IC_kwDODunzps5cJJji', 'user': {'login': 'mariosasko', 'id': 47462742, 'node_id': 'MDQ6VXNlcjQ3NDYyNzQy', 'avatar_url': 'https://avatars.githubusercontent.com/u/47462742?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/mariosasko', 'html_url': 'https://github.com/mariosasko', 'followers_url': 'https://api.github.com/users/mariosasko/followers', 'following_url': 'https://api.github.com/users/mariosasko/following{/other_user}', 'gists_url': 'https://api.github.com/users/mariosasko/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/mariosasko/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/mariosasko/subscriptions', 'organizations_url': 'https://api.github.com/users/mariosasko/orgs', 'repos_url': 'https://api.github.com/users/mariosasko/repos', 'events_url': 'https://api.github.com/users/mariosasko/events{/privacy}', 'received_events_url': 'https://api.github.com/users/mariosasko/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-05-12T15:13:52Z', 'updated_at': '2023-05-12T15:14:25Z', 'author_association': 'CONTRIBUTOR', 'body': '[`KeyDataset`](https://github.com/huggingface/transformers/blob/7f8b909189547944617741d8d3c6c84504701693/src/transformers/pipelines/pt_utils.py#L296) doesn\'t support iterable datasets, so you either need to implement a version that does (and also indexing nested (translation) fields):\r\n\r\n```python\r\nfrom torch.utils.data import Dataset, IterableDataset\r\n\r\ndef build_key_fetcher(key: str):\r\n    def _key_fetcher(item):\r\n        for sub_key in key.split("."):\r\n            item = item[sub_key]\r\n        return item\r\n    return _key_fetcher\r\n\r\nclass KeyDataset(Dataset):\r\n    def __new__(cls, dataset: Dataset, key: str):\r\n        cls = _KeyIterableDataset if isinstance(dataset, IterableDataset) else _KeyMapDataset\r\n        self = object.__new__(cls)\r\n        self.dataset = dataset\r\n        self.key = key\r\n        self._key_fetcher = build_key_fetcher(key)\r\n        return self\r\n\r\nclass _KeyMapDataset(KeyDataset):\r\n    def __getitem__(self, i):\r\n        return self._key_fetcher(self.dataset[i])\r\n    \r\n    def __len__(self):\r\n        return len(self.dataset)\r\n\r\n\r\nclass _KeyIterableDataset(KeyDataset):\r\n    def __iter__(self):\r\n        for ex in self.dataset:\r\n            yield self._key_fetcher(ex)\r\n\r\nks = KeyDataset(ds, "translation.en")\r\n```\r\n\r\nor use `IterableDataset`\'s `map`:\r\n```python\r\ndef fetch_en_translation(ex):\r\n    return {"en": ex["translation"]["en"]}\r\nks = ds.map(fetch_en_translation, remove_columns=ds.column_names) \r\n```\r\n\r\ncc @sgugger: Perhaps the `KeyDataset` + PyTorch `IterableDataset` case should be supported by Transformers', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1545902306/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1546059845', 'html_url': 'https://github.com/huggingface/datasets/issues/5847#issuecomment-1546059845', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5847', 'id': 1546059845, 'node_id': 'IC_kwDODunzps5cJwBF', 'user': {'login': 'jlquinn', 'id': 826841, 'node_id': 'MDQ6VXNlcjgyNjg0MQ==', 'avatar_url': 'https://avatars.githubusercontent.com/u/826841?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/jlquinn', 'html_url': 'https://github.com/jlquinn', 'followers_url': 'https://api.github.com/users/jlquinn/followers', 'following_url': 'https://api.github.com/users/jlquinn/following{/other_user}', 'gists_url': 'https://api.github.com/users/jlquinn/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/jlquinn/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/jlquinn/subscriptions', 'organizations_url': 'https://api.github.com/users/jlquinn/orgs', 'repos_url': 'https://api.github.com/users/jlquinn/repos', 'events_url': 'https://api.github.com/users/jlquinn/events{/privacy}', 'received_events_url': 'https://api.github.com/users/jlquinn/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-05-12T17:24:37Z', 'updated_at': '2023-05-12T17:24:37Z', 'author_association': 'NONE', 'body': '@mariosasko The map snippet didn\'t quite work, but gave me enough of a clue to get it working.  The following snippet does work:\r\n```\r\ndef en_translation(x):\r\n    return {"en":x[\'translation\'][\'en\']}\r\nks = ds.map(en_translation, remove_columns=[\'translation\'])\r\ntest=[]\r\nfor x in iter(ks):\r\n    test.append(x[\'en\'])\r\nxx= mt(test)\r\nfor x in xx:\r\n    print(x)\r\n```\r\n\r\nI tried just returning `x[\'translation\'][\'en`]` in the helper function instead of the dict, but that didn\'t give me an iterator over strings that pipeline would work with either.\r\n\r\n\r\nThe snippet as is gives the following error:\r\n```\r\nTraceback (most recent call last):\r\n  File "/home/jlquinn/miniconda3/envs/watnlp/lib/python3.9/pdb.py", line 1704, in main\r\n    pdb._runscript(mainpyfile)\r\n  File "/home/jlquinn/miniconda3/envs/watnlp/lib/python3.9/pdb.py", line 1573, in _runscript\r\n    self.run(statement)\r\n  File "/home/jlquinn/miniconda3/envs/watnlp/lib/python3.9/bdb.py", line 580, in run\r\n    exec(cmd, globals, locals)\r\n  File "<string>", line 1, in <module>\r\n  File "/home/jlquinn/models/hf/ende.t5.pipe.py", line 1, in <module>\r\n    from transformers import pipeline\r\n  File "/home/jlquinn/miniconda3/envs/watnlp/lib/python3.9/site-packages/transformers/pipelines/text2text_generation.py", line 335, in __call__\r\n    return super().__call__(*args, **kwargs)\r\n  File "/home/jlquinn/miniconda3/envs/watnlp/lib/python3.9/site-packages/transformers/pipelines/text2text_generation.py", line 138, in __call__\r\n    result = super().__call__(*args, **kwargs)\r\n  File "/home/jlquinn/miniconda3/envs/watnlp/lib/python3.9/site-packages/transformers/pipelines/base.py", line 1027, in __call__\r\n    return self.run_single(inputs, preprocess_params, forward_params, postprocess_params)\r\n  File "/home/jlquinn/miniconda3/envs/watnlp/lib/python3.9/site-packages/transformers/pipelines/base.py", line 1033, in run_single\r\n    model_inputs = self.preprocess(inputs, **preprocess_params)\r\n  File "/home/jlquinn/miniconda3/envs/watnlp/lib/python3.9/site-packages/transformers/pipelines/text2text_generation.py", line 287, in preprocess\r\n    return super()._parse_and_tokenize(*args, truncation=truncation)\r\n  File "/home/jlquinn/miniconda3/envs/watnlp/lib/python3.9/site-packages/transformers/pipelines/text2text_generation.py", line 100, in _parse_and_tokenize\r\n    raise ValueError(\r\nValueError:  `args[0]`: <datasets.iterable_dataset.IterableDataset object at 0x7f5fd38ef1c0> have the wrong format. The should be either of type `str` or type `list`\r\nUncaught exception. Entering post mortem debugging\r\nRunning \'cont\' or \'step\' will restart the program\r\n```\r\n', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1546059845/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1546061154', 'html_url': 'https://github.com/huggingface/datasets/issues/5847#issuecomment-1546061154', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5847', 'id': 1546061154, 'node_id': 'IC_kwDODunzps5cJwVi', 'user': {'login': 'jlquinn', 'id': 826841, 'node_id': 'MDQ6VXNlcjgyNjg0MQ==', 'avatar_url': 'https://avatars.githubusercontent.com/u/826841?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/jlquinn', 'html_url': 'https://github.com/jlquinn', 'followers_url': 'https://api.github.com/users/jlquinn/followers', 'following_url': 'https://api.github.com/users/jlquinn/following{/other_user}', 'gists_url': 'https://api.github.com/users/jlquinn/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/jlquinn/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/jlquinn/subscriptions', 'organizations_url': 'https://api.github.com/users/jlquinn/orgs', 'repos_url': 'https://api.github.com/users/jlquinn/repos', 'events_url': 'https://api.github.com/users/jlquinn/events{/privacy}', 'received_events_url': 'https://api.github.com/users/jlquinn/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-05-12T17:25:56Z', 'updated_at': '2023-05-12T17:25:56Z', 'author_association': 'NONE', 'body': "So perhaps there's no bug exactly, but I would love to see two things:  1) improve the documentation to better understand what's really getting returned.  2) update the example provided of using transformer pipeline with a dataset to include the oddball case that translation appears to be.", 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1546061154/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1549666470', 'html_url': 'https://github.com/huggingface/datasets/issues/5847#issuecomment-1549666470', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5847', 'id': 1549666470, 'node_id': 'IC_kwDODunzps5cXgim', 'user': {'login': 'sgugger', 'id': 35901082, 'node_id': 'MDQ6VXNlcjM1OTAxMDgy', 'avatar_url': 'https://avatars.githubusercontent.com/u/35901082?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/sgugger', 'html_url': 'https://github.com/sgugger', 'followers_url': 'https://api.github.com/users/sgugger/followers', 'following_url': 'https://api.github.com/users/sgugger/following{/other_user}', 'gists_url': 'https://api.github.com/users/sgugger/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/sgugger/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/sgugger/subscriptions', 'organizations_url': 'https://api.github.com/users/sgugger/orgs', 'repos_url': 'https://api.github.com/users/sgugger/repos', 'events_url': 'https://api.github.com/users/sgugger/events{/privacy}', 'received_events_url': 'https://api.github.com/users/sgugger/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-05-16T13:21:03Z', 'updated_at': '2023-05-16T13:21:03Z', 'author_association': 'MEMBER', 'body': 'cc @Narsil ', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1549666470/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1549799951', 'html_url': 'https://github.com/huggingface/datasets/issues/5847#issuecomment-1549799951', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5847', 'id': 1549799951, 'node_id': 'IC_kwDODunzps5cYBIP', 'user': {'login': 'Narsil', 'id': 204321, 'node_id': 'MDQ6VXNlcjIwNDMyMQ==', 'avatar_url': 'https://avatars.githubusercontent.com/u/204321?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/Narsil', 'html_url': 'https://github.com/Narsil', 'followers_url': 'https://api.github.com/users/Narsil/followers', 'following_url': 'https://api.github.com/users/Narsil/following{/other_user}', 'gists_url': 'https://api.github.com/users/Narsil/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/Narsil/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/Narsil/subscriptions', 'organizations_url': 'https://api.github.com/users/Narsil/orgs', 'repos_url': 'https://api.github.com/users/Narsil/repos', 'events_url': 'https://api.github.com/users/Narsil/events{/privacy}', 'received_events_url': 'https://api.github.com/users/Narsil/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-05-16T14:34:02Z', 'updated_at': '2023-05-16T14:34:02Z', 'author_association': 'CONTRIBUTOR', 'body': 'Hi,\r\n\r\nfor the original snippet, the issue is that `streaming` datasets are not countable (they have no len) and therefore `KeyDataset` cannot work with them ( KeyDataset is a dataset and therefore requires a length).\r\n\r\nI modified slightly the original snippet to make it work:\r\n\r\n```python\r\nfrom transformers import pipeline\r\nfrom transformers.pipelines.pt_utils import KeyDataset\r\nfrom datasets import load_dataset\r\n\r\nds = load_dataset(path="wmt14", name="fr-en", split="test", streaming=True)\r\nbs = 1\r\nmt = pipeline(\r\n    "translation_en_to_fr", model="hf-internal-testing/tiny-random-T5ForConditionalGeneration", batch_size=bs\r\n)\r\n\r\n\r\ndef ks(ds):\r\n    for item in ds:\r\n        yield item["translation"]["en"]\r\n\r\n\r\n# print(f"{ks}")\r\nxx = mt(ks(ds))\r\nfor x in xx:\r\n    print(x)\r\n```\r\n\r\nThis is what the first example in the docs suggests to use (as it\'s the most flexible): https://huggingface.co/docs/transformers/v4.29.1/en/pipeline_tutorial#using-pipelines-on-a-dataset\r\n\r\n`KeyDataset` really exists only to get a `sized` dataset to work nicer with `tqdm` for instance.\r\n\r\n@sgugger should we update the docs to remove `KeyDataset` entirely ? (We can add a note to pass manually the length of the data to tqdm so that the progress bar option can still be easy to use ?)\r\n', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1549799951/reactions', 'total_count': 1, '+1': 1, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1549816793', 'html_url': 'https://github.com/huggingface/datasets/issues/5847#issuecomment-1549816793', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5847', 'id': 1549816793, 'node_id': 'IC_kwDODunzps5cYFPZ', 'user': {'login': 'sgugger', 'id': 35901082, 'node_id': 'MDQ6VXNlcjM1OTAxMDgy', 'avatar_url': 'https://avatars.githubusercontent.com/u/35901082?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/sgugger', 'html_url': 'https://github.com/sgugger', 'followers_url': 'https://api.github.com/users/sgugger/followers', 'following_url': 'https://api.github.com/users/sgugger/following{/other_user}', 'gists_url': 'https://api.github.com/users/sgugger/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/sgugger/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/sgugger/subscriptions', 'organizations_url': 'https://api.github.com/users/sgugger/orgs', 'repos_url': 'https://api.github.com/users/sgugger/repos', 'events_url': 'https://api.github.com/users/sgugger/events{/privacy}', 'received_events_url': 'https://api.github.com/users/sgugger/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-05-16T14:44:02Z', 'updated_at': '2023-05-16T14:44:02Z', 'author_association': 'MEMBER', 'body': "Maybe moving `KeyDataset` later on in the guide and specify it's mostly for streaming then? Or is it also necessary for batch_size>1 (which is what the current doc implies)?", 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1549816793/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1549887607', 'html_url': 'https://github.com/huggingface/datasets/issues/5847#issuecomment-1549887607', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5847', 'id': 1549887607, 'node_id': 'IC_kwDODunzps5cYWh3', 'user': {'login': 'Narsil', 'id': 204321, 'node_id': 'MDQ6VXNlcjIwNDMyMQ==', 'avatar_url': 'https://avatars.githubusercontent.com/u/204321?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/Narsil', 'html_url': 'https://github.com/Narsil', 'followers_url': 'https://api.github.com/users/Narsil/followers', 'following_url': 'https://api.github.com/users/Narsil/following{/other_user}', 'gists_url': 'https://api.github.com/users/Narsil/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/Narsil/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/Narsil/subscriptions', 'organizations_url': 'https://api.github.com/users/Narsil/orgs', 'repos_url': 'https://api.github.com/users/Narsil/repos', 'events_url': 'https://api.github.com/users/Narsil/events{/privacy}', 'received_events_url': 'https://api.github.com/users/Narsil/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-05-16T15:23:39Z', 'updated_at': '2023-05-16T15:59:55Z', 'author_association': 'CONTRIBUTOR', 'body': "Hmm\r\n\r\nIterator (`yield`) :\r\n- Not countable\r\n- Super flexible\r\n- Cannot use `num_workers>1` (threading requires indexing at the correct location, iterators require to iterate in order,so each thread would iterate over the full thing being genuinely a bad idea)\r\n- Can batch\r\n- tqdm doesn't show a nice progress bar (it has no total)\r\n\r\nKeyDataset (Or any PyTorch like Dataset returning the correct object for the pipeline):\r\n- Countable\r\n- Less flexible (not applicable to datasets with streaming), can only work on single keys. But should be easy to read and write your own (like @mariosasko did)\r\n- Works with  `num_workers > 1` (Every worker can fetch exactly what's needed)\r\n- Can batch \r\n- tqdm shows a nice progress bar\r\n\r\nIn the docs, if we update all the examples to use iterators, and include an example with\r\n\r\n```\r\nfor item in tqdm.tqdm(pipe(iterator(), total=len(dataset))))\r\n```\r\n\r\nWe can save the biggest feature that doesn't wor

[]
[{'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1545834996', 'html_url': 'https://github.com/huggingface/datasets/issues/5846#issuecomment-1545834996', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5846', 'id': 1545834996, 'node_id': 'IC_kwDODunzps5cI5H0', 'user': {'login': 'mariosasko', 'id': 47462742, 'node_id': 'MDQ6VXNlcjQ3NDYyNzQy', 'avatar_url': 'https://avatars.githubusercontent.com/u/47462742?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/mariosasko', 'html_url': 'https://github.com/mariosasko', 'followers_url': 'https://api.github.com/users/mariosasko/followers', 'following_url': 'https://api.github.com/users/mariosasko/following{/other_user}', 'gists_url': 'https://api.github.com/users/mariosasko/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/mariosasko/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/mariosasko/subscriptions', 'organizations_url': 'https://api.github.com/users/mariosasko/orgs', 'repos_url': 'https://api.github.com/users/mariosasko/repos', 'events_url': 'https://api.github.com/users/mariosasko/events{/privacy}', 'received_events_url': 'https://api.github.com/users/mariosasko/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-05-12T14:28:15Z', 'updated_at': '2023-05-12T14:28:23Z', 'author_association': 'CONTRIBUTOR', 'body': "This is due to the slow resolution of the data files: https://github.com/huggingface/datasets/issues/5537.\r\n\r\nWe plan to switch to `huggingface_hub`'s `HfFileSystem` soon to make the resolution faster (will be up to 20x faster once we merge https://github.com/huggingface/huggingface_hub/pull/1443)\r\n\r\n", 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1545834996/reactions', 'total_count': 2, '+1': 1, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 1}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1547214281', 'html_url': 'https://github.com/huggingface/datasets/issues/5846#issuecomment-1547214281', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5846', 'id': 1547214281, 'node_id': 'IC_kwDODunzps5cOJ3J', 'user': {'login': 'enze5088', 'id': 14285786, 'node_id': 'MDQ6VXNlcjE0Mjg1Nzg2', 'avatar_url': 'https://avatars.githubusercontent.com/u/14285786?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/enze5088', 'html_url': 'https://github.com/enze5088', 'followers_url': 'https://api.github.com/users/enze5088/followers', 'following_url': 'https://api.github.com/users/enze5088/following{/other_user}', 'gists_url': 'https://api.github.com/users/enze5088/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/enze5088/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/enze5088/subscriptions', 'organizations_url': 'https://api.github.com/users/enze5088/orgs', 'repos_url': 'https://api.github.com/users/enze5088/repos', 'events_url': 'https://api.github.com/users/enze5088/events{/privacy}', 'received_events_url': 'https://api.github.com/users/enze5088/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-05-15T05:27:12Z', 'updated_at': '2023-05-15T05:27:12Z', 'author_association': 'NONE', 'body': "You're right, when I try to parse more than 50GB of text data, I also get very slow, usually taking hours or even tens of hours.", 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1547214281/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1548047064', 'html_url': 'https://github.com/huggingface/datasets/issues/5846#issuecomment-1548047064', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5846', 'id': 1548047064, 'node_id': 'IC_kwDODunzps5cRVLY', 'user': {'login': 'tbenthompson', 'id': 4241811, 'node_id': 'MDQ6VXNlcjQyNDE4MTE=', 'avatar_url': 'https://avatars.githubusercontent.com/u/4241811?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/tbenthompson', 'html_url': 'https://github.com/tbenthompson', 'followers_url': 'https://api.github.com/users/tbenthompson/followers', 'following_url': 'https://api.github.com/users/tbenthompson/following{/other_user}', 'gists_url': 'https://api.github.com/users/tbenthompson/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/tbenthompson/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/tbenthompson/subscriptions', 'organizations_url': 'https://api.github.com/users/tbenthompson/orgs', 'repos_url': 'https://api.github.com/users/tbenthompson/repos', 'events_url': 'https://api.github.com/users/tbenthompson/events{/privacy}', 'received_events_url': 'https://api.github.com/users/tbenthompson/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-05-15T15:07:34Z', 'updated_at': '2023-05-15T15:07:34Z', 'author_association': 'NONE', 'body': "> You're right, when I try to parse more than 50GB of text data, I also get very slow, usually taking hours or even tens of hours.\r\n\r\nThat's unrelated to the problem discussed in this issue. ", 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1548047064/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1548921076', 'html_url': 'https://github.com/huggingface/datasets/issues/5846#issuecomment-1548921076', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5846', 'id': 1548921076, 'node_id': 'IC_kwDODunzps5cUqj0', 'user': {'login': 'enze5088', 'id': 14285786, 'node_id': 'MDQ6VXNlcjE0Mjg1Nzg2', 'avatar_url': 'https://avatars.githubusercontent.com/u/14285786?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/enze5088', 'html_url': 'https://github.com/enze5088', 'followers_url': 'https://api.github.com/users/enze5088/followers', 'following_url': 'https://api.github.com/users/enze5088/following{/other_user}', 'gists_url': 'https://api.github.com/users/enze5088/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/enze5088/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/enze5088/subscriptions', 'organizations_url': 'https://api.github.com/users/enze5088/orgs', 'repos_url': 'https://api.github.com/users/enze5088/repos', 'events_url': 'https://api.github.com/users/enze5088/events{/privacy}', 'received_events_url': 'https://api.github.com/users/enze5088/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-05-16T03:23:46Z', 'updated_at': '2023-05-16T03:23:46Z', 'author_association': 'NONE', 'body': "> > You're right, when I try to parse more than 50GB of text data, I also get very slow, usually taking hours or even tens of hours.\r\n> \r\n> That's unrelated to the problem discussed in this issue.\r\n\r\nSorry, I misunderstood it.", 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1548921076/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}]

[]
[{'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1547639709', 'html_url': 'https://github.com/huggingface/datasets/issues/5841#issuecomment-1547639709', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5841', 'id': 1547639709, 'node_id': 'IC_kwDODunzps5cPxud', 'user': {'login': 'lhoestq', 'id': 42851186, 'node_id': 'MDQ6VXNlcjQyODUxMTg2', 'avatar_url': 'https://avatars.githubusercontent.com/u/42851186?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/lhoestq', 'html_url': 'https://github.com/lhoestq', 'followers_url': 'https://api.github.com/users/lhoestq/followers', 'following_url': 'https://api.github.com/users/lhoestq/following{/other_user}', 'gists_url': 'https://api.github.com/users/lhoestq/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/lhoestq/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/lhoestq/subscriptions', 'organizations_url': 'https://api.github.com/users/lhoestq/orgs', 'repos_url': 'https://api.github.com/users/lhoestq/repos', 'events_url': 'https://api.github.com/users/lhoestq/events{/privacy}', 'received_events_url': 'https://api.github.com/users/lhoestq/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-05-15T10:59:11Z', 'updated_at': '2023-05-15T11:16:18Z', 'author_association': 'MEMBER', 'body': 'Hi ! You can try to use the [Image](https://huggingface.co/docs/datasets/v2.12.0/en/package_reference/main_classes#datasets.Image) type which [decodes images on-the-fly](https://huggingface.co/docs/datasets/v2.12.0/en/about_dataset_features#image-feature) into pytorch tensors :)\r\n\r\n```python\r\nds = Dataset.from_dict({"tensor":a}).with_format("torch")\r\n%time sum(1 for _ in ds)\r\n# CPU times: user 5.04 s, sys: 96.5 ms, total: 5.14 s\r\n# Wall time: 5.14 s\r\n# 10000\r\n```\r\n\r\n```python\r\nfeatures = Features({"tensor": Image()})\r\nds = Dataset.from_dict({"tensor":a}, features=features).with_format("torch")\r\n%time sum(1 for _ in ds)\r\n# CPU times: user 1.86 s, sys: 49 ms, total: 1.91 s\r\n# Wall time: 1.9 s\r\n# 10000\r\n```\r\n\r\n-> Speed x2.7\r\n\r\nAnd if you want to keep using arrays of integers, consider using the [Array2D](https://huggingface.co/docs/datasets/v2.12.0/en/package_reference/main_classes#datasets.Array2D) or [Array3D](https://huggingface.co/docs/datasets/v2.12.0/en/package_reference/main_classes#datasets.Array3D) types which are even faster (since it doesn\'t decode images):\r\n\r\n```python\r\nfeatures = Features({"tensor": Array2D(shape=(100, 224), dtype="float32")})\r\nds = Dataset.from_dict({"tensor":a}, features=features).with_format("torch")\r\n%time sum(1 for _ in ds)\r\n# CPU times: user 828 ms, sys: 68.4 ms, total: 896 ms\r\n# Wall time: 897 ms\r\n# 10000\r\n```\r\n\r\n-> Speed x5.7\r\n\r\nBatching also speeds up a lot\r\n\r\n```python\r\nfrom torch.utils.data import DataLoader\r\ndl = DataLoader(ds, batch_size=100)\r\n%time sum(1 for _ in dl)\r\n# CPU times: user 564 ms, sys: 83.5 ms, total: 648 ms\r\n# Wall time: 579 ms\r\n# 100\r\n```\r\n\r\n-> Speed x8.9\r\n\r\n```python\r\n%time sum(1 for _ in ds.iter(batch_size=100))\r\n# CPU times: user 119 ms, sys: 96.8 ms, total: 215 ms\r\n# Wall time: 117 ms\r\n# 100\r\n```\r\n\r\n-> Speed x46', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1547639709/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1547644879', 'html_url': 'https://github.com/huggingface/datasets/issues/5841#issuecomment-1547644879', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5841', 'id': 1547644879, 'node_id': 'IC_kwDODunzps5cPy_P', 'user': {'login': 'lhoestq', 'id': 42851186, 'node_id': 'MDQ6VXNlcjQyODUxMTg2', 'avatar_url': 'https://avatars.githubusercontent.com/u/42851186?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/lhoestq', 'html_url': 'https://github.com/lhoestq', 'followers_url': 'https://api.github.com/users/lhoestq/followers', 'following_url': 'https://api.github.com/users/lhoestq/following{/other_user}', 'gists_url': 'https://api.github.com/users/lhoestq/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/lhoestq/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/lhoestq/subscriptions', 'organizations_url': 'https://api.github.com/users/lhoestq/orgs', 'repos_url': 'https://api.github.com/users/lhoestq/repos', 'events_url': 'https://api.github.com/users/lhoestq/events{/privacy}', 'received_events_url': 'https://api.github.com/users/lhoestq/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-05-15T11:02:17Z', 'updated_at': '2023-05-15T11:02:17Z', 'author_association': 'MEMBER', 'body': 'Anyway, regarding the speed difference between numpy and pytorch, I think the issue is that we first convert numpy sub-arrays to pytorch and then consolidate into one tensor, while we should to the opposite. Indeed converting a numpy array to pytorch has a fix cost that seems to cause a slow down. The current pipeline is\r\n\r\n```\r\narrow -> nested numpy arrays -> lists of torch tensors -> one torch tensor\r\n```\r\n\r\nand we should do\r\n\r\n```\r\narrow -> nested numpy arrays -> one numpy array -> one torch tensor\r\n```', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1547644879/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1548092666', 'html_url': 'https://github.com/huggingface/datasets/issues/5841#issuecomment-1548092666', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5841', 'id': 1548092666, 'node_id': 'IC_kwDODunzps5cRgT6', 'user': {'login': 'crisostomi', 'id': 51738205, 'node_id': 'MDQ6VXNlcjUxNzM4MjA1', 'avatar_url': 'https://avatars.githubusercontent.com/u/51738205?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/crisostomi', 'html_url': 'https://github.com/crisostomi', 'followers_url': 'https://api.github.com/users/crisostomi/followers', 'following_url': 'https://api.github.com/users/crisostomi/following{/other_user}', 'gists_url': 'https://api.github.com/users/crisostomi/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/crisostomi/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/crisostomi/subscriptions', 'organizations_url': 'https://api.github.com/users/crisostomi/orgs', 'repos_url': 'https://api.github.com/users/crisostomi/repos', 'events_url': 'https://api.github.com/users/crisostomi/events{/privacy}', 'received_events_url': 'https://api.github.com/users/crisostomi/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-05-15T15:34:59Z', 'updated_at': '2023-05-15T15:35:14Z', 'author_association': 'NONE', 'body': 'I have a similar issue: iterating over a dataset takes 5s without applying any transform, but takes ~30s after applying a transform.\r\nHere is the minimum code to reproduce the problem\r\n\r\n```python\r\nimport numpy as np\r\nfrom datasets import Dataset, DatasetDict, load_dataset, Array3D, Image, Features\r\nfrom torch.utils.data import DataLoader\r\nfrom tqdm import tqdm\r\nimport torchvision \r\nfrom torchvision.transforms import ToTensor, Normalize\r\n\r\n\r\n#################################\r\n# Without transform\r\n#################################\r\n    \r\ntrain_dataset = load_dataset(\r\n    \'cifar100\',\r\n    split=\'train\',\r\n    use_auth_token=True,\r\n)\r\n\r\ntrain_dataset.set_format(type="numpy", columns=["img", "fine_label"])\r\n\r\ntrain_loader= DataLoader(\r\n    train_dataset,\r\n    batch_size=100,\r\n    pin_memory=False,\r\n    shuffle=True,\r\n    num_workers=8,\r\n)\r\n\r\nfor batch in tqdm(train_loader, desc="Loading data, no transform"):\r\n    pass\r\n\r\n\r\n#################################\r\n# With transform\r\n#################################\r\n\r\ntransform_func = torchvision.transforms.Compose([\r\n    ToTensor(), \r\n    Normalize(mean=[0.485, 0.456, 0.406], std= [0.229, 0.224, 0.225]),]          \r\n)\r\n    \r\ntrain_dataset = train_dataset.map(\r\n    desc=f"Preprocessing samples",\r\n    function=lambda x: {"img": transform_func(x["img"])},\r\n)\r\n\r\ntrain_dataset.set_format(type="numpy", columns=["img", "fine_label"])\r\n\r\n\r\ntrain_loader= DataLoader(\r\n    train_dataset,\r\n    batch_size=100,\r\n    pin_memory=False,\r\n    shuffle=True,\r\n    num_workers=8,\r\n)\r\n\r\n\r\nfor batch in tqdm(train_loader, desc="Loading data after transform"):\r\n    pass \r\n```\r\n\r\nI have also tried converting the Image column to an Array3D\r\n```python\r\nimg_shape = train_dataset[0]["img"].shape\r\n\r\nfeatures = train_dataset.features.copy()\r\nfeatures["x"] = Array3D(shape=img_shape, dtype="float32")\r\n\r\ntrain_dataset = train_dataset.map(\r\n    desc=f"Preprocessing samples",\r\n    function=lambda x: {"x": np.array(x["img"], dtype=np.uint8)},\r\n    features=features,\r\n)\r\ntrain_dataset.cast_column("x", Array3D(shape=img_shape, dtype="float32"))\r\ntrain_dataset.set_format(type="numpy", columns=["x", "fine_label"])\r\n```\r\nbut to no avail. Any clue?', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1548092666/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1548098841', 'html_url': 'https://github.com/huggingface/datasets/issues/5841#issuecomment-1548098841', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5841', 'id': 1548098841, 'node_id': 'IC_kwDODunzps5cRh0Z', 'user': {'login': 'fecet', 'id': 41792945, 'node_id': 'MDQ6VXNlcjQxNzkyOTQ1', 'avatar_url': 'https://avatars.githubusercontent.com/u/41792945?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/fecet', 'html_url': 'https://github.com/fecet', 'followers_url': 'https://api.github.com/users/fecet/followers', 'following_url': 'https://api.github.com/users/fecet/following{/other_user}', 'gists_url': 'https://api.github.com/users/fecet/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/fecet/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/fecet/subscriptions', 'organizations_url': 'https://api.github.com/users/fecet/orgs', 'repos_url': 'https://api.github.com/users/fecet/repos', 'events_url': 'https://api.github.com/users/fecet/events{/privacy}', 'received_events_url': 'https://api.github.com/users/fecet/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-05-15T15:38:12Z', 'updated_at': '2023-05-15T15:38:12Z', 'author_association': 'NONE', 'body': 'Thanks! I convert my dataset feature to Array3D and this speed became awesome!', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1548098841/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}]

[{'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1544419618', 'html_url': 'https://github.com/huggingface/datasets/issues/5840#issuecomment-1544419618', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5840', 'id': 1544419618, 'node_id': 'IC_kwDODunzps5cDfki', 'user': {'login': 'mariosasko', 'id': 47462742, 'node_id': 'MDQ6VXNlcjQ3NDYyNzQy', 'avatar_url': 'https://avatars.githubusercontent.com/u/47462742?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/mariosasko', 'html_url': 'https://github.com/mariosasko', 'followers_url': 'https://api.github.com/users/mariosasko/followers', 'following_url': 'https://api.github.com/users/mariosasko/following{/other_user}', 'gists_url': 'https://api.github.com/users/mariosasko/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/mariosasko/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/mariosasko/subscriptions', 'organizations_url': 'https://api.github.com/users/mariosasko/orgs', 'repos_url': 'https://api.github.com/users/mariosasko/repos', 'events_url': 'https://api.github.com/users/mariosasko/events{/privacy}', 'received_events_url': 'https://api.github.com/users/mariosasko/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-05-11T17:39:41Z', 'updated_at': '2023-05-11T17:39:41Z', 'author_association': 'CONTRIBUTOR', 'body': "Please report this in the `transformers` repo, as it's not related to `datasets`", 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1544419618/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}]
[{'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1543724471', 'html_url': 'https://github.com/huggingface/datasets/issues/5842#issuecomment-1543724471', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5842', 'id': 1543724471, 'node_id': 'IC_kwDODunzps5cA123', 'user': {'login': 'amyeroberts', 'id': 22614925, 'node_id': 'MDQ6VXNlcjIyNjE0OTI1', 'avatar_url': 'https://avatars.githubusercontent.com/u/22614925?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/amyeroberts', 'html_url': 'https://github.com/amyeroberts', 'followers_url': 'https://api.github.com/users/amyeroberts/followers', 'following_url': 'https://api.github.com/users/amyeroberts/following{/other_user}', 'gists_url': 'https://api.github.com/users/amyeroberts/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/amyeroberts/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/amyeroberts/subscriptions', 'organizations_url': 'https://api.github.com/users/amyeroberts/orgs', 'repos_url': 'https://api.github.com/users/amyeroberts/repos', 'events_url': 'https://api.github.com/users/amyeroberts/events{/privacy}', 'received_events_url': 'https://api.github.com/users/amyeroberts/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-05-11T10:14:41Z', 'updated_at': '2023-05-11T10:14:41Z', 'author_association': 'CONTRIBUTOR', 'body': "Transferring this issue as it's related to the 🤗 Datasets library ", 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1543724471/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1544079859', 'html_url': 'https://github.com/huggingface/datasets/issues/5842#issuecomment-1544079859', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5842', 'id': 1544079859, 'node_id': 'IC_kwDODunzps5cCMnz', 'user': {'login': 'Bearnardd', 'id': 43574448, 'node_id': 'MDQ6VXNlcjQzNTc0NDQ4', 'avatar_url': 'https://avatars.githubusercontent.com/u/43574448?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/Bearnardd', 'html_url': 'https://github.com/Bearnardd', 'followers_url': 'https://api.github.com/users/Bearnardd/followers', 'following_url': 'https://api.github.com/users/Bearnardd/following{/other_user}', 'gists_url': 'https://api.github.com/users/Bearnardd/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/Bearnardd/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/Bearnardd/subscriptions', 'organizations_url': 'https://api.github.com/users/Bearnardd/orgs', 'repos_url': 'https://api.github.com/users/Bearnardd/repos', 'events_url': 'https://api.github.com/users/Bearnardd/events{/privacy}', 'received_events_url': 'https://api.github.com/users/Bearnardd/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-05-11T14:23:45Z', 'updated_at': '2023-05-11T14:23:45Z', 'author_association': 'NONE', 'body': 'Hi @surya-narayanan! Could you provide some code snippet?', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1544079859/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1544412685', 'html_url': 'https://github.com/huggingface/datasets/issues/5842#issuecomment-1544412685', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5842', 'id': 1544412685, 'node_id': 'IC_kwDODunzps5cDd4N', 'user': {'login': 'mariosasko', 'id': 47462742, 'node_id': 'MDQ6VXNlcjQ3NDYyNzQy', 'avatar_url': 'https://avatars.githubusercontent.com/u/47462742?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/mariosasko', 'html_url': 'https://github.com/mariosasko', 'followers_url': 'https://api.github.com/users/mariosasko/followers', 'following_url': 'https://api.github.com/users/mariosasko/following{/other_user}', 'gists_url': 'https://api.github.com/users/mariosasko/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/mariosasko/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/mariosasko/subscriptions', 'organizations_url': 'https://api.github.com/users/mariosasko/orgs', 'repos_url': 'https://api.github.com/users/mariosasko/repos', 'events_url': 'https://api.github.com/users/mariosasko/events{/privacy}', 'received_events_url': 'https://api.github.com/users/mariosasko/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-05-11T17:35:16Z', 'updated_at': '2023-05-11T17:35:16Z', 'author_association': 'CONTRIBUTOR', 'body': "This method has been recently added to the `IterableDataset`, so you need to update the `datasets`' installation (`pip install -U datasets`) to use it.", 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1544412685/reactions', 'total_count': 2, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 2, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}]
[{'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1543727901', 'html_url': 'https://github.com/huggingface/datasets/issues/5843#issuecomment-1543727901', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5843', 'id': 1543727901, 'node_id': 'IC_kwDODunzps5cA2sd', 'user': {'login': 'amyeroberts', 'id': 22614925, 'node_id': 'MDQ6VXNlcjIyNjE0OTI1', 'avatar_url': 'https://avatars.githubusercontent.com/u/22614925?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/amyeroberts', 'html_url': 'https://github.com/amyeroberts', 'followers_url': 'https://api.github.com/users/amyeroberts/followers', 'following_url': 'https://api.github.com/users/amyeroberts/following{/other_user}', 'gists_url': 'https://api.github.com/users/amyeroberts/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/amyeroberts/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/amyeroberts/subscriptions', 'organizations_url': 'https://api.github.com/users/amyeroberts/orgs', 'repos_url': 'https://api.github.com/users/amyeroberts/repos', 'events_url': 'https://api.github.com/users/amyeroberts/events{/privacy}', 'received_events_url': 'https://api.github.com/users/amyeroberts/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-05-11T10:17:28Z', 'updated_at': '2023-05-11T10:17:28Z', 'author_association': 'CONTRIBUTOR', 'body': 'Transferring as this is relating to the 🤗 Datasets library', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1543727901/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1544427971', 'html_url': 'https://github.com/huggingface/datasets/issues/5843#issuecomment-1544427971', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5843', 'id': 1544427971, 'node_id': 'IC_kwDODunzps5cDhnD', 'user': {'login': 'mariosasko', 'id': 47462742, 'node_id': 'MDQ6VXNlcjQ3NDYyNzQy', 'avatar_url': 'https://avatars.githubusercontent.com/u/47462742?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/mariosasko', 'html_url': 'https://github.com/mariosasko', 'followers_url': 'https://api.github.com/users/mariosasko/followers', 'following_url': 'https://api.github.com/users/mariosasko/following{/other_user}', 'gists_url': 'https://api.github.com/users/mariosasko/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/mariosasko/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/mariosasko/subscriptions', 'organizations_url': 'https://api.github.com/users/mariosasko/orgs', 'repos_url': 'https://api.github.com/users/mariosasko/repos', 'events_url': 'https://api.github.com/users/mariosasko/events{/privacy}', 'received_events_url': 'https://api.github.com/users/mariosasko/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-05-11T17:45:51Z', 'updated_at': '2023-05-11T17:45:51Z', 'author_association': 'CONTRIBUTOR', 'body': 'You need to use `IterableDatasetDict` instead of `DatasetDict` for iterable datasets.', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1544427971/reactions', 'total_count': 1, '+1': 1, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}]

[]

[{'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1542115470', 'html_url': 'https://github.com/huggingface/datasets/issues/5837#issuecomment-1542115470', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5837', 'id': 1542115470, 'node_id': 'IC_kwDODunzps5b6tCO', 'user': {'login': 'lhoestq', 'id': 42851186, 'node_id': 'MDQ6VXNlcjQyODUxMTg2', 'avatar_url': 'https://avatars.githubusercontent.com/u/42851186?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/lhoestq', 'html_url': 'https://github.com/lhoestq', 'followers_url': 'https://api.github.com/users/lhoestq/followers', 'following_url': 'https://api.github.com/users/lhoestq/following{/other_user}', 'gists_url': 'https://api.github.com/users/lhoestq/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/lhoestq/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/lhoestq/subscriptions', 'organizations_url': 'https://api.github.com/users/lhoestq/orgs', 'repos_url': 'https://api.github.com/users/lhoestq/repos', 'events_url': 'https://api.github.com/users/lhoestq/events{/privacy}', 'received_events_url': 'https://api.github.com/users/lhoestq/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-05-10T12:23:48Z', 'updated_at': '2023-05-10T12:23:48Z', 'author_association': 'MEMBER', 'body': 'Hi ! Doing `load_dataset("path/to/data.csv")` is not supported yet, but you can do\r\n\r\n```python\r\nds =  load_dataset("csv", data_files=["path/to/data.csv"])\r\n```', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1542115470/reactions', 'total_count': 1, '+1': 1, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1547142147', 'html_url': 'https://github.com/huggingface/datasets/issues/5837#issuecomment-1547142147', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5837', 'id': 1547142147, 'node_id': 'IC_kwDODunzps5cN4QD', 'user': {'login': 'LanShanPi', 'id': 58167546, 'node_id': 'MDQ6VXNlcjU4MTY3NTQ2', 'avatar_url': 'https://avatars.githubusercontent.com/u/58167546?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/LanShanPi', 'html_url': 'https://github.com/LanShanPi', 'followers_url': 'https://api.github.com/users/LanShanPi/followers', 'following_url': 'https://api.github.com/users/LanShanPi/following{/other_user}', 'gists_url': 'https://api.github.com/users/LanShanPi/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/LanShanPi/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/LanShanPi/subscriptions', 'organizations_url': 'https://api.github.com/users/LanShanPi/orgs', 'repos_url': 'https://api.github.com/users/LanShanPi/repos', 'events_url': 'https://api.github.com/users/LanShanPi/events{/privacy}', 'received_events_url': 'https://api.github.com/users/LanShanPi/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-05-15T03:31:12Z', 'updated_at': '2023-05-15T03:31:12Z', 'author_association': 'NONE', 'body': '@lhoestq thank you.', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1547142147/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1547152552', 'html_url': 'https://github.com/huggingface/datasets/issues/5837#issuecomment-1547152552', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5837', 'id': 1547152552, 'node_id': 'IC_kwDODunzps5cN6yo', 'user': {'login': 'LanShanPi', 'id': 58167546, 'node_id': 'MDQ6VXNlcjU4MTY3NTQ2', 'avatar_url': 'https://avatars.githubusercontent.com/u/58167546?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/LanShanPi', 'html_url': 'https://github.com/LanShanPi', 'followers_url': 'https://api.github.com/users/LanShanPi/followers', 'following_url': 'https://api.github.com/users/LanShanPi/following{/other_user}', 'gists_url': 'https://api.github.com/users/LanShanPi/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/LanShanPi/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/LanShanPi/subscriptions', 'organizations_url': 'https://api.github.com/users/LanShanPi/orgs', 'repos_url': 'https://api.github.com/users/LanShanPi/repos', 'events_url': 'https://api.github.com/users/LanShanPi/events{/privacy}', 'received_events_url': 'https://api.github.com/users/LanShanPi/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-05-15T03:51:36Z', 'updated_at': '2023-05-15T03:51:36Z', 'author_association': 'NONE', 'body': 'The other question: \r\nTraceback (most recent call last):\r\n  File "<stdin>", line 1, in <module>\r\n  File "/home/fm001/.conda/envs/hzl/lib/python3.8/site-packages/datasets/load.py", line 1767, in load_dataset\r\n    builder_instance = load_dataset_builder(\r\n  File "/home/fm001/.conda/envs/hzl/lib/python3.8/site-packages/datasets/load.py", line 1498, in load_dataset_builder\r\n    dataset_module = dataset_module_factory(\r\n  File "/home/fm001/.conda/envs/hzl/lib/python3.8/site-packages/datasets/load.py", line 1127, in dataset_module_factory\r\n    return PackagedDatasetModuleFactory(\r\n  File "/home/fm001/.conda/envs/hzl/lib/python3.8/site-packages/datasets/load.py", line 708, in get_module\r\n    data_files = DataFilesDict.from_local_or_remote(\r\n  File "/home/fm001/.conda/envs/hzl/lib/python3.8/site-packages/datasets/data_files.py", line 796, in from_local_or_remote\r\n    DataFilesList.from_local_or_remote(\r\n  File "/home/fm001/.conda/envs/hzl/lib/python3.8/site-packages/datasets/data_files.py", line 764, in from_local_or_remote\r\n    data_files = resolve_patterns_locally_or_by_urls(base_path, patterns, allowed_extensions)\r\n  File "/home/fm001/.conda/envs/hzl/lib/python3.8/site-packages/datasets/data_files.py", line 362, in resolve_patterns_locally_or_by_urls\r\n    for path in _resolve_single_pattern_locally(base_path, pattern, allowed_extensions):\r\n  File "/home/fm001/.conda/envs/hzl/lib/python3.8/site-packages/datasets/data_files.py", line 306, in _resolve_single_pattern_locally\r\n    raise FileNotFoundError(error_msg)\r\nFileNotFoundError: Unable to find \'/home/fm001/hzl/Data/qa/\' at /\r\n>>> mydata = load_dataset("/home/fm001/hzl/Data/qa/")\r\nTraceback (most recent call last):\r\n  File "<stdin>", line 1, in <module>\r\n  File "/home/fm001/.conda/envs/hzl/lib/python3.8/site-packages/datasets/load.py", line 1767, in load_dataset\r\n    builder_instance = load_dataset_builder(\r\n  File "/home/fm001/.conda/envs/hzl/lib/python3.8/site-packages/datasets/load.py", line 1508, in load_dataset_builder\r\n    builder_cls = import_main_class(dataset_module.module_path)\r\n  File "/home/fm001/.conda/envs/hzl/lib/python3.8/site-packages/datasets/load.py", line 115, in import_main_class\r\n    module = importlib.import_module(module_path)\r\n  File "/home/fm001/.conda/envs/hzl/lib/python3.8/importlib/__init__.py", line 127, in import_module\r\n    return _bootstrap._gcd_import(name[level:], package, level)\r\n  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import\r\n  File "<frozen importlib._bootstrap>", line 991, in _find_and_load\r\n  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked\r\n  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked\r\n  File "<frozen importlib._bootstrap_external>", line 783, in exec_module\r\n  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed\r\n  File "/home/fm001/.cache/huggingface/modules/datasets_modules/datasets/qa/b8b9f481eff9d17b769b4b50f30a51da32b47c94d1af4d2bdffb9fc2c589513a/qa.py", line 2, in <module>\r\n    mydata = load_dataset("/home/fm001/hzl/Data/qa/")\r\n  File "/home/fm001/.conda/envs/hzl/lib/python3.8/site-packages/datasets/load.py", line 1767, in load_dataset\r\n    builder_instance = load_dataset_builder(\r\n  File "/home/fm001/.conda/envs/hzl/lib/python3.8/site-packages/datasets/load.py", line 1524, in load_dataset_builder\r\n    builder_instance: DatasetBuilder = builder_cls(\r\nTypeError: \'NoneType\' object is not callable\r\n\r\nAnd I follow the setting with https://huggingface.co/docs/datasets/dataset_script', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1547152552/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}]

[{'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1540914935', 'html_url': 'https://github.com/huggingface/datasets/pull/5836#issuecomment-1540914935', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5836', 'id': 1540914935, 'node_id': 'IC_kwDODunzps5b2H73', 'user': {'login': 'HuggingFaceDocBuilderDev', 'id': 99929124, 'node_id': 'U_kgDOBfTMJA', 'avatar_url': 'https://avatars.githubusercontent.com/u/99929124?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/HuggingFaceDocBuilderDev', 'html_url': 'https://github.com/HuggingFaceDocBuilderDev', 'followers_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/followers', 'following_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/following{/other_user}', 'gists_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/subscriptions', 'organizations_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/orgs', 'repos_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/repos', 'events_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/events{/privacy}', 'received_events_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-05-09T21:27:11Z', 'updated_at': '2023-05-09T21:27:11Z', 'author_association': 'NONE', 'body': 'The docs for this PR live [here](https://moon-ci-docs.huggingface.co/docs/datasets/pr_5836). All of your documentation changes will be reflected on that endpoint.', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1540914935/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1542737410', 'html_url': 'https://github.com/huggingface/datasets/pull/5836#issuecomment-1542737410', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5836', 'id': 1542737410, 'node_id': 'IC_kwDODunzps5b9E4C', 'user': {'login': 'mariosasko', 'id': 47462742, 'node_id': 'MDQ6VXNlcjQ3NDYyNzQy', 'avatar_url': 'https://avatars.githubusercontent.com/u/47462742?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/mariosasko', 'html_url': 'https://github.com/mariosasko', 'followers_url': 'https://api.github.com/users/mariosasko/followers', 'following_url': 'https://api.github.com/users/mariosasko/following{/other_user}', 'gists_url': 'https://api.github.com/users/mariosasko/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/mariosasko/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/mariosasko/subscriptions', 'organizations_url': 'https://api.github.com/users/mariosasko/orgs', 'repos_url': 'https://api.github.com/users/mariosasko/repos', 'events_url': 'https://api.github.com/users/mariosasko/events{/privacy}', 'received_events_url': 'https://api.github.com/users/mariosasko/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-05-10T20:03:36Z', 'updated_at': '2023-05-10T20:03:36Z', 'author_association': 'CONTRIBUTOR', 'body': 'The error seems unrelated to the changes, so feel free to merge.', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1542737410/reactions', 'total_count': 1, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 1, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1542770571', 'html_url': 'https://github.com/huggingface/datasets/pull/5836#issuecomment-1542770571', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5836', 'id': 1542770571, 'node_id': 'IC_kwDODunzps5b9M-L', 'user': {'login': 'github-actions[bot]', 'id': 41898282, 'node_id': 'MDM6Qm90NDE4OTgyODI=', 'avatar_url': 'https://avatars.githubusercontent.com/in/15368?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/github-actions%5Bbot%5D', 'html_url': 'https://github.com/apps/github-actions', 'followers_url': 'https://api.github.com/users/github-actions%5Bbot%5D/followers', 'following_url': 'https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}', 'gists_url': 'https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/github-actions%5Bbot%5D/subscriptions', 'organizations_url': 'https://api.github.com/users/github-actions%5Bbot%5D/orgs', 'repos_url': 'https://api.github.com/users/github-actions%5Bbot%5D/repos', 'events_url': 'https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}', 'received_events_url': 'https://api.github.com/users/github-actions%5Bbot%5D/received_events', 'type': 'Bot', 'site_admin': False}, 'created_at': '2023-05-10T20:30:18Z', 'updated_at': '2023-05-10T20:30:18Z', 'author_association': 'NONE', 'body': '<details>\n<summary>Show benchmarks</summary>\n\nPyArrow==8.0.0\n\n<details>\n<summary>Show updated benchmarks!</summary>\n\n### Benchmark: benchmark_array_xd.json\n\n| metric | read_batch_formatted_as_numpy after write_array2d | read_batch_formatted_as_numpy after write_flattened_sequence | read_batch_formatted_as_numpy after write_nested_sequence | read_batch_unformated after write_array2d | read_batch_unformated after write_flattened_sequence | read_batch_unformated after write_nested_sequence | read_col_formatted_as_numpy after write_array2d | read_col_formatted_as_numpy after write_flattened_sequence | read_col_formatted_as_numpy after write_nested_sequence | read_col_unformated after write_array2d | read_col_unformated after write_flattened_sequence | read_col_unformated after write_nested_sequence | read_formatted_as_numpy after write_array2d | read_formatted_as_numpy after write_flattened_sequence | read_formatted_as_numpy after write_nested_sequence | read_unformated after write_array2d | read_unformated after write_flattened_sequence | read_unformated after write_nested_sequence | write_array2d | write_flattened_sequence | write_nested_sequence |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.006562 / 0.011353 (-0.004791) | 0.004568 / 0.011008 (-0.006440) | 0.098151 / 0.038508 (0.059643) | 0.028117 / 0.023109 (0.005008) | 0.305442 / 0.275898 (0.029544) | 0.338288 / 0.323480 (0.014808) | 0.005012 / 0.007986 (-0.002973) | 0.003415 / 0.004328 (-0.000913) | 0.075022 / 0.004250 (0.070771) | 0.036869 / 0.037052 (-0.000183) | 0.301427 / 0.258489 (0.042937) | 0.348485 / 0.293841 (0.054644) | 0.030761 / 0.128546 (-0.097785) | 0.011461 / 0.075646 (-0.064185) | 0.321987 / 0.419271 (-0.097285) | 0.042885 / 0.043533 (-0.000648) | 0.300691 / 0.255139 (0.045552) | 0.333208 / 0.283200 (0.050008) | 0.090203 / 0.141683 (-0.051480) | 1.459744 / 1.452155 (0.007590) | 1.522960 / 1.492716 (0.030243) |\n\n### Benchmark: benchmark_getitem\\_100B.json\n\n| metric | get_batch_of\\_1024\\_random_rows | get_batch_of\\_1024\\_rows | get_first_row | get_last_row |\n|--------|---|---|---|---|\n| new / old (diff) | 0.213219 / 0.018006 (0.195213) | 0.408118 / 0.000490 (0.407629) | 0.003716 / 0.000200 (0.003516) | 0.000077 / 0.000054 (0.000022) |\n\n### Benchmark: benchmark_indices_mapping.json\n\n| metric | select | shard | shuffle | sort | train_test_split |\n|--------|---|---|---|---|---|\n| new / old (diff) | 0.023060 / 0.037411 (-0.014351) | 0.097423 / 0.014526 (0.082897) | 0.103988 / 0.176557 (-0.072568) | 0.162793 / 0.737135 (-0.574343) | 0.108282 / 0.296338 (-0.188056) |\n\n### Benchmark: benchmark_iterating.json\n\n| metric | read 5000 | read 50000 | read_batch 50000 10 | read_batch 50000 100 | read_batch 50000 1000 | read_formatted numpy 5000 | read_formatted pandas 5000 | read_formatted tensorflow 5000 | read_formatted torch 5000 | read_formatted_batch numpy 5000 10 | read_formatted_batch numpy 5000 1000 | shuffled read 5000 | shuffled read 50000 | shuffled read_batch 50000 10 | shuffled read_batch 50000 100 | shuffled read_batch 50000 1000 | shuffled read_formatted numpy 5000 | shuffled read_formatted_batch numpy 5000 10 | shuffled read_formatted_batch numpy 5000 1000 |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.431628 / 0.215209 (0.216419) | 4.300881 / 2.077655 (2.223226) | 2.058853 / 1.504120 (0.554733) | 1.897910 / 1.541195 (0.356715) | 1.991723 / 1.468490 (0.523233) | 0.699686 / 4.584777 (-3.885091) | 3.395004 / 3.745712 (-0.350708) | 1.841613 / 5.269862 (-3.428248) | 1.152347 / 4.565676 (-3.413330) | 0.082517 / 0.424275 (-0.341758) | 0.012323 / 0.007607 (0.004715) | 0.535812 / 0.226044 (0.309767) | 5.374103 / 2.268929 (3.105174) | 2.429662 / 55.444624 (-53.014962) | 2.097199 / 6.876477 (-4.779277) | 2.172625 / 2.142072 (0.030552) | 0.810156 / 4.805227 (-3.995071) | 0.151629 / 6.500664 (-6.349035) | 0.066528 / 0.075469 (-0.008941) |\n\n### Benchmark: benchmark_map_filter.json\n\n| metric | filter | map fast-tokenizer batched | map identity | map identity batched | map no-op batched | map no-op batched numpy | map no-op batched pandas | map no-op batched pytorch | map no-op batched tensorflow |\n|--------|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 1.220667 / 1.841788 (-0.621121) | 13.696976 / 8.074308 (5.622668) | 14.042916 / 10.191392 (3.851524) | 0.129626 / 0.680424 (-0.550798) | 0.016593 / 0.534201 (-0.517607) | 0.383747 / 0.579283 (-0.195536) | 0.386872 / 0.434364 (-0.047492) | 0.456524 / 0.540337 (-0.083813) | 0.545033 / 1.386936 (-0.841903) |\n\n</details>\nPyArrow==latest\n\n<details>\n<summary>Show updated benchmarks!</summary>\n\n### Benchmark: benchmark_array_xd.json\n\n| metric | read_batch_formatted_as_numpy after write_array2d | read_batch_formatted_as_numpy after write_flattened_sequence | read_batch_formatted_as_numpy after write_nested_sequence | read_batch_unformated after write_array2d | read_batch_unformated after write_flattened_sequence | read_batch_unformated after write_nested_sequence | read_col_formatted_as_numpy after write_array2d | read_col_formatted_as_numpy after write_flattened_sequence | read_col_formatted_as_numpy after write_nested_sequence | read_col_unformated after write_array2d | read_col_unformated after write_flattened_sequence | read_col_unformated after write_nested_sequence | read_formatted_as_numpy after write_array2d | read_formatted_as_numpy after write_flattened_sequence | read_formatted_as_numpy after write_nested_sequence | read_unformated after write_array2d | read_unformated after write_flattened_sequence | read_unformated after write_nested_sequence | write_array2d | write_flattened_sequence | write_nested_sequence |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.006361 / 0.011353 (-0.004992) | 0.004516 / 0.011008 (-0.006493) | 0.077155 / 0.038508 (0.038647) | 0.027239 / 0.023109 (0.004130) | 0.359892 / 0.275898 (0.083994) | 0.391994 / 0.323480 (0.068514) | 0.004950 / 0.007986 (-0.003036) | 0.003379 / 0.004328 (-0.000949) | 0.077057 / 0.004250 (0.072806) | 0.039562 / 0.037052 (0.002509) | 0.364244 / 0.258489 (0.105755) | 0.416033 / 0.293841 (0.122192) | 0.031049 / 0.128546 (-0.097497) | 0.011479 / 0.075646 (-0.064167) | 0.086479 / 0.419271 (-0.332793) | 0.039381 / 0.043533 (-0.004151) | 0.372143 / 0.255139 (0.117004) | 0.388569 / 0.283200 (0.105369) | 0.090954 / 0.141683 (-0.050728) | 1.540957 / 1.452155 (0.088802) | 1.596841 / 1.492716 (0.104125) |\n\n### Benchmark: benchmark_getitem\\_100B.json\n\n| metric | get_batch_of\\_1024\\_random_rows | get_batch_of\\_1024\\_rows | get_first_row | get_last_row |\n|--------|---|---|---|---|\n| new / old (diff) | 0.221130 / 0.018006 (0.203123) | 0.403728 / 0.000490 (0.403238) | 0.003172 / 0.000200 (0.002972) | 0.000078 / 0.000054 (0.000024) |\n\n### Benchmark: benchmark_indices_mapping.json\n\n| metric | select | shard | shuffle | sort | train_test_split |\n|--------|---|---|---|---|---|\n| new / old (diff) | 0.024963 / 0.037411 (-0.012449) | 0.101065 / 0.014526 (0.086539) | 0.110846 / 0.176557 (-0.065710) | 0.158578 / 0.737135 (-0.578557) | 0.112235 / 0.296338 (-0.184104) |\n\n### Benchmark: benchmark_iterating.json\n\n| metric | read 5000 | read 50000 | read_batch 50000 10 | read_batch 50000 100 | read_batch 50000 1000 | read_formatted numpy 5000 | read_formatted pandas 5000 | read_formatted tensorflow 5000 | read_formatted torch 5000 | read_formatted_batch numpy 5000 10 | read_formatted_batch numpy 5000 1000 | shuffled read 5000 | shuffled read 50000 | shuffled read_batch 50000 10 | shuffled read_batch 50000 100 | shuffled read_batch 50000 1000 | shuffled read_formatted numpy 5000 | shuffled read_formatted_batch numpy 5000 10 | shuffled read_formatted_batch numpy 5000 1000 |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.457320 / 0.215209 (0.242111) | 4.548094 / 2.077655 (2.470439) | 2.175376 / 1.504120 (0.671256) | 1.964755 / 1.541195 (0.423561) | 2.008128 / 1.468490 (0.539638) | 0.702448 / 4.584777 (-3.882329) | 3.437595 / 3.745712 (-0.308117) | 3.009871 / 5.269862 (-2.259990) | 1.558181 / 4.565676 (-3.007496) | 0.082568 / 0.424275 (-0.341707) | 0.012371 / 0.007607 (0.004764) | 0.550688 / 0.226044 (0.324644) | 5.534210 / 2.268929 (3.265282) | 2.649605 / 55.444624 (-52.795020) | 2.317293 / 6.876477 (-4.559184) | 2.351525 / 2.142072 (0.209453) | 0.808971 / 4.805227 (-3.996256) | 0.152737 / 6.500664 (-6.347927) | 0.068416 / 0.075469 (-0.007053) |\n\n### Benchmark: benchmark_map_filter.json\n\n| metric | filter | map fast-tokenizer batched | map identity | map identity batched | map no-op batched | map no-op batched numpy | map no-op batched pandas | map no-op batched pytorch | map no-op batched tensorflow |\n|--------|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 1.340219 / 1.841788 (-0.501569) | 13.903388 / 8.074308 (5.829080) | 13.063477 / 10.191392 (2.872085) | 0.130216 / 0.680424 (-0.550208) | 0.016522 / 0.534201 (-0.517679) | 0.398946 / 0.579283 (-0.180337) | 0.382450 / 0.434364 (-0.051914) | 0.491007 / 0.540337 (-0.049330) | 0.577747 / 1.386936 (-0.809189) |\n\n</details>\n</details>\n\n![](https://cml.dev/watermark.png#15c37ed142e4fbcb8c00ae62d4c71c84ce41959a "CML watermark")\n', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1542770571/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1547337763', 'html_url': 'https://github.com/huggingface/datasets/pull/5836#issuecomment-1547337763', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5836', 'id': 1547337763, 'node_id': 'IC_kwDODunzps5cOoAj', 'user': {'login': 'github-actions[bot]', 'id': 41898282, 'node_id': 'MDM6Qm90NDE4OTgyODI=', 'avatar_url': 'https://avatars.githubusercontent.com/in/15368?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/github-actions%5Bbot%5D', 'html_url': 'https://github.com/apps/github-actions', 'followers_url': 'https://api.github.com/users/github-actions%5Bbot%5D/followers', 'following_url': 'https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}', 'gists_url': 'https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/github-actions%5Bbot%5D/subscriptions', 'organizations_url': 'https://api.github.com/users/github-actions%5Bbot%5D/orgs', 'repos_url': 'https://api.github.com/users/github-actions%5Bbot%5D/repos', 'events_url': 'https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}', 'received_events_url': 'https://api.github.com/users/github-actions%5Bbot%5D/received_events', 'type': 'Bot', 'site_admin': False}, 'created_at': '2023-05-15T07:36:12Z', 'updated_at': '2023-05-15T07:36:12Z', 'author_association': 'NONE', 'body': '<details>\n<summary>Show benchmarks</summary>\n\nPyArrow==8.0.0\n\n<details>\n<summary>Show updated benchmarks!</summary>\n\n### Benchmark: benchmark_array_xd.json\n\n| metric | read_batch_formatted_as_numpy after write_array2d | read_batch_formatted_as_numpy after write_flattened_sequence | read_batch_formatted_as_numpy after write_nested_sequence | read_batch_unformated after write_array2d | read_batch_unformated after write_flattened_sequence | read_batch_unformated after write_nested_sequence | read_col_formatted_as_numpy after write_array2d | read_col_formatted_as_numpy after write_flattened_sequence | read_col_formatted_as_numpy after write_nested_sequence | read_col_unformated after write_array2d | read_col_unformated after write_flattened_sequence | read_col_unformated after write_nested_sequence | read_formatted_as_numpy after write_array2d | read_formatted_as_numpy after write_flattened_sequence | read_formatted_as_numpy after write_nested_sequence | read_unformated after write_array2d | read_unformated after write_flattened_sequence | read_unformated after write_nested_sequence | write_array2d | write_flattened_sequence | write_nested_sequence |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.007812 / 0.011353 (-0.003541) | 0.005563 / 0.011008 (-0.005446) | 0.099372 / 0.038508 (0.060864) | 0.035629 / 0.023109 (0.012520) | 0.301457 / 0.275898 (0.025559) | 0.339136 / 0.323480 (0.015656) | 0.006152 / 0.007986 (-0.001834) | 0.005843 / 0.004328 (0.001515) | 0.075280 / 0.004250 (0.071030) | 0.052789 / 0.037052 (0.015736) | 0.301805 / 0.258489 (0.043316) | 0.347918 / 0.293841 (0.054078) | 0.036182 / 0.128546 (-0.092364) | 0.012655 / 0.075646 (-0.062991) | 0.334428 / 0.419271 (-0.084844) | 0.062746 / 0.043533 (0.019213) | 0.296932 / 0.255139 (0.041793) | 0.314115 / 0.283200 (0.030916) | 0.121291 / 0.141683 (-0.020392) | 1.453252 / 1.452155 (0.001097) | 1.564714 / 1.492716 (0.071997) |\n\n### Benchmark: benchmark_getitem\\_100B.json\n\n| metric | get_batch_of\\_1024\\_random_rows | get_batch_of\\_1024\\_rows | get_first_row | get_last_row |\n|--------|---|---|---|---|\n| new / old (diff) | 0.243810 / 0.018006 (0.225804) | 0.547129 / 0.000490 (0.546640) | 0.004666 / 0.000200 (0.004466) | 0.000089 / 0.000054 (0.000035) |\n\n### Benchmark: benchmark_indices_mapping.json\n\n| metric | select | shard | shuffle | sort | train_test_split |\n|--------|---|---|---|---|---|\n| new / old (diff) | 0.028214 / 0.037411 (-0.009197) | 0.108878 / 0.014526 (0.094352) | 0.122313 / 0.176557 (-0.054243) | 0.182412 / 0.737135 (-0.554723) | 0.127014 / 0.296338 (-0.169324) |\n\n### Benchmark: benchmark_iterating.json\n\n| metric | read 5000 | read 50000 | read_batch 50000 10 | read_batch 50000 100 | read_batch 50000 1000 | read_formatted numpy 5000 | read_formatted pandas 5000 | read_formatted tensorflow 5000 | read_formatted torch 5000 | read_formatted_batch numpy 5000 10 | read_formatted_batch numpy 5000 1000 | shuffled read 5000 | shuffled read 50000 | shuffled read_batch 50000 10 | shuffled read_batch 50000 100 | shuffled read_batch 50000 1000 | shuffled read_formatted numpy 5000 | shuffled read_formatted_batch numpy 5000 10 | shuffled read_formatted_batch numpy 5000 1000 |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.423946 / 0.215209 (0.208737) | 4.207112 / 2.077655 (2.129457) | 2.048658 / 1.504120 (0.

[{'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1540662016', 'html_url': 'https://github.com/huggingface/datasets/pull/5835#issuecomment-1540662016', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5835', 'id': 1540662016, 'node_id': 'IC_kwDODunzps5b1KMA', 'user': {'login': 'HuggingFaceDocBuilderDev', 'id': 99929124, 'node_id': 'U_kgDOBfTMJA', 'avatar_url': 'https://avatars.githubusercontent.com/u/99929124?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/HuggingFaceDocBuilderDev', 'html_url': 'https://github.com/HuggingFaceDocBuilderDev', 'followers_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/followers', 'following_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/following{/other_user}', 'gists_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/subscriptions', 'organizations_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/orgs', 'repos_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/repos', 'events_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/events{/privacy}', 'received_events_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-05-09T18:21:42Z', 'updated_at': '2023-05-19T13:07:13Z', 'author_association': 'NONE', 'body': '_The documentation is not available anymore as the PR was closed or merged._', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1540662016/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1540662839', 'html_url': 'https://github.com/huggingface/datasets/pull/5835#issuecomment-1540662839', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5835', 'id': 1540662839, 'node_id': 'IC_kwDODunzps5b1KY3', 'user': {'login': 'github-actions[bot]', 'id': 41898282, 'node_id': 'MDM6Qm90NDE4OTgyODI=', 'avatar_url': 'https://avatars.githubusercontent.com/in/15368?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/github-actions%5Bbot%5D', 'html_url': 'https://github.com/apps/github-actions', 'followers_url': 'https://api.github.com/users/github-actions%5Bbot%5D/followers', 'following_url': 'https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}', 'gists_url': 'https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/github-actions%5Bbot%5D/subscriptions', 'organizations_url': 'https://api.github.com/users/github-actions%5Bbot%5D/orgs', 'repos_url': 'https://api.github.com/users/github-actions%5Bbot%5D/repos', 'events_url': 'https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}', 'received_events_url': 'https://api.github.com/users/github-actions%5Bbot%5D/received_events', 'type': 'Bot', 'site_admin': False}, 'created_at': '2023-05-09T18:22:14Z', 'updated_at': '2023-05-09T18:22:14Z', 'author_association': 'NONE', 'body': '<details>\n<summary>Show benchmarks</summary>\n\nPyArrow==8.0.0\n\n<details>\n<summary>Show updated benchmarks!</summary>\n\n### Benchmark: benchmark_array_xd.json\n\n| metric | read_batch_formatted_as_numpy after write_array2d | read_batch_formatted_as_numpy after write_flattened_sequence | read_batch_formatted_as_numpy after write_nested_sequence | read_batch_unformated after write_array2d | read_batch_unformated after write_flattened_sequence | read_batch_unformated after write_nested_sequence | read_col_formatted_as_numpy after write_array2d | read_col_formatted_as_numpy after write_flattened_sequence | read_col_formatted_as_numpy after write_nested_sequence | read_col_unformated after write_array2d | read_col_unformated after write_flattened_sequence | read_col_unformated after write_nested_sequence | read_formatted_as_numpy after write_array2d | read_formatted_as_numpy after write_flattened_sequence | read_formatted_as_numpy after write_nested_sequence | read_unformated after write_array2d | read_unformated after write_flattened_sequence | read_unformated after write_nested_sequence | write_array2d | write_flattened_sequence | write_nested_sequence |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.006640 / 0.011353 (-0.004713) | 0.004606 / 0.011008 (-0.006402) | 0.098870 / 0.038508 (0.060362) | 0.028201 / 0.023109 (0.005092) | 0.304396 / 0.275898 (0.028498) | 0.339804 / 0.323480 (0.016324) | 0.005011 / 0.007986 (-0.002974) | 0.003530 / 0.004328 (-0.000799) | 0.075223 / 0.004250 (0.070973) | 0.037922 / 0.037052 (0.000870) | 0.310273 / 0.258489 (0.051784) | 0.348324 / 0.293841 (0.054483) | 0.030181 / 0.128546 (-0.098365) | 0.011584 / 0.075646 (-0.064062) | 0.322637 / 0.419271 (-0.096635) | 0.043119 / 0.043533 (-0.000414) | 0.314514 / 0.255139 (0.059375) | 0.334384 / 0.283200 (0.051185) | 0.092551 / 0.141683 (-0.049132) | 1.496694 / 1.452155 (0.044539) | 1.555426 / 1.492716 (0.062710) |\n\n### Benchmark: benchmark_getitem\\_100B.json\n\n| metric | get_batch_of\\_1024\\_random_rows | get_batch_of\\_1024\\_rows | get_first_row | get_last_row |\n|--------|---|---|---|---|\n| new / old (diff) | 0.205078 / 0.018006 (0.187072) | 0.399200 / 0.000490 (0.398710) | 0.004881 / 0.000200 (0.004681) | 0.000200 / 0.000054 (0.000146) |\n\n### Benchmark: benchmark_indices_mapping.json\n\n| metric | select | shard | shuffle | sort | train_test_split |\n|--------|---|---|---|---|---|\n| new / old (diff) | 0.025042 / 0.037411 (-0.012369) | 0.101501 / 0.014526 (0.086975) | 0.107430 / 0.176557 (-0.069127) | 0.170107 / 0.737135 (-0.567028) | 0.111253 / 0.296338 (-0.185086) |\n\n### Benchmark: benchmark_iterating.json\n\n| metric | read 5000 | read 50000 | read_batch 50000 10 | read_batch 50000 100 | read_batch 50000 1000 | read_formatted numpy 5000 | read_formatted pandas 5000 | read_formatted tensorflow 5000 | read_formatted torch 5000 | read_formatted_batch numpy 5000 10 | read_formatted_batch numpy 5000 1000 | shuffled read 5000 | shuffled read 50000 | shuffled read_batch 50000 10 | shuffled read_batch 50000 100 | shuffled read_batch 50000 1000 | shuffled read_formatted numpy 5000 | shuffled read_formatted_batch numpy 5000 10 | shuffled read_formatted_batch numpy 5000 1000 |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.460358 / 0.215209 (0.245149) | 4.592037 / 2.077655 (2.514383) | 2.222612 / 1.504120 (0.718493) | 2.022804 / 1.541195 (0.481610) | 2.040824 / 1.468490 (0.572334) | 0.700485 / 4.584777 (-3.884292) | 3.427847 / 3.745712 (-0.317866) | 2.836916 / 5.269862 (-2.432946) | 1.505055 / 4.565676 (-3.060621) | 0.083206 / 0.424275 (-0.341069) | 0.046492 / 0.007607 (0.038885) | 0.555562 / 0.226044 (0.329518) | 5.563574 / 2.268929 (3.294645) | 2.635273 / 55.444624 (-52.809351) | 2.299377 / 6.876477 (-4.577100) | 2.394512 / 2.142072 (0.252440) | 0.809541 / 4.805227 (-3.995686) | 0.151814 / 6.500664 (-6.348850) | 0.067241 / 0.075469 (-0.008228) |\n\n### Benchmark: benchmark_map_filter.json\n\n| metric | filter | map fast-tokenizer batched | map identity | map identity batched | map no-op batched | map no-op batched numpy | map no-op batched pandas | map no-op batched pytorch | map no-op batched tensorflow |\n|--------|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 1.188396 / 1.841788 (-0.653392) | 13.714596 / 8.074308 (5.640288) | 14.076906 / 10.191392 (3.885514) | 0.143447 / 0.680424 (-0.536977) | 0.016514 / 0.534201 (-0.517687) | 0.383075 / 0.579283 (-0.196209) | 0.386997 / 0.434364 (-0.047367) | 0.441941 / 0.540337 (-0.098396) | 0.522145 / 1.386936 (-0.864791) |\n\n</details>\nPyArrow==latest\n\n<details>\n<summary>Show updated benchmarks!</summary>\n\n### Benchmark: benchmark_array_xd.json\n\n| metric | read_batch_formatted_as_numpy after write_array2d | read_batch_formatted_as_numpy after write_flattened_sequence | read_batch_formatted_as_numpy after write_nested_sequence | read_batch_unformated after write_array2d | read_batch_unformated after write_flattened_sequence | read_batch_unformated after write_nested_sequence | read_col_formatted_as_numpy after write_array2d | read_col_formatted_as_numpy after write_flattened_sequence | read_col_formatted_as_numpy after write_nested_sequence | read_col_unformated after write_array2d | read_col_unformated after write_flattened_sequence | read_col_unformated after write_nested_sequence | read_formatted_as_numpy after write_array2d | read_formatted_as_numpy after write_flattened_sequence | read_formatted_as_numpy after write_nested_sequence | read_unformated after write_array2d | read_unformated after write_flattened_sequence | read_unformated after write_nested_sequence | write_array2d | write_flattened_sequence | write_nested_sequence |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.006266 / 0.011353 (-0.005086) | 0.004562 / 0.011008 (-0.006446) | 0.077472 / 0.038508 (0.038964) | 0.027596 / 0.023109 (0.004486) | 0.400498 / 0.275898 (0.124600) | 0.406728 / 0.323480 (0.083248) | 0.004745 / 0.007986 (-0.003241) | 0.003375 / 0.004328 (-0.000954) | 0.076645 / 0.004250 (0.072394) | 0.037756 / 0.037052 (0.000703) | 0.415183 / 0.258489 (0.156694) | 0.413758 / 0.293841 (0.119917) | 0.030624 / 0.128546 (-0.097922) | 0.011525 / 0.075646 (-0.064121) | 0.086033 / 0.419271 (-0.333238) | 0.039307 / 0.043533 (-0.004226) | 0.418192 / 0.255139 (0.163053) | 0.403152 / 0.283200 (0.119952) | 0.094141 / 0.141683 (-0.047542) | 1.459012 / 1.452155 (0.006857) | 1.546493 / 1.492716 (0.053777) |\n\n### Benchmark: benchmark_getitem\\_100B.json\n\n| metric | get_batch_of\\_1024\\_random_rows | get_batch_of\\_1024\\_rows | get_first_row | get_last_row |\n|--------|---|---|---|---|\n| new / old (diff) | 0.239494 / 0.018006 (0.221488) | 0.420918 / 0.000490 (0.420428) | 0.000411 / 0.000200 (0.000211) | 0.000057 / 0.000054 (0.000002) |\n\n### Benchmark: benchmark_indices_mapping.json\n\n| metric | select | shard | shuffle | sort | train_test_split |\n|--------|---|---|---|---|---|\n| new / old (diff) | 0.024525 / 0.037411 (-0.012886) | 0.099793 / 0.014526 (0.085267) | 0.105888 / 0.176557 (-0.070669) | 0.155912 / 0.737135 (-0.581223) | 0.109937 / 0.296338 (-0.186401) |\n\n### Benchmark: benchmark_iterating.json\n\n| metric | read 5000 | read 50000 | read_batch 50000 10 | read_batch 50000 100 | read_batch 50000 1000 | read_formatted numpy 5000 | read_formatted pandas 5000 | read_formatted tensorflow 5000 | read_formatted torch 5000 | read_formatted_batch numpy 5000 10 | read_formatted_batch numpy 5000 1000 | shuffled read 5000 | shuffled read 50000 | shuffled read_batch 50000 10 | shuffled read_batch 50000 100 | shuffled read_batch 50000 1000 | shuffled read_formatted numpy 5000 | shuffled read_formatted_batch numpy 5000 10 | shuffled read_formatted_batch numpy 5000 1000 |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.470108 / 0.215209 (0.254899) | 4.696390 / 2.077655 (2.618735) | 2.467841 / 1.504120 (0.963721) | 2.275012 / 1.541195 (0.733818) | 2.430736 / 1.468490 (0.962245) | 0.700442 / 4.584777 (-3.884335) | 3.458451 / 3.745712 (-0.287261) | 1.921120 / 5.269862 (-3.348742) | 1.183292 / 4.565676 (-3.382384) | 0.083985 / 0.424275 (-0.340290) | 0.012510 / 0.007607 (0.004903) | 0.589066 / 0.226044 (0.363022) | 5.896070 / 2.268929 (3.627141) | 2.935379 / 55.444624 (-52.509245) | 2.599524 / 6.876477 (-4.276953) | 2.663426 / 2.142072 (0.521354) | 0.812096 / 4.805227 (-3.993131) | 0.152559 / 6.500664 (-6.348105) | 0.066906 / 0.075469 (-0.008563) |\n\n### Benchmark: benchmark_map_filter.json\n\n| metric | filter | map fast-tokenizer batched | map identity | map identity batched | map no-op batched | map no-op batched numpy | map no-op batched pandas | map no-op batched pytorch | map no-op batched tensorflow |\n|--------|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 1.333341 / 1.841788 (-0.508446) | 14.441667 / 8.074308 (6.367359) | 14.754069 / 10.191392 (4.562677) | 0.155707 / 0.680424 (-0.524716) | 0.016983 / 0.534201 (-0.517218) | 0.389386 / 0.579283 (-0.189897) | 0.394106 / 0.434364 (-0.040258) | 0.447355 / 0.540337 (-0.092982) | 0.533142 / 1.386936 (-0.853794) |\n\n</details>\n</details>\n\n![](https://cml.dev/watermark.png#99ee4467ce77f8f718159a535e237dd8790b5bed "CML watermark")\n', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1540662839/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1554552681', 'html_url': 'https://github.com/huggingface/datasets/pull/5835#issuecomment-1554552681', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5835', 'id': 1554552681, 'node_id': 'IC_kwDODunzps5cqJdp', 'user': {'login': 'github-actions[bot]', 'id': 41898282, 'node_id': 'MDM6Qm90NDE4OTgyODI=', 'avatar_url': 'https://avatars.githubusercontent.com/in/15368?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/github-actions%5Bbot%5D', 'html_url': 'https://github.com/apps/github-actions', 'followers_url': 'https://api.github.com/users/github-actions%5Bbot%5D/followers', 'following_url': 'https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}', 'gists_url': 'https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/github-actions%5Bbot%5D/subscriptions', 'organizations_url': 'https://api.github.com/users/github-actions%5Bbot%5D/orgs', 'repos_url': 'https://api.github.com/users/github-actions%5Bbot%5D/repos', 'events_url': 'https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}', 'received_events_url': 'https://api.github.com/users/github-actions%5Bbot%5D/received_events', 'type': 'Bot', 'site_admin': False}, 'created_at': '2023-05-19T13:12:45Z', 'updated_at': '2023-05-19T13:12:45Z', 'author_association': 'NONE', 'body': '<details>\n<summary>Show benchmarks</summary>\n\nPyArrow==8.0.0\n\n<details>\n<summary>Show updated benchmarks!</summary>\n\n### Benchmark: benchmark_array_xd.json\n\n| metric | read_batch_formatted_as_numpy after write_array2d | read_batch_formatted_as_numpy after write_flattened_sequence | read_batch_formatted_as_numpy after write_nested_sequence | read_batch_unformated after write_array2d | read_batch_unformated after write_flattened_sequence | read_batch_unformated after write_nested_sequence | read_col_formatted_as_numpy after write_array2d | read_col_formatted_as_numpy after write_flattened_sequence | read_col_formatted_as_numpy after write_nested_sequence | read_col_unformated after write_array2d | read_col_unformated after write_flattened_sequence | read_col_unformated after write_nested_sequence | read_formatted_as_numpy after write_array2d | read_formatted_as_numpy after write_flattened_sequence | read_formatted_as_numpy after write_nested_sequence | read_unformated after write_array2d | read_unformated after write_flattened_sequence | read_unformated after write_nested_sequence | write_array2d | write_flattened_sequence | write_nested_sequence |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.007801 / 0.011353 (-0.003552) | 0.004884 / 0.011008 (-0.006124) | 0.114754 / 0.038508 (0.076245) | 0.040427 / 0.023109 (0.017318) | 0.402064 / 0.275898 (0.126166) | 0.428830 / 0.323480 (0.105350) | 0.006429 / 0.007986 (-0.001556) | 0.004394 / 0.004328 (0.000066) | 0.087681 / 0.004250 (0.083431) | 0.053684 / 0.037052 (0.016632) | 0.399967 / 0.258489 (0.141478) | 0.445298 / 0.293841 (0.151457) | 0.033194 / 0.128546 (-0.095352) | 0.010288 / 0.075646 (-0.065359) | 0.390719 / 0.419271 (-0.028552) | 0.059311 / 0.043533 (0.015778) | 0.393651 / 0.255139 (0.138512) | 0.418395 / 0.283200 (0.135196) | 0.121494 / 0.141683 (-0.020189) | 1.735470 / 1.452155 (0.283315) | 1.820485 / 1.492716 (0.327769) |\n\n### Benchmark: benchmark_getitem\\_100B.json\n\n| metric | get_batch_of\\_1024\\_random_rows | get_batch_of\\_1024\\_rows | get_first_row | get_last_row |\n|--------|---|---|---|---|\n| new / old (diff) | 0.012887 / 0.018006 (-0.005119) | 0.491652 / 0.000490 (0.491162) | 0.005481 / 0.000200 (0.005281) | 0.000127 / 0.000054 (0.000073) |\n\n### Benchmark: benchmark_indices_mapping.json\n\n| metric | select | shard | shuffle | sort | train_test_split |\n|--------|---|---|---|---|---|\n| new / old (diff) | 0.030931 / 0.037411 (-0.006480) | 0.125212 / 0.014526 (0.110686) | 0.136004 / 0.176557 (-0.040552) | 0.201686 / 0.737135 (-0.535449) | 0.140181 / 0.296338 (-0.156157) |\n\n### Benchmark: benchmark_iterating.json\n\n| metric | read 5000 | read 50000 | read_batch 50000 10 | read_batch 50000 100 | read_batch 50000 1000 | read_formatted numpy 5000 | read_formatted pandas 5000 | read_formatted tensorflow 5000 | read_formatted torch 5000 | read_formatted_batch numpy 5000 10 | read_formatted_batch numpy 5000 1000 | shuffled read 5000 | shuffled read 50000 | shuffled read_batch 50000 10 | shuffled read_batch 50000 100 | shuffled read_batch 50000 1000 | shuffled read_formatted numpy 5000 | shuffled read_formatted_batch numpy 5000 10 | shuffled read_formatted_batch numpy 5000 1000 |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.475003 / 0.215209 (0.259794) | 4.743918 / 2.077655 (2.666263) | 2.149422 / 1.504120 (0.645302) | 1.925016 / 1.541195 (0.383821) | 2.061441 / 1.468490 (0.592951) | 0.619845 / 4.584777 (-3.964932) | 4.534691 / 3.745712 (0.788979) | 2.248198 / 5.269862 (-3.021664) | 1.409868 / 4.565676 (-3.155808) | 0.080265 / 0.424275 (-0.344010) | 0.014455 / 0.007607 (0.006848) | 0.597810 / 0.226044 (0.371765) | 5.845492 / 2.268929 (3.576564) | 2.729139 / 55.444624 (-52.715486) | 2.313879 / 6.876477 (-4.562598) | 2.418763 / 2.142072 (0.276690) | 0.748687 / 4.805227 (-4.056540) | 0.165278 / 6.500664 (-6.335387) | 0.076848 / 0.075469 (0.001379) |\n\n### Benchmark: benchmark_map_filter.json\n\n| metric | filter | map fast-tokenizer batched | map identity | map identity batched | map no-op batched | map no-op batched numpy | map no-op batched pandas | map no-op batched pytorch | map no-op batched tensorflow |\n|--------|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 1.416349 / 1.841788 (-0.425439) | 17.440903 / 8.074308 (9.366595) | 17.025733 / 10.191392 (6.834341) | 0.167428 / 0.680424 (-0.512995) | 0.020484 / 0.534201 (-0.513717) | 0.470273 / 0.579283 (-0.109010) | 0.494380 / 0.434364 (0.060016) | 0.566131 / 0.540337 (0.025794) | 0.690444 / 1.386936 (-0.696492) |\n\n</details>\nPyArrow==latest\n\n<details>\n<summary>Show updated benchmarks!</summary>\n\n### Benchmark: benchmark_array_xd.json\n\n| metric | read_batch_formatted_as_numpy after write_array2d | read_batch_formatted_as_numpy after write_flattened_sequence | read_batch_formatted_as_numpy after write_nested_sequence | read_batch_unformated after write_array2d | read_batch_unformated after write_flattened_sequence | read_batch_unformated after write_nested_sequence | read_col_formatted_as_numpy after write_array2d | read_col_formatted_as_numpy after write_flattened_sequence | read_col_formatted_as_numpy after write_nested

[{'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1542118387', 'html_url': 'https://github.com/huggingface/datasets/issues/5834#issuecomment-1542118387', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5834', 'id': 1542118387, 'node_id': 'IC_kwDODunzps5b6tvz', 'user': {'login': 'lhoestq', 'id': 42851186, 'node_id': 'MDQ6VXNlcjQyODUxMTg2', 'avatar_url': 'https://avatars.githubusercontent.com/u/42851186?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/lhoestq', 'html_url': 'https://github.com/lhoestq', 'followers_url': 'https://api.github.com/users/lhoestq/followers', 'following_url': 'https://api.github.com/users/lhoestq/following{/other_user}', 'gists_url': 'https://api.github.com/users/lhoestq/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/lhoestq/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/lhoestq/subscriptions', 'organizations_url': 'https://api.github.com/users/lhoestq/orgs', 'repos_url': 'https://api.github.com/users/lhoestq/repos', 'events_url': 'https://api.github.com/users/lhoestq/events{/privacy}', 'received_events_url': 'https://api.github.com/users/lhoestq/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-05-10T12:25:56Z', 'updated_at': '2023-05-10T12:26:01Z', 'author_association': 'MEMBER', 'body': 'Hi ! The numpy formatting detaults to int64 and float32 - but you can use uint8 using\r\n```python\r\nds = ds.with_format("numpy", dtype=np.uint8)\r\n```', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1542118387/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1542325793', 'html_url': 'https://github.com/huggingface/datasets/issues/5834#issuecomment-1542325793', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5834', 'id': 1542325793, 'node_id': 'IC_kwDODunzps5b7gYh', 'user': {'login': 'mariosasko', 'id': 47462742, 'node_id': 'MDQ6VXNlcjQ3NDYyNzQy', 'avatar_url': 'https://avatars.githubusercontent.com/u/47462742?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/mariosasko', 'html_url': 'https://github.com/mariosasko', 'followers_url': 'https://api.github.com/users/mariosasko/followers', 'following_url': 'https://api.github.com/users/mariosasko/following{/other_user}', 'gists_url': 'https://api.github.com/users/mariosasko/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/mariosasko/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/mariosasko/subscriptions', 'organizations_url': 'https://api.github.com/users/mariosasko/orgs', 'repos_url': 'https://api.github.com/users/mariosasko/repos', 'events_url': 'https://api.github.com/users/mariosasko/events{/privacy}', 'received_events_url': 'https://api.github.com/users/mariosasko/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-05-10T14:40:49Z', 'updated_at': '2023-05-10T14:40:49Z', 'author_association': 'CONTRIBUTOR', 'body': 'Related to https://github.com/huggingface/datasets/issues/5517.', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1542325793/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1545718745', 'html_url': 'https://github.com/huggingface/datasets/issues/5834#issuecomment-1545718745', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5834', 'id': 1545718745, 'node_id': 'IC_kwDODunzps5cIcvZ', 'user': {'login': 'ryokan0123', 'id': 17979572, 'node_id': 'MDQ6VXNlcjE3OTc5NTcy', 'avatar_url': 'https://avatars.githubusercontent.com/u/17979572?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/ryokan0123', 'html_url': 'https://github.com/ryokan0123', 'followers_url': 'https://api.github.com/users/ryokan0123/followers', 'following_url': 'https://api.github.com/users/ryokan0123/following{/other_user}', 'gists_url': 'https://api.github.com/users/ryokan0123/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/ryokan0123/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/ryokan0123/subscriptions', 'organizations_url': 'https://api.github.com/users/ryokan0123/orgs', 'repos_url': 'https://api.github.com/users/ryokan0123/repos', 'events_url': 'https://api.github.com/users/ryokan0123/events{/privacy}', 'received_events_url': 'https://api.github.com/users/ryokan0123/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-05-12T13:07:07Z', 'updated_at': '2023-05-12T13:16:06Z', 'author_association': 'NONE', 'body': 'Thank you!\r\nBy setting `ds.with_format("numpy", dtype=np.uint8)`, the dataset returns the data in `uint8`.\r\n\r\nHowever, `with_format` and `set_format` seem to cast the data on-the-fly.\r\nI want to reduce the dataset size by using `uint8` instead of `int64` and I observe no difference between using `int64` and `uint8` for the vector.\r\nIs there any way to actually store the data in `uint8` and save the disk space and the downloading time when loaded from the hub?\r\n', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1545718745/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1545733623', 'html_url': 'https://github.com/huggingface/datasets/issues/5834#issuecomment-1545733623', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5834', 'id': 1545733623, 'node_id': 'IC_kwDODunzps5cIgX3', 'user': {'login': 'lhoestq', 'id': 42851186, 'node_id': 'MDQ6VXNlcjQyODUxMTg2', 'avatar_url': 'https://avatars.githubusercontent.com/u/42851186?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/lhoestq', 'html_url': 'https://github.com/lhoestq', 'followers_url': 'https://api.github.com/users/lhoestq/followers', 'following_url': 'https://api.github.com/users/lhoestq/following{/other_user}', 'gists_url': 'https://api.github.com/users/lhoestq/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/lhoestq/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/lhoestq/subscriptions', 'organizations_url': 'https://api.github.com/users/lhoestq/orgs', 'repos_url': 'https://api.github.com/users/lhoestq/repos', 'events_url': 'https://api.github.com/users/lhoestq/events{/privacy}', 'received_events_url': 'https://api.github.com/users/lhoestq/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-05-12T13:18:08Z', 'updated_at': '2023-05-12T13:18:08Z', 'author_association': 'MEMBER', 'body': 'If the feature type is `Value("uint8")` then it\'s written an uint8 on disk using the uint8 Arrow dtype.\r\n\r\ne.g.\r\n```python\r\nds = Dataset.from_dict({"a": range(10)}, features=Features({"a": Value("uint8")}))\r\nds.data.nbytes\r\n# 10\r\n```', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1545733623/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1546529090', 'html_url': 'https://github.com/huggingface/datasets/issues/5834#issuecomment-1546529090', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5834', 'id': 1546529090, 'node_id': 'IC_kwDODunzps5cLilC', 'user': {'login': 'ryokan0123', 'id': 17979572, 'node_id': 'MDQ6VXNlcjE3OTc5NTcy', 'avatar_url': 'https://avatars.githubusercontent.com/u/17979572?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/ryokan0123', 'html_url': 'https://github.com/ryokan0123', 'followers_url': 'https://api.github.com/users/ryokan0123/followers', 'following_url': 'https://api.github.com/users/ryokan0123/following{/other_user}', 'gists_url': 'https://api.github.com/users/ryokan0123/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/ryokan0123/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/ryokan0123/subscriptions', 'organizations_url': 'https://api.github.com/users/ryokan0123/orgs', 'repos_url': 'https://api.github.com/users/ryokan0123/repos', 'events_url': 'https://api.github.com/users/ryokan0123/events{/privacy}', 'received_events_url': 'https://api.github.com/users/ryokan0123/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-05-13T05:04:21Z', 'updated_at': '2023-05-13T05:04:21Z', 'author_association': 'NONE', 'body': 'Oh, I understand now.\r\nThe data was stored in `uint8` from the beginning (when the dataset returns `int64`).\r\n\r\nThank you for your time!\r\nMy question is fully resolved.', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1546529090/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}]

[{'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1540457522', 'html_url': 'https://github.com/huggingface/datasets/issues/5833#issuecomment-1540457522', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5833', 'id': 1540457522, 'node_id': 'IC_kwDODunzps5b0YQy', 'user': {'login': 'albertvillanova', 'id': 8515462, 'node_id': 'MDQ6VXNlcjg1MTU0NjI=', 'avatar_url': 'https://avatars.githubusercontent.com/u/8515462?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/albertvillanova', 'html_url': 'https://github.com/albertvillanova', 'followers_url': 'https://api.github.com/users/albertvillanova/followers', 'following_url': 'https://api.github.com/users/albertvillanova/following{/other_user}', 'gists_url': 'https://api.github.com/users/albertvillanova/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/albertvillanova/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/albertvillanova/subscriptions', 'organizations_url': 'https://api.github.com/users/albertvillanova/orgs', 'repos_url': 'https://api.github.com/users/albertvillanova/repos', 'events_url': 'https://api.github.com/users/albertvillanova/events{/privacy}', 'received_events_url': 'https://api.github.com/users/albertvillanova/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-05-09T15:59:40Z', 'updated_at': '2023-05-09T15:59:40Z', 'author_association': 'MEMBER', 'body': 'Thanks for reporting, @agombert.\r\n\r\nIn this case, I think the root issue is authentication: before pushing to Hub, you should authenticate. See our docs: https://huggingface.co/docs/datasets/upload_dataset#upload-with-python\r\n> 2. To upload a dataset on the Hub in Python, you need to log in to your Hugging Face account:\r\n   ```\r\n   huggingface-cli login\r\n   ```', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1540457522/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1540463065', 'html_url': 'https://github.com/huggingface/datasets/issues/5833#issuecomment-1540463065', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5833', 'id': 1540463065, 'node_id': 'IC_kwDODunzps5b0ZnZ', 'user': {'login': 'agombert', 'id': 17645711, 'node_id': 'MDQ6VXNlcjE3NjQ1NzEx', 'avatar_url': 'https://avatars.githubusercontent.com/u/17645711?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/agombert', 'html_url': 'https://github.com/agombert', 'followers_url': 'https://api.github.com/users/agombert/followers', 'following_url': 'https://api.github.com/users/agombert/following{/other_user}', 'gists_url': 'https://api.github.com/users/agombert/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/agombert/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/agombert/subscriptions', 'organizations_url': 'https://api.github.com/users/agombert/orgs', 'repos_url': 'https://api.github.com/users/agombert/repos', 'events_url': 'https://api.github.com/users/agombert/events{/privacy}', 'received_events_url': 'https://api.github.com/users/agombert/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-05-09T16:03:05Z', 'updated_at': '2023-05-09T16:03:05Z', 'author_association': 'NONE', 'body': 'Hey @albertvillanova well I actually did :D \r\n\r\n<img width="1079" alt="Capture d’écran 2023-05-09 à 18 02 58" src="https://github.com/huggingface/datasets/assets/17645711/e091aa20-06b1-4dd3-bfdb-35e832c66f8d">\r\n', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1540463065/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1540528407', 'html_url': 'https://github.com/huggingface/datasets/issues/5833#issuecomment-1540528407', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5833', 'id': 1540528407, 'node_id': 'IC_kwDODunzps5b0pkX', 'user': {'login': 'albertvillanova', 'id': 8515462, 'node_id': 'MDQ6VXNlcjg1MTU0NjI=', 'avatar_url': 'https://avatars.githubusercontent.com/u/8515462?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/albertvillanova', 'html_url': 'https://github.com/albertvillanova', 'followers_url': 'https://api.github.com/users/albertvillanova/followers', 'following_url': 'https://api.github.com/users/albertvillanova/following{/other_user}', 'gists_url': 'https://api.github.com/users/albertvillanova/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/albertvillanova/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/albertvillanova/subscriptions', 'organizations_url': 'https://api.github.com/users/albertvillanova/orgs', 'repos_url': 'https://api.github.com/users/albertvillanova/repos', 'events_url': 'https://api.github.com/users/albertvillanova/events{/privacy}', 'received_events_url': 'https://api.github.com/users/albertvillanova/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-05-09T16:51:05Z', 'updated_at': '2023-05-09T16:51:05Z', 'author_association': 'MEMBER', 'body': 'That is weird that you get a Forbidden error if you are properly authenticated...\r\n\r\nToday we had a big outage issue affecting the Hugging Face Hub. Could you please retry to push_to_hub your dataset? Maybe that was the cause...', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1540528407/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1540880766', 'html_url': 'https://github.com/huggingface/datasets/issues/5833#issuecomment-1540880766', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5833', 'id': 1540880766, 'node_id': 'IC_kwDODunzps5b1_l-', 'user': {'login': 'agombert', 'id': 17645711, 'node_id': 'MDQ6VXNlcjE3NjQ1NzEx', 'avatar_url': 'https://avatars.githubusercontent.com/u/17645711?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/agombert', 'html_url': 'https://github.com/agombert', 'followers_url': 'https://api.github.com/users/agombert/followers', 'following_url': 'https://api.github.com/users/agombert/following{/other_user}', 'gists_url': 'https://api.github.com/users/agombert/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/agombert/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/agombert/subscriptions', 'organizations_url': 'https://api.github.com/users/agombert/orgs', 'repos_url': 'https://api.github.com/users/agombert/repos', 'events_url': 'https://api.github.com/users/agombert/events{/privacy}', 'received_events_url': 'https://api.github.com/users/agombert/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-05-09T20:57:55Z', 'updated_at': '2023-05-09T20:57:55Z', 'author_association': 'NONE', 'body': "Yes I've just tried again and same error 403 :/", 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1540880766/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1558405819', 'html_url': 'https://github.com/huggingface/datasets/issues/5833#issuecomment-1558405819', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5833', 'id': 1558405819, 'node_id': 'IC_kwDODunzps5c42K7', 'user': {'login': 'cl886699', 'id': 31495593, 'node_id': 'MDQ6VXNlcjMxNDk1NTkz', 'avatar_url': 'https://avatars.githubusercontent.com/u/31495593?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/cl886699', 'html_url': 'https://github.com/cl886699', 'followers_url': 'https://api.github.com/users/cl886699/followers', 'following_url': 'https://api.github.com/users/cl886699/following{/other_user}', 'gists_url': 'https://api.github.com/users/cl886699/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/cl886699/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/cl886699/subscriptions', 'organizations_url': 'https://api.github.com/users/cl886699/orgs', 'repos_url': 'https://api.github.com/users/cl886699/repos', 'events_url': 'https://api.github.com/users/cl886699/events{/privacy}', 'received_events_url': 'https://api.github.com/users/cl886699/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-05-23T02:22:53Z', 'updated_at': '2023-05-23T02:22:53Z', 'author_association': 'NONE', 'body': 'Login successful but also got this error "Forbidden: pass `create_pr=1` as a query parameter to create a Pull Request"', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1558405819/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1586521001', 'html_url': 'https://github.com/huggingface/datasets/issues/5833#issuecomment-1586521001', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5833', 'id': 1586521001, 'node_id': 'IC_kwDODunzps5ekGOp', 'user': {'login': 'dmitrijsk', 'id': 42183699, 'node_id': 'MDQ6VXNlcjQyMTgzNjk5', 'avatar_url': 'https://avatars.githubusercontent.com/u/42183699?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/dmitrijsk', 'html_url': 'https://github.com/dmitrijsk', 'followers_url': 'https://api.github.com/users/dmitrijsk/followers', 'following_url': 'https://api.github.com/users/dmitrijsk/following{/other_user}', 'gists_url': 'https://api.github.com/users/dmitrijsk/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/dmitrijsk/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/dmitrijsk/subscriptions', 'organizations_url': 'https://api.github.com/users/dmitrijsk/orgs', 'repos_url': 'https://api.github.com/users/dmitrijsk/repos', 'events_url': 'https://api.github.com/users/dmitrijsk/events{/privacy}', 'received_events_url': 'https://api.github.com/users/dmitrijsk/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-12T03:28:40Z', 'updated_at': '2023-06-12T03:28:40Z', 'author_association': 'NONE', 'body': 'Make sure your API token has a `write` role. I had the same issue as you with the `read` token. Creating a `write` token and using that solved the issue.', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1586521001/reactions', 'total_count': 2, '+1': 2, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1609202129', 'html_url': 'https://github.com/huggingface/datasets/issues/5833#issuecomment-1609202129', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5833', 'id': 1609202129, 'node_id': 'IC_kwDODunzps5f6nnR', 'user': {'login': 'alicedingyueming', 'id': 13958389, 'node_id': 'MDQ6VXNlcjEzOTU4Mzg5', 'avatar_url': 'https://avatars.githubusercontent.com/u/13958389?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/alicedingyueming', 'html_url': 'https://github.com/alicedingyueming', 'followers_url': 'https://api.github.com/users/alicedingyueming/followers', 'following_url': 'https://api.github.com/users/alicedingyueming/following{/other_user}', 'gists_url': 'https://api.github.com/users/alicedingyueming/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/alicedingyueming/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/alicedingyueming/subscriptions', 'organizations_url': 'https://api.github.com/users/alicedingyueming/orgs', 'repos_url': 'https://api.github.com/users/alicedingyueming/repos', 'events_url': 'https://api.github.com/users/alicedingyueming/events{/privacy}', 'received_events_url': 'https://api.github.com/users/alicedingyueming/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-27T10:09:28Z', 'updated_at': '2023-06-27T10:09:28Z', 'author_association': 'NONE', 'body': '> Make sure your API token has a `write` role. I had the same issue as you with the `read` token. Creating a `write` token and using that solved the issue.\r\n\r\nI generate a token with write role. It works! thank you so much.', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1609202129/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}]

[{'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1540233167', 'html_url': 'https://github.com/huggingface/datasets/issues/5832#issuecomment-1540233167', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5832', 'id': 1540233167, 'node_id': 'IC_kwDODunzps5bzhfP', 'user': {'login': 'varungupta31', 'id': 51288316, 'node_id': 'MDQ6VXNlcjUxMjg4MzE2', 'avatar_url': 'https://avatars.githubusercontent.com/u/51288316?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/varungupta31', 'html_url': 'https://github.com/varungupta31', 'followers_url': 'https://api.github.com/users/varungupta31/followers', 'following_url': 'https://api.github.com/users/varungupta31/following{/other_user}', 'gists_url': 'https://api.github.com/users/varungupta31/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/varungupta31/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/varungupta31/subscriptions', 'organizations_url': 'https://api.github.com/users/varungupta31/orgs', 'repos_url': 'https://api.github.com/users/varungupta31/repos', 'events_url': 'https://api.github.com/users/varungupta31/events{/privacy}', 'received_events_url': 'https://api.github.com/users/varungupta31/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-05-09T14:25:41Z', 'updated_at': '2023-05-09T14:25:41Z', 'author_association': 'NONE', 'body': 'moved to https://github.com/huggingface/transformers/issues/23233', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1540233167/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}]
[{'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1539984305', 'html_url': 'https://github.com/huggingface/datasets/issues/5831#issuecomment-1539984305', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5831', 'id': 1539984305, 'node_id': 'IC_kwDODunzps5bykux', 'user': {'login': 'lucidBrot', 'id': 4920691, 'node_id': 'MDQ6VXNlcjQ5MjA2OTE=', 'avatar_url': 'https://avatars.githubusercontent.com/u/4920691?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/lucidBrot', 'html_url': 'https://github.com/lucidBrot', 'followers_url': 'https://api.github.com/users/lucidBrot/followers', 'following_url': 'https://api.github.com/users/lucidBrot/following{/other_user}', 'gists_url': 'https://api.github.com/users/lucidBrot/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/lucidBrot/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/lucidBrot/subscriptions', 'organizations_url': 'https://api.github.com/users/lucidBrot/orgs', 'repos_url': 'https://api.github.com/users/lucidBrot/repos', 'events_url': 'https://api.github.com/users/lucidBrot/events{/privacy}', 'received_events_url': 'https://api.github.com/users/lucidBrot/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-05-09T11:17:57Z', 'updated_at': '2023-05-09T11:19:27Z', 'author_association': 'NONE', 'body': "I am experiencing the same problem with the following environment:\r\n\r\n* `datasets` version: 2.11.0\r\n* Platform: `Linux 5.19.0-41-generic x86_64 GNU/Linux`\r\n* Python version: `3.8.5`\r\n* Huggingface_hub version: 0.13.3\r\n* PyArrow version: `11.0.0`\r\n* Pandas version: `1.5.3`\r\n\r\nTrying to get some diagnostics, I got the following:  \r\n\r\n```python\r\n>>> from huggingface_hub import scan_cache_dir\r\n>>> sd = scan_cache_dir()\r\n>>> sd\r\nHFCacheInfo(size_on_disk=0, repos=frozenset(), warnings=[CorruptedCacheException('Repo path is not a directory: /home/myname/.cache/huggingface/hub/version_diffusers_cache.txt')])\r\n\r\n```\r\nHowever, that might also be because I had tried to manually specify the `cache_dir` and that resulted in trying to download the dataset again ... but into a folder one level higher up than it should have.\r\n\r\nNote that my issue is with the `huggan/wikiart` dataset, so it is not a dataset-specific issue.", 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1539984305/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1539993721', 'html_url': 'https://github.com/huggingface/datasets/issues/5831#issuecomment-1539993721', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5831', 'id': 1539993721, 'node_id': 'IC_kwDODunzps5bynB5', 'user': {'login': 'TobiasLee', 'id': 20009381, 'node_id': 'MDQ6VXNlcjIwMDA5Mzgx', 'avatar_url': 'https://avatars.githubusercontent.com/u/20009381?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/TobiasLee', 'html_url': 'https://github.com/TobiasLee', 'followers_url': 'https://api.github.com/users/TobiasLee/followers', 'following_url': 'https://api.github.com/users/TobiasLee/following{/other_user}', 'gists_url': 'https://api.github.com/users/TobiasLee/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/TobiasLee/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/TobiasLee/subscriptions', 'organizations_url': 'https://api.github.com/users/TobiasLee/orgs', 'repos_url': 'https://api.github.com/users/TobiasLee/repos', 'events_url': 'https://api.github.com/users/TobiasLee/events{/privacy}', 'received_events_url': 'https://api.github.com/users/TobiasLee/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-05-09T11:24:32Z', 'updated_at': '2023-05-09T11:24:32Z', 'author_association': 'NONE', 'body': 'same problem with a private dataset repo, seems the huggingface hub server got some connection problem?', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1539993721/reactions', 'total_count': 2, '+1': 2, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1540021365', 'html_url': 'https://github.com/huggingface/datasets/issues/5831#issuecomment-1540021365', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5831', 'id': 1540021365, 'node_id': 'IC_kwDODunzps5bytx1', 'user': {'login': 'qmeeus', 'id': 25608944, 'node_id': 'MDQ6VXNlcjI1NjA4OTQ0', 'avatar_url': 'https://avatars.githubusercontent.com/u/25608944?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/qmeeus', 'html_url': 'https://github.com/qmeeus', 'followers_url': 'https://api.github.com/users/qmeeus/followers', 'following_url': 'https://api.github.com/users/qmeeus/following{/other_user}', 'gists_url': 'https://api.github.com/users/qmeeus/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/qmeeus/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/qmeeus/subscriptions', 'organizations_url': 'https://api.github.com/users/qmeeus/orgs', 'repos_url': 'https://api.github.com/users/qmeeus/repos', 'events_url': 'https://api.github.com/users/qmeeus/events{/privacy}', 'received_events_url': 'https://api.github.com/users/qmeeus/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-05-09T12:13:25Z', 'updated_at': '2023-05-09T12:13:25Z', 'author_association': 'NONE', 'body': 'Yes, dataset server seems down for now', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1540021365/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1540245059', 'html_url': 'https://github.com/huggingface/datasets/issues/5831#issuecomment-1540245059', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5831', 'id': 1540245059, 'node_id': 'IC_kwDODunzps5bzkZD', 'user': {'login': 'mariosasko', 'id': 47462742, 'node_id': 'MDQ6VXNlcjQ3NDYyNzQy', 'avatar_url': 'https://avatars.githubusercontent.com/u/47462742?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/mariosasko', 'html_url': 'https://github.com/mariosasko', 'followers_url': 'https://api.github.com/users/mariosasko/followers', 'following_url': 'https://api.github.com/users/mariosasko/following{/other_user}', 'gists_url': 'https://api.github.com/users/mariosasko/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/mariosasko/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/mariosasko/subscriptions', 'organizations_url': 'https://api.github.com/users/mariosasko/orgs', 'repos_url': 'https://api.github.com/users/mariosasko/repos', 'events_url': 'https://api.github.com/users/mariosasko/events{/privacy}', 'received_events_url': 'https://api.github.com/users/mariosasko/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-05-09T14:31:46Z', 'updated_at': '2023-05-09T14:31:46Z', 'author_association': 'CONTRIBUTOR', 'body': "@SingL3 You can avoid this error by setting the [`HF_DATASETS_OFFLINE`](https://huggingface.co/docs/datasets/v2.12.0/en/loading#offline) env variable to 1. By default,  if an internet connection is available, we check whether the cache of a cached dataset is up-to-date.\r\n\r\n@lucidBrot `datasets`' cache is still not aligned with `huggigface_hub`'s. We plan to align it eventually.", 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1540245059/reactions', 'total_count': 1, '+1': 1, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1540336064', 'html_url': 'https://github.com/huggingface/datasets/issues/5831#issuecomment-1540336064', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5831', 'id': 1540336064, 'node_id': 'IC_kwDODunzps5bz6nA', 'user': {'login': 'albertvillanova', 'id': 8515462, 'node_id': 'MDQ6VXNlcjg1MTU0NjI=', 'avatar_url': 'https://avatars.githubusercontent.com/u/8515462?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/albertvillanova', 'html_url': 'https://github.com/albertvillanova', 'followers_url': 'https://api.github.com/users/albertvillanova/followers', 'following_url': 'https://api.github.com/users/albertvillanova/following{/other_user}', 'gists_url': 'https://api.github.com/users/albertvillanova/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/albertvillanova/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/albertvillanova/subscriptions', 'organizations_url': 'https://api.github.com/users/albertvillanova/orgs', 'repos_url': 'https://api.github.com/users/albertvillanova/repos', 'events_url': 'https://api.github.com/users/albertvillanova/events{/privacy}', 'received_events_url': 'https://api.github.com/users/albertvillanova/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-05-09T15:08:00Z', 'updated_at': '2023-05-09T15:08:00Z', 'author_association': 'MEMBER', 'body': 'Today we had a big issue affecting the Hugging Face Hub, thus all the `504 Server Error: Gateway Time-out` errors.\r\n\r\nIt is fixed now and loading your datasets should work as expected.', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1540336064/reactions', 'total_count': 3, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 3, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1541171067', 'html_url': 'https://github.com/huggingface/datasets/issues/5831#issuecomment-1541171067', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5831', 'id': 1541171067, 'node_id': 'IC_kwDODunzps5b3Gd7', 'user': {'login': 'SingL3', 'id': 20473466, 'node_id': 'MDQ6VXNlcjIwNDczNDY2', 'avatar_url': 'https://avatars.githubusercontent.com/u/20473466?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/SingL3', 'html_url': 'https://github.com/SingL3', 'followers_url': 'https://api.github.com/users/SingL3/followers', 'following_url': 'https://api.github.com/users/SingL3/following{/other_user}', 'gists_url': 'https://api.github.com/users/SingL3/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/SingL3/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/SingL3/subscriptions', 'organizations_url': 'https://api.github.com/users/SingL3/orgs', 'repos_url': 'https://api.github.com/users/SingL3/repos', 'events_url': 'https://api.github.com/users/SingL3/events{/privacy}', 'received_events_url': 'https://api.github.com/users/SingL3/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-05-10T01:46:41Z', 'updated_at': '2023-05-10T01:48:20Z', 'author_association': 'NONE', 'body': 'Hi, @albertvillanova.\r\nIf there is a locally cached version of datasets or something cache using huggingface_hub, when a network problem(either client or server) occurs, is it a better way to fallback to use the current cached version rather than raise a exception and exit?', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1541171067/reactions', 'total_count': 1, '+1': 1, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}]

[]
[{'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1538721453', 'html_url': 'https://github.com/huggingface/datasets/issues/5829#issuecomment-1538721453', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5829', 'id': 1538721453, 'node_id': 'IC_kwDODunzps5btwat', 'user': {'login': 'mariosasko', 'id': 47462742, 'node_id': 'MDQ6VXNlcjQ3NDYyNzQy', 'avatar_url': 'https://avatars.githubusercontent.com/u/47462742?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/mariosasko', 'html_url': 'https://github.com/mariosasko', 'followers_url': 'https://api.github.com/users/mariosasko/followers', 'following_url': 'https://api.github.com/users/mariosasko/following{/other_user}', 'gists_url': 'https://api.github.com/users/mariosasko/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/mariosasko/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/mariosasko/subscriptions', 'organizations_url': 'https://api.github.com/users/mariosasko/orgs', 'repos_url': 'https://api.github.com/users/mariosasko/repos', 'events_url': 'https://api.github.com/users/mariosasko/events{/privacy}', 'received_events_url': 'https://api.github.com/users/mariosasko/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-05-08T16:55:04Z', 'updated_at': '2023-05-08T16:55:04Z', 'author_association': 'CONTRIBUTOR', 'body': 'Can you paste the error stack trace?', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1538721453/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1539237822', 'html_url': 'https://github.com/huggingface/datasets/issues/5829#issuecomment-1539237822', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5829', 'id': 1539237822, 'node_id': 'IC_kwDODunzps5bvue-', 'user': {'login': 'elcolie', 'id': 18206728, 'node_id': 'MDQ6VXNlcjE4MjA2NzI4', 'avatar_url': 'https://avatars.githubusercontent.com/u/18206728?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/elcolie', 'html_url': 'https://github.com/elcolie', 'followers_url': 'https://api.github.com/users/elcolie/followers', 'following_url': 'https://api.github.com/users/elcolie/following{/other_user}', 'gists_url': 'https://api.github.com/users/elcolie/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/elcolie/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/elcolie/subscriptions', 'organizations_url': 'https://api.github.com/users/elcolie/orgs', 'repos_url': 'https://api.github.com/users/elcolie/repos', 'events_url': 'https://api.github.com/users/elcolie/events{/privacy}', 'received_events_url': 'https://api.github.com/users/elcolie/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-05-09T00:46:41Z', 'updated_at': '2023-05-09T00:46:41Z', 'author_association': 'NONE', 'body': 'That is weird. I can\'t reproduce it again after reboot.\r\n```python\r\nIn [2]: import platform\r\n\r\nIn [3]: platform.platform()\r\nOut[3]: \'macOS-13.2-arm64-arm-64bit\'\r\n\r\nIn [4]: from datasets import load_dataset\r\n   ...:\r\n   ...: jazzy = load_dataset("nomic-ai/gpt4all-j-prompt-generations", revision=\'v1.2-jazzy\')\r\nFound cached dataset parquet (/Users/sarit/.cache/huggingface/datasets/nomic-ai___parquet/nomic-ai--gpt4all-j-prompt-generations-a3b62015e2e52043/0.0.0/2a3b91fbd88a2c90d1dbbb32b460cf621d31bd5b05b934492fdef7d8d6f236ec)\r\n100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 63.25it/s]\r\n```', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1539237822/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}]
[{'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1538922861', 'html_url': 'https://github.com/huggingface/datasets/issues/5828#issuecomment-1538922861', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5828', 'id': 1538922861, 'node_id': 'IC_kwDODunzps5buhlt', 'user': {'login': 'mariosasko', 'id': 47462742, 'node_id': 'MDQ6VXNlcjQ3NDYyNzQy', 'avatar_url': 'https://avatars.githubusercontent.com/u/47462742?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/mariosasko', 'html_url': 'https://github.com/mariosasko', 'followers_url': 'https://api.github.com/users/mariosasko/followers', 'following_url': 'https://api.github.com/users/mariosasko/following{/other_user}', 'gists_url': 'https://api.github.com/users/mariosasko/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/mariosasko/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/mariosasko/subscriptions', 'organizations_url': 'https://api.github.com/users/mariosasko/orgs', 'repos_url': 'https://api.github.com/users/mariosasko/repos', 'events_url': 'https://api.github.com/users/mariosasko/events{/privacy}', 'received_events_url': 'https://api.github.com/users/mariosasko/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-05-08T19:25:30Z', 'updated_at': '2023-05-08T19:25:30Z', 'author_association': 'CONTRIBUTOR', 'body': "Hi! \r\n\r\nYou can call `map` as follows to avoid the error:\r\n```python\r\naugmented_dataset_cln = dataset_cln['train'].map(augment_dataset, features=dataset_cln['train'].features)\r\n```", 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1538922861/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1541358511', 'html_url': 'https://github.com/huggingface/datasets/issues/5828#issuecomment-1541358511', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5828', 'id': 1541358511, 'node_id': 'IC_kwDODunzps5b30Ov', 'user': {'login': 'krishnapriya-18', 'id': 48817796, 'node_id': 'MDQ6VXNlcjQ4ODE3Nzk2', 'avatar_url': 'https://avatars.githubusercontent.com/u/48817796?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/krishnapriya-18', 'html_url': 'https://github.com/krishnapriya-18', 'followers_url': 'https://api.github.com/users/krishnapriya-18/followers', 'following_url': 'https://api.github.com/users/krishnapriya-18/following{/other_user}', 'gists_url': 'https://api.github.com/users/krishnapriya-18/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/krishnapriya-18/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/krishnapriya-18/subscriptions', 'organizations_url': 'https://api.github.com/users/krishnapriya-18/orgs', 'repos_url': 'https://api.github.com/users/krishnapriya-18/repos', 'events_url': 'https://api.github.com/users/krishnapriya-18/events{/privacy}', 'received_events_url': 'https://api.github.com/users/krishnapriya-18/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-05-10T05:05:47Z', 'updated_at': '2023-05-10T05:05:47Z', 'author_association': 'NONE', 'body': 'Thanks it is solved', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1541358511/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1613745382', 'html_url': 'https://github.com/huggingface/datasets/issues/5828#issuecomment-1613745382', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5828', 'id': 1613745382, 'node_id': 'IC_kwDODunzps5gL8zm', 'user': {'login': 'chengxiLei', 'id': 83874200, 'node_id': 'MDQ6VXNlcjgzODc0MjAw', 'avatar_url': 'https://avatars.githubusercontent.com/u/83874200?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/chengxiLei', 'html_url': 'https://github.com/chengxiLei', 'followers_url': 'https://api.github.com/users/chengxiLei/followers', 'following_url': 'https://api.github.com/users/chengxiLei/following{/other_user}', 'gists_url': 'https://api.github.com/users/chengxiLei/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/chengxiLei/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/chengxiLei/subscriptions', 'organizations_url': 'https://api.github.com/users/chengxiLei/orgs', 'repos_url': 'https://api.github.com/users/chengxiLei/repos', 'events_url': 'https://api.github.com/users/chengxiLei/events{/privacy}', 'received_events_url': 'https://api.github.com/users/chengxiLei/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-06-29T20:07:55Z', 'updated_at': '2023-06-29T20:07:55Z', 'author_association': 'NONE', 'body': 'Hi! \r\nI have run into the same problem with you. Could you please let me know how you solve it? Thanks!', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1613745382/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}]

[{'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1542128789', 'html_url': 'https://github.com/huggingface/datasets/issues/5827#issuecomment-1542128789', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5827', 'id': 1542128789, 'node_id': 'IC_kwDODunzps5b6wSV', 'user': {'login': 'lhoestq', 'id': 42851186, 'node_id': 'MDQ6VXNlcjQyODUxMTg2', 'avatar_url': 'https://avatars.githubusercontent.com/u/42851186?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/lhoestq', 'html_url': 'https://github.com/lhoestq', 'followers_url': 'https://api.github.com/users/lhoestq/followers', 'following_url': 'https://api.github.com/users/lhoestq/following{/other_user}', 'gists_url': 'https://api.github.com/users/lhoestq/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/lhoestq/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/lhoestq/subscriptions', 'organizations_url': 'https://api.github.com/users/lhoestq/orgs', 'repos_url': 'https://api.github.com/users/lhoestq/repos', 'events_url': 'https://api.github.com/users/lhoestq/events{/privacy}', 'received_events_url': 'https://api.github.com/users/lhoestq/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-05-10T12:32:27Z', 'updated_at': '2023-05-10T12:32:27Z', 'author_association': 'MEMBER', 'body': "Indeed the JSON dataset builder raises an error when it encounters an unexpected type.\r\n\r\nThere's an old PR open to add away to ignore such elements though, if it can help: https://github.com/huggingface/datasets/pull/2838", 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1542128789/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}]

[{'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1536620258', 'html_url': 'https://github.com/huggingface/datasets/issues/5825#issuecomment-1536620258', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5825', 'id': 1536620258, 'node_id': 'IC_kwDODunzps5blvbi', 'user': {'login': 'mariosasko', 'id': 47462742, 'node_id': 'MDQ6VXNlcjQ3NDYyNzQy', 'avatar_url': 'https://avatars.githubusercontent.com/u/47462742?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/mariosasko', 'html_url': 'https://github.com/mariosasko', 'followers_url': 'https://api.github.com/users/mariosasko/followers', 'following_url': 'https://api.github.com/users/mariosasko/following{/other_user}', 'gists_url': 'https://api.github.com/users/mariosasko/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/mariosasko/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/mariosasko/subscriptions', 'organizations_url': 'https://api.github.com/users/mariosasko/orgs', 'repos_url': 'https://api.github.com/users/mariosasko/repos', 'events_url': 'https://api.github.com/users/mariosasko/events{/privacy}', 'received_events_url': 'https://api.github.com/users/mariosasko/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-05-05T18:26:25Z', 'updated_at': '2023-05-05T18:26:25Z', 'author_association': 'CONTRIBUTOR', 'body': 'Hi! \r\n\r\nThis would only work if `bigscience/xP3` was a no-code dataset, but it isn\'t (it has a Python builder script).\r\n\r\nBut this should work: \r\n```python\r\nload_dataset("json", data_files="https://huggingface.co/datasets/bigscience/xP3/resolve/main/ur/xp3_facebook_flores_spa_Latn-urd_Arab_devtest_ab-spa_Latn-urd_Arab.jsonl")\r\n```\r\n\r\n', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1536620258/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1536721077', 'html_url': 'https://github.com/huggingface/datasets/issues/5825#issuecomment-1536721077', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5825', 'id': 1536721077, 'node_id': 'IC_kwDODunzps5bmIC1', 'user': {'login': 'Muennighoff', 'id': 62820084, 'node_id': 'MDQ6VXNlcjYyODIwMDg0', 'avatar_url': 'https://avatars.githubusercontent.com/u/62820084?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/Muennighoff', 'html_url': 'https://github.com/Muennighoff', 'followers_url': 'https://api.github.com/users/Muennighoff/followers', 'following_url': 'https://api.github.com/users/Muennighoff/following{/other_user}', 'gists_url': 'https://api.github.com/users/Muennighoff/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/Muennighoff/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/Muennighoff/subscriptions', 'organizations_url': 'https://api.github.com/users/Muennighoff/orgs', 'repos_url': 'https://api.github.com/users/Muennighoff/repos', 'events_url': 'https://api.github.com/users/Muennighoff/events{/privacy}', 'received_events_url': 'https://api.github.com/users/Muennighoff/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-05-05T20:06:52Z', 'updated_at': '2023-05-05T20:06:52Z', 'author_association': 'CONTRIBUTOR', 'body': 'I see, it\'s not compatible w/ regex right?\r\ne.g.\r\n`load_dataset("json", data_files="https://huggingface.co/datasets/bigscience/xP3/resolve/main/ur/*")`', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1536721077/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1537502132', 'html_url': 'https://github.com/huggingface/datasets/issues/5825#issuecomment-1537502132', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5825', 'id': 1537502132, 'node_id': 'IC_kwDODunzps5bpGu0', 'user': {'login': 'mariosasko', 'id': 47462742, 'node_id': 'MDQ6VXNlcjQ3NDYyNzQy', 'avatar_url': 'https://avatars.githubusercontent.com/u/47462742?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/mariosasko', 'html_url': 'https://github.com/mariosasko', 'followers_url': 'https://api.github.com/users/mariosasko/followers', 'following_url': 'https://api.github.com/users/mariosasko/following{/other_user}', 'gists_url': 'https://api.github.com/users/mariosasko/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/mariosasko/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/mariosasko/subscriptions', 'organizations_url': 'https://api.github.com/users/mariosasko/orgs', 'repos_url': 'https://api.github.com/users/mariosasko/repos', 'events_url': 'https://api.github.com/users/mariosasko/events{/privacy}', 'received_events_url': 'https://api.github.com/users/mariosasko/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-05-07T17:43:16Z', 'updated_at': '2023-05-07T17:43:46Z', 'author_association': 'CONTRIBUTOR', 'body': '> I see, it\'s not compatible w/ regex right? e.g. `load_dataset("json", data_files="https://huggingface.co/datasets/bigscience/xP3/resolve/main/ur/*")`\r\n\r\nIt should work for patterns that "reference" the local filesystem, but to make this work with the Hub, we must implement https://github.com/huggingface/datasets/issues/5281 first.\r\n\r\nIn the meantime, you can fetch these glob files with `HfFileSystem` and pass them as a list to `load_dataset`:\r\n```python\r\nfrom datasets import load_dataset\r\nfrom huggingface_hub import HfFileSystem, hf_hub_url # `HfFileSystem` requires the latest version of `huggingface_hub`\r\n\r\nfs = HfFileSystem()\r\nglob_files = fs.glob("datasets/bigscience/xP3/ur/*")\r\n# convert fsspec URLs to HTTP URLs\r\nresolved_paths = [fs.resolve_path(file) for file in glob_files]\r\ndata_files = [hf_hub_url(resolved_path.repo_id, resolved_path.path_in_repo, repo_type=resolved_path.repo_type) for resolved_path in resolved_paths]\r\n\r\nds = load_dataset("json", data_files=data_files)\r\n```', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1537502132/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}]
[{'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1536167086', 'html_url': 'https://github.com/huggingface/datasets/pull/5824#issuecomment-1536167086', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5824', 'id': 1536167086, 'node_id': 'IC_kwDODunzps5bkAyu', 'user': {'login': 'HuggingFaceDocBuilderDev', 'id': 99929124, 'node_id': 'U_kgDOBfTMJA', 'avatar_url': 'https://avatars.githubusercontent.com/u/99929124?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/HuggingFaceDocBuilderDev', 'html_url': 'https://github.com/HuggingFaceDocBuilderDev', 'followers_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/followers', 'following_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/following{/other_user}', 'gists_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/subscriptions', 'organizations_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/orgs', 'repos_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/repos', 'events_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/events{/privacy}', 'received_events_url': 'https://api.github.com/users/HuggingFaceDocBuilderDev/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-05-05T12:11:03Z', 'updated_at': '2023-05-05T12:34:55Z', 'author_association': 'NONE', 'body': '_The documentation is not available anymore as the PR was closed or merged._', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1536167086/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1536201888', 'html_url': 'https://github.com/huggingface/datasets/pull/5824#issuecomment-1536201888', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5824', 'id': 1536201888, 'node_id': 'IC_kwDODunzps5bkJSg', 'user': {'login': 'github-actions[bot]', 'id': 41898282, 'node_id': 'MDM6Qm90NDE4OTgyODI=', 'avatar_url': 'https://avatars.githubusercontent.com/in/15368?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/github-actions%5Bbot%5D', 'html_url': 'https://github.com/apps/github-actions', 'followers_url': 'https://api.github.com/users/github-actions%5Bbot%5D/followers', 'following_url': 'https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}', 'gists_url': 'https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/github-actions%5Bbot%5D/subscriptions', 'organizations_url': 'https://api.github.com/users/github-actions%5Bbot%5D/orgs', 'repos_url': 'https://api.github.com/users/github-actions%5Bbot%5D/repos', 'events_url': 'https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}', 'received_events_url': 'https://api.github.com/users/github-actions%5Bbot%5D/received_events', 'type': 'Bot', 'site_admin': False}, 'created_at': '2023-05-05T12:39:14Z', 'updated_at': '2023-05-05T12:39:14Z', 'author_association': 'NONE', 'body': '<details>\n<summary>Show benchmarks</summary>\n\nPyArrow==8.0.0\n\n<details>\n<summary>Show updated benchmarks!</summary>\n\n### Benchmark: benchmark_array_xd.json\n\n| metric | read_batch_formatted_as_numpy after write_array2d | read_batch_formatted_as_numpy after write_flattened_sequence | read_batch_formatted_as_numpy after write_nested_sequence | read_batch_unformated after write_array2d | read_batch_unformated after write_flattened_sequence | read_batch_unformated after write_nested_sequence | read_col_formatted_as_numpy after write_array2d | read_col_formatted_as_numpy after write_flattened_sequence | read_col_formatted_as_numpy after write_nested_sequence | read_col_unformated after write_array2d | read_col_unformated after write_flattened_sequence | read_col_unformated after write_nested_sequence | read_formatted_as_numpy after write_array2d | read_formatted_as_numpy after write_flattened_sequence | read_formatted_as_numpy after write_nested_sequence | read_unformated after write_array2d | read_unformated after write_flattened_sequence | read_unformated after write_nested_sequence | write_array2d | write_flattened_sequence | write_nested_sequence |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.007658 / 0.011353 (-0.003695) | 0.005497 / 0.011008 (-0.005511) | 0.097142 / 0.038508 (0.058633) | 0.034602 / 0.023109 (0.011493) | 0.304191 / 0.275898 (0.028293) | 0.329103 / 0.323480 (0.005624) | 0.005936 / 0.007986 (-0.002049) | 0.004324 / 0.004328 (-0.000004) | 0.073387 / 0.004250 (0.069137) | 0.049657 / 0.037052 (0.012604) | 0.301352 / 0.258489 (0.042863) | 0.343095 / 0.293841 (0.049254) | 0.036767 / 0.128546 (-0.091779) | 0.012438 / 0.075646 (-0.063208) | 0.333804 / 0.419271 (-0.085468) | 0.064557 / 0.043533 (0.021024) | 0.302397 / 0.255139 (0.047258) | 0.319739 / 0.283200 (0.036540) | 0.119264 / 0.141683 (-0.022418) | 1.465309 / 1.452155 (0.013155) | 1.578194 / 1.492716 (0.085478) |\n\n### Benchmark: benchmark_getitem\\_100B.json\n\n| metric | get_batch_of\\_1024\\_random_rows | get_batch_of\\_1024\\_rows | get_first_row | get_last_row |\n|--------|---|---|---|---|\n| new / old (diff) | 0.256552 / 0.018006 (0.238545) | 0.555344 / 0.000490 (0.554854) | 0.004845 / 0.000200 (0.004645) | 0.000082 / 0.000054 (0.000027) |\n\n### Benchmark: benchmark_indices_mapping.json\n\n| metric | select | shard | shuffle | sort | train_test_split |\n|--------|---|---|---|---|---|\n| new / old (diff) | 0.027215 / 0.037411 (-0.010197) | 0.107071 / 0.014526 (0.092545) | 0.116343 / 0.176557 (-0.060213) | 0.172646 / 0.737135 (-0.564490) | 0.123366 / 0.296338 (-0.172973) |\n\n### Benchmark: benchmark_iterating.json\n\n| metric | read 5000 | read 50000 | read_batch 50000 10 | read_batch 50000 100 | read_batch 50000 1000 | read_formatted numpy 5000 | read_formatted pandas 5000 | read_formatted tensorflow 5000 | read_formatted torch 5000 | read_formatted_batch numpy 5000 10 | read_formatted_batch numpy 5000 1000 | shuffled read 5000 | shuffled read 50000 | shuffled read_batch 50000 10 | shuffled read_batch 50000 100 | shuffled read_batch 50000 1000 | shuffled read_formatted numpy 5000 | shuffled read_formatted_batch numpy 5000 10 | shuffled read_formatted_batch numpy 5000 1000 |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.411421 / 0.215209 (0.196212) | 4.126028 / 2.077655 (2.048373) | 1.975826 / 1.504120 (0.471706) | 1.784404 / 1.541195 (0.243210) | 1.848697 / 1.468490 (0.380207) | 0.686400 / 4.584777 (-3.898377) | 3.677649 / 3.745712 (-0.068063) | 2.077787 / 5.269862 (-3.192075) | 1.310912 / 4.565676 (-3.254764) | 0.083980 / 0.424275 (-0.340295) | 0.012183 / 0.007607 (0.004575) | 0.506969 / 0.226044 (0.280924) | 5.094730 / 2.268929 (2.825802) | 2.419790 / 55.444624 (-53.024834) | 2.106592 / 6.876477 (-4.769884) | 2.244309 / 2.142072 (0.102237) | 0.814312 / 4.805227 (-3.990915) | 0.167872 / 6.500664 (-6.332792) | 0.065339 / 0.075469 (-0.010130) |\n\n### Benchmark: benchmark_map_filter.json\n\n| metric | filter | map fast-tokenizer batched | map identity | map identity batched | map no-op batched | map no-op batched numpy | map no-op batched pandas | map no-op batched pytorch | map no-op batched tensorflow |\n|--------|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 1.193314 / 1.841788 (-0.648474) | 14.980621 / 8.074308 (6.906313) | 14.352452 / 10.191392 (4.161060) | 0.164531 / 0.680424 (-0.515893) | 0.017432 / 0.534201 (-0.516769) | 0.422193 / 0.579283 (-0.157090) | 0.410047 / 0.434364 (-0.024317) | 0.497011 / 0.540337 (-0.043326) | 0.581395 / 1.386936 (-0.805541) |\n\n</details>\nPyArrow==latest\n\n<details>\n<summary>Show updated benchmarks!</summary>\n\n### Benchmark: benchmark_array_xd.json\n\n| metric | read_batch_formatted_as_numpy after write_array2d | read_batch_formatted_as_numpy after write_flattened_sequence | read_batch_formatted_as_numpy after write_nested_sequence | read_batch_unformated after write_array2d | read_batch_unformated after write_flattened_sequence | read_batch_unformated after write_nested_sequence | read_col_formatted_as_numpy after write_array2d | read_col_formatted_as_numpy after write_flattened_sequence | read_col_formatted_as_numpy after write_nested_sequence | read_col_unformated after write_array2d | read_col_unformated after write_flattened_sequence | read_col_unformated after write_nested_sequence | read_formatted_as_numpy after write_array2d | read_formatted_as_numpy after write_flattened_sequence | read_formatted_as_numpy after write_nested_sequence | read_unformated after write_array2d | read_unformated after write_flattened_sequence | read_unformated after write_nested_sequence | write_array2d | write_flattened_sequence | write_nested_sequence |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.007214 / 0.011353 (-0.004139) | 0.005449 / 0.011008 (-0.005559) | 0.074320 / 0.038508 (0.035812) | 0.034261 / 0.023109 (0.011152) | 0.378265 / 0.275898 (0.102367) | 0.414419 / 0.323480 (0.090939) | 0.005804 / 0.007986 (-0.002182) | 0.004205 / 0.004328 (-0.000124) | 0.073266 / 0.004250 (0.069015) | 0.050444 / 0.037052 (0.013392) | 0.372999 / 0.258489 (0.114510) | 0.436032 / 0.293841 (0.142191) | 0.035432 / 0.128546 (-0.093114) | 0.012581 / 0.075646 (-0.063065) | 0.085777 / 0.419271 (-0.333495) | 0.046902 / 0.043533 (0.003369) | 0.378732 / 0.255139 (0.123593) | 0.401746 / 0.283200 (0.118547) | 0.113398 / 0.141683 (-0.028285) | 1.463851 / 1.452155 (0.011696) | 1.566387 / 1.492716 (0.073670) |\n\n### Benchmark: benchmark_getitem\\_100B.json\n\n| metric | get_batch_of\\_1024\\_random_rows | get_batch_of\\_1024\\_rows | get_first_row | get_last_row |\n|--------|---|---|---|---|\n| new / old (diff) | 0.261246 / 0.018006 (0.243240) | 0.546730 / 0.000490 (0.546241) | 0.005245 / 0.000200 (0.005045) | 0.000103 / 0.000054 (0.000048) |\n\n### Benchmark: benchmark_indices_mapping.json\n\n| metric | select | shard | shuffle | sort | train_test_split |\n|--------|---|---|---|---|---|\n| new / old (diff) | 0.029441 / 0.037411 (-0.007970) | 0.111834 / 0.014526 (0.097308) | 0.122411 / 0.176557 (-0.054145) | 0.171288 / 0.737135 (-0.565847) | 0.130338 / 0.296338 (-0.166001) |\n\n### Benchmark: benchmark_iterating.json\n\n| metric | read 5000 | read 50000 | read_batch 50000 10 | read_batch 50000 100 | read_batch 50000 1000 | read_formatted numpy 5000 | read_formatted pandas 5000 | read_formatted tensorflow 5000 | read_formatted torch 5000 | read_formatted_batch numpy 5000 10 | read_formatted_batch numpy 5000 1000 | shuffled read 5000 | shuffled read 50000 | shuffled read_batch 50000 10 | shuffled read_batch 50000 100 | shuffled read_batch 50000 1000 | shuffled read_formatted numpy 5000 | shuffled read_formatted_batch numpy 5000 10 | shuffled read_formatted_batch numpy 5000 1000 |\n|--------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 0.433405 / 0.215209 (0.218196) | 4.315790 / 2.077655 (2.238135) | 2.121934 / 1.504120 (0.617814) | 1.924123 / 1.541195 (0.382928) | 2.029077 / 1.468490 (0.560587) | 0.710245 / 4.584777 (-3.874532) | 3.844393 / 3.745712 (0.098681) | 3.576580 / 5.269862 (-1.693281) | 1.930985 / 4.565676 (-2.634691) | 0.092186 / 0.424275 (-0.332090) | 0.012307 / 0.007607 (0.004700) | 0.533722 / 0.226044 (0.307677) | 5.324447 / 2.268929 (3.055519) | 2.615451 / 55.444624 (-52.829174) | 2.282310 / 6.876477 (-4.594167) | 2.319847 / 2.142072 (0.177774) | 0.849364 / 4.805227 (-3.955864) | 0.172722 / 6.500664 (-6.327942) | 0.064721 / 0.075469 (-0.010748) |\n\n### Benchmark: benchmark_map_filter.json\n\n| metric | filter | map fast-tokenizer batched | map identity | map identity batched | map no-op batched | map no-op batched numpy | map no-op batched pandas | map no-op batched pytorch | map no-op batched tensorflow |\n|--------|---|---|---|---|---|---|---|---|---|\n| new / old (diff) | 1.289942 / 1.841788 (-0.551846) | 15.875062 / 8.074308 (7.800754) | 14.784682 / 10.191392 (4.593290) | 0.144432 / 0.680424 (-0.535991) | 0.017703 / 0.534201 (-0.516498) | 0.424357 / 0.579283 (-0.154926) | 0.419078 / 0.434364 (-0.015286) | 0.489331 / 0.540337 (-0.051006) | 0.585284 / 1.386936 (-0.801652) |\n\n</details>\n</details>\n\n![](https://cml.dev/watermark.png#e3f4f124a1b118a5bfff5bae76b25a68aedbebbc "CML watermark")\n', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1536201888/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}]

[{'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1536206488', 'html_url': 'https://github.com/huggingface/datasets/issues/5823#issuecomment-1536206488', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5823', 'id': 1536206488, 'node_id': 'IC_kwDODunzps5bkKaY', 'user': {'login': 'lhoestq', 'id': 42851186, 'node_id': 'MDQ6VXNlcjQyODUxMTg2', 'avatar_url': 'https://avatars.githubusercontent.com/u/42851186?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/lhoestq', 'html_url': 'https://github.com/lhoestq', 'followers_url': 'https://api.github.com/users/lhoestq/followers', 'following_url': 'https://api.github.com/users/lhoestq/following{/other_user}', 'gists_url': 'https://api.github.com/users/lhoestq/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/lhoestq/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/lhoestq/subscriptions', 'organizations_url': 'https://api.github.com/users/lhoestq/orgs', 'repos_url': 'https://api.github.com/users/lhoestq/repos', 'events_url': 'https://api.github.com/users/lhoestq/events{/privacy}', 'received_events_url': 'https://api.github.com/users/lhoestq/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-05-05T12:43:16Z', 'updated_at': '2023-05-05T12:43:28Z', 'author_association': 'MEMBER', 'body': 'Hi ! Can you try adding the `s3://` prefix ?\r\n```python\r\nf"s3://{s3_bucket}/{s3_dir}/{dataset_name}"\r\n```', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1536206488/reactions', 'total_count': 1, '+1': 1, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1536391793', 'html_url': 'https://github.com/huggingface/datasets/issues/5823#issuecomment-1536391793', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5823', 'id': 1536391793, 'node_id': 'IC_kwDODunzps5bk3px', 'user': {'login': 'thejamesmarq', 'id': 5233185, 'node_id': 'MDQ6VXNlcjUyMzMxODU=', 'avatar_url': 'https://avatars.githubusercontent.com/u/5233185?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/thejamesmarq', 'html_url': 'https://github.com/thejamesmarq', 'followers_url': 'https://api.github.com/users/thejamesmarq/followers', 'following_url': 'https://api.github.com/users/thejamesmarq/following{/other_user}', 'gists_url': 'https://api.github.com/users/thejamesmarq/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/thejamesmarq/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/thejamesmarq/subscriptions', 'organizations_url': 'https://api.github.com/users/thejamesmarq/orgs', 'repos_url': 'https://api.github.com/users/thejamesmarq/repos', 'events_url': 'https://api.github.com/users/thejamesmarq/events{/privacy}', 'received_events_url': 'https://api.github.com/users/thejamesmarq/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-05-05T15:01:17Z', 'updated_at': '2023-05-05T15:01:17Z', 'author_association': 'NONE', 'body': 'Ugh, yeah that was it. Thank you!', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1536391793/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}]
[{'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1536216492', 'html_url': 'https://github.com/huggingface/datasets/issues/5822#issuecomment-1536216492', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5822', 'id': 1536216492, 'node_id': 'IC_kwDODunzps5bkM2s', 'user': {'login': 'lhoestq', 'id': 42851186, 'node_id': 'MDQ6VXNlcjQyODUxMTg2', 'avatar_url': 'https://avatars.githubusercontent.com/u/42851186?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/lhoestq', 'html_url': 'https://github.com/lhoestq', 'followers_url': 'https://api.github.com/users/lhoestq/followers', 'following_url': 'https://api.github.com/users/lhoestq/following{/other_user}', 'gists_url': 'https://api.github.com/users/lhoestq/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/lhoestq/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/lhoestq/subscriptions', 'organizations_url': 'https://api.github.com/users/lhoestq/orgs', 'repos_url': 'https://api.github.com/users/lhoestq/repos', 'events_url': 'https://api.github.com/users/lhoestq/events{/privacy}', 'received_events_url': 'https://api.github.com/users/lhoestq/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-05-05T12:51:12Z', 'updated_at': '2023-05-05T12:51:12Z', 'author_association': 'MEMBER', 'body': 'Hi ! Can you try with a more recent version of `datasets` ?', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1536216492/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1544654481', 'html_url': 'https://github.com/huggingface/datasets/issues/5822#issuecomment-1544654481', 'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/5822', 'id': 1544654481, 'node_id': 'IC_kwDODunzps5cEY6R', 'user': {'login': 'paulbauriegel', 'id': 20282916, 'node_id': 'MDQ6VXNlcjIwMjgyOTE2', 'avatar_url': 'https://avatars.githubusercontent.com/u/20282916?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/paulbauriegel', 'html_url': 'https://github.com/paulbauriegel', 'followers_url': 'https://api.github.com/users/paulbauriegel/followers', 'following_url': 'https://api.github.com/users/paulbauriegel/following{/other_user}', 'gists_url': 'https://api.github.com/users/paulbauriegel/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/paulbauriegel/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/paulbauriegel/subscriptions', 'organizations_url': 'https://api.github.com/users/paulbauriegel/orgs', 'repos_url': 'https://api.github.com/users/paulbauriegel/repos', 'events_url': 'https://api.github.com/users/paulbauriegel/events{/privacy}', 'received_events_url': 'https://api.github.com/users/paulbauriegel/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2023-05-11T20:45:53Z', 'updated_at': '2023-05-11T20:45:53Z', 'author_association': 'NONE', 'body': 'Ok, yes it worked with the most recent version. Thanks', 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/1544654481/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'performed_via_github_app': None}]

The final step is to push our dataset to the Hub. Let's take a look at how we can do that.

### Uploading the dataset to the Hugging Face Hub

In [122]:
HTML('<iframe width="640" height="360" src="https://www.youtube.com/embed/HaN6qCr_Afc" allowfullscreen></iframe>')

Now that we have our augmented dataset, it's time to push it to the Hub so we can share it with the community! Uploading a dataset is very simple: just like models and tokenizers from 🤗 Transformers, we can use a `push_to_hub()` method to push a dataset. To do that we need an authentication token, which can be obtained by first logging into the Hugging Face Hub with the `notebook_login()` function. But for simplicity, we use the `login()` function instead, since it allows us to run the entire notebook without having to pass a token manually for authentication.

In [123]:
# We have already authenticated above in order to push to the hub.
# HUGGINGFACE_TOKEN = os.getenv("HUGGINGFACE_TOKEN")
# from huggingface_hub import login
# login(token=HUGGINGFACE_TOKEN)

The `notebook_login` function would create a widget where you can enter your username and an API token that would be saved in *~/.huggingface/token*. If you're running the code in a terminal, you can log in via the CLI instead:
```
huggingface-cli login
```
Once we've done this, we can upload our dataset by running:

In [124]:
issues_with_comments_dataset.push_to_hub("github_issues") # = "mdroth/github_issues_10" on the huggingface hub

NameError: name 'issues_with_comments_dataset' is not defined

From here, anyone can download the dataset by simply providing `load_dataset()` with the repository ID as the path argument:

In [125]:
remote_dataset = load_dataset("mdroth/github_issues", split="train")
remote_dataset

DatasetNotFoundError: Dataset 'mdroth/github_issues' doesn't exist on the Hub or cannot be accessed.

Cool, we've pushed our dataset to the Hub and it's available for others to use! There's just one important thing left to do: adding a dataset card that explains how the corpus was created and provides other useful information for the community.

> 💡 <font color="darkgreen"> You can also upload a dataset to the Hugging Face Hub directly from the terminal by using huggingface-cli and a bit of Git magic. See the 🤗 Datasets guide for details on how to do this.</font>

> ✏️ Try it out! <font color="darkgreen">Use your Hugging Face Hub username and password to obtain a token and create an empty repository called `github_issues`. Remember to **never save your credentials** in Colab or any other repository, as this information can be exploited by bad actors.</font>

In [126]:
# Trying it out
## data splits: test (20%), validation (16%), training (64%)
## current state: training = 100% => split off 16% for validation
## https://discuss.huggingface.co/t/how-to-split-main-dataset-into-train-dev-test-as-datasetdict/1090/9
from datasets import DatasetDict
train_validTest = issues_with_comments_dataset_10.train_test_split(shuffle=True, seed=42, test_size=0.36)
valid_test = train_validTest["test"].train_test_split(shuffle=True, seed=42, test_size=5/9)
github_issues_dataset_10 = DatasetDict({
    "train": train_validTest["train"],
    "valid": valid_test["train"],
    "test": valid_test["test"]
})
print(github_issues_dataset_10)
## pushing to hub
## https://discuss.huggingface.co/t/save-datasetdict-to-huggingface-hub/12075/4
github_issues_dataset_10.push_to_hub(repo_id="github_issues_10")

NameError: name 'issues_with_comments_dataset_10' is not defined

Create a [git submodule](https://git-scm.com/book/en/v2/Git-Tools-Submodules#) in preparation of the next steps.

In [127]:
import pathlib
local_repo_path = "sections/section_5/data"
submodule_path = pathlib.Path(local_repo_path) / "github_issues_10"
if not submodule_path.exists():
    os.system(f"cd {local_repo_path} && git submodule add https://huggingface.co/datasets/mdroth/github_issues_10")
else:
    print(f"The git submodule already exists here: {submodule_path}")

The git submodule already exists here: sections/section_5/data/github_issues_10

Next, let's clone the repository from the Hub to our local machine and copy our dataset file into it. 🤗 Hub provides a handy `Repository` class that wraps many of the common Git commands, so to clone the remote repository we simply need to provide the URL and local path we wish to clone to:

In [ ]:
# run {!git lfs update --force} if necessary
repo_url = "https://huggingface.co/datasets/mdroth/github_issues_10/tree/main"
# https://huggingface.co/docs/huggingface_hub/main/en/package_reference/repository
repo_url = "https://huggingface.co/datasets/mdroth/github_issues_10"
#repo_url = "mdroth/github_issues_10"
from huggingface_hub import Repository
repo = Repository(local_dir="sections/section_5/data/github_issues_10", clone_from=repo_url)
repo.git_pull(lfs=True)
#!cp "sections/section_5/data/issues-datasets-with-comments.jsonl" "sections/section_5/data/github-issues/"
repo

By default, various file extensions (such as *.bin*, *.gz*, and *.zip*) are tracked with Git LFS so that large files can be versioned within the same Git workflow. You can find a list of tracked file extensions inside the repository's *.gitattributes* file. To include the JSON Lines format in the list, we can run the following command:

In [ ]:
repo.lfs_track("*.jsonl")

Then we can use `Repository.push_to_hub()` to push the dataset to the Hub:

In [ ]:
repo.push_to_hub()

If we navigate to the URL contained in `repo_url`, we should now see that our dataset file has been uploaded.

<img style="float=center;" width="70%" src="sections/section_5/images/lewtun_github_issues.png">

From here, anyone can download the dataset by simply providing `load_dataset()` with the repository ID as the `path` argument:

In [ ]:
remote_dataset = load_dataset("mdroth/github_issues_10")
remote_dataset

Cool, we've pushed our dataset to the Hub and it's available for others to use! There's just one important thing left to do: adding a *dataset card* that explains how the corpus was created and provides other useful information for the community.
> <font color="darkgreen">💡 You can also upload a dataset to the Hugging Face Hub directly from the terminal by using `huggingface-cli` and a bit of Git magic. See the [🤗 Datasets guide](https://huggingface.co/docs/datasets/share.html#add-a-community-dataset) for details on how to do this.</font>

### Creating a dataset card

Well-documented datasets are more likely to be useful to others (including your future self!), as they provide the context to enable users to decide whether the dataset is relevant to their task and to evaluate any potential biases in or risks associated with using the dataset.

On the Hugging Face Hub, this information is stored in each dataset repository's *README.md* file. There are two main steps you should take before creating this file:

1. Use the [`datasets-tagging` application](https://huggingface.co/datasets/tagging/) to create metadata tags in YAML format. These tags are used for a variety of search features on the Hugging Face Hub and ensure your dataset can be easily found by members of the community. Since we have created a custom dataset here, you'll need to clone the `datasets-tagging` repository and run the application locally. Here's what the interface looks like:

<img style="float=center;" width="70%" src="sections/section_5/images/dataset_card_assistant.png">

1. Read the [🤗 Datasets guide](https://github.com/huggingface/datasets/blob/master/templates/README_guide.md) on creating informative dataset cards and use it as a template.

You can create the *README.md* file directly on the Hub, and you can find a template dataset card in the `lewtun/github-issues` dataset repository. A screenshot of the filled-out dataset card is shown below.

<img style="float=center;" width="70%" src="sections/section_5/images/lewtun_github_issues.png">

> ✏️ Try it out! <font color="darkgreen">Use the `dataset-tagging` application and [🤗 Datasets guide](https://github.com/huggingface/datasets/blob/master/templates/README_guide.md) to complete the *README.md* file for your GitHub issues dataset.</font>

In [ ]:
# Trying it out
print("Procedure")
print('1. Read the above section on "Creating a dataset card".')
text_2 = "https://huggingface.co/spaces/huggingface/datasets-tagging"
print(f'2. Create tags with the "HuggingFace Dataset Tagger" at {text_2}.')
text_3 = "https://huggingface.co/datasets/card-creator"
print(f'3. Create a README.md file / dataset card with the "card-creator" at {text_3}.')
text_4 = "https://huggingface.co/datasets/mdroth/github_issues_10"
print(f'4. Upload the README.md file / dataset card to the model repo (in this case {text_4}):')
print('=> "Files and versions" > "Add file" > "Upload file" => Upload the README.md file')
text_5_1 = "https://huggingface.co/docs/datasets/v2.0.0/dataset_card"
text_5_2 = "https://huggingface.co/datasets/mdroth/github_issues_10"
print(f'\nSee {text_5_1} for a guide and {text_5_2} for an example.')

That's it! We've seen in this section that creating a good dataset can be quite involved, but fortunately uploading it and sharing it with the community is not. In the next section we'll use our new dataset to create a semantic search engine with 🤗 Datasets that can match questions to the most relevant issues and comments.

> ✏️ Try it out! <font color="darkgreen">Go through the steps we took in this section to create a dataset of GitHub issues for your favorite open source library (pick something other than 🤗 Datasets, of course!). For bonus points, fine-tune a multilabel classifier to predict the tags present in the `labels` field.</font>

In [ ]:
# Trying it out
import json
from datasets import DatasetDict
## load the file "transformers-issues.jsonl" that has been created by using 'fetch_issues(repo="transformers")' ...
## ... instead of 'fetch_issues()' just below the definition of the 'fetch_issues()' function further above
fetch_issues(repo="transformers")

In [ ]:
transformers_issues_dataset = transformers_issues_dataset.select_columns(["body", "labels"])
transformers_issues_dataset = transformers_issues_dataset.filter(lambda x: x["body"]!="" and x["labels"]!=[])
transformers_issues_dataset

In [ ]:
transformers_issues_dataset.filter(lambda x: x["body"]!=None and x["labels"]!=[])

In [ ]:
transformers_issues_dataset.filter(lambda x: x["body"]!=None and len(x["body"])>=100 and len(x["labels"])>=1)

In [ ]:
closed_dataset.filter(lambda x: x["pull_request"] is not None)

In [ ]:
transformers_issues_dataset["body"][:3]

In [ ]:
print(transformers_issues_dataset["labels"][7])

In [ ]:
for i, instance in enumerate(transformers_issues_dataset[:10]):
    print(f"\n\n#####\n# {i} #\n#####\n\nLabel:\t{instance}")

In [ ]:
transformers_issues_dataset["labels"][:10]

In [ ]:
transformers_issues_dataset[:10].filter(lambda item: item["labels"]!=None)

In [ ]:
transformer_issue_labels_dataset =

In [ ]:
transformers_issue_reactions_dataset = transformers_issues_dataset.filter(lambda item: item["reactions"]["total_count"]>0)
transformers_issue_reactions_dataset

In [ ]:
for instance_i in transformers_issues_dataset[5]:
    print(instance_i)

In [ ]:
transformers_issues_dataset["reactions"][0:150]

In [ ]:
for issue_i in transformers_issues_dataset[0:3]:
    if len(issue_i["body"]) > 50 and len(issue_i["body"]) < 1500 and issue_i

In [ ]:
for i in range(3):
    if transformer
    print(transformers_issues_dataset[i])#["labels"])#["name"]

In [ ]:
transformers_issues_dataset["labels"] # for each instance, get the "name" values for the following keys "name" and

In [ ]:
for label in transformers_issues_dataset["labels"]:#[:5]: # candidates: "reactions"
    if label!=[]:
        print(label[0]["name"])

In [ ]:
transformers_issues_text_dataset_1 = transformers_issues_dataset.rename_column(
    original_column_name="repository_url", new_column_name="text"
)
transformers_issues_text_dataset_0 = transformers_issues_text_dataset_1.rename_column(
    original_column_name="labels_url", new_column_name="num_labels"
)
transformers_issues_text_dataset = transformers_issues_text_dataset_0.rename_column(
    original_column_name="comments_url", new_column_name="arr_labels"
)
del transformers_issues_dataset, transformers_issues_text_dataset_0, transformers_issues_text_dataset_1
## combine the columns "title", "comments", "reactions", and "body" into a single string in the new "text" column
feature_keys = ["title", "comments", "reactions", "body"]
reaction_keys = ["+1", "-1", "laugh", "hooray", "heart", "rocket", "eyes"]
def make_text(item):
    text = ""
    for fk_i in feature_keys:
        if fk_i=="reactions":
            text += f"\n\n{fk_i.upper()}"
            reactions = item[fk_i]
            reactions_json = json.loads(json.dumps(reactions, indent = 4))
            for rk_i in reaction_keys:
                rk_iCount = reactions_json[rk_i]
                text += f"\n{rk_i}: {rk_iCount}"
        else:
            text += f"\n\n{fk_i.upper()}\n{item[fk_i]}"
    item["text"] = text
    return item
transformers_issues_text_dataset = transformers_issues_text_dataset.map(make_text)
## build labels (list of strings)
def make_labels(item):
    labels = item["labels"]
    label_list = []
    for label in labels:
        label_json = json.loads(json.dumps(label, indent=4))
        label_name = label_json["name"]
        label_list.append(label_name)
    item["labels"] = label_list
    return item
transformers_issues_text_dataset = transformers_issues_text_dataset.map(make_labels)
## build num_labels (list of numbers) ...
## ... see also https://stackoverflow.com/questions/952914/how-to-make-a-flat-list-out-of-a-list-of-lists
flat_label_list = [label for labels_i in transformers_issues_text_dataset["labels"] for label in labels_i]
unique_labels = list(set(flat_label_list))
n_unique_labels = len(unique_labels)
def make_num_labels(item):
    label_list = item["labels"]
    num_label_list = []
    for label in label_list:
        num_label = unique_labels.index(label)
        num_label_list.append(num_label)
    item["num_labels"] = num_label_list
    return item
transformers_issues_text_dataset = transformers_issues_text_dataset.map(make_num_labels)
## build arr_labels (full list of 0s and 1s)
def make_arr_labels(item):
    num_labels = item["num_labels"]
    arr_label_list = [0 for _ in range(n_unique_labels)]
    for num_label in num_labels:
        arr_label_list[num_label] = 1
    item["arr_labels"] = arr_label_list
    return item
transformers_issues_text_dataset = transformers_issues_text_dataset.map(make_arr_labels)
## filter for instances with labels!=[]
idx = 0
print(f'Before filtering\n=> Empty labels for index {idx}:\t\t{transformers_issues_text_dataset["labels"][idx]}')
transformers_issues_text_dataset = transformers_issues_text_dataset.filter(lambda x: x["labels"]!=[])
print(f'After filtering\n=> Non-empty labels for index {idx}:\t{transformers_issues_text_dataset["labels"][idx]}')
## remove all columns but "labels", "text", and "url"
keep_keys = ["text", "labels", "num_labels", "arr_labels", "url"]
remove_keys = [key for key in list(transformers_issues_text_dataset.features.keys()) if key not in keep_keys]
transformers_issues_text_dataset = transformers_issues_text_dataset.remove_columns(remove_keys)
## show dataset
print(f"\nDataset with num_labels:\n{transformers_issues_text_dataset}")
idx = 5 # 5 or 13 or (almost) anything
print(f'\n{3*"#"+" "}text{" "+71*"#"}{transformers_issues_text_dataset["text"][idx]}')
print(f'\n{3*"#"+" "}labels{" "+69*"#"}\n\n{transformers_issues_text_dataset["labels"][idx]}')
print(f'\n{3*"#"+" "}num_labels{" "+65*"#"}\n\n{transformers_issues_text_dataset["num_labels"][idx]}')
print(f'\n{3*"#"+" "}arr_labels{" "+65*"#"}\n\n{transformers_issues_text_dataset["arr_labels"][idx]}')
print(f'\n{3*"#"+" "}url{" "+72*"#"}\n\n{transformers_issues_text_dataset["url"][idx]}')
print(f'\n{80*"#"}\n')
## DatasetDict: make splits, build, print, and push to hub
train_dev = transformers_issues_text_dataset.train_test_split(shuffle=True, seed=42, test_size=0.003)
train_validTest = train_dev["train"].train_test_split(shuffle=True, seed=42, test_size=0.36)
valid_test = train_validTest["test"].train_test_split(shuffle=True, seed=42, test_size=5/9)
transformers_issues_text_dataset = DatasetDict({
    "train": train_validTest["train"],
    "valid": valid_test["train"],
    "test": valid_test["test"],
    "dev": train_dev["test"]
})
repo_id="transformers_issues_labels"
transformers_issues_text_dataset.save_to_disk(f"sections/section_5/data/GitHub-repo-{repo_id}") # save locally
transformers_issues_text_dataset.push_to_hub(repo_id=repo_id) # push to hub
transformers_issues_text_dataset

In [ ]:
transformers_issues_text_dataset

In [ ]:
# useful keys: "text", "num_labels"
# useless keys: "url", "arr_labels"
transformers_issues_text_dataset["train"]["labels"]

In [ ]:
transformers_issues_text_dataset["dev"]["arr_labels"]

In [ ]:
for key in list(transformers_issues_text_dataset["dev"].features.keys()):
    print(f"\n{key}")
    print(f"{transformers_issues_text_dataset["dev"][key]}")

In [ ]:
# still trying it out
## imports
from transformers import DataCollatorWithPadding, BertTokenizer, BertForSequenceClassification
from transformers import Trainer, TrainingArguments
import torch
## define custom trainer
class CustomTrainer(Trainer):
    def compute_loss(self, model, inputs, return_outputs=False):
        outputs = model(
            input_ids=inputs["input_ids"],
            attention_mask=inputs["attention_mask"],
            token_type_ids=inputs["token_type_ids"]
        )
        loss = torch.nn.BCEWithLogitsLoss()(outputs["logits"].float(), inputs["labels"].float())
        return (loss, outputs) if return_outputs else loss
## load dataset, tokenize, adapt columns, and apply datacollator
checkpoint = "bert-base-cased"
transformers_tokenizer = BertTokenizer.from_pretrained(checkpoint)
def transformers_tokenize_function(item):
    return transformers_tokenizer(item["text"], padding=True, truncation=True)
transformers_tokenized_datasets = (
    load_dataset("mdroth/transformers_issues_labels")
    .map(transformers_tokenize_function, batched=True)
    .remove_columns(column_names=["url", "text", "num_labels", "labels"])
    .rename_column("arr_labels", "labels")
)
transformers_data_collator = DataCollatorWithPadding(tokenizer=transformers_tokenizer)
## training arguments
training_args = TrainingArguments(
    "sections/section_5/logs/transformers_issues_model",
    load_best_model_at_end=True,
    save_strategy="epoch",
    evaluation_strategy="epoch",
    num_train_epochs=3,
    per_device_train_batch_size=4,
    per_device_eval_batch_size=4
)
## model
transformers_model = BertForSequenceClassification.from_pretrained(checkpoint, num_labels=n_unique_labels)
## trainer
trainer = CustomTrainer(
    transformers_model,
    training_args,
    train_dataset=transformers_tokenized_datasets["dev"],
    eval_dataset=transformers_tokenized_datasets["dev"],
    data_collator=transformers_data_collator,
    tokenizer=transformers_tokenizer
)
## train
trainer.train()

In [ ]:
# Trying it out
import json
from datasets import DatasetDict
## load the file "transformers-issues.jsonl" that has been created by using 'fetch_issues(repo="transformers")' ...
## ... instead of 'fetch_issues()' just below the definition of the 'fetch_issues()' function further above
fetch_issues(repo="transformers")
transformers_issues_dataset = load_dataset("json", data_files="sections/section_5/data/transformers-issues.jsonl", split="train")
## add columns "text" and "num_labels"
print(transformers_issues_dataset)
transformers_issues_text_dataset_1 = transformers_issues_dataset.rename_column(
    original_column_name="repository_url", new_column_name="text"
)
transformers_issues_text_dataset_0 = transformers_issues_text_dataset_1.rename_column(
    original_column_name="labels_url", new_column_name="num_labels"
)
transformers_issues_text_dataset = transformers_issues_text_dataset_0.rename_column(
    original_column_name="comments_url", new_column_name="arr_labels"
)
del transformers_issues_dataset, transformers_issues_text_dataset_0, transformers_issues_text_dataset_1
## combine the columns "title", "comments", "reactions", and "body" into a single string in the new "text" column
feature_keys = ["title", "comments", "reactions", "body"]
reaction_keys = ["+1", "-1", "laugh", "hooray", "heart", "rocket", "eyes"]
def make_text(item):
    text = ""
    for fk_i in feature_keys:
        if fk_i=="reactions":
            text += f"\n\n{fk_i.upper()}"
            reactions = item[fk_i]
            reactions_json = json.loads(json.dumps(reactions, indent = 4))
            for rk_i in reaction_keys:
                rk_iCount = reactions_json[rk_i]
                text += f"\n{rk_i}: {rk_iCount}"
        else:
            text += f"\n\n{fk_i.upper()}\n{item[fk_i]}"
    item["text"] = text
    return item
transformers_issues_text_dataset = transformers_issues_text_dataset.map(make_text)
## build labels (list of strings)
def make_labels(item):
    labels = item["labels"]
    label_list = []
    for label in labels:
        label_json = json.loads(json.dumps(label, indent=4))
        label_name = label_json["name"]
        label_list.append(label_name)
    item["labels"] = label_list
    return item
transformers_issues_text_dataset = transformers_issues_text_dataset.map(make_labels)
## build num_labels (list of numbers) ...
## ... see also https://stackoverflow.com/questions/952914/how-to-make-a-flat-list-out-of-a-list-of-lists
flat_label_list = [label for labels_i in transformers_issues_text_dataset["labels"] for label in labels_i]
unique_labels = list(set(flat_label_list))
n_unique_labels = len(unique_labels)
def make_num_labels(item):
    label_list = item["labels"]
    num_label_list = []
    for label in label_list:
        num_label = unique_labels.index(label)
        num_label_list.append(num_label)
    item["num_labels"] = num_label_list
    return item
transformers_issues_text_dataset = transformers_issues_text_dataset.map(make_num_labels)
## build arr_labels (full list of 0s and 1s)
def make_arr_labels(item):
    num_labels = item["num_labels"]
    arr_label_list = [0 for _ in range(n_unique_labels)]
    for num_label in num_labels:
        arr_label_list[num_label] = 1
    item["arr_labels"] = arr_label_list
    return item
transformers_issues_text_dataset = transformers_issues_text_dataset.map(make_arr_labels)
## filter for instances with labels!=[]
idx = 0
print(f'Before filtering\n=> Empty labels for index {idx}:\t\t{transformers_issues_text_dataset["labels"][idx]}')
transformers_issues_text_dataset = transformers_issues_text_dataset.filter(lambda x: x["labels"]!=[])
print(f'After filtering\n=> Non-empty labels for index {idx}:\t{transformers_issues_text_dataset["labels"][idx]}')
## remove all columns but "labels", "text", and "url"
keep_keys = ["text", "labels", "num_labels", "arr_labels", "url"]
remove_keys = [key for key in list(transformers_issues_text_dataset.features.keys()) if key not in keep_keys]
transformers_issues_text_dataset = transformers_issues_text_dataset.remove_columns(remove_keys)
## show dataset
print(f"\nDataset with num_labels:\n{transformers_issues_text_dataset}")
idx = 5 # 5 or 13 or (almost) anything
print(f'\n{3*"#"+" "}text{" "+71*"#"}{transformers_issues_text_dataset["text"][idx]}')
print(f'\n{3*"#"+" "}labels{" "+69*"#"}\n\n{transformers_issues_text_dataset["labels"][idx]}')
print(f'\n{3*"#"+" "}num_labels{" "+65*"#"}\n\n{transformers_issues_text_dataset["num_labels"][idx]}')
print(f'\n{3*"#"+" "}arr_labels{" "+65*"#"}\n\n{transformers_issues_text_dataset["arr_labels"][idx]}')
print(f'\n{3*"#"+" "}url{" "+72*"#"}\n\n{transformers_issues_text_dataset["url"][idx]}')
print(f'\n{80*"#"}\n')
## DatasetDict: make splits, build, print, and push to hub
train_dev = transformers_issues_text_dataset.train_test_split(shuffle=True, seed=421, test_size=0.003)
train_validTest = train_dev["train"].train_test_split(shuffle=True, seed=42, test_size=0.36)
valid_test = train_validTest["test"].train_test_split(shuffle=True, seed=42, test_size=5/9)
transformers_issues_text_dataset = DatasetDict({
    "train": train_validTest["train"],
    "valid": valid_test["train"],
    "test": valid_test["test"],
    "dev": train_dev["test"]
})
print(transformers_issues_text_dataset)
repo_id="transformers_issues_labels"
transformers_issues_text_dataset.save_to_disk(f"sections/section_5/data/GitHub-repo-{repo_id}") # save locally
transformers_issues_text_dataset.push_to_hub(repo_id=repo_id) # save on hub

For *Try it out!*-**bonus points**, the following cell builds and trains a multilabel classifier for the (multilabel) labels of the dataset that has just been created. See also [this discussion on the HuggingFace forum](https://discuss.huggingface.co/t/reshaping-logits-when-using-trainer/18214?u=mdroth).

In [ ]:
from transformers import BertConfig, BertForSequenceClassification

num_labels = 82  # Set to the correct number of labels in your dataset.
config = BertConfig.from_pretrained(
    checkpoint,
    num_labels=num_labels,
    problem_type="multi_label_classification"  # This sets up the model to use BCEWithLogitsLoss.
)
model = BertForSequenceClassification.from_pretrained(checkpoint, config=config)




#from transformers import BertConfig, BertForSequenceClassification, BertTokenizer, DataCollatorWithPadding, Trainer, TrainingArguments
from datasets import load_dataset

# Define checkpoint and load tokenizer
checkpoint = "bert-base-cased"
tokenizer = BertTokenizer.from_pretrained(checkpoint)

# Prepare your dataset (example using your dataset)
def tokenize_function(item):
    return tokenizer(item["text"], padding=True, truncation=True)

tokenized_datasets = (
    load_dataset("mdroth/transformers_issues_labels")
    .map(tokenize_function, batched=True)
    .remove_columns(column_names=["url", "text", "num_labels", "labels"])
    .rename_column("arr_labels", "labels")
)

data_collator = DataCollatorWithPadding(tokenizer=tokenizer)

# Specify the number of unique labels
n_unique_labels = 82  # Replace with the correct number

# Create a model configuration with problem_type set to multi_label_classification.
config = BertConfig.from_pretrained(checkpoint,
                                    num_labels=n_unique_labels,
                                    problem_type="multi_label_classification")
model = BertForSequenceClassification.from_pretrained(checkpoint, config=config)

# Define training arguments.
training_args = TrainingArguments(
    output_dir="sections/section_5/logs/transformers_issues_model",
    report_to=[],  # disable external logging
    load_best_model_at_end=True,
    save_strategy="epoch",
    evaluation_strategy="epoch",
    num_train_epochs=3,
    per_device_train_batch_size=4,
    per_device_eval_batch_size=4,
)

# Initialize the Trainer without any custom code.
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_datasets["dev"],
    eval_dataset=tokenized_datasets["dev"],
    data_collator=data_collator,
    tokenizer=tokenizer,
)

# Start training.
trainer.train()

In [ ]:
# still trying it out
## imports
from transformers import DataCollatorWithPadding, BertTokenizer, BertForSequenceClassification
from transformers import Trainer, TrainingArguments
import torch
## define custom trainer
class CustomTrainer(Trainer):
    def compute_loss(self, model, inputs, return_outputs=False):
        outputs = model(
            input_ids=inputs["input_ids"],
            attention_mask=inputs["attention_mask"],
            token_type_ids=inputs["token_type_ids"]
        )
        loss = torch.nn.BCEWithLogitsLoss()(outputs["logits"].float(), inputs["labels"].float())
        return (loss, outputs) if return_outputs else loss
## load dataset, tokenize, adapt columns, and apply datacollator
checkpoint = "bert-base-cased"
transformers_tokenizer = BertTokenizer.from_pretrained(checkpoint)
def transformers_tokenize_function(item):
    return transformers_tokenizer(item["text"], padding=True, truncation=True)
transformers_tokenized_datasets = (
    load_dataset("mdroth/transformers_issues_labels")
    .map(transformers_tokenize_function, batched=True)
    .remove_columns(column_names=["url", "text", "num_labels", "labels"])
    .rename_column("arr_labels", "labels")
)
transformers_data_collator = DataCollatorWithPadding(tokenizer=transformers_tokenizer)
## training arguments
training_args = TrainingArguments(
    "sections/section_5/logs/transformers_issues_model",
    report_to=[],
    load_best_model_at_end=True,
    save_strategy="epoch",
    evaluation_strategy="epoch",
    num_train_epochs=3,
    per_device_train_batch_size=4,
    per_device_eval_batch_size=4
)
## model
transformers_model = BertForSequenceClassification.from_pretrained(checkpoint, num_labels=n_unique_labels)
## trainer
trainer = CustomTrainer(
    transformers_model,
    training_args,
    train_dataset=transformers_tokenized_datasets["dev"],
    eval_dataset=transformers_tokenized_datasets["dev"],
    data_collator=transformers_data_collator,
    tokenizer=transformers_tokenizer
)
## train
trainer.train()

**Restart the kernel in preparation for the next section.**

In [ ]:
import os
os._exit(00)

## [Semantic search with FAISS](https://huggingface.co/course/chapter5/6?fw=pt)

In [section 5](https://huggingface.co/course/chapter5/5), we created a dataset of GitHub issues and comments from the 🤗 Datasets repository. In this section we'll use this information to build a search engine that can help us find answers to our most pressing questions about the library!

In [ ]:
from IPython.display import HTML
HTML('<iframe width="640" height="360" src="https://www.youtube.com/embed/OATCgQtNX2o" allowfullscreen></iframe>')

### Using embeddings for semantic search
As we saw in [Chapter 1](https://huggingface.co/course/chapter1), Transformer-based language models represent each token in a span of text as an *embedding vector*. It turns out that one can "pool" the individual embeddings to create a vector representation for whole sentences, paragraphs, or (in some cases) documents. These embeddings can then be used to find similar documents in the corpus by computing the dot-product similarity (or some other similarity metric) between each embedding and returning the documents with the greatest overlap.

In this section we'll use embeddings to develop a semantic search engine. These search engines offer several advantages over conventional approaches that are based on matching keywords in a query with the documents.

<img style="float=center;" width="30%" src="sections/section_5/images/relevant_doc.png">

### Loading and preparing the dataset
The first thing we need to do is download our dataset of GitHub issues, so let's use the 🤗 Hub library to resolve the URL where our file is stored on the Hugging Face Hub:

In [ ]:
from huggingface_hub import hf_hub_url
data_files = hf_hub_url(
    repo_id="lewtun/github-issues",
    filename="datasets-issues-with-comments.jsonl",
    repo_type="dataset"
)
data_files

With the URL stored in data_files, we can then load the remote dataset using the method introduced in [section 2](https://huggingface.co/course/chapter5/2):

In [ ]:
from datasets import load_dataset
issues_dataset = load_dataset("json", data_files=data_files, split="train")
issues_dataset

Here we've specified the default train split in `load_dataset()`, so it returns a `Dataset` instead of a `DatasetDict`. The first order of business is to filter out the pull requests, as these tend to be rarely used for answering user queries and will introduce noise in our search engine. As should be familiar by now, we can use the `Dataset.filter()` function to exclude these rows in our dataset. While we're at it, let's also filter out rows with no comments, since these provide no answers to user queries:

In [ ]:
issues_dataset = issues_dataset.filter(lambda x: (x["is_pull_request"]==False and len(x["comments"]) > 0))
issues_dataset

We can see that there are a lot of columns in our dataset, most of which we don't need to build our search engine. From a search perspective, the most informative columns are `title`, `body`, and `comments`, while `html_url` provides us with a link back to the source issue. Let's use the `Dataset.remove_columns()` function to drop the rest:

In [ ]:
columns = issues_dataset.column_names
columns_to_keep = ["title", "body", "html_url", "comments"]
columns_to_remove = set(columns_to_keep).symmetric_difference(columns)
issues_dataset = issues_dataset.remove_columns(columns_to_remove)
issues_dataset

To create our embeddings we'll augment each comment with the issue's title and body, since these fields often include useful contextual information. Because our comments column is currently a list of comments for each issue, we need to "explode" the column so that each row consists of an (`html_url`, `title`, `body`, `comment`) tuple. In Pandas, we can do this with the [`DataFrame.explode()` function](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.explode.html), which creates a new row for each element in a list-like column, while replicating all the other column values. To see this in action, let's first switch to the Pandas `DataFrame` format:

In [ ]:
issues_dataset.set_format("pandas")
df = issues_dataset[:]
df

If we inspect the first row in this `DataFrame` we can see there are two comments associated with this issue:

In [ ]:
print(df["comments"][0].tolist())
len(df["comments"][0].tolist())

When we explode `df`, we expect to get one row for each of these comments. Let's check if that's the case:

In [ ]:
comments_df = df.explode("comments", ignore_index=True)
comments_df.head(9)

Great, we can see the rows have been replicated, with the `comments` column containing the individual comments! Now that we're finished with Pandas, we can quickly switch back to a `Dataset` by loading the `DataFrame` in memory:

In [ ]:
from datasets import Dataset
comments_dataset = Dataset.from_pandas(comments_df)
comments_dataset

Okay, this has given us a few thousand comments to work with!
> ✏️ Try it out! <font color="darkgreen">See if you can use `Dataset.map()` to explode the `comments` column of `issues_dataset` *without* resorting to the use of Pandas. This is a little tricky; you might find the ["Batch mapping"](https://huggingface.co/docs/datasets/v2.0.0/about_map_batch?batch-mapping#batch-mapping) section of the 🤗 Datasets documentation useful for this task.</font>

In [ ]:
# Trying it out
def explode_comments(items):
    # initialize empty arrays "html_url_arr = []", "title_arr = []", "comments_arr = []", and "body_arr = []"
    # loop over items
    # for each item:
    ## get the values for "html_url", "title", and "body"
    ## get "n_i" = the number of copies that need to be made (length of this item's "comments_arr" array)
    ## loop index "ii" over "range(n_i)"
    ### in step ii of the loop, get the ii-th value (= i-th comment) of the current item's "comments_arr" array
    ### append all current values (html_url, title, comment, body) to their corresponding arrays
    # build the dictionary and return it
    html_url_arr = []
    title_arr = []
    comments_arr = [] # only nested array
    body_arr = []
    n_items = len(items["html_url"])
    for i in range(n_items):
        html_url = items["html_url"][i]
        title = items["title"][i]
        body = items["body"][i]
        n_i = len(items["comments"][i])
        for ii in range(n_i):
            comment = items["comments"][i][ii]
            html_url_arr.append(html_url)
            title_arr.append(title)
            comments_arr.append(comment)
            body_arr.append(body)
    return {"html_url": html_url_arr, "title": title_arr, "comments": comments_arr, "body": body_arr}
# https://huggingface.co/docs/datasets/v2.0.0/about_map_batch?batch-mapping#batch-mapping
try_issues_dataset_exploded_comments = issues_dataset.map(explode_comments, batched=True)
# https://discuss.huggingface.co/t/how-do-you-rename-a-column-in-a-dataset/15121
try_issues_dataset_exploded_comments = try_issues_dataset_exploded_comments.rename_column("comments", "comment")
print("try_issues_dataset_exploded_comments")
try_issues_dataset_exploded_comments.set_format("pandas")
try_issues_dataset_exploded_comments[:]

Now that we have one comment per row, let's create a new `comments_length` column that contains the number of words per comment:

In [ ]:
comments_dataset = comments_dataset.map(lambda x: {"comment_length": len(x["comments"].split())})

We can use this new column to filter out short comments, which typically include things like "cc @lewtun" or "Thanks!" that are not relevant for our search engine. There's no precise number to select for the filter, but around 15 words seems like a good start:

In [ ]:
comments_dataset = comments_dataset.filter(lambda x: x["comment_length"] > 15)
comments_dataset

Having cleaned up our dataset a bit, let's concatenate the issue title, description, and comments together in a new `text` column. As usual, we'll write a simple function that we can pass to `Dataset.map()`:

In [ ]:
def concatenate_text(examples):
    return {"text": examples["title"] + " \n " + examples["body"] + " \n " + examples["comments"]}
comments_dataset = comments_dataset.map(concatenate_text)

We're finally ready to create some embeddings! Let's take a look.

### Creating text embeddings
We saw in [Chapter 2](https://huggingface.co/course/chapter2) that we can obtain token embeddings by using the `AutoModel` class. All we need to do is pick a suitable checkpoint to load the model from. Fortunately, there's a library called `sentence-transformers` that is dedicated to creating embeddings. As described in the library's [documentation](https://www.sbert.net/examples/applications/semantic-search/README.html#symmetric-vs-asymmetric-semantic-search), our use case is an example of *asymmetric semantic search* because we have a short query whose answer we'd like to find in a longer document, like a an issue comment. The handy [model overview table](https://www.sbert.net/docs/pretrained_models.html#model-overview) in the documentation indicates that the `multi-qa-mpnet-base-dot-v1` checkpoint has the best performance for semantic search, so we'll use that for our application. We'll also load the tokenizer using the same checkpoint:

In [ ]:
from transformers import AutoTokenizer, AutoModel
model_ckpt = "sentence-transformers/multi-qa-mpnet-base-dot-v1"
tokenizer = AutoTokenizer.from_pretrained(model_ckpt)
model = AutoModel.from_pretrained(model_ckpt)

To speed up the embedding process, it helps to place the model and inputs on a GPU device, so let's do that now:

In [ ]:
import torch
device = torch.device("cuda" if torch.cuda.is_available() else "cpu") # use gpu if possible, else cpu
print(device)
model.to(device)

As we mentioned earlier, we'd like to represent each entry in our GitHub issues corpus as a single vector, so we need to "pool" or average our token embeddings in some way. One popular approach is to perform *CLS pooling* on our model's outputs, where we simply collect the last hidden state for the special `[CLS]` token. The following function does the trick for us:

In [ ]:
def cls_pooling(model_output):
    return model_output.last_hidden_state[:, 0]

Next, we'll create a helper function that will tokenize a list of documents, place the tensors on the GPU, feed them to the model, and finally apply CLS pooling to the outputs:

In [ ]:
def get_embeddings(text_list):
    encoded_input = tokenizer(text_list, padding=True, truncation=True, return_tensors="pt")
    encoded_input = {k: v.to(device) for k, v in encoded_input.items()}
    model_output = model(**encoded_input)
    return cls_pooling(model_output)

We can test the function works by feeding it the first text entry in our corpus and inspecting the output shape:

In [ ]:
embedding = get_embeddings(comments_dataset["text"][0])
embedding.shape

Great, we've converted the first entry in our corpus into a 768-dimensional vector! We can use `Dataset.map()` to apply our `get_embeddings()` function to each row in our corpus, so let's create a new `embeddings` column as follows:

In [ ]:
embeddings_dataset = comments_dataset.map(
    lambda x: {"embeddings": get_embeddings(x["text"]).detach().cpu().numpy()[0]}
)

Notice that we've converted the embeddings to NumPy arrays — that's because 🤗 Datasets requires this format when we try to index them with FAISS, which we'll do next.

### Using FAISS for efficient similarity search
Now that we have a dataset of embeddings, we need some way to search over them. To do this, we'll use a special data structure in 🤗 Datasets called a *FAISS index*. [FAISS](https://faiss.ai/) (short for Facebook AI Similarity Search) is a library that provides efficient algorithms to quickly search and cluster embedding vectors.

The basic idea behind FAISS is to create a special data structure called an *index* that allows one to find which embeddings are similar to an input embedding. Creating a FAISS index in 🤗 Datasets is simple — we use the `Dataset.add_faiss_index()` function and specify which column of our dataset we'd like to index:

In [ ]:
embeddings_dataset.add_faiss_index(column="embeddings")

We can now perform queries on this index by doing a nearest neighbor lookup with the `Dataset.get_nearest_examples()` function. Let's test this out by first embedding a question as follows:

In [ ]:
question = "How can I load a dataset offline?"
question_embedding = get_embeddings([question]).cpu().detach().numpy()
question_embedding.shape

Just like with the documents, we now have a 768-dimensional vector representing the query, which we can compare against the whole corpus to find the most similar embeddings:

In [ ]:
scores, samples = embeddings_dataset.get_nearest_examples("embeddings", question_embedding, k=5)

The `Dataset.get_nearest_examples()` function returns a tuple of scores that rank the overlap between the query and the document, and a corresponding set of samples (here, the 5 best matches). Let's collect these in a `pandas.DataFrame` so we can easily sort them:

In [ ]:
import pandas as pd
samples_df = pd.DataFrame.from_dict(samples)
samples_df["scores"] = scores
samples_df.sort_values("scores", ascending=False, inplace=True)

Now we can iterate over the first few rows to see how well our query matched the available comments:

In [ ]:
for _, row in samples_df.iterrows():
    print(f"COMMENT: {row.comments}")
    print(f"SCORE: {row.scores}")
    print(f"TITLE: {row.title}")
    print(f"URL: {row.html_url}")
    print("=" * 50)
    print()

Not bad! Our second hit seems to match the query.
> ✏️ Try it out! <font color="darkgreen">Create your own query and see whether you can find an answer in the retrieved documents. You might have to increase the `k` parameter in `Dataset.get_nearest_examples()` to broaden the search.</font>

In [ ]:
# Trying it out
## query and embeddings
query = "How does batch mapping work?" # custom query
query_embedding = get_embeddings([query]).cpu().detach().numpy()
print(query_embedding.shape)
## sample the k nearest instances as well as their score (wrt the query)
scores, samples = embeddings_dataset.get_nearest_examples("embeddings", query_embedding, k=15) # maybe adapt k
## turn samples into a pandas dataframe, add the scores as a column, and sort the rows by their scores
samples_df = pd.DataFrame.from_dict(samples)
samples_df["scores"] = scores
samples_df.sort_values("scores", ascending=False, inplace=True)
## print the results sample by sample
for _, row in samples_df.iterrows():
    print(f"COMMENT: {row.comments}")
    print(f"SCORE: {row.scores}")
    print(f"TITLE: {row.title}")
    print(f"URL: {row.html_url}")
    print("=" * 50)
    print()

## [🤗 Datasets, check!](https://huggingface.co/course/chapter5/7?fw=pt)
Well, that was quite a tour through the 🤗 Datasets library — congratulations on making it this far! With the knowledge that you've gained from this chapter, you should be able to:
- Load datasets from anywhere, be it the Hugging Face Hub, your laptop, or a remote server at your company.
- Wrangle your data using a mix of the `Dataset.map()` and `Dataset.filter()` functions.
- Quickly switch between data formats like Pandas and NumPy using `Dataset.set_format()`.
- Create your very own dataset and push it to the Hugging Face Hub.
- Embed your documents using a Transformer model and build a semantic search engine using FAISS.

In [Chapter 7](https://huggingface.co/course/chapter7), we'll put all of this to good use as we take a deep dive into the core NLP tasks that Transformer models are great for. Before jumping ahead, though, put your knowledge of 🤗 Datasets to the test with a quick quiz!

## [End-of-chapter quiz](https://huggingface.co/course/chapter5/8?fw=pt)
This chapter covered a lot of ground! Don't worry if you didn't grasp all the details; the next chapters will help you understand how things work under the hood.

Before moving on, though, let's test what you learned in this chapter.

**1. The `load_dataset()` function in 🤗 Datasets allows you to load a dataset from which of the following locations?**<br>
⚫️ Locally, e.g. on your laptop
> **Correct!** Correct! You can pass the paths of local files to the `data_files` argument of `load_dataset()` to load local datasets.

⚫️ The Hugging Face Hub
> **Correct!** Correct! You can load datasets on the Hub by providing the dataset ID, e.g. `load_dataset('emotion')`.

⚫️ A remote server
> **Correct!** Correct! You can pass URLs to the `data_files` argument of `load_dataset()` to load remote files.

**2. Suppose you load one of the GLUE tasks as follows:**
```python
from datasets import load_dataset
dataset = load_dataset("glue", "mrpc", split="train")
```
Which of the following commands will produce a random sample of 50 elements from dataset?<br>
⚪️ `dataset.sample(50)`<br>
⚫️ `dataset.shuffle().select(range(50))`
> **Correct!** Correct! As you saw in this chapter, you first shuffle the dataset and then select the samples from it.

⚪️ `dataset.select(range(50)).shuffle()`

**3. Suppose you have a dataset about household pets called `pets_dataset`, which has a `name` column that denotes the name of each pet. Which of the following approaches would allow you to filter the dataset for all pets whose names start with the letter "L"?**<br>
⚫️ `pets_dataset.filter(lambda x : x['name'].startswith('L'))`
> **Correct!** Correct! Using a Python lambda function for these quick filters is a great idea. Can you think of another solution?

⚪️ `pets_dataset.filter(lambda x['name'].startswith('L'))`<br>
⚫️ Create a function like `def filter_names(x): return x['name'].startswith('L')` and run `pets_dataset.filter(filter_names)`.
> **Correct!** Correct! Just like with `Dataset.map()`, you can pass explicit functions to `Dataset.filter()`. This is useful when you have some complex logic that isn't suitable for a short lambda function. Which of the other solutions would work?

**4. What is memory mapping?**<br>
⚪️ A mapping between CPU and GPU RAM<br>
⚫️ A mapping between RAM and filesystem storage
> **Correct!** Correct! 🤗 Datasets treats each dataset as a memory-mapped file. This allows the library to access and operate on elements of the dataset without needing to fully load it into memory.

⚪️ A mapping between two files in the 🤗 Datasets cache

**5. Which of the following are the main benefits of memory mapping?**<br>
⚫️ Accessing memory-mapped files is faster than reading from or writing to disk.
> **Correct!** Correct! This allows 🤗 Datasets to be blazing fast. That's not the only benefit, though.

⚫️ Applications can access segments of data in an extremely large file without having to read the whole file into RAM first.
> **Correct!** Correct! This allows 🤗 Datasets to load multi-gigabyte datasets on your laptop without blowing up your CPU. What other advantage does memory mapping offer?

⚪️ It consumes less energy, so your battery lasts longer.

**6. Why does the following code fail?**
```python
from datasets import load_dataset
dataset = load_dataset("allocine", streaming=True, split="train")
dataset[0]
```
<br>
⚪️ It tries to stream a dataset that's too large to fit in RAM.<br>
⚫️ It tries to access an `IterableDataset`.
> **Correct!** Correct! An `IterableDataset` is a generator, not a container, so you should access its elements using `next(iter(dataset))`.

⚪️ The `allocine` dataset doesn't have a `train` split.

**7. Which of the following are the main benefits of creating a dataset card?**<br>
⚫️ It provides information about the intended use and supported tasks of the dataset so others in the community can make an informed decision about using it.
> **Correct!** Undocumented datasets may be used to train models that may not reflect the intentions of the dataset creators, or may produce models whose legal status is murky if they're trained on data that violates privacy or licensing restrictions. This isn't the only benefit, though!

⚫️ It helps draw attention to the biases that are present in a corpus.
> **Correct!** Correct! Almost all datasets have some form of bias, which can produce negative consequences downstream. Being aware of them helps model builders understand how to address the inherent biases. What else do dataset cards help with?

⚫️ It improves the chances that others in the community will use my dataset.
> **Correct!** Correct! A well-written dataset card will tend to lead to higher usage of your precious dataset. What other benefits does it offer?

**8. What is semantic search?**<br>
⚪️ A way to search for exact matches between the words in a query and the documents in a corpus<br>
⚫️ A way to search for matching documents by understanding the contextual meaning of a query
> **Correct!** Correct! Semantic search uses embedding vectors to represent queries and documents, and uses a similarity metric to measure the amount of overlap between them. How else might you describe it?

⚫️ A way to improve search accuracy<br>
> **Correct!** Correct! Semantic search engines can capture the intent of a query much better than keyword matching and typically retrieve documents with higher precision. But this isn't the only right answer - what else does semantic search provide?

**9. For asymmetric semantic search, you usually have:**<br>
⚫️ A short query and a longer paragraph that answers the query
> **Correct!** Correct!

⚪️ Queries and paragraphs that are of about the same length<br>
⚪️ A long query and a shorter paragraph that answers the query


**10. Can I use 🤗 Datasets to load data for use in other domains, like speech processing?**<br>
⚪️ No<br>
⚫️ Yes
> **Correct!** Correct! Check out the exciting developments with speech and vision in the 🤗 Transformers library to see how 🤗 Datasets is used in these domains.